### ISSUE TITLE
[ota-requestor-app] Use AnnounceOTAProvider as trigger to begin OTA

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#10040]
#### Problem
Currently, `ota-provider-app` begins the OTA process immediately upon startup. This is only feasible right now because `ota-requestor-app` is not commissioned, and instead "steals" credentials from `chip-tool` persisted data.

To mirror a more likely production scenario, `ota-requestor-app` should wait to be commissioned. For testing purposes, we will still want to be able to control when `ota-requestor-app` begins the OTA process. For starters, we can use the ~~`DefaultOTAProvider` attribute write~~ `AnnounceOTAProvider` command as the trigger to begin. This also provides a method for giving `ota-requestor-app` the location of the OTA Provider to connect to.

 #### Proposed Solution
* add OTA Requestor cluster to `ota-requestor-app` and ~~include `DefaultOTAProvider` attribute~~ support `AnnounceOTAProvider` command
* ~~listen for`DefaultOTAProvider` attribute writes,~~ hook up application handler for `AnnounceOTAProvider` which triggers a connection to OTA Provider and `QueryImage` command send

**Comment by tcarmelveilleux** [comment]
This is problematic since DefaultOTAProvider could be written before CommissioningComplete command has executed and it's possible it's not yet guaranteed/feasible for the Node to go check for OTA at that time. This methodology would not scale to real products.

Perhaps the AnnounceOtaProvider command could be used instead.

**Comment by holbrookt** [comment]
Thanks @tcarmelveilleux, I had thought that the attribute write always took place after commissioning. Agree that AnnounceOTAProvider would be a better trigger. I'll edit this Issue to reflect that

**Comment by carol-apple** [comment]
Closing as this issue is fixed by https://github.com/project-chip/connectedhomeip/pull/11010
