### ISSUE TITLE
Refactor the ESP32 example application

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#1006]
#### Problem
The ESP32 example application should be using FreeRTOS tasks(like the EFR32, nRF5 examples) instead of a while loop with a sleep. Because of this it currently needs to poll the buttons to use them. 

 #### Proposed Solution
Switch to the AppTask model the other examples use and update the buttons to be interrupt based, if possible.

**Comment by woody-apple** [comment]
SW BRB: Is this still needed? @sagar-apple

**Comment by sagar-apple** [comment]
This is a "nice to have" as the current example isn't really pretty and may not be the best example application of a CHIP accessory on an ESP32. Specifically when it comes to power consumption and such.

**Comment by bitkis** [comment]
@sagar-apple please confirm this issue is still relevant? if so, I'll start working on it

**Comment by sagar-apple** [comment]
Yes the esp32 app is still not using freeRTOS tasks. This would be a nice to have.

**Comment by dhrishi** [comment]
@woody-apple I will take a look
