### ISSUE TITLE
Basic information and Bridge device Basic information cluster attributes names to be updated. 

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#10098]
Per ballot spec, rename the 'UserLable' attribute with 'NodeLabel' in both Basic information and Bridge device Basic information cluster. 
Spec ref
![Screen Shot 2021-09-29 at 10 55 52 PM](https://user-images.githubusercontent.com/68604034/135396021-83a43aa6-93c8-423d-a70a-e333b242cf95.png)

Also need to add support for UniqueID attribute. Current XML file do not have it. Spec ref

![Screen Shot 2021-09-29 at 11 01 50 PM](https://user-images.githubusercontent.com/68604034/135396112-8123df83-5893-4427-95d1-8a6ac68bec1d.png)

**Comment by lzgrablic02** [comment]
This is no longer outstanding
