### ISSUE TITLE
ThreadNetworkDiagnostics - ResetCounts

### ISSUE THREAD

**Issue by doublemis1** [project-chip/connectedhomeip#10109]
#### Problem
the ResetCounts (ThreadNetworkDiagnostics) command should only reset the OverrunCount.
Matter Specification: 11.13.6.1. ResetCounts

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsThread.adoc#16-commands

This means that the current implementation resets too many counters.
It seems that it's intentional behavior, not just the issue just in the command section in the spec, for example, each attribute has a clear description when it has to be reset.

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsThread.adoc#rxerrinvalidscraddrcount-attribute

**Comment by jmartinez-silabs** [comment]
@doublemis1 Went over the spec again and available apis in Thread. You are right that base on the spec only Overrun count should be resetted by the command and that too many counters are being resetted. 

Over when you mention `each attribute has a clear description when it has to be reset.`, that is right but Overrun attributes mentioon the same as the others 

`The OverrunCount attribute SHALL be reset to 0 upon a reboot of the Node`
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsThread.adoc#overruncount-attribute

Also, Currently there isn't a mechanism to track Overrun counts.  What is your view on how to do so? 

Multiple errors are tracked in the MacCounters but nothing that matches Overrun description
