### ISSUE TITLE
CI does not track Docker image versions 

### ISSUE THREAD

**Issue by rwalker-apple** [project-chip/connectedhomeip#1013]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/1005#issuecomment-639082569
circleCI scripts require manual updates when Docker image versions are advanced

 #### Proposed Solution
 enhance `make` in .circleci to populate version from current tree

**Comment by andy31415** [comment]
We moved to github actions, however maybe we have similar issues there due to versions.

@rwalker-apple should we update the problem description for github or should we close this?

**Comment by rwalker-apple** [comment]
is obsolete
