### ISSUE TITLE
[im]  kCsTag_CommandList should be 2

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#10170]
#### Problem
`kCsTag_CommandList = 0`, but the 10.6.9 of the specification has:

| InvokeRequests |   | Context Tag | 2 | Array of CommandDataIB |

 #### Proposed Solution
Update the `InvokeRequests` path tag in either the SDK or spec so the two match.

**Comment by bzbarsky-apple** [comment]
Fixed in #11169
