### ISSUE TITLE
Random Passcode exceeds the range 

### ISSUE THREAD

**Issue by doublemis1** [project-chip/connectedhomeip#10189]
#### Problem
During the opening commissioning window ECM, the chip device controller assigns Random Passcode which exceeds the Passcode range (e.g 109172366).

5.1.1.6. Passcode
A Passcode SHALL be included as a 27-bit unsigned integer, which serves as proof of possession
during commissioning. The 27-bit unsigned integer encodes an 8-digit decimal numeric value, and
therefore shall be restricted to the values 0x0000001 to 0x5F5E0FE (00000001 to 99999998 in decimal),
excluding the invalid Passcode values.

**Comment by Damian-Nordic** [comment]
Isn't it fixed by https://github.com/project-chip/connectedhomeip/commit/12ce67285e75337d613361620bf4ccadb861167f?
