### ISSUE TITLE
Remove uses of C APIs 'rand' and 'srand'

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#10212]
#### Problem

'rand' relies on a global seed which causes the following issues:

- Interferes with application uses of these APIs (e.g., by re-seeding the generator at init)
- rand() isn't guaranteed thread safe

 #### Proposed Solution

Remove uses of rand(), srand().

**Comment by kghost** [comment]
Already resolved, there is no `rand` usage now.
