### ISSUE TITLE
[DNS-SD] Remove the singleton pattern from ServiceAdvertiser and Resolver

### ISSUE THREAD

**Issue by Damian-Nordic** [project-chip/connectedhomeip#10225]
#### Problem
Although `Resolver` and `ServiceAdvertiser` are pure virtual interfaces, they still use the singleton pattern, so it's impossible to inject an arbitrary implementation at runtime.

 #### Proposed Solution
As a minimal solution, let applications construct `Resolver` and `ServiceAdvertiser` objects and set them with some `Resolver::SetInstance` and `ServiceAdvertiser::SetInstance` methods.

**Comment by tcarmelveilleux** [comment]
Seems like it was done by #10181. @Damian-Nordic to confirm and close

**Comment by woody-apple** [comment]
Thanks @tcarmelveilleux , @Damian-Nordic please re-open if this is an issue.
