### ISSUE TITLE
Add CAT support to SubjectDescriptor

### ISSUE THREAD

**Issue by mlepage-google** [project-chip/connectedhomeip#10243]
- SubjectDescriptor basic implementation was added in initial prototype (#10236)
- this task is to add CAT support
- CAT1/CAT2 need to be set

**Comment by mlepage-google** [comment]
Current approach will be to store CAT tags in type NodeId in the subject descriptor, since the upper bits have discriminating ranges we can use to tell what "type" of NodeId it is.

**Comment by emargolis** [comment]
Addressed by #12027 and #12689

**Comment by mlepage-google** [comment]
Still need to hook up the CATs from the session into the SubjectDescriptor.

PR #13003 provides a place to do this, but doesn't actually do this.

**Comment by mlepage-google** [comment]
This is done now.
