### ISSUE TITLE
Implement simple access control cluster persistence/storage

### ISSUE THREAD

**Issue by mlepage-google** [project-chip/connectedhomeip#10251]
- design storage format
- implement load/save functionality
- ensure system is robust (data integrity etc.)
- lean and fast also important (in that order)
- defer extensions for now, but keep them in mind (#10252)

**Comment by mlepage-google** [comment]
PR #11550 adds an in-memory implementation that uses a single array of POD "storage" structs for the entry data. That format is already quite terse.

Therefore, what mainly needs to happen here:
- in AccessControl::Init, check for any stored ACL data, and if it exists, load it into the ACL storage area in-memory
- otherwise don't, and let the in-memory storage be the starting data
- in AccessControl::CreateEntry, write the new entry (the last one in the in-memory ACL storage) to flash storage
- in AccessControl::UpdateEntry, write the updated entry (just that one, could be anywhere in ACL) to flash storage
- in AccessControl::DeleteEntry, write the entries from the deleted index to the end of the used indexes, to flash storage (since they moved to fill the hole)

Probably wise to consider some kind of mini header for the flash storage, containing a version etc.

**Comment by mlepage-google** [comment]
@harimau-qirex is putting the simple approach (down in access control module) in PR #14253 so we can have some persistence in the interim, then will refactor it out into the cluster with improved storage format and more use of generated code.

**Comment by harimau-qirex** [comment]
The remaining work is for each platform to call chip::Access::Examples::SetAccessControlDelegateStorage (defined in src/access/examples/ExampleAccessControlDelegate.h) with a PersistentStorageDelegate implementation. Linux and MacOS call this in examples/platform/linux/AppMain.cpp with an implementation of PersistentStorageDelegate backed by the KVS manager.

The keys passed into the PersistentStorageDelegate are defined in src/lib/support/DefaultStorageKeyAllocator.h as AccessControlList and AccessControlEntry. By default there are 48 entries (numbered 0-47), but that is configurable by setting CHIP_CONFIG_MAX_DEVICE_ADMINS and CHIP_CONFIG_EXAMPLE_ACCESS_CONTROL_MAX_ENTRIES_PER_FABRIC.
