### ISSUE TITLE
Calls to SetStart(), SetDataLength() on LwIP's pbuf based PacketBuffer fail

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#1026]
#### Problem
For `LwIP` targets, if `PacketBuffer` is allocated by `LwIP` stack (e.g. on data ingress), it's allocated as `pbuf` structure. The `PacketBuffer` class wraps this structure. Some of the `PacketBuffer` functions (e.g. `SetDataLength()`, `SetStart()` etc) assume that `PacketBuffer` has an inline buffer for the `payload`. That is incorrect for `pbuf` based `PacketBuffers`. So these functions fail to move the data pointers, and update the size of packet buffer correctly.

This seems to be the case only when `pbuf` is allocated as `PBUF_REF` or `PBUF_ROM` type.

 #### Proposed Solution
Need special handling of `pbuf` based `PacketBuffer` structure. Or, design needs to be updated.

**Comment by woody-apple** [comment]
SW BRB: @pan-apple what are next steps here?
