### ISSUE TITLE
SendMsg() for target using sockets does not work for chain of PacketBuffers

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#1027]
#### Problem
`SendMsg()` for `CHIP_SYSTEM_CONFIG_USE_LWIP` configuration expects that linked list of `PacketBuffers` has only one entry. Otherwise it returns error.

https://github.com/project-chip/connectedhomeip/blob/8b7a20b2a64ce1736ed368dca5f7d0a86237e7a3/src/inet/IPEndPointBasis.cpp#L776

 #### Proposed Solution
This can be handled by using `sendmsg()` API (https://www.man7.org/linux/man-pages/man3/sendmsg.3p.html). This API takes a list of disjoint `iovecs`. Each `PacketBuffer` can be used as individual `iovec`. It'll allow to send multiple `PacketBuffers` as one UDP packet.

**Comment by andy31415** [comment]
Do we require this functionality currently?

Trying to figure out if this is something we need to implement or just ignore because it is not needed. Currently it is flagged as P1 work.

**Comment by woody-apple** [comment]
SW BRB: Agree, doesn't seem required at this point. Closing for now until this is required.
