### ISSUE TITLE
Defaults for cluster objects

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#10271]
So comparing this to our existing decoding code I see the following differences:

1. Our existing code ensures that all mandatory command arguments are present, or at least tries to.  I think it might be assuming all arguments are mandatory.  This is important, because our members don't have any initializers, generally, so if there are missing fields we will have un-initialized data in the struct.  Or we need to add initialization to some sort of (XML-defined?) default values....  Or something.
2. Our existing code errors out if the same field id is present twice.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/10171#r722866456_

**Comment by mrjerryjohns** [comment]
Seems like @bzbarsky-apple took an initial crack at this, so assigning this his way.
