### ISSUE TITLE
Flow Measurement Cluster - Optional attribute Tolerance is not implemented in SDK

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#10323]
Spec Snippet : 
<img width="1500" alt="Screen Shot 2021-10-07 at 11 08 34 AM" src="https://user-images.githubusercontent.com/84206864/136439832-017c431f-5ec4-4546-9150-876535ef9182.png">

Only the mandatory attributes seem to be implemented

**Comment by mrjerryjohns** [comment]
Marking optional attributes as post 1.0.
