### ISSUE TITLE
IM status codes are whittled down to an 8-bit Ember code before dispatch to client logic

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#10331]
#### Problem

Status codes from IM commands can contain a 16-bit IM status code as well as a 16-bit cluster-specific status code.

However, the API up to the client whittles all that down to an 8-bit Ember status code (see `IMDefaultResponseCallback`).

This should be fixed.

**Comment by turon** [comment]
IM status codes must match spec for v1.
Removing tag `v1_triage_split_4`
