### ISSUE TITLE
Fix our representation of scene attribute sets

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#10334]
#### Problem
Right now we just try to decode that list as a single uint8_t.  

 #### Proposed Solution
Need to fix the XML, figure out how to represent the "variable" type (e.g. TLVReader?), etc.

**Comment by woody-apple** [comment]
SDK Spec Review: Moving out of 1.X, given we do not have an implementation plan for scenes in 1.0
