### ISSUE TITLE
[IM] WriteClient Lifecycle Management

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#10366]
#### Problem
Like the work being done for CommandSender, need to update the lifecycle management of WriteClient to not be allocated by the stack, but rather, allocated and managed by the application.

**Comment by mrjerryjohns** [comment]
Since we already have a `WriteClientHandle`, I'm inclined to say that for v1, that suffices. Going to close this issue for now.

**Comment by mrjerryjohns** [comment]
Sorry - I meant that it will be punted out of TE7.5

**Comment by yufengwangca** [comment]
@erjiaqing I think this task has already been completed, no?

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/13248
