### ISSUE TITLE
Broken API for Diagnostics cluster.

### ISSUE THREAD

**Issue by sweetymhaiske** [project-chip/connectedhomeip#10379]
#### Problem
* Currently, Getter methods for some WiFi Diagnostic clusters attributes return 0 on failure. However, specs demand NULL value.
Spec -
`A value of NULL SHALL indicates that the interface is not currently configured or operational.`

**Comment by bzbarsky-apple** [comment]
@yufengwangca Do you have time to look at this?

@mrjerryjohns To implement this we need to decide how nullables will be represented for purposes of DataModel::Encode.  I still think we should treat them the way we treated List compared to Span and have a Nullable that derives from Optional....

**Comment by mrjerryjohns** [comment]
@yufengwangca is this done?

**Comment by bzbarsky-apple** [comment]
This is not done.  These attributes all need to get marked nullable in the XML and the spec-expected behavior around when null is returned needs to be implemented.

**Comment by holbrookt** [comment]
This seems important but hasn't seen any activity since November. Does this need to be in for 1.0?

**Comment by bzbarsky-apple** [comment]
Yes, unless the spec changes.  Right now we are not following the spec for this cluster on the server, and our clients can't parse spec-compliant server responses.
