### ISSUE TITLE
Calling "matter config" shell command doesn't return all expected parameters values

### ISSUE THREAD

**Issue by kkasperczyk-no** [project-chip/connectedhomeip#10384]
#### Problem
Calling "matter config" shell command should result in returning following output:

```
VendorId:        9050 (0x235A)
ProductId:       20043 (0x4E4B)
ProductRevision: 1 (0x1)
FabricId:
PinCode:         020202021
Discriminator:   f00
DeviceId:
```

however only first three parameters are printed, despite the fact that device was commissioned, so FabricId value should be set.

 #### Proposed Solution
Two possible cases to investigate:
- What happens if parameter to get is not set? Will it be printed as empty or method will break at this point and not continue to the following parameters?
- Is ConfigurationMgr() able to get up to date values of all parameters even though some of them is set outside of it during commissioning and setting operational credentials?

**Comment by bzbarsky-apple** [comment]
@kkasperczyk-no Is this still an issue? What are the actual steps to reproduce this?
