### ISSUE TITLE
iOS CHIP framework integration question

### ISSUE THREAD

**Issue by amaolll123** [project-chip/connectedhomeip#10405]
Hi @bzbarsky-apple , @jmartinez-silabs , @pan-apple , @vivien-apple , @eve-cxrp , @sagar-apple , 

We have a project under construction at the same layer as [CHIPTool](https://github.com/project-chip/connectedhomeip/tree/master/src/darwin/CHIPTool), so that we are planning to integrate CHIP frame work into our project.

What we are doing now is:
-> Build CHIP project in `connectedhomeip` repo
-> Find built artifact (`CHIP.framework` file)
-> Embed `CHIP.framework` into our project
Which is working but I guess it's way too hacky.

Question: 
Is there a better/recommended way to do this integration?
I've tried pull [CHIP xcodeproject](https://github.com/project-chip/connectedhomeip/tree/master/src/darwin/Framework) out, but building would fail as submodule info is not come along from .git.

One follow-up:
By editing scheme of `CHIP`, I found frameworks' size show as following:
```
Debug Arm64 - 8.2 MB
Release Arm64 - 6.8 MB
```
Is 6.8 MB the optimal framework size at the moment? 
Any other setting I can do to downsize the framework?

Thanks!

**Comment by bzbarsky-apple** [comment]
@amaolll123 Note that CHIP.framework is generally available on iOS.  See https://developer.apple.com/videos/play/wwdc2021/10298/
