### ISSUE TITLE
VerifyOrDie(!IsAckPending()) crash after calling EnableNetwork for IP commissioning

### ISSUE THREAD

**Issue by randyrossi** [project-chip/connectedhomeip#10416]
https://github.com/project-chip/connectedhomeip/blob/86894434d7d7269e40701e7dca4851aef4b9d875/src/messaging/ExchangeContext.cpp#L268

Should the destructr trigger a crash if an ACK is not processed before the exchange context is destroyed?  

This assert was causing my client to crash after calling EnableNetwork() from a OnPairingComplete callback.  I think the call to EnableNetwork() was not necessary and the path to getting this triggered was unclear.  Although I suppose it was because the somehow context was being destroyed before an expected ack was processed.  However, I don't think the code should crash.

**Comment by woody-apple** [comment]
Sounds like we should document this behavior for V1.0, but developers can work around it for now?
