### ISSUE TITLE
EFR32 Unit Test crashes

### ISSUE THREAD

**Issue by rgoliver** [project-chip/connectedhomeip#10447]
#### Problem
EFR32 Unit tests crashes while running:
`python -m nl_test_runner.nl_test_runner -d /dev/ttyACM0 -f out/debug/chip-efr32-device_tests.s37 -o out.log`

```
...
<detail> [IN] New secure session created for device 0x0000000006A11E3D, key 2!!
<detail> [IN] New secure session created for device 0x000000000001E306, key 1!!
<info  > [IN] Prepared encrypted message 0x20020518 to 0x0000000006A11E3D of type 0xhx and protocolId (1, 0) on exchange 4� with
 MessageCounter:105.
<info  > [IN] Sending encrypted msg 0x20020518 with MessageCounter:1 to 0x0000000006A11E3D at monotonic time: ld msec
<info  > [-] 
FREERTOS ASSERT ( (pxLink->xBlockSize & xBlockAllocatedBit) != 0 )

<info  > [-] 
FREERTOS ASSERT ( ( portNVIC_INT_CTRL_REG & portVECTACTIVE_MASK ) == 0 )
```

**Comment by rgoliver** [comment]
App tests have a harfault during the TestReadInteraction:
<error > HardFault:

SCB->CFSR   0x00000400
SCB->HFSR   0x40000000
SCB->MMFAR  0xe000ed34
SCB->BFAR   0xe000ed38
SP          0x20029190
R0          0x00000f29

R1          0x30bd08fc

R2          0x01200000

R3          0x4fb50847

R12         0xa5a5a5a5

LR          0x000105ad

PC          0x0000f88e

PSR         0x01000000

**Comment by rgoliver** [comment]
src/controller/tests/TestDevice.cpp test has hardfault:
<error > HardFault:

SCB->CFSR   0x00000400
SCB->HFSR   0x40000000
SCB->MMFAR  0xe000ed34
SCB->BFAR   0xe000ed38
SP          0x20028c28
R0          0x00001fe5

R1          0x002b1080

R2          0x1180b0f0

R3          0x002b1280

R12         0xa5a5a5a5

LR          0x000126b1

PC          0x00011994

PSR         0x01000000

**Comment by andy31415** [comment]
Still happening, @rgoliver  asked to reopen

**Comment by rgoliver** [comment]
#14238 disables TestExchangeMgr which hands on EFR32.

**Comment by bzbarsky-apple** [comment]
@rgoliver Is this still an issue?

**Comment by rgoliver** [comment]
@jmartinez-silabs  I know you were looking at fixing the EFR unit tests, can this be closed?

**Comment by jmartinez-silabs** [comment]
I just tested the tests. They all link but there is an issue with the event loop. The queue gets full and it causes other issues in the exchanges manager from what I can see. I also opened #33372

I should have a few cycles to investigate further.
