### ISSUE TITLE
E (234898) chip[BLE]: HandleChipConnectionReceived failed, err = 417

### ISSUE THREAD

**Issue by WOLEN6914183** [project-chip/connectedhomeip#10472]
(234878) chip[IN]: Clearing BLE pending packets.
I (234888) chip[BLE]: Releasing end point's BLE connection back to application.
E (234898) chip[BLE]: HandleChipConnectionReceived failed, err = 417
E (234898) chip[BLE]: failed handle new chip BLE connection, status = 417
V (234968) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.134
I (235018) chip[DL]: Write request/command received for CHIPoBLE TX CCCD characteristic (con 0 ) indicate = 0 notify = 1
I (235018) chip[DL]: CHIPoBLE subscribe received
E (235018) chip[BLE]: no endpoint for sub recvd
I (235028) app-devicecallbacks: CHIPoBLE connection established
I (235038) app-devicecallbacks: Current free heap: 93100

V (235048) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.134
V (235148) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.134
V (235378) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.134
I (249868) chip[DL]: Write request/command received for CHIPoBLE TX CCCD characteristic (con 0 ) indicate = 0 notify = 0
I (249868) chip[DL]: CHIPoBLE unsubscribe received
E (249868) chip[BLE]: no endpoint for unsub recvd
I (249888) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable, device name MATTER-3840)
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=2 adv_filter_policy=0 adv_itvl_min=40 adv_itvl_max=40
I (249918) chip[DL]: CHIPoBLE advertising started
I (249918) app-devicecallbacks: Current free heap: 93656

I (250948) chip[DL]: BLE GAP connection terminated (con 0 reason 0x13)
I (250948) app-devicecallbacks: CHIPoBLE disconnected
I (250948) app-devicecallbacks: Current free heap: 93656

I (250958) chip[DL]: Configuring CHIPoBLE advertising (interval 25 ms, connectable, device name MATTER-3840)
I (250978) chip[DL]: Device already advertising, stop active advertisement and restart
GAP procedure initiated: stop advertising.
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=2 adv_filter_policy=0 adv_itvl_min=40 adv_itvl_max=40
V (255108) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (256138) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (258188) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (260438) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.174
V (260448) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.174
V (260568) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (260778) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (261348) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (261358) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (262068) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (262068) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (262218) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (262278) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (262498) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (262528) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (264338) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (264358) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234
V (264558) chip[DIS]: Broadcasting mDns reply for query from 10.10.10.234

**Comment by woody-apple** [comment]
Given this is an older issue, is this complete at this point? If not, please re-open.
