### ISSUE TITLE
Reenable TIME_SERVICE_TIME_SYNC

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#105]
#### Problem
#104 disabled TIME_SERVICE_TIME_SYNC at https://github.com/project-chip/connectedhomeip/blob/ca9dfc24d1aa0845f7e98eb87ab9d43068c44734/src/include/platform/CHIPDeviceConfig.h#L407

and https://github.com/project-chip/connectedhomeip/blob/ca9dfc24d1aa0845f7e98eb87ab9d43068c44734/src/include/platform/nRF5/CHIPDevicePlatformConfig.h#L43

#125 removed the TimeSync Service configuration from the EFR32 Platform Config.
Reference: https://github.com/project-chip/connectedhomeip/blob/ca9dfc24d1aa0845f7e98eb87ab9d43068c44734/src/include/platform/EFR32/CHIPDevicePlatformConfig.h#L38

 #### Proposed Solution
Check if these need to be enabled. If required, enable and fix the associated issues.

**Comment by woody-apple** [comment]
Closing this, as it''s covered here:
https://github.com/project-chip/connectedhomeip/issues/2871
https://github.com/project-chip/connectedhomeip/issues/2872
