### ISSUE TITLE
Subscription LivenessCheckTime timeout does not appear to be set for a new subscription

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#10510]
#### Problem
When a new subscription is created on a DUT, the LivenessCheckTimeout is not set up immediately. Instead, the timeout appears to be set up for the first time after the next subsequent report is received from the DUT.

 #### Steps to Reproduce
1. zclconfigure OnOff OnOff <nodeid> <endpointid> 10 20 0
2. Sever communications immediately after SubscribeResponse is received

**Comment by mrjerryjohns** [comment]
Stale, should not be a problem anymore on master.
