### ISSUE TITLE
Followup:Also, the fact that the status ib builder hangs off the GetCommandDataElementBuilder is pretty weird. If we have command data we don't have a status. Again, followup to make this match spec better.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#10511]
Followup: That "EndOfStatusIB()" bit is just noise that we should not have....

Also, the fact that the status ib builder hangs off the GetCommandDataElementBuilder is pretty weird.  If we have command data we don't have a status.  Again, followup to make this match spec better.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/10460#discussion_r729045891_

**Comment by turon** [comment]
Per follow-up comment, `EndOfStatusIB` was removed in #10511, and no longer exists in the codebase.
