### ISSUE TITLE
Omit encoding NodeId over the wire if it matches the target's NodeId

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#10596]
#### Problem

In the current encoding implementation in the IM, we send NodeId fairly liberally across the wire. Not only does this need to get cleaned up to match spec, but it needs to be omitted in scenarios where it matches the target's NodeId.

**Comment by yunhanw-google** [comment]
From boris, "I don't think we send node ids on the wire in the IM anymore... it's still there in the IBs, but we never try to read it outside tests and never try to write it outside tests."  Agree with boris, I think it is file to close 10596, and just left it in IB definition
