### ISSUE TITLE
Add BleManager for Darwin

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#1063]
#### Problem
Add BleManager for Darwin

**Comment by vivien-apple** [comment]
@woody-apple  Was it basically https://github.com/project-chip/connectedhomeip/issues/1660 ?
If not, can you add a bit more description on the issue ?

**Comment by woody-apple** [comment]
Duplicate of:
https://github.com/project-chip/connectedhomeip/pull/1660
