### ISSUE TITLE
Message counter sync is now broken

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#10643]
#### Problem
After https://github.com/project-chip/connectedhomeip/pull/10095 the sequence of events for a group message needing counter sync is as follows:

1. Receive the message.
2. Decrypt it.
3. Start message counter sync, queue up decrypted data.
4. When sync completes, call `SessionManager::OnMessageReceived` with that data.
5. Land in `SessionManager::SecureMessageDispatch`.
6. Try to decrypt the data _again_ and I woul hope fail.

 #### Proposed Solution
We need to either keep the dispatch path as it is now and queue up the encrypted data, or queue up unencrypted data but then the dispatch after sync completes needs to be different.

**Comment by bzbarsky-apple** [comment]
Also, the payload header gets lost now: it gets parsed out and consumed in `Decrypt`, then we store only the actual payload, sans header, and on re-dispatch it's not there.  So if we change the dispatch we need to make sure to keep track of the payload header too.

**Comment by holbrookt** [comment]
@bzbarsky-apple is this still broken? Is this an issue for 1.0?

**Comment by bzbarsky-apple** [comment]
> @bzbarsky-apple is this still broken?

Right now it's even more broken, in that we never call into counter sync, and in fact never check message counters for group messages at all.

> Is this an issue for 1.0?

That depends on whether we are trying to ship the cache-and-sync counter sync method in 1.0.

**Comment by jepenven-silabs** [comment]
Closing it since duplicated by #11689
