### ISSUE TITLE
How to reconnect device with app

### ISSUE THREAD

**Issue by JourneyYoung** [project-chip/connectedhomeip#10653]
#### Problem
I can control the device after pairing successfully in my App, but when I kill the App and restart it, I'll lose the connection between my Matter device with the App. To keep the device  connectied all the time in the App,  could you tell me the reconnection mechanism how to recennect the Matter device with my App?

 #### Proposed Solution
I guess before sending commands to the App, we should try to reconnect the matter device, is it correct?

**Comment by bzbarsky-apple** [comment]
See https://github.com/project-chip/connectedhomeip/issues/17298 which once resolved will fix this.

**Comment by woody-apple** [comment]
Issue Review: We believe this is complete in the current SDK, can you please verify, and re-open if this is still an issue?
