### ISSUE TITLE
[TC-OO-2.3] OnOffCluster: OnWithTimedOff, Steps 9a, 9b etc.

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [project-chip/connectedhomeip#10668]
#### Problem

When executing [TC-OO-2.3]  steps 9a, 9b and following in testevent 6, TH sends OnWithTimedOff command to DUT and immediately TH reads OnOff attribute, OnTime attribute and OffWaitTime attribute from DUT. Values in the attribute values remain 0.

#### Proposed Solution

Implement missing functionality?

**Comment by naveenkommareddi** [comment]
This is a stale issue that's not seen anymore. We should close this

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
