### ISSUE TITLE
Need to define a Binding or PeerAddress or equivalent structure

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1069]
#### Problem
We need to be able to encode how a peer should be connected to. Currently we assume UDP however as we add more transports, we need more info. Specifically:
   - when a connection is received, need to figure out what path it came through, so we reply over the same path (UDP, keep a TCP socket or BLE)
  - when we need to contact a peer, we need to be able to say how to contact that peer
  - Need to keep track of UDP ports, so that a peer listening on a different port can still communicate with a peer on a standard port.

 #### Proposed Solution
Define a Binding/PeerInfo class that can be constructed and used to both store peer information and send packets to that peer.

**Comment by vivien-apple** [comment]
@andy31415 Is `src/transport/raw/PeerAddress.h` the thing you opened this issue for ?

**Comment by woody-apple** [comment]
SW BRB: ping @vivien-apple @andy31415

**Comment by andy31415** [comment]
Peer address seems to be the current construct. Closing the super old bug.
