### ISSUE TITLE
Messages should have persistent counters 

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1071]
#### Problem
Message IDs are sequential and ids are used for request ack. If 1 is always a starting value, we have a high chance of collision during unexpected resets.

 #### Proposed Solution
Use a PersistentCounter implementation for message id tracking, so that message numbers are not reused except after very long times.

**Comment by bzbarsky-apple** [comment]
@andy31415 Is this talking about PASE/CASE counters (which restart at 1 for each new key and are not persistent, per spec) or something else?
