### ISSUE TITLE
HashLengthAndBase64Value() needs to be reimplemented

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#108]
#### Problem
#104 deleted implementation of `HashLengthAndBase64Value()` and corresponding calls to it. This was done because `Platform::Security` module is not available.

 #### Proposed Solution
Reimplement the function with available APIs. Add the calls to function from where it was removed.

Deleted code reference: 
https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/internal/GenericConfigurationManagerImpl.ipp#L1053

**Comment by woody-apple** [comment]
ping @pan-apple ?

**Comment by pan-apple** [comment]
We can close this issue, as this code is not relevant for CHIP.
