### ISSUE TITLE
Optional Attributes not implemented in SDK for Binary Input Cluster

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#10806]
Only the mandatory attributes are implemented for this Cluster,

Following optional attributes not yet implemented : 

Description
MaxPresentValue
MinPresentValue
Reliability
Resolution
EngineeringUnits
ApplicationType

**Comment by yufengwangca** [comment]
@raju-apple 
Where is this cluster defined in the spec?

**Comment by bzbarsky-apple** [comment]
This cluster does not seem to be in the Matter App Clusters spec.

**Comment by raju-apple** [comment]
Cluster no longer exists, closing it out
