### ISSUE TITLE
In CC(Color Control Cluster) the ClusterRevision value is incorrect in SDK

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#10807]
According to the latest spec :
<img width="1081" alt="Screen Shot 2021-10-21 at 3 44 48 PM" src="https://user-images.githubusercontent.com/84206864/138367183-a5ae53d2-2809-4a71-943a-45db76444f5b.png">

ClusterRevision value needs to be 5 , but its incorrect in the SDK

**Comment by holbrookt** [comment]
@raju-apple is this still an issue? Please close if not.

**Comment by raju-apple** [comment]
Dupe of #9772
