### ISSUE TITLE
FLW ( Flow Measurement Cluster) - ClusterRevision value is incorrect in SDK

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#10812]
According to the latest spec : 
<img width="1062" alt="Screen Shot 2021-10-21 at 4 31 49 PM" src="https://user-images.githubusercontent.com/84206864/138370608-43aed691-1564-4143-aa71-53829695b8bb.png">

The value for ClusterRevision should be 3 , but the SDK is reporting it incorrectly currently

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
