### ISSUE TITLE
Some of the test cases have conditional PICS checks for each of the steps , need YAML support for this

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#10811]
Look at this example in the TC-DM-1.1 test case : 
<img width="793" alt="Screen Shot 2021-10-21 at 4 25 27 PM" src="https://user-images.githubusercontent.com/84206864/138370152-3c65094c-63fd-4356-aa71-ed2d2059a3b5.png">

We need a way to conditionally execute certain steps based on the value , need a way in YAML to implement this as well

**Comment by raju-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/11322

**Comment by raju-apple** [comment]
PR Merged

**Comment by kidip** [comment]
Initial PR is most likely not sufficient for the Test Harness.  Will work with @vivien-apple to design something that works for both CI and Test Harness.

**Comment by vivien-apple** [comment]
Should have been fixed by #11729. Feel free to reopen if that still not enough.
