### ISSUE TITLE
Fix the behavior of WriteClient when receiving unexpected messages

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#10813]
This seems like it will behave _very_ oddly if the message that comes back is not a Write Response message (e.g. a status response).

In particular:
1. It will not parse the status response.  This should be a followup.
2. It will not call `OnError` at all on the callback, or anything other than `OnDone`.  This seems very odd to me.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/10488#discussion_r734052010_

**Comment by erjiaqing** [comment]
https://github.com/project-chip/connectedhomeip/blob/97cf4ff6000136a59f0b5515822704f9e974c579/src/app/WriteClient.cpp#L298-L352

I think this issue is fixed when landing status ib.

**Comment by bzbarsky-apple** [comment]
This was fixed in https://github.com/project-chip/connectedhomeip/pull/11667
