### ISSUE TITLE
On/Off Cluster : ClusterRevision value returned by SDK doesn't match the spec

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#10827]
Based on the latest spec : 
<img width="1219" alt="Screen Shot 2021-10-21 at 8 42 35 PM" src="https://user-images.githubusercontent.com/84206864/138390141-ce2373a4-1e9a-4287-8864-b5be4471fa99.png">

The ClusterRevision attribute value needs to be 4 , SDK is returning an incorrect value currently.

**Comment by vivien-apple** [comment]
@raju-apple  The SDK has been updated to return `4`. I suspect that the test plan needs to be updated ?

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
