### ISSUE TITLE
Occupancy Sensing Cluster : ClusterRevision value incorrect

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#10829]
According to the latest spec : the value of ClusterRevision for the Occupancy Sensor is as follows : 

<img width="1511" alt="Screen Shot 2021-10-21 at 9 25 30 PM" src="https://user-images.githubusercontent.com/84206864/138393480-cd6cb065-f2cc-442e-b365-d709caa078ff.png">

Value needs to be 3 but the SDK is incorrectly returning as 2 currently.

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
