### ISSUE TITLE
[linux] dbus sharing design

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#1084]
#### Problem
Extend PlatformMgr to allow service registration to select loop.
Each service creates its own thread to drive DBUS: Thread, BLE, WiFi. 
Need a consistent way to register such services to drive DBUS in a common way.

 #### Proposed Solution

Map out pros and cons of each approach below.  
Down-select solution.  
Implement solution with unit tests.

1) Allow service to register with PlatformMgr main select loop.
delegate struct { .prepareSelect, .update }

2) Or dedicated I/O thread for DBUS

3) Or separate threads, but common way to drive DBUS

**Comment by turon** [comment]
@yufengwangca : proceeding with gio/glib approach.  Proceeding to implementation stage. 2-3 days expected.
@turon: consider having some general APIs for adding services -- both`RegisterSelectService` and `RegisterGioService`
@yunhanw-google : can work with you on BLE integration part
@yufengwangca : WiFi / wpasupplicant part also using gio.
Concerned about potential conflict with ThreadMgr using raw dbus API in parallel.
@bukepo : Doesn't gio use the raw dbus API?  Is WiFi using gio right now?
@kghost : No, gio has their own from scratch impl.  Yes, both WiFi and BLE using gio right now.
@yufengwangca : WiFi using pre-defined gio dbus API from wpasupplicant.
@bukepo : Ok, we could convert ThreadMgr to gio when we have time.
@yufengwangca : Think that will be required to prevent conflicts
@bukepo : Believe gio can handle raw file descriptors
@yufengwangca : Didn't try that, but anticipate there would be subtle problems with that, unless it has its own thread
@turon : Current Thread impl has separate std::thread just for dbus handling 
@gjc13 : Correct
@turon : If it can work, defer gio port of ThreadMgr to optimization.  
@yufengwangca : Believe there will be conflicts.  
@turon : Thought dbus is designed for multiple clients and services on one system
@yufengwangca : Not advised to have multiple dbus clients in one process.  Multiple dbus IDs would confuse the system.  Not designed for that.
@bukepo : Please share material on those limitations

**Comment by yufengwangca** [comment]
https://github.com/project-chip/connectedhomeip/pull/1557

**Comment by yufengwangca** [comment]
This issue can be closed
