### ISSUE TITLE
[ESP32] EnableNetwork returns success before trying to join wifi network

### ISSUE THREAD

**Issue by fengli** [project-chip/connectedhomeip#10865]
#### Problem
EnableNetwork returns success before trying to join wifi network. There seems no way for client to validate whether joining network succeeded, as it'll success even with wrong ssid/password (which was added with addNetwork in a prior step).

By looking into the implementation for ESP32 for WifiProvisioning [here:](https://github.com/project-chip/connectedhomeip/blob/2d490271a63d156cf8d036ef90353cfa6c94d58a/src/platform/ESP32/WiFiProvisioning.cpp#L53), `ConnectivityMgr().SetWiFiStationMode` is called to enable wifi. Which is implemented [here](https://github.com/project-chip/connectedhomeip/blob/2d490271a63d156cf8d036ef90353cfa6c94d58a/src/platform/ESP32/ConnectivityManagerImpl_WiFi.cpp#L69), while implementation of SetWiFiStationMode is asynchronous in [this line](https://github.com/project-chip/connectedhomeip/blob/2d490271a63d156cf8d036ef90353cfa6c94d58a/src/platform/ESP32/ConnectivityManagerImpl_WiFi.cpp#L79).

The SPEC defines the expected behavior as:

> This SHALL enable a network in the Cluster, set its Enabled field to true and attempt to connect to the network. Network is identified by its NetworkID. 

> If connecting to the network is unsuccessful, a respective ErrorCode is sent in the EnableNetworkResponse and the Enabled field is set to false.

 #### Proposed Solution
EnableNetwork should return success only when it joins the network successfully.

**Comment by turon** [comment]
Deterministic means to detect whether EnableNetwork is successful or fails is required for v1 on all platforms.
Removing tag `v1_triage_split_4`

**Comment by woody-apple** [comment]
SDK Spec Review: We believe this is stale and resolved. Closing for now, please re-raise if this is an issue.
