### ISSUE TITLE
[TC-MC-8.1 & 8.2] `CurrentTarget` Attribute not available for `targetnavigator` cluster

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#10880]
#### Test Case ID:
[TC-MC-8.1]  Navigate Target Verification (DUT as Server)
[TC-MC-8.2] Navigate Target Verification (DUT as Client)

#### Describe Issue:
`CurrentTarget` Attribute not found in `chip-tool`, unable to complete Steps `1a`, `2b`, and `3c` for both `TC-MC-8.1`  and `TC-MC-8.2`. This missing attribute makes it so the test case cannot be accurately performed because all other steps rely on knowing the `current target` attribute's value.

#### Issue located in Steps:
 Steps 1a, 2b, and 3c

#### Testing Setup:
DUT (Controller) `chip-tool` on Mac, `test_event_6` branch commit: `82bcd4e36f4856a4216cb76a16116faeec40e223`
TH (Accessory) `chip-tv-app` on RasPi4, `test_event_6` branch commit: `82bcd4e36f4856a4216cb76a16116faeec40e223`

#### Specification References:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#test-procedure-24

#### Logs:
[TC-MC-8-1.txt](https://github.com/project-chip/connectedhomeip/files/7401644/TC-MC-8-1.txt)
[TC-MC-8-2.txt](https://github.com/project-chip/connectedhomeip/files/7401645/TC-MC-8-2.txt)

**Comment by liamgonyea** [comment]
### Update
Issue is still happening on `test_event_7` branch. 

#### Testing Setup:
DUT (Controller) chip-tool on RasPi4, `test_event_7` branch commit: `f51eeb39de1e58c8f55a13cfc59782e8e11c6948`
TH (Accessory) chip-tv-app on RasPi4, `test_event_7` branch commit: `f51eeb39de1e58c8f55a13cfc59782e8e11c6948`

**Comment by lazarkov** [comment]
It's present now

`➜  connectedhomeip git:(feature/enable-struct-atributes-for-chip-tool) ✗ out/debug/standalone/chip-tool targetnavigator read                    
[1644257570311] [13547:652718] CHIP: [TOO] Missing attribute name
Usage:
  out/debug/standalone/chip-tool targetnavigator read attribute-name [param1 param2 ...]

  +-----------------------------------------------------+
  | Attributes:                                                                         |
  +-----------------------------------------------------+
  | * target-navigator-list                                                      |
  | * current-navigator-target                                               |
  | * server-generated-command-list                                  |
  | * client-generated-command-list                                   |
  | * attribute-list                                                                   |
  | * cluster-revision                                                              |
  +-----------------------------------------------------+`
