### ISSUE TITLE
[TC-MC-9.1 & 9.2] Missing `ApplicationVersion` and `AllowedVendorList` Attributes for `applicationbasic` cluster

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#10882]
#### Test Case ID:
[TC-MC-9.1] Application Basic Attribute Verification (DUT as Server)
[TC-MC-9.2] Application Basic Attribute Verification (DUT as Client)

#### Describe Issue:
`ApplicationVersion` and `AllowedVendorList`  Attributes not found in `chip-tool`, unable to complete Steps `7` and `8`,  for both `TC-MC-9.1`  and `TC-MC-9.2`. These missing attributes are needed to complete the whole test case accurately. 

#### Issue located in Steps:
 Steps 7 and 8

#### Testing Setup:
DUT (Controller) `chip-tool` on Mac, `test_event_6` branch commit: `82bcd4e36f4856a4216cb76a16116faeec40e223`
TH (Accessory) `chip-tv-app` on RasPi4, `test_event_6` branch commit: `82bcd4e36f4856a4216cb76a16116faeec40e223`

#### Specification References:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#test-procedure-26
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#test-procedure-27

#### Logs:
![image](https://user-images.githubusercontent.com/80923273/138530866-31b53e97-f11c-4e72-97af-a9b901980831.png)

**Comment by liamgonyea** [comment]
### Update
The same attributes and issue is still happening on `test_event_7` branch. 

#### Testing Setup:
DUT (Controller) chip-tool on RasPi4, `test_event_7` branch commit: `f51eeb39de1e58c8f55a13cfc59782e8e11c6948`
TH (Accessory) chip-tv-app on RasPi4, `test_event_7` branch commit: `f51eeb39de1e58c8f55a13cfc59782e8e11c6948`

**Comment by raju-apple** [comment]
No longer an issue
