### ISSUE TITLE
Multi Admin Chip tool commissioning failing on Master

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#10884]
On the latest master branch commit - b1fcb673a62ccd26aaad1c242d94416a935c316c observing that the multiadmin chip tool commissioning is failing.

Steps followed:
1 -> Connect over IP from python controller (1st commissioner)
2 -> Open ECM commissioning window from 1st commissioner
3 -> Try commissioning with chip tool (2nd commissioner). Observe that this step fails and chip too fails to commission. Tried commissioning chip tool to accessory with onnetwork command and onnetwork-commissioning-mode command as well. Both of them failed to commission.
[pythoncontroller.pdf](https://github.com/project-chip/connectedhomeip/files/7401943/pythoncontroller.pdf)
[Chiptool_commissionablenode.pdf](https://github.com/project-chip/connectedhomeip/files/7401944/Chiptool_commissionablenode.pdf)
[Accessorylog.pdf](https://github.com/project-chip/connectedhomeip/files/7401945/Accessorylog.pdf)

**Comment by woody-apple** [comment]
This appears to be working now?
