### ISSUE TITLE
mismatch Basic Information and Bridged Device Basic Information Clusters in SDK vs spec

### ISSUE THREAD

**Issue by leorozendaal** [project-chip/connectedhomeip#10908]
#### Problem
Comparing the Basic Information Cluster source file ( src\app\zap-templates\zcl\data-model\chip\basic-information-cluster.xml ) with the spec (recirc2, section 11.1) reveals the following differences from spec updates since this xml file was created
* attribute 5 `UserLabel` has been renamed to `NodeLabel`
* attribute 18 has been added `UniqueID`
* event 3 has been added `ReachableChanged`
* Also, the events are listed as commands in the xml-file.

Similarly, for Bridged Device Basic Information ( src\app\zap-templates\zcl\data-model\chip\bridged-device-basic.xml ) vs. spec (recirc2, section 9.13):
* name has been changed to include `Information`
* attribute 5 `UserLabel` has been renamed to `NodeLabel`
* attribute 18 has been added `UniqueID`
* Also, the events are listed as commands in the xml-file.

Besides
* for attribute 9, SOFTWARE_VERSION, the max="0xFFFF" does not makes sense since it's a uint32
* for attribute 12, PART_NUMBER, the (max) length is 32 chars
* for attribute 17, REACHABLE, default is True which I assume to be 0x01 not 0x00
* for event 3  `ReachableChanged` the comment is a copy of the previous event's comment

 #### Proposed Solution
update the xml files (and the associated zap files) for these clusters

**Comment by pjzander-signify** [comment]
Implemented and merged.
