### ISSUE TITLE
[TC-RH-2.1] MaxMeasuredValue attribute default value violates the constraints specified in the spec. 

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#10947]
#### Problem

- The Water Content Measurement base cluster specifies constraints for the MaxMeasuredValue attribute to be between 1 and 10000, however the default value read is 0.
![image](https://user-images.githubusercontent.com/12559578/138810162-cc43f12c-17fa-4935-84c3-2f6da5209b51.png)
![image](https://user-images.githubusercontent.com/12559578/138810237-b12c07b5-303d-4681-b1ac-779e87537073.png)

- The optional attribute "Tolerance" is not supported by the YAML test framework.
![image](https://user-images.githubusercontent.com/12559578/138810569-d277b5b2-d792-42b2-9f2b-24abe5b3f940.png)

 #### Proposed Solution

- MaxMeasuredValue's default value must be 1.
- Add support for the optional tolerance attribute in the YAML framework.

**Comment by kowsisoundhar12** [comment]
1. MaxMeasuredValue's default value is still failing 
![2022-02-02_16-38](https://user-images.githubusercontent.com/57476670/152144604-beeac55a-1acb-428e-9221-54e9e09b2c60.png)
[RH_2_1_Error-logs.zip](https://github.com/project-chip/connectedhomeip/files/7985961/RH_2_1_Error-logs.zip)
2.Tolerence attribute added in yaml framework
![2022-02-02_16-51](https://user-images.githubusercontent.com/57476670/152145007-1bd1bc5a-3e98-4767-a3cb-55f3a17347e6.png)
