### ISSUE TITLE
[TC-PCC-2.3]Control Mode Attribute not supported in yaml framework.

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#10954]
#### Problem
[TC-PCC-2.3] Primary functionality with server as DUT, step3a requires us to write attribute ControlMode [Pump Configuration and Control] which does not seem to be supported currently.
![image](https://user-images.githubusercontent.com/12559578/138837641-32f9d46d-17f5-481c-9930-cbd449001743.png
[PCC_2_3.txt](https://github.com/project-chip/connectedhomeip/files/7416385/PCC_2_3.txt)
)

**Comment by woody-apple** [comment]
Doesn't this just mean the ControlMode isn't implemented?

**Comment by vivien-apple** [comment]
Based on https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_PCC_2_3.yaml#L40 it seems to work now.
