### ISSUE TITLE
[TC-PCC-2.2] Values written to EffectiveOperationMode attribute do not reflect back on read.

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#10951]
#### Problem
Writing values to OperationMode attribute is always successful, but reading  EffectiveOperationMode value back always returns 0 always.
Attached logs:
[pcc_2_2_step1.txt](https://github.com/project-chip/connectedhomeip/files/7415684/pcc_2_2_step1.txt)

**Comment by bzbarsky-apple** [comment]
@kvikrambhat Is this still an issue on ToT?  What are the steps to reproduce?

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
