### ISSUE TITLE
Need support for ability of a simulated device to change levels of packet loss

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#10999]
#### Problem
Need a way for TH/DUT to change how many packets it received to simulate partial packet loss scenario. 
No simulated device exists to test such a test case when using `chip-tool`.

For example, in `[TC-SC-1.1] MRP Retransmission Messaging`, Steps 1.a, 2.a, 2.c, 3.a require it. 

![Expected Outcome](https://user-images.githubusercontent.com/80923273/138958927-e514195d-e4ee-4230-a2b3-056d520f927a.png)

**Comment by woody-apple** [comment]
Suggest doing at the system layer, that's the only way to do this reliably.
