### ISSUE TITLE
Simulated Device YAML Discovery Support 

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#11001]
#### Problem
7.2.2. [TC-DD-2.2] Discovery by commissioner verification [DUT - Commissioner]

The above test requires stringent validation of the discovery process from the simulated device. From the simulated device we need to be able to validate that the commissioner (DUT) is capable of discovering the Simulated Device (TH) and that the boarding payload is reported correctly. 

Example Yaml :

Hopefully the syntax can be something like this :

```
label : "Broadcast advertising data."
command: "broadcastBLE"
arguments :
  values:
    - name: "discriminator"
      value: 3840
    - name: "vendorID"
      value: null
    - name: "productID"
      value: null
    - name: "extendedData"
      value: null
    - name: "timeOut"
      value: 10

label : "Validate onboarding payload."
command: "validateOnboardingPayload"
arguments :
  values:
    - name: "param1"
      value: 3840
    - name: "param2"
      value: 'AABBCCDDEEFF"
    - name: "param3"
      value: 0

```

Here is the test: https://github.com/CHIP-Specifications/chip-test-plans/blob/a5a498779fefe2d4cfa1141dc332120b91b561c6/src/devicediscovery.adoc#322-tc-dd-22-discovery-by-commissioner-verification-dut---commissioner

**Comment by raju-apple** [comment]
This will be needed for 1.0
