### ISSUE TITLE
Create bare Android app

### ISSUE THREAD

**Issue by dnicoara** [project-chip/connectedhomeip#1102]
This is mostly to get things going and have something useful that multiple developers can share while working on different parts of the Android App.

* Add basic Android App
* Add README with instructions on how to build it, any dependencies, etc.

**Comment by randyrossi** [comment]
Skeleton app is complete with code to scan a QR code and parse it in review.  Echo and on/off screens are stubs for now.

Will open a separate task for the CHIPDeviceConnection layer.
Will open separate tasks for the echo and on/off tasks once CHIPDeviceConnection is available.

**Comment by sagar-apple** [comment]
@vidhis88 I think you've already taken care of this. Wanna self assign and close it?
