### ISSUE TITLE
google Matter EAP

### ISSUE THREAD

**Issue by denny089** [project-chip/connectedhomeip#11037]
Google Smart Home Developer Summit 2021 mentioned that Google development preview support Matter now. We would like to play around with that, so we need the access to the Early Access Program(EAP). 
We couldn't find any information about how to join EAP, Could someone explain how to get the access ?

**Comment by andy31415** [comment]
Closing as a matter oss sdk issue as this is not a feature/bug request for the SDK itself.

@denny089 for google EAP joining, you should contact google directly.
