### ISSUE TITLE
[TC-PRS-1.1] Global Attributes Missing From Pressure Measurement Cluster

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#11053]
#### Problem
The following global cluster attributes seem to be missing in the Pressure Measurement cluster
 - FeatureMap
 - AttributeList
 - CommandList
 - EventList
 
**Spec Ref**
![image](https://user-images.githubusercontent.com/12559578/139087031-9c9b993e-6121-47c4-b0f7-38c12a5f735c.png)

**YAML Test Script Logs**
![image](https://user-images.githubusercontent.com/12559578/139086961-02d17316-7e6f-4bac-a878-c882aa9aace8.png)

**Comment by manjunathambiger23** [comment]
The following global attributes seem to be missing in the all clusters 
1. FeatureMap
2. AttributeList
3. EventList
4. ClientGeneratedCommandList
5. ServerGeneratedCommandList

The following Testcases are missing the global attribute 
TC-BI-1.1 ,TC-BOOL-1.1 ,TC-CC-1.1 ,TC-DIAGTH-1.1 ,TC-EMR-1.1 ,TC-ILL-1.1 ,TC-LVL-1.1 ,TC-MC-1.1, TC-OCC-1.1 ,TC-OO-1.1 ,TC-PCC-1.1, TC-PRS-1.1 ,TC-RH-1.1, TC-TM-1.1, TC-TSTAT-1.1, TC-TSUIC-1.1, TC-WNCV-1.1

 Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/142194210-faa46ff8-fae0-4be3-821c-d288cf21e1f0.png)

**Comment by holbrookt** [comment]
@kvikrambhat is this still an issue?

**Comment by manjunathambiger23** [comment]
@holbrookt we are still facing attribute missing issue
Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/151983796-b453a2cd-c7de-43ba-89d0-1348fab6607b.png)
Execution screenshot:
![1](https://user-images.githubusercontent.com/84442963/151975062-3fc534ad-c8a1-4bf7-b4ac-c38289d852e7.png)
![BI_1 1](https://user-images.githubusercontent.com/84442963/151975070-a31e07d4-2c1b-4ed1-a929-4ffd3f69647f.png)
![image](https://user-images.githubusercontent.com/84442963/151998324-71f7b580-24a5-4bde-be53-1c4e03ddac9a.png)

**Comment by bzbarsky-apple** [comment]
On current tip I see:
```
./out/debug/standalone/chip-tool pressuremeasurement read
[1644466642455] [32667:14897110] CHIP: [TOO] Missing attribute name
Usage:
  ./out/debug/standalone/chip-tool pressuremeasurement read attribute-name [param1 param2 ...]

  +-------------------------------------------------------------------------------------+
  | Attributes:                                                                         |
  +-------------------------------------------------------------------------------------+
  | * measured-value                                                                    |
  | * min-measured-value                                                                |
  | * max-measured-value                                                                |
  | * attribute-list                                                                    |
  | * cluster-revision                                                                  |
  +-------------------------------------------------------------------------------------+
```

No FeatureMap, which seems like a mismatch against current spec.

No EventList; that's tracked in https://github.com/project-chip/connectedhomeip/issues/15011.

**Comment by vivien-apple** [comment]
Currently `chip-tool` generates commands for all the attributes/commands for all clusters.
In theory, if it is missing it is an SDK bug, not a test harness issue.

Here is the output of `chip-tool` on ToT. You can see that it still miss `event-list` but this is because of #15011 as mentioned by Boris.

So I'm closing this issue, assuming `event-list` will automatically appears in `chip-tool` once #15011 is resolved.
```
$ ./out/debug/standalone/chip-tool pressuremeasurement read
```

```
Usage:
  ./out/debug/standalone/chip-tool pressuremeasurement read attribute-name [param1 param2 ...]

  +-------------------------------------------------------------------------------------+
  | Attributes:                                                                         |
  +-------------------------------------------------------------------------------------+
  | * measured-value                                                                    |
  | * min-measured-value                                                                |
  | * max-measured-value                                                                |
  | * tolerance                                                                         |
  | * scaled-value                                                                      |
  | * min-scaled-value                                                                  |
  | * max-scaled-value                                                                  |
  | * scaled-tolerance                                                                  |
  | * scale                                                                             |
  | * server-generated-command-list                                                     |
  | * client-generated-command-list                                                     |
  | * attribute-list                                                                    |
  | * feature-map                                                                       |
  | * cluster-revision                                                                  |
  +-------------------------------------------------------------------------------------+
```
