### ISSUE TITLE
chip tool pairing onnetwork-commissioning-mode api fails at CASE session establishment

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#11064]
On ToT (521345202fef46c8039d2b79d38a29507905ca41) chip tool pairing onnetwork-commissioning-mode api fails at CASE session establishment. 

Steps to reproduce, 
1. Build chip-tool  using below commands
   A. gn gen out/debug --args='chip_mdns="platform"' 
   B. ninja -C out/debug
2. launch onnetwork-commissioning-mode using sudo ./out/debug/chip-tool pairing onnetwork-commissioning-mode 99997777 20202021

Attached log
[log-2.txt](https://github.com/project-chip/connectedhomeip/files/7427807/log-2.txt)

**Comment by woody-apple** [comment]
I'm assuming this is resolved now?
