### ISSUE TITLE
Add code comments documenting the use of providerFabricIndex in the call to  gOperationalDeviceProxy.Init()

### ISSUE THREAD

**Issue by selissia** [project-chip/connectedhomeip#11069]
#### Problem
This was brought up by @tcarmelveilleux: Current variable naming of providerFabricIndex is misleading.

 #### Proposed Solution
Add a comment to SendQueryImageCommand() around the call to gOperationalDeviceProxy.Init() explaining that the fabric index has only local significance and that it's obtained from the context of the session for the Announce OTA Provider command. If possible, rename the providerFabricIndex variable to reflect this.

**Comment by carol-apple** [comment]
This is not longer relevant as CASESessionManager is used to establish CASE sessions instead of directly using OperationalDeviceProxy objects.
