### ISSUE TITLE
Certification declaration parsing is future-hostile

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#11082]
#### Problem
The code added in #10825 requires that there be no tags after kTag_DACOriginVendorId.  That means future spec versions will not be able to add anything there.

Why are we doing that?

 #### Proposed Solution
Stop requiring CHIP_END_OF_TLV there.  Allow CHIP_NO_ERROR as well, and probably CHIP_ERROR_UNEXPECTED_TLV_ELEMENT.

**Comment by woody-apple** [comment]
This looks resolved?

**Comment by bzbarsky-apple** [comment]
Looks like #11838 fixed this.
