### ISSUE TITLE
[TC-MF-1.4] Read Fabriclist fails when Second Controller Commissions and read attribute

### ISSUE THREAD

**Issue by praveenCY** [project-chip/connectedhomeip#11092]
#### Problem
[TC-MF-1.4] Node Behavior using BCM [DUT - Commissionee]

TH_CR1 starts a commissioning process with DUT_CE

If (PICS_MF_BCM) TH_CR1 opens a commissioning window on DUT_CE using a commissioning timeout of PIXIT_COMM_WIN seconds using BCM
zcl AdministratorCommissioning OpenBasicCommissioningWindow 12344321 0 0 commissioningTimeout=500

TH_CR1 writes and reads the Basic Information Cluster’s NodeLabel mandatory attribute of DUT_CE
zclwrite Basic UserLabel 12344321 0 0 TE5New
zclread Basic UserLabel 12344321 0 0

TH_CR2 starts a commissioning process with DUT_CE
connect -ip 192.168.1.111 20202021 12345678

TH_CR1 reads the list of Fabrics on DUT_CE
zclread OperationalCredentials FabricsList 12344321 0 0

TH_CR2 reads the list of Fabrics on DUT_CE
zclread OperationalCredentials FabricsList 12345678 0 0 ==> This fails , but CR1 can still read attributes

[LOCK-TC-MF-1.4-MasterFailureLog.txt](https://github.com/project-chip/connectedhomeip/files/7429488/LOCK-TC-MF-1.4-MasterFailureLog.txt)

**Commit log**
commit edc22bd (HEAD -> master, origin/master, origin/HEAD)
Author: Vivien Nicolas vnicolas@apple.com
Date: Wed Oct 27 22:02:31 2021 +0200

**DUT Log:**

CHIP:SC: Sending status report. Protocol code 0, exchange 22744
CHIP:EM: Piggybacking Ack for MessageCounter:1845535937 on exchange: 22744r
CHIP:IN: Prepared plaintext message 0x8018220 to 0x0000000000000000 of type 0xhx and protocolId (64, 0) on exchange 0� with MessageCounter:114.
CHIP:IN: Sending plaintext msg 0x8018220 with MessageCounter:755342411 to 0x0000000000000000 at monotonic time: ld msec
CHIP:IN: CASE Session established. Setting up the secure channel.
CHIP:IN: Marking old secure session for device 0x00000000000008AE as expired
CHIP:IN: New secure session created for device 0x00000000000008AE, key 3!!
CHIP:IN: CASE secure channel is available now.
CHIP:IN: CASE Server enabling CASE session setups
CHIP:DL: Long dispatch time: 2262 ms, for event type 4
CHIP:EM: Received message of type 0xhx with protocolId (16, 0) and MessageCounter:0 on exchange 42178�
CHIP:EM: Rxd Ack; Removing MessageCounter:755342411 from Retrans Table on exchange 22744r
CHIP:EM: Removed CHIP MessageCounter:755342411 from RetransTable on exchange 22744r
CHIP:IN: Data received on an unknown connection (4). Dropping it!!
CHIP:EM: Error receiving message from UDP:192.168.1.115:43750: Error CHIP:0x0000007F
CHIP:IN: Data received on an unknown connection (4). Dropping it!!
CHIP:EM: Error receiving message from UDP:192.168.1.115:43750: Error CHIP:0x0000007F
CHIP:IN: Data received on an unknown connection (4). Dropping it!!
CHIP:EM: Error receiving message from UDP:192.168.1.115:43750: Error CHIP:0x0000007F
CHIP:IN: Data received on an unknown connection (4). Dropping it!!
CHIP:EM: Error receiving message from UDP:192.168.1.115:43750: Error CHIP:0x0000007F
CHIP:DIS: Broadca

**Comment by bzbarsky-apple** [comment]
Not a 1.0 issue, since this is Python repl specific.
