### ISSUE TITLE
[YAML |`chip-tool`] Support for custom/overwriting endpointID 

### ISSUE THREAD

**Issue by mikaelhm** [project-chip/connectedhomeip#11102]
#### Problem
Currently cluster endpoint ID is hard coded in YAML test. When testing real devices, we need to specify cluster ID matching the DUT.
 
 #### Proposed Solution
Allow the cluster ID to be overwritten via a cli argument to the `chip-tool` command. So you can run it similar to this:

```shell
chip-tool tests Test_TC_OCC_2_1 --cluster-id=X
```

**Comment by vivien-apple** [comment]
Should have been fixed by #11740.
