### ISSUE TITLE
Implement non-volatility of attributes that are supposed to be non-volatile

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#11113]
#### Problem
The mechanism used for non-volatility in the initial silabs code (see #3623) no longer exists.

 #### Proposed Solution
Need to figure out how to deal with some attributes needing to be non-volatile.

**Comment by tcarmelveilleux** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/13172
