### ISSUE TITLE
ESP32 examples should build size-optimized

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1114]
#### Problem
Got out of flash space errors already (before we have BLE, thread and more logic). We need to ensure chip library is small. I managed to get it to run by adding -Os in the makefile for the example, but it still compiles with -O0 and just  -Og for many files (spot checked and it seemed like chip itself was not size optimized during compile)

 #### Proposed Solution
Update the build system to propagate -Os flag by default across builds.
Ensure linker strips out unused sections

**Comment by vivien-apple** [comment]
@shana-apple @kpschoedel I guess this issue falls on what you are looking at those days

**Comment by woody-apple** [comment]
SW BRB: @shana-apple @kpschoedel any update here?
