### ISSUE TITLE
Implement nimble as a transport for the BLE platform layer

### ISSUE THREAD

**Issue by kedars** [project-chip/connectedhomeip#1115]
#### Problem
NimBLE is fairly light-weight, its implementation in the ESP32 platform layer is missing.

 #### Proposed Solution
For ESP32, NimBLE is much more footprint optimised as opposed to BlueDroid (which pulls in classic-BT stuff as well). IIRC, this results in flash footprint savings of around 250KB and heap around 30-40K.

NimBLE being also supported by some other platforms that support BLE, it can also be factored out into a common piece of code at some point.

**Comment by woody-apple** [comment]
SW BRB: @kedars is there anyone than can sign up for this? Seems like a huge win.

**Comment by dhrishi** [comment]
Hey @vivien-apple  Yes, this can be closed now. NimBLE is the default BLE host for ESP32 in CHIP examples now :-)

**Comment by dhrishi** [comment]
Closing this as it is already done in https://github.com/project-chip/connectedhomeip/pull/1969
