### ISSUE TITLE
YAML / simulated device: Need support for sending DNS-SD advertising messages individually

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#11158]
#### Problem
Need support for YAML to send/receive messages to a simulated device and send/receive messages from chip-tool so that we can verify the Node discovery/commissioning process on a step-by-step basis.

Note: this functionality is already present in device discovery / commissioning but cannot thoroughly be tested without constructing and sending DNS-SD advertising messages individually.

 #### Examples
1. `[TC-SC-4.3] Operational Discovery - Node` test step 4 requires sending, intentionally, incorrectly formatted data so that the DUT can be sure it does not respond. https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/securechannel.adoc#343-tc-sc-43-operational-discovery---node 

![every discovery method](https://user-images.githubusercontent.com/80923273/139326119-31126593-bd55-4af8-9856-74ac740ea411.png)

2. `[TC-SC-4.4] Operational Discovery - Controller [DUT - Controller]` needs to test steps at precise times so that it can verify all of the correct advertising data before trying another step.  https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/securechannel.adoc#344-tc-sc-44-operational-discovery---controller-dut---controller 

![image](https://user-images.githubusercontent.com/80923273/139339675-7200d323-a375-499e-b34f-3be0a4b091f8.png)

**Comment by raju-apple** [comment]
@manjunath-grl can you try out the methods listed in https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/TestDiscovery.yaml  and try out how many of the SC/CADMIN tests this unblocks us with ?

**Comment by raul-marquez-csa** [comment]
Script has been automated in python
