### ISSUE TITLE
Shut Down, Restart, Factory Reset commands not supported in Chip-Tool - Requesting support

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#11167]
To check few test cases like TC-DM-1.2 steps 1, 2 and 3 via chip-tool and to further automate this test case, we need to know the chip-tool commands for Shut Down, Restart and Factory Reset. Requesting support for these commands in chip-tool.

<img width="942" alt="Screen Shot 2021-10-28 at 5 29 51 PM" src="https://user-images.githubusercontent.com/34750871/139354033-01f992d5-dd76-4d0c-bbdb-5da32d425ebb.png">

**Comment by raju-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/14240
