### ISSUE TITLE
Need a template class for linked list

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#11171]
#### Problem
LinkedList is a useful data structure for holding a list of uncertain number items (since we cannot have containers like std::vector due to tight memory), but we don't have one.

 #### Proposed Solution
Implement (or port) one.

**Comment by bzbarsky-apple** [comment]
Intrusive or not?

**Comment by bzbarsky-apple** [comment]
@erjiaqing Does IntrusiveList handle this?
