### ISSUE TITLE
[Test-TC-DIASW-1.1] ThreadMetrics attribute seems to be missing from the Software Diagnostics cluster

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#11185]
#### Problem
The optional attribute ThreadMetrics seems to be missing from the  Software Diagnostics cluster.

**Spec Ref**
![SoftwareDiagnosticsAttributes](https://user-images.githubusercontent.com/12559578/139425693-04054ed6-94f0-4d44-96a5-c3c7b2495a3e.png)

**YAML Test Script Error**
![TC-DIAGSW-1 1](https://user-images.githubusercontent.com/12559578/139425699-4567897b-745d-4ffe-b3e0-783560a4931c.png)

**Comment by kowsisoundhar12** [comment]
@holbrookt ThreadMetrics attribute added in yaml
![2022-02-01_13-16](https://user-images.githubusercontent.com/57476670/152141908-c402e0aa-4fb1-4f14-8fdb-1019a0c60a11.png)

**Comment by bzbarsky-apple** [comment]
This works fine, but the test is trying to read it from the wrong endpoint, so failing...  Fix coming up.
