### ISSUE TITLE
YAML and chip-tool: Add capability to send magic packet over ethernet on a specific MAC address

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#11213]
#### Problem
21.6.1. [TC-MC-4.1] Wake-On LAN Verification

In order to automate the test above, we need an ability to send a magic wake on LAN packet to a specific MAC address using YAML code gen. The Mac address will depend on a previous read attribute. The MAC address decency from a previous read has this [issue](https://github.com/project-chip/connectedhomeip/issues/10816) created.

[Test Case Link](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-4-1-wake-on-lan-verification)

**Comment by raju-apple** [comment]
Can be marked P2 considering that there is a way to run this manually currently.
