### ISSUE TITLE
YAML: Need to be able to execute test steps with wait times inserted before a step is run

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#11234]
#### Problem
There is a need to run test case steps with time between steps when executing chip-tool commands with YAML. 
This issue is present in many of the Color Control Cluster test cases that rely on attribute values rising or falling over a period of time and the need to periodically check them before moving forward with subsequent test steps.

 #### Example
`[TC-CC-3.1] Hue MoveTo functionality with server as DUT`, Steps 2b, 3b, 4b all require periodical attribute readings before moving to the next step to ensure the attribute value has reached it's desired value and not gone beyond its predefined limits. https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/colorcontrol.adoc#322-tc-cc-31-hue-moveto-functionality-with-server-as-dut

![image](https://user-images.githubusercontent.com/80923273/139499977-2ba693ab-396c-4a38-9c84-780023f52abe.png)

Other examples of same YAML support needed: 
`TC-CC-3.1 | Hue MoveTo functionality with server as DUT`
`TC-CC-3.2 | Hue Move functionality with server as DUT`
`TC-CC-3.3 | Hue Step functionality with server as DUT`
`TC-CC-4.1 | Saturation MoveTo functionality with server as DUT`
`TC-CC-4.2 | Saturation Move functionality with server as DUT`
`TC-CC-4.3 | Saturation Step functionality with server as DUT`
`TC-CC-4.4 | MoveToHueAndSaturation functionality with server as DUT`
`TC-CC-5.1 | Color MoveTo functionality with server as DUT`

</google-sheets-html-origin>

**Comment by vivien-apple** [comment]
@raju-apple Does https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/TestDelayCommands.yaml#L22 is of any helps here ?
