### ISSUE TITLE
[efr] EFR32 Device Layer needs ConfigurationMgr.

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#1128]
#### Problem
ConfigurationMgr is not part of SiLabs DeviceLayer build right now.

 #### Proposed Solution
Extend the partial implementation of ConfigurationMgrImpl to work and add it to the build.

Similar to #1127.

**Comment by sagar-apple** [comment]
@turon looks like EFR32 has a ConfiguraitonManager now. Should we close this?

**Comment by jepenven-silabs** [comment]
ConfiguraitonManager is implemented for EFR32 since August 2020.
