### ISSUE TITLE
iOS Framework integration dynamic vs static

### ISSUE THREAD

**Issue by amaolll123** [project-chip/connectedhomeip#11293]
#### Problem
Currently, Amazon is working on integrating CHIP.framework into our mobile App

However, as the built artifact of [CHIP framework](https://github.com/project-chip/connectedhomeip/tree/master/src/darwin/Framework) goes in `Dynamic Library` manner, it brings heavy latency impact on our app.

Question:
Is there a way to change the output format into `Static Library`? 
What would the workload look like for converting dynamic to static? 

@sagar-apple @vivien-apple

**Comment by amaolll123** [comment]
I tried to change `Mach-o` type to `staticlib`, but the building will fail to 
```
"error: unsupported Mach-O type 'staticlib' for Text-Based API (in target 'CHIP' from project 'CHIP')"
```

**Comment by amaolll123** [comment]
Turns out building in Xcode 13.1 will fix the issue. Closing.

**Comment by JourneyYoung** [comment]
Hello, I just change the output format into Static Library, and building in Xcode 14.0. But when I use Static Matter.framework in app target，It will be crash. Did you meet this issue?
