### ISSUE TITLE
Some of the test cases have dependency on Featuremap attribute, need chip-tool support

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#11295]
Few clusters have dependency on Featuremap attribute and the way we test the test case (Like the next steps in the test case) is changing with the value of the Featuremap attribute. Hence from the automation point of view, we need chip tool support for Featuremap attribute
<img width="964" alt="Screen Shot 2021-11-01 at 4 51 14 PM" src="https://user-images.githubusercontent.com/34750871/139757090-68c390f3-a231-4dd0-9bb7-ca8d14e89080.png">

**Comment by woody-apple** [comment]
Can't this attribute be read?

**Comment by raju-apple** [comment]
Looks like manually we have the ability to do this . @Garik098 can you double check please ?

**Comment by Garik098** [comment]
Featuremap Attribute is now available in Chip tool. It was not present when I raised the ticket but it is now present to read. Closing the ticket.
