### ISSUE TITLE
nRF5 platform makefile is not building all source code

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#113]
#### Problem
The following files are not being built, as they are heavily dependent on removed code (as part of #104 )

`ConfigurationManagerImpl.cpp`
`ThreadStackManagerImpl.cpp`
 `GroupKeyStoreImpl.cpp`
`SoftwareUpdateManagerImpl.cpp`
`Entropy.cpp`

Removed from `src/platform/Makefile.am`

 #### Proposed Solution
Fix the code, and add to makefile.

**Comment by bukepo** [comment]
`ConfigurationManagerImpl.cpp` was fixed by 9267c5b136d68428b3524e4f1d80b60fafbd4a0a.

Thread stack is already built and up.

Group key store, Entropy and SoftwareUpdateManager seems not used on any platform.

I don't think this is a blocking issue for project *nRF5 platform*.
