### ISSUE TITLE
Missing Fabric Index access from CommandHandler

### ISSUE THREAD

**Issue by rcasallas-silabs** [project-chip/connectedhomeip#11313]
#### Problem
Cluster callbacks receive an instance of CommandHandler as parameter, but to obtain the fabric index:
```
FabricIndex fabricIndex = commandObj->GetExchangeContext()->GetSessionHandle().GetFabricIndex();
```

 #### Proposed Solution
Add a direct accessor to FabricIndex to the CommandHandler class

**Comment by bzbarsky-apple** [comment]
`CommandHandler::GetAccessingFabricIndex` is a thing now.
