### ISSUE TITLE
Pump Configuration Control Cluster: operation-mode Write action not changing effective-operation-mode attribute value

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#11338]
#### Problem
When testing `[TC-PCC-2.2] Primary functionality with server as DUT`, running the `operation-mode` write command, the `effective-operation-mode` attribute should be updated but it does not change away from the default 0 value. 

Issue shows multiple times on Steps 2a, 3a, and 4a in `[TC-PCC-2.2] Primary functionality with server as DUT`.

#### Testing Setup
DUT: RasPi TE6 image's `chip-tool`
TH:  RasPi TE6 image's `chip-all-clusters-app`

![image](https://user-images.githubusercontent.com/80923273/139955912-f049686a-8e9e-4a5c-a5ce-2635cd4fc6a2.png)

Test Case: https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/pump_configuration_and_control.adoc#322-tc-pcc-22-primary-functionality-with-server-as-dut

DUT Logs attached.
[TC-PCC-2.2 Logs.txt](https://github.com/project-chip/connectedhomeip/files/7464170/TC-PCC-2.2.Logs.txt)

**Comment by tlykkeberg-grundfos** [comment]
This should have been fixed with PR #17181

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
