### ISSUE TITLE
CHIP Clusters do not support multiple requests in single message

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#11335]
#### Problem
Currently there is no way to implement tests or any tests covering the following tests in the steps where there is multiple requests in one message. The zzz_generated/controller-clusters/zap-generated/CHIPClusters.cpp file does not implement a way to perform these actions which the YAML test infrastructure uses to write tests. 

[[TC-IDM-3.2] Write Response Action from DUT to TH.](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-3-2-write-response-action-from-dut-to-th)
[[TC-IDM-4.1] SubscriptionRequestMessage from DUT test cases](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#351-tc-idm-41-subscriptionrequestmessage-from-dut-test-cases)
[[TC-IDM-4.2] ReportDataMessage from DUT test cases](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-4-2-reportdatamessage-from-dut-test-cases)

 #### Proposed Solution
Update the Zap files below to support the following:
Multiple AttributeRequests, EventRequests, and EventFilters in SubscribeRequestMessage and ReadRequestMessage. 
Multiple WriteRequests in WriteRequestMessage

src/app/zap-templates/templates/app/CHIPClusters.zapt
src/app/zap-templates/templates/app/CHIPClusters-src.zapt

 #### Notes
Once the proposed solution is added, the YAML framework should be able to add test cases based off the command added to the clusters. The parameters can be a list of EndPoints, and the value. Please take in consideration YAML framework. 

Example: [Test Link]() In step 2

**Comment by raju-apple** [comment]
This is needed for 1.0

**Comment by vivien-apple** [comment]
`CHIPClusters.zapt`  and `CHIPClusters-src.zapt` are gone but we will find some ways to get it to work.

**Comment by raju-apple** [comment]
P1 - ETA 3/15

**Comment by vivien-apple** [comment]
The command line bits (aka `chip-tool`) are here: https://github.com/project-chip/connectedhomeip/pull/15787
Those bits should let us remove the `manual-testing` tag from this issue.
