### ISSUE TITLE
YAML and chip-tool support needed for Sniffer

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#11347]
For the Device Attestation test cases, we need Sniffer support for Chip tool and YAML.
<img width="1108" alt="Screen Shot 2021-11-02 at 4 53 22 PM" src="https://user-images.githubusercontent.com/34750871/139967357-ca43820f-063c-41c8-8d05-0f754ba6b1eb.png">
.

**Comment by mikaelhm** [comment]
I don't think we need a sniffer for this test:

1. TH2 would know the Fabric ID internally
2. DUT fabric ID can be verified by commissioning TH1 or TH3 to the DUT network.

**Comment by raju-apple** [comment]
@manjunath-grl Can you look at Mikael's comment , can you check if we need to re-open this or create a new one
