### ISSUE TITLE
YAML support needed for multiple commissioners scenario

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#11342]
In Multi admin testcases, we need to run multiple commissioners (Chip tool, python controllers) at the same time connecting to DUT. Need YAML support to have multiple commissioners to automate these scenarios.
<img width="1001" alt="Screen Shot 2021-11-02 at 3 30 07 PM" src="https://user-images.githubusercontent.com/34750871/139960665-225cfae2-7f16-46bb-a76d-dee5e5978fa8.png">

**Comment by raju-apple** [comment]
P2 , manually possible to test . Only needed for scripting.

**Comment by vivien-apple** [comment]
It exists already. You can use: `"identity": alpha` on any command and it will send the command from commissioner "alpha".

You can choose between:
  * alpha (default)
  * beta
  * gamma
