### ISSUE TITLE
[SimNodes] Piggyback ScanNetworksResponse payload for validation of AddWifi/ThreadNetwork.

### ISSUE THREAD

**Issue by trombadore** [project-chip/connectedhomeip#11340]
#### Problem
For controller certification test[ TC-DM-3.3](https://github.com/CHIP-Specifications/chip-test-plans/blob/5b213bdbf12bea3abea14aeb76bdc49df915e557/src/devicemanagement.adoc#333-tc-dm-33-network-commissioning-commands-dut---commissioner), the DUT controller will send a `ScanNetworks` command to a simulated node. The simulated node will respond with a list of networks via the `ScanNetworksResponse` command it sends back to the DUT controller. The simulated node will then wait to receive an `AddThreadNetwork` or `AddWifiNetwork`command. 

The simulated node needs to verify that the argument sent along with `AddWifi/ThreadNetwork` is contained within the list of networks sent by the simulated node via `ScanNetworksResponse` from the prior step. 

#### Proposed Solution
Piggyback the payload of the simulated device's `ScanNetworksResponse` for validation in later steps when waiting to receive AddWifi/ThreadNetwork command from DUT controller.

**Comment by SaileeG** [comment]
Any update on this?
