### ISSUE TITLE
Support for IsUrgent for IM event

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#11386]
#### Problem
Need Support for IsUrgent for IM event

**Comment by holbrookt** [comment]
@yunhanw-google Is this a spec issue? Should it remain in the 1.0 list?

**Comment by yunhanw-google** [comment]
Fixed.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/12459
