### ISSUE TITLE
Support for BDX session initiation

### ISSUE THREAD

**Issue by ukatira** [project-chip/connectedhomeip#11387]
#### Problem
 The only way for initiating/testing BDX protocol is in the context of file transfer with OTA.
But it only tests BDX in a specific configuration and remaining configs cannot be tested. 
There is no way right now to execute tests TC-BDX-1.5, 1.6.

 #### Proposed Solution
Add support for BDX session initiation to either OTA reference apps or chip-tool to perform these tests.

**Comment by woody-apple** [comment]
@carol-apple ?

**Comment by carol-apple** [comment]
We can't test this for v1.0

**Comment by woody-apple** [comment]
Moving out then, thanks!
