### ISSUE TITLE
Support for injecting eventStatus to IM event management

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#11388]
#### Problem
Need Support for injecting eventStatus to IM event management
 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
What is this blocking?

**Comment by yunhanw-google** [comment]
@mrjerryjohns I think currently we don't need work this one for 1.0?

**Comment by woody-apple** [comment]
Closing this, please re-open if needed!
