### ISSUE TITLE
[ota-requestor-app] Make values of QueryImage Command configurable

### ISSUE THREAD

**Issue by ukatira** [project-chip/connectedhomeip#11399]
#### Problem
The following field of the QueryImage command is currently not configurable.

The RequestorCanConsent field of the QueryImage command (Spec: 11.20.6.7 Pg-673) can be:
- False (default)
- True for testing purposes (Ex: TC-SU-3.3 Step-3, 4)

 #### Proposed Solution

- Provide a way to respond with different RequestorCanConsent field values

**Comment by mrjerryjohns** [comment]
@carol-apple @holbrookt is this a v1.0 feature?

**Comment by woody-apple** [comment]
@mrjerryjohns Yup.
