### ISSUE TITLE
[ota-provider-app] Make various values to QueryImageResponse Command configurable

### ISSUE THREAD

**Issue by ukatira** [project-chip/connectedhomeip#11393]
#### Problem
The following fields of the QueryImageResponse command are currently not configurable.

The SoftwareVersion field of the QueryImageResponse command can be:
- Version of image being provided
- Incorrect value for testing purposes (Ex: TC-SU-2.2 Step-6)

UserConsentNeeded field of the QueryImageResponse command can be:
- False (default)
- True for testing purposes (Ex: TC-SU-2.2 Step-7)

 #### Proposed Solution
- Provide a way to respond with different SoftwareVersion field values
- Provide a way to respond with different UserConsentNeeded field values

**Comment by dhrishi** [comment]
@shubhamdp PTAL

**Comment by shubhamdp** [comment]
Command line option for user consent is added in PR #13816 and for software version it is added in #14619
