### ISSUE TITLE
ReadClient should store a ScopedNodeId to avoid FabricIndex/NodeID mismatch

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#11431]
#### Problem
After #11318 a ReadClient stores a fabric index and node id.

 #### Proposed Solution
Perhaps store a ScopedNodeId instead.

**Comment by woody-apple** [comment]
Sounds like this could be addressed post v1.0

**Comment by bzbarsky-apple** [comment]
This is fixed.  ReadClient now stores ScopedNodeId.
