### ISSUE TITLE
Bridge-app has unmerged conflict on branch `test_event_7`

### ISSUE THREAD

**Issue by mikaelhm** [project-chip/connectedhomeip#11454]
#### Problem
https://github.com/project-chip/connectedhomeip/blob/test_event_7/examples/bridge-app/linux/main.cpp#L450-L492
The `main.cpp` file for `bridge-app` has an unmerged conflict on branch `test_event_7`

 #### Proposed Solution
I unfortunately don't know anything about the conflict.
@andreilitvin, @pjzander-signify you seem to have been working on this, based on git blame.

**Comment by cjandhyala** [comment]
Although we fix the merge conflicts and build the app, provisioning the app seem to fail. We need that to be looked at as well.

**Comment by andy31415** [comment]
I believe I fixed it - at least I removed the merge markers and kept the two functions there.

**Comment by andy31415** [comment]
I did not look into or resolve the 'provision the app fails'. For that please open a separate issue so we have only one per problem. That requires followup from someone familiar with the app (likely Paul).
