### ISSUE TITLE
Chip-tool : Few of the steps might need a different action for CI and TH

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#11474]
For few steps in TCs , we might need the yaml test to perform a specific set of steps for CI and also have a different set of steps in case the TH calls the same TC

So might require some sort of `ifdef` declarations while compiling for TH and CI to have this support

**Comment by vivien-apple** [comment]
As discussed, let' see if this can be done with PICS at the moment.

**Comment by vivien-apple** [comment]
@raju-apple I will close it soon unless you tell me that the PICS approach is not enough !

**Comment by raju-apple** [comment]
Lets do with PICS for now.
