### ISSUE TITLE
NOCs attribute is missing from operational cluster in XML

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#11492]
#### Problem
NOCs attribute is missing in src/app/zap-templates/zcl/data-model/chip/operational-credentials-cluster.xml

[Spec Reference](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/OperationalCredentialCluster.adoc#16-attributes)

**Comment by tcarmelveilleux** [comment]
Implemented by https://github.com/project-chip/connectedhomeip/pull/13563
