### ISSUE TITLE
Investigate ESP32 Stack Growth

### ISSUE THREAD

**Issue by gerickson** [project-chip/connectedhomeip#1150]
#### Problem
In PR #1145, the CHIP task stack size was increased to 8,192. For reference, the equivalent `CONFIG_WEAVE_TASK_STACK_SIZE` was/is 5,120. We should do a stack analysis to determine what we think ends up needing an extra ~3 KiB. I have a `stackan` script I can contribute if we want to mechanistically analyze this.

I'm concerned at this early stage of development in which the stack isn't even close to complete that we need to already need to grow the stack this much.

**Comment by vivien-apple** [comment]
@shana-apple @kpschoedel I believe this issue falls into what you are looking into those days

**Comment by woody-apple** [comment]
SW BRB: @shana-apple can you close this with the output of your investigation with @kpschoedel and @kedars ?

**Comment by kedars** [comment]
cc @dhrishi

**Comment by sweetymhaiske** [comment]
We checked the working of code with CHIP task stack size as 4608 on both M5Stack and DevkitC followed by pairing(via BLE and WiFi) -> toggling on on/off cluster -> reset to factory -> repeat. It worked fine, leaving the minimum free stack size as 400, which was checked using FreeRTOS API `uxTaskGetStackHighWaterMark`. These observations were tried out on latest code with commit id - `9318d1307bc437635d740e9a18181c837fecbe0c`.

**Comment by dhrishi** [comment]
@sweetymhaiske  Thanks!

@woody-apple Considering the minimum free stack size of ~400 bytes during the process, I think it is safe to set the stack size to 4.5K (4608 bytes mentioned above) or 5K? There would have been a lot of churn in the CHIP code as well from the time this issue was reported. So, may be, something fixed this?

**Comment by dhrishi** [comment]
@sweetymhaiske  One more thing you could try is to enable debug level logs and run the same test again. If it passes, then we can make the change to set the stack size to 5120 bytes (to be on the safer side)

**Comment by sweetymhaiske** [comment]
@dhrishi Tried the changes with debug logs enabled and it worked fine. PR for the same #4757
