### ISSUE TITLE
Note, though, that except for proxies the Node id can (and should!) be omitted.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#11513]
Note, though, that except for proxies the Node id can (and should!) be omitted.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/11500#discussion_r744038065_

**Comment by bzbarsky-apple** [comment]
Note that proxies are out of scope for 1.0, so we should simply not have the node id bits here at all.
