### ISSUE TITLE
[TC-TSTAT-2.1] Some Thermostat Attributes are missing from YAML framework

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#11524]
Summary :
As per Spec there are 49 attributes which supports Thermostat Cluster but when made a run 22 attributes are missing in YAML framework.

Spec Screenshot and Log file :
![image](https://user-images.githubusercontent.com/84442963/140746706-b992ec98-371a-4168-8e82-027fa0ff4da2.png)
[TSTAT_2_1.txt](https://github
![Screenshot from 2021-11-08 16-50-05](https://user-images.githubusercontent.com/84442963/140746948-12dad8ad-e860-4b9e-a277-1d42c81a56cf.png)
.com/project-chip/connectedhomeip/files/7497106/TSTAT_2_1.txt)

**Comment by chrisbeach59** [comment]
Only the attributes currently supported by the thermostat cluster are in the controller zap file.  The ones related to scheduling are present as scheduling implementation had been started, but were unable to be completed and tested due to missing functionality in the SDK (lists and structs).

**Comment by kowsisoundhar12** [comment]
@chrisbeach59 still observing attribute missing error in TC-TSTAT-2.1 Scripts,please find spec screenshot and error logs
Error screenshot :
![2022-02-24_14-57](https://user-images.githubusercontent.com/57476670/155497550-08a6352f-10ee-458f-9d56-bd13b39f52ff.png)

Spec screenshot : 
![2022-02-24_14-59](https://user-images.githubusercontent.com/57476670/155497663-49b6fd68-2d30-4854-8183-1ec1abf7ec3e.png)
![2022-02-24_14-59_1](https://user-images.githubusercontent.com/57476670/155497703-e369614a-b02c-4038-b459-06358192295a.png)
![2022-02-24_14-59_2](https://user-images.githubusercontent.com/57476670/155497721-ee297131-67ad-4e99-b635-6227c1fdce80.png)
![2022-02-24_14-59_3](https://user-images.githubusercontent.com/57476670/155497735-d568665b-c2da-484b-8206-c53a360cf011.png)
![2022-02-24_14-59_4](https://user-images.githubusercontent.com/57476670/155497751-4a886847-a3f2-42e4-9e4d-ba25dd120c0e.png)
