### ISSUE TITLE
Support read cache attribute values for peer Sleepy Devices

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#11554]
#### Problem
This applies mainly for controller devices. If a peer device is a sleepy device, it will not be reachable at all times. If the controller application tries to read or write attributes of such devices, it'll currently fail.

To mitigate, the controller API can cache the attribute values for such devices. The read requests will return the last known value from the controller cache. The write attribute request will update the cache, and enqueue a command to be sent to the sleepy device.

**Comment by mrjerryjohns** [comment]
I'm actually working on something similar caching attribute data on reads/subscribes such that there's a cache available that describes the latest state on the target device. We should likely collaborate.

**Comment by mrjerryjohns** [comment]
A class to implement this (`AttributeCache`) has been implemented and checked in a while back
