### ISSUE TITLE
[TC-DIAGSW-3.2] Command failing --ResetWatermarks

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#11578]
Summary :
As per test plane the command  ResetWatermarks is  to be send from the TH and should return a successful status, however when we try to use this command in the YAML test scripts they seem to always fail, please refer attached screenshots and logs

Test-plan Screenshot:
![image](https://user-images.githubusercontent.com/84442963/140897826-7fd9e62e-db89-4a5b-bf30-6645a0fe5fa3.png)

Spec Screenshot:
![image](https://user-images.githubusercontent.com/84442963/140898342-de5832d2-c4a4-40d5-a51d-182d5ae07bf8.png)

Log file and Execution Screenshot:
[DIASW_3_2.txt](https://github.com/project-chip/connectedhomeip/files/7503579/DIASW_3_2.txt)
![image](https://user-images.githubusercontent.com/84442963/140899157-cb64543b-cb8f-411c-b040-9d89bf5b24e1.png)

**Comment by bzbarsky-apple** [comment]
That's because the test is sending it to endpoint 1, not endpoint 0.
