### ISSUE TITLE
[TC-TSTAT-2.1] Attribute default value mismatch

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#11625]
Summary:
As per Spec the default value of NumberOfWeeklyTransitions and NumberOfDailyTransitions Attribute needs to be 0 but when we execute YAML script the value returned for NumberOfWeeklyTransitions and NumberOfDailyTransitions are 7 and 4.

Spec screenshot :
![image](https://user-images.githubusercontent.com/84442963/141085639-c7d9de76-29a0-4abc-ae0c-6ad598b23ce2.png)

Execution Screenshot:
![Tstat_1](https://user-images.githubusercontent.com/84442963/141085971-93fa3bbe-369f-4a07-9dce-e43cee181c87.png)
![tstat_2](https://user-images.githubusercontent.com/84442963/141085999-479a3b99-93bc-494c-9fb0-cbc31bde9e00.png)

Execution log :
[TSTAT_2_1.txt](https://github.com/project-chip/connectedhomeip/files/7511410/TSTAT_2_1.txt)

**Comment by chrisbeach59** [comment]
The defaults are there to support dependencies for when an attribute is not present.  If you look at the zap file for the thermostat example.  That is the current values that are configured.  A DUT at power up is not expected/required to respond with default values.

**Comment by manjunathambiger23** [comment]
@chrisbeach59 as per the test plan they are asking us to check default value
![image](https://user-images.githubusercontent.com/84442963/152282512-50a0f524-4b13-4498-ae59-fb477f92919e.png)
