### ISSUE TITLE
Build failure on ToT

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#11637]
#### Problem
ninja: Entering directory `./out/debug'
[156/4419] ld fake_x64_gcc/tests/TestPlatform
FAILED: fake_x64_gcc/tests/TestPlatform fake_x64_gcc/tests/TestPlatform.map 
g++ -O0 -fPIC -Werror -Wl,--fatal-warnings -Wl,-z,defs -fdiagnostics-color -pie -Wl,-Map,fake_x64_gcc/tests/TestPlatform.map -Wl,--gc-sections @fake_x64_gcc/tests/TestPlatform.rsp -o fake_x64_gcc/tests/TestPlatform
/usr/bin/ld: fake_x64_gcc/obj/src/lib/dnssd/lib/dnssd.a(dnssd.Discovery_ImplPlatform.cpp.o): in function `chip::DeviceLayer::ConfigurationMgr()':
/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:109: multiple definition of `chip::DeviceLayer::ConfigurationMgr()'; fake_x64_gcc/lib/libMdnsFakePlatformTests.a(libMdnsFakePlatformTests.TestPlatform.cpp.o):/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:109: first defined here
/usr/bin/ld: fake_x64_gcc/obj/src/lib/dnssd/lib/dnssd.a(dnssd.Discovery_ImplPlatform.cpp.o): in function `chip::DeviceLayer::SetConfigurationMgr(chip::DeviceLayer::ConfigurationManagerImpl*)':
/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:114: multiple definition of `chip::DeviceLayer::SetConfigurationMgr(chip::DeviceLayer::ConfigurationManagerImpl*)'; fake_x64_gcc/lib/libMdnsFakePlatformTests.a(libMdnsFakePlatformTests.TestPlatform.cpp.o):/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:114: first defined here
/usr/bin/ld: fake_x64_gcc/obj/src/platform/lib/libDeviceLayer.a(libDeviceLayer.Globals.cpp.o): in function `chip::DeviceLayer::ConfigurationMgr()':
/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:109: multiple definition of `chip::DeviceLayer::ConfigurationMgr()'; fake_x64_gcc/lib/libMdnsFakePlatformTests.a(libMdnsFakePlatformTests.TestPlatform.cpp.o):/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:109: first defined here
/usr/bin/ld: fake_x64_gcc/obj/src/platform/lib/libDeviceLayer.a(libDeviceLayer.Globals.cpp.o): in function `chip::DeviceLayer::SetConfigurationMgr(chip::DeviceLayer::ConfigurationManagerImpl*)':
/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:114: multiple definition of `chip::DeviceLayer::SetConfigurationMgr(chip::DeviceLayer::ConfigurationManagerImpl*)'; fake_x64_gcc/lib/libMdnsFakePlatformTests.a(libMdnsFakePlatformTests.TestPlatform.cpp.o):/usr/local/google/home/cecille/chip/connectedhomeip/out/debug/../../src/platform/fake/ConfigurationManagerImpl.h:114: first defined here
collect2: error: ld returned 1 exit status
[203/4419] c++ fake_x64_gcc/obj/src/transport/raw/tests/libNetworkTestHelpers.NetworkTestHelpers.cpp.o
FAILED: fake_x64_gcc/obj/src/transport/raw/tests/libNetworkTestHelpers.NetworkTestHelpers.cpp.o 
g++ -MMD -MF fake_x64_gcc/obj/src/transport/raw/tests/libNetworkTestHelpers.NetworkTestHelpers.cpp.o.d -Wconversion -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow -Wunreachable-code -Wvla -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wno-cast-function-type -fdiagnostics-color -fno-strict-aliasing -std=gnu++14 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -I../../src/include -I../../src -Ifake_x64_gcc/gen/include -I../../zzz_generated/app-common -I../../config/standalone -I../../third_party/nlassert/repo/include -I../../third_party/nlio/repo/include -I../../third_party/nlfaultinjection/repo/include -I../../third_party/nlunit-test/repo/src -c ../../src/transport/raw/tests/NetworkTestHelpers.cpp -o fake_x64_gcc/obj/src/transport/raw/tests/libNetworkTestHelpers.NetworkTestHelpers.cpp.o
../../src/transport/raw/tests/NetworkTestHelpers.cpp: In member function ‘CHIP_ERROR chip::Test::IOContext::Init()’:
../../src/transport/raw/tests/NetworkTestHelpers.cpp:33:90: error: ‘GetDefaultInstance’ is not a member of ‘chip::DeviceLayer::ConfigurationManagerImpl’
   33 |     chip::DeviceLayer::SetConfigurationMgr(&chip::DeviceLayer::ConfigurationManagerImpl::GetDefaultInstance());
      |                                                                                          ^~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
[229/4419] c++ linux_x64_clang/obj/zzz_generated/controller-clusters/zap-generated/data_model.CHIPClustersInvoke.cpp.o
ninja: build stopped: subcommand failed.

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by harimau-qirex** [comment]
It looks like there are two problems in the fake platform:
1) The ConfigurationMgr/SetConfigurationMgr methods are defined multiple times because they're defined in a header file.
2) The tests require ConfigurationManagerImpl::GetDefaultInstance, which isn't defined.
