### ISSUE TITLE
Remove "Type" suffix and use spec-defined names for enum and struct in cluster xmls

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#11643]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
@yufengwangca Is this necessary for v1? Not clear.
