### ISSUE TITLE
[AttributeAccessInterface] Return back path-specific status codes in read/write failure   

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#11663]
#### Problem
In both the code being added and the existing code for reads, there is no facility for providers to return back path-specific status codes. Instead, any error returned back is deemed terminal to the interaction and tears it all down.

 #### Proposed Solution
Jerry Johns  11:34 AM
My suggestion would be to:
Make any errors encountered in Read and Write not be terminal.
Return back a StatusIB (or something equivalent that encapsulates an IM + cluster-specific code) instead.
Encode that within the response.

Boris Zbarsky  10 hours ago
The #1 question is whether this error handling should be inside ReadSingleClusterData or in its caller.

Boris Zbarsky  10 hours ago
As in, how does it interact with reads not going via AttributeAccessInterface?

Boris Zbarsky  10 hours ago
Similar for writes

Jerry Johns  1 minute ago
Likely inside ReadSingleClusterData itself, since it has to deal directly with IM-level status codes coming back from the calls to the attribute access overrides.

Similarly, it would have to convert the EmberAfStatus (which we need to fix btw) coming back from EmberAfReadAttribute .

**Comment by mrjerryjohns** [comment]
Summary of chat with @bzbarsky-apple:

1. Prioritize encapsulating IM StatusIBs in a `CHIP_ERROR`.
2. Fix the `Write` API in `AttributeAccessInterface` to only permit returning back a StatusIB.
3. Provide utility method to convert any CHIP_ERROR to StatusIB.
