### ISSUE TITLE
[device layer] Implement missing functionality in GenericConfigurationMgr

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#1166]
#### Problem
GenericConfigurationMgr references missing implementations for FabricState and hash algorithm.

 #### Proposed Solution
Align hash algorithm with decisions from crypto team.

Regarding FabricState, need to track decisions there as well (TODO add reference to FabricState tracking issue #756).

Extend various platform implementations to support the new generic functionality (add new key/value pairs as needed and enable generic configuration tests)

**Comment by yufengwangca** [comment]
https://github.com/project-chip/connectedhomeip/pull/1181

This issue can be closed
