### ISSUE TITLE
Thermostat cluster attributes that should be nullable are not marked that way in the XML

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#11670]
Summary:
As per spec the default value of some attributes are null and we need to check the default value as expected using Scripts but Null check is not implemented in YAML framework.

Spec Screenshot: 
![image](https://user-images.githubusercontent.com/84442963/141275335-232e0ed7-5dd8-4e42-94d3-3651f3c4f61a.png)

Execution Screenshot:
![image](https://user-images.githubusercontent.com/84442963/141275540-042e13f1-0031-4414-86db-6a488681358c.png)

**Comment by bzbarsky-apple** [comment]
Null checking is implemented just fine.  But in the XML these attributes are not marked nullable.

**Comment by manjunathambiger23** [comment]
@bzbarsky-apple we are facing same build error issue in Pump configuration cluster:
Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/148787680-3dfdeeb7-2709-4c6f-8c8a-b598c7be2fee.png)
Execution screenshot:
![image](https://user-images.githubusercontent.com/84442963/148788407-4f8f0def-9f69-4857-97d1-d40341200b85.png)

**Comment by bzbarsky-apple** [comment]
> @bzbarsky-apple we are facing same build error issue in Pump configuration cluster:

I suggest filing separate issues per cluster that has this problem, but more importantly getting the domain owners for these clusters to fix those issues...

**Comment by manjunathambiger23** [comment]
> > @bzbarsky-apple we are facing same build error issue in Pump configuration cluster:
> 
> I suggest filing separate issues per cluster that has this problem, but more importantly getting the domain owners for these clusters to fix those issues...

ok i will do it

**Comment by manjunathambiger23** [comment]
https://github.com/project-chip/connectedhomeip/issues/16552

**Comment by manjunathambiger23** [comment]
https://github.com/project-chip/connectedhomeip/issues/16550

**Comment by manjunathambiger23** [comment]
https://github.com/project-chip/connectedhomeip/issues/16554

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
