### ISSUE TITLE
[TC-TSTAT-2.2] Write command above max and below min value returns Sucess Response 

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#11718]
Summary:
As per the Test-plan the Test Step tells  we have use write command to write the below min and above max value it should return the error CONSTRAINT_ERROR (0x87)
but when we execute the YAML script it returned with status: Success  (0x0000) 
Attributes : OCCUPIEDCOOLINGSETPOINT , OCCUPIEDHEATINGSETPOINT , MINHEATSETPOINTLIMIT , MAXHEATSETPOINTLIMIT , MINCOOLSETPOINTLIMIT ,MAXCOOLSETPOINTLIMIT

Test-plan screenshot:
![image](https://user-images.githubusercontent.com/84442963/141420860-2a21632c-40e9-43c6-ac4c-35952c3f8ee2.png)
same goes for 3b,4b, 5b, 6b, 7b

Execution logs and Screenshot:
[tstat-2.2[W].txt](https://github.com/project-chip/connectedhomeip/files/7525306/tstat-2.2.W.txt)
![Tstat1](https://user-images.githubusercontent.com/84442963/141420706-4d28495e-cf71-4f0d-ae50-50155bd54182.png)
![Tstat2](https://user-images.githubusercontent.com/84442963/141420711-669790c8-18cf-4047-928b-001548e41f33.png)
![Tstat3](https://user-images.githubusercontent.com/84442963/141420717-56397b89-723f-4ad3-897f-35dda2d02f5e.png)
![Tstat4](https://user-images.githubusercontent.com/84442963/141420724-e9a570cb-284e-4f80-abc2-16625f4e3797.png)
![Tstat5](https://user-images.githubusercontent.com/84442963/141420730-875224b0-e2b6-4969-b46e-60e351921e58.png)
![Tstat6](https://user-images.githubusercontent.com/84442963/141420735-18228329-9f9e-4100-a66c-5f6a4799819e.png)
![Tstat7](https://user-images.githubusercontent.com/84442963/141420742-3a36625e-4262-4952-b5a6-f4a6838104dd.png)

**Comment by chrisbeach59** [comment]
I suspect that your DUT does not provide the pre-attribute-changed-callback.  Please review the example code in the thermostat-app.
