### ISSUE TITLE
Followup: Shouldn't this failure to decode the incoming message send a failure response instead of just silently dropping things on the floor?  Similar for other failures in this method.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#11724]
Followup: Shouldn't this failure to decode the incoming message send a failure response instead of just silently dropping things on the floor?  Similar for other failures in this method.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/11667#discussion_r747745098_

**Comment by bzbarsky-apple** [comment]
The comment there was about InteractionModelEngine::OnReadInitialRequest.

See also https://github.com/project-chip/connectedhomeip/issues/17623
