### ISSUE TITLE
[TC-DIAGSW-2.1] Reading the List is not implemented in YAML framework

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#11725]
Summary:
As per the Test-plan we have to read the list of softwareFault struct event from DUT to TH but reading the list in not implemented in YAML framework

Test-plan screenshot:
![image](https://user-images.githubusercontent.com/84442963/141423368-f20b210a-0d89-4aac-a0ea-65f24f357d0b.png)

Spec Screenshot:
![image](https://user-images.githubusercontent.com/84442963/141441054-bd426f36-e6d8-4ede-b922-0cef283a9f57.png)

**Comment by vivien-apple** [comment]
YAML knows how to read list already. I assume this is related to events, and in this case it is a duplicate of #11343. Feel free to reopen if I'm wrong.
