### ISSUE TITLE
Mode Select Cluster's On/Off feature is not supported

### ISSUE THREAD

**Issue by du48s03** [project-chip/connectedhomeip#11746]
#### Problem
 * Mode Select Cluster's On/Off feature should be supported
 * Mode Select Cluster's On/Off feature is not supported

 #### Proposed Solution
Implement the On/Off feature for Mode Select Cluster

**Comment by turon** [comment]
Mode Cluster must be spec compliant for v1.
Removing tag `v1_triage_split_4`
