### ISSUE TITLE
Mode Select Cluster does not support scene

### ISSUE THREAD

**Issue by du48s03** [project-chip/connectedhomeip#11745]
#### Problem
 * Mode Select Cluster's CurrentMode attribute should support Scene, as specified by the Specification
 * CurrentMode Attribute is not supporting scene

 #### Proposed Solution
Add implementation in `src/app/clusters/scenes/scenes.cpp` to support CurrentMode

**Comment by woody-apple** [comment]
SDK Spec Review: Moving out of 1.X, given we do not have an implementation plan for scenes in 1.0
