### ISSUE TITLE
Support write cache attribute values for peer Sleepy Devices

### ISSUE THREAD

**Issue by carol-apple** [project-chip/connectedhomeip#11754]
#### Problem
https://github.com/project-chip/connectedhomeip/issues/11554 will handle reading of cache attribute values. This ticket is to track the work needed for writing of the cache. The write attribute request will update the cache, and enqueue a command to be sent to the sleepy device.

**Comment by SkipAshton** [comment]
Is this required for the 1.0 release or it is a later optimization?  Cache or proxy operations may be beyond initial scope (but would be nice to have)

**Comment by woody-apple** [comment]
Isn’t this the same as:
https://github.com/project-chip/connectedhomeip/issues/11555
?
