### ISSUE TITLE
Set optional list attributes dirty when their values get changed

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#11814]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Can you please clarify what this is? It has no description.
