### ISSUE TITLE
#TE7 [TC-GENDIAG-1.1] and [TC-GENDIAG-1.2] description and verification steps are wrong.

### ISSUE THREAD

**Issue by fessehaeve** [project-chip/connectedhomeip#11828]
#### Problem

The description for these tests is very misleading and incorrect. The test as the name says is general and doesn’t depend on the networking capability of the DUT. In addition, the verification steps are wrong.
```
3.1.1. [TC-GENDIAG-1.1] Attributes with server as DUT
	Purpose						
	This test case verifies the behavior of the non-global attributes of the WiFi network diagnostics cluster server.	
```					
and
```
	3.1.2. [TC-GENDIAG-1.2] Attributes with client as DUT					Pls refer to the PICS definition https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc	
	Purpose						
	This test case verifies the behavior of the non-global attributes of the ethernet network diagnostics cluster server.	
```					

 #### Proposed Solution

Description should be updated from the PICS doc.
Verification steps for [TC-GENDIAG-1.1] should be something like this:

```
  "# TC-GENDIAG-1.1"
"./chip-tool generaldiagnostics read network-interfaces 1 0"
"./chip-tool generaldiagnostics read reboot-count 1 0"
```

**Comment by mrjerryjohns** [comment]
Is this still relevant?

**Comment by mrjerryjohns** [comment]
@fessehaeve can you confirm?

**Comment by fessehaeve** [comment]
@mrjerryjohns the verification steps are correct now. The description is still wrong.
TC-GENDIAG-1.1
`This test case verifies the behavior of the non-global attributes of the WiFi network diagnostics cluster server.`
TC-GENDIAG-1.2
`This test case verifies the behavior of the non-global attributes of the ethernet network diagnostics cluster server.`

**Comment by woody-apple** [comment]
@raju-apple Do you know where this should go?
