### ISSUE TITLE
[TC-WIFIDIAG-1.1] WifiNetworkDiagnostics cluster attributes report incorrect values

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#11821]
#### Problem
Information reported from some of the WifiNetworkDiagnostics cluster attributes is incorrect.
* Bssid is empty
* Security type is correct
* WifiVersion potentially wrong expected 2 Reported 0.
* Wifi Channel is correct
* RSSI looks OK.
* Beacon Count is 0 (?)
* All packet counts and rates are 0. Expect some non-zero values.

Looks like some attributes may be simply returning the default value.

#### Test Cases
TC-WIFIDIAG-1.1 | Attributes with server as DUT
* https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/wifi_diagnostics.adoc#tc-wifidiag-1-1-attributes-with-server-as-dut

#### Logs
[21-11-16_04:07_TC-WIFIDIAG-1.1.log](https://github.com/project-chip/connectedhomeip/files/7543591/21-11-16_04.07_TC-WIFIDIAG-1.1.log)

#### DUT
* commit f51eeb39de1e58c8f55a13cfc59782e8e11c6948 (HEAD -> test_event_7, origin/test_event_7
 * ESP32 Platform
 * On/Off Light Switch

**Comment by franck-apple** [comment]
@andrew-lifx and @wqx6 , is this fixed by PR #12082?

**Comment by wqx6** [comment]
@franck-apple Yes, it is fixed now.
