### ISSUE TITLE
[TC-I-2.3] DUT is sending default Failure response to identify trigger-effect command when identify is not active

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#11898]
#### Problem
From Test Event 7
The DUT is generating a default Failure response to an identify trigger-effect when identify is not active on the device.

Expected response is to trigger the effect or the default is not supported.

#### Test Cases
TC-I-2.2 | Primary functionality with server as DUT

#### Logs
[21-11-16_23:52:28_TC-I-2.3.log](https://github.com/project-chip/connectedhomeip/files/7551233/21-11-16_23.52.28_TC-I-2.3.log)

#### DUT
* commit f51eeb39de1e58c8f55a13cfc59782e8e11c6948 (HEAD -> test_event_7, origin/test_event_7
 * ESP32 Platform
 * On/Off Light Switch

 #### Proposed Solution
According to the Specification
> 1.2.5.3.3. Effect on Receipt
> On receipt of this command, the device SHALL execute the trigger effect indicated in the EffectIdentifier and EffectVariant fields. If the EffectVariant field specifies a variant that is not supported on the device, it SHALL execute the default variant.

**Comment by franck-apple** [comment]
@andrew-lifx and @wqx6 , is this fixed by PR #12082?

**Comment by wqx6** [comment]
@franck-apple Yes, it is fixed now.
