### ISSUE TITLE
[TC-I-2.2] Identify-time attribute is not counting down

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#11895]
#### Problem
The identify-time attribute is not counting down while an identity is active. It remains at the last set value either by and identify command or an attribute write.

#### Test Cases
TC-I-2.2 | Primary functionality with server as DUT

#### Logs
[21-11-16_23:19:49_TC-I-2.2.log](https://github.com/project-chip/connectedhomeip/files/7551078/21-11-16_23.19.49_TC-I-2.2.log)

#### DUT
* commit f51eeb39de1e58c8f55a13cfc59782e8e11c6948 (HEAD -> test_event_7, origin/test_event_7
 * ESP32 Platform
 * On/Off Light Switch

**Comment by franck-apple** [comment]
@andrew-lifx and @wqx6 , is this fixed by PR #12082?

**Comment by wqx6** [comment]
@franck-apple Yes, it is fixed now.
