### ISSUE TITLE
[TC-GENDIAG-1.1] All generaldiagnostics cluster attributes returned zero or empty data

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#11899]
#### Problem
From Test Event 7
The DUT returned zero or an empty list/string/array for all cluster attributes in [TC-GENDIAG-1.1]
This implies that none of these attributes are actually being filled out with valid data.

#### Test Cases
TC-GENDIAG-1.1 |  Attributes with server as DUT

#### Logs
[21-11-17_04:06:53_TC-GENDIAG-1.1.log](https://github.com/project-chip/connectedhomeip/files/7551626/21-11-17_04.06.53_TC-GENDIAG-1.1.log)

#### DUT
* commit f51eeb39de1e58c8f55a13cfc59782e8e11c6948 (HEAD -> test_event_7, origin/test_event_7
 * ESP32 Platform
 * On/Off Light Switch, all-cluster-app

**Comment by wqx6** [comment]
Hi, Andrew, Here is a temporary fix for your issues https://github.com/wqx6/connectedhomeip/tree/test_event_7 , I will raise a PR later.

**Comment by bzbarsky-apple** [comment]
@andrew-lifx Is this still an issue?

**Comment by franck-apple** [comment]
resolved in #11654
