### ISSUE TITLE
Getting a subcommand failure in ESP32 build command

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#11903]
#### Problem
<Getting a subcommand failure in ESP32 build command
  * expected behavior  : 
            "idf.py -p /dev/ttyUSB0 erase_flash build flash monitor " command should work fine so that we could have advertising with controller .

  * actual behavior  :  

          - "ninja: build stopped: subcommand failed."

 * screenshots, images, logs, etc.
 >
[esp cmd failing.txt](https://github.com/project-chip/connectedhomeip/files/7554452/esp.cmd.failing.txt)

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by chshu** [comment]
The actual error in the log:
```
../main/DeviceCallbacks.cpp:31:10: fatal error: esp_check.h: No such file or directory
 #include "esp_check.h"
```
`esp_check` was instroduced since IDF-v4.3, so please double check the IDF version you are using, IDF v4.4 is recommened now.
