### ISSUE TITLE
[TE7] TC-MF-1.20 max number of Commissioned Fabrics and SupportedFabrics rollover using ECM or BCM [DUT - Commissioner]

### ISSUE THREAD

**Issue by cabin15** [project-chip/connectedhomeip#11901]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior: Third commissioner should failed to commission to commissionee due to exceeding the max number of supported fabrics with NOCResponse with a StatusCode of 0x05 on the step 6 of TC-MF-1.20.
 * actual behavior: Third commissioner failed to commission to commissionee with timeout
 * steps to reproduce: You can refer to steps of TC-MF-1.20
 * system configuration
 * screenshots, images, logs, etc.
 >

This bug was already filed on https://github.com/project-chip/connectedhomeip/issues/10052.
On the ticket, reporter said that this bug is not reproduced on the master.

I assumed that test_event_7 branch already has the fix for this. So, I tested on test_event_7 branch, but issue still persists.

You can refer to my reproduced log on https://github.com/project-chip/connectedhomeip/issues/10052.

If this is fixed on master, could anyone let me know what commits fix this? so that I can cherry-pick it on test_event_7 branch and test.

Thanks in advance.

**Comment by franck-apple** [comment]
@cjandhyala is this not resolved?

**Comment by bzbarsky-apple** [comment]
@cabin15 Is this still a problem?  The logic for this is in place as far as I know....

**Comment by naveenkommareddi** [comment]
Issue resolved per latest SDK test report. This can be closed

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
