### ISSUE TITLE
Refactor DeviceAttestationVerifier to have Async interface

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#11917]
#### Problem
Since the DeviceAttestation procedure relies on data that may be remote (e.g. DCL or equivalent), we need the DeviceAttestationVerifier APIs to be asynchronous (non-blocking) so that long running processes do not block the main SDK event loop

 #### Proposed Solution
- Introduce a delegate API to `VerifyAttestationInformation` so that the outcome is provided through the delegate, rather than awaiting a blocking synchronous return value to the call

**Comment by vijs** [comment]
@tcarmelveilleux  Can this issue be closed? Is there anything pending?

**Comment by woody-apple** [comment]
@tcarmelveilleux Please re-open if needed
