### ISSUE TITLE
Add details to `VerifyAttestationInformation` so that more `AttestationVerificationResult` values are reportable

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#11918]
#### Problem
Current `VerifyAttestationInformation` does simplified processing that will return `AttestationVerificationResult::kDacSignatureInvalid` for *any* failure of the certificate chain validation, event if not related to DAC signature. This is because there is only a bool result used and we do not expose the internal outcome of the certificate chain validation that would expose the true error, such as validity period expiration, malformed certs, missing extensions.

 #### Proposed Solution

- Update `ValidateCertificateChain` in CHIPCryptoPal to have more details about the failures
- Convert new `ValidateCertificateChain` errors into `AttestationVerificationResult` cases
- Add checks to `VerifyAttestationInformation` to account for additional Matter-only policy regarding contents of DAC chain elements (e.g. specific requirements for extensions present, etc)

**Comment by vijs** [comment]
This issue is addressed in PR #12655
