### ISSUE TITLE
Power attribute missing in Pump Configuration and Control Cluster in Mac Chip Tool

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#11945]
The below mentioned attributes were present in ZCL but for MAC Chip Tool they are not available to read.

zclread PumpConfigurationAndControl LifetimeRunningHours 12344321 1 0
zclread PumpConfigurationAndControl Power 12344321 1 0

Attaching a screenshot of what attributes were currently available for the Mac Chip Tool to read. Other than these attributes others were not present to read.
<img width="652" alt="Screen Shot 2021-11-17 at 2 08 39 PM" src="https://user-images.githubusercontent.com/34750871/142290385-400b4cce-a0bb-4772-92b3-5ea0fb4c3a0f.png">

**Comment by Garik098** [comment]
Lifetimerunninghours and Power are now appearing in the chip tool list

**Comment by turon** [comment]
Closing based on @Garik098 's comment.
Can reopen if in fact the support has not been added fully.
