### ISSUE TITLE
Review comments for PR 11615

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#11951]
#### Problem
#11615 landed before I reviewed it, which is not a problem per se, but it has various code that can't possibly work (or even compile, if the template were being instantiated), which _is_ a problem.  See https://github.com/project-chip/connectedhomeip/pull/11615#pullrequestreview-809270516

@mrjerryjohns @LuDuda @chrisdecenzo @jmartinez-silabs @yunhanw-google 

 #### Proposed Solution
Fix issues.

**Comment by mrjerryjohns** [comment]
Already merged.

**Comment by bzbarsky-apple** [comment]
Not all addressed.  See https://github.com/project-chip/connectedhomeip/pull/11615#discussion_r751752143

**Comment by bzbarsky-apple** [comment]
Ah, nevermind, I missed the comment being added some lines up.
