### ISSUE TITLE
[TE#7] [TC-CC-1.1] Test Harness does not execute step 2

### ISSUE THREAD

**Issue by Kxuan** [project-chip/connectedhomeip#11962]
#### Problem
The step 2 of TC-CC-1.1 requires TH read ClusterRevision on DUT.
But TH does not do this.

![image](https://user-images.githubusercontent.com/10725111/142385219-b3052053-497e-426f-9441-0c31ea44b4d4.png)

**Comment by franck-apple** [comment]
Please file this issue in the Test Harness repo. Closing it here.
