### ISSUE TITLE
need extend supersetof function to overlapped for clusterInfoA and clusterInfoB, and need to get the overlapped part, and send report with overlapped part

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#11960]
yep, need extend supersetof function to overlapped for clusterInfoA and clusterInfoB, and need to get the overlapped part, and send report with overlapped part, perhaps in

_Originally posted by @yunhanw-google in https://github.com/project-chip/connectedhomeip/pull/11795#discussion_r751958515_

**Comment by tcarmelveilleux** [comment]
@erjiaqing Is this complete?

**Comment by erjiaqing** [comment]
No, this is not complete, but I think this is a optimization for saving CPU cycles and memory consumption.

My idea would be adding a filter to `AttributePathExpandIterator` instead of calculating the overlapped paths.

**Comment by woody-apple** [comment]
Let's move this to post v1.X until it's clear this is required.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/18597 where we resolve partial overlap issue between subscribed path and setDirty path
