### ISSUE TITLE
[TE#7][TC-CC-6.1]Test Harness execute wrong steps

### ISSUE THREAD

**Issue by Kxuan** [project-chip/connectedhomeip#11971]
#### Problem
**TH should do these steps:**

* TH reads ColorTemperature attribute from DUT.
* TH sends MoveToColorTemperature(150) command to DUT over TransitionTime(200) in 10th of a second Does not execute  command if the On/Off cluster, OnOff attribute is FALSE. ( optionsMask=0 optionOverride=0) 
* Over TransitionTime, TH reads ColorTemperature attribute from DUT.

**But what really do is:

            - Starting ChipTool Test [EXECUTING]
            - Starting ChipTool Test [PASSED]
            - Turn on light for color control tests [EXECUTING]
            - Turn on light for color control tests [PASSED]
            - Check on/off attribute value is true after on command [EXECUTING]
            - Check on/off attribute value is true after on command [PASSED]
            - Move To Color Temperature command [EXECUTING]
            - Move To Color Temperature command [PASSED]
            - Turn off light that we turned on [EXECUTING]
            - Turn off light that we turned on [PASSED]
            - Check on/off attribute value is false after off command [EXECUTING]
            - Check on/off attribute value is false after off command [PASSED]

It does not check the Color Temperature attribute

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by franck-apple** [comment]
Please file this issue in the Test Harness repo. Closing it here.
