### ISSUE TITLE
[Darwin] The Operational Credentials Cluster has no reportable attributes

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#11985]
#### Problem
We seem to not be generating subscribe/report APIs for the attributes in `CHIPOperationalCredentials`. 

 #### Proposed Solution
Mark the attributes as reportable (if applicable) and regenerate the APIs for it.

**Comment by bzbarsky-apple** [comment]
Partially fixed by https://github.com/project-chip/connectedhomeip/pull/11995

**Comment by bzbarsky-apple** [comment]
All attributes are reportable now.
