### ISSUE TITLE
Some Light transition fail timing requirments on ESP32 platform due to the excessive amount of logging.

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#12012]
#### Problem
Test Event 7, TC-LVL-4.1and TC-LVL-5.1 failed.
The DUT fails to perform the level transitions in the correct time.
This is caused by the high rate of updates to the CurrentLevel attribute and the excessive amount of logging output produced on each update.
Note this can also be affected by delays in the application side, post change attribute callback.

#### Test Cases
TC-LVL-4.1 | Move Verification (DUT as Server)
TC-LVL-5.1 | Step Verification (DUT as Server)

#### Logs
[TC-LVL-4.1_21-11-19_01:49:53.log](https://github.com/project-chip/connectedhomeip/files/7567690/TC-LVL-4.1_21-11-19_01.49.53.log)
[TC-LVL-5.1_21-11-19_04:32:10.log](https://github.com/project-chip/connectedhomeip/files/7567788/TC-LVL-5.1_21-11-19_04.32.10.log)

#### DUT
* commit f51eeb39de1e58c8f55a13cfc59782e8e11c6948 (HEAD -> test_event_7, origin/test_event_7
 * ESP32 Platform
 * Extended Color Light

#### Proposed Solution
The are a few way this could be rectified.
* reduce the amount of logging into transition updates.
* Change the global CHIP logging level for the platform to reduce the amount of logging generated.
* Decouple the transition operation such. the logging and callbacks for attribute changes happens asynchronous to the actual attribute update. Thereby maintaining the correct rate of change to the attribute irrespective time taken to to report a change in the attribute.

**Comment by franck-apple** [comment]
Not seen on raspPi. Closing
