### ISSUE TITLE
[TE7][TC-MF-1.13][TC-MF-1.15] Wrong status code when trying to open two commissioning window

### ISSUE THREAD

**Issue by du48s03** [project-chip/connectedhomeip#12015]
#### Problem

 * expected behavior: when opening a second commissioning window while the first is still open, the response  status code should be BUSY(0x9c)
 * actual behavior: The status code was Failed (0x01)

**Comment by bzbarsky-apple** [comment]
The spec for opening commissioning windows (in both "11.19.8.1. OpenCommissioningWindow (OCW) Command" and "11.19.8.2. OpenBasicCommissioningWindow (OBCW) Command") says:

> If a commissioning window is already currently open, this command SHALL fail with a cluster specific status code of Busy.

This status code is defined in "11.19.9. Status Codes" to have the value 1.  And the response I am seeing matches the spec:

```
[1651727336706] [63884:41054898] CHIP: [DMG] 				StatusIB =
[1651727336706] [63884:41054898] CHIP: [DMG] 				{
[1651727336706] [63884:41054898] CHIP: [DMG] 					status = 0x01 (FAILURE),
[1651727336706] [63884:41054898] CHIP: [DMG] 					cluster-status = 0x1,
[1651727336707] [63884:41054898] CHIP: [DMG] 				},
```

The `0x9c` listed above is the _global_ BUSY status code, but that's not what this cluster spec uses.
