### ISSUE TITLE
[TC-OO-2.3] Fails because OffWithEffect OnWithRecallGlobalScene and OnWithTimedOff are not supported in the build

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#12018]
#### Problem
In Test Event 7 [TC-OO-2.3] Fails because the on-off Cluster commands OffWithEffect, OnWithRecallGlobalScene and OnWithTimedOff are not supported in the current SDK build.
If these commands are enabled linker errors occur in the build. 
 undefined reference to `emberAfOnOffClusterOffWithEffectCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OnOff::Commands::OffWithEffect::DecodableType const&)'
 undefined reference to `emberAfOnOffClusterOnWithRecallGlobalSceneCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OnOff::Commands::OnWithRecallGlobalScene::DecodableType const&)'
 undefined reference to `emberAfOnOffClusterOnWithTimedOffCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OnOff::Commands::OnWithTimedOff::DecodableType const&)'
 undefined reference to `emberAfOnOffClusterOffWithEffectCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OnOff::Commands::OffWithEffect::DecodableType const&)'
 undefined reference to `emberAfOnOffClusterOnWithRecallGlobalSceneCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OnOff::Commands::OnWithRecallGlobalScene::DecodableType const&)'
 undefined reference to `emberAfOnOffClusterOnWithTimedOffCallback(chip::app::CommandHandler*, chip::app::ConcreteCommandPath const&, chip::app::Clusters::OnOff::Commands::OnWithTimedOff::DecodableType const&)'

These functions can be found in src/app/clusters/zll-on-off-server/zll-on-off-server.c, but cannot cannot be used in the build because of missing header includes.

**Comment by mrjerryjohns** [comment]
TE7 was quite a ways back, and the code has evolved significantly since then. Marking this as stale.
