### ISSUE TITLE
TH doesn't  sends OnWithTimedOff command to DUT   [TC-OO-2.3]

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#12024]
#### Problem
<TH doesn't  sends OnWithTimedOff command to DUT  
 * expected behavior  :  After a few seconds the value of OnOff has to be 0x01
 * actual behavior  :  there is no value of OnOff
 

 
[TC-OO-2.3 CTRL 3.odt](https://github.com/project-chip/connectedhomeip/files/7568735/TC-OO-2.3.CTRL.3.odt)
[TC-OO-2.3-DUT 3.odt](https://github.com/project-chip/connectedhomeip/files/7568736/TC-OO-2.3-DUT.3.odt)

**Comment by franck-apple** [comment]
Please file this issue in the Test Harness repo. Closing it here.
