### ISSUE TITLE
YAML Bridge test support

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#12033]
#### Problem
We need to be able to determine which command to perform based on previous test step. For example, if bridge has support for cluster A and B, we need to perform actions on A and B or if bridge support cluster C and D, we need to perform action on C and D.

**Comment by woody-apple** [comment]
@pjzander-signify Given you've been working on the bridge, can you please help work on the testing of this as well for the certification program?

@franck-apple FYI.

Note: We believe this is supported by manual testing right now.
