### ISSUE TITLE
rename userLabel attribute to NodeLabel in both Basic Information Cluster and Bridge Basic Information Cluster

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#12048]
rename userLabel attribute to NodeLabel (Mandatory attribute) in both Basic Information Cluster and Bridge Basic Information Cluster. SDK needs to have implementation for the added UniqueID attribute

Spec Ref
![Screen Shot 2021-11-19 at 11 04 01 AM](https://user-images.githubusercontent.com/68604034/142677397-32ae1660-2ceb-40ed-acdd-55f3b1d35941.png)

![Screen Shot 2021-11-19 at 11 05 52 AM](https://user-images.githubusercontent.com/68604034/142677615-bdef8ffe-2f13-439e-9d1c-7801d009c556.png)

**Comment by franck-apple** [comment]
closing this one, as this is done
