### ISSUE TITLE
Fabric Filtered Reads/Writes/Subscribes

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#12053]
Implemented fabric-filtered reads/writes/subscribes.

This should likely happen within the `AttributeAccessInterface`, very similar to what is being done for chunking in #12019, i.e the application/cluster handler shouldn't have to manage this bit of logic. Rather, the IM can automatically transpose the list indices as needed.

**Comment by mlepage-google** [comment]
Related: #10237
