### ISSUE TITLE
Port Happy to CHIP for parallel integration test.

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1207]
#### Problem
UDP and secure session unit tests create "real sockets" on the chip standard port and listen on the local loopback interface. If these tests run in parallel, several UDP sockets are openend and they all listen on the same port, receiving packets from different tests.

This makes tests fail due to unexpected packets being received.

 #### Proposed Solution
Use a unique port for every test run, so at  least within the same toolchain tests can run in parallel.
Find a way for a test runner to pass in a port to use (environment variables or command line for example).

**Comment by yunhanw-google** [comment]
Do we have contact person for the circleCI? in openweave, when using travis CI, It works expected. Our team is putting resource to integrate HAPPY here.

**Comment by andy31415** [comment]
Apparently there is also https://gvisor.dev/ as an option. It abstracts away the network stack and supposedly can run linux binaries unmodified. This could allow us to run the tests under it.

**Comment by yunhanw-google** [comment]
Github action azure VM support ip netns container, we should be good to go.
