### ISSUE TITLE
Light transitions stalling during chip-tool message processing. (ESP32)

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#12075]
#### Problem
This issues was observed during Test Event 7, Color Control Cluster ColorLoopSet tests.
There were significant delays while processing messages from chip-tool. These delay appeared to stall any active transitions in progress. The result being that the transition timing was inaccurate.
The delays ere of the order 1-3 seconds. 
These delays were observed when using the chip-device-ctrl tool.

The stall is easiest to observe in the DUT log.
This could be a Platform specific issue.

#### Test Cases
[TC-CC-9.1] | ColorLoopSet Validation
[TC-CC-9.1] | ColorLoopSet Validation - change direction without stop
[TC-CC-9.1] | ColorLoopSet Validation - change time without stop

#### Logs
[TC-CC-9.1_21-11-21_22:06:35.log](https://github.com/project-chip/connectedhomeip/files/7577625/TC-CC-9.1_21-11-21_22.06.35.log)
[TC-CC-9.2_21-11-21_22:43:28.log](https://github.com/project-chip/connectedhomeip/files/7577626/TC-CC-9.2_21-11-21_22.43.28.log)
[TC-CC-9.3_21-11-21_22:48:25.log](https://github.com/project-chip/connectedhomeip/files/7577628/TC-CC-9.3_21-11-21_22.48.25.log)
[TC-CC-9.1_DUT_stall.log](https://github.com/project-chip/connectedhomeip/files/7577642/TC-CC-9.1_DUT_stall.log)

#### DUT
* commit f51eeb39de1e58c8f55a13cfc59782e8e11c6948 (HEAD -> test_event_7, origin/test_event_7
 * ESP32 Platform
 * Extended Color Light, all-cliuster-app

**Comment by mrjerryjohns** [comment]
TE7 was quite a long ways back, so marking this as stale. If issue still exists, please file a new issue with latest code.
