### ISSUE TITLE
No response from DUT while running command [TC-LVL-2.2]

### ISSUE THREAD

**Issue by kvsmohan** [project-chip/connectedhomeip#12085]
#### Problem
<No response from DUT while running command 
 While running the following command there is no response from DUT side but  the expected Outcome is Verify that the DUT response contains an integer. Record the value for usage in step 1b.

chip-tool levelcontrol read on-off-transition-time 1 0
chip-tool levelcontrol write on-off-transition-time 5 1 1
chip-tool levelcontrol read on-level 1 1
chip-tool levelcontrol read default-move-rate 1 1
chip-tool levelcontrol write default-move-rate 5 1 1
chip-tool levelcontrol write start-up-current-level 5  1 1
chip-tool levelcontrol read start-up-current-level 1 1

[[TC-LVL-2.2].txt](https://github.com/project-chip/connectedhomeip/files/7579131/TC-LVL-2.2.txt)

In DUT side there is no response

**Comment by turon** [comment]
All cert tests must pass for v1.
Removing tag `v1_triage_split_4`

**Comment by bzbarsky-apple** [comment]
@kvsmohan Is this an issue on tip?

**Comment by naveenkommareddi** [comment]
Issue resolved per latest test reports

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
