### ISSUE TITLE
[TC-TSTAT-1.1] Value mismatch for FeatureMap attribute

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#12089]
Summary :
As per specification " default value of FeatureMap attribute is 0 but when we made a run the expected value is 11 " however in the test plan it reads the default value 0 as success response

Spec Screenshot: 
![image](https://user-images.githubusercontent.com/84442963/142840593-f8f746c9-55e7-4024-90b7-b4cd485f4ad2.png)

Testplan Screenshot:
![image](https://user-images.githubusercontent.com/84442963/142840478-8d632eff-60b1-45db-bdd1-9263c352b6a0.png)

Execution log :
[TSTAT.txt](https://github.com/project-chip/connectedhomeip/files/7579887/TSTAT.txt)

**Comment by chrisbeach59** [comment]
Feature Map for thermostat is mandatory.  This is an issue with the spec.  I will put up a PR to fix this.  
The thermostat server uses it to know what the thermostat can and can not do.
At this time there is an issue with the generation of Feature map, for little endian machines.  As such there are overrides allowed in thermostat-server.cpp file to set the feature map of the thermostat.

**Comment by chrisbeach59** [comment]
4.3.3.1. Features
This cluster SHALL support the FeatureMap bitmap attribute as defined below.
