### ISSUE TITLE
Attributes mismatch for Content Launcher Cluster AcceptHeader

### ISSUE THREAD

**Issue by xylophone21** [project-chip/connectedhomeip#12091]
#### Problem
 * expected behavior: the type of Content Launcher Cluster -> AcceptHeader should be [list-def][string]
     * https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/49f5a1fb8e73c515233b851500e9c4219eb07c47/src/app_clusters/media/ContentLauncher.adoc#13-attributes
 * actual behavior: the type is   DataModel::List  《 const chip::ByteSpan》 ;
     * https://github.com/project-chip/connectedhomeip/blob/master/zzz_generated/app-common/app-common/zap-generated/cluster-objects.h#L26571    
 >

 #### Proposed Solution
change to DataModel::List 《 const chip::CharSpan》; ?

**Comment by bzbarsky-apple** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/pull/12961
