### ISSUE TITLE
Crash on contentlauncher launch-content linux tv

### ISSUE THREAD

**Issue by xylophone21** [project-chip/connectedhomeip#12131]
#### Problem
* code: 2e16d32966a30146235fca6b873289e2765671d3
* contoller macos M1
   * ./scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool
   * ./out/chip-tool/chip-tool pairing ethernet 112244 20202021 3840 192.168.88.251 5540
   * ./out/chip-tool/chip-tool contentlauncher launch-content 1 abc 112244 
* tvapp on Raspberry Pi 4 
    * ./scripts/examples/gn_build_example.sh examples/tv-app/linux/ out/host/
    * sudo ./out/host/chip-tv-app
* Segmentation fault on side

[RaspberryPi4.log](https://github.com/project-chip/connectedhomeip/files/7585590/RaspberryPi4.log)
[MacBook-Air.log](https://github.com/project-chip/connectedhomeip/files/7585785/MacBook-Air.log)

**Comment by xylophone21** [comment]
Seems it is because responses can not use struct as param. All responses using struct are in todo.

like: src/app/clusters/tv-channel-server/tv-channel-server.cpp

    std::string matchString(match.data(), match.size());
    // TODO: Enable this once struct as param is supported
    // TvChannelInfo channelInfo = tvChannelClusterChangeChannel(matchString);
    // sendResponse(command, channelInfo);
    emberAfSendImmediateDefaultResponse(EMBER_ZCL_STATUS_FAILURE);

**Comment by xylophone21** [comment]
fixed at

https://github.com/project-chip/connectedhomeip/pull/12250

**Comment by lazarkov** [comment]
Fixed
