### ISSUE TITLE
Account Login Cluster mismatch

### ISSUE THREAD

**Issue by xylophone21** [project-chip/connectedhomeip#12156]
#### Problem
 * In spec, the Account Login Cluster has 4 commands ( [CommandId](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/AccountLogin.adoc#14-commands)）
    *  0 - GetSetupPIN Request
    *  1 - GetSetupPIN Response
    *  2 - Login Request
    *  3 - Logout Request
* But in code zzz_generated/app-common/app-common/zap-generated/ids/Commands.h
    * GetSetupPIN CommandId = 0 OK
    * GetSetupPINResponse CommandId = 0 ( should be 1? )
    * Login CommandId = 1 (should be 2?)
    * No Logout CommandId

**Comment by lazarkov** [comment]
The SDK is updated per spec.
