### ISSUE TITLE
TC-SC-4.9 RIO test fails because the second controller on thread network can't commission the DUT.

### ISSUE THREAD

**Issue by wqx6** [project-chip/connectedhomeip#12193]
#### Problem
I used a laptop (disable all ipv4 interfaces) with a Thread RCP connected to the USB port, then started a border router on the laptop, and connected the BR to another BR on RasPi. So that I can start a controller on thread network. The RasPi was connected to an AP which my DUT  is also connected to. However I can't commission my DUT to the controller on thread network. I can't get the mdns services advertised by my DUT on the laptop using 'avahi-browse' commands.

the logs:
[BR1.txt](https://github.com/project-chip/connectedhomeip/files/7593523/BR1.txt)
[BR2.txt](https://github.com/project-chip/connectedhomeip/files/7593526/BR2.txt)
[DUT.txt](https://github.com/project-chip/connectedhomeip/files/7593520/DUT.txt)
[CHIP_TOOL2.txt](https://github.com/project-chip/connectedhomeip/files/7593518/CHIP_TOOL2.txt)
 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by chshu** [comment]
To verify RIO functionality, we added a shell command (#13900) to establish CASESession from a Wi-Fi node to a Thread node. If the CASESession is done, it means the Wi-Fi node has processed the RIO properly.

The Test harness will test RIO in other way, but out of SDK scope.
