### ISSUE TITLE
Missing Zigbee pro service discovery implementation

### ISSUE THREAD

**Issue by bhaskar-apple** [project-chip/connectedhomeip#1219]
#### Problem
Missing Zigbee pro service discovery implementation

 #### Proposed Solution
Port `util/service-discovery-*` set of files.

**Comment by woody-apple** [comment]
SW BRB: Is this needed anymore? @bhaskar-apple @bzbarsky-apple ?

**Comment by rwalker-apple** [comment]
I think this is no longer relevant
