### ISSUE TITLE
[TC-TSUIC-1.1] test-harness does not align with TE7 Excel steps

### ISSUE THREAD

**Issue by jamesharrow** [project-chip/connectedhomeip#12228]
#### Problem
The Excel sheet for TE7 TC-TSUIC-1.1 is different from the actual YAML implementation.

* expected behavior

> Excel sheet has the following:
> Step 2: TH reads all mandatory global attributes from DUT one at a time.
> ./chip-tool thermostat read cluster-revision 1 1

 * actual behavior
 Test harness tries to write to cluster revision, which fails as expected.

> INFO     | 2021-11-24 10:33:44.656 | Executing Test Case: 12.1.1. [TC-TSUIC-1.1] Global attributes with server as DUT
> INFO     | 2021-11-24 10:33:44.660 | Executing Test Step: Starting ChipTool Test
> DEBUG    | 2021-11-24 10:33:44.661 | Parsing 128 lines from chip-tool
> CHIPTOOL | 2021-11-24 10:33:44.663 | [1637749993.301974][87:87] CHIP:CTL: Generating NOC
> CHIPTOOL | 2021-11-24 10:33:44.666 | [1637749993.302345][87:87] CHIP:CTL: Generating ICAC
> CHIPTOOL | 2021-11-24 10:33:44.668 | [1637749993.307624][87:87] CHIP:DL: AUDIT: ===== RANDOM NUMBER GENERATOR AUDIT START ====
> CHIPTOOL | 2021-11-24 10:33:44.670 | [1637749993.307661][87:87] CHIP:DL: AUDIT: * Validate buf1 and buf2 are <<<different every run/boot!>>>
> CHIPTOOL | 2021-11-24 10:33:44.671 | [1637749993.307674][87:87] CHIP:DL: AUDIT: * Validate r1 and r2 are <<<different every run/boot!>>>
> CHIPTOOL | 2021-11-24 10:33:44.673 | [1637749993.307689][87:87] CHIP:DL: AUDIT: * buf1: 344EDE90ADBAB47A772C5089D6FD685F
> CHIPTOOL | 2021-11-24 10:33:44.675 | [1637749993.307701][87:87] CHIP:DL: AUDIT: * buf2: E6523A1EE710DFE8F57D59CF6D381F80
> CHIPTOOL | 2021-11-24 10:33:44.677 | [1637749993.307757][87:87] CHIP:DL: AUDIT: * r1: 0x23619B1C r2: 0x3B81C9F5
> CHIPTOOL | 2021-11-24 10:33:44.679 | [1637749993.307771][87:87] CHIP:DL: AUDIT: ===== RANDOM NUMBER GENERATOR AUDIT END ====
> CHIPTOOL | 2021-11-24 10:33:44.681 | [1637749993.308522][87:87] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-0z6YdN)
> CHIPTOOL | 2021-11-24 10:33:44.683 | [1637749993.309186][87:87] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
> CHIPTOOL | 2021-11-24 10:33:44.684 | [1637749993.309241][87:87] CHIP:DL: NVS set: chip-counters/reboot-count = 8 (0x8)
> CHIPTOOL | 2021-11-24 10:33:44.686 | [1637749993.310170][87:87] CHIP:DL: Got Ethernet interface: eth0
> CHIPTOOL | 2021-11-24 10:33:44.688 | [1637749993.310794][87:87] CHIP:DL: Found the primary Ethernet interface:eth0
> CHIPTOOL | 2021-11-24 10:33:44.689 | [1637749993.311466][87:87] CHIP:DL: Got WiFi interface: wlan0
> CHIPTOOL | 2021-11-24 10:33:44.691 | [1637749993.313734][87:87] CHIP:DL: Found the primary WiFi interface:wlan0
> CHIPTOOL | 2021-11-24 10:33:44.694 | [1637749993.313805][87:87] CHIP:IN: UDP::Init bind&listen port=5541
> CHIPTOOL | 2021-11-24 10:33:44.696 | [1637749993.313916][87:87] CHIP:IN: UDP::Init bound to port=5541
> CHIPTOOL | 2021-11-24 10:33:44.697 | [1637749993.313939][87:87] CHIP:IN: UDP::Init bind&listen port=5541
> CHIPTOOL | 2021-11-24 10:33:44.699 | [1637749993.314026][87:87] CHIP:IN: UDP::Init bound to port=5541
> CHIPTOOL | 2021-11-24 10:33:44.701 | [1637749993.314048][87:87] CHIP:IN: TransportMgr initialized
> CHIPTOOL | 2021-11-24 10:33:44.702 | [1637749993.314107][87:87] CHIP:DIS: Init fabric pairing table with server storage
> CHIPTOOL | 2021-11-24 10:33:44.704 | [1637749993.314595][87:87] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-P7DJWL)
> CHIPTOOL | 2021-11-24 10:33:44.707 | [1637749993.315275][87:87] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
> CHIPTOOL | 2021-11-24 10:33:44.708 | [1637749993.315335][87:87] CHIP:DL: NVS set: chip-counters/GlobalMCTR = 8000 (0x1F40)
> CHIPTOOL | 2021-11-24 10:33:44.710 | [1637749993.315452][87:87] CHIP:CTL: System State Initialized...
> CHIPTOOL | 2021-11-24 10:33:44.712 | [1637749993.318222][87:87] CHIP:DL: MDNS failed to join multicast group on eth0 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
> CHIPTOOL | 2021-11-24 10:33:44.717 | [1637749993.324211][87:87] CHIP:DL: MDNS failed to join multicast group on veth86fefc1 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
> CHIPTOOL | 2021-11-24 10:33:44.719 | [1637749993.326433][87:87] CHIP:DL: MDNS failed to join multicast group on veth1c9144c for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
> CHIPTOOL | 2021-11-24 10:33:44.721 | [1637749993.328537][87:87] CHIP:DL: MDNS failed to join multicast group on veth755ecf6 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
> CHIPTOOL | 2021-11-24 10:33:44.723 | [1637749993.330373][87:87] CHIP:DL: MDNS failed to join multicast group on vethfb0ad7b for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
> CHIPTOOL | 2021-11-24 10:33:44.725 | [1637749993.333160][87:87] CHIP:DL: MDNS failed to join multicast group on wpan0 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
> CHIPTOOL | 2021-11-24 10:33:44.727 | [1637749993.333338][87:87] CHIP:ZCL: Using ZAP configuration...
> CHIPTOOL | 2021-11-24 10:33:44.729 | [1637749993.333976][87:87] CHIP:DIS: Verifying the received credentials
> CHIPTOOL | 2021-11-24 10:33:44.731 | [1637749993.335822][87:87] CHIP:DIS: Added new fabric at index: 1, Initialized: 1
> CHIPTOOL | 2021-11-24 10:33:44.733 | [1637749993.335891][87:87] CHIP:DIS: Assigned compressed fabric ID: 0xB73AD7335717047D, node ID: 0x000000000001B669
> CHIPTOOL | 2021-11-24 10:33:44.734 | [1637749993.335908][87:87] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0xB73AD7335717047D
> CHIPTOOL | 2021-11-24 10:33:44.736 | [1637749993.336237][87:98] CHIP:DL: CHIP task running
> CHIPTOOL | 2021-11-24 10:33:44.739 | [1637749993.337110][87:98] CHIP:IN: Prepared plaintext message 0xaaaafac0de20 to 0x0000000000000000 of type 0x30 and protocolId (0, 0) on exchange 321i with MessageCounter:2241253921.
> CHIPTOOL | 2021-11-24 10:33:44.741 | [1637749993.337170][87:98] CHIP:IN: Sending plaintext msg 0xaaaafac0de20 with MessageCounter:2241253921 to 0x0000000000000000 at monotonic time: 414958 msec
> CHIPTOOL | 2021-11-24 10:33:44.743 | [1637749993.337339][87:98] CHIP:SC: Sent Sigma1 msg
> CHIPTOOL | 2021-11-24 10:33:44.745 | [1637749996.751199][87:98] CHIP:EM: Received message of type 0x31 with protocolId (0, 0) and MessageCounter:3890979423 on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.746 | [1637749996.751303][87:98] CHIP:EM: Rxd Ack; Removing MessageCounter:2241253921 from Retrans Table on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.748 | [1637749996.751332][87:98] CHIP:EM: Removed CHIP MessageCounter:2241253921 from RetransTable on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.749 | [1637749996.751379][87:98] CHIP:SC: Received Sigma2 msg
> CHIPTOOL | 2021-11-24 10:33:44.752 | [1637749996.751420][87:98] CHIP:SC: Peer assigned session session ID 9
> CHIPTOOL | 2021-11-24 10:33:44.754 | [1637749996.757211][87:98] CHIP:SC: Sending Sigma3
> CHIPTOOL | 2021-11-24 10:33:44.756 | [1637749996.757775][87:98] CHIP:EM: Piggybacking Ack for MessageCounter:3890979423 on exchange: 321i
> CHIPTOOL | 2021-11-24 10:33:44.757 | [1637749996.757840][87:98] CHIP:IN: Prepared plaintext message 0xaaaafac0de20 to 0x0000000000000000 of type 0x32 and protocolId (0, 0) on exchange 321i with MessageCounter:2241253922.
> CHIPTOOL | 2021-11-24 10:33:44.760 | [1637749996.757886][87:98] CHIP:IN: Sending plaintext msg 0xaaaafac0de20 with MessageCounter:2241253922 to 0x0000000000000000 at monotonic time: 418378 msec
> CHIPTOOL | 2021-11-24 10:33:44.761 | [1637749996.758085][87:98] CHIP:SC: Sent Sigma3 msg
> CHIPTOOL | 2021-11-24 10:33:44.763 | [1637750001.703534][87:98] CHIP:IN: Sending plaintext msg 0xaaaafac0de20 with MessageCounter:2241253922 to 0x0000000000000000 at monotonic time: 423324 msec
> CHIPTOOL | 2021-11-24 10:33:44.766 | [1637750001.703765][87:98] CHIP:EM: Retransmitted MessageCounter:2241253922 on exchange 321i Send Cnt 1
> CHIPTOOL | 2021-11-24 10:33:44.767 | [1637750001.956317][87:98] CHIP:IN: Sending plaintext msg 0xaaaafac0de20 with MessageCounter:2241253922 to 0x0000000000000000 at monotonic time: 423577 msec
> CHIPTOOL | 2021-11-24 10:33:44.769 | [1637750001.956609][87:98] CHIP:EM: Retransmitted MessageCounter:2241253922 on exchange 321i Send Cnt 2
> CHIPTOOL | 2021-11-24 10:33:44.771 | [1637750002.212115][87:98] CHIP:IN: Sending plaintext msg 0xaaaafac0de20 with MessageCounter:2241253922 to 0x0000000000000000 at monotonic time: 423832 msec
> CHIPTOOL | 2021-11-24 10:33:44.773 | [1637750002.212343][87:98] CHIP:EM: Retransmitted MessageCounter:2241253922 on exchange 321i Send Cnt 3
> CHIPTOOL | 2021-11-24 10:33:44.774 | [1637750002.467866][87:98] CHIP:EM: Failed to Send CHIP MessageCounter:2241253922 on exchange 321i sendCount: 3 max retries: 3
> CHIPTOOL | 2021-11-24 10:33:44.776 | [1637750003.675012][87:98] CHIP:EM: Received message of type 0x40 with protocolId (0, 0) and MessageCounter:3890979424 on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.783 | [1637750003.675117][87:98] CHIP:EM: CHIP MessageCounter:2241253922 not in RetransTable on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.785 | [1637750003.675273][87:98] CHIP:SC: Success status report received. Session was established
> CHIPTOOL | 2021-11-24 10:33:44.787 | [1637750003.675316][87:98] CHIP:IN: New secure session created for device 0x00000000ED107948, key 9!!
> CHIPTOOL | 2021-11-24 10:33:44.789 | [1637750003.675458][87:98] CHIP:TOO:  **** Test Setup: Device Connected
> CHIPTOOL | 2021-11-24 10:33:44.791 | 
> CHIPTOOL | 2021-11-24 10:33:44.792 | [1637750003.675519][87:98] CHIP:TOO:  **** Test Start: Test_TC_TSUIC_1_1
> CHIPTOOL | 2021-11-24 10:33:44.794 | 
> INFO     | 2021-11-24 10:33:44.800 | Test Step Completed [PASSED]: Starting ChipTool Test
> INFO     | 2021-11-24 10:33:44.804 | Executing Test Step: write the default values to mandatory global attribute: ClusterRevision
> CHIPTOOL | 2021-11-24 10:33:44.805 | [1637750003.925664][87:98] CHIP:TOO:  ***** Test Step 0 : write the default values to mandatory global attribute: ClusterRevision
> CHIPTOOL | 2021-11-24 10:33:44.807 | 
> CHIPTOOL | 2021-11-24 10:33:44.809 | [1637750003.925772][87:98] CHIP:DMG: WriteClient moving to [Initialize]
> CHIPTOOL | 2021-11-24 10:33:44.811 | [1637750003.925830][87:98] CHIP:DMG: WriteClient moving to [AddAttribu]
> CHIPTOOL | 2021-11-24 10:33:44.814 | [1637750003.926013][87:98] CHIP:IN: Prepared encrypted message 0xaaaafac0de20 to 0x00000000ED107948 of type 0x6 and protocolId (0, 1) on exchange 322i with MessageCounter:0.
> CHIPTOOL | 2021-11-24 10:33:44.816 | [1637750003.926093][87:98] CHIP:IN: Sending encrypted msg 0xaaaafac0de20 with MessageCounter:0 to 0x00000000ED107948 at monotonic time: 425546 msec
> CHIPTOOL | 2021-11-24 10:33:44.817 | [1637750003.926360][87:98] CHIP:DMG: WriteClient moving to [AwaitingRe]
> CHIPTOOL | 2021-11-24 10:33:44.819 | [1637750003.926419][87:98] CHIP:EM: Sending Standalone Ack for MessageCounter:3890979424 on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.821 | [1637750003.926473][87:98] CHIP:IN: Prepared plaintext message 0xffffb1b12a80 to 0x0000000000000000 of type 0x10 and protocolId (0, 0) on exchange 321i with MessageCounter:2241253923.
> CHIPTOOL | 2021-11-24 10:33:44.822 | [1637750003.926528][87:98] CHIP:IN: Sending plaintext msg 0xffffb1b12a80 with MessageCounter:2241253923 to 0x0000000000000000 at monotonic time: 425547 msec
> CHIPTOOL | 2021-11-24 10:33:44.824 | [1637750003.926694][87:98] CHIP:EM: Flushed pending ack for MessageCounter:3890979424 on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.826 | [1637750003.927052][87:98] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3890979425 on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.829 | [1637750003.927125][87:98] CHIP:EM: OnMessageReceived failed, err = ../../third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:270: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
> CHIPTOOL | 2021-11-24 10:33:44.830 | [1637750003.927425][87:98] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3890979426 on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.832 | [1637750003.927478][87:98] CHIP:EM: OnMessageReceived failed, err = ../../third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:270: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
> CHIPTOOL | 2021-11-24 10:33:44.834 | [1637750003.927690][87:98] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3890979427 on exchange 321i
> CHIPTOOL | 2021-11-24 10:33:44.836 | [1637750003.927742][87:98] CHIP:EM: OnMessageReceived failed, err = ../../third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:270: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
> CHIPTOOL | 2021-11-24 10:33:44.838 | [1637750004.074965][87:98] CHIP:EM: Received message of type 0x7 with protocolId (0, 1) and MessageCounter:1 on exchange 322i
> CHIPTOOL | 2021-11-24 10:33:44.839 | [1637750004.075072][87:98] CHIP:EM: Rxd Ack; Removing MessageCounter:0 from Retrans Table on exchange 322i
> CHIPTOOL | 2021-11-24 10:33:44.842 | [1637750004.075101][87:98] CHIP:EM: Removed CHIP MessageCounter:0 from RetransTable on exchange 322i
> CHIPTOOL | 2021-11-24 10:33:44.844 | [1637750004.075195][87:98] CHIP:DMG: WriteResponse =
> CHIPTOOL | 2021-11-24 10:33:44.849 | [1637750004.075230][87:98] CHIP:DMG: {
> CHIPTOOL | 2021-11-24 10:33:44.850 | [1637750004.075260][87:98] CHIP:DMG: 	AttributeStatusList =
> CHIPTOOL | 2021-11-24 10:33:44.852 | [1637750004.075286][87:98] CHIP:DMG: 	[
> CHIPTOOL | 2021-11-24 10:33:44.853 | [1637750004.075311][87:98] CHIP:DMG: 		AttributeStatusIB =
> CHIPTOOL | 2021-11-24 10:33:44.855 | [1637750004.075337][87:98] CHIP:DMG: 		{
> CHIPTOOL | 2021-11-24 10:33:44.857 | [1637750004.075361][87:98] CHIP:DMG: 			AttributePath =
> CHIPTOOL | 2021-11-24 10:33:44.858 | [1637750004.075388][87:98] CHIP:DMG: 			{
> CHIPTOOL | 2021-11-24 10:33:44.860 | [1637750004.075416][87:98] CHIP:DMG: 				FieldTag = 0x0000_FFFD,
> CHIPTOOL | 2021-11-24 10:33:44.862 | [1637750004.075443][87:98] CHIP:DMG: 				NodeId = 0x0,
> CHIPTOOL | 2021-11-24 10:33:44.863 | [1637750004.075469][87:98] CHIP:DMG: 				ClusterId = 0x204,
> CHIPTOOL | 2021-11-24 10:33:44.865 | [1637750004.075493][87:98] CHIP:DMG: 				EndpointId = 0x1,
> CHIPTOOL | 2021-11-24 10:33:44.866 | [1637750004.075515][87:98] CHIP:DMG: 			}
> CHIPTOOL | 2021-11-24 10:33:44.868 | [1637750004.075548][87:98] CHIP:DMG: 				
> CHIPTOOL | 2021-11-24 10:33:44.870 | [1637750004.075572][87:98] CHIP:DMG: 			StatusIB =
> CHIPTOOL | 2021-11-24 10:33:44.872 | [1637750004.075595][87:98] CHIP:DMG: 			{
> CHIPTOOL | 2021-11-24 10:33:44.874 | [1637750004.075619][87:98] CHIP:DMG: 				status = 0x88,
> CHIPTOOL | 2021-11-24 10:33:44.876 | [1637750004.075640][87:98] CHIP:DMG: 			},
> CHIPTOOL | 2021-11-24 10:33:44.878 | [1637750004.075665][87:98] CHIP:DMG: 			
> CHIPTOOL | 2021-11-24 10:33:44.879 | [1637750004.075690][87:98] CHIP:DMG: 		},
> CHIPTOOL | 2021-11-24 10:33:44.881 | [1637750004.075721][87:98] CHIP:DMG: 		
> CHIPTOOL | 2021-11-24 10:33:44.883 | [1637750004.075743][87:98] CHIP:DMG: 	],
> CHIPTOOL | 2021-11-24 10:33:44.884 | [1637750004.075776][87:98] CHIP:DMG: 	
> CHIPTOOL | 2021-11-24 10:33:44.885 | [1637750004.075799][87:98] CHIP:DMG: }
> CHIPTOOL | 2021-11-24 10:33:44.887 | [1637750004.075874][87:98] CHIP:ZCL: WriteResponse:
> CHIPTOOL | 2021-11-24 10:33:44.889 | [1637750004.075913][87:98] CHIP:ZCL:   status: UnsupportedWrite       (0x0088)
> CHIPTOOL | 2021-11-24 10:33:44.892 | [1637750004.075944][87:98] CHIP:TOO:  **** Test Complete: Test_TC_TSUIC_1_1
> CHIPTOOL | 2021-11-24 10:33:44.893 | 
> CHIPTOOL | 2021-11-24 10:33:44.896 | [1637750004.076015][87:98] CHIP:DMG: WriteClient moving to [Uninitiali]
> CHIPTOOL | 2021-11-24 10:33:44.898 | [1637750004.076062][87:98] CHIP:EM: Sending Standalone Ack for MessageCounter:1 on exchange 322i
> CHIPTOOL | 2021-11-24 10:33:44.899 | [1637750004.076147][87:98] CHIP:IN: Prepared encrypted message 0xffffb1b12a50 to 0x00000000ED107948 of type 0x10 and protocolId (0, 0) on exchange 322i with MessageCounter:1.
> CHIPTOOL | 2021-11-24 10:33:44.901 | [1637750004.076192][87:98] CHIP:IN: Sending encrypted msg 0xffffb1b12a50 with MessageCounter:1 to 0x00000000ED107948 at monotonic time: 425697 msec
> CHIPTOOL | 2021-11-24 10:33:44.903 | [1637750004.076397][87:98] CHIP:EM: Flushed pending ack for MessageCounter:1 on exchange 322i
> CHIPTOOL | 2021-11-24 10:33:44.907 | [1637750004.076803][87:87] CHIP:CTL: Shutting down the commissioner
> CHIPTOOL | 2021-11-24 10:33:44.909 | [1637750004.076907][87:87] CHIP:CTL: Shutting down the controller
> CHIPTOOL | 2021-11-24 10:33:44.912 | [1637750004.079584][87:87] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
> CHIPTOOL | 2021-11-24 10:33:44.915 | [1637750004.080186][87:87] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-f96uMK)
> CHIPTOOL | 2021-11-24 10:33:44.917 | [1637750004.081162][87:87] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
> CHIPTOOL | 2021-11-24 10:33:44.919 | [1637750004.081249][87:87] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
> CHIPTOOL | 2021-11-24 10:33:44.920 | [1637750004.081281][87:87] CHIP:DL: Inet Layer shutdown
> CHIPTOOL | 2021-11-24 10:33:44.922 | [1637750004.081415][87:87] CHIP:DL: BLE layer shutdown
> CHIPTOOL | 2021-11-24 10:33:44.923 | [1637750004.081453][87:87] CHIP:DL: System Layer shutdown
> INFO     | 2021-11-24 10:33:44.927 | Test Step Completed [PASSED]: write the default values to mandatory global attribute: ClusterRevision
> INFO     | 2021-11-24 10:33:44.928 | This is a test case cleanup
> INFO     | 2021-11-24 10:33:44.931 | Test Case Completed[PASSED]: 12.1.1. [TC-TSUIC-1.1] Global attributes with server as DUT
> 

 #### Proposed Solution
Excel sheet is wrong since it is reading the thermostat cluster.
This should be ./chip-tool **thermostatuserinterfaceconfiguration** read cluster-revision 1 1

Test case YAML should be reviewed if the Excel is the master.
https://github.com/project-chip/connectedhomeip/blob/test_event_7.lts/src/app/tests/suites/certification/Test_TC_TSUIC_1_1.yaml

Similar to #12225

**Comment by franck-apple** [comment]
Please file this issue in the Test Harness repo. Closing it here.
