### ISSUE TITLE
[TC-TSTAT-1.1] test-harness does not align with TE7 Excel steps

### ISSUE THREAD

**Issue by jamesharrow** [project-chip/connectedhomeip#12225]
#### Problem
The Excel sheet for TE7 TC-TSTAT-1.1 is different from the actual YAML implementation.

 * expected behavior
Excel sheet has the following:

> Step 2: TH reads all mandatory global attributes from DUT one at a time.
> `./chip-tool thermostat read cluster-revision 1 1`
> 
> `: ReadAttributesResponse:
> CHIP:ZCL:   ClusterId: 0x0000_0201
> CHIP:ZCL:   attributeId: 0x0000_FFFD
> CHIP:ZCL:   status: Success                (0x0000)
> CHIP:ZCL:   attribute TLV Type: 0x04
> CHIP:TOO: Int16u attribute Response: 3`
> 
> Step 3: TH writes the respective default value to all mandatory global attributes to DUT one at a time.
> If the access control of DUT is set to READ, the DUT response will indicate that the attribute write command was not a SUCCESS. If the access control of DUT is set to READ/WRITE, the DUT response will indicate that the write command was a SUCCESS.
> - Will always return an error

 * actual behavior
It doesn't implement step 2, and jumps straight to step 3.

> INFO     | 2021-11-24 10:33:24.570 | Executing Test Case: 42.1.1. [TC-TSTAT-1.1] Global attributes with server as DUT
INFO     | 2021-11-24 10:33:24.574 | Executing Test Step: Starting ChipTool Test
DEBUG    | 2021-11-24 10:33:24.576 | Parsing 128 lines from chip-tool
CHIPTOOL | 2021-11-24 10:33:24.578 | [1637749981.483326][76:76] CHIP:CTL: Generating NOC
CHIPTOOL | 2021-11-24 10:33:24.580 | [1637749981.483691][76:76] CHIP:CTL: Generating ICAC
CHIPTOOL | 2021-11-24 10:33:24.582 | [1637749981.488914][76:76] CHIP:DL: AUDIT: ===== RANDOM NUMBER GENERATOR AUDIT START ====
CHIPTOOL | 2021-11-24 10:33:24.585 | [1637749981.488956][76:76] CHIP:DL: AUDIT: * Validate buf1 and buf2 are <<<different every run/boot!>>>
CHIPTOOL | 2021-11-24 10:33:24.587 | [1637749981.488968][76:76] CHIP:DL: AUDIT: * Validate r1 and r2 are <<<different every run/boot!>>>
CHIPTOOL | 2021-11-24 10:33:24.589 | [1637749981.488982][76:76] CHIP:DL: AUDIT: * buf1: 584C4D91B68589290B186503E03168C0
CHIPTOOL | 2021-11-24 10:33:24.591 | [1637749981.488994][76:76] CHIP:DL: AUDIT: * buf2: 09E8EB02AFC97100EA1A428FC6705982
CHIPTOOL | 2021-11-24 10:33:24.593 | [1637749981.489055][76:76] CHIP:DL: AUDIT: * r1: 0x7D020482 r2: 0x99A9688A
CHIPTOOL | 2021-11-24 10:33:24.594 | [1637749981.489069][76:76] CHIP:DL: AUDIT: ===== RANDOM NUMBER GENERATOR AUDIT END ====
CHIPTOOL | 2021-11-24 10:33:24.596 | [1637749981.489818][76:76] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-pdls8X)
CHIPTOOL | 2021-11-24 10:33:24.599 | [1637749981.490490][76:76] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
CHIPTOOL | 2021-11-24 10:33:24.601 | [1637749981.490547][76:76] CHIP:DL: NVS set: chip-counters/reboot-count = 7 (0x7)
CHIPTOOL | 2021-11-24 10:33:24.603 | [1637749981.491518][76:76] CHIP:DL: Got Ethernet interface: eth0
CHIPTOOL | 2021-11-24 10:33:24.605 | [1637749981.492150][76:76] CHIP:DL: Found the primary Ethernet interface:eth0
CHIPTOOL | 2021-11-24 10:33:24.607 | [1637749981.492782][76:76] CHIP:DL: Got WiFi interface: wlan0
CHIPTOOL | 2021-11-24 10:33:24.609 | [1637749981.495200][76:76] CHIP:DL: Found the primary WiFi interface:wlan0
CHIPTOOL | 2021-11-24 10:33:24.610 | [1637749981.495283][76:76] CHIP:IN: UDP::Init bind&listen port=5541
CHIPTOOL | 2021-11-24 10:33:24.612 | [1637749981.495414][76:76] CHIP:IN: UDP::Init bound to port=5541
CHIPTOOL | 2021-11-24 10:33:24.615 | [1637749981.495436][76:76] CHIP:IN: UDP::Init bind&listen port=5541
CHIPTOOL | 2021-11-24 10:33:24.616 | [1637749981.495541][76:76] CHIP:IN: UDP::Init bound to port=5541
CHIPTOOL | 2021-11-24 10:33:24.618 | [1637749981.495569][76:76] CHIP:IN: TransportMgr initialized
CHIPTOOL | 2021-11-24 10:33:24.620 | [1637749981.495638][76:76] CHIP:DIS: Init fabric pairing table with server storage
CHIPTOOL | 2021-11-24 10:33:24.621 | [1637749981.496197][76:76] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-jCbyNV)
CHIPTOOL | 2021-11-24 10:33:24.623 | [1637749981.496947][76:76] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
CHIPTOOL | 2021-11-24 10:33:24.625 | [1637749981.497013][76:76] CHIP:DL: NVS set: chip-counters/GlobalMCTR = 7000 (0x1B58)
CHIPTOOL | 2021-11-24 10:33:24.627 | [1637749981.497152][76:76] CHIP:CTL: System State Initialized...
CHIPTOOL | 2021-11-24 10:33:24.629 | [1637749981.500096][76:76] CHIP:DL: MDNS failed to join multicast group on eth0 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
CHIPTOOL | 2021-11-24 10:33:24.634 | [1637749981.506031][76:76] CHIP:DL: MDNS failed to join multicast group on veth86fefc1 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
CHIPTOOL | 2021-11-24 10:33:24.636 | [1637749981.508024][76:76] CHIP:DL: MDNS failed to join multicast group on veth1c9144c for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
CHIPTOOL | 2021-11-24 10:33:24.637 | [1637749981.509974][76:76] CHIP:DL: MDNS failed to join multicast group on veth755ecf6 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
CHIPTOOL | 2021-11-24 10:33:24.639 | [1637749981.512021][76:76] CHIP:DL: MDNS failed to join multicast group on vethfb0ad7b for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
CHIPTOOL | 2021-11-24 10:33:24.641 | [1637749981.514870][76:76] CHIP:DL: MDNS failed to join multicast group on wpan0 for address type IPv4: ../../third_party/connectedhomeip/src/inet/IPEndPointBasis.cpp:387: Inet Error 0x00000110: Address not found
CHIPTOOL | 2021-11-24 10:33:24.645 | [1637749981.515508][76:76] CHIP:ZCL: Using ZAP configuration...
CHIPTOOL | 2021-11-24 10:33:24.646 | [1637749981.516170][76:76] CHIP:DIS: Verifying the received credentials
CHIPTOOL | 2021-11-24 10:33:24.648 | [1637749981.518081][76:76] CHIP:DIS: Added new fabric at index: 1, Initialized: 1
CHIPTOOL | 2021-11-24 10:33:24.650 | [1637749981.518115][76:76] CHIP:DIS: Assigned compressed fabric ID: 0xB73AD7335717047D, node ID: 0x000000000001B669
CHIPTOOL | 2021-11-24 10:33:24.652 | [1637749981.518129][76:76] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0xB73AD7335717047D
CHIPTOOL | 2021-11-24 10:33:24.654 | [1637749981.518461][76:86] CHIP:DL: CHIP task running
CHIPTOOL | 2021-11-24 10:33:24.655 | [1637749981.519368][76:86] CHIP:IN: Prepared plaintext message 0xaaab09b40e20 to 0x0000000000000000 of type 0x30 and protocolId (0, 0) on exchange 53046i with MessageCounter:1750895786.
CHIPTOOL | 2021-11-24 10:33:24.657 | [1637749981.519423][76:86] CHIP:IN: Sending plaintext msg 0xaaab09b40e20 with MessageCounter:1750895786 to 0x0000000000000000 at monotonic time: 403140 msec
CHIPTOOL | 2021-11-24 10:33:24.659 | [1637749981.519592][76:86] CHIP:SC: Sent Sigma1 msg
CHIPTOOL | 2021-11-24 10:33:24.661 | [1637749984.884958][76:86] CHIP:EM: Received message of type 0x31 with protocolId (0, 0) and MessageCounter:3890979418 on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.662 | [1637749984.885073][76:86] CHIP:EM: Rxd Ack; Removing MessageCounter:1750895786 from Retrans Table on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.664 | [1637749984.885105][76:86] CHIP:EM: Removed CHIP MessageCounter:1750895786 from RetransTable on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.668 | [1637749984.885157][76:86] CHIP:SC: Received Sigma2 msg
CHIPTOOL | 2021-11-24 10:33:24.669 | [1637749984.885203][76:86] CHIP:SC: Peer assigned session session ID 8
CHIPTOOL | 2021-11-24 10:33:24.670 | [1637749984.891680][76:86] CHIP:SC: Sending Sigma3
CHIPTOOL | 2021-11-24 10:33:24.672 | [1637749984.892388][76:86] CHIP:EM: Piggybacking Ack for MessageCounter:3890979418 on exchange: 53046i
CHIPTOOL | 2021-11-24 10:33:24.674 | [1637749984.892466][76:86] CHIP:IN: Prepared plaintext message 0xaaab09b40e20 to 0x0000000000000000 of type 0x32 and protocolId (0, 0) on exchange 53046i with MessageCounter:1750895787.
CHIPTOOL | 2021-11-24 10:33:24.675 | [1637749984.892521][76:86] CHIP:IN: Sending plaintext msg 0xaaab09b40e20 with MessageCounter:1750895787 to 0x0000000000000000 at monotonic time: 406513 msec
CHIPTOOL | 2021-11-24 10:33:24.677 | [1637749984.892750][76:86] CHIP:SC: Sent Sigma3 msg
CHIPTOOL | 2021-11-24 10:33:24.679 | [1637749989.885256][76:86] CHIP:IN: Sending plaintext msg 0xaaab09b40e20 with MessageCounter:1750895787 to 0x0000000000000000 at monotonic time: 411506 msec
CHIPTOOL | 2021-11-24 10:33:24.680 | [1637749989.885540][76:86] CHIP:EM: Retransmitted MessageCounter:1750895787 on exchange 53046i Send Cnt 1
CHIPTOOL | 2021-11-24 10:33:24.682 | [1637749990.138186][76:86] CHIP:IN: Sending plaintext msg 0xaaab09b40e20 with MessageCounter:1750895787 to 0x0000000000000000 at monotonic time: 411759 msec
CHIPTOOL | 2021-11-24 10:33:24.685 | [1637749990.138462][76:86] CHIP:EM: Retransmitted MessageCounter:1750895787 on exchange 53046i Send Cnt 2
CHIPTOOL | 2021-11-24 10:33:24.686 | [1637749990.394373][76:86] CHIP:IN: Sending plaintext msg 0xaaab09b40e20 with MessageCounter:1750895787 to 0x0000000000000000 at monotonic time: 412015 msec
CHIPTOOL | 2021-11-24 10:33:24.688 | [1637749990.394630][76:86] CHIP:EM: Retransmitted MessageCounter:1750895787 on exchange 53046i Send Cnt 3
CHIPTOOL | 2021-11-24 10:33:24.689 | [1637749990.650180][76:86] CHIP:EM: Failed to Send CHIP MessageCounter:1750895787 on exchange 53046i sendCount: 3 max retries: 3
CHIPTOOL | 2021-11-24 10:33:24.690 | [1637749991.735588][76:86] CHIP:EM: Received message of type 0x40 with protocolId (0, 0) and MessageCounter:3890979419 on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.698 | [1637749991.735686][76:86] CHIP:EM: CHIP MessageCounter:1750895787 not in RetransTable on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.700 | [1637749991.735765][76:86] CHIP:SC: Success status report received. Session was established
CHIPTOOL | 2021-11-24 10:33:24.701 | [1637749991.735809][76:86] CHIP:IN: New secure session created for device 0x00000000ED107948, key 8!!
CHIPTOOL | 2021-11-24 10:33:24.704 | [1637749991.735952][76:86] CHIP:TOO:  **** Test Setup: Device Connected
CHIPTOOL | 2021-11-24 10:33:24.705 | 
CHIPTOOL | 2021-11-24 10:33:24.707 | [1637749991.735997][76:86] CHIP:TOO:  **** Test Start: Test_TC_TSTAT_1_1
CHIPTOOL | 2021-11-24 10:33:24.708 | 
INFO     | 2021-11-24 10:33:24.711 | Test Step Completed [PASSED]: Starting ChipTool Test
INFO     | 2021-11-24 10:33:24.713 | Executing Test Step: write the default values to mandatory global attribute: ClusterRevision
CHIPTOOL | 2021-11-24 10:33:24.716 | [1637749991.986164][76:86] CHIP:TOO:  ***** Test Step 0 : write the default values to mandatory global attribute: ClusterRevision
CHIPTOOL | 2021-11-24 10:33:24.717 | 
CHIPTOOL | 2021-11-24 10:33:24.719 | [1637749991.986268][76:86] CHIP:DMG: WriteClient moving to [Initialize]
CHIPTOOL | 2021-11-24 10:33:24.720 | [1637749991.986325][76:86] CHIP:DMG: WriteClient moving to [AddAttribu]
CHIPTOOL | 2021-11-24 10:33:24.722 | [1637749991.986512][76:86] CHIP:IN: Prepared encrypted message 0xaaab09b40e20 to 0x00000000ED107948 of type 0x6 and protocolId (0, 1) on exchange 53047i with MessageCounter:0.
CHIPTOOL | 2021-11-24 10:33:24.723 | [1637749991.986816][76:86] CHIP:IN: Sending encrypted msg 0xaaab09b40e20 with MessageCounter:0 to 0x00000000ED107948 at monotonic time: 413607 msec
CHIPTOOL | 2021-11-24 10:33:24.725 | [1637749991.987333][76:86] CHIP:DMG: WriteClient moving to [AwaitingRe]
CHIPTOOL | 2021-11-24 10:33:24.727 | [1637749991.987605][76:86] CHIP:EM: Sending Standalone Ack for MessageCounter:3890979419 on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.728 | [1637749991.987852][76:86] CHIP:IN: Prepared plaintext message 0xffff8affba80 to 0x0000000000000000 of type 0x10 and protocolId (0, 0) on exchange 53046i with MessageCounter:1750895788.
CHIPTOOL | 2021-11-24 10:33:24.729 | [1637749991.988106][76:86] CHIP:IN: Sending plaintext msg 0xffff8affba80 with MessageCounter:1750895788 to 0x0000000000000000 at monotonic time: 413608 msec
CHIPTOOL | 2021-11-24 10:33:24.731 | [1637749991.988484][76:86] CHIP:EM: Flushed pending ack for MessageCounter:3890979419 on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.732 | [1637749991.988867][76:86] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3890979420 on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.734 | [1637749991.988952][76:86] CHIP:EM: OnMessageReceived failed, err = ../../third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:270: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
CHIPTOOL | 2021-11-24 10:33:24.735 | [1637749991.989182][76:86] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3890979421 on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.737 | [1637749991.989254][76:86] CHIP:EM: OnMessageReceived failed, err = ../../third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:270: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
CHIPTOOL | 2021-11-24 10:33:24.739 | [1637749991.989470][76:86] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:3890979422 on exchange 53046i
CHIPTOOL | 2021-11-24 10:33:24.740 | [1637749991.989541][76:86] CHIP:EM: OnMessageReceived failed, err = ../../third_party/connectedhomeip/src/messaging/ExchangeMgr.cpp:270: CHIP Error 0x00000070: Unsolicited msg with originator bit clear
CHIPTOOL | 2021-11-24 10:33:24.742 | [1637749992.137612][76:86] CHIP:EM: Received message of type 0x7 with protocolId (0, 1) and MessageCounter:1 on exchange 53047i
CHIPTOOL | 2021-11-24 10:33:24.743 | [1637749992.137739][76:86] CHIP:EM: Rxd Ack; Removing MessageCounter:0 from Retrans Table on exchange 53047i
CHIPTOOL | 2021-11-24 10:33:24.745 | [1637749992.137780][76:86] CHIP:EM: Removed CHIP MessageCounter:0 from RetransTable on exchange 53047i
CHIPTOOL | 2021-11-24 10:33:24.746 | [1637749992.137853][76:86] CHIP:DMG: WriteResponse =
CHIPTOOL | 2021-11-24 10:33:24.755 | [1637749992.137893][76:86] CHIP:DMG: {
CHIPTOOL | 2021-11-24 10:33:24.757 | [1637749992.137925][76:86] CHIP:DMG: 	AttributeStatusList =
CHIPTOOL | 2021-11-24 10:33:24.759 | [1637749992.137969][76:86] CHIP:DMG: 	[
CHIPTOOL | 2021-11-24 10:33:24.760 | [1637749992.138001][76:86] CHIP:DMG: 		AttributeStatusIB =
CHIPTOOL | 2021-11-24 10:33:24.762 | [1637749992.138037][76:86] CHIP:DMG: 		{
CHIPTOOL | 2021-11-24 10:33:24.763 | [1637749992.138069][76:86] CHIP:DMG: 			AttributePath =
CHIPTOOL | 2021-11-24 10:33:24.765 | [1637749992.138106][76:86] CHIP:DMG: 			{
CHIPTOOL | 2021-11-24 10:33:24.766 | [1637749992.138146][76:86] CHIP:DMG: 				FieldTag = 0x0000_FFFD,
CHIPTOOL | 2021-11-24 10:33:24.769 | [1637749992.138184][76:86] CHIP:DMG: 				NodeId = 0x0,
CHIPTOOL | 2021-11-24 10:33:24.771 | [1637749992.138221][76:86] CHIP:DMG: 				ClusterId = 0x201,
CHIPTOOL | 2021-11-24 10:33:24.773 | [1637749992.138257][76:86] CHIP:DMG: 				EndpointId = 0x1,
CHIPTOOL | 2021-11-24 10:33:24.775 | [1637749992.138292][76:86] CHIP:DMG: 			}
CHIPTOOL | 2021-11-24 10:33:24.777 | [1637749992.138336][76:86] CHIP:DMG: 				
CHIPTOOL | 2021-11-24 10:33:24.778 | [1637749992.138369][76:86] CHIP:DMG: 			StatusIB =
CHIPTOOL | 2021-11-24 10:33:24.779 | [1637749992.138404][76:86] CHIP:DMG: 			{
CHIPTOOL | 2021-11-24 10:33:24.782 | [1637749992.138439][76:86] CHIP:DMG: 				status = 0x88,
CHIPTOOL | 2021-11-24 10:33:24.783 | [1637749992.138470][76:86] CHIP:DMG: 			},
CHIPTOOL | 2021-11-24 10:33:24.785 | [1637749992.138508][76:86] CHIP:DMG: 			
CHIPTOOL | 2021-11-24 10:33:24.786 | [1637749992.138540][76:86] CHIP:DMG: 		},
CHIPTOOL | 2021-11-24 10:33:24.788 | [1637749992.138585][76:86] CHIP:DMG: 		
CHIPTOOL | 2021-11-24 10:33:24.789 | [1637749992.138616][76:86] CHIP:DMG: 	],
CHIPTOOL | 2021-11-24 10:33:24.791 | [1637749992.138659][76:86] CHIP:DMG: 	
CHIPTOOL | 2021-11-24 10:33:24.793 | [1637749992.138689][76:86] CHIP:DMG: }
CHIPTOOL | 2021-11-24 10:33:24.795 | [1637749992.138780][76:86] CHIP:ZCL: WriteResponse:
CHIPTOOL | 2021-11-24 10:33:24.798 | [1637749992.138830][76:86] CHIP:ZCL:   status: UnsupportedWrite       (0x0088)
CHIPTOOL | 2021-11-24 10:33:24.800 | [1637749992.138871][76:86] CHIP:TOO:  **** Test Complete: Test_TC_TSTAT_1_1
CHIPTOOL | 2021-11-24 10:33:24.806 | 
CHIPTOOL | 2021-11-24 10:33:24.808 | [1637749992.138961][76:86] CHIP:DMG: WriteClient moving to [Uninitiali]
CHIPTOOL | 2021-11-24 10:33:24.809 | [1637749992.139018][76:86] CHIP:EM: Sending Standalone Ack for MessageCounter:1 on exchange 53047i
CHIPTOOL | 2021-11-24 10:33:24.813 | [1637749992.139114][76:86] CHIP:IN: Prepared encrypted message 0xffff8affba50 to 0x00000000ED107948 of type 0x10 and protocolId (0, 0) on exchange 53047i with MessageCounter:1.
CHIPTOOL | 2021-11-24 10:33:24.815 | [1637749992.139237][76:86] CHIP:IN: Sending encrypted msg 0xffff8affba50 with MessageCounter:1 to 0x00000000ED107948 at monotonic time: 413760 msec
CHIPTOOL | 2021-11-24 10:33:24.816 | [1637749992.139496][76:86] CHIP:EM: Flushed pending ack for MessageCounter:1 on exchange 53047i
CHIPTOOL | 2021-11-24 10:33:24.820 | [1637749992.139909][76:76] CHIP:CTL: Shutting down the commissioner
CHIPTOOL | 2021-11-24 10:33:24.821 | [1637749992.139970][76:76] CHIP:CTL: Shutting down the controller
CHIPTOOL | 2021-11-24 10:33:24.823 | [1637749992.143117][76:76] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
CHIPTOOL | 2021-11-24 10:33:24.824 | [1637749992.143821][76:76] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-dMcZdV)
CHIPTOOL | 2021-11-24 10:33:24.826 | [1637749992.145058][76:76] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
CHIPTOOL | 2021-11-24 10:33:24.828 | [1637749992.145170][76:76] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
CHIPTOOL | 2021-11-24 10:33:24.829 | [1637749992.145218][76:76] CHIP:DL: Inet Layer shutdown
CHIPTOOL | 2021-11-24 10:33:24.831 | [1637749992.145390][76:76] CHIP:DL: BLE layer shutdown
CHIPTOOL | 2021-11-24 10:33:24.833 | [1637749992.145440][76:76] CHIP:DL: System Layer shutdown
INFO     | 2021-11-24 10:33:24.835 | Test Step Completed [PASSED]: write the default values to mandatory global attribute: ClusterRevision
INFO     | 2021-11-24 10:33:24.836 | This is a test case cleanup
INFO     | 2021-11-24 10:33:24.839 | Test Case Completed[PASSED]: 42.1.1. [TC-TSTAT-1.1] Global attributes with server as DUT

 #### Proposed Solution
Determine which is correct (Excel or Test Case) and amend appropriately.
See https://github.com/project-chip/connectedhomeip/blob/test_event_7.lts/src/app/tests/suites/certification/Test_TC_TSTAT_1_1.yaml

**Comment by franck-apple** [comment]
Please file this issue in the Test Harness repo. Closing it here.
