### ISSUE TITLE
Segmentation fault on app commission timeout. 

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#12331]
#### Problem
When attempting to commission with chip-tool and the commission times out, the app hits a segmentation fault. 

[seg_fault_timeout.txt](https://github.com/project-chip/connectedhomeip/files/7620738/seg_fault_timeout.txt)

**Comment by tcarmelveilleux** [comment]
@krypton36 Is this still reproducible with latest code?

**Comment by tcarmelveilleux** [comment]
Reported by @krypton36 to no longer happen
