### ISSUE TITLE
FeatureMap default value not to be 0

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#12452]
Summary:
              As per spec the default value of  FeatureMap is 0 but FeatureMap exits to express the capabilities of a device and the data type for the attribute is map32, so the default should not be 0.

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/144372709-1b7da2ee-0486-4c6e-911b-d74549edf2dc.png)

**Comment by yufengwangca** [comment]
I think the default value for the FeatureMap is cluster dependent and get set by each cluster

**Comment by yufengwangca** [comment]
@manjunathambiger23 
is this the spec issue or sdk issue?

**Comment by manjunathambiger23** [comment]
@yufengwangca its spec related issue

**Comment by woody-apple** [comment]
@manjunathambiger23 Can you please file this against the spec?
