### ISSUE TITLE
Support list index in read response

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#12649]
#### Problem

We only supports Replace All (no list index) and Append (null list index) in read response, need to support other list operations in interfaction model & buffered read handler etc.

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by mrjerryjohns** [comment]
Unlikely we'll support this for v1.0.

**Comment by turon** [comment]
Removed tag `v1_triage_split_4`
