### ISSUE TITLE
Update (or small refactor) to AttributeValueEncoder

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#12650]
#### Problem

The AttributeValueEncoder is used for encode the attribute value field in attribute data ib. However, to support features like list chunking, it has to support encode a whole report ib instead of a single field.

This should probably taken place after #12053 

 #### Proposed Solution

Some changes need to be discussed:

- [ ] Field (names) in `AttributeValueEncoder::AttributeEncodeState`
- [ ] `mPath.mListOp` in EncodeList

**Comment by erjiaqing** [comment]
The new title is not accurate (and even made me confused -- list chunking should be supported by AttributeValueEncoder), this should be a refactor and is not related to spec.

**Comment by bzbarsky-apple** [comment]
@erjiaqing I think this issue could benefit from a clearer description of what the problem is, but I agree this is not a spec issue and not a 1.0 issue.
