### ISSUE TITLE
Run the "npm ci" command in the third_party/zap/repo folder to report an error

### ISSUE THREAD

**Issue by ChengqiangShe** [project-chip/connectedhomeip#12714]
#### Problem : Run the "npm ci" command in the third_party/zap/repo folder to report an error
platform：Ubuntu 20.04.2 LTS
commit 186c004a1838db829811cec7d70844e3c00379b8

`> macos-alias@0.2.11 install /home/chengqiang/work/connectedhomeip/third_party/zap/repo/node_modules/macos-alias
> node-gyp rebuild

make: Entering directory '/home/chengqiang/work/connectedhomeip/third_party/zap/repo/node_modules/macos-alias/build'
  CXX(target) Release/obj.target/volume/src/volume.o
../src/volume.cc:9:2: error: #error This platform is not implemented yet
    9 | #error This platform is not implemented yet
      |  ^~~~~
In file included from ../src/volume.cc:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/volume.cc: In function ‘void Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/volume.cc:16:49: error: ‘MethodGetVolumeName’ was not declared in this scope
   16 |     Nan::GetFunction(Nan::New<FunctionTemplate>(MethodGetVolumeName)).ToLocalChecked());
      |                                                 ^~~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan.h:54,
                 from ../src/volume.cc:2:
../src/volume.cc: At global scope:
/usr/include/nodejs/src/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  573 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/usr/include/nodejs/src/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
  607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/volume.cc:19:1: note: in expansion of macro ‘NODE_MODULE’
   19 | NODE_MODULE(volume, Initialize)
      | ^~~~~~~~~~~
In file included from /usr/include/nodejs/src/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../src/volume.cc:2:
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/usr/include/nodejs/src/node_object_wrap.h:84:78:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [volume.target.mk:103: Release/obj.target/volume/src/volume.o] Error 1
make: Leaving directory '/home/chengqiang/work/connectedhomeip/third_party/zap/repo/node_modules/macos-alias/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.11.0-41-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/chengqiang/work/connectedhomeip/third_party/zap/repo/node_modules/macos-alias
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

> electron@12.2.2 postinstall /home/chengqiang/work/connectedhomeip/third_party/zap/repo/node_modules/electron
> node install.js

RequestError: connect ENETUNREACH 192.30.255.112:443 - Local (0.0.0.0:0)
    at ClientRequest.request.once.error (/home/chengqiang/work/connectedhomeip/third_party/zap/repo/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args (/home/chengqiang/work/connectedhomeip/third_party/zap/repo/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@12.2.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@12.2.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chengqiang/.npm/_logs/2021-12-08T06_17_59_163Z-debug.log
`

**Comment by woody-apple** [comment]
I just ran these on ubuntu 20, can you confirm this is working for you?

```
cd third_party/zap/repo/                                                                                                                                                                 terafin@ubuntu
                npm ci
                npm run version-stamp
                npm rebuild canvas --update-binary
                npm run build-spa
```
