### ISSUE TITLE
Set up integration/functional tests for CHIP

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1273]
#### Problem
Tests  should be available for end-to-end functionality.
#1207 brought up the Happy test framework, which is suitable for running complex ip tests on a single network.

 #### Proposed Solution
Port happy (or suggest alternative), add some end to end tests.

**Comment by yunhanw-google** [comment]
I have validated happy in github action, and I have upgrade happy with python3 support. We should be good to go with TestInetLayerMulticast. 
@gerickson I'd start with the ones that drive TestInetLayer{Multicast}, are you working on this? If not, @erjiaqing should be able to do this.
thanks

**Comment by erjiaqing** [comment]
Happy is already setup, follow up #3214
