### ISSUE TITLE
TestGroupMessaging testcase seems to be failing

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#12779]
Summary:
                TestGroupMessaging testcase seems to be failing when executing YAML test cases,the test executes fine when we disable the test step in line #37 

Yaml files screenshot: 
![GM_yaml](https://user-images.githubusercontent.com/84442963/145350495-501a49a5-d2d4-4f81-8bda-396bddadbc2a.png)

Test cases fail screenshot and log :
![TMG_ERR](https://user-images.githubusercontent.com/84442963/145350558-b3223108-d9e0-4d61-943d-2c8ebe2ea53f.png)
[Build_fail.txt](https://github.com/project-chip/connectedhomeip/files/7682946/Build_fail.txt)

PR zap templets generation fail screenshot:
![Zap_Err](https://user-images.githubusercontent.com/84442963/145350883-80acd652-2ea3-4b47-bbdf-a9898e42b2ab.png)
PR link: https://github.com/project-chip/connectedhomeip/pull/12771

**Comment by franck-apple** [comment]
Is this still relevant? @rcasallas-silabs @manjunathambiger23 ?
