### ISSUE TITLE
Multiple instances of session ID allocator create session ID collisions at shared Matter port

### ISSUE THREAD

**Issue by msandstedt** [project-chip/connectedhomeip#12821]
#### Problem
Each controller object contains its own session ID allocator.  However, all controllers (or commissioners) vended from the controller factory multiplex traffic through a single session manager.

This breaks session ID matching because the multiple allocators can have collisions.  This also isn't spec compliant and cannot work when multiplexing secure channel traffic through a single port.

 #### Proposed Solution

* Move the session ID allocator to the Session Manager

We will also need cleanup around session ID persistence.

**Comment by bzbarsky-apple** [comment]
@msandstedt I believe https://github.com/project-chip/connectedhomeip/pull/16233 addresses the critical problem here, but we might still want to move the id allocator into the SessionManager....
