### ISSUE TITLE
Media Clusters Follow Up

### ISSUE THREAD

**Issue by lazarkov** [project-chip/connectedhomeip#12853]
#### Problem
Comments haven't been resolved for the media clusters code update [PR](https://github.com/project-chip/connectedhomeip/pull/12757) 

https://github.com/project-chip/connectedhomeip/pull/12757#discussion_r766016979
https://github.com/project-chip/connectedhomeip/pull/12757#discussion_r766019241

 #### Proposed Solution
Update code per suggestion in the [PR](https://github.com/project-chip/connectedhomeip/pull/12757)

**Comment by franck-apple** [comment]
@lazarkov could you please bring here the details on what's needed?

**Comment by lazarkov** [comment]
@franck-apple honestly, with this poorly written ticket, I need time as well figure out.

**Comment by lazarkov** [comment]
All comments have been resolved.
