### ISSUE TITLE
Media playback cluster preconditions and commands failling

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#12884]
Summary:
              As per the test-plan media playback cluster precondition and commands seems to fail when we execute

Test-plan screenshot:
![Media_cluster_pre](https://user-images.githubusercontent.com/84442963/145579922-58b0a15c-0457-4ea2-8b22-abef1667e1f4.png)

Spec media playback commands screenshot:
![image](https://user-images.githubusercontent.com/84442963/145580361-b469f7a6-1593-463a-902f-28676aac63ad.png)

Yaml script screenshot:
![image](https://user-images.githubusercontent.com/84442963/145582801-f31e6ef4-a224-499e-9cd6-c35c574e644e.png)

Execution logs:
![image](https://user-images.githubusercontent.com/84442963/145583841-7e501a41-6694-4523-8cb1-eb0c378aaa3e.png)
[Precondition_fail.txt](https://github.com/project-chip/connectedhomeip/files/7692983/Precondition_fail.txt)
[command_fail.txt](https://github.com/project-chip/connectedhomeip/files/7693158/command_fail.txt)

**Comment by turon** [comment]
Playback cluster must pass cert tests for v1.
Removing tag `v1_triage_split_4`

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id-  manjunath-grl
