### ISSUE TITLE
ZLL Clusters implementation broken ?

### ISSUE THREAD

**Issue by caipiblack** [project-chip/connectedhomeip#12927]
#### Problem

I need to use the `OnWithTimedOff` command from the OnOff cluster,

This functionality seems to be available only in zll-on-off-server.c, if i include this file to the build of my project I get errors during the build because of an include that is not pointing to the correct folder.

```
#include « ../../include/af.h »
```

As `af.h` file is in the `src/app/util` folder, it can’t find the include.

Is it supposed to build ?

 #### Proposed Solution

fix includes and build errors for all the zll cluster implementations

**Comment by caipiblack** [comment]
I just realize that there is another issue about it: https://github.com/project-chip/connectedhomeip/issues/12018#issue-1058182987

**Comment by franck-apple** [comment]
Closing this one, please refer to #12018
