### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by ayushsharma82** [project-chip/connectedhomeip#12929]
#### Problem
I wanted to know more about how to set up a matter controller. My problem is that there is no forum!  There is hardly any doc available outside this repository. It's too bad for a beginner to hop into an active community of "code only" rather than forms where I can search for my issue and understand the topic in "human language". Looking through unnecessary readmes is too time consuming and having a proper forum where people and interact solves this problem.

 #### Proposed Solution
Please enable GitHub "discussions" on this repository so that people can ask & share information with each other. It will serve justice to people interested in getting started with it.

**Comment by woody-apple** [comment]
Thank you for the suggestion, we will considering this moving forward.

**Comment by olalonde** [comment]
@woody-apple Could you enable discussions? Or maybe launch a Discord server? I too have questions related to Matter that are not really code issues.
