### ISSUE TITLE
Where is Matter specification?

### ISSUE THREAD

**Issue by shishkin** [project-chip/connectedhomeip#12942]
Hi! After visiting https://buildwithmatter.com/ and browsing through this repo I'm still puzzled if Matter specification is available.

**Comment by nicolabortignon** [comment]
1+ and following

**Comment by retfie** [comment]
#13268

**Comment by andy31415** [comment]
Closing this as part of pre v1 triage: this is not a SDK issue/bug that we can triage for implementation.
