### ISSUE TITLE
Cleanup Comments for IM

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#12976]
#### Problem
1. Add necessary comments to explain the code in Engine::BuildAndSendSingleReportData
 else if (apReadHandler->IsReadType() && !hasMoreChunks)
    {
        apReadHandler->Shutdown();
    }
Answer: for read, we don't expect status response for last report

**Comment by woody-apple** [comment]
Nice cleanup for post V1.X
