### ISSUE TITLE
YAML Scripts Fail - "Location" Attribute value read fails.

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#12983]
#### Location Attribute Read Fail.
Following YAML test scripts are failing when they try to read and validate the "location" attribute.
1.Basic Information Cluster Tests
2.Basic Group Messaging Testsrun

Attaching screenshots and logs for reference 
![BICluterTestFail](https://user-images.githubusercontent.com/12559578/145963344-9a2b33b1-bc85-4ce5-9a79-f0b773389971.png)
[BICluterTestFail.txt](https://github.com/project-chip/connectedhomeip/files/7709999/BICluterTestFail.txt)
![image](https://user-images.githubusercontent.com/12559578/145966120-6c59e158-8f41-48cf-92a7-4b1ee14d90c4.png)

**Comment by franck-apple** [comment]
Closing issue, It looks like this was achieved with PR #12960, please re-open if not.
