### ISSUE TITLE
chip-tool CLI command to compute manul pairing code cheksum

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#13025]
Test Case TC-DD-1.2 Step 3 requires us to compute checksum of the manual pairing code and validate, Can a CLI command be added into chip-tool for computing this checksum for test scripts to use.

Test plan screenshot for reference  
![image](https://user-images.githubusercontent.com/12559578/146154921-eb733d91-122d-4896-9e94-595b6d716d00.png)

**Comment by franck-apple** [comment]
Closing issue, It looks like this was achieved with PR #13048, @kvikrambhat please re-open if not.
