### ISSUE TITLE
During testing we need a way to set SuppressResponse true in YAML.

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#13052]
#### Problem
In step 8 in test [3.1.2. [TC-IDM-1.2] Invoke Response Action from DUT to TH](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#test-procedure-1) there needs to be a way to set SuppressResponse to true. There are other tests that require this as well.

 #### Proposed Solution
- Add a key/value item in YAML to set SuppressResponse to true.

**Comment by woody-apple** [comment]
Support for this is added for manual testing. Automation can be post V1.X

**Comment by krypton36** [comment]
This has beed added to YAML and chip tool. Closing this issue.
