### ISSUE TITLE
[test] TLVWriter needs more complete test and more explicit encoding API.

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#1306]
#### Problem
As shown in #1289 the chip::TLV::TLVWriter tests do not seem to have coverage for many inttypes (uint8_t, int8_t, uint16_t, int16_t) nor the `preserveSize` option.

Also, the API isn't completely explicit and requires specific casting on some toolchains.

 #### Proposed Solution
Expand the test suite.  Consider making the API explicit: `Put32`, `Put8`, etc.

**Comment by tcarmelveilleux** [comment]
This is still true

**Comment by tcarmelveilleux** [comment]
@turon is the issue resolved enough to close? If not what's missing?
