### ISSUE TITLE
Unable to comission chip-tool and chip-app1[simulated device app] when running them on the same setup.

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#13070]
When trying to execute simulated device test cases, I am unable to get the chip-tool and chip-app1 apps to commission, Both the apps are running on the same Ubuntu laptop and are being commissioned using Ethernet flow. Attaching logs from both app for reference 
[chip-tool-logs.txt](https://github.com/project-chip/connectedhomeip/files/7724498/chip-tool-logs.txt)
[chip-app1-logs.txt](https://github.com/project-chip/connectedhomeip/files/7724499/chip-app1-logs.txt)

**Comment by woody-apple** [comment]
Looks like resolved in the linked PR. Can you confirm?
