### ISSUE TITLE
chip-app1 missing mandatory cluster attributes

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#13132]
When trying to access certain clusters in the simulated devices test scripts we see error messages during the zap generation phase that seem to indicate that these clusters are missing from the placeholder apps.

![image](https://user-images.githubusercontent.com/12559578/146589182-fd9c8c18-6e2a-47dc-9a33-822aa9f8f228.png)

![image](https://user-images.githubusercontent.com/12559578/146589155-4f84b7df-b340-4e17-a0f5-0845f83a8f21.png)

**Comment by harimau-qirex** [comment]
Resolved by #13139.
