### ISSUE TITLE
Combine ZCL callbacks and expose it through a callback class

### ISSUE THREAD

**Issue by kedars** [project-chip/connectedhomeip#1316]
#### Problem
Provide a consistent mechanism for all the callback handling at various levels. Currently the session mgr callbacks are also handled in a similar callback class mechanism. 

 #### Proposed Solution
Combine the multiple callbacks from ZCL data model processing code into a callback class, so applications can define their behaviour accordingly.

**Comment by woody-apple** [comment]
@rwalker-apple does this still apply?

**Comment by rwalker-apple** [comment]
possibly, but moving to a class for these impacts codegen, which isn't landed, so not mutable to meet needs here
