### ISSUE TITLE
[ota-requestor] Implement OTA Requestor Server cluster attributes

### ISSUE THREAD

**Issue by selissia** [project-chip/connectedhomeip#13169]
#### Problem
OTA Requestor Server cluster attributes are not implemented

 #### Proposed Solution
Implement OTA Requestor Server cluster attributes as defined in Section 11.20.7.5. of the Matter specification

The DefaultOTAProviders attribute must be set from the AnnounceOTAProvider content -- this contradicts the specification but given that no other source of the Provider location is currently available (chip-tool does not support this, Jan 4, 2022), there is no other choice.

**Comment by carol-apple** [comment]
The DefaultOTAProviders should be set externally on the command line via yaml. This issue will track implementing all OTA Requestor Server cluster attributes except DefaultOTAProviders.
