### ISSUE TITLE
Spec-required level control interactions were removed from on/off cluster

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#13168]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/12507 removed some level control bits from the on/off cluster, claiming they are not spec compliant.  But as far as I can tell they are in fact required by the spec.

The requirement is a COMEFROM-style requirement in the _level control_ cluster, so it's not obvious from reading just the on/off cluster.  The relevant spec section is "1.6.4.1.1. Effect of On/Off Commands on the CurrentLevel Attribute" in the appclusters spec.  The PR says no automated test regressions were caused, but all that says to me is that we have no test coverage for this part of the spec and should add some.

 #### Proposed Solution
Double-check what implements this spec section in our code, write tests for it, make sure we pass those tests.

**Comment by bzbarsky-apple** [comment]
@mkardous-silabs

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs @Damian-Nordic

**Comment by mkardous-silabs** [comment]
@bzbarsky-apple Fix is on it's way with an update on the level control and the OnOff cluster.
