### ISSUE TITLE
Java clients should switch to managing ReadClient objects directly for subscriptions

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#13163]
#### Problem

Java clients today rely on the 'fire-and-forget' methods in CHIPCluster.h to setup a subscription to a particular node, and then calling `ShutdownSubscriptions` and `ShutdownSubscription` methods on the IM Engine to tear down a particular subscription, or all subscriptions to a particular node.

This subverts the ownership model, where while the application should be truly responsible for the lifetime of the subscription object, but instead, the ownership is managed by the stack instead.

It also avoids problems with leaked ReadClients because there is a strong ownership model that can be put in place using smart pointers.

**Comment by mrjerryjohns** [comment]
FYI @austinh0

**Comment by woody-apple** [comment]
Hard to tell, is this complete in the linked PR? @mrjerryjohns
