### ISSUE TITLE
Running cli shellscript throws poetry not found error

### ISSUE THREAD

**Issue by Srinivasan-78** [project-chip/connectedhomeip#13171]
CLI is not working with the chiptool on raspberrypi setup

     "./cli.sh: line 3: poetry: command not found"

Suggested fix:
Installing poetry locally:

     curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
     source $HOME/.poetry/env && poetry update && poetry install

Dependency has to be installed automatically.

**Comment by turon** [comment]
This is a `chip-tool` utility, not `chip-shell`.
