### ISSUE TITLE
Network Commissioning : Add platform driver support

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#13170]
#### Problem
Network commissioning clusters requires the platform to implement the platform driver.

(The list comes from src/platform directory)

Platforms not for MCUs
- [ ] Android
- [ ] Darwin
- [ ] Linux (Minor issue fix & small refactor)

Platforms with WiFi
- [x] ESP32
- [x] Ameba (#13576 )
- [x] P6 (#14767)
- [ ] Tizen
- [ ] mbed os

Thread Only platforms (should be benefited from general openthread driver)
- [x] [TBD]General OpenThread ThreadDriver (#14713)
- [x] EFR32 (#14713)(#15356)
- [ ] cc13x2
- [x] nrf
- [ ] k32w
- [ ] QPG
- [ ] telink

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
@woody-apple Need to break this apart
