### ISSUE TITLE
Establish operational credentials with accessory

### ISSUE THREAD

**Issue by bhaskar-apple** [project-chip/connectedhomeip#132]
Establish operational credentials with accessory

Sub of TLF: [SC&T] Device Onboarding #127

**Comment by smides-nest** [comment]
This should have a "provisioning" label instead of "rendezvous" label. For some reason I can't edit.

**Comment by smides-nest** [comment]
This should have a "provisioning" label instead of "rendezvous" label. For some reason I can't edit.

**Comment by franck-apple** [comment]
this is done. closing
