### ISSUE TITLE
OTA reference app needs updates for QueryStatus and DelayedActionTime

### ISSUE THREAD

**Issue by akrithika27** [project-chip/connectedhomeip#13387]
Starting the ota-provider reference app with the following options
1) ./chip-ota-provider-app -f sw_image.txt -q UpdateNotAvailable
On the ota-requestor-app I see that the file is being downloaded. 
Expected behavior - File should not be transferred.

2) set DelayedActionTime field to 600 seconds. The file gets transferred immediately. 
Expected behavior - File should only be transferred after the time mentioned.

**Comment by carol-apple** [comment]
@akrithika27 On ToT, I do not see issue #2. Perhaps you tested this on an older commit.
