### ISSUE TITLE
Use of GetFabricIndex was broken in session handle refactor

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#13396]
#### Problem
#13330 replaced code like this:
```
    return mpExchangeCtx->GetSessionHandle().GetFabricIndex();
```

with code like this:
```
    return mpExchangeCtx->GetSessionHandle()->AsSecureSession()->GetFabricIndex();
```

at a large number of callsites.

Unfortunately, the latter will crash if the session is a group session, whereas the former worked correctly in that case.

 #### Proposed Solution
Fix things so we don't crash if someone groupcasts a command that cares about the fabric index.  In practice this probably means moving mFabricIndex up to `Session`, having it initialized to 0 for `UnauthenticatedSession`, initializing it correctly for group and secure sessions, and implementing `GetFabricIndex` on `Session`.  Or is there a reason that can't happen?

@kghost @andreilitvin @msandstedt

**Comment by msandstedt** [comment]
> #### Proposed Solution
> Fix things so we don't crash if someone groupcasts a command that cares about the fabric index. In practice this probably means moving mFabricIndex up to `Session`, having it initialized to 0 for `UnauthenticatedSession`, initializing it correctly for group and secure sessions, and implementing `GetFabricIndex` on `Session`. Or is there a reason that can't happen?

I think this makes sense.  Fabric index 0 is our special reserved value for no-fabric, so it's exactly for this type of thing.
