### ISSUE TITLE
Chip-tool support for wild card read or write attributes is missing.

### ISSUE THREAD

**Issue by akrithika27** [project-chip/connectedhomeip#13419]
#### current chip-tool doesnt support wild card read or write attributes. 
We need the support in chip-tool to test this and ultimately test it thru yaml as well.

**Comment by vivien-apple** [comment]
`chip-tool` does support it now. For reading, writing, subscribing and even for commands. Now the stack does not supports all of it but at least you can send packets with wildcards to the accessory.
