### ISSUE TITLE
Null check not implemented for onLevel, OnTransitionTime and OffTransitionTime

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#13414]
Summary : 
                As per spec the default value for the attributes onLevel, OnTransitionTime and OffTransitionTime of Level control cluster is null but when we made a run showing reponse as " expected to be null but isn't ".

Spec screenshot: 
![image](https://user-images.githubusercontent.com/84442963/148783062-eade721e-92b2-4a00-92ba-a32602a51326.png)

Execution screenshot:
![image](https://user-images.githubusercontent.com/84442963/148783195-c30b7f83-e020-456e-89ba-de9b811b6cfa.png)
![image](https://user-images.githubusercontent.com/84442963/148789027-88e57a56-99c1-4df5-9b86-cbf386708fd4.png)
![image](https://user-images.githubusercontent.com/84442963/148792422-8e8383f0-9f20-48d4-a86c-14c64bae21fd.png)

**Comment by bzbarsky-apple** [comment]
The default value is the value to use if no value is provided on the wire.  An actual device may default to a different value.
