### ISSUE TITLE
chip-tool does not support sending events

### ISSUE THREAD

**Issue by akrithika27** [project-chip/connectedhomeip#13420]
current chip-tool doesnt support sending/receiving events , we need this feature to test eventing test cases.

**Comment by woody-apple** [comment]
Updating this to just cover sending events.

**Comment by woody-apple** [comment]
Receiving events is supported in chip-tool, it's not clear to us why sending is needed in chip-tool, vs the simulated device. Can you please confirm what's needed in chip-tool and for what test cases for sending, and re-open if needed. Thanks.
