### ISSUE TITLE
`chip-tool` needs to log the URL for custom commissioning to the command line

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#13430]
#### Problem
`chip-tool` needs support for Custom Flow commissioning for test case **[TC-DD-3.9] Commissioning Flow - Custom Flow**.

Steps 1-3 all require that `chip-tool` read an Onboarding Payload from a DUT accessory and fetch data from a Distributed Compliance Ledger (DCL) to assist the user in commissioning the DUT to `chip-tool ` 

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/80923273/148853814-0d30a7d3-b36e-4248-b626-00deaf21accc.png">

#### Test Case
**[TC-DD-3.9] Commissioning Flow - Custom Flow**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicediscovery.adoc#339-tc-dd-39-commissioning-flow---custom-flow

**Comment by vivien-apple** [comment]
@raju-apple We spoke about the onboarding payload at some point. This can be done without `chip-tool` at the moment, is that correct ? If so, we need to update the priority of this issue.

**Comment by woody-apple** [comment]
Given above, moving to post V1.
