### ISSUE TITLE
attributes that are currently not supported in YAML are causing issue even when optional tag is enabled

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#13442]
Summary:
1. Attributes that are currently not supported in YAML are causing test scripts to crash even when optional tag is enabled
2. This issue is common for all the optional attributes that are currently not supported in YAML 

Build Error screenshot:
![2022-01-11_12-42](https://user-images.githubusercontent.com/57476670/148897950-879efeb3-80b0-4d38-b878-279d551b33e3.png)

Teststep Screenshot :
![2022-01-11_12-48](https://user-images.githubusercontent.com/57476670/148898051-7d93aa92-174b-4dab-b70a-399b95304f63.png)
 
[test-execution-log.zip](https://github.com/project-chip/connectedhomeip/files/7844480/test-execution-log.zip)

**Comment by woody-apple** [comment]
Optional means this is optional for the server, if you want to skip this test, you should mark this as disabled until it's present - and file a bug for the FeatureMap to be implemented. Thanks
