### ISSUE TITLE
Yaml Support for Multi-Admin Test Plan

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#13460]
Test Cases : 

TC-MF 1.1 - TC-MF-1.24

**Comment by raju-apple** [comment]
ETA 02/15

**Comment by raju-apple** [comment]
Marking as P2 , since its possible to execute this suite manually

**Comment by holbrookt** [comment]
Hi Raju, is this needed for 1.0? Also please consider adding some details to the summary.

**Comment by raju-apple** [comment]
We currently have less coverage in automation for the Core tests , so wanted to get some of the Multi-Admin test cases also into CI  so that it can make the certification process faster as well . Talking about these set of tests. Hopefully after adding the Discovery api we can get these in as well : 
<img width="613" alt="Screen Shot 2022-02-01 at 9 50 32 AM" src="https://user-images.githubusercontent.com/84206864/152023042-d8f1291f-a0f6-448b-9c61-54ef3125761b.png">

**Comment by raju-apple** [comment]
WIP PR : https://github.com/vivien-apple/connectedhomeip-1/blob/TestMultiAdmin/src/app/tests/suites/TestMultiAdmin.yaml
