### ISSUE TITLE
chip-tool needs support for timed requests

### ISSUE THREAD

**Issue by akrithika27** [project-chip/connectedhomeip#13506]
Currently we do not have support in chip-tool for sending timed requests. 

We need this to test timed requests as part of data model.

**Comment by woody-apple** [comment]
@bzbarsky-apple Is this supported?

**Comment by bzbarsky-apple** [comment]
What's supported is doing a timed request followed by a write or a timed request followed by an invoke: see the `--timedInteractionTimeoutMs` optional argument and the `timedInteractionTimeoutMs` field in YAML.

@akrithika27 is that what you are asking for?  Or are you looking to send _just_ a timed request with no followup write/invoke?

**Comment by woody-apple** [comment]
Closing, given it sounds like this is complete. Please re-open if work is needed
