### ISSUE TITLE
`[TC-DD-1.12]` Needs an updated "Purpose" description

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#13513]
#### Problem
The current `Purpose` section for `[TC-DD-1.12] Onboarding Payload Verification - Custom Flow = 0` is not clear and should be re-worded to more accurately reflect the test case's intentions.

Current language used:

> This test case verifies that the interactions defined by the custom flow bit are reflected by the DUT

#### Proposed Solution

> This test case verifies that the interactions defined by the custom flow bit set to 0, Standard Flow, are reflected by the DUT.

**Comment by tcarmelveilleux** [comment]
This is a Test Plan issue, not SDK

**Comment by woody-apple** [comment]
Agree, @liamgonyea can you please open this against the test plans?
