### ISSUE TITLE
chip-tool support for Diagnostic Logs cluster

### ISSUE THREAD

**Issue by ukatira** [project-chip/connectedhomeip#13596]
#### Problem
chip-tool support needed for Diagnostic Logs cluster to verify TC-DIAGLOG-1.1, TC-DIAGLOG-1.2, TC-DIAGLOG-1.3, TC-BDX-1.1 and TC-BDX-1.3

**Comment by woody-apple** [comment]
Thought here is we need to just turn on Diagnostic Cluster, and regenerate.

**Comment by woody-apple** [comment]
We're not sure what's missing, as it seems to all be there. Can you please confirm what's needed and reopen? Thanks!
