### ISSUE TITLE
Thread is disabled in Device Configs for EFR32

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#136]
#### Problem
The following config items were removed from EFR32 `CHIPDevicePlatformConfig.h` files.

EFR32: 
https://github.com/project-chip/connectedhomeip/blob/ca9dfc24d1aa0845f7e98eb87ab9d43068c44734/src/include/platform/EFR32/CHIPDevicePlatformConfig.h#L35
https://github.com/project-chip/connectedhomeip/blob/ca9dfc24d1aa0845f7e98eb87ab9d43068c44734/src/include/platform/EFR32/CHIPDevicePlatformConfig.h#L125

 #### Proposed Solution
Figure out how to bring Thread Support back in.

**Comment by sagar-apple** [comment]
nRF5 Thread support has been enabled, updated Issue to reflect this.

**Comment by mspang** [comment]
Already done
