### ISSUE TITLE
Tv-app issues

### ISSUE THREAD

**Issue by chrisdecenzo** [project-chip/connectedhomeip#13618]
#### Problem
* Move Binding assignment to AppPlatform.
* Set ACLs.
* Descriptor cluster for ContentApp is not populated.

Completed
* UDC prompt is sent to CHIPDeviceController and no callback is made to tv-app. Need to add this callback. Put this in AppPlatform along with prompt callback for entering setup PIN.

**Comment by holbrookt** [comment]
Hi Chris, is this needed for 1.0? Please remove the label if not

**Comment by chrisdecenzo** [comment]
Yes, and I am working on it

**Comment by chrisdecenzo** [comment]
The items in this issue have all been addressed so closing
