### ISSUE TITLE
Level control minLevel/maxLevel handling broken with multiple endpoints

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#13613]
#### Problem
The Level Control cluster reads minLevel/maxLevel on every endpoint init, but stores them in the same static variables.  This breaks as soon as there are two endpoints with different min/max levels.

 #### Proposed Solution
Store the state per-endpoint instead.

@jmartinez-silabs

**Comment by jmartinez-silabs** [comment]
Fixed with https://github.com/project-chip/connectedhomeip/pull/13820
