### ISSUE TITLE
Attributes and commands of "WiFi Network Diagnostics" cluster are failing 

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#13645]
Summary:
               All attributes and commands of WiFi Network Diagnostics cluster showing Failure response when made a run.
Attributes:
BSSID, SecurityType, WiFiVersion, ChannelNumber, RSSI, BeaconLostCount, BeaconRxCount, PacketMulticastRxCount, PacketMulticastTxCount, PacketUnicastRxCount, PacketUnicastTxCount, CurrentMaxRate, OverrunCount
Command:
ResetCounts

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/149919827-73e92bbc-d616-47d4-92f4-608a6e32121a.png)
![image](https://user-images.githubusercontent.com/84442963/149919943-6b9dedb3-10f7-4ac3-aa07-2b709f5a7f6e.png)
![image](https://user-images.githubusercontent.com/84442963/149920134-d2d87b66-950f-4891-b21d-c87071cccb2e.png)

Execution screenshot and Log files:
![Security_key](https://user-images.githubusercontent.com/84442963/149920303-69caaa50-240a-4005-b7ac-ccfe89345075.png)
![wifi_Command](https://user-images.githubusercontent.com/84442963/149920318-ef6e09fc-69a4-44df-9fb3-ff9e5fda3f3a.png)
![WIFI_NWK_STR](https://user-images.githubusercontent.com/84442963/149920331-c83a6793-0342-4c69-a009-b5f1aef7f8fc.png)
![wifiversion](https://user-images.githubusercontent.com/84442963/149920338-d8992598-3e87-4467-beb7-9d79c27ee01a.png)
[nwk_str.txt](https://github.com/project-chip/connectedhomeip/files/7888285/nwk_str.txt)
[security_key.txt](https://github.com/project-chip/connectedhomeip/files/7888286/security_key.txt)
[wificommand.txt](https://github.com/project-chip/connectedhomeip/files/7888287/wificommand.txt)
[wifiversion.txt](https://github.com/project-chip/connectedhomeip/files/7888288/wifiversion.txt)

**Comment by cecille** [comment]
Is this on all devices or a specific device?

**Comment by manjunathambiger23** [comment]
@cecille we ran this on linux have not tested on other platforms

**Comment by bzbarsky-apple** [comment]
Test is trying to read the cluster on endpoint 1, which is not where this cluster lives.

That said, we probably need to merge https://github.com/project-chip/connectedhomeip/pull/14755 for this to really work right.

**Comment by bzbarsky-apple** [comment]
And also, ResetCounts might just not work on some platforms.....

**Comment by kowsisoundhar12** [comment]
Testscript name ---> [TC-WIFIDIAG-1.3] Command received functionality with server as DUT

ResetCounts Command is giving failure response ,because of this command following attributes response value is not resetting to "0"

BeaconLostCount,
 BeaconRxCount, 
PacketMulticastRxCount,
 PacketMulticastTxCount, 
PacketUnicastRxCount, 
![Uploading WIFIDIAG-error.png…]()
PacketUnicastTxCount.

**Comment by kowsisoundhar12** [comment]
Testscript name ---> [TC-WIFIDIAG-1.3] Command received functionality with server as DUT

ResetCounts Command is giving failure response ,because of this command following attributes response value is not resetting to "0"

BeaconLostCount,
BeaconRxCount,
PacketMulticastRxCount,
PacketMulticastTxCount,
PacketUnicastRxCount,
PacketUnicastTxCount.
![WIFIDIAG-error](https://user-images.githubusercontent.com/57476670/167167527-77175232-c81f-4dd4-aa45-650b38f2317b.png)
![WIFI-DIAG](https://user-images.githubusercontent.com/57476670/167167541-9dd5e7f7-662f-4e6a-95e2-43f6fa88a646.png)
[WIFIDIAG-Exceution-logs.zip](https://github.com/project-chip/connectedhomeip/files/8641944/WIFIDIAG-Exceution-logs.zip)

**Comment by bzbarsky-apple** [comment]
@kowsisoundhar12 getting a nonzero number there is absolutely correct.  See https://github.com/CHIP-Specifications/chip-test-plans/issues/941

**Comment by kowsisoundhar12** [comment]
Following attributes are giving failure response 
1.BeaconLostCount
2.PacketMulticastRxCount
3.PacketMulticastTxCount
4.PacketUnicastRxCount
5.PacketUnicastTxCount
6.CurrentMaxRate
7.OverrunCount

Error Screenshot:
![Screenshot from 2022-05-09 19-26-08](https://user-images.githubusercontent.com/57476670/167426194-3c145dc7-ac80-4212-aca3-211798f24664.png)

please refer testlogs here
[TC-WIFI-DIAG.zip](https://github.com/project-chip/connectedhomeip/files/8653939/TC-WIFI-DIAG.zip)

**Comment by bzbarsky-apple** [comment]
That's running against what server?

**Comment by kowsisoundhar12** [comment]
i have executed this  testcase in linux,i have used following commands

1 ) ./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-chip-tool-no-ble-tsan-clang \
                        --target linux-x64-all-clusters-test-group-no-ble-tsan-clang \
                        --target linux-x64-lock-no-ble-tsan-clang \
                        --target linux-x64-tv-app-no-ble-tsan-clang \
                        build \
                        --copy-artifacts-to objdir-clone \
                     "				 
						 
.2) /scripts/run_in_build_env.sh \
                  "./scripts/tests/run_test_suite.py \
                     --chip-tool ./out/linux-x64-chip-tool-no-ble-tsan-clang/chip-tool \
                     run \
                     --iterations 1 \
                     --all-clusters-app ./out/linux-x64-all-clusters-test-group-no-ble-tsan-clang/chip-all-clusters-app \
                     --lock-app ./out/linux-x64-lock-no-ble-tsan-clang/chip-lock-app \
                     --tv-app ./out/linux-x64-tv-app-no-ble-tsan-clang/chip-tv-app \
                  "

**Comment by bzbarsky-apple** [comment]
OK, but then how would it pass?  The server is not directly connected to wi-fi, right?

**Comment by bzbarsky-apple** [comment]
@manjunath-grl Is there still an issue here?

**Comment by manjunath-grl** [comment]
@bzbarsky-apple it is resolved and i tried it in ToT its passing ,can you please close this issue
