### ISSUE TITLE
[msg] Confirm proper handling of message and secure extensions

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#13669]
#### Problem
A future v2 message may utilize the message extensions (MX flag = 1) and secure extensions (SX flag = 1).  We need to verify the v1 SDK properly handles the length of the extensions portion of such future messages and properly parses them.

 #### Proposed Solution
Add a certification test and verify the implementation.

**Comment by turon** [comment]
For forward-compatibility, this is required for v1.
Removing `v1_triage_split_4`.

**Comment by woody-apple** [comment]
@turon Can you open an issue against the certification group for this?

**Comment by turon** [comment]
Test spec issue created: https://github.com/CHIP-Specifications/chip-test-plans/issues/904
