### ISSUE TITLE
Can not complete commission with iOS-CHIP-Tool

### ISSUE THREAD

**Issue by zzz2016** [project-chip/connectedhomeip#13679]
After I used iOS-CHIP-Tool to complete the commission, my esp32(BLE + WiFi， all-cluster-demo) can join the specified WiFi network, but cannot complete the device discovery, the output log is 
"I (8658) chip[DIS]: Failed to find a valid admin pairing. Node ID unknown
I (8668) chip[DIS]: Start dns-sd server - no current nodeId".

But with the Android-CHIP-Tool, the whole process can be completed.

On the Android side, I found that there are NOCs related operations in the logs of esp32, but not on the iOS side. Is this the crux of the matter?

**Comment by caoguoqing** [comment]
I am also an IOS developer，you can add me wx(caocaolovecaocao),follow up exchange with matter stepping pit
