### ISSUE TITLE
Reset to Factory on m5stack after commissioning does not remove fabric

### ISSUE THREAD

**Issue by g-coppock** [project-chip/connectedhomeip#13720]
#### Problem

1. Commission an m5stack.
2. Setup > Reset to factory.
3. View logs or attempt commissioning again

The device re-enters commissioned state and stops advertising (though it sends at least one initial BLE advertisement before this happens).

Note that "Reset Wi-fi" does complete the factory reset and reset the commissioned state.

**Comment by chshu** [comment]
@g-coppock The issue has been fixed, please try again with the latest master.
