### ISSUE TITLE
[TC-PS-2.1] Attributes Missing From Power Source Cluster

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#13758]
Summary:
The following  attributes seem to be missing in the Power Source Cluster
	1.WiredAssessedInputVoltage
	2.WiredAssessedInputFrequency
	3.WiredCurrentType
	4.WiredAssessedCurrent
	5.WiredNominalVoltage
	6.WiredMaximumCurrent
	7.WiredPresent
	8.ActiveWiredFaults
	9.BatReplacementNeeded
	10.BatReplaceability
	11.BatPresent
	12.BatReplacementDescription
	13.BatCommonDesignation
	14.BatANSIDesignation
	15.BatIECDesignation
	16.BatApprovedChemistry
	17.BatCapacity
	18.BatQuantity
	19.BatTimeToFullCharge
	20.BatFunctionalWhileCharging
	21.BatChargingCurrent
	22.ActiveBatChargeFaults
Spec-screenshot:
![2022-01-20_16-34](https://user-images.githubusercontent.com/57476670/150333689-bb4809d3-6ea9-42f7-869c-9762f91ec843.png)
![2022-01-20_16-34_1](https://user-images.githubusercontent.com/57476670/150333704-dd5f6876-79b2-40a9-b8ef-e8da102bcaee.png)

Testscripts Logs:
![2022-01-20_16-27](https://user-images.githubusercontent.com/57476670/150333838-d59895ca-a1b0-4ed1-944d-ff12d39f62e2.png)

**Comment by bzbarsky-apple** [comment]
chip-tool should support these now.  @kowsisoundhar12 can you confirm?

**Comment by kowsisoundhar12** [comment]
@bzbarsky-apple still observing above attribute missing error in power Source Cluster
![2022-05-06_00-40](https://user-images.githubusercontent.com/57476670/167008316-01a29bc4-a0db-4aff-bdec-9f764037ac38.png)

**Comment by bzbarsky-apple** [comment]
Ah, yaml is still using controller-clusters.  Thanks, I'll get a PR up.
