### ISSUE TITLE
  Manual code and QR code does not take the operational parameters while pairing .

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#13768]
#### Problem

As we cannot provide Operational network parameters (like SSID/PASSWD), we are not able to pair manual code and QR code using  BLE-WIFI or BLE-THREAD  hence by default  it is considering provisioning through IP network since raspi is connected through ethernet.

Below  are the commands used for manual and QR code pairing

/chip-tool pairing manualcode 1 34970112332
/chip-tool pairing qrcode 3 MT:YNJV7VSC00KA0648G00

**Comment by woody-apple** [comment]
Note to self: I have a patch for this.
