### ISSUE TITLE
[ota-provider-app] Provider crashes after the second  announce-ota-provider command

### ISSUE THREAD

**Issue by selissia** [project-chip/connectedhomeip#13767]
#### Problem
Once the chip-tool issues the announce-ota-provider twice in a row the Provider crashes. 

Setup: Provider and chip-tool running on the same Raspberry Pi, OTBR is a separate RPi, Requestor is a Thread device. Set up the network and send `./chip-tool otasoftwareupdaterequestor announce-ota-provider`. After that complete successfully you send the command `./chip-tool otasoftwareupdaterequestor announce-ota-provider` again, the Provider crashes. Provider log is attached. 

 #### Proposed Solution
[OTA_provider_crash.txt](https://github.com/project-chip/connectedhomeip/files/7906931/OTA_provider_crash.txt)

**Comment by carol-apple** [comment]
This has been fixed by https://github.com/project-chip/connectedhomeip/pull/13329
