### ISSUE TITLE
Not able to read the attribute with string type value

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#13771]
#### Problem
 
 I found the default generated attribute get API does not work for the attrbute with type of string, such as:
  
namespace Description {
EmberAfStatus Get(chip::EndpointId endpoint, chip::MutableCharSpan value); // char_string
EmberAfStatus Set(chip::EndpointId endpoint, chip::CharSpan value);

The Set API works well.

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
The MutableCharSpan passed in needs to point to a buffer to copy the string into.  And the read will fail if the buffer is not big enough.
