### ISSUE TITLE
emberAfSetDynamicEndpoint does not prevent use of fixed endpoint IDs

### ISSUE THREAD

**Issue by bkrawetz-dev2** [project-chip/connectedhomeip#13783]
#### Problem
emberAfSetDynamicEndpoint only enforces that the proposed endpoint ID be unique across other dynamic endpoints. It does not check fixed endpoints.

 #### Proposed Solution
Since id == index for fixed endpoints, it should be sufficient to check that the proposed id is >= fixed endpoint count.

**Comment by chiragatal** [comment]
I think a better solution would be to check for the IDs of the fixed endpoints too, for finding duplicates. This would not assume that id == index for fixed endpoints.

It can be done by starting the loop, which checks for duplicates, from 0 instead of FIXED_ENDPOINT_COUNT.
