### ISSUE TITLE
Minimal mdns should send Rmv notifications as needed

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#13793]
#### Problem
If a node is commissionable, it publishes records with CM=1.

When it stops being commissionable, it should stop advertising those.  Right now platform mdns seems to handle this right, but minimal mdns does not.

 #### Proposed Solution
Fix minimal mdns to send Rmv notifications for the CM=1 records, so we are not incorrectly advertising ourselves as being commissionable until the TTL is hit

@andy31415

**Comment by turon** [comment]
Minimal mdns must be spec compliant for v1.
Removing tag `v1_triage_split_4`

**Comment by woody-apple** [comment]
SDK Spec Review: We do not believe this is a spec requirement for 1.0.
