### ISSUE TITLE
In windowcovering cluster the expected results are inconsistent with the actual results of test cases using TE7.5  [tc-wncv-3.1] [tc-wncv-3.2]

### ISSUE THREAD

**Issue by cherishQAQ123** [project-chip/connectedhomeip#13812]
when test  window covering cluster, the expected results are inconsistent with the actual results using new image TE7.5 of this commit id b0af6ba

> expected behavior - success
> actual behavior - Inconsistent values，value has always been 0

actual logs attached here
[tc-wncv-3.1] commands:
./chip-tool windowcovering down-or-close 1234 1
./chip-tool windowcovering read current-position-lift-percent100ths 1234 1
./chip-tool windowcovering read current-position-tilt-percent100ths 1234 1
./chip-tool windowcovering up-or-open 1234 1
./chip-tool windowcovering read current-position-lift-percent100ths 1234 1
./chip-tool windowcovering read current-position-tilt-percent100ths 1234 1
./chip-tool windowcovering read operational-status 1234 1
 ./chip-tool windowcovering read current-position-lift-percent100ths 1234 1
./chip-tool windowcovering read current-position-tilt-percent100ths 1234 1
[window_covering_cluster_TC-WNCV-3.1.txt](https://github.com/project-chip/connectedhomeip/files/7911919/window_covering_cluster_TC-WNCV-3.1.txt)

[tc-wncv-3.2] commands:
./chip-tool windowcovering up-or-open 1234 1
./chip-tool windowcovering read current-position-lift-percent100ths 1234 1
./chip-tool windowcovering read current-position-tilt-percent100ths 1234 1
./chip-tool windowcovering down-or-close 1234 1
./chip-tool windowcovering read target-position-lift-percent100ths 1234 1
./chip-tool windowcovering read target-position-tilt-percent100ths 1234 1
./chip-tool windowcovering read operational-status 1234 1
./chip-tool windowcovering read current-position-lift-percent100ths 1234 1
./chip-tool windowcovering read current-position-tilt-percent100ths 1234 1
[window_covering_cluster_TC-WNCV-3.2.txt](https://github.com/project-chip/connectedhomeip/files/7911796/window_covering_cluster_TC-WNCV-3.2.txt)

**Comment by jmeg-sfy** [comment]
https://github.com/project-chip/connectedhomeip/issues/13812
