### ISSUE TITLE
Access control defaults should not be permissive

### ISSUE THREAD

**Issue by mlepage-google** [project-chip/connectedhomeip#13867]
It's preferable if the defaults are not permissive, i.e. they error or deny access. Users should not have a permissive system by forgetting to configure access control, so users will have to configure access control to have a functioning system.

This is difficult in the short term, because our configuration (including for unit tests and integration tests) is not confined to one place. Therefore, because access control is baked into the IM, tests can fail if they haven't configured access control. Having more permissive defaults helps us develop until we reach feature complete, and until we improve our startup/shutdown story (including for tests).

Production code will also include the access control cluster, which will configure the access control module. Therefore, all a build (such as an example app) needs to do is include the cluster, and the system will be correctly configured for operation.

Once we hit feature complete, we can reorganize this (e.g. find all the tests that need to also configure access control) and make the defaults less permissive again.

**Comment by tcarmelveilleux** [comment]
Spec-compliance: 

> The Access Control system is rule-based with no implicit access permitted by default. Access to a Node's Targets is denied unless the Access Control system grants the required privilege level to a given Subject to interact with given Targets on that Node. Initial Access Control privileges are <<ref_ACL_Bootstrapping, bootstrapped>> during the commissioning phase, and maintained thereafter by Administrators.
> 
> All access privileges, from the <<ref_AccessControlEntryPrivilegeEnum>> enumeration, SHALL be granted by Access Control. Thus, the Initiator ("Subject" hereafter) of any Interaction Model action SHALL NOT succeed in executing a given action on a Node's Target unless that Node's Access Control system explicitly grants the required privilege to that Subject for that particular action.
>
