### ISSUE TITLE
TCP and IP-frag do not work with this, yet:

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13910]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/lwip/standalone/lwipopts.h#L168-L173

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `todo` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by holbrookt** [comment]
Seems to be an lwip related TODO, and the file hasn't been touched for ~2 years. Assuming not critical for 1.0.
