### ISSUE TITLE
This should not be a list at all!

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13922]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/general-commissioning-server/general-commissioning-server.cpp#L86-L91

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
This is a spec compliance issue, since the spec does not actually define that as a list.

**Comment by bzbarsky-apple** [comment]
Fixed in #14671
