### ISSUE TITLE
Most of the callers are incorrectly passing SecureChannel as the protocol ID, when in fact, the status code provided

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13921]
above is always an IM code. Instead of fixing all the callers (which is a fairly sizeable change), we&#x27;ll embark on fixing this more completely when we fix #9530.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/CommandHandler.cpp#L325-L330

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by andy31415** [comment]
@erjiaqing - is this supposed to be v1 or is this TODO actually #9530 (which is v1.x)?
