### ISSUE TITLE
Pass the actual network id to device control server.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13926]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/network-commissioning/network-commissioning.cpp#L294-L299

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
Is this still needed @erjiaqing @cecille ?
