### ISSUE TITLE
Add support to the following attributes

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13925]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/network-commissioning/network-commissioning.cpp#L193-L198

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by cecille** [comment]
This has been fixed and the todo has been removed.
https://github.com/project-chip/connectedhomeip/pull/15124
