### ISSUE TITLE
Optimize Packet buffer usage in CHIPoBLE ACK management 

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13939]
tx buf before sending ack.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/ble/BLEEndPoint.cpp#L883-L888

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by kpschoedel** [comment]
This might be a nice small-memory optimization, but the TODO is seven years old (from Weave) so doing it for 1.0 doesn't seem worth the risk. Will remove the TODO to placate automated scans, but leave the issue for 1.x consideration.
