### ISSUE TITLE
Do we need to support more than one network?

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13937]
emberAfPushNetworkIndex(i);

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/util/util.cpp#L256-L261

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `FIXME` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
Stale since we don't use Ember's network management logic anymore.
