### ISSUE TITLE
Can we actually hit this case in CHIP, or can this whole block

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13931]
go away? emAfSetCryptoOperationInProgress();

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/util/af-main-common.cpp#L315-L320

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by kpschoedel** [comment]
File removed by 8b503ad05993ccef1063c1b38d9a906a85955445 #14571
