### ISSUE TITLE
have an eviction policy so if the cache is full, an entry may be deleted.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13954]
One policy may be Least-time-to-live

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/lib/dnssd/DnssdCache.h#L55-L60

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by woody-apple** [comment]
We need some eviction policy for v1... suggest the simplest one :) LRU if possible!

**Comment by bzbarsky-apple** [comment]
dns-sd cache was removed.
