### ISSUE TITLE
Revisit these if and when fabric ID and node ID support has

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13955]
been integrated into the stack.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/lib/support/CHIPArgParser.cpp#L55-L60

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by holbrookt** [comment]
This TODO was carried over from the initial openweave import so I'm assuming it's not relevant for 1.0. Not sure who should be assigned
