### ISSUE TITLE
enable CommissionedListCommand (listing devices chip-tool has commissioned)

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13973]
make_unique&lt;CommissionedListCommand&gt;(),

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/examples/chip-tool/commands/pairing/Commands.h#L199-L204

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by turon** [comment]
All commands specified for commissioning are required for v1.
Removing tag `v1_triage_split_4`

**Comment by cecille** [comment]
@woody-apple - can you specify what the spec issue is here? This looks like a chip-tool feature request to me. I'm possibly misunderstanding what this issue is for.

**Comment by bzbarsky-apple** [comment]
This is in fact a chip-tool feature, and not needed for 1.0
