### ISSUE TITLE
chip-tool missing command support for floats/structs in commands

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13974]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/examples/chip-tool/templates/commands.zapt#L523-L528

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by tcarmelveilleux** [comment]
Renamed after looking at code. This is a template issue for the `chip-tool` template.

**Comment by vivien-apple** [comment]
Done.
