### ISSUE TITLE
We don't Platform::MemoryShutdown because ~CASESessionManager calls

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13970]
Dnssd::ResolverProxy::Shutdown, which starts doing Platform::Delete. Platform::MemoryShutdown();

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/examples/all-clusters-app/linux/fuzzing-main.cpp#L28-L33

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
Looks critical, since it involves shutdown and object free coordination.

**Comment by woody-apple** [comment]
Agree.
