### ISSUE TITLE
add API for OTARequestor to pass QueryImageResponse info to the application to use for OTADownloader init

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13986]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/examples/ota-requestor-app/linux/main.cpp#L114-L119

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by yufengwangca** [comment]
@holbrookt Could you help to take a look at this TODO item?

**Comment by holbrookt** [comment]
Not needed for 1.0
