### ISSUE TITLE
add confiuration for returning BUSY status

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13982]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp#L98-L103

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by woody-apple** [comment]
Not clear if this is required for v1, @carol-apple ?

**Comment by carol-apple** [comment]
This is a stale TODO. The configuration for BUSY has already been supported.
