### ISSUE TITLE
This uses the current node as the provider to supply the OTA image. This can be configurable such that the provider

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13983]
supplying the response is not the provider supplying the OTA image.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/examples/ota-provider-app/ota-provider-common/OTAProviderExample.cpp#L115-L120

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by woody-apple** [comment]
@carol-apple is this needed for v1?

**Comment by carol-apple** [comment]
Not needed for v1.0

**Comment by carol-apple** [comment]
Dupe of https://github.com/project-chip/connectedhomeip/issues/12772
