### ISSUE TITLE
Accept these values over CLI

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#13993]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/examples/tv-casting-app/linux/main.cpp#L59-L64

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by holbrookt** [comment]
Hi @sharadb-amazon, it looks like you introduced this TODO. It doesn't seem necessary for 1.0, but please relabel this issue if I'm wrong. Thanks!
