### ISSUE TITLE
Add the implicit admit for PASE after the spec is updated.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14008]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/access/AccessControl.cpp#L137-L142

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by cecille** [comment]
Seems fairly security critical, but would like a second opinion. Possibly related to #14604?

**Comment by mlepage-google** [comment]
This TODO issue is obsolete, PR #14550 removed that TODO and clause, and added the "implicit admin for PASE" condition.
