### ISSUE TITLE
Replace implementation of `ServerClusterCommandExists()` in ember-compatibility-functions.cpp by IM command catalog look-up

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14022]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/InteractionModelEngine.h#L264-L269

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by tcarmelveilleux** [comment]
This is dependant on https://github.com/project-chip/connectedhomeip/pull/14299
