### ISSUE TITLE
The endpoint id on response command (client side command) is unclear, so we don't have a ClientClusterCommandExists

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14023]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/InteractionModelEngine.h#L266-L271

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by woody-apple** [comment]
@mrjerryjohns ?

**Comment by bzbarsky-apple** [comment]
That TODO comment no longer exists.

We don't need a ClientClusterCommandExists because command responses just get routed to whoever sent the request (the server command's sender).  And if you sent a command, the assumption is you can handle its response.
