### ISSUE TITLE
8967) Implementation of CommandSender::Callback should be removed after switching to ClusterObjects.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14021]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/DeviceControllerInteractionModelDelegate.h#L18-L23

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by turon** [comment]
References #8967 which is closed.

**Comment by mrjerryjohns** [comment]
This is now fixed (`DeviceControllerInteractionModelDelegate.h` has now been removed).
