### ISSUE TITLE
Add ListOperation::ReplaceItem support. (Attribute path with valid list index)

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14024]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/ReadClient.cpp#L483-L488

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by woody-apple** [comment]
@mrjerryjohns ?

**Comment by mrjerryjohns** [comment]
Stale comment, it's not longer there in the code.
