### ISSUE TITLE
add binding table to the persistent storage

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14034]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/bindings/bindings.cpp#L35-L40

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by bzbarsky-apple** [comment]
Bindings persistence is implemented.
