### ISSUE TITLE
Make the pending notifications list of binding table indecies and list of contexts

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14033]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/bindings/BindingManager.h#L144-L149

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by holbrookt** [comment]
@gjc13 you were the last one to edit this file and TODO. Please remove the label if this isn't needed for 1.0
