### ISSUE TITLE
Some reference counting mechanism shall be added the CASESessionManager

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14032]
so that other session clients don&#x27;t get accidentally closed.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/bindings/BindingManager.cpp#L37-L42

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by yufengwangca** [comment]
@gjc13 Could you help to take a look of this TODO item?
