### ISSUE TITLE
Implement clearing the user

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14039]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/door-lock-server/door-lock-server.cpp#L379-L384

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by Morozov-5F** [comment]
Should already be addressed in the SDK.
