### ISSUE TITLE
PowerSource cluster: Implement attribute read of ActiveBatteryFaults.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14049]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/power-source-server/power-source-server.cpp#L55-L60

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by turon** [comment]
PowerSource cluster must comply with spec for v1.
Removing tag `v1_triage_split_4`

**Comment by cjandhyala** [comment]
@fessehaeve @woody-apple , We do have a test case to read that Attribute. But per spec this attribute is optional, So we are not verifying for optional attributes for V1.0. Ref spec ref

![Screen Shot 2022-05-27 at 3 33 42 PM](https://user-images.githubusercontent.com/68604034/170796794-803fae60-ba25-49f1-a376-dbfa60f58711.png)

**Comment by andy31415** [comment]
Moved post 1.0 since this functionality is optional
