### ISSUE TITLE
TC_MC_9_1 "reads the application attribute": Enable once attribute struct is supported

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14055]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/tests/suites/certification/Test_TC_MC_9_1.yaml#L68-L73

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by bzbarsky-apple** [comment]
Fixed in #19543
