### ISSUE TITLE
WindowCovering Test WNCV_2_1 add/complete some Conditional test using the FeatureMap (dynamics Mandatory and Optional attributes)

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14056]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/tests/suites/certification/Test_TC_WNCV_2_1.yaml#L15-L20

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by naveenkommareddi** [comment]
This is a DUP of #16725 which is being used to track all the FeatureMap issues

**Comment by jmeg-sfy** [comment]
actually this is still a problem (need to be rewritten) in the SDK looking at PICS -<vs>- FeatureMap
and the fact we cannot still test featureMap's bit flag against YAML  PICS_MyFeature
