### ISSUE TITLE
4503): length should be passed to commands when byte string is in argument list.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14068]
TODO(#4503): Commands should take group id as an argument.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/templates/app/CHIPClusters-src.zapt#L18-L23

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by turon** [comment]
Modern issue to implement general cluster handling features required for v1.
Removing tag `v1_triage_split_4`

**Comment by bzbarsky-apple** [comment]
The code referenced above is gone, and byte strings are passed as ByteSpan, which has a length.
