### ISSUE TITLE
4503): Commands should take group id as an argument.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14069]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/templates/app/CHIPClusters-src.zapt#L19-L24

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by jepenven-silabs** [comment]
Comment is not in the code anymore
