### ISSUE TITLE
Refactor WriteSingleClusterData and all dependent functions to take ConcreteAttributePath instead of ClusterInfo

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14064]
as the input argument.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/util/ember-compatibility-functions.cpp#L812-L817

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by bzbarsky-apple** [comment]
`WriteSingleClusterData` takes `ConcreteDataAttributePath` now.
