### ISSUE TITLE
4502): onCompletion is not used by IM for now.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14067]
TODO(#4503): length should be passed to commands when byte string is in argument list. TODO(#4503): Commands should take group id as an argument.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/templates/app/CHIPClusters-src.zapt#L17-L22

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
This file has been deleted and the approach has pivoted, so issue is no longer relevant.
