### ISSUE TITLE
These IM related callbacks contains small or no generated code, should be put into separate file to reduce the size of template. }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14066]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/templates/app/CHIPClientCallbacks-src.zapt#L118-L123

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by andy31415** [comment]
Moved to post v1 as this does not seem to be a blocking bug but more maintenance of template logic (overly long templates and repeated code).
