### ISSUE TITLE
Nothing emits WiredFaultChange events.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14078]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/zcl/data-model/chip/power-source-cluster.xml#L66-L71

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by bzbarsky-apple** [comment]
Events generally work.  Nothing right now emits this specific event, as far as I can tell....

**Comment by cjandhyala** [comment]
@woody-apple Events in the Power source config cluster are optional per latest spec, hence we are not testing for v1.0
![Screen Shot 2022-05-27 at 3 37 14 PM](https://user-images.githubusercontent.com/68604034/170797093-86e5ce8b-2449-42e5-be1e-fc881efdc1c3.png)

**Comment by andy31415** [comment]
Moving out of v1.0 functionality that is optional
