### ISSUE TITLE
Add feature map once it is supported 

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14079]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/zcl/data-model/chip/target-navigator-cluster.xml#L26-L31

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by andy31415** [comment]
I checked src/app_clusters/media/TargetNavigator.adoc in latest spec and the feature map of this cluster seems empty:

```
103 === Features
104 This cluster SHALL support the FeatureMap bitmap attribute as defined below.
105
106 [options="header",valign="middle"]
107 |===
108 s| Bit | Code | Feature         | Description
109 |===
110
```

as such, I am unclear what needs to be done here, so I am moving this out of v1, but asking the original TODO author to review. @lazarkov
