### ISSUE TITLE
Change Endpoints to INT16U array in Bridged Action Clusters XML

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14074]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/zcl/data-model/chip/bridged-actions-cluster.xml#L83-L88

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by bzbarsky-apple** [comment]
Struct members that are lists are very much supported and have been for quite a while.

**Comment by bzbarsky-apple** [comment]
@pjzander-signify Are you blocked on something here?

**Comment by bzbarsky-apple** [comment]
Oh, this got fixed in #12065.  We just forgot to remove the TODO comment.
