### ISSUE TITLE
A list of list is not supported yet. Otherwise this should be a list of SemanticTags 

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14077]
item name&#x3D;&quot;SemanticTags&quot; type&#x3D;&quot;SemanticTag&quot; array&#x3D;&quot;true&quot; optional&#x3D;&quot;false&quot;/&gt; --&gt;

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/zap-templates/zcl/data-model/chip/mode-select-cluster.xml#L30-L35

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by bzbarsky-apple** [comment]
This should be supported fine.  

@du48s03 could you please take a look into fixing this?
