### ISSUE TITLE
check that there is no commissioning in progress currently.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14081]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/AutoCommissioner.cpp#L195-L200

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
Rationale for keeping it v1: Ensuring we don't start commissioning when one is in progress seems like good house-keeping to do to prevent worse failures from cropping up later.

**Comment by woody-apple** [comment]
@cecille can you take a look at this, also - note this one:
https://github.com/project-chip/connectedhomeip/issues/13945
