### ISSUE TITLE
cecille): We should add a PII bytespan concept.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14089]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/CommissioningDelegate.h#L57-L62

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by tcarmelveilleux** [comment]
Please remove this TODO
