### ISSUE TITLE
fill out parameter types }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14095]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/java/templates/ClusterInfo-java.zapt#L316-L321

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by holbrookt** [comment]
Hi @JasonLiuZhuoCheng - you were the last to modified this TODO. Is this something that's needed for 1.0? If not, please remove the label.
