### ISSUE TITLE
Add support for struct-typed attributes }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14097]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/java/templates/ClusterInfo-write-interaction.zapt#L19-L24

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by kowsisoundhar12** [comment]
Need a Yaml support for checking the structure type for each entries 

following Thread Network Diagnostics Cluster attributes are related to structure type checking 

1.SecurityPolicy
2.OperationalDatasetComponents
3.RouteTable Struct
4.NeighborTable Struct
