### ISSUE TITLE
Support array types. }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14099]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/java/templates/partials/encode_value.zapt#L12-L17

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by andy31415** [comment]
Encode values seems to already be supported in the latest encode_value.zapt (there is an isArray check and no more todo).
