### ISSUE TITLE
Use if_is_struct, which works better for nested types. Currently can't because inline partials aren't found in its else block. }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14100]
TODO: Support struct types. }}

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/java/templates/partials/encode_value.zapt#L14-L19

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
This looks fairly important, but assigning to @austinh0 for further triage.

**Comment by andy31415** [comment]
encode_value.zapt does not contain any TODO anymore.  Assuming already fixed since todo gone. also I see if_is_struct usage.
