### ISSUE TITLE
Implement a real type for structs. }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14104]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/java/templates/partials/list_attribute_callback_type.zapt#L14-L19

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by turon** [comment]
File doesn't exist in tree anymore.
Removing `v1_triage_split_2`.
Closing.
