### ISSUE TITLE
If the inline partial is indented, generation fails with "result.split is not a function". }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14103]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/java/templates/partials/encode_value.zapt#L70-L75

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by tcarmelveilleux** [comment]
Recommend converting to a pure comment. This is not a TODO, but rather a warning.
