### ISSUE TITLE
Support struct types. }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14101]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/controller/java/templates/partials/encode_value.zapt#L15-L20

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by turon** [comment]
Support for struct types is required for v1.
Removing tag `v1_triage_split_4`

**Comment by mrjerryjohns** [comment]
Is done.
