### ISSUE TITLE
The "all events" part does not work yet.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14125]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/darwin/Framework/CHIP/CHIPDevice.h#L45-L50

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by bzbarsky-apple** [comment]
@jtung-apple
