### ISSUE TITLE
Remove once the Attestation Credentials storage mechanism is updated.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14120]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/credentials/examples/DeviceAttestationCredsExample.cpp#L23-L28

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by holbrookt** [comment]
Hi Evgeni - this TODO came from your PR https://github.com/project-chip/connectedhomeip/pull/12568. Is it needed for 1.0? If not please remove the label
