### ISSUE TITLE
Parse the header when the image is received

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14129]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/include/platform/OTAImageProcessor.h#L36-L41

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by turon** [comment]
OTA support required for v1.
Removing tag `v1_triage_split_4`

**Comment by carol-apple** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/14790 and https://github.com/project-chip/connectedhomeip/pull/14875
