### ISSUE TITLE
Need to add support for struct-type attibutes here.  And remove the callbackName

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14127]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/darwin/Framework/CHIP/templates/CHIPClustersObjc-src.zapt#L85-L90

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by mrjerryjohns** [comment]
This looks fairly important, but marking it as secondary triage. @vivien-apple @bzbarsky-apple to comment further.

**Comment by bzbarsky-apple** [comment]
We need this for the Darwin Framework, yes.   Otherwise we can't read some attributes right now.

This is generally on my radar.
