### ISSUE TITLE
Device Type (DT) TXT field is 16 bits but should be 32

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14142]
false

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/lib/dnssd/TxtFields.h#L107-L112

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by tcarmelveilleux** [comment]
DeviceTypeID is 32 bits in the spec, but only vendor-specific device types are >16 bits. Suggest moving to 32 bits at this line.

**Comment by cecille** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/15918
