### ISSUE TITLE
haveIPv6Conn */

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14159]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/EFR32/ConnectivityManagerImpl_WIFI.cpp#L406-L411

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by holbrookt** [comment]
Hi Narayan, it looks like this TODO came from https://github.com/project-chip/connectedhomeip/pull/13193 - is this something that needs to be fixed for 1.0?

**Comment by selissia** [comment]
@mrfinesse99 , could you please take a look?

**Comment by mrfinesse99** [comment]
That TODO was there as a place holder for RS911x - However it is no longer needed as the abstraction that interfaces to lower level of WiFi code handles this correctly. So that comment of TODO can be safely ignored for 1.0
