### ISSUE TITLE
cecille): This command fails on ESP32, but it's blocking IP cluster-based commissioning so for now just return a success

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14158]
status.

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/DeviceControlServer.cpp#L95-L100

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by yufengwangca** [comment]
it looks we ConfigurationMgr implementation for the related config flag is missing on ESP32. We should at least overwrite those config API on ESP32 platform and return CHIP_NO_ERROR there.

**Comment by jadhavrohit924** [comment]
#16520

**Comment by cecille** [comment]
Thank you!
