### ISSUE TITLE
expire the group session

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14156]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/messaging/tests/MessagingContext.cpp#L116-L121

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by jepenven-silabs** [comment]
Comment is not present anymore
