### ISSUE TITLE
742): restart CHIP exe

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14167]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/Linux/ConfigurationManagerImpl.cpp#L305-L310

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by andy31415** [comment]
@woody-apple - I am unsure if this should be v1: the log says "not implemented" and generally if chip is embedded, it is unclear to me if a restart of the app is possible or even desirable.
