### ISSUE TITLE
change the code to using IPv6 address

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14160]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/EFR32/ConnectivityManagerImpl_WIFI.cpp#L427-L432

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by cecille** [comment]
started by mrfinesse99 (narayan.mohanram@silabls.com) - for some reason I can't assign this issue.
