### ISSUE TITLE
756) Add FabricState support

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14180]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/android/CHIPPlatformConfig.h#L30-L35

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by bzbarsky-apple** [comment]
CHIP_CONFIG_ENABLE_FABRIC_STATE does not exist anymore...
