### ISSUE TITLE
Define a Singleton instance of CHIP Group Key Store here

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14191]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/nxp/k32w/k32w0/ConfigurationManagerImpl.cpp#L41-L46

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by jepenven-silabs** [comment]
Closing as TODO is not present in said file anymore
