### ISSUE TITLE
What do we do when we abort?

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14197]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/platform/qpg/OTAImageProcessorImpl.cpp#L132-L137

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by holbrookt** [comment]
Assigning to @tima-q who introduced this TODO. Doesn't seem critical for 1.0

**Comment by tima-q** [comment]
TODO removed in subsequent updates. Abort will reset received bytes - updated in #14388
