### ISSUE TITLE
Remove use of hardcoded time during CASE setup

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14202]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/protocols/secure_channel/CASESession.cpp#L1338-L1343

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by holbrookt** [comment]
Pankaj, it looks like you added this TODO recently. Is this something that needs to be done for 1.0?
