### ISSUE TITLE
The SetPeerNodeId method should not be exposed; PASE sessions

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14203]
should not need to be told their peer node ID

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/protocols/secure_channel/PASESession.h#L93-L98

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by tcarmelveilleux** [comment]
This was fixed via other changes over time.
