### ISSUE TITLE
Fix Message Counter Sync to use group key

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14204]
TestMessageCounterManager.cpp&quot;,

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/protocols/secure_channel/tests/BUILD.gn#L15-L20

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by kghost** [comment]
@17622 This PR migrated all test-cases to use async transport, so `DrainAndServiceIO` may be needed in variety places when re-enable these tests.
