### ISSUE TITLE
use 0xffff to match any key id, this is a temporary solution for

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14215]
InteractionModel, where key id is not obtainable. This will be removed when InteractionModel is migrated to messaging layer

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/transport/SecureSessionTable.h#L28-L33

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by mrjerryjohns** [comment]
Not relevant anymore/is stale. Closing.
