### ISSUE TITLE
fill other group subjects fields

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14212]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/transport/GroupSession.h#L42-L47

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by jepenven-silabs** [comment]
Was completed by @mlepage-google
