### ISSUE TITLE
6652): This is a stub implementation, should be replaced by the real one when CASE and PASE is completed

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14213]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/transport/PairingSession.h#L88-L93

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by woody-apple** [comment]
Todo introduced here.

**Comment by kghost** [comment]
The initial value of message counter is always one. close this issue.
