### ISSUE TITLE
13711): this check won't work until the issue is addressed

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14214]
false

---

https://github.com/project-chip/connectedhomeip/blob/e169fcf99510c98ea16504e77c7fd8bf86f6b806/src/transport/SecureSession.h#L123-L128

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in e169fcf99510c98ea16504e77c7fd8bf86f6b806.

**Comment by bzbarsky-apple** [comment]
The code is in `AdoptFabricIndex` now, #13711 is fixed, and the TODO comment is gone.
