### ISSUE TITLE
[ TC-DIAG-TH_NW-1.2]- could not able to verify channel attribute value ,Need yaml support for this

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#14225]
Summary:
 not able to verify channel attribute value,need yaml support for this 
Test Plan Screenshot:
![2022-01-25_16-07](https://user-images.githubusercontent.com/57476670/150962285-595980a6-7038-4b94-867f-34038456384f.png)
Spec-Screenshot :
![2022-01-25_16-15](https://user-images.githubusercontent.com/57476670/150962637-506c1299-fbed-4264-ae6c-27453dab8d4a.png)

**Comment by vivien-apple** [comment]
@kowsisoundhar12 Sorry I'm not sure to understand the issue. I assume `Channel` contains a number which is the 802.15.4 channel number so likely some value between 11 and 26 ?
Why are you not able to verify that ?

**Comment by kowsisoundhar12** [comment]
@vivien-apple i have tried the various value inbetween 11 and 26 for channel attribute  but getting value mismatch issue
![2022-02-02_10-39](https://user-images.githubusercontent.com/57476670/152097078-a49a9ea4-2cff-4377-a1d5-3057897225ab.png)
![2022-02-02_10-49](https://user-images.githubusercontent.com/57476670/152097356-ab2d6431-5559-434d-aa0d-302ef254b887.png)
[err-logs.zip](https://github.com/project-chip/connectedhomeip/files/7983761/err-logs.zip)

**Comment by vivien-apple** [comment]
@kowsisoundhar12 
So per my understanding what you want is to have a `configuredChannel` field in the config section that defaults to `0` for CI.
Then instead of `12` (or any other number you need to use 'configuredChannel`.

This setting should let you pass `--configured-channel` as a command line argument to the command depending on the configured channel of the thread interface.

**Comment by raju-apple** [comment]
Script modification needed

**Comment by kowsisoundhar12** [comment]
@raju-apple @vivien-apple i have updated the script based on above suggestion  and tested ,its working fine 
please refer attached screenshot and logs 
![2022-03-22_15-33](https://user-images.githubusercontent.com/57476670/159458498-0b8a5632-314d-445b-8396-ef412041f878.png)
[execution-log-march22.zip](https://github.com/project-chip/connectedhomeip/files/8323307/execution-log-march22.zip)
