### ISSUE TITLE
TC-GENDIAG-1.1 NetworkInterfaceType

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/connectedhomeip#14236]
#### Problem
typedef struct _NetworkInterfaceType
{
    chip::CharSpan Name;
    bool FabricConnected;
    bool OffPremiseServicesReachableIPv4;
    bool OffPremiseServicesReachableIPv6;
    chip::ByteSpan HardwareAddress;
    uint8_t Type;
} NetworkInterfaceType;

Is missing IPV4 Address and IPV6 Address that the test case is looking for.

 #### Proposed Solution
Add IPV4 and IPV6 Mac addresses

**Comment by franck-apple** [comment]
dupe of #14840. Closing.
