### ISSUE TITLE
SaveAs keyword does not seem to work in Darwin

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#14237]
Summary:
              when we use saveAs keyword its failing in Darwin value does not get saved and gets checked with zero as per over observation but when we use hard coded values it works fine.

YAML screenshot:
![image](https://user-images.githubusercontent.com/84442963/150998734-49b85726-7b04-49c6-937c-a8d3be0c9bd5.png)

Execution log and screenshot :
![image](https://user-images.githubusercontent.com/84442963/150998609-d89fb391-4c0a-4e65-8cdb-5d022fb7461c.png)
[Build Darwin.zip](https://github.com/project-chip/connectedhomeip/files/7934545/Build.Darwin.zip)

**Comment by raju-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/14322
