### ISSUE TITLE
add more capabilities

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14247]
false

---

https://github.com/project-chip/connectedhomeip/blob/d0cbf834ccb8d466970de2456e61b5f6412d9bdc/src/access/AccessControl.h#L322-L327

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in d0cbf834ccb8d466970de2456e61b5f6412d9bdc.

**Comment by mlepage-google** [comment]
This is covered by issue #14455

**Comment by woody-apple** [comment]
Closing this as a duplicate
