### ISSUE TITLE
The second arg here is wrong, but we need to fix the signature of

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14245]
OnOpenPairingWindowFailureResponse and how we send some commands to fix that.

---

https://github.com/project-chip/connectedhomeip/blob/d0cbf834ccb8d466970de2456e61b5f6412d9bdc/src/controller/CHIPDeviceController.cpp#L400-L405

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in d0cbf834ccb8d466970de2456e61b5f6412d9bdc.

**Comment by cecille** [comment]
This was fixed by Vivien in https://github.com/project-chip/connectedhomeip/pull/13371/files#diff-30c3779ffb95f404ea48b1ed6319a810a1f5639a9b035002f11a44193b4cddbeL418.
