### ISSUE TITLE
What about the cluster-specific part of the status?

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14249]
false

---

https://github.com/project-chip/connectedhomeip/blob/d0cbf834ccb8d466970de2456e61b5f6412d9bdc/src/darwin/Framework/CHIP/CHIPError.mm#L39-L44

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in d0cbf834ccb8d466970de2456e61b5f6412d9bdc.

**Comment by woody-apple** [comment]
Let's just have a sub NSError here

**Comment by bzbarsky-apple** [comment]
What we current have implemented is:
```
/**
 * MatterInteractionErrorDomain contains errors that represent a Matter
 * StatusIB error.  These represent errors reported by the other side of a
 * Matter interaction.
 *
 * When the code is MatterInteractionErrorCodeFailure the userInfo may have a
 * key named @"clusterStatus" whose value is the cluster-specific status that
 * was reported.  This key will be absent if there was no cluster-specific
 * status.
 */
```

We could do the sub NSError instead if that's better?

**Comment by woody-apple** [comment]
Works fine as is :)

**Comment by woody-apple** [comment]
@bzbarsky-apple
