### ISSUE TITLE
Missing various defines/declarations in SiLabs code contribution

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#1425]
#### Problem
I am trying to compile against some of the headers from https://github.com/project-chip/connectedhomeip/pull/1164 and running into a few missing definitions:

* [x] `EmberIncomingMessageType`
* [x] `EmberOutgoingMessageType`
* [x] `EUI64_SIZE`
* [x] `EMBER_ENCRYPTION_KEY_SIZE`
* [x] `SIGNED_ENUM`
* [x] `EmberEventControl` -- I guess this is in the `ember-types.h` in the SDK.  Not sure what the license status there is.
* [x] `EmberStatus` -- Also in `ember-types.h` in the SDK
* [x] `EXTENDED_PAN_ID_SIZE` -- Also in `ember-types.h` in the SDK
* [x] `EmberEndpointDescription`
* [x] `EmberZigbeePacketType`
* [x] `EmberZigbeeNetwork`
* [x] `EmberPacketAction`
* [x] `EmberZdoStatus`
* [x] `EmberBindingTableEntry`
* [x] `EmberInitialSecurityState`
* [x] `EmberDeviceUpdate`
* [x] `EmberJoinDecision`
* [x] `EmberKeyStatus`
* [x] `EmberAfPluginNetworkSteeringJoiningState`
* [x] `SleepModes`
* [x] `EmberNetworkStatus` -- Also in `ember-types.h` in the SDK
* [x] `EmberNetworkParameters` -- Also in `ember-types.h` in the SDK
* [x] `EmberMessageBuffer` -- Also in `ember-types.h` in the SDK
* [x] `EmberVersion` -- Also in `ember-types.h` in the SDK
* [x] `EmberChildData`
* [x] `EMBER_WILDCARD_PROFILE_ID`
* [x] `EMBER_MAXIMUM_STANDARD_PROFILE_ID`
* [x] `EMBER_OUTGOING_DIRECT`
* [x] `EMBER_UNKNOWN_NODE_ID`
* [x] `EMBER_OUTGOING_VIA_ADDRESS_TABLE`
* [x] `EMBER_OUTGOING_VIA_BINDING`
* [x] `EMBER_OUTGOING_MULTICAST`
* [x] `EMBER_OUTGOING_BROADCAST`
* [x] `EMBER_SUCCESS` -- It's in the SDK
* [x] `EMBER_BROADCAST_ADDRESS` -- It's in the SDK
* [x] `UNUSED_VAR` -- It's in the SDK
* [x] `EMBER_INVALID_ENDPOINT` -- It's in the SDK
* [x] `EMBER_MAX_802_15_4_CHANNEL_NUMBER`  -- It's in the SDK
* [x] `EMBER_MIN_802_15_4_CHANNEL_NUMBER`  -- It's in the SDK
* [x] `EMBER_PHY_INVALID_CHANNEL`  -- It's in the SDK
* [x] `EMBER_MAX_SUBGHZ_CHANNEL_NUMBER_ON_PAGES_28_30_31`
* [x] `EMBER_MAX_SUBGHZ_CHANNEL_NUMBER_ON_PAGE_29`
* [x] `EMBER_NO_NETWORK`
* [x] `EMBER_LIBRARY_NOT_PRESENT` -- It's in the SDK
* [x] `EMBER_ACCEPT_PACKET`
* [x] `EMBER_ZDP_NOT_SUPPORTED`
* [x] `EMBER_BROADCASTE_ENDPOINT`
* [x] `MEM*` macros -- these are in the SDK, but now that I've looked at that, it's not 100% clear to me what the licensing is for us just using the C stdlib versions...
* [x] `BIT` -- It's in the SDK
* [x] `LOW_BYTE`  -- It's in the SDK
* [x] `HIGH_BYTE`  -- It's in the SDK
* [x] `BYTE_0` -- It's in the SDK
* [x] `BYTE_1` -- It's in the SDK
* [x] `BYTE_2` -- It's in the SDK
* [x] `BYTE_3` -- It's in the SDK
* [ ] `MAIN_FUNCTION_PARAMETERS`
* [x] `EmberBindingType`
* [x] `EmberJoinMethod`
* [x] `EmberVersionType`
* [x] `EmberEventUnits`
* [x] `EmberTaskId`

 #### Proposed Solution
Figure out which of these should be defined in the ZCL code (e.g. in `types_stub.h`), which should be defined in CHIP somehow, and which we just don't need (e.g. because we can remove the parts of the SiLabs code/headers that use them).  then take appropriate action.

@bhaskar-apple @selissia

**Comment by rwalker-apple** [comment]
I'm also looking for:

- [ ]  `EmberApsFrame`

**Comment by bhaskar-apple** [comment]
@bzbarsky-apple - some of these are to do with security / networking e.g. `EmberInitialSecurityState` 
We may not need them as we have our own layer. And might be safe to remove any code that uses it.

**Comment by bzbarsky-apple** [comment]
>  EmberApsFrame

@rwalker-apple It's in https://github.com/project-chip/connectedhomeip/pull/1164 (added after you grabbed your copy of it).  See https://github.com/project-chip/connectedhomeip/pull/1164/commits/113fac2de64556ad1a4731428d88c88f747b1e84

**Comment by bzbarsky-apple** [comment]
> We may not need them as we have our own layer. And might be safe to remove any code that uses it.

That seems plausible.  For now I just listed the things that were missing so we can evaluate each one and decide whether we need its definition from SiLabs or not and track that happening.

**Comment by bhaskar-apple** [comment]
> > We may not need them as we have our own layer. And might be safe to remove any code that uses it.
> 
> That seems plausible. For now I just listed the things that were missing so we can evaluate each one and decide whether we need its definition from SiLabs or not and track that happening.

That's fair. Let's get these all in then! :)

**Comment by bzbarsky-apple** [comment]
To be clear, what I'd really like here is for @wehale or @selissia or @tecimovic to go through the list and give us some guidance on which of these we really are likely to need and how we should get them vs which ones we should just remove the code that uses them or change it to use CHIP types.

**Comment by wehale** [comment]
Most of these are specifically related to ZigbeePro so I don't think you want them in CHIP, you want some CHIP equivalent. We should go through them, but I can see that, since they are not included in the open source they come from the stack which is a ZigbeePro Stack.

**Comment by wehale** [comment]
Lets plan to go through these with @tecimovic, @selissia, for each I expect you need to know, where it comes from, what it is used for and if it is relevant to CHIP. This is exactly the crusty portion of the interface we're going to run into where some CHIP equivalents will need to be provided in order to bolt this onto CHIP

**Comment by selissia** [comment]
I plan to go through this in the next couple of days.

________________________________

**Comment by bzbarsky-apple** [comment]
That sounds lovely.  I don't know that we need a sync meeting to go through these; async short text blurbs would be just fine on my end.

**Comment by selissia** [comment]
[types_stub.zip](https://github.com/project-chip/connectedhomeip/files/4899449/types_stub.zip)
Attaching updated types_stub.c here as the commits to my private fork are not propagated to the PR.

**Comment by selissia** [comment]
Added all missing definitions in the attachment above. 
Many of these types and functions that use them are not needed and should be purged from the code. Some of these are:
EmberZigbeePacketType
EmberZigbeeNetwork
SleepModes

**Comment by bzbarsky-apple** [comment]
@selissia Thank you for that zip file!

I grabbed the header from it, with the following modifications:

1. `EMBER_MIN_802_15_4_CHANNEL_NUMBER` should be 11, not 1.  Probably doesn't matter for CHIP anyway.
2. `EmberNetworkStatus` was in the header twice; I just removed the second declaration.

It's still missing `EMBER_BROADCAST_ENDPOINT`, `MEMSET`, `MEMCOPY`, `MEMMOVE`, `MEMCOMPARE`, `BIT`, `LOW_BYTE`, `HIGH_BYTE`, `BYTE_0`, `BYTE_1`, `BYTE_2`, `BYTE_3`, `MAIN_FUNCTION_PARAMETERS`.  Some of those I had not managed to get on the list, apparently; some might have gotten missed while going through the list.

**Comment by selissia** [comment]
Attached a file with missing definitions. Looks like `EmberBindingType` might actually be needed, the rest I think can be made into `uint8_t` , I included them anyway.

[missing_types.zip](https://github.com/project-chip/connectedhomeip/files/4914820/missing_types.zip)

**Comment by bzbarsky-apple** [comment]
Thanks, that is very helpful.  I assume you're OK with me just fixing the 6 items from <https://github.com/project-chip/connectedhomeip/issues/1425#issuecomment-657740924>, in terms of licensing?

**Comment by selissia** [comment]
> I assume you're OK with me just fixing the 6 items from #1425 (comment), in terms of licensing?
Yes, absolutely.

**Comment by bzbarsky-apple** [comment]
One other compile issue I ran into: `types_stub.h` needs to include `string.h` for the `mem*` functions.  With that fixed, things are good now.
