### ISSUE TITLE
Address review comments on PR 12969

### ISSUE THREAD

**Issue by chrisdecenzo** [project-chip/connectedhomeip#14279]
#### Problem
- Not all comments in [PR](https://github.com/project-chip/connectedhomeip/pull/12969) were addressed  

 #### Proposed Solution
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r792145585 - `LoadContentApp` in `examples/tv-app/linux/AppImpl.h` and various other places should perhaps take `CatalogVendorApp` by reference, not by value.
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r792155710 - `bool Matches(CatalogVendorApp app)` should perhaps take the thing to match by reference.
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r787315546 - The `CreateBindingWithCallback` API should not exist and _certainly_ should not be using the old CHIPClusters command API we are trying to remove.
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r789401850 - Same thing about `CreateBindingWithCallback`.
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r787279597
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r787284766 - `kCatalogVendorId` and various vendor id use in `examples/tv-app` should probably use `chip::VendorId`.
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r787285046 - Same thing about VendorId.
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r787298221 - ContentLauncherManager::mSupportedStreamingProtocols should be declared to be of type `std::underlying_type_t<relevant-spec-enum>` instead of hardcoding `uint32_t`.
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r787308767 - Can we build ContentApp.cpp and ContentAppPlatform.cpp from somewhere (e.g. `src/app/BUILD.gn`) where they will be compiled with `-Wconversion`?  Though it's possible this is not relevant and they _are_ being built that way, at least for the Linux tv-app.  Should check!
- https://github.com/project-chip/connectedhomeip/pull/12969#discussion_r787314098 - Use of ApplicationLauncherApplication (from af-structs.h) instead of the cluster-objects struct for that type, which necessitates back-and-forth conversion code.

**Comment by woody-apple** [comment]
These all look addressed, please re-open if not!
