### ISSUE TITLE
Use AutoValue for inner classes. }}

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14287]
false

---

https://github.com/project-chip/connectedhomeip/blob/1202bc79f8a53c0b1515851bae0b9e295c2b79fc/src/controller/java/templates/ChipStructs-java.zapt#L11-L16

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in 1202bc79f8a53c0b1515851bae0b9e295c2b79fc.

**Comment by holbrookt** [comment]
Austin, it looks like this came from a recent PR of yours. It doesn't seem like this is necessary for 1.0, but if it is, can you relabel it?

**Comment by austinh0** [comment]
This is not necessary for 1.0, thanks.
