### ISSUE TITLE
event notification for newly created ACL entry

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14285]
false

---

https://github.com/project-chip/connectedhomeip/blob/1202bc79f8a53c0b1515851bae0b9e295c2b79fc/src/app/clusters/operational-credentials-server/operational-credentials-server.cpp#L76-L81

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in 1202bc79f8a53c0b1515851bae0b9e295c2b79fc.

**Comment by mlepage-google** [comment]
This is already tracked by #14326, what do I do with this issue, can we close it?

**Comment by harimau-qirex** [comment]
Duplicate of #14326.

**Comment by mlepage-google** [comment]
Yes, duplicate, thanks. And I just tested this in the REPL, it is working on master.
