### ISSUE TITLE
remove hard coded fabric index once GroupDataProvider->Decrypt is implemented

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14292]
false

---

https://github.com/project-chip/connectedhomeip/blob/1202bc79f8a53c0b1515851bae0b9e295c2b79fc/src/transport/SessionManager.cpp#L620-L625

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in 1202bc79f8a53c0b1515851bae0b9e295c2b79fc.

**Comment by jepenven-silabs** [comment]
Fixed in SDK
