### ISSUE TITLE
CASE auth fail after ESP32 crash

### ISSUE THREAD

**Issue by Kxuan** [project-chip/connectedhomeip#14308]
#### Problem
connectedhomeip commit id: b0af6ba42b6ce494748f18ecf3e054a400b8f45b  (TE7.5)
TC-MF-1.17 commission device with 3 TH.
When step 13 (TH_CR2 starts a commissioning process with DUT_CE) is executed, DUT is crashed. (due to LoadProhibited in `chip::Ble::BLEEndPoint::ReleaseBleConnection`).

And when ESP32 reboot automatically, TH1 is unable to authenticate with DUT. 

 #### Proposed Solution
<suggested fix, suggested enhancement>
[dut.log](https://github.com/project-chip/connectedhomeip/files/7940079/dut.log)
[th1.log](https://github.com/project-chip/connectedhomeip/files/7940080/th1.log)
[th2.log](https://github.com/project-chip/connectedhomeip/files/7940081/th2.log)
[th3.log](https://github.com/project-chip/connectedhomeip/files/7940082/th3.log)

**Comment by bzbarsky-apple** [comment]
See #17568 and #17298
