### ISSUE TITLE
[TE-7-5] chip-tool pairing is flaky 

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#14316]
#### Problem
Hi,

so I'm trying to pair a accessory over `ble-thread` to the matter. And in 1 / 10 attempts I succeed. I also see different error behaviours. So I have attached some log files with different error cases. 

My setup is the Raspberry Pi 4 with the TE-7-5 image. I just us the "shipping" chip-tool which is present at `connectedhomeip/out/debug/standalone/chip-tool`.  I'm also using as suggested by the test description document the `connectedhomeip:te7` docker image. 

Here are 3 attempts to pair.
[chip-tool-log-0.txt](https://github.com/project-chip/connectedhomeip/files/7942461/chip-tool-log-0.txt)
[chip-tool-log-1.txt](https://github.com/project-chip/connectedhomeip/files/7942463/chip-tool-log-1.txt)
[chip-tool-log-2.txt](https://github.com/project-chip/connectedhomeip/files/7942464/chip-tool-log-2.txt)

**Comment by jmeg-sfy** [comment]
I got the same issues
