### ISSUE TITLE
third_party/openthread/ot-ifx: commit hash not on default branch cyw30739

### ISSUE THREAD

**Issue by tewarid** [project-chip/connectedhomeip#14318]
third_party/openthread/ot-ifx does not contain commit hash da522560fbff49f6b27bfef2139e898018c5f0f4 on default branch cyw30739
https://github.com/project-chip/connectedhomeip/blob/20c1f60a289e293246020a13aa85f81de5fec8c8/.gitmodules#L85

**Comment by turon** [comment]
This is blocking my local build currently after reset to `origin/master`.

Removing `v1_triage_split_10` tag.

**Comment by turon** [comment]
Try `git submodule update --init -f --recursive`.

**Comment by turon** [comment]
May have been introduced in PR #13491.

Entered tree as commit 1af90eb

Temp work-around to revert to dd209ce

**Comment by turon** [comment]
@woody-apple Are other Mac devs not seeing this?

**Comment by turon** [comment]
I pretty much just had to reclone the entire repo from scratch.
No combination of commands would restore my local tree:

```
git reset --hard origin/master
git restore third_party/openthread/ot-ifx
git submodule update --init --recursive -f
...
```

**Comment by woody-apple** [comment]
> @woody-apple Are other Mac devs not seeing this?

Not that I know of? However, it sounds like this is pretty broken.

**Comment by ItoddchouFX** [comment]
@turon  @tewarid  The issue is corrected in Infineon/ot-ifx-release. Let me if it works.

**Comment by tewarid** [comment]
Thanks @ItoddchouFX - our yocto linux build works now.
