### ISSUE TITLE
TC-SU-3.1 Pairing the Requestor using chip-tool fails with timeout

### ISSUE THREAD

**Issue by cm-s-dev** [project-chip/connectedhomeip#14335]
Problem

Unable to complete step 'Pair the Requestor using chip-tool'. Runs into a timeout/crash. Also seeing strings printed in logs that appear to be  not null-terminated.

`chip-tool pairing onnetwork-long 10867168584672756883 20202021 3844`

Test Setup:

Running all apps (ota-requestor/provider, chip-tool) on RPI, following instructions in te7.5 test plan verification steps. Works until the pair requestor step.

commit b0af6ba42b6ce494748f18ecf3e054a400b8f45b, TE7.5.

RPI Log
[tc-su-3.1_error.txt](https://github.com/project-chip/connectedhomeip/files/7943779/tc-su-3.1_error.txt)

**Comment by isiu-apple** [comment]
This is an old issue and pairing the Requestor using chip-tool has been working for a long time.
