### ISSUE TITLE
Add persistent storage support for DefaultOTAProviders attribute

### ISSUE THREAD

**Issue by carol-apple** [project-chip/connectedhomeip#14338]
#### Problem
https://github.com/project-chip/connectedhomeip/issues/13855 will add support for reading/writing of DefaultOTAProviders attribute. However, because persistent storage is not supported for AttributeAccessInterface, this attribute will not be persisted.

 #### Proposed Solution
Maybe use the app-provided attr store with a key based on the path

"app provided attr store" == "app provided storage delegate that the attr store uses to store stuff"

**Comment by yufengwangca** [comment]
You can set the storage type of the attribute to 'NVM', then the attribute should be persisted.

**Comment by carol-apple** [comment]
@yufengwangca This particular attribute is a list of structs and so I had to set it to `External` and add support for it directly through AttributeAccessInterface. AFAIK, persistent storage for `External` is up to the implementation for AttributeAccessInterface. Unless there's something else I'm missing?

**Comment by hrajendran-samsung** [comment]
Based on asking/looking around, it seems that the way to go would be to use the DefaultAttributePersistenceProvider. The attribute values ended up being stored in /tmp/chip_kvs , bas64 encoded I think.

**Comment by hrajendran-samsung** [comment]
@Damian-Nordic suggested the following:

An implementation would be provided by the application but we could provide GenericOTARequestorStorage which would implement the methods using KeyValueStoreMgr().XXX functions

```
class OTARequestorStorage
{
virtual CHIP_ERROR StoreDefaultProviderList(...) = 0;
virtual CHIP_ERROR LoadDefaultProviderList(...) = 0;

virtual CHIP_ERROR StoreCurrentProvider(...) = 0;
virtual CHIP_ERROR LoadCurrentProvider(...) = 0;

virtual CHIP_ERROR StoreUpdateToken(...) = 0;
virtual CHIP_ERROR LoadUpdateToken(...) = 0;

...
};

```
