### ISSUE TITLE
Retry git checkout in CI

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14345]
#### Problem
Occasionally git checkout fails

 #### Proposed Solution
we should retry this once

**Comment by woody-apple** [comment]
Here's another: https://github.com/project-chip/connectedhomeip/runs/4966936145?check_suite_focus=true

**Comment by woody-apple** [comment]
And another: https://github.com/project-chip/connectedhomeip/runs/4968409257?check_suite_focus=true

**Comment by turon** [comment]
Improving CI is always good.
Removing `v1_triage_split_4`.

**Comment by woody-apple** [comment]
Agree, however not seeing this as much, moving to V1.X
