### ISSUE TITLE
This delegate is now deprecated given we've shifted to narrower delegates scoped to each interaction type. This will

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14341]
false

---

https://github.com/project-chip/connectedhomeip/blob/12db26db2662c4ea7a819d0758e16084d644f33b/src/app/InteractionModelDelegate.h#L50-L55

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in 12db26db2662c4ea7a819d0758e16084d644f33b. It&#x27;s been assigned to @mrjerryjohns because they committed the code.

**Comment by mrjerryjohns** [comment]
This is done.
