### ISSUE TITLE
[TC-MC-10.5] chip-tool `launch-urlrequest` command in `contentlauncher` cluster returns sample data for TE7.5

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#14373]
#### Problem
Running the commands for Steps 1-5 all return sample data instead of proper error codes mentioned in the expected results of the test steps shown below. 

Testing on TE7.5 commit: `b0af6ba42b6ce494748f18ecf3e054a400b8f45b`

3.12.5. [TC-MC-10.5] Launch URL Verification (DUT as Server)
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/80923273/151288984-c1f4abee-417d-4ab9-8058-dde16ef0e888.png">
https://github.com/CHIP-Specifications/chip-test-plans/blob/TE_7_5_updates_IDM/src/cluster/media.adoc#3125-tc-mc-105-launch-url-verification-dut-as-server

 #### Logs
Lines of interest:

> ./out/debug/chip-tool contentlauncher launch-urlrequest https://csa-iot.org/ HelloWorld 1234 1

`[1643074824356] [18627:5810601] CHIP: [TOO]   data: exampleData
`

>  ./out/debug/chip-tool contentlauncher launch-urlrequest https://badurl HelloWorld 1234 1

`[1643074859675] [18629:5810779] CHIP: [TOO]   data: exampleData
`

> ./out/debug/chip-tool contentlauncher launch-urlrequest https://csa-iot.org/badauth HelloWorld 1234 1

`[1643074895062] [18634:5811135] CHIP: [TOO]   data: exampleData
`

[consolidated_mac_accessory_TC-MC-10-5.txt](https://github.com/project-chip/connectedhomeip/files/7947454/consolidated_mac_accessory_TC-MC-10-5.txt)

**Comment by naveenkommareddi** [comment]
This should be the same issue as #17896 . @liamgonyea  to reverify and confirm.
