### ISSUE TITLE
Need YAML support for "value and constraints" check in one step

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#14375]
Summary:
              Need YAML support for  value and constraints check in one step .if both "value" and "constraints" is set the "constraints" gets ignored, infact. If you look for the generated code for this function, it just checks the value, not the type.

YAML screenshot: 
![image](https://user-images.githubusercontent.com/84442963/151294829-e720ac81-d59e-4f6a-98a3-54f61557a5b2.png)

**Comment by vivien-apple** [comment]
It has been fixed by https://github.com/project-chip/connectedhomeip/pull/13658
