### ISSUE TITLE
review LGTM.com warnings and address them

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1440]
#### Problem

https://lgtm.com/projects/g/project-chip/connectedhomeip/alerts/?mode=list 

Presents various potential code problems, like 'IPAddress has an assignment operator, but no copy constructor' or 'CHIPCryptoPALOpenSSL.cpp has a comparison that is always true'

 #### Proposed Solution
Review the list of issues and address them.

**Comment by woody-apple** [comment]
Closing for now, will open some more once I have CodeQL sane and not 1900+ items!
