### ISSUE TITLE
[TC-WNCV-2.3] Yaml is missing:  Mode Attribute with server as DUT -> need SDK support

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#14406]
#### Problem
<what's wrong or missing, please include any applicable:
 * Need Bit reading and checking 
 * Might require small update on the cluster Window-covering
 

 #### Proposed Solution
They should be easy to add once #13024 is done

**Comment by holbrookt** [comment]
looks critical due to cert label. Jonathon - can you confirm this is required for 1.0?

**Comment by jmeg-sfy** [comment]
Yes it is

**Comment by jmeg-sfy** [comment]
TC-WNCV-2.3] Mode Attribute with server as DUT - Needs an SDK implementation
