### ISSUE TITLE
Add custom required privilege definitions for clusters that need them

### ISSUE THREAD

**Issue by mlepage-google** [project-chip/connectedhomeip#14419]
IM operations have default required privileges (e.g. view for read attribute, operate for write attribute) but can override these defaults with custom required privileges (e.g. administer for anything to do with Access Control Cluster).

This functionality was intended to be provided by ZAP (#10246) and Ember (#10247). In the interim, it is being provided by a simple class (#14283).

Regardless, there is still the task (this issue) of populating the data for the custom required privileges. Each cluster that has custom (non-default) required privileges will have to specify them in src/RequiredPrivilege.cpp (interim approach) and cluster XML (desired ZAP/Ember approach).

**Comment by mlepage-google** [comment]
Reopening just so I have an issue to track adding the actual XML declarations for any remaining custom privileges. Normally this would be done by cluster authors, but it's easier overall for me to do them in one big swoop.

**Comment by mlepage-google** [comment]
I think after #17115 and #17134 PRs it's really only the **pump control and configuration cluster** that needs updating; that one's waiting for a small spec change regarding the privileges (which currently require manage for read as well as write, but probably will be updated to only require manage for read).

**Comment by mlepage-google** [comment]
Probably should also wait for this other pump configuration-and-control-cluster.xml change to land.
PR #17181

**Comment by tlykkeberg-grundfos** [comment]
Will be fixed for pump-configuration-and-control-cluster in #17181

**Comment by mlepage-google** [comment]
I do see @tlykkeberg-grundfos is handling the last access definitions for pump in #17181 so I will close this issue now. Thanks!
