### ISSUE TITLE
DefaultDeviceAttestationVerifier does not use correct vendorId and productId

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#14434]
#### Problem

Because the `DeviceCommissioner` code had no code to read basic information, there is no plumbing to use the correct device VID/PID during device attestation procedure to test the CD and DAC metadata, which are required by spec.

The code currently uses a fixed value that is not correct whenever a real DAC is used:

```
void DefaultDACVerifier::VerifyAttestationInformation(const ByteSpan & attestationInfoBuffer,
                                                      const ByteSpan & attestationChallengeBuffer,
                                                      const ByteSpan & attestationSignatureBuffer, const ByteSpan & paiDerBuffer,
                                                      const ByteSpan & dacDerBuffer, const ByteSpan & attestationNonce,
                                                      Callback::Callback<OnAttestationInformationVerification> * onCompletion)
{

    ......... A LOT OF OTHER CODE.........
    
    {
        CHIP_ERROR error = CHIP_NO_ERROR;
        ByteSpan certificationDeclarationSpan;
        ByteSpan attestationNonceSpan;
        uint32_t timestampDeconstructed;
        ByteSpan firmwareInfoSpan;
        DeviceAttestationVendorReservedDeconstructor vendorReserved;
        ByteSpan certificationDeclarationPayload;

        DeviceInfoForAttestation deviceInfo{
            .vendorId    = 0xFFF1,
            .productId   = 0x8000, // TODO: Retrieve vendorId and ProductId from Basic Information Cluster
            .dacVendorId = dacVendorId,
            .paiVendorId = dacVendorId,
        };
```

In the above, there is `// TODO: Retrieve vendorId and ProductId from Basic Information Cluster` to fill the correct DeviceInfoForAttestation.

 #### Proposed Solution

Once there is code to read VID/PID during start of commissioning, we need to update the code above to take the right values.

This will require updating the structure of `VerifyAttestationInformation`.

To be more future proof, suggest making `VerifyAttestationInformation` replace the following args:
```
const ByteSpan & attestationInfoBuffer,
const ByteSpan & attestationChallengeBuffer,
const ByteSpan & attestationSignatureBuffer, const ByteSpan & paiDerBuffer,
const ByteSpan & dacDerBuffer, const ByteSpan & attestationNonce
```
with a new struct that encapsulates these, in addition to `const DeviceInfoForAttestation &`.

**Comment by cecille** [comment]
This is now complete. @tcarmelveilleux - if there is remaining work here, please re-open with details.
