### ISSUE TITLE
Clean up fabric filtered read

### ISSUE THREAD

**Issue by mlepage-google** [project-chip/connectedhomeip#14430]
See PR #13881 and particularly this conversation:
https://github.com/project-chip/connectedhomeip/pull/13881#discussion_r791407955

Essentially, if not using the generated cluster types for encode, they won't fabric filter if a MatchesFabricIndex method isn't provided. They also won't fail to compile or otherwise warn, so this is highly dangerous.

There is discussion in that conversation about various ways to address this. It should be addressed at the DM/IM level as appropriate, and then whatever changes need to happen to access control cluster (for whatever new mechanism is used for fabric filtered read) will have to happen.

**Comment by erjiaqing** [comment]
I guess this is resolved,

IsFabricScoped now requires "kIsFabricScoped" attribute always exists when encoding structs.

https://github.com/project-chip/connectedhomeip/blob/87d1d3e5bd09423f6012add27ccf6bd76cfdb063/src/app/data-model/FabricScoped.h#L36-L54
