### ISSUE TITLE
[TE 7.5] TC-GC-1.1 - GeneralCommissioning.BasicCommissioningInfoList

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/connectedhomeip#14456]
#### Problem
chip-tool generalcommissioning read basic-commissioning-info-list 1111 0
When the device is already comissioned
The list is empty.  
Test case says it should be reporting ID0 as 900 (fail safe timer 900 second)
See log file attached beginning at line 2214

 #### Proposed Solution
Behavior needs to be clarified if this is expected. 
Spec is not clear on behavior, so if this needs to be a spec issue.
[TC-GC-1-1.log](https://github.com/project-chip/connectedhomeip/files/7953900/TC-GC-1-1.log)

**Comment by bzbarsky-apple** [comment]
The current SDK implementation here is:
```
    case BasicCommissioningInfoList::Id: {
        // TODO: This should not be a list at all!
        return aEncoder.EncodeEmptyList();
    }
```

Like the comment says, it shouldn't be: per spec this is a struct, not a list.  Basically, this attribute was added without any sort of reasonable implementation, and we need to implement it.
