### ISSUE TITLE
CASE generates a report to all EP0 subscribers

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#14463]
#### Problem

Session establishment is causing reports on other subscribers' subscription. This should not have side effects.

Notably this means that the first report after running any 'chip-tool' command is a spurious report regarding the fabric list, and the real side effect is delayed by min report interval.

Cause seems to be
```
    void OnFabricRetrievedFromStorage(FabricInfo * fabric) override
    {
        emberAfPrintln(EMBER_AF_PRINT_DEBUG,
                       "OpCreds: Fabric 0x%" PRIu8 " was retrieved from storage. FabricId 0x" ChipLogFormatX64
                       ", NodeId 0x" ChipLogFormatX64 ", VendorId 0x%04" PRIX16,
                       fabric->GetFabricIndex(), ChipLogValueX64(fabric->GetFabricId()),
                       ChipLogValueX64(fabric->GetPeerId().GetNodeId()), fabric->GetVendorId());
        fabricListChanged();
    }
```

When the list didn't change, it was only loaded.

**Comment by bzbarsky-apple** [comment]
Fixed first by #16098 making us not call `OnFabricRetrievedFromStorage` for a fabric that was already in memory and not really being loaded from storage and second by #16587 removing the `LoadFromStorage` calls on random reads, instead doing all the loads at init time.
