### ISSUE TITLE
Add access control cluster to any example apps that don't have it yet

### ISSUE THREAD

**Issue by mlepage-google** [project-chip/connectedhomeip#14461]
It's in some example apps, will need to be added to the remaining ones.

**Comment by hrajendran-samsung** [comment]
Assigned to @hrajendran-samsung

**Comment by mlepage-google** [comment]
It does look like PR #14657 got all the example apps, and I tried a couple on Linux and they seemed to work. Closing, if we missed one, we'll have to get it separately.
