### ISSUE TITLE
[TC-PSCFG-1.1] missing `command-list `, `event-list` attributes in `powersourceconfiguration ` chip-tool cluster for TE7.5

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#14474]
#### Problem
When running TC-PSCFG-1.1, Step 4 and 5, the `command-list` and `event-list` attributes for the `powersourceconfiguration ` cluster.

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/80923273/151475362-bc39a8e6-963d-413a-b252-f3c1edb28b31.png">

#### Test Case
3.1.1. [TC-PSCFG-1.1] Global attributes with server as DUT
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/powersourceconfiguration.adoc#311-tc-pscfg-11-global-attributes-with-server-as-dut

#### Logs
TE7.5 commit: `b0af6ba42b6ce494748f18ecf3e054a400b8f45b`

`command-list`
> [1643335486193] [35487:7166913] CHIP: [TOO] Unknown attribute: command-list

`event-list`

> [1643335521455] [35489:7167126] CHIP: [TOO] Unknown attribute: event-list
[consolidated_mac_accessory_TC-PSCFG-1-1.txt](https://github.com/project-chip/connectedhomeip/files/7955278/consolidated_mac_accessory_TC-PSCFG-1-1.txt)

**Comment by bzbarsky-apple** [comment]
event-list is not supported in the SDK and won't be for 1.0.

command-list does not exist.  There are generated-command-list and accepted-command-list.
