### ISSUE TITLE
How to process incomming commands in case of Controller.

### ISSUE THREAD

**Issue by yonko-gospodinov** [project-chip/connectedhomeip#14485]
To send a command I can assign corresponding cluster to the target device and then send the desire command, but how I can receive and process incoming commands like IASZone#ZoneEnrollRequest?

**Comment by woody-apple** [comment]
@raju-apple Can you help here?

**Comment by bzbarsky-apple** [comment]
IASZone is not part of Matter 1.0, precisely because it's not clear how to map it onto the Matter interaction model.
