### ISSUE TITLE
TE7.5 [TC-MF-1.x] open-commissioning-window command timeout on slow device

### ISSUE THREAD

**Issue by ryan-ma** [project-chip/connectedhomeip#14490]
branch: TE7.5
device: ESP32 WiFi LED light blub (ESP32 single core 80MHz)

problem:
While testing TC-MF-1.x test case, open-commissioning-window command will timeout and fail.
```
[1643005362.786203][3333:3333] CHIP:-: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:232: CHIP Error 0x00000032: Timeout at ../../examples/chip-tool/commands/common/CHIPCommand.cpp:59
[1643005362.786302][3333:3333] CHIP:TOO: Run command failure: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:232: CHIP Error 0x00000032: Timeout
[1643005362.792823][3333:3333] CHIP:SPT: VerifyOrDie failure at ../../src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0
Aborted (core dumped)
```

I run the device at 80MHz single core. If ESP32 is run at 240MHz, the command will pass.

It looks similar to issue [#13929](https://github.com/project-chip/connectedhomeip/issues/13929)

**Comment by bzbarsky-apple** [comment]
@ryan-ma What is the exact command being run?

**Comment by ryan-ma** [comment]
@bzbarsky-apple I used this command `./chip-tool pairing open-commissioning-window 1 1 100 1000 3840`
I verified this problem persist in TE9. There is no issue if I run the device with 160MHz.
I captured the log of RPi controller and ESP32, both 80MHz failure and 160MHz passed case
[TC-MF-1.21-80MHz-Timeout-RPi-Controller.txt](https://github.com/project-chip/connectedhomeip/files/8713842/TC-MF-1.21-80MHz-Timeout-RPi-Controller.txt)
[TC-MF-1.21-160MHz-Passed-ESP32.txt](https://github.com/project-chip/connectedhomeip/files/8713843/TC-MF-1.21-160MHz-Passed-ESP32.txt)
[TC-MF-1.21-160MHz-Passed-RPi-controller.txt](https://github.com/project-chip/connectedhomeip/files/8713844/TC-MF-1.21-160MHz-Passed-RPi-controller.txt)
[TC-MF-1.21-80MHz-Timeout-ESP32.txt](https://github.com/project-chip/connectedhomeip/files/8713845/TC-MF-1.21-80MHz-Timeout-ESP32.txt)
.

**Comment by bzbarsky-apple** [comment]
Thank you, that is very helpful.  It looks like we are hitting the 5-second timeout for this command, which is probably (1) too short and (2) should be configurable anyway.  Let me create a PR to fix both.
