### ISSUE TITLE
[TC-WNCV-xx] YAML Update tests case to use hasMaskSet hasMaskClear to check bitmaps

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#14491]
Summary: 
              Need bitwise operator support in YAML for OperationalStatus attribute verification.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/151520599-c44f329b-9cdd-4706-9b85-9205f951357e.png)

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/151520945-3dc54cdc-aa50-417a-84f7-415966487dfa.png)

**Comment by jmeg-sfy** [comment]
linked to this https://github.com/project-chip/connectedhomeip/issues/13024

**Comment by raju-apple** [comment]
P3

**Comment by woody-apple** [comment]
Given the priority, moving this to post V1.
