### ISSUE TITLE
[OTA] chip-tool on Linux may send out an invalid CountryCode in the SetRegulatoryConfig command

### ISSUE THREAD

**Issue by selissia** [project-chip/connectedhomeip#14500]
#### Problem
When the chip-tool is running on Linux in the presence of another Matter application (e.g. OTA Provider app) the value of CountryCode sent in the SetRegulatoryConfig command. In all likelihood this is caused by some corruption of the key value store which on Linux is shared by all Matter apps.  

 #### Proposed Solution

**Comment by bzbarsky-apple** [comment]
Please pass `--KVS` args as needed to use separate stores for separate apps.
