### ISSUE TITLE
Report-event support in chip-tool is missing 

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#14518]
chip-tool does not have report events in clusters which support events

![image](https://user-images.githubusercontent.com/90545664/151592983-ec2b1556-d310-46e5-8fc5-cb219a7e686b.png)

**Comment by bzbarsky-apple** [comment]
@sowmyassp subscribe-event is right there, no?  That subscribes to event reports.

**Comment by andy31415** [comment]
Matter uses `subscribe` instead of `report`. Assuming this issue can be closed.
