### ISSUE TITLE
[Test_TC_DIAG_TH_NW_1_2]-getting type error for ChannelPage0Mask attribute

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#14525]
Summary:
ChannelPage0Mask  attribute is giving Type Error, while running with default value 0

Error screenshot:
![2022-01-28_22-17](https://user-images.githubusercontent.com/57476670/151598661-cfae5303-cfcc-4c0c-951f-a173b44ec5e7.png)
Testpaln Screenshot:
![2022-01-28_23-37](https://user-images.githubusercontent.com/57476670/151599084-a63e99b2-be44-4e5a-9904-1190b629346f.png)
Spec Screenshot 
![2022-01-28_23-37_1](https://user-images.githubusercontent.com/57476670/151599123-af3841c5-8f02-4af3-80b1-993304ce7d27.png)

**Comment by andy31415** [comment]
Looks like a duplicate of #14472

**Comment by andy31415** [comment]
Mistakenly marked duplicate. Sorry.

**Comment by vivien-apple** [comment]
@kowsisoundhar12 Sorry I don't understand the issue.
chip-tool currently has `ChannelMask` which is what `ChannelPage0Mask` used to be called back in the days - but somebody that has updated the spec has not updated the cluster description in the SDK.

So how can you run "ChannelPage0Mask attribute is giving Type Error, while running with default value 0" ?
Can you give me the steps to reproduce ?

**Comment by kowsisoundhar12** [comment]
@raju-apple ,I have ran this testcase ,now i am not getting any type error
![2022-02-25_10-09](https://user-images.githubusercontent.com/57476670/155655323-1d852a46-c0b8-4f72-9dbc-e082b7b9292b.png)
![2022-02-25_08-58](https://user-images.githubusercontent.com/57476670/155655329-78981ee3-07e2-4778-a5a6-6bcf0efa82a1.png)
![2022-02-25_08-57](https://user-images.githubusercontent.com/57476670/155655330-55baa71d-b9e8-47b3-9e9c-6b771b201ad3.png)

**Comment by kowsisoundhar12** [comment]
not observing this issue now,hence closing this issue
