### ISSUE TITLE
TE7.5 Mac chip tool testing - [TC-BRAC-2.1] partslist attribute not present

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#14538]
While testing Bridged Actions Cluster [TC-BRAC-2.1] Step 3a, partslist attribute for reading is not available in Mac Chip Tool.
<img width="976" alt="Screen Shot 2022-01-28 at 12 09 15 PM" src="https://user-images.githubusercontent.com/34750871/151614557-85e8c870-148e-4fb0-8d3e-c124537fc1be.png">

**Comment by bzbarsky-apple** [comment]
There is no "partslist" attribute in the Actions cluster (used to be Bridged Actions) in the spec, so the behavior here looks correct.
