### ISSUE TITLE
iOS tv-casting-app: Implement Content Launch command

### ISSUE THREAD

**Issue by sharadb-amazon** [project-chip/connectedhomeip#14559]
#### Problem
The iOS tv-casting-app does not send any Casting commands (like the Content Launch command)

 #### Proposed Solution
TBD

**Comment by turon** [comment]
1.0 spec describes commands: `LaunchContent Request`, `LaunchURL Request`, and `Launch Response`.
These would presumably need to be implemented for v1 for the ContentLauncher cluster to be part of 1.0.
Removing tag `v1_triage_split_4`

**Comment by woody-apple** [comment]
SDK supports this, but moving this tooling enhancement to post V1

**Comment by sharadb-amazon** [comment]
Addressed in https://github.com/project-chip/connectedhomeip/pull/19779
