### ISSUE TITLE
network cluster on EP1 on all clusters app has empty feature map

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#14565]
#### Problem
no features = useless cluster

 #### Proposed Solution
That's not right. Fix.

**Comment by bzbarsky-apple** [comment]
It's probably using the old network commissioning cluster impl.... We need to finish moving things over to the new one, but the new one requires new per-platform code to be written, so it mostly hasn't been happening.

**Comment by bzbarsky-apple** [comment]
This is fixed now, I believe.
