### ISSUE TITLE
TE7.5 [TC-MF-1.3] The coammand of ./chip-tool basic write node-label fails 

### ISSUE THREAD

**Issue by Minan-Tuyasmart** [project-chip/connectedhomeip#14575]
Problem：
[TC-MF-1.3] The coammand of ./chip-tool basic write node-label fails 

platform:
Testing image on RasPi：v1.7.img
Connectedhomeip commitID : b0af6ba
OTBR commitID：72bb3d45684f837e67e7f1ec20a9a8e3ac4a4419
lighting-app run on the EFR32MG24 board base on commitID : b0af6ba
[TC-MF-1.3.txt](https://github.com/project-chip/connectedhomeip/files/7963190/TC-MF-1.3.txt)
[otbr-log.txt](https://github.com/project-chip/connectedhomeip/files/7963191/otbr-log.txt)
[light-log.txt](https://github.com/project-chip/connectedhomeip/files/7963192/light-log.txt)

**Comment by bzbarsky-apple** [comment]
Log shows UNSUPPORTED_ATTRIBUTE for the write.  Sounds like the server was buggy and did not implement the mandatory attribute.....  I did verify that this attribute is implemented for all-clusters-app on tip and writing it works.
