### ISSUE TITLE
Events being sent on all the endpoints

### ISSUE THREAD

**Issue by chiragatal** [project-chip/connectedhomeip#14624]
#### Problem
 * expected behavior: Events triggered on the device should be sent only to a particular endpoint_id.
 * actual behavior: Events triggered are sent to all the endpoints that have the cluster included.
 * steps to reproduce: Create a device with 2 endpoints and both having the switch cluster. Trigger the SwitchLatched event on the device. The event gets reported on both the endpoints instead of just one.
 * reference: Check `OnSwitchLatched` in `switch-server.cpp`.

 #### Proposed Solution
 * The events should accept the endpoint_id also as an argument, and send the event just on that endpoint.

**Comment by dhrishi** [comment]
@yufengwangca Can you please check?

**Comment by yufengwangca** [comment]
@chiragatal The event is triggered on the device, it does not have the endpoint_id as an argument, so it gets logged to all endpoints on which the relevant cluster is enabled

**Comment by bzbarsky-apple** [comment]
The point is, the switch cluster API here is broken, no?  It should either know which endpoint is being addressed to start with (have per-endpoint delegates) or allow passing in the endpoint id from the caller.

Looks like the implementation in PR #13036 just does not make sense for a device with more than one switch on it....

**Comment by dhrishi** [comment]
The same is to be checked/implemented for all other utility/app clusters too that support events?

**Comment by bzbarsky-apple** [comment]
Probably worth it, yes...

**Comment by mrjerryjohns** [comment]
Taking off the IM label since this isn't an IM limitation but rather an issue with the app clusters.
