### ISSUE TITLE
Relative Humidity - In TC-RH- 1.1 the cluster revision value is  not matched with the expected outcome

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#14628]
In Relativehumidity testcase 1.1 (TC-RH-1.1),  the "cluster revision attribute" value must be 3 as per the spec. 
But the actual outcome is 2. This needs to be fixed as per spec.

Test Spec link:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/WaterContentMeasurement.adoc

 * expected behavior - cluster revision attribute - 3
 * actual behavior - cluster revision - 2
 
Actual command -  ./chip-tool relativehumiditymeasurement read cluster-revision 3 1
Actual logs are attached below 
[Relative humidity  1.1 DUT log.txt](https://github.com/project-chip/connectedhomeip/files/7978753/Relative.humidity.1.1.DUT.log.txt)
[Relative humidity 1.1 ctrl.txt](https://github.com/project-chip/connectedhomeip/files/7978845/Relative.humidity.1.1.ctrl.txt)

**Comment by somu1710** [comment]
For Relative humidity cluster still the cluster revision value is not matched with the spec.

**Comment by vivien-apple** [comment]
Duplicate of #17532
