### ISSUE TITLE
We may want to reject kUndefinedFabricIndex for writing fabric scoped data. mAccessingFabricIndex will be

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14633]
kUndefinedFabricIndex on PASE sessions.

---

https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/app/AttributeAccessInterface.h#L330-L335

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by bzbarsky-apple** [comment]
Fixed in #15442.
