### ISSUE TITLE
The implementation lives in ember-compatibility-functions.cpp, this should be replaced by IM command catalog look up

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14634]
https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/app/InteractionModelEngine.h#L309-L314

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by bzbarsky-apple** [comment]
Fixed in #14806
