### ISSUE TITLE
Do we need to check the modifier fabric here? Discuss with Spec team and add it if necessary.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14639]
https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/app/clusters/door-lock-server/door-lock-server.cpp#L2008-L2013

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by Morozov-5F** [comment]
Per discussion with @DanM-AssaAbloy in Slack, there's no need to perform this check in the code.

**Comment by woody-apple** [comment]
Thanks. Will remove the TODO.
