### ISSUE TITLE
Clear holiday schedules when they're implemented

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14640]
https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/app/clusters/door-lock-server/door-lock-server.cpp#L2307-L2312

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by Morozov-5F** [comment]
Holiday schedules are already implemented.
