### ISSUE TITLE
Change Endpoints to INT16U array once it is supported 

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14646]
https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/app/zap-templates/zcl/data-model/chip/bridged-actions-cluster.xml#L83-L88

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by bzbarsky-apple** [comment]
Duplicate of #14074
