### ISSUE TITLE
if the device library adds a network commissioning device type, this will need to be 1 per endpoint.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14648]
https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/controller/AutoCommissioner.h#L64-L69

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by cecille** [comment]
This is now obsolete - we check the feature maps of all network clusters on the device and select the endpoint in a different way.
