### ISSUE TITLE
Enable once attribute struct is supported

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14645]
https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/app/tests/suites/certification/Test_TC_MC_9_1.yaml#L68-L73

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by bzbarsky-apple** [comment]
Struct attributes are supported, but reading this attribute from all-clusters-app always returns failure.  This test should probably run against tv-app?
