### ISSUE TITLE
[TC-LC-1.1] Write command is not implemented

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#14737]
#### Problem

In Draft TE8 [TC-LC-1.1] there is a step "TH1 tries to write LabelList attribute of the DUT by setting Label = "Test_Label", Value= "Test_Value" but write command is not implemented so we cant run this step.
But in verification step they given a command " sudo ./chip-tool fixedlabel write label-list [room:bed
room]" which is not executable.

**Comment by woody-apple** [comment]
I'm not sure I understand what's being asked for here. Can you provide logs and the test steps please?
