### ISSUE TITLE
chip-tool-darwin implementation should use [[NSRunLoop currentRunLoop] run];

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#14734]
#### Problem
chip-tool-darwin's current implementation is using a C++ blocking loop and needs to be updated to use` [[NSRunLoop currentRunLoop] run]; ` and to stop loop with `CFRunLoopStop(CFRunLoopGetMain());`

**Comment by woody-apple** [comment]
@krypton36 is this required for v1?

**Comment by krypton36** [comment]
> @krypton36 is this required for v1?

No
