### ISSUE TITLE
 [TC-MC-5.2] and [TC-MC-5.3] CurrentChannel Attribute not available for Channel Cluster

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#14744]
Test Case ID:
[TC-MC-5.2] Change Channel by Number Verification
[TC-MC-5.3] Skip Channel Verification

CurrentChannel Attribute not found in chip-tool, unable to complete Step 3 for TC-MC-5.2 and steps 2,4 for TC-MC-5.3. This missing attribute makes it so the test case cannot be accurately performed because all other steps rely on knowing the CurrentChannel attribute's value
 
Specification References:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tv-channel-test-cases

Logs:
[[TC-MC-5.2 and 5.3] log.txt](https://github.com/project-chip/connectedhomeip/files/7995081/TC-MC-5.2.and.5.3.log.txt)

**Comment by vivien-apple** [comment]
That should be fixed by #14794 for the `chip-tool` side.
