### ISSUE TITLE
GlobalElements needs to be developed in SDK software. 

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#14750]
CHIP-tool SDK software has to implement the the following mandatory global elements, mentioned in the spec section 7.14.

1. Cluster Revision.
2. FeatureMap
3. AttributeList
4. EventList
5. ClientGeneratedCommandList
6. ServerGeneratedCommandList.
7. FabricIndex.

**Comment by bzbarsky-apple** [comment]
1, 2, 3, 5, 6 are implemented (though no all clusters that should declare 2).

7 was a recent spec change.  I filed https://github.com/project-chip/zap/issues/411 on some infrastructure we might need for it.

4 is tracked in https://github.com/project-chip/connectedhomeip/issues/15011
