### ISSUE TITLE
SessionHandle is unsafe

### ISSUE THREAD

**Issue by kpschoedel** [project-chip/connectedhomeip#14849]
#### Problem

`Transport::SessionHandle` uses `ReferenceCountedHandle<Transport::Session>`, which depends on `Session::Retain()` and `Release()`. However, `Session` has:

```
     virtual void Retain() {}
     virtual void Release() {}
```

and at least some subclasses are held in `SessionHandle` without overriding these. Lifetime errors arising from this have been masked for at least two known issues (#14444, #14512) by allocating subclasses from a `BitMapObjectPool` so that ASAN testing doesn't catch the incorrect lifetimes.

 #### Proposed Solution

- Implement `Retain()` and `Release()` for subclasses held in `SessionHandle`.
- Make `Session::Retain()` and `Release()` pure virtual so that `SessionHandle` can't be used without an actual reference count implementation.
- Use `ObjectPool` rather than `BitMapObjectPool` so that ASAN on heap builds can catch lifetime errors.

**Comment by kghost** [comment]
`SecureSession` is not reference counted, all `SessionHandle` are allocated on the stack which must be automatically released after a "schedule".

My solution is:
1. Make session deleted `ExpireInactiveSessions`.
2. Prune the session after a "schedule".

**Comment by kghost** [comment]
For SecureSession, the removal of it happens in SessionManager::ExpiryTimerCallback, which runs in a timer, so it can not race with any other part using the session.

For UnauthenticatedSession, It is reference counted, for no change for dangling.

For GroupSession, the issue will be tracked by #14512
