### ISSUE TITLE
Make doc does not work

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1486]
#### Problem
`make help` claims that doc should work .Attempting it results in failure.

 #### Proposed Solution
Figure out if we should have a doc step and if yes, then make it actually work

**Comment by andy31415** [comment]
@gerickson  found that `make -C docs` is the magic incantation.

`make help` should be updated then

**Comment by andy31415** [comment]
* the -C docs did something, however I still cannot see the output. Still needs investigation

**Comment by vivien-apple** [comment]
For info here is how I can successfully build docs from the vscode container on top of a clean tree:
```
 $ sudo apt-get install doxygen 
 $ mkdir build/documentation
 $ cd build/documentation
 $ ../../bootstrap-configure --enable-docs
 $ make docdist
```

Outputs should be in `build/documentations/docs/`

Beside the missing doxygen into the Dockerfile, not sure what else I need to fix besides documentation.

**Comment by vivien-apple** [comment]
Simpler:

```
$ sudo apt-get install doxygen
$ DOCS=1 make -f Makefile-Standalone
```

Outputs should be in `build/target_name/docs/html/`

**Comment by vivien-apple** [comment]
@andy31415 I added a PR with some doc.
I would like to know if the last steps works for you, and if so if the documentation PR is good enough.
