### ISSUE TITLE
[ESP32 bridge-app] How to start http server in parallel to matter stack?

### ISSUE THREAD

**Issue by VOMediola** [project-chip/connectedhomeip#14886]
When including "esp_http_server.h" in main I get no file found. Compiling command doesn't include all of esp-idf components, where can I change the build parameters to include http_server component?

**Comment by dhrishi** [comment]
@VOMediola Can you please add `esp_http_server` entry [here](https://github.com/project-chip/connectedhomeip/blob/master/examples/bridge-app/esp32/main/CMakeLists.txt#L50) in the bridge-app?

**Comment by VOMediola** [comment]
@dhrishi  thank you, that works. Can you exaplain why I need to require that, but not, for example, nvs_flash or esp_netif as a component?

Also, can you tell me what should I pay attention to when trying to use http server with matter? Do I need to init netif and create default event loop, or is it handled somwhere in Matter stack?
