### ISSUE TITLE
Add an API that will log ChipLogError via NSLog

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#14909]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/14816#discussion_r802035535

 #### Proposed Solution
- Add a new API that will log a ChipError using NSLog

**Comment by bzbarsky-apple** [comment]
It's not clear that we need this, given that ChipLogEror is using the os_log bits....

**Comment by woody-apple** [comment]
Not required for 1.0

**Comment by bzbarsky-apple** [comment]
I have verified that ChipLogError ends up using `os_log_with_type(..., OS_LOG_TYPE_ERROR, ...)`.
