### ISSUE TITLE
Door-Lock-Server returning Next Available Index on GetUserCommand and GetCredentialStatusCommand instead of next Occupied Index

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#14919]
#### Problem
Door-Lock-Server.cpp is returning the Next Available user index on Get User command
Door-Lock-Server.cpp is returning the Next Available credential index on Get Credential Status command

per spec, the NextIndex for both of these commands should instead return the next *occupied* index.

**Comment by bzbarsky-apple** [comment]
Also, this code is not setting the value to null if there is no such index.

This looks like a must-fix 1.0 issue.

@Morozov-5F
