### ISSUE TITLE
Move mWriteResponseBuilder in WriteHandler to stack

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#14943]
As a followup (please do not try to address this in this PR): is there a reason mMessageWriter and mWriteResponseBuilder need to be persistent members of this object?  Shouldn't they just have stack lifetime here?

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/13641#discussion_r802261592_

**Comment by bzbarsky-apple** [comment]
OK, `mWriteResponseBuilder` is used in a bunch of methods called from various places outside this class, so having it be a member makes some sense.  But `mMessageWriter` I am pretty sure we can move.
