### ISSUE TITLE
Feature Map is not implemented in chip-tool but present in Spec

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#14941]
#### Problem
Some clusters have feature-map in Spec but doesn't implement in chip-tool.

The clusters in which feature-map is not implemented:
Mode Select cluster
Pressure Measurement Cluster
Color Control Cluster
Account Login Cluster
Low Power Cluster
KeyPad Input Cluster
Application Launcher Cluster
Media Input Cluster
Wake On LAN Cluster
Media Playback Cluster
Audio Output Cluster
Channel Cluster
Application Basic Cluster
General commissioning cluster
Administrator Commissioning

Chip-tool Screenshot:
![image](https://user-images.githubusercontent.com/90545664/153135953-92db12c1-93a5-4765-b2a6-869b267fe7ff.png)

**Comment by bzbarsky-apple** [comment]
Will be fixed by https://github.com/project-chip/connectedhomeip/pull/14794
