### ISSUE TITLE
MF not work on Android

### ISSUE THREAD

**Issue by xylophone21** [project-chip/connectedhomeip#14944]
#### Problem
 * expected behavior
     * on android tv DUT
     * chip-tool pairing open-commissioning-window
     * chip-tool pairing manualcode 
     * paring success
 * actual behavior
     * paring failed

 #### Proposed Solution
1. when calling chip-tool pairing manualcode, The TV should be fond by SetUpCodePairer::StartDiscoverOverIP
2. It will call DeviceCommissioner::DiscoverCommissionableNodes --> MinMdnsResolver::FindCommissionableNodes  --> MinMdnsResolver::BrowseNodes --> MinMdnsResolver::SendQuery, which will use subType to find the TV
3. But on android TV, NsdManagerServiceResolver.java::publish, the subTypes is not used because there is no such support in android NSD_SERVICE
4. Solutions
    1  Using both subtype and TxT in MinMdnsResolver to find TV
    2  Find some app layer DNS sd impl on Android TV

Which one do you think is better?

**Comment by bzbarsky-apple** [comment]
Fixed by #15009
