### ISSUE TITLE
[TC-MC-3.1]KeyPad Input Cluster-Getting Invalid Argument error for key code 1000 in Step 9

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#14954]
#### Problem
As per the expectation, for the Media Cluster TC-MC-3.1 step 9, the response should be value 1 and unsupported key, in chip-tool as the controller and chip-tv-app as the accessory, getting an invalid argument error response. 

Tested with commit ID:-6380d38f44c46f9e8f684024bf99c6a203622455		

PFA Screenshot
![image](https://user-images.githubusercontent.com/95841834/153205079-97907738-5ca2-462b-88b9-5cd1b1ba400e.png)

**Comment by lazarkov** [comment]
@Rajashreekalmane Yes, you can only use codes that are defined in CEC protocol. There's no code 256 or 0x100 (in HEX value), from the list here: https://android.googlesource.com/platform/frameworks/base.git/+/master/services/core/java/com/android/server/hdmi/HdmiCecKeycode.java

**Comment by Rajashreekalmane** [comment]
@lazarkov In test-Plan they are mentioned "TH sends <Any Unsupported> Navigation Keycode to DUT" for this we should get a response as "unsupported key (value 1) status response" in test step 9.

Test-Plan reference:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-3-1-navigation-keycode-verification.

Spec reference :
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/KeypadInput.adoc#data-types

**Comment by lazarkov** [comment]
@Rajashreekalmane Any of the CEC predefined codes can be unsupported. The problem for the code defined in test case by number 1000. It's not that it's not supported, it's not valid. 

With current SDK you can choose number 10 for test-case it's not supported.
