### ISSUE TITLE
[Arduino-ESP32] binding ESP32 Arduino Core library in the matter project breaks generated includes

### ISSUE THREAD

**Issue by VOMediola** [project-chip/connectedhomeip#14965]
Arduino Core for ESP32 uses compile flag -DESP32, which translates to -DESP32=1, according to https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#index-D-1 .

This, in turn is taken over in macros generated by GN, for example in build/esp-idf/chip/gen/include/ble/BleBuildConfig.h
`#define BLE_PLATFORM_CONFIG_INCLUDE <platform/ESP32/BlePlatformConfig.h>`

which transforms into `#define BLE_PLATFORM_CONFIG_INCLUDE <platform/1/BlePlatformConfig.h>`

or, even worse in `#define CHIP_DEVICE_LAYER_TARGET ESP32`

which in turn breaks 
`#define CONFIGURATIONMANAGERIMPL_HEADER \
        <platform/CHIP_DEVICE_LAYER_TARGET/ConfigurationManagerImpl.h>
#include CONFIGURATIONMANAGERIMPL_HEADER`

which is fatal error: file not found.

**Comment by jakubdybczak** [comment]
There is a workaround, you can undefine ESP32, include Matter and then redefine it again, like I did here: https://github.com/jakubdybczak/esp32-arduino-matter/blob/master/src/Matter.h
