### ISSUE TITLE
Rename chip-tool-darwin to chip-tool

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14987]
As an aside, what is the difference beteween `chip-tool` and `chip-tool-darwin`? Both seem CLI. Would chip-tool not work on darwin as well? Why do both exist?

_Originally posted by @andy31415 in https://github.com/project-chip/connectedhomeip/issues/14816#issuecomment-1033827983_

**Comment by bzbarsky-apple** [comment]
> As an aside, what is the difference beteween chip-tool and chip-tool-darwin?

@andy31415 One is a POSIX app that happens to run on Darwin (and Linux) and uses the C++ SDK APIs directly, and one is an Objective-C app that uses the Darwin Matter framework.

They both exists because the exercise different code paths and different API surfaces.

**Comment by woody-apple** [comment]
Moving this out of v1.0, doesn't seem critical!
