### ISSUE TITLE
Implement EventList attribute

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#15011]
#### Problem
EventList not implemented.

 #### Proposed Solution
Implement it.

Not sure whether we need to do this for 1.0.

@mrjerryjohns @woody-apple

**Comment by raju-apple** [comment]
P2

**Comment by andy31415** [comment]
This seems to be a requirement for issues raised against the spec.

**Comment by woody-apple** [comment]
Cert Blocker Review: Spec is being updated, closing.

**Comment by bzbarsky-apple** [comment]
This shouldn't be closed; the attribute should still get implemented at some point.
