### ISSUE TITLE
[ota-provider-app] Apply UserConsentNeeded field of Query image command properly in conjunction with RequestorCanConsent field

### ISSUE THREAD

**Issue by isiu-apple** [project-chip/connectedhomeip#15043]
#### Problem
In scenario 1 below, OTA Requestor app is always treating UserConsentNeeded as true.  We need to fix the behavior when UserConsentNeeded is false.

The -c option for UserConsentNeeded in OTA Provider app also needs to be updated to indicate that -c means UserConsentNeeded is true and -c not present means UserConsentNeeded is false.

Requestor
RequestorCanConsent = true —> requestor has the ability (UI, etc) to get user consent
RequestorCanConsent= false

Provider
UserConsentNeeded = true —> provider has not obtained user consent
UserConsentNeeded = false

Scenario 1
Requestor -> Provider (QueryImage command)
RequestorCanConsent = true

Provider -> Requestor (QueryImageResponse)
UserConsentNeeded = true or false

Scenario 2
Requestor -> Provider
RequestorCanConsent = false

Provider -> Requestor
UseConsentNeeded = false

 #### Proposed Solution
When OTA Provider app has set UserConsentNeeded to false, then UserConsentNeeded should be false regardless if OTA requestor app has set UserConsentNeeded to be true or false.

**Comment by carol-apple** [comment]
Maybe we should get rid of the `-c` option altogether. Instead, use the `-u/--userConsentState` option to indicate what the `UserConsentNeeded` field should be set to.

**Comment by carol-apple** [comment]
Actually, on second thought, because `-u/--userConsentState` alters the status field in the response, we can't use it to purely set the UserConsentNeeded field without affect the status field.
