### ISSUE TITLE
Seeing CHIP Error 0x00000050: Unsupported certificate format on one of the M5 boards when tried to pair it with chip tool iOS app

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#15050]
#### Problem
Seeing CHIP Error 0x00000050: Unsupported certificate format on one of the M5 boards when tried to pair it with chip tool iOS app and pairing fails.

SHA: cfab82d3a63fd4e035cca03c4063bb96079a27d9

Steps to reproduce

1. Pair M5 board with mentioned SHA with chip tool 
2. Pairing does not succeed on chip tool and seeing below errors on chip tool logs:

9] CHIP: [CTL] Device returned status 3 on receiving the NOC
2022-02-10 12:15:56.808565-0800  localhost CHIPTool[10702]: (CHIP) [com.zigbee.chip:all] ðµ [1644524156808] [10702:392229] CHIP: [CTL] Add NOC failed with error ../../../../../../../../../../../CHIP-TOOL/connectedhomeip/src/controller/CHIPDeviceController.cpp:1265: CHIP Error 0x00000050: Unsupported certificate format
2022-02-10 12:15:56.808660-0800  localhost CHIPTool[10702]: (CHIP) [com.zigbee.chip:all] ð´ [1644524156808] [10702:392229] CHIP: [CTL] Failed to perform commissioning step 12

Note: Have seen this issue on 1 of 2 M5 boards. The other M5 board did not have this issue. 

[unsupported-cert-format-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8044048/unsupported-cert-format-M5-logs.txt)

[unsupported-cert-format-chip-tool-logs.txt](https://github.com/project-chip/connectedhomeip/files/8044047/unsupported-cert-format-chip-tool-logs.txt)

**Comment by vinay-apple** [comment]
Still hitting this issue on latest SHA: 149c271f497b4493dbc009aed8f616922fc9b5fe

I tried with multiple M5 boards when I hit this issue and no luck getting past this issue, same issue exhibited while pairing M5 boards with chip tool.  Adding logs from recent test. 

[Unsupported-cert-format-Chiptool-logs.txt](https://github.com/project-chip/connectedhomeip/files/8101137/Unsupported-cert-format-Chiptool-logs.txt)
[Unsupported-cert-format-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8101138/Unsupported-cert-format-M5-logs.txt)

**Comment by thok-itx** [comment]
Problem still occurs at latest SHA 235a4ac32cb54f60e2e4d9bb07d75b37077249fe
Commissioning of Linux Bridge-App with the chip-tool still not working. I also tried with the python CHIP controller, but the same error is reported during commissioning (see logs).

[log_linux-bridge-app.txt](https://github.com/project-chip/connectedhomeip/files/8160548/log_linux-bridge-app.txt)
[log_python-CHIP-controller.txt](https://github.com/project-chip/connectedhomeip/files/8160550/log_python-CHIP-controller.txt)

**Comment by LookAtThisTree** [comment]
Call `chip::DeviceLayer::PersistedStorage::KeyValueStoreMgrImpl().Init(CHIP_CONFIG_KVS_PATH);` somewhere at startup.

**Comment by thok-itx** [comment]
Thank you for the hint! This resolves the issue for my setup. This method was not called within the bridge-app example

**Comment by kean-apple** [comment]
I started seeing this issue on my setup (iOS chiptool provisioning M5 board all clusters) with 86a84443c7cda19e91ad5685ec86f2e5d60bc7e3

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/16132 will fix the new issue @kean-apple ran into (but is unrelated to the original intermittent problem).

**Comment by kean-apple** [comment]
Validated fix from https://github.com/project-chip/connectedhomeip/pull/16132. Untagging this as smoke test blocker

**Comment by woody-apple** [comment]
Closing this as fixed
