### ISSUE TITLE
Invoke the OTARequestor logic from the chip task context

### ISSUE THREAD

**Issue by selissia** [project-chip/connectedhomeip#15128]
#### Problem
Calls into the core CHIP functionality from OTARequestor APIs are not done in the context of the CHIP task on the platforms that use FreeRTOS; CHIP logic should only be invoked from the context of the CHIP task. For example, writing the UpdateState attribute in `OTARequestor::Init()` is not done in the context of the chip task on the platforms that use FreeRTOS. Detailed discussion: https://csamembers.slack.com/archives/G014G30SVV0/p1644588487457649

 #### Proposed Solution
Investigate whether it is possible for the OTARequestor APIs to internally schedule the actual work through `PlatformMgr::ScheduleWork()` or a similar method -- and if so, implement this fix. If the above is not possible, ensure that all the platforms schedule `OTARequestor` API calls from the correct context.

**Comment by bzbarsky-apple** [comment]
On FreeRTOS the other option is to take the Matter lock around the relevant calls.
