### ISSUE TITLE
Commissioning over BLE and IP are failing on Bridge-app.

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#15134]
#### Problem
Pairing  DUT with chip-tool is failing on Bridge-app (CommitID - 6380d38f44c46f9e8f684024bf99c6a203622455) on Master Branch .
For both BLE and IP commissioning I am gacing this issue itself.
Screenshot of the issue:
![image](https://user-images.githubusercontent.com/90545664/153836015-fc1ffa74-e2d5-4f84-8040-1339c07e7307.png)

Log:
[Bridge_app_failing.txt](https://github.com/project-chip/connectedhomeip/files/8059495/Bridge_app_failing.txt)

**Comment by thok-itx** [comment]
Also reported within following issue: https://github.com/project-chip/connectedhomeip/issues/15050

**Comment by sowmyassp** [comment]
@PSONALl - I tried with commit ID (d671a523745079b1ea1778ee4885159868d9c002) which you have mentioned but still facing same issue.

**Comment by sowmyassp** [comment]
I can't launch bridge-app with commitID (2982c0ca0623773327def4cc7180d07f6b959c42) 
This is the issue I am facing 
![image](https://user-images.githubusercontent.com/90545664/158312962-a019eda2-4b4e-42bb-8b91-d3a1e54d6207.png)

Attached log:
[bridge_launching.txt](https://github.com/project-chip/connectedhomeip/files/8250434/bridge_launching.txt)

**Comment by sowmyassp** [comment]
Still facing same issue with commitID (fa5561c23d8c1f9464da8669931affbae0660f51)
