### ISSUE TITLE
Is Matter accepting the support of new chipsets?

### ISSUE THREAD

**Issue by pakls** [project-chip/connectedhomeip#15131]
#### Problem
I'd like to add the support of Matter to our chipset. I looked around the source tree and found it seems I need to create new folders.
Do you accept new chipsets at the moment?

 #### Proposed Solution
We will create PRs for our chipset if new chipsets are accepted.

**Comment by bzbarsky-apple** [comment]
Yes, we are generally accepting new chipsets.
