### ISSUE TITLE
[group] Add salt to group key KDF

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#15155]
#### Problem
If the same EpochKey is installed on two fabrics, there will be collisions with the messages.

 #### Proposed Solution
Add a diversifier to the KDF salt for operational group key generation as being defined in:
https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4910 (issue)
https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/4911 (PR)

This will make it extremely unlikely that the operational group key is the same on two fabrics even when the same epoch key input is used.  Current proposal of passing `CompressedFabricId` as salt has `2^-64` chance of collisions.  If folks want to lobby for `2^-128` chance of collisions (max key size output), we could pass `RootPuclicKey || FabricID` instead.

**Comment by andy31415** [comment]
V1.0 since we need to match spec.
