### ISSUE TITLE
AddNOC, CSRRequest, adding trusted roots no longer possible outside commissioning, which breaks certificate rotation

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#15237]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/15204 changed AddNOC to fail out if we don't have a commissioning window open.  This breaks certificate rotation.  Similar for CSRRequest and adding a trusted root.

 #### Proposed Solution
Fix whatever problem we were trying to fix in a way that does not break cert rotation.

We _should_ be checking we have a valid failsafe for the relevant fabric.  I believe that should provide the requisite mutual exclusion for `gFabricBeingCommissioned`, if we also implement the "can't have more than one failsafe active" semantics from the spec.

@yufengwangca @cecille @jmartinez-silabs @tcarmelveilleux

**Comment by yufengwangca** [comment]
Currently, the ArmFailSafe Command implementation is not spec compliant, we need to update this together with OperationalCredentials cluster to align with spec
