### ISSUE TITLE
chip-tool pairing ble-wifi command is failing

### ISSUE THREAD

**Issue by vijs** [project-chip/connectedhomeip#15261]
#### Problem

https://github.com/project-chip/connectedhomeip/pull/14751 had disabled Wi-Fi and replaced it with Thread.
By making the Thread (as default), the chip-tool pairing ble-wifi command does not work anymore.

 * expected behavior
    chip-tool pairing ble-wifi command should work
 * actual behavior
    chip-tool pairing ble-wifi command is not working in the latest master
 * steps to reproduce
    Run "chip-tool pairing ble-wifi" command

**Comment by tcarmelveilleux** [comment]
Please provide more details about:

- What is the config at commissioning side
- What is the config at commissionee side
- Logs for both sides

**Comment by tcarmelveilleux** [comment]
Slack resolution: lighting-app was being used, which does not have proper Network Commissioning cluster setup on LInux.
