### ISSUE TITLE
TV_AccountLoginCluster.yaml failing in Linux platform

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#15296]
Summary:
               TV_AccountLoginCluster.yaml testcase seems to be failing when we execute in the Linux system

Execution log and Screenshot:
![image](https://user-images.githubusercontent.com/84442963/154475651-9b78b93b-b9a6-490c-9367-bcef9c541e22.png)
[faillog.zip](https://github.com/project-chip/connectedhomeip/files/8088382/faillog.zip)

**Comment by manjunathambiger23** [comment]
> @manjunathambiger23 Are you executing it against tv-app, or all-clusters-app?

@bzbarsky-apple we are executing it against all-clusters-app ,when we try to use this command ./scripts/tests/run_test_suite.py --log-level debug run we are getting this error

**Comment by bzbarsky-apple** [comment]
The TV cluster tests need to be run against the tv app.  See how CI does it.  all-clusters-app just does not implement the relevant clusters in a meaningful way.
