### ISSUE TITLE
M5 board crashes when removing fabric - abort() was called at PC 0x400e3785 on core 0

### ISSUE THREAD

**Issue by kean-apple** [project-chip/connectedhomeip#15305]
#### Problem
M5 board crashes when removing fabric. The M5 board has 2 commissioned fabrics

SHA: 5cbe2931f64e16a44fc843e148325909fbe1511d

Steps:
1. Pair M5 board with Chip Tool 1 - verify toggle light works
2. On Chip tool 1, enable pairing mode
3. On Chip tool 2, pair M5 board by entering pin code provided by Chip tool 1 - verify toggle light works
4. On Chip tool 1, remove all fabric from Fabric management menu

In step 4, observed M5 board crashes (seen at least twice):
abort() was called at PC 0x400e3785 on core 0
0x400e3785: chip::SessionHolder::Get() const at /Users/keanhinlim/connectedhomeip/src/lib/support/CodeUtils.h:477
 (inlined by) chip::Optional<chip::ReferenceCountedHandle<chip::Transport::Session> >::Value() const & at /Users/keanhinlim/connectedhomeip/src/lib/core/Optional.h:170
 (inlined by) chip::SessionHolder::Get() const at /Users/keanhinlim/connectedhomeip/src/transport/SessionHolder.h:54
[M5 crashes removing all fabrics-chiptool-logs.txt](https://github.com/project-chip/connectedhomeip/files/8089946/M5.crashes.removing.all.fabrics-chiptool-logs.txt)
[M5-crash-removing-all-fabrics-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8089947/M5-crash-removing-all-fabrics-M5-logs.txt)

**Comment by kean-apple** [comment]
Probably dup of https://github.com/project-chip/connectedhomeip/issues/15175.

**Comment by kean-apple** [comment]
still seen with 9f09e5290e5ce97f446158ac83aaf1942fc4f540

**Comment by kean-apple** [comment]
still seeing on SHA 3b834619186a84db03281a5c76f236562db27ebd

**Comment by bzbarsky-apple** [comment]
@kean-apple I would expect this works now...  Can you check, please?

**Comment by woody-apple** [comment]
Issue Scrub: Closing old issues, please re-file a new issue if this is still a problem.
