### ISSUE TITLE
Cirque Test: For network commissioning test, we need to check if device support network commissioning or not via descriptor cluster

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#15341]
#### Problem
Cirque Test: For network commissioning test, we need to check if device support network commissioning or not via descriptor cluster

**Comment by cecille** [comment]
Auto commissioner now checks the network cluster to determine what kind of network is supported (thread/wifi) and will error the commissioner is using BLE commissioning but has not supplied the correct parameters. This should already be in place for cirque tests, as they are using this commissioner. So I think this is done. @yunhanw-google - can you confirm that I understand the issue correctly here and close if appropriate?

**Comment by mrjerryjohns** [comment]
@erjiaqing can you comment?

**Comment by erjiaqing** [comment]
Yes, however, seems the code for setting network commissioning params for the auto commissioner is commented out. I will do some cleanup for the python testing script and re-enable it.
