### ISSUE TITLE
[TC-ETHDIAG-2.1] PacketTxCount and PacketRxCount attribute value mismatch

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#15348]
Summary:
              As per testplan PacketTxCount and PacketRxCount attribute value must be 0 after sending ResetCounts command but when we execute its failing showing value mismatch for both attribute.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/154681626-646d671d-5b9f-458e-8fbc-4dbf4a8a48f8.png)

Execution logs and screenshot:
[packetRxcount.zip](https://github.com/project-chip/connectedhomeip/files/8097028/packetRxcount.zip)
![packetRxCount](https://user-images.githubusercontent.com/84442963/154681723-9c1995d6-2518-4795-acd3-9720a65590f4.png)
![packetTxCount](https://user-images.githubusercontent.com/84442963/154681734-e076864d-3a2b-40b2-88e9-e285bb1c5e5a.png)
[packetTxCount.zip](https://github.com/project-chip/connectedhomeip/files/8097029/packetTxCount.zip)

**Comment by bzbarsky-apple** [comment]
The test plan is wrong.

When ResetCounts is received, the counts are set to 0, sure.  Then a response is sent, which is a transmitted packet, so the TX count becomes 1.  That's the value that is sent in the response.

Similarly, after ResetCount a response is sent and an MRP ack is received, so the RX count becomes 1.  Now a read is sent, which is received, the the RX count becomes 2.  That's the value that is sent in the response.

**Comment by bzbarsky-apple** [comment]
Filed https://github.com/CHIP-Specifications/chip-test-plans/issues/941
