### ISSUE TITLE
Enumeration test - Unable to read device list of endpoint 65534 - Error Domain=MatterInteractionErrorDomain Code=195 "The cluster indicated is not supported" UserInfo={NSLocalizedDescription=The cluster indicated is not supported}

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#15359]
#### Problem

Enumeration test - Unable to read device list of endpoint 65534 - Error Domain=MatterInteractionErrorDomain Code=195 "The cluster indicated is not supported" UserInfo={NSLocalizedDescription=The cluster indicated is not supported}

SHA: 149c271f497b4493dbc009aed8f616922fc9b5fe

Steps to reproduce
 
1. Pair M5 with chip tool and toggle light works fine. 
2. Perform enumeration test
3. Observe chip tool logs, we are able to read server list from endpoints 1 and 2 fine. 
4. But we see error such as below for reading device list on endpoint 65534

2022-02-18 11:38:47.878938-0800  localhost CHIPTool[12034]: UpdatingUIResult: Unable to read device list for Endpoint:65534 Error: Error Domain=MatterInteractionErrorDomain Code=195 "The cluster indicated is not supported" UserInfo={NSLocalizedDescription=The cluster indicated is not supported}

[Unable-to-read-device-list-for-ep-65534-Chiptool.txt](https://github.com/project-chip/connectedhomeip/files/8099948/Unable-to-read-device-list-for-ep-65534-Chiptool.txt)
[Unable-to-read-device-list-for-ep-65534-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8099949/Unable-to-read-device-list-for-ep-65534-M5-logs.txt)

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/15546 will fix this by hiding this endpoint on esp32, since it's not used there.
