### ISSUE TITLE
[TC-OCC-2.1] Attributes Missing From Occupancy Sensing Cluster 

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#15377]
Summary:
The following attributes seem to be missing in the Occupancy Sensing Cluster
1.PIROccupiedToUnoccupiedDelay
2.PIRUnoccupiedToOccupiedDelay
3.PIRUnoccupiedToOccupiedThreshold
4.UltrasonicOccupiedToUnoccupiedDelay
5.UltrasonicUnoccupiedToOccupiedDelay
6.UltrasonicUnoccupiedToOccupiedThreshold
7.PhysicalContactOccupiedToUnoccupiedDelay
8.PhysicalContactUnoccupiedToOccupiedDelay
9.PhysicalContactUnoccupiedToOccupiedThreshold

Spec Screenshot:
![2022-02-21_09-21_2](https://user-images.githubusercontent.com/57476670/154886314-8bef46ec-d9b7-4995-b7f4-7eec1315c99e.png)
![2022-02-21_09-21_1](https://user-images.githubusercontent.com/57476670/154886318-dd01af51-f49b-4200-bd72-7c868e980763.png)
![2022-02-21_09-21](https://user-images.githubusercontent.com/57476670/154886320-5961370f-5459-44eb-af01-2cb1872d7a7d.png)

Error log screenshot :
![2022-02-21_09-14](https://user-images.githubusercontent.com/57476670/154886354-52602e63-d7ef-4229-98fc-35c502321de2.png)

**Comment by bzbarsky-apple** [comment]
Fixed in #18209 as far as the YAML support this issue is about goes.
