### ISSUE TITLE
Device Discovery - [TC-DD-3.1] SetFabric command is not been implemented in chip-tool.

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#15381]
#### Problem
In test case [TC-DD-3.1] of Device Discovery SetFabric command is not been implemented in chip-tool (step 1f)

Test-plan reference:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicediscovery.adoc#tc-dd-1-2-manual-pairing-code-payload-verification

**Comment by bzbarsky-apple** [comment]
@sowmyassp There is no SetFabric command in the spec.  Filed https://github.com/CHIP-Specifications/chip-test-plans/issues/942
