### ISSUE TITLE
Followup: we should not be making manual Run() calls in tests: those just cover up bugs with Run() scheduling.  We should be doing DrainAndServiceIO.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#15402]
Followup: we should not be making manual Run() calls in tests: those just cover up bugs with Run() scheduling.  We should be doing DrainAndServiceIO.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/14805#discussion_r811578098_

**Comment by bzbarsky-apple** [comment]
In particular:

1.  The tests should be using an async loopback, not a sync one.
2. We should remove the `Run` calls.

Relevant tests:
```
src/app/tests/TestReadInteraction.cpp
src/controller/tests/TestReadChunking.cpp
```
