### ISSUE TITLE
Remove fabric index field from the ProviderLocation struct

### ISSUE THREAD

**Issue by carol-apple** [project-chip/connectedhomeip#15435]
#### Problem
https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/4931 removed the fabric index field from the `ProviderLocation ` struct.

 #### Proposed Solution
Removing for fabric index should be reflected in chip-ota.xml as well.

**Comment by selissia** [comment]
Also need to update SetCurrentProviderLocation(ProviderLocationType providerLocation) = 0; as discussed in the comments for https://github.com/project-chip/connectedhomeip/pull/15433
