### ISSUE TITLE
M5 board stops reporting when reading temp from a 2nd chiptool app

### ISSUE THREAD

**Issue by kean-apple** [project-chip/connectedhomeip#15441]
#### Problem
M5 board stops Reporting when reading temp from a 2nd chiptool app

SHA: 28833946df933e042257208a4947a41206ea1bf3
Steps
Initial: load instance of iOS chiptool app on same iOS device (different name & bundle ids)
1. Pair M5 board to Chiptool App 1 - verify able to toggle light
2. Enable pairing mode, pair with Chip tool App2 using the provided pin code. Verify toggle light works
3. In Chip tool App 1, go to temp sensor. Setup up reporting : Min 1s, Max: 2s, Delta: 1C confirm M5 board send reports & when changing temp on M5 board it reflects in Chip tool App 1
4. In Chip tool App 2, go to temp sensor. Perform a read using the refresh option -> verify reads current temp sensor
5. In Chip too App 1, go to temp sensor. Verify its still receiving updates when modifying temp on the M5 board

In step 4 & 5, Looks like M5 board stops reporting after performing read from Chip tool App 2. 

//See reporting happening every 1s on M5 board:
E (261307) chip[IN]: Sending encrypted msg 0x3ffe83d4 with MessageCounter:8800578 to 0x7AE396E0F22F31BB (1) at monotonic time: 260524 msec
E (261327) chip[EM]: Flushed pending ack for MessageCounter:12870440 on exchange 52809i
E (261337) chip[DL]: Long dispatch time: 124 ms, for event type 3
E (262147) chip[DMG]: Unblock report hold after min 1 seconds
E (263147) chip[DMG]: Refresh subscribe timer sync after 1 seconds
E (263147) chip[DMG]: <RE> Sending report (payload has 15 bytes)...
E (263147) chip[DMG]: IM RH moving to [AwaitingReportResponse]
E (263167) chip[IN]: Prepared secure message 0x3ffca0ec to 0x7AE396E0F22F31BB (1)  of type 0x5 and protocolId (0, 1) on exchange 52810i with MessageCounter:8800579.
E (263177) chip[IN]: Sending encrypted msg 0x3ffca0ec with MessageCounter:8800579 to 0x7AE396E0F22F31BB (1) at monotonic time: 262391 msec
E (263187) chip[DMG]: Refresh Subscribe Sync Timer with max 2 seconds
E (263187) chip[DMG]: <RE> ReportsInFlight = 1 with readHandler 0, RE has no more messages
E (263257) chip[EM]: Received message of type 0x1 with protocolId (0, 1) and MessageCounter:12870441 on exchange 52810i
E (263267) chip[EM]: Found matching exchange: 52810i, Delegate: 0x3ffceac8
E (263277) chip[EM]: Rxd Ack; Removing MessageCounter:8800579 from Retrans Table on exchange 52810i
E (263287) chip[EM]: Removed CHIP MessageCounter:8800579 from RetransTable on exchange 52810i
E (263287) chip[DMG]: StatusResponseMessage =
E (263297) chip[DMG]: {
E (263297) chip[DMG]: 	Status = 0x0,
E (263297) chip[DMG]: 	InteractionModelRevision = 1
E (263317) chip[DMG]: }
E (263317) chip[IM]: Received status response, status is 0

//Receive read request:
 E (264987) chip[IM]: Received Read request
E (264987) chip[DMG]: ReadRequestMessage =
E (264997) chip[DMG]: {
E (264997) chip[DMG]: 	AttributePathIBs =
E (265007) chip[DMG]: 	[
E (265007) chip[DMG]: 		AttributePathIB =
E (265017) chip[DMG]: 		{
E (265017) chip[DMG]: 			Endpoint = 0x1,
E (265017) chip[DMG]: 			Cluster = 0x402,
E (265027) chip[DMG]: 			Attribute = 0x0000_0000,
E (265027) chip[DMG]: 		}
E (265027) chip[DMG]: 			
E (265037) chip[DMG]: 	],
E (265037) chip[DMG]: 		
E (265047) chip[DMG]: 	isFabricFiltered = true, 
E (265057) chip[DMG]: 	InteractionModelRevision = 1
E (265057) chip[DMG]: },
E (265057) chip[DMG]: IM RH moving to [GeneratingReports]
E (265067) chip[DMG]: <RE:Run> Cluster 402, Attribute 0 is dirty
E (265067) chip[DMG]: Reading attribute: Cluster=0x0000_0402 Endpoint=1 AttributeId=0x0000_0000 (expanded=0)
E (265087) chip[DMG]: AccessControl: checking f=2 a=c s=0x701FF79093BC99E0 t= c=0x0000_0402 e=1 p=
 (265097) chip[DMG]: <RE> Sending report (payload has 38 bytes)...
E (265097) chip[EM]: Piggybacking Ack for MessageCounter:10618034 on exchange: 22347r
E (265107) chip[IN]: Prepared secure message 0x3ffca0ec to 0x701FF79093BC99E0 (2)  of type 0x5 and protocolId (0, 1) on exchange 22347r with MessageCounter:12763722.
E (265127) chip[IN]: Sending encrypted msg 0x3ffca0ec with MessageCounter:12763722 to 0x701FF79093BC99E0 (2) at monotonic time: 264338 msec
E (265137) chip[DMG]: <RE> OnReportConfirm: NumReports = 0
E (265137) chip[DMG]: <RE> ReportsInFlight = 0 with readHandler 1, RE has no more messages
E (265147) chip[DMG]: IM RH moving to [AwaitingDestruction]
E (265197) chip[DMG]: Refresh subscribe timer sync after 1 seconds
E (265197) chip[DMG]: <RE> Sending report (payload has 15 bytes)...
E (265197) chip[DMG]: IM RH moving to [AwaitingReportResponse]
E (265207) chip[IN]: Prepared secure message 0x3ffca104 to 0x7AE396E0F22F31BB (1)  of type 0x5 and protocolId (0, 1) on exchange 52811i with MessageCounter:8800581.
E (265227) chip[IN]: Sending encrypted msg 0x3ffca104 with MessageCounter:8800581 to 0x7AE396E0F22F31BB (1) at monotonic time: 264439 msec
E (265237) chip[DMG]: Refresh Subscribe Sync Timer with max 2 seconds
E (265237) chip[DMG]: <RE> ReportsInFlight = 1 with readHandler 0, RE has no more messages
E (265257) chip[EM]: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:10618035 on exchange 22347r
E (265267) chip[EM]: Found matching exchange: 22347r, Delegate: 0x0
E (265267) chip[EM]: Rxd Ack; Removing MessageCounter:12763722 from Retrans Table on exchange 22347r
E (265277) chip[EM]: Removed CHIP MessageCounter:12763722 from RetransTable on exchange 22347r
E (266237) chip[DMG]: Unblock report hold after min 1 seconds
E (267247) chip[DMG]: Refresh subscribe timer sync after 1 seconds
I (268047) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (268047) all-clusters-app: editing attribute as integer: 56 (+)
E (268057) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 58b5f1fe
I (268057) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (268067) app-devicecallbacks: Unhandled cluster ID: 1026
I (268087) app-devicecallbacks: Current free heap: 57976

//Seems like reporting stops now, I was changing temp on M5 board and it wasn't reflecting on ChipTool app
I (268047) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (268047) all-clusters-app: editing attribute as integer: 56 (+)
E (268057) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 58b5f1fe
I (268057) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (268067) app-devicecallbacks: Unhandled cluster ID: 1026
I (268087) app-devicecallbacks: Current free heap: 57976

I (268247) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (268497) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (268497) all-clusters-app: editing attribute as integer: 57 (+)
E (268507) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 58b5f1ff
I (268507) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (268517) app-devicecallbacks: Unhandled cluster ID: 1026
I (268537) app-devicecallbacks: Current free heap: 57976

I (268697) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (269097) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (269097) all-clusters-app: editing attribute as integer: 58 (+)
E (269107) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 58b5f200
I (269107) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (269117) app-devicecallbacks: Unhandled cluster ID: 1026
I (269137) app-devicecallbacks: Current free heap: 57976

I (269297) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (269497) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (269497) all-clusters-app: editing attribute as integer: 59 (+)
E (269507) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 58b5f201
I (269507) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (269517) app-devicecallbacks: Unhandled cluster ID: 1026
I (269537) app-devicecallbacks: Current free heap: 57976

I (269697) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (269797) all-clusters-app: Display awake but will switch off automatically in 30 seconds
I (269797) all-clusters-app: editing attribute as integer: 60 (+)
E (269807) chip[DMG]: Endpoint 1, Cluster 0x0000_0402 update version to 58b5f202
I (269807) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0402', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (269817) app-devicecallbacks: Unhandled cluster ID: 1026
I (269837) app-devicecallbacks: Current free heap: 57976

//some time out errors 
E (270237) chip[EM]: Retransmitting MessageCounter:8800581 on exchange 52811i Send Cnt 0
E (270237) chip[IN]: Sending encrypted msg 0x3ffca104 with MessageCounter:8800581 to 0x7AE396E0F22F31BB (1) at monotonic time: 269455 msec
E (272237) chip[EM]: Retransmitting MessageCounter:8800581 on exchange 52811i Send Cnt 1
E (272247) chip[IN]: Sending encrypted msg 0x3ffca104 with MessageCounter:8800581 to 0x7AE396E0F22F31BB (1) at monotonic time: 271457 msec
E (274247) chip[EM]: Retransmitting MessageCounter:8800581 on exchange 52811i Send Cnt 2
E (274247) chip[IN]: Sending encrypted msg 0x3ffca104 with MessageCounter:8800581 to 0x7AE396E0F22F31BB (1) at monotonic time: 273460 msec
E (276247) chip[EM]: Failed to Send CHIP MessageCounter:8800581 on exchange 52811i sendCount: 3 max retries: 3
E (277207) chip[DMG]: Time out! failed to receive status response from Exchange: 52811i
E (277207) chip[DMG]: <RE> OnReportConfirm: NumReports = 0
E (277227) chip[DMG]: IM RH moving to [AwaitingDestruction]
E (282097) chip[EM]: Received message of type 0x1 with protocolId (0, 1) and MessageCounter:12870442 on exchange 52811i
E (282107) chip[EM]: Handling via exchange: 52811i, Delegate: 0x0
E (282117) chip[EM]: CHIP MessageCounter:8800581 not in RetransTable on exchange 52811i
E (282127) chip[EM]: Sending Standalone Ack for MessageCounter:12870442 on exchange 52811i
E (282127) chip[IN]: Prepared secure message 0x3ffe8484 to 0x7AE396E0F22F31BB (1)  of type 0x10 and protocolId (0, 0) on exchange 52811i with MessageCounter:8800582.
E (282147) chip[IN]: Sending encrypted msg 0x3ffe8484 with MessageCounter:8800582 to 0x7AE396E0F22F31BB (1) at monotonic time: 281359 msec
E (282157) chip[EM]: Flushed pending ack for MessageCounter:12870442 on exchange 52811i
E (282167) chip[EM]: Dropping unexpected message of type 0x1 with protocolId (0, 1) and MessageCounter:12870442 on exchange 52811i
E (282187) chip[EM]: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:12870443 on exchange 52811i
E (282187) chip[EM]: OnMessageReceived failed, err = Error CHIP:0x00000070
E (282207) chip[EM]: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:12870444 on exchange 52811i
E (282217) chip[EM]: OnMessageReceived failed, err = Error CHIP:0x00000070
E (282217) chip[EM]: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:12870445 on exchange 52811i
E (282227) chip[EM]: OnMessageReceived failed, err = Error CHIP:0x00000070
E (289247) chip[EM]: Received message of type 0x2 with protocolId (0, 1) and MessageCounter:12870446 on exchange 9862r

 #### Proposed Solution
<suggested fix, suggested enhancement>
[reporting-stops-when-reading-from-2nd-client-chiptool-logs.txt](https://github.com/project-chip/connectedhomeip/files/8121426/reporting-stops-when-reading-from-2nd-client-chiptool-logs.txt)
[reporting-stops-when-reading-read-from-2nd-client-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8121428/reporting-stops-when-reading-read-from-2nd-client-M5-logs.txt)

**Comment by bzbarsky-apple** [comment]
@kean-apple Is this still being a problem?
