### ISSUE TITLE
[TC-MC-1.2] Global attributes - Keypad Input Cluster, FeatureMap returns Error Response

### ISSUE THREAD

**Issue by anaamrit** [project-chip/connectedhomeip#15458]
TC : TH reads the FeatureMap attribute from the DUT

TC : Reference : https://github.com/CHIP-Specifications/chip-test-plans/blob/jsena-media-17Feb22/src/cluster/media.adoc#tc-mc-1-2-global-attributes-keypad-input-cluster-dut-as-server

Response Failure Received, PFA  log file.
[FeatureMap_KepadInput.txt](https://github.com/project-chip/connectedhomeip/files/8125108/FeatureMap_KepadInput.txt)

**Comment by joesena-amz** [comment]
This may be acceptable as per the spec - I think either a value of 0 (no bits set) or error should be okay.
