### ISSUE TITLE
[TC-MC-1.2] Global attributes - Keypad Input Cluster, AttributeList attribute returns non Empty list.

### ISSUE THREAD

**Issue by anaamrit** [project-chip/connectedhomeip#15459]
TC : TH reads the AttributeList attribute from the DUT

TC : Reference : https://github.com/CHIP-Specifications/chip-test-plans/blob/jsena-media-17Feb22/src/cluster/media.adoc#tc-mc-1-2-global-attributes-keypad-input-cluster-dut-as-server

Response Failure Received, PFA log file.
[AttributeList_KeypadInput.txt](https://github.com/project-chip/connectedhomeip/files/8125166/AttributeList_KeypadInput.txt)

**Comment by joesena-amz** [comment]
This can be resolved - these are global attributes.

**Comment by bzbarsky-apple** [comment]
Resolving; behavior is correct.
