### ISSUE TITLE
[TC-MC-1.3] Global attributes - Media Input Cluster, FeatureMap returns Error Response

### ISSUE THREAD

**Issue by anaamrit** [project-chip/connectedhomeip#15463]
TC : TH reads the FeatureMap attribute from the DUT
Expected : Verify that the DUT response indicates that the FeatureMap attribute has bit 0 set to 1 if the DUT supports the Application Platform feature (PICS_AP_S is true).

TC Reference : https://github.com/CHIP-Specifications/chip-test-plans/blob/jsena-media-17Feb22/src/cluster/media.adoc#tc-mc-1-2-global-attributes-keypad-input-cluster-dut-as-server

PFA log

[FeatureMap _MediaInput.txt](https://github.com/project-chip/connectedhomeip/files/8125327/FeatureMap._MediaInput.txt)

**Comment by joesena-amz** [comment]
This should be implemented as per https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Data-Model.adoc#132-featuremap-attribute
