### ISSUE TITLE
Fix Minimal mDNS resolver to process TTL correctly

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#15489]
#### Problem

PR #15445 fixes an issue with DNS resolution results that were not correctly populating the expiration time, resulting in bogus values triggering a false expiration of the result.

It does so by placing a default in all cases. This is not actually spec compliant.

 #### Proposed Solution

As per the suggested solution from @andreilitvin in [this](https://github.com/project-chip/connectedhomeip/pull/15445#discussion_r812916231) comment, the resolved data should pick the smallest expiration time from the returned records.

**Comment by andy31415** [comment]
Marking as 1.x since I am not convinced TTL can be reliably set by a CHIP device: we have no way of knowing how long an IP address is valid, so we will end up reading default TTLs anyway.

**Comment by cecille** [comment]
The commissioner should still honor the TTL set by the device, though, as a device may well have an impl with a proper TTL set. Post 1.0 is still probably fine.
