### ISSUE TITLE
Global attribute-Event-List is not implemented in chip-tool but present in Spec.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15509]
#### Problem
Some clusters have Event-List in Spec as a mandatory but doesn't implement in chip-tool.
Level Control cluster
illuminance Measurement Cluster
Identify cluster
Temperature Measurement Cluster
Thermostat Cluster
Thermostat User Configuration Cluster
keypadinput Cluster
Accountlogin Cluster
Applicationbasic Cluster
Applicationlauncher Cluster
 Channel cluster 
Audiooutput cluster
 contentlauncher Cluster
mediainput  Cluster
 mediaplayback  Cluster
Targetnavigator Cluster
Generalcommissioing cluster
Userlabel cluster
Fixedlabel cluster
Label cluster
Network commissioning cluster
Localization cluster

Chip-tool Screenshot:
![image](https://user-images.githubusercontent.com/95841834/155513594-c9c43400-6a18-4209-bcef-59539e42912e.png)

**Comment by somu1710** [comment]
Event list is not implemented in chip-tool but present in spec  for these clusters also
1. on/off
2. modeselect
3. pressure measurement
4. occupancy sensing 
5. Relativehumidity
6. pump configuration and control
7. windowcovering
8. power source
9. power source configuration

**Comment by sowmyassp** [comment]
Event list is not implemented in chip-tool but present in spec for these clusters also
1. Boolean State Cluster
2. Flow Measurement Cluster
3. Color Control Cluster
4. Bridged Actions Cluster

**Comment by Survensa** [comment]
Need event list implementation for descriptor cluster

**Comment by cjandhyala** [comment]
@andy31415 @vivien-apple @bzbarsky-apple Along with EventList, Global Elements talks about other fields like "Accepted CommandList" and "Generate dCommandList" , Are these two are also out of scope ? Ref Section 7.13 from Spec

![Screen Shot 2022-04-12 at 5 25 20 PM](https://user-images.githubusercontent.com/68604034/163075654-28cf3d98-945b-468d-8a2c-b70b91b0bf52.png)

**Comment by bzbarsky-apple** [comment]
Everything there except EventList is implemented.

**Comment by Rajashreekalmane** [comment]
Closing this issue in SDK as @cjandhyala @vivien-apple and @andy31415 as suggested above.
