### ISSUE TITLE
Cluster-specific-error(0x02) is not received for 21st attempt with correct passcode both in ECM and BCM of M5 Stack and Raspberry pi platform

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#15522]
#### Problem
Didn't receive expected cluster-specific-error(0x02) for 21st attempt with correct passcode after 20 unsuccessful attempts with wrong passcode both in ECM and BCM 

**Expected behaviour** : Should receive cluster-specific-error code (0x02) 

**Actual behaviour** :  Pairing Failure: ../../third_party/connectedhomeip/src/controller/CHIPDeviceController.cpp:1336: CHIP Error 0x00000032: Timeout

**Test-plan reference** : https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/multiplefabrics.adoc#tc-mf-1-9-device-exit-commissioning-mode-after-20-failed-commission-attempts-ecm-dut-commissionee

**Spec reference** : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/AdminCommissioningCluster.adoc#ref_AdminCommissioningCluster_Status

**Test platform** :
Chip-tool - RPI
DUT - RPI

**Steps to reproduce**:

- After commissioning over BLE
- ./chip-tool pairing open-commissioning-window 1 1 200 2000 3840 / ./chip-tool administratorcommissioning open-basic-commissioning-window 200 1 0 --timedInteractionTimeoutMs 1000 (On 1st controller)
- ./chip-tool pairing manualcode 2 12345678912 / ./chip-tool pairing onnetwork 2 20202019 (With wrong passcode 20 times on 2nd controller)
- ./chip-tool pairing manualcode 2 36340417266 / ./chip-tool pairing onnetwork 2 20202021 (with correct passcode but should fail)

[TC_MF_1.12_2ndcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133879/TC_MF_1.12_2ndcntrl.txt)
[TC_MF_1.12_1stcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133880/TC_MF_1.12_1stcntrl.txt)
[TC_MF_1.11_2ndcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133881/TC_MF_1.11_2ndcntrl.txt)
[TC_MF_1.11_1stcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133882/TC_MF_1.11_1stcntrl.txt)
[TC_MF_1.10_2ndcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133883/TC_MF_1.10_2ndcntrl.txt)
[TC_MF_1.10_1stcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133884/TC_MF_1.10_1stcntrl.txt)
[TC_MF_1.9_2ndcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133885/TC_MF_1.9_2ndcntrl.txt)
[TC_MF_1.9_1stcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8133886/TC_MF_1.9_1stcntrl.txt)

**Comment by Garik098** [comment]
Observing the same issue on chip-tool-darwin

**Comment by bzbarsky-apple** [comment]
@sowmyassp Why are you expecting "cluster-specific-error (0x02)" and for which cluster, exactly?  This is failing in PASE session setup, before any cluster commands get a chance to be sent.

**Comment by cjandhyala** [comment]
@bzbarsky-apple There is an interesting bug here, with ToT (375fff343430f07df3ea01d211cbf45c6ac10fea) after 15 consecutive failed attempts to establish PASE i.e. 2nd admin tries to establish PASE with wrong passcode for 15 times, the accessory is not trying to establish PASE session from 16th attempt onwards. Once accessory (raspi running all-cluster-apps) in this state , even the 1st admin can not establish CASE session and send messages to the accessory. This is different to what Sowmya is reporing though. 
[2nd_admin_chip_tool_log.txt](https://github.com/project-chip/connectedhomeip/files/8508628/2nd_admin_chip_tool_log.txt)
[1st_admin_chip_tool_log.txt](https://github.com/project-chip/connectedhomeip/files/8508629/1st_admin_chip_tool_log.txt)
[raspi_log.txt](https://github.com/project-chip/connectedhomeip/files/8508630/raspi_log.txt)

**Comment by bzbarsky-apple** [comment]
@cjandhyala Please report a separate issue for that with steps to reproduce, @-mention me and I will take a look.

**Comment by sowmyassp** [comment]
@bzbarsky-apple I have already raised the ticket for the issue mentioned by chaitanya, here is the ticket

https://github.com/project-chip/connectedhomeip/issues/17167

**Comment by bzbarsky-apple** [comment]
Perfect, thank you.  The question remains: why is this issue expecting "cluster-specific-error (0x02)"?  @sowmyassp

**Comment by sowmyassp** [comment]
For 20 unsuccessful attempt we are sending wrong passcode which makes PAKEParameterError ie.,(0x02) right? After that only pase session will be failed right.

**Comment by bzbarsky-apple** [comment]
The only place where PAKEParameterError happens in the spec is incorrect input to the OpenCommissioningWindow command.

Wrong passcode for a PASE session attempt is not an OpenCommissioningWindow command...

**Comment by sowmyassp** [comment]
@bzbarsky-apple  Yes then this ticket is valid for BCM test-cases and for ECM test-cases the output is correct (Pairing Failure: ../../third_party/connectedhomeip/src/controller/CHIPDeviceController.cpp:1336: CHIP Error 0x00000032: Timeout) right??

**Comment by bzbarsky-apple** [comment]
This ticket does not look to be valid at all, as far as I can tell.  Again, where would a _cluster specific_ code come from in a PASE setup failure, where there are not cluster interactions happening?

**Comment by sowmyassp** [comment]
@bzbarsky-apple Ok, thank you I understood the test-case and I will close this issue
