### ISSUE TITLE
Audit DefaultDACVerifier against latest spec for any divergence

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#15541]
#### Problem
Spec is settled for Device Attestation. A lot of small changes have occurred over time in the spec. We need to ensure the current 
DefaultDACVerifier implementation follows all the necessary checks of the spec.

 #### Proposed Solution
Audit the DefaultDACVerifier implementation for what's missing for spec compliance.

**Comment by woody-apple** [comment]
Spec Review: Presently we believe we're conforming to spec, removing spec label.

**Comment by woody-apple** [comment]
Spec Review: Closing for now, @tcarmelveilleux will open an issue if we find any remaining problems.
