### ISSUE TITLE
[TV-App] Global attribute -FeatureMap returns status code as 0x86 Error(unsupported attribute) Response.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15566]
#### Problem
Though the feature map attribute is implemented in below mentioned clusters it throws an error code as 0x86(unsupported attribute)

1. Application Launcher Cluster[TC-MC1.3]
2. Media Input Cluster[TC-MC-1.4]
3. Channel Cluster[TC-MC-1.6]
4. Media Playback Cluster[TC-MC-1.7]
5. Audio Output Cluster[TC-MC-1.8]
6. Content Launcher Cluster[TC-MC-1.11]
7. Keypad Input Cluster [TC-MC-1.2] 
 * expected behavior:-FeatureMap bitmap value
 * actual behavior:-0x86(unsupported attribute)

PFA log below:
[TV-feature-map.txt](https://github.com/project-chip/connectedhomeip/files/8140612/TV-feature-map.txt)

**Comment by lazarkov** [comment]
Addressed in:
https://github.com/project-chip/connectedhomeip/pull/17473
