### ISSUE TITLE
ESP32/M5 IDF menuconfig missing option for setup pin code and discriminator 

### ISSUE THREAD

**Issue by kean-apple** [project-chip/connectedhomeip#15615]
#### Problem
ESP32/M5 IDF menuconfig missing option for setup pin code and discriminator
SHA: 448578dd09004679d10a7fa883f2e680de05079d
1. Run idf.py menuconfig
2. Go to Component Config -> CHIP Device Layer-> Testing Options
 - missing option to set setup pin code & decriminator

This use to be present a while back. Without this option it makes it hard to pair multiple M5 boards on the same network

<img width="447" alt="image" src="https://user-images.githubusercontent.com/73258860/155813439-cca5fd20-c13e-43be-a818-6d1059edab97.png">

**Comment by dhrishi** [comment]
@kean-apple I think that it was removed in https://github.com/project-chip/connectedhomeip/pull/14676 on purpose.

Discriminator is taken from persistent storage of the platform and if not available then the test value is used from [here](https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/CHIPDeviceConfig.h#L900). Similarly, setup pin code is calculated from the spake2 verifier and if not available then the test value is used from [here](https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/CHIPDeviceConfig.h#L890)

**Comment by dhrishi** [comment]
Closing this as it is addressed.
