### ISSUE TITLE
 [TC-TSTAT-2.1]Thermostat Cluster- Few attributes needs to developed in chip-tool.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15626]
#### Problem
CHIP-tool SDK software has to implement the the following attributes mentioned in Thermostat Cluster.

1. OccupiedSetbackMin attribute
2. OccupiedSetbackMax attribute
3. UnoccupiedSetback attribute
4. UnoccupiedSetbackMin attribute
5. UnoccupiedSetbackMax attribute 
6. EmergencyHeatDelta attribute
7. OccupiedSetback

system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 20e1a4a705770d5222a8ebf04e12ab2ce0304df6
Dut: All-Clusters-app and thermostat app

Reference Screenshot:
![image](https://user-images.githubusercontent.com/95841834/155955697-cdd9f181-261b-431d-928f-22d7abe376d9.png)

Spec Reference:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Thermostat.adoc#ref_sec_6_3_2_2_4_4

**Comment by andy31415** [comment]
These seem like optional attributes

**Comment by Rajashreekalmane** [comment]
@andy31415 All are mandatory attributes Expect EmergencyHeatDelta attribute based on the feature these attributes are supporting.

**Comment by bzbarsky-apple** [comment]
These are all supported and have been for a while.
