### ISSUE TITLE
New Testscripts are not running 

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#15620]
Summary :
I have added 3 Test scripts from Secure Channel,after the test Execution noticed added testscripts are not executed 

Execution screenshot and logs:
![image (1)](https://user-images.githubusercontent.com/57476670/155918103-062e05a9-7ba1-48d2-a797-0c3fecb6653b.png)
![image](https://user-images.githubusercontent.com/57476670/155918112-fa98be1e-2208-451e-a35e-c36920556691.png)
[Execution_log (1).zip](https://github.com/project-chip/connectedhomeip/files/8150333/Execution_log.1.zip)

Note :
1.i have tested this old commit id "593b427fffc850cade435523beed340f741fb6d7",in this commit id we can able to add & test new scripts ,this particular commit id date is feb 22
2.i have tested one more commit id "09af03fb005f0a4fe6b3ba4741dc43eebbe56bb6",in this commit id newly added  testscripts are not supporting ,this particular commit id date is feb23

**Comment by raju-apple** [comment]
@kowsisoundhar12 @manjunathambiger23 Can you guys try with this command ? `export NODE_OPTIONS="--max-old-space-size=5120"`and see if it still fails. Spoke to Vivien briefly and he mentioned that he has seen the nodes runner memory going out of space for chip-tool

**Comment by raju-apple** [comment]
A quick way to confirm is to just run : `./scripts/tools/zap_regen_all.py --type tests --tests chip-tool`

**Comment by kowsisoundhar12** [comment]
@raju-apple I have ran this command "./scripts/tools/zap_regen_all.py --type tests --tests chip-tool",EXecution got failed
![2022-03-03_09-29](https://user-images.githubusercontent.com/57476670/156493812-b14e516e-840d-4983-94d4-fb039e445ca7.png)
