### ISSUE TITLE
[ Android App] Cluster Interaction Tool commands and Sensor Cluster commands fails or app crashes (exits).

### ISSUE THREAD

**Issue by shivani-tipnis** [project-chip/connectedhomeip#15637]
Problem
Following commands fail or app crashes (exits) -

Cluster Interaction Tool commands -

- Color Control (Write Attribute) [ app crashes and exits ]
- Level Control (Read and Write Attribute) [ app crashes and exits ]
- OTA provider/OTA requestor [ app crashes and exits ]

Sensor Clusters commands -
- Read Pressure : returns fail

Expected behavior

- Cluster Interaction Tool commands and Sensor Cluster commands should pass. app should not crash and exit out.

Actual behavior

- Cluster Interaction Tool commands and Sensor Cluster commands fails or app crashes (exits).

Steps to reproduce

- Compile and flash app onto device
- Commission device using Android chip tool app using Commission with Wifi
- Run command (for eg. Read/Write Level Control commands)
- Run Cluster Interaction Tool Commands (mentioned above which are failing)

System configuration

- CHIP commit id: https://github.com/project-chip/connectedhomeip/commit/4668421c09d8d985de8be1bcaea535b431cd4118
- App: all_clusters_app
- Device: esp32devkit-c
- Android App: App built on the above mentioned CHIP commit id.

Device (esp32-devkitc) Logs:

[android_app_device_esp32devkitc_logs.pdf](https://github.com/project-chip/connectedhomeip/files/8159491/android_app_device_esp32devkitc_logs.pdf)

**Comment by dhrishi** [comment]
@andy31415 Can you please assign to someone appropriate?
