### ISSUE TITLE
Pressure measurement [TC-PRS-2.3] -Needs an SDK implementation on Non-global optional attributes.

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#15639]
**Problem:**
While Executing the behavior of the non-global attributes of the Pressuremeasurement cluster, few optional attributes throws error code as 0x86(unsupported attribute).In  [TC-PRS-2.1] , [TC-PRS-2.3] and [TC-PRS-3.1]  is got failed during the execution.

  **expected behavior** - Pass , status(0x0)
  **actual behavior** - Response Failure: IM Error 0x00000586: General error: 0x86 (unsupported attribute)
 
 **Actual steps** -  ./chip-tool pressuremeasurement read tolerance 1 1
                             ./chip-tool pressuremeasurement read scaled-value 1 1
                            ./chip-tool pressuremeasurement read scale 1 1
                            ./chip-tool pressuremeasurement read min-scaled-value 1 1
                             ./chip-tool pressuremeasurement read max-scaled-value 1 1
                             ./chip-tool pressuremeasurement read scaled-tolerance 1 1

**App used** - All cluster app
**platform** - Raspberrypi

**spec link:**

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/PressureMeasurement.adoc#features

![prs2 3](https://user-images.githubusercontent.com/93810525/156008135-eed6a3fb-af11-494f-810a-022a1dea2d3b.png)

Here i attached the log files for your reference
[prs fail.txt](https://github.com/project-chip/connectedhomeip/files/8170137/prs.fail.txt)

**Comment by andy31415** [comment]
Pressure management spec marks all of ScaledValue,MinScaledValue,MaxScaledValue,ScaledTolerance and Scale as `EXT`  feature wise.

So if the DUT does not have this feature (feature itself is marked as optional) then it seems reasonable for the device to say 'unsupported attribute'

**Comment by andy31415** [comment]
Test case should likely start with 'is feature supported' and only proceed if feature is supported.

The part that is unclear to me is what if we do not build this in our example (which seems spec-correct) yet at a later time some device comes in to certification with this feature and asks for certification. What do we do then?

**Comment by somu1710** [comment]
Then in the case optional attributes no need to verify? we have to verify the optional attributes also because other than this some clusters verifying optional attribute also

**Comment by bzbarsky-apple** [comment]
You can't require optional attributes to be implemented.  What exactly are you trying to verify?

@cjandhyala

**Comment by somu1710** [comment]
Optional attributes are 'not verifiable' for V1.0 as per discussion.So I close the ticket.
