### ISSUE TITLE
[ota-provider-app] Add counters for various QueryImageResponse and ApplyImageResponse commands

### ISSUE THREAD

**Issue by ukatira** [project-chip/connectedhomeip#15656]
#### Problem
There is no way right now to simulate real world scenarios where Provider replies Busy, gets the image and then Available or AwaitNextAction and then Proceed

 #### Proposed Solution
Add counters for various QueryImageResponse and ApplyImageResponse commands to simulate sending Busy/NotAvailable for a specified number of times and then sending Available or sending AwaitNextAction for a specified number of times and then sending Proceed.

**Comment by carol-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/15939 provides a way for ota-provider-app to be terminated and started back up with a different query image response.

**Comment by carol-apple** [comment]
Moving this back into v1. Had an offline discussion with @ukatira and the following test could be done more conveniently with this issue addressed:

> Requestor sends Query, Provider replies Busy with delay of say 180 sec, Requestor will query again based on delay and Provider responds with Available this time and transfer goes through.
