### ISSUE TITLE
Wrong usage of CharSpan by OTAImageProcessorImpl

### ISSUE THREAD

**Issue by harsha-rajendran** [project-chip/connectedhomeip#15726]
Issue:
The OTAImageProcessorImpl expects the imageFile parameter to be NULL-terminated string when in reality it is a char span (might or might not be null terminated).

> The reason it works is because all usages of the imageFile charspan in the OTA code simply use it as a null-terminated pointer 

That seems like a bug, no?  Nothing requires a CharSpan to be null-terminated.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/15660#discussion_r817383839_

**Comment by bzbarsky-apple** [comment]
This was fixed in #16482.
