### ISSUE TITLE
Update usage of PASE PasscodeId to always be 0 to match spec

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#15735]
#### Problem
It was raised in #15362 that passcode ID handling was incorrect and ambiguous for multi-admin. This led to spec issue https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4969, which was resolved by https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/4972.

The outcome of all of this is:

- When opening an ECM window, the passcodeID to use in PASE PBKDFParamRequest needs to always be 0.
- Non-zero values of passcodeID in PASE PBKDFParamRequest are forbidden
- PasscodeId field in OpenCommissioningWindow command needs to be removed

 #### Proposed Solution
- Update PASE and OCW code to follow https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/4972

**Comment by emargolis** [comment]
resolved with #15924
