### ISSUE TITLE
M5 lock app does not reflect lock/ unlock states with the help of an LED similar to what light app does 

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#15755]
#### Problem
M5 lock app does not reflect lock/ unlock states with the help of an LED similar to what light app does 

SHA: 448578dd09004679d10a7fa883f2e680de05079d

Steps to reproduce:

1. Build M5 lock app and pair with iOS Home app. 
2. Perform lock/ unlock from the iOS Home app. 
3. We do not see any LED states on M5 changing to reflect either lock or unlock state. 

Expected Results:

We need to toggle a LED on M5 for lock / unlock states similar to what we have for on/ off light or dimmable light app. 

Logs from M5 attached:
[M5-Lock-Unlock-No-LED-indication.txt](https://github.com/project-chip/connectedhomeip/files/8173491/M5-Lock-Unlock-No-LED-indication.txt)

**Comment by dhrishi** [comment]
@vinay-apple The purpose of controlling the led in the all-clusters-app is a sample demonstration of controlling attributes (OnOff cluster chosen). Similarly, you can manage the door lock attribute changes in the example [here](https://github.com/project-chip/connectedhomeip/blob/master/examples/all-clusters-app/esp32/main/DeviceCallbacks.cpp#L141) by handling the door lock cluster
