### ISSUE TITLE
Chip-Tool should support the "wild card" to read for all the commands from all the clusters for wildcard endpoint 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15803]
#### Problem
While verifying the Wild Card to read the all the features that is all the commands from all the clusters for wildcard endpoint 
it throws the status code as 0x7f (unsupported endpoint).

 * expected behavior:- Chip-tool should list all the available commands from all the clusters for wildcard endpoint.
 * actual behavior:- 0x7f (unsupported endpoint)

 * steps to reproduce:-sudo ./chip-tool any command-by-id  0xFFFFFFFF 0xFFFFFFFF 0 1 0xFFFF

* system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID:-883528dd3dadfcc665492be864866ad2e3889e16			
 
PFA log below:-
[wildcard command.txt](https://github.com/project-chip/connectedhomeip/files/8178534/wildcard.command.txt)

**Comment by bzbarsky-apple** [comment]
Please see "8.9.4.2. Valid Command Paths" in the spec.  You can't "read for all the commands", because that's nonsense.
