### ISSUE TITLE
[TC-IDM-2.2][TC-IDM-3.2] and [TC-IDM-4.2] -Chip-tool needs to support the"Dataversion field" value to set.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15812]
#### Problem
Chip-tool needs to provide a way to set the Dataversion field to set the value. As per the 
Test-Plan the test step 25 in [TC-IDM-3.2], test step 29 in [TC-IDM-2.2]  and test step 20 in  [TC-IDM-4.2] 
 is expecting to set the dataversion field value.

Reference Test-Plan
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc

**Comment by Garik098** [comment]
Adding to the above one, TC-IDM-2.1, TC-IDM-3.1 chip-tool support is needed for "SuppressResponse field" value to set. Steps in these testcases were expecting the SuppressResponse field value.

**Comment by Rajashreekalmane** [comment]
[https://github.com/project-chip/connectedhomeip/issues/15845](url)
