### ISSUE TITLE
TC-IDM-4.2]-Chip-tool needs to support the"  KeepSubscriptions flag" value to set.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15845]
#### Problem
Chip-tool needs to provide API to set the  KeepSubscriptions flag value.
 As per the Test-Plan, the test step 16 & 17 in [TC-IDM-4.2] is expecting to set keepsubscription flag to  true.

Test Spec Ref:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#ref_IM.SubscribeInteraction
Section 5.2.1.

Table shows, 'KeepSubscriptions' field to be mandatory to set, Currently chip-tool doesn't have option to set this field . 

PFA Screenshot:-
![image](https://user-images.githubusercontent.com/95841834/158975391-37745ae8-8ca7-4dce-b709-a5fe8b1fdd9e.png)

Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-4-2-reportdatamessage-from-dut-test-cases

**Comment by Rajashreekalmane** [comment]
[TC-IDM-4.1]Chip-Tool needs to provide a way to set the suppressresponse value for subscription request messages 

 PFA screenshot below
https://user-images.githubusercontent.com/95841834/158975391-37745ae8-8ca7-4dce-b709-a5fe8b1fdd9e.png

**Comment by Garik098** [comment]
Need the same above mentioned support for chip-tool-darwin as well

**Comment by vivien-apple** [comment]
@Rajashreekalmane The second request `[TC-IDM-4.1]Chip-Tool need to provide a way to set SuppressResponse field to True in step 10 for subscription request messages` is a separate issue. Can you file a separate issue for it ?
Furthermore I believe [TC-IDM-4.1] expect the test harness itself to answer with the `SuppressResponse` field set false which is an answer from the `Test Harness` not a command from `chip-tool`.

**Comment by vivien-apple** [comment]
> 


> Need the same above mentioned support for chip-tool-darwin as well

That would be a separate issue as well. Can you file such an issue.
