### ISSUE TITLE
M5 minimum connection time for wifi is too short

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#15861]
#### Problem
M5 network cluster minimum connection time is set to 20s. We have definitely seen connections take longer than this.

 #### Proposed Solution
ESP platform devs would need to set this to the proper number.

**Comment by cecille** [comment]
@g-coppock - can you give a summary of the scenario that was causing timeouts?

**Comment by g-coppock** [comment]
I didn't save any measurements, but the original issue I'd seen was that the command timeout was defaulting to 12 seconds (which would always cause a failure if the first connect attempt failed). We had just changed the overall command timeout to 40 seconds temporarily.

**Comment by cecille** [comment]
I think the failure happened when there was a retry on the connection.

I don't have any significant insight here - I might well have been wrong about 20s being too short. It was just lower than what we were using. Feel free to close if ESP is satisfied with the value as-is.

**Comment by jadhavrohit924** [comment]
I’ll  put up a PR that bumps up the timeout to 30s.
