### ISSUE TITLE
OTAProviderDelegate needs to clearly define who is responsible for responding

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#15889]
#### Problem
The `OTAProviderDelegate` functions don't document whether they will handle responding or whether the cluster needs to.  This can lead to two responses, or zero, where there should be one.

 #### Proposed Solution
Decide, for each of the delegate functions, whether it handles responses, and in which cases, or whether the cluster does.  Document it clearly.  Ensure that the cluster and the example delegate do the right things.

Possible ways to split up the responding:
1. Delegate does all of it.  In that case, the delegate functions should probably just return void, unless the cluster is expected to act on failure returns somehow.
2. Delegate does data responses, cluster handles status responses.  In that case, the delegate should return a status and the cluster should respond with that status if the status is failure or the command expects a status response (or both).
3. Delegate does all success responses, cluster handles error responses.  In that case, the delegate needs to return a status, cluster needs to send it only if the status is failure.

In both cases 2 and 3 delegate should probably be ensuring there is no attempt to send status after it calls AddResponseData.

@carol-apple @holbrookt

**Comment by holbrookt** [comment]
My recommendation is option 1 in your list of proposals. There isn't really much of a concept of "the cluster" when it comes to OTA Provider. So much is unique to each implementation that it doesn't make sense to have common cluster code. The delegate will have all of the information needed to respond to commands appropriately.
