### ISSUE TITLE
Fix Darwin framework generic interaction methods

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#15930]
#### Problem
Various issues in the code added in #15602 
1. API surface not consistent with our other APIs (dictionaries instead of objects), raw integers instead of NSNumber, etc.
2. What look like potential crashes (buffer overruns, deleting pointers to stack).
3. Various other bits.

See https://github.com/project-chip/connectedhomeip/pull/15272#pullrequestreview-902000294

 #### Proposed Solution
Fix those.

**Comment by bzbarsky-apple** [comment]
@kpark-apple @anush-apple

**Comment by woody-apple** [comment]
Darwin Review: Assigning to @bzbarsky-apple to see if anything is outstanding.

**Comment by bzbarsky-apple** [comment]
Looks good at this point.
