### ISSUE TITLE
bootstrap.sh and activate.sh do essentially the same thing

### ISSUE THREAD

**Issue by rwalker-apple** [project-chip/connectedhomeip#1593]
#### Problem
//scripts/bootstrap.sh and //scripts/activate.sh do essentially the same thing, but their roles aren't well documented.  Both eventually run their namesakes in pigweed, but those namesakes are actually the same file

 #### Proposed Solution
document the difference between them or delete one of them

**Comment by mspang** [comment]
I definitely agree with merging them, filed https://bugs.chromium.org/p/pigweed/issues/detail?id=229 for this
