### ISSUE TITLE
Power source cluster testcase [TC-PS-2.1] SDK needs implementation on  non-global Mandatory attributes .

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#15960]
**Problem**

While Executing the behavior of the non-global attributes of the power source cluster, few  Mandatory attributes and optional attributes throws error code as 0x86(unsupported attribute). [TC-PS-2.1], [TC-PS-3.1].

** Expected behavior** - pass , status 0x0
 ** Actual behavior** - failure , status - 0x86 , General error [Unsupported attribute]
failing commands -
 
**MANDATORY:**
 ./chip-tool powersource read wired-current-type 1 1
./chip-tool powersource read battery-quantity 1 1
./chip-tool powersource read battery-functional-while-charging 1 1
./chip-tool powersource read battery-replacement-description 1 1
./chip-tool powersource read battery-replaceability 1 1
./chip-tool powersource read battery-replacement-needed 1 1

Here i attached the screenshot for your reference
![PRS 2 1 ](https://user-images.githubusercontent.com/93810525/157244146-671f38a7-b1a7-4b10-8d21-e53eed1f58ff.png)

And here I attached one log also
[PRS2.1 FAIL.txt](https://github.com/project-chip/connectedhomeip/files/8206433/PRS2.1.FAIL.txt)

**Comment by andy31415** [comment]
I believe a lot of these attributes depend on features - like WIRED feature for the wired attbitues and `BAT` for the battery information.

Test cases should be updated to apply the test based on what the feature map says is supported.

**Comment by somu1710** [comment]
As feature map supports for the WIRED feature ,then it should be implement right ?

FYI-**./chip-tool powersource read feature-map 1 1**

[1651245038.584442][2428:2433] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_002F Attribute 0x0000_FFFC DataVersion: 1887093579
[1651245038.584599][2428:2433] CHIP:TOO:   **FeatureMap: 0**

![PS F](https://user-images.githubusercontent.com/93810525/165974734-d083a453-2d0e-4413-a724-a952c1d546c9.png)

**Comment by andy31415** [comment]
I see featuremap is 0, so no features are enabled/supported.

I expect bitwise to have 0x01 to be wired, 0x02 to be bat, 0x04 to be rech and 0x08 to be replc.

To be specific: "Feature Map == 0" means no features (the list of features mentions "bits" so bit 0 is 0x01 ... it would have been clearer if spec would have written the constant bitflag as well I guess).

**Comment by andy31415** [comment]
> some of the attributes in BAT features are mentioned as mandatory in test plan but as per spec in the conformance its mentioned as [BAT].

Spec is always considered correct in my understanding. Test plan should be adjusted and remove the mandatory bits if spec says optional.

**Comment by somu1710** [comment]
Then in the case test plan needs to update as per spec right? If it changes means we cant able to verify this test case because of no features.This test case is only verifiyable by using real DUT which is supports the features?

**Comment by somu1710** [comment]
In recent commit its fixed and the feature map value is getting as 2 and its supporting BAT mandatory attributes.so i am closing the issue.
