### ISSUE TITLE
Media Playback cluster-While verifying test cases they given precondition as "load/select the media content..". TV-app needs to provide a way to load/select in chip-tv-app.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15992]
#### Problem
While verifying media playback cluster test cases, they given precondition as "load/select the media content..". chiptool needs to provide a way to load/select in chip-tv-app.
 
 * screenshots, images, logs, etc.
 >
![image](https://user-images.githubusercontent.com/95841834/157390894-3d55768a-45d4-4740-b8cc-95f75acc839f.png)

**Comment by chrisdecenzo** [comment]
Hi @Rajashreekalmane - with the dummy tv-app, you can just send a pause command to the TV to set the precondition state. Eg:

chip-tool mediaplayback pause 1234 3 

Can you add this instruction to the test scripts?
