### ISSUE TITLE
[TC-MC-4.1]- Chiptool needs to provide a way to verify if the device really woke-up from low power state.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#15995]
#### Problem
As per Test-Plan, the TestCase [TC-MC-4.1] step 3 says , TH needs to send a magic packet to wake-up a device and Verify that the DUT is no longer in a low-power state, but the step prior to sending is ‘sleep’ command and expects the device to wake up from low power state after sending this magic packet. I dont think we have a way to verify if the device really woke-up from low power state.

Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-4-1-wake-on-lan-verification

**Comment by chrisdecenzo** [comment]
I added this verification note to the test plan:
To verify a device has woken up, any Matter cluster command can be send to the device (for example, read descriptor cluster at endpoint 1).

@Rajashreekalmane - is there an update needed to the test script?
