### ISSUE TITLE
[TC-MC-3.1]KeyPad Input Cluster-In Chip-Tool not able to send a navigation keycode from TH to DUT when DUT in a processing state.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16009]
#### Problem
As per the Test-Plan In [TC-MC-3.1]KeyPad Input Cluster test case test step 10 says that
 we should send navigation keycode to DUT, when DUT is in progress state, but currently Chip-tool not able 
to send keycode when DUT is in progress state. Chip-tool needs to provide a way to send navigation keycode 
when DUT is in progress state.
 
 * screenshots, images, logs, etc.
 
![image](https://user-images.githubusercontent.com/95841834/157450005-4e190c82-18a1-489c-80ed-1ba60fbb1a9e.png)

Spec Reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/KeypadInput.adoc#sendkey-command

**Comment by chrisdecenzo** [comment]
Hi @Rajashreekalmane  - I'm not sure that this is a valid test case to have since that error code (2) is context specific and there won't be a uniform way to force the device into such a state. I'm not sure that every error condition can be created on every device.

**Comment by lazarkov** [comment]
@Rajashreekalmane can you please close the issue if it's no longer valid?
