### ISSUE TITLE
KVS is being initialized multiple times with different paths

### ISSUE THREAD

**Issue by harsha-rajendran** [project-chip/connectedhomeip#16015]
The KVS Init() call is being made atleast two times in Linux/Darwin applications (perhaps others as well). The first time with a custom path passed in by the application command line arguments (or default KVS path.). The second time inside PosixConfig::Init() with the default KVS path.
This might cause discrepancies, especially if the configuration paths are different. Currently, the code silently ignores the second init().

_Originally posted by @andy31415 in https://github.com/project-chip/connectedhomeip/pull/15963#discussion_r821853254_

**Comment by woody-apple** [comment]
Issue Scrub: Assigning to @tcarmelveilleux for v1.1
