### ISSUE TITLE
[TC-MF-1.6] RevokeCommissioning commands seems to always fail when used in YAML scripts

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#16018]
RevokeCommissioning commands seems to always fail when used in YAML scripts, the commands seems to work fine when used with the chip-tool CLI.

Attaching screenshots for reference 
1.Test plan screenshot
![image](https://user-images.githubusercontent.com/12559578/157474506-a0482a88-33a2-4ede-ba8f-efbce3c643e9.png)
2.YAML logs
[revokecommandfail.txt](https://github.com/project-chip/connectedhomeip/files/8216141/revokecommandfail.txt)
![revokecommandfail](https://user-images.githubusercontent.com/12559578/157478816-efe86ebe-1fc5-4511-9bf9-c5a9ed48bec1.png)

**Comment by raju-apple** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/TestDiscovery.yaml#L290

**Comment by kvikrambhat** [comment]
Closing issue , command works fine when "timedInteractionTimeoutMs" argument is used.
