### ISSUE TITLE
Controllers should not implicitly store data without using the Storage Delegate

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#16028]
#### Problem
The Storage Delegate passed in to controllers allows the client application to implement storage in any way they see fit.
Unfortunately, our platform layers and the controller facing SDK have divergent mechanisms for storage. 

The platform layer(at least on Darwin) uses a build time configured path to decide where things are stored. It has no knowledge of the Controller's storage interface.

This results in any Controller instance storing things in 2 completely separate storages. The Platform Layer's KVS is completely opaque to the client application. 

 #### Proposed Solution
https://github.com/project-chip/connectedhomeip/pull/16005 adds a mechanism to configure the platform layer KVS location but that doesn't solve the main problem where 2 disjoint storage implementations are being used.

A controller's storage delegate must override the platform's KVS implementation.

**Comment by bzbarsky-apple** [comment]
I believe at this point this is fixed.  @sagar-apple can you please confirm?
