### ISSUE TITLE
[TC-MF-1.4] YAML Support required to check length of list attribute

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#16094]
1. Need support to verify the current length of a list attribute read from the DUT and verify the values of each list element.
 Test cases that need this feature : TC-MF-1.1/1.2/1.3/1.4/1.13/1.14/1.15/1.16/1.17/1.18/1.19/1.20 [12 test cases]
![image](https://user-images.githubusercontent.com/12559578/157805131-578f8871-9002-4241-ae57-f5130e8f67f3.png)

2.Need support to check DNS-SD frames from DUT 
![image](https://user-images.githubusercontent.com/12559578/157846738-f06c0592-cbcb-4edf-9b9a-f9e5439a4193.png)

**Comment by bzbarsky-apple** [comment]
This is supported in chip-tool: you list your expected value, and chip-tool verifies that the expected and observed lengths match.
