### ISSUE TITLE
[TC-MF-1.17] Need support for Remove Fabric command in YAML

### ISSUE THREAD

**Issue by kvikrambhat** [project-chip/connectedhomeip#16104]
Need support to send RemoveFabric command to DUT from a YAML script.

Adding test plan screenshot for reference 
![image](https://user-images.githubusercontent.com/12559578/157848571-d23d7555-99dd-4cf8-913a-e0e47c75c804.png)

**Comment by bzbarsky-apple** [comment]
This is supported in YAML.  @kvikrambhat may I ask what made you think it's not supported?
