### ISSUE TITLE
[TE8][TC_WNCV_3_1, TC_WNCV_3_2, TC_WNCV_3_4,  TC_WNCV_3_5, TC_WNCV_4_3] CurrentPositionLiftPercentage is optional 

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16116]
#### Problem
Chip-Tool tries to read CurrentPositionLiftPercentage although it is marked as optional according to the spec. Our device does not have this attribute. 

 #### Proposed Solution
Check should not fail if it is not present.

**Comment by bzbarsky-apple** [comment]
> although it is marked as optional according to the spec

Those reads are gated on PICS bits, as far as I can tell.  Was that PICS set correctly for the test?

**Comment by jmeg-sfy** [comment]
Indeed if you can use PICS info the file to filter out those

**Comment by eve-cxrp** [comment]
Well, the Test Harness has no selection for PICS? Or did I miss that?

**Comment by jmeg-sfy** [comment]
file  /tmp/PICS.txt contains let say:
A_CONFIGSTATUS=0

./out/debug/standalone/chip-tool tests Test_TC_WNCV_2_2 0x12345 --PICS /tmp/PICS.txt

the if = 0 it will skip the test

sadly YAML  cannot simply read the feature map to apply a test (yet hopefully)




then you got
[1643286226417] [32173:84101267] CHIP: [TOO]  ***** Test Step 2 : Reads ConfigStatus attribute from DUT
[1643286226417] [32173:84101267] CHIP: [TOO]  **** Skipping: A_CONFIGSTATUS == false
