### ISSUE TITLE
SoftAP is not implemented in chip-tool

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#16112]
#### Problem

chip-all-clusters-app does not currently support Custom Commissioning Flow or SoftAP as part of its commissioning flow as in test-plan it says we need to test it.

Test-plan reference:
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicediscovery.adoc#tc-dd-2-2-discovery-by-commissioner-verification-dut-commissioner

**Comment by bzbarsky-apple** [comment]
SoftAP is not supported in the SDK for 1.0.
