### ISSUE TITLE
[TE8][TC_WNCV_2_1, TC_WNCV_4_4] Does not respect feature map

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16117]
#### Problem
Our accessory does not have a Tilt feature. So reading the tilt attributes results in execution error. 

 #### Proposed Solution
Respect the feature map.

**Comment by jmeg-sfy** [comment]
Same you must (sadly since this is static config and not dynamic test) use the PICs filter via a parameter file

**Comment by eve-cxrp** [comment]
seems to be related to https://github.com/project-chip/connectedhomeip/issues/16116
