### ISSUE TITLE
[TE8][TC-IDM-XX] Proposal to embed a idmtest cluster for IDM testing

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#16123]
#### Problem
Right now test steps for IDM checking on the DUT is not scalable nor scriptable
If we had a kinda of test only cluster for the IDM we will not have this kind of trouble where we cannot checks thoroughly a device IDM
A kind of mandatory extra cluster for this would do the jobs minus a bit more flash used..

 #### Proposed Solution
I suggest to amend the specs to embed this or just drop all IDM tests from the TH

**Comment by mrjerryjohns** [comment]
Most, if not all of the IDM tests are meant to utilize standard utility clusters that exist on all devices. Is there a specific concern with that approach that you see as not being viable?
