### ISSUE TITLE
[TE8][TC-LC-1.1] Fixed Label cluster				

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#16137]
#### Problem
The tests state chip-tool must write into the fixedlabel cluster
BUT there is no write command possible list
Test wants to check the UNSUPPORTED_WRITE

 ./chip-tool fixedlabel write label-list [room:bedroom]

  ./chip-tool fixedlabel command_name [param1 param2 ...]

  +-------------------------------------------------------------------------------------+
  | Commands:                                                                           |
  +-------------------------------------------------------------------------------------+
  | * command-by-id                                                                     |
  | * read-by-id                                                                        |
  | * read                                                                              |
  | * write-by-id                                                                       |
  | * subscribe-by-id                                                                   |
  | * subscribe                                                                         |
  | * read-event-by-id                                                                  |
  | * subscribe-event-by-id                                                             |
  +-------------------------------------------------------------------------------------+

**Comment by ReneJosefsen** [comment]
Agree, the test-steps is not valid, they should be changed to:

./chip-tool fixedlabel write-by-id 0 [room:bedroom] <nodeId> 0

This seems to return the error 0x88, which is UNSUPPORTED_WRITE

**Comment by bzbarsky-apple** [comment]
Please file test plan issues at https://github.com/CHIP-Specifications/chip-test-plans/issues/new/choose
