### ISSUE TITLE
Issues Setting the Target

### ISSUE THREAD

**Issue by vicc-superhome** [project-chip/connectedhomeip#16160]
#### Problem
##### Expected Behavior
Following steps in the [examples](https://github.com/project-chip/connectedhomeip/tree/83aac592cedfa04cb2941bb0f75f2a4c44ddf799/examples/all-clusters-app/esp32#chip-esp32-all-clusters-example) readme to set the target.

##### Actual Behavior
After I setup my environment, I change directory to where I cloned `connectedhomeip`:
```
$ cd ${HOME}/tools/esp-idf
$ ./install.sh
$ . ./export.sh
$ cd {path-to-connectedhomeip}
```
I then download and install packages:
```
$ source ./scripts/bootstrap.sh
$ source ./scripts/activate.sh
```

However, when I attempt to set the target using:
```
idf.py set-target esp32
```
I get the following error: `zsh: command not found: idf.py` Not sure if I need to switch back to the 4.4 esp-idf repo or not.
##### Actual Behavior
Using MacOS Monterey 12.2.1
 >

**Comment by alexandertv** [comment]
Same Problem with MacOs 12.3
