### ISSUE TITLE
[TC_NC_1.1] and [TC_NC_1.3] Feature map is implememted but while passing this command we are getting 0x86(Unsupported attribute)

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#16163]
#### Problem
Feature map is implememted but while passing this command we are getting 0x86(Unsupported attribute)
 * expected behavior :  FeatureMap value should be 1
 * actual behavior : Response Failure: IM Error 0x00000586: General error: 0x86
 * steps to reproduce : ./chip-tool descriptor read feature-map 1 1
 * screenshots, images, logs, etc.
 >
[TC_NC_1.1_feature.txt](https://github.com/project-chip/connectedhomeip/files/8242836/TC_NC_1.1_feature.txt)

**Comment by sowmyassp** [comment]
Same issue facing in [TC-BOOL-1.1] test-case also

**Comment by sowmyassp** [comment]
[TC-NC-1.3]Feature map is implememted but while passing this command we are getting 0x86(Unsupported attribute)

expected behavior : FeatureMap value should be 2
actual behavior : Response Failure: IM Error 0x00000586: General error: 0x86
steps to reproduce : ./chip-tool descriptor read feature-map 1 1
screenshots, images, logs, etc.
[TC_NC_1.3.txt](https://github.com/project-chip/connectedhomeip/files/8321971/TC_NC_1.3.txt)

**Comment by bzbarsky-apple** [comment]
> Feature map is implememted 

Is it?  In the SDK descriptor cluster does not have a feature map attribute.

**Comment by sowmyassp** [comment]
@bzbarsky-apple Sorry actually the command should be "./chip-tool networkcommissioning read feature-map 1 0" but I read feature-map for descriptor, sorry its my mistake

**Comment by bzbarsky-apple** [comment]
@sowmyassp OK.  Does reading the networkcommissioning feature map work for you?  I would expect that to work.

**Comment by sowmyassp** [comment]
@bzbarsky-apple Yes its working
