### ISSUE TITLE
[TC-OO-2.4] - The value of onoff always seems to return false

### ISSUE THREAD

**Issue by cherishQAQ123** [project-chip/connectedhomeip#16162]
[TC-OO-2.4]
step 4d 5g 6d doesn't return expected outcome.
expected outcome is true.

[TC-OO-2.4.md](https://github.com/project-chip/connectedhomeip/files/8242531/TC-OO-2.4.md)

The value of onoff always seems to return false.

**Comment by markus-becker-tridonic-com** [comment]
Interestingly, for me it always returns TRUE, failing in steps 3d and 5d.

**Comment by CSS-IanTseng** [comment]
I am always receive "TRUE" and failing in steps 3d and 6h.

**Comment by bzbarsky-apple** [comment]
@markus-becker-tridonic-com @cherishQAQ123 Is this an issue on current tip?
