### ISSUE TITLE
[TE8][TC_WNCV_4_1] Chip-Tool truncates 100th data

### ISSUE THREAD

**Issue by eve-cxrp** [project-chip/connectedhomeip#16167]
#### Problem
Step 4a from test case verification steps:

`./chip-tool windowcovering go-to-lift-percentage 75 7520 1 1`

chip-tool should send `7520` as target lift percentage 100th but it truncates it to 7500.

**Comment by jmeg-sfy** [comment]
this is a bug on the cluster window covering SDK
need to a do PR for this

**Comment by eve-cxrp** [comment]
I don't think it is? I was verifying it by calling directly `WindowCovering::Attributes::TargetPositionLiftPercent100ths::Get` and this function was already returning me 7500. This had nothing to do with the `window-covering-server` impl. So my guess was that it is related to `chip-tool` that it uses the `75` as also the value for the `Percent100ths`?
