### ISSUE TITLE
 Got back error trying to read fabrics list Error Domain=CHIPErrorDomain Code=9 "Transaction timed out. seen when trying to read fabric list after "Remove All Fabrics" 

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#16191]
#### Problem
 Got back error trying to read fabrics list Error Domain=CHIPErrorDomain Code=9 "Transaction timed out. seen when trying to read fabric list after "Remove All Fabrics" 

SHA:  d86a7d49e050f6d9eec438934ea205aa93ce77fd

Steps to reproduce

1. Pair M5 with Chip tool 1 and toggle light and it works fine. 
2. Pair M5 with Chip tool 2 and toggle light and it works fine. 
3. On Chip tool 1 go to Fabric Management and "Remove All Fabrics" 
4. Go out of Fabric Management screen and then select Fabric Management to trigger reading of fabric list. 
5. Seeing timeout error as seen below on both Chip tool 1 and Chip tool 2

-01F582351B7E/CHIPTool.app> (executable, loaded), key: Transaction timed out., value: , table: Localizable, localizationName: (null), result: Transaction timed out.
2022-03-14 12:21:28.184055-0700  localhost CHIPTool[1029]: Got back fabrics list: (null) error Error Domain=CHIPErrorDomain Code=9 "Transaction timed out." UserInfo={NSLocalizedDescription=Transaction timed out.}
2022-03-14 12:21:28.184098-0700  localhost CHIPTool[1029]: (CHIP) [com.zigbee.chip:all] ðµ [1647285688184] [1029:39009] CHIP: [DMG] Time out! failed to receive report data from Exchange: 40037i
2022-03-14 12:21:28.184499-0700  localhost CHIPTool[1029]: Got back error trying to read fabrics list Error Domain=CHIPErrorDomain Code=9 "Transaction timed out." UserInfo={NSLocalizedDescription=Transaction timed out.}

Need to clarify if this is an expected behavior and if the error code seems right? should this still timeout trying to read or another error code relevant to empty fabric list should be returned? 

[chiptool1-logs-timeout-reading-fabric-after-remove-all-fabrics.txt](https://github.com/project-chip/connectedhomeip/files/8248074/chiptool1-logs-timeout-reading-fabric-after-remove-all-fabrics.txt)
[chiptool2-logs-timeout-reading-fabric-after-remove-all-fabrics.txt](https://github.com/project-chip/connectedhomeip/files/8248075/chiptool2-logs-timeout-reading-fabric-after-remove-all-fabrics.txt)
[M5-logs-timeout-reading-fabric-after-remove-all-fabrics.txt](https://github.com/project-chip/connectedhomeip/files/8248076/M5-logs-timeout-reading-fabric-after-remove-all-fabrics.txt)
![read-fabric-timeout-after-remove-all-fabrics](https://user-images.githubusercontent.com/99367303/158248334-d8818caa-35fb-4bbd-85c3-2fc0a46077fb.jpeg)

**Comment by bzbarsky-apple** [comment]
When all the fabrics are removed from the device, trying to talk to it will time out, no?  In that you will not be able to establish a CASE session, etc.  So timeout looks correct to me here.
