### ISSUE TITLE
M5 crash seen while reporting was setup abort() was called at PC 0x40126635 on core 1

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#16200]
#### Problem
M5 crash seen while reporting was setup abort() was called at PC 0x40126635 on core 1

SHA: d86a7d49e050f6d9eec438934ea205aa93ce77fd

Steps to reproduce: 

1. Pair M5 with chip tool and setup reporting with Min 1s, Max 2s, delta: 1 C
2. Verify reporting is working fine by changing temp values on M5 board
3. Exit the temp sensor screen on chip tool and come back into temp sensor screen again 
4. Seems like within ~1-2 mins of step 3, saw M5 crash with below logs on M5:

abort() was called at PC 0x40126635 on core 1
0x40126635: chip::Inet::UDPEndPointImplLwIP::LwIPReceiveUDPMessage(void*, udp_pcb*, pbuf*, ip_addr const*, unsigned short) at /Users/vganji/MATTER-iOS/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/lib/support/CodeUtils.h:489
 (inlined by) chip::ReferenceCounted<chip::Inet::UDPEndPoint, chip::Inet::EndPointDeletor<chip::Inet::UDPEndPoint>, 1>::Retain() at /Users/vganji/MATTER-iOS/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/lib/core/ReferenceCounted.h:55
 (inlined by) chip::Inet::UDPEndPointImplLwIP::LwIPReceiveUDPMessage(void*, udp_pcb*, pbuf*, ip_addr const*, unsigned short) at /Users/vganji/MATTER-iOS/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/inet/UDPEndPointImplLwIP.cpp:374

[chiptool-logs-M5-crash-seen-during-reporting.txt](https://github.com/project-chip/connectedhomeip/files/8248366/chiptool-logs-M5-crash-seen-during-reporting.txt)
[M5-logs-M5-crash-seen-during-reporting.txt](https://github.com/project-chip/connectedhomeip/files/8248367/M5-logs-M5-crash-seen-during-reporting.txt)

**Comment by dhrishi** [comment]
@kean-apple Do you still see this with the latest codebase?
