### ISSUE TITLE
[TC-I-2.2] Not meeting the expected results

### ISSUE THREAD

**Issue by cherishQAQ123** [project-chip/connectedhomeip#16206]
[TC-I-2.2]
step 2c 6b doesn't return expected outcome.
step 2c ：The value of the identificationtime attribute should be approximately equal to 0x0032.
step 6b ：The value of the identificationtime attribute should be approximately equal to 0x000a.
[TC-I-2.2.md](https://github.com/project-chip/connectedhomeip/files/8249511/TC-I-2.2.md)

**Comment by Rajashreekalmane** [comment]
@cherishQAQ123 Issue was resolved in latest image, Could you please re-verify and close the issue.

**PFA log below for your reference:**
[Identify with pics.log](https://github.com/project-chip/connectedhomeip/files/9681442/Identify.with.pics.log)
