### ISSUE TITLE
In YAML if labels are same facing build error in some platform

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#16236]
Summary:
               In YAML scripts when the labels are similar in the beginning of the label we are facing build error in some checks of PR but works fine in Linux platform
               
YAML files
[Test_TC_I_2_3.zip](https://github.com/project-chip/connectedhomeip/files/8255751/Test_TC_I_2_3.zip)

Build error screenshot:
![image](https://user-images.githubusercontent.com/84442963/158434413-1d3324cc-2ae9-4198-a55c-bb55dfd5f510.png)

**Comment by bzbarsky-apple** [comment]
@krypton36 Could you take a look?
