### ISSUE TITLE
ClusterInfo should not be dual-purposed to track both dirty things, read/subscribe paths and version filter list.

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#16242]
#### Problem

`ClusterInfo` is class used to track both dirty items in the global dirty set, as well as paths in the original subscribe/read requests AND the version filter list. Making this triple-purpose ends up being wasteful in terms of the amount of RAM this object takes up.

### Proposal

Make three different variants: `DirtyAttributeInfo`, `RequestPathInfo` (or re-use `AttributePathParams`?) and `DataVersionPathInfo`.

Notably:
1. `mTickTouched` is not necessary for request path storage
2. `mNodeId` should be removed entirely in all use-cases for 1.0
3. `mAttributeId` and `mEventId` should be unioned when used for request path storage. `mEventId` isn't needed for the object tracking the dirty set.
4. `mListIndex` should be removed entirely for 1.0
5. `mDataVersion` should only be present in the data version representation.
6. `mIsUrgentEvent` should be unioned, and only present in the RequestPathInfo.

**Comment by bzbarsky-apple** [comment]
When `mDataVersion` is used, neither an attribute nor an event id can be present, right?
