### ISSUE TITLE
`AttributeCache` should cache data versions and use them in subsequent Read/Subscribe requests

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#16243]
#### Problem

When issuing reads/subscribes, most folks aren't actually using data versions, resulting in a fairly large number of reports sent during subscription priming as well as reads. While we have API support in `ReadClient` to express these data versions, the actual management and storage of those data versions across transactions is not very easily achieved today.

#### Proposal

`AttributeCache` provides a great solution to cache attribute state that can be re-used across multiple read/subscribe interactions. Extending it to cache data versions that can then be used to populate subsequent read/subscribe requests transparently without application involvement would make this feature a lot more usable.

**Client-side specifics:**

1. Extend `AttributeCache` to also store the data version alongside other attribute state. Would be worthwhile reserving an attribute ID to track data versions to normalize this.
2. Provide a means to retrieve the data version through the `ReadClient::Callback` so that it gets routed to the AttributeCache at the time the Subscribe/Read request is getting formed. An option should be added to `ReadPrepareParams` to signal this modality of retrieval, which would circumvent the typical approach of retrieving the version list from the params itself.
3. There's a strong chance we cannot fit every single data version filter path in the Read/Subscribe request. Structure the logic such that it's a 'best-effort' semantic, such that it'll _try_ to stuff as many of the paths as it can in the request, but if it cannot fit them all, to correctly roll back and safely close out the Read/Subscribe request.
4. To prioritize the right paths in the limited space available in the packet, sort the attributes by cluster by size in the cache, and form version filter paths in descending order of largest cluster in the cache to smallest.

**Server-side specifics:**

1. We need to change the logic such that we allocate a separate pool for the data version filter list (see related #16242 )
2. Structure the read/subscribe parsing logic to not fail if we cannot allocate any more out of the data version filter pool. This just means we'll be sub-optimal, but we shouldn't have to fail the request. This necessitates a spec change as well.
3. We should free up the pool once we establish a subscription, so that we can release it for use with other subscriptions.

**Comment by yunhanw-google** [comment]
When further thinking about the implementation, for 4.  wildcard attribute path, it seems to include wildcard endpointId, wildcard clusterId, we need to expand it to cluster instances, however, in client side, we don't have ember so we don't know emberAfEndpointCount and cannot do such expanding.
