### ISSUE TITLE
[TE8] TC-PRS-3.1 Attributes with client as DUT

### ISSUE THREAD

**Issue by cabin15** [project-chip/connectedhomeip#16268]
Test-Case ID:-[TC-PRS-3.1] Attributes with client as DUT

Problem
While Executing the behavior of the attributes of the pressuremeasurement cluster, a few attributes throws error code as 0x86(unsupported attribute).
- tolerance
- scaled-value
- min-scaled-value
- max-scaled-value
- scaled-tolerance
- and so on (Please check with 0x86 error code on attached log)

Test log
[TC-PRS-3.1.txt](https://github.com/project-chip/connectedhomeip/files/8258794/TC-PRS-3.1.txt)

**Comment by woody-apple** [comment]
Spec Review: We do not believe this a spec compliance issue, but is a bug. @cabin15 does this still happen? Please re-open if it does.
