### ISSUE TITLE
[TC-LVL-5.1]step 2a, 2b, is return <0>

### ISSUE THREAD

**Issue by zhangxiaosen88** [project-chip/connectedhomeip#16277]
[TC-LVL-5.1]
step 2a,2b doesn't return expected outcome.
expected outcome is < current level: 64>

[TC-LVL-5.1.md](https://github.com/project-chip/connectedhomeip/files/8260206/TC-LVL-5.1.md)

The value of  read current-level always seems to return <current level: 0>

**Comment by cjandhyala** [comment]
@zhangxiaosen88 Test plan is updated lately , pls chk with the latest test plans and file issue in test plan repo if it still an issue. Closing this ticket in SDK repo  for now .
