### ISSUE TITLE
[TE8] TC-SC-4.2 Commissionable Node Discovery - Commissioner Case [DUT - Commissioner]

### ISSUE THREAD

**Issue by cabin15** [project-chip/connectedhomeip#16271]
Test-Case ID:-[TC-SC-4.2] Commissionable Node Discovery - Commissioner Case [DUT - Commissioner]

Problem
Step 5 of the TC-SC-4.2 is not clear for tester to perform.
`By any means, TH adds an unknown key/value pair in the advertised data(e.g. AB=12345) and is put in Commissioning Mode using Open Basic Commissioning Window command`

Need more clarification how to achieve the expected result of Step 5.

**Comment by bzbarsky-apple** [comment]
@cjandhyala This sounds like a bug against the test steps, not the SDK?

**Comment by cjandhyala** [comment]
@bzbarsky-apple correct. 
@cabin15 Pls file the issue against test plans
