### ISSUE TITLE
[TC-CC-5.2]  read current-x  current-y

### ISSUE THREAD

**Issue by zhangxiaosen88** [project-chip/connectedhomeip#16279]
[TC-CC-5.2]
step 3a.3b, 5a,5b doesn't return expected outcome.

[TC-CC-5.2.md](https://github.com/project-chip/connectedhomeip/files/8260599/TC-CC-5.2.md)

**Comment by cjandhyala** [comment]
@zhangxiaosen88 Test plan is updated lately, pls chk with the latest test plans and file issue in the test plan repo if it is still an issue. Closing this ticket in the SDK repo for now.
