### ISSUE TITLE
[TE8] TC-MF-1.11 Device exits commissioning mode after 20 failed commission attempts [ECM] [DUT - Commissioner]

### ISSUE THREAD

**Issue by cabin15** [project-chip/connectedhomeip#16272]
Test-Case ID:-[MF-1.11] Device exits commissioning mode after 20 failed commission attempts [BCM] [DUT - Commissioner]

Problem
Expected:
After 20 failed commission attempts using invalid passcode, 21st commissioning attempt should fail.

Actual behavior:
After 20 failed commission attempts using invalid passcode, 21st commissioning attempt succeeds.

Test log
[TC-MF-1.11.txt](https://github.com/project-chip/connectedhomeip/files/8258953/TC-MF-1.11.txt)

**Comment by bzbarsky-apple** [comment]
@cabin15 Is this still an issue on tip?

**Comment by woody-apple** [comment]
Spec Review: We do not believe this a spec compliance issue, but is a bug. @cabin15 does this still happen? Please re-open if it does.
