### ISSUE TITLE
[TC-LVL-6.1] step 4，read  current level  is error 

### ISSUE THREAD

**Issue by zhangxiaosen88** [project-chip/connectedhomeip#16278]
[TC-LVL-6.1]
step 4 doesn't return expected outcome.
expected outcome is <2>

[TC-LVL-6.1.md](https://github.com/project-chip/connectedhomeip/files/8260251/TC-LVL-6.1.md)

The value of current level always seems to return <0>

**Comment by cjandhyala** [comment]
@zhangxiaosen88 Test plan is updated lately , pls chk with the latest test plans and file issue in test plan repo if it still an issue. Closing this ticket in SDK repo for now .
