### ISSUE TITLE
[TC-I-2.2]-Identify Cluster-test-step 5 mismatched with the expected outcome.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16282]
#### Problem
As per the Test-Plan, when we sends IdentifyQuery command to DUT,DUT should not send a IdentifyQueryResponse command to TH in test step 5. Currently in chip-tool getting a response as SUCCESS(0x00).
 
 * expected behavior:-DUT should not send a IdentifyQueryResponse command to TH
 * actual behavior:-In TH getting SUCCESS response with DUT is responding  identifyTime is 
 at 0( Sending back default response)

 * steps to reproduce:- sudo ./chip-tool identify identify-query 3 0
 
Test-Plan reference
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/identify.adoc#tc-i-2-2-primary-functionality-with-server-as-dut

PFA logs:-
[TC-I-2.2.txt](https://github.com/project-chip/connectedhomeip/files/8262162/TC-I-2.2.txt)

**Comment by Survensa** [comment]
Same issue is reflected in thread connectivity.
