### ISSUE TITLE
[TC-SU-2.1] - SDK needs to implement the feature of  queryImage command sent once during the required time

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16281]
Test case [TC-SU-2.1] - is not verifying all the test step mentioned in the test paln.step no.2 needs to be implement in the SDK. 

Test step needs to be implement  - We have to verify that the OTA-P sends the  QueryImage command  only once in that 1 minute interval.

**Comment by ukatira** [comment]
Fixed here: https://github.com/project-chip/connectedhomeip/issues/13782
