### ISSUE TITLE
[TC-SU-2.3] - SDK needs to implement the features in transfer of software update image

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16295]
In OTA [TC-SU-2.3]- This test case not verify all steps mentioned in testplan ,some steps like no .3,4,5 needs to be implement in SDK.
url of the software image, force fail the transfer before it completely transfers the image

**Comment by ukatira** [comment]
3, 5 out of scope for V1.0 (Already mentioned in test plan)
4 Fixed here: https://github.com/project-chip/connectedhomeip/pull/15939
