### ISSUE TITLE
[TC-SU-2.5] - SDK needs to implement the features in Applyupdate response

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16296]
In OTA [TC-SU-2.5] - This test case not verify all steps mentioned in testplan ,some steps like 3,4,5 needs to be implemented in SDK.
Awaitnextaction and discontinue commands needs to be implement

**Comment by ukatira** [comment]
Fixed here: https://github.com/project-chip/connectedhomeip/pull/15208
