### ISSUE TITLE
[TC-SU-3.3] - SDK needs to implement the features in transfer of Images between the DUT and OTA-R

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16304]
IN OTA [TC-SU-3.3] - Test step no 5 and 6 describes  ,force fail the transfer before it completely transfers the image is  needs to be  implemented in SDK .

**Comment by ukatira** [comment]
5 Fixed here: https://github.com/project-chip/connectedhomeip/pull/15939
6 out of scope for V1.0 (Already mentioned in test plan)
