### ISSUE TITLE
OTA Requestor App attempts second query when killing Provider app to abort transfer midway

### ISSUE THREAD

**Issue by ukatira** [project-chip/connectedhomeip#16323]
#### Problem

- Delete CHIP KVS folders for both provider and requestor
- Launch and commission both provider and requestor apps
- Add ACL entry for OTA Provider
- Initiate query using AnnounceOTA
- Kill Provider app to abort transfer midway and wait for BDX Timeout

Requestor App attempts second query when killing Provider app to abort transfer midway instead of waiting for 5 min BDX transfer timeout

 #### Proposed Solution
Requestor App should wait for 5 min BDX transfer timeout and initiate query only after this timeout when triggered using AnnounceOTA or Periodic query.

[ota-p.txt](https://github.com/project-chip/connectedhomeip/files/8268951/ota-p.txt)
[ota-r.txt](https://github.com/project-chip/connectedhomeip/files/8268952/ota-r.txt)

**Comment by hrajendran-samsung** [comment]
The issue seems to be that the commissioning-callback timer is not stopped properly before issuing a new Queryimage.

**Comment by hrajendran-samsung** [comment]
@ukatira Please note that due to the nature of this timer function, the actual time taken to detect a stalled BDX connection might be anywhere in the range of [mTimeout, 2*mTimeout).
mTimeout being 5 minutes.
