### ISSUE TITLE
[TC-SU-3.4] Tests the scenarios on when a software update should be applied by the OTA-R - needs SDK implementation

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16349]
Problem
IN OTA testcase [TC-SU-3.4] - Not verifying all the test step mentioned in the testplan. SDK implementation needs on step no. 2 and 3 for the command AwaitNextAction and Discontinue.

**Comment by ukatira** [comment]
Fixed here: https://github.com/project-chip/connectedhomeip/pull/15208
