### ISSUE TITLE
[TC_OO_2.1] - StartUpOnOff value doesn't match with spec on Raspberrypi , ESP32 and Thread platform

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16341]
content 
problem
[TC_OO_2.1] - StartUpOnOff value doesn't match with spec

 * expected behavior : 
![image](https://user-images.githubusercontent.com/93810525/158751740-c2683f9d-0699-44b7-9e5e-3a975a0a0dfa.png)

* actual behavior : 
![image](https://user-images.githubusercontent.com/93810525/158751807-70afd3f8-7b13-481c-b57c-e0eb451ff17b.png)

 * steps to reproduce : ./chip-tool onoff read start-up-on-off 1 1

 * screenshots, images, logs, etc.
[TC_OO_2.1_fail.txt](https://github.com/project-chip/connectedhomeip/files/8282071/TC_OO_2.1_fail.txt)

**Comment by Survensa** [comment]
Same issue is reflected in thread connectivity.

**Comment by somu1710** [comment]
Issue has been resolved in startuponoff attribute.Now it showing the value has NULL as mentioned in the spec.
![TC-OO2 1 -NULL](https://user-images.githubusercontent.com/93810525/160341533-e0aefb36-4255-4786-9e1c-59535bc1d12e.png)
