### ISSUE TITLE
[TC-WNCV-2.3] Mode Attribute with server as DUT - Needs an SDK implementation

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16358]
Problem

To execute [TC-WNCV-2.3] in window covering cluster, it requires SDK implementation to set and clear the value of the Mode, and also to perform the calibration on the device.
Here is the test plan Screen shot
![wncv 2 3](https://user-images.githubusercontent.com/93810525/159632796-0acb31fe-4cd4-4e96-856d-46377d6799d9.png)

@Jonathan Mégevand

**Comment by franck-apple** [comment]
Closing as this issue has multiple issues reported, which are all closed.

**Comment by jmeg-sfy** [comment]
Okay we keep this one as the only one
https://github.com/project-chip/connectedhomeip/issues/14406
