### ISSUE TITLE
 [TC-SU-4.2] Tests for verifying cluster attributes from Admin(DUT) - Needs SDK implementation

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16351]
Problem
IN OTA Testcase [TC-SU-4.2] -Its not verifying all the steps mentioned in the testplan,some steps like 1 and 2 does not reject invalid command and read request to default OTA attribute is need to implement in SDK.

**Comment by ukatira** [comment]
Fixed here: https://github.com/project-chip/connectedhomeip/issues/13855
