### ISSUE TITLE
[TC-SU-4.1] Tests for verifying cluster attributes on OTA-R(DUT) - Needs SDK implementation

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16350]
Problem
IN OTA Testcase [TC-SU-4.1]- Not verifying all the steps mentioned in testplan. few of the steps like 1,2,3,4,5,6 needs SDK implementation.for constraint error(0x87), fabrics etc;

**Comment by ukatira** [comment]
Fixed here: https://github.com/project-chip/connectedhomeip/issues/13855
