### ISSUE TITLE
Request to check Build Android

### ISSUE THREAD

**Issue by jonggab-park** [project-chip/connectedhomeip#1636]
We try to build Android with your building guide, but we meet the build error.

This is my environment and version of tools.
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export ANDROID_HOME=~/Android/Sdk
export ANDROID_NDK_HOME=~/Android/Sdk/ndk/21.3.6528147

After downloading codes on master branch, I follow your guide until 'make -f Makefile-Android'
Could you check to build Android??

We began to check this building issue because of android-studio build error
.../connectedhomeip/src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/setuppayloadscanner/BarcodeFragment.kt: (119, 27): Unresolved reference: SetupPayloadParser

For getting .so files, we thought it needs to build ndk.
And we tried to do 'build Android'.

If you have the best solution for android-studio build error, share with us, plz.

**Comment by woody-apple** [comment]
@vidhis88 ?

**Comment by vidhis88** [comment]
The steps to build Android are listed in the README here: https://github.com/project-chip/connectedhomeip/tree/master/src/android/CHIPTool
Please let me know if this still doesn't help build the Android demo app.

**Comment by andy31415** [comment]
I believe this issue is obsolete: we moved the build system to GN and there are build instructions.

The error seems to be caused by a failure to load so (either themselves or libstdc++). This should be resolved if following the readme since it contains some not as obvious steps.
