### ISSUE TITLE
 While verifying the "wild card" read for all the cluster for all the attributes,  chiptool responds as Invalid Cluster-Specific error code 0x11.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16378]
#### Problem
While verifying the wildcard read using the below command, towards the end, Chiptool throws an error with a code 0x11, which is not specified anywhere in the spec.
Can you please clarify the error code?

 * steps to reproduce:-Execution Command:-./chip-tool any read-by-id 0xFFFFFFFF 0xFFFFFFFF 1 0xFFFF

 * system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 2982c0ca0623773327def4cc7180d07f6b959c42 		
Dut: All-Clusters-app

Test-Plan Reference;-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-2-1-read-request-action-from-dut-to-th-dut-controller
 
Spec Reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#attributepathib

PFA screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/158842199-5ec2018f-5c64-4e29-9d31-6e7b8f21a9f3.png)

**Comment by Rajashreekalmane** [comment]
Problem:
While verifying the "wild card" read for all the cluster for all the attributes for specific endpoint, chiptool responds as Invalid Cluster-Specific error code 0x11.

steps to reproduce:-Execution Command:-./chip-tool any read-by-id 0xFFFFFFFF 0xFFFFFFFF 1 1

PFA screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/160397052-58f6540a-89b4-49e4-80dc-1a262dee9b25.png)

**Comment by Rajashreekalmane** [comment]
Problem:-
While verifying the "wild card" read for all the cluster for all the attributes for specific endpoint, chiptool responds as Run command failure( General error: 0x01).

steps to reproduce:-Execution Command:-./chip-tool any read-by-id 0xFFFFFFFF 0xFFFFFFFF 1 1

PFA screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/160397391-ba510278-b19b-49b3-865b-f897c611d3ee.png)

**Comment by vivien-apple** [comment]
This error will not happens for real world device. This is because the `all-clusters-app` contains `TestCluster` which has special attributes that are made to fails when they are read.
For example if you do: 
`./out/debug/standalone/chip-tool testcluster read cluster-error-boolean 0x12344321 1` you will notice the `IM Error 0x00000611: Cluster-specific error: 0x11` code that you are mentioning here.

Reading `general-error-boolean ` also generates an error.
