### ISSUE TITLE
[TC-IDM-5.2] Chip-tool needs to provide a way to set delayed write request to verify the step 2.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16373]
#### Problem
As per Test-Plan, [TC-IDM-5.2] test step 2 expecting that we should set  "TH to Wait for 5 seconds and then send a Write Request Message to the DUT", But 
Chip-tool needs to provide a way to set wait time for write request messages.

PFA screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/159700662-5a48dfe9-2a57-4e78-b234-e62734a3bf73.png)

 
Test-Plan Reference
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-5-2-timed-request-action-th-to-dut

Spec Reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#timed-request-action

**Comment by vivien-apple** [comment]
Should be fixed by https://github.com/project-chip/connectedhomeip/pull/16135

**Comment by franck-apple** [comment]
closing, as #16135 is merged.
