### ISSUE TITLE
`chip-all-clusters-app` capabilities parameter bug 

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#16383]
#### Problem
Running the `chip-all-clusters-app` with the `capabilities` set to 0=None, the accessory app still is discoverable over OnNetwork and commissions successfully to the `chip-tool` commissioner when it should not even be discoverable. 

For reference:

> Usage: ./out/all-clusters-app/chip-all-clusters-app [options]
> 
> GENERAL OPTIONS
...
>   --capabilities <None = 0, SoftAP = 1 << 0, BLE = 1 << 1, OnNetwork = 1 << 2>
>        Discovery Capabilities Bitmask which contains information about Device’s available technologies for device discovery.

#### Proposed Solution
Have `chip-all-clusters-app`'s `capabilities` argument function properly so that the app can be run without allowing a commissioner to discover it over any of the three mediums (SoftAP, BLE, OnNetwork)

#### Logs
[all-clusters-app Capabilities logs.txt](https://github.com/project-chip/connectedhomeip/files/8288534/all-clusters-app.Capabilities.logs.txt)

**Comment by bzbarsky-apple** [comment]
On-network discovery _always_ works, because it's required for post-initial-pairing commissioning.
