### ISSUE TITLE
[Darwin] Expose functionality to start a controller for a given fabric

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#16397]
#### Problem
There's no way to start a controller for a given fabric with the Darwin Framework.

The framework currently assumes there's only 1 fabric and always starts a controller for that fabric. 

Also the framework only allows creating one controller at a time. It needs to be updated to support multiple simultaneously.

 #### Proposed Solution
We should expose the ability to choose what fabric the controller is being created for and support more than 1 controller instance at a time.

**Comment by bzbarsky-apple** [comment]
Fixed in #17307.
