### ISSUE TITLE
[TC-OO-3.2] simulated tests missing commands

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16416]
Summary:
                 TC-OO-3.2 "on/off" cluster simulated testcase facing commands missing build error when executed

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/158945531-64067eb9-b36f-4f51-8f45-5f4d627f18e9.png)

Execution log:
[on_off.txt](https://github.com/project-chip/connectedhomeip/files/8301944/on_off.txt)

**Comment by vivien-apple** [comment]
```
ERROR:
 3.3.2. [TC-OO-3.2] Functionality with client as DUT :  DUT issues an Off command to the TH
Missing Command "Off" in: 
	* OffWithEffect
	* OnWithRecallGlobalScene
	* OnWithTimedOff
```

It seems to be the same root cause than #[16421](https://github.com/project-chip/connectedhomeip/issues/16421) and https://github.com/project-chip/connectedhomeip/issues/16419
