### ISSUE TITLE
[TC-DD-2.1] Need information on  GAP General Discoverable mode in Spec

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#16433]
#### Problem

Announcement by device verification Uses the GAP General Discoverable mode where we need more information in spec

Test-plan reference : 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicediscovery.adoc#tc-dd-2-1-announcement-by-device-verification

**Comment by lisaaaas** [comment]
I also encountered the same problem, running the instruction "avahi-browse _services._dns-sd. _udp-r" failed, what is the specific solution?

**Comment by lisaaaas** [comment]
I also encountered the problem, running the instruction "avahi-browse _services._dns-sd. _udp-r" failed, what is the specific solution?
