### ISSUE TITLE
Modeselect cluster [TC-MOD-3.3] - Needs SDK implementation on OTA update

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16430]
Problem
In mode select cluster test case [TC-MOD-3.3]   is not able to apply the OTA update,which requires SDK support
Here is the test plan screen shot and row no. 3 a 

![mod 3 3](https://user-images.githubusercontent.com/93810525/159631717-6df3d312-09ac-4e17-846f-5c996e36e79a.png)

**Comment by ukatira** [comment]
This test is about persistence of attribute value post an OTA Update but has nothing to do with OTA process itself.

**Comment by vivien-apple** [comment]
So, if the OTA update process works, then there is nothing left for me to do ?
@somu1710 When you say "is not able to apply the OTA update" can you provide more informations on what is the issue exactly ?

**Comment by somu1710** [comment]
@vivien-apple could u tell me how could i apply the OTA update on device.

**Comment by vivien-apple** [comment]
> @vivien-apple could u tell me how could i apply the OTA update on device for modeselect cluster.

@carol-apple  @isiu-apple  Do you have instructions about how to perform an OTA update for a given device ?

@somu1710  Per my understanding this is completely irrelevant to the `ModeSelect` cluster. This is a just an OTA update for the whole device.

**Comment by Survensa** [comment]
@vivien-apple and @carol-apple , As per the test plan, we need to reboot the DUT and verify the mode after it reboots.

CUrrently, if we reboot or reinitiate the CHIP Sample DUT, it requires a repairing to read the mode attribute. Hence we filed this ticket to soft reboot the DUT to read the attribute without repairing.

This ticket needs to be assigned to general DUT support to add the soft reboot.

**Comment by vivien-apple** [comment]
This is surprising that you need to repair. Why is that ? 
Fir example in YAML there are test step that are rebooting the DUT but it does not requires a repairing and locally I’m killing the server very often without the need to repair. Could it be a misconfiguration ?

**Comment by carol-apple** [comment]
Talked with Chaitanya to clear up the ask here:

```
we need get OTA update to working to run this TC, we dont need to build anything for modselect cluster w.r.t OTA.
```

I don't believe there is anything specific in the SDK that needs to be provided for this issue so @somu1710, I think this issue should be closed as the TC you need to run just depends on verification that OTA update works (which is currently being verified).

**Comment by somu1710** [comment]
> This is surprising that you need to repair. Why is that ? Fir example in YAML there are test step that are rebooting the DUT but it does not requires a repairing and locally I’m killing the server very often without the need to repair. Could it be a misconfiguration ?

Actually we cant able read/write the commands after reboot the dut without repairing the dut and controller.

**Comment by somu1710** [comment]
TC-MOD-3.2 also the same issue we are facing that on reboot the dut. In step no 3a

![TC-MOD-3 2](https://user-images.githubusercontent.com/93810525/161706949-aa5a8228-74df-4bee-94eb-1b131eab38cb.png)

**Comment by cjandhyala** [comment]
@somu1710 why cant you reboot the device and read the attribute ?

**Comment by somu1710** [comment]
If i reboot the device it requires pairing of dut and controller then only I able to read the attribute.

**Comment by vivien-apple** [comment]
> If i reboot the device it requires pairing of dut and controller then only I able to read the attribute.could i do like this?

This is the issue. You should not need to repair the device. Do I understand correctly and the device requires re-pairing wether or not there is an OTA update ?

**Comment by somu1710** [comment]
yeah I able to do OTA software update
