### ISSUE TITLE
 [TC-DD-3.4]- Step 2 says TH must find the DUT Commissioner which fails to do so

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#16434]
#### Problem
TH is instructed to start the commissioning procedure with the DUT found at step 2 where tv-casting-app is failing to do so
 * expected behavior : TH is instructed to start the commissioning procedure with the DUT found at step 2
 * actual behavior : But DUT is not found as tv-casting -app is failing to do so 
 * steps to reproduce : step 1) sudo ./chip-tv-app
                                    step 2) sudo ./chip-tv-casting-app
![image](https://user-images.githubusercontent.com/90545664/159013039-7e04f48f-0bcf-4d39-a84f-16159386c06c.png)

 * screenshots, images, logs, etc.
 >
[tv-casting-app.txt](https://github.com/project-chip/connectedhomeip/files/8304849/tv-casting-app.txt)

**Comment by chrisdecenzo** [comment]
I think this is already fixed in top of tree. What branch are you building tv-casting-app from?

**Comment by sowmyassp** [comment]
@chrisdecenzo I build tv-app using Linux platform on master branch
