### ISSUE TITLE
Revert the state of operational key pair, NOC and ICAC on fail-safe expiration

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#16443]
#### Problem
<what's wrong or missing, please include any applicable:
If an UpdateNOC command had been successfully invoked, revert the state of operational key pair, NOC and ICAC for that Fabric to the state prior to the Fail-Safe timer being armed, for the Fabric Index that was the subject of the UpdateNOC command.

    if (event->CommissioningComplete.UpdateNocCommandHasBeenInvoked)
    {
        // TODO: Revert the state of operational key pair, NOC and ICAC
    }

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Spec Review: Assigning to @tcarmelveilleux
