### ISSUE TITLE
TC-TSTAT-3.1 Chip-tool-darwin testing: Few read attributes were missing in the Darwin tool

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#16499]
Compared to the chip-tool, chip-tool-darwin is missing few read attributes. They are needed for the first and second step in the TSTAT-3.1. Below is the image showing the difference of the read attributes currently supported by chip-tool and chip-tool Darwin. Right side is chip-tool-darwin and left side is chip-tool.
<img width="1420" alt="Screen Shot 2022-03-21 at 11 46 03 AM" src="https://user-images.githubusercontent.com/34750871/159342712-c7bc4ec8-e174-48e9-a202-091b2e2b3fea.png">

**Comment by bzbarsky-apple** [comment]
Fixed in #18276
