### ISSUE TITLE
Need to permit applications to provide final input on negotiated subscription intervals

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#16494]
#### Problem

Applications cannot actually provide any input to the final negotiated subscription intervals (min and max reporting intervals). The IM decides this completely on its own.

#### Proposal

Provide a simple API interface that by default, will use the values the IM decides, but can be over-ridden by the application to specify a different set of negotiated values.

**Comment by drempelg** [comment]
I think it would be useful to know what the attribute being subscribed to is as part of the negotiation.  Just my $0.02.
