### ISSUE TITLE
TC-GC-1.1 chip-tool-darwin testing: Basic commissioning info attribute missing to read

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#16507]
As per step 6 of TC-GC-1.1, Basic commissioning info attribute needs to be present to read which is missing in chip-tool-darwin tool. In the image below, the above list is chip-tool-darwin and the below one is chip-tool. The attribute is present in chip-tool while it is missing in chip-tool-darwin.
<img width="801" alt="Screen Shot 2022-03-21 at 3 17 10 PM" src="https://user-images.githubusercontent.com/34750871/159372502-52ef9050-4567-4e63-bfcc-ceac7d19d6fa.png">

**Comment by krypton36** [comment]
Definitely a bug. I can resolve this issue. Thank you.

**Comment by bzbarsky-apple** [comment]
Fixed.
