### ISSUE TITLE
Xcode compile CHIP Framework error

### ISSUE THREAD

**Issue by Lee6804** [project-chip/connectedhomeip#16511]
gn --root=/Users/lee/Desktop/Matter gen --check out '--args=default_configs_cosmetic=[] chip_crypto="mbedtls" chip_build_tools=false chip_build_tests=false target_cpu="arm64" target_defines=["CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>","DEBUG=1","CHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=<lib/address_resolve/AddressResolve_DefaultImpl.h>"] target_cflags=["-target","arm64-apple-ios13.4","-arch","arm64","-flto"] target_os="ios" import("//config/ios/args.gni")'
./chip_xcode_build_connector.sh: line 159: gn: command not found
Command PhaseScriptExecution failed with a nonzero exit code

Xcode Version：13.3
iPhone System Version：15.4

gn --version
1905 (9ea1dd3f)

**Comment by xieguangming** [comment]
How did you solve this error?  I also encounter this problem.
