### ISSUE TITLE
TC-LO-1.1 chip-tool-darwin testing: SupportedLocale attribute not present to write

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#16538]
As per TC-LO-1.1 step 2, there should be SupportedLocale attribute to write to, which is not present. This attribute is not present both in Chip-tool-darwin as well as in Chip-tool. Below is the screenshot for the same.

<img width="699" alt="Screen Shot 2022-03-22 at 2 08 40 PM" src="https://user-images.githubusercontent.com/34750871/159576314-2b7061f7-d1e7-4c5f-ba59-226abe010206.png">

**Comment by bzbarsky-apple** [comment]
Note that the attribute can be written using `write-by-id`.
