### ISSUE TITLE
Wi-Fi Network Diagnostics Cluster attributes with default value "null" showing response as "expected to be null but isn't" 

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16554]
Summary:
              As per spec Wi-Fi Network Diagnostics Cluster some  attributes with default value "null" showing response as "expected to be null but isn't"  when we executed
               
Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/159649715-1184cb35-3e45-4d0a-bd67-1435249fdd19.png)

Execution logs and screenshot:
![image](https://user-images.githubusercontent.com/84442963/159649572-969f1f6d-dd5f-49a9-815a-f47bdf269bce.png)
[wifidiag.txt](https://github.com/project-chip/connectedhomeip/files/8330938/wifidiag.txt)

**Comment by bzbarsky-apple** [comment]
@manjunath-grl @cjandhyala Is this still an issue?

**Comment by manjunath-grl** [comment]
@bzbarsky-apple issue is resolved can you please close it.
