### ISSUE TITLE
[TC-ETHDIAG-1.1] attribute with default as "null" showing failure response

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16552]
Summary:
               As per spec default value of PHYRate attribute is "null" showing failure response when we executed. 
               
Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/159642891-26d8ab8e-a477-4542-a1be-f6783b18b118.png)

Execution logs and screenshot:
![image](https://user-images.githubusercontent.com/84442963/159642682-56c542a2-b461-476b-90b5-e1425408dd17.png)
[ethdiag.txt](https://github.com/project-chip/connectedhomeip/files/8330554/ethdiag.txt)

**Comment by manjunathambiger23** [comment]
@bzbarsky-apple still facing this issue if we try to read the null value.
![image](https://user-images.githubusercontent.com/84442963/161702141-a513c3ca-99c6-4cdb-aa2d-b9f95c09eb27.png)

**Comment by bzbarsky-apple** [comment]
That's an UNSUPPORTED_CLUSTER response.  Is the cluster involved actually enabled in the server you are trying to read from @manjunathambiger23 ?

**Comment by manjunathambiger23** [comment]
@bzbarsky-apple i uploaded wrong logs i tried it in endpoint 0 its still showing failure response

**Comment by bzbarsky-apple** [comment]
@manjunathambiger23 Is the response still UNSUPPORTED_CLUSTER?

Which _exact_ commands are being run on which exact SHA on which exact example apps?

**Comment by manjunathambiger23** [comment]
@bzbarsky-apple the response is: expected to be null but isn't 
![image](https://user-images.githubusercontent.com/84442963/163939295-e3217b34-bf5a-40f8-8408-cdc86b7b4d7f.png)
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/8510393/exe_log.txt)

**Comment by bzbarsky-apple** [comment]
The spec for PHYRate says:
```
The PHYRate attribute SHALL indicate the current nominal, usable speed at the top of the physical layer of the Node. A value of null SHALL indicate that the interface is not currently configured or operational.
```
It's coming back as "5", which is "Rate10G".

Why are you expecting null?  Is the interface in question in fact "not configured or operational"?  What is the _exact_ server setup?

**Comment by bzbarsky-apple** [comment]
Resolving, given correct-looking SDK behavior and no response.
