### ISSUE TITLE
YAML does not support 15 minutes time delays used in some test plans

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#16579]
As found in [TC-MF-1.25 & TC-MF-1.26]

Open Commissioning Window command is not supporting 15 minutes time delay ,its giving unsigned conversion error ,need yaml support for handling 15 minutes time delay

Testplan screenshot :
![2022-03-23_23-42](https://user-images.githubusercontent.com/57476670/159770381-f5d7cb4e-c734-43db-86f1-3791d8e49148.png)
Error screenshot:
![2022-03-23_23-58_1](https://user-images.githubusercontent.com/57476670/159770529-91e1194f-ee10-4fe6-ad49-b7285498497b.png)
Test step:
![2022-03-23_23-59](https://user-images.githubusercontent.com/57476670/159770726-d7e306d8-f7cc-474c-bbc7-9bb01cb5dd12.png)
[build-error-mf-1.zip](https://github.com/project-chip/connectedhomeip/files/8335603/build-error-mf-1.zip)

**Comment by bzbarsky-apple** [comment]
Fixed in #17906.
