### ISSUE TITLE
[TC-IDM-2.1]-SDK support required for the test step 16 in Read Request Action from DUT to TH test case.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16570]
Test-Case ID
[TC-IDM-2.1] Read Request Action from DUT to TH [DUT - Controller] 

#### Problem
 As per Test-Plan, test step 16 is expecting "DUT should sends the Read Request Message to the
 TH to read any data which is larger than 1 MTU(1280 bytes)"  was out of scope for TE-8 and doesn't had the verification steps.

 * PFA Test-plan Screenshot:
![image](https://user-images.githubusercontent.com/95841834/159750556-d7d24b62-fb93-4454-bde0-e063dd29d266.png)

 Do we have the SDK developed to support these steps? If it is , please share the verification steps for the same.

**Comment by cjandhyala** [comment]
Test Plan reference : 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#312-tc-idm-12-invoke-response-action-from-dut-to-th

**Comment by vivien-apple** [comment]
@Rajashreekalmane @mrjerryjohns   It is unclear to me that there is anything to do here, expect picking up the right attribute that is a list with enough data ? Or even do a read of multiple elements such as `./out/debug/standalone/chip-tool any read-by-id 0xFFFFFFFF 0xFFFFFFFF 0x12344321 1` and observe that there is multiple chunked messages ?
