### ISSUE TITLE
[TC-DL-1.7]  Door Lock cluster Commands are missing in yaml 

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#16636]
Following Commands are missing in YAML framework SetUserStatus  ,GetUserStatus 

TestPlan Screenshot:
![2022-03-24_22-59](https://user-images.githubusercontent.com/57476670/159975847-b37394e8-9e05-4d57-9aee-fc1b60def29e.png)

Error Screenshot :
![2022-03-24_22-58](https://user-images.githubusercontent.com/57476670/159975981-242c938e-7fcf-469b-9755-a843c886d3c8.png)

**Comment by krypton36** [comment]
door-lock-server.cpp doesn't seem to implement the following functions to support this in the sample App. Even if I enable these, chip-tool test will fail with NOT_SUPPORTED
emberAfDoorLockClusterGetUserStatusCallback
emberAfDoorLockClusterSetUserStatusCallback

**Comment by bzbarsky-apple** [comment]
The YAML bits were fixed in #18209
