### ISSUE TITLE
min report interval 0 subscription doesn't flush final CurrentLevel after On/Off command

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#16653]
#### Problem

Setting the minimal report interval to zero so that updates arrive in the minimal possible time can cause dirty attributes to not be flushed out (as in the case of the level control cluster and the On and Off commands)

```
In [1]: node = 0x3e8

In [2]: sub = await devCtrl.ReadAttribute(node, [Clusters.OnOff.Attributes.OnOff, Clusters.LevelControl.Attributes.CurrentLevel], reportInterval=(0, 120))
2022-03-24 22:26:55 yuif chip.SC[372750] ERROR The device does not support GetClock_RealTimeMS() API. This will eventually result in CASE session setup failures.

In [3]: await devCtrl.SendCommand(node, 1, Clusters.OnOff.Commands.On())

Attribute Changed:
{
│   'Endpoint': 1,
│   'Attribute': <class 'chip.clusters.Objects.LevelControl.Attributes.CurrentLevel'>,
│   'Value': 1
}
Attribute Changed:
{
│   'Endpoint': 1,
│   'Attribute': <class 'chip.clusters.Objects.OnOff.Attributes.OnOff'>,
│   'Value': True
}
```

Issuing a read seems to force the subscription to flush:

```
In [4]: _ = await devCtrl.ReadAttribute(node, [Clusters.OnOff.Attributes.OnOff, Clusters.LevelControl.Attributes.CurrentLevel])
Attribute Changed:
{
│   'Endpoint': 1,
│   'Attribute': <class 'chip.clusters.Objects.LevelControl.Attributes.CurrentLevel'>,
│   'Value': 254
}
```

@mrjerryjohns @erjiaqing

**Comment by mrjerryjohns** [comment]
Yeah, seems something is wonky in the dirty management and report generation logic...

**Comment by mrjerryjohns** [comment]
We weren't running the reporting engine upon receiving a status response to the last report in the exchange. This would happen automatically with a min interval != 0, since that schedules a timer after the report gets sent (assuming the timer fires after we receive a status response, which it should in most cases...)

Will put out a fix tomorrow with tests...
