### ISSUE TITLE
TC-SC-4.1 Need YAML support to enable Extended Discovery

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16665]
Summary:
               As per testplan [TC-SC-4.1] need YAML support to enable Extended discovery for DNS advertisings

Testplan screenshot: 
![image](https://user-images.githubusercontent.com/84442963/160116588-e1cdb699-8262-406e-bb05-0b34273398f7.png)

**Comment by bzbarsky-apple** [comment]
I don't understand what this YAML support would do.  Extended discovery needs to be enabled on the actual DUT, no?

@cjandhyala

**Comment by manjunath-grl** [comment]
@bzbarsky-apple its not related to yaml can you please close this issue

**Comment by bzbarsky-apple** [comment]
@manjunath-grl Sure thing.
