### ISSUE TITLE
TC-SC-4.* Need YAML support to validate the service type and the service domain

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16660]
Summary:
              As per test-plan need to validate the service type and the service domain need YAML support for this.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/160106472-cbc2cf61-4dc2-41bd-904e-54219aafbda2.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
