### ISSUE TITLE
iOS chiptool fails to compile: TemperatureSensorViewController.m:223:29: No visible @interface for 'CHIPDevice' declares the selector 'subscribeWithQueue:minInterval:maxInterval:params:reportHandler:subscriptionEstablished:'

### ISSUE THREAD

**Issue by kean-apple** [project-chip/connectedhomeip#16679]
iOS chiptool fails to compile using SHA 48b48c28a5c2aa699ee2699d8a051717ff6d0686

See following error:
/Users/keanhinlim/connectedhomeip/src/darwin/CHIPTool/CHIPTool/View Controllers/Temperature Sensor/TemperatureSensorViewController.m:223:29: No visible @interface for 'CHIPDevice' declares the selector 'subscribeWithQueue:minInterval:maxInterval:params:reportHandler:subscriptionEstablished:'

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/73258860/160164782-31c91d14-dd49-4a08-81fa-d684af5082c1.png">

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
Fallout from https://github.com/project-chip/connectedhomeip/pull/16534
