### ISSUE TITLE
chip-device-ctrl > set-pairing-wifi-credential <ssid> <psk> --> Error - 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by HeneryH** [project-chip/connectedhomeip#16678]
#### Problem
This seems new to me.  Haven't had this problem before.  Not sure if anything changed or anyone else is seeing this.

```
chip-device-ctrl > set-pairing-wifi-credential My-SSID 12345678
'bytes' object has no attribute 'encode'

chip-device-ctrl > set-pairing-wifi-credential My-SSID '12345678'
'bytes' object has no attribute 'encode'

chip-device-ctrl > set-pairing-wifi-credential My-SSID "12345678"
'bytes' object has no attribute 'encode'

chip-device-ctrl > set-pairing-wifi-credential "My-SSID" "qwe12345678"
'bytes' object has no attribute 'encode'

``` 
#### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by HeneryH** [comment]
Seems like a string is being mis-typed as a byte[] or vise versus.

**Comment by timredfern** [comment]
I see this problem too with chip-device-ctrl, I'm using commit 44dd01b9fa49b2a31a7d8ba52084cef7d9e73e17 from May 9, OSX 12.3.1

**Comment by caipiblack** [comment]
Same here on [TE9] tag.

**Comment by hidaris** [comment]
I fix it in https://github.com/project-chip/connectedhomeip/pull/19792 You can try it to see if it solves your problem
