### ISSUE TITLE
Add support for client to override device attestation procedure failure while using default device commissioner

### ISSUE THREAD

**Issue by carricdsilva-apple** [project-chip/connectedhomeip#16681]
#### Problem
* Current behavior: While using the default device commissioner and the default device attestation verifier if a device attestation error occurs. The default device attestation verifier informs the commissioner via `OnAttestationInformationVerification` callback. However the default device commissioner acts on this error and fails commissioning. The client does not have an opportunity to override attestation failure are proceed with commissioning.

 #### Proposed Solution
Add a mechanism to the default device commissioner to inform the client of device attestation procedure failure. Based on clients response the device commissioner should fail or proceed with commissioning. 

Also need an Objective-C mechanism to bubble up the attestation failure to the Objective-C client of `CHIPDeviceController`. The Objective-C client of `CHIPDeviceController` would respond with user's decision.

**Comment by woody-apple** [comment]
Note: We need to add a single parameter here:
https://github.com/project-chip/connectedhomeip/blob/c14faebbc566b6436f199f1fe8b261e60638c9fc/src/darwin/Framework/CHIP/CHIPDeviceController.mm#L146
