### ISSUE TITLE
Add parameter to Objective-C CHIPDeviceController to accept PAA certificates from Objective-C client

### ISSUE THREAD

**Issue by carricdsilva-apple** [project-chip/connectedhomeip#16684]
#### Problem
- Current behavior: Currently CHIPDeviceController sets up the Default Device Attestation Verifier with Testing Root Store.

 #### Proposed Solution
Provide a mechanism for the Objective-C client to pass in PAA certs to `CHIPDeviceController` and setup the `AttestationTrustStore` with the provided PAA certs.

**Comment by woody-apple** [comment]
Note, we need to add a parameter here:
https://github.com/project-chip/connectedhomeip/blob/c14faebbc566b6436f199f1fe8b261e60638c9fc/src/darwin/Framework/CHIP/CHIPDeviceController.mm#L146

**Comment by woody-apple** [comment]
Dup of this: https://github.com/project-chip/connectedhomeip/issues/14126
