### ISSUE TITLE
Implement Descriptor:DeviceTypeList in SDK as defined in the spec

### ISSUE THREAD

**Issue by leorozendaal** [project-chip/connectedhomeip#16686]
#### Problem
The specification defines the `DeviceTypeList` attribute in the `Descriptor` cluster as
`list[DeviceTypeStruct]`
with DeviceTypeStruct defined as
![image](https://user-images.githubusercontent.com/16798461/160181388-a5098a22-72bb-46e6-8922-de5799f53316.png)

So effectively this attribute is a list of device types and their revision which "live" on the endpoint.
Apparently, SDK implements a single device type per endpoint

Having this as a list (as the spec defines) is needed for several devices, e.g.
- device with battery - needs to have both the DeviceType of the actual (e.g.) sensor as well as Power Source device type to indicate battery information is present in a Power Source cluster on this EP (especially if multiple sensors with each a battery are exposed  by a device, you need this to link the battery to the sensor)
- bridge where each EP for a bridged device needs to have both the device type of the Bridged Device (e.g. `Extended Color Light`) as well as the device type `Bridged Node` (to indicate it is a bridged device) - see image below
- bridge EP0 which needs to have both device types Root Node and Bridge on EP0

Example;
![image](https://user-images.githubusercontent.com/16798461/160182053-e1f53002-7605-4100-813e-b73d42b74b19.png)

 #### Proposed Solution
Implement this attribute as a list of DeviceTypeStruct

Discussed (also in past slack) with @woody-apple  @mrjerryjohns   @bzbarsky-apple

**Comment by bzbarsky-apple** [comment]
See also https://github.com/project-chip/connectedhomeip/issues/12418

**Comment by bzbarsky-apple** [comment]
Note that we do implement this as a list of DeviceTypeStruct.  We just have no way to specify more than one entry in that list right now...
