### ISSUE TITLE
Darwin: synchronous-read API part 2: support generic events in subscription, and expected value cache expiration

### ISSUE THREAD

**Issue by kpark-apple** [project-chip/connectedhomeip#16691]
#### Problem
Current CHIPDevice subscribeWitthQueue: API only supports known standard attributes. For manufacturer specific extensions or unimplemented standard attributes, subscribeAttributeWithEndpointId:... API can be used. However, in such a case, it forces both of them to set keepPreviousSubscriptions option in order not to cancel each other, limiting the flexibility of application to clear up previous subscriptions.

 #### Proposed Solution
Add a generic report handler argument of CHIPDeviceResponseHandler type to subscribeWithQueue API in addition to the existing standard attribute report handler. Note that if standard event handler argument is added to the API, the same generic report handler can be used to receive any event as well as any attribute.

**Comment by bzbarsky-apple** [comment]
@jtung-apple Note the bit about events above.

**Comment by woody-apple** [comment]
Darwin Review: Note to self, update this to cover current scope for subscriptions.

**Comment by jtung-apple** [comment]
Renamed issue to better reflect what this is tracking.

Details: https://github.com/project-chip/connectedhomeip/pull/20519 implemented generic attributes, but is still missing generic events, as well as other TODOs for the synchronous-read API. Updating this issue to explicitly track these items.

**Comment by jtung-apple** [comment]
Closing because #21566 and #21757 are in now.
