### ISSUE TITLE
Reland weave message layer to CHIP with clean port

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#1669]
Weave message layer is broadly agreed in previous TSG meeting, we are trying to reland weave message layer to CHIP in order to prepare the integration for weave event logging, Weave BTP and so on.

**Comment by yunhanw-google** [comment]
This is high-level ticket. We are still investigating the WML features needed for CHIP to align with message layer baseline, and try to incrementally create the meaningful feature ticket later.
currently we have the below 
https://github.com/project-chip/connectedhomeip/issues/1692
https://github.com/project-chip/connectedhomeip/issues/1670
thanks

**Comment by woody-apple** [comment]
Let's keep issues actionable, as we start to put dates on things. closing this, given the other two.
