### ISSUE TITLE
unlockwithTimeout command failing when executed

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#16716]
Summary:
              unlockwithTimeout command showing failure response instead of success response when executed.

Spec screenhot:
![image](https://user-images.githubusercontent.com/84442963/160402654-3a82effb-42f4-499c-ab1c-bc2c0c3652ae.png)

Execution screenshot and logs: 
![image](https://user-images.githubusercontent.com/84442963/160402262-9593966e-1479-40ec-b357-a21777fd79e5.png)
[unlockwithTimeout_command.txt](https://github.com/project-chip/connectedhomeip/files/8362806/unlockwithTimeout_command.txt)

**Comment by bzbarsky-apple** [comment]
0x81 is UNSUPPORTED_COMMAND.

Note that "Unlock with Timeout" is an optional door lock command; servers do not have to support it.

Which server application is being used?

In `examples/door-lock-app/door-lock-common/door-lock-app.zap` this command is not enabled.  In `examples/all-clusters-app/all-clusters-common/all-clusters-app.zap` this command is likewise not enabled.

**Comment by manjunathambiger23** [comment]
@bzbarsky-apple we are using Door Lock app ,we try enabling that command and let you know
