### ISSUE TITLE
Need YAML support for List  fields constraints check

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16712]
Summary:
                As per testplan need to check the lists fields constraints check need YAML support for list element fileds constraints check

Testplan:
![image](https://user-images.githubusercontent.com/84442963/160384098-3e8f00dd-99ca-4be7-8fbb-cd819a1dfd49.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
