### ISSUE TITLE
[TC-DIAG Log-2.2]Need YAML support if DUT initiated BDX transfer or not

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16715]
Summary:
                Need YAML support to verify DUT and TH supports BDX transfer or not and support forDUT response with commands of "Diagnostics logs" cluster
TC-DIAG LOG-2.1
TC-DIAG LOG-2.2

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/160395472-86826d3c-0c04-4838-9284-0f0ecc44551c.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
