### ISSUE TITLE
Fix the potential wildcard dirty path issue in MergeOverlappedAttributePath

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#16734]
#### Problem
When we extend setDirty with wildcard support, we have not yet updated MergeOverlappedAttributePath, Concretely, let's say path is (wildcard endpoint, cluster 6, wildcard attribute) and aAttributePath is (wildcard endpoint, wildcard cluster, wildcard attribute), we would update the path with aAttributePath.

 #### Proposed Solution
 update MergeOverlappedAttributePath with wildcard handling

**Comment by bzbarsky-apple** [comment]
> we would update the path with aAttributePath

We do that wrong now, is the point of this issue.
