### ISSUE TITLE
Need YAML support to increment the saved value

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16756]
Summary:
              Need YAML support to increment the saved value by some values.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/160578106-e5307c0c-c091-4857-ab4d-e728304594d0.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
