### ISSUE TITLE
 Clusters missing in simulated tests

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#16765]
Summary:
Facing below clusters missing in simulated tests
1. Power Source
2. Power Source Configuration
3. Pressure Measurement
4. Flow Measurement
5. Boolean State
6. Illuminance Measurement
7. software diagnostics
8. Ethernet Network Diagnostics
9. WiFi Diagnostics
10. Bridged Actions

Execution logs:
[PSC.txt](https://github.com/project-chip/connectedhomeip/files/8371799/PSC.txt)

**Comment by raju-apple** [comment]
@krypton36 Can you please take a look ?
