### ISSUE TITLE
Need to sort out what to do with af-gen-event.h

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#16785]
#### Problem
This file is "generated", but we don't actually generate it via ZAP.  People end up having to hand-write it and put it in the zzz_generated directory.

 #### Proposed Solution
Either stop using this file and come up with a different solution for the things its used for, or actually create a generation path for it.

**Comment by woody-apple** [comment]
Issue Scrub: Closing, given this was resolved by @andy31415 recently.
