### ISSUE TITLE
[TC-IDM-6.2] Chip-tool needs to provide a way to set optional Path Field "IsUrgent flag"  for a particular event path in the EventPathIB.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16816]
Test-Case ID:-
 [TC-IDM-6.2] Events Subscribe Interaction from TH to DUT

 #### Issue
As per Test-Plan test step 9 says "Activate Event subscription from TH to DUT and change the 
attribute value to create subscribed event before minimum interval with 'IsUrgent' flag specified for a
 particular event path in the EventPathIB". Chip-tool needs to provide a way to set optional Path
 Field "IsUrgent flag"  for a particular event path in the EventPathIB.

PFA Test-Plan screenshot:-
![image](https://user-images.githubusercontent.com/95841834/160766480-6c4322f7-8fa5-4c71-a801-75d15e91c7fe.png)

Spec screenshot:-
![image](https://user-images.githubusercontent.com/95841834/160766603-6ddcc09c-1768-4d0c-8fa7-c8799a8b5921.png)

**Comment by vivien-apple** [comment]
@Rajashreekalmane This is not a `chip-tool` issue. You need to trigger an event that is "urgent". So the event will contains the `IsUrgent` flag.
