### ISSUE TITLE
Darwin dns-sd advertising needs to use the right hostname

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#16849]
#### Problem
Right now operational and commissionable DNS-SD advertising on Darwin uses the default hostname of the device involved, because we are passing `NULL` for the `host` argument when calling `DNSServiceRegister`.

Per spec, the hostname is supposed to be the MAC (or whatever randomized thing we are pretending is the MAC).

I tried implemeting this as follows:
1. Modify `Register` in `src/platform/Darwin/DnssdImpl.cpp` to take a `hostname` argument.
2. Pass `service->mHostName` to `Register` from `ChipDnssdPublishService` in that file.
3. Do some munging on the hostname in `Register`:
    ```
    // Treat empty hostname as null.
    if (hostname != nullptr && strcmp(hostname, "") == 0) {
        hostname = nullptr;
    }

    std::string hostnameStr;
    if (hostname != nullptr) {
        hostnameStr = std::string(hostname) + '.' + kLocalDot;
        hostname = hostnameStr.c_str();
    }
    ```
4. Pass `hostname` to `DNSServiceRegister`.

That fixes the advertisements to have the right hostname, afaict, but address resolution then fails because there is no IP associated with that hostname.  The documentation at https://developer.apple.com/documentation/dnssd/1804733-dnsserviceregister?language=objc says to call [DNSServiceRegisterRecord](https://developer.apple.com/documentation/dnssd/1804727-dnsserviceregisterrecord?language=objc) to handle that, but I could not figure out the right arguments to pass it, even when hard-coding the relevant IPs, to get past "invalid argument" errors it was giving me.

 #### Proposed Solution
* Figure out whether the combination of passing a hostname to `DNSServiceRegister` and calling `DNSServiceRegisterRecord` is actually what we want to be doing here.
* If so, sort out how to actually call `DNSServiceRegisterRecord` properly.

**Comment by andy31415** [comment]
Would it be easier to update the spec to recommend using the mac as hostname?
Or does that potentially cause issues because macs (or other devices) may have overly long hostnames that devices then fail to work with due to embedded constrains?

**Comment by bzbarsky-apple** [comment]
> Or does that potentially cause issues because macs (or other devices) may have overly long hostnames that devices then fail to work with due to embedded constrains?

Exactly.  We ran into this because minmdns was using a buffer sized to the spec thing and failing out if the hostname did not
fit in there, iir.
