### ISSUE TITLE
Testing support: Create 'all-clusters-app' with ONLY mandatory attribute support

### ISSUE THREAD

**Issue by dwgaul** [project-chip/connectedhomeip#16851]
#### Problem
We are looking to update some of our client/controller test cases for TE9. In PR [875](https://github.com/CHIP-Specifications/chip-test-plans/pull/875) we want to pull in tests where a client/controller attempts to read/write to optional attributes that are not supported by the server. This testing is more cluster specific, validation is done on each cluster the client claims support for.

An example would be an app made by company A that supports lightbulbs from company A and from company B. In this case company A lightbulb supports all optional attributes, but company B lightbulb only supports mandatory attributes. We would want to ensure that if this app attempts to read optional attributes on lightbulb B, it handles the "UNSUPPORTED_ATTRIBUTE" error gracefully. 

From the discussion in 875 it sounds like it is a possibility and not forbidden by the spec for a client to read/write to an attribute ignoring any listed support in the servers attributeList.

 #### Proposed Solution
In addition to the existing "all-clusters-app" example we would be supplied with a similar app that only has support for the mandatory attributes. An "all-clusters-mandatory-app" if you will

**Comment by mlepage-google** [comment]
`all-clusters-mandatory-attributes-app` ?

**Comment by dwgaul** [comment]
Hey @bzbarsky-apple, yes its to validate the additional steps suggested in the test plan PR mentioned above. We want to include these steps in TE9.

As for how it's implemented, I don't have an opinion either way. Whether it's a separate app or another endpoint, as long as we can facilitate testing a client attempting to read from an optional attribute that is not present on the server we should be good.

**Comment by bzbarsky-apple** [comment]
I guess one question is whether we'd also want to implement only the bare-minimum set of functionality on the clusters on endpoint 0.

That is, do we just need _an_ attribute that is optional and not present on the server, or do we want _all_ optional attributes to not be present, for all clusters including Basic Information and so on?

**Comment by dwgaul** [comment]
We would need all optional attributes to not be present since this test is present in all app cluster tests. Essentially it is to check that if your client claims support for a given cluster, make sure it can gracefully handle clusters that may not have optional attributes.

**Comment by bzbarsky-apple** [comment]
OK, but app clusters only, or utility clusters too?

Sounds like you want utility clusters too, which means we'd need a separate app.

**Comment by dwgaul** [comment]
Was thinking originally just app clusters, but utility clusters make sense as well.

**Comment by cjandhyala** [comment]
@dwgaul this "UNSUPPORTED_ATTRIBUTE" error scenario is covered in IDM test plan, do we still need a separate app for that ? we can just test for the test cluster, which is not implemented in the production devices anyway ..

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to myself to find an assignee for this issue.

**Comment by dwgaul** [comment]
We've got a PR up on the test plan side if this slips out of V1. Will keep an eye out and merge appropriately.
