### ISSUE TITLE
Need YAML support for Secure channel tests

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16865]
Summary:
                 Need YAML support for Secure channel tests 
TC-SC-4.4
TC-SC-4.5
TC-SC-4.6
TC-SC-4.7
TC-SC-4.8
TC-SC-4.9

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/161000487-8d0a68ba-f595-46af-9f75-b594972cbfd9.png)
![image](https://user-images.githubusercontent.com/84442963/161000555-f99df809-0c8a-4768-abba-9c522ab6aa97.png)
![image](https://user-images.githubusercontent.com/84442963/161000624-d869b4eb-6443-419b-b138-990889addc2a.png)
![image](https://user-images.githubusercontent.com/84442963/161000703-4185fafc-d13e-45ff-a062-47613c0477c4.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
