### ISSUE TITLE
[TC-IDM-6.1]-SDK support required for test step 12  to read event Interaction from TH to DUT

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16875]
Test case ID 
 [TC-IDM-6.1] Events Read Interaction from TH to DUT

Issue:-
As per Test-Plan, test step 12 is expecting to Set or Indicate the event number less than
the EventMin field in EventfilterIB.  Do we have the SDK developed to support these steps?
If it is, please share the verification steps for the same.

Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-6-1-events-read-interaction-from-th-to-dut
 
Spec Reference
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#event-information-blocks-and-paths

**Comment by vivien-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/16867 has landed for this purpose.
