### ISSUE TITLE
[ TC-DL-1.10 ] Need YAML verify if an attribute is enabled/disbaled

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#16874]
Summary:
           As per the testplan we need Verify that YearDayScheduleUser, WeekDayScheduleUser is enabled when the User Type is ScheduleRestrictedUser how to verify it in YAML.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/161055447-d9584414-5e28-489d-a0c6-e8b593108095.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
