### ISSUE TITLE
M5 board crashes enabling reports via iOS Chiptool - Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by kean-apple** [project-chip/connectedhomeip#16896]
M5 board crashes enabling reports via iOS Chiptool

SHA: fbcaa81a96c9d372cb217c356bdbb6e7fd8eb7f9

1. Pair M5 board (all-clusters app) using iOS chiptool
2. from iOS chip tool, go to temp sensor and enable reports: Min: 1s, Max: 2s

In step 2, M5 board crashes when enabling reports , seems 100% (5 out of 5)

Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x400de9ac  PS      : 0x00060830  A0      : 0x800da611  A1      : 0x3ffe7180  
0x400de9ac: (anonymous namespace)::FixedLabelAttrAccess::Read(chip::app::ConcreteReadAttributePath const&, chip::app::AttributeValueEncoder&) at /Users/keanhinlim/connectedhomeip/examples/all-clusters-app/esp32/build/../third_party/connectedhomeip/src/app/clusters/fixed-label-server/fixed-label-server.cpp:58
 (inlined by) Read at /Users/keanhinlim/connectedhomeip/examples/all-clusters-app/esp32/build/../third_party/connectedhomeip/src/app/clusters/fixed-label-server/fixed-label-server.cpp:92
 (inlined by) Read at /Users/keanhinlim/connectedhomeip/examples/all-clusters-app/esp32/build/../third_party/connectedhomeip/src/app/clusters/fixed-label-server/fixed-label-server.cpp:85

A2      : 0x00000000  A3      : 0x00000000  A4      : 0x3ffe71f0  A5      : 0x00000000  
A6      : 0xfffffffd  A7      : 0x00000000  A8      : 0x800de9ac  A9      : 0x3ffe7160  
A10     : 0x00000000  A11     : 0x00000040  A12     : 0x00000040  A13     : 0x00000000  
A14     : 0x3ffcb378  A15     : 0x19249ad4  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xfffffffa  

Note: did not see this yesterday with bbbf7cec7770b373618f7b24a60addc38aca7813

[M5-crashes-enabling-reports-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8392831/M5-crashes-enabling-reports-M5-logs.txt)
[M5-board-enabling-reports-CHIPTOOL-logs.txt](https://github.com/project-chip/connectedhomeip/files/8392832/M5-board-enabling-reports-CHIPTOOL-logs.txt)

**Comment by bzbarsky-apple** [comment]
This was broken by #16861.  The crashing line looks like this:
```
    DeviceLayer::DeviceInfoProvider::FixedLabelIterator * it = DeviceLayer::GetDeviceInfoProvider()->IterateFixedLabel(endpoint);
```
but `DeviceLayer::GetDeviceInfoProvider()` is null on all non-Linux platforms, so this crashes.

@yufengwangca should we just be null-checking the provider?
