### ISSUE TITLE
ESP32 example lighting-app with chip-tool

### ISSUE THREAD

**Issue by joskra** [project-chip/connectedhomeip#16924]
**Problem**

Cannot switch on LED using [lighting-app](https://github.com/project-chip/connectedhomeip/tree/TE8/rc3/examples/lighting-app) on ESP32-DevKitC

 * I am using **ESP32-DevKitC** connected together with **Linux Ubuntu 20.04LTS chip-tool** or **Android app chip-tool**
 - chip-tool command with Randevouse BLE -> log cannot established bluetooth connection using USB dongle ASUS USB-BT500 on PC.
I am using USB bluetooth dongle because my laptop has older in-built bluetooth.
 [pairing with qrcode chip-tool text file](https://github.com/project-chip/connectedhomeip/files/8395479/ble_qrcode_log.txt)
 - network search on MatterTest Wifi: notebook and ESP32 on same site
<p float="left">
<img src="https://user-images.githubusercontent.com/46843997/161061033-c7a9fbc2-52c9-4227-b4c8-c8677edd54c3.png"
width=33% height=33%>
<img src="https://user-images.githubusercontent.com/46843997/161063741-88cb8fb8-6c81-42d1-9a00-97b1d24952e4.jpg"
width=10% height=10%>
<img src="https://user-images.githubusercontent.com/46843997/161212328-038112c3-a67d-4180-b499-c94e41bcb2a0.png"
width=40% height=40%>
<p>
<p float="left">
<img src="https://user-images.githubusercontent.com/46843997/161220295-b22c0d6f-e5c6-4332-b8e9-58c7f18bb3d6.png"
width=30% height=30%>
<p>

- chip-tool command with Randevouse Wifi -> log is ok I got IPv4 and IPv6 address but now I don't know how to control LED ...
which command I need to use. ESP32 Node Id is 0x20.

* Huawei P20 lite Android app chip-tool and ESP32-DevKitC
**BLE connection i established and turning ON OFF Toggle is working.**
<p float="left">
<img src="https://user-images.githubusercontent.com/46843997/161050595-693352f5-dcf4-44d3-812f-9416824b34d2.jpg"
width=15% height=15%>
<img src="https://user-images.githubusercontent.com/46843997/161210379-72b09078-a03c-4f9d-9cb2-042ca528a0e6.jpg"
width=15% height=15%>
<img src="https://user-images.githubusercontent.com/46843997/161052619-e0fab012-28b0-46e1-b371-7d330a224dc5.jpg" width=15% height=15%>
<img src="https://user-images.githubusercontent.com/46843997/161060502-6c87ce34-75aa-4cc8-91ed-ceee3b96772d.jpg"
width=15% height=15%>
<img src="https://user-images.githubusercontent.com/46843997/161216744-1b120152-c430-4c7a-8cce-429325405a41.jpg"
width=15% height=15%>
<img src="https://user-images.githubusercontent.com/46843997/161273140-404af087-770f-4fbf-8c1a-cba669cf4eb8.jpg"
width=15% height=15%>
</p>

[ligthing app log with wifi parameters](https://github.com/project-chip/connectedhomeip/files/8395653/mobile_app_ble_only_wifi.txt)

line 255 I (18870) chip[DIS]: Advertise operational node B2A71D38322AD529-0000000000000020
so my Node ID is 0x20 hex 32 dec, my IPv4 is 192.168.135.40:5540 I can see clusters and endpoints in the log.

I also searched some examples. But is no working for me. Bluetooth fail.
[Announcing Matter on ESP32](https://blog.espressif.com/announcing-matter-previously-chip-on-esp32-84164316c0e3)
[Announcing Matter on ESP32 my log](https://github.com/project-chip/connectedhomeip/files/8395888/matter_esp32_example.txt)
**Maybe I found one problem. I needed to install manually: pip install deprecation**

This example also not works. Command **./out/debug/chip-tool pairing bypass** not exist.
[Getting Started with Connected Home over IP (CHIP](https://codelabs.developers.google.com/codelabs/chip-get-started)](https://codelabs.developers.google.com/codelabs/chip-get-started#6)

So I have question. How can I control my LED only trough wifi connection? Which command form chip-tool on PC side I have to use? I am using **TE8/rc3** tag and **esp-idf v4.4**. Thank you.

**Comment by jmmb13** [comment]
I'm also trying to use the lighting app with esp32 but when I try to connect to it fails:
![image](https://user-images.githubusercontent.com/35546901/164947823-acc7e151-ec09-4c79-ad51-278bf3fa72a8.png)

These error messages were when trying to "Commission with IP address" through the device address.

I was successful with google codelabs, but I'm not able to demo with the latest version.

@joskra [joskra](https://github.com/joskra) did you solve it?
