### ISSUE TITLE
[TC-OO-2.2] - SDK need to implement some DUT actions

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#16923]
Problem

Few of the On/Off clusters tescases , for ex:[TC-OO-2.2]  step no.6a and 6c need  to verify by changing few parameters directly on the physical device. 
As this vendor specific, this can't be tested using Soft DUT.

![TC-OO-2 2 ](https://user-images.githubusercontent.com/93810525/161233606-b03024ef-f795-4cef-a634-2881ab7b7f90.png)

**Comment by sankarselvam** [comment]
@somu1710  This parameter needs to be changed directly in the DUT & needs to be verified.
As this is vendor specific test case/step, please update the comments in Verification steps nd mark as N/A in the test report.
