### ISSUE TITLE
chip::Platform::MemoryInit()/MemoryShutdown() are called from common code but belong to product/platform

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#16969]
#### Problem
`chip::Platform::MemoryInit()` and `chip::Platform::MemoryShutdown()` are called from `Server` class and a few other places, but the calls always belong 

 #### Proposed Solution
- Add an API `bool chip::Platform::IsMemoryInitialized()` that determines dynamic memory subsystem is initialized
- Error-out in `Server::Init()` if MemoryInit() was not called
- Remove all MemoryInit()/Shutdown() calls from common SDK code and hoist to the outer caller code (examples)

**Comment by SI-David-Kopczynski** [comment]
This issue is still being referred to in `CHIP_ERROR Server::Init(const ServerInitParams & initParams)` (see https://github.com/project-chip/connectedhomeip/blob/master/src/app/server/Server.cpp#L151)
