### ISSUE TITLE
chip-tool crashes when called with no arguments

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#1698]
#### Problem
Compiling the binary in `examples/chip-tool` and running it with no arguments crashes.  This problem was introduced in https://github.com/project-chip/connectedhomeip/pull/1660 by removing the `argc` check at the beginning of `DetermineCommand`.

 #### Proposed Solution
Put the `argc` check back.

@vivien-apple

**Comment by vivien-apple** [comment]
Should have been fixed by #1680.

**Comment by bzbarsky-apple** [comment]
Yep, looks like it. Thank you!
