### ISSUE TITLE
chip-tool behaves incorrectly for echo, on, off, toggle commands

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#1700]
#### Problem
None of these commands work properly in the tool that lives in `examples/chip-tool`.  I haven't dug into why in detail, but it looks like the argument processing got rejiggered so that instead of keeping track of ip/port on the stack it's kept track of in `CommandArgs`.... but that's a union, not a struct.  So the various members just clobber each other and none of this works.

Looks like the problem was introduced in https://github.com/project-chip/connectedhomeip/pull/1660

 #### Proposed Solution
Fix argument processing to work correctly.

@vivien-apple

**Comment by vivien-apple** [comment]
Should have been fixed by #1680.

**Comment by bzbarsky-apple** [comment]
Yep, looks like it.  Thank you!
