### ISSUE TITLE
Network Commissioning cluster has many subtle spec deviations due to non-spec XML

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#17010]
#### Problem
Apart from not setting various string max lengths, we have the following deviations from the spec:

* `Security` field of `WiFiInterfaceScanResult` has wrong type.
* `PanId` and `ExtendedAddress` fields of `ThreadInterfaceScanResult` have wrong types.
* `ScanMaxTimeSeconds` and `ConnectMaxTimeSeconds` attributes are not marked optional, even though they would not be present on an "Ethernet" version of the cluster.
* `SSID` field in `ScanNetworks` needs to be nullable and optional.
* `DebugText` field in `ScanNetworksResponse` needs to be optional.
* `DebugText` field in `ConnectNetworkResponse` needs to be optional.

 #### Proposed Solution
Apply attached diff to the XML, then regenerate and fix whatever C++ code needs fixing.
[network-commissioning.txt](https://github.com/project-chip/connectedhomeip/files/8412330/network-commissioning.txt)

**Comment by tcarmelveilleux** [comment]
FYI @erjiaqing
