### ISSUE TITLE
I'd rather the cache (and every other potential implementor of this function) not be responsible for rollback. This should happen in just once place in the IM, key'ed off of a CHIP_OUT_OF_MEMORY error.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#17034]
I'd rather the cache (and every other potential implementor of this function) not be responsible for rollback. This should happen in just once place in the IM, key'ed off of a CHIP_OUT_OF_MEMORY error.

_Originally posted by @mrjerryjohns in https://github.com/project-chip/connectedhomeip/pull/16602#discussion_r840927436_

**Comment by mrjerryjohns** [comment]
@yunhanw-google this is still relevant right?
