### ISSUE TITLE
Occupancy sensing cluster [ TC-OCC-3.1,][TC-OCC-3.2] - Test step shows operate dut manually to change the occupancy status

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#17049]
Problem
In occupancy sensing cluster testcase [ TC-OCC-3.1] and [TC-OCC-3.2] - For TC-3.1& 3.2 - Row no.3  need to verify by changing  parameters(occupancy status) directly on the physical device.
Heres the screen shot 

![TC-OCC-3 1](https://user-images.githubusercontent.com/93810525/161724411-ee710954-17a0-44c2-99d6-5d69af2f2788.png)
![TC-OCC-3 2](https://user-images.githubusercontent.com/93810525/161724428-4076a811-1d20-4796-b2a1-c9a56e1e2e8f.png)

**Comment by s-mcclain** [comment]
Hey @somu1710 can I ask why you closed out this issue? Seems like this is still a problem which makes the tests TC-OCC-3.2 impossible to execute with the test harness at the moment

**Comment by somu1710** [comment]
@s-mcclain  Actually I closed this ticket because of manual operation we cant perform by using the Raspi device ,App- All clusters app.so this can be executable on real DUT .So we thought of  no need this ticket and we closed all manual operation required test cases.Should I need to reopen the issue again?
