### ISSUE TITLE
Top of the tree code is failing while executing build command

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#17042]
Top of the tree code is failing while executing build command ,please refer attached screenshot 
![2022-04-05_11-27](https://user-images.githubusercontent.com/57476670/161688477-95f489e5-1301-4e3b-b992-7baeccedbbba.png)

Note :I have tried 2 various  build commands but i am observing the same failure response 
1. ./gn_build.sh 
2. ./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-chip-tool-no-ble-tsan\
                        --target linux-x64-all-clusters-test-group-no-ble-tsan \
                        --target linux-x64-door-lock-no-ble-tsan \
                        --target linux-x64-tv-app-no-ble-tsan \
                        build \
                        --copy-artifacts-to objdir-clone \
                     "
[Execution-logs-2-Apr5.zip](https://github.com/project-chip/connectedhomeip/files/8415386/Execution-logs-2-Apr5.zip)
[Execution-logs-Apr5.zip](https://github.com/project-chip/connectedhomeip/files/8415387/Execution-logs-Apr5.zip)

**Comment by bzbarsky-apple** [comment]
Yes, you need to install the readline headers and library.
