### ISSUE TITLE
We should move DeviceInfoProviderImpl away from PlatformManagerImpl and make Server have a reference to it

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#17088]
#### Problem
DeviceInfoProviderImpl is used in a way that is very hidden. I didn't even know it existed until today. This is not a platform item, it is a per-product item. We should move this away from PlatformManagerImpl and make Server have a reference to it, so that eventually we can init the UserLabel clutser to use the DeviceInfoProvider rather than these deep hidden singletons

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
Can't actually implement a compliant fixed label cluster on top of what we have right now....

**Comment by woody-apple** [comment]
Spec Review: This is just an implementation problem. Closing, as we also believe this is complete
