### ISSUE TITLE
Move clusters out of `general.xml` into their own Matter-specific definitions

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#17080]
#### Problem

We have a bunch of clusters defined in `general.xml` that are a hold-over from the legacy Zigbee definitions. We should split them up by cluster into their own XML files and add them to the existing set in `data-model/chip/`.

**Comment by mlepage-google** [comment]
There's also `ha.xml` at least. Not sure where else clusters live. I think we should have one place to find them, bring them all together and bind them. (Possibly with sub organization of course.)
