### ISSUE TITLE
After timeout of TH1 when I tried to commission TH2 I am not getting any error log

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#17100]
-  **Issue** : After commissioning of TH1 with DUT and then open a commissioning window in TH1 after timeout we should commissioning TH2 with DUT where I should receive "PASESession timed out while waiting for a response from the peer" instead I got " Run command failure: ../../commands/common/CHIPCommand.cpp:365: CHIP Error 0x00000032: Timeout"

- **Expected behaviour** :  PASESession timed out while waiting for a response from the peer

- **Actual behaviour** : Run command failure: ../../commands/common/CHIPCommand.cpp:365: CHIP Error 0x00000032: Timeout

- **PFA logs** : 
[TC_MF_1.6_cntrl01.txt](https://github.com/project-chip/connectedhomeip/files/8426524/TC_MF_1.6_cntrl01.txt)
[TC_MF_1.6_2ndcntrl.txt](https://github.com/project-chip/connectedhomeip/files/8426523/TC_MF_1.6_2ndcntrl.txt)

**Comment by jamesluo11** [comment]
@sowmyassp Can i know the reason why close this issue directly. I also encountered this issue.
