### ISSUE TITLE
Pump Control and Configuration ControlMode and OperationMode should have min/max specified in XML

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#17112]
#### Problem
We don't do range checks on sets to these attributes.

 #### Proposed Solution
We should be doing range checks, but that requires the valid range to be specified in the XML.

@tlykkeberg-grundfos @mgarb1

**Comment by tlykkeberg-grundfos** [comment]
Hi @bzbarsky-apple I have been looking into this on ToT and I find the following in the `pump-configuration-and-control.cluster.xml` file:

```xml
    <attribute side="server" code="0x0020" define="OPERATION_MODE" type="ENUM8" min="0x00" max="0xFE" writable="true" default="0x00" optional="false">OperationMode</attribute>
    <attribute side="server" code="0x0021" define="CONTROL_MODE" type="ENUM8" min="0x00" max="0xFE" writable="true" default="0x00" optional="true">ControlMode</attribute>
```
I'm not quite sure what you mean in this context? The `min` and `max` values are specified in the attribute definition in the XML.

**Comment by bzbarsky-apple** [comment]
Yes, but they are specified for the full (nullable) uint8 range, not the actual valid range for the relevant enums.

**Comment by tlykkeberg-grundfos** [comment]
Fixed in #17181

**Comment by tlykkeberg-grundfos** [comment]
Hi @bzbarsky-apple since the pr #17181 I have introduced this into these two attributes in the XML:
```xml
<attribute side="server" code="0x0020" define="OPERATION_MODE" type="PumpOperationMode" min="0x00" max="0x03" writable="true" default="0x00" optional="false">
      <description>OperationMode</description>
      <access op="read" privilege="view"/>
      <access op="write" privilege="manage"/>
    </attribute>
    <attribute side="server" code="0x0021" define="CONTROL_MODE" type="PumpControlMode" min="0x00" max="0x07" writable="true" default="0x00" optional="true">
      <description>ControlMode</description>
      <access op="read" privilege="view"/>
      <access op="write" privilege="manage"/>
    </attribute>
```
Here there are min/max values and the exact enum type (instead of ENUM8). Would that be sufficient or do you see any further implementation needed for this issue to be closed?

**Comment by bzbarsky-apple** [comment]
#17181 fixes this, yes.  Thank you!
