### ISSUE TITLE
[TC-MF-1.11]  After 11th attempt of invalid passcode chip-tool is  not showing any error logs 

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#17167]
**Issue** : 
According to test-plan [TC-MF-1.11] step 3, until 20 unsuccessful invalid pass code attempts the chip-tool should throw PASE session failure, and then for  21st attempt should throw a message that can’t begin "PASE (failure at PBKDFRequest, not obtaining a PBKDFResponse)", but here after 11  unsuccessful attempts chip-tool is not showing any error logs.

**Expected behaviour** : Untill 21st attempt chip-tool should throw pase session failure error 

**Actual behaviour** : Affter 11th attempt chip-tool doesn't throw pase session failure error

**Spec Reference** : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/AdminCommissioningCluster.adoc#ref_OCW

**Test-plan reference** : https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/multiplefabrics.adoc#tc-mf-1-9-device-exit-commissioning-mode-after-20-failed-commission-attempts-ecm-dut-commissionee

**Test platform** : 
             Chip-tool - RPI
             DUT - RPI/MAC

**Steps to reproduce** : 

1. DUT side : 

- sudo rm -rf /tmp/chip_*
- sudo ./chip-all-clusters-app --wifi (Discriminator - 3841, Passcode - 20202021)

2. TH side : 

- ./chip-tool pairing ble-wifi 1 zigbeehome matter123 20202021 3841(on TH1)
- ./chip-tool pairing open-commissioning-window 1 1 100 1000 3841/./chip-tool administratorcommissioning open-basic-commissioning-window 500 1 0 --timedInteractionTimeoutMs 1000 (on TH1)
- ./chip-tool pairing manualcode 2 35484132896 / ./chip-tool pairing onnetwork 2 20202019(wrong manual code)(on TH2)
- Above command should be given 20 times
- But when we pass 11th time of above command chip-tool is not showing error logs 
- ./chip-tool pairing manualcode 2 34970112332 / ./chip-tool pairing onnetwork 2 20202021(correct manual code)(on TH2)

             
PFA logs : 
[TC_MF_1.11_cntrl02.txt](https://github.com/project-chip/connectedhomeip/files/8442375/TC_MF_1.11_cntrl02.txt)

**Comment by sowmyassp** [comment]
For [TC_MF_1.12] After 4th attempt of invalid passcode we are not getting any error log

PFA logs : 
[Uploading TC_MF_1.12.txt…]()

**Comment by sowmyassp** [comment]
@bzbarsky-apple Can you please take a look at this issue

**Comment by bzbarsky-apple** [comment]
I am seeing this fail after 15 failed attempts, but definitely seeing it fail.  What happens is that in `CommissioningWindowManager::HandleFailedAttempt` the call to `AdvertiseAndListenForPASE` fails.

And that fails because we fail to allocate a session in `PairingSession::AllocateSecureSession`.  And looking at the session pool:

1. It's a `BitmapObjectPool`, so is actually fixed-size.
2. The pool size is `CHIP_CONFIG_PEER_CONNECTION_POOL_SIZE`, which is 16.

So we seem to be leaking sessions, at first glance...

**Comment by bzbarsky-apple** [comment]
Ah, this is because we have started allocating sessions up front, before we know pairing has been successful, and never clean them up afterward. Fix coming up.
