### ISSUE TITLE
Pairing of ESP32 with chip-tool on linux platform is failing

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#17164]
**Issue** : 
        Pairing ESP32 with chip-tool failing on Linux platform but successfully pairing on MAC with commit (1fb5900175f29acea972a4ce955c30edd8c6e88d)

 **Expected behaviour** : 
          Device commissioning completed with success

**Actual behaviour** : 
          Device connection failed. Error ../../third_party/connectedhomeip/src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:176: CHIP Error 0x00000032: Timeout

**Test platform** :
Chip-tool - RPI
DUT - ESP32(all-clusters-app)

**Screenshot** : 

![image](https://user-images.githubusercontent.com/90545664/162178999-05678760-c776-4587-b37f-22ae6651f9d8.png)

**PFA logs**:

[ESP.txt](https://github.com/project-chip/connectedhomeip/files/8441987/ESP.txt)
[ESP_cntrl.txt](https://github.com/project-chip/connectedhomeip/files/8441988/ESP_cntrl.txt)

**Comment by sowmyassp** [comment]
Same issue facing with commitID (fa5561c23d8c1f9464da8669931affbae0660f51)

**Comment by alantsai0821** [comment]
Is there anyone know how to fix this?
I just meet the same error when try to pairing EFR32MG12 lighting-app with chip-tool on ubuntu...

[EFR32-chip-tool-log.txt](https://github.com/project-chip/connectedhomeip/files/8493662/EFR32-chip-tool-log.txt)

**Comment by dhrishi** [comment]
@sowmyassp Please confirm if it is working with the latest codebase on ESP32. I can successfully perform commissioning and cluster control using Linux chip-tool on latest head (4b4e035e15eab106e33a88eac6ffbe557d82e584)

**Comment by sowmyassp** [comment]
Yes @dhrishi Its working with latest head
