### ISSUE TITLE
[Controller API] Create API for ACL setup

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1717]
On the controller, we need an API to configure accessory ACLs

**Comment by mlepage-google** [comment]
Setup of ACLs will occur through regular read/write attribute IM calls, and already functions now (e.g. using chip-repl) modulo a few details (like the fabric-filtered writes which are in the process of landing in the IM) and the fact that enforcement isn't turned on yet (can't do that until you can write ACLs and administrators are updated to do so).

I think this is a redundant issue and can be closed.
