### ISSUE TITLE
Add/RemoveTrustedRootCertificate must be updated to match latest spec

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#17209]
#### Problem
The `RemoveTrustedRootCertificate` handler in the SDK does not seem to work at all.

By inspecting the code, we find:

```
// TODO: Implement the logic for RemoveTrustedRootCertificate
    EmberAfStatus status = EMBER_ZCL_STATUS_FAILURE;
    emberAfSendImmediateDefaultResponse(status);
```

 #### Proposed Solution
Fix the logic of RemoveTrustedRootCertificate to follow spec. This is symmetrical to #17208

**Comment by tcarmelveilleux** [comment]
https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5269 covers a fix in spec to match SDK by removing the command

**Comment by woody-apple** [comment]
Spec Review: After the above spec change, this is not a spec blocking issue.

**Comment by tcarmelveilleux** [comment]
Spec changes impact AddTrustedRootCertiticate as well
