### ISSUE TITLE
AttributeCache cannot handle large list

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#17204]
#### Problem
when reviewing bufferReaderCallback and AttributeCache, finding that when there is large buffered list, AttributeCache cannot use PacketBufferHandle with kMaxSecureSduLengthBytes to store that large list unless we improve PacketBufferHandle with chain or use Platform::ScopedMemoryBuffer when AttributeCache find it is list with size

**Comment by mrjerryjohns** [comment]
Should definitely get this fixed for 1.0.
