### ISSUE TITLE
[Accessory API] Support ACL setup

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1723]
On the accessory side, we need an API to support ACL setup

**Comment by mlepage-google** [comment]
Hi, on "accessory side" you mean the client device (e.g. speaker hub or phone), which must be an administrator (to change ACLs), desiring to change ACLs on the server device (e.g. the light bulb)?

If so, that will occur through regular read/write attribute IM calls, and already functions now (e.g. using chip-repl) modulo a few details (like the fabric-filtered writes which are in the process of landing in the IM) and the fact that enforcement isn't turned on yet (can't do that until you can write ACLs and administrators are updated to do so).

I think this is a redundant issue and can be closed.

**Comment by woody-apple** [comment]
Agree this can be closed.
