### ISSUE TITLE
Darwin attribute cache needs to have expiration time to detect a device that is down/ offline for very long time

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#17249]
#### Problem
Presently we do not have expiration for attribute cache, hence we cannot reliably detect if a device is down or offline for a very long periods of time and show appropriate device status to end user. 

 #### Proposed Solution
We could have something on the cache that indicates whether we have a live subscription or not (i.e. we started a subscription and have not seen OnDone) and hence whether we consider the cache "current"...

**Comment by bzbarsky-apple** [comment]
This is specifically for the Darwin wrapper around the core attribute cache.

@kpark-apple @sagar-apple

**Comment by mrjerryjohns** [comment]
There is a broader need to provide this inference that shouldn't be specifically tried to the use of the cache.

I've filed that issue [here](https://github.com/project-chip/connectedhomeip/issues/16202).

**Comment by woody-apple** [comment]
Agree with @mrjerryjohns, there's a non-platform specific baseline change needed here:
https://github.com/project-chip/connectedhomeip/issues/16202

**Comment by woody-apple** [comment]
Darwin Review: We believe subscription expiry is sufficient, please re-open if needed.
