### ISSUE TITLE
[SQA] Door lock test cases failed due to "Invalid CASE parameter"

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#17244]
Door lock cases were failed due to "Invalid CASE parameter" in few seconds after it has been paired.

During any "read" actions after it has been paired, Chip-Tool log thrown an error "The device does not support GetClock_RealTimeMS() API. This will eventually result in CASE session setup failures."

Following the above error, it has failed with "Invalid CASE parameter" for the further commands from Chip-tool.

Entire log has been attached. It contains few read attribute commands & the failure of the commands at the end of the log.

Error log file :
[DL timeout error log.txt](https://github.com/project-chip/connectedhomeip/files/8463979/DL.timeout.error.log.txt)

**Comment by bzbarsky-apple** [comment]
Some questions, @Survensa:

1. What SHA is being used for chip-tool?  What SHA is being used for the server app?
2. Which server app is being used?
3. Which platform is the server app running on?

**Comment by bzbarsky-apple** [comment]
Oh, and:

> "The device does not support GetClock_RealTimeMS() API. This will eventually result in CASE session setup failures."

"eventually" here means "after some code gets changed to require time-based certificate validation".  Which has not happened, so those messages are not relevant to whatever is going on here.

**Comment by bzbarsky-apple** [comment]
> Executed doorlock app using ble-wifi platform.

No, I mean what hardware/OS?  In terms of trying to reproduce, it's best if people are using a setup as close to the one you have as possible.

**Comment by bzbarsky-apple** [comment]
Oh, and when you say "doorlock app", does that mean the thing in `examples/lock-app` or in `examples/door-lock-app`?

**Comment by cjandhyala** [comment]
@bzbarsky-apple it is `examples/door-lock-app`

**Comment by bzbarsky-apple** [comment]
Alright, I have tried to reproduce on that SHA for a while as follows:

1. `scripts/examples/gn_build_example.sh examples/door-lock-app/linux out/debug/standalone chip_config_network_layer_ble=false`
2. `scripts/examples/gn_build_example.sh examples/chip-tool out/debug/standalone/`
3. `rm /tmp/chip*`
4. Run `./out/debug/standalone/chip-door-lock-app`
5. `./out/debug/standalone/chip-tool pairing onnetwork 17 20202021`
6. Repeat calls to `./out/debug/standalone/chip-tool doorlock read attribute-list 1 1` a number of times, with various gaps between them (did gaps of up to 10 mins or so).  Every read worked.

Maybe this is specific to the ble-wifi case, but that seems pretty doubtful.  But just to check:

* Can you reproduce when using on-network commissioning.
* Either way, can you attach a log from the server (and a matching log for the client) for a failing case?

**Comment by Survensa** [comment]
@bzbarsky-apple Door-lock-app work fine on `onnetwork/ethernet` but facing the issue only on `Ble-wifi`.

I have attached both DUT and CNTRL log for the "CASE Parameter" error .

LOG: 
[door lock ctrl log.txt](https://github.com/project-chip/connectedhomeip/files/8486763/door.lock.ctrl.log.txt)
[door lock dut log.txt](https://github.com/project-chip/connectedhomeip/files/8486764/door.lock.dut.log.txt)

**Comment by bzbarsky-apple** [comment]
> Door-lock-app work fine on onnetwork/ethernet but facing the issue only on Ble-wifi.

I am finding this _very_ hard to believe; once we finish commissioning the two cases should act identically.

What other differences are there between the ble-wifi and onnetwork cases?

I never did see an answer to the "what hardware/OS?" question....

Looking at the logs, the key part is this, on the server:
```
[1649916219.318395][3326:3326] CHIP:SC: CASE failed to match destination ID with local fabrics
```
and then it fails out because there is no NOC for the fabric on the device:
```
[1649916219.319358][3326:3326] CHIP:IN: CASE Session establishment failed: ../../third_party/connectedhomeip/src/credentials/FabricTable.h:164: CHIP Error 0x00000003: Incorrect state
```
(That's in FabricInfo::GetNOCCert.)

So we had an IPK match the group storage for some fabic index, but the actual fabric for that index was not initialized properly...

Just to check: are the client and server running on the same hardware or different pieces of hardware?

**Comment by Survensa** [comment]
@bzbarsky-apple Using two different raspberrypi, one as DUT and other as CNTRL.

**Comment by bzbarsky-apple** [comment]
OK.  Can you step through in a debugger on the CASE responder and see what's actually going on?  What does the fabric table look like?

**Comment by liamgonyea** [comment]
I had run the same commands mentioned [above](https://github.com/project-chip/connectedhomeip/issues/17244#issuecomment-1098698913) and had the same findings as well with no failures when `chip-tool` reads an attribute from `chip-door-lock-app `after onNetwork pairing

#### Steps Ran 

1. `scripts/examples/gn_build_example.sh examples/door-lock-app/linux out/debug/standalone chip_config_network_layer_ble=false` 
2. `scripts/examples/gn_build_example.sh examples/chip-tool out/debug/standalone/`
3. `./out/debug/standalone/chip-door-lock-app`
4.  `./out/debug/standalone/chip-tool pairing onnetwork 17 20202021`5. 
5.  `./out/debug/standalone/chip-tool doorlock read cluster-revision 17 1`

#### Test Setup
1st RasPi: `chip-tool` built with commit SHA: `fa5561c23d8c1f9464da8669931affbae0660f51`

2nd RasPi: `door-lock-app` built with commit SHA: `fa5561c23d8c1f9464da8669931affbae0660f51`
`scripts/examples/gn_build_example.sh examples/door-lock-app/linux out/debug/standalone chip_config_network_layer_ble=false`

#### Lines of Interest
Lines of Interest:
```
ubuntu@controller:~/TE/stableBuild/connectedhomeip$ ./out/debug/standalone/chip-tool pairing onnetwork 17 20202021
...
[1650578349.007276][17409:17416] CHIP:TOO: Device commissioning completed with success
```
```

ubuntu@controller:~/TE/stableBuild/connectedhomeip$ ./out/debug/standalone/chip-tool doorlock read cluster-revision 17 1
...
[1650579166.721625][17799:17804] CHIP:TOO:   ClusterRevision: 3
```

#### Logs
[chip-tool_issue_17244.txt](https://github.com/project-chip/connectedhomeip/files/8535746/chip-tool_issue_17244.txt)
[doorlock_issue_17244.txt](https://github.com/project-chip/connectedhomeip/files/8535747/doorlock_issue_17244.txt)

**Comment by liamgonyea** [comment]
When pairing over `ble-wifi`, I had experienced the same issue when `chip-tool `attempts to read an attribute from `chip-door-lock-app` 

### Summary of Findings 
(`chip-tool` logs for each attempt at reading an attribute from `chip-door-lock-app`)
#### 1st Attempt: Successful
`[1650657650.054116][3880:3885] CHIP:TOO:   ClusterRevision: 3`

#### 2nd Attempt: Fail (Invalid CASE parameter)
`[1650657980.921764][3898:3898] CHIP:TOO: Run command failure: ../../../examples/chip-tool/third_party/connectedhomeip/src/protocols/secure_channel/CASESession.cpp:1479: CHIP Error 0x00000054: Invalid CASE parameter`

#### 3rd Attempt: Fail (Timeout)
`[1650658795.688720][3936:3936] CHIP:TOO: Run command failure: ../../../examples/chip-tool/third_party/connectedhomeip/src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:174: CHIP Error 0x00000032: Timeout`

### Steps Ran 

1. `scripts/examples/gn_build_example.sh examples/door-lock-app/linux out/debug/standalone_ble chip_config_network_layer_ble=true` 
2. `scripts/examples/gn_build_example.sh examples/chip-tool out/debug/standalone/`
3. `./out/debug/standalone_ble/chip-door-lock-app`
4.  `./out/debug/standalone/chip-tool pairing ble-wifi 1234  SSID SSIDpwd 20202021 3840` 
5.  `./out/debug/standalone/chip-tool doorlock read cluster-revision 1234 1` 
6.  `./out/debug/standalone/chip-tool doorlock read cluster-revision 1234 1`
7.  `./out/debug/standalone/chip-tool doorlock read cluster-revision 1234 1`

### Test Setup
1st RasPi: `chip-tool` built with commit SHA: `fa5561c23d8c1f9464da8669931affbae0660f51`

2nd RasPi: `door-lock-app` built with commit SHA: `fa5561c23d8c1f9464da8669931affbae0660f51`
`scripts/examples/gn_build_example.sh examples/door-lock-app/linux out/debug/standalone_ble chip_config_network_layer_ble=true`

### Logs
[ble_wifi_chip-tool_issue_17244.txt](https://github.com/project-chip/connectedhomeip/files/8543896/ble_wifi_chip-tool_issue_17244.txt)
[ble_wifi_doorlock_issue_17244.txt](https://github.com/project-chip/connectedhomeip/files/8543897/ble_wifi_doorlock_issue_17244.txt)

**Comment by bzbarsky-apple** [comment]
@liamgonyea Thank you!  Those logs make it pretty clear what's going on here:
1. The commissionee in this case is already on the network (via ethernet I am told) but also being commissioned as a wifi device.
2. Commissioning fails after AddNOC, because the commissionee claims to be a thread-only device, or so we think, but we only have wifi credentials.  From the chip-tool log:
    ```
    [1650657604.415267][3870:3875] CHIP:CTL: Finished commissioning step 'SendNOC' with error '../../../examples/chip-tool/third_party/connectedhomeip/src/controller/CHIPDeviceController.cpp:1390: Success'
    [1650657604.415327][3870:3875] CHIP:CTL: Required network information not provided in commissioning parameters
    [1650657604.415378][3870:3875] CHIP:CTL: Parameters supplied: wifi (yes) thread (no)
    [1650657604.415428][3870:3875] CHIP:CTL: Device supports: wifi (no) thread(yes)
    [1650657604.415492][3870:3875] CHIP:CTL: Going from commissioning step 'SendNOC' with lastErr = '../../../examples/chip-tool/third_party/connectedhomeip/src/controller/AutoCommissioner.cpp:180: CHIP Error 0x0000002F: Invalid argument' --> 'Cleanup'
    ```
5. The commissioner _claims_ to commission successfully (says `Device commissioning completed with success`) because the _cleanup_ step succeeds, but that's a lie, of course.  We failed out in an earlier step.   We need to get this part fixed.
6. Since we did AddNOC, the commissionee advertises operational, and it's on the network, so when we try to do a read it works.
7. Some time passes, and the fail-safe expires on the commissionee:
    ````
    [1650657662.023673][10820:10820] CHIP:SVR: Failsafe timer expired
    ...
    [1650657662.023706][10820:10820] CHIP:SVR: Commissioning failed (attempt 1): ../../../examples/door-lock-app/linux/third_party/connectedhomeip/src/app/server/CommissioningWindowManager.cpp:63: CHIP Error 0x00000032: Timeout
    ````
    and then it kills off the new fabric we added.  The next time we try a read, we still have the cached advertisement (until the DNS TTL expires), so even though commissionee is no longer advertising operational we discover it.  But when we try to set up CASE that fails, because the fabric is gone on the commissionee.

The "we think this is thread" issue is suspiciously like https://github.com/project-chip/connectedhomeip/issues/17477 but in reverse.

**Comment by bzbarsky-apple** [comment]
OK, so `LinuxWiFiDriver` is _only_ instantiated in all-clusters-app, lighting-app, and thermostat.  `LinuxThreadDriver` only in all-clusters-app, for that matter.

Which means that the door lock app is not actually running a useful network commissioning server at all.  But it does claim to implement the cluster, and has a FeatureMap attribute with default value 2: see https://github.com/project-chip/connectedhomeip/blob/fa087ea426877b570f4fc0ab72bf97826f9dc267/examples/lock-app/lock-common/lock-app.zap#L2503

So that's what we end up with here.
