### ISSUE TITLE
Modeselect cluster [TC-MOD-3.3] - is failed in OTA-Requestor app due to endpoint issue

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#17271]
**Issues**:
TC-MOD-3.3 - The commands which are executed using OTA-Requestor app  for OTA update it shows "unsupported cluster" for endpoint "0" and "unsupported endpoint" for endpoint "1", 

**Expected behaviour** :
            For endpoint "1" This testcase {TC-MOD-3.3} should work fine using OTA-Requestor app  for OTA update.
                  
**Actual behaviour**:
 ./chip-tool modeselect read start-up-mode 321 0
  { Response Failure: IM Error 0x000005C3: General error: 0xc3 (UNSUPPORTED_CLUSTER)}

./chip-tool modeselect read start-up-mode 321 1
{Response Failure: IM Error 0x0000057F: General error: 0x7f (UNSUPPORTED_ENDPOINT)}

**PFA Logs**:
[Mod t3.3 fail.txt](https://github.com/project-chip/connectedhomeip/files/8469629/Mod.t3.3.fail.txt)

[mod 3.3 f.txt](https://github.com/project-chip/connectedhomeip/files/8469627/mod.3.3.f.txt)

**Comment by woody-apple** [comment]
Cert Blocker Review: Also assigning @bzbarsky-apple for clarifications

**Comment by bzbarsky-apple** [comment]
Nothing requires any particular application to implement the Mode Select cluster.  If the endpoint does not claim conformance to the Mode Select device type, or some other device type that uses that cluster (none of which are defined so far) then it will not have that cluster.

**Comment by bzbarsky-apple** [comment]
@cjandhyala What needs to be fixed on the certification side here so we are not trying to require this cluster to exist when it doesn't have to?
