### ISSUE TITLE
Identify cluster supports lighting app but if we read or pass any command or attribute we are getting issues in RPI platform but passing in thread platform.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17277]
Issues:-
Scenario 1 : Identify cluster supports lighting app but if we read attribute using lighting app the values are different compared to spec where the same attribute is read using all-clusters-app we are getting expected values  according to spec.

Scenario 2 : Identify cluster supports lighting app but if we pass a command  using lighting app we are getting invalid command where the same command passed  using all-clusters-app we are getting expected values  according to spec.

"The mentioned above 2 scenario is for RPI platform which works fine for Thread platform"

steps to reproduce:- sudo ./chip-tool identify trigger-effect 0 0 1 1

PFA log executed in Thread platform using lighting app:-
[Identify command in thread platform.txt](https://github.com/project-chip/connectedhomeip/files/8472666/Identify.command.in.thread.platform.txt)

PFA log executed in RPI platform using lighting app:-
[Identify command.txt](https://github.com/project-chip/connectedhomeip/files/8472678/Identify.command.txt)

PFA log executed in RPI platform using all-cluster-app
[identify command in All-cluster-app.txt](https://github.com/project-chip/connectedhomeip/files/8472705/identify.command.in.All-cluster-app.txt)

**Comment by cjandhyala** [comment]
@Rajashreekalmane since this is working on all-cluster-app can we close this issues. Not sure if this functionality will be implemented in lightingApp.
