### ISSUE TITLE
Build ZAP UI

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1730]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by wehale** [comment]
ZAP already has a UI, we are working all the time on extending it. There may be specific features we need and we should add those when we run into them.
