### ISSUE TITLE
[TC-TM-2.1]MeasuredValue, MinMeasuredValue attribute and MaxMeasuredValue Attribute fails to return the value within the expected range.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17308]
#### Problem
As per the test-plan In [TC-TM-2.1] test case MeasuredValue, MinMeasuredValue attribute and MaxMeasuredValue
 Attribute fails to return the value within the expected range, but currently in chip-tool getting responses as "null".

 * expected behavior:- value should be in the range of -27315 and 32767
 * actual behavior:- getting response value as "Null"

 * steps to reproduce:-
 ./chip-tool temperaturemeasurement read measured-value 1 1
./chip-tool temperaturemeasurement read min-measured-value 1 1
./chip-tool temperaturemeasurement read max-measured-value 1 1

Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/temperaturemeasurement.adoc#tc-tm-2-1-attributes-with-server-as-dut

Spec screenshot:-
![image](https://user-images.githubusercontent.com/95841834/163127992-b9a82600-be77-4f29-9700-2dd806b75d07.png)

PFA log below:-
[[TC-TM-2.1].txt](https://github.com/project-chip/connectedhomeip/files/8479331/TC-TM-2.1.txt)

**Comment by bzbarsky-apple** [comment]
The attribute is nullable, and null is a valid value.
