### ISSUE TITLE
[SQA] Attributes has to be implemented Based on TC-DL-2.1

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#17314]
Issue : Below mentioned attributres has to be implemented in CHIPTOOL 

Reference : [https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/door_lock_Cluster.adoc#32-tc-dl-21-attributes-check-dut---server](url)

**Missing attributes** :

- DoorOpen Events
- DoorClosed Events
- OpenPeriod
- NumberOfLogRecordsSupported
- NumberOfHoliDaySchedulesSuppored
- EnableLogging 
-  WrongCodeEntryLimit
-  UserCodedTemporaryDisableTime
-  SendPINOverTheAir
-  ExpiringUserTimeOut
-  AlarmMask 
-  KeypadOperationEventMask
-  RemoteOperationEventMask
-  ManualOperationEventMask
-  RFIDOperationEventMask
-  KeypadProgrammingEventMask
-  RFIDProgrammingEventMask

**Comment by andy31415** [comment]
@Survensa could you provide a summary of which of the above are mandatory vs optional and what you are observing based on featuremap key on your tests?

Looking at the first few:
  - DoorOpenEvents is conformance `[DPS]` so it seems optional to me and even then only available if DPS feature exists
  - same for doorclosedevents and openperiod

overall the list of items in door lock seems to contain a large list of optional or feature dependent attributes.

We have to focus only on the items that are fully mandatory in the spec.

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @cjandhyala to follow up. @bzbarsky-apple points out that this may actually work now.

**Comment by Survensa** [comment]
Test plan has been updated and merged with PR : [1270](https://github.com/CHIP-Specifications/chip-test-plans/pull/1270)
