### ISSUE TITLE
[TC-IDM-3.2]--In test step 25 "DUT Fails to send Write Response message with the error DATA_VERSION_MISMATCH" 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17312]
#### Problem
As per Test-Plan [TC-IDM-3.2] test-step 25 expected that DUT should sends a Write Response message with the error DATA_VERSION_MISMATCH for the second Write request, when TH sends a second Write 
Request Message to the DUT to modify the value of an attribute with the dataversion field set to
 the value received earlier.
 
* expected behavior:-DATA_VERSION_MISMATCH(0x92)
 * actual behavior:-SUCCESS (0x00)

 * steps to reproduce:-
 1. ./chip-tool onoff read start-up-on-off 1 1
 2.  ./chip-tool onoff write start-up-on-off 1 1 1
 3. ./chip-tool onoff write start-up-on-off 2 1 1 --data-version 0x365b6fd5

system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 20e1a4a705770d5222a8ebf04e12ab2ce0304df6
Dut: All-Clusters-app

Spec Reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#write-response-action

Test-Plan screenshot:-
![image](https://user-images.githubusercontent.com/95841834/163150476-4e6b84c9-14c9-49eb-8bb1-4a88eaa42092.png)

PFA log below:-
[TC-IDM-3.2_step 25.txt](https://github.com/project-chip/connectedhomeip/files/8480198/TC-IDM-3.2_step.25.txt)

**Comment by vivien-apple** [comment]
@yunhanw-google Do you have any idea of what is going on ?

**Comment by yufengwangca** [comment]
I saw following error as I try to repo this issue.

```
yufengwang@yufengwang:~/connectedhomeip/out/debug/standalone$ ./chip-tool onoff write start-up-on-off 2 12344321 1 --data-version 0x1172457513
[1650930536.603139][1341278:1341278] CHIP:TOO: InitArgs: Invalid argument data-version: 0x1172457513
Usage:
  ./chip-tool onoff write attr-name attr-value node-id/group-id endpoint-id-ignored-for-group-commands [--paa-trust-store-path] [--commissioner-name] [--commissioner-nodeid] [--commissioner-fabricid] [--trace_file] [--trace_log] [--ble-adapter] [--timedInteractionTimeoutMs] [--data-version] [--suppressResponse] [--timeout]
[1650930536.603190][1341278:1341278] CHIP:TOO: Run command failure: ../../../examples/chip-tool/commands/common/Commands.cpp:137: Error 0x0000002F
yufengwang@yufengwang:~/connectedhomeip/out/debug/standalone$ 
yufengwang@yufengwang:~/connectedhomeip/out/debug/standalone$ 
```

**Comment by yunhanw-google** [comment]
From the log, it should the last WriteRequest don't have dataVersion inside, it should have dataVersion inside, in addition, this logic has been validated in python, so there is the regression from chip-tool's WriteAttribute dataVersion to WriteClient::EncodeAttribute. @erjiaqing  could you take a look at this?

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/17801
