### ISSUE TITLE
Data dependency bug in Fail Safe arming detection

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#17324]
#### Problem
- In the log [run_test_suite_log.txt](https://github.com/project-chip/connectedhomeip/files/8481924/run_test_suite_log.txt), I had just run `run_test_suites.py` against a ToT (a75cd99d851cff80e14e753c85f34ff936c84254) and I got a crash in chip-all-clusters-app on Linux.

The backtrace: 
[all-clusters-fail-safe-backtrace.txt](https://github.com/project-chip/connectedhomeip/files/8481941/all-clusters-fail-safe-backtrace.txt)

From the backtrace, it appears that `chip::DeviceLayer::PlatformManager::InitChipStack()` can fail if:
- `GetFailSafeArmed(failSafeArmed)` yields that `failSafeArmed` is true BUT that `FailSafeContext::LoadFromStorage` fails.

This causes early init crash of Linux app, in a way that is unrecoverable without removing both ConfigurationManager storage (`/tmp/*.ini` file) and KVS (`/tmp/*kvs*`). The issue seems related to having previous aborted commissioning, and then having run unit tests, but I cannot reproduce easily after removing the config files. The root cause is obvious though: too strong of an assumption that storage will succeed to load.

*WE SHOULD NOT HAVE ANY* failure of `chip::DeviceLayer::ConfigurationManagerImpl::Init()` due to missing storage. We should also *NOT* be handling the fail-safe reboot check that deep in init. It should be handled after stack init.

 #### Proposed Solution
In the below code, it is clear that we both use ConfigurationManager and PersistentStorageDelegate, which is an unacceptable mix that can get out of sync on Linux.

Fix is to avoid using ConfigurationManager at all to detect fail-safe arming, and only rely on fail-safe context storage

![image](https://user-images.githubusercontent.com/1313847/163193360-97e17c4f-6198-4d05-b03f-e0ba1fd44d68.png)

**Comment by bzbarsky-apple** [comment]
@tcarmelveilleux Is this still an issue after your changes to how we do fail-safe stuff across restarts?
