### ISSUE TITLE
Added one variable in config section but getting error when executed

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17327]
Summary:
               [ TC-DM-2.2 ] tried adding supportedFabric value as 16 in config section getting zap error when executed: TypeError: value.replace is not a function, below i added YAML and execution screenshot.

YAML screenshot: 
![image](https://user-images.githubusercontent.com/84442963/163196472-0d3a89c5-f6a4-4f16-9ddd-fa664275fa21.png)
![image](https://user-images.githubusercontent.com/84442963/163196555-1c3e9422-ec38-4622-8c89-65a2a68043f8.png)

Execution logs and screenshot:
![image](https://user-images.githubusercontent.com/84442963/163196723-39d7c9ed-43f8-41bc-90ac-279dc081e013.png)
[Execution_log.txt](https://github.com/project-chip/connectedhomeip/files/8482028/Execution_log.txt)

**Comment by bzbarsky-apple** [comment]
I just tried this on top of Matter revision 6109d14348023229614227775b57b8b4c80f131a with the following diff applied:
```
diff --git a/src/app/tests/suites/certification/Test_TC_DM_2_2.yaml b/src/app/tests/suites/certification/Test_TC_DM_2_2.yaml
index 625417b1f..c7024ecee 100644
--- a/src/app/tests/suites/certification/Test_TC_DM_2_2.yaml
+++ b/src/app/tests/suites/certification/Test_TC_DM_2_2.yaml
@@ -18,6 +18,9 @@ config:
     nodeId: 0x12344321
     cluster: "Operational Credentials"
     endpoint: 0
+    supportFabric:
+        type: INT8U
+        defaultValue: 16
 
 tests:
     - label: "Wait for the commissioned device to be retrieved"
@@ -69,7 +72,7 @@ tests:
       command: "readAttribute"
       attribute: "SupportedFabrics"
       response:
-          value: 16
+          value: supportFabric
           constraints:
               type: uint8
 
```

and things generated fine.  @manjunathambiger23 what are the exact steps to reproduce this?  Please attach a diff to apply as needed, or better yet please link to a branch in github with the relevant changes.

**Comment by bzbarsky-apple** [comment]
No response, can't reproduce, resolving. 

@cjandhyala
