### ISSUE TITLE
Integrate ZAP into sample application CI

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1733]
#### Problem
Replace the files inside /gen/ folder with file generated from the ZAP application

 #### Proposed Solution
1. Starting with the data available inside the ZCL xml, generate only the required files
2. Move all required functions already present inside the /gen/ folders of examples application to /src/app/
3. Cleanup all unnecessary data from the generated files.
4. Add a generic .zap file to each /gen/ folder in order to allow regeneration of the generated files

**Comment by vivien-apple** [comment]
I assume this task has been done. Closing.
