### ISSUE TITLE
Build failure on M1 Mac with the error message -> No such file or directory: 'protoc'

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#17334]
Starting with commit id a4201ea6fdaff22b6562144a30c563d566152f8f
I am unable to source bootstrap.sh onto M1 Mac machine. 
It throws the following error;

3/226] python3 ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../../third_party/pigweed/repo/pw_protobuf --lockfile protocol_buffer/pip.lock --default-toolchain=//build/toolchain/host:mac_arm64_gcc --current-toolchain=//third_party/pigweed/repo/pw_protobuf_compiler/toolchain:protocol_buffer --capture-output -- ../../third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py --language python --include-file protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/includes.txt --compile-dir protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/sources --out-dir protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/python --sources protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/sources/pw_protobuf_protos/common.proto protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/sources/pw_protobuf_protos/status.proto
FAILED: protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/python/pw_protobuf_protos/common_pb2.py protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/python/pw_protobuf_protos/common_pb2.pyi protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/python/pw_protobuf_protos/status_pb2.py protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/python/pw_protobuf_protos/status_pb2.pyi 
python3 ../../third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../../third_party/pigweed/repo/pw_protobuf --lockfile protocol_buffer/pip.lock --default-toolchain=//build/toolchain/host:mac_arm64_gcc --current-toolchain=//third_party/pigweed/repo/pw_protobuf_compiler/toolchain:protocol_buffer --capture-output -- ../../third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py --language python --include-file protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/includes.txt --compile-dir protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/sources --out-dir protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/python --sources protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/sources/pw_protobuf_protos/common.proto protocol_buffer/gen/third_party/pigweed/repo/pw_protobuf/common_protos.proto_library/sources/pw_protobuf_protos/status.proto
Traceback (most recent call last):
  File "../../third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py", line 202, in <module>
    sys.exit(main())
  File "../../third_party/pigweed/repo/pw_protobuf_compiler/py/pw_protobuf_compiler/generate_protos.py", line 184, in main
    process = subprocess.run(cmd,
  File "/opt/homebrew/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/homebrew/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'

**Steps to reproduce:**
1. git clone --recurse-submodules https://github.com/project-chip/connectedhomeip.git
2. cd connectedhomeip/
3. git reset --hard a4201ea6fdaff22b6562144a30c563d566152f8f
4. git clean -Xdf
5. git submodule update --init
6. source scripts/bootstrap.sh 

Attaching the complete log file
[bootstrap-error.txt](https://github.com/project-chip/connectedhomeip/files/8482433/bootstrap-error.txt)

**Comment by kean-apple** [comment]
confirmed fixed with https://github.com/project-chip/connectedhomeip/pull/17345
