### ISSUE TITLE
Allow injecting SessionResumptionStorage for controller

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#17412]
#### Problem
Currently SessionResumptionStorage can be injected for server.  But not on controller

 #### Proposed Solution
Make it injectable for controller

**Comment by msandstedt** [comment]
We have also identified another problem with the current implementation, which has concrete implementation in the base class.  We require a fully replaceable implementation, which means we need a completely abstract base class.  A class hierarchy like this could work:

* `AbstractSessionResumptionStorage` abstract class, only virtual interfaces; does not exist today
* `SessionResumptionStorage : AbstractSessionResumptionStorage`: some implementation
* `SimpleSessionResumptionStorage : AbstractSessionResumptionStorage`: the rest of the implementation

@kghost, can this be provide as part of the work for this issue, or do we need to introduce this ourselves.

CC @kianooshkarami , @wbschiller , @z-michel, @tcarmelveilleux
