### ISSUE TITLE
CASE storage: FabricSession() key is slightly inconsistent

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#17445]
#### Problem
DefaultStorageKeyAllocator.h uses the key FabricSession() formatted as "f/%x/s/%08" PRIX32 "%08" PRIX32 which is slightly inconsistent with the convention used for all the other numeric keys that do not use zero padding and do not use uppercase hex. For fabric 1/1 we end up with the key "f/1/s/0000000000000001".

 #### Proposed Solution
Use "f/%x/s/%" PRIx64 which for the example above will result in "f/1/s/1".

**Comment by bzbarsky-apple** [comment]
> Use "f/%x/s/%" PRIx64 which for the example above will result in "f/1/s/1".

We can't use PRIx64 on devices....  not all libcs support it.

**Comment by bluebin14** [comment]
Closing as per above.
