### ISSUE TITLE
CASESession: data needed for resumption key derivation is uninitialized

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#17450]
#### Problem
mInitiatorRandom and mResumptionId are needed to derive resumption keys as per the specification. Yet mInitiatorRandom is left uninitialized in the server and mResumptionId is left uninitialized in the client.

 #### Proposed Solution
1 - in HandleSigma1() after calling ParseSigma1() add:
memcpy(mInitiatorRandom, initiatorRandom.data(), sizeof(mInitiatorRandom));

2 - in HandleSigma2Resume() after getting resumptionId from TLV add:
mResumptionId = resumptionId;

**Comment by kghost** [comment]
I found this problem when solving #17440

Also I need to know whether the session is resumed or not, I'm rewriting state of CASE session to make it more clear.
