### ISSUE TITLE
[TC-MC-1.10] (Application Basic cluster) attribute value mismatch 

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#17459]
Summary:
As per testplan of TC-MC-1.10 GeneratedCommandList attribute got wrong response value, got [ ] 0 expected value [2].

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/163807141-81ebc027-4674-44db-bab1-1b37a42e775e.png)

Execution screenshot:
[MC10_GCL.txt](https://github.com/project-chip/connectedhomeip/files/8505586/MC10_GCL.txt)
![MC10_GeneratedCL](https://user-images.githubusercontent.com/84442963/163807168-14d44887-f843-4151-a595-879f8fe783e6.png)

**Comment by bzbarsky-apple** [comment]
@manjunathambiger23 "Application Basic" does not have any commands.  Please fix the test plan.
