### ISSUE TITLE
[TC-MC-1.11] (Content Launcher cluster) attribute value mismatch

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#17460]
Summary:
As per testplan TC-MC-1.11 AcceptedCommandList and GeneratedCommandList attribute showing value mismatch error when executed
1. AcceptedCommandList expected value [0] but got [0,1].
2. GeneratedCommandList expected value [1] but got [ ] 0 entries.

Testplan screenshot: 
![image](https://user-images.githubusercontent.com/84442963/163808050-6f43eebf-30dd-452f-b274-f81f16b8ba6d.png)

Execution screenshot and logs:
[MC11_ACL.txt](https://github.com/project-chip/connectedhomeip/files/8505642/MC11_ACL.txt)
[MC11_GCL.txt](https://github.com/project-chip/connectedhomeip/files/8505643/MC11_GCL.txt)
![MC-11_ACL](https://user-images.githubusercontent.com/84442963/163808152-feffb9aa-cd4a-4197-b86f-31839f8c4c2a.png)
![MC-11_GCL](https://user-images.githubusercontent.com/84442963/163808159-9a603f45-b516-4c9d-89fd-e77fa173229b.png)

**Comment by bzbarsky-apple** [comment]
This depends on the feature map of the cluster.  The generated command list must be `[2]`, but the accepted command list might be different things.  Please get the test plan fixed @manjunathambiger23

**Comment by manjunathambiger23** [comment]
https://github.com/CHIP-Specifications/chip-test-plans/issues/1107

**Comment by franck-apple** [comment]
> CHIP-Specifications/chip-test-plans#1107

test plan modified. Closing the issue.
