### ISSUE TITLE
[TC-MC-1.12] (Account Login cluster) attribute value mismatch

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17461]
Summary:
As per testplan TC-MC-1.12 AcceptedCommandList and GeneratedCommandList attribute got value mismatch error when executed
1.AcceptedCommandList expected value [0,2,3] but got [0
2.GeneratedCommandList expected value [1] but got [0]

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/163809225-a917600c-300a-4044-a670-8a1a8c75c934.png)

Execution screenshot:
![MC12_ACL](https://user-images.githubusercontent.com/84442963/163809344-ff0e058f-e8f9-42fc-bb11-4213f3db8882.png)
[MC12_ACL.txt](https://github.com/project-chip/connectedhomeip/files/8505683/MC12_ACL.txt)
![MC12_GCL](https://user-images.githubusercontent.com/84442963/163809358-41cdad93-3d26-4fd6-8ed4-a391dae7114d.png)
[MC12_GCL.txt](https://github.com/project-chip/connectedhomeip/files/8505684/MC12_GCL.txt)

**Comment by manjunathambiger23** [comment]
https://github.com/CHIP-Specifications/chip-test-plans/issues/1107

**Comment by bzbarsky-apple** [comment]
#17833 might fix this.

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.

**Comment by bzbarsky-apple** [comment]
At this point the accepted list is `[0]` and the generated list is `[1]`.  The actual ZAP config has everything disabled (not valid, for required commands), so I'm a little surprised the lists are not just empty...

**Comment by woody-apple** [comment]
SDK Spec Review: Tagging @cjandhyala to follow up to see if this should be a cert blocker.

**Comment by cjandhyala** [comment]
closing per @manjunath-grl request

**Comment by manjunath-grl** [comment]
@cjandhyala its related to scripting issues can you please reopon it.

**Comment by bzbarsky-apple** [comment]
@manjunath-grl I am happy to reopen if there is an updated description of the state of things on ToT right now and what's not working right.  Can you provide that please?  This issue is not actionable in the form it's in right now.
