### ISSUE TITLE
[TC-TSUIC-1.1] "Thermostat User Interface Configuration" cluster attribute value mismatch

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#17464]
Summary:
As per testplan TC-TSUIC-1.1 AttributeList showing value mismatch error when executed.
expected value [0,1,2] but got more than that.

Testplan screenshot: 
![image](https://user-images.githubusercontent.com/84442963/163813678-6cd1fc15-87ff-49a8-a988-5585303070f4.png)

Execution logs:
![Tsuic_1AL](https://user-images.githubusercontent.com/84442963/163813716-23c7c1f4-9cbe-4b16-a80a-29bc0c473340.png)
[Tsuic_1AttributeList.txt](https://github.com/project-chip/connectedhomeip/files/8505856/Tsuic_1AttributeList.txt)

**Comment by bzbarsky-apple** [comment]
@manjunathambiger23 The test plan is wrong.  AttributeList always includes the global attributes.
