### ISSUE TITLE
[TC-TM-1.1] Temperature Mesurement cluster AttributeList attribute value mismatch

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#17463]
Summary: 
As per testplan TC-TM-1.1 AttributeList showing value mismatch error when executed .
expected value [0,1,2,3] but got more than that.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/163810878-dc1a094b-b426-4d1d-9a1f-947ac5d21937.png)

Execution screenshot:
![TM_AttributeList](https://user-images.githubusercontent.com/84442963/163810912-dd891fef-8d20-4e23-a305-79e16e02bc58.png)
[TM_AttributeList.txt](https://github.com/project-chip/connectedhomeip/files/8505750/TM_AttributeList.txt)

**Comment by bzbarsky-apple** [comment]
@manjunathambiger23 The test plan is wrong. AttributeList always includes the global attributes.
