### ISSUE TITLE
[TC-BOOL-1.1]-AttributeList Value Mismatch 

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#17480]
Summary:
Executed TC-BOOL-1.1 Testscript as per latest testplan but getting Attribute List value mismatch error

Note:
Expected value is [0] but instead of that got  [0,65528,65529,65531,65533] value response

Testplan screenshot:
![Bool-1-1](https://user-images.githubusercontent.com/57476670/163911672-7adf9ac6-db1d-4ced-81a9-c2bc4a8be7ea.png)
Error Screenshot:
![Screenshot from 2022-04-18 14-08-22](https://user-images.githubusercontent.com/57476670/163911699-166f90b7-b274-42cf-b060-735b42dd4283.png)
[BOOL-1-1-Attributelist-mismatch.zip](https://github.com/project-chip/connectedhomeip/files/8509510/BOOL-1-1-Attributelist-mismatch.zip)

**Comment by bzbarsky-apple** [comment]
The test plan (depending on how you read it) and test (definitely) is wrong: global attributes are always included in the list.
