### ISSUE TITLE
[SQA]- Thread-Getting 0x87 error code instead of 0x85

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#17493]
**Problem:**
While executing the (TC-MOD-2.1) Verification Step 3 expects 0x85 as error response code but getting 0x87.

**Expected behavior:** 0x85 ( INVALID_COMMAND)

**Actual behavior:** 0x87 (CONSTRAINT_ERROR)

**Steps to reproduce:** `./chip-tool modeselect change-to-mode 2 51 1`

**Platform:** Thread All-clusters-app

**CommitID** used: 20e1a4a705770d5222a8ebf04e12ab2ce0304df6

**Reference:**
![Screenshot from 2022-04-19 15-40-56](https://user-images.githubusercontent.com/95559513/163981761-63684a5b-5bce-4d62-aa03-ab60dc2f7069.png)

**Log:**

> CHIP:TOO: Run command failure: IM Error 0x00000587: General error: 0x87 (CONSTRAINT_ERROR)

**Comment by Damian-Nordic** [comment]
Posted a PR.
