### ISSUE TITLE
[TC-IDM-3.2]-SDK support required to set endpoint as null.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17501]
Test Case ID:-
[TC-IDM-3.2] Write Response Action from DUT to TH

Problem:-
As per Test-Plan, test step 21 says "TH sends the Write Request Message to the DUT to modify the value of one attribute on a given cluster and endpoint to null". Do we have the SDK developed to support these steps?

Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-2-2-report-data-action-from-dut-to-th

PFA screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/164007376-eecae8b1-bc09-4887-95f5-04c7624cbb9b.png)

**Comment by vivien-apple** [comment]
```0xFFFF``` should be the value you are looking for. It maps to `null` in this case.
