### ISSUE TITLE
Keypad Input cluster showing failure response for Endpoint 1

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#17510]
Summary:
Keypad Input cluster:  showing :" 0xc3 (UNSUPPORTED_CLUSTER) " response for endpoint "1" when executed.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/164033648-2b35e4c0-92a0-4650-9bcd-ae363ed532e6.png)

Execution screenshot:
![image](https://user-images.githubusercontent.com/84442963/164034260-208429c8-db97-4176-8309-d6ef2bc5deae.png)
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/8514144/exe_log.txt)

**Comment by bzbarsky-apple** [comment]
@manjunathambiger23 Is this being tested against an app (like tv-app) that actually supports this cluster?

**Comment by manjunathambiger23** [comment]
@bzbarsky-apple yes its been tested against tv-app

**Comment by manjunathambiger23** [comment]
we use the following command for Build
./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-chip-tool-no-ble-tsan \
                        --target linux-x64-all-clusters-test-group-no-ble-tsan \
                        --target linux-x64-lock-app-no-ble-tsan \
                        --target linux-x64-tv-app-no-ble-tsan \
                        build \
                        --copy-artifacts-to objdir-clone \
                     "

**Comment by chrisdecenzo** [comment]
For some reason, it looks like the KeypadInput cluster commands are not enabled in zap:

        {
          "name": "Keypad Input",
          "code": 1289,
          "mfgCode": null,
          "define": "KEYPAD_INPUT_CLUSTER",
          "side": "server",
          "enabled": 1,
          "commands": [],
          "attributes": [
            {
              "name": "ClusterRevision",
              "code": 65533,
              "mfgCode": null,
              "side": "server",
              "included": 1,
              "storageOption": "RAM",
              "singleton": 0,
              "bounded": 0,
              "defaultValue": "1",
              "reportable": 1,
              "minInterval": 0,
              "maxInterval": 65344,
              "reportableChange": 0
            }
          ]
        },

When I perform a read of the cluster revision attribute on this cluster, I get back success:

./out/debug/chip-tool keypadinput read cluster-revision 1234 1

So I think the issue is just that the commands are not enabled.

**Comment by chrisdecenzo** [comment]
And it looks like this never worked on all-clusters-app

**Comment by chrisdecenzo** [comment]
hi @lazarkov - can you enable all the commands and all the attributes for each media cluster on the all-clusters-app please?

**Comment by lazarkov** [comment]
@manjunathambiger23 can you please use tv-app for testing? all-clusters-app is not supported.
