### ISSUE TITLE
Generate Test Vectors for Device Attestation Flow Testing

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#17511]
#### Problem
Need to generate test vectors for positive and negative testing of Device Attestation flow when Commissioner is DUT. 

related to #14395, #14397, #14399

 #### Proposed Solution
Use `chip-cert` tool to generate these test vectors. 
Proposed groups of test vectors:
  * PAI Certificate Structural errors 
  * DAC Certificate Structural errors 
  * CD Structural errors 
  * Validation flow errors

**Comment by woody-apple** [comment]
SDK Spec Review: Closing, this is complete.
