### ISSUE TITLE
Ensure tests drain all message in loopback transport

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#17624]
#### Problem
Some tests leaves messages in async loopback transport after complete, we should ensure that all tests drain all messages after completion.

 #### Proposed Solution
Add `DrainAndServiceIO` after such test cases.

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/17622#discussion_r855792077 has one such test that needs fixing.
