### ISSUE TITLE
Facing pairing issues for ECM test of Multi Fabrics testcases 

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17666]
Summary:
Facing Pairing issue for ECM tests. if commissioning window is opened for 1st Commissioner ,if we try to open commissioning process with DUT_CE for 2 nd Commissioner showing FAILURE response
and its blocking following tests
TC-MF-1.5
TC-MF-1.13

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/164882843-744716f8-6b0f-442d-9906-bcdb0fdec658.png)
![image](https://user-images.githubusercontent.com/84442963/164882857-884d6ab4-98a0-405d-9c1d-a588fe36cf87.png)

Execution screenshot:
![image](https://user-images.githubusercontent.com/84442963/164882890-20affd1b-7ca7-415b-bb38-a7e00785ac42.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.

**Comment by manjunath-grl** [comment]
Added diff: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:Commissioning_error

**Comment by manjunath-grl** [comment]
@raju-apple discussed with QA team they are not facing this issue and they are following the testplan no Preconditions are there and script is also as per testplan but in " step 13: TH_CR2 starts a commissioning process with DUT_CE " we are getting failure response when executed.
YAML script [TC_CADMIN_1_5](https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CADMIN_1_5.yaml).

**Comment by raju-apple** [comment]
@krypton36 can you please check this issue out when you get a chance ?

**Comment by krypton36** [comment]
The PAKEVerifier and the setup PIN code do not match. 
The setup qr parses to the following (20202021):
<img width="704" alt="Screenshot 2022-07-27 at 1 06 21 PM" src="https://user-images.githubusercontent.com/12054330/181362471-a0b1d71f-4e4a-45b1-abdf-7e6622aee436.png">

The PAKEVerifier is using the following (47514138):
<img width="1223" alt="Screenshot 2022-07-27 at 1 06 38 PM" src="https://user-images.githubusercontent.com/12054330/181362585-4eeceb30-a161-4d37-a4a3-5baccc628192.png">

This corresponds to the error message:
`Failed to verify peer's MAC. This can happen when setup code is incorrect.`

Please make sure that the PAKEVerifier for ECM and the SetupQRCode pin code match.

**Comment by manjunath-grl** [comment]
@krypton36 can you please tell the steps how to generate PAKEVerifier using setup PIN code.

**Comment by krypton36** [comment]
ninja -v -C out/host spake2p
./out/host/spake2p gen-verifier -p 20202021 -i 1000 -l 32 -s 5350414B453250204B65792053616C74 -o pake_verifier.txt

**Comment by krypton36** [comment]
5350414B453250204B65792053616C74 might need to be encoded to base64

**Comment by krypton36** [comment]
echo "5350414B453250204B65792053616C74" | xxd -r -p | base64

**Comment by krypton36** [comment]
Or `echo -n "SPAKE2P Key Salt" | od -A n -t x1 | xxd -r -p | base64`

**Comment by manjunath-grl** [comment]
@raju-apple can you please close the ticket its resolved.
