### ISSUE TITLE
[nRF Platform Example] Bring up CHIP Stack - Support Pairing Start button

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1768]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by mspang** [comment]
Already done.

**Comment by mspang** [comment]
Actually this probably still needs work as it triggers thread commissioning.

**Comment by LuDuda** [comment]
That is already implemented and not valid for the nRF Connect platform. Closing.
