### ISSUE TITLE
Color control cluster doesn't support feature map for hue/saturation/color temperature

### ISSUE THREAD

**Issue by nivi-apple** [project-chip/connectedhomeip#17700]
#### Problem
Color control cluster exposes apis for reading/writing and subscribing to Hue, Saturation and color temperature. However it doesn't support the feature map attribute. Hence it's not spec complaint. See the feature map table from the spec -

Bit Code Feature Description
--
0 | HS | Hue/Saturation | Supports color specification via hue/saturation.
1 | EHUE | Enhanced Hue | Enhanced hue is supported.
2 CL Color loop Color loop is supported.
3 | XY | XY | Supports color specification via XY.
4 | TEMP | Color temperature | Supports specification of color temperature.

 #### Proposed Solution
Need to add support for feature map attribute to Color Control cluster

**Comment by bzbarsky-apple** [comment]
@nivi-apple I believe this was fixed in #17082.  Can you please confirm?  You filed this issue much later than that, but I don't know what SHA you were using....

**Comment by nivi-apple** [comment]
@bzbarsky-apple I was on an older SHA. I will verify on the tip of tree as well next time :). closing the issue. Thanks
