### ISSUE TITLE
[nRF Platform Example] Bring up CHIP Stack - Support LED

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1770]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by mspang** [comment]
Already done.
