### ISSUE TITLE
[TC-LO-2.1] Need YAML support for SupportedLocales attribute list not having duplicates

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17738]
Summary:
Need YAML support for SupportedLocales attribute list values are not repeated.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/165289693-8bc53256-00dd-4473-9d07-f5fda463d95b.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
