### ISSUE TITLE
[TC-DM-4.*] Need YAML support for access XPAN ID form Operational Dataset

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17735]
Summary:
How do we access XPAN ID form OperationalDataset’s need to save the value as "Userth_op"
Also need way to check if a specific value is present in the "ServerList" attribute
Affecting following tests:
1.TC-DM-4.6
2.TC-DM-4.10
3.TC-DM-4.12
4.TC-DM-4.8
5.TC-DM-4.16
6.TC-DM-4.7
Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/165281578-b0230300-c795-42cc-a2e3-e80ea63ab7e8.png)
![image](https://user-images.githubusercontent.com/84442963/165281641-025be05f-0077-4df2-acbe-ae295a09329b.png)

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/165282008-9bcb3214-6e19-4451-b7b2-aea4f1bd85e0.png)

**Comment by raju-apple** [comment]
@manjunath-grl - Can you tag your previous issues with your new ID so folks don't ignore the tickets please

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
