### ISSUE TITLE
PICS_SKIP_SAMPLE_APP not working in Darwin system

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#17734]
Summary:
PICS_SKIP_SAMPLE_APP is not working fine in Darwin system it is not skipping the test step instead it running the tests as usual but works fine in linux
Steps to produce:
1.Add PICS_SKIP_SAMPLE_APP value to 0 in ci-pics_value file
2. Run zap_regen_all,build and run the tests
3. The tests step with PICS: PICS_SKIP_SAMPLE_APP are not skipping eg( PR: https://github.com/project-chip/connectedhomeip/pull/17513)

execution logs:
[logs_950321.zip](https://github.com/project-chip/connectedhomeip/files/8561261/logs_950321.zip)

**Comment by bzbarsky-apple** [comment]
The best course of action is to have the tests run in chip-tool-darwin.  We are working on removing the XCTest tests and do not plan to add new features to them.  chip-tool-darwin-based tests are the replacement.

For now, whatever tests need to use PICS should probably be removed from the XCTest test manifests.
