### ISSUE TITLE
[TC-BC-2.1] Need YAML support for following Scenario

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17741]
Summary:
Need YAML support for following scenarios
 Scenario 1: How do we make sure the devices are with same node id but different endpoints
 Scenario 2: How do we make sure endpoints and node ids are different 
 Scenario 3: How do we have multiple TH devices on different fabric

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/165296376-38930472-ec81-43df-9006-59e379a02f05.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
