### ISSUE TITLE
[TC-MC-1.7]Media Playback Cluster--FeatureMap returns status code as 0x86 Error(unsupported attribute) Response

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17749]
#### Problem
Though the feature map attribute is implemented in Application Launcher
cluster it throws an error code as 0x86(unsupported attribute).

    expected behavior:-FeatureMap bitmap value

    actual behavior:-0x86(unsupported attribute

 * steps to reproduce:-sudo ./chip-tool mediaplayback read feature-map 1 3

system configuration:-
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/3a7f03a0a1c58c4f6cf69ea7e6b808feff3b6636
Dut: TV-app
 
Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-1-6-global-attributes-channel-cluster-dut-as-server

PFA log below:-
[TC-MC-1.6.txt](https://github.com/project-chip/connectedhomeip/files/8563362/TC-MC-1.6.txt)

**Comment by chrisdecenzo** [comment]
I believe this is addressed by https://github.com/project-chip/connectedhomeip/pull/17574. Can you confirm @lazarkov
