### ISSUE TITLE
[TC-GC-2.3] need YAML support to send commands in  between commissioning process

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17747]
Summary:
Need YAML support for Step5 :How do we send command in  between commissioning process

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/165303772-1ecce004-348a-431d-b897-9318ddbbf847.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.

**Comment by krypton36** [comment]
@manjunath-grl this should be possible if you do not do the WaitForCommissionee command. You will have to run each of the commands to pair.

**Comment by raju-apple** [comment]
@krypton36 @manjunath-grl Can you guys sync up on the next steps here please ? Creating a list for the items that we need  from the SDK team post 1.0, so want to have clear requirements for each task

**Comment by raju-apple** [comment]
@manjunath-grl , were you able to sync up ?
