### ISSUE TITLE
[TC-DM-4.*] how to access the List elements

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17753]
Summary:
Need YAML support to 'Userwifi_ssid' is the SSID value and serves as the NetworkID value also which is present in the Networks attribute list with NetworkIndex as 'Wifinet_idx'
TC-DM-4.4
TC-DM-4.5
TC-DM-4.11

Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/165310275-05e21f82-10e5-41bf-985f-a501cb896128.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
