### ISSUE TITLE
[TC-GC-2.4] Need YAML support for to save FailSafeExpiryLengthSeconds value from previous commissioning session

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#17756]
Summary:
Need YAML support to reads the BasicCommissioningInfo attribute’s FailSafeExpiryLengthSeconds value from the DUT during the previous commissioning session.

Testplan screenshot;
![image](https://user-images.githubusercontent.com/84442963/165324789-7e25387b-fce4-4fb3-a7d2-ce3c2cbd82ee.png)

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/165324669-fed79b43-4bcc-43e5-a535-a6cc409c3e6a.png)

**Comment by manjunath-grl** [comment]
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.
