### ISSUE TITLE
[TC-GC-1.1] Global attribute Generated-command-list is listing 2 entries instead 3 entries.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17809]
#### Problem
As per Test-Plan, for Generated Command list DUT  should include all mandatory 
commads(values 1,3,5). currently DUT is responding with 2 entries.

 * expected behavior:-DUT Should list all mandatory commands(1,3,5)
 * actual behavior:-Dut responds with 2 commands(1,5)
 
* steps to reproduce:-sudo ./chip-tool generalcommissioning read generated-command-list  1 0

system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 3a7f03a0a1c58c4f6cf69ea7e6b808feff3b6636
Dut: All-Clusters-app
 
Test-Plan reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/General_Commissioning.adoc#tc-gc-1-1-global-attributes-dut-server

PFA logs below:-
[TC-GC-1.1.txt](https://github.com/project-chip/connectedhomeip/files/8572937/TC-GC-1.1.txt)

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/zap/pull/515 will fix things.
