### ISSUE TITLE
Secure session establishment can fail if local MRP parameters cannot fit within 16 bits

### ISSUE THREAD

**Issue by msandstedt** [project-chip/connectedhomeip#17812]
#### Problem

Nodes can exchange MRP parameters during CASE/PASE handshake with the mrp-parameter-struct, which encloses active and idle retry times as 16-bit values.

However, maximum bounds for these are 360,000 milliseconds.  It appears that when populating these, the pairing session code will simply fail.  The implication is that long MRP intervals can likely break PASE and CASE at this location in the code:

https://github.com/project-chip/connectedhomeip/blob/master/src/transport/PairingSession.cpp#L62

 #### Proposed Solution

* consider saturating values for placement in mrp-parameter-struct if local values don't fit
* or consider not sending these if they can't fit - sending is optional
* however, we shouldn't fail secure session establishment as we do now for values that overflow

**Comment by bzbarsky-apple** [comment]
@msandstedt This is a spec-level issue, right?  

I do wonder whether it's worth just changing the units on these values from ms to 10s of ms or 100s of ms, depending on the granularity we think we actually need....

**Comment by robszewczyk** [comment]
Makes sense to me.  I'd prefer to go with the approach that @tcarmelveilleux proposed in the PR and keep the granularity of `ms` rather than invent new units.  Please approve the spec PR, and I will merge it.

**Comment by msandstedt** [comment]
@robszewczyk ,

Thanks.  Makes sense.  Will do.

**Comment by msandstedt** [comment]
@robszewczyk , @tcarmelveilleux , 

See the sdk PR here: https://github.com/project-chip/connectedhomeip/pull/17978
