### ISSUE TITLE
[Silicon Labs Platform Example] Bring up CHIP Stack - Support thread setup over BT

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1782]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by mspang** [comment]
Already done
