### ISSUE TITLE
Failed to decrypt commands sent in a row

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#17858]
with Tot(cfc35951be66a664a6efdadea56d1b8ea6e63e96), running chip-tool on raspi and running all-cluster-app on raspi, when same cmds sent in a row, first cmd throws the below error, while the 2nd CMD succeeds. 

`[1651177351.070468][17194:17200] CHIP:-: ../../src/crypto/CHIPCryptoPALOpenSSL.cpp:336: CHIP Error 0x000000AC: Internal error at ../../examples/chip-tool/commands/clusters/ModelCommand.cpp:53`

[log.txt](https://github.com/project-chip/connectedhomeip/files/8586784/log.txt)

**Comment by bzbarsky-apple** [comment]
@cjandhyala Is this still happening?  This looks like an issue around CASE resumption....
