### ISSUE TITLE
[Darwin Framework] Create object/dispatch oriented abstraction/callbacks for all clusters in Objective C / Swift

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1788]
On Darwin the CHIP framework should use native dispatch and OS APIs.

**Comment by woody-apple** [comment]
SW BRB: Assigning to @vivien-apple

**Comment by vivien-apple** [comment]
@woody-apple Is the work done in #4661 enough or do you expect something else ?
