### ISSUE TITLE
[TV-APP]While verifying the "wild card" read for all the cluster for all the attributes, chiptool responds as "General error: 0x01 (FAILURE)" in TV-APP

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17904]
#### Problem
In tv-app While verifying the wildcard read using the below command, towards the end, Chiptool throws an error with a code 
 "General error: 0x01 (FAILURE)" 
 
* expected behavior:-Success(0x00) 
 * actual behavior:-FAILURE(0x01)

 * steps to reproduce:- sudo ./chip-tool any  read-by-id 0xFFFFFFFF 0xFFFFFFFF 1 0xFFFF

system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/2982c0ca0623773327def4cc7180d07f6b959c42
Dut: tv-app
 
PFA screenshot:-
![image](https://user-images.githubusercontent.com/95841834/165942930-be7cba14-b62e-4127-8bd1-a0010a59510d.png)

Spec reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#valid-read-attribute-paths

**Comment by Rajashreekalmane** [comment]
Problem:
While verifying the "wild card" read for all the cluster for all the attributes for specific endpoint(0), chiptool responds as Invalid Cluster-Specific error code 0x11.

steps to reproduce:-Execution Command:-./chip-tool any read-by-id 0xFFFFFFFF 0xFFFFFFFF 1 0

PFA screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/165945622-2317adb8-4dbf-43db-8d84-ccee7e44ccf5.png)

**Comment by chrisdecenzo** [comment]
this problem is no longer happening for me. It might have been a bug fix in the chip tool
