### ISSUE TITLE
[TC-IDM-3.2]--In test step 25 "DUT Fails to send Write Response message with the error DATA_VERSION_MISMATCH" 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#17909]
#### Problem
Problem

As per Test-Plan [TC-IDM-3.2] test-step 25 expected that DUT should sends a Write Response message with the error DATA_VERSION_MISMATCH for the second Write request, when TH sends a second Write
Request Message to the DUT to modify the value of an attribute with the dataversion field set to
the value received earlier.

    expected behavior:-DATA_VERSION_MISMATCH(0x92)

    actual behavior:-SUCCESS (0x00)

    steps to reproduce:-

    ./chip-tool onoff read start-up-on-off 1 1
    ./chip-tool onoff write start-up-on-off 1 1 1
    ./chip-tool onoff write start-up-on-off 2 1 1 --data-version 0x365b6fd5

system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 99988e5ae1a2271e4eec9e0c296a3fd58358238d 
Dut: All-Clusters-app

Spec Reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#write-response-action

Test-Plan screenshot:-
![image](https://user-images.githubusercontent.com/95841834/165958392-b390a77d-1377-4c9b-91fd-da471a066957.png)

PFA log:-
[TC-IDM-3.2.txt](https://github.com/project-chip/connectedhomeip/files/8591293/TC-IDM-3.2.txt)

**Comment by cjandhyala** [comment]
@Rajashreekalmane Is this still an issue , if not pls close it.
