### ISSUE TITLE
[Android package] Create object/dispatch oriented abstraction/callbacks for all clusters

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1792]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by vidhis88** [comment]
Not clear what this is. Are there more details?

**Comment by woody-apple** [comment]
SW BRB: Not needed for Android.
