### ISSUE TITLE
[Android package] Support QR code Parsing

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1793]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by vidhis88** [comment]
This is already done and tracked by #1103 
@franck-apple, I'll defer to you to appropriately close it.

**Comment by woody-apple** [comment]
SW BRB: Closing
