### ISSUE TITLE
[Android package] Support Communication

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1794]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by vidhis88** [comment]
Not clear on this one. Are there more details?

**Comment by woody-apple** [comment]
SW BRB: This is working great, closing.
