### ISSUE TITLE
[Android package] Support Pairing & Onboarding

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1795]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by vidhis88** [comment]
Will this be covered by #1935?

**Comment by woody-apple** [comment]
SW BRB: Yup, closing.
