### ISSUE TITLE
Global attribute missing from Thermostat cluster

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#17971]
Summary: 
Global attribute "AcceptedCommandList" and "GeneratedCommandList" missing from Thermostat cluster.

Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/166313159-d2b4a7f5-220c-498a-bb5b-4f4c906b5fd3.png)

Execution logs:
[tstat11_CL.txt](https://github.com/project-chip/connectedhomeip/files/8605598/tstat11_CL.txt)
![tstat_CL](https://user-images.githubusercontent.com/102359958/166313194-0c5a14b4-21ff-4745-9376-85c42089d8c3.png)

**Comment by bzbarsky-apple** [comment]
Fixed in #18209.
