### ISSUE TITLE
[Secure Channel] Operational Credentials

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1802]
We need an API to utilize operational credentials. Specifically, we need to be able to:

1. Sign arbitrary blobs of data using the private key backing a device's op cred.
2. Export the operational credential (so as to be sent in a message).
3. Verify a given operational credential chains up to a root.

**Comment by woody-apple** [comment]
SW BRB: @pan-apple @emargolis what are the next steps here?

**Comment by pan-apple** [comment]
Device attestation and CASE session establishment code will help resolve this issue.
