### ISSUE TITLE
Incorrect data type for subscription function in CHIP.framework.

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#18020]
#### Problem
[ChipDevice.h](https://github.com/project-chip/connectedhomeip/blob/caa1d6baca5c662c65ac156564ff3dca6eea0fb3/src/darwin/Framework/CHIP/CHIPDevice.h#L165)
has the incorrect data type in the function linked. It is currently requiring uint16_t and the others are using NSNumber.
 
 #### Proposed Solution
Update function parameters to accept NSNumber.

**Comment by bzbarsky-apple** [comment]
Is there a problem with using uint16_t for these required params?

**Comment by bzbarsky-apple** [comment]
I have a fix for this, but can't post it until after #18527 merges.
