### ISSUE TITLE
[TC-TSTAT-1.1]Thermostat Cluster--Value mismatch for FeatureMap attribute 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18029]
**Problem**

As per test plan [TC-TSTAT-1.1] FeatureMap attribute showing value mismatch error when executed, DUT should
responds with feature map value 5 but currently DUT responding feature map value has 11.

    **expected behavior**:-FeatureMap attribute value should be bit 5.
    **actual behavior**:- DUT responds has bit 11
    **steps to reproduce**:-./chip-tool thermostat read feature-map 1 1

**system configuration**:-
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID:4d50b1084284018c4a628f919b0d2e01ea2a39f8
Dut: all-cluster-app

**PFA log below**:-
[TC-TSTAT-1.1.txt](https://github.com/project-chip/connectedhomeip/files/8618135/TC-TSTAT-1.1.txt)

**Test-plan reference**:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/thermostat.adoc#tc-tstat-1-1-global-attributes-with-server-as-dut

**Comment by bauerschwan** [comment]
I think the test description is wrong. It should never enforce a certain value of FeatureMap. Instead it should only make sure that at least bit 0 and/or bit 1 are set. The other bits should not be checked.
