### ISSUE TITLE
[Data Model] Timed Writes

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1803]
In order to protect against interception attacks, we need to implement timed writes. @pan-apple or @anush-apple can help if folks have questions.

**Comment by pan-apple** [comment]
Timed write commands will be tagged with an expiry TTL. If an accessory mandates a timed write for an attribute, and it receives a timed write command, it tests that the TTL is not expired before executing the command. If the TTL is expired, it does not execute the command, and possibly returns an error. Also, if it receives a non-timed write command for the attribute, it fails the command, and returns an error.

**Comment by woody-apple** [comment]
SW BRB: Assigning to @bzbarsky-apple

**Comment by bzbarsky-apple** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/pull/12567
