### ISSUE TITLE
TV-Casting-app--DUT fails to generate  QR/manual code pairing code.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18043]
**#### Problem**
While testing [TC-MC-11.2], the test steps require generating invalid QR/manual codes used as an Onboarding Payload while testing 
DUT does not currently support generating QR/manual codes.

 * **steps to reproduce**:- ./tv-casting-app
 
**system configuration:-**
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID:4d50b1084284018c4a628f919b0d2e01ea2a39f8			
Dut: tv-casting-app

**Test-Plan Reference**:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-11-2-casting-video-player-via-ux-screen-with-pin-verification-dut-as-server

**PFA log**:-
[tv-casting-app.txt](https://github.com/project-chip/connectedhomeip/files/8621265/tv-casting-app.txt)

**Comment by chrisdecenzo** [comment]
Updated the test case to read: "TH must provide 11/21 digit manual pairing code or setup passcode to enter into DUT." and tv-casting-app displays the setup passcode.
