### ISSUE TITLE
Remove internal synchronization for event management

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#18065]
Wait, why is EventManagement doing internal synchronization?  Followup to stop doing that, please....

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/18016#discussion_r865399931_

**Comment by yunhanw-google** [comment]
@mrjerryjohns @bzbarsky-apple just wanna double confirm the event management would not be used by multi-thread. We are strictly following single threading model?

**Comment by bzbarsky-apple** [comment]
It can be used by multi-thread, but then the consumer has to either lock the Matter stack lock or queue the event bits to the Matter event queue, right?
