### ISSUE TITLE
[Secure Channel] 1-1 traffic - Decrypt Traffic

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1812]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by pan-apple** [comment]
Implemented as part of secure pairing work.
