### ISSUE TITLE
[TC-DM-2.1]--While verifying  optional SoftwareVersionString attribute to write chip-tool throws an error 0x87(CONSTRAINT_ERROR) instead 0x88(UNSUPPORTED_WRITE(0x88)

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18149]
**#### Problem**
[TC-DM-2.1]--While verifying  SoftwareVersionString attribute to write chip-tool throws an error 0x87(CONSTRAINT_ERROR) instead 0x88(UNSUPPORTED_WRITE(0x88)
   

-  **expected behavior:**-UNSUPPORTED_WRITE(0x88)
-  **actual behavior**:- CONSTRAINT_ERROR(0x87)

* **steps to reproduce:**- sudo  ./chip-tool basic write-by-id 0x10 versionstring 1 0

 **system configuration**
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID:4d50b1084284018c4a628f919b0d2e01ea2a39f8			
Dut: All-Clusters-app

**PFA log:-**
[DM-2.1.txt](https://github.com/project-chip/connectedhomeip/files/8639859/DM-2.1.txt)

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicemanagement.adoc#tc-dm-2-1-basic-information-cluster-server-attributes

**Comment by bzbarsky-apple** [comment]
Attribute 0x10 is "LocalConfigDisabled", which is a writable attribute.  But the value being written is wrong for that attribute's type (it's a boolean), so you get the CONSTRAINT_ERROR bit.

If you want to write  SoftwareVersionString the attribute ID needs to be `10` or `0xa`, not `0x10`.
