### ISSUE TITLE
[SQA] TH throws the failure output for the Unlock Door Command.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#18156]
**Problem :** 
While Executing the TC-DL-2.3 , the Unlock door command with the  --timedInteractionTimeoutMs and pincode arguments throws the error code 0x01 (FALIURE). But  the execpted outcome is not the Failure.

**Excepted outcome** :   0x00 (SUCCESS)

**Actual outcome** :  0x01 (FAILURE)

**Step to reproduce :**  `./chip-tool doorlock unlock-door 1 1  --timedInteractionTimeoutMs 1000 --PinCode xxxxxxxx`

**Commit** Used :  4d50b1084284018c4a628f919b0d2e01ea2a39f8

**Platform** : RPI - RPI .

**Logs:**

> [1651750522.416718][3327:3332] CHIP:DMG:                                StatusIB =
[1651750522.416771][3327:3332] CHIP:DMG:                                {
[1651750522.416820][3327:3332] CHIP:DMG:                                        status = 0x01 (FAILURE),
[1651750522.416872][3327:3332] CHIP:DMG:                                },

**Comment by cjandhyala** [comment]
@Survensa is this still an issue ?

**Comment by Survensa** [comment]
Verified with latest commit
