### ISSUE TITLE
[Secure Channel] 1-N Traffic - Support QoS / Reliability Levels

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1817]
Support an API for multicast messaging that expresses various reliability guarantees to the data/interaction model that abstracts away network details. @woody-apple or @pan-apple can help here

**Comment by andy31415** [comment]
Matter spec does not include reliabiligy for group  messaging. This issue was raised pre-spec, however now that the spec is finalized we can close it.
