### ISSUE TITLE
TE9 TC-GC-3.2 Chip tool Darwin testing: Sending GETGROUPMEMBER giving error response

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18181]
As per TC-GC-3.2 step 3, when sending GETGROUPMEMBER command through chip tool Darwin, getting error response saying "Error while encoding GroupList as an array". Seeing the same response on chip tool as well.

Below is the screenshot for the same.
<img width="708" alt="Screen Shot 2022-05-06 at 5 36 12 PM" src="https://user-images.githubusercontent.com/34750871/167230790-fa3f5724-c99e-4d11-8190-7ccea216d8d7.png">

**Comment by krypton36** [comment]
This is an incorrect format. 0x23 is not a list. You will have to send the command as follows:
