### ISSUE TITLE
TE9 TC-DL-3.2 chip tool Darwin testing: Few attributes are not present to send

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18184]
Few attributes specified to be sent in Doorlock as per TC-DL-3.2 were not present. Support needed in chip tool Darwin to send these attributes. They were present in chip tool but not in chip tool Darwin. 

All the attributes specified in this link needs to be supported - https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/door_lock_Cluster.adoc#tc-dl-3-2-commands-dut-client

Below are the screenshots of the missing commands.

Chip tool Darwin supported send attributes,
<img width="726" alt="Screen Shot 2022-05-06 at 6 02 22 PM" src="https://user-images.githubusercontent.com/34750871/167231744-1cf42a3a-6b7d-4724-98cb-78e99d7faf80.png">

Chip tool supported send attributes,
<img width="714" alt="Screen Shot 2022-05-06 at 6 02 45 PM" src="https://user-images.githubusercontent.com/34750871/167231762-765550fb-4d43-47df-a451-48b4d58d7216.png">

**Comment by bzbarsky-apple** [comment]
Fixed in #18276
