### ISSUE TITLE
TE9 Groups Chip tool Darwin testing: Groupnames attribute not present to read

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18180]
As per the testcase TC-GR-3.1 step 2, Groupnames attribute needs to be present to read, but the attribute is not present in chip tool Darwin. This attribute is not present in chip tool either. 
<img width="1064" alt="Screen Shot 2022-05-06 at 5 26 41 PM" src="https://user-images.githubusercontent.com/34750871/167230469-96820f7b-7d3a-446d-b2c9-73588a853ad4.png">
<img width="771" alt="Screen Shot 2022-05-06 at 5 27 10 PM" src="https://user-images.githubusercontent.com/34750871/167230486-431d037a-2218-4de7-83ca-48639b1a36ed.png">

**Comment by dwgaul** [comment]
Actually it looks like this is an issue with the test plan that is being resolved here: https://github.com/CHIP-Specifications/chip-test-plans/pull/1279

Looking at the spec, Group Name is not an attribute, but is a data field used in the AddGroup, AddGroupIfIdentifying, and ViewGroupResponse commands.

**Comment by cjandhyala** [comment]
@Garik098 @dwgaul also I don't see the featureMap attribute in here ..

**Comment by Garik098** [comment]
Raised a ticket on test plan - https://github.com/CHIP-Specifications/chip-test-plans/issues/1301
