### ISSUE TITLE
TE9 TC-DL-3.1 chip tool Darwin testing: Few attributes are not present to read

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18183]
As per the steps in TC-DL-3.1, below attributes needs to be present to read through chip tool Darwin which were not present at the moment. 

door-open-events                                                             
door-closed-events                                                             
open-period          
number-of-log-records-supported
credential-rules-support                                                          |
enable-logging  
ledsettings  
default-configuration-register                                                    |
enable-local-programming  
enable-inside-status-led
local-programming-features 
send-pinover-the-air 
require-pinfor-remote-operation                                                   |
expiring-user-timeout                                                             |
 alarm-mask                                                                        |
 keypad-operation-event-mask                                                       |
remote-operation-event-mask                                                       |
manual-operation-event-mask                                                       |
rfidoperation-event-mask                                                          |
keypad-programming-event-mask                                                     |
remote-programming-event-mask                                                     |
 rfidprogramming-event-mask
feature-map

These were present in chip tool but not in chip tool Darwin. Need support for these attributes for this testcase.

Below is chip tool Darwin read attributes
<img width="730" alt="Screen Shot 2022-05-06 at 5 57 01 PM" src="https://user-images.githubusercontent.com/34750871/167231569-bad4e719-9162-4b62-beee-ef46156e12ef.png">

Below is chip tool read attributes
<img width="675" alt="Screen Shot 2022-05-06 at 5 57 42 PM" src="https://user-images.githubusercontent.com/34750871/167231594-7b46e64e-27bf-4ba4-bc7a-9a74f391435b.png">

**Comment by bzbarsky-apple** [comment]
Fixed in #18276
