### ISSUE TITLE
ReportDataMessage TLV tags used by SDK conflict with specification

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#18190]
### Problem

ReportDataMessage TLV tags used by SDK conflict with specification. See

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Encoding-Specification.adoc#encoding-ReportDataMessage

https://github.com/project-chip/connectedhomeip/blob/master/src/app/MessageDef/ReportDataMessage.h#L40

### Suggestion

Make SDK and specification match.

**Comment by bzbarsky-apple** [comment]
See https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/4730
