### ISSUE TITLE
[TC-MC-3.7]Application Launcher Cluster--Chip-tool needs to provide a way for TH to sends a LaunchApp command to DUT to launch an app which is not available and launch an app  when device is busy.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18201]
**#### Problem**
[TC-MC-3.7]Application Launcher Cluster--Chip-tool needs to provide a way for TH to sends a LaunchApp command to DUT to launch an app which is not available and launch an app when device is busy

Test-Plan screenshot
![image](https://user-images.githubusercontent.com/95841834/167380092-d2111598-3740-4718-94c1-c3ca9653a99b.png)

**Comment by chrisdecenzo** [comment]
I'm not sure we need a test case for every error code.

**Comment by chrisdecenzo** [comment]
Remove PICS_APPLAUNCHER_BUSY since it does not make sense to test every error code unless there are specific behavior requirements specified for it.
