### ISSUE TITLE
Attributes generated-command-list and accepted-command-list  must be implemented for chip tool darwin 

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18232]
The following attributes are implemented in chip tool, they need to be implemented for chip tool darwin
generated-command-list
accepted-command-list 

Attaching the screen shot;

<img width="764" alt="read attribute 1" src="https://user-images.githubusercontent.com/101904389/167520588-38433346-6018-4efc-8f5a-ce41f3fb8c96.png">

**Comment by bzbarsky-apple** [comment]
Done in #18276
