### ISSUE TITLE
Attributes: tolerance, scaled-value, min-scaled-value, max-scaled-value, scaled-tolerance, scale  must be implemented for chip tool darwin

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18234]
The following attributes are implemented in chip tool, they need to be implemented for chip tool darwin:

tolerance
scaled-value
min-scaled-value
max-scaled-value
scaled-tolerance
scale 

Attaching the screen shot;

<img width="763" alt="read attribute 3" src="https://user-images.githubusercontent.com/101904389/167521101-f7d1798b-3acb-4f4c-a4a7-758a61cf0914.png">

**Comment by bzbarsky-apple** [comment]
Done in #18276.
