### ISSUE TITLE
TE9 TC-LC-1.1 chip tool Darwin testing: Support needed for feature map, event list attributes

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18235]
As per the Label cluster testcase TC-LC-1.1, feature map and event list attributes needs to be present to read, which are missing in chip tool Darwin. Chip tool has feature map attribute but not event list. Sharing the screenshot for the same.
<img width="735" alt="Screen Shot 2022-05-09 at 5 55 55 PM" src="https://user-images.githubusercontent.com/34750871/167521593-06359364-9a4e-4f9e-b744-8dede27af33c.png">
.

**Comment by bzbarsky-apple** [comment]
Event list is https://github.com/project-chip/connectedhomeip/issues/15011

Feature map was fixed in #18276
