### ISSUE TITLE
[TC-LVL-1.1]Level Control cluster-AttributeList attribute missed to list the Mandatory OnLevel(0x0011) attribute.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18240]
**#### Problem**
[TC-LVL-1.1]Level Control cluster- As per Test-plan,  AttributeList attribute missed to list the Mandatory OnLevel(0x0011) attribute.

 *** expected behavior**:- TH should read mandatory attributes (values 0, 11, 15) from DUT
 *** actual behavior:**- TH missed to read Mandatory OnLevel(0x0011) attribute from DUT
 
*** steps to reproduce**:- ./chip-tool levelcontrol read attribute-list 1 1

***system configuration:-**
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 11587f5bf0bb9e621edd4c867c0bc942d804d1ce			
Dut:all-clusters-app

**Chip-tool screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/167572654-c72bb488-f618-4772-8ebb-b258541efb0d.png)

**Test-Plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/levelcontrol.adoc#tc-lvl-1-1-global-attributes-with-server-as-dut

Spec reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/LevelControl.adoc#ref_sec_3_10_3_1

**Comment by bzbarsky-apple** [comment]
The attribute is right there in the list:

> [10]: 17

The attribute's id ix 0x11, which is 17.

Test plan has been fixed since this issue was filed, and now says:

> should include the mandatory attributes (values 0, 17, 15)
