### ISSUE TITLE
Pressure Measurement cluster optional attribute showing status = 0x86 (UNSUPPORTED_ATTRIBUTE)

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#18243]
Summary:
[TC-PRS-1.1] as per testplan need to read optional attribute constraints checks when executed got status = 0x86 (UNSUPPORTED_ATTRIBUTE) response
Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/167583450-98046c1d-a47a-48d0-8167-4605f2744985.png)
Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/167583610-db9dbab2-7fe0-4bbf-8585-2daa7e82ba69.png)
Execution logs:
![image](https://user-images.githubusercontent.com/102359958/167583057-1d37e762-39fc-4c19-9ec0-8714b2b0a08b.png)
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/8659694/exe_log.txt)

**Comment by bzbarsky-apple** [comment]
@manjunath-grl That test plan says those tests are conditioned on some PICS checks (PICS_A_PRESSURE_SCALED_MAX, etc).  Are the tests in fact conditioned on those PICS checks?

**Comment by manjunath-grl** [comment]
> @manjunath-grl That test plan says those tests are conditioned on some PICS checks (PICS_A_PRESSURE_SCALED_MAX, etc). Are the tests in fact conditioned on those PICS checks?

I even tried with these PICS condition getting same output: (UNSUPPORTED_ATTRIBUTE)
![image](https://user-images.githubusercontent.com/102359958/168758701-841b9c02-e1e3-453d-8589-468889f7f75b.png)

**Comment by bzbarsky-apple** [comment]
@manjunath-grl `A_PRESSURE_SCALED` is not a defined PICS value for our YAML tests.

It sounds like we should define the PICS value, use it in the YAML, set it correctly for the test app if it does not implement this functionality yet.
