### ISSUE TITLE
[TE9] Failed to build TE9 test environment，Failed to connect device

### ISSUE THREAD

**Issue by DesiLuo** [project-chip/connectedhomeip#18250]
#### Problem
     After I built the TE9 test environment, the connection to the lighting-app device was always unsuccessful, and the error in the picture below appeared;
     my environment：
           Raspberry Pi image：https://www.dropbox.com/s/qd31hfsboa3mh4g/v_latest-2.img.zip?dl=0
           ot-br-posix commit ID f0bd216
           lighting-app：SHA: cfc35951be66a664a6efdadea56d1b8ea6e63e96
           rcp commit ID ec69725
           rcp board: silicon BRD4162A
           lighting board: silicon BRD4187A

![image](https://user-images.githubusercontent.com/87367022/167599375-ef98dac4-db49-4f4a-bd9b-18a84249b8d0.png)
![image](https://user-images.githubusercontent.com/87367022/167599496-d9a30cbd-c9f9-466c-ae57-bf4d9ac5ef77.png)

Please tell me, what am I doing wrong?

**Comment by cjandhyala** [comment]
@DesiLuo Could you re-test this on latest ToT
