### ISSUE TITLE
[TC-I-1.1]-AcceptedCommandList attribute Value Mismatch.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18251]
#### Problem
In Identify Cluster, testcase 1.1 [TC-I-1.1], the "AcceptedCommandList attribute" value must be mandatory attribute  **0x00, 0x01 and optional 0x40**, But the actual outcome is  **0x00, 0x01 and 0x64**. This needs to be fixed as per Test plan expected outcome.

 *** expected behavior**:- AcceptedCommandList: 3 entries that is 0x00, 0x01, 0x40

 *** actual behavior:-**
  [1652176238.707727][3784:3789] CHIP:TOO:   AcceptedCommandList: 3 entries
[1652176238.707772][3784:3789] CHIP:TOO:     [1]: 0
[1652176238.707809][3784:3789] CHIP:TOO:     [2]: 1
[1652176238.707846][3784:3789] CHIP:TOO:     [3]: 64

 * steps to reproduce:-  sudo ./chip-tool identify read accepted-command-list 1 1

***system configuration:-**
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/11587f5bf0bb9e621edd4c867c0bc942d804d1ce
Dut:all-clusters-app

**PFA screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/167604974-9b8c59fb-0126-4018-a2e4-eb4d67e6209f.png)

 **Test-plan refernce:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/identify.adoc#tc-i-1-1-global-attributes-with-server-as-dut

**Comment by bzbarsky-apple** [comment]
The output is decimal, not hex.  Decimal 64 is hex 0x40.

So everything is correct, as far as I can tell.
