### ISSUE TITLE
Attributes for thermostat read must be implemented for chip tool darwin 

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18269]
chip-tool has some thermostat read attributes which are missing from chip-tool-darwin

Attaching the screen shot;

<img width="1678" alt="read-3" src="https://user-images.githubusercontent.com/101904389/167698243-12957389-b58e-4a4b-9f33-ad290b7edefe.png">

**Comment by bzbarsky-apple** [comment]
Fixed in #18276
