### ISSUE TITLE
Test case to test the functionality of the Thermostat cluster client fails with (UNSUPPORTED_CLUSTER) error for chip-tool and chip-tool-darwin

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18275]
The test case has 3 steps;

1. To increase the temperature by SetpointRaiseLower command 
2. To Lower the temperature by SetpointRaiseLower command 
3. To issue GetRelayStatusLog command to the Test Harness

All the 3 steps fail with (UNSUPPORTED_CLUSTER) error for chip-tool and chip-tool-darwin.

**For chip-tool-darwin**

Command for 1st step (To increase the temperature by SetpointRaiseLower command ):
./chip-tool-darwin thermostat setpoint-raise-lower 0 1 1 0

Attaching the log;
[thermostat-low-chiptooldarwin.txt](https://github.com/project-chip/connectedhomeip/files/8664450/thermostat-low-chiptooldarwin.txt)

Command for 2nd step (To Lower the temperature by SetpointRaiseLower command ):
./chip-tool-darwin thermostat setpoint-raise-lower 0 1 1 1

Attaching the log;
[thermostat-raise-chiptooldarwin.txt](https://github.com/project-chip/connectedhomeip/files/8664459/thermostat-raise-chiptooldarwin.txt)

Command for 3rd step (To issue GetRelayStatusLog command to the Test Harness):
./chip-tool-darwin thermostat get-relay-status-log  1 0  

Attaching the log;
[get-relay-status-log.txt](https://github.com/project-chip/connectedhomeip/files/8664473/get-relay-status-log.txt)

**For chip-tool**

Command for 1st step (To increase the temperature by SetpointRaiseLower command ):
./chip-tool thermostat setpoint-raise-lower 0 1 1 0

Attaching the log;
[thermostat-low-chiptool.txt](https://github.com/project-chip/connectedhomeip/files/8664498/thermostat-low-chiptool.txt)

Command for 2nd step (To Lower the temperature by SetpointRaiseLower command ):
./chip-tool thermostat setpoint-raise-lower 0 1 1 1

Attaching the log;
[Uploading thermostat-raise-chiptool.txt…]()

Command for 3rd step (To issue GetRelayStatusLog command to the Test Harness):
./chip-tool thermostat get-relay-status-log  1 0  

Attaching the log;
[get-relay-status-log.txt](https://github.com/project-chip/connectedhomeip/files/8664497/get-relay-status-log.txt)

**Comment by bzbarsky-apple** [comment]
@phonnakasturi-apple That's using what server app?  all-clusters-app has no thermostat commands enabled, looks like.  Or are you using the thermostat app as the server?
