### ISSUE TITLE
[Provisioning Devices] General provisioning - Send Thread credentials to a device over IP

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1827]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by smides-nest** [comment]
This should have a "provisioning" label instead of "rendezvous" label. For some reason I can't edit.
