### ISSUE TITLE
FabricTable relies strongly on Serialize/Deserialize of the operational keypair

### ISSUE THREAD

**Issue by g-coppock** [project-chip/connectedhomeip#18279]
#### Problem

In `FabricTable`, the `SetOperationalKey` method makes a copy of the provided `P256Keypair` through `Serialize` / `Deserialize`. For implementations which cannot be serialized (i.e. a key which is delegated to a hardware keystore) this approach is insufficient

**Comment by tcarmelveilleux** [comment]
This has been resolved by the OperationalKeystore
