### ISSUE TITLE
Attributes for thermostat write must be implemented for chip tool darwin

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18270]
chip-tool has some thermostat read attributes which are missing from chip-tool-darwin

Attaching the screen shot;

<img width="1678" alt="read-4" src="https://user-images.githubusercontent.com/101904389/167698999-719482b7-1eba-4222-999e-7734875c7653.png">

**Comment by bzbarsky-apple** [comment]
Fixed in #18276
