### ISSUE TITLE
Remove dataVersion for reportAttribute in ReadInteraction.h

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#18288]
#### Problem
Assume it read one attribute path along with the matched data version filter, then it would get empty report, OnAttribute callback would not be called, onDone would be invoked. Further, inside ReadInteraction.h, currently there is no OnDone in struct ReportAttributeParams, so there is no callback to notify the application when application use ReadInteraction.h, application may be stuck there.

 #### Proposed Solution
Remove dataVersion for reportAttribute in ReadInteraction.h

**Comment by andy31415** [comment]
Fixed by #18825
