### ISSUE TITLE
[TE9][TC-DM-4.4]TC chip-tool command is not correct

### ISSUE THREAD

**Issue by wilbur-se** [project-chip/connectedhomeip#18296]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

step 1 and step2 use wrong chip-tool command

 #### Proposed Solution
<suggested fix, suggested enhancement>

using bellow command to test:
	#1 ./chip-tool networkcommissioning scan-networks  1 0 --Ssid null --Breadcrumb 0
	#2 ./chip-tool networkcommissioning scan-networks  1 0 --Ssid PDCN --Breadcrumb 0
also for #2, ssid need real ssid string or add "hex:" prefix

**Comment by bzbarsky-apple** [comment]
Doesn't sound like an SDK issue.  If this is a test plan issue, please file in https://github.com/CHIP-Specifications/chip-test-plans/issues
