### ISSUE TITLE
[Provisioning Devices] Access Control - ACL provisioning

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1829]
Setup ACL on accessories

**Comment by smides-nest** [comment]
This should have a "provisioning" label instead of "rendezvous" label. For some reason I can't edit.

**Comment by mlepage-google** [comment]
Hi what is an accessory? What does this issue mean? Is this about administrators making the ACLs on behalf of the devices on their fabric, so they can operate on their fabric? If so, this issue will have to be assigned to whoever is responsible for those administrators.

**Comment by andy31415** [comment]
I believe this was a catch-all bug per features, however specifically for ACL we have separate tracking at the moment and this bug is not needed. Closing.
