### ISSUE TITLE
Minimal MDNS functionality broken for Multi-Admin

### ISSUE THREAD

**Issue by doru91** [project-chip/connectedhomeip#18308]
#### Problem
* Multi-Admin doesn't work on NXP K32W0 platform if chip-tool is compiled with minimal MDNS (e.g.: `./scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool-app`) - second administrator commissioning is not successful and it fails at the operational discovery step. Because of this, Sigma1 message is not initiated from the chip-tool to the device;
* If chip tool is compiled with platform mdns (e.g.: `./scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool-app 'chip_mdns="platform"'`) then second administrator commissioning is successful.

 #### Proposed Solution
During TE8, chip-tool with minimal MDNS used to work so I did a git bisect to check when the functionality got broken: [here ](https://github.com/project-chip/connectedhomeip/commit/4d18b49d66a932b00652b20c08dd0d39a2e2f8d6) is the commit id. 

@cecille , any idea what could have happened?

What I did on my side was to analyze the traffic on the RPI and see the difference between chip-tool compiled with and without the above commit id (see the Wireshark captures NOT_OK_capture_rpi_during_second_admin.pcap / OK_capture_rpi_during_second_admin.pcap - [MDNS_captures.zip](https://github.com/project-chip/connectedhomeip/files/8668756/MDNS_captures.zip)). I am not an expert in mDNS but here is what it seems strange to me:

- OK capture: 
![image](https://user-images.githubusercontent.com/9597450/167820397-58282e24-bf16-4151-956b-1af3b473df5a.png)

1. packet 626 queries for matter._tcp
2. packet 628 is an answer for this query containing the IPV6 address of the device
3. packet 642 contains the Sigma1 message

- NOT OK capture:
![image](https://user-images.githubusercontent.com/9597450/167821694-af3e01f1-80a9-4aa9-910e-5c246d6c4dc9.png)
 
I still see the matter._tcp queries but the replies don't contain the IPv6 address of the device. No Sigma1 message can be seen in the captures.

Seems similar to https://github.com/project-chip/connectedhomeip/issues/18084

**Comment by andy31415** [comment]
@doru91 - does this still happen on ToT? #18256 should be fixed now by allowing recursive queries for IP addresses during both browse and operational discovery.
