### ISSUE TITLE
[TE9] FixedLabel cluster FeatureMap global attribute missing

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#18314]
#### Problem
<what's wrong or missing, please include any applicable:
* Tested with WindowCovering seems other example have the same problem
* The FeatureMap attribute is an available argument from chip-tool on Linux
 >

 #### Proposed Solution
Fix Code + Zap

**Comment by cjandhyala** [comment]
dup to #16725
