### ISSUE TITLE
[TE9][TC-OO-2.4] wrong TH implementation when DUT has to be rebooted

### ISSUE THREAD

**Issue by bauerschwan** [project-chip/connectedhomeip#18313]
In TC-OO-2.4 there are several test steps where the DUT should be rebooted. This is wrongly implemented in the TH. It tries to reboot the Raspi.

A better solution would be to ask the User to reboot the DUT instead.

**Comment by raju-apple** [comment]
Same as https://github.com/CHIP-Specifications/chip-test-scripts/issues/74
