### ISSUE TITLE
[TE9][TC-OO-1.1] TH behaves in the wrong way in step 3

### ISSUE THREAD

**Issue by bauerschwan** [project-chip/connectedhomeip#18312]
When TC-OO-1.1 gets performed with the Test Harness then it complaints at step 3 that the FeatureMap value should be 1.

This is obviously wrong because the value of FeatureMap is DUT-dependent and TH should not check against a hard value

**Comment by bzbarsky-apple** [comment]
@cjandhyala

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @cjandhyala to clarify what's needed here.
