### ISSUE TITLE
[TC-DGGEN-1.1] General Diagnostics--AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18322]
**Test-case ID** 
 [TC-DGGEN-1.1] Global attributes with server as DUT

**Problem:-**
As per Test-Plan, AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute

**expected behavior**:- TH should read mandatory attributes (values 0, 1, 8) from DUT
**actual behavior:**- TH missed to read Mandatory TestEventTriggersEnabled(8) attribute from DUT
**steps to reproduce:**-./chip-tool generaldiagnostics read attribute-list 1 0

**system configuration:-**
system configuration
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/25e241ebcbf11b1f63dbe25546b1f10219866ad0
Dut application: All-Clusters-app

**Chip-tool screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/167848758-d5325157-f0e5-4fc0-ad5d-dad0475de795.png)

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#tc-dggen-1-1-global-attributes-with-server-as-dut

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsGeneral.adoc

**Comment by woody-apple** [comment]
Assigning to @cjandhyala to follow up.

**Comment by andy31415** [comment]
Removed @cjandhyala - based on the comment from Vivien, this is a case of "attribute and command missing implementation". A developer can check and I imagine 2 paths:
  - if these are spec mandatory, we should implement
  - if these are spec optional, we will take the bug out of cert blocker as we do not implement optional at this time

**Comment by bzbarsky-apple** [comment]
@andy31415 This attribute and command are mandatory per spec.

**Comment by woody-apple** [comment]
Cert Blocker Review: Given this is a diagnostic cluster issue, assigning to @andy31415 for comment and assignment.

**Comment by jaehs6sam** [comment]
This TestEventTriggers command was recently introduced to the spec and its implementation will be manufacturer specific.  Its key and test mode values have to be pre-provisioned by a manufacturer to client and sever devices.  And this command will be used only during certification testing and to the certification candidate DUT only.  Again, testing mode value implementation & interpretation is upto the manufacturer (may not use PICS) such that it is difficult for a 3rd party to validate testing modes unless it is informed by the manufacturer a prior.  I personally think that this command should be optional and be post 1.0 implementation at this juncture.

**Comment by tcarmelveilleux** [comment]
Test event trigger will be used for OTA test plans

**Comment by tehampson** [comment]
https://github.com/project-chip/connectedhomeip/pull/18852
