### ISSUE TITLE
 Reset command fails in WiFi Diagnostics Cluster and Ethernet Network Diagnostics Cluster

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#18321]
**Issue** : Reset command fails in WiFi Diagnostics Cluster and Ethernet Network Diagnostics Cluster

**Commit used** : 11587f5bf0bb9e621edd4c867c0bc942d804d1ce			

**Expected behavior** : status = 0x00 (SUCCESS),

**Actual behavior** : status = 0x01 (FAILURE)

**Steps to reproduce** :

- DUT side :

1. sudo rm -rf /tmp/chip_*
2. sudo ./chip-all-clusters-app 

- TH side :

1. ./chip-tool pairing ethernet 1 20202021  3840  fe80::e65f:1ff:fe0f:3baf  5540
2. ./chip-tool ethernetnetworkdiagnostics reset-counts 1 0
3. ./chip-tool wifinetworkdiagnostics reset-counts 1 0

**Test platform** :
Chip-tool - RPI/MAC
DUT - RPI

**PFA Logs** : 
[reset_dut.txt](https://github.com/project-chip/connectedhomeip/files/8669697/reset_dut.txt)
[reset_cntrl.txt](https://github.com/project-chip/connectedhomeip/files/8669698/reset_cntrl.txt)

**Comment by bzbarsky-apple** [comment]
This command's implementation tries to set the attributes in the in-memory attr store, but they don't live there (they're in the `DiagnosticDataProvider`, so that fails).  @yufengwangca

**Comment by bzbarsky-apple** [comment]
That said, even with this fixed this will fail on platforms where there is no diagnostics data provider (i.e. not Linux).
