### ISSUE TITLE
 [TC-DGGEN-1.1] General Diagnostics--FeatureMap returns status code as 0x86 Error(unsupported attribute) Response

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18324]
#### Problem
Though the feature map attribute is implemented in  General Diagnostics
cluster it throws an error code as 0x86(unsupported attribute).
 
**expected behavior**:-FeatureMap attribute  should be empty.
 **actual behavior**:-0x86 Error(unsupported attribute)
 **steps to reproduce**:-./chip-tool generaldiagnostics read  feature-map 1 0
 **system configuration:-**
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 11587f5
Dut:all-clusters-app

**PFA screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/167851773-ce527d43-879b-44f1-80e9-402ef7da2933.png)

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#tc-dggen-1-1-global-attributes-with-server-as-dut

**Comment by vivien-apple** [comment]
Did a PR (#18554)
