### ISSUE TITLE
Operational Discovery fails for the OTA Provider

### ISSUE THREAD

**Issue by doru91** [project-chip/connectedhomeip#18332]
#### Problem
* operational discovery of the OTA Provider fails on the OTA Requestor side if RPI Device has active both Ethernet and Wi-Fi interfaces (if only the Wi-Fi interface is active then then the discovery works)
* tested using NXP K32W0 with TE9 topology (RPI4 OS image, chip-tool compiled with platform mDNS)

 #### Proposed solution
- RPI has both Wi-Fi and Ethernet interfaces active (see the captures NOT_OK_Announce/NOT_OK_Capture_Announce - first capture is for air traffic, the second one is for RPi traffic, 192.168.0.103 - Wi-Fi, 192.168.1.102 - Ethernet)
![image](https://user-images.githubusercontent.com/9597450/167879265-197559e0-f887-49af-bfea-a3f9a89c8348.png)

1. Packet 732 contains the matter._tcp query initiated by the OTA Provider
2. Packet 741 contains the reply but it lacks the IPv6 address of the OTA Provider

Also, the RPi traffic doesn't look good:
![image](https://user-images.githubusercontent.com/9597450/167880266-c88dce4f-54d9-4a14-85c5-b03bc8b85b41.png)

- RPi has only the Wi-Fi interface active (see the captures OK_Announce/OK_Capture_Announce - first capture is for air traffic, the second one is for RPi traffic)
![image](https://user-images.githubusercontent.com/9597450/167883177-fdb76c76-76f8-4d35-ba79-76f012acac4a.png)
1. Packet 281contains the matter._tcp query initiated by the OTA Provider
2. Packet 287 contains the reply and it also contains the IPv6 address of the OTA Provider
[MDNS_captures.zip](https://github.com/project-chip/connectedhomeip/files/8671113/MDNS_captures.zip)

**Comment by andy31415** [comment]
I only see SRV queries over the wire. I expect minmdns to reply with just the SRV entry in this case and it would not attach A/AAAA or TXT entries to it. 

What client side library is used here? I would expect a query for SRV to also be followed by AAAA and TXT if using some 3rd party mdns library. If using minmdns, we should always query for 'ANY'

**Comment by andy31415** [comment]
Is the issue that nobody replies to SRV queries even though they seem valid?

**Comment by tcarmelveilleux** [comment]
> I only see SRV queries over the wire. I expect minmdns to reply with just the SRV entry in this case and it would not attach A/AAAA or TXT entries to it.

No, according to DNS-SD RFC, AAAA at least are needed:
```
https://datatracker.ietf.org/doc/html/rfc6763#section-12.2
```

Also note that https://datatracker.ietf.org/doc/html/rfc6763#section-12 says:


>    This section recommends which additional records SHOULD be generated
>    to improve network efficiency, for both Unicast and Multicast DNS-SD
>    responses.
> 
>    Note that while **servers SHOULD add these additional records** for
>    efficiency purposes, as with all DNS additional records, it is the
>    client's responsibility to determine whether or not to trust them.
> 
>    Generally speaking, stub resolvers that talk to a single recursive
>    name server for all their queries will trust all records they receive
>    from that recursive name server (whom else would they ask?).
>    Recursive name servers that talk to multiple authoritative name
>    servers should verify that any records they receive from a given
>    authoritative name server are "in bailiwick" for that server, and
>    ignore them if not.
> 
>    **Clients MUST be capable of functioning correctly with DNS servers
>    (and Multicast DNS Responders) that fail to generate these additional
>    records automatically, by issuing subsequent queries for any further
>    record(s) they require.**  The additional-record generation rules in
>    this section are RECOMMENDED for improving network efficiency, but
>    are not required for correctness.

**Comment by woody-apple** [comment]
Spec Review: @doru91 any update on this? Is this still happening? We may need help digging in if so.

**Comment by woody-apple** [comment]
Spec Review: Per @andy31415 there have been changes in min-mDNS can you please re-test this?

**Comment by woody-apple** [comment]
Closing this given this has had enough time to re-test. @doru91 can you please re-open if this is still happening?
