### ISSUE TITLE
[Provisioning Devices] Provision over Bluetooth - Broadcast BT Beacon

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1833]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Done
