### ISSUE TITLE
[TE9][TC-GC-1.1] WindowCovering example: GeneralCommissioning cluster out-of-sync

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#18333]
#### Problem

Located in the WindowCovering example might be present elsewhere

<what's wrong or missing, please include any applicable:
 * FeatureMap is preset at 6 and should be 0
 * SupportsConcurrentConnection not present
 * SetRegulatoryConfigResponse not present
 >

 #### Proposed Solution
Need a patch in ZAP for alignement with the latest spec

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @jmeg-sfy to resolve.

**Comment by woody-apple** [comment]
Cert Blocker/SDK Spec Review: Given this does not affect reference certification which uses the all-cluster-app, removing "cert blocker"
