### ISSUE TITLE
[TC-PS-2.1] Following attributes are giving unsupported attribute response

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#18357]
Following attributes are giving failure response:
1.WiredAssessedInputVoltage
2.WiredAssessedInputFrequency
3.WiredCurrentType
4.WiredAssessedCurrent
5.WiredNominalVoltage
6.WiredMaximumCurrent
7.WiredPresent
8.ActiveWiredFaults
9.BatReplacementNeeded
10.BatReplaceability
11.BatPresent
12.BatReplacementDescription
13.BatCommonDesignation
14.BatANSIDesignation
15.BatIECDesignation
16.BatApprovedChemistry
17.BatCapacity
18.BatQuantity
19.BatTimeToFullCharge
20.BatFunctionalWhileCharging
21.BatChargingCurrent
22.ActiveBatChargeFaults

Testplan screenshot:
![2022-05-10_22-33](https://user-images.githubusercontent.com/57476670/167982431-2a8d46fb-c37b-40e8-82d5-4a1c4dda7b44.png)
[PS-2.zip](https://github.com/project-chip/connectedhomeip/files/8674665/PS-2.zip)

**Comment by jmeg-sfy** [comment]
Same problem on Window covering demo
