### ISSUE TITLE
[TC-GC-2.4] While verifying SetRegulatoryConfig command DUT responds as debugText as a integer instead 'string' value.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18362]
**#### Problem**
While verifying SetRegulatoryConfig command DUT responds as debugText as a integer value as 12 instead 'string' value.

 *** expected behavior**:- DebugText should be 'string' value
 *** actual behavior**:- debugText  integer 12 value.
 *** steps to reproduce**:-./chip-tool generalcommissioning set-regulatory-config 4 12 0 1 0

**system configuration:-**
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/11587f5bf0bb9e621edd4c867c0bc942d804d1ce
Dut:all-clusters-app

**PFA screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/168018311-1d755329-0f4d-41c2-b00d-991883453906.png)

**Test-plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/General_Commissioning.adoc#tc-gc-2-4-verification-for-commissioningerror-on-response-message-dut-commissionee

**Spec screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/168018532-08b163c2-ff38-4aa8-a53f-04e9dd796da3.png)

**Comment by Rajashreekalmane** [comment]
[TC-GC-2.4]--While verifying  CommissioningComplete command  DUT responds as debugText as empty instead 'string' value.

PFA screenshot:-
![image](https://user-images.githubusercontent.com/95841834/168020526-3edb0966-4d7f-436b-aa59-3ec9a803f5c1.png)

**Comment by andy31415** [comment]
@Rajashreekalmane could you explain the test case a bit? I look at the send and redceive data, you send 12 and receive 12. Actual formatting of the logs may not contain quotes.

Could you send debug text that is clearly text like `xy` and see if that goes through?
