### ISSUE TITLE
IP Commissioning is failing in latest commit using tv-app (example app)

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18369]
**Issue**
IP Commissioning is failing in latest commit using tv-app (example app)

**Expected behavior** We have to get successful commissioning on TH Log 

**Actual behavior**:-[1652351037.856043][10544:10549] CHIP:SC: PASESession timed out while waiting for a response from the peer. Expected message type was 33
[1652351037.856169][10544:10549] CHIP:TOO: Secure Pairing Failed
[1652351037.856292][10544:10549] CHIP:TOO: Pairing Failure: 
 
**Steps to reproduce** 

- DUT side

1. sudo rm -rf  /tmp/chip_*
2. ./chip-tv-app

- TH side:-

1. sudo rm -rf  /tmp/chip_*
2. ./chip-tool pairing ethernet 1 20202021 3840 fe80::e65f:1ff:fe30:e67f  5540

**System configuration :** 
DUT - RPI
Chip-tool - RPI
Commit Id:-588d4c90fb68ffafdee536172ee46fe4c2294f54
Platform : IP

**PFA log below:-**
[TV-app ethernet pairing issue.txt](https://github.com/project-chip/connectedhomeip/files/8678607/TV-app.ethernet.pairing.issue.txt)

**Comment by chrisdecenzo** [comment]
we changed the default port for tv-app from 5540 to 5640 so you need to either modify your chip-tool command:

chip-tool pairing ethernet 1234 20202021 3840 127.0.0.1 5640

or

chip-tool pairing onnetwork-long 1234 20202021 3840
