### ISSUE TITLE
[TE9][TC-GR-2.2] Command GetGroupMemberShip not functional w/ chip-tool

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#18373]
#### Problem
<what's wrong or missing, please include any applicable:
 * The chip tool command below is not working as expected
 * /chip-tool groups get-group-membership 0x0087 4253 1

  and we obtain CHIP:TOO: Error while encoding GroupList as an array.
 >

**Comment by bzbarsky-apple** [comment]
That's passing a number for an argument that expects an array.

This syntax should work:
```
chip-tool groups get-group-membership "[135]" 4253 1
```

(Note that the array entries need to be decimal.)
