### ISSUE TITLE
[TC_DL_2.5,2.6,2.10] few Doorlock cluster commands and attributes are missing in yaml

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#18391]
Following attribute and command  missing In the Door lock cluster:

Attribute :
NumberOfLogRecordsSupported

Commands:
GetLogRecord
SetPINCode
SetUserType
GetUserType

![2-5](https://user-images.githubusercontent.com/57476670/168130748-98edf88c-e64e-4280-b024-23853648c1e4.png)
![2-5--](https://user-images.githubusercontent.com/57476670/168130756-ec379da7-73a5-4a43-868d-238ff3be4848.png)
![2 6](https://user-images.githubusercontent.com/57476670/168132835-2a85c6b6-0368-4c10-ba94-6fae7d639973.png)
![2-10](https://user-images.githubusercontent.com/57476670/168132871-5d56bf99-ae17-4369-a6e1-1b4cae4075d9.png)

Testpaln  screenshot:
![testplan-2 5](https://user-images.githubusercontent.com/57476670/168130821-26bd5182-66d7-4575-ab3c-216858f527a4.png)
![testplan-2 6](https://user-images.githubusercontent.com/57476670/168133000-40f80a8b-768f-4eb6-b430-8cc75f251e7f.png)
![testplan-2 10](https://user-images.githubusercontent.com/57476670/168133028-cde30a63-975b-4f70-8581-7e1e9ea519dd.png)

[DL-2-5.zip](https://github.com/project-chip/connectedhomeip/files/8681298/DL-2-5.zip)
[DL-2-5--.zip](https://github.com/project-chip/connectedhomeip/files/8681299/DL-2-5--.zip)
[DL-2-10.zip](https://github.com/project-chip/connectedhomeip/files/8681355/DL-2-10.zip)
[DL-2.zip](https://github.com/project-chip/connectedhomeip/files/8681357/DL-2.zip)

**Comment by bzbarsky-apple** [comment]
> SetPINCode
> SetUserType
> GetUserType

These are not part of Matter, so they are expected to not be supported by any Mater tooling or Matter devices.

>  NumberOfLogRecordsSupported
>  GetLogRecord

These should work in YAML on tip.  @kowsisoundhar12 can you retest, please?
