### ISSUE TITLE
[TC-DL-2.9] SetHolidaySchedule Command showing (0x81 UNSUPPORTED_COMMAND) failure response

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#18393]
SetHolidaySchedule Command is giving unsupported command 0x81  failure while running this testscript  

![DL-2-9](https://user-images.githubusercontent.com/57476670/168134526-edc10b1a-ad91-4646-b5d8-805319d8ae2c.png)

Testplan screenshot:
![2-9](https://user-images.githubusercontent.com/57476670/168134785-d45653ec-7c51-43c2-a78a-0edc6ac6277c.png)
[dl-2-9.zip](https://github.com/project-chip/connectedhomeip/files/8681394/dl-2-9.zip)

**Comment by cjandhyala** [comment]
@kowsisoundhar12 is SCH feature bit set in the reference app ?

**Comment by kowsisoundhar12** [comment]
this issue has been resolved ,hence closing this issue
