### ISSUE TITLE
BindingManager invalidates CASE sessions when it shouldn't

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#18436]
#### Problem

In:
```
void BindingManager::FabricRemoved(CompressedFabricId compressedFabricId, FabricIndex fabricIndex)
{
    mPendingNotificationMap.RemoveAllEntriesForFabric(fabricIndex);
    mInitParams.mCASESessionManager->ReleaseSessionsForFabric(compressedFabricId);
}
```

This invalidates session from a place where this should not be done. The behavior of fabric removal in NOC cluster should suffice, and propagate the necessary session eviction.

 #### Proposed Solution

- Remove `ReleaseSessionsForFabric` from `BindingManager`

**Comment by andy31415** [comment]
V1 review: @mrjerryjohns and @tehampson to review and provide justification if this needs to be a v1.0 blocker.

**Comment by mrjerryjohns** [comment]
Given the recent changes that @tehampson made to pivot `OperationalSessionSetup` to now just be relevant during CASE establishment only, this isn't a P0 anymore.

When a fabric is removed, two things happen:
1. `CleanupSessionsForFabric` is called, which will expire all sessions in the `SessionManager` for that fabric.
2. `CASESession::OnFabricRemoved` will get called, which will terminate any pending session establishment and as a result, terminate any open `OperationalSessionSetup` instances as well. Consequently, the call to `ReleaseSessionsForFabric` in BindingManager is just redundant.

**Comment by andy31415** [comment]
Decreased blocking status based on comment from @mrjerryjohns above (Jerry added the p1 flag oringally)

**Comment by mrjerryjohns** [comment]
Taking off p1 label.
