### ISSUE TITLE
Cannot provide externally obtained NOC and externally managed key pair to Darwin framework on controller init

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#18444]
#### Problem
When managing your own fabric for multi-fabric use-cases on iOS, there is currently no API that allows providing an NOC for a controller, and associated key pair protocol implementation.

This has the following side-effects:

- Clients have to provide the root CA key **pair** (including private key) and let the framework decide of NOC issuance for the local controller, which is impossible if the key pair resides outside the app calling the framework (e.g. a cloud-based CA). 
- There is no way to provide a Keychain-based or other secured non-native version of the implementation of the operational key used during CASE, to safeguard access to the private key bits, which increases attack surface to operational keys that may underpins administrator controller applications in a fabric.

 #### Proposed Solution

- Allow providing an optional already-generated NOC and associated keypair if the issuance of controller NOCs is delegated to outside the framework
- Allow the P256Keypair* in the fabric table to be backed by a bridge to externally provided crypto implementation with the following minimal API which suffices for both initiator and responder roles in CASE:
  - GetPublicKey()
  - SignMessage()
  - ECDHDeriveSecret()

**Comment by bzbarsky-apple** [comment]
> ECDHDeriveSecret()

As discussed today, this is not needed, because secrets are derived from ephemeral keys during CASE; the operational key is only used to sign things.

The rest can be done once https://github.com/project-chip/connectedhomeip/pull/18482 merges.
