### ISSUE TITLE
Cannot override DeviceAttestationVerifier in Darwin commissioning flow

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#18445]
#### Problem
The API surface for Darwin commissioning flows prevents passing a Device Attestation Verifier equivalent that would allow arbitrary policy checks, and allow aggregation/saving of the DAC cert chain and attestation elements/signature, which are needed to do an end-to-end attestation flow if the CA resides off the device (e.g. if running a custom fabric in a multi-fabric situation with app on iOS with Matter framework). Similarly, this prevents having rules that simplify the usage/trust of development device attesattion credentials in a given fabric, where additional rules or validations may be needed.

 #### Proposed Solution

- Allow providing a protocol implementation that is equivalent to `DeviceAttestationVerifier::VerifyAttestationInformation` API surface, if the default policy is insufficient.

**Comment by bzbarsky-apple** [comment]
@anush-apple @woody-apple FYI.

**Comment by terafin** [comment]
@tcarmelveilleux Can you provide a minimum example API that would fit the needs here?

**Comment by woody-apple** [comment]
@tcarmelveilleux Can you provide an example API that would fit the needs here?

**Comment by woody-apple** [comment]
@tcarmelveilleux Anything remaining here that's needed? If so, we can move back into 1.0.

**Comment by woody-apple** [comment]
@tcarmelveilleux I believe the API needed is now complete, and working, correct? Please re-open if needed.
