### ISSUE TITLE
[TE9] I'm getting status 9 instead of 5 on step 6 in [TC-MF-1.23] / [TC-MF-1.24]

### ISSUE THREAD

**Issue by cabin15** [project-chip/connectedhomeip#18476]
#### Problem
Controller: My DUT
Controlee: all-clusters-app of test Harness image on rpi4

On step 6 in [TC-MF-1.23] and [TC-MF-1.24], I'm getting status 9 instead of 5.

Expected result
`[1649756670.402192][10794:10799] CHIP:CTL: Device returned status 5 on receiving the NOC
[1649756670.402221][10794:10799] CHIP:CTL: Add NOC failed with error ../../third_party/connectedhomeip/src/controller/CHIPDeviceController.cpp:1110: CHIP Error 0x0000000B: No memory
`
Actual result
`[1652319250.706064][2608:2613] CHIP:CTL: Device returned status 9 on receiving the NOC
[1652319250.706099][2608:2613] CHIP:CTL: Add NOC failed with error ../../src/controller/CHIPDeviceController.cpp:1204: CHIP Error 0x0000007E: Trying to add a NOC for a fabric that already exists`

[TE9-TC-MF-1.23.txt](https://github.com/project-chip/connectedhomeip/files/8700979/TE9-TC-MF-1.23.txt)
[TE9-TC-MF-1.24.txt](https://github.com/project-chip/connectedhomeip/files/8700980/TE9-TC-MF-1.24.txt)

Observation:
It is reproduced same with using chip-tool on test harness.

**Comment by bzbarsky-apple** [comment]
The `chip-tool` commands in the log (for TC-MF-1.23) look like this:
```
chip-tool pairing ethernet 12341234 50582328 3840 fe80::870:daaf:910d:24ba 5540
chip-tool pairing ethernet 34563456 65185905 3840 fe80::870:daaf:910d:24ba 5540
```
Those are in fact trying to commission the device into the same fabric.  To use different fabrics, see the `--commissioner-name` argument to `chip-tool`.

Given those commands, the "Trying to add a NOC for a fabric that already exists" response is correct.
