### ISSUE TITLE
Reject subscription establishment if subscriber has no access

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#18485]
#### Problem

See [this](https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/5219) spec issue.

 #### Proposed Solution

Iterate over every expanded path in the `SubscribeRequest` and check if any of the paths have at least `View` privilege (this is already handled by calling `RequiredPrivilege::ForReadAttribute(aPath)`). If not a single path has that privilege, the subscription should not be established.

This processing should happen BEFORE we allocate a ReadHandler to serve the subscription. This ensures we don't tear down existing valid subscriptions to serve a subscription that is not valid.

**Comment by woody-apple** [comment]
Cert Blocker Review: @CamWms @bzbarsky-apple @mrjerryjohns - Can we confirm if the current spec, SDK, and test plans are currently in sync. If so, we should move this to post 1.0.

**Comment by andy31415** [comment]
V1 reivew: PR existed, needs reviving. Since this is a spec issue, it will be accepted in 1.0

**Comment by mrjerryjohns** [comment]
@yunhanw-google to resurrect the PR that I had open previously, and ensure the relevant changes are made to that PR to ensure it is spec compliant.
