### ISSUE TITLE
[New Cluster] IAS WD

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1849]
IAS Zones are not implemented, need to decide what we're doing here, and implement/defer

**Comment by bzbarsky-apple** [comment]
I'm not sure there's much to do here other than porting the command dispatch from Simplicity Studio to Zap.  In particular, the commands in this cluster have no non-custom logic other than parsing out the command arguments.  Command dispatch does that, then calls `emberAfIasWdClusterStartWarningCallback` or `emberAfIasWdClusterSquawkCallback` depending on the command, and those callbacks need to be implemented by the device vendor afaict.

I guess we could have a CHIP impl of those and put some other API on top for device vendors; we need to decide on such an API first.
