### ISSUE TITLE
[TE9] Get INVALID_ACTION of read-by-id command on IDM-2.1

### ISSUE THREAD

**Issue by cabin15** [project-chip/connectedhomeip#18497]
#### Problem
Controller: My DUT
Controlee: all-clusters-app of test Harness image on rpi4

When testing read-by-id command of any cluster from all-clusters-app, my DUT got INVALID_ACTION return.

Belows are the step that failed due to UNSUPPORTED_COMMAND.
- Step 18, 22

Expected result
0x00 Success should be returned.

Actual result
May 09 18:18:24 raspberrypi4 chip-tool[2274]: StatusResponseMessage =
May 09 18:18:24 raspberrypi4 chip-tool[2274]: {
May 09 18:18:24 raspberrypi4 chip-tool[2274]:         Status = 0x80 (INVALID_ACTION),
May 09 18:18:24 raspberrypi4 chip-tool[2274]:         InteractionModelRevision = 1
May 09 18:18:24 raspberrypi4 chip-tool[2274]: }

[TE9-TC-IDM-2.1.txt](https://github.com/project-chip/connectedhomeip/files/8704437/TE9-TC-IDM-2.1.txt)

**Comment by bzbarsky-apple** [comment]
The controller sent a message with a wildcard read for "wildcard endpoints, wildcard clusters, attribute 0".

Per "8.9.2.3. Valid Read Attribute Paths" in the spec, a read path for a specific attribute id and wildcard cluster is only allowed if the attribute id is for a global attribute (i.e. one applicable to all clusters).  For example, reading attribute `0xFFFD` (ClusterRevision) is allowed.  But 0 is not a global attribute id, so the server correctly responds with INVALID_ACTION.
