### ISSUE TITLE
[Darwin] Open Commissioning Window APIs need to be async

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#18527]
#### Problem
The current `openPairingWindow` and `openPairingWindowWithPIN` APIs exposed to Darwin clients are not really usable. 
These APIs are synchronous and will always succeed. 

For example, repeated calls to `openPairingWindowWithPIN`  _appear_ to work whereas the server cannot honor these until the previous duration has expired and so it returns an error. That error is never returned to the Darwin client. 

 #### Proposed Solution
We should make these async since they represent a remote request on the server

**Comment by bzbarsky-apple** [comment]
The changes for https://github.com/project-chip/connectedhomeip/issues/22420 will likely fix this.
