### ISSUE TITLE
EFR32MG24 lighting-app does not work

### ISSUE THREAD

**Issue by cjszz2001** [project-chip/connectedhomeip#18522]
#### Problem
EFR32MG24 lighting-app does not work.
Build the lighting-app on the EFR32_BOARD=BRD4186A
on the branch of interop_testing_te9
Flash the hex file to the development board. It does not even startup

Proposed Solution
the light example should work

**Comment by andy31415** [comment]
In #18520 I tested the latest light app flash and it booted.

I assume this may be a problem in the old branch interop_testing_te9, however we are not maintaining old branches at this point.
