### ISSUE TITLE
[TE9][TC-SC-5.1] Lock-app is failing on step 2 (./chip-tool groupkeymanagement key-set-write)

### ISSUE THREAD

**Issue by epeng100** [project-chip/connectedhomeip#18532]
In [TC-SC-5.1] Step 2,
./chip-tool groupkeymanagement key-set-write '{"groupKeySetID": 42,
"groupKeySecurityPolicy": 0, "epochKey0":
"d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 2220000,"epochKey1":
"d1d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime1": 2220001,"epochKey2":
"d2d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime2": 2220002 }' 1 0

The result shows UNSUPPORTED_CLUSTER for lock-app.

Checking examples/lock-app/lock-common/lock-app.zap, there is no "Group Key Management" cluster as other applications.
If the test is mandatory for all type devices, lock-app should support the cluster.

**Comment by cjandhyala** [comment]
@epeng100 is there a reason why you need to run this TC on lock app?

**Comment by epeng100** [comment]
No, we tested it because the case is in TEDS list for lock app.

**Comment by bzbarsky-apple** [comment]
This cluster is mandatory for all devices.

That said, devices are allowed to support only one keyset per fabric (for the IPK) if they don't implement the Groups cluster.  And locks are absolutely allowed (and in fact strongly encouraged not to) implement the Groups cluster.  So doing that keyset write is absolutely allowed to fail for a lock, just not with UNSUPPORTED_CLUSTER.

**Comment by woody-apple** [comment]
Spec Issue Review: Sankar to confirm that this test case is indeed running and passing.

**Comment by sankarselvam** [comment]
@woody-apple  This test is not passing in QA. This test has been linked to the testplan issue  [1453](https://github.com/CHIP-Specifications/chip-test-plans/issues/1453)  
Test plan requires an update as well.

**Comment by Morozov-5F** [comment]
> > does that mean we should enable the groups-cluster in the lock-app and configure it properly?
> 
> 
> 
> Group key management, not groups.

Yep, sorry, I meant exactly that, thanks
