### ISSUE TITLE
Thermostat cluster "SetpointRaiseLower" command shwoing status = 0xc3 (UNSUPPORTED_CLUSTER)

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#18545]
Summary:
[TSTAT-2.2] Thermostat cluster  "SetpointRaiseLower" command shwoing status = 0xc3 (UNSUPPORTED_CLUSTER) when executed 
Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/168986853-24f8a967-8c0b-4e8e-86e2-6dca18b66426.png)
Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/168987080-f7599b8c-5c3b-44ee-9296-6498c17631d8.png)
Execution logs:
[setRaisePoint.txt](https://github.com/project-chip/connectedhomeip/files/8714260/setRaisePoint.txt)
![TSTAT_SetpointRaiseLower](https://user-images.githubusercontent.com/102359958/168987152-10e8cb03-7dd4-4981-8e67-0a467eeee7ea.png)

**Comment by bzbarsky-apple** [comment]
This command is not enabled in all-clusters-app, looks like.

**Comment by woody-apple** [comment]
SDK Spec Review: Tagging this as a potential cert blocker, tagging @cjandhyala

**Comment by cjandhyala** [comment]
closing per @manjunath-grl request

**Comment by cjandhyala** [comment]
@manjunath-grl per QA team you need to run this test using the thermostat app.

**Comment by manjunath-grl** [comment]
@cjandhyala  tried in TOT its passing
    SHA used: https://github.com/project-chip/connectedhomeip/commit/c1e1d018820c0fdd51f124f607b9207f31fae2ff
    Client app: Chip-tool
    Server app: thermostat app
Execution logs:
[TC_TSTAT_2_2.zip](https://github.com/project-chip/connectedhomeip/files/8906488/TC_TSTAT_2_2.zip)
