### ISSUE TITLE
[TC-TSTAT-2.2] Write for Thermostat cluster command above max and below min value returns Sucess Response

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#18544]
Summary:
As per the Test-plan the test Step tells we have use write command to write the below min and above max value it should return the error CONSTRAINT_ERROR (0x87)
but when we execute the YAML script it returned with status: Success (0x0000)
Attributes : OCCUPIEDCOOLINGSETPOINT , OCCUPIEDHEATINGSETPOINT , MINHEATSETPOINTLIMIT , MAXHEATSETPOINTLIMIT , MINCOOLSETPOINTLIMIT ,MAXCOOLSETPOINTLIMIT
same goes for step 3b,4b, 5b, 6b, 7b
Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/168982382-aa40995d-0c1f-4591-9303-7797e2fef04d.png)
![image](https://user-images.githubusercontent.com/102359958/168982435-1caf414c-8125-4994-bd49-c4fd0942db44.png)
Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/168982083-022a0533-178d-4db2-a5d2-3a24f7ab5f17.png)
Execution logs and screenshot:
![OccupiedCoolingSetPoint](https://user-images.githubusercontent.com/102359958/168982544-c8cc7e57-22d3-4a44-8b66-0ac9287a14ee.png)
[Occupiedoolsetpoint.txt](https://github.com/project-chip/connectedhomeip/files/8714095/Occupiedoolsetpoint.txt)
![UnoccupiedHeatingSetpoint](https://user-images.githubusercontent.com/102359958/168982563-58faeb41-7422-4b27-8e21-2577c7db2cf2.png)
[UnoccupiedHeatingSP.txt](https://github.com/project-chip/connectedhomeip/files/8714098/UnoccupiedHeatingSP.txt)

**Comment by bzbarsky-apple** [comment]
`MatterThermostatClusterServerPreAttributeChangedCallback`, which is supposed to enforce this, is not being called.
