### ISSUE TITLE
[TC-DL-2.12&TC-DL-2.16] Following commands are missing in Door lock cluster

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#18595]
Following commands are missing in door lock cluster
GetUserStatus
SetRFIDCode
GetRFIDCode

![error-screenshot](https://user-images.githubusercontent.com/57476670/169217268-d82452f0-6191-40e7-8e8a-e009531fca47.png)
![error-screenshot](https://user-images.githubusercontent.com/57476670/169217289-a8ca966e-0ad6-4cbb-8412-9c23f4b50353.png)
[execution-logs.zip](https://github.com/project-chip/connectedhomeip/files/8725323/execution-logs.zip)
[exe-logs.zip](https://github.com/project-chip/connectedhomeip/files/8725324/exe-logs.zip)

**Comment by bzbarsky-apple** [comment]
In the device library the USR feature is _required_ for Matter, and therefore these commands are _required_ to not be supported in a Matter device.

**Comment by bzbarsky-apple** [comment]
As in, those commands are not part of Matter at all.  They're in the cluster definition, but Zigbee-only.
