### ISSUE TITLE
chip-tool should store persistent data in a configurable location so it can outlive OS reboot

### ISSUE THREAD

**Issue by Leo2442926161** [project-chip/connectedhomeip#18592]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 commissioner and commissionee are able to interaction with each other everytime since paired.

 * actual behavior
 it lost connection when I restarted ubuntu, I have using "sudo ./chip-tool pairing ble-thread" to pair it again for establish a connection.

 * steps to reproduce
 just reboot ubuntu in VMware.

 * system configuration
 ubuntu 20.04

**Comment by bzbarsky-apple** [comment]
@Leo2442926161 Did you pass `--KVS` arguments to the relevant applications so that their persistent storage files would go somewhere that's not `/tmp`?  Because if not, then an OS restart would clear `/tmp` and hence delete the storage, so the "I am commissioned" information would be lost.

**Comment by Leo2442926161** [comment]
Hi bzbarsky, thanks for your help.

how to add --KVS arguments to relevant applications?

**Comment by bzbarsky-apple** [comment]
You just do it:
```
chip-all-clusters-app  --KVS /home/whatever/something
```

**Comment by Leo2442926161** [comment]
Hi bzbarsky, thanks again,

I am using chiptool, there no --KVS parameter

**Comment by bzbarsky-apple** [comment]
@Leo2442926161 When you say "I restarted ubuntu", is the thing running on ubuntu chip-tool or the server side?

**Comment by Leo2442926161** [comment]
@bzbarsky-apple the chip-tool run on ubuntu

**Comment by bzbarsky-apple** [comment]
chip-tool supports setting `TMPDIR` now to the value of your choice.
