### ISSUE TITLE
[TC-DL-2.11] ClearYearDay Schedule Command is giving UNSUPPORTED_COMMAND Error

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#18590]
ClearYearDay Schedule Command is giving( UNSUPPORTED_COMMAND 0x81 ) Error
![11](https://user-images.githubusercontent.com/57476670/169199380-841a66a1-2ac3-4b80-875f-fbd1a681ab57.png)
![error-screenshot](https://user-images.githubusercontent.com/57476670/169199397-e7ac150c-546a-4078-a91e-5183407e875b.png)
[Test_TC_DL_2_11.zip](https://github.com/project-chip/connectedhomeip/files/8723257/Test_TC_DL_2_11.zip)

**Comment by andy31415** [comment]
ClearYearDaySchedule has conformance `SCH`. Could you validate if the door lock feature map claims this feature is supported?

**Comment by kowsisoundhar12** [comment]
@andy31415  SCH bit is not set in feature map

**Comment by DanM-AssaAbloy** [comment]
What door lock example app was this performed on?
Does this still apply to the latest version of the sample app?

**Comment by kowsisoundhar12** [comment]
this issue has been fixed ,hence closing this issue
