### ISSUE TITLE
[TC-DL-2.11] need to compare  LocalEndTime and  LocalStartTime but getting type error in yaml

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#18591]
Summary :
As per testplan need to Verify  LocalEndTime is greater than LocalStartTime or not but getting type error ,i have used SaveAS function to store the LocalStartTime value 

Testplan screenshot:
![testplan](https://user-images.githubusercontent.com/57476670/169200234-f36f993a-0daa-433f-8e45-a3e925fd6efb.png)

Error screenshot:
![error-screenshot](https://user-images.githubusercontent.com/57476670/169200283-545ca057-5028-49cf-b548-37c66e9bb4a5.png)

[logs.zip](https://github.com/project-chip/connectedhomeip/files/8723282/logs.zip)
[Test_TC_DL_2_11-yaml.zip](https://github.com/project-chip/connectedhomeip/files/8723283/Test_TC_DL_2_11-yaml.zip)

**Comment by kowsisoundhar12** [comment]
[DL 2.8] As per testplan need to Verify EndMinute is greater than StartMinute or not but getting type error ,i have used SaveAS function to store the StartMinute value
![2022-05-18_22-43](https://user-images.githubusercontent.com/57476670/169227933-cf45ff7c-76cf-4e88-8296-850a4bb13489.png)

![2-8](https://user-images.githubusercontent.com/57476670/169228115-5090b4d5-dd39-4aab-8f80-7db61fe33d40.png)

![2022-05-18_22-39](https://user-images.githubusercontent.com/57476670/169227880-f7ae9a50-e5f8-40ba-8f99-76479ac46876.png)

[Test_TC_DL_2_8.zip](https://github.com/project-chip/connectedhomeip/files/8725962/Test_TC_DL_2_8.zip)
[exe-logs.zip](https://github.com/project-chip/connectedhomeip/files/8725963/exe-logs.zip)

**Comment by kowsisoundhar12** [comment]
[TC-DL-2.8]
As per testplan need to Verify EndMinute is greater than StartMInute or not but getting type error while running build command ,i have used SaveAS function to store the StartMinutevalue

[Test_TC_DL_2_8.zip](https://github.com/project-chip/connectedhomeip/files/8726700/Test_TC_DL_2_8.zip)
[exe-logs.zip](https://github.com/project-chip/connectedhomeip/files/8726701/exe-logs.zip)

![2022-05-18_22-43](https://user-images.githubusercontent.com/57476670/169237399-694f0198-495c-4080-86c7-e041983e851f.png)

**Comment by bzbarsky-apple** [comment]
So the context here is that this is an optional field.

We generate an `Optional<uint32_t>` to store it in, but then we do:
```
        {{saveAs}} = {{asPropertyValue}};
```
inside maybeSaveAs.zapt, and `asPropertyValue` by default unwraps optionals.  So we generate `LocalStartTimeValue = value.localStartTime.Value()` and are trying to store a `uint32_t` into an `Optional<uint32_t>`.

So a few options here:

1. We could allow the saved value to be missing, and then adjust the templates to make that work.
2. We could require that any time saveAs is being used the value being saved in fact exists and is not missing.

@vivien-apple any feeling on which of those is better?

The second problem we are running into is that `CheckConstraintMinValue` can't handle the min value being an optional, but whether we have to handle that or not, and how we handle it, depends on the answer to the "what should we be storing to start with?" question above.

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @bzbarsky-apple, who has followed up on the spec side, as well as working with @vivien-apple

**Comment by vivien-apple** [comment]
@woody-apple @franck-apple Is that really a cert blocker given this is a YAML only issue ?

**Comment by vivien-apple** [comment]
> So a few options here:
> 
> 1. We could allow the saved value to be missing, and then adjust the templates to make that work.
> 2. We could require that any time saveAs is being used the value being saved in fact exists and is not missing.

I'm sort of in favor of 1. That raised the question of how to compare missing values, for which I would think we should just throw if any of the compared value is missing.
