### ISSUE TITLE
[TC-IDM-5.2]-Chip-tool needs to provide a way to set delayed write request to verify the step 3

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18601]
**#### Problem**
As per Test-Plan, [TC-IDM-5.2] test step 3 expecting that we should set "Wait for 5 seconds(Timer has expired) and then send the Write Request Message to the DUT", But Chip-tool needs to provide a way to set wait time for write request messages.

**PFA screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/169238704-b3167b09-e9f5-4d6d-a046-6c42aa1f5ddb.png)

**system configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and Wifi
Commit-ID: 25e241ebcbf11b1f63dbe25546b1f10219866ad0			
Dut application: All-Clusters-app

**Test-Plan screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/169239907-348e678b-0e7c-497e-92db-29e0595049d7.png)

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#timed-write-transaction

**Comment by bzbarsky-apple** [comment]
There is YAML syntax for this, but not command-line syntax....

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @cjandhyala to follow up, looks like the test should be runnable in YAML right now.

**Comment by Rajashreekalmane** [comment]
I tried in chip-tool interactive mode.

steps to reproduce:-
sudo ./chip-tool interactive start
then at the shell prompt  sent the timed request 
./chip-tool administratorcommissioning open-basic-commissioning-window 500 1 0 --timedInteractionTimeoutMs 1000
waited for 5 mins
then sent a write command ./chip-tool levelcontrol write on-level 1 1 1
getting response as success instead of unsupported access.

Shall I know, is there any way to verify this test step in chip-tool?

**Comment by bzbarsky-apple** [comment]
Just to repeat:

> There is YAML syntax for this, but not command-line syntax....

**Comment by woody-apple** [comment]
@cjandhyala Can you please close this, and file a ticket to update the test plan?

**Comment by sankarselvam** [comment]
@vivien-apple We still see this issue and not able to send a delayed request. Hence we reopened the ticket for the further follow-up.

**Comment by Rajashreekalmane** [comment]
When it was tried in another setup, it worked fine.
