### ISSUE TITLE
[TC-IDM-2.2]-Chip-tool needs to support the "SuppressResponse field" value to set for Read Request Message to the DUT to read an attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18608]
#### Problem
Chip-tool needs to provide API to set the SuppressResponse field value.
As per the Test-Plan, the test step 32 in [TC-IDM-2.2] is expecting to set SuppressResponse field set to False.

**PFA screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/169291922-3f7b84c2-f93f-4057-b709-98302c5db81f.png)

**system configuration**
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: 25e241e
Dut: All-Clusters-app

**Test-Plan Screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/169292118-13255b6c-62c1-415c-82b5-911e3bbe2799.png)

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#outgoing-read-request-action

**Comment by bzbarsky-apple** [comment]
This test plan is very confused; there is no "SuppressResponse" field in a Read Request.

Filed https://github.com/CHIP-Specifications/chip-test-plans/issues/1313 to get the test plan fixed to make sense.

**Comment by bzbarsky-apple** [comment]
@cjandhyala
