### ISSUE TITLE
Figure out what read path count enforcement should look like.

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#18610]
#### Problem
Right now (except in configurations that allow completely unlimited paths) we outright reject any read attempt that has more than the spec-mandated minimum number of paths, no matter how many paths we can actually support or how many fabrics we actually have configured. 

 #### Proposed Solution
Figure out whether we can have a maximum that is not also the bare minimum, possible depending on device configuration.

**Comment by mrjerryjohns** [comment]
@erjiaqing assigning this to you for now since this is your wheel-house.
