### ISSUE TITLE
[GC-2.4] Device should response with error for invalid regulatory config value. 

### ISSUE THREAD

**Issue by doublemis1** [project-chip/connectedhomeip#18617]
#### Problem
Step ./chip-tool generalcommissioning set-regulatory-config 4 12 0 15 0 shall fail
with ifeld ErrorCode as 'ValueOutsideRange'(1) and DebugText as a 'string' value.

[GC_2_4.log](https://github.com/project-chip/connectedhomeip/files/8730316/GC_2_4.log)

**Comment by bzbarsky-apple** [comment]
@doublemis1 What SHA is this being tested on?  This was fixed in #18067 on May 5, as far as I can tell....

**Comment by doublemis1** [comment]
The issue was revealed on TE9 SHA (https://github.com/project-chip/connectedhomeip/tree/TE9)

**Comment by bzbarsky-apple** [comment]
Ah, yes, that predates that fix.

This works correctly on tip.
