### ISSUE TITLE
[TC-MC-3.7]Application Launcher Cluster--Chip-tool needs to provide a way for TH to sends a LaunchApp command to DUT to launch an app and bring an application to the foreground.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18663]
#### Problem
[TC-MC-3.7]Application Launcher Cluster--Chip-tool needs to provide a way for TH to sends a LaunchApp command to DUT to launch an app and bring an application to the foreground.

**Test-Plan screenshot**
![image](https://user-images.githubusercontent.com/95841834/169523593-3b9d25de-cfd0-43d0-be08-cc3cdbab3cc8.png)

**Comment by andy31415** [comment]
@chrisdecenzo - would this fall under your development as this involves application launcher cluster?

**Comment by chrisdecenzo** [comment]
You can use the launch-app command. For example, the following works to launch an app in the tv-app example:

chip-tool applicationlauncher launch-app '{"catalogVendorId": 123, "applicationId": "exampleid"}' 1234 1

I added this instruction to the notes section of this test case in the test plan doc.
