### ISSUE TITLE
[Door-Lock-Server] Server sets LockState to 'Locked' upon initialization

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#18677]
#### Problem
door-lock-server's InitServer method sets the LockState to 'Locked'.

This creates two unwanted side effects:
1. LockState is assumed as 'Locked' until the application changes it (which could be misconstrued by a client).
2. A Lock-Operation-Event is generated in the Event List that says that the door was locked, which is not true.

 #### Proposed Solution
Suggest modifying to set the LockState to null.

From the spec: "The LockState Attribute may be NULL if the lock hardware does not currently know the status of the locking mechanism. For example, a lock may not know the LockState status after a power cycle until the first lock actuation is completed."

**Comment by mrjerryjohns** [comment]
Also seems pretty critical...
