### ISSUE TITLE
[Door-Lock-Server] Lock and Unlock commands cause the LockState attribute to immediately be set upon Success

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#18678]
#### Problem
The LockDoor, UnlockDoor, and UnlockWithTimeout commands received by door-lock-server case that the LockState attribute (and corresponding events) be set immediately after the underlying app returns SUCCESS. This SUCCESS from the calls to the underlying app indicates that the app has successfully accepted the operation, it does NOT mean that the LockState has already moved to its intended final state.

For example, a LockDoor command will cause door-lock-server to call `emberAfPluginDoorLockOnDoorLockCommand`, which should return TRUE if the command is accepted. Currently, door-lock-server interprets this TRUE value as success and immediately sets the LockState to `kLocked`. This is typically NOT correct. Since the lock operation itself typically takes substantial time by the hardware, the hardware will transition to a Locked position after several seconds.

 #### Proposed Solution
The setting of the LockState should be moved to the application (as well as the default implementation of emberAfPluginDoorLockOnDoorLockCommand).

**Comment by mrjerryjohns** [comment]
This seems like a fairly critical bug. @Morozov-5F, would you have cycles to help address this?
