### ISSUE TITLE
[Door-Lock-Server] Move Auto-Relock timing out of server and into Application

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#18676]
#### Problem
DoorLockServer currently implements AutoRelock and UnlockWithTimeout relock timing internally. However, this presents a problem for lock devices that implement such functionality in hardware (for security issues, etc). 

 #### Proposed Solution
Two possible solutions:
1. Move relock timing out of door-lock-server and into the application (add implementation to door-lock sample).
2. Encase existing auto-relock functionality inside compile-time conditionals (#if's).

**Comment by DanM-AssaAbloy** [comment]
post 1.0 enhancement.
No spec compliance implications
