### ISSUE TITLE
[Door-Lock-Server] Move implementation of Clear-All-Users and Clear-All-Credentials into the app

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#18680]
#### Problem
Per the DoorLock spec, a value of 0xFFFE for a UserIndex or 0xFFFE for a CredentialIndex will cause all Users or Credentials of specified type to be cleared.

Currently, door-lock-server interprets these values and loops internally from 1..NumberOfUsersSupported calling the `emberAfPluginDoorLockSetUser` or `emberAfPluginDoorLockSetCredential` method provided by the application. This can be extremely inefficient and time consuming (especially for a constrained device with a flash-based filesystem) to individually clear each of the entries -- especially if the device supports many users. The device will likely support a way to efficiently wipe the entire database if the implementation of 0xFFFE is moved to the device's application implementation.

 #### Proposed Solution
Move loops for implementation of 0xFFFE to the application.

**Comment by DanM-AssaAbloy** [comment]
post1.0 enhancement.
No affect on spec compliance.
