### ISSUE TITLE
[Java] No way to read/subscribe attributes without fabric-filtering

### ISSUE THREAD

**Issue by g-coppock** [project-chip/connectedhomeip#18686]
#### Problem

In the generated cluster code, for example in `OperationalCredentialsClient-ReadImpl.cpp`, the `ReadAttribute` method has a default boolean parameter for `aIsFabricFiltered` which defaults to `true`.

As this generated code does not provide any mechanism by which to set this attribute, all reads are fabric-filtered.

 #### Proposed Solution

Suggested solutions:

1. Generate overloaded methods for each `readX` method which accept a boolean for `fabricFiltered`. Probably the simplest option, but the downside here is a lot of extra code, and a growing parameter list.
2. Update the generated methods to require a boolean argument for `fabricFiltered`. Also simple, but is a breaking change for Java clients.
3. Add a Java-layer `ReadParams` class that contains any arguments that we want to surface (timeout, fabricFiltered) to mirror `ReadPrepareParams`, and have the generated code accept this as an argument. This would also be a breaking change, but would simplify later addition of any other arguments for reading attributes without breaking compatibility. Downsides here are that `ReadPrepareParams` has overlap between read/subscribe, so this would add parameters to the read methods that may be meaningless (e.g. `mMinIntervalFloorSeconds` for a read).

**Comment by yunhanw-google** [comment]
Plan to have Java class ReadPrepareParams

**Comment by andy31415** [comment]
#19437 adds options for fabric filtering
