### ISSUE TITLE
[Door-Lock-Server] Calls to emberAfPluginDoorLockOnUnhandledAttributeChange need added attributePath parameter

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#18681]
#### Problem
The `emberAfPluginDoorLockOnUnhandledAttributeChange` function needs the attributePath parameter added to the parameter list.

 #### Proposed Solution
change function declaration from:
`emberAfPluginDoorLockOnUnhandledAttributeChange(chip::EndpointId EndpointId, EmberAfAttributeType attrType, uint16_t attrSize, uint8_t * attrValue)`
to:
`emberAfPluginDoorLockOnUnhandledAttributeChange(chip::EndpointId EndpointId, const chip::app::ConcreteAttributePath & attributePath, EmberAfAttributeType attrType, uint16_t attrSize, uint8_t * attrValue)`

**Comment by mrjerryjohns** [comment]
@Morozov-5F would you be able to help take this on?

**Comment by bzbarsky-apple** [comment]
@jrhees-cae what are the observable consequences of this function having the wrong signature?

**Comment by jrhees-cae** [comment]
Without the attribute path being included as a parameter, the function is
completely useless to an app which wishes to override the weak link. The
app gets the call, but had no way of knowing which attribute was being
changed.

Jon

**Comment by bzbarsky-apple** [comment]
Sounds like lock apps will need this....

**Comment by woody-apple** [comment]
SDK Review: Seems like this could help Lock's for SVE, not required, but given where we are right now, we can take this.

**Comment by woody-apple** [comment]
SDK Review: @Morozov-5F are you able to take a look at this?
