### ISSUE TITLE
No support commissionee device to delete fabric

### ISSUE THREAD

**Issue by nicelyjust** [project-chip/connectedhomeip#18727]
#### Problem
On some devices with a screen(more  for the Android platform), if user want to delete a fabric that has commissioned,how to do it?

 #### Proposed Solution
I think this is a very common feature for users, I hope it can be supported

**Comment by mrjerryjohns** [comment]
Please check out the `RemoveFabric` command on the `OperationalCredentialsCluster`. That requires a fabric-index of the fabric to be deleted to be passed in. The fabric index that corresponds to the right fabric can be retrieved by reading the `Fabrics` list and upon finding the right entry, to retrieve the 'fabric-index' field from within that entry.

**Comment by mrjerryjohns** [comment]
Please close if the above comment resolves your question.

**Comment by nicelyjust** [comment]
Thank you for the response, @mrjerryjohns 
OperationalCredentialsCluster is responsible for commissioner ->commissionee, I mean that adding fabric deletion methods to allow the user to delete a fabric on device side,not through commissioner

**Comment by bzbarsky-apple** [comment]
Generally speaking, the intent is that only a valid administrator of the device will be able to remove fabrics, right?

**Comment by nicelyjust** [comment]
yes, For example:
![image](https://user-images.githubusercontent.com/20015907/170188413-49c4b309-9d9c-4afa-9342-88aca7dc6a89.png)

**Comment by nicelyjust** [comment]
Yes, For example I want to manager fabrics on TV, GUI like this
![image](https://user-images.githubusercontent.com/20015907/170188809-467c499f-ac1c-4d3f-85ac-7e9fb748c5bc.png)
