### ISSUE TITLE
FeatureMap returns 0x86 (UNSUPPORTED_ATTRIBUTE) in multiple clusters.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18750]
**#### Problem**
Though the feature map attribute is implemented in below mentioned clusters, still it throws an error code as 0x86(unsupported attribute).
 Thermostatuserinterfaceconfiguration Cluster
Temperaturemeasurement Cluster
 Illuminancemeasurement Cluster
Identify cluster

**expected behavior:-**FeatureMap bitmap value 0
**actual behavior:-**0x86(unsupported attribute

 ***** steps to reproduce****
 ./chip-tool   illuminancemeasurement  read feature-map 1 1
./chip-tool   thermostatuserinterfaceconfiguration   read feature-map 1 1
./chip-tool  temperaturemeasurement   read feature-map 1 1
 ./chip-tool identify  read feature-map 1 1

****system configuration:-****
Chip-Tool: RPI(chip-tool)
DUT: RPI(all-cluster-app)
Platform : IP
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/7afd35229da424a139642e4ebbe68bb4d71554cf
Platform:-Linux platform

**Spec reference:-**
![image](https://user-images.githubusercontent.com/95841834/170026700-cf2855d5-0e40-4ac9-8a53-5b0f190c69a3.png)

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/thermostatuserconfiguration.adoc#tc-tsuic-1-1-global-attributes-with-server-as-dut
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/temperaturemeasurement.adoc#tc-tm-1-1-global-attributes-with-server-as-dut
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/illuminance_measurement.adoc#tc-ill-1-1-global-attributes-with-server-as-dut
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/identify.adoc#tc-i-1-1-global-attributes-with-server-as-dut

**PFA log:-**
[feature map.txt](https://github.com/project-chip/connectedhomeip/files/8762317/feature.map.txt)
[identify.txt](https://github.com/project-chip/connectedhomeip/files/8762370/identify.txt)

**Comment by somu1710** [comment]
Facing the same issue as error code as 0x86(unsupported attribute) in below mentioned test cases:
1.Pressure measurement cluster
2.Occupancy sensing cluster
3.Relative humidity
4.Power Source Configuration
5.Descriptor

**Comment by bzbarsky-apple** [comment]
> Commit-ID: https://github.com/project-chip/connectedhomeip/commit/7afd35229da424a139642e4ebbe68bb4d71554cf

Please don't bother testing FeatureMap (or at leats reporting issues about it) on anything before 2db812e8ef2f7fe3edfe04da4b526b3e977a1a43.

I just tried all the clusters listed in https://github.com/project-chip/connectedhomeip/issues/18750#issuecomment-1136066609 in all-clusters app on tip  (fda7854efb39fbfac9dd1063cc428c17b9676970) and they all work correctly.
