### ISSUE TITLE
[New Cluster] Logging

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#1876]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/2874
https://github.com/project-chip/connectedhomeip/issues/2875
