### ISSUE TITLE
[TC-WNCV-4.3] CurrentPositionLiftPercentage attribute showing value mismatch error

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#18794]
Summary:
As per testplan of TC-WNCV-4.3 
Step 1a: TH reads CurrentPositionLiftPercent100ths attribute from DUT and saved value as attrCurrentPositionLiftPercent100ths got value as 500
Step 1c: TH reads CurrentPositionLiftPercentage from  DUT + assert CurrentPositionLiftPercent100ths/100 equals CurrentPositionLiftPercentage expected value is 5 but got 50 

Testplan screenhot:
![image](https://user-images.githubusercontent.com/102359958/170257872-7c58208a-08af-4331-a78a-14b78e8b3ce6.png)
YAML screenshot:
![image](https://user-images.githubusercontent.com/102359958/170257540-63c70945-c1b0-4942-9804-a2b7032f190b.png)
Execution logs:
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/8770879/exe_log.txt)

**Comment by bzbarsky-apple** [comment]
@jmeg-sfy

**Comment by woody-apple** [comment]
SDK Spec Review: Tagging @cjandhyala to confirm this is or is not a cert blocker.

**Comment by jmeg-sfy** [comment]
@manjunath-grl how did you test this ?

**Comment by manjunath-grl** [comment]
@jmeg-sfy we are using the commands used for CI
For Build:
./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-chip-tool-no-ble-tsan-clang\
                        --target linux-x64-all-clusters-no-ble-tsan-clang \
                        --target linux-x64-lock-no-ble-tsan-clang \
                        --target linux-x64-ota-provider-no-ble-tsan-clang \
                        --target linux-x64-ota-requestor-no-ble-tsan-clang \
                        --target linux-x64-tv-app-no-ble-tsan-clang \
                        build \
                     "
For running tests:
./scripts/run_in_build_env.sh \
                  "./scripts/tests/run_test_suite.py \
                     --chip-tool ./out/linux-x64-chip-tool-no-ble-tsan-clang/chip-tool \
                     run \
                     --iterations 1 \
                     --all-clusters-app ./out/linux-x64-all-clusters-no-ble-tsan-clang/chip-all-clusters-app \
                     --lock-app ./out/linux-x64-lock-no-ble-tsan-clang/chip-lock-app \
                     --ota-provider-app ./out/linux-x64-ota-provider-no-ble-tsan-clang/chip-ota-provider-app \
                     --ota-requestor-app ./out/linux-x64-ota-requestor-no-ble-tsan-clang/chip-ota-requestor-app \
                     --tv-app ./out/linux-x64-tv-app-no-ble-tsan-clang/chip-tv-app \
                  "
