### ISSUE TITLE
Should chip-tool be compatiable with matter all-cluster demo - compiled from same version?

### ISSUE THREAD

**Issue by wxiangcheng** [project-chip/connectedhomeip#18795]
#### Problem
I want to use chip-tool running on Linux as controller. The other matter device is ESP32 board.
when I compiled chip-tool from top master branch, I found it can't do commission with my ESP32 board. But with one elder chip-tool, it can do commission with ESP32. But this elder chip-tool lost its workspace.

So, how to know which chip-tool should I use to do commission with my ESP32 board? Are they required to be generated from same SDK?

Thanks
<>

**Comment by bzbarsky-apple** [comment]
Generally speaking, chip-tool and the server should be from the same SHA, historically, as the wire format was getting updated.

So yes, if you use a current tip chip-tool with some random old-enough SHA it will fail.
