### ISSUE TITLE
Reconnect to devices that are already commissioned using chip-device-ctrl

### ISSUE THREAD

**Issue by songshan99** [project-chip/connectedhomeip#18797]
I have been trying examples with NRF52840 and ESP32, using BLE to commission the device to Thread or WiFi network.
The examples work as expected, and I can use Python Matter Controller (chip-device-ctrl) to turn on/off an LED.

The exmaples work in such a way that you do the WiFi/thread network commissioning first, and then you can use zcl command to control the device

But i also expect that after the commissioning is done, there should be  a way to connect and control the device which is already comissioned. Such as if I re-start the chip-device-ctrl, there should be a way to reconnect to the device.

I list the below available commands in Python Matter Controller, i tried the "connect" command and "resolve" command but none of them works.

Available commands (type help <name> for more information):
============================================================
ble-adapter-print   close-session  open-commissioning-window      setup-payload
ble-adapter-select  commission     paseonly                       zcl
ble-debug-log       connect        resolve                        zclread
ble-scan            discover       set-pairing-thread-credential  zclsubscribe
close-ble           get-fabricid   set-pairing-wifi-credential

Maybe i didn't use the commands correctly but can someone give me some suggestion on how to re-connect to a already-commissioned device?
Thanks a lot!

**Comment by dhrishi** [comment]
I am not sure if that is possible using `chip-device-ctrl` but it is possible through the host based [chip-tool](https://github.com/project-chip/connectedhomeip/tree/master/examples/chip-tool) which is now supposed to the be default testing tool, also used by the cert team.
