### ISSUE TITLE
TC-SWTCH-3.2 - Client test case needs an reference app to modify and verify the state of the the switch.

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#18801]
**Problem description:** 

To verify the latching and Momentary switch state as explained in the test case TC-SWTCH-3.2 , If there is an reference app to modify the state of the switch will be helpful to verify this simulated functionality.

currently test case expects to change the state of the switch from 0 to 1 and vice versa and expects to read the attribute. As of now there is no provision to change the change the state of the switch. Hence requesting for a reference app to verify this functionality.  

For your reference here i attached the Draft TE9 document link:
https://docs.google.com/spreadsheets/d/1h4d4J90KAxFqUL_cXZHyM3pHjHCEXzFITkQhN2KMqDY/edit?pli=1#gid=1872755018

**Comment by mrjerryjohns** [comment]
It looks like there is an example implementation of the `SwitchDelegate` for LInux, but there is no way to actually interact with that to effect changes to the switch state from a CLI. There are some issues with the existing `switch-server.cpp` impl in that it doesn't _actually_ change the state of the switch attributes, but that will be a separate issue.

**Comment by yufengwangca** [comment]
This issue should be fixed by #19007, but I only added the way to toggle those states in chip-all-clusters app, not lighting-switch app since it is missing Linux implementation

**Comment by franck-apple** [comment]
Per Silabs team, this is not needed for the lighting-switch app. Closing.
