### ISSUE TITLE
TC-MF-1.11 Chip tool Darwin testing: After 20 unsuccessful attempts, 21st attempt pairing is going through

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18813]
As per TC-MF-1.11, after 20 unsuccessful pairing attempts, the commissioning window should be closed. But while executing these steps through chip tool Darwin, the pairing at 21st attempt is going through. 

Note: The issue is appearing on ECM. On BCM it is working as expected.

Command used for unsuccessful pairing attempts:  ./chip-tool-darwin pairing manualcode 1 3496902900 --commissioner-name beta
Command used to pair in 21st attempt: ./chip-tool-darwin pairing manualcode 1 34969029007 --commissioner-name beta

**Comment by bzbarsky-apple** [comment]
I just tried the following steps to reproduce this:

1. Check out current tip (a3fdd059ebcf22131f6905dd551eabd631466db4).
2. `scripts/examples/gn_build_example.sh examples/all-clusters-app/linux out/debug/standalone chip_config_network_layer_ble=false` to build all-clusters app.
3. `scripts/examples/gn_build_example.sh examples/chip-tool-darwin out/debug/standalone/` to build chip-tool-darwin
4. `scripts/examples/gn_build_example.sh examples/chip-tool out/debug/standalone/` to build chip-tool
5. `rm /tmp/chip_*`
6. In terminal 1, run `./out/debug/standalone/chip-all-clusters-app`
7. In terminal 2, run `./out/debug/standalone/chip-tool pairing onnetwork 17 20202021` to pair.
8. In terminal 2, run `./out/debug/standalone/chip-tool pairing open-commissioning-window 17 1 900 1000 2000` to open the commissioning window.  The log says:
    ```
   [1653509701464] [37382:55252849] CHIP: [CTL] Manual pairing code: [15353635273]
    ```
9. `./out/debug/standalone/chip-tool payload parse-setup-payload 15353635273` which says:
    ```
    [1653509773066] [37387:55253309] CHIP: [SPL] Parsing decimalRepresentation: 15353635273
    [1653509773066] [37387:55253309] CHIP: [SPL] CommissioningFlow: 0
    [1653509773066] [37387:55253309] CHIP: [SPL] VendorID: 0
    [1653509773066] [37387:55253309] CHIP: [SPL] Version: 0
    [1653509773066] [37387:55253309] CHIP: [SPL] ProductID: 0
    [1653509773066] [37387:55253309] CHIP: [SPL] Discriminator: 1792
    [1653509773066] [37387:55253309] CHIP: [SPL] SetUpPINCode: 57790752
    [1653509773066] [37387:55253309] CHIP: [SPL] RendezvousInformation: 0
    ```
10. Run `./out/debug/standalone/chip-tool-darwin pairing ethernet 1 57790751 1792 ::1 5540` (wrong setup PIN) 20 times .  each one fails.  Server closes commissioning window.
11. Run `./out/debug/standalone/chip-tool-darwin pairing ethernet 1 57790752 1792 ::1 5540` (correct pin).  No response from server, as expected.

@Garik098 How was the manual code 3496902900 derived in your case?  Was the commissioner actually contacting the server during the 20 failed commissioning attempts?  Beacause that looks like an invalid (fails checksum) code that the commissioner would not be able to extract a setup payload from at all...

**Comment by Garik098** [comment]
@bzbarsky-apple Got it. Unlike chip tool, chip tool Darwin is not printing the manual code in the logs every time we open the ecm commissioning window. So, Josh gave me the manual code to use. It is the same manual code 34969029007 every time. 

I see that it is because of the failed checksum and I am closing this ticket as I see expected behavior when tried with manual code 34969027009 for 20 times and gave the right one 21st time and it didn't commission.

**Comment by bzbarsky-apple** [comment]
> chip tool Darwin is not printing the manual code in the logs every time we open the ecm commissioning window

How are you opening the ECM commissioning window?  We should fix this....

**Comment by bzbarsky-apple** [comment]
@Garik098

**Comment by Garik098** [comment]
@bzbarsky-apple For ECM, I am using the command that was given by @krypton36 

./chip-tool-darwin administratorcommissioning open-commissioning-window 500 hex:06c756dffcd722653452a12dcd945d8c54da2b0f3cbd1b4dc3f1adb223aeb26b047cd24c96866f979b1d83ec50e2b4ae30cdf2fdb32bd8a211b837dc94edcd56f4d14377191076bfc59d99b7dd3053efd6f02c4434f2bdd27aa4f9cea70d738e4c 3840 1000 hex:5350414b453250204b65792053616c74 1 0


The output for this command in Darwin tool doesn't print the manual pairing code in the logs (Chip tool provides a different manual code every time in the logs). For that I got 34969029007 manual code from @krypton36  which will work every time.

**Comment by bzbarsky-apple** [comment]
> ./chip-tool-darwin administratorcommissioning open-commissioning-window 500 hex:06c756dffcd722653452a12dcd945d8c54da2b0f3cbd1b4dc3f1adb223aeb26b047cd24c96866f979b1d83ec50e2b4ae30cdf2fdb32bd8a211b837dc94edcd56f4d14377191076bfc59d99b7dd3053efd6f02c4434f2bdd27aa4f9cea70d738e4c 3840 1000 hex:5350414b453250204b65792053616c74 1 0

Ah.  Yes, that will not print the manual pairing code, since it has no way to know what that is.  It's just given a verifier derived from the code....

We should add a command that will take a PIN and compute things from that.  Filed https://github.com/project-chip/connectedhomeip/issues/18916 on doing that.
