### ISSUE TITLE
This may exceed the limit of key name length in ESP32 platform

### ISSUE THREAD

**Issue by nykh2010** [project-chip/connectedhomeip#18828]
https://github.com/project-chip/connectedhomeip/blob/433c5ff9049600e67a214abbb1b0d1b984df6147/src/lib/support/DefaultStorageKeyAllocator.h#L60

This may exceed the limit of key name length in ESP32 platform. The max length is 16 bytes.

**Comment by bzbarsky-apple** [comment]
See https://github.com/project-chip/connectedhomeip/pull/18604
