### ISSUE TITLE
[TC-IDM-4.3]--Chip tool needs to provide a way to set MinIntervalFloor value > MinIntervalFloor value For subscription request.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18839]
#### Problem
As per Test-Plan, step 21 says TH sends a subscription request action for attribute and set the MinIntervalFloor value to be greater than MaxIntervalCeiling, and expecting response as  DUT sends an error message and the subscription is not established.
**Chip tool needs to provide a way to set MinIntervalFloor value > MaxIntervalCeiling value when TH sends a subscription request action for attribute to DUT.**
 
**Test-Plan screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/170544038-0458679d-5f1b-4f5e-afc9-795a05767617.png)

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#subscribe-response-action

**Comment by bzbarsky-apple** [comment]
@Rajashreekalmane @cjandhyala I don't understand this issue.  The test plan says to set MinIntervalFloor to the same value as MaxIntervalCeiling (which chip-tool supports), but the text talks about setting `MinIntervalFloor > MinIntervalFloor`, which is obviously not possible.

**Comment by bzbarsky-apple** [comment]
I am _guessing_ this issue is actually about step 21, not step 20, and that the request is that we allow `MinIntervalFloor > MaxIntervalCeiling`?

If so, that's not allowed in the SDK right now, so adding it to chip-tool is not exactly trivial.

**Comment by andy31415** [comment]
Are we supposed to cert-block on negative test cases? I imagine many of these may be non-trivial to implement.

@cjandhyala what is the policy here? I would be inclined to not block on "allow invalid values to be accepted by tooling" or at least separate these cases a bit, since we will want some flags/builds/error injection capability for "I am providing invalid values but I know what I am doing and really need it"

**Comment by Rajashreekalmane** [comment]
@bzbarsky-apple Yes this issue is on step 21 , I have updated  the issue Now.

**Comment by mrjerryjohns** [comment]
I don't think is validatable without modifications to the IM implementation in the SDK to permit this 'test modality' and skips initial validation of these parameters.

I'd recommend we skip this test.

**Comment by bzbarsky-apple** [comment]
@mrjerryjohns See #18855
