### ISSUE TITLE
[TC-CC-9.*] ColorLoopStoredEnhancedHue attribute value  mismatch error.

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#18848]
Summary:
As per testplan [TC-CC-9.*] Precondition: Set DUT EnhancedCurrentHue to 0x4000 using EnhancedMoveToHue command
but in Step 5c: TH read ColorLoopStoredEnhancedHue attribute from DUT and value is the same as EnhancedCurrentHue attribute (0x4000) set in Pre-Condition but got 0 when executed.
Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/170517445-6edb78bb-8135-411f-a28c-2422250df6a7.png)
![image](https://user-images.githubusercontent.com/102359958/170517249-bce6d51d-b036-4f56-9b4e-687541ebdaa7.png)
Execution logs:
[CLSEH_Value.txt](https://github.com/project-chip/connectedhomeip/files/8780028/CLSEH_Value.txt)
![ColorLoopStoredEnhancedHue](https://user-images.githubusercontent.com/102359958/170518889-a0ea583e-cb99-44cd-868a-f3e3845f1220.png)

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs

**Comment by jmartinez-silabs** [comment]
I will review it but I think those are teat plan instructions set issues and not implementation issues

**Comment by woody-apple** [comment]
SDK Spec Review: Tagging @cjandhyala, as this may be an issue with the test plan

**Comment by jmartinez-silabs** [comment]
Spec and Test plan are correct. I tested manually following the test-plan instructions and the implementation matches the expected results of the test plan.

Here are all the logs of test case 9.1 I ran.
[TC-CC-9-1.txt](https://github.com/project-chip/connectedhomeip/files/8835662/TC-CC-9-1.txt)

ColorLoopStoredEnhancedHue gets updated to the EnhancedHue Value before a loop. 

I suspect the issue you faced is either a Yaml test issue or the pre-conditions for the test were not met.

Who is expected to fix/validate the YAML tests?

**Comment by woody-apple** [comment]
Spec Review: Tagging @raju-apple to take a look at updating the YAML/tests as necessary.

**Comment by raju-apple** [comment]
@manjunath-grl Can you re-try today again and see if its still happening and check.

**Comment by manjunath-grl** [comment]
@woody-apple @raju-apple after Precondition we added a delay of 1 sec now it is working fine
YAML screenshot:
![image](https://user-images.githubusercontent.com/102359958/174782968-b6712b23-de89-4e02-87b4-68fe15f7d830.png)
Execution logs:
[CC_9_1.zip](https://github.com/project-chip/connectedhomeip/files/8948176/CC_9_1.zip)
