### ISSUE TITLE
[TC-CC-9.*] EnhancedCurrentHue value mismatch error.

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#18850]
Summary:
As per testplan [TC-CC-9.*] TH sends ColorLoopSet command  EnhancedCurrentHue should decrease and continue to Max allowed enhanced hue if reach 0. After 30 sec, it should return to ColorLoopStartEnhancedHue but got random value within 0 to 65535 when executed.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/170520181-5369b420-0138-4b27-97b4-9b77c4846c94.png)

Execution logs:
[ECH_random.txt](https://github.com/project-chip/connectedhomeip/files/8780091/ECH_random.txt)
![Echu_Random_value txt](https://user-images.githubusercontent.com/102359958/170520325-92e46b9a-3c00-4897-b54d-a294152bbf8f.png)
[ECH_value.txt](https://github.com/project-chip/connectedhomeip/files/8780093/ECH_value.txt)
![EnhancedCurrentValue](https://user-images.githubusercontent.com/102359958/170520350-5a5588fb-c274-41a6-9610-6fc1db3fcdcc.png)

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs

**Comment by woody-apple** [comment]
SDK Spec Review: Tagging @cjandhyala to confirm that this is or is not a cert blocker, or a test plan issue.

**Comment by cjandhyala** [comment]
@woody-apple ColorLoopSet is an optional command and we are not going support optional cmds for v1.0, hence not cert blocker

![Screen Shot 2022-05-27 at 4 10 51 PM](https://user-images.githubusercontent.com/68604034/170799110-6f95e7a6-4e5b-44f1-8c7c-aad075f30955.png)

**Comment by yinyihu-silabs** [comment]
@manjunath-grl 
The two values you read is normal. with color loop, the _EnhancedCurrentHue_ is continuously changing. Unless you're reading _EnhancedCurrentHue_ exactly 30 seconds from the time of activation (not the same as time between sending activation and read command), you're likely not going to received the exact match.

Based on the logs, I assumed you set the initial _EnhancedCurrentHue_ to 160. Both 379 and 65477 are reasonably within the range of 160 where 379 is likely just short of 30 seconds and 65477 is just over 30 seconds wrapping over the Max limit.

In Step 5e follows, it's expected that  _EnhancedCurrentHue_  will continue decreasing over every 30-second loop.

**Comment by manjunath-grl** [comment]
@yinyihu-silabs thanks for the information
