### ISSUE TITLE
Nordic lighting app does not start/boot up

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18864]
With SHA eb7628f103faeb53b29519a6d40a47bafb290f62

Thread test fails because nordic board cannot be started.

**Steps:**
 1. cd ~/connectedhomeip
 2. git pull
 3. git reset --hard eb7628f103faeb53b29519a6d40a47bafb290f62
 4. source scripts/activate.sh
 5. python3 scripts/setup/nrfconnect/update_ncs.py --update
 6. cd examples/lighting-app/nrfconnect
 7. west build -b nrf52840dk_nrf52840 --pristine always
 8. west flash --erase
 9. minimum -s
 10. Set the port number (can be obtained by ls /dev/tty.*)
 
**Output**
minimum terminal hangs;

% minicom -s

Welcome to minicom 2.8

OPTIONS:                                                                     
Compiled on Oct 25 2021, 04:59:49.                                           
Port /dev/tty.usbmodem0006832436881, 13:28:31                                
                                                                             
Press Meta-Z for help on special keys                                        
                                                                             
                                                                             
Also
press + hold of button 1 does not reset the board as no led lights are getting flashed

**Comment by kean-apple** [comment]
This is specific to Nordic example lighting app. Nordic all clusters app powers up ok

**Comment by bzbarsky-apple** [comment]
@Damian-Nordic

**Comment by phonnakasturi-apple** [comment]
WIth SHA f6a79db073621a2af0b3b5c5317fd8dc4028c58c
This issue was resolved.
Nordic lighting app was able to power up.
