### ISSUE TITLE
[Thread Network Diagnostics] SECURITY_POLICY & OPERATIONAL_DATASET_COMPONENTS are no more array

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#18906]
#### Problem
SECURITY_POLICY & OPERATIONAL_DATASET_COMPONENTS are no more array

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
The SDK encodes these as lists, but they're not lists in the spec.
