### ISSUE TITLE
[TC-DL-2.8] Set User Command is giving Failure response

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#18987]
Set User Command is giving Failure response while executing 

Testplan Screenshot:
![2022-05-31_15-39_1](https://user-images.githubusercontent.com/57476670/171150579-ea19bc27-66a9-4b81-a8ca-79fbb108174d.png)

Error Screenshot:
![2022-05-31_15-37](https://user-images.githubusercontent.com/57476670/171150650-4590a202-0102-42b0-bb65-9c770dbabc9b.png)

Yaml Scrrenshot:
![2022-05-31_15-39](https://user-images.githubusercontent.com/57476670/171150728-a2bd7931-4876-45c8-9f4a-cb4a46181cee.png)
[Execution-logs-DL-2-8.zip](https://github.com/project-chip/connectedhomeip/files/8804215/Execution-logs-DL-2-8.zip)

**Comment by bzbarsky-apple** [comment]
@kowsisoundhar12 which server app is being tested here?

**Comment by franck-apple** [comment]
removing "request cert blocker" per discussion with @manjunath-grl

**Comment by bzbarsky-apple** [comment]
This was presumably being tested with all-clusters-app, since this is YAML, where that's not going to work.
