### ISSUE TITLE
[pre-sve] TC-SU-2.8 unable to commission second ota-provider

### ISSUE THREAD

**Issue by pankore** [project-chip/connectedhomeip#18986]
#### Problem
- Test case ID: TC-SU-2.8
- SHA: 425f1fb916ca154deeb75cd82cd5196778aba152
- DUT platform: Ameba all-clusters-app
- Chip-tool platform: Raspberry Pi
- OTA provider platform: Raspberry Pi linux ota-provider-app

TH1/CR1, TH2/OTAP1, TH3/OTAP2 are all running on a single RPI.
- Step 2 requires 2 instances of OTA-provider. 
- Commissioning the first OTAP1 using chiptool is successful. Commissioning the next OTAP2 results in timeout error.
- Also noted that after an OTA-provider is killed, in order to commission a new OTA-provider, tmp files needs to be deleted `rm /tmp/chip*`

Steps to reproduce
- On TH2/OTAP1, launch provider app `./ota-provider-app -f <filepath>`
- On TH1/CR1, commission TH2/OTAP1 `./chip-tool pairing onnetwork 1234 20202021`
- On TH3/OTAP2, launch provider app `./ota-provider-app -f <filepath>`
- On TH1/CR1, commission TH3/OTAP2 `./chip-tool pairing onnetwork 1235 20202021`

[TC-SU-2.8-chip-tool.txt](https://github.com/project-chip/connectedhomeip/files/8803869/TC-SU-2.8-chip-tool.txt)

**Comment by woody-apple** [comment]
Cert Blocker Review: Given this has been in review for > 2 days, closing this. Please re-open if this an issue after running the test plan.
