### ISSUE TITLE
 [TC-DGGEN-2.1] & [TC-DGGEN-3.1] -General Diagnostics-chip-tool needs to implement mandatory TestEventTriggersEnabled attribute.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18993]
**Problem**

[TC-DGGEN-2.1]-General Diagnostics-chip-tool needs to implement mandatory TestEventTriggersEnabled attribute.

**system configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID:4d84a4a978ffc867a62b9b15423a9b70d9cb993e
Dut application: all-clusters-app

**PFA screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/171179756-82bfea81-264a-4b67-b744-6ce72d811ea6.png)

**Test-Plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#tc-dggen-2-1-attributes-with-server-as-dut

**Spec reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsGeneral.adoc

**Comment by mrjerryjohns** [comment]
The commit reference doesn't contain support for this, which was recently added (see https://github.com/project-chip/connectedhomeip/pull/18852). Please re-test.

**Comment by Rajashreekalmane** [comment]
@mrjerryjohns Still mandatory TestEventTriggersEnabled attribute is not implemented in chip-tool.
