### ISSUE TITLE
[TC-DGGEN-1.1] General Diagnostics--AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18994]
**Test-case ID**
[TC-DGGEN-1.1] Global attributes with server as DUT

**Problem:-**
As per Test-Plan, AttributeList attribute missed to list the Mandatory TestEventTriggersEnabled attribute

**expected behavior**:- TH should read mandatory attributes (values 0, 1, 8) from DUT
**actual behavior:-** TH missed to read Mandatory TestEventTriggersEnabled(8) attribute from DUT
**steps to reproduce**:-./chip-tool generaldiagnostics read attribute-list 1 0

**system configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID:4d84a4a978ffc867a62b9b15423a9b70d9cb993e
Dut application: all-clusters-app

**Test-Plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#tc-dggen-1-1-global-attributes-with-server-as-dut

**Spec reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsGeneral.adoc

**PFA log below:-**
[GENDIAG-1.1.txt](https://github.com/project-chip/connectedhomeip/files/8805393/GENDIAG-1.1.txt)

**Comment by mrjerryjohns** [comment]
The commit reference doesn't contain support for this, which was recently added (see #18852). Please re-test.
