### ISSUE TITLE
Update existing example app to support switch cluster event 

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#19007]
#### Problem
switch cluster event APIs have been moved from platform layer to app domain, currently, CSG does not have a way to validate these events

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Cert Blocker Review: Marking cert blocker, given this will fail testing. Need to follow up to confirm we have a test for this as well (or make one).

Tagging in @franck-apple as well to follow up on the test plan side of things.

**Comment by franck-apple** [comment]
@cjandhyala confirmed there's a test case for it. That test case triggered issue #18801.
@jmartinez-silabs, @yufengwangca can these 2 issues be treated simultaneously?

**Comment by jmartinez-silabs** [comment]
I think so yes. I can sync with yufeng on monday

**Comment by woody-apple** [comment]
Cert Blocker Review: Removing request cert blocker, as this is covered in the linked issue.
