### ISSUE TITLE
[pre-sve] TC-DGSW-2.3 reset-wartermarks command returns failure

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/connectedhomeip#19013]
**Problem**
_Expected Behavior_
Step 2a: _./chip-tool softwarediagnostics reset-watermarks 1 0_  command executed successfully.

_System Configuration_
- DUT: EFR32
- App: lighting
- SDK SHA: 425f1fb916ca154deeb75cd82cd5196778aba152

_Log_
[tc-dgsw-2.3.txt](https://github.com/project-chip/connectedhomeip/files/8809634/tc-dgsw-2.3.txt)

**Comment by mrjerryjohns** [comment]
It seems like the `DiagnosticDataProvivderImpl` for EFR32 does not implement the `ResetWatermarks` method. That's likely the cause of this error.

The spec requires that if you claim support for the optional `WTRMRK` feature (which this app does state it does), then that command should be implemented.
