### ISSUE TITLE
[TC-WNCV-4.4] -  CurrentPositionTiltPercentage attribute value is not matched with the expected outcome

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#19055]
**Problem:**
As per testplan CurrentPositionTiltPercent100ths attribute value /100 should be equal to the  CurrentPositionTiltPercentage attribute value.but values are mismatched.

**Actual outcome:**
CurrentPositionTiltPercent100ths: 500
 CurrentPositionTiltPercentage: 50

**Expected outcome:**
CurrentPositionTiltPercent100ths: 500
CurrentPositionTiltPercentage: 5

**steps to reproduce:**
CurrentPositionTiltPercentage must be equal to CurrentPositionTiltPercent100ths / 100 

App used - allclusters app
Platform-Raspberrypi

Here i attached the logs for your reference:

[TC-WNCV-4.4.txt](https://github.com/project-chip/connectedhomeip/files/8814591/TC-WNCV-4.4.txt)

**Comment by jmeg-sfy** [comment]
it is because init value are wrong this PR would fix it
