### ISSUE TITLE
[pre-sve] TC-I-2.2 after waiting 10s identify-time is unchanged

### ISSUE THREAD

**Issue by jimlyall-q** [project-chip/connectedhomeip#19054]
#### Problem
 * Expected - Set identify-time to 60, read identify time as 60, wait 10s, read identify-time as ~50
 * Actual - After 10s identify-time is still 60
 * TC-I-2.2 steps to 2c
 * qpg6105 + x64 chip-tool

[TC_I_2_2.1653981452.log](https://github.com/project-chip/connectedhomeip/files/8814564/TC_I_2_2.1653981452.log)

 #### Proposed Solution
No fix

**Comment by woody-apple** [comment]
Cert Blocker Review: @franck-apple to find a platform owner for this.

**Comment by woody-apple** [comment]
Cert Blocker Review: Removing cert blocker, given the Core SDK supports this, but does need resolution in the specific platform.

**Comment by mkleszcz-no** [comment]
I have exactly the same problem on nRF.
chip-tool and DUT commit id : 5d8599d (pre-sve SHA)

Logs:
[TC_I_2_2_nRF.log](https://github.com/project-chip/connectedhomeip/files/8877909/TC_I_2_2_nRF.log)
[TC_I_2_2_nRF_DUT.log](https://github.com/project-chip/connectedhomeip/files/8877911/TC_I_2_2_nRF_DUT.log)

**Comment by tima-q** [comment]
@woody-apple could this reviewed by TSG again given 2 platforms (one FreeRTOS, other Zephyr based) have this issue ? The code seems to re-use code generic timer code that's also used in other clusters, but there might be some detail missing I don't fully grasp.
`chip::DeviceLayer::SystemLayer().StartTimer`

**Comment by tima-q** [comment]
Issue was related to application level implementation of Identify behavior.
Without a handling class, the cluster does not take any action.
Fixed by adding placeholder implementation of Identify handling at application level
