### ISSUE TITLE
Actions Cluster - SDK needs to implement the Mandatory commands 

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#19062]
**Problem**:
While Executing the behavior of the non-global commands of the Actions cluster, mandatory attribute throws error code as 0x81(unsupported command).

**Commit used** : 4d84a4a978ffc867a62b9b15423a9b70d9cb993e	

- Chip-tool - RPI-4, 8GB RAM
- DUT - RPI - RPI-4, 8GB RAM	
- Platform : linux platform
- Dut application: all-clusters-app
	
 **Expected behavior** :  Pass with status(0x0)

 **Actual behavior** : Fail with status 0x81(unsupported command) 

**Screenshot** : 
![image](https://user-images.githubusercontent.com/90545664/171565335-c3f28d64-ce58-4a27-86bb-10fd01c27a11.png)

**Test-plan reference** :
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/actions.adoc#tc-act-3-2-functionality-with-client-as-dut

**Spec reference** : 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/bridge-clusters.adoc

**Comment by andy31415** [comment]
@sowmyassp  what was the command executed? `mandatory attribute throws error` is somewhat vague. Could you also share the chip-tool commands used or at least the attribute names (at least one of them)

**Comment by andy31415** [comment]
Test plans may change. It would be useful to see list of commands in the issue itself so that we can reference them in case test plans are updated.

**Comment by andy31415** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/examples/all-clusters-app/all-clusters-common/all-clusters-app.matter#L4246 seems to claim that actionList and endpointList are available as a callback:

```
server cluster BridgedActions {
    callback attribute actionList;
    callback attribute endpointList;
    callback attribute setupUrl;
    ram      attribute featureMap;
    callback attribute clusterRevision default = 1;
}
```

guessing callback probably not properly implemented or missing.

**Comment by andy31415** [comment]
I also wonder if we should use all-clusters to test bridge as we have a dedicated bridge example.

**Comment by sowmyassp** [comment]
@andy31415 I actually run this commands in all-clusters-app, once I will run in bridge app if I face same issue I will raise an issue then now I will close this ticket, thank you
