### ISSUE TITLE
TrustedRootCertificates does not contain a newly-added root until after AddNOC

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#19066]
#### Problem
We read the TrustedRootCertificates attribute out of the fabric table, but we don't add roots to that until AddNOC.

 #### Proposed Solution
Maybe `OperationalCredentialsAttrAccess::ReadRootCertificates` should grab the root from `gFabricBeingCommissioned` if we're in a state where it's expected to have somethign?

@tcarmelveilleux

**Comment by woody-apple** [comment]
Spec Review: Same as #20791
