### ISSUE TITLE
[pre-sve] TC-I-2.3 Add implementation for Trigger effect command on TI platform all-clusters application

### ISSUE THREAD

**Issue by adabreuti** [project-chip/connectedhomeip#19060]
#### Problem
Currently, the all clusters app on CC13x2x7 returns INVALID_COMMAND for TC-I-2.3 as it is missing a a def

system configuration
- DUT used : CC13x2x7
- app use: all-clusters-app
- chip-tool commit id : https://github.com/project-chip/connectedhomeip/commit/425f1fb916ca154deeb75cd82cd5196778aba152 (pre-sve SHA)

![image](https://user-images.githubusercontent.com/76965454/171445384-a7134477-7003-4f6f-a06e-6734ba786839.png)

 #### Proposed Solution
Add default triggers trigger-effect

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @franck-apple to find an owner for this issue.

**Comment by adabreuti** [comment]
@woody-apple @franck-apple, I'm currently working on a fix for this issue which is specific to the cc13x2x7 platform.
