### ISSUE TITLE
Evaluate OTA Provider retry counter usage

### ISSUE THREAD

**Issue by carol-apple** [project-chip/connectedhomeip#19078]
#### Problem
The initial introduction of the `DefaultOTARequestorDriver::mProviderRetryCount` is to track how many times a provider has responded with `Busy` response. After some max retry has been attempted, the requestor should stop retrying and either move on to another provider (if one exists) or stop the OTA process. Over time, the code has changed a bit such that this counter now keeps track of every time a `QueryImage` is sent, regardless of whether it is due to the provider being busy or not.

Specifically, there could be a small window where the default provider responds with `Busy`, the requestor has transitioned to `Idle` state internally to wait for the next `QueryImage` and then an `AnnounceOTAProvider` occurs for a different provider. The current code would increment the counter, which may result in reaching the max retry faster than expected.

 #### Proposed Solution
Evaluate usage of `mProviderRetryCount` and make sure its meaning is consistent.

**Comment by isiu-apple** [comment]
We should also take into account that currently, we check `mProviderRetryCount` against `kMaxBusyProviderRetryCount` and move to next provider in the list only in`DefaultOTARequestorDriver::ScheduleQueryRetry()`.  We may want to consider a `mProviderRetryCount` per provider.
