### ISSUE TITLE
Wireshark dissector for CHIP payload

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [project-chip/connectedhomeip#1908]
#### Problem

It seems there is currently no Wireshark dissector for CHIP payload available/planned.

 #### Proposed Solution

Implement a dissector.

**Comment by yunhanw-google** [comment]
Weave have wireshark dissector, we potentially can apply it in CHIP
@turon @gerickson @robszewczyk @andy31415

**Comment by markus-becker-tridonic-com** [comment]
https://github.com/CHIP-Specifications/matter-dissector

**Comment by schadom** [comment]
> https://github.com/CHIP-Specifications/matter-dissector

Unfortunately the link is broken. Is there a Matter dissector for wireshark already?
