### ISSUE TITLE
[Thread plaatform] - Long Manual code is not printing in the device configuration while launching the all-clusters-app

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#19096]
**Problem** : 
21 digit manual code is not printing in the device configuration log when we launch all-cluster-app where instead we observe that, logs has, General QR Code and the manual 11 digit short code.

![image](https://user-images.githubusercontent.com/90545664/171606355-16244422-1461-4b90-ab3d-7c527ac23e0c.png)

**PFA Logs** : 
[Thread UART.txt](https://github.com/project-chip/connectedhomeip/files/8822761/Thread.UART.txt)

**Comment by bzbarsky-apple** [comment]
Which SHA is this on?  Which platform?  How was all-clusters-app compiled?

**Comment by bzbarsky-apple** [comment]
@sowmyassp Which SHA is this on? Which platform? How was all-clusters-app compiled?

Please always include that sort of information in bug reports.  Having to do a bunch of round-trips to get basic configuration information is a waste of everyone's time...

**Comment by sowmyassp** [comment]
@bzbarsky-apple I am sorry for that will make sure to provide required information on further issues

**Comment by bzbarsky-apple** [comment]
>  Platform - Thread plaatform

That's nrfconnect, I assume?

`examples/all-clusters-app/nrfconnect/main/AppTask.cpp` prints the onboarding code for the actual application configuration, which does not use custom flow commissioning and hence does not use a long manual code.  Why was there an expectation for a long manual code to be printed?

(`examples/platform/linux/AppMain.cpp` does print both codes, but it's not really clear to me why it does that.)
