### ISSUE TITLE
[Pre-SVE] all cluster app doorlock issue

### ISSUE THREAD

**Issue by HubertHugo** [project-chip/connectedhomeip#19097]
SHA: 425f1fb916ca154deeb75cd82cd5196778aba152
all-cluster-app
nRF52840
Chip tool returns failure when I try to lock/unlock the door. Lock state does not change. 

[doorlock_issue_DUT.log](https://github.com/project-chip/connectedhomeip/files/8822726/doorlock_issue_DUT.log)
[doorlock_issue_chip-tool.log](https://github.com/project-chip/connectedhomeip/files/8822727/doorlock_issue_chip-tool.log)

**Comment by cjandhyala** [comment]
@HubertHugo which test case is this scenario referred to? For Pre-SVE1, All the door lock tests are marked as 'Not Verifiable' as test plan/verification steps not ready. Pls do not test that feature. closing the ticket.
