### ISSUE TITLE
[TC-IDM-6.2]Chip-tool needs to provide a way to set a optional IsUrgent optional flag.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#19107]
**#### Problem**
The step is expecting Activate Event subscription from TH to DUT and change the attribute value to create subscribed event before minimuminterval with 'IsUrgent' flag specified for a particular event path in the EventPathIB.  Chip-tool needs to provide a way to set a optional IsUrgent optional flag. currently Chip-tool needs to provide a way to set a optional IsUrgent optional flag.
 
**System configuration:-**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID:4d84a4a978ffc867a62b9b15423a9b70d9cb993e
Dut application: all-clusters-app

**PFA screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/171645232-ea6343b6-56ba-4316-9dd6-d4bc34e148ff.png)

**Test-plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-6-2-events-subscribe-interaction-from-th-to-dut

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#eventpathib

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/19003 fixes this.
