### ISSUE TITLE
 Stop using signals for those faults, altogether, and move to a different notification means, like a pipe

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#19114]
#### Problem
Currently, we reuse signal to trigger the various event on the device, this mechanism has several restrictions.

We only have very limited signal on Unix, we may run out of available signal for all events
Signal can not pass additional parameter information other than the command itself
All signals have default actions, we overwrite those default behaviors, such as Ctrl+C can not terminate the program.

 #### Proposed Solution
Use named pipe instead of signal to trigger the event

**Comment by bzbarsky-apple** [comment]
@yufengwangca Please put in an actual problem description.  This issue is not actionable as it is...
