### ISSUE TITLE
Update MEI implementation to be spec compliant

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#19127]
#### Problem

With the change to the MEI spec to now include scoped identifiers in addition to standard/MC types, we need to validate and possibly update our existing SDK implementations + code-gen constructs to ensure they are compliant.

**Comment by andy31415** [comment]
I am unclear on the amount of change here - MEI defines what identifiers are, however from an internal SDK perspective it sounds like we should treat any number as acceptable and maybe add some range validations. 

Not having extra validation does not sound like blocking due to spec.

**Comment by andy31415** [comment]
Removing spec tag for now to soften the "blocker" status of this. I am unsure if this is actually for 1.0 anymore now that TestCluster is MEI and we have a sample MEI attribute in all clusters app.

**Comment by mrjerryjohns** [comment]
I think we've tackled all that is needed for v1.0.
