### ISSUE TITLE
[pre-sve]TC-DM-2.1 Failure - Ameba

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/connectedhomeip#19136]
#### Problem
SubscriptionsPerFabric is not returning default of 3 - Step 56 of test case
 * actual behavior
[1654216188.087692][82835:82840] CHIP:TOO:   CapabilityMinima: {
[1654216188.087760][82835:82840] CHIP:TOO:     CaseSessionsPerFabric: 3
[1654216188.087798][82835:82840] CHIP:TOO:     SubscriptionsPerFabric: 65506
[1654216188.087850][82835:82840] CHIP:TOO:    }
 * steps to reproduce
 *  ./chip-tool basic read capability-minima 1111 0
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
`InteractionModelEngine::GetMinSubscriptionsPerFabric` is broken.  It basically does:
```
  return static_cast<uint16_t>((GetReadHandlerPoolCapacity() - kReservedPathsForReads)/fabricCount);
```
`GetReadHandlerPoolCapacity()` is 48 for me.  kReservedPathsForReads is 9*16 = 144, so the subtraction underflows, etc.

But why are we subtracting paths from handlers anyway?  @erjiaqing

**Comment by woody-apple** [comment]
Cert Blocker Review: Closing as a dup of https://github.com/project-chip/connectedhomeip/issues/19535
