### ISSUE TITLE
  [TC-IDM-3.1]Chip-tool support needed to send a WriteRequest message from TH to DUT to write any attribute on two clusters.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#19139]
#### Problem
As per Test-Plan, test-step 15 says "DUT sends a WriteRequestMessage to the DUT to both the clusters with the appropriate dataversions(received in the previous step) to modify the value of an attribute ",
Chip-tool support needed to send a  WriteRequestMessage  from DUT  to TH to read any attribute on two clusters.

**PFA log below:-**
![image](https://user-images.githubusercontent.com/95841834/171798369-988c6ef3-f71c-4ce1-b13f-72a465be0953.png)

Spec Reference:-
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Interaction-Model.adoc#ref_WriteRequestAction

**Comment by bzbarsky-apple** [comment]
Sounds like this would need multi-path write support in chip-tool...

**Comment by woody-apple** [comment]
Cert Blocker Review: Marking cert blocker, assigning to @vivien-apple.

**Comment by vivien-apple** [comment]
Do we actually supports multiple writes in a single invoke in the SDK ? I thought it was not a v1.0 thing.
@mrjerryjohns @woody-apple ?

**Comment by bzbarsky-apple** [comment]
> Do we actually supports multiple writes in a single invoke in the SDK ?

We support multiple writes in a single write request message, yes.  We do not support multiple _commands_ in a single _invoke_.

**Comment by vivien-apple** [comment]
> > Do we actually supports multiple writes in a single invoke in the SDK ?
> 
> We support multiple writes in a single write request message, yes. We do not support multiple _commands_ in a single _invoke_.

I was wrong as you said. Supports is in #19139
