### ISSUE TITLE
The "constexpr CASEAuthTag IsValidCASEAuthTag(CASEAuthTag aCAT)" return type maybe bool

### ISSUE THREAD

**Issue by nykh2010** [project-chip/connectedhomeip#19145]
https://github.com/project-chip/connectedhomeip/blob/8dabae04c14c2b9382a83b60b3dd480de164d050/src/lib/core/CASEAuthTag.h#L97
The return type maybe bool.

**Comment by bzbarsky-apple** [comment]
Nice catch, thank you!

**Comment by emargolis** [comment]
Indeed! Thanks!
