### ISSUE TITLE
Lighting-app example missing Binding Cluster

### ISSUE THREAD

**Issue by pankore** [project-chip/connectedhomeip#19140]
#### Problem
According to spec, Binding Cluster is part of the Base Cluster Requirements and is mandatory for all device types.
Lighting-app example is missing this Binding Cluster

 #### Proposed Solution
Add binding cluster to lighting-app

**Comment by bzbarsky-apple** [comment]
> According to spec, Binding Cluster is part of the Base Cluster Requirements and is mandatory for all device types.

Where do you see that @pankore ?

"1.1.7. Base Cluster Requirements for Matter" in the device library says it's required for all device types _that include a client cluster_ and are simple device types.  Lighting app implements the "Dimmable Light" device type, for which the only client cluster is an optional "Occupancy Sensing" client.  And lighting app does not implement that client....  

That said, if https://github.com/project-chip/connectedhomeip/issues/19116 is fixed, then it would indeed need Binding.

**Comment by pankore** [comment]
Noted, closing this issue.
