### ISSUE TITLE
[TC-MC-6.4]Mediaplayback cluster-Values are mismatching with Expected outcome when TH send command to DUT.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#19148]
#### Problem
Values are mismatching with Expected outcome when TH send command to DUT. For example TH sends a FastForward command to the DUT, DUT  responds as success after if TH tries to read PlaybackSpeed attribute and CurrentState attribute from the DUT
It should response as 
![image](https://user-images.githubusercontent.com/95841834/171834198-633963ed-8971-4315-912c-109ea0e2a524.png)
**But currently DUT responding with same value for  all the commands(Rewind, Play, Pause, FastForward)** **after if TH tries to read PlaybackSpeed attribute and CurrentState attribute**

**Test-Plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/media.adoc#tc-mc-6-4-variable-speed-media-playback-verification

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/MediaPlayback.adoc#attributes

**PFA log below:-**
[[TC-MC-6.4].txt](https://github.com/project-chip/connectedhomeip/files/8831704/TC-MC-6.4.txt)

**Comment by chrisdecenzo** [comment]
this should now be addressed, thanks
