### ISSUE TITLE
[TC-MC-1.3] AttributeList and AcceptedCommandList value mismatch error

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#19150]
Summary:
As per Testplan [TC-MC-1.3] and spec
1. "AttributeList" expected value: [0,1,65528, 65529, 65531, 65532, 65533] but got value: [0,65528, 65529, 65531, 65532, 65533] 
2. "AcceptedCommandList" expected value: [0, 1, 2] but got value: [0]
when executed 
Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/171842539-d70645e3-72f3-422e-b14c-23a9e1f065b4.png)
![image](https://user-images.githubusercontent.com/102359958/171842631-1b7edf17-16fd-4364-850a-23f6dd5237e4.png)
Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/171842681-8ee589d5-68af-4709-beeb-407ae236f944.png)
![image](https://user-images.githubusercontent.com/102359958/171842714-f52713c6-1d80-4b11-83d9-8313b03066d2.png)
Execution logs:
![MC1_3_ACL](https://user-images.githubusercontent.com/102359958/171842753-7680eaab-978a-461b-8058-53a41ae29bc6.png)
[MC1_3_ACL.txt](https://github.com/project-chip/connectedhomeip/files/8831855/MC1_3_ACL.txt)
![MC1_3_AL](https://user-images.githubusercontent.com/102359958/171842781-8b1ed41d-ddd4-45b0-8144-7580da33e990.png)
[MC1_3_AL.txt](https://github.com/project-chip/connectedhomeip/files/8831859/MC1_3_AL.txt)

**Comment by bzbarsky-apple** [comment]
> AttributeList" expected value: [0,1,65528, 65529, 65531, 65532, 65533]

The attribute with id 1 is optional.  Why is the test plan requiring it to be present?  @manjunath-grl @cjandhyala

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @franck-apple to follow up to see if we can update the test plans here.

**Comment by franck-apple** [comment]
after discussion with @cjandhyala , assigning to @manjunath-grl for more information.

**Comment by manjunath-grl** [comment]
@bzbarsky-apple @franck-apple 1. AttributeList : we checked with QA team it is  passing for them we used same app and endpoint but we are observing missing Optional attribute, we are waiting on logs to investigate further 
2. AcceptedCommandList : commands are mandatory we got [0] but the expected value is [0,1,2] as per spec
Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/172654633-05b0558e-1180-46cb-9b86-6acc531b7bca.png)

**Comment by manjunath-grl** [comment]
@bzbarsky-apple @franck-apple tried in TOT its passing
1. SHA used: c1e1d018820c0fdd51f124f607b9207f31fae2ff
2. Client app: Tv-app
3. Server app: Chip-tool
[TC_MC_1_3.zip](https://github.com/project-chip/connectedhomeip/files/8890129/TC_MC_1_3.zip)

**Comment by bzbarsky-apple** [comment]
> Client app: Tv-app
> Server app: Chip-tool

I assume those are backwards...
