### ISSUE TITLE
[TC-MC-1.6] AttributeList and AcceptedCommandList value mismatch error

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#19152]
Summary:
As per testplan [TC-MC-1.6] 
"AttributeList" expected value: [0,1,2,65528, 65529, 65531, 65532, 65533] but got value: [0,65528, 65529, 65531, 65532, 65533]
"AcceptedCommandList" expected value: [0, 2, 3] but got value: [0,2]
when executed
Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/171845059-5191384f-f85b-40ed-acb1-a72b7bf77cb6.png)
![image](https://user-images.githubusercontent.com/102359958/171845097-b54aafb4-6bd5-4ef2-8063-e9c626b335fe.png)
Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/171845204-b1740996-7e86-40eb-b22b-45017074c1b8.png)
![image](https://user-images.githubusercontent.com/102359958/171845241-ba301f2a-94cc-422b-9741-af370a7c8962.png)
Execution logs:
![MC1_6_ACL](https://user-images.githubusercontent.com/102359958/171845261-59e61bac-8334-41a7-ae9c-c4aaae97eff3.png)
[MC1_6_ACL.txt](https://github.com/project-chip/connectedhomeip/files/8831947/MC1_6_ACL.txt)
![MC1_6_AL](https://user-images.githubusercontent.com/102359958/171845272-18112611-7ef8-42de-87dc-84c957ff2e38.png)
[MC1_6_AL.txt](https://github.com/project-chip/connectedhomeip/files/8831949/MC1_6_AL.txt)

**Comment by chrisdecenzo** [comment]
hi @manjunath-grl  What version of the example/tv-app were you using? Eg. was this latest TOT or TE9 or something else? When I run with TOT, I see all the attributes for these two clusters so trying to figure out what might be different in your environment

**Comment by manjunath-grl** [comment]
@chrisdecenzo i tested it in latest TOT against Tv-app in Linux system

**Comment by chrisdecenzo** [comment]
hi @manjunath-grl I see the top line in the txt files is:

~/CHIP/APR13/connectedhomeip

Can you please double check that you have mainline synced to TOT because these missing commands/attributes were fixed in a PR from May timeframe

**Comment by chrisdecenzo** [comment]
Specifically, this is fixed by https://github.com/project-chip/connectedhomeip/pull/18762
