### ISSUE TITLE
[TC-MC-1.7] AttributeList value mismatch error

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#19154]
Summary:
As per Testplan [TC-MC-1.7] and spec "AttributeList" expected value: [0,1,2,3,4,5,665528, 65529, 65531, 65532, 65533] but got value: [0,1,2,4,5,6,65528, 65529, 65531, 65532, 65533] value 3 (SampledPosition attribute) missing.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/171845888-34704756-0637-4e21-af48-fb055956be1e.png)
Spec screenshot:
![image](https://user-images.githubusercontent.com/102359958/171846183-c9aa9838-9c0d-42c3-a78f-c59d057ef3a1.png)
Execution logs:
![MC1_7_AL](https://user-images.githubusercontent.com/102359958/171846269-7b694a47-021c-430d-be0e-2bdad8af2563.png)
[MC1_7_AL.txt](https://github.com/project-chip/connectedhomeip/files/8832009/MC1_7_AL.txt)

**Comment by andy31415** [comment]
@manjunath-grl - what is the environment being tested? what app and what platform? https://github.com/project-chip/connectedhomeip/blob/master/docs/BUG_REPORT.md#environment-for-reproduction

**Comment by chrisdecenzo** [comment]
hi @manjunath-grl  What version of the example/tv-app were you using? Eg. was this latest TOT or TE9 or something else? When I run with TOT, I see all the attributes for these two clusters so trying to figure out what might be different in your environment

**Comment by manjunath-grl** [comment]
@chrisdecenzo i tested it in latest TOT against Tv-app in Linux system

**Comment by chrisdecenzo** [comment]
Specifically, this is fixed by https://github.com/project-chip/connectedhomeip/pull/18762

**Comment by chrisdecenzo** [comment]
Specifically, this is fixed by https://github.com/project-chip/connectedhomeip/pull/18762
