### ISSUE TITLE
[pre-sve] TC-MF-1.9 : DUT getting commissioned after 20 failed attempts 

### ISSUE THREAD

**Issue by chirag-silabs** [project-chip/connectedhomeip#19166]
#### Problem

TC-MF-1.9

* expected behavior
The test case to open a commissioning window using the first raspberry pi via, 
./chip-tool pairing open-commissioning-window 1 1 900 1000 3840

And entering the invalid code of the generated by chip-tool on second pi. It should fail with integrity check failed. Trying this 20 times and giving the correct pairing code on 21st attempt the commissioning should fail.

 * actual behavior
Commissioning seems to be passing on the 21st attempt on the 2nd pi.

 * system configuration
 Silabs DUT
 EFR32 + RS9116 
 EFR32 + WF200 
 * logs
 
[tc-mf-1.9(2).txt](https://github.com/project-chip/connectedhomeip/files/8832829/tc-mf-1.9.2.txt)
[tc-mf-1.9(1).txt](https://github.com/project-chip/connectedhomeip/files/8832830/tc-mf-1.9.1.txt)

**Comment by bzbarsky-apple** [comment]
> Trying this 20 times and giving the correct pairing code on 21st attempt the commissioning should fail.

No, it should not.  What should fail is the 21st PBKDFParamRequest message after 20 PASE setup failures.

But if the pairing code is failing integrity checks, there are no PASE attempts at all.

I just looked at the test plan, and it says to use an _incorrect_ setup code, not an _invalid_ one:

> Set up a TH_CR2 to start attempting to do PASE to DUT_CE and failing 20 times. This can be done using a valid manual code with an incorrect setupcode
