### ISSUE TITLE
[pre-sve] TC-TSTAT-2.1 DUT does not support all mandatory attribute for COOL HEAT and SCH

### ISSUE THREAD

**Issue by doublemis1** [project-chip/connectedhomeip#19185]
#### Problem
all cluster app
nrf52840
revision: https://github.com/project-chip/connectedhomeip/commit/425f1fb916ca154deeb75cd82cd5196778aba152

DUT's featuremap is set to 11 (001011) which means that shall support COOL, HEAT, SCH feature.
```
[1654267195.246615][103315:103320] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0201 Attribute 0x0000_FFFC DataVersion: 291366424
[1654267195.246653][103315:103320] CHIP:TOO:   FeatureMap: 11
```
But following that featuremap, device does not support mandatory attributes:
* UnoccupiedCoolingSetpoint COOL & HEAT
* UnoccupiedHeatingSetpoint COOL & HEAT

**Comment by bzbarsky-apple** [comment]
>   UnoccupiedCoolingSetpoint COOL & HEAT
>   UnoccupiedHeatingSetpoint COOL & HEAT

@doublemis1 Where does that come from?  The spec has "COOL & OCC" and "HEAT & OCC" for those two attributes' conformance, and the cluster does not claim support for OCC.

**Comment by doublemis1** [comment]
Ohh sorry, my mistake. Thanks for check
