### ISSUE TITLE
Move the qr code generated from the sdk at https://dhrishi.github.io/connectedhomeip/ to a more formal location :)

### ISSUE THREAD

**Issue by nivi-apple** [project-chip/connectedhomeip#19199]
#### Problem
The current qr code url points to  https://dhrishi.github.io. I had a discussion a while back with Woody to request this change. :)
It would be good to move it to a more formal (for lack of a better term) location

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by dhrishi** [comment]
#3266

**Comment by dhrishi** [comment]
@nivi-apple This is done now!
