### ISSUE TITLE
Test case for devices with multiple instances of the same device type

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#19209]
Is there a test case for something like a single light device with four independently controllable bulbs? Each bulb would be on its own end_point but the all EPs have the same device type. This is needed to ensure that controllers don't make an assumption of only one copy of a device type per device when it is legal to have many.  A parallel case would be a single device implementing multiple light switches. Just want to make sure this is tested for since controllers could easily make a one to one assumption instead of one to many.

A specific hardware example: LED string light controllers that control multiple, independent strings.  It would have a single IP address with four color light EPs.

**Comment by MonicaisHer** [comment]
I am also facing this issue using [examples/lighting-app/python](https://github.com/project-chip/connectedhomeip/tree/master/examples/lighting-app/python).
