### ISSUE TITLE
M1 Mac Build issue

### ISSUE THREAD

**Issue by raman325** [project-chip/connectedhomeip#19215]
#### Problem

Follow the wiki here: https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md

at `ninja -C out/host` see the following: https://rentry.co/b5nu4

It appears my laptop wants to target the x86_64 architecture even though I am running an arm64 architecture. I tried setting the `target_cpu` option to no avail. Any suggestions on how to resolve?

**Comment by bzbarsky-apple** [comment]
Duplicate of #19134

**Comment by raman325** [comment]
thanks for the heads up, I will track this in the other issue
