### ISSUE TITLE
[pre-sve] [TC-GC-1.1]General commissioning cluster---Value mismatch for FeatureMap attribute

### ISSUE THREAD

**Issue by AlvinHsiao** [project-chip/connectedhomeip#19218]
Problem

As per test plan [TC-GC-1.1] FeatureMap attribute showing value mismatch error when executed, DUT should
responds with feature map value 0 but currently DUT responding feature map value has 6.

expected behavior:-FeatureMap attribute value should be bit 0.
actual behavior:- DUT responds has bit 6
steps to reproduce:-./chip-tool generalcommissioning read feature-map 2 0

system configuration
- Chip-Tool: RPI
- DUT used : Infineon CYW30739
- app use: lighting-app
- chip-tool and DUT commit id : https://github.com/project-chip/connectedhomeip/commit/425f1fb916ca154deeb75cd82cd5196778aba152 (pre-sve SHA)

logs
- [TC-GC-1.1.txt](https://github.com/project-chip/connectedhomeip/files/8842586/TC-GC-1.1.txt)

**Comment by bzbarsky-apple** [comment]
Looks similar to https://github.com/project-chip/connectedhomeip/issues/18028 but for lighting-app.
