### ISSUE TITLE
Make `OperationalDeviceProxy` shareable by multiple applications, and delivers its callbacks to multiple applications

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#19259]
#### Problem
* 1: ~~If an application context is released before the pairing completes, will render the pointer passed into `OnDeviceConnected` dangling~~
* 2: in `OperationalDeviceProxy::DequeueConnectionCallbacks` we may use member fields which is already destructed
  * `cb->mCall(cb->mContext, mPeerId, error)`
    * We are loop for all callbacks here, but `this` object may already destructed by previous callback, so `mPeerId` may not valid here
  * `cb->mCall(cb->mContext, this)`
    * Obviously, `this` may not valid here

 #### Proposed Solution
* ~~Implement a type-safe and RAII style callback queue using `IntrusiveList` to solve problem 1~~ 
* When implementing `DequeueConnectionCallbacks`, split the function into 2 parts:
  1. Move the callback queue to a stack variable
  2. Use an static member function to call all callback, to ensure that no member fields is used

**Comment by bzbarsky-apple** [comment]
The plan is to stop passing `this` to the callbacks altogether and just pass the session handle, right?  So problem 1 is not worth worrying about, I suspect.

The use of `mPeerId` is a problem; very good catch there.  Factoring out the callback-calling into a static function to avoid those problems seems good.

**Comment by kghost** [comment]
In `DeviceCommissioner::OnDeviceConnectedFn`, `this` (an `OperationalDeviceProxy`) is being used. So, problem 1 still need some attention.

**Comment by bzbarsky-apple** [comment]
> The context pointer in the callback is dangling, calling the callback after its context is released will yield pretty bad result.

Anything that releases the context should Cancel() the callback, no?  That's why we are using cancelables here....  I thought you meant the pointer to the OperationalDeviceProxy could dangle, for point 1.

> In DeviceCommissioner::OnDeviceConnectedFn, this (an OperationalDeviceProxy) is being used. So, problem 2.2 still need some attention.

Problem 2.2 is what "just pass in the session instead" will solve, right?

> I'm really frustrated dealing with object freeing itself inside its member function

Sure.

> can we just give OperationalDeviceProxy a reference counter and call it a day ?

Again, the plan is to not have OperationalDeviceProxy _at all_.

**Comment by kghost** [comment]
@bzbarsky-apple When trying to solve problem 2.2, the `OperationalDeviceProxy` object is passed to `ClusterBase::Associate` which assigned to `ClusterBase::mDevice`.

So I have to change `mDevice` to a session handle, this should be a straightforward and simple change, but not small. Also need to add a member of pointer to `ExchangeManager` to `ClusterBase`, which may impact memory usage.

**Comment by mrjerryjohns** [comment]
I'm labelling this 1.0 since this will become more imperative when we have multiple consumers of `OperationalDeviceProxy` in the SDK (IM will be one of them...)

**Comment by bzbarsky-apple** [comment]
@kghost Just to allay the ClusterBase concern: those are stack-only objects in practice.

**Comment by mrjerryjohns** [comment]
This is not completed. #19673 just unblocks the core work for this issue.

**Comment by mrjerryjohns** [comment]
As part of addressing this, we should also remove `CASESessionManager::Release*` APIs as well.

**Comment by woody-apple** [comment]
SVE/Cert Blocker Review: Does not appear to be blocking a test case, removing SVE.
