### ISSUE TITLE
MF-10 and MF-1.9 tests failes for Darwin(no-ble-asan) showing Invalid PASE parameter

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#19276]
Summary:
As per testplan TC-MF-1.10 TH start attempting to do PASE to DUT_CE and failing 20 times for Invalid payload value but  Test Suites - Darwin (no-ble-asan) seems to be failing showing that Invalid PASE Parameter for PR https://github.com/project-chip/connectedhomeip/pull/18521

Execution logs:
![image](https://user-images.githubusercontent.com/102359958/172434881-4b278058-ade0-4441-893d-63c65532a1ce.png)
![image](https://user-images.githubusercontent.com/102359958/172434690-66293d50-eb3c-4a04-8e7a-02197e247a13.png)
[logs_1075704.zip](https://github.com/project-chip/connectedhomeip/files/8854977/logs_1075704.zip)

**Comment by manjunath-grl** [comment]
> @manjunath-grl So this is for darwin-framework-tool and specifically for using `PairWithCode` with an incorrect code?

@bzbarsky-apple yes

**Comment by manjunath-grl** [comment]
> @manjunath-grl I can't reproduce this.  I pulled the code for PR https://github.com/project-chip/connectedhomeip/pull/18521 and ran:
> ```
> ./scripts/run_in_build_env.sh "./scripts/tests/run_test_suite.py --chip-tool ./out/debug/standalone/darwin-framework-tool --target Test_TC_MF_1_10 run --iterations 1 --all-clusters-app ./out/debug/standalone/chip-all-clusters-app"
> ```
> and it passed fine for me....

I disabled the tests MF-1.10 and MF-1.9 from Darwin tests.js as per @raju-apple request can you please enable them and test it.

**Comment by bzbarsky-apple** [comment]
I pulled the PR before you did that, so I don't have the test disabled.  It just passes.

**Comment by bzbarsky-apple** [comment]
@manjunath-grl As in the CI failed?

**Comment by bzbarsky-apple** [comment]
Note that the bits about "invalid PASE parameter" are absolutely expected.  What's not necessarily expected is a OnPairingComplete call with error after that.

**Comment by bzbarsky-apple** [comment]
@manjunath-grl I tried taking your PR and re-enabling the Darwin tests, then running CI and I do see it fail.  I wonder why I can't reproduce that locally...

**Comment by bzbarsky-apple** [comment]
Ah, interesting, that failure is in MF-1.9, not MF-1.10.  All the text above claimed the failure was in MF-1.10.

But locally I can't reproduce the failure in MF-1.9 either.

**Comment by bzbarsky-apple** [comment]
Still can't reproduce this locally, but the linked PR fixes it in CI...
