### ISSUE TITLE
Unable to clear fabric from credential - error noticed when trying to unpair M5 board

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#19322]
With SHA 5362125e31b8bdd7b2dddb2da381eb7bffe80f73

Unpair of M5 board throws -> "Unable to clear fabric from credential" error

**Steps to reproduce**

1. Install and launch chiptool app on iOS
2. Make sure M5 board is flashed
3. Pair M5 board with chipTool app by scanning QR code or by using short pin
4. Select Unpair Devices on chiptool app
5. Choose Unpair Devices

**Note:** Unpair still works but error is noticed

Attaching the complete logs from M5 board:
[unpairErrorLogs.txt](https://github.com/project-chip/connectedhomeip/files/8863377/unpairErrorLogs.txt)

**Comment by bzbarsky-apple** [comment]
This looks like door lock bits.  @Morozov-5F could you take a look please?

**Comment by bzbarsky-apple** [comment]
And in particular, it does not make sense to log errors in this loop:
```
    for (uint16_t userIndex = 1; userIndex <= maxNumberOfUsers; ++userIndex)
    {
        EmberAfPluginDoorLockUserInfo user;
        if (!emberAfPluginDoorLockGetUser(endpointId, userIndex, user))
        {
            ChipLogError(Zcl,
                         "[OnFabricRemoved] Unable to get the user - internal error [endpointId=%d,fabricIndex=%d,userIndex=%d]",
```
because not having all slots filled with users is _normal_, no?  But maybe the real issue here is just the bogus lock delegate in all-clusters-app?

Similar for this loop:
```
    for (uint16_t credentialIndex = startIndex; credentialIndex <= maxNumberOfCredentials; ++credentialIndex)
    {
        EmberAfPluginDoorLockCredentialInfo credential;
        if (!emberAfPluginDoorLockGetCredential(endpointId, credentialIndex, credentialType, credential))
        {
            ChipLogError(
```

**Comment by Morozov-5F** [comment]
@bzbarsky-apple the door lock cluster expects that the `emberAfPluginDoorLockGetUser` and such return `false` only in case when the error occurred, when the user is missing it should be specified in the `userStatus` field of the `user`. This is [outlined](https://github.com/project-chip/connectedhomeip/blob/de9e9076303a11c568d2533b3e624a96db366dae/src/app/clusters/door-lock-server/door-lock-server.h#L787) in the function doxygen but in a twisted way, I admit.

@phonnakasturi-apple regarding the issue, if that was an `all-clusters-app` for esp32 then it is because those callbacks are not implemented and they return `false` by default.

**Comment by bzbarsky-apple** [comment]
@Morozov-5F Perhaps the all-clusters-app callbacks should be changed to just return all users as not there instead of false?  And similarly for credentials?

Alternately, it could return 0 for max numbers of users/credentials supported?

**Comment by Morozov-5F** [comment]
@bzbarsky-apple yeah, that's a great idea. Actually, I just realized that Linux all-clusters-app borrows the lock implementation from the Linux lock-app. Maybe we can make a minimal shared lock implementation for all-clusters-app?

**Comment by bzbarsky-apple** [comment]
> Maybe we can make a minimal shared lock implementation for all-clusters-app that could be fit into more constrained platforms as well?

That would be pretty nice if we find the time, obviously, but for now we should just try to get to the point where all-clusters-app at least is not violating the spec, if we can do it easily.
