### ISSUE TITLE
`strncpy` Max Copy Length Does Not Always Copy Null Terminator

### ISSUE THREAD

**Issue by robszewczyk** [project-chip/connectedhomeip#19339]
#### Problem
In some instances of `strncpy`, the string can fill up the entire destination buffer while dropping the terminating `NUL` character.  

Some examples: 
src/controller/CommissionerDiscoveryController.cpp
src/platform/P6/BLEManagerImpl.cpp
src/protocols/user_directed_commissioning/UDCClientState.h
src/lib/dnssd/Resolver_ImplMinimalMdns.cpp
src/lib/dnssd/Discovery_ImplPlatform.cpp

 #### Proposed Solution
Audit code and:
* add a terminating `NUL` regardless of execution, 
* (optionally) set the length of bytes to copy to `sizeof(dst) - 1`

**Comment by bzbarsky-apple** [comment]
We should not be using `strncpy` at all. We should be using `CopyString`.
