### ISSUE TITLE
ASN1 Integer Overflow in `ASN1Reader::Next()`

### ISSUE THREAD

**Issue by robszewczyk** [project-chip/connectedhomeip#19336]
#### Problem

In `ASN1Reader.cpp` the following code does not consider integer overflow:

````
    CHIP_ERROR ASN1Reader::Next()
    {
        ReturnErrorCodeIf(EndOfContents, ASN1_END);
        ReturnErrorCodeIf(IndefiniteLen, ASN1_ERROR_UNSUPPORTED_ENCODING);
        mElemStart += (mHeadLen + ValueLen);
        ResetElementState();
        ReturnErrorCodeIf(mElemStart == mContainerEnd, ASN1_END);
        return DecodeHead();
    }
````

Because the variables `mHeadLen` and `ValueLen` are both typed `uint32_t` their sum can
wrap around, incrementing `mElemStart`  by an incorrect value.

When `ASN1Reader::Next()` is called in a loop and `mElemStart` is incremented by `0`, this will
result in an infinite loop. This is the case for `DumpASN1()` , and it might also be for `ChipDN::DecodeFromASN1()` and `ConvertExtensions()` .

#### Proposed solution
If either of the variables is casted to `size_t` , an overflow would not happen. Alternatively,
if either of the two variables is declared as `size_t` , an overflow would not happen either.

**Comment by emargolis** [comment]
Closing with #19627
