### ISSUE TITLE
linux: delete the dbus generated files

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#1936]
Ack, will do after we finalize the WiFi support

_Originally posted by @yufengwangca in https://github.com/project-chip/connectedhomeip/pull/1909#discussion_r463410990_

**Comment by mspang** [comment]
GN build generates these files on the fly. Once automake is removed they can be deleted.

**Comment by yufengwangca** [comment]
@mspang 
What files need to be deleted since those files are generated during the build in GN?

    Linux/gen/DBusWpa.c                   \
    Linux/gen/DBusWpaInterface.c          \
    Linux/gen/DBusWpaNetwork.c            \

I noticed, we checked in DbusBluez.c source to CHIP, and this file should also get generated in run-time. We need to fix this issue to make BLE and WIFI consistent

**Comment by Itz-RogueX** [comment]
I'll do it.
