### ISSUE TITLE
[build] submodule sync issue in third_party/cyw30739_sdk/repos/30739A0

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#19412]
#### Problem

Rebase or fresh clone top-of-tree and run `./gn_build.sh` fails with:

```
fatal: remote error: upload-pack: not our ref ab7601a74bdffc7374353c1e19b22388bb3dcedd
fatal: Fetched in submodule path 'third_party/cyw30739_sdk/repos/30739A0', but it did not contain ab7601a74bdffc7374353c1e19b22388bb3dcedd. Direct fetching of that commit failed.
```

Perhaps the repo was renamed from https://github.com/Infineon/30739A0.git 
to  https://github.com/Infineon/OT-Matter-30739A0.git but that didn't get changed in the matter submodule config?

Related issues:
https://github.com/Infineon/TARGET_CYW930739M2EVB-01.git --> https://github.com/Infineon/OT-Matter-TARGET_CYW930739M2EVB-01.git

**Comment by turon** [comment]
@hsusid

**Comment by hsusid** [comment]
Try to do `git submodule sync` and then do `git submodule update`.
