### ISSUE TITLE
Sort out what we should do with ember event control bits

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#1944]
#### Problem
In the initial landing in #1609, we commented out calls to `emberEventControlSetInactive`, `emberEventControlGetActive`, `emberEventControlSetActive` in `util.c`.

 #### Proposed Solution
Figure out what use case that system is addressing and how to address those in CHIP.

@tecimovic @wehale @selissia @bhaskar-apple @rwalker-apple

**Comment by vivien-apple** [comment]
#3570 should add the last part of this issue by implementing  `emberEventControlGetActive` since the other methods has been added by #2915
