### ISSUE TITLE
[pre-sve] After bringing DUT into a state so that StateValue is TRUE, the value is not reflected in state attribute of Boolean State Cluster

### ISSUE THREAD

**Issue by PSONALl** [project-chip/connectedhomeip#19455]
#### Problem
In TC-BOOL-2.2 in step 4d and 4e:
 * expected behavior
      - After manually bringing DUT into a state so that StateValue is TRUE when we read state attribute it should be true
 * actual behavior
      - there is no change in state

 * system configuration
          -  DUT used : ESP32 
        -  app use: all-clusters-app
        - chip-tool and DUT commit id : 425f1fb916ca154deeb75cd82cd5196778aba152 (pre-sve SHA)
        
 * logs:
       - esp32: [esp32.txt](https://github.com/project-chip/connectedhomeip/files/8878608/esp32.txt) 
       - chip-tool: [th.txt](https://github.com/project-chip/connectedhomeip/files/8878611/th.txt)

**Comment by bzbarsky-apple** [comment]
@PSONALl What steps were used to "manually bring DUT into a state so that StateValue is TRUE"?  I am guessing those steps are not right, but it's hard to say without knowing what they were.

**Comment by franck-apple** [comment]
Bumping this issue to cert blocker as it's a request cert blocker discovered during pre-SVE tests.

**Comment by andy31415** [comment]
assigning to PSONALI for adding addiontal info: please describe all steps to reproduce the issue. Specifically here we are missing at least the how to "manually bringing DUT into a state so that StateValue is TRUE "

**Comment by andy31415** [comment]
Also please add how the `read attribute` is done (what attribute, what command, what endpoint...).

**Comment by PSONALl** [comment]
@andy31415 for bringing DUT to true state I used cli option on DUT side to set attribute to true and reading the attribute with this command: `./chip-tool booleanstate read state-value 1 1`

**Comment by bzbarsky-apple** [comment]
>  I used cli option on DUT side to set attribute to true 

Could you please describe the _exact_ commands you ran so that someone else, who is possibly not familiar with the setup, can try to reproduce your steps?

Because again, the working assumption is that this is where the issue is, but it's really hard to tell with the provided info.

**Comment by vivien-apple** [comment]
Looking at the test plan, those steps are gated behind a PICS code: `M.ManuallyControlled` which is defined as: 
```Can the StateValue attribute be changed by manual operation at the DUT?```

The only place where I can see code  referencing `StateValue`is in the all-clusters-app (and the minimal version too) at https://github.com/project-chip/connectedhomeip/blob/f188fd9625f171a7d32a4b8e4a00d6abf60af891/examples/all-clusters-minimal-app/esp32/main/DeviceWithDisplay.cpp#L538

But I don't see any code to toggle it...

**Comment by PSONALl** [comment]
> But I don't see any code to toggle it...

I had added a cli option to set an attribute to true on my own let me check that patch again and I will update here soon

**Comment by PSONALl** [comment]
Tried changing state through CLI on DUT side on pre-sve week 2 SHA and this test case worked for me, so closing this issue
