### ISSUE TITLE
[pre-sve] TC-TSTAT-2.2 Write for Thermostat cluster command in correct range returns constraint error , if performed after write above max

### ISSUE THREAD

**Issue by mkleszcz-no** [project-chip/connectedhomeip#19468]
all-cluster-app
nrf52840dk
revison: https://github.com/project-chip/connectedhomeip/commit/5d8599d195a93dfe5473f64e4f888c322e5df1d2

Step 2c:
Write command should succeed without an error - it returns CONSTRAINT_ERROR.
It doesn't matter, if THC tries to write OccupiedCoolingSetpoint below the MinCoolSetpointLimit or above the MaxCoolSetpointLimit in the previous step (2b)

logs:
[TC_TSTAT_2_2_nRF.log](https://github.com/project-chip/connectedhomeip/files/8880144/TC_TSTAT_2_2_nRF.log)
[TC_TSTAT_2_2_nRF_DUT.log](https://github.com/project-chip/connectedhomeip/files/8880123/TC_TSTAT_2_2_nRF_DUT.log)

**Comment by bzbarsky-apple** [comment]
@mkleszcz-no This is not actionable as filed.  The harness log has all the bits about what it's actually sending the to DUT stripped out, and the DUT has verbose logging disabled so does not show what it received from the harness.

The operating assumption is that the harness is in fact sending an invalid value to the DUT, because some test script is broken.

Please attach complete logs when reopening.

**Comment by bzbarsky-apple** [comment]
That said, if this bit in the log:
```

[1654873233.271568][102634:102640] CHIP:TOO:   min cool setpoint limit: 1600
[1654873234.618158][102643:102649] CHIP:TOO:   max cool setpoint limit: 3200
[1654873235.968150][102650:102656] CHIP:TOO:   occupied cooling setpoint: 2600
[1654873238.632098][102665:102671] CHIP:TOO:   occupied heating setpoint: 2200
```
is showing the values currrently set on the server, and in step 2c we are to set OccupiedCoolingSetpoint to 1600 (the min cool setpoint limit), then given that all-clusters-app supports AUTO I expect the problem is that 1600 is below what OccupiedHeatingSetpoint is set to (2200), which is not allowed per spec.

**Comment by bzbarsky-apple** [comment]
Filed https://github.com/CHIP-Specifications/chip-test-plans/issues/1456 on the test plan.

**Comment by mkleszcz-no** [comment]
@bzbarsky-apple 

Thank you for your note about AUTO mode feature, it was my fault that I didn't see it before.
However I tried to run this test again bearing this in mind and I found another issue.

In accordance with spec:
`• MinCoolSetpointLimit <= OccupiedCoolingSetpoint <= MaxCoolSetpointLimit`

What's more if AUTO:
`• OccupiedHeatingSetpoint <= (OccupiedCoolingSetpoint - MinSetpointDeadBand)`

When I'm trying to execute step 2c my values are:

> min cool setpoint limit: 1600
> occupied heating setpoint: 2200
> max cool setpoint limit: 3200
> min setpoint dead band: 25


It means, that new OccupiedCoolingSetpoint value should be in range:
`2225 <= OccupiedCoolingSetpoint <= 3200`
otherwise I should get CONSTRAINT_ERROR

The problem is that the test succeed if I'm trying to write values in range 2200-3200.
**In this case writing value that is below 2225 is not allowed per spec.**

Steps:
1. all-clusters-app supports AUTO
2. Read current values of OccupiedHeatingSetpoint, minSetpointDeadBand
3. Try to write OccupiedCoolingSetpoint value above OccupiedHeatingSetpoint and below (OccupiedHeatingSetpoint + minSetpointDeadband)

logs:
[TC_TSTAT_2_2_nRF.log](https://github.com/project-chip/connectedhomeip/files/8889812/TC_TSTAT_2_2_nRF.log)
[TC_TSTAT_2_2_nRF_DUT.log](https://github.com/project-chip/connectedhomeip/files/8889813/TC_TSTAT_2_2_nRF_DUT.log)
[TC_TSTAT_2_2_nRF_verbose_logging.log](https://github.com/project-chip/connectedhomeip/files/8889814/TC_TSTAT_2_2_nRF_verbose_logging.log)

**Comment by bzbarsky-apple** [comment]
@mkleszcz-no Nice catch!  I filed https://github.com/project-chip/connectedhomeip/issues/19551 to track that problem, along with analysis.
