### ISSUE TITLE
Objective-C Framework: We need a way to cancel subscriptions for specific attributes.

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#19471]
#### Problem
It currently is possible to subscribe to attributes in the Objective-C framework, but currently there is not way to cancel the subscription. We need an API that will allow for cancellation of the targeted subscription. Once this API is added, we will need to add it to out cleanup.

Additional Suggestion: Add an additional API to cancel all subscriptions. For example, a user subscripts to attribute A, B, C, D and wants only E would do the following `cancelAll -> subscribe(E)` instead of `cancel(A) -> cancel(B) -> cancel(C) -> cancel(D) -> subscribe(E)`

 #### Proposed Solution
See above.

**Comment by bzbarsky-apple** [comment]
The specific-attribute APIs currently use SDK APIs that do not allow canceling the subscription....

**Comment by bzbarsky-apple** [comment]
@krypton36 Is this still an issue now that controller shutdown shuts down all subscriptions?

**Comment by krypton36** [comment]
This is no longer an issue. closing.
