### ISSUE TITLE
[pre-sve] DGSW-2.3 reset-watermarks command is supported while FeatureMap = 0

### ISSUE THREAD

**Issue by mkleszcz-no** [project-chip/connectedhomeip#19524]
all-cluster-app
nrf52840dk
revison: https://github.com/project-chip/connectedhomeip/commit/5d8599d195a93dfe5473f64e4f888c322e5df1d2 

#### Problem
Step 2a
It needs to be decided if we want to support reset-watermarks command.
Now FeatureMap = 0, therefore we shouldn't support reset-watermarks command (expected outcome ex. "unsupported_command")- now it returns failure.
The remaining steps in the test depends on this step.

logs:
[TC_DGSW_2_3_nRF.log](https://github.com/project-chip/connectedhomeip/files/8890777/TC_DGSW_2_3_nRF.log)
[TC_DGSW_2_3_nRF_DUT.log](https://github.com/project-chip/connectedhomeip/files/8890778/TC_DGSW_2_3_nRF_DUT.log)

**Comment by bzbarsky-apple** [comment]
Feature map was fixed in https://github.com/project-chip/connectedhomeip/pull/19195
