### ISSUE TITLE
 Unable to find current revision in submodule path 'third_party/mbed-os/repo'

### ISSUE THREAD

**Issue by quyennguyenvan** [project-chip/connectedhomeip#19574]
Current checkout to commit ID: 4d50b1084 
and have to do with the command: git submodule update --init

and meet this issue: 
`fatal: Needed a single revision
fatal: Unable to find current revision in submodule path 'third_party/mbed-os/repo'
`

**Comment by bzbarsky-apple** [comment]
@quyennguyenvan Does `git submodule sync --recursive` help?

**Comment by quyennguyenvan** [comment]
> @quyennguyenvan Does `git submodule sync --recursive` help?

it does not work!
