### ISSUE TITLE
Expose BDX on Darwin

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#19590]
#### Problem
Remaining work is to expose BDX to Darwin

**Comment by TheWalkingDead1024** [comment]
when Darwin API will support firmware update?

**Comment by TheWalkingDead1024** [comment]
> The following are some PRs that track support for Darwin API: #20295 #20516 #20517
> 
> There is still some bits missing related to exposing BDX which is being added soon.

hello，any updates？

**Comment by vivien-apple** [comment]
#21161 should fix this issue.

**Comment by carol-apple** [comment]
@vivien-apple Also added https://github.com/project-chip/connectedhomeip/pull/21235

**Comment by woody-apple** [comment]
Resolved
