### ISSUE TITLE
Actions Cluster - SDK needs to implement the Mandatory commands

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#19612]
**Problem:**
While Executing the behavior of the non-global commands of the Actions cluster, mandatory attribute throws error code as 0x81(unsupported command).

**Commit used** : c1e1d018820c0fdd51f124f607b9207f31fae2ff			

- Chip-tool - RPI-4, 8GB RAM
- DUT - RPI - RPI-4, 8GB RAM
- Platform : linux platform
- Dut application: bridge-app

**Expected behavior** : Pass with status(0x0)

**Actual behavior** : Fail with status 0x81(unsupported command)
![image](https://user-images.githubusercontent.com/90545664/173783104-2e155523-05de-4c92-b071-ad3a954fd040.png)

**Steps to reproduce** : 
1.  ./chip-tool bridgedactions  start-action  0 1 1
2. ./chip-tool bridgedactions  instant-action  0 1 1
3. ./chip-tool bridgedactions  stop-action  0 1 1
4. ./chip-tool bridgedactions  pause-action  0 1 1
5. ./chip-tool bridgedactions  resume-action  0 1 1
6.  ./chip-tool bridgedactions  enable-action  0 1 1
7.  ./chip-tool bridgedactions  disable-action  0 1 1
8. ./chip-tool bridgedactions start-action-with-duration 0 1 1 1
9.  ./chip-tool bridgedactions instant-action-with-transition 0 1 1 1
10.  ./chip-tool bridgedactions pause-action-with-duration 0 1 1 1
11.  ./chip-tool bridgedactions enable-action-with-duration 0 1 1 1
12.  ./chip-tool bridgedactions disable-action-with-duration 0 1 1 1

**Test-plan reference** :
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/actions.adoc#tc-act-3-2-functionality-with-client-as-dut

**Spec reference** :
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/bridge-clusters.adoc

**Comment by bzbarsky-apple** [comment]
In particular, the spec says "desc" for conformance for all these commands, and the prose says:

> Conformance: a server SHALL support a command when it is listed in the SupportedCommands data field of one or more actions listed in the ActionList provided by the server.

In this case the ActionList is an empty list.
