### ISSUE TITLE
Test_TC_CGEN_2_1.yaml BasicCommissioningInfo should not use specific hardcoded values

### ISSUE THREAD

**Issue by tehampson** [project-chip/connectedhomeip#19620]
#### Problem
After https://github.com/project-chip/connectedhomeip/pull/19582 this xml looks like
```
          value:
              {
                  FailSafeExpiryLengthSeconds: 60,
                  MaxCumulativeFailsafeSeconds: 900,
              }
```

While these are the default values they are not the required values and cert testing should just make sure that these fields are populated with some value greater than 0

**Comment by bzbarsky-apple** [comment]
@kowsisoundhar12 please take a look?

**Comment by raju-apple** [comment]
Currently looks like we don't have a way to check the range within a struct value in yaml (https://github.com/project-chip/connectedhomeip/issues/17997) , But for now we can put up a manual user prompt just for this step for the user to validate its within the range and not checking a specific value. @kvikrambhat Can you please put the PR for this modified script once its up please ?
