### ISSUE TITLE
TC-SU-2.2 - UpdateAvailable is fails to send the image transfer after 3 minutes [180 sec] 

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#19632]
**Problem:**
TC-SU-2.2 step no-4 UpdateAvailable is fails to send the  image transfer after 3 minutes ,while sets the DelayedActionTime to 3 minutes.But the image transfer is happening without any time delay.

**Proposed solution:**
While set the DelayedActionTime to 3 minutes it should transfer the image after the 3 minutes.

Commit used: c1e1d018820c0fdd51f124f607b9207f31fae2ff
Device used : Raspi 

**Steps used:**
**Provider:**
STEP-1:
 ./chip-ota-provider-app --discriminator 3840 --KVS ~/provider/chip_kvs_provider --filepath  ota-requestor-app.ota -q updateAvailable -t 180

**Chip-tool:**
STEP-2: 
./chip-tool pairing onnetwork-long 123 20202021 3840

STEP-4:
./chip-tool pairing onnetwork-long 321 20202021 3841 

STEP-5:
 ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": [321], "targets": null}]' 123 0

STEP-6:
./chip-tool otasoftwareupdaterequestor announce-ota-provider 123 0 0 0 321 0

**Requestor:**
STEP-3:
./chip-ota-requestor-app --discriminator 3841 --secured-device-port 5541 --KVS ~/requestor/chip_kvs_requestor --periodicQueryTimeout 86300 --otaDownloadPath ota-requestor-app.ota  --autoApplyImage --watchdogTimeout 86400 

Here I attached the logs for your reference:

[TC-SU-2.2 UA - OTA-PRO.txt](https://github.com/project-chip/connectedhomeip/files/8911867/TC-SU-2.2.UA.-.OTA-PRO.txt)
[TC-SU-2.2 UA-OTA-REQ.txt](https://github.com/project-chip/connectedhomeip/files/8911869/TC-SU-2.2.UA-OTA-REQ.txt)

**Comment by isiu-apple** [comment]
There has been a recent spec change:

`The DelayedActionTime field SHALL only be present if the Status field is set to Busy.`

OTA Test plan was updated to account for recent spec changes - https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5248
And this test case has been removed as a part of this change.
Plz refer to the latest Test plan here - https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/softwareupdate.adoc

See similar issue that was closed: https://github.com/project-chip/connectedhomeip/issues/19518
