### ISSUE TITLE
Add New Negative Test Cases for Commissioner DUT

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#19648]
#### Problem
There are about 140 negative test vectors generated and placed here:
    credentials/development/commissioner_dut/
Those test vectors include various errors in DAC, PAI, and CD, which should be rejected by commissioner.

 #### Proposed Solution
Implement those test cases

**Comment by akrithika27** [comment]
Reference [document](https://docs.google.com/spreadsheets/d/12a1HNgskNOpafIXEiJif6lLtCq8oi_CqkRoUOfOCIJ8/edit?resourcekey=0-z4RHDg9WjNX4zOKqES_QHg#gid=1687570238)
