### ISSUE TITLE
pre-sve [TC-MF-1.21][TC-MF-1.22]

### ISSUE THREAD

**Issue by Shadi-Silabs** [project-chip/connectedhomeip#19642]
#### TC-MF-1.21 and 1.22 step#5:
Not able to commission the 5th fabric for both tests. supported-fabrics parameter is 5, and I was able to commission 4 fabrics and open the 5th commissioning window without an error, but commissioning the 5th fabric failed.
The errors are either:
CHIP Error 0x00000003: Incorrect state
or
CHIP Error 0x00000032: Timeout
the logs are all below:
[TC-MF-1.21.txt](https://github.com/project-chip/connectedhomeip/files/8912882/TC-MF-1.21.txt)
[TC-MF-1.21-DUT.txt](https://github.com/project-chip/connectedhomeip/files/8912883/TC-MF-1.21-DUT.txt)
[TC-MF-1.22.txt](https://github.com/project-chip/connectedhomeip/files/8921525/TC-MF-1.22.txt)
[TC-MF-1.22-DUT.txt](https://github.com/project-chip/connectedhomeip/files/8921526/TC-MF-1.22-DUT.txt)

test Platform:
EFR32 as DUT
Lighting-app

**Comment by bzbarsky-apple** [comment]
[TC-MF-1.22-DUT.txt](https://github.com/project-chip/connectedhomeip/files/8912885/TC-MF-1.22-DUT.txt) is an empty file, so not much to say about that one....

**Comment by bzbarsky-apple** [comment]
OK, so in the 1.22 DUT log I see:
```
00> <info  > [DL] advertising srp service: 376851A89CC29C75._matterc._udp
00> <info  > [DL] removing srp service: 1A461415045D135D._matterc._udp
00> <info  > [ZCL] Commissioning window is now open
...
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
00> <error > [DL] OnSrpClientNotification: Timed out waiting on server response
```
and again the TH log does not show `376851A89CC29C75` anywhere.  So seems like the same issue...

**Comment by Damian-Nordic** [comment]
If you get "Timed out waiting on server response" error, it's worth checking OTBR logs as well. In our testing we only encountered "Parsing operation failed" error when sending big SRP updates. https://github.com/project-chip/connectedhomeip/pull/19803, merged yesterday, should reduce the size of our SRP updates, and https://github.com/openthread/openthread/pull/7776 in OpenThread should help process big SRP updates anyway.
