### ISSUE TITLE
TC- PRS 3.1 -> read tolerance, scaled-value, min-scaled-value , max-scaled-value , scaled-tolerance and scale throw (UNSUPPORTED_ATTRIBUTE) error

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#19657]
With SHA 5d8599d195a93dfe5473f64e4f888c322e5df1d2

In test case TC- PRS 3.1 -> read tolerance, scaled-value, min-scaled-value , max-scaled-value , scaled-tolerance and scale throw (UNSUPPORTED_ATTRIBUTE) error on raspi for chip-tool and darwin-framework-tool

Attaching the logs from chip-tool:
[TC-PRS-3.1chiptoolLog.txt](https://github.com/project-chip/connectedhomeip/files/8915218/TC-PRS-3.1chiptoolLog.txt)

Attaching the logs from darwin-framework-tool:
[TC-PRS-3.1darwin-framework-toolLog.txt](https://github.com/project-chip/connectedhomeip/files/8915220/TC-PRS-3.1darwin-framework-toolLog.txt)

Attaching the logs from raspi:
[TC-PRS-3.1-raspiLog.txt](https://github.com/project-chip/connectedhomeip/files/8915228/TC-PRS-3.1-raspiLog.txt)

**Comment by bzbarsky-apple** [comment]
@phonnakasturi-apple These are all optional attributes.  Some conditioned on the EXT feature, some outright optional.

Was the EXT bit set in the feature map in this case?  When I test with all-clusters-app it's not set.  So the attributes are optional, not supported in this app, and correctly return UNSUPPORTED_ATTRIBUTE.  Where is the issue?
