### ISSUE TITLE
TC-TSTAT-3.2 -> thermostat setpoint-raise-lower throws General error: 0x81 (UNSUPPORTED_COMMAND) error on raspi

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#19654]
With SHA 5d8599d195a93dfe5473f64e4f888c322e5df1d2

For test case TC-TSTAT-3.2

The following commands throw -> General error: 0x81 (UNSUPPORTED_COMMAND) error on raspi for chip-tool + darwin-framework-tool

./darwin-framework-toolthermostat setpoint-raise-lower 0 10 1 1
./darwin-framework-tool thermostat setpoint-raise-lower 0 -10 1 1

./chip-tool thermostat setpoint-raise-lower 0 10 1 1
./chip-tool thermostat setpoint-raise-lower 0 -10 1 1

raspi is executing chip-all-clusters-app
and on mac we are executing darwin-framework-tool app

Attaching the logs from Mac for darwin-framework-tool:
[TC_STAT3.2-darwin-framework-toolLog.txt](https://github.com/project-chip/connectedhomeip/files/8915041/TC_STAT3.2-darwin-framework-toolLog.txt)

Attaching the logs from raspi:
[TC_STAT3.2-raspiLg.txt](https://github.com/project-chip/connectedhomeip/files/8915043/TC_STAT3.2-raspiLg.txt)

Attaching the logs from Mac for chip-tool:
[TC_STAT3.2-chiptoolLog.txt](https://github.com/project-chip/connectedhomeip/files/8915056/TC_STAT3.2-chiptoolLog.txt)

Attaching the logs from raspi:
[TC_STAT3.2-chiptoolraspiLog.txt](https://github.com/project-chip/connectedhomeip/files/8915095/TC_STAT3.2-chiptoolraspiLog.txt)

**Comment by bzbarsky-apple** [comment]
Fixed in #19467
