### ISSUE TITLE
get-relay-status-log must be implemented for chip-tool + darwin-framework-tool

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#19655]
get-relay-status-log must be implemented for chip-tool + darwin-framework-tool for testing step 3 in TC-TC-TSTAT - 3.2

<img width="1542" alt="get-relay-status-log" src="https://user-images.githubusercontent.com/101904389/173977084-4de70e61-30ec-4cee-9d04-95abec8e1771.png">

**Comment by bzbarsky-apple** [comment]
Device library section "9.2.5. Element Requirements" says this is Zigbee-only.
