### ISSUE TITLE
TC-OCC 2.2 -> Steps 5 - 15 throw 0x86 (UNSUPPORTED_ATTRIBUTE) on raspi

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#19650]
With SHA 5d8599d195a93dfe5473f64e4f888c322e5df1d2

In test case TC-OCC-2.2 from steps 5-15 throw 0x86 (UNSUPPORTED_ATTRIBUTE) on raspi (ubuntu)

This is seen in chip-tool + darwin-framework-tool

raspi is executing chip-all-clusters-app
and on mac we are executing darwin-framework-tool app

Attaching the logs from Mac (darwin-framework-tool);
[macLogs.txt](https://github.com/project-chip/connectedhomeip/files/8914860/macLogs.txt)

Attaching the logs from Mac (chip-tool);
[TC-OCC-2.2_chip-toolLogs.txt](https://github.com/project-chip/connectedhomeip/files/8915254/TC-OCC-2.2_chip-toolLogs.txt)

Attaching the logs from raspi;
[raspiLogs.txt](https://github.com/project-chip/connectedhomeip/files/8914862/raspiLogs.txt)

**Comment by bzbarsky-apple** [comment]
@phonnakasturi-apple These are optional attributes, and are not implemented by all-clusters-app, right?  These tests are conditioned on PICS in the test plan....  Why is this an issue?
