### ISSUE TITLE
Spell check broken by #19043

### ISSUE THREAD

**Issue by cpagravel** [project-chip/connectedhomeip#19776]
#### Problem
* Spellcheck CI was broken by #19043

 #### Proposed Solution
* Fix the spellcheck CI.

We should consider avoiding merges if CI jobs are broken. In that particular PR there are only 59 of 66 checks passing.

**Comment by Arkq** [comment]
> We should consider avoiding merges if CI jobs are broken. In that particular PR there are only 59 of 66 checks passing.

Sorry for that, I've missed that the spell check has failed. Maybe it should be marked as required? @andy31415
