### ISSUE TITLE
[SQA] State value is not changing for changing the state of the Lock attribute in doorlock

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#19794]
### Problem :
Door Position Sensor is not able to fetch current door-state, it remains constant when door-lock is unlocked from lock-state or locked from unlock-state. Due to this DUT is not able to fetch any door-state-change event.

## Platform used : 

- > Tested on : 2ac3ee761232b466db70c196986e90081f2c4ec3
- > server : lock-app ( RPI-4, 8GB RAM)
- > client : chip-tool ( RPI-4, 8GB RAM )
- > network : Ethernet (IP)

## Steps to Reproduce :

1. Unlock the door :` ./chip-tool doorlock unlock-door 1 1 --timedInteractionTimeoutMs 1000`

> [1655800200.270350][11456:11461] CHIP:DMG: Received Command Response Status for Endpoint=1 Cluster=0x0000_0101 Command=0x0000_0001 Status=0x0
2. Verify the lock-state :` ./chip-tool doorlock read lock-state 1 1`

> [1655800295.826025][11480:11485] CHIP:TOO:   LockState: 2

3. Verify the door-state :  `./chip-tool doorlock read door-state 1 1`

 > [1655800406.609853][11544:11549] CHIP:TOO:   DoorState: 0

4. Lock the door : `./chip-tool doorlock lock-door 1 1 --timedInteractionTimeoutMs 1000`

> [1655805043.974722][11927:11932] CHIP:DMG: Received Command Response Status for Endpoint=1 Cluster=0x0000_0101 Command=0x0000_0000 Status=0x0
5. Verify the lock-state :` ./chip-tool doorlock read lock-state 1 1`

> [1655805051.448416][11933:11938] CHIP:TOO:   LockState: 1

6. Verify the door-state :  `./chip-tool doorlock read door-state 1 1`

  

- > Actual behavior :  [1655805059.725560][11939:11944] CHIP:TOO:   DoorState: 0
- > Expected behavior : [1655805059.725560][11939:11944] CHIP:TOO:   DoorState: 1

7. Checked door-state-chnage event :  `./chip-tool doorlock read-event door-state-change 1 1`

- Actual behavior :

> **DUT response for the Read Event:  :** 
[1655805081.422912][10675:10675] CHIP:DMG: Building Reports for ReadHandler with LastReportGeneration = 0 DirtyGeneration = 0
[1655805081.423866][10675:10675] CHIP:DMG: Fetched 0 events
[1655805081.423898][10675:10675] CHIP:DMG: <RE> Sending report (payload has 7 bytes)...

- Expected behavior : Event should be listed in Chiptool

### Reference : 

- Test Plan : https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/door_lock_Cluster.adoc#test-procedure-10 [ STEP : 9 and 10 ]
- SPEC :  https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/DoorLock.adoc#52-doorstatechange-event

### Full log :
[Door_state log.txt](https://github.com/project-chip/connectedhomeip/files/8947763/Door_state.log.txt)

**Comment by bzbarsky-apple** [comment]
I don't see anything in the spec that prevents the "door is open but lock is in the locked position" situation.  So staying in the "door open" state when lock-door happens does not seem impossible...

@DanM-AssaAbloy @RyanLindemanCAE  @Morozov-5F

**Comment by woody-apple** [comment]
Cert Blocker Review: Agree with @DanM-AssaAbloy above. Marking invalid test and closing.
