### ISSUE TITLE
[Pre-SVE] door-lock does not lock/unlock

### ISSUE THREAD

**Issue by HubertHugo** [project-chip/connectedhomeip#19798]
SHA: 1e3f12041013dd71a53d035dbf2f6d142fc06c4e
platform nRF52840
all-cluster-app
Chip tool returns failure when I try to lock/unlock the door. Lock state does not change. Same thing I mentioned in https://github.com/project-chip/connectedhomeip/issues/19097 
Chip tool logs:
[door-lock-issue-chip-tool.log](https://github.com/project-chip/connectedhomeip/files/8947614/door-lock-issue-chip-tool.log)

**Comment by bzbarsky-apple** [comment]
Please use lock-app, not all-clusters-app, for door lock tests.

**Comment by woody-apple** [comment]
Cert Blocker Review: Same as https://github.com/project-chip/connectedhomeip/issues/19802, closing. Please re-test using the lock app.
