### ISSUE TITLE
[Pre-SVE] TC-DRLK 2.1 enable_inside_status_led_constraint error

### ISSUE THREAD

**Issue by HubertHugo** [project-chip/connectedhomeip#19797]
SHA: 1e3f12041013dd71a53d035dbf2f6d142fc06c4e
platform: nRF52840
all-clusters-app
When writing to enable-inside-status-led i get constraint error.

[enable_inside_status_led_constraint_error_door_lock_chip_tool.log](https://github.com/project-chip/connectedhomeip/files/8947435/enable_inside_status_led_constraint_error_door_lock_chip_tool.log)

**Comment by bzbarsky-apple** [comment]
The command being used is:
```
./chip-tool doorlock write-by-id 42 1 1 1
```
This sends the integer "1" as the value for the attribute, encoded as a TVL integer.

But this is a boolean attribute, and the valid values are `true` and `false`, encoded as TLV booleans.  So a TLV integer here is in fact a CONSTRAINT_ERROR error.

Using
```
./chip-tool doorlock write-by-id 42 true 1 1
```
works fine, as expected.
