### ISSUE TITLE
TC-ACT-2.2 - Need verification steps to verify action-list atribute

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#19790]
**Issue :** 
1. Need verification steps to verify action-list attribute that is test-step 3 to 4e.
2. This [PR](https://github.com/project-chip/connectedhomeip/pull/19487) contains the details of the verification for endpoint-list attribute but not for action-list attribute

**Test-plan reference :**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/actions.adoc#tc-act-2-2-primary-functionality-with-server-as-dut

@jwinder-ca @leorozendaal Can I get any information on it

**Comment by bzbarsky-apple** [comment]
The action-list depends on the device, no?  It's a list of what actions the device supports.

This does not seem like an SDK issue to me...
