### ISSUE TITLE
[SQA] [TC-DRLK-2.10] Lock-Operation-Error & Door Lock Alarm events need to be implemented in Lock-app.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#19807]
### Summary : 

While identifying the verification steps for doorlock cluster test plan,  SQA found that the following events are not able to be triggered.

## Events which needs implementation :

1. > LockOperationError Event for DisabledUserDenied and Restricted
2. > Door-lock-alarm Event for  LockJammed
3. > Door-state-change for Lock and Unlock [ https://github.com/project-chip/connectedhomeip/issues/19794 ]

## Platform used :
Tested on : https://github.com/project-chip/connectedhomeip/commit/2ac3ee761232b466db70c196986e90081f2c4ec3

server : lock-app ( RPI-4, 8GB RAM)

client : chip-tool ( RPI-4, 8GB RAM )

network : Ethernet (IP)

### Reference : 
- SPEC : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/DoorLock.adoc#5-events

**Comment by Survensa** [comment]
@Morozov-5F  As discussed, I have raised this issue, kindly give your comments if any.

**Comment by woody-apple** [comment]
Cert Blocker Review: @Morozov-5F can you please take a look at the mandatory events? Thanks

**Comment by cjandhyala** [comment]
@Morozov-5F For the DIAG clusters we had developers implemented some signal handlers to generate the events, Could we follow a similar mechanism to generate these events?

**Comment by woody-apple** [comment]
Cert Blocker Review: Marking this as 'needs provisional' unless we have a resolution to this issue today.
