### ISSUE TITLE
[Pre-SVE] TC-DRLK 2.8 Set,get,clear user result in failure

### ISSUE THREAD

**Issue by HubertHugo** [project-chip/connectedhomeip#19802]
SHA: 1e3f12041013dd71a53d035dbf2f6d142fc06c4e
platform: nRF52840
all-clusters-app

Set-user, get-user, clear-user return failure.

Logs: 
[set-get-clear-user-issue.log](https://github.com/project-chip/connectedhomeip/files/8947917/set-get-clear-user-issue.log)

**Comment by HubertHugo** [comment]
Test 2.9 (set,get,clear credential) fail due to the same reason.

**Comment by woody-apple** [comment]
Cert Blocker Review: Leaving as requested, we don't know what's being tested for locks.
