### ISSUE TITLE
[pre-sve] TC-GC-1.1/2.1 supports-concurrent-connection missing in Window Cover app

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/connectedhomeip#19804]
#### Problem
supports-concurrent-connection is not implemented in Window cover sample app.

 #### Commit
SHA: https://github.com/project-chip/connectedhomeip/commit/1e3f12041013dd71a53d035dbf2f6d142fc06c4e
Platform: EFR32

**Comment by bzbarsky-apple** [comment]
Yep, looks like this thing needs to be enabled.

**Comment by woody-apple** [comment]
Cert Blocker Review: Assuming that we need this sample app for cert, marking cert blocker. Assigning to @jmeg-sfy can you take a peek please?

**Comment by jmeg-sfy** [comment]
https://github.com/project-chip/connectedhomeip/issues/18333
