### ISSUE TITLE
[pre-sve] TC-BINFO-2.1 Issue with writing type string values to Attributes

### ISSUE THREAD

**Issue by mkleszcz-no** [project-chip/connectedhomeip#19811]
all-cluster-app
nrf52840dk
revison: https://github.com/project-chip/connectedhomeip/commit/1e3f12041013dd71a53d035dbf2f6d142fc06c4e

It is not possible to write values of type string to attributes in Basic Information Cluster.

### Example:

![Screenshot from 2022-06-21 16-00-23](https://user-images.githubusercontent.com/105919822/174818733-688b7d40-e158-45f8-aaa9-8a230f138d61.png)

VendorName attribute is type string - It should be possible to run this test in the same way as in the test plan, but chip-tool do not accept write-by-id command with string value as the second argument:

![Screenshot from 2022-06-21 16-11-59](https://user-images.githubusercontent.com/105919822/174821539-8e4043da-d53e-4dba-aaaa-4ccb9b44359c.png)

 * steps to reproduce
1. Try to write value of type string to one of the type string attributes (VendorName, NodeLabel, SoftwareVersionString etc.)

**Comment by woody-apple** [comment]
Cert Blocker Review: This is not correct usage of the tool. @bzbarsky-apple to update.

**Comment by bzbarsky-apple** [comment]
When doing write-by-id the input is JSON.

In JSON, a string is in quotes.  The quotes above are being "eaten" by your shell, so not making their way to the JSON parser.

You want `chip-tool basic write-by-id 0x1 '"sample"' 1 0` or `chip-tool basic write-by-id 0x1 \"sample\" 1 0` or some other method of escaping those quotes from the shell.
