### ISSUE TITLE
AddTrustedRootCertificate Command send constraint_error when invalid_command is expected while sending malformed certificate

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#19839]
**Problem:**

When Arm fail command is sent  with malformed Root Certificate in a new fail safe timer period we expect to see INVALID_Command but we are seeing CONSTRAINT_ERROR

**Spec Referrence**-11.18.7.13
![image](https://user-images.githubusercontent.com/90545664/174967012-2be0f261-7486-40c7-96c0-a8cfef8059a2.png)

**Commit used** : c60233daaa8ea68b4f1198d640e6f89966363f31			

**Sequence of Steps:**
1.Commission DUT to TH - Success
2. Send arm-fail-safe commad - Sucess
3. Send AddTrustedRootCertificate Command with valid root certificate - Success
4. In a new fail safe timer period send arm-fail-safe command - Success
5. Send AddTrustedRootCertificate Command with malformed root certificate - Failure(CONSTRAINT_ERROR)

**Test platform :**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM

**Test-plan reference :**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicemanagement.adoc#tc-opcreds-3-1-attribute-nocs-trustedrootcertificates-list-validation-dut-server

**PFA Logs:**
[TC-OPCREDS_3.1_cntrl.txt](https://github.com/project-chip/connectedhomeip/files/8955456/TC-OPCREDS_3.1_cntrl.txt)

**Comment by bzbarsky-apple** [comment]
I read through the test plan, and it looks like this s trying to do step 40 from the test plan?  But the steps being carried out above look nothing like the parts of the test plan that come before step 40....

**Comment by bzbarsky-apple** [comment]
Though following the test plan exactly would run into trouble too.  Filed https://github.com/CHIP-Specifications/chip-test-plans/issues/1560
