### ISSUE TITLE
[Pre-SVE] Subscription and changing acls to incorrect

### ISSUE THREAD

**Issue by HubertHugo** [project-chip/connectedhomeip#19883]
SHA: 1e3f12041013dd71a53d035dbf2f6d142fc06c4e
platform: nRF52840
all clusters app

There are a couple of issues regarding scenario presented below. When I write bad acls it looks like it removes old ones but fails to write new ones, so DUT ends up with no acls, shouldn't it give error while writing instead? Also when I later subscribe to an event it prints UNSUPPORTED_ACCESS as I would expect but sends subscribe response message every max interval as if it had subscription alive. Normal read just gives UNSUPPORTED_ACCESS as expected.

Steps:
1. ./chip-tool interactive start
2. accesscontrol write acl [{"fabricIndex":1,"privilege":23,"authMode":123,"subjects":[112233],"targets":null}] 1 0
3. basic subscribe-event-by-id 0x000 5 10 1 0

[acl_issue_chip-tool.log](https://github.com/project-chip/connectedhomeip/files/8965821/acl_issue_chip-tool.log)

**Comment by bzbarsky-apple** [comment]
List writes are chunked, hence can't be atomic, so the "removes old ones but fails to write new ones" behavior is expected.

> it prints UNSUPPORTED_ACCESS as I would expect but sends subscribe response message every max interval as if it had subscription alive

See https://github.com/project-chip/connectedhomeip/issues/18485
