### ISSUE TITLE
[Proxy] Looks like proxies are not yet fully supported.

### ISSUE THREAD

**Issue by haigithub** [project-chip/connectedhomeip#19888]
##### Clusters about proxies are not yet supported.
ClusterId | ClusterName | Enable Or Not
-- | -- | --
0x0042 | Proxy Configuration Cluster | Not Enable
0x0043 | Proxy Discovery Cluster | Not Enable
0x0044 | Proxy Valid Cluster | Not Enable

##### Definetion of above clusters hasn't been compeleted in XML files.
- connectedhomeip/src/app/zap-templates/zcl/data-model/chip/**proxy-discovery-cluster.xml**
- connectedhomeip/src/app/zap-templates/zcl/data-model/chip/**proxy-valid-cluster.xml**
- connectedhomeip/src/app/zap-templates/zcl/data-model/chip/**proxy-configuration-cluster.xml**
- connectedhomeip/src/app/zap-templates/zcl/data-model/chip/**matter-devices.xml**

##### Spec:  Connected Home over IP Specification Version master 58bd4f0, 2022-02-08
![image](https://user-images.githubusercontent.com/6647157/175303176-c7982278-90ed-4858-aa0a-720cdb4e6b56.png)

 #### Proposed Solution
- suggested fix

**Comment by bzbarsky-apple** [comment]
Proxies are out of scope for 1.0.
