### ISSUE TITLE
[Network Commissioning] [TC-CNET-4.13 & TC-CNET-4.14] - Unable to perform ReorderNetwork

### ISSUE THREAD

**Issue by sethunk** [project-chip/connectedhomeip#19884]
**1. Problem**
In Network Commissioning, As the MaxNetworks value is 1, we are unable to perform the ReorderNetwork Command for WiFi and Thread networks.

**2. Sequence of steps**
./chip-tool networkcommissioning read max-networks 1 0

> [1655981853.230331][8334:8339] CHIP:DMG: ReportDataMessage =
> [1655981853.230375][8334:8339] CHIP:DMG: {
> [1655981853.230410][8334:8339] CHIP:DMG:        AttributeReportIBs =
> [1655981853.230460][8334:8339] CHIP:DMG:        [
> [1655981853.230500][8334:8339] CHIP:DMG:                AttributeReportIB =
> [1655981853.230552][8334:8339] CHIP:DMG:                {
> [1655981853.230595][8334:8339] CHIP:DMG:                        AttributeDataIB =
> [1655981853.230652][8334:8339] CHIP:DMG:                        {
> [1655981853.230706][8334:8339] CHIP:DMG:                                DataVersion = 0xcc4d0d84,
> [1655981853.230759][8334:8339] CHIP:DMG:                                AttributePathIB =
> [1655981853.230812][8334:8339] CHIP:DMG:                                {
> [1655981853.230869][8334:8339] CHIP:DMG:                                        **Endpoint = 0x0,**
> [1655981853.230927][8334:8339] CHIP:DMG:                                        **Cluster = 0x31,**
> [1655981853.230980][8334:8339] CHIP:DMG:                                        **Attribute = 0x0000_0000,**
> [1655981853.231034][8334:8339] CHIP:DMG:                                }
> [1655981853.231085][8334:8339] CHIP:DMG:
> [1655981853.231141][8334:8339] CHIP:DMG:                                **Data = 1,**
> [1655981853.231192][8334:8339] CHIP:DMG:                        },
> [1655981853.231246][8334:8339] CHIP:DMG:
> [1655981853.231287][8334:8339] CHIP:DMG:                },
> [1655981853.231340][8334:8339] CHIP:DMG:
> [1655981853.231379][8334:8339] CHIP:DMG:        ],
> [1655981853.231428][8334:8339] CHIP:DMG:
> [1655981853.231468][8334:8339] CHIP:DMG:        SuppressResponse = true,
> [1655981853.231510][8334:8339] CHIP:DMG:        InteractionModelRevision = 1
> [1655981853.231548][8334:8339] CHIP:DMG: }
> [1655981853.231831][8334:8339] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0031 Attribute 0x0000_0000 DataVersion: 3427601796
> [1655981853.234465][8334:8339] CHIP:TOO:   **MaxNetworks: 1**

**3. Test Environment**

App used - allclusters app
Platform - Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Network - Ble-wifi
Commit - 2ac3ee761232b466db70c196986e90081f2c4ec3

**4. Logs**
[ReorderNetwork.txt](https://github.com/project-chip/connectedhomeip/files/8966713/ReorderNetwork.txt)

**Comment by bzbarsky-apple** [comment]
What is the issue, exactly?  Supporting only one network is a perfectly valid state for a device.

Please reopen with a clear description of the specific changes that you want to see here, if needed.
