### ISSUE TITLE
Raspberry Pi armhf build always failing

### ISSUE THREAD

**Issue by rwells1703** [project-chip/connectedhomeip#19896]
Hello, I've been trying to build Matter (specifically chip-tool and lighting-app) for the Raspberry Pi (32 bit armhf) for some time now however the Ninja compilation always fails with the same error.

I'm not sure why, but the x86_64 version of glib seems to be in the included dirs

![image](https://user-images.githubusercontent.com/13154431/175324694-6d4f4d38-0b14-4795-b620-2d028be4495d.png)

 even though I'm cross compiling for armhf on an amd64 system. Is this normal? I have installed the libglib2.0-dev library with ```sudo apt install libglib2.0-dev:armhf``` but it doesn't seem to have changed anything.

Here are the logs:
[build failed chip-tool armhf.txt](https://github.com/project-chip/connectedhomeip/files/8968169/build.failed.chip-tool.armhf.txt)
[build failed lighting-app armhf.txt](https://github.com/project-chip/connectedhomeip/files/8968172/build.failed.lighting-app.armhf.txt)

Thanks!

**Comment by bzbarsky-apple** [comment]
@mspang @andy31415

**Comment by andy31415** [comment]
What are the commands you use to compile?

**Comment by andy31415** [comment]
For cross compilation you will need some sysroot that is compatible. I believe our docker images just have a arm64 sysroot.

**Comment by rwells1703** [comment]
> What are the commands you use to compile?

Oh yes sorry, it's in the logs but I should have made it clearer. ```gn gen out/rpi_armhf --args='target_os="linux" target_cpu="arm"'``` followed by ```ninja -C out/rpi_armhf``` for both chip-tool and lighting-app.


> For cross compilation you will need some sysroot that is compatible. I believe our docker images just have a arm64 sysroot.

So I can compile it for arm64 just fine with ```gn gen out/rpi_arm64 --args='target_os="linux" target_cpu="arm64"'``` followed by ```ninja -C out/rpi_arm64``` (obviously the out/* directory names don't matter, they're just for me to keep track). Will the arm64 sysroot allow me to compile for armhf as well? 

If not then I've heard it's possible to mount the target device file system and then use that as a sysroot, but I can't see any references to sysroot in either the Ninja nor the GN documentation so I'm not sure how this can be achieved.

I have also noticed the ```build/toolchain/arm/arm_sysroot.gni``` and ```build/toolchain/arm_gcc/arm_toolchain.gni``` files, which look promising  - is there a certain flag that I pass to GN that will specify using these as toolchains?
