### ISSUE TITLE
ACL extensions not removed on RemoveFabric

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#19899]
#### Problem
RemoveFabric command does not remove ACL extensions from storage. Only the ACL cluster touches it in `AccessControlAttribute::WriteExtension`

 #### Proposed Solution
- Delete extensions for fabric on RemoveFabric, but must first add API abstraction for extensions storage so that not only the cluster server knows about them

**Comment by Damian-Nordic** [comment]
Have you seen `OpCredsFabricTableDelegate`. I thought ACLs are deleted there.

**Comment by woody-apple** [comment]
Spec Review: Assigning to @andy31415 to follow up, v1.0 issue.
