### ISSUE TITLE
Generic Switch: Linux sample uses previousPosition / newPosition wrongly and uses positions > numberOfPositions 

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [project-chip/connectedhomeip#19923]
#### Problem

previousPosition / newPosition handled wrongly in https://github.com/project-chip/connectedhomeip/blob/master/examples/all-clusters-app/linux/main-common.cpp#L159-L160.

Values of 10 and 20 are also wrong (should be 0 and 1), since numberOfPositions is 2: https://github.com/project-chip/connectedhomeip/blob/master/examples/all-clusters-app/all-clusters-common/all-clusters-app.matter#L4228.

#### Proposed Solution

Use values 0 and 1. Use newPosition=1 on press and previousPosition=1 on release.

**Comment by woody-apple** [comment]
Spec Review: Reference app should be fixed for 1.0

**Comment by markus-becker-tridonic-com** [comment]
previousPosition and newPosition are passed as parameters in JSON now and are no longer hard-coded anymore.
