### ISSUE TITLE
[pre-sve] TC-MF-1.5 DUT_CE opens Commissioning window - it should fail

### ISSUE THREAD

**Issue by mkleszcz-no** [project-chip/connectedhomeip#19945]
all-cluster-app
nrf52840dk
revison: https://github.com/project-chip/connectedhomeip/commit/1e3f12041013dd71a53d035dbf2f6d142fc06c4e

 #### Problem
Step 10
TH_CR1 opens a new commissioning window on DUT_CE using a commissioning timeout of PIXIT_COMM_WIN seconds using ECM but with wrong PakeVerifier value - command should fail, but it succeed.

 * expected behavior
    DUT_CE fails to open Commissioning window with status code 2 (PakeParameterError)

 * actual behavior
    DUT_CE open commissioning window with wrong PakeVerifier value

 * steps to reproduce

1.   Generate correct PakeVerifier value:
> ./spake2p gen-verifier -o - -i 1000 -s "SPAKE2P Key Salt" -p 20202021 --out -

Output:
>0,20202021,1000,U1BBS0UyUCBLZXkgU2FsdA==,uWFwqugDNGiEck/po7KHwwMwwqZgN10XuyBajPGuyzUEV/iree4lOrao5GuwnlQ65CJzbeUB49s31EH+NEkg0JVI5MGCQGMMT/SRPFNRODm3wH/MBiehuFc6FJ/NH6Rmzw==

2.   Open commissioning window with correct PakeVerifier value:
>./chip-tool administratorcommissioning open-commissioning-window 200 uWFwqugDNGiEck/po7KHwwMwwqZgN10XuyBajPGuyzUEV/iree4lOrao5GuwnlQ65CJzbeUB49s31EH+NEkg0JVI5MGCQGMMT/SRPFNRODm3wH/MBiehuFc6FJ/NH6Rmzw==  3328 1000 "SPAKE2P Key Salt" 1 0 --timedInteractionTimeoutMs 1000

Command is successful as expected

3. Close commissioning window

4.   Generate wrong PakeVerifier value (with wrong SetupPinCode):
> ./spake2p gen-verifier -o - -i 1000 -s "SPAKE2P Key Salt" -p 20202018 --out -

Output:
>0,20202018,1000,U1BBS0UyUCBLZXkgU2FsdA==,ojaw9zwyG5DpC7QvuhgZ7AYmkRbb6wf60RKQWrSxNsoE5Ga5v/zXq30y2VI7fQmuTG8Mruf0jGJHs+pD9nWGEI98QfUBT7Juhvw6PtejKlq5Da5LA3LzhTqWXhJh/POu2g==

5. Open commissioning window with wrong PakeVerifier value:
>./chip-tool administratorcommissioning open-commissioning-window 200 ojaw9zwyG5DpC7QvuhgZ7AYmkRbb6wf60RKQWrSxNsoE5Ga5v/zXq30y2VI7fQmuTG8Mruf0jGJHs+pD9nWGEI98QfUBT7Juhvw6PtejKlq5Da5LA3LzhTqWXhJh/POu2g==  3328 1000 "SPAKE2P Key Salt" 1 0 --timedInteractionTimeoutMs 1000

Command is successful - it should fail in accordance with the test
>[1656058730.424507][18978:18983] CHIP:DMG: 				StatusIB =
>[1656058730.424534][18978:18983] CHIP:DMG: 				{
>[1656058730.424561][18978:18983] CHIP:DMG: 					status = 0x00 (SUCCESS),
>[1656058730.424584][18978:18983] CHIP:DMG: 				},

Logs:
[TC_MF_1_5_nRF.log](https://github.com/project-chip/connectedhomeip/files/8974820/TC_MF_1_5_nRF.log)
[TC_MF_1_5_nRF_DUT.log](https://github.com/project-chip/connectedhomeip/files/8974821/TC_MF_1_5_nRF_DUT.log)

**Comment by bzbarsky-apple** [comment]
Why would this fail?  The verifier value is perfectly valid, for PIN code 20202018.

What should fail is an attempt to then pair with some PIN code that is not 20202018.

@mkleszcz-no What made you think this command should fail?
