### ISSUE TITLE
Test_TC_MF_1_9/10 don't make sense

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#19973]
#### Problem
These tests open a commissioning window for 3 minutes, then do 20 pairing attempts, which takes at least 30 seconds per attempt, so 10 minutes, then test that the commissioning window has closed.... but it's just closed because enough time has passed.

 #### Proposed Solution
We should probably have a way for the 20 pairing attempts to fail out faster than after 30+ seconds... But at the very least we should use a 15-minute commissioning window here, not a 3-minute one.

@vivien-apple @manjunath-grl

**Comment by doublemis1** [comment]
I think that the commissioning timeout should be set to 15 minutes (max commissioning timeout). Moreover, I think that commissioning should fail faster than after 30 seconds since the passcode is wrong so the PASE will fail,
