### ISSUE TITLE
[pre-SVE] TC-DRLK-2.2 UserCodeTemporaryDisableTime attribute is not triggered

### ISSUE THREAD

**Issue by AlvinHsiao** [project-chip/connectedhomeip#19989]
Problem

expected behavior vs actual behavior

At step14 after step13, DUT should send failure response to the TH, but sent success response instead.

system configuration :
Chip-Tool: RPI
DUT used : Infineon CYW30739
app use: Lock-app
chip-tool and DUT commit id : https://github.com/project-chip/connectedhomeip/commit/1e3f12041013dd71a53d035dbf2f6d142fc06c4e (pre-sve SHA)

logs
[TC-DRLK-2.2.txt](https://github.com/project-chip/connectedhomeip/files/8988573/TC-DRLK-2.2.txt)

**Comment by bzbarsky-apple** [comment]
door-lock-server has:
```
    // TODO: check whether UserCodeTemporaryDisableTime expired or not.
```
and
```
    // TODO: If limit is exceeded, lock remote operations for UserCodeTemporaryDisableTime.
```
so looks like this is not implemented yet....

**Comment by woody-apple** [comment]
Cert Blocker Review: @Morozov-5F are you able to take a look at this lock cert blocker? Thanks!

**Comment by woody-apple** [comment]
Cert Blocker Review: Marking this as 'needs provisional' unless we have a resolution to this issue today.
