### ISSUE TITLE
[TC-DRLK-2.8] Door-lock Set User Command is returning Failure instead of  OCCUPIED.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#19991]
**Problem** - Set User command with existing user index value is failed.

Actual Behavior -After giving repeated user index value we are getting Failure response

> [1656314035.358615][2757:2762] CHIP:TOO: Error: IM Error 0x00000501: General error: 0x01 (FAILURE)

Expected Behavior - After giving repeated user index value we have to get OCCUPIED

> [1656314035.358615][2757:2762] CHIP:TOO: Error: IM Error 0x00000501: General error: 0x03 (OCCUPIED)

In DUT Log (Attached), it returns "Unable to overwrite existing user [endpointId=1,userIndex=1]"

> [1656314035.338115][2974:2974] CHIP:ZCL: [createUser] Unable to overwrite existing user [endpointId=1,userIndex=1]

App used - lock app
Platform - Chip-tool - RPI-4, 8GB RAM
DUT - RPI-4, 8GB RAM
Network - Ble-wifi
Commit - 2ac3ee7

Reference:
SPEC : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/DoorLock.adoc#434-set-user-command
Test plan : https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/door_lock_Cluster.adoc#test-procedure-8

log :
[Doorlock Set user Command logs.txt](https://github.com/project-chip/connectedhomeip/files/8989913/Doorlock.Set.user.Command.logs.txt)

**Comment by bzbarsky-apple** [comment]
@Morozov-5F

**Comment by woody-apple** [comment]
SDK Review: @Morozov-5F are you able to take a look at this?

**Comment by bzbarsky-apple** [comment]
>    [1656314035.358615][2757:2762] CHIP:TOO: Error: IM Error 0x00000501: General error: 0x03 (OCCUPIED)

Note, by the way: this is _not_ the right expected value.  The rigtht expected value is a cluster-specific error, not a general error.

**Comment by woody-apple** [comment]
Cert Blocker Review: Marking this as 'needs provisional' unless we have a resolution to this issue today.
