### ISSUE TITLE
TC-CNET-4.13 and 4.14 Network Commissioning -  Reorder Network command cannot be performed

### ISSUE THREAD

**Issue by sethunk** [project-chip/connectedhomeip#20112]
**1.Problem** 
When adding a new network using the add-or-update-wi-fi-network command, the response is successful for the first entry. When a second network is added the response is BoundsExceeded. In this case, the reorder-network cannot be performed.

**2.Steps to reproduce**
**AddOrUpdateWiFiNetwork**
> ./chip-tool networkcommissioning add-or-update-wi-fi-network hex:63686970736574757032 matter123 1 0

> [1656512209.493211][3277:3282] CHIP:DMG: Received Command Response Data, Endpoint=0 Cluster=0x0000_0031 Command=0x0000_0005
> [1656512209.493308][3277:3282] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0031 Command 0x0000_0005
> [1656512209.493466][3277:3282] CHIP:TOO:   NetworkConfigResponse: {
> [1656512209.493570][3277:3282] CHIP:TOO:     networkingStatus: 0
> [1656512209.493633][3277:3282] CHIP:TOO:     networkIndex: 0
> [1656512209.493688][3277:3282] CHIP:TOO:    }

> ./chip-tool networkcommissioning add-or-update-wi-fi-network hex:63686970736574757033 matter123 1 0

> [1656512223.867560][3286:3291] CHIP:DMG: Received Command Response Data, Endpoint=0 Cluster=0x0000_0031 Command=0x0000_0005
> [1656512223.867621][3286:3291] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0031 Command 0x0000_0005
> [1656512223.867709][3286:3291] CHIP:TOO:   NetworkConfigResponse: {
> [1656512223.867770][3286:3291] CHIP:TOO:     networkingStatus: 2
> [1656512223.867799][3286:3291] CHIP:TOO:    }

**3.Test Environment**
	
**App used** - allclusters app
**Platform** - Chip-tool - RPI-4, 8GB RAM
           DUT - RPI - RPI-4, 8GB RAM
**Network** - Ble-wifi
**Commit** - c38e9159d0500a880b9c789bf5d87fa16c039633

**Comment by bzbarsky-apple** [comment]
Yes, you can't reorder networks if the list can only hold one network.  If the test plan thinks you can, the test plan needs fixing...
