### ISSUE TITLE
[Pre-SVE] [Groups] Groups Cluster for lock-app works with endpoint 1 not 0

### ISSUE THREAD

**Issue by mamehta** [project-chip/connectedhomeip#20119]
#### Problem
The Group cluster is working with endpoint 1 because it's added in endpoint 1 in the zap config file for the lock-app. It is not working with endpoint 0 which is mentioned in the test case instructions. 

 #### Proposed Solution
The test cases for Groups cluster for the lock-app should be updated with endpoint 1 instead of 0.

**Comment by bzbarsky-apple** [comment]
lock-app should not have groups cluster at all.

Please file test case instructions issues at https://github.com/CHIP-Specifications/chip-test-plans/
