### ISSUE TITLE
distribution_check.sh does not work on Mac

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2011]
#### Problem
Running `scripts/build/distribution_check.sh` (after `scripts/build/bootstrap.sh`) on Mac fails with:
```
make[6]: *** No rule to make target `Linux/gen/DbusBluez.c', needed by `distdir-am'.  Stop.
```

 #### Proposed Solution
Stop looking for Linux-specific generated files on Mac.  Not clear to me yet why we're ending up doing that in the first place.

@robszewczyk @rwalker-apple

**Comment by rwalker-apple** [comment]
the stuff in scripts/build was always only there to support CI, never tested any other way unfortunately

I'll try to have a look later, we need to get more energy pointed at the GN-based build, I think.
