### ISSUE TITLE
"Build ESP32 QEMU and Run Tests" task randomly fails

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2012]
#### Problem
The " Build ESP32 QEMU and Run Tests" task of the "QEMU / ESP32" test seems to fail randomly.  It failed on https://github.com/project-chip/connectedhomeip/pull/2009 for me, then passed when retriggered.

 #### Proposed Solution
Figure out why it fails randomly and fix.  Sadly the logs CI provides don't include the `src/transport/tests/test-suite.log` file that should have included details on the failure.

@pan-apple

**Comment by bzbarsky-apple** [comment]
Logs: [logs_14092.zip](https://github.com/project-chip/connectedhomeip/files/5037589/logs_14092.zip)

**Comment by kpschoedel** [comment]
Seems obsolete.
