### ISSUE TITLE
[Pre-SVE] [EFR32-WiFi] WiFi Diagnostics Read Event for ConnectionStatus not returning struct

### ISSUE THREAD

**Issue by mamehta** [project-chip/connectedhomeip#20173]
#### Problem
TC-DGWIFI-2.2, step 4
Expected: ConnectionStatus event should be returned
Actual outcome: Read event works but doesn't return a struct
DUT: EFR32 + RS9116/WF200
<TODO: Attach logs>

**Comment by bzbarsky-apple** [comment]
>  <TODO: Attach logs>

Please reopen when you do.  ConnectionStatus has a single field, which is an enum; there should be no "struct" involved offhand, other than the one encoding the event itself.
