### ISSUE TITLE
How to modify BUILD.gn or other makefile to set macro PW_ TRACE_ BACKEND_ SET make its is be defined?

### ISSUE THREAD

**Issue by yangchaoFree** [project-chip/connectedhomeip#20204]
I want to see insight of matter protocol code process.
How to modify BUILD.gn to set macro PW_ TRACE_ BACKEND_ SET make its is be defined.

**Comment by rwells1703** [comment]
Is this helpful? It shows 'defines' in the context of Configs, but they can be used in other targets too.
https://gn.googlesource.com/gn/+/main/docs/language.md#Configs

Inside the target you're building (declared in BUILD.gn), you should add the line:
```defines = [ "PW_TRACE_BACKEND_SET" ]```
