### ISSUE TITLE
CHIPTool app crashes on iOS while trying to pair with M5 board

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#20230]
With SHA 6c6dca3b9a32c73647db882237467dff08da06fa

CHIPTool app crashes on iOS when trying to pair via QR code or with manual short pin

**Steps to reproduce:**

1. Build chiptool app on iOS
2. On a command line flash the M5 device
3. Pair the M5 board with CHIPTool iOS app via QR code or using the short pin code.

Attaching the logs from M5 board + from iOS:
[M5logs.txt](https://github.com/project-chip/connectedhomeip/files/9031105/M5logs.txt)
[iOSlogs.txt](https://github.com/project-chip/connectedhomeip/files/9031106/iOSlogs.txt)

**Comment by bzbarsky-apple** [comment]
```
2022-07-01 11:58:45.711632-0700  localhost CHIPTool[4810]: (CHIP) [com.csa.matter:all] ð´ [1656701925711] [4810:861967] CHIP: [DL] Chip stack locking error at '../../../../../../../../../../../test/connectedhomeip/src/messaging/ExchangeContext.cpp:138'. Code is unsafe/racy
```

I wonder whether https://github.com/project-chip/connectedhomeip/pull/20197 fixed this.  Checking now.
