### ISSUE TITLE
not enough space to initialize the connectedhomeip/chip-build-imx:latest container

### ISSUE THREAD

**Issue by FaqiangZhu-nxp** [project-chip/connectedhomeip#20257]
#### Problem
During the CI test, connectedhomeip/chip-build-imx:latest docker image fails to be downloaded because of not enough space. the log is as below:

```
  failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /opt/fsl-imx-xwayland/5.15-kirkstone/sysroots/armv8a-poky-linux/usr/share/terminfo/c/cdc456: no space left on device
```

I pulled the container image on my local server, the info is as below:

```
REPOSITORY                       TAG       IMAGE ID       CREATED        SIZE
connectedhomeip/chip-build-imx   latest    9f9db4e01eb7   5 days ago     33.5GB
```

 * expected behavior: the docker image can be pulled and run to compile the code.
 * actual behavior: the docker image fail to be pulled.
 * steps to reproduce: pull the connectedhomeip/chip-build-imx:latest docker image
 * system configuration: default CI test configuration
 * screenshots, images, logs, etc: check the PR CI test failure info here https://github.com/project-chip/connectedhomeip/runs/7173480484?check_suite_focus=true
 >

 #### Proposed Solution
the docker image should be under "/var" by default. enlarge the related filesystem.

**Comment by bzbarsky-apple** [comment]
Caused by https://github.com/project-chip/connectedhomeip/pull/19941 I assume.  @andy31415 was trying to prod people about this, I think.... 

@FaqiangZhu-nxp
