### ISSUE TITLE
For java binding, ensure the cluster object is be freed when the session is released

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#20267]
#### Problem
The cluster object is ephemeral, but in Java implementation, its lifespan is managed by GC. It must guarantee that the cluster object is be freed when the session is released.

 #### Proposed Solution
The Java and objective-c binding should implement `OnSessionReleased` callback, null-out the cluster, and deny all future operations to the cluster.

**Comment by woody-apple** [comment]
@bzbarsky-apple Should we separate the darwin and android changes here?

**Comment by bzbarsky-apple** [comment]
The Darwin part of this was fixed in https://github.com/project-chip/connectedhomeip/pull/21504: we no longer hold on to CHIPCluster objects anywhere on the heap; we just stack-allocate them.  So this is a pure Android issue now.
