### ISSUE TITLE
[Question] cert->mNotBeforeTime does not convert to UTC, is it right?

### ISSUE THREAD

**Issue by wickyou23** [project-chip/connectedhomeip#20302]
#### Problem

I used the CHIP-tool app for iOS to pairing a device but got a `CHIP Error 0x0000004F: Certificate not yet valid` error. I try to print more logs and detect something went wrong?.

See this line in the log:

`2022-07-05 16:31:54.105325+0700 CHIPTool[27035:1447930] [all] 🟢 [1657013514105] [27035:1447930] CHIP: [TST] [TP]::CurrentChipEpochTime: 710328714 - cert->mNotBeforeTime: 710353903`

`CurrentChipEpochTime: 710328714` -> This time is convert to UTC.
`cert->mNotBeforeTime: 710353903` -> This time is still using UTC+7 (My current timezone).

Note: For more details, you can compare the time when print log (`2022-07-05 16:31:54.105325+0700`).

So when comparing two values, `CurrentChipEpochTime` is always smaller `cert->mNotBeforeTime`.

![Screen Shot 2022-07-05 at 18 25 18](https://user-images.githubusercontent.com/5183190/177317139-e9a04eab-7c3e-430d-ab77-860710aea1a9.png)
`(CHIPCert.cpp:388)`

Full log at client:

[2022-06-27 13:52:16.681694+0700 CHIPTool.log](https://github.com/project-chip/connectedhomeip/files/9046008/2022-06-27.13.52.16.681694%2B0700.CHIPTool.log)

**Comment by bzbarsky-apple** [comment]
@wickyou23 Thank you for catching this, and for the excellent issue report!
