### ISSUE TITLE
[SVE1][TC-OO-1] With OO-LT feature disabled Attributeslist in yaml file should be reduced

### ISSUE THREAD

**Issue by mgarb1** [project-chip/connectedhomeip#20315]
#### Problem
When Test OO_LT == false  elements in the global AttributeList are not applicable.

YAML file:
- label: "Read the global attribute: AttributeList"
      command: "readAttribute"
      attribute: "AttributeList"
      response:
          value:
              [0, 16384, 16385, 16386, 16387, 65528, 65529, 65531, 65532, 65533]
          constraints:
              type: list

However {16384, 16385, 16386, 16387} which is GlobalSceneControl, OnTime, OffWaitTime og StartUpOnOff attributes are not applicaple when OO-LT== false

 #### Proposed Solution
Adjust the yaml file to disregard 16384, 16385, 16386, 16387 when  OO-LT== false for a DUT.

**Comment by cjandhyala** [comment]
@mgarb1 could you file the issue in test scripts repo https://github.com/CHIP-Specifications/chip-test-scripts/issues
