### ISSUE TITLE
*Device methods on `DeviceController` are no longer valid, and highly confusing.

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#20452]
#### Problem

Once #19259 completes, there are a number of *Device methods in `DeviceController` that will no longer make sense:

`UpdateDevice`: This already looks to be deprecated, we should just delete this.
`ReleaseOperationalDevice`: This won't make any more sense once the changes to `OperationalDeviceProxy` lifetime get completed in #19259, since the proxy instance will not be publicly accessible anymore.
`DisconnectDevice`: This should be removed. Consumers who want to expire sessions should go through `SessionManager` directly.

**Comment by tehampson** [comment]
Address the following comments:
* https://github.com/project-chip/connectedhomeip/pull/21256#discussion_r935957897
* https://github.com/project-chip/connectedhomeip/pull/21256#discussion_r935958324

**Comment by bzbarsky-apple** [comment]
> UpdateDevice: This already looks to be deprecated, we should just delete this.

It's deprecated for external use.  For internal use, we use it to implement `OnFirstMessageDeliveryFailed`.  We need a replacement for that, since that's actually a kind of critical part of our error-recovery mechanisms.

**Comment by woody-apple** [comment]
SVE/Cert Blocker Review: Does not appear to be blocking a test case, removing SVE.

**Comment by mrjerryjohns** [comment]
> since that's actually a kind of critical part of our error-recovery mechanisms

FYI it's an optimization, and isn't strictly necessary for correct behavior. We should assess if we really need that for 1.0 given that.

**Comment by bzbarsky-apple** [comment]
> FYI it's an optimization, and isn't strictly necessary for correct behavior. We should assess if we really need that for 1.0 given that.

FYI, a spec SHOULD means "do it unless you have really good reasons not to".  I agree we should assess, but:
1. We have it working, and we are deliberately breaking it.
2. The burden of proof is on proving we should not do it.
