### ISSUE TITLE
[TC-IDM-4.3]Chip-tool support needed to send subscribe Request Message for all events and attributes from the DUT. 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#20479]
**#### Problem**
As per step 16 says "TH sends a subscription request action for an attribute and all events. Set the MinIntervalFloor to some value say "N"(seconds). Change the value of the attribute and trigger an action on the DUT to trigger any event. 
we don't have a option to verify both attributes and events by giving subscribe command"

**System configuration:-**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID:1107d8efe933c925e16db0818ba638a7146b6efd
Dut application: all-clusters-app

**PFA log:-**
![image](https://user-images.githubusercontent.com/95841834/177959724-4b0f4615-5365-43fa-a910-bb3c7a057dd6.png)

**Test-Plan reference**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-4-3-report-data-messages-post-subscription-activation-from-dut-test-cases-dut_server

**Comment by andy31415** [comment]
Would this not be chip-tool interactive instead? I would imagine we want to send several subscribe requests separately.

**Comment by andy31415** [comment]
Cert block review: chip tool cannot currently subscribe to both events and attributes on the same subscription. (interactive or not does not seem relevant).

Existing API does support it (chip repl has an implementation). Need chip-tool implementation.

@vivien-apple could you provide some estimation on how hard this is to add to chip-tool?

**Comment by bzbarsky-apple** [comment]
So this is like https://github.com/project-chip/connectedhomeip/pull/20270 but for subscriptions?  Or does it need more flexibility (e.g. not just wildcard-except-endpoint for the paths)?

**Comment by woody-apple** [comment]
Cert Blocker Review: @vivien-apple can you help add this functionality to chip-tool?

@cjandhyala to provide an example of what the test plan would require (command wise)

**Comment by cjandhyala** [comment]
@mrjerryjohns Per slack conversation, Krithika is not available this week, In the absence of her, Could you pls provide your input on what is the test plan expectation here,  is it on all clusters/one cluster one end point/all end points ..etc
