### ISSUE TITLE
CHIP: [BLE] Service not found on the device

### ISSUE THREAD

**Issue by JourneyYoung** [project-chip/connectedhomeip#20481]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

An iphone12 running on iOS 15.3.1 can not find FFF6 Service. I used two iphone12 to connect the same matter device,  the other one was running on iOS 15.4. When I connected to the matter ble device, the one running on iOS 15.4 can successed create PASE Session, but the other iphone running on 15.3.1 cannot find FFF6 service, then failed to create PASE Session, the error info is "CHIP: [BLE] Service not found on the device" . So I used nRF connect app to look up Matter blutooth service, see as these pictures:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/15240665/178647030-958e8328-b3de-4a1b-8220-ca20998afe20.png">

<img width="791" alt="image" src="https://user-images.githubusercontent.com/15240665/178647150-790491d0-31af-4039-83b0-80e142d9eafc.png">

The failed one can not find FFF6 service. Is this an iOS's bug？How can I fix it?

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by andy31415** [comment]
marked darwin to tag iOS developers. @woody-apple - we do not seem to have a iOS tag (unsure if needed or not)

**Comment by JourneyYoung** [comment]
您好。你的邮件我已经收到，谢谢！

**Comment by woody-apple** [comment]
@JourneyYoung thank you for the report! Can you please let us know what version of the framework the device is using? Does this happen on 15.6 developer releases?
