### ISSUE TITLE
Darwin(no-ble-asan) getting Build failure when we try to write "Basic" cluster attributes

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#20547]
Summary:
Darwin (no-ble-asan)  getting  Build failure for some of the attribute write showing "error: no visible @interface for 'MTRBaseClusterBasic' declares the selector 'writeAttributeVendorNameWithValue:completionHandler:' for tests TC-BINFO-2.1 in which we am trying to write "Basic" clusters attribute and response will be Unsupported_Write.

Diff link:
https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:Darwin_no-ble-asan_Failure

Execution logs:
![image](https://user-images.githubusercontent.com/102359958/178267531-a8f7ce30-5c09-4bfc-a0c9-088638538d55.png)
[logs_1171830.zip](https://github.com/project-chip/connectedhomeip/files/9084088/logs_1171830.zip)

**Comment by bzbarsky-apple** [comment]
This is because the test-only "allow writes to readonly attributes" cluster subclass bits got removed.
