### ISSUE TITLE
[ota] Exchange leak

### ISSUE THREAD

**Issue by Damian-Nordic** [project-chip/connectedhomeip#20565]
#### Problem
When OTA is cancelled due inactivity timeout, the BDX transfer exchange is leaked. Apart from the possibility to run out of exchanges on constrained devices, it causes a Sleepy End Device never getting back to the idle mode, which may drain the battery.
Same thing may occur in different scenarios, such as passing an error to `BDXDownloader::OnPreparedForDownload`.

 #### Proposed Solution
I tried to fix that in a stupid way to close an exchange each time we go back to the idle state, but I wasn't aware of various subtleties of the exchange management and it lead to crashes: https://github.com/project-chip/connectedhomeip/pull/20563.
We need to somehow extend BDX APIs so that we can distinguish cancel events caused by the exchange layer or by external components and close the exchange in the latter cases only.

**Comment by bzbarsky-apple** [comment]
In particular, BDXMessenger is all sorts of broken; starting by fixing that is probably a good idea.  I'll take a stab at it.

**Comment by Damian-Nordic** [comment]
`BDXDownloader::OnPreparedForDownload` is another occurrence that may require manual closing of the exchange, because it is called before any message is sent using that exchange (I think). Also, `BDXDownloader::StartDownload` should probably use `ExchangeHandle` to release the exchange on error.

I don't guarantee there are no more places :)

**Comment by bzbarsky-apple** [comment]
@Damian-Nordic I believe https://github.com/project-chip/connectedhomeip/pull/20632 should address this.....  It's your changes from #20304 plus a fix to BDXDownloader to handle the exchange lifetime correctly.
