### ISSUE TITLE
[OTA Matter.framework] Code is unsafe/racy error message

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#20591]
#### Problem
After setting the OTA delegate in Matter.framework and receiving Query Image InvokeCommand to the controller (Matter.framework), an error message states that the code is unsafe/racy. This appears to be the issue because during the transmission of the message we are using a delegate that is passed in from the caller [here](https://github.com/project-chip/connectedhomeip/pull/20516/files#diff-13bd030c2b38e3e7d4738070dd3c919bbdfe9ec8b39cc29996989936150e6d1fR59).  After inspecting the code, the assertion calls IsChipStackLockedByCurrentThread to check whether messaging is locked. For this to be set to true the following condition needs to be true `!mWorkQueue || mIsWorkQueueSuspended || dispatch_get_current_queue() == mWorkQueue` 

 #### Proposed Solution
Update the queue used to send the message to the node. 

[controller_error_log.txt](https://github.com/project-chip/connectedhomeip/files/9089424/controller_error_log.txt)

**Comment by bzbarsky-apple** [comment]
The `completionHandler` there should be dispatching to the Matter work queue, no?  @carol-apple

**Comment by krypton36** [comment]
@carol-apple I am going to update this.
