### ISSUE TITLE
[SVE1] zap sets old cluster revisions by default for Identify Server Cluster (version 2 instead of 4)

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [project-chip/connectedhomeip#20607]
#### Problem

When creating a new EP and e.g. create an Identify Server Cluster, zap fills in version 2 for the Cluster Revision of Identify. Current value is 4.

 #### Proposed Solution

Set the latest ClusterRevision by default.

**Comment by markus-becker-tridonic-com** [comment]
I noticed this only for Identify when adding a new endpoint and adding the server cluster. Might not be limited to Identify Server cluster though. Yes, I was using the ZAP UI.

**Comment by andy31415** [comment]
Maybe this should be reported to zap? @tecimovic - how do we triage and split bugs between zap and matter sdk?

**Comment by andy31415** [comment]
Assigning myself to validate that our XML is correct. Assume that zap takes the value from the xml.

**Comment by andy31415** [comment]
illuminance-measurement-cluster.xml has 2 instead of 3

**Comment by andy31415** [comment]
preassure-measurement has 2 instead of 3

**Comment by andy31415** [comment]
Created a diffs script, revisions mismatches:
0x0004 should be 4 not 3
0x0301 should be 4 not 3
0x0406 should be 3 not 2

Several other clusters I could not properly parse spec vs code. The spec adocs are  too free form.
