### ISSUE TITLE
[SVE1] Possible memory leak in chip-tool 

### ISSUE THREAD

**Issue by doru91** [project-chip/connectedhomeip#20608]
#### Problem

After successfully commissioning with the 4th administrator, chip-tool reports:

**[1657625195.034286][3459:3459] CHIP:SPT: VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/lib/support/Pool.h:317: Allocated() == 0**

This is 100% reproductible on NXP platform.
[chip_tool_logs_4th_admin.txt](https://github.com/project-chip/connectedhomeip/files/9092507/chip_tool_logs_4th_admin.txt)
[dut_logs_4th_admin.txt](https://github.com/project-chip/connectedhomeip/files/9092508/dut_logs_4th_admin.txt)

Also attached the entire logs on the DUT and chip-tool side.

**Comment by andy31415** [comment]
@cjandhyala - please see above: is this actually a cert blocker (if so please explain and re-add the tag) or was my removal of cert blocker tag correct?
