### ISSUE TITLE
Import ../third_party/connectedhomeip/src/app/clusters/on-off

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#2061]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
@franck-apple I'm not sure what this issue is about.  Where is that path (`../third_party/connectedhomeip/src/app/clusters/on-off-client`) meant to be rooted at?

**Comment by franck-apple** [comment]
My mistake. It's actually ../third_party/connectedhomeip/src/app/clusters/on-off (I corrected the title)
Client part needs to be imported.
Maybe @rwalker-apple can bring some clarity.

**Comment by bzbarsky-apple** [comment]
@rwalker-apple and I talked about this yesterday a bit.  It looks like there is no client part to on-off in the silabs code.  The only commands for it ("Read Attributes Response" and "Default Response", afaict) are not cluster-specific.

**Comment by rwalker-apple** [comment]
yep.  no client.

**Comment by franck-apple** [comment]
Got it. Closing the issue then.
