### ISSUE TITLE
Import ../third_party/connectedhomeip/src/app/clusters/scenes-client

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#2065]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bhaskar-apple** [comment]
Taking this one.

**Comment by bhaskar-apple** [comment]
https://github.com/rwalker-apple/connectedhomeip/pull/6
