### ISSUE TITLE
[Android] How to get ChipDeviceController node id?

### ISSUE THREAD

**Issue by Allen-Guof** [project-chip/connectedhomeip#20668]
I want to upgrade firmware through Android phone as ota provider. The firmware upgrade package is in the local file. But when announceOtaProvider, I can't find providerNodeId. I'm guessing that providerNodeId is the ChipDeviceController node id. Is there anyone who can help me.

**Comment by TheWalkingDead1024** [comment]
@vidhis88 @mspang michael @Damian-Nordic @markus-becker-tridonic-com @austinh0 @ritikananda27 @wgtdkp @vivien-apple @chulspro @pan-apple @g-coppock @joonhaengHeo @woody-apple @emargolis @joonhaengHeo @gmarcosb @chrisdecenzo, could anybody have a look at this issue？Many thanks!

**Comment by TheWalkingDead1024** [comment]
https://github.com/project-chip/connectedhomeip/issues/21517

**Comment by Allen-Guof** [comment]
@yunhanw-google Hi, is there any update on this issue. If the issue is not resolved, please help me change the status of the issue. I do not have the permission.

**Comment by TheWalkingDead1024** [comment]
@https://github.com/yunhanw-google Could you please take a look at this GitHub issue?

**Comment by TheWalkingDead1024** [comment]
@yunhanw-google Could you please take a look at this GitHub issue?
