### ISSUE TITLE
TC-BRBINFO-1.1 - Feature-map attribute should be implemented

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#20731]
**Issue :** 
While Executing the behavior of the global mandatory feature-map attribute  of the Bridged Basic Information cluster, throws error code as 0x86(unsupported attribute).

**Commit used** : 0390a8d33b1d1c709fcc4499eab6e132428ad5e2

- Chip-tool - RPI-4, 8GB RAM
- DUT - RPI - RPI-4, 8GB RAM
- Platform : linux platform
- Dut application: bridge-app
- Expected behavior : Pass with status(0x0)

**Actual behavio**r : Fail with status 0x86(unsupported attribute)
![image](https://user-images.githubusercontent.com/90545664/178998260-4cfb5ee4-7fe9-49ac-aa0a-a6a64e5b9360.png)

**Steps to reproduce :**
./chip-tool bridgeddevicebasic read feature-map 1 3

**Test-plan reference :**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/bridged_device_basic_information.adoc#tc-brbinfo-1-1-global-attributes-for-bridged-device-basic-information-cluster-cluster-dut-server

**Comment by andy31415** [comment]
I think we need to explain/justify cert blocker status a bit here.

Cert blocker in my mind means "Certification cannot prove that the SDK can be used to build an application that can be certified". In this case, we have feature map attributes working in other apps, so the SDK can be used to build certifiable applications.

Bridge app in particular seems not to be updated fully, so this is an issue and we may chose to do so before 1.0, however in terms of certification blocking, I do not believe this is so.

**Comment by andy31415** [comment]
In generally I am trying to avoid code SDK developers being on the hook to develop fully certifiable applications for all possible applications (we have a lot of them already: light, lock, all-clusters, all-clusters-minimal, several tv bits, bridge, ota provider and requestor, shell, thermostat, temperature measurement, window, pump .... etc).

**Comment by cjandhyala** [comment]
@andy31415 Cert blocker is also for something that is failing a certification test case that need fix in SDK and example app, so that CSG can verify the test ones. In this case its blocking a cert TC TC-BRBINFO-1.1.

**Comment by woody-apple** [comment]
Cert Blocker Review: Given bridge app is used for verification, we need to make sure the feature map is correct.

**Comment by franck-apple** [comment]
@jwinder-ca is looking at this.
