### ISSUE TITLE
[SVE][TC-CNET-4.1] thread device’s PICS should NOT test WiFi test case 

### ISSUE THREAD

**Issue by yeccc** [project-chip/connectedhomeip#20734]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >
![PICS_ISSUE_PICS_TO_WRONG_TC_202207141435212](https://user-images.githubusercontent.com/22901855/179003355-9f64aa1c-e4a1-476b-a527-8d90921709e7.png)

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
@cjandhyala

**Comment by franck-apple** [comment]
removing the 'request cert blocker' label, as it's a script issue.

**Comment by woody-apple** [comment]
Cert Blocker Review: This is not an SDK issue. Can you please make sure this is filed in the test harness repo.

**Comment by franck-apple** [comment]
test harness repo: https://github.com/CHIP-Specifications/chip-certification-tool
