### ISSUE TITLE
Switch the zpro encoder/decoder to using BufBound

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2073]
#### Problem
There's a bunch of manual buffer management code in `src/app/chip-zcl-zpro/command-encoder/encoder.c` that can use `BufBound` now that @rwalker-apple's https://github.com/project-chip/connectedhomeip/pull/1947 has landed.

 #### Proposed Solution
Switch these files from C to C++ (still with an `extern "C"` API) and use BufBound where appropriate.

**Comment by bhaskar-apple** [comment]
Working on this currently
