### ISSUE TITLE
[SVE][TC-DGGEN-3.1] PICS can NOT filtered out 3.1 while only chose DUT as server

### ISSUE THREAD

**Issue by yeccc** [project-chip/connectedhomeip#20732]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >
![PICS_ISSUE_PICS_TO_WRONG_TC_20220714143521](https://user-images.githubusercontent.com/22901855/179002391-0af3c11a-c684-41e8-bc33-7fc8cae001a9.png)

<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
This does not look like an SDK issue.  @cjandhyala @naveenkommareddi  where should this be filed?
