### ISSUE TITLE
Unable to pair with on-network device 

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#20762]
With SHA 39e5ed22d5ad4bfc0fbf25d7f82cc01f660a1d35

Unable to pair with on-network device

**Steps to reproduce**

1. cd ~/connectedhomeip
2. git reset --hard  39e5ed22d5ad4bfc0fbf25d7f82cc01f660a1d35
3. export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
4. source scripts/activate.sh
5. rm /tmp/chip_kvs*
6. scripts/examples/gn_build_example.sh examples/all-clusters-app/linux out/debug chip_config_network_layer_ble=false
7 ./out/debug/chip-all-clusters-app --discriminator 3841 --secured-device-port 5560 --KVS /tmp/chip_kvs_test
8. Copy and the paste QR code URL obtained in step 7
9. Build CHIPTool app on iOS using Xcode
10. Scan the QR code using CHIPTool app

**Attaching the logs:**
[iOS logs.txt](https://github.com/project-chip/connectedhomeip/files/9115127/iOS.logs.txt)
[macLogs.txt](https://github.com/project-chip/connectedhomeip/files/9115128/macLogs.txt)

**Comment by bzbarsky-apple** [comment]
@phonnakasturi-apple Looking at the logs, but I just tried those steps on that PR and it works fine for me...

**Comment by bzbarsky-apple** [comment]
Log shows that the server never even got a PBKDFParamRequest from the client.

But the client:
1. Discovered something with the right instance name (`823AD7968F94E157`)
2. Resolved a reasonable-looking IP+port for it (`[fe80::c36:9df2:2d2a:2c91%en2]:5560`).
3. Sent a PBKDFParamRequest
4. Got an ack.

Is it possible that there were multiple copies of all-clusters-app (or other Matter bits) running on port 5560 and the client ended up talking to the wrong one?  @phonnakasturi-apple

**Comment by phonnakasturi-apple** [comment]
@bzbarsky-apple Yes there were 2 instances of ll-clusters-app  running.. I cleared them up and its working fine now
