### ISSUE TITLE
Python based controller Permission error

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#20774]
#### Problem
 * expected behavior
 * actual behavior
 * steps to reproduce

> $ git log -1
> commit 51e41f9dfb49727a90b9641621085e60f642a884 (HEAD -> 51e41f9)
> Author: yunhanw-google <yunhanw@google.com>
> Date:   Wed Jul 13 07:24:56 2022 -0700
> 
>     remove ami.xmp from matter (#20659)

./scripts/build_python.sh -m platform -i separate
source ./out/python_env/bin/activate
sudo out/python_env/bin/chip-device-ctrl

 * system configuration
 * screenshots, images, logs, etc.
[Log.txt](https://github.com/project-chip/connectedhomeip/files/9117273/Log.txt)

**Comment by rachel-li-jci** [comment]
I saw same issue on sve branch, commit 6545766956187317ca62c4be619fdfc91c9d3d95.
any solution to this issue?
