### ISSUE TITLE
[SQA] TC-CNET-4.11 Step 12 : TH is not able to connect back DUT on  WIFI_1ST_ACCESS point

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#20800]
### Problem
After Step 11 : Disarm the failsafe should revert all changes made from step 2-10 and connect back to WIFI_1ST_ACCESS point, so that TH gets connected to DUT on WIFI_1ST_ACCESS point. But TH is not able to connect DUT on WIFI_1ST_ACCESS again.
 
 * Expected behavior : 

>    [1657733596.457792][7640:7645] CHIP:TOO:   Networks: 1 entries
>    [1657733596.457867][7640:7645] CHIP:TOO:     [1]: {
>    [1657733596.457906][7640:7645] CHIP:TOO:       NetworkID: 536265655F4D6F746F
>    [1657733596.457940][7640:7645] CHIP:TOO:       Connected: TRUE
>    [1657733596.457972][7640:7645] CHIP:TOO:      }

 * Actual behavior :

>    [1657882138.081363][3137:3142] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0031 Attribute 0x0000_0001 DataVersion: 4100768981
>    [1657882138.081472][3137:3142] CHIP:TOO:   Networks: 0 entries
>    [1657882138.081595][3137:3142] CHIP:EM: Sending Standalone Ack for MessageCounter:1130145 on exchange 5803i

 ### Steps to reproduce

- Step 11 is a disarm of the failsafe, so all network configurations from step 1 to step 11 should be negated.

- Pretest - DUT is connected to WIFI_1ST_ACCESS_POINT
- step 1: arm the failsafe
- steps 2 - 10: remove WIFI_1ST_ACCESS_POINT, add WIFI_2ND_ACCESS_POINT, Connect to WIFI_2ND_ACCESS_POINT
- step 11: Disarm the failsafe. This should revert all changes made from step 2-10. So DUT should be back in the pretest state, connected to WIFI_1ST_ACCESS point
- Step 12 - TH moves back to WIFI_1ST_ACCESS_POINT

### System configuration

- > DUT : All-cluster-app ( RPI)
- > CNTRL : Chiptool ( RPI)
- > Network : Ble-Wifi

**Comment by cjandhyala** [comment]
@Survensa There seems to be an issue with the test setup. let me close this issue and we will reopen it if the issue still exits.

**Comment by Survensa** [comment]
@cjandhyala please reopen this issue.

**Comment by Survensa** [comment]
Attached full execution log for reference : [cnet-4.11.txt](https://github.com/project-chip/connectedhomeip/files/9219172/cnet-4.11.txt)

**Comment by cjandhyala** [comment]
Dup of #21341
