### ISSUE TITLE
Remove tunneling support for WML baseline

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#2080]
#### Problem
Change #2077 added an unchanged (except license and renaming) copy of weave message layer into chip.

This copy needs to be cleaned up and unnecessary parts removed.

 #### Proposed Solution
One item to remove is any tunneling support. (all ifdefs and dependencies)

**Comment by yufengwangca** [comment]
Currently,  tunneling support exists throughout CHIP stack which include SystemLayer, InetLayer, PlatformLayer (DeviceConfig, ConnectivityManager), MessageLayer, Configuration etc..

Is this issue cover message layer tunnel support only or all the tunnel support in CHIP stack?

**Comment by andy31415** [comment]
I believe we should remove it throughout. Tunneling is currently not supported by CHIP spec.
