### ISSUE TITLE
Audit matter-devices.xml for sanity

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#20809]
#### Problem
We have all sorts of bad copy/paste bugs in matter-devices.xml.  For example, On/Off Plug-In unit has:
```
            <include cluster="Binding" client="true" server="false" clientLocked="false" serverLocked="true">
                <requireAttribute>BINDING</requireAttribute>
            </include>
```
which defaults to including a binding client for some reason, even though the device type does not mention that.

 #### Proposed Solution
Go through this file, align with spec.

**Comment by woody-apple** [comment]
This may be resolved with a bunch of PRs like so:
https://github.com/project-chip/connectedhomeip/pull/21911
Can you confirm?

**Comment by yufengwangca** [comment]
Is Binding cluster one of Base clusters?

Base Cluster Requirements for Matter
Each device type definition SHALL include these clusters, as a minimum set, based on the conformance defined below. This conformance table SHALL assume the Matter conformance condition is TRUE (in Conformance column).
Descriptor
Binding 
FixedLabel
UserLabel

Base Cluster Requirements for Zigbee
Each device type definition SHALL include these clusters, as a minimum set, based on the conformance defined below. This conformance table SHALL assume the Zigbee conformance condition is TRUE (in Conformance column).
Basic

**Comment by yufengwangca** [comment]
Shall those five base clusters be included to each Device Type by default? The device type don't need to mention them explicitly.

**Comment by yufengwangca** [comment]
Each device type is attached to an endpoint, same device type could be attached to different endpoints, so we should have each device type definition include Descriptor cluster which is mandatory base cluster

**Comment by yufengwangca** [comment]
Binding cluster is defined as an Optional base cluster on the server side, so we should be turned off AND user can not turn it on at the client and is turned off but user CAN turn it on at the server side.

<include cluster="Binding" client="false" server="false" clientLocked="true" serverLocked="false">
           <requireAttribute>BINDING</requireAttribute>
</include
