### ISSUE TITLE
IdentifyType wrong value on boot of DUT

### ISSUE THREAD

**Issue by innovation-matters-iot** [project-chip/connectedhomeip#20844]
#### Problem
A value of 0x01 for IdentifyType on the identify cluster:

0x01 | Light output | Light output of a lighting product.

 set by ZAP tool is read as value 0x02 by the DUT on boot.
![image](https://user-images.githubusercontent.com/94078875/179352419-f043af05-659c-4b1a-bf7f-b8d29199a6d2.png)
![image](https://user-images.githubusercontent.com/94078875/179352441-4d9f4e64-a886-4fbe-9bec-1583d802fdc0.png)
![image](https://user-images.githubusercontent.com/94078875/179352562-f9c46227-dcf1-4eff-b717-a35884a35d79.png)

**Comment by bzbarsky-apple** [comment]
The ZAP default is not used for identify in practice.  What matters is how the `Identify` is constructed.  How is it constructed in the case of this DUT @innovation-matters-iot ?

**Comment by innovation-matters-iot** [comment]
It was constructed the wrong way. Thanks for the help!
