### ISSUE TITLE
KeepSubscriptions handling does not match spec

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#20869]
#### Problem
The spec says (in "8.5.2.3. Incoming Subscribe Request Action"):

> If this interaction is not terminated by an error Status Response and KeepSubscriptions is FALSE, all existing or pending subscriptions on the publisher for this subscriber, SHALL be terminated.

and this is the only normative text around KeepSubscriptions.

But the SDK handles KeepSubscriptions before it ever tries to process the new subscription, hence will terminate existing subscriptions even if the new one is going to error out.  This does not match the spec.

 #### Proposed Solution
Follow the spec.

@mrjerryjohns @yunhanw-google

**Comment by woody-apple** [comment]
Spec Review: Let's update the spec, given that's a smaller effort. @bzbarsky-apple to propose the spec change.

**Comment by bzbarsky-apple** [comment]
Filed https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/5484
