### ISSUE TITLE
DefaultOTARequestorDriver::GetMaxDownloadBlockSize() always returns 1024

### ISSUE THREAD

**Issue by eric-ocasio-nxp** [project-chip/connectedhomeip#20898]
Looks like a simple typo. Should return  maxDownloadBlockSize.

**Comment by bzbarsky-apple** [comment]
@selissia @tcarmelveilleux @carol-apple

**Comment by tcarmelveilleux** [comment]
`** Maximum Block Size requested by OTA Requestors over non-TCP transports SHALL be no larger than 1024 (2^10) bytes. OTA Providers SHALL support the Maximum Block Size of at least 1024 bytes in those cases.` 

^^^ I think the fact that a Provider must support 1024 max block size got extrapolated to "let's always test 1024". I agree it should be maxDownloadBlockSize
