### ISSUE TITLE
TC-BINFO-2.1

### ISSUE THREAD

**Issue by martin-bv** [project-chip/connectedhomeip#20894]
#### Problem
Test case FAILS even when the DUT send the correct response 

CHIPTOOL   | 2022-07-17 13:39:05.216478 | [1658090338.792190][25:35] CHIP:DMG: ReportDataMessage =
CHIPTOOL   | 2022-07-17 13:39:05.218374 | [1658090338.792216][25:35] CHIP:DMG: {
CHIPTOOL   | 2022-07-17 13:39:05.219802 | [1658090338.792229][25:35] CHIP:DMG: 	AttributeReportIBs =
CHIPTOOL   | 2022-07-17 13:39:05.221070 | [1658090338.792252][25:35] CHIP:DMG: 	[
CHIPTOOL   | 2022-07-17 13:39:05.222772 | [1658090338.792267][25:35] CHIP:DMG: 		AttributeReportIB =
CHIPTOOL   | 2022-07-17 13:39:05.224479 | [1658090338.792288][25:35] CHIP:DMG: 		{
CHIPTOOL   | 2022-07-17 13:39:05.226261 | [1658090338.792302][25:35] CHIP:DMG: 			AttributeDataIB =
CHIPTOOL   | 2022-07-17 13:39:05.228274 | [1658090338.792317][25:35] CHIP:DMG: 			{
CHIPTOOL   | 2022-07-17 13:39:05.230258 | [1658090338.792333][25:35] CHIP:DMG: 				DataVersion = 0x2ec1937b,
CHIPTOOL   | 2022-07-17 13:39:05.232612 | [1658090338.792348][25:35] CHIP:DMG: 				AttributePathIB =
CHIPTOOL   | 2022-07-17 13:39:05.234840 | [1658090338.792363][25:35] CHIP:DMG: 				{
CHIPTOOL   | 2022-07-17 13:39:05.236786 | [1658090338.792378][25:35] CHIP:DMG: 					Endpoint = 0x0,
CHIPTOOL   | 2022-07-17 13:39:05.239737 | [1658090338.792393][25:35] CHIP:DMG: 					Cluster = 0x28,
CHIPTOOL   | 2022-07-17 13:39:05.241095 | [1658090338.792409][25:35] CHIP:DMG: 					Attribute = 0x0000_0006,
CHIPTOOL   | 2022-07-17 13:39:05.242332 | [1658090338.792423][25:35] CHIP:DMG: 				}
CHIPTOOL   | 2022-07-17 13:39:05.245132 | [1658090338.792440][25:35] CHIP:DMG: 					
CHIPTOOL   | 2022-07-17 13:39:05.246910 | [1658090338.792458][25:35] CHIP:DMG: 				**Data = "in",** 
CHIPTOOL   | 2022-07-17 13:39:05.249749 | [1658090338.792471][25:35] CHIP:DMG: 			},
CHIPTOOL   | 2022-07-17 13:39:05.251102 | [1658090338.792490][25:35] CHIP:DMG: 			
CHIPTOOL   | 2022-07-17 13:39:05.252764 | [1658090338.792504][25:35] CHIP:DMG: 		},
CHIPTOOL   | 2022-07-17 13:39:05.254676 | [1658090338.792522][25:35] CHIP:DMG: 		
CHIPTOOL   | 2022-07-17 13:39:05.256576 | [1658090338.792536][25:35] CHIP:DMG: 	],
CHIPTOOL   | 2022-07-17 13:39:05.258402 | [1658090338.792556][25:35] CHIP:DMG: 	
CHIPTOOL   | 2022-07-17 13:39:05.260086 | [1658090338.792572][25:35] CHIP:DMG: 	SuppressResponse = true, 
CHIPTOOL   | 2022-07-17 13:39:05.261595 | [1658090338.792586][25:35] CHIP:DMG: 	InteractionModelRevision = 1
CHIPTOOL   | 2022-07-17 13:39:05.263170 | [1658090338.792599][25:35] CHIP:DMG: }
CHIPTOOL   | 2022-07-17 13:39:05.264305 | [1658090338.792708][25:35] CHIP:TOO:  ***** Test Failure: location value mismatch, expected 'in' but got 'in
**DEBUG      | 2022-07-17 13:39:05.266500 | Found failure:  location value mismatch, expected 'in' but got 'in
WARNING    | 2022-07-17 13:39:05.268377 | Test Failure:  location value mismatch, expected 'in' but got 'in**

See lines 5266 to 5279 on the log file
[TC-BINFO_2_1_ERROR.log](https://github.com/project-chip/connectedhomeip/files/9135823/TC-BINFO_2_1_ERROR.log)

**Comment by raju-apple** [comment]
@martin-bv can you also attach the trace logs as well ?

**Comment by bzbarsky-apple** [comment]
I don't think the DUT sent the right response here, based on that log.  I suspect that instead of sending `"in"` the DUT sent `"in\0"` (that is, mis-computed its string length and included the trailing null in the data it sent).

@martin-bv Can you please double-check what the DUT is actually sending?

**Comment by woody-apple** [comment]
Cert Blocker Review: Assigning to @cjandhyala to follow up with the DUT, we believe this is a DUT issue.

**Comment by chrisbeach59** [comment]
This is believed to be a TH issue.  The device reported correctly.  The Test case was passing manually, but failed when run in the TH.  Ticket should be against the TH, not SDK

**Comment by chrisbeach59** [comment]
@woody-apple I didn't restore the cert blocker tag, but if the TH is failing it probably is.

**Comment by franck-apple** [comment]
This is not an SDK issue. Can you please make sure this is filed in the test harness repo:  https://github.com/CHIP-Specifications/chip-certification-tool

**Comment by bzbarsky-apple** [comment]
>  The device reported correctly.

I don't think it did @chrisbeach59 .  See this line in the log:

>  DEBUG | 2022-07-17 13:39:05.266500 | Found failure: location value mismatch, expected 'in' but got 'in

That's missing the close quote on the actual value, which is almost certainly because that actual value included an embedded null.

**Comment by bzbarsky-apple** [comment]
> the TH is printing the received packet from the DUT

Yes.

> it looks correct, it has "in", is this true? is the TH printing it correctly?

I suspect not.  Hence the changes in https://github.com/project-chip/connectedhomeip/pull/20934 to also print the length, not just the data up to the first null.

> is the backend using this value to build the pass-fails? 

It's using the actual value, not the value that got printed.

> what is printed in the console is not a mirror of what the DUT is responding to the TH?

It's not in cases when the DUT is including nulls in a char string (which is not a spec-compliant string, and the logging code does not handle this case of spec-non-compliance too well).

**Comment by bzbarsky-apple** [comment]
Note that we might be able to improve the logging to show nulls as `\0` or something like that.  Patches very much accepted...
