### ISSUE TITLE
Port spake2p tool to Python

### ISSUE THREAD

**Issue by Damian-Nordic** [project-chip/connectedhomeip#20932]
#### Problem
`spake2p` tool for generating Spake2+ verifier can be quite easily implemented in Python.
Python port would be more portable and easier to integrate in build systems.

 #### Proposed Solution
Tennessee has almost complete implementation. We just need to add command line parsing.

**Comment by ihidchaos** [comment]
Agreed, this will make it easier to use spake2p and chip-cert on windows platforms.
