### ISSUE TITLE
Simplify enum checking in door lock code

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#20936]
There are also some places in the door lock ([here](https://github.com/project-chip/connectedhomeip/blob/8e26081616d736cd0427bdf3846da4220d80ea0a/src/app/clusters/door-lock-server/door-lock-server.cpp#L290), [here](https://github.com/project-chip/connectedhomeip/blob/8e26081616d736cd0427bdf3846da4220d80ea0a/src/app/clusters/door-lock-server/door-lock-server.cpp#L300), [here](https://github.com/project-chip/connectedhomeip/blob/8e26081616d736cd0427bdf3846da4220d80ea0a/src/app/clusters/door-lock-server/door-lock-server.cpp#L606), [here](https://github.com/project-chip/connectedhomeip/blob/8e26081616d736cd0427bdf3846da4220d80ea0a/src/app/clusters/door-lock-server/door-lock-server.cpp#L615) and [here](https://github.com/project-chip/connectedhomeip/blob/8e26081616d736cd0427bdf3846da4220d80ea0a/src/app/clusters/door-lock-server/door-lock-server.cpp#L2988)) where we check the range of the enum value. Maybe we can now simplify the checks and just verify the value against corresponding `kUnknownEnumValue`?

_Originally posted by @Morozov-5F in https://github.com/project-chip/connectedhomeip/pull/20907#discussion_r924173531_

**Comment by DanM-AssaAbloy** [comment]
This is not a must have for v1.0. This clean up will happen post 1.0
