### ISSUE TITLE
What happen with next version of Matter data model that want to add something stated 6 ?

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#20956]
What happen with next version of Matter data model that want to add something stated 6 ?
same question apply  for all these enum.
When we iterate and add new feature or bump up enum list , then this might be an issue 
I just wondering how this gonna be handled in the future

_Originally posted by @jmeg-sfy in https://github.com/project-chip/connectedhomeip/pull/20937#discussion_r924770608_

**Comment by woody-apple** [comment]
Note, filed this @jmeg-sfy

**Comment by bzbarsky-apple** [comment]
See https://github.com/project-chip/connectedhomeip/pull/20937#discussion_r924979917

@mrjerryjohns and I don't think there's a problem here.

**Comment by bzbarsky-apple** [comment]
Note also discussion in https://github.com/project-chip/connectedhomeip/issues/24368
