### ISSUE TITLE
Determine next path for fabric provisioning in WML baseline

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#2097]
#### Problem
WML baseline was added with dependencies as header-only (so that we get WRM, dispatch, framing etc, without pulling in all dependencies given that WML is very guardian-knot-like and pulls in a lot of things).

Next path for some profiles is clear (e.g. directory service is easy to remove, security handles sessions, so it can be updated based on SCTT spec), however fabric provisioning is not as clear yet.

 #### Proposed Solution
Determine the plan for fabric provisiongin:
   - is this a concept that we want to keep _or_
   - remove this profile

If we do not know path forward yet, I would propose to bias towards removing it first so that we get a linkable WML that can be used.

**Comment by yufengwangca** [comment]
This issue is not valid anymore since WML baseline is not selected.
