### ISSUE TITLE
nordic 平台light-switch-app&lighting-app  Demo待机一晚均会出现死机现象

### ISSUE THREAD

**Issue by ZhongShangWen** [project-chip/connectedhomeip#20976]
**light-switch-app log**

![image](https://user-images.githubusercontent.com/36146106/179882177-f60829c2-1679-46a5-9f45-ffd57e1e0be3.png)

**lighting-app log**

![image](https://user-images.githubusercontent.com/36146106/179882590-d4cd4248-cfd3-4ea8-97bd-f63804f5b509.png)

**Comment by ZhongShangWen** [comment]
**chip commit 记录**
![image](https://user-images.githubusercontent.com/36146106/179882961-1a19eed3-7332-4450-a9f4-5d91e4e1af7d.png)

**Comment by SteveCruise** [comment]
兄弟加油，30w智能家居装修就等matter成熟了

**Comment by Damian-Nordic** [comment]
I think it has been fixed in the light switch sample and later, more generally by:
> commit 72ada957a02a6056499779f6184b10a8252431b9
> Author: Damian Królik <66667989+Damian-Nordic@users.noreply.github.com>
> Date:   Fri Jul 1 23:29:22 2022 +0200
>
> [zephyr] Fix crash on saving TotalOperatingHours to KVS (#20214)

Could you confirm that the issue is not appearing using a revision newer than that?
