### ISSUE TITLE
iOS tv-casting-app: Allow selecting a receiver after commissioning

### ISSUE THREAD

**Issue by sharadb-amazon** [project-chip/connectedhomeip#21029]
#### Problem
The iOS tv-casting-app only allow sending media/casting commands to the TV that commissioned it. There is no way to send commands to one or multiple other TVs on the fabric. 

 #### Proposed Solution
Update iOS MatterTvCastingBridge Framework to allow setting the target (targetVideoPlayerInfo and endpointId) on the CastingServer. The casting/media commands would then be sent to the selected TV.

**Comment by bzbarsky-apple** [comment]
Is this about Android or iOS?  Summary says Android, text says iOS, but then talks about JNI....

**Comment by sharadb-amazon** [comment]
Updated title/description. This is for iOS.
