### ISSUE TITLE
[TC-G-2.2] Unsupported access when adding multiple groups

### ISSUE THREAD

**Issue by pankore** [project-chip/connectedhomeip#21076]
#### Problem
- In the setup steps, we are required to do `key-set-write`, then do `write group-key-map` for all the groups.
- After doing that for groups 1, 2, 3, 4, doing `add-group` for 1, 2 and 3 will result in unsupported access.
- `add-group` for 4 returns success.

[tc-g-2.2.txt](https://github.com/project-chip/connectedhomeip/files/9162614/tc-g-2.2.txt)

**Comment by bzbarsky-apple** [comment]
OK, so the actual commands executed here are:
```
chip-tool groupkeymanagement key-set-write '{"groupKeySetID": 42, "groupKeySecurityPolicy": 0, "epochKey0": "d0d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime0": 2220000,"epochKey1": "d1d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime1": 2220001,"epochKey2": "d2d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime2": 2220002 }' 1 0
```
which adds the keys, for keyset 42
```
chip-tool groupkeymanagement write group-key-map '[{"groupId": 1, "groupKeySetID": 42, "fabricIndex": 1}]' 1 0
```
which binds keyset 42 to group id 1.
```
chip-tool groupkeymanagement write group-key-map '[{"groupId": 2, "groupKeySetID": 42, "fabricIndex": 1}]' 1 0
chip-tool groupkeymanagement write group-key-map '[{"groupId": 3, "groupKeySetID": 42, "fabricIndex": 1}]' 1 0
chip-tool groupkeymanagement write group-key-map '[{"groupId": 4, "groupKeySetID": 42, "fabricIndex": 1}]' 1 0
```
which re-binds keyset 42 to group ids 2, 3, 4.  After this group id 4 has keys associated, and the other group ids do not.
```
chip-tool groups add-group 0x0001 grp1 1 1
```
which will fail becuase group 1 has no group id.

You probably want to do something more like this:
```
chip-tool groupkeymanagement write group-key-map '[{"groupId": 1, "groupKeySetID": 42 }, {"groupId": 2, "groupKeySetID": 42 }, {"groupId": 3, "groupKeySetID": 42 }, {"groupId": 4, "groupKeySetID": 42 }]' 1 0
```

If those group-key-map writes came from the verification step spreadsheet, please file an issue on that?

@cjandhyala
