### ISSUE TITLE
Fabric deletion should synchronously clean-up all relevant IM objects

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#21084]
#### Problem

Fabric deletion doesn't actually synchronously clean-up affected IM objects today. They each discover this implicitly when they get around to allocating exchanges off of a session that no longer exists.

#### Solution

Register for `OnFabricChanged` in the IM engine, and use that to drive the clean-up.

**Comment by woody-apple** [comment]
Issue Review: Keeping in v1.0 for now.
