### ISSUE TITLE
[Android] "pairing fail" occurs after save network on CHIPTool app.

### ISSUE THREAD

**Issue by tatsutaigu** [project-chip/connectedhomeip#21093]
#### Problem
 * actual behavior
`pairing fail` occurs after save network on CHIPTool app.
 * steps to reproduce
1. Press `PROVISION CHIP DEVICE WITH WI-FI`
2. Enter Payload MTxxxxx in bottom box
3. Press `SUBMIT`
4. Enter WiFi SSID and Password
5. Press `SAVE NETWORK`
6. Start pairing and find device, but pairing fail

 * system configuration
connectedhomeip : commit https://github.com/project-chip/connectedhomeip/commit/513235823b2a1f6b5a299f71feef9e28c95dc1cf (HEAD -> master, origin/master, origin/HEAD)
Android device : Huawei mediapad m3 lite
Cluster App : all-clusters-app
Cluster device : ESP32-C3-DevkitM-1

 * screenshots, images, logs, etc.
[esp32c3-0721.txt](https://github.com/project-chip/connectedhomeip/files/9163731/esp32c3-0721.txt)

Is it concern about below errors?

>  I (108761) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 1) status= 0 
> E (108771) chip[SVR]: Failsafe timer expired
> I (108781) chip[SC]: SecureSession[0x3fc945c8]: Moving from state 'kActive' --> 'kPendingEviction'
> E (108791) chip[SVR]: Commissioning failed (attempt 1): 32
> I (108791) chip[BLE]: Releasing end point's BLE connection back to application.
> I (108801) chip[DIS]: Updating services using commissioning mode 1
> I (108801) chip[DIS]: CHIP minimal mDNS started advertising.
> I (108811) chip[DIS]: Advertise commission parameter vendorID=65521 productID=32769 discriminator=3840/15
> I (108831) chip[DIS]: CHIP minimal mDNS configured as 'Commissionable node device'.
> I (108831) chip[DIS]: mDNS service published: _matterc._udp
> E (108841) chip[ZCL]: OpCreds: Got FailSafeTimerExpired
> E (108841) chip[ZCL]: OpCreds: Proceeding to FailSafeCleanup on fail-safe expiry!
> E (108851) chip[FP]: Reverting pending fabric data for fabric 0x1
> I (108851) chip[TS]: Pending Last Known Good Time: 2022-07-21T10:57:11

**Comment by jonsmirl** [comment]
Failure from the Android app....
 OpCreds: Failed AddNOC request with IM error 0x85

I (841990) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 0) status= 0 
E (842000) chip[DL]: Long dispatch time: 694 ms, for event type 7
I (842070) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
I (842160) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
I (842160) chip[EM]: Received message of type 0x8 with protocolId (0, 1) and MessageCounter:38710441 on exchange 9894r
I (842170) chip[ZCL]: OpCreds: Received an AddNOC command
E (842170) chip[ZCL]: OpCreds: Failed AddNOC request with IM error 0x85
I (842180) chip[IN]: Prepared secure message 0x3ffdecd4 to 0xFFFFFFFB00000000 (0)  of type 0x9 and protocolId (0, 1) on exchange 9894r with MessageCounter:262313159.
I (842190) chip[IN]: Sending encrypted msg 0x3ffdecd4 with MessageCounter:262313159 to 0xFFFFFFFB00000000 (0) at monotonic time: 00000000000CD6ED msec
I (842210) NimBLE: GATT procedure initiated: notify; 
I (842210) NimBLE: att_handle=14

Working log from chip-tool...

 (15431) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 0) status= 0 
E (15441) chip[DL]: Long dispatch time: 692 ms, for event type 7
I (15501) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
I (15601) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
I (15701) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
I (15701) chip[EM]: Received message of type 0x8 with protocolId (0, 1) and MessageCounter:200151212 on exchange 1980r
I (15711) chip[ZCL]: OpCreds: Received an AddNOC command
I (15721) chip[FP]: Validating NOC chain
I (16981) chip[FP]: NOC chain validation successful
I (16981) chip[FP]: Added new fabric at index: 0x1
I (16981) chip[FP]: Assigned compressed fabric ID: 0xBB32F7DBFC5A30EF, node ID: 0x000000000000D903
I (16991) chip[TS]: Last Known Good Time: 2022-07-26T18:54:08
I (16991) chip[TS]: New proposed Last Known Good Time: 2021-01-01T00:00:00
I (17001) chip[TS]: Retaining current Last Known Good Time
I (17021) chip[ZCL]: OpCreds: ACL entry created for Fabric index 0x1 CASE Admin Subject 0x000000000001B669
I (17021) chip[DIS]: Advertise operational node BB32F7DBFC5A30EF-000000000000D903
I (17031) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'.
I (17041) chip[DIS]: mDNS service published: _matter._tcp
I (17041) chip[ZCL]: OpCreds: successfully created fabric index 0x1 via AddNOC

**Comment by jonsmirl** [comment]
This failure has been reproduced by three independent developers now.

I fully cleaned system (deleted 'out' and Android 'build' ) and rebuilt -- no change.

**Comment by jonsmirl** [comment]
I tried rebuilding from a clean checkout using these instructions:
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/android_building.md

This command fails:
./scripts/build/build_examples.py --target android-arm64-chip-tool build

It is missing a gn command.
2022-07-27 08:26:25 INFO    Building JNI android-arm64-chip-tool
2022-07-27 08:26:25 INFO    ninja: Entering directory `/home/jonsmirl/aosp/connectedhomeip/out/android-arm64-chip-tool'
2022-07-27 08:26:25 WARNING ninja: error: loading 'build.ninja': No such file or directory

Adding this doesn't fix it
 ./scripts/build/build_examples.py --target android-arm64-chip-tool gen

So something is broken in the build process for the Android app.

**Comment by jonsmirl** [comment]
BTW, doing "gn gen ." in /home/jonsmirl/aosp/connectedhomeip/out/android-arm64-chip-tool will get you past the build failure.

But the error is still there when built from a clean checkout....
E (842170) chip[ZCL]: OpCreds: Failed AddNOC request with IM error 0x85
