### ISSUE TITLE
[Android] QR code scanner does not work on CHIPTool app.

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#21091]
#### Problem
 * actual behavior
QR code scanner does not work on CHIPTool App.

 * steps to reproduce

1. Show QR CODE : https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3AXXXXXXXXXXXXXXXXXXX
2. Press `SCAN QR CODE` or `PROVISION CHIP DEVICE WITH WI-FI` on Android app
3. Camera is starting, however, it does not detect QR CODE

 * system configuration
connectedhomeip : commit 513235823b2a1f6b5a299f71feef9e28c95dc1cf (HEAD -> master, origin/master, origin/HEAD)
Android device : Huawei mediapad m3 lite
Cluster App : all-clusters-app
Cluster device : ESP32-C3-DevkitM-1

**Comment by jonsmirl** [comment]
This works for me on a Google Pixel 3.
