### ISSUE TITLE
TC-CGEN-2.3 test steps are missing.

### ISSUE THREAD

**Issue by manogna-silabs** [project-chip/connectedhomeip#21103]
TC-CGEN-2.3 test steps are missing in the latest excel sheet.

https://silabs.sharepoint.com/:x:/s/MatterCHIPAlpha/ERtCQcDJjkxDivLQSH_NtOUBvojI8G3lcG-21dzg7TPjzg?e=ODi3Ok

Thanks,
G. Manogna

**Comment by bzbarsky-apple** [comment]
This is not the right repo for issues in the excel sheet.

@cjandhyala What is the right repo?

**Comment by cjandhyala** [comment]
Correct, The TC is removed in the test plans, hence not there in the excel sheet. For any test plan and steps issue, pls file issue in test plans repo. closing the ticket here.
