### ISSUE TITLE
Client-side logic doesn't send `InvalidSubscription` error back correctly

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#21125]
#### Problem

If a report is received that doesn't match any existing subs present on the client, the SDK today doesn't send back an `InvalidSubscription` error. Instead, it just sends back a StatusResponse containing success.

This violates the spec.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/src/app/ReadClient.cpp#L471,  it seems we are sending status failure if that is invalid subscription in client side, it seems that we just need to send InvalidSubscription status.

**Comment by yunhanw-google** [comment]
fixed in 
https://github.com/project-chip/connectedhomeip/pull/21368
https://github.com/project-chip/connectedhomeip/pull/21500
