### ISSUE TITLE
Default priority for Door Closed and Door Open events need to be CRITICAL.

### ISSUE THREAD

**Issue by akrithika27** [project-chip/connectedhomeip#21176]
#### Problem
Currently only Door Closed event is CRITICAL. According to this comment - https://github.com/CHIP-Specifications/chip-test-plans/pull/1896#issuecomment-1194125912  both of them should default to CRITICAL. 

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
I don't understand the issue here @akrithika27.  The SDK always emits DoorStateChange events with CRITICAL priority right now.

This is also what https://github.com/CHIP-Specifications/chip-test-plans/pull/1896#issuecomment-1193618188 said.
