### ISSUE TITLE
Darwin framework needs to safely shut down subscriptions when controllers shut down

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#21198]
#### Problem
When a Mater.framework controller shuts down, any live subscriptions associated with its fabric should also get cleanly shut down.  Right now we would end up with dangling pointers and crashes in that scenario.

 #### Proposed Solution
Have the framework track subscriptions and shut them down.

**Comment by bzbarsky-apple** [comment]
@jtung-apple

**Comment by woody-apple** [comment]
Darwin Issue Review: We believe this is resolved, closing for now.

**Comment by bzbarsky-apple** [comment]
This is handled by `chip::DeviceController` now after #22323.
