### ISSUE TITLE
Bridge-functionality - The keypress is aborting the DUT

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#21212]
**Issue :**
We have test-steps saying to press 'c' to read the state in bridge-app and press 'b' in bridge-app to change the light which are aborting the DUT 
![image](https://user-images.githubusercontent.com/90545664/180936104-c19e40a9-447a-4919-922c-45e5e2123062.png)

- Commit used : 29873290196796fbf23e28083163f8565bb479ba
- Chip-tool - RPI-4, 8GB RAM
- DUT - RPI - RPI-4, 8GB RAM
- Platform : linux platform
- Dut application: bridge-app

**Test-plan reference**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/bridge.adoc#ref_TC-BR-4

**Comment by sowmyassp** [comment]
The Keypress 2 and 4 is also aborting DUT 
![image](https://user-images.githubusercontent.com/90545664/181721303-67a25436-3d77-454e-b84a-247ce25ba111.png)

**Comment by bzbarsky-apple** [comment]
@sowmyassp https://github.com/project-chip/connectedhomeip/pull/21287 should fix those on Linux.  On Mac some more work will be needed to make it work....

**Comment by sowmyassp** [comment]
@bzbarsky-apple I am working it on Linux itself, but its aborting in linuc too
