### ISSUE TITLE
Provisioning not working on M1 MacBook

### ISSUE THREAD

**Issue by rosahay-silabs** [project-chip/connectedhomeip#21227]
#### Problem
Commission not working on the macbook M1 Pro.

 * expected behavior
     User should be able to commission DUT by using the chip-tool on the M1 macbook.
 * actual behavior
     User unable to commission the DUT.
 * steps to reproduce
     - Compile chip-tool on device.
     - Put device in the BLE advertisement mode.
     - Start commissioning process on macbook.
 * system configuration:
     - MacBook Pro M1(Apple silicon)/macOS Monterey(12.2.1)
     - RS9116+MG24, device under test(DUT)

[macbook.chip-tool.run.log](https://github.com/project-chip/connectedhomeip/files/9189721/macbook.chip-tool.run.log)

**Comment by bzbarsky-apple** [comment]
@woody-apple Is 12.2.1 one of the MacOS versions with issues around BLE commissioning with chip-tool?

**Comment by woody-apple** [comment]
Yes please, @rosahay-silabs can you try the latest macOS release? There were some known BLE issues on previous releases

**Comment by woody-apple** [comment]
Please re-open if this happens on the newest releases
