### ISSUE TITLE
[TC-OCC-3.2] all-clusters-app has no functionality to change occupancy status

### ISSUE THREAD

**Issue by s-mcclain** [project-chip/connectedhomeip#21236]
#### Problem
Occupancy Sensing cluster test case TC-OCC-3.2 still requires the Test Harness (all-cluster-app, etc.) to change the occupancy status in some way. This is not currently supported in the current applications which makes it impossible to execute this test case where the DUT is the client.

 #### Proposed Solution
Enable some sort of argument/mechanism for the all-cluster-app to be able to change the occupancy status on the application.

**Comment by woody-apple** [comment]
Cert Blocker Review: Need to find an owner for this. Lower priority given this is optional.

**Comment by woody-apple** [comment]
Cert Blocker Review: Marking this as 'needs provisional' unless we have a resolution to this issue today.
