### ISSUE TITLE
TC-BRBINFO-2.2 - ReachableChanged event - Need information for verification steps

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#21270]
**Problem** - Need information for verification steps for reading ReachableChanged event 

**App used** - bridge-app

**Platform**
 Chip-tool - RPI-4, 8GB RAM
DUT - RPI-4, 8GB RAM

**Network** - ethernet

**Commi**t - 29873290196796fbf23e28083163f8565bb479ba

**Sequence of steps I tried with :**
1. Commission DUT with TH using below commands :
        DUT - sudo ./chip-bridge-app
        Controller - ./chip-tool pairing ethernet 20202021 3840 fe80::e65f:1ff:fe0f:2753  5540
2. ./chip-tool bridgeddevicebasic read-event reachable-changed   1 0

PFA Logs:
[event.txt](https://github.com/project-chip/connectedhomeip/files/9197509/event.txt)

**Note : This is not SDK issue but need information how to verify the leave event**

**Comment by bzbarsky-apple** [comment]
> Note : This is not SDK issue but need information how to verify the leave event

Leave or reachable?

The way to verify this would presumably be to have a bridge, have a device behind the bridge, then remove that device behind that bridge so the bridge can no longer reach it....

As you said, not an SDK issue.
