### ISSUE TITLE
Need to add temperature sensor in bridge-app

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#21401]
**Issue :** 
Need to add temperature sensor in bridge-app when chip-tool read DeviceTypeList with EP3, 4, 5, 6, 10,11, 12, 13.
When DeviceTypeList is read with above EP, the device-list should contain Type 770(Temperature sensor)

**PFA Logs:** 
[BR.txt](https://github.com/project-chip/connectedhomeip/files/9218832/BR.txt)

**Comment by bzbarsky-apple** [comment]
@sowmyassp Does https://github.com/project-chip/connectedhomeip/pull/21287 resolve this?

**Comment by sowmyassp** [comment]
@bzbarsky-apple Yes 21287 will resolve this issue so closing this issue here will follow up with 21287, thank you
