### ISSUE TITLE
Bridge-functionality - The keypress 2 and 4 is aborting the DUT

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#21410]
**Issue :**
The keypress 2 and 4 are aborting the DUT
![image](https://user-images.githubusercontent.com/90545664/181770857-e4815add-9b30-494a-a29d-bebbfbb263e1.png)

**Commit used** : https://github.com/project-chip/connectedhomeip/commit/29873290196796fbf23e28083163f8565bb479ba
**Chip-tool** - RPI-4, 8GB RAM
**DUT** - RPI - RPI-4, 8GB RAM
**Platform** : linux platform
**Dut application**: bridge-app

**Comment by bzbarsky-apple** [comment]
On Linux, https://github.com/project-chip/connectedhomeip/pull/21287 will fix this, by holding the right locks.

On Mac, we will need a bit more work.  But given this issue is for RPI, https://github.com/project-chip/connectedhomeip/pull/21287 should be enough.

**Comment by sowmyassp** [comment]
Ok then I will follow up with 21287 PR on linux, and close this isue here
