### ISSUE TITLE
TC-BINFO-2.2 test case 

### ISSUE THREAD

**Issue by ChengqiangShe** [project-chip/connectedhomeip#21482]
How can I generate shutdown event in TC-BINFO-2.2 test case

**Comment by bzbarsky-apple** [comment]
if you are using an actual device, you would do it by shutting down the device.  If you are using one of the simulated "example app" devices, you can kill the app.

**Comment by lisaaaas** [comment]
Hello, I want to know what shut down the DUT means. I have the same result as you, but I have not solved this problem at present
