### ISSUE TITLE
 When will Android API support firmware update?

### ISSUE THREAD

**Issue by TheWalkingDead1024** [project-chip/connectedhomeip#21517]
When will Android API support firmware update?

**Comment by TheWalkingDead1024** [comment]
@bzbarsky-apple any update？

**Comment by bzbarsky-apple** [comment]
@TheWalkingDead1024 I'm not sure why you're asking me about an _Android_ issue....

**Comment by srdantas** [comment]
any updates about this?

**Comment by TheWalkingDead1024** [comment]
> @TheWalkingDead1024 I'm not sure why you're asking me about an _Android_ issue....

Thank you for your response. I apologize for any confusion.

Would you be able to point me in the direction of the team member who handles the Android development? I have this issue related to the Android part of the project and would really appreciate any guidance you could provide.

Thank you so much for your time and assistance.

**Comment by TheWalkingDead1024** [comment]
@yunhanw-google hi, could you please have look at this issue?

**Comment by yunhanw-google** [comment]
Hi @TheWalkingDead1024 we have landed the support for Android OTA/BDX functionality in sdk side, please try the latest code, and use android chip-tool to experiment this functionality, feel free to ping me directly in slack, my slack id is [Google]yunhanw, thanks
