### ISSUE TITLE
Apple Homekit can't control device when device reset.

### ISSUE THREAD

**Issue by shchen-Lab** [project-chip/connectedhomeip#21521]
Hi
I refer apple homekit user guide， this guide can add commission and control my device. My device is BL602 Lighting  example firmware.  This device code commit id  8638802e06fce1501c5c73b40a1d4eae98d076cb base interop_testing_te9 branch.  It can't control by homekit app when device reset.
![image](https://user-images.githubusercontent.com/75290921/182301550-e38f0808-c5e4-40d1-9f95-819f000cf691.png)
![1848c779a2b0a0d8c22f1e0df42117c](https://user-images.githubusercontent.com/75290921/182301619-a4a8b5a1-78b2-4c81-bfb3-f32a49c9d83d.jpg)

[https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md](url)

**Comment by bzbarsky-apple** [comment]
When you say "device reset" do you mean power cycle or factory reset?

For the latter, I would not expect it to be controllable anymore.

For the former, I would expect it to work after a single error now that https://github.com/project-chip/connectedhomeip/pull/21504 is in.  At least once that's picked up by the Home app.

**Comment by shchen-Lab** [comment]
@bzbarsky-apple   I mean power cycle reset .
