### ISSUE TITLE
source bootstrap.sh cloning unnecessary submodules

### ISSUE THREAD

**Issue by shubhamdp** [project-chip/connectedhomeip#21520]
#### Problem
- Clone chip repo to depth 1
    ```
    git clone --depth 1 https://github.com/project-chip/connectedhomeip.git /tmp/connectedhomeip
    ```

- Shallow clone the submodules with depth 1 for specific platform
    ```
    scripts/checkout_submodules.py --shallow --platform esp32
    ```

- Below is the output for `source scripts/bootstrap.sh`, and it is deep cloning the submodules
```
$ source scripts/bootstrap.sh
Cloning into '/private/tmp/chip/third_party/bouffalolab/bl602_sdk/repo'...
....
```

 #### Proposed Solution
- It should not clone the submodules or at least do a shallow copy

**Comment by dhrishi** [comment]
@mspang Can you please help?

**Comment by Damian-Nordic** [comment]
I guess `bootstrap.sh` could simply call `git submodule update` (without `--init`) if `third_party/pigweed/repo/pw_env_setup/util.sh` already exists. That way it would preserve the user's choice on which submodules should be fetched.

**Comment by shubhamdp** [comment]
@Damian-Nordic This would be happening in CI as well right?

**Comment by Damian-Nordic** [comment]
CI uses `activate.sh` which doesn't do any submodule update if the mentioned `util.sh` file exists.

**Comment by shubhamdp** [comment]
Got it, Shall I put up a PR?

**Comment by Damian-Nordic** [comment]
If @mspang is OK with that, I don't have any objections :).

**Comment by Damian-Nordic** [comment]
Note `--init` is probably needed if `[ ! -f "$_CHIP_ROOT/third_party/pigweed/repo/pw_env_setup/util.sh" ]`. Alternatively, we could simply edit this line to:
```
git submodule update --init third_party/pigweed/repo
```
to only update the submodule that bootstrap depends on.

**Comment by Damian-Nordic** [comment]
This is already resolved by https://github.com/project-chip/connectedhomeip/pull/24383
