### ISSUE TITLE
PICS expression parsing return wrong value

### ISSUE THREAD

**Issue by innovation-matters-iot** [project-chip/connectedhomeip#21532]
#### Problem
The PICSBooleanExpressionParser in [PICSChecker.h](https://github.com/project-chip/connectedhomeip/blob/ed95611a2d4a2b62b4e99c533b899442baad1894/src/app/tests/suites/include/PICSChecker.h#L40) returns false when it should be true which results in skipped testcases.

TC:
https://github.com/project-chip/connectedhomeip/blob/cbd90ca207260147f89107cc728071a0baab6253/src/app/tests/suites/certification/Test_TC_CC_6_1.yaml#L46-L51

Inputs from parsed xml file: 

- CC.S.A000F=1
- CC.S.F04=1

Output in TH2_beta:

- Test Step Not Applicable: TH writes 0 to the Options attribute - Test step skipped: [1659428417.346307][25:36] CHIP:TOO: **** Skipping: CC.S.F04 && CC.S.A000f == false

**Comment by bzbarsky-apple** [comment]
@innovation-matters-iot `CC.S.A000f` (as in the YAML file) and `CC.S.A000F` (as in the parsed XML) are not the same thing.   Per https://docs.google.com/document/d/1xuQsjFEjIyqPgxlySE7q74o6ppQj-R54vPOD0VzLDtI/edit#heading=h.xg8lq46m7f3b the right spelling is `CC.S.A000f` as in the YAML file: under "Attribute Support" it says:

> ID is attribute identifier as 4 lowercase hex digits

https://github.com/project-chip/connectedhomeip/pull/21432 added a workaround to treat PICS as case-insensitive (incorrectly; they're case-sensitive) in chip-tool to deal with situations like this, but ideally the XML file involved will be fixed to have the right PICS.
