### ISSUE TITLE
[Thread] OpenThread configuration is not reverted on reboot when fail-safe is armed.

### ISSUE THREAD

**Issue by Damian-Nordic** [project-chip/connectedhomeip#21543]
#### Problem
Previously, the network commissioning driver's `RevertConfiguration` method was automatically called after a reboot with the fail-safe armed.
After https://github.com/project-chip/connectedhomeip/pull/20010/, the fail-safe cleanup on boot is only done when the fail-safe marker has been saved into KVS, which happens at the beginning of `CommissioningComplete` command handler.

 #### Proposed Solution
Call `RevertConfiguration` on boot manually in the generic Thread driver.

**Comment by bzbarsky-apple** [comment]
@tcarmelveilleux

**Comment by bzbarsky-apple** [comment]
Maybe we should be saving the marker earlier....
