### ISSUE TITLE
Subscription id handling in ReadClient is weird

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#21594]
#### Problem
In ReadClient, we:

1. Read and try to verify SubscriptionId values even if we're not a subscription.  This is pretty broken.
2. Enforce that the SubscriptionId in a Subscribe Response matches the previous Report Data, and fail if it does not.  The spec does not say to do this.  This might need to be a spec issue instead.  It's really not clear to me why the spec has a SubscriptionId in Subscribe Response at all, given that it's in the Report Data bits....
3. Have an `mIsPrimingReports` that seems to be used only for `mSubscriptionId` management and does not have clearly defined semantics.  It does have a name that suggests it should be true during the entire priming read, though, which it's not....

 #### Proposed Solution
Align with spec, make code understandable, add tests.

**Comment by yunhanw-google** [comment]
for 2, spec issue is here https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/5525
