### ISSUE TITLE
[Data Model] TLV encoder/decoder

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#2165]
#### Problem
Existed Imported code is used a fixed buffer implementation. The request from the data model team is to use TLV. 

 #### Proposed Solution
Move to TLV. 

Need spec from data model team for format.

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/2168 is a prerequisite for this.

**Comment by woody-apple** [comment]
SW BRB: @andy31415 who was working on this?
