### ISSUE TITLE
[ESP32] incorrect link in README.md

### ISSUE THREAD

**Issue by tatsutaigu** [project-chip/connectedhomeip#21745]
#### Problem
 * actual behavior
[https://github.com/project-chip/connectedhomeip/tree/master/examples/all-clusters-app/esp32#chip-esp32-all-clusters-example](https://github.com/project-chip/connectedhomeip/tree/master/examples/all-clusters-app/esp32#chip-esp32-all-clusters-example
)
 [setup ESP-IDF and CHIP Environment](https://github.com/project-chip/connectedhomeip/tree/master/examples/all-clusters-app/esp32#setup-esp-idf-and-chip-environment) and [Build, Flash, Monitor, and Commissioning](https://github.com/project-chip/connectedhomeip/tree/master/examples/all-clusters-app/esp32#build-flash-monitor-and-commissioning) are looped in README.md.
I cannot find information which set up esp-idf & chip environment, build, flash, monitor and commissioning. 
links are incorrect.

I did not check other examples.

**Comment by dhrishi** [comment]
Oops. Looks like this is the case with the recent changes. Will update asap.
