### ISSUE TITLE
Socket service is not connected if keep iOS app in background for a while

### ISSUE THREAD

**Issue by JourneyYoung** [project-chip/connectedhomeip#21783]
Hello. When we test our app with chip-tool on darwin, if we keep app on backgroud for a while then make it to the front, the socket service can never connected again, and matter framework will loop log print "Socket is not connected", see as the picture. This issue will make us can not pair any matter device unless we restart the app. 
So I want to know how to fix this?

<img width="1393" alt="wecom-temp-3c25815a537d8aa9176db2442e4b28f3" src="https://user-images.githubusercontent.com/15240665/183881593-b7b062b7-4d14-4bb9-a5ef-e051ec489b2a.png">

**Comment by JourneyYoung** [comment]
We use iPhone12 running on iOS 15.4

**Comment by bzbarsky-apple** [comment]
This is a known limitation of the current iOS CHIPTool.  See also https://github.com/project-chip/connectedhomeip/issues/584

**Comment by JourneyYoung** [comment]
您好。你的邮件我已经收到，谢谢！

**Comment by bzbarsky-apple** [comment]
And right now the fix is "restart the app".

**Comment by JourneyYoung** [comment]
Now this issue will call iOS App OOM crash,  how can I close socket service when the app on backgroup?

**Comment by woody-apple** [comment]
Darwin Issue Review: Not critical for 1.0, moving to 1.1

**Comment by woody-apple** [comment]
Dup of: https://github.com/project-chip/connectedhomeip/issues/584
