### ISSUE TITLE
commissioning from multi commissioner

### ISSUE THREAD

**Issue by tatsutaigu** [project-chip/connectedhomeip#21780]
#### Problem
How do I do commissioning from multi commissioner?

When chip-tool on Linux finished commissioning, cluster stopped BLE advertising.
CHIPtool on Android cannot access to cluster and cannot start commissioning because cluster stopped BLE advertising.

![image](https://user-images.githubusercontent.com/44219065/183845098-ed20441c-8f0f-4dd2-aaa2-f0c1b1e7f649.png)

As my understanding, Matter specified to access from multi home network.
for example, one cluster can be controlled from Alexa, Google assistant and Siri on the same network and at same time.

 * system configuration
 connectedhomeip: commit 34ef52cf5cbdb4fb74320fa638845726f3fe3a81
 example: all-clusters-app for esp32

**Comment by dhrishi** [comment]
@tatsutaigu After the first commissioning is done, the commissioning for the next admin can be done over the IP network (on-network commissioning) and BLE isn't required in that case.

After commissioning, you can use the Linux chip-tool commands to put the device into commissioning mode (using open basic/enhanced commissioning window) and then try to commission with the Android app (I am not sure if the app supports that) as the next admin

Or you can do the other way round: First commission the device over BLE using the Android app as first admin and then select option "Multi-Admin Cluster" and then add the Linux chip-tool as the next admin
