### ISSUE TITLE
Wrong error code set in GetWeekDaySchedule for missing user

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#21791]
#### Problem
Door lock spec, in "5.2.4.16.1. Status" says:

> NOT_FOUND if both WeekDayIndex and UserIndex are within the valid range, however, there is not corresponding schedule entry found.

but what the SDK implements in `DoorLockServer::getWeekDayScheduleCommandHandler` has:

```
    if (!userExists(endpointId, userIndex))
    {
        emberAfDoorLockClusterPrintln("[GetWeekDaySchedule] User does not exist [endpointId=%d,weekDayIndex=%d,userIndex=%d]",
                                      endpointId, weekDayIndex, userIndex);
        sendGetWeekDayScheduleResponse(commandObj, commandPath, weekDayIndex, userIndex, DlStatus::kFailure);
        return;
    }
```

which is using FAILURE instead of NOT_FOUND, afaict.

It's not clear to me whether there is a certification test for this...

@mykrupp @cjandhyala @naveenkommareddi 

 #### Proposed Solution
Double-check that I am not missing something, and if not fix the error code.

**Comment by mykrupp** [comment]
I think the spec is not clear as to what happens if the user index is in a valid range, but there is no user in the index. The spec doesn't say it, but shouldn't this return NOT_FOUND? Or maybe USER_NOT_FOUND?

The other potential issue is that checking whether or not the schedule at the current given index is done in the Linux example, when it should be done in door-lock-server unless I am missing something. (i.e. that it was deliberately done this way). But seems unlikely as door-lock-server has a userExists function. Seems that the solution should be adding a scheduleExists function to door-lock-server.

**Comment by mykrupp** [comment]
More succinctly - What happens when a user index is in valid bounds, but there is no user found there? What is the response? Is this defined in the spec?

**Comment by bzbarsky-apple** [comment]
Again, the spec says:

>   NOT_FOUND if both WeekDayIndex and UserIndex are within the valid range, however, there is not corresponding schedule entry found.

Which means NOT_FOUND in the scenario you describe, no?  No user means no schedule entry...

**Comment by mykrupp** [comment]
You are technically correct. No user means no schedule entry. I didn't immediately jump to that conclusion. 

I guess I would have liked to clearly see something like 

NOT_FOUND If a valid user index is given, but no user is found in that index.

NOT_FOUND if both WeekDayIndex and UserIndex are within the valid range, however, there is not corresponding schedule entry found

Just my thought

**Comment by bzbarsky-apple** [comment]
Yes, it would have been nice for the spec to be clearer here; a spec issue to that effect might be good.

In the meantime, the SDK needs to do what the spec says...  ;)

**Comment by mykrupp** [comment]
The SDK should then probably also be doing the checking for missing schedules which is currently done in the linux example

**Comment by bzbarsky-apple** [comment]
@mykrupp Was a spec issue ever raised here?

**Comment by mykrupp** [comment]
I did not raise a spec issue. Willing to do so now if we still think this is relevant.

**Comment by bzbarsky-apple** [comment]
@mykrupp Yes, this is still relevant....

**Comment by mykrupp** [comment]
https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6285

**Comment by jrhees-cae** [comment]
This also similarly affects GetYearDaySchedule commands
