### ISSUE TITLE
Some functions of DeviceInfoProvider does not work 

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#21798]
#### Problem
Currently, some functions of DeviceInfoProvider does not work since storage delegate has not been setup for DeviceInfoProvider. 

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by mrjerryjohns** [comment]
Is this needed for 1.0?

**Comment by yufengwangca** [comment]
Yes, I think this is needed for 1.0. PR has been put up.

I saw we already have a workaround in Linux implementation,  but it does not fix the initialization order issue , we need to first setup DeviceInfoProvider then setup the storage delegate of  DeviceInfoProvider.
