### ISSUE TITLE
Did not receive a response from TestSpecificResponse using Matter API

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#21807]
#### Problem
When invoking the command on the TestCluster(4294048773)-> TestSpecificResponse(0) using the API below in the Matter framework, we do not receive response data and only get the command path object.
```
- (void)invokeCommandWithEndpointId:(NSNumber *)endpointId
                          clusterId:(NSNumber *)clusterId
                          commandId:(NSNumber *)commandId
                      commandFields:(id)commandFields
                 timedInvokeTimeout:(NSNumber * _Nullable)timeoutMs
                        clientQueue:(dispatch_queue_t)clientQueue
                         completion:(MTRDeviceResponseHandler)completion;
```

For command field I have tried the following:
```
'{"type": "Structure", "value":[]}' 
{"type": "Structure", "value":[{"contextTag": 0, "data": {"type": "UnsignedInteger", "value": 7}}]}
```

Note: chip-tool also does not report a response with the following command:
./out/host/chip-tool any command-by-id 4294048773 0 {} 1122 1

**Comment by bzbarsky-apple** [comment]
`TestSpecificResponse` is a response command.  You can't issue it from the client.

Command id 0 for a client-to-server on TestCluster is the Test command, which has no fields and just has a status response.

Command id 2 for a client-to-server command on TestCluster is the TestSpecific command, which has no fields and will get a TestSpecificResponse in response
