### ISSUE TITLE
Try to reuse the lwIP pbuf in UDPEndPointImplLwIP.cpp

### ISSUE THREAD

**Issue by gjc13** [project-chip/connectedhomeip#21816]
#### Problem

Currently all the UDP packets are copied to fit the `PacketBuffer` memory model.

 #### Proposed Solution

Check the memory layout of the lwIP pbuf and reuse it if it already fits the `PacketBuffer`.

**Comment by bzbarsky-apple** [comment]
Per https://github.com/project-chip/connectedhomeip/pull/20923#issuecomment-1204501799 I think we can do better than that and only copy when copying is actually needed, but just make sure we do it correctly for non-inline pbufs.
