### ISSUE TITLE
Using different commissioner name other than beta or gamma in chip-tool interactive mode throws segmentation error 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#21828]
Issue:
While doing provision to RD1, RD2, RD3, RD4 and RD5 on distinct fabrics in RPI platform TC-IDM-7.1 facing following issue
After successful provision of RD4  using "--commissioner-name 4"  If RD4 is try to send any command in interactive mode throws segmentation error
 for example "basic write node-label 1 4 0  --commissioner-name 4" in interactive mode I am getting segmentation fault for commissioner-name other then beta or gamma
![image](https://user-images.githubusercontent.com/95841834/184130713-24377e7f-bfc3-4a32-b20a-f7df733cc6e6.png)

 * **expected behavior** : We should get the expected outcome as per test-plan
 * **actual behavior** : Segmentation fault
 * **steps to reproduce:-**
For example
 Commission DUT to TH
./chip-tool interactive start
For example below command, but for all the commands getting segmentation fault
basic write node-label 1 4 0  --commissioner-name 4

 **system configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : IP and wifi
Commit-ID : a1643eee5ef5534d494ae205bb586b4a9cbfee23 
Dut application: all-clusters-app
 
**PFA log below:-**
[TC-IDM-7.1.txt](https://github.com/project-chip/connectedhomeip/files/9308572/TC-IDM-7.1.txt)

**Test-Plan reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-7-1-multi-fabric-subscription-test-cases-dut_server

**Comment by bzbarsky-apple** [comment]
Steps to reproduce:

1. Start all-clusters-app.
2. `./chip-tool pairing code 4 36390931024  --commissioner-name 4`
3. `./chip-tool interactive start`
4. `basic write node-label 1 4 1  --commissioner-name 4`

ASAN says:
```
==97506==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000106973d88 at pc 0x000105f32e4a bp 0x700007910700 sp 0x7000079106f8
READ of size 8 at 0x000106973d88 thread T1
    #0 0x105f32e49 in chip::internal::HeapObjectList::ForEachNode(void*, chip::Loop (*)(void*, void*))+0x49 (chip-tool:x86_64+0x1012fae49)
    #1 0x1062faa95 in chip::Loop chip::HeapObjectPool<chip::CommissioneeDeviceProxy>::ForEachActiveObject<chip::Controller::DeviceCommissioner::FindCommissioneeDevice(unsigned long long)::$_0>(chip::Controller::DeviceCommissioner::FindCommissioneeDevice(unsigned long long)::$_0&&)+0x105 (chip-tool:x86_64+0x1016c2a95)
    #2 0x1062fa8cc in chip::Controller::DeviceCommissioner::FindCommissioneeDevice(unsigned long long)+0x1fc (chip-tool:x86_64+0x1016c28cc)
    #3 0x1062fb2ef in chip::Controller::DeviceCommissioner::GetDeviceBeingCommissioned(unsigned long long, chip::CommissioneeDeviceProxy**)+0x5f (chip-tool:x86_64+0x1016c32ef)
    #4 0x105ccb15e in ModelCommand::RunCommand() ModelCommand.cpp:40
    #5 0x105cd6594 in CHIPCommand::RunQueuedCommand(long) CHIPCommand.cpp:386
```
```
