### ISSUE TITLE
[New Cluster] IAS ACE

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#2184]
Figure out if we need this cluster, and/or implement it

**Comment by woody-apple** [comment]
@bzbarsky-apple anything remaining here?

**Comment by bzbarsky-apple** [comment]
It's not entirely clear whether we need this cluster.  It's needed for "security systems" from the device list, but nothing else.

Silicon Labs does not seem to have an implementation of this cluster, as far as I can tell.  @selissia @wehale is that right?

**Comment by selissia** [comment]
Yes, that's right, there's no implementation.
