### ISSUE TITLE
TestCommandHandlerWithProcessReceivedEmptyDataMsg not quite checking the status returned from `ProcessInvokeRequest`

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#21863]
#### Problem

In `TestCommandInteraction::TestCommandHandlerWithProcessReceivedEmptyDataMsg`, the act of sending an invoke where messageIsTimed did not match transactionIsTimed previously used to result in a status response being sent out.

I don't see that anymore after I synced up to master

**Comment by bzbarsky-apple** [comment]
In a normal message reception flow it would be sent (by the caller).  TestCommandHandlerWithProcessReceivedEmptyDataMsg directly calls an internal implementation message that returns status that the caller then sends.   Perhaps it should check the returned status?

**Comment by mrjerryjohns** [comment]
Ah ok. In that case, will take off the spec label.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/21871

**Comment by yunhanw-google** [comment]
fixed
