### ISSUE TITLE
build android chip-tool error in android studio

### ISSUE THREAD

**Issue by xufangbo** [project-chip/connectedhomeip#21880]
#### Problem
build android chip-tool in android studio has such error:
~~~
In file included from{chip-tool}/src/crypto/CHIPCryptoPALmbedTLS.cpp:23:
{chip-tool}/src/crypto/CHIPCryptoPAL.h:26:10: fatal error: 'crypto/CryptoBuildConfig.h' file not found
~~~

matterSdkSourceBuild is setting to 'true' in file {chip-tool}/src/android/CHIPTool/gradle.properties

 #### Proposed Solution
-

**Comment by sunshinehu** [comment]
I have the same problem when building android chip-tool on M1 Mac

**Comment by IoT-Project-MDS** [comment]
Did you solve this problem? i have the same issue.

**Comment by lliebig** [comment]
I ran into the same issue and found the missing files in the output folder of the core Matter code.

For example:
`connectedhomeip/out/android_arm64/gen/include`

I have just copied the files to the expected location. But afterwards I ran into another build issue:

`FAILED: connectedhomeip/out/android_arm64/gen/src/controller/java/java.classlist `

**Comment by lliebig** [comment]
I started over and realized, that I forgot to execute this in the terminal:

`./scripts/build/build_examples.py --target android-arm64-chip-tool build`

Given in:
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/android_building.md#building-android-chiptool-from-scripts

**Comment by felixbaral** [comment]
i have the same issue, any solution yet?

**Comment by theyoung** [comment]
There is a "fatal error: 'crypto/CryptoBuildConfig.h' file not found" error that occurred during the build android artifact. Does any other option exist?

**Comment by ManBali** [comment]
ye,i havae the same issue, any one know how to solve it

**Comment by felixbaral** [comment]
I am using the app with nordic stuff anyways so i tried their repo and v2.1.0 tag and i did not have the error there: https://github.com/nrfconnect/sdk-connectedhomeip/tree/v2.1.0

**Comment by fangxiaoying** [comment]
> Do you know the tag base on which branch? My side didn't encourage the issue before.

**Comment by fangxiaoying** [comment]
> 

Do you know the tag base on which branch? My side didn't encourage the issue before.

**Comment by fangxiaoying** [comment]
> I am using the app with nordic stuff anyways so i tried their repo and v2.1.0 tag and i did not have the error there: https://github.com/nrfconnect/sdk-connectedhomeip/tree/v2.1.0

Do you know the tag base on which branch? My side didn't encourage the issue before.
