### ISSUE TITLE
Color control cluster tests don't take the execution time of commands into wait time. This leads to an increase in time intervals more than described in the test steps documentation.

### ISSUE THREAD

**Issue by AntonGrey** [project-chip/connectedhomeip#21990]
#### Time intervals between test steps, can be more than described in the test steps documentation.
I took TC-CC-5.2 as an example.
 * steps to reproduce:
   1. Run TC-CC-5.2.
   2. See timestamps of steps in the log. I have got the following results. 
   * Step 2a. TH sends MoveColor command.
   Timestamp of receiving response `[1660752213.977571][227245:227250] CHIP:DMG: status = 0x00 (SUCCESS),`
   * Step 2b. After 10 seconds, TH reads CurrentX
   Timestamp is `[1660752224.984597][227245:227250] CHIP:DMG: Data = 31976, `
   * Step 2c. After another 10 seconds, TH reads CurrentX
   Timestamp is `[1660752237.688875][227245:227250] CHIP:DMG: Data = 30706,`
   * Step 2d. After another 10 seconds, TH reads CurrentX
   Timestamp is `[1660752249.664296][227245:227250] CHIP:DMG: Data = 29506,`

| Test step time wait | Actual timestamp in seconds | Expected timestamp in seconds  |
| ------------- | --------- | ----- |
| Start               | 213.9  | 213.9 |
| Wait 10 seconds     | 224.9  | 223.9 |
| Wait 10 seconds     | 237.6  | 233.9 |
| Wait 10 seconds     | 249.6  | 243.9 |

At the end of the command execution, the time difference is about 6 second. This leads to a false failure of the test.

 * system configuration: chip-tool bundled from TH 2.3, Signify DUT as a server.
 * log:  [TC-CC-5.2.log](https://github.com/project-chip/connectedhomeip/files/9372067/TC-5.2.log)

**Comment by ifyall** [comment]
This was refiled in the scripts project and can be closed.
