### ISSUE TITLE
Chip tool needs override for device attestation check to continue to commission in case of device attestation failure

### ISSUE THREAD

**Issue by vinay-apple** [project-chip/connectedhomeip#22027]
#### Problem

Presently in chip tool there is no override for device attestation check to continue to commission in case of failure

SHA: 2e10854201c8b1c0bdf8fba5d53a7b47b7e101c0

 #### Proposed Solution

Chip tool needs override for device attestation check to continue to commission in case of device attestation failure

[chip-tool-cli-pairing-M5-fail.txt](https://github.com/project-chip/connectedhomeip/files/9378538/chip-tool-cli-pairing-M5-fail.txt)

**Comment by shubhamdp** [comment]
From the logs:
```
Failed in verifying 'Attestation Information' command received from the device: err 604. Look at AttestationVerificationResult enum to understand the errors
```
 
https://github.com/project-chip/connectedhomeip/blob/3f69587863e92405c0c9d99667be0b4ab200ed70/src/credentials/attestation_verifier/DeviceAttestationVerifier.h#L69


To pass this stage, VID in basic cluster, CD and DAC shall match.

I see VID reported by basic cluster is 0x1111, can you please check if DACs and CD has the same VID.
