### ISSUE TITLE
Port weave network profile/protocol baseline to CHIP

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#2207]
Per Rendezvous TT + Service & Device Management TT Provisioning joint meeting in Aug 17,2020, with broad agreement, we decide to port weave network profile/protocol baseline to CHIP.
Later, we will convert the GAP/improvement we discussed to github ticket and address one by one.

**Comment by woody-apple** [comment]
We'll need to see how this fits into the existing CHIP code, given the network profile won't work as is. Are there documents and/or specs we can share with developers?
