### ISSUE TITLE
[SVe2 ] [TC-CC-1.1]featureMap value mismatch in lighting-app example

### ISSUE THREAD

**Issue by tulasi-silabs** [project-chip/connectedhomeip#22095]
#### Problem
Getting the featureMap value mismatch in lighting-app example
Precondition:
Update the testHarness Version: v2.3 and Sha: ed69865  and Upload the latest pics file and  upload in to the testHarness
Steps:
1.Choose the test case TC-CC-1.1
2.Run the test case through testHarness

Expected:It should run all the test cases by maching the expected output as per the test case 
As per the test cases we should get the below output-
./chip-tool colorcontrol read feature-map 1 1

Verify feature-map value is 31  in  TH(chip-tool)  Logs:

HIP:TOO: Endpoint: 1 Cluster: 0x0000_0300 Attribute 0x0000_FFFC DataVersion: 540305990
[1651482978.090885][3167:3172] CHIP:TOO:   **FeatureMap: 31**
[1651482978.090993][3167:3172] CHIP:EM: Sending Standalone Ack for MessageCounter:14913055 on exchange 54094i

Actual: Found failure in the testHarness at step Read the global attribute:FeatureMap
DEBUG      | 2022-08-23 06:17:12.262812 |Found failure:  featureMap value mismatch: expected 0 but got 31
WARNING    | 2022-08-23 06:17:12.264695 | Test Failure:  featureMap value mismatch: expected 0 but got 31

Tested on:
Test Harness version:v2.3 and Sha: ed69865
Commit id : 7d424839ff11b8ddb9c656d0721730433c9d526a

Logs:
[UI_Test_Run_2022_8_23_11_46_56.log](https://github.com/project-chip/connectedhomeip/files/9400028/UI_Test_Run_2022_8_23_11_46_56.log)

**Comment by sowmyassp** [comment]
@tulasi-silabs  We have use all-clusters-app for CC test-cases

**Comment by cjandhyala** [comment]
Pls open issue in the scripts repo. this is not SDK issue, closing it here.

**Comment by innovation-matters-iot** [comment]
https://github.com/CHIP-Specifications/chip-test-scripts/issues/406
