### ISSUE TITLE
Hex dump method missing to help log payloads during debugging

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#22136]
#### Problem
- We don't have an easy way to dump a binary payload during debugging to assist diagnosing issues
- Most platforms have output log line length limitations
- For large payloads like certificates, temporary buffers may be large, and need to be pre-allocated before we can dump hex

 #### Proposed Solution
Implement at `DumpSpanAsHex` that *trivially* dumps a buffer in easy to extract hex notation

**Comment by bzbarsky-apple** [comment]
We have a `LogByteSpan` thing, right?  This might not be "easy to extract", though.

**Comment by bzbarsky-apple** [comment]
We also have `DataModelLogger::LogValue` which is using a somewhat different output format....
