### ISSUE TITLE
Whether the Extension attribute of the ACL is optional or mandatory

### ISSUE THREAD

**Issue by 66sheng** [project-chip/connectedhomeip#22145]
#### Problem
Whether the Extension attribute of the ACL is optional or mandatory

Extension is mandatory in [TC-ACL-1.1] of Draft_SVE2_TestPlanVerificationSteps
However display in Access Control cluster.xml is optional

**Comment by bzbarsky-apple** [comment]
This is optional in the spec.  Filed https://github.com/CHIP-Specifications/chip-test-plans/issues/2103 on the verification steps.

**Comment by cjandhyala** [comment]
closing the issue as the PICS updated in the test plan
