### ISSUE TITLE
Apple Store Review: "Matter.framework" is not permitted, do not include platform frameworks in your app.

### ISSUE THREAD

**Issue by JourneyYoung** [project-chip/connectedhomeip#22155]
#### Problem
I notice the darwin framework's name is "Matter.framework" and the newest iOS16 system contains this framework. Our App has contained matter.framework, when I tried to apply it to the TestFlight, I got this message:

"'Matter.framework' is not permitted. Do not include platform frameworks in your app."

We want thoes who use  iphones running on iOS15 or earlier  can use Matter, how can I make matter.framework in our app?

 #### Proposed Solution
Can I change the framework's name to use it?

**Comment by JourneyYoung** [comment]
@bzbarsky-apple   Hello.  Do your team have plan to resolve this issue?

**Comment by bzbarsky-apple** [comment]
@woody-apple Please take a look?

**Comment by woody-apple** [comment]
Hi @JourneyYoung. Thanks for the issue! Matter.framework is shipping by default on the iOS platform (and has for a while), so feel free to use that if you can. That said, if you want to bring another framework named "Matter.framework" I encourage you to rename yours so there are no runtime conflicts with the system provided Matter.framework.

**Comment by CaoJieNan** [comment]
@JourneyYoung May I ask how you handled this issue? Did you directly rename the "Matter.framework"?

**Comment by JourneyYoung** [comment]
@CaoJieNan just use Matter.framework which provide by Apple

**Comment by CaoJieNan** [comment]
@JourneyYoung Understood, thank you for your response! If I still wish to use my self-compiled Matter.framework, do you have any recommendations?
