### ISSUE TITLE
Remove #define for CHIP_CONFIG_ENABLE_RELIABLE_MESSAGING

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#2215]
Should we just remove this define? We need reliable messaging in CHIP :)

_Originally posted by @woody-apple in https://github.com/project-chip/connectedhomeip/pull/2206_

**Comment by yufengwangca** [comment]
Confirmed with Grant, this feature is mandatory for all products, we can remove this feature flag

**Comment by yufengwangca** [comment]
The decision whether to use RMP or UDP is made at the Binding level, when Binding is created there will be a setting whether RMP should be used for this protocol
