### ISSUE TITLE
Cleanup kChipMessageFlag_ReuseMessageId, as well as other message flags

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#2217]
This is a straight copy from weave, no attempts at updating. I think we should update in separate PRs (lots of cleanup needed in general).

I expect the entire security model needs to be plugged out and replaced with SCTT.

_Originally posted by @andy31415 in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ3MTgyMjAyNQ==/comments/review_comment_

**Comment by yufengwangca** [comment]
It looks this issue has already been taken cared with https://github.com/project-chip/connectedhomeip/pull/2264
