### ISSUE TITLE
Changes from PR 22104 break commissioning flows where the network info is provided later

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#22195]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/22104 changed things so we do only on-network discovery if we don't have network credentials at commissioning start.

But the infrastructure @chrisdecenzo put in place allows providing the network credentials later, async, after performing a scan for available networks, etc.  It's no longer possible to provide those credentials after start of commissioning when using the "commission by pairing code" APIs (as opposed to the "create PASE session by pairing code, then commission by device id" APIs).

 #### Proposed Solution
Revert #22104.

@vivien-apple @woody-apple

**Comment by vivien-apple** [comment]
I suspect this is related to the changes in #20766 ?

Can't we add a new field to `CommissioningParameters` such that we can rely on that to force the network scan if no credentials are provided ?
And in `chip-tool` an optional param can be added to enable/disable this flag...

**Comment by bzbarsky-apple** [comment]
> I suspect this is related to the changes in https://github.com/project-chip/connectedhomeip/pull/20766 ?

Yes.

> Can't we add a new field to CommissioningParameters such that we can rely on that to force the network scan

Yes, we can.  That would also address this issue.  

The problem is not forcing a network scan, by the way.  That will happen if there are no credentials and we discovered over BLE.  The problem is not skipping BLE discovery.

**Comment by andy31415** [comment]
@vivien-apple - is this fixed now given that #22300 is merged?
