### ISSUE TITLE
Return valid code MTRError when commissioning is attempted with duplicate NOC

### ISSUE THREAD

**Issue by skothawade-apple** [project-chip/connectedhomeip#22214]
#### Problem
MTRError doesn't define code for duplicate fabric, therefore clients receive MTRError with default code 1. Here is how error message looks like-

```
Error Domain=MTRErrorDomain Code=1 "Undefined error:126." UserInfo={underlyingError=<MTRErrorHolder: 0x106223f20>, NSLocalizedDescription=Undefined error:126., errorCode=126}
```

 #### Proposed Solution
We should define a new MTRError code and return that instead of above

**Comment by aajain-com** [comment]
This is needed so we can gracefully handle cases where the accessory is already added to the fabric previously.

**Comment by bzbarsky-apple** [comment]
Note to self: that's `CHIP_ERROR_FABRIC_EXISTS`.
