### ISSUE TITLE
How we can enable/disable features using run_zaptool?

### ISSUE THREAD

**Issue by jadhavrohit924** [project-chip/connectedhomeip#22219]
#### Problem
* How we can enable/disable features using run_zaptool.sh?
* How we can get details of features added in clusters using run_zaptool.sh?

Example : I can see entry of lighting feature [here](https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/onoff-cluster.xml#L100) in the xml. How to use/enable it?

**Comment by bzbarsky-apple** [comment]
> How we can enable/disable features using run_zaptool.sh?

By setting the default value of the FeatureMap attribute for the relevant cluster and then enabling/disabling the relevant attributes/commands for the relevant cluster.

There is, so far, no support for any sort of smart mapping of feature flags to attributes/commands in ZAP.  Please file isses on https://github.com/project-chip/zap/ as needed.

> How we can get details of features added in clusters using run_zaptool.sh?

I'm not sure what this is asking.

**Comment by jadhavrohit924** [comment]
Ok, Thanks.
Second question was about attributes and commands.

**Comment by bzbarsky-apple** [comment]
@jadhavrohit924 What is the specific question about them?  How to tell whether a given attribute or command is enabled for a given cluster instance?

**Comment by jadhavrohit924** [comment]
I want to create API's of attributes and commands of features using these xmls. Xml only tells up about which cluster have wich features but not the details like attributes and commands?
