### ISSUE TITLE
CmakeLists.txt  file error 

### ISSUE THREAD

**Issue by venkateshBATT067** [project-chip/connectedhomeip#22228]
#### Problem ---->   CmakeLists.txt  file error 

Hi 

I am getting " C:\Users\Karthik\Downloads\sdk-connectedhomeip-2.0.2\out\android_arm64\CMakeLists.txt but that file doesn't exist "
error while building application.

**Comment by andy31415** [comment]
What are the commands used building? I am not sure we ever built these on Windows.
