### ISSUE TITLE
ColorTemperatureMireds naming does not match spec

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#22278]
#### Problem
ColorTemperatureMireds is called ColorTemperature in our XML.

This makes various APIs that are generated based on the XML have naming that does not match the spec.

The on-the-wire bits are correct; this is just an issue in terms of the resulting generated API surface.

 #### Proposed Solution
Fix the naming in the XML.

The only drawback is that this will also change the attribute name chip-tool uses for read/write command lines.

**Comment by andy31415** [comment]
Will accept a patch for this based on the discussion in slack and PR.
