### ISSUE TITLE
Actions cluster - ChipTool throws (UNSUPPORTED_COMMAND) for [TC-ACT-3.2]

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#22288]
With SHA 5471b35f09beafd7db4a5e6ccb9ca2e63d7c9010 from sve-2 branch

For [TC-ACT-3.2] Functionality with client as DUT, chip-tool throws  the following error:
`Run command failure: IM Error 0x00000581: General error: 0x81 (UNSUPPORTED_COMMAND)`

**Steps to reproduce**

1. Build bridge app and execute ./chip-bridge-app  on raspi
2. Pari chip tool from mac
3. Execute the command as mentioned in the test case -> ./chip-tool actions start-action-with-duration 0x1001 100 1 14. 

Note: fails with both with darwin-framework-tool and chip-tool

**Attaching the logs**

[TC-ACT-3.2-THLogs.txt](https://github.com/project-chip/connectedhomeip/files/9457388/TC-ACT-3.2-THLogs.txt)
[TC-ACT-3.2-DUTLogs.txt](https://github.com/project-chip/connectedhomeip/files/9457394/TC-ACT-3.2-DUTLogs.txt)

**Comment by bzbarsky-apple** [comment]
chip-all-clusters-app does not support start-action-with-duration, which is why you get UNSUPPORTED_COMMAND.

**Comment by andy31415** [comment]
I do not believe we can support new clusters in time for 1.0.

**Comment by phonnakasturi-apple** [comment]
Updated the app name it must be bridge-app (sorry about the typo earlier)

**Comment by bzbarsky-apple** [comment]
bridge-app does not support start-action-with-duration either, fwiw.

**Comment by cjandhyala** [comment]
closing the issue
