### ISSUE TITLE
ContentAppPlatform support for specifying endpointId when adding content app

### ISSUE THREAD

**Issue by amitnj** [project-chip/connectedhomeip#22285]
#### Problem
Currently ContentAppPlatform code does not allow passing endpointId from outside when adding content apps as endpoints. It also does not persist dynamically discovered endpoints/apps. Which means that for dynamic endpoints to be added and maintained across restarts someone has to persist this info and pass it to the attribute-storage to use when creating the endpoint. Looking at the bridge example this seems to be done from the App code and that makes sense for ContentAppPlatform as well. To do that from the app code we will require the app code to be able to tell the ContentAppPlatform which endpointId to use.

- **This is needed for 1.0** to support the end to end casting flow from mobile apps to the app on the TV device across restarts of the TV device.
- **If this change is NOT made in 1.0**, the commissioned clients(mobile apps) may become out of sync with the corresponding app endpoints on the TV. The endpointId that the mobile app associates with the content app on the device may not match the endpointId that the content app was assigned after the restart of the TV. It will then require the mobile app to commission to the TV again and hence user intervention will be required everytime after a restart.

 #### Proposed Solution
Add additional method in the ContentAppPlatform which allows caller to specify the endpointId when requesting to add a content app as an endpoint via the AddContentApp method.

**Comment by andy31415** [comment]
Marked patches for 1.0 acceptable: requiring a re-comission after each device reboot is a very poor user experience. Accepting as bugfix for app/cluster functionality.
