### ISSUE TITLE
TC-DA-1.4: Darwin tool support needed for [--paa-trust-store-path] optional attribute 

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#22350]
As per TC-DA-1.4 step 7, Darwin tool support is needed for [--paa-trust-store-path] optional attribute to execute the scenario. This optional attribute is present in chip tool but not in the Darwin tool. 

<img width="1624" alt="Screenshot 2022-09-01 at 12 21 20 PM" src="https://user-images.githubusercontent.com/34750871/187995443-9f64a3fa-7201-46f2-91a7-6b648c715594.png">

<img width="929" alt="Screenshot 2022-09-01 at 12 12 16 PM" src="https://user-images.githubusercontent.com/34750871/187993992-2e92169f-9743-498e-9b69-7940447c34f2.png">

**Comment by bzbarsky-apple** [comment]
@krypton36 @vivien-apple

**Comment by krypton36** [comment]
@bzbarsky-apple I can take this one. I am already working with Shyam.
