### ISSUE TITLE
[SVE2][TC-SU-2.2] Retry QueryImage command is never scheduled

### ISSUE THREAD

**Issue by marius-alex-tache** [project-chip/connectedhomeip#22364]
#### Problem
Context: OTA provider sends a `QueryImageResponse` with field `Status` set to `NotAvailable`.

In `DefaultOTARequestorDriver::ScheduleQueryRetry`, if no other OTA Providers are available, a `QueryImage` command should be scheduled for a resend to the original OTA provider that was set through the `announce-ota-provider` command. The command is never sent.

Please see https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/OTASoftwareUpdate.adoc#324-handling-notavailable-value-in-status-field
 * expected behavior
 If no other OTA providers are available, `QueryImage` command is sent to the original OTA provider after a delay equal to the maximum value between minimum interval defined by spec (2 minutes) and the `DelayActionTime` field from `QueryImageResponse` command.
 * actual behavior
 If no other OTA providers are available, `QueryImage` command is never sent.
 * steps to reproduce
 TC-SU-2.2, Step 3

 #### Proposed Solution
Nothing for now. Can someone confirm this issue?

**Comment by tcarmelveilleux** [comment]
Spec says:

> ==== Handling `NotAvailable` value in `Status` field
> 
> The `NotAvailable` status indicates that there is definitely no update currently available from the queried OTA Provider.
> 
> The OTA Requestor MAY choose to attempt a <<QueryImageCommand, QueryImage command>> on a different OTA Provider in its OTA Provider List to determine if an update is available from that other OTA Provider.
> 
> Otherwise, if there are no other OTA Providers available to query, the OTA Requestor SHALL NOT re-query the OTA Provider which was the subject of the command sooner than 2 minutes (120 seconds) from the last <<QueryImageCommand, QueryImage command>>.
> Note that if a Node loses its timekeeping state due to events such as power loss or restart, the above timing constraint MAY be ignored, however, the previously stated overriding constraint of a minimum delay of 120 seconds between queries to any single OTA Provider by a given OTA Requestor have to be respected.
> 

You said:

> expected behavior
> If no other OTA providers are available, QueryImage command is sent to the original OTA provider after a delay equal to the maximum value between minimum interval defined by spec (2 minutes) and the DelayActionTime field from QueryImageResponse command.
> 

The expectation you have is for a  MAY, and not a SHALL. Therefore, there is no bug, but an SDK change could be done. If the test case TC-SU-2.2 expects a new query, then it has an issue that it expects non-mandatory behavior to be mandatory

**Comment by marius-alex-tache** [comment]
In this context, I was looking at 

> Otherwise, if there are no other OTA Providers available to query, the OTA Requestor SHALL NOT re-query the OTA Provider which was the subject of the command sooner than 2 minutes (120 seconds) from the last <<QueryImageCommand, QueryImage command>>.

which specifies a SHALL, not a MAY.

**Comment by marius-alex-tache** [comment]
Actually, do you mean that the "Otherwise" paragraph falls into the scope of the first paragraph?

**Comment by selissia** [comment]
The spec says "OTA Requestor SHALL NOT re-query the OTA Provider .. sooner than 2 minutes".
The implementation does not re-query the OTA Provider at all -- thus the spec requirement is fulfilled
