### ISSUE TITLE
Darwin API: start attestation before network commissioning.

### ISSUE THREAD

**Issue by kpark-apple** [project-chip/connectedhomeip#22383]
#### Problem
Currently, the Darwin API has the following to start commissioning as well as attestation.

```
-[MTRDeviceController commissionDevice:commissioningParams:error:]
```

If user wants to obtain the commissioned device's network scan result before commissioning a network, commissioner would have to complete attestation before it sends scan command to the device being commissioned commissioned and to pass on commissioning parameters afterwards.

Hence, please separate API to start device attestation and to start network commissioning from the above API.

**Comment by woody-apple** [comment]
Closing as a dup of: https://github.com/project-chip/connectedhomeip/issues/24709
