### ISSUE TITLE
Matter.framework should make sure that MTRErrorHolder conforms to NSSecureCoding

### ISSUE THREAD

**Issue by aajain-com** [project-chip/connectedhomeip#22388]
#### Problem
MTRErrorHolder does not conforms to NSSecureCoding which makes it difficult to be sent over XPC. We have seen a few crashes because of this.

 #### Proposed Solution
Make sure that MTRErrorHolder conforms to NSSecureCoding

**Comment by woody-apple** [comment]
Resolve with: https://github.com/project-chip/connectedhomeip/pull/22328
