### ISSUE TITLE
[TC-IDM-7.1] sve-2 branch RPi has subscription issue

### ISSUE THREAD

**Issue by TE-N-ElvenWang** [project-chip/connectedhomeip#22389]
There are some TH prebuilt binary issue and there should be some SDK issue. I did test by using TH chip-tool + TH's chip-all-clusters-app.
1.chip-tool interactive mode. If subscribe one event by fabric 1, and then try to subscribe the second fabric (via --commissioner-name), it will report error for timeout. like below and more like resolve failure:
[1662113690.944854][2774:2779] CHIP:DL: Re-trying resolve
[1662113695.948021][2774:2779] CHIP:DL: Re-trying resolve
[1662113700.944378][2774:2779] CHIP:DIS: Checking node lookup status after 15004 ms
[1662113700.944503][2774:2779] CHIP:DIS: OperationalSessionSetup[6:0000000000000002]: operational discovery failed: ../../src/lib/address_resolve/AddressResolve_DefaultImpl
.cpp:174: CHIP Error 0x00000032: Timeout
2.  the chip-all-clusters-app of TH won't send out the subscription message to chip-tool when use "basic write location in 1 0" and I believe there it is the SDK issue somewhere for SVE-2 branch.

**Comment by Rajashreekalmane** [comment]
@TE-N-ElvenWang pls follow the steps in the VS doc without those shell scripts and see if you are having the same issue that you reported earlier.
PFA logs below:-

[TC-IDM-7.1 [DUT]step2.txt](https://github.com/project-chip/connectedhomeip/files/9663934/TC-IDM-7.1.DUT.step2.txt)
[[TC-IDM-7.1]step2-RD1.txt](https://github.com/project-chip/connectedhomeip/files/9663939/TC-IDM-7.1.step2-RD1.txt)
[[TC-IDM-7.1]Step 2-RD2.txt](https://github.com/project-chip/connectedhomeip/files/9663935/TC-IDM-7.1.Step.2-RD2.txt)
[[TC-IDM-7.1]step2-RD3.txt](https://github.com/project-chip/connectedhomeip/files/9663938/TC-IDM-7.1.step2-RD3.txt)
[[TC-IDM-7.1]step 2-RD4.txt](https://github.com/project-chip/connectedhomeip/files/9663936/TC-IDM-7.1.step.2-RD4.txt)
[[TC-IDM-7.1]step2-RD5.txt](https://github.com/project-chip/connectedhomeip/files/9663937/TC-IDM-7.1.step2-RD5.txt)
