### ISSUE TITLE
Need 'make pretty' replacement

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#2238]
#### Problem
Make pretty doesn't work in GN/Ninja land.

 #### Proposed Solution
We should move over to a local restyle

**Comment by mspang** [comment]
This seems broken today. Marking non-blocking

**Comment by gerickson** [comment]
+1, just tried a PR today. Life seems much harder on this front than previously.

**Comment by mspang** [comment]
Did you see restyle-diff.sh ? Would be worth knowing what's missing from that to close this out.

**Comment by woody-apple** [comment]
@rwalker-apple this is done right? Can you confirm it's a drop in replacement? (I think it is!)

**Comment by rwalker-apple** [comment]
`restyle-diff.sh` aims to replicate what restyled.io does in CI.  it pulls down the restyled.io CLI and runs it on any file with diffs from a supplied refspec (as the first argument, which defaults to `master`)
