### ISSUE TITLE
Is there a way to optimize the size of matter sdk on iOS? 

### ISSUE THREAD

**Issue by zzz2016** [project-chip/connectedhomeip#22391]
The size of matter framework on iOS is too big. 
Is there a way to optimize it ?

**Comment by woody-apple** [comment]
There is an ongoing effort to reduce size, but another option you have is to follow the documentation here, and use the built in one: https://developer.apple.com/documentation/mattersupport/adding-matter-support-to-your-ecosystem

**Comment by huchuankan** [comment]
Matter Commission  demo video ： https://www.bilibili.com/video/BV1Nx421y7sa/
