### ISSUE TITLE
Encrypt Rendezvous messages using keys established via SPAKE2+

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#2239]
#### Problem
Rendezvous messages (post spake2+ key exchange) are not being encrypted.

 #### Proposed Solution
Obtain a `SecureSession` object from `SecurePairingSession` object, after the pairing is complete. Use this `SecureSession` object to encrypt and decrypt Rendezvous messages.

**Comment by vivien-apple** [comment]
Assigning to myself. I have a WIP that depends on #2394 and needs some cleanups.

**Comment by vivien-apple** [comment]
I guess this has been closed by #2658. For some reasons I forgot to close this one.
