### ISSUE TITLE
Building and Running CHIP Linux Examples for i.MX 8M Mini EVK

### ISSUE THREAD

**Issue by MikeYJ6** [project-chip/connectedhomeip#22408]
#### Problem
 I meet a problem in the subtitle "Build the example application:"of 
"Building and Running CHIP Linux Examples for i.MX 8M Mini EVK"
( connectedhomeip/docs/guides/nxp_imx8m_linux_examples.md ).

The problem is i can not find these files : scripts/activate.sh   scripts/examples/imxlinux_example.sh   scripts/build/build_examples.py.

I want to know where is the path of  these files,  thank you for replying .

**Comment by bzbarsky-apple** [comment]
Those are paths relative to the root of the connectedhomeip repo: https://github.com/project-chip/connectedhomeip/blob/master/scripts/activate.sh and https://github.com/project-chip/connectedhomeip/blob/master/scripts/examples/imxlinux_example.sh

**Comment by MikeYJ6** [comment]
Thank you for  give me the path of the files .
Can I ask anthor question?
In the subtitle "Build the example application",
there is a command :
./scripts/examples/imxlinux_example.sh examples/all-clusters-app/linux examples/all-clusters-app/linux/out/aarch64.

I could not find the path "examples/all-clusters-app/linux/out/aarch64" on Github, is something wrong with that?
I want to know the path of "aarch64". If you know, please tell me the path.
thank you for replying.

**Comment by bzbarsky-apple** [comment]
> I could not find the path "examples/all-clusters-app/linux/out/aarch64" on Github

The last argument to that script is the directory to place the build (objdir) in.  It's not part of the source tree, and you can choose whatever directory name you want.

**Comment by MikeYJ6** [comment]
Thank you for give me the answer.
I execute the scripts/activate.sh and the result is as below.

![2022-09-08matter](https://user-images.githubusercontent.com/112938283/189070757-18fa8802-6acb-4fd1-9fd1-0625739a79b7.png)

It looks like there are some errors in the step "setting up Python environment".

What do these errors mean? [it sees like my enviroment must be advised]     How can I resolve thees errors? 
And  in what file output the log 
"Setting up Python environment.....[-]Ignoring pyobjc-core: markers 'sys_platform == "darwin"' don't match your environment"?

Thank you for replying.

**Comment by bzbarsky-apple** [comment]
@MikeYJ6 I have no idea.  Maybe @mspang knows?

**Comment by MikeYJ6** [comment]
Hi everyone, 
Thanks a lot for help! 
As the previous statements, I met some errors when  executing the scripts/activate.sh.
I found  the file "script/requirements.txt" which is about the error log and the content is as the picture below,
![2022-09-12matter1](https://user-images.githubusercontent.com/112938283/189608333-f7b547df-184d-4399-bfec-cf6f2f48710e.png)

Does this help to solve this problem?
How can I resolve the error, is there any idea ?

**Comment by MikeYJ6** [comment]
Hi everyone,
Thanks a lot for help!
As the previous statements, I met some errors when executing the scripts/activate.sh.
I found the file "script/requirements.txt" which is about the error log and the content is as the picture below,

![2022-09-12matter1](https://user-images.githubusercontent.com/112938283/189621404-bda8e803-22f0-4c24-81ea-845b5654c218.png)

Does this help to solve this problem? Is there any idea ?

Thank you for replying.
