### ISSUE TITLE
[1.0] attestation elements and signature are not available during opcert signing

### ISSUE THREAD

**Issue by chrisdecenzo** [project-chip/connectedhomeip#22419]
### Reproduction steps

```bash
1.Configure Android ChipDeviceController for opcert signing callback
2.AttestationElements and Signature object are often corrupted since these are not deep copied into the CommissioningParameters object (so the memory is freed after the AttestationValidation step). 
3.The AttestationElements and Signature objects provided to the opcert signing callback are often corrupted
```

### Bug prevalence

Memory corruption if often

### GitHub hash of the SDK that was being used

master

### Platform

android

### Type

Core SDK Memory Issue

**Comment by andy31415** [comment]
@chrisdecenzo - `1.Configure Android ChipDeviceController for opcert signing callback`  could you share code or commands to do this?

How does a developer reproduce the bug?

**Comment by chrisdecenzo** [comment]
hi @andy31415 - in ChipDeviceController.java, assign a NOCChainIssuer (using setNOCChainIssuer).
