### ISSUE TITLE
Attribute reporting in large networks

### ISSUE THREAD

**Issue by dtodor** [project-chip/connectedhomeip#22422]
What would be the best way of keeping track of attribute changes in a large Matter network? For instance, if we had 50 nodes and one controller, which needs to get notified on attribute changes, would the controller just create 50 subscriptions? Doesn't this strategy incur a "huge" overhead on the controller's side - e.g. for each subscription we have to create a ReadClient to handle the liveliness checks and and possibly do re-subscriptions? In a ZigBee setup we would normally create bindings and receive attribute reports without having to implement any management logic on the controller's side. Matter also supports bindings, but I'm not quite sure whether these can be only used to trigger commands. 

Any thoughts or suggestions are highly appreciated.

**Comment by bzbarsky-apple** [comment]
> would the controller just create 50 subscriptions?

That is the way it's expected to work, yes.

> Matter also supports bindings, but I'm not quite sure whether these can be only used to trigger commands.

What exactly bindings do is not defined in the spec, and in practice it's left to the application what to do with them.  But there is no way to do the equivalent of ZigBee's "configure reporting" (which is needed in addition to bindings) apart from subscriptions.
