### ISSUE TITLE
Multicast binding not working.

### ISSUE THREAD

**Issue by jadhavrohit924** [project-chip/connectedhomeip#22447]
###Problem
* Group multicast fails when we bind group on light app to the switch app
* Steps followed:

1.  Binded light and light-switch app to control light using swich.
    `chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 1, "privilege": 3, "authMode": 2, "subjects": [2], "targets": [{"cluster": 6, "endpoint": 1, "deviceType": null}, {"cluster": 8, "endpoint": 1, "deviceType": null}]}]' 1 0`

    `chip-tool binding write binding '[{"fabricIndex": 1, "node": 1, "endpoint": 1, "cluster": 6}, {"fabricIndex": 1, "node": 1, "endpoint": 1, "cluster": 8}]' 2 1`

2.  Created group on light app and binded to light-switch using groupId.
    `chip-tool tests TestGroupDemoConfig --nodeId 1`

    `chip-tool binding write binding '[{"fabricIndex": 1, "group": 257}]' 2 1`

3.  Entering on/off commands don’t send any multicast to light.
    `Press boot button`
    `matter switch groups onoff toggle`

nodeId of light `1`
nodeId of switch `2`

**Comment by jadhavrohit924** [comment]
@rosahay-silabs we need to send `chip-tool tests TestGroupDemoConfig` command to switch also. Then it will work.

**Comment by somu1710** [comment]
Hi @jadhavrohit924 could u please attach the logs here it will helpful for us.The command you provided `chip-tool tests TestGroupDemoConfig` is not getting success response .It  shows run command failure in my set up.Actually for my set up if I press the button on nordic board ,signal sent to the switch app and not to the light-app  .while read onoff it shows false response.could you eloborate the steps to get success.

**Comment by jadhavrohit924** [comment]
Steps for multicase binding:

* Node Id of switch used during commissioning is 0x7283 (29315 in decimal)
* Node Id of light1 used during commissioning is 0x5164 (20836 in decimal)

**Binding switch and light app**

* ``chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [ 112233, 29315 ], "targets": null}]' 0x5164 0x0``
* ``chip-tool     binding write binding '[{"fabricIndex": 1, "node":20836, "endpoint":1, "cluster":6}]' 0x7283 0x1``

**Add groups to switch and light**

Below command (similar to [this](https://github.com/project-chip/connectedhomeip/issues/20979#issuecomment-1190351414) will add group to switch and light with group id 257

* ``chip-tool tests TestGroupDemoConfig --nodeId 29315``
* ``chip-tool tests TestGroupDemoConfig --nodeId 20836``
* ``chip-tool binding write binding '[{"fabricIndex": 1, "group": 257}]' 0x7283 0x1``


Logs

[chiptool-logs.txt](https://github.com/project-chip/connectedhomeip/files/9534532/chiptool-logs.txt)
[light-logs.txt](https://github.com/project-chip/connectedhomeip/files/9534533/light-logs.txt)
[switch-logs.txt](https://github.com/project-chip/connectedhomeip/files/9534534/switch-logs.txt)
