### ISSUE TITLE
Sort out RNG issue with android toolchain

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#2246]
should we add some TODO with github issue number to describe the RNG issue and add a fix?

_Originally posted by @andy31415 in https://github.com/project-chip/connectedhomeip/pull/2241_

**Comment by vidhis88** [comment]
I believe @mspang / @andy31415 would be the experts in the GN build area.

**Comment by mspang** [comment]
I have no idea what this comment is referring to.
