### ISSUE TITLE
[Platform] Apply darwin API review changes to MTRKeypair

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#22538]
### Reproduction steps

1. Make `publicKey` be a readonly property, not a "method".  This needs to be done a bit carefully to avoid compile issues and leaks.
2. Switch signing functions to one function that takes an enum for what sort of signature to produce (RAW or DER).
3. Add a way to ask the delegate for a bitmask indicating which signature types it supports.

Part of https://github.com/project-chip/connectedhomeip/issues/22420 and looks like it's independent of the other work going on for that issue.

### Platform

darwin

### Type

Manually tested with SDK

**Comment by woody-apple** [comment]
Closing this, given this has shipped, and more complicated to change the API surface at this point.
