### ISSUE TITLE
[Platform] MediaTek Genio support

### ISSUE THREAD

**Issue by pakls** [project-chip/connectedhomeip#22573]
### Reproduction steps

```bash
New Platform: MediaTek Genio

This is a manual bug created for #22404 
```

### Platform

other

### Type

Manually tested with SDK, Platform validated

### (Optional) If manually tested please explain why this is only manually tested

Still at early stage. Tested in-house.

**Comment by andy31415** [comment]
@pakls regarding `Still at early stage. Tested in-house.` - this platform was added in effectively the last week before 1.0 branch time. Hoping this will be stable enough. The late merge is a bit concerning.

**Comment by pakls** [comment]
> @pakls regarding `Still at early stage. Tested in-house.` - this platform was added in effectively the last week before 1.0 branch time. Hoping this will be stable enough. The late merge is a bit concerning.

Thank you, Andy.
