### ISSUE TITLE
move Xcode MacOS builds off "standalone", harmonize Darwin builds

### ISSUE THREAD

**Issue by rwalker-apple** [project-chip/connectedhomeip#2257]
#### Problem
MacOS builds of CHIP Framework use "standalone" configs in some places, "darwin" configs in others

for example: src/platform/Darwin headers and defines are used for both MacOS and iOS, but for CHIPProjectConfig.h, iOS uses config/ios and MacOS uses config/standalone

 #### Proposed Solution
collapse these to the extent possible, eliminate the notion of "iOS" as it differs from "Darwin"

**Comment by woody-apple** [comment]
Resolved
