### ISSUE TITLE
Darwin: DNS service connection reset on interface changes

### ISSUE THREAD

**Issue by dtodor** [project-chip/connectedhomeip#22689]
Shouldn't this read `ResetSharedConnection` instead of `StartSharedConnection`:

https://github.com/project-chip/connectedhomeip/blob/49d7b42d0e732ae63fb0efc8c474f487633da46d/src/platform/Darwin/DnssdHostNameRegistrar.cpp#L275

The callback will be invoked on interface changes and will fail since the connection already exists.

**Comment by vivien-apple** [comment]
As you may have guessed I have written the code for this method but apparently I did a typo while cleaning up my changes. Thanks for catching it!
