### ISSUE TITLE
[Platform] Darwin DFTErrorHolder doesn't actually work

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#22803]
### Reproduction steps

Nothing ever creates a DFTErrorHolder, so the code from https://github.com/project-chip/connectedhomeip/pull/22730 checking for it is all dead code.

The code _before_ https://github.com/project-chip/connectedhomeip/pull/22730 actually sort of made sense: the framework would create NSErrors with an MTRErrorHolder, and then darwin-framework-tool would extract CHIPError out of those.  They had two definitions of MTRErrorHolder, and one got picked randomly, but the definitions were identical, so as long as the same one got picked on both ends it was working (if not pretty).

@vivien-apple @jtung-apple

### Platform

darwin

### Type

Manually tested with SDK

**Comment by vivien-apple** [comment]
Will be fixed by https://github.com/project-chip/connectedhomeip/pull/22811

**Comment by bzbarsky-apple** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/22811
