### ISSUE TITLE
YAML: No support for using a config variable for endpoint

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#22866]
### Reproduction steps

Summary:
we tried to make endpoint as a configurable parameter we are seeing a build error attached diff link for the changes made in YAML file please please let us know if i am doing it in wrong way.

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:endpoint_Config_BuildError

### Bug prevalence

-

### GitHub hash of the SDK that was being used

dc66d4efbd95c55c6564c2432f4929cb5a46ba24

### Platform

other

### Anything else?

Execution logs for reference:
![Endpoint](https://user-images.githubusercontent.com/102359958/192243966-bb8bf876-e05d-4f8d-a4f6-9f7434bae426.png)
[Endpoint_Error.zip](https://github.com/project-chip/connectedhomeip/files/9644976/Endpoint_Error.zip)

**Comment by raju-apple** [comment]
@vivien-apple we still need this support to add 2 endpoints in the same script
