### ISSUE TITLE
[Scenes] Add Chip-tool support for scenes commands

### ISSUE THREAD

**Issue by jepenven-silabs** [project-chip/connectedhomeip#22874]
Preliminary test shows that if we try to run the `add-scene` command, chip-tool issue the `CHIP_ERROR_INVALID_ARGUMENT` error code since the number of arguments seems to be more than the average command

**Comment by lpbeliveau-silabs** [comment]
Once a destination device has been commissioned and paired with the nodeId=25119 and the GroupId=0x4141, the following formatting of the add-scenes command will result in the General error: 0xc3 (UNSUPPORTED_CLUSTER) from that end device:

`./chip-tool scenes add-scene 0x4141 1 1 "Test" '[{"clusterId": 5, "attributeValueList":[{"attributeId": 1, "attributeValue": [1]}]}]' 25119 1`

Chip-tool support for scene commands thus seems functional.
