### ISSUE TITLE
[Feature] Emit OnSessionHang automatically on subscription liveliness timeout

### ISSUE THREAD

**Issue by msandstedt** [project-chip/connectedhomeip#22960]
### Feature description

When we `MarkAsDefunct` for outbound messages, we also dispatch OnSessionHang:

https://github.com/project-chip/connectedhomeip/blob/a6ecd62777cd2d9646f13d809b61c8203b0bd924/src/messaging/ExchangeContext.cpp#L491

https://github.com/project-chip/connectedhomeip/blob/a6ecd62777cd2d9646f13d809b61c8203b0bd924/src/messaging/ReliableMessageMgr.cpp#L150

For consistency, it would be nice if this also happened when marking sessions defunct due to subscription liveliness timeout here:

https://github.com/project-chip/connectedhomeip/blob/a6ecd62777cd2d9646f13d809b61c8203b0bd924/src/app/ReadClient.cpp#L874

A simple approach may be to emit the event from the SecureSession itself whenever the session is marked `kDefunct`, as we do for `MarkForEviction`:

https://github.com/project-chip/connectedhomeip/blob/a6ecd62777cd2d9646f13d809b61c8203b0bd924/src/transport/SecureSession.cpp#L149

### Platform

core

**Comment by bzbarsky-apple** [comment]
That said, there are places where we `MarkAsDefunct` because of something on _our_ end (various "Disconnect"-like APIs), and those should probably not OnSessionHang.

Also not sure we should OnSessionHang in `ReadClient::OnLivenessTimeoutCallback` for the sessions that are not the one we were expecting a message on (but have been idle for at least as long).

**Comment by msandstedt** [comment]
On reflection, I don't think this is feasible.  The problem is that the ReadClient cannot know whether its subscription has timed out because another ReadClient has sent a request with keep-subscriptions=false.  If one has, subscription timeout does not indicate session disappearance.

Only code that has view of all of the ReadClients and which has serialized subscription requests (which also requires waiting for responses before issuing new subscription requests because Matter secure channel comms aren't inherently ordered) can make this inference.  Code that does have this view can itself emit OnSessionHang if it knows all of the above and sees the client OnError with CHIP_ERROR_TIMEOUT.

@bzbarsky-apple 's point is also well taken: a subscription could survive across multiple sessions; there is no way for the read client to know whether the SessionHolder in the client that was used to establish the subscription is still relevant.  So code emitting session hang would also need to tie this together.

Hence, closing.
