### ISSUE TITLE
[BUG] DefaultSessionResumptionStorage::Save does not reuse index locations to save data for the same node

### ISSUE THREAD

**Issue by msandstedt** [project-chip/connectedhomeip#23044]
### Reproduction steps

DefaultSessionResumptionStorage::Save does not reuse index locations to save data for the same node.  This has a few consequences:

1. Each subsequent session resumption write for a given node will unnecessarily evict entries for other nodes.
2. Backing storage in the state table won't ever have more than one entry for the given node.  This leaves it out of sync with the index.
3. Most seriously, entries in the link table are leaked at each occurrence.

The leak is specifically here:

https://github.com/project-chip/connectedhomeip/blob/7301ecfeb99f4473502ecb9cee75d68d83daa286/src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp#L62

Note that the fact Delete always returns CHIP_NO_ERROR keeps eviction working.  But the leak remains and is serious.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

fa8db560907713c555b06120658034e8c6ccea1a

### Platform

core

**Comment by msandstedt** [comment]
Oops, I think we may also be leaking storage here:

https://github.com/project-chip/connectedhomeip/blob/7301ecfeb99f4473502ecb9cee75d68d83daa286/src/protocols/secure_channel/DefaultSessionResumptionStorage.cpp#L62

The link path is `/g/s/<resumptionId>`.  If we delete the state entry first, the link entry is orphaned.  That's pretty serious.

**Comment by bzbarsky-apple** [comment]
We definitely leak `g/s/*` entries, in our testing....

**Comment by msandstedt** [comment]
Yup.  We do.  This will slowly kill nodes.
