### ISSUE TITLE
Need YAML support for subscribing Events

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#23050]
### Feature description

```bash
Summary:
Need YAML support for subscribing Events.
```

### Platform

all

### Anything else?

Testplan screenshot: 
![image](https://user-images.githubusercontent.com/102359958/194297762-dcfacc07-b786-4a42-9b78-5e4762122e7a.png)

**Comment by bzbarsky-apple** [comment]
Does the existing subscribeEvent in YAML not do the right thing here?  @manjunath-grl

**Comment by manjunath-grl** [comment]
@bzbarsky-apple working on that i will update the ticket if that works

**Comment by manjunath-grl** [comment]
Tired the subscribeEvent from event.yaml file working fine closing the issue.
