### ISSUE TITLE
source scripts/activate.sh: FileNotFoundError: [Errno 2] No such file or directory: 'gn'

### ISSUE THREAD

**Issue by venlx** [project-chip/connectedhomeip#23069]
### Reproduction steps

```bash
Following the Guide on https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md
1. git clone --recurse-submodules git@github.com:project-chip/connectedhomeip.git
2. sudo apt-get install git gcc g++ pkg-config libssl-dev libdbus-1-dev \
     libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev \
     python3-pip unzip libgirepository1.0-dev libcairo2-dev libreadline-dev
3. sudo apt-get install pi-bluetooth avahi-utils
4. cd ./connectedhomeip
5. source scripts/activate.sh
```

### Bug prevalence

Whenever i do this

### GitHub hash of the SDK that was being used

561d23d

### Platform

raspi

### Anything else?

![image](https://user-images.githubusercontent.com/115226500/194543834-51311cf2-6304-45b1-a99d-15c54de0f0fb.png)

**Comment by phbasler** [comment]
@bzbarsky-apple I have the same problem on my pi 4. Ninja-build did add nothing to PATH and `gn` is not found.
But I read in the raspi install instruction that you recommend ubuntu server as an OS. My pi has the latest raspberry OS (debian bullseye) installed. Do you know if there are any packages that need to be installed extra?

**Comment by bzbarsky-apple** [comment]
I'm a little surprised bootstrap requires `gn`, since one of its jobs is to install the cipd `gn` (and then activate adds that to the PATH)...  @mspang do you know how this is supposed to work?

**Comment by phbasler** [comment]
@bzbarsky-apple  Are there any updates on this? Or do you have an idea how one could set up a workaround for this?

**Comment by RedPoppies** [comment]
@bzbarsky-apple 
![image](https://user-images.githubusercontent.com/51362835/195973536-c9562642-efd7-4da2-a2f0-4526812c01c4.png)
I've been stuck here for a long time.
How to solve this problem.

**Comment by bzbarsky-apple** [comment]
I have no idea.  If I knew, I would have said up above.  You need to get the attention of someone who knows how bootstrap/activate are supposed to work...  @andy31415

**Comment by phbasler** [comment]
@bzbarsky-apple  @andy31415 @mspang 
I got a tip on discord and tested it with a 64bit raspberry os lite. There it works without a problem. On my previous test I still had a 32 bit Raspberry OS.

**Comment by tunm1228** [comment]
I am also facing the same error. Please help me? 
<img width="1053" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/42457760/600970b0-f653-4a93-a1ca-b05ab68cf527">
