### ISSUE TITLE
Need YAML support for test TC-ACL-2.10 

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#23146]
### Feature description

```bash
Need YAML support/syntax for testcase TC-ACL-2.10
Step 14: If DUT is an app on host, examine persistent storage in /tmp/chip_kvs text file
```

### Platform

all

### Anything else?

![image](https://user-images.githubusercontent.com/102359958/195316800-83982ca4-c1e8-401f-8e96-6a77f8c7d797.png)

**Comment by bzbarsky-apple** [comment]
This is not a reasonable test step; storage details are subject to change and are not something test plans can mandate.  @manjunath-grl
