### ISSUE TITLE
[BUG] [iOS] Is developer mode necessary in iOS 16 to connect to a matter device ?

### ISSUE THREAD

**Issue by zzz2016** [project-chip/connectedhomeip#23192]
### Reproduction steps

```bash
1. turn off the developer mode in iOS 16
2. pair and commission the device
3. the error occurred: 
BLE: Error writing Characteristics in Chip service on the device: [The specified UUID is not allowed for this operation.]

If I turn on the developer mode, no error occurrs.
```

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

26a054c31144478e3c27391c06b0dc3230bb0882

### Platform

darwin

### Platform Version(s)

iOS 16 +

### Anything else?

![5af3f6cc-2e95-4145-8d8f-f9268d93ee31](https://user-images.githubusercontent.com/19794679/195805636-147aa2bc-64b2-4836-827f-680bbcc15ae4.jpeg)

**Comment by bzbarsky-apple** [comment]
@woody-apple could you take a look please?

**Comment by caipiblack** [comment]
We also have the problem IOS 16.1 on the branch master.

Someone have a workaround ?

**Comment by zzz2016** [comment]
Update.
According to a iOS FAE stuff，In iOS 16，we must use the MatterSupport Framework to pair the device.

**Comment by LucaFagan** [comment]
Does this mean we can't use this framework in production ?

**Comment by plan44** [comment]
My understanding is: no, you can't.

Matter is a device-level framework, you shouldn't (except in testing and development setups) have more than one matter stack running per device, the same way as you can't bring a second TCP/IP stack along with your app.

The matter stack (the code from connectedhomeip) in iOS is built-in, and can be used via the MatterSupport iOS Framework. All apps on the device, including Home.app, share that same common matter stack.

chip tool on the other hand, is a developer tool for testing all sorts of interactions with matter devices, brings along its own matter stack and thus is not suitable in any way for end user apps.

**Comment by huchuankan** [comment]
Matter Commission  demo video ： https://www.bilibili.com/video/BV1Nx421y7sa/

**Comment by huchuankan** [comment]
> Update. According to a iOS FAE stuff，In iOS 16，we must use the MatterSupport Framework to pair the device.

indeed ！！
