### ISSUE TITLE
[Platform] Can we download trial Matter controller APP for IOS or google home or amazon APP to test with our Matter products? 

### ISSUE THREAD

**Issue by wxiangcheng** [project-chip/connectedhomeip#23213]
### Reproduction steps

```bash
Hi, we prepared some matter end device like matter bulb over WiFi and Thread. we want to demo it our customer. Currently we had to use chiptool under Ubuntu 20 or a verrrrry simple APK built from matter folder which has lots of bugs.
I'm thinking of using a more convinced tool like apple's homekit or google tool that talks with our matter products. Can I download some trial version of it? 
Any comments are welcome.
```

### Platform

efr32, esp32

### Type

Platform validated

**Comment by oidebrett** [comment]
You could try watching the video from silicon labs "works with" matter development training  called "MAT-302: Matter Development with Google". It explains how to get a matter device working with Google Home. I was able to get Google home working with a matter light cluster endpoint by following that tutorial.
