### ISSUE TITLE
[Telink] use src/app/chip_data_model.cmake for data model inclusions

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#23225]
### Reproduction steps

Telink CMakeFiles directly include `/src/app/util/*` and  zzz_generated paths for includes.

This makes any common refactors tedious. Mbed and NRF already use a common src/app/chip_data_model.cmake

### Platform

Telink

**Comment by s07641069** [comment]
@andy31415 Please check if I did everything what you mean. If something missed just inform me.

**Comment by Damian-Nordic** [comment]
This is already fixed.
