### ISSUE TITLE
Wrong colours in Light app

### ISSUE THREAD

**Issue by AchimPieters** [project-chip/connectedhomeip#23291]
### Reproduction steps

When the light app is created, the button works fine, but the colours on the LED do not match the colour selected in the home app.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

-

### Platform

esp32

### Type

Test Improvement

### Anything else?

![Example](https://user-images.githubusercontent.com/16034588/197202642-b9f6372b-1908-4056-be66-cea0a6839422.png)

**Comment by dhrishi** [comment]
@AchimPieters How do you control the light from? Which Home app is this?

Can you please use the chip-tool and try the commands for setting specific colors? Or, may be, you can mention the colors that you are seeing incorrectly and we will try them using the chip-tool and provide the commands. Just want to understand where is the actual problem.

**Comment by AchimPieters** [comment]
@dhrishi It's solved here: https://github.com/Kristian8606/esp-matter/tree/main/examples/ws2812_led_strip

**Comment by dhrishi** [comment]
Thanks. We will take a look. cc @jadhavrohit924

**Comment by jadhavrohit924** [comment]
Hi @AchimPieters, It will be helpful if you can specify which colors do not match the colour selected in the home app.
