### ISSUE TITLE
[Documentation] Network pre-requisite

### ISSUE THREAD

**Issue by chomper1** [project-chip/connectedhomeip#23308]
### Documentation issues

1. I've followed the steps for creating a lighting example for the ESP32C3 for both Apple and Google ecosystems. I've also built and ran the equivalent Linux samples.
2. I'm able to find, commission, and pair the devices to their respective ecosystems, but I'm unable to control the devices following the pairing. The devices show up in their respective Home Apps but Apple and Google Home both report issues trying to control the device after pairing.
3. There isn't an issue with control when running chip-tool through a RaspberryPi or Linux environment.
4. Is there a networking pre-requisite that might be affecting me on a global scale? Something I need to address on my router perhaps? Resetting the hubs and devices have no effect.
...

### Platform

esp32, other

**Comment by bzbarsky-apple** [comment]
@chomper1 So you can control the device with Linux chip-tool but not with Apple Home or Google Home?  Do the latter fail to control it completely, or just intermittently?  Does Linux chip-tool in interactive mode work?

Logs might be helpful here.  In particular, logs from the device and if possible from the controllers (e.g. a sysdiagnose for the Apple case).
