### ISSUE TITLE
Log messages from level-control.cpp print a hexadecimal pointer value where the intention is to print a text string

### ISSUE THREAD

**Issue by stevegrau-ayla** [project-chip/connectedhomeip#23343]
https://github.com/project-chip/connectedhomeip/blob/0c2f7c6c09e8542c18da5e4e64cc48545571a384/src/app/clusters/level-control/level-control.cpp#L343

There are 15 instances of "%p" in this file that should be "%s". In most instances there is also a missing space so "%p" should be "%s "

**Comment by bzbarsky-apple** [comment]
Looks like this was fixed in #24949

**Comment by stevegrau-ayla** [comment]
Yes, that should fix it.
