### ISSUE TITLE
[Feature] Use subscription id to restore a lost subscription

### ISSUE THREAD

**Issue by nykh2010** [project-chip/connectedhomeip#23356]
### Feature description

```bash
when use wildcard path to subscribe, the end device would report attributes/events which be subscribed. if enable the auto-resubscribe, and in a week net environment，the subscription maybe 
 easier to lost sync and then trigger the end device report data. this would aggravate network congestion.
so it canbe use subscription id to restore the last subscription without report data?
```

### Platform

all

**Comment by bzbarsky-apple** [comment]
@nykh2010 If you restore the subscription but don't get reports, how do you know what the values are?

And if you're using a ClusterStateCache to store the values, then auto-resubscribe will already send along the data-versions to avoid re-sending of data that's already available....
