### ISSUE TITLE
[BUG] CHIPTool App doesn't work in iOS 16.1

### ISSUE THREAD

**Issue by zzz2016** [project-chip/connectedhomeip#23353]
### Reproduction steps

```bash
1. Scan the QR code
2. Enter the Wifi info
3. Pair the device
```

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

26a054c31144478e3c27391c06b0dc3230bb0882

### Platform

darwin

### Platform Version(s)

16.1

### Anything else?

![O7XfkHw0hB](https://user-images.githubusercontent.com/19794679/197921062-f3976957-8332-4704-9a6d-96c288a23c6d.jpg)

**Comment by bzbarsky-apple** [comment]
@zzz2016 I believe you need to install https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig on iOS and turn on developer mode to use the test iOS CHIPTool.

**Comment by TheWalkingDead1024** [comment]
> @zzz2016 I believe you need to install https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig on iOS and turn on developer mode to use the test iOS CHIPTool.

@bzbarsky-apple  Many thanks for your replay. We also met this issue when we use matter framework in iOS SDK. Could you please tell us when it will be released in iOS.  It will be very helpful if you share us the milestone. Thanks again.

**Comment by bzbarsky-apple** [comment]
@TheWalkingDead1024 If you are trying to use the system-provided Matter framework to commission devices, you should look into the MatterSupport framework.   See https://developer.apple.com/apple-home/matter/

**Comment by TheWalkingDead1024** [comment]
> https://developer.apple.com/apple-home/matter/

@bzbarsky-apple Thanks again. Let's go back to the chip Matter framework(non system-provided). Would you please share us more information about when this issue will be resolved or, let me put it straight, when CHIPTool(chip framework) will work in iOS 16 without installing the profile and turn on developer mode.

**Comment by huchuankan** [comment]
Matter Commission  demo video ： https://www.bilibili.com/video/BV1Nx421y7sa/
