### ISSUE TITLE
[BUG] Console not responding to input ESP32 example

### ISSUE THREAD

**Issue by ar0311** [project-chip/connectedhomeip#23365]
### Reproduction steps

```bash
1. Build lighting-app ESP32 example
2. idf.py monitor
3. Device output displays fine but not responding to any input
...
```

### Bug prevalence

Everytime i build

### GitHub hash of the SDK that was being used

bd2c96a1944f3eb8e0e2497e9d2fa4747848d501

### Platform

esp32

**Comment by ar0311** [comment]
Fixed, the shell enable option was not set in the default config.

Is this something that should be turned on by default?

**Comment by bzbarsky-apple** [comment]
@dhrishi @shubhamdp

**Comment by dhrishi** [comment]
@ar0311 I think it should be okay to enable the console by default. We will check and update
