### ISSUE TITLE
[Darwin] Missing support for isUrgent flag in MTR framework when subscribing to events

### ISSUE THREAD

**Issue by bauerschwan** [project-chip/connectedhomeip#23370]
### Reproduction steps

In interface MTRSubscribeParams there is no support for isUrgent feature. Without this events will be delivered according to minInterval and maxInterval which is sub-optimal for many important events.

### Platform

darwin

### Platform Version(s)

N/A

### Type

Platform validated

**Comment by bzbarsky-apple** [comment]
This basically affects `MTRBaseDevice`'s `SubscribeWithQueue`.

**Comment by bzbarsky-apple** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/pull/24057.
