### ISSUE TITLE
[1.0] Why does not support multiple commands?

### ISSUE THREAD

**Issue by nykh2010** [project-chip/connectedhomeip#23381]
### Reproduction steps

```bash
in spec chapter 10.6.9, the InvokeRequestMessage's InvokeRequests Element is an array type, but CommandSender not support multiple commands? what's the reason?
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

tag v1.0.0

### Platform

vscode

### Type

Spec Compliance Issue

**Comment by bzbarsky-apple** [comment]
@nykh2010 There were open issues about how it should work, and limited time before 1.0 for answering those questions and implementation.

See also spec section "2.12.1. Invoke Multiple Paths":

> Support for an Invoke Interaction with multiple paths or wildcard paths is provisional.

**Comment by vivien-apple** [comment]
Just to make it clear, the `chip-tool` syntax for such a command would be:
```
$ ./out/debug/standalone/chip-tool onoff toggle 0x12344321 1,2
```

It does not work as of today because the stack does not supports sending commands to multiple endpoints.
Once it works in on the stack side I could implement `chip-tool` supports for it.

**Comment by yunhanw-google** [comment]
batch command has been supported since 1.3, close this one, thanks
