### ISSUE TITLE
[CS] Feature needs to be implemented in Group Key Management 

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#23456]
### Feature description

CacheAndSync[CS](The ability to support CacheAndSync security policy and MCSP) feature has to be implemented in Group Key Management.

### Platform

All Platform

### Test plan impact :  

TC-GRPKEY-5.4 - https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/group_communication.adoc#tc-grpkey-5-4-verification-for-keysetreadresponse-command-for-cacheandsync

### Reference :
Spec : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Group-Key-Management-Cluster.adoc

**Comment by cecille** [comment]
This will need a new test plan as 5.1 doesn't test reboot behaviour
