### ISSUE TITLE
[MS, MSR, MSL, MSM] Feature needs to be implemented in Switch

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#23460]
### Feature description

```bash
...
The following feature has to be implemented in the Switch
1. MS	- Momentary Switch
2. MSR	- Momentary Switch Release
3. MSL	- Momentary Switch LongPress
4. MSM	- Momentary Switch MultiPress
```

### Platform

All Platform

### Test plan impact:
TC-SWTCH-1.1, TC-SWTCH-2.1, TC-SWTCH-2.2 and TC-SWTCH-3.2
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/switch.adoc

### Reference :
Spec : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Switch.adoc

**Comment by bzbarsky-apple** [comment]
Those features should generally work, I would think: you just set them in the feature map, and then emit the events as needed.  That all happens in the application.

What's the SDK-side work that this is actually asking for, @Survensa ?
