### ISSUE TITLE
[FGP, FACE] Feature needs to be implemented in Doorlock

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#23462]
### Feature description

```bash
...
The following feature has to be implemented in the Door lock
1. FGP	- Finger Credentials (Lock supports finger-related credentials (fingerprint, finger vein))
2. FACE	- Face Credentials (Lock supports face-related credentials (face, iris, retina))
```

### Platform

All Platform

### Reference : 
Spec : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/DoorLock.adoc

**Comment by bzbarsky-apple** [comment]
@Survensa What exact implementation are you looking for on the SDK side here?  The SDK will call into the app for these; it's up to the app to do the face/finger bits itself....
