### ISSUE TITLE
Build overall getting started documentation

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#235]
#### Problem
Many folks (including myself) have questions about where to start. Let's build some good documentation here.

 #### Proposed Solution
Help people get started with docs

**Comment by andy31415** [comment]
@woody-apple do we still need to add more 'getting started' documentation or is what we have sufficient? I believe we have some 'how to compile chip' and 'how to build android' and such.

We may likely never be really done with docs, however maybe we have enough for the getting started bit.

**Comment by woody-apple** [comment]
SW BRB: Looks done to us for now :)
