### ISSUE TITLE
[TC-SU-3.3] Need yaml syntax support for Following Step

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#23506]
### Feature description

```bash
...
need an yaml syntax support for following steps:
 1: OTA-R/TH sends a QueryImage Command to the DUT. Protocol supported should only list "BDX". DUT responds with the QueryImageResponse to the OTA-R/TH.
```

### Platform

all

### Anything else?

![2022-11-04_21-15](https://user-images.githubusercontent.com/57476670/200017789-e752b6d2-d59d-4910-ba28-e31589be8982.png)

**Comment by kowsisoundhar12** [comment]
https://github.com/project-chip/connectedhomeip/issues/23249

**Comment by bzbarsky-apple** [comment]
I would think this already worsk. In particular, if you send a QueryImage in YAML and the response is not QueryImageResponse, the test will fail right now.

@kowsisoundhar12 what exactly is missing here?

**Comment by kowsisoundhar12** [comment]
QueryImage command will work in yaml ,hence closing this issue
