### ISSUE TITLE
[TC-SU-2.5] Need yaml syntax support for following steps

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#23501]
### Feature description

```bash
...
[TC-SU-2.5] Need yaml syntax support for verifying the following Expected Outcome steps

1.Verify that the DUT starts updating its software.
2.Verify that the DUT clears its previously downloaded software image, and resets the UpdateState Attribute to Idle.
```

### Platform

all

### Anything else?

![SU-2 5](https://user-images.githubusercontent.com/57476670/199996338-634d2136-f1f3-4608-aaa5-d60f153eda35.png)
![SU-2 5-1](https://user-images.githubusercontent.com/57476670/199996467-e2ed2870-bdf9-4395-8513-632442f221f9.png)

**Comment by kowsisoundhar12** [comment]
https://github.com/project-chip/connectedhomeip/issues/23249

**Comment by bzbarsky-apple** [comment]
How can YAML possibly verify "that the DUT starts updating its software" for an actual device?  @kowsisoundhar12

**Comment by kowsisoundhar12** [comment]
@bzbarsky-apple sorry ,let me close this issue ,since we can't verify above steps in yaml
