### ISSUE TITLE
Why can't you subscribe to more than one property

### ISSUE THREAD

**Issue by moon20704** [project-chip/connectedhomeip#23541]
### Reproduction steps

```bash
when we subcribe to more than one property, the second will replace the first,the log is in "Anythings else" item.
```

### Bug prevalence

it appear  inevitably

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip        master branch

### Platform

android

### Anything else?

the error log is that:

D  Found matching exchange: 11177i, Delegate: 0x779dafe710
D  Rxd Ack; Removing MessageCounter:88395640 from Retrans Table on exchange 11177i
D  SubscribeResponse is received
D  SubscribeResponseMessage =
D  {
D  	SubscriptionId = 0x9a5eaf4f,
D  	MaxInterval = 0x3c,
D  	InteractionModelRevision = 1
D  }
D  Subscription established with SubscriptionID = 0x9a5eaf4f MinInterval = 10s MaxInterval = 60s Peer = 01:0000000000000006
D  MoveToState ReadClient[0x779dafe700]: Moving to [Subscripti]
D  Refresh LivenessCheckTime for 61500 milliseconds with SubscriptionId = 0x9a5eaf4f Peer = 01:0000000000000006
D  <<< [E:11177i M:88395641 (Ack:69692302)] (S) Msg TX to 1:0000000000000006 [D1F6] --- Type 0000:10 (SecureChannel:StandaloneAck)
D  (S) Sending msg 88395641 on secure session with LSID: 40128
D  Flushed pending ack for MessageCounter:69692302 on exchange 11177i
I  AnalyticsMessageHandler msg wath = 3
I  delayFlush timeDelayMills = 15000
I  sendData
I  rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893525580}]
I  sendHttpRequest path = https://uat.collector.ap-south-1.bd.tcljd.com/v2/secured?project=Yv1_nhtgSxuOFmf-wyXXJw&country=in
I  sendHttpRequest rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893525580}]
I  query = crc=668098241&gzip=1&data_list=H4sIAAAAAAAAAH1Ty27bMBD8F7rHWCApiaR8C9oGcYA%2BgByaoigEPlY2G0k0KMpuEOTfu5QTJLn0QonD0ewOd%2FTrkbQpanvfekc2StWSlSW9IMkPQDZMCKmkog2uEsGHA4Jk4ZML0ntDNo%2Fkw%2FIkl6OLAUUuFqA9Qpx8GPGAF7SQL%2FAAaR%2BwErHBwQvoIGnfL%2BBQTDBOIU5OJ13oUfcPydsJ3xb1YnL3xaWZcgvp9sz8hMzL79vVaunr8xHGtB0TRPx2tRrnHlfeMPJ0QSCfYRl9OLTQg%2B394uMQwwFi8jAtdiYbAcY2RI9snc4mDiGivE%2B55TC9ccdohgZ0kw184ZSWN6y%2B%2FXgmvr%2BXZ%2BWTd2mPl0sVfQX34Hd7bI6XVUYHPc4depwjRBS58zoMPmvk3l%2BrV4UsOMLa2jCPaRkiKRtZSUNd53htWC3KhsmaGWdrUSvnwFTSKu0kGA1GQldyLZHbsK60VDmLej4knMrRW1gUbdOxGpRSqANMUNsJScGAsEZWRktrjKOCa%2BMAeGmkqgytJONaM621ELnxk%2B882aQ4A25GSKcQ79vnRP3YXm0zx8y%2Bd6%2F2eIMYTucP2GdrP4%2BsHfdpd%2Ft3%2FnY1dOvTw93dzWm5lzmFM4eJEq%2B2qhRvFGeVoNqqem25g3WF%2Fa0bK5p151yp0TYvhf1%2FZN%2BPMMLO5%2FTlWLRLhjdk%2BzWHSO%2FgXP%2Ba4RbjNcDLQK7ZWuT8tV0%2FT%2Fv2zb%2FVlDWva0Wffv8DaeEX%2F4kDAAA%3D
I  [okhttp]:check permission begin!
W  ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I  [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I  errorMessage = Connection error: java.net.UnknownHostException: Unable to resolve host "uat.collector.ap-south-1.bd.tcljd.com": No address associated with hostname
E  Subscription Liveness timeout with SubscriptionID = 0xd85396dd, Peer = 01:0000000000000006
D  SecureSession[0x77804cda80]: MarkAsDefunct Type:2 LSID:40093
D  SecureSession[0x77804cdb68]: MarkAsDefunct Type:2 LSID:40094
D  SecureSession[0x77804cdc50]: MarkAsDefunct Type:2 LSID:40095
D  SecureSession[0x77804cdd38]: MarkAsDefunct Type:2 LSID:40096
D  SecureSession[0x77804cde20]: MarkAsDefunct Type:2 LSID:40097
D  SecureSession[0x77804cdf08]: MarkAsDefunct Type:2 LSID:40098
D  SecureSession[0x77804cdff0]: MarkAsDefunct Type:2 LSID:40099
D  SecureSession[0x77804ce0d8]: MarkAsDefunct Type:2 LSID:40100
D  SecureSession[0x77804ce1c0]: MarkAsDefunct Type:2 LSID:40101
D  SecureSession[0x77804ce2a8]: MarkAsDefunct Type:2 LSID:40102
D  SecureSession[0x77804ce390]: MarkAsDefunct Type:2 LSID:40103
D  SecureSession[0x77804ce478]: MarkAsDefunct Type:2 LSID:40104
D  SecureSession[0x77804ce560]: MarkAsDefunct Type:2 LSID:40105
D  SecureSession[0x77804ce648]: MarkAsDefunct Type:2 LSID:40106
D  SecureSession[0x77804ce730]: MarkAsDefunct Type:2 LSID:40107
D  SecureSession[0x77804ce818]: MarkAsDefunct Type:2 LSID:40108
D  SecureSession[0x77804ce900]: MarkAsDefunct Type:2 LSID:40109
D  SecureSession[0x77804ce9e8]: MarkAsDefunct Type:2 LSID:40110
D  SecureSession[0x77804cead0]: MarkAsDefunct Type:2 LSID:40111
D  SecureSession[0x77804cebb8]: MarkAsDefunct Type:2 LSID:40112
D  SecureSession[0x77804ceca0]: MarkAsDefunct Type:2 LSID:40113
D  SecureSession[0x77804ced88]: MarkAsDefunct Type:2 LSID:40114
D  SecureSession[0x77804cee70]: MarkAsDefunct Type:2 LSID:40115
D  SecureSession[0x77804cef58]: MarkAsDefunct Type:2 LSID:40116
D  SecureSession[0x77804cf040]: MarkAsDefunct Type:2 LSID:40117
D  SecureSession[0x77804cf128]: MarkAsDefunct Type:2 LSID:40118
D  SecureSession[0x77804cf210]: MarkAsDefunct Type:2 LSID:40119
D  SecureSession[0x77804cf2f8]: MarkAsDefunct Type:2 LSID:40120
D  SecureSession[0x77804cf3e0]: MarkAsDefunct Type:2 LSID:40121
D  SecureSession[0x77804cf4c8]: MarkAsDefunct Type:2 LSID:40122
D  SecureSession[0x77804cf5b0]: MarkAsDefunct Type:2 LSID:40123
D  SecureSession[0x77804cf698]: MarkAsDefunct Type:2 LSID:40124
D  SecureSession[0x77804cf780]: MarkAsDefunct Type:2 LSID:40125
D  SecureSession[0x77804cf868]: MarkAsDefunct Type:2 LSID:40126
D  SecureSession[0x77804cf950]: MarkAsDefunct Type:2 LSID:40127
D  SecureSession[0x77804cfa38]: MarkAsDefunct Type:2 LSID:40128
D  SecureSession[0x77804cfa38]: Moving from state 'kActive' --> 'kDefunct'
D  MoveToState ReadClient[0x779dfd1f00]: Moving to [      Idle]
D  Will try to resubscribe to 01:0000000000000006 at retry index 0 after 0ms due to error 32
D  OnResubscribeTimerCallback: DoCASE = 1
D  SecureSession[0x77804cfa38]: MarkAsDefunct Type:2 LSID:40128
D  FindOrEstablishSession: PeerId = [1:0000000000000006]
D  FindOrEstablishSession: No existing OperationalSessionSetup instance found
D  OperationalSessionSetup[1:0000000000000006]: State change 1 --> 2
D  Resolving 6792A892ADD0D1F6:0000000000000006 ...
D  resolve: Starting service resolution for '6792A892ADD0D1F6-0000000000000006' type '_matter._tcp'
I  Resolved service '6792A892ADD0D1F6-0000000000000006' to /192.168.31.5
D   ----- entry [0] : T 1
D   ----- entry [1] : SAI 300
D   ----- entry [2] : SII 5000
D  Node ID resolved for 6792A892ADD0D1F6:0000000000000006
D  	Hostname: 192.168.31.5
D  	IP Address #1: 192.168.31.5
D  	Port: 5540
D  	Mrp Interval idle: 5000 ms
D  	Mrp Interval active: 300 ms
D  	TCP Supported: 1
D  Lookup clearing interface for non LL address
D  UDP:192.168.31.5:5540: new best score: 2
D  Checking node lookup status after 20 ms
D  Keeping DNSSD lookup active
D  Checking node lookup status after 201 ms
D  OperationalSessionSetup[1:0000000000000006]: Updating device address to UDP:192.168.31.5:5540 while in state 2
D  OperationalSessionSetup[1:0000000000000006]: State change 2 --> 3
D  SecureSession[0x77804cfb20]: Allocated Type:2 LSID:40129
D  Initiating session on local FabricIndex 1 from 0x000000000001B669 -> 0x0000000000000006
D  KVS: Getting key f/1/g
D  KVS: Getting key f/1/k/0
D  KVS: Getting key f/1/s/0000000000000006
D  <<< [E:11178i M:61251636] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:30 (SecureChannel:CASE_Sigma1)
D  (U) Sending msg 61251636 to IP address 'UDP:192.168.31.5:5540'
D  Sent Sigma1 msg
D  OperationalSessionSetup[1:0000000000000006]: State change 3 --> 4
D  >>> [E:11178i M:37658015 (Ack:61251636)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
D  Found matching exchange: 11178i, Delegate: 0x77801e6088
D  Rxd Ack; Removing MessageCounter:61251636 from Retrans Table on exchange 11178i
D  >>> [E:11178i M:37658016 (Ack:61251636)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:33 (SecureChannel:CASE_Sigma2Resume)
D  Found matching exchange: 11178i, Delegate: 0x77801e6088
D  CHIP MessageCounter:61251636 not in RetransTable on exchange 11178i
D  <<< [E:11178i M:61251637 (Ack:37658016)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
D  (U) Sending msg 61251637 to IP address 'UDP:192.168.31.5%wlan0:5540'
D  Flushed pending ack for MessageCounter:37658016 on exchange 11178i
D  Received Sigma2Resume msg
D  Found MRP parameters in the message
D  Peer assigned session session ID 2692
D  KVS: Getting key g/sri
D  KVS: Getting key f/1/s/0000000000000006
D  KVS: Deleting key g/s/byYSjniEQZhGi+Xy/B433A==
D  KVS: Setting key f/1/s/0000000000000006
D  KVS: Setting key g/s/pvuq956yUpQjrecqqAVwOQ==
D  Sending status report. Protocol code 0, exchange 11178
D  <<< [E:11178i M:61251638 (Ack:37658016)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:40 (SecureChannel:StatusReport)
D  (U) Sending msg 61251638 to IP address 'UDP:192.168.31.5%wlan0:5540'
D  SecureSession[0x77804cfb20]: Moving from state 'kEstablishing' --> 'kActive'
D  SecureSession[0x77804cfb20]: Activated - Type:2 LSID:40129
D  New secure session activated for device <0000000000000006, 1>, LSID:40129 PSID:2692!
D  OperationalSessionSetup[1:0000000000000006]: State change 4 --> 5
D  HandleDeviceConnected
D  <<< [E:11179i M:236386726] (S) Msg TX to 1:0000000000000006 [D1F6] --- Type 0001:03 (IM:SubscribeRequest)
D  (S) Sending msg 236386726 on secure session with LSID: 40129
D  MoveToState ReadClient[0x779dfd1f00]: Moving to [AwaitingIn]
D  Received a duplicate message with MessageCounter:37658016 on exchange 11178i
D  >>> [E:11178i M:37658016 (Ack:61251636)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:33 (SecureChannel:CASE_Sigma2Resume)
D  Found matching exchange: 11178i, Delegate: 0x0
D  Forcing tx of solitary ack for duplicate MessageCounter:37658016 on exchange 11178i
D  <<< [E:11178i M:61251639 (Ack:37658016)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
D  (U) Sending msg 61251639 to IP address 'UDP:192.168.31.5%wlan0:5540'
D  >>> [E:11178i M:37658017 (Ack:61251638)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
D  Found matching exchange: 11178i, Delegate: 0x0
D  Rxd Ack; Removing MessageCounter:61251638 from Retrans Table on exchange 11178i
D  >>> [E:11179i M:107641253 (Ack:236386726)] (S) Msg RX from 1:0000000000000006 [D1F6] --- Type 0001:05 (IM:ReportData)
D  Found matching exchange: 11179i, Delegate: 0x779dfd1f10
D  Rxd Ack; Removing MessageCounter:236386726 from Retrans Table on exchange 11179i
D  ReportDataMessage =
D  {
D  	SubscriptionId = 0xd0f07f35,
D  	AttributeReportIBs =
D  	[
D  		AttributeReportIB =
D  		{
D  			AttributeDataIB =
D  			{
D  				DataVersion = 0x34065dab,
D  				AttributePathIB =
D  				{
D  					Endpoint = 0x1,
D  					Cluster = 0x202,
D  					Attribute = 0x0000_0000,
D  				}
D  					
D  				Data = 2, 
D  			},
D  			
D  		},
D  		
D  	],
D  	
D  	InteractionModelRevision = 1
D  }
E  readFanModeAttribute onSuccess 2
D  MoveToState ReadClient[0x779dfd1f00]: Moving to [AwaitingSu]
D  <<< [E:11179i M:236386727 (Ack:107641253)] (S) Msg TX to 1:0000000000000006 [D1F6] --- Type 0001:01 (IM:StatusResponse)
D  (S) Sending msg 236386727 on secure session with LSID: 40129
I  'emitMatter相关事件', { matter_ac_attr: '{"method":"writeFanModeAttribute","value":"2"}' }
I  '收到matter空调的状态信息', { method: 'writeFanModeAttribute', value: '2' }
D  >>> [E:11179i M:107641254 (Ack:236386727)] (S) Msg RX from 1:0000000000000006 [D1F6] --- Type 0001:04 (IM:SubscribeResponse)
D  Found matching exchange: 11179i, Delegate: 0x779dfd1f10
D  Rxd Ack; Removing MessageCounter:236386727 from Retrans Table on exchange 11179i
D  SubscribeResponse is received
D  SubscribeResponseMessage =
D  {
D  	SubscriptionId = 0xd0f07f35,
D  	MaxInterval = 0x3c,
D  	InteractionModelRevision = 1
D  }
D  Subscription established with SubscriptionID = 0xd0f07f35 MinInterval = 10s MaxInterval = 60s Peer = 01:0000000000000006
D  MoveToState ReadClient[0x779dfd1f00]: Moving to [Subscripti]
D  Refresh LivenessCheckTime for 61500 milliseconds with SubscriptionId = 0xd0f07f35 Peer = 01:0000000000000006
D  <<< [E:11179i M:236386728 (Ack:107641254)] (S) Msg TX to 1:0000000000000006 [D1F6] --- Type 0000:10 (SecureChannel:StandaloneAck)
D  (S) Sending msg 236386728 on secure session with LSID: 40129
D  Flushed pending ack for MessageCounter:107641254 on exchange 11179i
I  AnalyticsMessageHandler msg wath = 3
I  delayFlush timeDelayMills = 15000
I  sendData
I  rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893540657}]
I  sendHttpRequest path = https://uat.collector.ap-south-1.bd.tcljd.com/v2/secured?project=Yv1_nhtgSxuOFmf-wyXXJw&country=in
I  sendHttpRequest rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893540657}]
I  query = crc=1208967404&gzip=1&data_list=H4sIAAAAAAAAAH1Ty27bMBD8F7rHWCApiaR8C9oGcYA%2BgByaoigEPlY2G0k0KMpuEOTfu5QTJLn0QonD0ewOd%2FTrkbQpanvfekc2StWSlSW9IMkPQDZMCKmkog2uEsGHA4Jk4ZML0ntDNo%2Fkw%2FIkl6OLAUUuFqA9Qpx8GPGAF7SQL%2FAAaR%2BwErHBwQvoIGnfL%2BBQTDBOIU5OJ13oUfcPydsJ3xb1YnL3xaWZcgvp9sz8hMzL79vVaunr8xHGtB0TRPx2tRrnHlfeMPJ0QSCfYRl9OLTQg%2B394uMQwwFi8jAtdiYbAcY2RI9snc4mDiGivE%2B55TC9ccdohgZ0kw184ZSWN6y%2B%2FXgmvr%2BXZ%2BWTd2mPl0sVfQX34Hd7bI6XVUYHPc4depwjRBS58zoMPmvk3l%2BrV4UsOMLa2jCPaRkiKRtZSUNd53htWC3KhsmaGWdrUSvnwFTSKu0kGA1GQldyLZHbsK60VDmLej4knMrRW1gUbdOxGpRSqANMUNsJScGAsEZWRktrjKOCa%2BMAeGmkqgytJONaM621ELnxk%2B882aQ4A25GSKcQ79vnRP3YXm0zx8y%2Bd6%2F2eIMYTucP2GdrP4%2BsHfdpd%2Ft3%2FnY1dOvTw93dzWm5lzmFM4eJEq%2B2qhRvFGeVoNqqem25g3WF%2Fa0bK5p151yp0TYvhf1%2FZN%2BPMMLO5%2FTlWLRLhjdk%2BzWHSO%2FgXP%2Ba4RbjNcDLQK7ZWuT8tV0%2FT%2Fv2zb%2FVlHVFRS2ffv8DaPGPfIkDAAA%3D
I  [okhttp]:check permission begin!
W  ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I  [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I  errorMessage = Connection error: java.net.UnknownHostException: Unable to resolve host "uat.collector.ap-south-1.bd.tcljd.com": No address associated with hostname
I  AnalyticsMessageHandler msg wath = 3
I  delayFlush timeDelayMills = 15000
I  sendData
I  rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893555668}]
I  sendHttpRequest path = https://uat.collector.ap-south-1.bd.tcljd.com/v2/secured?project=Yv1_nhtgSxuOFmf-wyXXJw&country=in
I  sendHttpRequest rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893555668}]
I  query = crc=-1979770150&gzip=1&data_list=H4sIAAAAAAAAAH1Ty27bMBD8F7rHWCApiaR8C9oGcYA%2BgByaoigEPlY2G0k0KMpuEOTfu5QTJLn0QonD0ewOd%2FTrkbQpanvfekc2StWSlSW9IMkPQDZMCKmkog2uEsGHA4Jk4ZML0ntDNo%2Fkw%2FIkl6OLAUUuFqA9Qpx8GPGAF7SQL%2FAAaR%2BwErHBwQvoIGnfL%2BBQTDBOIU5OJ13oUfcPydsJ3xb1YnL3xaWZcgvp9sz8hMzL79vVaunr8xHGtB0TRPx2tRrnHlfeMPJ0QSCfYRl9OLTQg%2B394uMQwwFi8jAtdiYbAcY2RI9snc4mDiGivE%2B55TC9ccdohgZ0kw184ZSWN6y%2B%2FXgmvr%2BXZ%2BWTd2mPl0sVfQX34Hd7bI6XVUYHPc4depwjRBS58zoMPmvk3l%2BrV4UsOMLa2jCPaRkiKRtZSUNd53htWC3KhsmaGWdrUSvnwFTSKu0kGA1GQldyLZHbsK60VDmLej4knMrRW1gUbdOxGpRSqANMUNsJScGAsEZWRktrjKOCa%2BMAeGmkqgytJONaM621ELnxk%2B882aQ4A25GSKcQ79vnRP3YXm0zx8y%2Bd6%2F2eIMYTucP2GdrP4%2BsHfdpd%2Ft3%2FnY1dOvTw93dzWm5lzmFM4eJEq%2B2qhRvFGeVoNqqem25g3WF%2Fa0bK5p151yp0TYvhf1%2FZN%2BPMMLO5%2FTlWLRLhjdk%2BzWHSO%2FgXP%2Ba4RbjNcDLQK7ZWuT8tV0%2FT%2Fv2zb%2FVlHVdC6Gefv8DvIPck4kDAAA%3D
I  [okhttp]:check permission begin!
W  ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I  [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I  errorMessage = Connection error: java.net.UnknownHostException: Unable to resolve host "uat.collector.ap-south-1.bd.tcljd.com": No address associated with hostname
I  AnalyticsMessageHandler msg wath = 3
I  delayFlush timeDelayMills = 15000
I  sendData
I  rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893570745}]
I  sendHttpRequest path = https://uat.collector.ap-south-1.bd.tcljd.com/v2/secured?project=Yv1_nhtgSxuOFmf-wyXXJw&country=in
I  sendHttpRequest rawMessage = [{"_track_id":88571330,"time":1667878097877,"type":"track","lib":{"$lib":"Android","$lib_version":"2.0.7","$lib_method":"code","$lib_detail":"com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI##trackEventInternal##null##291"},"event":"app_eleclick","properties":{"$screen_orientation":"portrait","$os_version":"10","$model":"M2003J15SC","$os":"Android","$screen_width":1080,"$screen_height":2340,"$manufacturer":"Xiaomi","$app_version":"4.7.2","account_id":"39747b0dfd25b156391751bdc5658ddeb47c8ad7ebaeb7ef32a7fd291f3c08dc","iot_deviceid":"c9f15e888751e160cf670ebe6cb74ba7cbbd062abdee23b784b04712aa1aaa66","$wifi":true,"$network_type":"WIFI","$build_version":29,"$project_id":"Yv1_nhtgSxuOFmf-wyXXJw","$auto_id":"16310844829821460ac85-c2de-4dee-9c69-fdd3aa7f236c","$lib_version":"2.0.7","$lib":"Android","$registration_code":"IN","page_id":"H1","element_id":"H1-6"},"_flush_time":1667893570745}]
I  query = crc=-2023257002&gzip=1&data_list=H4sIAAAAAAAAAH1Ty27bMBD8F7rHWCApiaR8C9oGcYA%2BgByaoigEPlY2G0k0KMpuEOTfu5QTJLn0QonD0ewOd%2FTrkbQpanvfekc2StWSlSW9IMkPQDZMCKmkog2uEsGHA4Jk4ZML0ntDNo%2Fkw%2FIkl6OLAUUuFqA9Qpx8GPGAF7SQL%2FAAaR%2BwErHBwQvoIGnfL%2BBQTDBOIU5OJ13oUfcPydsJ3xb1YnL3xaWZcgvp9sz8hMzL79vVaunr8xHGtB0TRPx2tRrnHlfeMPJ0QSCfYRl9OLTQg%2B394uMQwwFi8jAtdiYbAcY2RI9snc4mDiGivE%2B55TC9ccdohgZ0kw184ZSWN6y%2B%2FXgmvr%2BXZ%2BWTd2mPl0sVfQX34Hd7bI6XVUYHPc4depwjRBS58zoMPmvk3l%2BrV4UsOMLa2jCPaRkiKRtZSUNd53htWC3KhsmaGWdrUSvnwFTSKu0kGA1GQldyLZHbsK60VDmLej4knMrRW1gUbdOxGpRSqANMUNsJScGAsEZWRktrjKOCa%2BMAeGmkqgytJONaM621ELnxk%2B882aQ4A25GSKcQ79vnRP3YXm0zx8y%2Bd6%2F2eIMYTucP2GdrP4%2BsHfdpd%2Ft3%2FnY1dOvTw93dzWm5lzmFM4eJEq%2B2qhRvFGeVoNqqem25g3WF%2Fa0bK5p151yp0TYvhf1%2FZN%2BPMMLO5%2FTlWLRLhjdk%2BzWHSO%2FgXP%2Ba4RbjNcDLQK7ZWuT8tV0%2FT%2Fv2zb%2FVlLWksqqffv8DTnE%2Fy4kDAAA%3D
I  [okhttp]:check permission begin!
W  ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
I  [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
I  errorMessage = Connection error: java.net.UnknownHostException: Unable to resolve host "uat.collector.ap-south-1.bd.tcljd.com": No address associated with hostname
E  Subscription Liveness timeout with SubscriptionID = 0x9a5eaf4f, Peer = 01:0000000000000006

**Comment by bzbarsky-apple** [comment]
The SDK supports this fine.  Not sure whether the Android bits expose the "KeepSubscriptions" configuration....

**Comment by yunhanw-google** [comment]
@joonhaengHeo  could you help take a look at this? Generally speaking, the JAVA/Kotlin API support multiple attributes, but there is UI bug regarding how to describe multiple attributes? maybe add a wildcard mode?

**Comment by joonhaengHeo** [comment]
In my case, I add several attributes to the wildcard function below.
Example : 
`listOf(attribute1, attribute2)`

https://github.com/project-chip/connectedhomeip/blob/1ab43dffb01702e748219b22bf43d59e669c7673/src/controller/java/src/chip/devicecontroller/ChipDeviceController.java#L497

However, in this case, only string(object) and tlv format were returned in java and kotlin, so tlv decoding function was additionally implemented internally and used. (Using ZAP)

String(Object)
https://github.com/project-chip/connectedhomeip/blob/1ab43dffb01702e748219b22bf43d59e669c7673/src/controller/java/src/chip/devicecontroller/model/AttributeState.java#L42

TLV :
https://github.com/project-chip/connectedhomeip/blob/1ab43dffb01702e748219b22bf43d59e669c7673/src/controller/java/src/chip/devicecontroller/model/AttributeState.java#L49

**Comment by joonhaengHeo** [comment]
I modified in CHIPTool UI.
Please refer below PR.
#25677
