### ISSUE TITLE
[BUG] Chip-tool ble-wifi pairing fails to connect

### ISSUE THREAD

**Issue by pankore** [project-chip/connectedhomeip#23552]
### Reproduction steps

```bash
- ./chip-tool ble-wifi 1 <SSID> <PW> 20202021 3840
- Matched discriminator, attempting to connect but failed
- See attached logs
```

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

ce2f4875caac9ba87cb151b197c7902a923fc123

### Platform

other

### Anything else?

[chip-tool-ble-wifi.log](https://github.com/project-chip/connectedhomeip/files/9966993/chip-tool-ble-wifi.log)

**Comment by s07641069** [comment]
Partly fixed in this commit: https://github.com/project-chip/connectedhomeip/commit/d249a43cd805f9bf89498b9f2feefdaf6c7a38cc

And timeout issue can be observed: https://github.com/project-chip/connectedhomeip/issues/23438

**Comment by bzbarsky-apple** [comment]
@pankore Is this different from #23438?

**Comment by pankore** [comment]
fixed on ToT
