### ISSUE TITLE
Lighting-App (Master) unresponsive after pairing with iPhone on iOS 16.1.1

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#23565]
Hi,

after upgrading my iPhone (!!) to iOS to 16.1.1 I was able to pair the lighting app (see before pairing issues from iOS 16.1), but after pairing the device is shown as "unavailable". I also see nothing the log of the Lighting app about connection tries or such ... 

Pairing log:
[chiplog.txt](https://github.com/project-chip/connectedhomeip/files/9979484/chiplog.txt)

Additional information: I now also did a pair with an HomePod (and scanning the QR Code) and afte rthe pairing the home app also stated roughly 30-45 seconds that the Lighting device is not responding, but THEN it connected and since then I can control the app and it is responsive. When I end the lighting app and restart then it needs again 20-45 seconds to reconnect.
Could it be that maybe tge Lighting app do not announce himself often enough so that it is received by an "IPhone" listening? But somehow "good enough" for an HomePod?

INITIAL issue:

While testing we discovered that the Lighting app (compiled o an Ubuntu Machine and run via Ethernet) do not successfully pair with iOS 16.1

In fact yes it could be iOS or it could be Chip ...:-)

When I read the log (see below) correctly then iOS answer with an error 2 to the Case_Sigma2 message.
iOS tells me about an uncertified device that I want to pair with, but then it runs into a timeout .

[chiplog.txt](https://github.com/project-chip/connectedhomeip/files/9975750/chiplog.txt)

PS: Also interesting is that if I choose to use the QR Code then iOS 16.1 tells me that I need a Hub device to connect it. When I use the PIN then the above log happens

**Comment by Apollon77** [comment]
BTW: As one info: We experience the same result with a "Node-matter" branch: see https://github.com/mfucci/node-matter/issues/103#issuecomment-1304650359

**Comment by Apollon77** [comment]
I enhanced the issue again with informations after a try to pair with an HomePod which was indeed successfull

**Comment by Apollon77** [comment]
For completeness here the log of the Homepod (not pairing but reconnection after restart of the lighting app
[out.txt](https://github.com/project-chip/connectedhomeip/files/9992714/out.txt)

**Comment by carol-apple** [comment]
@Apollon77 Can you please follow instructions below to file a feedback assistant ticket? 

Feedback assistant ticket:
- File a feedback assistant ticket.
https://developer.apple.com/bug-reporting/#feedback-assistant
- Click on the link below using your account:
https://feedbackassistant.apple.com/new-form-response
- Choose iOS/iPadOS to file an issue
- Choose the area as Home App and fill in the details of the type of issue and the description
* Technical Information
Please provide the following
a) Sysdiagnose logs for iPhone / iPad with the timestamp / timeframe of the issue
b) Sysdiagnose logs for all the Home Hubs (HomePod mini / HomePod / Apple TV) with the timestamp / timeframe of the issue
c) Accessory logs with the timestamp / timeframe of the issue
d) mDNS network logs with timestamp / timeframe of the issue
e) Video or screenshot describing the issue (optional but beneficial)
Please make sure you download and install the profiles for iOS and tvOS as provided here. The instructions are also in these links.
* iOS:
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=homekit
 - https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=network
 - https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=mdns
* tvOS:
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=homekit
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=network
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=mdns
For installation instructions, refer to https://developer.apple.com/bug-reporting/profiles-and-logs.
Note: Once you have the profile on the iPhone, it will ask you if you want to install it on other devices. Follow the prompts to install on the HomePod, Apple TV, etc., where you have the described issue and reproduce it.

**Comment by Apollon77** [comment]
I will recheck this with iOS 16.2 soon.

BTWWhen pairing with a Homepod then it works

**Comment by Apollon77** [comment]
Works in the meantime - and in fact is about homepod being there.
