### ISSUE TITLE
[BUG] Unable to compile iOS chiptool - redefinition of enumerations errors

### ISSUE THREAD

**Issue by kean-apple** [project-chip/connectedhomeip#23586]
### Reproduction steps

```bash
1.open iOS chiptool Xcode project (connectedhomeip/src/darwin/Darwin.xcworkspace)
2. Set Xcode team info
3.Try to compile iOS chiptool get various redefinition of enumerations errors and property has a previous declaration errors

Observed this with 008df4d5ad0e16896cdb155cf8d310d8747fb974 & b278e34bbf4720ac6008776fec2aba8a3a75ebd8
```

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

008df4d5ad0e16896cdb155cf8d310d8747fb974

### Platform

darwin

### Anything else?

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/73258860/201417770-8a582f74-cbe1-4798-a664-7adda94f08f6.png">

**Comment by kean-apple** [comment]
Seems to compile on older Xcode versions eg. 13.4.1 on a different Mac

**Comment by bzbarsky-apple** [comment]
@kean-apple Where do the error messages claim the "original" definition is?

My guess is that you are somehow managing to include both the system headers and the local headers or something like that....
