### ISSUE TITLE
[Feature] Support subscriptions on PASE sessions

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#23650]
### Feature description

```bash
In the spec, we says "A server may permit subscribe interactions even when there is no accessing fabric, subject to available resources (e.g. over PASE)"

For now, we reject all subscription over PASE, we should support it.
```

### Platform

all

### Platform Version(s)

N/A

**Comment by bzbarsky-apple** [comment]
There are some issues in terms of how this should work (e.g. how a subscription report on the client side should be matched up with things, given that there are no authenticated operational node IDs involved).  Needs to be done pretty carefully.
