### ISSUE TITLE
Javascript and python yaml test parse does not properly support utf8 octet strings

### ISSUE THREAD

**Issue by tehampson** [project-chip/connectedhomeip#23669]
If you provide a octet string that is >= `u+0200`, such as `ɼ`, `zap_regen_all.py` errors out. Additionally anything greater than 0xFF has the upper bytes chopped off.

Python parse was implemented to match behaviour of javascript. This needs to be fixed on both yaml parser/code generators

**Comment by bzbarsky-apple** [comment]
We should make such strings explicitly error out, ideally.  The ability to write octet strings as non-hex is a convenience, and we should not try to make it work for non-ASCII, with its UTF-8 vs UTF-16 (JS) confusion, etc.
