### ISSUE TITLE
[Darwin] Add fabric index to MTRDevice/MTRClusters logging

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#23671]
We should log things like:

1. When operations are queued.
2. When operations are pulled from the queue and started.
3. When operations are completed.

Ideally including the fabric index and target id in the logs.

**Comment by bzbarsky-apple** [comment]
@jtung-apple what's left here after https://github.com/project-chip/connectedhomeip/pull/23784?

**Comment by jtung-apple** [comment]
> @jtung-apple what's left here after #23784?

Fabric index. I'll make a PR to add this.
