### ISSUE TITLE
[BUG] Cannot resolve services using Android NsdManager when running Matter SDK

### ISSUE THREAD

**Issue by sharadb-amazon** [project-chip/connectedhomeip#23709]
### Reproduction steps

Tested with Android 9.

1. Start [linux tv-app](https://github.com/project-chip/connectedhomeip/tree/master/examples/tv-app/linux) and then the [Android tv-casting-app](https://github.com/project-chip/connectedhomeip/tree/master/examples/tv-casting-app/android)
2. Android tv-casting-app will discover the tv-app using **Commissioner discovery**, and show it on the UI. Select the TV.
3. The Linux tv-app will receive User directed commissioning requests, accept them by issuing the command "controller ux ok".
4. The Linux tv-app will commission the Android tv-casting-app.
5. Kill the Linux tv-app (using Ctrl/Cmd+C) AND clear the Matter SDK cache (run "rm /tmp/chip*") on the tv side.
6. Kill the Android tv-casting-app.
7. Start linux tv-app and then the Android tv-casting-app. This should automatically trigger **Operational discovery** on the Android tv-casting-app.
8. The Android tv-casting-app will fail to do Commissioner discovery of the Linux tv-app this time with the following error:
`2022-11-21 11:48:56.527 25644-25673/com.chip.casting E/NsdResolveListener: NsdResolveListener FAILURE_ALREADY_ACTIVE - Service: name: 98963D3F685FFD2A, type: _matterd._udp., host: null, port: 0, txtRecord: `

Note: This issue causes problems with both Matter as well as non-Matter use cases on a client Android app, if they need to use the NsdManager service resolver after the above steps. The NsdManager never seems to callback and always seems to stay busy trying to resolve the service.

See logs which cover steps #7 and #8 above (not #1 to #6):
* [android-tv-casting-app-20221121.log](https://github.com/project-chip/connectedhomeip/files/10061580/android-tv-casting-app-20221121.log)
* [linux-tv-app-20221121.log](https://github.com/project-chip/connectedhomeip/files/10061581/linux-tv-app-20221121.log)

### Bug prevalence

Every time with the above repro steps

### GitHub hash of the SDK that was being used

669cd4713793d8f0e45d90335cec4f8f9b6520ef

### Platform

android

### Anything else?

The issues seem to stem from two underlying problems:
1. The NsdManager's service resolver running in an app, can resolve one service at a time, or else, it'll callback with a [FAILURE_ALREADY_ACTIVE](https://developer.android.com/reference/android/net/nsd/NsdManager#FAILURE_ALREADY_ACTIVE) error (onResolveFailed), and
2. There doesn't seem to be a way to stop the NsdManager service resolver and it doesn't seem to time itself out.

Also note, we do wait for the callbacks using the NsdManagerResolverAvailState object, before trying to request a new service resolution on the NsdManager. The problem is, the NsdManager never seems to time itself out when following the above repro steps.

**Comment by Allen-Guof** [comment]
Looks like the same issue. https://github.com/project-chip/connectedhomeip/issues/23775

**Comment by joonhaengHeo** [comment]
I have had a similar issue before.
I think the problem is that when the resolve service times out on Android Platform, it stays busy until the app ends.

In order to defend this case, it is necessary to review whether it is necessary to unconditionally cover internally and then resolve.
I tried to process it with the workaround code based on the contents shown in the URL below.
https://developer.android.com/reference/android/net/nsd/NsdManager?hl=en
