### ISSUE TITLE
[BUG] ERROR Target 'linux-x64-java-matter-controller' could not be found. Nothing executed for it

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#23725]
### Reproduction steps

```bash
1. Get commit b4501101ba475024331582c69f105c14be416524
2. Building targets: linux-x64-java-matter-controller
```

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

b4501101ba475024331582c69f105c14be416524

### Platform

other

### Platform Version(s)

Java 1.8.0_352

### Anything else?

When I am trying to build Linux-x64-java-matter-controller with commit b4501101ba475024331582c69f105c14be416524, I am facing an error: 
**Target 'linux-x64-java-matter-controller' could not be found**. Nothing executed for it

```
ubuntu@RPI4:$ cd ~/connectedhomeip
ubuntu@RPI4:~/connectedhomeip$ ./scripts/build/build_examples.py --target linux-x64-java-matter-controller build
2022-11-22 19:39:30 INFO    Building targets: linux-x64-java-matter-controller
2022-11-22 19:39:30 ERROR   Target 'linux-x64-java-matter-controller' could not be found. Nothing executed for it
```

**Comment by yunhanw-google** [comment]
please try this, thanks
https://github.com/project-chip/connectedhomeip/tree/master/examples/java-matter-controller, which can run java controller in linux environment to test accessary.

some instructions are as below.
-- Build
docker run -it -v /workspace/connectedhomeip:/connectedhomeip connectedhomeip/chip-build:0.6.06
git config --global --add [safe.directory](http://safe.directory/) /connectedhomeip
git config --global --add [safe.directory](http://safe.directory/) /connectedhomeip/third_party/pigweed/repo
export JAVA_PATH=/usr/lib/jvm/java-8-openjdk-amd64/
source scripts/bootstrap.sh
./scripts/build/build_examples.py --target linux-x64-java-matter-controller build
./scripts/build/build_examples.py --target linux-x64-all-clusters build

--In Terminal A
docker exec -it c20375aeb713 bash
rm -rf /tmp/chip* & ./out/linux-x64-all-clusters/chip-all-clusters-app

--In terminal B
docker exec -it c20375aeb713 bash
java -verbose:jni -Xcheck:jni -jar -Djava.library.path=out/linux-x64-java-matter-controller/lib/jni out/linux-x64-java-matter-controller/bin/java-matter-controller pairing onnetwork-long 1 20202021 3840 1000
