### ISSUE TITLE
[Documentation] [nrfconnect] Missing Building with low-power configuration section

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#23794]
### Documentation issues

Missing 'Building with low-power configuration' section in page examples/light-switch-app/nrfconnect

### Platform

nrf

### Anything else?

Broken link: [Building with low-power configuration
](https://github.com/project-chip/connectedhomeip/tree/master/examples/light-switch-app/nrfconnect#building-with-low-power-configuration)

**Comment by Damian-Nordic** [comment]
The section has been removed from all nRF Connect examples as we decided to apply all low-power modifications to the release configuration and hence, reduce the number of variants. Thanks for letting us know about the broken links, I'll clean them up.
