### ISSUE TITLE
[Darwin] MTRDevice needs a non-subscription API 

### ISSUE THREAD

**Issue by jtung-apple** [project-chip/connectedhomeip#23808]
### Reproduction steps

```bash
n/a
```

### Platform

darwin

### Platform Version(s)

1.0

### Type

Platform validated

### Anything else?

Client of MTRDevice may wish to communicate (command / write / read) with accessories without subscribing to everything.

This issue tracks new API to support this.

**Comment by woody-apple** [comment]
Closing this. @bzbarsky-apple and @jtung-apple to break this out and clarify.
