### ISSUE TITLE
Missing cluster error in simulated test

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#23834]
### Reproduction steps / Feature

```bash
Seeing cluster missing error when tried to run simulated tests.
1 . Add FLABEL-3.1 simulated test
2 . Run regen command ( ./scripts/tools/zap_regen_all.py )
3 . Shows cluster missing error

Missing cluster:
Account Login
Application Launcher
Fixed Label
Audio Output
Channel
Thread Network Diagnostics
Diagnostic Logs
Door Lock
Low Power
Unit Localization
Time Format Localization
Media Input
Media Playback
Occupancy
Pressure Measurement
User Label
Wake on LAN
Bridged Device Basic Information
Localization Configuration
```

### Platform

other

### Platform Version(s)

N/A

### Type

YAML tested

### Anything else?

diff link:
https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:Simulated_Cluster_MissingError
Execution logs:
![image](https://user-images.githubusercontent.com/102359958/204879053-6250ca6e-173b-41a8-9117-788bc9d7c55a.png)
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/10126179/exe_log.txt)

**Comment by bzbarsky-apple** [comment]
@raju-apple @manjunath-grl Does it help if you enable the relevant cluster(s) in the placeholder app .zap files?

**Comment by manjunath-grl** [comment]
@bzbarsky-apple sure i will try it.
