### ISSUE TITLE
[genio] correct dnssd api usage 

### ISSUE THREAD

**Issue by j8xixo12** [project-chip/connectedhomeip#23847]
### Reproduction steps

```bash
1. Commission with multiple controller
2. Dnssd publish service can not publish service due to out of socket
```

### Platform

other

### Type

Manually tested with SDK

**Comment by pakls** [comment]
@bzbarsky-apple This addresses test case failures we found and is necessary.

**Comment by pakls** [comment]
@j8xixo12 Could the description be updated specify platform as Genio or MT793x? Currently it's 'other' in the description above. Thanks.

**Comment by pakls** [comment]
#23848

**Comment by j8xixo12** [comment]
@pakls I can not find Genio or MT793x in the Platform list, so.... I choice other
