### ISSUE TITLE
[1.0] Google Nest hub Gen2 is not updating to support Matter 1.0

### ISSUE THREAD

**Issue by AlexeyYukhin** [project-chip/connectedhomeip#23899]
### Reproduction steps

Sorry if my issue is not relevant, but I hope i can find answers here.

I have Google Nest hub Gen2. I've switched on the option "Development program" in Google home app menu to have an ability to get updates for my nest hub, as Matter 1.0 release was announced recently. But it's still on 1.56.309385 chromecast firmware version (47.9.4.447810048 software version).

I also tried to perform device reboot and factory reset, but no luck. So my question is - what is to be done from my side to get my Nest hub work with Matter 1.0? I really need it to be able to develop and test matter devices integration.

### Bug prevalence

The issue exists since i bought Google Nest hub Gen2

### GitHub hash of the SDK that was being used

7c2353bb7af06303350796103867ed5aa9b4fd27

### Platform

android, esp32

### Type

Platform Issue

**Comment by andy31415** [comment]
This request seems to be google specific rather than open source SDK.

Closing this issue. Instead, a vendor specific forum should be used. In this case maybe https://support.google.com/googlenest/gethelp?hl=en
