### ISSUE TITLE
[Documentation] Profile installation failed

### ISSUE THREAD

**Issue by CryptoGL** [project-chip/connectedhomeip#23919]
### Documentation issues

```bash
1.iPhone shows the profile is no longer valid
2.iOS 16.1.2
3.
...
```

### Anything else?

![ae2340f542e68179a0a4e7a4d9e4818a](https://user-images.githubusercontent.com/22292685/205798710-0f3ee840-2f55-4121-a054-0b27829b62b7.jpg)

![0dbfc6a0dbaac13e58ede92aab599aeb](https://user-images.githubusercontent.com/22292685/205799284-d780b114-5e3c-495d-80e5-910af0af47fc.jpg)

**Comment by bzbarsky-apple** [comment]
@CryptoGL I don't believe the profile you are trying to install is needed on iOS 16.1.

**Comment by CryptoGL** [comment]
> @CryptoGL I don't believe the profile you are trying to install is needed on iOS 16.1.

<img width="901" alt="image" src="https://user-images.githubusercontent.com/22292685/206140982-683aadc2-7acf-400c-9d07-62d9b9be6d8d.png">
I used the profile downloaded from above.

**Comment by sidhoo2** [comment]
@CryptoGL there is no need to install the profile on iOS 16.1. but i  am not success 😭

**Comment by bzbarsky-apple** [comment]
@CryptoGL Those instructions are outdated (note they are referencing 15.6).  See https://github.com/project-chip/connectedhomeip/pull/23979 for the updated instructions that would be relevant on 16.1.
