### ISSUE TITLE
How does Android APP know that the matter device is offline/online[BUG] 

### ISSUE THREAD

**Issue by 123yangu** [project-chip/connectedhomeip#23945]
### Reproduction steps

```bash
1.PairingComplete matter device
2.Monitor whether the material device is online/offline
3.How to monitor online/offline
...
```

### Bug prevalence

1

### GitHub hash of the SDK that was being used

chiptool

### Platform

android

### Platform Version(s)

Android

**Comment by yunhanw-google** [comment]
I think you can create the IM subscription via android IM API, https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/src/chip/devicecontroller/ChipDeviceController.java#L699, then if the device goes offline, you will receive callback in controller side saying subsciprtion timeout via https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/src/chip/devicecontroller/ReportCallback.java#L28, the error is set in https://github.com/project-chip/connectedhomeip/blob/master/src/app/ReadClient.cpp#L634. let me know whether you have further question on it, feel free to reopen it, thanks
