### ISSUE TITLE
[Feature] SoftAP commissioning

### ISSUE THREAD

**Issue by wqx6** [project-chip/connectedhomeip#23998]
### Feature description

There are some issues for SoftAP commissioning:
- [ ] The commissioner cannot setup the device's network when using softAP commissioning. #23868
- [ ] The commissionee will advertise operational service on its AP network when it has joined the operational network. That results that the commissioner establishes CASE Session over SoftAP link instead of the operational network if the commissioner keeps the connection with the SoftAP.
- [ ] For chip-tool(or other commissioners), the connection over SoftAP link cannot be terminated even if the commissionee has joined the  operational network. It will result a Timeout error. For some commissioners, it would switch to the operational network from the SoftAP network when it receives `ConnectedNetwork` from the commissionee. 
- [ ] Vendor Specific IE should be added for platforms if they enable the SoftAP commissioning.

**Comment by woody-apple** [comment]
Closing as a duplicate of: https://github.com/project-chip/connectedhomeip/issues/17487
