### ISSUE TITLE
[TC-SC-2.]SDK support Required for Passcode-Authenticated Session Establishment (PASE) flags.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#24017]
### Feature description

```bash
SDK support Required for Passcode-Authenticated Session Establishment (PASE)  Protocol flags in Secure channel Session Establishment.
Related test cases :
TC-SC-2.1
TC-SC-2.2
```

### Platform

raspi

### Anything else?

**Spec Reference :** 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/secure_channel/Password_Authenticated_Session_Establishment.adoc#protocol-details

**Test-plan Reference :**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/securechannel.adoc#session-establishment

**Comment by KishokG** [comment]
@Ashwinigrl Please check and reopen the issue, if it's not fixed..
