### ISSUE TITLE
[TC-SC-] Chip-tool support required to handle the error scenarios in Secure Channel.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#24020]
### Feature description

```bash
Chip-tool support required to handle the error scenarios in Secure Channel for PASE Error Handling and Case Error handling to validate the below mentioned Tesyt Cases.
[TC-SC-2.3], [TC-SC-2.4], [TC-SC-3.4] and [TC-SC-3.5].
```

### Platform

raspi

### Anything else?

**Test-plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/securechannel.adoc#tc-sc-2-3-pase-error-handling-dut_respondercommissionee-removed
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/securechannel.adoc#tc-sc-3-4-case-error-handling-dut_responder-removed

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/secure_channel/Password_Authenticated_Session_Establishment.adoc#protocol-details
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/secure_channel/Certificate_Authenticated_Session_Establishment.adoc

**Comment by KishokG** [comment]
@Ashwinigrl Please check and reopen the issue, if it's not fixed..
