### ISSUE TITLE
[Documentation] The letter 'c' is omitted in the word 'description'

### ISSUE THREAD

**Issue by LawrenceQuarshie** [project-chip/connectedhomeip#24098]
### Omission of Letter 'c' in the word 'description'

The letter 'c' is missing in the word 'description' in the sentence "Please delete the instructions below and replace with PR description".

### Anything else?

![Matter_Issues_Screenshot_0](https://user-images.githubusercontent.com/59454677/207937995-68f7ff89-28e4-41a8-acfb-e339a24fe69f.png)

https://github.com/project-chip/connectedhomeip/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by andy31415** [comment]
Consider creating a PR to fix this, should be an easy fix.

**Comment by LawrenceQuarshie** [comment]
Well noted Andy.

That will be my first pull request on an open source project.

I will let you know when I am done.

Thank you for giving me this opportunity.

**Comment by LawrenceQuarshie** [comment]
Hello @andy31415 

Done with the pull request.

It is opened yet to be closed.

Thank you.

**Comment by LawrenceQuarshie** [comment]
Hello @andy31415,

I created a PR and now the issue is fixed and closed.

Thank you for the encouragement.
