### ISSUE TITLE
Vendor Id 

### ISSUE THREAD

**Issue by guylevin** [project-chip/connectedhomeip#24112]
In the esp32 example projects, where is the vendor id set?

**Comment by YOGYUI** [comment]
You can find in esp-idf menuconfig. (Component config -> CHIP Device Layer -> Device Identification Options)
$idf.py menuconfig
![image](https://user-images.githubusercontent.com/87917955/210535540-4b65973f-11db-4a90-9564-26bdd2263547.png)

This action changed sdkconfig file (See CONFIG_DEVICE_VENDOR_ID definition)
![image](https://user-images.githubusercontent.com/87917955/210535890-cf3af7cb-2418-4a14-a072-ea7267af4119.png)

I hope this content is what you're looking for.
