### ISSUE TITLE
ACL-2.4 nodeId mismatch test run error

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#24133]
### Reproduction steps

 Tried to add test TC_ACL-2.4 script as per testplan in 
Step 1. while commissions we are using nodeId as 0x12344321 from config section
while in step 3: we are reading ACL attribute and the subject field of it expects the value nodeId which is used while pairing that is 0x12344321 but seeing failure response showing that " Test Failure: acl[0].subjects.Value()[0] value mismatch: expected 305414945 but got 112233 "
Reproduction steps:
1. Add test ACL-2.6 and run below commands.
2. Regen
'''./scripts/tools/zap_regen_all.py --type tests'''
3. Build
'''./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-chip-tool-no-ble-tsan-clang \
                        --target linux-x64-all-clusters-no-ble-tsan-clang \
                        --target linux-x64-lock-no-ble-tsan-clang \
                        --target linux-x64-ota-provider-no-ble-tsan-clang \
                        --target linux-x64-ota-requestor-no-ble-tsan-clang \
                        --target linux-x64-tv-app-no-ble-tsan-clang \
                        --target linux-x64-bridge-no-ble-tsan-clang \
                        build \
                     " '''
4. Python test run:
'''./scripts/run_in_build_env.sh \
                  "./scripts/tests/run_test_suite.py \
                     --chip-tool ./out/linux-x64-chip-tool-no-ble-tsan-clang/chip-tool \
                     run \
                     --iterations 1 \
                     --test-timeout-seconds 120 \
                     --all-clusters-app ./out/linux-x64-all-clusters-no-ble-tsan-clang/chip-all-clusters-app \
                     --lock-app ./out/linux-x64-lock-no-ble-tsan-clang/chip-lock-app \
                     --ota-provider-app ./out/linux-x64-ota-provider-no-ble-tsan-clang/chip-ota-provider-app \
                     --ota-requestor-app ./out/linux-x64-ota-requestor-no-ble-tsan-clang/chip-ota-requestor-app \
                     --tv-app ./out/linux-x64-tv-app-no-ble-tsan-clang/chip-tv-app \
                     --bridge-app ./out/linux-x64-bridge-no-ble-tsan-clang/chip-bridge-app \
                  " '''
 ACL-2.* ran and seeing " Test Failure: acl[0].subjects.Value()[0] value mismatch: expected 305414945 but got 112233 "

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

04c20f6584ed47d1b4ba9bb7d873b7867cc2c60d

### Platform

other

### Anything else?

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:ACL_nodeId_mismatch_error

Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/208415409-1034f973-fd4d-411e-a32c-1c4cc96d705f.png)
YAML screenshot:
![image](https://user-images.githubusercontent.com/102359958/208415506-409632ae-b36d-4d85-9257-be1f5d4ed4fd.png)
Execution logs:
![image](https://user-images.githubusercontent.com/102359958/208415612-5576cd73-dad0-4636-b0f8-4703c1badd14.png)
[exe_log.txt](https://github.com/project-chip/connectedhomeip/files/10258830/exe_log.txt)

**Comment by bzbarsky-apple** [comment]
The subject would be the node id of the _commissioner_, not the node id of the node being commissioned.  So this test YAML is just wrong as written.
