### ISSUE TITLE
Matter device showing offline

### ISSUE THREAD

**Issue by SYESHASWINI** [project-chip/connectedhomeip#24146]
I have flashed Light example to Esp32c3 board and added the device to google home. It is successfully added, but the device is showing offline. I have factory reset the nest hub, updated google home and tried, but nothing worked. Requesting for the suggestions.

Board: esp32c3
Nest Hub version: 1.56.324896

![WhatsApp Image 2022-12-20 at 15 09 02](https://user-images.githubusercontent.com/59026832/208638107-14544439-1564-4938-bf75-149b896148be.jpeg)

**Comment by bzbarsky-apple** [comment]
This sounds like an issue to report to Google Home, not here....
