### ISSUE TITLE
[BUG] [WSL2] Unable to build the project

### ISSUE THREAD

**Issue by Valcob** [project-chip/connectedhomeip#24147]
### Reproduction steps

ENV: Win10+WSL2(Ubuntu18)

in WSL2
1. Clone the project https://github.com/project-chip/connectedhomeip.git (done in WSL2 directly)
2. cd into project directory and run "code ."
3. when prompted to switch to docker container do so
4.  wait for docker image to build 
5.  when build container is started open a new terminal window in VS code and run "source /opt/espressif/esp-idf/export.sh"
6.  then run "source scripts/activate.sh" and afterwards "source scripts/bootstrap.sh"
7.  when all is updated and installed  cd into a project  "cd examples/all-clusters-app/esp32"
8.  now try to build it by running idf.py set-target esp32 and then idf.py build

Actual result: 

![image](https://user-images.githubusercontent.com/37367415/208642335-fe30f129-3ccf-4897-a4d9-d5273625afd9.png)

### Bug prevalence

*

### GitHub hash of the SDK that was being used

04c20f6584ed47d1b4ba9bb7d873b7867cc2c60d

### Platform

vscode

**Comment by Piyush2495** [comment]
connected home ip
