### ISSUE TITLE
[BUG] [nRF52840] nRF52840dongle build error

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#24142]
### Reproduction steps

I follow below URL and set up environment (native shell).
[https://github.com/project-chip/connectedhomeip/tree/v1.0-branch/examples/lighting-app/nrfconnect#using-native-shell-for-setup](https://github.com/project-chip/connectedhomeip/tree/v1.0-branch/examples/lighting-app/nrfconnect#using-native-shell-for-setup)

```bash
cd $matter-dir/examples/lighting-app/nrfconnect
rm -rf build
west build -b nrf52840dongle_nrf52840
```
However, it cannot finish building.
`west build -b nrf52840dk_nrf52840` could finish without error.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 7f2b0a5920d1a7acc202c2932ac4c626c54cd31e (HEAD -> v1.0-branch, origin/v1.0-branch)

### Platform

nrf

### Log

`nRF52840 dongle` cannot finish building with error.
[nrf52840dongle_nrf52840.txt](https://github.com/project-chip/connectedhomeip/files/10265491/nrf52840dongle_nrf52840.txt)

I tried `ubx_evkninab3_nrf52840`, and it had error.
it cannot finish building.
[ubx_evkninab3_nrf52840.txt](https://github.com/project-chip/connectedhomeip/files/10265494/ubx_evkninab3_nrf52840.txt)

`nRF52840-DK` can finish building normally.
[nrf52840dk_nrf52840.txt](https://github.com/project-chip/connectedhomeip/files/10265475/nrf52840dk_nrf52840.txt)

### Environment
OS : ubuntu 20.04

~/ncs/nrf$ git log -1
commit 053756565898659278f957e5f58000cc0491a88d (HEAD, tag: v2.0.2)

~/ncs/zephyr$ git log -1
commit be360e7db2db7e1f0e9fcac686a08e62e350bf55 (HEAD, tag: v3.0.99-ncs1-1, manifest-rev)

arm toolchain
gcc-arm-none-eabi-10.3-2021.10

**Comment by kkasperczyk-no** [comment]
This is because nRF52840 dongle doesn't have external flash required for DFU, so you cannot use default configuration that enables DFU with this board. Please try to use `prj_no_dfu.conf` build. You can do that by invoking: `west build -b nrf52840dongle_nrf52840 -- -DCONF_FILE=prj_no_dfu.conf`command. See documentation for more details: https://github.com/project-chip/connectedhomeip/tree/v1.0-branch/examples/lighting-app/nrfconnect#example-build-types

**Comment by mmt-10** [comment]
@kkasperczyk-no 
Thank you for your advice.
it can finish building without error.
