### ISSUE TITLE
[Linux] ACL-2.10 Attribute write showing UNSUPPORTED_ACCESS instead of success response

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#24151]
### Reproduction steps / Feature

Summary:
        As per testplan in step 7:  Trying to write Extension attribute with Data field: D_OK_EMPTY but seeing " UNSUPPORTED_ACCESS " response when executed.

Reproduction steps:
1. Add test ACL-2.10 and run below commands.
2. Regen
'''./scripts/tools/zap_regen_all.py --type tests'''
3. Build
''' ./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-chip-tool-no-ble-tsan-clang \
                        --target linux-x64-all-clusters-no-ble-tsan-clang \
                        --target linux-x64-lock-no-ble-tsan-clang \
                        --target linux-x64-ota-provider-no-ble-tsan-clang \
                        --target linux-x64-ota-requestor-no-ble-tsan-clang \
                        --target linux-x64-tv-app-no-ble-tsan-clang \
                        --target linux-x64-bridge-no-ble-tsan-clang \
                        build \ "
 '''
4. Python test run:
''' ./scripts/run_in_build_env.sh \
                  "./scripts/tests/run_test_suite.py \
                     --chip-tool ./out/linux-x64-chip-tool-no-ble-tsan-clang/chip-tool \
                     run \
                     --iterations 1 \
                     --test-timeout-seconds 120 \
                     --all-clusters-app ./out/linux-x64-all-clusters-no-ble-tsan-clang/chip-all-clusters-app \
                     --lock-app ./out/linux-x64-lock-no-ble-tsan-clang/chip-lock-app \
                     --ota-provider-app ./out/linux-x64-ota-provider-no-ble-tsan-clang/chip-ota-provider-app \
                     --ota-requestor-app ./out/linux-x64-ota-requestor-no-ble-tsan-clang/chip-ota-requestor-app \
                     --tv-app ./out/linux-x64-tv-app-no-ble-tsan-clang/chip-tv-app \
                     --bridge-app ./out/linux-x64-bridge-no-ble-tsan-clang/chip-bridge-app \"
'''

### Platform

other

### Type

YAML tested

### Anything else?

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:ACL_2_10_UnsupportedAccess_ERR

Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/208669531-76d20307-3b9f-470a-a1fe-a496e5db9656.png)

Execution logs:
[ACL_2_10.zip](https://github.com/project-chip/connectedhomeip/files/10268401/ACL_2_10.zip)

**Comment by bzbarsky-apple** [comment]
The test YAML does the following: (step labeling is the YAML steps, not the test plan steps):

1. Step 7: change ACLs so that only node ids `nodeId2` and `2222` have admin access on fabric 2.
2. Step 9: Try to write the Extension attribute on fabric 2.

But the node id of the commissioner on fabric 2 is `112233` as far as I can tell.  And `nodeId2` is the address of the _commissionee_.  So after step 7 the commissioner no longer has access to the device.
