### ISSUE TITLE
[Linux] ACL-2.9 Attribute read showing UNSUPPORTED_ACCESS instead of success response

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#24150]
### Reproduction steps / Feature

Summary:
        As per testplan in step 7: Attribute read of SubjectsPerAccessControlEntry should give success response but seeing " UNSUPPORTED_ACCESS " response when executed.

Reproduction steps:
1. Add test ACL-2.9 and run below commands.
2. Regen
'''./scripts/tools/zap_regen_all.py --type tests'''
3. Build
''' ./scripts/run_in_build_env.sh \
                     "./scripts/build/build_examples.py \
                        --target linux-x64-chip-tool-no-ble-tsan-clang \
                        --target linux-x64-all-clusters-no-ble-tsan-clang \
                        --target linux-x64-lock-no-ble-tsan-clang \
                        --target linux-x64-ota-provider-no-ble-tsan-clang \
                        --target linux-x64-ota-requestor-no-ble-tsan-clang \
                        --target linux-x64-tv-app-no-ble-tsan-clang \
                        --target linux-x64-bridge-no-ble-tsan-clang \
                        build \ "
 '''
4. Python test run:
''' ./scripts/run_in_build_env.sh \
                  "./scripts/tests/run_test_suite.py \
                     --chip-tool ./out/linux-x64-chip-tool-no-ble-tsan-clang/chip-tool \
                     run \
                     --iterations 1 \
                     --test-timeout-seconds 120 \
                     --all-clusters-app ./out/linux-x64-all-clusters-no-ble-tsan-clang/chip-all-clusters-app \
                     --lock-app ./out/linux-x64-lock-no-ble-tsan-clang/chip-lock-app \
                     --ota-provider-app ./out/linux-x64-ota-provider-no-ble-tsan-clang/chip-ota-provider-app \
                     --ota-requestor-app ./out/linux-x64-ota-requestor-no-ble-tsan-clang/chip-ota-requestor-app \
                     --tv-app ./out/linux-x64-tv-app-no-ble-tsan-clang/chip-tv-app \
                     --bridge-app ./out/linux-x64-bridge-no-ble-tsan-clang/chip-bridge-app \"
'''

### Platform

other

### Type

YAML tested

### Anything else?

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:ACL_SubjectsPerAccessControlEntry_UnsupportedAttribute_ERR

Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/208665716-8fc8611d-a496-482c-ba3b-d40e860122ea.png)

Execution logs:
[ACL_2_9.zip](https://github.com/project-chip/connectedhomeip/files/10268288/ACL_2_9.zip)

**Comment by bzbarsky-apple** [comment]
When the YAML linked here is writing ACLs, it's only giving Manage access to `nodeId`.  `nodeId` is the node id of the _commissionee_, not the _commissioner_.  So after that step (step 2 in the YAML) runs, the commissioner no longer has access.

The test plan says:

> N1 is the node ID of TH1

and 

> Subjects field: [N1]

but that's not what the YAML is doing.
