### ISSUE TITLE
[BUG] Does CHIP_DEVICE_CONFIG_ENABLE_TEST_SETUP_PARAMS do anything?

### ISSUE THREAD

**Issue by step0035** [project-chip/connectedhomeip#24247]
### Reproduction steps

Not really a bug.
Does `CHIP_DEVICE_CONFIG_ENABLE_TEST_SETUP_PARAMS` in platform configs do anything?
If not, it should be removed to avoid confusion.

### Bug prevalence

NA

### GitHub hash of the SDK that was being used

23e5fb2c17a8148d56ec95d874d7007589b8204d

### Platform

other

**Comment by bzbarsky-apple** [comment]
>  Does CHIP_DEVICE_CONFIG_ENABLE_TEST_SETUP_PARAMS in platform configs do anything?

Yes.  See https://github.com/project-chip/connectedhomeip/blob/34f9130609314ea76c6ac06f93feb314eee438b3/src/include/platform/CHIPDeviceConfig.h#L811-L892
