### ISSUE TITLE
[ICD] Add the possibility to resolve an IP address without establishing a case session

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#24255]
### Feature description

Currently, you can only resolve an IP address and establish a case session at the same time.  In the case of an IC device, it will only need to resolve the IP address. It will not be establishing a case session.

**Comment by mkardous-silabs** [comment]
This still needs to be resolved.

**Comment by jepenven-silabs** [comment]
Resolved by https://github.com/project-chip/connectedhomeip/pull/30385
