### ISSUE TITLE
[ICD] Implement Check-in Processing with chip-tool 

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#24263]
### Feature description

For testing purposes, the chip-tool needs to be able to receive check-in messages and process them correctly.
Ideally,  a counter would be incremented everytime a check-in message is received to be able to verify that the correct number of check-in message were receveid over a certain period of time.

**Comment by mkardous-silabs** [comment]
This still needs to be resolved.

**Comment by yunhanw-google** [comment]
dup with https://github.com/project-chip/connectedhomeip/issues/28232
