### ISSUE TITLE
[ICD] Add encryption to the check-in message 

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#24261]
### Feature description

The type of encryption to be used on a check-in message hasn't been decided yet. Once #24243 is done and the mecanisme has been established, add encryption to the check-in message.

**Comment by mkardous-silabs** [comment]
This still needs to be resolved.

**Comment by jepenven-silabs** [comment]
Resolved by https://github.com/project-chip/connectedhomeip/pull/27615
