### ISSUE TITLE
[ICD] Remove dependency on the Server.cpp file to get Persistant data storage delegate 

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#24289]
### Feature description

When creating an instance of the ICDManagementRegistrationTable, the icd-management-server requires a reference to the Persistant data storage delegate which we get from the Server::instance.

We need to figure out a way to get it without adding a dependency to the Server instance.

**Comment by mkardous-silabs** [comment]
This still needs to be resolved.

**Comment by turon** [comment]
WG: Is this just internal clean up?  Perhaps not a blocker.

**Comment by mkardous-silabs** [comment]
@turon Not a blocker; more like a nice to have
