### ISSUE TITLE
[Darwin] 

### ISSUE THREAD

**Issue by LucaFagan** [project-chip/connectedhomeip#24382]
### Reproduction steps

How do I get the Matter device's capabilities in chip-tool? What command/method needs to be sent?

For example, I need to know which endpoints are included in the Matter device, and which clusterIds are under each endpoint.

### Platform

darwin

### Platform Version(s)

1.0

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
> For example, I need to know which endpoints are included in the Matter device

Read the PartsList of endpoint 0.

> which clusterIds are under each endpoint.

Read the ServerList and ClientList attributes of the relevant endpoints.
