### ISSUE TITLE
Client Monitoring cluster implementation does not seem to match draft spec

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#24425]
See https://github.com/project-chip/connectedhomeip/pull/24284#pullrequestreview-1248719654 -- instead of a writable attribute as per spec, there are commands to manipulate the registrations....

**Comment by mkardous-silabs** [comment]
Client Monitoring Cluster implementation doesn't match the new revision of the specification.
See https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6482 for the current spec text for the client monitoring.

**Comment by mkardous-silabs** [comment]
@bzbarsky-apple closing the issue since it is no longer applicable / fixed
