### ISSUE TITLE
PR #24097: Size comparison from b49c3ed920f7b95fc0f95ce5e8bdb82c85e757d8 to 28ae775b3625ef42ff20ed850d97310ee8d3a7df

### ISSUE THREAD

**Issue by Kongpcmail** [project-chip/connectedhomeip#24430]
PR #24097: Size comparison from b49c3ed920f7b95fc0f95ce5e8bdb82c85e757d8 to 28ae775b3625ef42ff20ed850d97310ee8d3a7df

<details>
<summary>Increases (6 builds for bl702, linux, telink)</summary>

| platform   | target             | config         | section      |   b49c3ed9 |   28ae775b |   change |   % change |
|:-----------|:-------------------|:---------------|:-------------|-----------:|-----------:|---------:|-----------:|
| bl702      | lighting-app       | bl702          | .debug_info  |   39187066 |   39187067 |        1 |        0.0 |
|            |                    |                | .text        |     956734 |     956736 |        2 |        0.0 |
|            |                    | bl702+rpc      | .debug_info  |   43479486 |   43479487 |        1 |        0.0 |
|            |                    |                | .text        |    1030716 |    1030718 |        2 |        0.0 |
| linux      | chip-tool-ipv6only | arm64          | (read only)  |   10582156 |   10583900 |     1744 |        0.0 |
|            |                    |                | .rodata      |     535068 |     535180 |      112 |        0.0 |
|            |                    |                | .text        |    8412356 |    8413988 |     1632 |        0.0 |
| telink     | light-switch-app   | tlsr9518adk80d | (read/write) |     932092 |     932100 |        8 |        0.0 |
|            |                    |                | text         |     637928 |     637932 |        4 |        0.0 |
|            | ota-requestor-app  | tlsr9518adk80d | text         |     649184 |     649188 |        4 |        0.0 |
|            | thermostat         | tlsr9518adk80d | text         |     638612 |     638616 |        4 |        0.0 |
</details>

<details>
<summary>Decreases (4 builds for bl602, nrfconnect, telink)</summary>

| platform   | target                   | config                   | section      |   b49c3ed9 |   28ae775b |   change |   % change |
|:-----------|:-------------------------|:-------------------------|:-------------|-----------:|-----------:|---------:|-----------:|
| bl602      | lighting-app             | bl602                    | (read/write) |    1356258 |    1356250 |       -8 |       -0.0 |
|            |                          |                          | .text        |    1039050 |    1039048 |       -2 |       -0.0 |
| nrfconnect | all-clusters-app         | nrf7002dk_nrf5340_cpuapp | text         |     759866 |     759862 |       -4 |       -0.0 |
| telink     | all-clusters-app         | tlsr9518adk80d           | (read/write) |    1071336 |    1071328 |       -8 |       -0.0 |
|            |                          |                          | text         |     726146 |     726142 |       -4 |       -0.0 |
|            | all-clusters-minimal-app | tlsr9518adk80d           | text         |     691308 |     691306 |       -2 |       -0.0 |
</details>

<details>
<summary>Full report (21 builds for bl602, bl702, k32w, linux, mbed, nrfconnect, qpg, telink)</summary>

| platform   | target                   | config                      | section           |   b49c3ed9 |   28ae775b |   change |   % change |
|:-----------|:-------------------------|:----------------------------|:------------------|-----------:|-----------:|---------:|-----------:|
| bl602      | lighting-app             | bl602                       | (read/write)      |    1356258 |    1356250 |       -8 |       -0.0 |
|            |                          |                             | .bss              |      86977 |      86977 |        0 |        0.0 |
|            |                          |                             | .data             |       9984 |       9984 |        0 |        0.0 |
|            |                          |                             | .text             |    1039050 |    1039048 |       -2 |       -0.0 |
|            |                          | bl602+rpc                   | (read/write)      |    1402034 |    1402034 |        0 |        0.0 |
|            |                          |                             | .bss              |      95017 |      95017 |        0 |        0.0 |
|            |                          |                             | .data             |      10384 |      10384 |        0 |        0.0 |
|            |                          |                             | .text             |    1070472 |    1070472 |        0 |        0.0 |
| bl702      | lighting-app             | bl702                       | (read only)       |       3262 |       3262 |        0 |        0.0 |
|            |                          |                             | (read/write)      |    1196143 |    1196143 |        0 |        0.0 |
|            |                          |                             | .bleromro         |       6296 |       6296 |        0 |        0.0 |
|            |                          |                             | .bleromrw         |        124 |        124 |        0 |        0.0 |
|            |                          |                             | .boot2            |        688 |        688 |        0 |        0.0 |
|            |                          |                             | .bss              |      67102 |      67102 |        0 |        0.0 |
|            |                          |                             | .bss_psram        |      30048 |      30048 |        0 |        0.0 |
|            |                          |                             | .comment          |         48 |         48 |        0 |        0.0 |
|            |                          |                             | .data             |       4048 |       4048 |        0 |        0.0 |
|            |                          |                             | .debug_abbrev     |    1529020 |    1529020 |        0 |        0.0 |
|            |                          |                             | .debug_aranges    |     132568 |     132568 |        0 |        0.0 |
|            |                          |                             | .debug_frame      |     486468 |     486468 |        0 |        0.0 |
|            |                          |                             | .debug_info       |   39187066 |   39187067 |        1 |        0.0 |
|            |                          |                             | .debug_line       |    5149996 |    5149996 |        0 |        0.0 |
|            |                          |                             | .debug_loc        |    3381237 |    3381237 |        0 |        0.0 |
|            |                          |                             | .debug_ranges     |     363808 |     363808 |        0 |        0.0 |
|            |                          |                             | .debug_str        |    3480446 |    3480446 |        0 |        0.0 |
|            |                          |                             | .hbn              |        509 |        509 |        0 |        0.0 |
|            |                          |                             | .hbn_noinit       |        260 |        260 |        0 |        0.0 |
|            |                          |                             | .init             |        342 |        342 |        0 |        0.0 |
|            |                          |                             | .init_array       |        144 |        144 |        0 |        0.0 |
|            |                          |                             | .psram            |          0 |          0 |        0 |        0.0 |
|            |                          |                             | .riscv.attributes |         47 |         47 |        0 |        0.0 |
|            |                          |                             | .rodata           |     116352 |     116352 |        0 |        0.0 |
|            |                          |                             | .rsvd             |       3188 |       3188 |        0 |        0.0 |
|            |                          |                             | .shstrtab         |        293 |        293 |        0 |        0.0 |
|            |                          |                             | .stack            |       2048 |       2048 |        0 |        0.0 |
|            |                          |                             | .strtab           |     569095 |     569095 |        0 |        0.0 |
|            |                          |                             | .symtab           |     172176 |     172176 |        0 |        0.0 |
|            |                          |                             | .tcm_data         |         36 |         36 |        0 |        0.0 |
|            |                          |                             | .tcmcode          |       3262 |       3262 |        0 |        0.0 |
|            |                          |                             | .text             |          0 |          0 |        0 |        0.0 |
|            |                          |                             |                   |     956734 |     956736 |        2 |        0.0 |
|            |                          | bl702+rpc                   | (read only)       |       3262 |       3262 |        0 |        0.0 |
|            |                          |                             | (read/write)      |    1284651 |    1284651 |        0 |        0.0 |
|            |                          |                             | .bleromro         |       6296 |       6296 |        0 |        0.0 |
|            |                          |                             | .bleromrw         |        124 |        124 |        0 |        0.0 |
|            |                          |                             | .boot2            |        688 |        688 |        0 |        0.0 |
|            |                          |                             | .bss              |      75118 |      75118 |        0 |        0.0 |
|            |                          |                             | .bss_psram        |      30304 |      30304 |        0 |        0.0 |
|            |                          |                             | .comment          |         48 |         48 |        0 |        0.0 |
|            |                          |                             | .data             |       4576 |       4576 |        0 |        0.0 |
|            |                          |                             | .debug_abbrev     |    1676352 |    1676352 |        0 |        0.0 |
|            |                          |                             | .debug_aranges    |     140688 |     140688 |        0 |        0.0 |
|            |                          |                             | .debug_frame      |     513888 |     513888 |        0 |        0.0 |
|            |                          |                             | .debug_info       |   43479486 |   43479487 |        1 |        0.0 |
|            |                          |                             | .debug_line       |    5539445 |    5539445 |        0 |        0.0 |
|            |                          |                             | .debug_loc        |    3575958 |    3575958 |        0 |        0.0 |
|            |                          |                             | .debug_ranges     |     387344 |     387344 |        0 |        0.0 |
|            |                          |                             | .debug_str        |    3882844 |    3882844 |        0 |        0.0 |
|            |                          |                             | .hbn              |        509 |        509 |        0 |        0.0 |
|            |                          |                             | .hbn_noinit       |        260 |        260 |        0 |        0.0 |
|            |                          |                             | .init             |        342 |        342 |        0 |        0.0 |
|            |                          |                             | .init_array       |        160 |        160 |        0 |        0.0 |
|            |                          |                             | .psram            |          0 |          0 |        0 |        0.0 |
|            |                          |                             | .riscv.attributes |         47 |         47 |        0 |        0.0 |
|            |                          |                             | .rodata           |     130112 |     130112 |        0 |        0.0 |
|            |                          |                             | .rsvd             |       3188 |       3188 |        0 |        0.0 |
|            |                          |                             | .shstrtab         |        293 |        293 |        0 |        0.0 |
|            |                          |                             | .stack            |       2048 |       2048 |        0 |        0.0 |
|            |                          |                             | .strtab           |     629379 |     629379 |        0 |        0.0 |
|            |                          |                             | .symtab           |     190352 |     190352 |        0 |        0.0 |
|            |                          |                             | .tcm_data         |         36 |         36 |        0 |        0.0 |
|            |                          |                             | .tcmcode          |       3262 |       3262 |        0 |        0.0 |
|            |                          |                             | .text             |          0 |          0 |        0 |        0.0 |
|            |                          |                             |                   |    1030716 |    1030718 |        2 |        0.0 |
| k32w       | contact                  | k32w0+release               | (read/write)      |     662652 |     662652 |        0 |        0.0 |
|            |                          |                             | .bss              |      77032 |      77032 |        0 |        0.0 |
|            |                          |                             | .data             |       2104 |       2104 |        0 |        0.0 |
|            |                          |                             | .text             |     564404 |     564404 |        0 |        0.0 |
|            | light                    | k32w0+release               | (read/write)      |     673216 |     673216 |        0 |        0.0 |
|            |                          |                             | .bss              |      74824 |      74824 |        0 |        0.0 |
|            |                          |                             | .data             |       2060 |       2060 |        0 |        0.0 |
|            |                          |                             | .text             |     593604 |     593604 |        0 |        0.0 |
|            | lock                     | k32w0+release               | (read/write)      |     634188 |     634188 |        0 |        0.0 |
|            |                          |                             | .bss              |      75584 |      75584 |        0 |        0.0 |
|            |                          |                             | .data             |       2080 |       2080 |        0 |        0.0 |
|            |                          |                             | .text             |     553796 |     553796 |        0 |        0.0 |
| linux      | chip-tool-ipv6only       | arm64                       | (read only)       |   10582156 |   10583900 |     1744 |        0.0 |
|            |                          |                             | (read/write)      |     691560 |     691560 |        0 |        0.0 |
|            |                          |                             | .bss              |      33912 |      33912 |        0 |        0.0 |
|            |                          |                             | .data             |       2768 |       2768 |        0 |        0.0 |
|            |                          |                             | .data.rel.ro      |     636008 |     636008 |        0 |        0.0 |
|            |                          |                             | .dynamic          |        560 |        560 |        0 |        0.0 |
|            |                          |                             | .got              |      13824 |      13824 |        0 |        0.0 |
|            |                          |                             | .init             |         24 |         24 |        0 |        0.0 |
|            |                          |                             | .init_array       |        200 |        200 |        0 |        0.0 |
|            |                          |                             | .rodata           |     535068 |     535180 |      112 |        0.0 |
|            |                          |                             | .text             |    8412356 |    8413988 |     1632 |        0.0 |
|            | thermostat-no-ble        | arm64                       | (read only)       |    2477308 |    2477308 |        0 |        0.0 |
|            |                          |                             | (read/write)      |     144936 |     144936 |        0 |        0.0 |
|            |                          |                             | .bss              |      55336 |      55336 |        0 |        0.0 |
|            |                          |                             | .data             |       1816 |       1816 |        0 |        0.0 |
|            |                          |                             | .data.rel.ro      |      78568 |      78568 |        0 |        0.0 |
|            |                          |                             | .dynamic          |        560 |        560 |        0 |        0.0 |
|            |                          |                             | .got              |       5184 |       5184 |        0 |        0.0 |
|            |                          |                             | .init             |         24 |         24 |        0 |        0.0 |
|            |                          |                             | .init_array       |        432 |        432 |        0 |        0.0 |
|            |                          |                             | .rodata           |     149416 |     149416 |        0 |        0.0 |
|            |                          |                             | .text             |    2067456 |    2067456 |        0 |        0.0 |
| mbed       | lock-app                 | CY8CPROTO_062_4343W+release | (read only)       |       6224 |       6224 |        0 |        0.0 |
|            |                          |                             | (read/write)      |    2463616 |    2463616 |        0 |        0.0 |
|            |                          |                             | .bss              |     214932 |     214932 |        0 |        0.0 |
|            |                          |                             | .data             |       5872 |       5872 |        0 |        0.0 |
|            |                          |                             | .text             |    1426260 |    1426260 |        0 |        0.0 |
| nrfconnect | all-clusters-app         | nrf52840dk_nrf52840         | (read/write)      |    1190807 |    1190807 |        0 |        0.0 |
|            |                          |                             | bss               |     145205 |     145205 |        0 |        0.0 |
|            |                          |                             | rodata            |     144460 |     144460 |        0 |        0.0 |
|            |                          |                             | text              |     820026 |     820026 |        0 |        0.0 |
|            |                          | nrf7002dk_nrf5340_cpuapp    | (read/write)      |    1361070 |    1361070 |        0 |        0.0 |
|            |                          |                             | bss               |     105144 |     105144 |        0 |        0.0 |
|            |                          |                             | rodata            |     211556 |     211556 |        0 |        0.0 |
|            |                          |                             | text              |     759866 |     759862 |       -4 |       -0.0 |
|            | all-clusters-minimal-app | nrf52840dk_nrf52840         | (read/write)      |    1136467 |    1136467 |        0 |        0.0 |
|            |                          |                             | bss               |     144440 |     144440 |        0 |        0.0 |
|            |                          |                             | rodata            |     120776 |     120776 |        0 |        0.0 |
|            |                          |                             | text              |     790194 |     790194 |        0 |        0.0 |
| qpg        | lighting-app             | qpg6105+debug               | (read/write)      |    1151180 |    1151180 |        0 |        0.0 |
|            |                          |                             | .bss              |     100348 |     100348 |        0 |        0.0 |
|            |                          |                             | .data             |        840 |        840 |        0 |        0.0 |
|            |                          |                             | .text             |     598280 |     598280 |        0 |        0.0 |
|            | lock-app                 | qpg6105+debug               | (read/write)      |    1117476 |    1117476 |        0 |        0.0 |
|            |                          |                             | .bss              |      95828 |      95828 |        0 |        0.0 |
|            |                          |                             | .data             |        836 |        836 |        0 |        0.0 |
|            |                          |                             | .text             |     564572 |     564572 |        0 |        0.0 |
| telink     | all-clusters-app         | tlsr9518adk80d              | (read only)       |          4 |          4 |        0 |        0.0 |
|            |                          |                             | (read/write)      |    1071336 |    1071328 |       -8 |       -0.0 |
|            |                          |                             | bss               |      98856 |      98856 |        0 |        0.0 |
|            |                          |                             | text              |     726146 |     726142 |       -4 |       -0.0 |
|            | all-clusters-minimal-app | tlsr9518adk80d              | (read only)       |          4 |          4 |        0 |        0.0 |
|            |                          |                             | (read/write)      |    1010636 |    1010636 |        0 |        0.0 |
|            |                          |                             | bss               |      98080 |      98080 |        0 |        0.0 |
|            |                          |                             | text              |     691308 |     691306 |       -2 |       -0.0 |
|            | light-switch-app         | tlsr9518adk80d              | (read only)       |          4 |          4 |        0 |        0.0 |
|            |                          |                             | (read/write)      |     932092 |     932100 |        8 |        0.0 |
|            |                          |                             | bss               |      90320 |      90320 |        0 |        0.0 |
|            |                          |                             | text              |     637928 |     637932 |        4 |        0.0 |
|            | lighting-app             | tlsr9518adk80d              | (read only)       |          4 |          4 |        0 |        0.0 |
|            |                          |                             | (read/write)      |    1010068 |    1010068 |        0 |        0.0 |
|            |                          |                             | bss               |      98380 |      98380 |        0 |        0.0 |
|            |                          |                             | text              |     703708 |     703708 |        0 |        0.0 |
|            | ota-requestor-app        | tlsr9518adk80d              | (read only)       |          4 |          4 |        0 |        0.0 |
|            |                          |                             | (read/write)      |     945688 |     945688 |        0 |        0.0 |
|            |                          |                             | bss               |      91276 |      91276 |        0 |        0.0 |
|            |                          |                             | text              |     649184 |     649188 |        4 |        0.0 |
|            | thermostat               | tlsr9518adk80d              | (read only)       |          4 |          4 |        0 |        0.0 |
|            |                          |                             | (read/write)      |     935232 |     935232 |        0 |        0.0 |
|            |                          |                             | bss               |      91712 |      91712 |        0 |        0.0 |
|            |                          |                             | text              |     638612 |     638616 |        4 |        0.0 |

</details>

_Originally posted by @github-actions[bot] in https://github.com/project-chip/connectedhomeip/issues/24097#issuecomment-1353550788_

**Comment by bzbarsky-apple** [comment]
Not actionable as filed.
