### ISSUE TITLE
Error compiling on raspberry pi

### ISSUE THREAD

**Issue by shun-dgut** [project-chip/connectedhomeip#24467]
### Reproduction steps

follow this guide
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md#installing-prerequisites-on-linux
An error occurred
![image](https://user-images.githubusercontent.com/31812214/212878077-98f17aeb-b845-433f-98f0-3245b49d5d49.png)

### Bug prevalence

always

### GitHub hash of the SDK that was being used

bd94d060c3656

### Platform

raspi

**Comment by anoop18pant** [comment]
The reason for above bug is that your submodules are not cloned correctly. Please check the thirdparty/nlfaultinjection/repo will be blank.

try to clone again.

Best of luck

**Comment by shun-dgut** [comment]
> The reason for above bug is that your submodules are not cloned correctly. Please check the thirdparty/nlfaultinjection/repo will be blank.
> 
> try to clone again.
> 
> Best of luck

I've tried updating submodules, but still no files.

![image](https://user-images.githubusercontent.com/31812214/215250972-28d6d222-fc42-4431-8f64-fa38880daad1.png)
