### ISSUE TITLE
[XML] Update Ethernet Network Diagnostics Cluster XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#24464]
### Reproduction steps

The data types names has been updated in Ethernet Network Diagnostics Cluster and must be updated in the XML as well.

PHYRate -> PHYRateEnum

### Bug prevalence

N/A

### GitHub hash of the SDK that was being used

N/A

### Platform

other

### Platform Version(s)

N/A

**Comment by bzbarsky-apple** [comment]
Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6161 (already merged).
