### ISSUE TITLE
Decide whether Python APIs should preserve acronyms (in some names?)

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#24486]
We have enum items named things like "OK" which turn into "kOk" in the python APIs (so we get `Enums.NodeOperationalCertStatusEnum.kOk`). Should this be "kOK"? What about other acronyms (ACL, USB, URL) that currently end up getting turned in Acl, Usb, Url, respectively?

Need to decide what this API surface should look like.

@tehampson @mrjerryjohns @tcarmelveilleux @yunhanw-google @yufengwangca

**Comment by yunhanw-google** [comment]
https://docs.python.org/3/library/enum.html#creating-an-enum
it seems the official prefers the uppercase without k

**Comment by bzbarsky-apple** [comment]
I suspect the "k" was carried over from C++, where it was added because some enum names (incorrectly) started with a number.  I'm pretty sure at this point all enums don't do that.
