### ISSUE TITLE
How get the list of attributes in a cluster

### ISSUE THREAD

**Issue by LucaFagan** [project-chip/connectedhomeip#24519]
### Feature description

I'm using readAttributePartsListWithCompletionHandler to get the EndPoint list and readAttributeServerListWithCompletion to get all clusters in each EndPoint.
How can I get the list of attributes in a cluster ?

### Platform

darwin

### Platform Version(s)

1.0

**Comment by bzbarsky-apple** [comment]
`readAttributeAttributeListWithCompletion`
