### ISSUE TITLE
[Bug] ZAP not outputting .matter file

### ISSUE THREAD

**Issue by step0035** [project-chip/connectedhomeip#24513]
### Reproduction steps / Feature

not sure if this is the correct way of generating a .matter file, here is the command that i ran.

```
python3 ./scripts/tools/zap/generate.py examples/all-clusters-app/all-clusters-common/all-clusters-app.zap -t src/app/zap-templates/matter-idl.json -o zzz_generated/all-clusters-app/zap-generated/
```

nothing was outputted to `zzz_generated/all-clusters-app/zap-generated/`

zap version: `v2023.01.09-nightly`

### Platform

other

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
The .matter file is copied over to `examples/all-clusters-app/all-clusters-common/all-clusters-app.matter` by the command listed above, no?  See https://github.com/project-chip/connectedhomeip/blob/8ad1073c4dd7d76b2ee89f86ce2f7c86865e7ae4/scripts/tools/zap/generate.py#L161-L177

**Comment by step0035** [comment]
verified it is copied to `examples/all-clusters-app/all-clusters-common/all-clusters-app.matter`, thanks
