### ISSUE TITLE
[BUG] Running 'ninja -C out/host' requires zap-cli

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#24537]
### Reproduction steps

1. cd to connectedhomeip
2. Run `gn gen  out/host `
3. Run `ninja -C out/host`

Note: Running on macOS

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

89c6fb677e9f02a0ee51f25a9636a60c070e7f3b

### Platform

darwin

### Platform Version(s)

N/A

### Anything else?

The issue started to occur in this [PR](https://github.com/project-chip/connectedhomeip/pull/23962).

**Comment by bzbarsky-apple** [comment]
This is expected behavior...  What's not expected is xcodebuild needing zap-cli.
