### ISSUE TITLE
[SQA] BRBINFO Write Attributes are Not-implemented in Chip-tool

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#24550]
**Issue**:
      For BRBINFO Attributes (except node-label ) are not implemented for write command in the latest commit : b4c2827465b0b36caa231fa8d055ce128194db00 in the master branch
   

**Step to reproduce** : `./chip-tool bridgeddevicebasic write vendor-name sample 1 3`

**Execpted outcome:** 

> [1656495259.991989][2164:2169] CHIP:TOO: Response Failure: IM Error 0x00000588: General error: 0x88 (UNSUPPORTED_WRITE)

**Actual outcome:**

> [1674219827.099381][48451:48451] CHIP:TOO: Unknown attribute: vendor-name
Usage:
  ./chip-tool bridgeddevicebasic write attribute-name [param1 param2 ...]

  +-------------------------------------------------------------------------------------+
  | Attributes:                                                                         |
  +-------------------------------------------------------------------------------------+
  | * node-label                                                                        |
  +-------------------------------------------------------------------------------------+
[1674219827.099615][48451:48451] CHIP:TOO: Run command failure: ../../commands/common/Commands.cpp:138: Error 0x0000002F

Note: Execpted outcome for these attributes are "UNSUPPORTED_WRITE" ,if it is an Test-plan error please transfer this issue to test-plan repo.

**Comment by bzbarsky-apple** [comment]
chip-tool by default only exposes `write` for attributes that are writable.  If you want to write to non-writable attributes, use `write-by-id`.
