### ISSUE TITLE
[Feature] Create chip tool command to verify if a device is commissioned

### ISSUE THREAD

**Issue by ccruzagralopes** [project-chip/connectedhomeip#24648]
### Feature description

Create a chip tool command to verify if a device with a specific `node_id` is commissioned or not.

Command suggestion:
```
$ ./chip-tool pairing is-commissioned <node_id>
```

Returns true if the device is already commissioned in the fabric and false otherwise.

Suggestion for the return:
```
CHIP:TOO:   Is commissioned: true
```

### Platform

all

**Comment by bzbarsky-apple** [comment]
@ccruzagralopes How would chip-tool determine this, exactly?  That is, what definition of "commissioned" do you want to use here?  Just "operational advertisement is present"?  Or "can set up CASE session"?  Or something else?

**Comment by ccruzagralopes** [comment]
> @ccruzagralopes How would chip-tool determine this, exactly? That is, what definition of "commissioned" do you want to use here? Just "operational advertisement is present"? Or "can set up CASE session"? Or something else?

I want to know if the node already has a CASE session or not

**Comment by bzbarsky-apple** [comment]
If chip-tool is not in interactive mode, the answer is "it does not".

If chip-tool is in interactive mode, you can know whether chip-tool has a session id for the node, but you can't know whether the node knows about that session.  That is, sending messages on that session can still fail.  But we could expose API for this, yes.  Would you want to include a sessions marked "defunct" in this check, or just active ones?

And how would this get used in practice?

**Comment by ccruzagralopes** [comment]
This would get used in Test Harness. We'd like to commission the device before running a test case, but only if it's not already commissioned. So we need this check first.

I'm not familiar with interactive mode. I don't believe that's used in Test Harness. Are you saying that if we don't use interactive mode, then it's not possible to know about the CASE session?

**Comment by ccruzagralopes** [comment]
Someone just told me that I can use the command `chip-tool delay wait-for-commissionee <nodeID>` for what I need, so I'm closing this issue. Thank you

**Comment by bzbarsky-apple** [comment]
Ah.  That command establishes a CASE session to the node, so a different definition of "commissioned" from the above....
