### ISSUE TITLE
[BUG] onnetwork commissioning doesn't add network to networks list

### ISSUE THREAD

**Issue by pankore** [project-chip/connectedhomeip#24684]
### Reproduction steps

Connect wifi device to the same wifi network as the commissioner beforehand
Commission the device using onnetwork pairing
`./chip-tool pairing onnetwork 1 20202021`
Read the networks list, it should show 0 entries
`./chip-tool networkcommissioning read networks 1 0`

- Controller/commissioner has no way to get the wifi password
- `AddOrUpdateWiFiNetwork` is not called
- The wifi network is not added to the networks list, this also results in `CommitConfiguration` storing an empty `mStagingNetwork` and the wifi is not persisted in kvs for Ameba platform

Is this an expected behaviour? Should platform code implement adding the network or should it be the controller's job? If it is controller's job, how would the wifi password be known to the controller? 

### Bug prevalence

always

### GitHub hash of the SDK that was being used

bdefbcb39b115f7be9c30df9e106ac9302f49033

### Platform

ameba, other

**Comment by bzbarsky-apple** [comment]
If a device is placed on the network through non-Matter means, then either the network should not appear in the networks list, or whatever did the placing on the network should explicitly add the network there.

The first of those is argued for by this part of the spec:

> The order of list items SHALL only be modified by the AddOrUpdateThreadNetwork, AddOrUpdateWiFiNetwork and ReorderNetwork commands. In other words, the list SHALL be stable over time, unless mutated externally.

but the spec does have provisions for the Ethernet version of the network commissioning cluster to automatically populate the list with the one entry....

So really, this needs to be raised as a spec issue to clarify behavior.

**Comment by ksperling-apple** [comment]
To my reading that spec paragraph simply talks about the fact that the list *order* reflects configuration precedence and doesn't change by itself (e.g. when the primary network is unavailable and the device falls back to the secondary network).

**Comment by pankore** [comment]
closing issue, onnetwork devices should not have network commissioning cluster
