### ISSUE TITLE
[examples/tv-casting-apapp/darwin] Build iOS tv-casting-app as part of CI

### ISSUE THREAD

**Issue by sharadb-amazon** [project-chip/connectedhomeip#24736]
### Reproduction steps / Feature

The iOS tv-casting-app located here: https://github.com/project-chip/connectedhomeip/tree/master/examples/tv-casting-app/darwin should be built as part of the Matter CI.

### Platform

darwin

### Type

Manually tested with SDK

**Comment by woody-apple** [comment]
Closing as this looks complete.
