### ISSUE TITLE
[TC-ACE-1.2] The result of executing the test command is timeout in TH2

### ISSUE THREAD

**Issue by lisaaaas** [project-chip/connectedhomeip#24746]
### Reproduction steps

Test Case ID

[TC-ACE-1.2] Subscriptions
Describe Issue:
Step 3：Expected Outcome is save SubscriptionId as subscription_noc，But my execution result is timeout
![image](https://user-images.githubusercontent.com/45091319/215634235-dcb38778-e2a7-4298-afc1-c0459d3bacc1.png)
I am not sure why I operate on node 2 in interactive mode. I would like to know whether there are preconditions for executing test case TC-ACE-1.2

### Bug prevalence

many times

### GitHub hash of the SDK that was being used

esp-idf

### Platform

esp32

### Platform Version(s)

1.0.1

### Type

Test Improvement

**Comment by bzbarsky-apple** [comment]
Those steps make no sense: as you note, node 2 is wrong.

Please report this bug in the test plan repo, since that's where verification step issues are tracked.
