### ISSUE TITLE
[BUG] dynamic-bridge-app: Aggregator PartList attribute empty

### ISSUE THREAD

**Issue by raven-worx** [project-chip/connectedhomeip#24783]
### Reproduction steps

Inspecting my custom bridge (based on dynamic-bridge-app) i noticed that the Aggregator (EP 1) Endpoint's PartList attribute is empty, instead of being filled with the available bridged device node endpoints. Only the Root Nodes PartList attribute is filled.

According to the Core Spec (9.12.2):
> Additionally, it SHALL expose an endpoint with the device type Aggregator which has a Descriptor
cluster with a PartsList attribute containing all the endpoints representing those Bridged
Devices. See Endpoint Composition for the concept of hierarchical composition.

It seems Google Home doesn't mind this and displays my endpoints, whereas Apple Home doesn't like it and displays no endpoints at all.

**Edit**:
if i see this correct, there should also be a special handling for the Endpoint ID 1 (if its a Aggregator node):
https://github.com/project-chip/connectedhomeip/blob/7195bd81ec4f4d7b1a2d769da3542961b82675d1/src/app/clusters/descriptor/descriptor.cpp#L58-L80

But this wont be the best solution afterall i guess, since there can be multiple Aggregator nodes, for logical grouping.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

43dd327f1cf497cdf8c90dfb2e481dd567abfaa9

### Platform

core

### Platform Version(s)

1.0.0.2

**Comment by bzbarsky-apple** [comment]
The "special handling" needs to be in the example dynamic-bridge-app.  It should be setting up its endpoints with the aggregator as the parent, and it's not.

In particular, in `AddDeviceEndpoint` it does:
```
                ret =
                    emberAfSetDynamicEndpoint(index, gCurrentEndpointId, dev->endpointType(), dev->versions(), dev->deviceTypes());
```

where the function is declared as:
```
EmberAfStatus emberAfSetDynamicEndpoint(uint16_t index, chip::EndpointId id, const EmberAfEndpointType * ep,
                                        const chip::Span<chip::DataVersion> & dataVersionStorage,
                                        chip::Span<const EmberAfDeviceType> deviceTypeList = {},
                                        chip::EndpointId parentEndpointId                  = chip::kInvalidEndpointId);
```

Note the lack of `parentEndpointId` at the callsite.

**Comment by bzbarsky-apple** [comment]
@andy31415 could you please assign to @dnicoara?

**Comment by bzbarsky-apple** [comment]
dynamic-bridge is gone.
