### ISSUE TITLE
SHA for iOS/iPadOS/tvOS 16.3

### ISSUE THREAD

**Issue by samleemc** [project-chip/connectedhomeip#24803]
### Documentation issues

https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md

Can we please have the SHA for iOS 16.3 please? It is been publicly available and Apple has shutdown the certification for 16.2.

### Platform

darwin

### Anything else?

https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md

**Comment by bzbarsky-apple** [comment]
@samleemc PR up to update the docs.  It's the same SHA as for 16.2.
