### ISSUE TITLE
[TE 1.1] [TC-PS-3.1] Missing attributes in PS PowerSource Cluster

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#24893]
### Problem
When executing TC-PS-3.1 for TE1.1 using the cert-tool, the following attributes are returned with status `UNSUPPORTED_ATTRIBUTE` when attempting a read on them from `chip-tool` using the `chip-all-clusters-app`:
1. `active-wired-faults`
2. `bat-voltage`
3. `bat-percent-remaining`
4. `bat-time-remaining`
5. `bat-present`
6. `active-bat-faults`
7. `bat-replacement-description`
8. `bat-common-designation`
9. `bat-ansidesignation`
10. `bat-iecdesignation`
11. `bat-approved-chemistry`
12. `bat-capacity`
13. `bat-quantity`
14. `bat-charge-state`
15. `bat-time-to-full-charge`
16. `bat-functional-while-charging`
17. `bat-charging-current`
18. `active-bat-charge-faults`

### Proposed Fix

Implement the attributes in all-clusters-app OR don't require it in the test execution steps for TC-PS-3.1 for TE1.1. The test plan template is [a generic template ](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/powersource.adoc#331-tc-ps-31-attributes-with-client-as-dut) so it's unclear if PICS should be here to prevent all of these from needing to be run.

### Setup
connectedhomeip: `7e69c66bb44c91fe0b9bed7c7b8d272d3208c8dd`
Client: `chip-tool`
Server: `chip-all-clusters-app`

chip-certification-tool: Version: `v2.7-official-TE`, Sha: `821e3f8`

**Comment by cjandhyala** [comment]
closing the ticket per conversation with @liamgonyea.
