### ISSUE TITLE
Create the generic IM write API in JAVA/JNI layer

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#24930]

**Comment by jagadeesh-ayla** [comment]
@yunhanw-google is there a way we can write path/attributePath without creating Cluster instance? 
in chip device controller we have read/subscribe APIs but no write API.

**Comment by yunhanw-google** [comment]
we have merged this generic write api in java matter controller now. @jagadeesh-ayla 
thanks

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/25445
