### ISSUE TITLE
[Android] 'pairing on-network' should use DNS based pair to align with chip-tool implementation.

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#24938]
### Reproduction steps

Currently pairing on-network also use pairDeviceWithAddress in which local host address is used, this is wrong, that is why I am only able to use 'pairing on-network' to pair a device on the same host, but not the device within the same network. I think we need to use DNS based pair to align with chip-tool implementation.

### Platform

android

### Type

CI tested

**Comment by Steven1937** [comment]
Hi, how did you get the ".so" lib files?
