### ISSUE TITLE
[Feature] using the android phone to send group command

### ISSUE THREAD

**Issue by eling22** [project-chip/connectedhomeip#24934]
### Feature description

I was recently using a chip-tool and noticed a feature called "group control." 
I success to bind a group and use switch to control the group, but I can't find a way to use phone direct send group message to the group, like following reference.
https://github.com/project-chip/connectedhomeip/tree/master/examples/chip-tool#using-the-client-to-send-group-multicast-matter-commands
I was wondering if this feature is available in Android as well. If it is, could you please direct me to where I can find it? If not, I would like to suggest that you consider adding this feature to the Android platform.

### Platform

android

### Platform Version(s)

v1.0.0

**Comment by yunhanw-google** [comment]
yes, we currently don't have it, we need to add generic IM command in java/jni layer so that we can send out group command in android chip-tool, it would happen after I complete this https://github.com/project-chip/connectedhomeip/issues/24931

**Comment by yunhanw-google** [comment]
@eling22 we just complete the group feature in android chip-tool, please have the test. thanks

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/29244
