### ISSUE TITLE
.matter files should reflect codegen reality: mandatory global cluster list-typed attributes are always supported

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#24947]
ZAP codegen ignores the "included" state for mandatory global cluster attributes, since that's not a valid configuration.  So no matter what the .zap file says they are supported by servers.

It looks like .matter files reflect the contents of the .zap file for these attributes (at least based on what I am seeing in https://github.com/project-chip/connectedhomeip/pull/24937/files), not the actual reality that these are always supported.

**Comment by andy31415** [comment]
Do we have a list of what mandatory global attributes are always included so I can match this in the IDL logic?
I may need to do the same in xml parsing logic ...

Is there a code location where this decision is made or is it already set up in the XML definitions somehow?

**Comment by bzbarsky-apple** [comment]
The specific list of attributes involved here is:
```
  0xfff8, // GeneratedCommandList
  0xfff9, // AcceptedCommandList
  0xfffa, // EventList
  0xfffb, // AttributeList
```

On the server side, these are excluded from the metadata (because every cluster must have them) and the IM code special-cases them.  See https://github.com/project-chip/zap/blob/fd7e0bfbc72c3821053352730f02c75de229d969/src-electron/generator/helper-endpointconfig.js#L965 and its callsites in that file, and https://github.com/project-chip/connectedhomeip/blob/16a64b357293a9ef02c541ff743e3fabf057bc71/src/app/GlobalAttributes.h#L31 and its consumers.
