### ISSUE TITLE
Test harness setup

### ISSUE THREAD

**Issue by stefano055415** [project-chip/connectedhomeip#24943]
is there a guide on how to configure and use Test harness?

the repository [https://github.com/CHIP-Specifications/chip-certification-tool](https://github.com/CHIP-Specifications/chip-certification-tool) no longer exists

**Comment by bzbarsky-apple** [comment]
> the repository https://github.com/CHIP-Specifications/chip-certification-tool no longer exists

It exists just fine, but you may not have permissions to view it...

**Comment by stefano055415** [comment]
@bzbarsky-apple 

ok, but do I have to ask for access via the csa portal?

**Comment by bzbarsky-apple** [comment]
@stefano055415 I think you should probably reach out to @clapre for access.
