### ISSUE TITLE
[BUG] TC-DA-1.7 PAI's AKID is wrong and PAA and signature is invalid

### ISSUE THREAD

**Issue by PSONALl** [project-chip/connectedhomeip#24972]
### Reproduction steps

- Tested on TE1.1 commit
- At step 4 - PAI's AKID matches a PAA and signature is valid fails 
- Logs 
       - DUT: [esp32.txt](https://github.com/project-chip/connectedhomeip/files/10707743/esp32.txt)
       - TH: [th.txt](https://github.com/project-chip/connectedhomeip/files/10707744/th.txt)

### Bug prevalence

EveryTime

### GitHub hash of the SDK that was being used

7e69c66bb44c91fe0b9bed7c7b8d272d3208c8dd

### Platform

esp32

**Comment by cjandhyala** [comment]
@PSONALl you should not be using the SDK default PAI for this test. you will need to generate PAA/PAI and use those on your product
