### ISSUE TITLE
[BUG]TC-CGEN-2.4 PASESession timed out at step 3

### ISSUE THREAD

**Issue by PSONALl** [project-chip/connectedhomeip#24970]
### Reproduction steps

- Tested on TE1.1 commit
- At step 3 - error recieved : PASESession timed out while waiting for a response from the peer
- Logs 
       - DUT: [esp32.txt](https://github.com/project-chip/connectedhomeip/files/10707670/esp32.txt)
       - TH: [th.txt](https://github.com/project-chip/connectedhomeip/files/10707671/th.txt)

### Bug prevalence

EveryTime

### GitHub hash of the SDK that was being used

7e69c66bb44c91fe0b9bed7c7b8d272d3208c8dd

### Platform

esp32

**Comment by adamb-q** [comment]
I'm also seeing this on qpg platform

**Comment by marius-alex-tache** [comment]
Also on k32w0.

**Comment by PSONALl** [comment]
I am still facing this issue on updated TH version

**Comment by PSONALl** [comment]
This is not an sdk issue, This is an issue with test harness, as the test passes with chip-tool
I have raised an issue on TH repo here: https://github.com/CHIP-Specifications/chip-certification-tool/issues/883
So closing this issue
