### ISSUE TITLE
[Darwin] Adopt MTR_DEPRECATED in zap templates

### ISSUE THREAD

**Issue by ksperling-apple** [project-chip/connectedhomeip#24994]
Adopt MTR_DEPRECATED instead of API_DEPRECATED in zap templates to handle cases where the old and new version of a renamed ObjC symbol import into Swift as the same name.

This is a follow-up to #24963

**Comment by bzbarsky-apple** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/25501
