### ISSUE TITLE
[XML] Update General Diagnostics Cluster XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#24998]
The data types names has been updated in General Diagnostics Cluster and must be updated in the XML as well.

**Updated**
NetworkInterface -> NetworkInterfaceStruct

Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6181 (already merged)

**Comment by bzbarsky-apple** [comment]
The spec change was undone in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6338.
