### ISSUE TITLE
Replace silab COUNTOF by equivalent method 

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#2499]
Replace silab COUNTOF by equivalent method

**Comment by bzbarsky-apple** [comment]
This is defined in the silabs SDK like so:
```
#define COUNTOF(a) (sizeof(a) / sizeof(a[0]))
```

@wehale @selissia OK to put that in `types_stub.h`?

**Comment by selissia** [comment]
> This is defined in the silabs SDK like so:
> 
> ```
> #define COUNTOF(a) (sizeof(a) / sizeof(a[0]))
> ```
> 
> @wehale @selissia OK to put that in `types_stub.h` in terms of licensing?

Yes.

**Comment by rwalker-apple** [comment]
as CHIP defines (and elsewhere uses) `ArraySize()`, prefer the fix uses that instead of COUNTOF()
