### ISSUE TITLE
[XML] Update Time Synchronization Cluster XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#25001]
The data types names has been updated in Time Synchronization Cluster and must be updated in the XML as well.

**Updated**
TimeZoneType -> TimeZoneStruct
DstOffsetType  -> DSTOffsetStruct

DstOffset -> DSTOffset (Attribute)

DstTableEmpty -> DSTTableEmpty (Event)
DstStatus -> DSTStatus (Event)

Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6212 (already merged)

**Comment by bzbarsky-apple** [comment]
Change missing from the above list: the `DstOffset` attribute got renamed to `DSTOffset`.

**Comment by bzbarsky-apple** [comment]
And some of the events got renamed, but the SDK does not contain those so far anyway.

**Comment by ReneJosefsen** [comment]
You are right, I was so focused on the data types that I completely forgot the impact of the Dst to DST change. I have updated the description.
