### ISSUE TITLE
Replace silab emberEventControlSet (DelayMS/Inactive...) methods with equivalent

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#2503]
Reimplement following methods:
emberEventControlSetDelayMS
emberEventControlSetInactive

**Comment by bzbarsky-apple** [comment]
We added stubs for these in #2429 and I think https://github.com/project-chip/connectedhomeip/issues/1944 and https://github.com/project-chip/connectedhomeip/issues/658 and https://github.com/project-chip/connectedhomeip/issues/2431 are relevant here in terms of tracking stuff.

**Comment by vivien-apple** [comment]
This has been done in #2915.
