### ISSUE TITLE
[BUG] Android CHIPTool crashes when running the readLocal Temperature command for a thermostat cluster.

### ISSUE THREAD

**Issue by HirokiOgawa1129** [project-chip/connectedhomeip#25033]
### Reproduction steps

1.Press the PROVISION CHIP DEVICE WITH THREAD button in the CHIPTool app to commission the thermostat device.
2.Press the CLUSTER INTERACTION TOOL button on the CHIPTool app to transition to the screen for accessing the thermostat cluster.
3.Execute the following command.
![コマンド送信画面](https://user-images.githubusercontent.com/33824269/218600352-e3a7473d-fd94-4b49-a7d8-db3ee6b3d21a.png)
4.An error occurs as below.
![エラー画面](https://user-images.githubusercontent.com/33824269/218600546-a9ec8a4e-2008-43d1-809f-6ee11d2d8c33.png)

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/tree/master/examples/android/CHIPTool

### Platform

android

### Platform Version(s)

Android ver 13

### Anything else?

The app also crashes when I run WriteOccupiedCoolingSetpoint .

**Comment by joonhaengHeo** [comment]
This issue appears to be caused by missing some Cluster Callback classes when create ClusterInfo.java using ZAP.

**Comment by yunhanw-google** [comment]
@joonhaengHeo we miss some generated cluster callback? or this issue is caused by new cluster with missing generated things?

**Comment by joonhaengHeo** [comment]
@yunhanw-google 
https://github.com/project-chip/connectedhomeip/blob/83dd188990e57ab141e2a07672ca55e0962367c5/src/controller/java/zap-generated/chip/devicecontroller/ClusterReadMapping.java#L10179

It seems that an issue occurred in the line above. This is where the Java Type Casting Exception occurs, and some ZAP files need to be modified.

The ZAP file has been modified and the commit has been uploaded. #25098
