### ISSUE TITLE
Use separate transitions for hue and saturation in color control

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#25040]
Right now, a move on the hue will terminate an in-progress move on the saturation, and vice versa.

This is pretty unfortunate, from a client's point of view, and has no basis in the spec as far as I can tell.  We should probably consider just doing separate transitions for the two (but allow the MoveToHueAndSaturation/etc commands to combine into a single transition).  

One possible approach: we could support doing up to two transitions per endpoint, where each transition is transitioning hue, or saturation, or both.  When a new transition wants to start, there are three cases:

1. It wants to transition both; cancel any existing transitions.
2. It wants to transition hue only.  Cancel any existing hue-only transition, convert any existing hue-and-saturation transition to saturation-only.
3. It wants to transition saturation only.  Cancel any existing saturation-only transition, convert any existing hue-and-saturation transition to hue-only.

@jmartinez-silabs thoughts?

**Comment by jmartinez-silabs** [comment]
@bzbarsky-apple I agree, separating the two gives a better user experience and more flexibility and I don't see any cons either. It is fairly straightforward to implement. 

Note that hue and enhanced hue will be grouped together has the same transition.

**Comment by bzbarsky-apple** [comment]
Yep, there's only one hue to transition, so enhanced hue and hue have to use the same thing.
