### ISSUE TITLE
Do not ignore real-life IPv6 RouteAdvertisements with lifetime over 12.42 days

### ISSUE THREAD

**Issue by HomeACcessoryKid** [project-chip/connectedhomeip#25058]
The MasterBranch has this line of code that will ignore the long lived routes.
https://github.com/project-chip/connectedhomeip/blob/6ce0f901b50948280baaf56cb1778b58708e0eb2/src/platform/ESP32/route_hook/ESP32RouteTable.c#L68

In real life, there are valid RAs with e.g. 14 days or 30 days, as reported in the espressif GitHub issues. https://github.com/espressif/esp-matter/issues/217

To avoid problems, the timer concept needs to be expanded to cover these longer timeouts.
Just brainstorming, the `route_timeout_handler` could read the life_time attribute and we encode some knowledge how often to repeat the timer at maximum length before actually removing the entry.

**Comment by bzbarsky-apple** [comment]
@shubhamdp @dhrishi
