### ISSUE TITLE
Silabs lock-app does something weird with credentials in LockManager::SetUser

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#25082]
It's overriding the type and index of the passed-in credentials with other values, which looks wrong to me. At the very least it needs a comment explaining why it's doing that and why that's not a spec violation.

This applies to both the efr32 and the SiWx917 versions of lock-app.

@mykrupp @jmartinez-silabs

**Comment by jmartinez-silabs** [comment]
pr mentioned above fixed this ticket a while back.
