### ISSUE TITLE
[1.0]  VerifyOrDie(gAddressPolicy != nullptr);

### ISSUE THREAD

**Issue by cyyyys** [project-chip/connectedhomeip#25102]
### Reproduction steps

The code has a problem in src/lib/dnssd/minimal_mdns/AddressPolicy.cpp.

line 30. 

VerifyOrDie(gAddressPolicy != nullptr);

Normal here gAddressPolicy should not equal nullptr.

But the value of gAddressPolicy is nullptr here, and the  program is stuck here.

So the bluetooth could not be found next...

### Bug prevalence

not a bug

### GitHub hash of the SDK that was being used

tag 1.0.0.2

### Platform

freeRTOS

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
@andy31415

**Comment by cyyyys** [comment]
I guess the cause of the problem is that some CPP files are not introduced in Make.defs.

**Comment by cyyyys** [comment]
![image](https://user-images.githubusercontent.com/39301000/219293653-71269218-dc5b-4826-a38e-8c122e880b6a.png)

**Comment by cyyyys** [comment]
The path of the select.h in my project is /usr/include/x86_64-linux-gnu/sys/select.h

**Comment by cyyyys** [comment]
I solved this problem.

in src/lib/dnssd/MinimalMdnsServer.cpp

open the CHIP_MINMDNS_DEFAULT_POLICY macro

**Comment by andy31415** [comment]
@cyyyys for future bug reports, please provide more context on things. Here it looks like you are using some custom compilation instructions and such info would be useful in the bug report.
