### ISSUE TITLE
[BUG] [Android] When scan QR Code, happen to crash 

### ISSUE THREAD

**Issue by jeonghwan7** [project-chip/connectedhomeip#25140]
### Reproduction steps

Android Chip Tool - Currently master branch 

When scan QR Code (PROVISION CHIP DEVICE WI-FI or PROVISION CHIP DEVICE THREAD) , The app meet the crash
Log is below.

`
02-17 08:21:11.778 D 27017    27017    AndroidRuntime:                                                          Shutting down VM 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          FATAL EXCEPTION: main 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          Process: com.google.chip.chiptool, PID: 27017 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          java.lang.IllegalStateException: Neither the parent Fragment null nor the host Activity null of BarcodeFragment implement Callback. 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at com.google.chip.chiptool.util.FragmentUtil.getHost(FragmentUtil.kt:49) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.handleScannedQrCode$lambda-10(BarcodeFragment.kt:205) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.lambda$KQ_xOxz0LBqlN0rG11wbU9zHO7E(Unknown Source:0) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at com.google.chip.chiptool.setuppayloadscanner.-$$Lambda$BarcodeFragment$KQ_xOxz0LBqlN0rG11wbU9zHO7E.run(Unknown Source:4) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at android.os.Handler.handleCallback(Handler.java:942) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at android.os.Handler.dispatchMessage(Handler.java:99) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at android.os.Looper.loopOnce(Looper.java:226) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at android.os.Looper.loop(Looper.java:313) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at android.app.ActivityThread.main(ActivityThread.java:8741) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at java.lang.reflect.Method.invoke(Native Method) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
02-17 08:21:11.779 E 27017    27017    AndroidRuntime:                                                          	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

`

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

5f058f9232cd7b050b98c6752302ac3282464e5b

### Platform

android

**Comment by joonhaengHeo** [comment]
Although we did not review it accurately, it is presumed that the PR below is the cause.
https://github.com/project-chip/connectedhomeip/pull/25063

It seems that this of getHost changed to a value other than BarcodeFragment due to the change in where startCamera is called in this PR modification. I uploaded a new PR on #25141 to solve the cause.
