### ISSUE TITLE
Sort out what should happen with the "identify" callbacks

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2516]
#### Problem
We have pulled in the "identify" cluster, but we still have three callbacks in `cluster-callback-stubs.c` for it; there should be none.

 #### Proposed Solution
The three callbacks are:
```
bool emberAfIdentifyClusterIdentifyQueryResponseCallback(uint16_t timeout);
bool emberAfPluginIdentifyStartFeedbackCallback(uint8_t endpoint, uint16_t identifyTime);
bool emberAfPluginIdentifyStopFeedbackCallback(uint8_t endpoint);
```

What we do with them....

* `emberAfIdentifyClusterIdentifyQueryResponseCallback` is implemented in the silabs PR in the `ezmode-commissioning` plug-in and in the `find-and-bind-initiator` plug-in.  Need to figure out how this maps into the CHIP world.

* `emberAfPluginIdentifyStartFeedbackCallback` and `emberAfPluginIdentifyStopFeedbackCallback` appear in a bunch of `callback-stub.c` files, which means the app can implement them.  But there's also an `identify-feedback` plug-in that implements them in the silabs PR.  The actual implementation there seems like it can toggle LEDs or use a buzzer depending on various ifdefs, and calls into the silabs HAL to do those things.

**Comment by bhaskar-apple** [comment]
After speaking to @bzbarsky-apple offline plan is as follows - 
1. Move `emberAfPluginIdentifyStartFeedbackCallback` and `emberAfPluginIdentifyStopFeedbackCallback` to `callback-stub.c`
2. `emberAfIdentifyClusterIdentifyQueryResponseCallback` leave this is as stubbed for now till we have a better plan around where the code for zcl client side lives.
