### ISSUE TITLE
[XML] Update Power Source Cluster XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#25181]
The data types names has been updated in Network Commissioning Cluster and must be updated in the XML as well.

**Updated**
WiredFault -> WiredFaultEnum
BatFault -> BatFaultEnum
BatChargeFault -> BatChargeFaultEnum
PowerSourceStatus -> PowerSourceStatusEnum

**Added**
WiredCurrentTypeEnum
BatChargeLevelEnum
BatReplaceabilityEnum
BatCommonDesignationEnum
BatApprovedChemistryEnum
BatChargeStateEnum

Not sure if this also requires change to the XML, but the names in BatApprovedChemistryEnum

Also, BatIECDesignation was used in attribute table, but BatIECType in description section, so in case XML uses BatIECType this needs to be updated as well.

Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6211 (already merged)

**Comment by bzbarsky-apple** [comment]
SDK did not have enums for BatApprovedChemistryEnum or BatApprovedChemistryEnum so the fact that names changed in BatApprovedChemistryEnum is not a problem.  And the SDK used BatIECDesignation, so we are good there.
