### ISSUE TITLE
Convert java matter controller test program from java version into kotlin version

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#25253]
Currently, java-matter-controller is written in Java, we have request from our internal team to convert it to kotlin to better align with our internal development and easy to integrate with our internal utility libs written in kotlin, such as TLV writter and reader, etc...

**Comment by yufengwangca** [comment]
Currently, java-matter-controller is written in Java, we have request from our internal team to convert it to kotlin to better align with our internal development and easy to integrate with our internal utility libs written in kotlin, such as TLV writter and reader, etc...
