### ISSUE TITLE
[XML] Update Thread Network Diagnostics Cluster XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#25339]
The data types names has been updated in Thread Network Diagnostics Cluster and must be updated in the XML as well.

**Updated**
NetworkFault -> NetworkFaultEnum

**Added**
- RoutingRoleEnum
- NeighborTableStruct
- RouteTableStruct
- SecurityPolicy (https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6338)
- OperationalDatasetComponents (https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6338)

Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6169 (already merged)

**Comment by bzbarsky-apple** [comment]
> SecurityPolicyStruct

This is actually called SecurityPolicy in the spec, after https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6338

> OperationalDatasetComponentsStruct

Likewise, it's OperationalDatasetComponents

**Comment by ReneJosefsen** [comment]
Yeah, I forgot to update these issues after we got the revert merged. Good catch, my mistake 😅
