### ISSUE TITLE
[BUG] build bridge-app error

### ISSUE THREAD

**Issue by XiaoCongWu** [project-chip/connectedhomeip#25387]
### Reproduction steps

I tried to compile the program for ARMv7l architecture, but encountered the following error.
【platform】
Raspberry Pi 4B ubuntu 22.10  32bit -Ubuntu SMP PREEMPT Wed Jan 18 11:51:38 UTC 2023 armv7l armv7l armv7l GNU/Linux

Reproduction steps
1、git submodule update --init
2、gn gen out/debug
Done. Made 227 targets from 201 files in 660ms
3、ninja -C out/debug

ninja: Entering directory `out/debug'
[11/714] ACTION //third_party/connectedhomeip/examples/bridge-app/bridge-common:bri...apgen_zap_pregen(//third_party/connectedhomeip/build/toolchain/linux:linux_arm_gcc
FAILED: gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/access.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/gen_config.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/endpoint_config.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/CHIPClientCallbacks.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/CHIPClusters.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/IMClusterCommandHandler.cpp 
python ../../third_party/connectedhomeip/third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../../third_party/connectedhomeip/examples/bridge-app/bridge-common --default-toolchain=//third_party/connectedhomeip/build/toolchain/linux:linux_arm_gcc --current-toolchain=//third_party/connectedhomeip/build/toolchain/linux:linux_arm_gcc --capture-output --python-dep-list-files gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/bridge-common_zapgen_zap_pregen_metadata_path_list.txt -- ../../third_party/connectedhomeip/scripts/tools/zap/generate.py --no-prettify-output --templates /home/ubuntu/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/src/app/zap-templates/app-templates.json --output-dir /home/ubuntu/connectedhomeip/examples/bridge-app/linux/out/debug/gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated --lock-file /home/ubuntu/connectedhomeip/examples/bridge-app/linux/out/debug/zap_gen.lock --parallel /home/ubuntu/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/examples/bridge-app/bridge-common/bridge-app.zap
Searching for zcl file from /home/ubuntu/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/examples/bridge-app/bridge-common/bridge-app.zap
FAILED TO EXECUTE ZAP GENERATION: No such file or directory - "zap-cli"
********************************************************************************
* You may need to install zap. Please ensure one of these applies:
* - `zap-cli` is in $PATH. Install from https://github.com/project-chip/zap/releases
*   see docs/guides/BUILDING.md for details
* - `zap-cli` is in $ZAP_INSTALL_PATH. Use this option if you
*   installed zap but do not want to update $PATH
* - Point $ZAP_DEVELOPMENT_PATH to your local copy of zap that you
*   develop on (to use a developer build of zap)
********************************************************************************
[15/714] cc obj/out/debug/gen/include/platform/Linux/dbus/bluez/bluez.DbusBluez.c.o

### Bug prevalence

every day

### GitHub hash of the SDK that was being used

eff5773

### Platform

raspi

### Platform Version(s)

22.10 armv7l GNU/Linux

### Anything else?

ninja: Entering directory `out/debug'
[11/714] ACTION //third_party/connectedhomeip/examples/bridge-app/bridge-common:bri...apgen_zap_pregen(//third_party/connectedhomeip/build/toolchain/linux:linux_arm_gcc
FAILED: gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/access.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/gen_config.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/endpoint_config.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/CHIPClientCallbacks.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/CHIPClusters.h gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated/IMClusterCommandHandler.cpp 
python ../../third_party/connectedhomeip/third_party/pigweed/repo/pw_build/py/pw_build/python_runner.py --gn-root ../../ --current-path ../../third_party/connectedhomeip/examples/bridge-app/bridge-common --default-toolchain=//third_party/connectedhomeip/build/toolchain/linux:linux_arm_gcc --current-toolchain=//third_party/connectedhomeip/build/toolchain/linux:linux_arm_gcc --capture-output --python-dep-list-files gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/bridge-common_zapgen_zap_pregen_metadata_path_list.txt -- ../../third_party/connectedhomeip/scripts/tools/zap/generate.py --no-prettify-output --templates /home/ubuntu/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/src/app/zap-templates/app-templates.json --output-dir /home/ubuntu/connectedhomeip/examples/bridge-app/linux/out/debug/gen/third_party/connectedhomeip/examples/bridge-app/bridge-common/zap_pregen/zap-generated --lock-file /home/ubuntu/connectedhomeip/examples/bridge-app/linux/out/debug/zap_gen.lock --parallel /home/ubuntu/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/examples/bridge-app/bridge-common/bridge-app.zap
Searching for zcl file from /home/ubuntu/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/examples/bridge-app/bridge-common/bridge-app.zap
FAILED TO EXECUTE ZAP GENERATION: No such file or directory - "zap-cli"
********************************************************************************
* You may need to install zap. Please ensure one of these applies:
* - `zap-cli` is in $PATH. Install from https://github.com/project-chip/zap/releases
*   see docs/guides/BUILDING.md for details
* - `zap-cli` is in $ZAP_INSTALL_PATH. Use this option if you
*   installed zap but do not want to update $PATH
* - Point $ZAP_DEVELOPMENT_PATH to your local copy of zap that you
*   develop on (to use a developer build of zap)
********************************************************************************
[15/714] cc obj/out/debug/gen/include/platform/Linux/dbus/bluez/bluez.DbusBluez.c.o

**Comment by bzbarsky-apple** [comment]
@XiaoCongWu Yes, if you're compiling on a a raspberry PI you need to use a source-code version of ZAP with ZAP_DEVELOPMENT_PATH pointed to it.  See https://github.com/project-chip/zap/issues/897
