### ISSUE TITLE
[mbed-mcu-boot] mbed-mcu-boot repo include too much submodule 

### ISSUE THREAD

**Issue by shchen-Lab** [project-chip/connectedhomeip#25391]
### Reproduction steps

Hi Team

mbed-mcu-boot platform include too much sub module，this ’s badly affected sync submodule.
![image](https://user-images.githubusercontent.com/75290921/222064512-f3c4bb6d-40d6-428b-b237-f16955d34ce4.png)

### Platform

other

### Type

Platform validated

**Comment by bzbarsky-apple** [comment]
@shchen-Lab what exact command did you run to cause all those to be cloned?  `third_party/mbed-mcu-boot/repo/boot/espressif/hal/esp-idf/` is empty for me when I run either a normal bootstrap or `scripts/checkout_submodules.py`

**Comment by shchen-Lab** [comment]
git submodule update --recursive --init

**Comment by bzbarsky-apple** [comment]
Yes, "don't do that".  In particular, that `--recursive` bit: don't do it.
