### ISSUE TITLE
[BUG] Door-Lock-Server sends user-changed event for every user deleted upon reception of a ClearCredentials(FFFE) command

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#25413]
### Reproduction steps

1. Create multiple users on DUT, e.g.:
`$ doorlock set-credential 0 '{"credentialType":1, "credentialIndex":1}' '1111' null null null 1 1 --timedInteractionTimeoutMs 1000`
2. Clear all credentials (which will delete associated users, since there is only a single credential associated with each user)
`$ doorlock clear-credential '{"credentialType":1, "credentialIndex":65534}' 1 1 --timedInteractionTimeoutMs 1000`
3. Examine lock-user-change events. A user-change event will have been generated for *each* user deleted, followed by a final user-change event for the all-credentials (0xFFFE). For example, after creating two users and issuing the clear-credential(All) command, the event list appears like:
```
Endpoint: 1 Cluster: 0x0000_0101 Event 0x0000_0004
   Event number: 4128803
   Priority: Info
   Timestamp: 427813
   LockUserChange: {
     LockDataType: 2
     DataOperationType: 1
     OperationSource: 7
     UserIndex: 1
     FabricIndex: 1
     SourceNode: 112233
     DataIndex: 1
    }
 Endpoint: 1 Cluster: 0x0000_0101 Event 0x0000_0004
   Event number: 4128804
   Priority: Info
   Timestamp: 428575
   LockUserChange: {
     LockDataType: 2
     DataOperationType: 1
     OperationSource: 7
     UserIndex: 2
     FabricIndex: 1
     SourceNode: 112233
     DataIndex: 2
    }
 Endpoint: 1 Cluster: 0x0000_0101 Event 0x0000_0004
   Event number: 4128805
   Priority: Info
   Timestamp: 428724
   LockUserChange: {
     LockDataType: 6
     DataOperationType: 1
     OperationSource: 7
     UserIndex: 65534
     FabricIndex: 1
     SourceNode: 112233
     DataIndex: 65534
    }

```

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

main

### Platform

core

**Comment by bzbarsky-apple** [comment]
@jrhees-cae What behavior were you expecting and why?  Please quite the exact spec bits that support the expectation.

Note that deleting all credentials may not delete all users; for example users that do not have any associated credentials at all will _not_ be deleted.  And of course in the example above, where it's "all credentials of a given type", not "all credentials" that are being deleted users that have a different type of credential will not be deleted.

**Comment by jrhees-cae** [comment]
@bzbarsky-apple These are good points. I suppose that due to the fact that deleting a credential does not necessarily delete a user as a consequence thus requires a user deleted event to be generated for each user that *is* deleted. I was hoping that we could avoid the side effect of generating a large number of events when a ClearAllCredentials command is issued. I suppose logic could be added to generate a singe UserChanged event with userIndex==FFFE  *IF* all users were indeed removed as a result of the operation, but I'm not sure this is worth the effort.
