### ISSUE TITLE
[1.0]Unable to commission matter device to custom fabric

### ISSUE THREAD

**Issue by ajay-gantayet** [project-chip/connectedhomeip#25427]
### Reproduction steps

We are trying to commission a matter device to a custom fabric.
We have tested the connectedhomeip/examples/all-clusters-app/esp32 example using the latest iOS SDK Matter.framework. Examples used:
- connectedhomeip example  commit ID: 5847d93cbe24d6731cd1915bed7944394fa327cb
- iOS version: 16.3.

### Steps to reproduce issue:
First we are trying to initially commission the matter device using MatterSupport during which wifi credentials are sent to the matter device and on boarding payload is retrieved.
Post MatterSupport workflow we are able to achieve the following using cluster commands:
- Get onboarding payload from the MatterSupport famework.
- Pair device and the iPhoneExecute following cluster commands:
- read basic commissioning info
- arm failsafe timer
- read regulatory config
- get PAI/DACr
- equest device attestation
- verify attestation request
- get CSR
- send CSR to cloud and generate NOC
- add trusted root certificateadd NOC [NOC chain is validated]

### Issue:

- Post NOC chain validation, the commissioner and commissionee should establish CASE session and all subsequent communication should happen over CASE since the matter device already has the wifi credentials that were passed to it via the MatterSupport extension. This is where we are facing the issue.
- Is there any API that can allow us to establish CASE session or is that supposed to be taken care of implicitly by the Matter framework post NOC chain validation?

Could you please help us with this? Any assistance would be greatly appreciated.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

5847d93cbe24d6731cd1915bed7944394fa327cb

### Platform

darwin, esp32

### Platform Version(s)

iOS 16.3

### Type

Common Cluster Logic

**Comment by dhrishi** [comment]
Thanks @bzbarsky-apple for all the details. We were able to commission the Matter device to the custom fabric using the iOS app. I will close this issue now.

**Comment by huchuankan** [comment]
Matter Commission  demo video ： https://www.bilibili.com/video/BV1Nx421y7sa/
