### ISSUE TITLE
Matter Test-Harness

### ISSUE THREAD

**Issue by stefano055415** [project-chip/connectedhomeip#25433]
I have a problem with TH version 2.6

If I load the PICS files the correct tests are not selected

Steps to reproduce it
Modify the project by uploading the Pics file:

<img width="932" alt="Screenshot 2023-03-02 at 16 28 36" src="https://user-images.githubusercontent.com/4798738/222474313-08193057-8e48-443f-890e-61199d417c2e.png">

I press on Run Test:

<img width="1299" alt="Screenshot 2023-03-02 at 16 29 12" src="https://user-images.githubusercontent.com/4798738/222474367-69fe95e9-47d9-4568-bb53-c867b9ac18cf.png">

I create a new test:

<img width="1303" alt="Screenshot 2023-03-02 at 16 29 29" src="https://user-images.githubusercontent.com/4798738/222474401-ea262115-f4a2-495b-ba0f-567609e0d9c1.png">

But the selected tests do not match those of the pics file

what am I doing wrong thanks

this is the pics file

[On-Off Cluster Test Plan.xml.zip](https://github.com/espressif/esp-matter/files/10872949/On-Off.Cluster.Test.Plan.xml.zip)

**Comment by yangboHDU** [comment]
How do you get your pics file? My TH2.6 only has some test cases at present. I can't find the file when uploading the pics file

**Comment by cjandhyala** [comment]
Pls file the ticket in the Matter TH repo https://github.com/CHIP-Specifications/chip-certification-tool, closing the ticket here as this is not SDK issue.

**Comment by stefano055415** [comment]
@zmeryy 
The file is present in the csa spec https://groups.csa-iot.org/wg/members-all/document/folder/2269

@cjandhyala 
This repo is private and I don't know who to ask for access, could you help me?

**Comment by cjandhyala** [comment]
@stefano055415 Could you pls reach out to CSA staff or Chris LaPré for help.
