### ISSUE TITLE
Use generic IM(invoke,read,write,subscribe) APIs in android chip-tool

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#25468]
Migrate light on/of, level cluster, sensor cluster, multiple admin cluster, operational credential cluster,basic cluster to use the generic IM API for cluster interaction.

**Comment by bzbarsky-apple** [comment]
The commit that fixed this was reverted due to CI failures: see https://github.com/project-chip/connectedhomeip/pull/26704
