### ISSUE TITLE
[Feature] Add a flag for disabling all encryption

### ISSUE THREAD

**Issue by schadom** [project-chip/connectedhomeip#25474]
### Feature description

Add a flag for disabling all message encryption.
This would make debugging network communication much easier.

### Platform

all

**Comment by bzbarsky-apple** [comment]
@schadom What is the exact proposal?  Would there still be CASE sessions but the actual encrypt/decrypt steps would be no-ops (i.e. not use the negotiated keys)?

Is this a proposed build time flag or run time flag?
