### ISSUE TITLE
[BUG] The tv-app sample is shown as not supported in the Home app.Is it currently supported?

### ISSUE THREAD

**Issue by nirvana9** [project-chip/connectedhomeip#25481]
### Reproduction steps

1. Run TV-App Sample on the device side.
2. Use the Home app to scan the QR code to pair the device.
3. The home app shows the Add this matter device, but says "Not Supported".

### Bug prevalence

always

### GitHub hash of the SDK that was being used

v1.0-branch

### Platform

raspi, other

### Anything else?

HomePod : 16.3.2
iPadOS :16.3.1

**Comment by nirvana9** [comment]
Thanks for the reply. Is there any plan to support TV in the future this year?

**Comment by bzbarsky-apple** [comment]
@nirvana9 I can't comment about future releases; standard Apple policy.
