### ISSUE TITLE
[BUG] scripts/bootstrap.sh

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#25568]
### Reproduction steps

```bash
cd ${MATTER-SDK}
source ./scripts/bootstrap.sh
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 536a0d9b0f738ed79a939c638ef1bbfae3e7cf59 (HEAD -> master, origin/master, origin/HEAD)

### Platform

other

## Environment

OS: ubuntu 20.04

python --version : Python 3.8.10

## Log

I think brew is for Mac.

> 
>   BOOTSTRAP! Bootstrap may take a few minutes; please be patient.
> 
> Downloading and installing packages into local source directory:
> 
>   Setting up CIPD package manager...[|]======================================================================
> It looks like this version of Python does not support SSL. This is common
> when using Homebrew. If using Homebrew please run the following commands.
> If not using Homebrew check how your version of Python was built.
> 
> brew install openssl  # Probably already installed, but good to confirm.
> brew uninstall python && brew install python
> ======================================================================                                                                                                                     Traceback (most recent call last):
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 857, in <module>
>     sys.exit(main())
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 849, in main
>     return EnvSetup(**vars(parse())).setup()
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 501, in setup
>     result = step(spin)
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 595, in cipd
>     cipd_client = cipd_wrapper.init(
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 378, in init
>     bootstrap(client, silent, rosetta=rosetta)
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 328, in bootstrap
>     tmp.write(client_bytes(rosetta))
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 228, in client_bytes
>     conn = https_connect_with_proxy(CIPD_HOST)
>   File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 201, in https_connect_with_proxy
>     conn = httplib.HTTPSConnection(url.hostname, url.port)
>   File "/usr/lib/python3.8/http/client.py", line 1383, in __init__
>     super(HTTPSConnection, self).__init__(host, port, timeout,
>   File "/usr/lib/python3.8/http/client.py", line 834, in __init__
>     (self.host, self.port) = self._get_hostport(host, port)
>   File "/usr/lib/python3.8/http/client.py", line 868, in _get_hostport
>     i = host.rfind(':')
> AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by bzbarsky-apple** [comment]
@mmt-10 Your python install on Ubuntu is somehow configured without SSL/TLS support.  Did you just install it from packages (which ones?) or did you do something manual to get that python?

**Comment by mmt-10** [comment]
Thank you for your reply.
I checked my PC, and PC may be wrong.

**Comment by aaaaa654** [comment]
Hey guys, I got a problem with bootstrap.sh as well, CPID package was fine but the python environment is causing problem, i'm not a developer so it would be great if anyone can have a look and help me, thanks
![image](https://user-images.githubusercontent.com/107745009/223951880-01a43b24-a1d7-4bb8-906b-a70e301ee47c.png)
![image](https://user-images.githubusercontent.com/107745009/223952060-7e66807f-35e9-4674-ad29-768f67a4fbb9.png)

**Comment by bzbarsky-apple** [comment]
@aaaaa654 Do you have the devel packages for glib and gio-unix installed?  In particular, did you follow the instructions at https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md#prerequisites where is says to install various packages including `libglib2.0-dev`?

**Comment by aaaaa654** [comment]
> @aaaaa654 Do you have the devel packages for glib and gio-unix installed? In particular, did you follow the instructions at https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md#prerequisites where is says to install various packages including `libglib2.0-dev`?

yes i did install those packages and followed all the steps, this is the only problem i encountered in the whole process.

**Comment by bzbarsky-apple** [comment]
Well, your pkg-config does not seem to be aware of the libglib2.0-dev bits... what does running:
```
pkg-config --cflags --libs glib-2.0
```
at the shell show you?

**Comment by aaaaa654** [comment]
It says the pkg isn't found in the path
![image](https://user-images.githubusercontent.com/107745009/224229994-9254195e-a4aa-4af7-b3ad-5444b43555e0.png)

**Comment by bzbarsky-apple** [comment]
OK, do you have a `glib-2.0.pc` file somewhere on your disk? If so where?  And what, if anything, is your `PKG_CONFIG_PATH` environment variable set to?

**Comment by bzbarsky-apple** [comment]
I'd start with seeing whether `locate glib-2.0.pc` says anything useful, @aaaaa654

**Comment by LiuHuanYin** [comment]
> 20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 228, in client_bytes
> conn = https_connect_with_proxy(CIPD_HOST)
> File "/home/muto/matter/matter-master-20230308/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/wrapper.py", line 201, in https_connect_with_proxy
> conn = httplib.HTTPSConnection(url.hostname, url.port)
> File "/usr/lib/python3.8/http/client.py", line 1383, in init
> super(HTTPSConnection, self).init(host, port, timeout,
> File "/usr/lib/python3.8/http/client.py", line 834, in init
> (self.host, self.port) = self._get_hostport(host, port)
> File "/usr/lib/python3.8/http/client.py", line 868, in _get_hostport
> i = host.rfind(':')
> AttributeError: 'NoneType' object has no attribute 'rfind'

Please check the https_proxy settings. 
Do not work: `https_proxy=127.0.0.1:7890`
Works well: `https_proxy=http://127.0.0.1:7890`
