### ISSUE TITLE
[BUG] [lighting-app] [ESP32-C3] commissioning error

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#25586]
### Reproduction steps

1. power on ESP32-C3 devKitM-1
2. Start Google Home app and search devices.
3. Select `Matter-enabled device`
4. Read QR code
Then, Google Home app shows error that ESP32 is not support matter cluster device.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 1f2f882 (HEAD -> master, origin/master, origin/HEAD)

### Platform

esp32

### Anything else?

# Log
[20230309.txt](https://github.com/project-chip/connectedhomeip/files/10928213/20230309.txt)

After Moving state `'kEstablishing' --> 'kActive'`, then Error occurred ` Type 0001:02` and ` Type 0001:05`.
> I (37556) chip[SC]: SecureSession[0x3fc97340]: Moving from state 'kEstablishing' --> 'kActive'
> I (37566) chip[SVR]: Commissioning completed session establishment step
> I (37566) chip[DIS]: Updating services using commissioning mode 0
> I (37576) chip[DIS]: CHIP minimal mDNS started advertising.
> I (37586) chip[SVR]: Device completed Rendezvous process
> I (37636) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 1) status= 14 
> I (37636) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 1 12
> I (37656) chip[EM]: >>> [E:8971r S:1997 M:48062720] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
> I (37666) chip[EM]: <<< [E:8971r S:1997 M:11621619] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:05 (IM:ReportData)
> I (37666) chip[IN]: (S) Sending msg 11621619 on secure session with LSID: 1997
> I (37676) NimBLE: GATT procedure initiated: indicate; 
> I (37696) NimBLE: att_handle=14
> 
> I (37766) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 1) status= 14 
> I (37776) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 1 12
> I (37786) chip[EM]: >>> [E:8972r S:1997 M:48062721] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:02 (IM:ReadRequest)
> I (37806) chip[EM]: <<< [E:8972r S:1997 M:11621620] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:05 (IM:ReportData)
> I (37806) chip[IN]: (S) Sending msg 11621620 on secure session with LSID: 1997
> I (37816) NimBLE: GATT procedure initiated: indicate; 
> I (37826) NimBLE: att_handle=14

# Environment
Commissioner: Google Home App
ESP-IDF: v4.4.4

**Comment by bzbarsky-apple** [comment]
That log shows a CSRRequest command, then nothing.

Presumably the device failed device attestation, which I believe Google Home does after having both the device attestation info and the CSR, as I recall.

But fundamentally, this is an issue you should report to Google so they can investigate, not an SDK issue....
