### ISSUE TITLE
[Documentation] Specs vs XML difference GeneralCommissioningCluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25608]
### Documentation issues

The Specs (Core 11.9.6) have a default value for Location­Capability, but the XML (https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/general-commissioning-cluster.xml#L51) does not.

**Comment by bzbarsky-apple** [comment]
Thinking about the "default" thing some more: "default" in the XML right now does not mean the same concept as "default" does in the spec. So there's no particular reason they should be aligned, and in some cases aligning them will be actively confusing. This is one of those cases: if we add a default in the XML, the attributes will have a value set in the ZAP UI, but that value will then be completely ignored and the actual value will come from some totally different place....

We need to figure out how to reflect the spec in the XML here, I guess, but that's a general question across the board for default values; we might need a new attribute for the "spec default value" or something.
