### ISSUE TITLE
[Documentation] Specs vs XML Differences AccessControlCluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25606]
### Documentation issues

The Specification (core 9.10) defines default values for the attributes in XML  at https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/access-control-cluster.xml#L89-L102, but XML do not contain them.

Affected are
* Sub­jectsPerAc­cessCon­trolEntry
* TargetsPer­AccessCon­trolEntry
* AccessControlEntries­PerFabric

### Platform

other

**Comment by bzbarsky-apple** [comment]
Thinking about the "default" thing some more: "default" in the XML right now does not mean the same concept as "default" does in the spec.  So there's no particular reason they should be aligned, and in some cases aligning them will be actively confusing.  This is one of those cases: if we add a default in the XML, the attributes will have a value set in the ZAP UI, but that value will then be completely ignored and the actual value will come from some totally different place....
