### ISSUE TITLE
[Documentation] Spec vs XML difference BooleanStateCluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25605]
### Documentation issues

I found the following differences between specifications (1.0) and the Chiptool XML for the BooleanStateCluster

XML: https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/boolean-state-cluster.xml

* the XML defined the value "false" as default falue, the specification do not state any default value
* The XML defines the event as NOT optional, the specification state optional. With the info in the specs "This event SHALL be generated when the StateValue attribute changes." it feels that the specs are wrong in the table in ApplicationCluster Specs 1.7.5

### Platform

other

**Comment by bzbarsky-apple** [comment]
@Apollon77 Thank you for doing this audit!

> the XML defined the value "false" as default falue, the specification do not state any default value

Yep, good catch.

> The XML defines the event as NOT optional, the specification state optional.

See https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6270 opened a month or so ago.

**Comment by Apollon77** [comment]
> See https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6270 opened a month or so ago.

This is not accessible for "Normal GitHub users" it seems

**Comment by bzbarsky-apple** [comment]
Yes, you have to be a CSA member, and even then it's somewhat restricted.  Deeply unfortunate.  What the issue says is:

> The table says optional, the prose says "This event SHALL be generated when the StateValue attribute changes." as a blanket statement. We should either make it mandatory, or change the prose to say "If this event is supported, then this event SHALL be generated when ..." or something.

**Comment by bzbarsky-apple** [comment]
The issue is still open, so I don't have an answer to that question....

**Comment by bzbarsky-apple** [comment]
Thinking about the "default" thing some more: "default" in the XML right now does not mean the same concept as "default" does in the spec.  So there's no particular reason they should be aligned, and in some cases aligning them will be actively confusing.

**Comment by bzbarsky-apple** [comment]
That said, in this case removing the default="0" is probably fine.
