### ISSUE TITLE
[Documentation] Specs vs XML differences OccupancySensingCluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25614]
### Documentation issues

I discovered the following differences:
* Attributes *OccupiedToUnoccupiedDelay and *OccupiedToOccupiedDelay mention an max value sof 0xFFFE in XML but not in the specs (* meaning pir, ultrasonic, ... all the same)

**Comment by bzbarsky-apple** [comment]
Good catch!  This is wrong.
