### ISSUE TITLE
[Documentation] XML error TemperatureMesaurement Cluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25618]
### Documentation issues

The tolerance attribute should have 0x0800 as max and not 0x8000 I assume to match with all other measurement clusters? :-)

https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/temperature-measurement-cluster.xml#L30

**Comment by bzbarsky-apple** [comment]
Nice catch!
