### ISSUE TITLE
[Documentation] Specs vs XML differences OnOffCluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25615]
### Documentation issues

* Attributes OnTime and Offwait time and Nullable as per specs, but the XML do not include this
* Command onWithTimed off has Nullable fields as per spec which is not in XML and XML noted min/max values that are not covered by specs

**Comment by bzbarsky-apple** [comment]
@Apollon77 Good catch, but see https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6336 -- this needs to be fixed in the spec.
