### ISSUE TITLE
[Documentation] Specs vs XML difference User/Fixed Label cluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25610]
### Documentation issues

In the attribute definitions in both clusters the XML list a max length of 254 entries for the Array (see e.g. https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/fixed-label-cluster.xml#L34) ... The specifications (Core 9.7-9.9) do not say anything about maxLength

**Comment by bzbarsky-apple** [comment]
max length is ignored for lists anyway, but yes, it's confusing and we should remove it.
