### ISSUE TITLE
[BUG] Written ACL entries in second fabric may not match subsequent reading of ACL entries for second fabric

### ISSUE THREAD

**Issue by morahman2022** [project-chip/connectedhomeip#25629]
### Reproduction steps

I found that sometimes after writing ACL entries in second fabric followed by reading of ACL entries may result in different read values of ACL entries from written values for ACL entries.  

I commissioned a lighting end device. Then I opened a commissioning window of the first fabric using discrimintaor of the lighting end device. Next, I commissioned lighting end device to second fabric. I write two ACL entries on ACL write operation. Next, I read the ACL entries. The reading values of ACL entries may not match with written values for ACL entries (e.g., FabricIndex) value. 

The commands I used are provided below and the output log of ACL reading is attached.

[Lighting_End_Device_ACL_Read_Log.txt](https://github.com/project-chip/connectedhomeip/files/10945174/Lighting_End_Device_ACL_Read_Log.txt)

Lighting Device:
```
./chip-tool pairing ble-thread 2 hex:0e080000000000000000000300000b35060004001fffe00208dead00beef00cafe0708fddead00beef00000510e60f9a3e2c9940ebe1628550b8ee595c030a4f70656e546872656164010270f004108bda77ff23951646eef39a396def3d350c0402a0f7f8 20202021 3100
./chip-tool pairing open-commissioning-window 2 1 400 2000 3100
./chip-tool pairing code 12 30536726920  --commissioner-name beta
./chip-tool accesscontrol write acl '[{"fabricIndex": 2, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}, {"fabricIndex": 2, "privilege": 3, "authMode": 2, "subjects": [1], "targets": [
{"cluster": 6, "endpoint": 1, "deviceType": null}
]}]' 12 0 --commissioner-name beta
./chip-tool accesscontrol read acl 12 0 --commissioner-name beta
```

### Bug prevalence

For every three and four attempts

### GitHub hash of the SDK that was being used

80ee243109c

### Platform

efr32

**Comment by bzbarsky-apple** [comment]
> The reading values of ACL entries may not match with written values for ACL entries (e.g., FabricIndex) value.

The FabricIndex on read will be whatever the relevant fabric's FabricIndex on the device is.  When writing:

1. The value does not need to be provided at all.  As in, the "write acl" command could have just left the fabricIndex bits out.
2. If provided, will not be sent on the wire.  Relevant part of the spec is in section "7.18.1.10. Struct" under "Fabric-Scoped Struct" and says:

    > * The global FabricIndex field of a fabric-scoped struct SHOULD NOT be indicated in a write interaction.
4. If it were sent on the wire, the server would ignore it.  Relevant part of the spec is the same section as above:
    > * The global FabricIndex field of a fabric-scoped struct SHALL be ignored in a write interaction.
   > * When a write interaction creates a fabric-scoped struct entry (in a fabric-scoped list), the server SHALL implicitly load the accessing fabric-index into the global FabricIndex field of the struct.
