### ISSUE TITLE
need specify more integer type in android chip-tool UI for IM invoke and write

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#25637]
https://github.com/joonhaengHeo/connectedhomeip/blob/499b480f1b7b6f7d12eff32d1b41cfaa23b0cb8e/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/WildcardFragment.kt#L402

We need specify unsigned short, unsignedInt, unsigned long in the below map since their encoding is different for different type.          
  "UnsignedInt" to object:TlvWriterInterface {
              override fun generate(writer : TlvWriter, value: String, tag: chip.tlv.Tag) {
                writer.put(tag, value.toUInt())
              }

**Comment by joonhaengHeo** [comment]
@yunhanw-google 
In my opinion, Integer Type can be divided into two types.

Int : Int, Long, Short
UnsignedInt : UInt, ULong, UShort

Therefore, I think we only need two types.
All Int types are converted to Long types in TLVWriter.kt and are being processed.

**Comment by joonhaengHeo** [comment]
https://github.com/project-chip/connectedhomeip/blob/e1381bf86142261601344adff5dc1c4304e9aaf2/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/WildcardFragment.kt#L405
`writer.put(tag, value.toULong())`

https://github.com/project-chip/connectedhomeip/blob/e1381bf86142261601344adff5dc1c4304e9aaf2/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/WildcardFragment.kt#L410
`writer.put(tag, value.toLong())`

**Comment by joonhaengHeo** [comment]
https://github.com/project-chip/connectedhomeip/blob/e1381bf86142261601344adff5dc1c4304e9aaf2/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/WildcardFragment.kt#L405
`writer.put(tag, value.toULong())`

https://github.com/project-chip/connectedhomeip/blob/e1381bf86142261601344adff5dc1c4304e9aaf2/examples/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/clusterclient/WildcardFragment.kt#L410
`writer.put(tag, value.toLong())`
