### ISSUE TITLE
[Documentation] XML vs Specs differences Group Key management cluster

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#25642]
### Documentation issues

* The command "KeySetReadAllIndices" has no request parameters according to specs, but XML defines an ID as input. I would assume XML to be wrong when checking the meaning of the command
* The Feature defined in the specs is not contained in the XML
* The GroupKeySetStruct misses the GroupKey­Multicast­Policy enum as defined in the XML (ok this is a provisional feature, no ideal how to handle that?

**Comment by bzbarsky-apple** [comment]
> I would assume XML to be wrong when checking the meaning of the command

The XML is wrong; the question is how we fix it without breaking compat at this point...  Need to think about this carefully.

> The Feature defined in the specs is not contained in the XML

Yep, not least because that feature is just not implemented in the SDK, so there's been no need for it....

> The GroupKeySetStruct misses the GroupKey­Multicast­Policy enum as defined in the XML (ok this is a provisional feature, no ideal how to handle that?

If it's provisional, it should generally not be included in the XML.

**Comment by bzbarsky-apple** [comment]
I filed https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6344 to track reserving this field id on the spec side.

**Comment by Apollon77** [comment]
So we will add this field to the specs even that it makes no real sense?

**Comment by bzbarsky-apple** [comment]
> Ahh you just make sure that if ever fields get added they do not use this field ID?

Yes, exactly.

**Comment by ReneJosefsen** [comment]
> The GroupKeySetStruct misses the GroupKey­Multicast­Policy enum as defined in the XML (ok this is a provisional feature, no ideal how to handle that?

Can you elaborate on this, looking at the spec, the defined GroupKeySetStruct type does include GroupKeyMulticastPolicy (field 8) and the type of that field is GroupKeyMulticastPolicyEnum?

**Comment by bzbarsky-apple** [comment]
@ReneJosefsen The _spec_ has that, but the XML in the SDK does not.
