### ISSUE TITLE
BLEManagerImpl may have MTU overflow its storage

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2569]
#### Problem
In `src/platform/ESP32/BLEManagerImpl.cpp` we have this line in `BLEManagerImpl::HandleGATTCommEvent`:
```
conState->MTU = param->mtu.mtu;
```
The right-hand side is a `uint16_t`.  The left-hand side is a 10-bit bitfield.  There seems to be no check that the value on the right will fit on the left, nor any explanation for why a check is not needed.

 #### Proposed Solution
Either introduce a check or add an explanation for why it's not needed.

@sagar-apple it looks like you might know something about this code?

**Comment by sagar-apple** [comment]
@shana-apple amd @vivien-apple are probably more familiar with this. I can look if they're unable.

**Comment by bzbarsky-apple** [comment]
`src/platform/EFR32/BLEManagerImpl.cpp` has a similar issue in `BLEManagerImpl::UpdateMtu`.

**Comment by andy31415** [comment]
This looks like platform specific code - re-assigned to platform owner.

**Comment by dhrishi** [comment]
>nor any explanation for why a check is not needed.

@bzbarsky-apple As per the BLE specification, the maximum MTU value can be 517 bytes. This can be accomodated in 10 bits. Good enough to close this?

**Comment by bzbarsky-apple** [comment]
Good enough, but would be even better with a comment.  ;)
