### ISSUE TITLE
BLEManagerImpl::SoftDeviceBLEEventCallback in nRF5 BLEManager can overflow size computation

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2571]
#### Problem
The code looks like this:
```
        const uint16_t valLen     = bleEvent->evt.gatts_evt.params.write.len;
        const uint16_t minBufSize = CHIP_SYSTEM_PACKETBUFFER_HEADER_SIZE + valLen;
```
There is no check that the result of the addition doesn't overflow `uint16_t`.

 #### Proposed Solution
Add a check.  I'm not sure whether it should emit `kCHIPoBLEOutOfBuffersEvent` or do something else....

@pan-apple do you know who generally deals with this code?

**Comment by kpschoedel** [comment]
Obsolete — this nRF5 code is no longer in tree
