### ISSUE TITLE
CHAR_TO_BLUEZ assumes its input is [0-9a-f] but consumers don't seem to enforce this

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2574]
#### Problem
The calculation `CHAR_TO_BLUEZ` does only makes sense if its input is a hex digit in lowercase.  It's not clear to me why that is guaranteed at all the callsites.

 #### Proposed Solution
Add checks, or document why they are not needed.

@yunhanw-google

**Comment by kpschoedel** [comment]
Obsolete — uses were removed in 880c5f3e0a31ecc3122feb44fdd2351dde02350c #2954 and definition was removed in e393b5ea9961867ff5fe1570f36c1152c34b8d29 #4347
