### ISSUE TITLE
[Documentation] attestation DAC Challenge Response Verification

### ISSUE THREAD

**Issue by shalevv123** [project-chip/connectedhomeip#25751]
### Documentation issues

This thread is not really a an issue but rather a question.
I was looking through the documentation and i couldn't really find the standard for the messages passed in the attestation stage:
 
![Screenshot_3](https://user-images.githubusercontent.com/73291739/226371027-f9543109-5f22-4138-b2ae-a252b5b5fcd5.png)

If someone can direct me towards the messages that are passed during that step it will be very helpful.

**Comment by bzbarsky-apple** [comment]
See section "6.2. Device Attestation" and section "6.3. Certification Declaration" and [11.17.6.1. AttestationRequest Command" and "11.17.6.2 AttestationResponse Command" in the Matter specification.
