### ISSUE TITLE
BluezHandleAdvertisementFromDevice assumes g_variant_n_children will not return a large value

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2576]
#### Problem
In `BluezHandleAdvertisementFromDevice` we have:
```
                buf[i++] = g_variant_n_children(rawVal) + 2 + 1;
```
This is writing to a `uint8_t`, so assuming that there are not too many children.

 #### Proposed Solution
Either add a check that this is safe or document why a check is not needed.

@yunhanw-google

**Comment by kpschoedel** [comment]
Obsolete — this code was removed by https://github.com/project-chip/connectedhomeip/commit/880c5f3e0a31ecc3122feb44fdd2351dde02350c  (#2954)
