### ISSUE TITLE
WindowCovering: hard to implement StopMotion Command for hardware.

### ISSUE THREAD

**Issue by Kxuan** [project-chip/connectedhomeip#25797]
### Reproduction steps

The current implemention of [emberAfWindowCoveringClusterStopMotionCallback](https://github.com/project-chip/connectedhomeip/blob/bd94d060c3656c76bfd410f20698639bda68cc1e/src/app/clusters/window-covering-server/window-covering-server.cpp#L721) causes the attribute value of current value to be inconsistent with the actual value.

**What happenned**
As the spec saids, the StopMotion command shall:

- TargetPositionLiftPercent100ths attribute will be set to CurrentPositionLiftPercent100ths attribute value.
- TargetPositionTiltPercent100ths attribute will be set to CurrentPositionTiltPercent100ths attribute value.

[emberAfWindowCoveringClusterStopMotionCallback](https://github.com/project-chip/connectedhomeip/blob/bd94d060c3656c76bfd410f20698639bda68cc1e/src/app/clusters/window-covering-server/window-covering-server.cpp#L721) get the value of `CurrentPositionLiftPercent100ths` and set the value to `TargetPositionLiftPercent100ths` immediately.

But some hardwares update `CurrentPositionLiftPercent100ths` periodically. The value of `CurrentPositionLiftPercent100ths` may differ than the real position.

For example, the hardware design may put `connectedhomeip` on a high performance processor with network capabilities, and put motor control on another low performance controller. The two communicate using UART.

Assuming that the target value is now set to 100%, current value is set to 0%. When current value increases to 50%, the application invokes StopMotion. Then the timeline and status of each value are as follows:

```
|          time |   0   |  10  |  20  |  30  |  40  |  50  |  51  |
|         motor |   0%  |  10% |  20% |  30% |  40% |  50% |  51% |
|   (UART Comm.)| *SYNC |      |*SYNC |      |*SYNC |*STOP |*SYNC?|
| Current Value |   0%  |   0% |  20% |  20% |  40% |  40% |  51%?|
|  Target Value | 100%  | 100% | 100% | 100% | 100% |  40% |  40%?|
```
^ *SYNC: motor controller reports its current value to `connectedhomeip`.
^ *STOP: `connectedhomeip` send STOP command to motor.

At the time 50, StopMotion is received. `emberAfWindowCoveringClusterStopMotionCallback` get the current value base on the last sync value, and it set the target value to the out-dated value. And this results in the target value and current value not as expected (which is 50%).

### Bug prevalence

--

### GitHub hash of the SDK that was being used

master/v1.0-branch

### Platform

core

### Anything else?

**prefer solution**

There are some solutions I have considered:
1. the motor stop work immediately, and **do not update** current value to its real current value. 
   This solution will result the value on attribute and the real value mismatched.
2. the motor stop work immediately, and **update** current value to its real value after `emberAfWindowCoveringClusterStopMotionCallback`
   This solution will result current value and target value mismatched.
3. the motor stop and **move back** to 40%.
   This solution will result "StopMotion" does not acturally stop the motor. And mostly it is not what users want.
4. **block working thread** in HandleStopMotion() delegate, and wait motor sync its current value. After that, finish `emberAfWindowCoveringClusterStopMotionCallback`.
   This solution will result in nearly all operations stop working for an undetermined amount of time. And the code in HandleStopMotion() can not reply error status to the invoker, if motor controller does not report its states in time.
5. **update target value** when motor update its real current value, after `emberAfWindowCoveringClusterStopMotionCallback`
   This solution will result StopMotion **does not work as the spec expected** slightly. When StopMotion response to the command invoker, the target value does not changed immediately. Instead, it changed slightly later.
6. make `emberAfWindowCoveringClusterStopMotionCallback` could handle command asynchronously. And then, we could wait for the motor controller report its state without blocking working thread. After that, send command response.
   This solution requires modification on the processing flow of InvokeRequest. And it requires more discussion.

I prefer solution 4 currently. But I expect the solution 6 to be discussed, and be implmemented in `connectedhomeip`. I think it will be a better solution than solution 4 if it is implmeneted.

Please let me know if there are other solutions. Thank you!

**Comment by bzbarsky-apple** [comment]
@jmeg-sfy

**Comment by jmeg-sfy** [comment]
The goal is to stop the motor asap and in real life there is inertia.
This is why the test step allows some time to pass between the command and reading the results.
This might be improved in the current test harness by adding some dedicated PIXIT for the stopping time.
At the end the outcome of a stop command SHALL be current == target. 
Or Stop command equals GoToCurrent position basically.

@Kxuan Meanwhile reading your comments about the implementation.
You can propose indeed improvements and this is a demo proposal that you can tweak to fit your real hardware implementation, solution 4, 5 or 6 seems all valid to me but not 1 ,2 or 3.
A very short delay to allow the motor current position to be known before updating its target can work
(this is not really immediate... , we may improve the specs if needed)
This is why there is a delay in the test plan (1 or 2 seconds by default if i remember) 
The rest it is your own implementation on your real product , you do like you want !
But if you wish to bring improvement in the public SDK you are welcome !

**Comment by Kxuan** [comment]
@jmeg-sfy Thanks for your reply.

For solution 5, if I update target value after `emberAfWindowCoveringClusterStopMotionCallback`. 

It causes active attribute subscribers get two reports with different value in very short time. And it also results in the GUI of some apps changes twice in short time. It seems abnormal for users.

If I want the GUI changes only once, I need prevent `emberAfWindowCoveringClusterStopMotionCallback` update the target value.

Would you mind me open a PR to do this on emberAfWindowCoveringClusterStopMotionCallback?
I will do:
* add a new error code, for example, CHIP_ERROR_INPROGRESS
* check the return value of HandleStopMotion. If the vendor code returns CHIP_ERROR_INPROGRESS, then do not update target value to current value. Instead, let the vendor code update its value later.

Since we are using a new error code, it will not break any old code.

**Comment by jmeg-sfy** [comment]
Well not sure you can do CHIP_ERROR_INPROGRESS that easily.
The problem it is looking like this won't be specs compliant..

**Comment by jmeg-sfy** [comment]
If you want to do a PR go ahead.
