### ISSUE TITLE
[BUG] Bridge matter idl generation

### ISSUE THREAD

**Issue by mustafayuce33** [project-chip/connectedhomeip#25799]
### Reproduction steps

If you take a look at this line; 
https://github.com/project-chip/connectedhomeip/blob/master/scripts/py_matter_idl/matter_idl/generators/bridge/__init__.py#L90

It checks if the definition is nullable. But it should check if it is optional I guess. So this line should be as follows

```
if definition.is_optional:
        cType = '::chip::Optional<{}>'.format(cType)
```

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/commit/b9d32ecefd004adb7cc4c70a5f4a567dca199da0

### Platform

raspi

**Comment by andy31415** [comment]
Seems fixed by #26229
