### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by s07641069** [project-chip/connectedhomeip#25801]
### Reproduction steps

Follow the procedure below to reproduce the issue.
1. Commission a Matter device (a Matter Light) to a Fabric created by a Google Nest Hub
2. Ensure you can control this device with Google Home.
3. Power off then on the Matter device.
4. Wait for this device to reappear in Google Home, and you can also control it.

It usually takes around 40 secs or even longer for the Matter device to reconnect to a Matter Fabric and be controlled again.

The issue can be produced by a Telink or Nordic SoC. I believe even a SciLab SoC also has the same issue.

Here is a quick summary of the root cause of this issue above.
1. The Matter device reconnects to the Thread network created by Nest Hub. All the session information has been lost due to the power cycling.
2. However, the Google Nest Hub thinks the Matter device stays the same and communicates with it using the session id created before (e.g., during CASE establishment).
3. The Matter device receives an unknown session id from the Nest Hub and drops it. See attached screenshot.
4. After a few retransmissions fail, the Nest Hub has to create a new secure session again via CASE.
5. The Nest Hub can communicate with the Matter device again.

The chip-tool always creates a secure session when it runs and therefore, it cannot be used to reproduce the same issue.

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

a6dc62c6582de394d3c628f4386defd71b09bee1

### Platform

core

**Comment by bzbarsky-apple** [comment]
This sounds like an issue you should report to Google Home, not a core SDK issue....
