### ISSUE TITLE
[Scenes] Handle Change of Extension Field Set size on OTA

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#25826]
Related to: https://github.com/project-chip/connectedhomeip/pull/24561#discussion_r1147841635

SceneTable needs to take action in the event that a Scene becomes un-useable after an OTA update.

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/24561#discussion_r1147841635 is probably a better link that gitghub won't break when the PR issues are resolved or there are updates to the code.
