### ISSUE TITLE
Log saving apparently not working in the QEMU CI workflow

### ISSUE THREAD

**Issue by rwalker-apple** [project-chip/connectedhomeip#2585]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/2558/checks?check_run_id=1101210841

QEMU tests fail and log uploading appears to be skipped, as there are no artifacts produced by the failed run.

 #### Proposed Solution
 upload logs unconditionally, perhaps with a separate workflow or job?

**Comment by rwalker-apple** [comment]
@andy31415 ?

**Comment by woody-apple** [comment]
SW BRB: We think this is the same issue as in here: https://github.com/project-chip/connectedhomeip/issues/2227 TLDR; if the job fails, it fails.
