### ISSUE TITLE
[BUG] spelling error carried over from spec

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#25974]
### Reproduction steps

Code inspection

### Bug prevalence

appears in tests

### GitHub hash of the SDK that was being used

884c4e249797e2ebf9e8655c699d9e47facfd51c

### Platform

core

### Anything else?

Fixed in spec in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6372, this is to track

**Comment by bzbarsky-apple** [comment]
This is specifically about `RxErrInvalidScrAddrCount` which should be `RxErrInvalidSrcAddrCount`.  That is, should be `Src` instead of `Scr`.

**Comment by cecille** [comment]
Not sure why this wasn't auto-closed, but the linked PR fixes this.
