### ISSUE TITLE
[Question] Multi-Admin in Same fabric for Linux - Example/Documentation

### ISSUE THREAD

**Issue by pintu-sakariya** [project-chip/connectedhomeip#26030]
1. Device#1 Ubuntu as commissioner using chip-tool #fabric1
2. Device#2 ESP32 Lightbulb endnode #fabric1
3. Device#3 Ubuntu - Please some one can help me to understand following,
    is chip-tool can be used as multi-admin administrator? for Device#3 
    How to provision Device#3 in fabric1, command line argument to commissioning device#3 as administrator.

**Comment by bzbarsky-apple** [comment]
> is chip-tool can be used as multi-admin administrator? for Device#3

Yes.  You can copy over the storage from Device #1 (so that the generated private keys are available, etc), and then run chip-tool on Device #3 with a non-default commissioner node id.

Device #1 would need to set up the right ACLs for this, of course.
