### ISSUE TITLE
[Platform] [Linux] A deadlock occurs in the commission of the device

### ISSUE THREAD

**Issue by yzm157** [project-chip/connectedhomeip#26041]
### Reproduction steps

1. Turn off all Matter devices
2. Use Python for device commission

```
# ..... Init devCtrl
devCtrl.CommissionWiFi(3840, 20202021, 1, "wifi-ssid", "wifi-password")    # deadlock
```

Deadlock caused by not handling bluetooth timeout.

At src/platform/Linux/BLEManagerImpl.cpp
```
void BLEManagerImpl::OnScanError(CHIP_ERROR err)
{
    ChipLogError(Ble, "BLE scan error: %" CHIP_ERROR_FORMAT, err.Format());
}
```
The failure reason is not called back to BleLayer

### Platform

python, raspi

### Type

Platform validated

**Comment by tianfeng-yang** [comment]
at src/controller/CHIPDeviceController.cpp

**Comment by tianfeng-yang** [comment]
@yzm157 @bzbarsky-apple 

at src/controller/CHIPDeviceController.cpp

```
1. DeviceCommissioner::PairDevice(NodeId remoteDeviceId, RendezvousParameters & rendezvousParams, CommissioningParameters & commissioningParams)
2. DeviceCommissioner::EstablishPASEConnection(NodeId remoteDeviceId, RendezvousParameters & params)
3. DeviceCommissioner::FindCommissioneeDevice(const Transport::PeerAddress & peerAddress)
```

blocked in step3, FindCommissioneeDevice not set timeout. There is an infinite loop here
