### ISSUE TITLE
[Query]Matter Multi-Admin 

### ISSUE THREAD

**Issue by bsrinivasanc** [project-chip/connectedhomeip#26044]
With the release of Matter 1.0 specification, we are trying to explore various features of Matter specially Multi-Admin. As detailed in the specification, we understand that multi-admin is the feature that enables more than one admins to form their individual fabric and control the same end-device. We also understood that through ACL (fabric scoped) the admin#1 can impose access restrictions to other device on the same fabric#1.

However, is it possible for **admin#1 of fabric#1** to impose access restriction to **admin#2 of fabric#2** ? Since the ACLs are fabric scoped, is this type of restrictions valid with current scope of the specification, if yes, could the team here please guide with the procedures.          

The above query is with the intention of allowing all Door Lock operations such as lock, unlock, Set Credential, Set PIN from admin#1, however admin#2 shall only perform lock/unlock and should not set the user PIN/Credential.

Note: admin#2 in all the above query can be considered as phone app of other standard ecosystem and can set only Lock/Unlock on the lock device.

**Comment by bzbarsky-apple** [comment]
> However, is it possible for admin#1 of fabric#1 to impose access restriction to admin#2 of fabric#2 ?

No, that is not possible.  A fundamental premise of the multi-fabric feature is that all fabrics are on an equal footing.

If you want restricted access for some entities, those entities need to be within the same fabric as something else that sets the restricted ACLs for them.
