### ISSUE TITLE
[1.0] TC-DGGEN-2.2 can not read event

### ISSUE THREAD

**Issue by cyyyys** [project-chip/connectedhomeip#26046]
### Reproduction steps

Problem
TC-DGGEN-2.2 cannot read hardware-fault-change radio-fault-change network-fault-change Event.

Here is the log.

[TC-DGGEN-2.2.txt](https://github.com/project-chip/connectedhomeip/files/11198639/TC-DGGEN-2.2.txt)

### Bug prevalence

not a bug

### GitHub hash of the SDK that was being used

tag 1.0.0.2

### Platform

freeRTOS

### Type

Test Improvement

**Comment by bzbarsky-apple** [comment]
`examples/all-clusters-app/linux/AllClustersCommandDelegate.cpp` is _always part of all-clusters-app_.  Why wouldn't we just remove those `#if` bits entirely from that file @yufengwangca ?
