### ISSUE TITLE
[1.0] how to read fifo event in chip platform 

### ISSUE THREAD

**Issue by cyyyys** [project-chip/connectedhomeip#26078]
### Reproduction steps

for example if I can read the event in TC-DGGEN-2.2 by when compiling examples/all-clusters-app/linux/AllClustersCommandDelegate.cpp
but how can to realize it in esp32 or other Chip platform?
Because I noticed the code in  examples/all-clusters-app/linux/main-common.cpp, but not adaptation on other chip platform.

### Bug prevalence

not a bug

### GitHub hash of the SDK that was being used

tag 1.0.0.2

### Platform

esp32, freeRTOS

### Type

Test Improvement

**Comment by bzbarsky-apple** [comment]
The fifo thing is just for testing in the all-clusters test app on Linux.

A normal Matter application will generate the events relevant to it as needed, without the fifo business.
