### ISSUE TITLE
[Question] Speaker Server and OnOff Client compoistion.

### ISSUE THREAD

**Issue by pintu-sakariya** [project-chip/connectedhomeip#26119]
Device#1 Application device type composition
        Device ID = 0x0022 Speaker (Endpoint#1) - Cluster Server OnOff and Level 
        Device ID = 0x0103 OnOff Light Switch (Virtual - No physical switch) (Endpoint#2) - Cluster 0x0006 (Client)
Question: Is this valid combination of node (Physical device) as Speaker?

Device#2 Simple Light OnOff
       Device ID = 0x0100 OnOff Light (Endpoint#1) - Cluster 0x0006 (Server)

Device#3 Chip-tool Commissioner/Administrator

Questions:
Is it possible to bind device Device#1 Endpoint#2 (OnOff Client) and Device#2 Endpoint#1 (OnOff Server) via chip-tool binding?
Does binding client cluster need to add for Device#1 at endpoint#0 (Root node) or Endpoint#2?

---------------- I am trying to modify light switch example to add speaker endpoint, I am not able to see any modification on either .zap or .matter. The other header and cpp file is generated where these files need to copy? Below command i used to modify endpoint. 
Project location connectedhomeip/examples/light-switch-app/light-switch-common
 $./scripts/tools/zap/run_zaptool.sh examples/light-switch-app/light-switch-common/light-switch-app.zap
total 508
-rw-rw-r-- 1   280615 Apr 17 13:59 light-switch-app.zap
-rw-rw-r-- 1    85224 Apr 17 13:59 light-switch-app.matter
-rw-rw-r-- 1      929 Apr 17 13:59 BUILD.gn
**-rw-rw-r-- 1    34702 Apr 17 18:10 IMClusterCommandHandler.cpp
-rw-rw-r-- 1     9834 Apr 17 18:10 gen_config.h
-rw-rw-r-- 1    61817 Apr 17 18:10 endpoint_config.h
-rw-rw-r-- 1     2385 Apr 17 18:10 CHIPClusters.h
-rw-rw-r-- 1     3989 Apr 17 18:10 CHIPClientCallbacks.h
-rw-rw-r-- 1    22573 Apr 17 18:10 access.h**
Could you please help with how these generated file used with actual application (Where needs to copy or add in BUILD.gn? Why *.zap and *matter file not modified?)

**Comment by bzbarsky-apple** [comment]
>  Question: Is this valid combination of node (Physical device) as Speaker?

If the switch and speaker bits are on different endpoints, yes.

> Is it possible to bind device Device#1 Endpoint#2 (OnOff Client) and Device#2 Endpoint#1 (OnOff Server) via chip-tool binding?

Yes.

>  Does binding client cluster need to add for Device#1 at endpoint#0 (Root node) or Endpoint#2?

Endpoint#2.

> Why *.zap and *matter file not modified?

I would expect the .zap file to be modified when you save in zAP and the .matter file to be modified when you re-run the non-build-time codegen after modifying the .zap file.

**Comment by pintu-sakariya** [comment]
ZAP CLI UI instead of pressing generate, I have file->save button. It's updating .zap file.  
If possible could you add help to update this step in https://project-chip.github.io/connectedhomeip-doc/code_generation.html

**Comment by bzbarsky-apple** [comment]
@pintu-sakariya Which step?  The relevant bit of that document is https://project-chip.github.io/connectedhomeip-doc/code_generation.html#flow-for-updating-an-application-zap-file

**Comment by pintu-sakariya** [comment]
While opening UI there is option to generate which is generating below files, To update zap file will new addition need to save zap file instead of generating. It is creating bit confusion like what needs to do with below files. If we save .zap it will do compile time generation of this file. So https://project-chip.github.io/connectedhomeip-doc/code_generation.html#flow-for-updating-an-application-zap-file is confusion for me at least.
-rw-rw-r-- 1 34702 Apr 17 18:10 IMClusterCommandHandler.cpp
-rw-rw-r-- 1 9834 Apr 17 18:10 gen_config.h
-rw-rw-r-- 1 61817 Apr 17 18:10 endpoint_config.h
-rw-rw-r-- 1 2385 Apr 17 18:10 CHIPClusters.h
-rw-rw-r-- 1 3989 Apr 17 18:10 CHIPClientCallbacks.h
-rw-rw-r-- 1 22573 Apr 17 18:10 access.h

**Comment by pintu-sakariya** [comment]
You can close this question, I am observing crash for binding using chip-tool, command is reaching while processing it is crashing Will create new question.

**Comment by bzbarsky-apple** [comment]
> While opening UI there is option to generate 

That option will not do the right thing.  The right thing will be done by the scripts in the Matter repository.  The instructions linked say to use the ZAP UI to edit (_not_ generate), then run `generate.py`.
