### ISSUE TITLE
[BUG] Commissioning fails at "AttestationVerification" when trying to pair Matter Devices 

### ISSUE THREAD

**Issue by smishra-volansys** [project-chip/connectedhomeip#26142]
### Reproduction steps

**Environment:**

1. Gateway/Router running the Matter Stack.
2. Eve Matter Supported Device ( currently using Eve Energy PowerPoint https://www.evehome.com/en/eve-energy) (US Variant)

**Steps:**'

1. Using the Chip Tool run the command to commission the Eve Device in the Network. 
2. The Device's Mac ID is detected as shown in the Logs attached and moves forward with the process of commissioning. 
4. After reaching the Step8 of Attestation Verification it fails and aborts the commissioning process  

We are trying to pair the Eve Matter devices available in the Market using Chip-Tool.

Please note that we have a custom matter-supported device running the light example which easily gets commissioned without any errors and we are also able to control the same. 

We are using the Eve Energy devices' Powerpoint to commission it via ble-thread which supports our Network. 
As a part of the prerequisites, we are maintaining the OpenThread Dataset and also the Device is placed near the setup. 

### Bug prevalence

Frequent

### GitHub hash of the SDK that was being used

v1.0-branch

### Platform

other

### Platform Version(s)

v1.0-branch

### Anything else?

[attestation_error.log](https://github.com/project-chip/connectedhomeip/files/11261110/attestation_error.log)

**Comment by bzbarsky-apple** [comment]
```
[1681800961.050730][3631:3648] CHIP:CTL: Failed in verifying 'Attestation Information' command received from the device: err 101. Look at AttestationVerificationResult 
```
101 is `kPaaNotFound`.

You didn't include the exact way you ran chip-tool, but by default chip-tool only uses the test PAA.  The light example app in the tree uses the test PAA, so it will work with chip-tool.  But production devices would not be using the test PAA; they would be using real PAAs.

You probably want to pass a `--paa-trust-store-path` argument to chip-tool which points to the directory that contains the PAA certs you want to trust.  If you just want to trust them all, passing the `credentials/development/paa-root-certs` or `credentials/production/paa-root-certs` directory in the Matter repo should work.

**Comment by smishra-volansys** [comment]
We ran the chip tool by using the below command:
chip-tool pairing ble-thread <nodeID> <hexkey of the OT dataset> <Discriminator and Pin of the device>

**Comment by smishra-volansys** [comment]
I tried adding both the Certificate path (i.e. developers and production). Development certificate gives the same response as yes it has test PAA. 

But when tried with Production Certificates I am getting the following error of ERR 601.

![image](https://user-images.githubusercontent.com/121939154/233549864-115a75d9-7c3a-4ea7-8049-fa57ce22f039.png)

**Comment by bzbarsky-apple** [comment]
601 is `kCertificationDeclarationNoCertificateFound`.  Presumably you also need to pass `--cd-trust-store-path` pointing to the relevant root certs.

**Comment by fxm2022** [comment]
For eve matter device, you may need DigiCert PAA (https://webui.dcl.csa-iot.org/).

**Comment by bzbarsky-apple** [comment]
@fxm2022 `credentials/production/paa-root-certs` has a DigiCert PAA of some sort...

**Comment by smishra-volansys** [comment]
Thank you for the Information @bzbarsky-apple  and @fxm2022. 
I have a question,
Do we need to generate our own certificate for the Matter Gateway that we have developed (by taking the membership of CSA or something of that sort) or is there some sort of certificate already available out there that we can use to make our own trust decisions before we move ahead with the CSA Membership?

**Comment by bzbarsky-apple** [comment]
@smishra-volansys If your device is going to be commissioned by other things, it will need certificates issued by CSA.

If your device is commissioning other things, it just needs to recognize their certificates.

**Comment by smishra-volansys** [comment]
@bzbarsky-apple No, our Device will not be commissioned by any entity as it is a Matter Controller itself or you can consider it as a Hub through which we commission other devices and control them using this custom gateway of ours. 
So, for development purposes, we have Eve Matter Devices and Motion Sensor from Heiman Tech, which is not getting paired/commissioned with the Gateway and throws the same error as attached above. 

Please let me know, if any further information is required on our end to understand the usecase.

**Comment by bzbarsky-apple** [comment]
Then you just need the relevant PAA and CD root certs, which are all public in the DCL....

**Comment by smishra-volansys** [comment]
![image](https://user-images.githubusercontent.com/121939154/235844653-950b0714-9663-4c5a-8c95-69a633a93371.png)
Hi @bzbarsky-apple ,
While we are giving the Path to the Cd-certs, it is giving such error all the time ! 
PFA Attached the snap of the same !

**Comment by bzbarsky-apple** [comment]
@smishra-volansys What SHA is that on?  With tip, line 487 in `src/credentials/attestation_verifier/DefaultDeviceAttestationVerifier.cpp` does not have a CHIP_ERROR_NO_MEMORY error on it.

**Comment by bzbarsky-apple** [comment]
That said, the most likely cause is that your `CHIP_CONFIG_NUM_CD_KEY_SLOTS` (default 5) is too low for the number of CD keys you are trying to load.

**Comment by smishra-volansys** [comment]
@bzbarsky-apple We are using the v1.0-branch for this phase of Development due to the stability. 
The current Chip tool build is from this commit id: 561d23d0db215a99705ff0696e73853c8edf11b2 committed lastly on September 30. Should I take a latest Pull and try ?

**Comment by smishra-volansys** [comment]
@bzbarsky-apple I changed it to a larger Value and now the issue is Solved! 
Thanks for mentioning that! 
Sometimes, while pairing the device it fails in the ThreadNetworkEnable stage now, after providing the proper PAAs that we asked for from the Vendor of that device. Always giving a timeout error.
Does this mean that the Device is unable to send a response back on time?

**Comment by smishra-volansys** [comment]
We are able to commission the Device successfully now after using the new PAA certificates provided by the Vendor.
Thanks for the Constant support over this thread @bzbarsky-apple. Appreciate it !

**Comment by bzbarsky-apple** [comment]
@smishra-volansys You're welcome!

**Comment by Vardhman-Modi** [comment]
> . The light example app in the tree uses the test PAA, so it will work with chip-tool. But production devices woul

Can you share PAA certificate of EVE Energy Smart Plug Device. I am facing same problem.

**Comment by varun2103** [comment]
@bzbarsky-apple Hey could you please say me in which file I can find "CHIP_CONFIG_NUM_CD_KEY_SLOTS" this parameter

**Comment by bzbarsky-apple** [comment]
@varun2103 It's defaulted in src/lib/core/CHIPConfig.h but you should just set it in the app config file for your app...
