### ISSUE TITLE
[BUG] The API signature is broken for 'ByteSpan' from 'GetWiFiBssId'

### ISSUE THREAD

**Issue by hyunuktak** [project-chip/connectedhomeip#26155]
### Reproduction steps

CHIP_ERROR chip::DeviceLayer::DiagnosticDataProvider::GetWiFiBssId(ByteSpan & value);
CHIP_ERROR chip::DeviceLayer::DiagnosticDataProviderImpl::GetWiFiBssId(ByteSpan & bssId) override;

- Change to `MutableByteSpan` from `ByteSpan`.
- Build some examples
- Get error messages

It is handing a pointer to the stack of local function to the caller. it will not work right.
When local function returns, that memory will no longer be holding anything useful.
So when the caller tries to read the data, they will get garbage or occur crash.
Some platforms have to modify this part.
And also, the real problem is that the API signature is broken.
The `ByteSpan` in `GetWiFiBssId` has to be updated according to new signature.
New signature is :  CHIP_ERROR GetWiFiBssId(MutableByteSpan & value);

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

e1a7322

### Platform

core

**Comment by bzbarsky-apple** [comment]
> https://github.com/project-chip/connectedhomeip/commit/e1a7322889a80c4e0da51d0c5a197c617309e9fc

I have no idea where this SHA is coming from, but on master right now GetWiFiBssId takes a MutableByteSpan.  See #26088
