### ISSUE TITLE
[BUG] Flashing bridge-app on M5 stack does not provide pairing QR code link (url) nor does it provide PIN code in the logs

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#26152]
### Reproduction steps

SHA used: 0f1fc1b230eca4b4ce2f45c4a8cf1ce238284e96

Post building and flashing of bridge-app for M5board, the logs do not provide the pairing QR code link nor does it provide any PIN code (short pin) 

**Steps to reproduce:**

**Build the bridge-app:**

1. cd ~/connectedhomeip
2. git reset --hard 0f1fc1b230eca4b4ce2f45c4a8cf1ce238284e96
3. git clean -Xdf
4. git submodule update --init
5. export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
6. source scripts/bootstrap.sh
7. source scripts/activate.sh
8. cd ${HOME}/tools/esp-idf
9. git submodule update --init
10. ./install.sh
11. . ./export.sh
12. cd ~/connectedhomeip/examples/bridge-app/esp32
13. idf.py build

**Flash the M5 board:**

Obtain the port using the command -> ls/dev/tty.*

idf.py -p /dev/tty.SLAB_USBtoUART flash monitor

**Note:** when I tried to pair with default code 34970112332 -> it worked and I was able to control the endpoints, but the logs by itself does not provide any pairing information

**Attaching the M5 logs;**

[brdige-app_M5_logs.txt](https://github.com/project-chip/connectedhomeip/files/11266502/brdige-app_M5_logs.txt)

### Bug prevalence

Today

### GitHub hash of the SDK that was being used

0f1fc1b230eca4b4ce2f45c4a8cf1ce238284e96

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
Yes, the bridge-app example never calls `PrintOnboardingCodes`.
