### ISSUE TITLE
[BUG] Cannot send commands to bridge app window covering ( 0xc3 (UNSUPPORTED_CLUSTER) )

### ISSUE THREAD

**Issue by nmtoan91** [project-chip/connectedhomeip#26174]
### Reproduction steps

I'm deploying a window covering the bridged app based on example/linux/ .

All attributes are readable, for example:
`./chip-tool windowcovering read current-position-lift `  ===> OK
but when I try to send a command:
`./chip-tool windowcovering up-or-open `    ===>  0xc3 (UNSUPPORTED_CLUSTER)

then, when I removed the UpOrOpen command ID from macro, I got a different error:
`./chip-tool windowcovering up-or-open`     ===>  0xc3 (UNSUPPORTED_COMMAND)

### Bug prevalence

all the time

### GitHub hash of the SDK that was being used

latest

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
@nmtoan91 The window covering cluster requires a delegate.  Are you registering it?

That said, even if you are, chances are https://github.com/project-chip/connectedhomeip/issues/25984 makes that not work.
