### ISSUE TITLE
[Platform] Question of Darwin build option

### ISSUE THREAD

**Issue by joonhaengHeo** [project-chip/connectedhomeip#26206]
### Reproduction steps

I have a question regarding Darwin builds.

1. When building Darwin App (src/darwin), is there a Build Option used for libCHIP.a?
2. Is there anything I can do to build the library with minimal library size?

### Platform

darwin

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
> When building Darwin App (src/darwin), is there a Build Option used for libCHIP.a?

It depends on exactly how you are building it, and exactly what you mean by "Build Option".

> Is there anything I can do to build the library with minimal library size?

The thing that would probably help the most here is stripping debug symbols from the built library.

All of this only matters if you're not using the system Matter.framework, of course.

**Comment by joonhaengHeo** [comment]
@bzbarsky-apple 
Thank you for your response.

I'm looking for a way to reduce the size of the libCHIP.a image when building the Matter.Framework. Using this, we are trying to implement a Matter-supported iOS App.

Please ask if there are any additional places to check.

**Comment by joonhaengHeo** [comment]
Additionally, can you tell me how to clear the debug symbol you mentioned?

**Comment by bzbarsky-apple** [comment]
@joonhaengHeo If you are building your own Matter.framework, presumably see `src/darwin/Framework/chip_xcode_build_connector.sh` for the builds that build libCHIP.  Make sure you are not building a Debug configuration.  Past that, you could try setting `optimize_debug_level="s"` in the gn args in that script.

And for removing the debug symbols, `strip`, but which exact arguments depends on exactly what you are trying to do.

**Comment by woody-apple** [comment]
Please re-open if you still have questions here.
