### ISSUE TITLE
dynamic bridge example build error(no viable overloaded) [BUG] 

### ISSUE THREAD

**Issue by jinbiaochenstayhungry** [project-chip/connectedhomeip#26203]
### Reproduction steps

1、update zap project to the latest.
2、/scripts/tools/zap/generate.py  .... bridge-app.zap
3、then build dynamic bridge example,will show error log below:

gen/bridge/BridgeGlobalStructs.h:19:21: error: no viable overloaded '='
      applicationID = t.applicationID;

### Bug prevalence

whenerver i do this

### GitHub hash of the SDK that was being used

76eaffc1571cb240859a079693405627bf162c29

### Platform

darwin

### Anything else?

after i check the code in matter and found that, new version zap will generate elements below in .matter file:

struct ApplicationStruct {
    int16u catalogVendorID = 0;
    char_string applicationID = 1;
}

struct LabelStruct {
    char_string<16> label = 0;
    char_string<16> value = 1;
}

and in the src/app/zzz_template/common/override i can see:

  case 'char_string':
  case 'long_char_string':
    return 'chip::CharSpan';

which means   t.applicationID  will be a chip::CharSpan type,
but in scripts/py_matter_idl/matter_idl/generators/types.py,  check the code

elif lowercase_name in ['char_string', 'long_char_string']:
        return BasicString(idl_name=lowercase_name, is_binary=False, max_length=data_type.max_length)
 
applicationID will be generate  as  type std::string.

which case  no viable overloaded.
more detail error log:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:905:19: note: candidate function not viable: no known conversion from 'chip::CharSpan' (aka 'Span<const char>') to 'const std::string' for 1st argument

i think this  is a bug, or may be i miss something.

**Comment by bzbarsky-apple** [comment]
> https://github.com/project-chip/connectedhomeip/commit/76eaffc1571cb240859a079693405627bf162c29

This was fixed since then.  See https://github.com/project-chip/connectedhomeip/pull/26129.  Update to a newer SHA, please.
