### ISSUE TITLE
[BUG] Error flashing Matter light example into esp32c3

### ISSUE THREAD

**Issue by LinJiaDeng** [project-chip/connectedhomeip#26255]
### Reproduction steps

I'm following the following espressif documentation for Matter implementation: 
[documentation](https://docs.espressif.com/projects/esp-matter/en/latest/esp32c3/developing.html) 

Installed the prerequisites for ESP IDF:

`mkdir -p ~/esp
cd ~/esp
git clone -b v4.4.3 --recursive https://github.com/espressif/esp-idf.git`

`cd ~/esp/esp-idf
./install.sh esp32`

Getting the Repositories:

`cd esp-idf
source ./export.sh
cd ..

git clone --depth 1 https://github.com/espressif/esp-matter.git
cd esp-matter
git submodule update --init --depth 1
cd ./connectedhomeip/connectedhomeip
./scripts/checkout_submodules.py --platform esp32 linux --shallow
cd ../..
./install.sh
cd ..`

After getting the Repositories:

1. `cd esp-idf; source ./export.sh; cd ..`
2. `cd esp-matter; source ./export.sh; cd..`
3. `cd esp-matter/examples/light`
4. `idf.py set-target esp32c3`
5. `idf.py -p /dev/ttyUSB0 flash`

### Bug prevalence

Everytime I try to flash an example

### GitHub hash of the SDK that was being used

Espressif

### Platform

esp32

### Anything else?

Screenshot of error message

![Error_for_github](https://user-images.githubusercontent.com/61759437/234415999-884f2788-de22-43dc-8e8c-e0536cd6bde1.png)

**Comment by bzbarsky-apple** [comment]
This sounds like an issue that should be reported at https://github.com/espressif/esp-matter/issues
