### ISSUE TITLE
[BUG] mode-select-server always includes on-off-server.h, even if DEPONOFF is '0'

### ISSUE THREAD

**Issue by eric-ocasio-nxp** [project-chip/connectedhomeip#26252]
### Reproduction steps

Create an application with mode select server and no on-off cluster. Try to build and it will fail since EMBER_AF_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT is not defined.

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

Latest

### Platform

darwin

### Anything else?

I think the include of on-off-server.h should be gated, similar to what is done in emberAfModeSelectClusterServerInitCallback. I don't know if the same macro should be used, but the general idea is the same.

Dependency with On/Off is optional in the spec.

**Comment by bzbarsky-apple** [comment]
Yes, this should probably be conditioned on `EMBER_AF_PLUGIN_ON_OFF`.

@eric-ocasio-nxp can you create a PR for that, since you have a way to test it?

**Comment by eric-ocasio-nxp** [comment]
Done.

https://github.com/project-chip/connectedhomeip/pull/26263
