### ISSUE TITLE
[Platform][ASR] add asr582x & asr595x support 

### ISSUE THREAD

**Issue by tx2rx** [project-chip/connectedhomeip#26294]
add asr platform support

brief:
ASR582X is a low-power, high-performance, highly integrated combo SoC supporting 1x1 IEEE 802.11 b/g/n and BLE 5.1. The chip integrates RF transceiver, 802.11/BLE PHY + MAC, Arm China STAR-MC1 Processor, multiple peripheral interfaces, AOA/AOD, Real Time Counter (RTC) and a complete power management module.

ASR595X is a low-power, high-performance, highly integrated combo SoC supporting 1x1 IEEE 802.11 b/g/n/ax and BLE 5.1. Thanks to the uniquely designed power management circuitry, this chip significantly reduces power consumption and peripheral components.

**Comment by tx2rx** [comment]
https://github.com/project-chip/connectedhomeip/pull/26295

**Comment by mideayanghui** [comment]
Nice, keep go on

**Comment by tx2rx** [comment]
https://github.com/project-chip/connectedhomeip/pull/26361
