### ISSUE TITLE
[Darwin] Add availability annotations for Dishwasher Control cluster

### ISSUE THREAD

**Issue by rbultman** [project-chip/connectedhomeip#26297]
### Reproduction steps / Feature

To reproduce:
Run `zap_regen_all.py` on [branch](https://github.com/rbultman/connectedhomeip/tree/addDishControlClusterXML) associated with PR #26284. 

Warnings similar to the following are generated:
```
WARNING: Missing "introduced" entry for: 'DishwasherControl' '{"isForIds":true,"minimalRelease":"First major API revamp","attribute":"SteamWash"}'
```

### Platform

other

### Platform Version(s)

Ubuntu 22.04

### Type

Unit tested

### (Optional) If manually tested please explain why this is only manually tested

The type above is probably wrong.

### Anything else?

@bzbarsky-apple requested that this issue be entered.

**Comment by bzbarsky-apple** [comment]
Dishwasher control removed from the fall ballot.
