### ISSUE TITLE
[Feature] support for MGM240P/xGM240P board based on the Series 2 EFR32MG24 SoC

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#26350]
### Feature description

Hello,

Could you add support for [MGM240P/xGM240P board](https://www.silabs.com/documents/public/data-sheets/mgm240p-datasheet.pdf) based on the Series 2 EFR32MG24 SoC?

_The MGM240P wireless module is built around the EFR32MG24 Wireless SoC with a 32-bit ARM Cortext-M33 core processor running at 39 MHz with 1536 kb Flash memory and 256 kb RAM. The MGM240P works with common 802.15.4 wireless protocols (Matter®, Zigbee®, and OpenThread®) as well as Bluetooth® Low Energy 5.3. The MGM240P supports Silicon Labs' [Secure Vault™](https://www.silabs.com/security/secure-vault) for Thread applications._

Regards

### Platform

efr32

**Comment by jmartinez-silabs** [comment]
MGM240P refers to a Silicon Labs module family and not an individual board.

From what I read on the PR you created you are trying to add support for the Sparkfun board

The SparkFun board is already supported and is referenced as BRD2704A.
Use that board name to build your sample app for the SparkFun board. We can some notes to clearly identify that the board name has the Sparkfun one.

If you require support for a different board let us know. We can see what can be done or we can provide info on how to support the board you want locally
