### ISSUE TITLE
Why do we need Hub for commisioning

### ISSUE THREAD

**Issue by mustafayuce33** [project-chip/connectedhomeip#26359]
### Reproduction steps

We develop a dynamic-bridge-app and bridge can be commissioned to Apple Home. But we need an Apple TV for it. Our bridge runs on raspberry pi. 

I do not understand why we need a hub (Apple TV) for commissioning our bridge to Apple Home. It seems that thread border router is needed even we do not have thread devices. Is that correct?

Can we commission my dynamic bridge without any hub (Apple Tv or Google Nest for Google Home)?

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/commit/b9d32ecefd004adb7cc4c70a5f4a567dca199da0

### Platform

raspi

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
> I do not understand why we need a hub (Apple TV) for commissioning our bridge to Apple Home.

That has nothing to do with Matter per se.   It's something about the way Apple Home works right now.

> It seems that thread border router is needed even we do not have thread devices

You don't need a Thread border router if the device does not use Thread.  But Apple Home right now needs a resident (hub) to commission Matter devices.

> Can we commission my dynamic bridge without any hub (Apple Tv or Google Nest for Google Home)?

You can if you're not commissioning it into Apple Home or Google Home.  Other fabrics/ecosystems/etc may have different policies.
