### ISSUE TITLE
[Feature] [EFR32] Adding pairing QRcode URL in the console at boot

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#26394]
### Feature description

Hello,

Could you print the link to the pairing QRcode in the console at boot in order to perform the pairing with boards without LCD screen?
I can't find it from the current state of the program:

```
SEGGER J-Link V7.88 - Real time terminal output
Silicon Labs J-Link OB compiled Sep 30 2022 13:05:09 V1.0, SN=449050146
Process: JLinkExe
[00:00:00.000][silabs ]==================================================
[00:00:00.000][silabs ]SiLabs-Light-Switch starting
[00:00:00.000][silabs ]==================================================
[00:00:00.000][silabs ]Init CHIP Stack
[00:00:00.000][silabs ]Initializing OpenThread stack
[00:00:00.000][info  ][DL] OpenThread started: OK
[00:00:00.000][info  ][DL] Setting OpenThread device type to ROUTER
[00:00:00.000][silabs ]Starting OpenThread task
[00:00:00.000][info  ][SVR] Subscription persistence not supported
[00:00:00.000][info  ][SVR] Server initializing...
[00:00:00.000][detail][FP] Initializing FabricTable from persistent storage
[00:00:00.000][info  ][TS] Last Known Good Time: [unknown]
[00:00:00.000][info  ][TS] Setting Last Known Good Time to firmware build time 2023-05-05T11:33:55
[00:00:00.000][info  ][DMG] AccessControl: initializing
[00:00:00.000][info  ][DMG] Examples::AccessControlDelegate::Init
[00:00:00.000][info  ][DMG] AccessControl: setting
[00:00:00.000][info  ][D[00:00:30.016][detail][DL] bleAdv Timeout : Start slow advertissment
```

Regards

### Platform

efr32

**Comment by mkardous-silabs** [comment]
@lboue The URL to get the QR code is already printed but might get truncated because of the high volume of logs at boot.

With the matter shell, you are able to get the commissioning information.

**Comment by lboue** [comment]
@mkardous-silabs 
When flashing from SimplicityStudio projet example. Matter shell works fine in this case.
I can't get anything from the serial console when flashing from connectedhomeip repo. I can't see URL to get the QR code through SEGGER J-Link neither.
Did I miss some parameter to access to matter shell?

**Comment by mkardous-silabs** [comment]
By default, on the Connectedhomeip and Silicon Labs repo, the ot-cli is enabled but not the matter shell.
To enable the matter shell, add `chip_build_libshell=true` to the build command.

For example:
`./scripts/examples/gn_efr32_example.sh examples/lighting-app/silabs/efr32 out/lighting-app BRDXXXX chip_build_libshell=true`

**Comment by mkardous-silabs** [comment]
Once in the matter shell, to get the URL you can do `onboardingcodes ble` for the ble commissioning

**Comment by lboue** [comment]
> By default, on the Connectedhomeip and Silicon Labs repo, the ot-cli is enabled but not the matter shell. To enable the matter shell, add `chip_build_libshell=true` to the build command.
> 
> For example: `./scripts/examples/gn_efr32_example.sh examples/lighting-app/silabs/efr32 out/lighting-app BRDXXXX chip_build_libshell=true`

I didn't notice any changes with  `chip_build_libshell=true` argument.

I am getting the same console log:
...................
###RTT Client: Connected.

SEGGER J-Link V7.88 - Real time terminal output
Silicon Labs J-Link OB compiled Sep 30 2022 13:05:09 V1.0, SN=449050146
Process: JLinkExe
[00:00:00.000][silabs ]==================================================
[00:00:00.000][silabs ]SiLabs-Light starting
[00:00:00.000][silabs ]==================================================
[00:00:00.000][silabs ]Init CHIP Stack
[00:00:00.000][info  ][DL] Setting device name to : "SiLabs-Light"
[00:00:00.000][silabs ]Initializing OpenThread stack
[00:00:00.000][info  ][DL] OpenThread started: OK
[00:00:00.000][info  ][DL] Setting OpenThread device type to ROUTER
[00:00:00.000][silabs ]Starting OpenThread task
[00:00:00.000][info  ][SVR] Subscription persistence not supported
[00:00:00.000][info  ][SVR] Server initializing...
[00:00:00.000][detail][FP] Initializing FabricTable from persistent storage
[00:00:00.000][info  ][TS] Last Known Good Time: [unknown]
[00:00:00.000][info  ][TS] Setting Last Known Good Time to firmware build time 2023-05-05T23:07:57
[00:00:00.000][info  ][DMG] AccessControl: initializing
[00:00:00.000][info  ][DMG] Examples::AccessControlDelegate::Init
[00:00:00.000][
[00:00:30.016][detail][DL] bleAdv Timeout : Start slow advertissment

Do I have to set `enable_openthread_cli=false`?

**Comment by lboue** [comment]
And the detailed build log:
[build_light_shell.log](https://github.com/project-chip/connectedhomeip/files/11410172/build_light_shell.log)

**Comment by lboue** [comment]
Here is what I get with a demo program in SimplicityStudio (MatterLightOverThread).
I have the Matter console via the serial port.

```
matterCli > help
  base64          Base64 encode / decode utilities
  exit            Exit the shell application
  help            List out all top level commands
  version         Output the software version
  ble             BLE transport commands
  config          Manage device configuration. Usage to dump value: config [param_name] and to set some values (discriminator): config [param_name] [param_value].
  device          Device management commands
  onboardingcodes Dump device onboarding codes. Usage: onboardingcodes none|softap|ble|onnetwork [qrcode|qrcodeurl|manualpairingcode]
  dns             Dns client commands
  ota             OTA commands
  echo            Echo back provided inputs
  log             Logging utilities
  rand            Random number utilities
  otcli           Dispatch OpenThread CLI command
Done
matterCli > onboardingcodes ble qrcode
MT:6FCJ142C00KA0648G00
Done

matterCli > onboardingcodes ble qrcodeurl
https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3A6FCJ142C00KA0648G00
Done
```
I would like to achieve the same behavior with this code

**Comment by lboue** [comment]
> HI @lboue,
> 
> I've been able to reproduce your issue and I can help you correct it.
> 
> As it turns out, there are differences in the serial configuration between the SMG (Silabs Matter on Github/connectedhomeip) and Studio/GSDK builds. I'm not sure why, and will investigate. A guess is that it _may_ have to do with some Sparkfun device ecosystem interface. But for your initial question, this is what you can do to get your SMG version going:
...
> Let us know how this works for you.

Thank you very much for taking the time to investigate. I'll give it a try tomorrow and see if it works for me.

**Comment by lboue** [comment]
Config for BRD4316A is OK in the same repo for RX and TX pin :
[sl_uartdrv_eusart_vcom_config.h]https://github.com/SiliconLabs/sdk_support/blob/2bc3f28d778850417f34c7201cbe78bd72e3ee78/matter/efr32/mgm24/BRD4316A/config/sl_uartdrv_eusart_vcom_config.h#L90)


```
// EUSART0 TX on PA05
#define SL_UARTDRV_EUSART_VCOM_TX_PORT           gpioPortA
#define SL_UARTDRV_EUSART_VCOM_TX_PIN            5

// EUSART0 RX on PA06
#define SL_UARTDRV_EUSART_VCOM_RX_PORT           gpioPortA
#define SL_UARTDRV_EUSART_VCOM_RX_PIN            6
```

So it seems that the configuration is incorrect only for the board BRD2704A:
![image](https://github.com/project-chip/connectedhomeip/assets/938089/d5b5d3b7-7355-47b2-8fbd-4e16f9a7a36a)

**Comment by silabs-AKates** [comment]
Hi @lboue, 

Yes, I hope this Port/Pin change was made just for the Sparkfun board. I still haven't discovered if there is a good reason for the change and I'm going to file a bug at Silabs to pursue it. 

My understanding was that you were asking about the Sparkfun MGM240P board, BRD2704A. Was that incorrect?

Are you still having difficulty getting serial on your board, and which board is it?

-Alex

**Comment by lboue** [comment]
> Hi @lboue,
> 
> Yes, I hope this Port/Pin change was made just for the Sparkfun board. I still haven't discovered if there is a good reason for the change and I'm going to file a bug at Silabs to pursue it.
> 
> My understanding was that you were asking about the Sparkfun MGM240P board, BRD2704A. Was that incorrect?

Yes it is.

> Are you still having difficulty getting serial on your board, and which board is it?
Yes. I cleared the flash of the board, modified the source code then compiled in a new folder and flashed.
I haven't seen a difference and still don't get the matter shell.


```
commander device masserase

rm -rf out/light*
vim third_party/silabs/matter_support/matter/efr32/mgm24/BRD2704A/config/sl_uartdrv_eusart_vcom_config.h
grep --color SL_UARTDRV_EUSART_VCOM_ third_party/silabs/matter_support/matter/efr32/mgm24/BRD2704A/config/sl_uartdrv_eusart_vcom_config.h
...
#define SL_UARTDRV_EUSART_VCOM_PERIPHERAL        EUSART0
#define SL_UARTDRV_EUSART_VCOM_PERIPHERAL_NO     0
#define SL_UARTDRV_EUSART_VCOM_TX_PORT           gpioPortA
#define SL_UARTDRV_EUSART_VCOM_TX_PIN            5
#define SL_UARTDRV_EUSART_VCOM_RX_PORT           gpioPortA
#define SL_UARTDRV_EUSART_VCOM_RX_PIN            6
#define SL_UARTDRV_EUSART_VCOM_CTS_PORT          gpioPortC
#define SL_UARTDRV_EUSART_VCOM_CTS_PIN           2
#define SL_UARTDRV_EUSART_VCOM_RTS_PORT          gpioPortC
#define SL_UARTDRV_EUSART_VCOM_RTS_PIN           4

./scripts/examples/gn_efr32_example.sh examples/lighting-app/silabs/efr32 out/lighting-app_uart BRD2704A chip_build_libshell=true
out/lighting-app_uart/BRD2704A/chip-efr32-lighting-example.flash.py

commander flash ~/SiliconLabs/bootloader_binaries/bootloader-storage-internal-single-512k-BRD2704A-gsdk4.2.s37
out/lighting-app_uart/BRD2704A/chip-efr32-lighting-example.flash.py
JLinkExe -device EFR32MG24AXXXF1536 -if SWD -speed 4000 -autoconnect  1
```

**Logs**
```
user@SL-Matter:~$ JLinkRTTClient
###RTT Client: ************************************************************
###RTT Client: *               SEGGER Microcontroller GmbH                *
###RTT Client: *   Solutions for real time microcontroller applications   *
###RTT Client: ************************************************************
###RTT Client: *                                                          *
###RTT Client: *       (c) 2012 - 2016  SEGGER Microcontroller GmbH       *
###RTT Client: *                                                          *
###RTT Client: *     www.segger.com     Support: support@segger.com       *
###RTT Client: *                                                          *
###RTT Client: ************************************************************
###RTT Client: *                                                          *
###RTT Client: * SEGGER J-Link RTT Client   Compiled Apr 28 2023 08:38:36 *
###RTT Client: *                                                          *
###RTT Client: ************************************************************

###RTT Client: -----------------------------------------------
###RTT Client: Connecting to J-Link RTT Server via localhost:19021 ...
###RTT Client: Connected.

SEGGER J-Link V7.88 - Real time terminal output
Silicon Labs J-Link OB compiled Sep 30 2022 13:05:09 V1.0, SN=449050146
Process: JLinkExe
###RTT Client: Connection lost. Going to reconnect.
###RTT Client: Connecting to J-Link RTT Server via localhost:19021 .......
###RTT Client: Connected.

SEGGER J-Link V7.88 - Real time terminal output
Silicon Labs J-Link OB compiled Sep 30 2022 13:05:09 V1.0, SN=449050146
Process: JLinkExe
[00:00:00.000][silabs ]==================================================
[00:00:00.000][silabs ]SiLabs-Light starting
[00:00:00.000][silabs ]==================================================
[00:00:00.000][silabs ]Init CHIP Stack
[00:00:00.000][info  ][DL] Setting device name to : "SiLabs-Light"
[00:00:00.000][silabs ]Initializing OpenThread stack
[00:00:00.000][info  ][DL] OpenThread started: OK
[00:00:00.000][info  ][DL] Setting OpenThread device type to ROUTER
[00:00:00.000][silabs ]Starting OpenThread task
[00:00:00.000][info  ][SVR] Subscription persistence not supported
[00:00:00.000][info  ][SVR] Server initializing...
[00:00:00.000][detail][FP] Initializing FabricTable from persistent storage
[00:00:00.000][info  ][TS] Last Known Good Time: 2023-05-10T21:21:41
[00:00:00.000][info  ][DMG] AccessControl: initializing
[00:00:00.000][info  ][DMG] Examples::AccessControlDelegate::Init
[00:00:00.000][info  ][DMG] AccessControl: setting
[00:00:00.000][info  ][DMG] DefaultAclStorage: initia
```

**Comment by lboue** [comment]
@silabs-AKates 

You are right. I made a mistake, I was using he J-Link RTT Viewer application.
So I checked with PuTTY this time and I confirm that it works.
I get the matterCli. 
```
matterCli > help
  base64          Base64 encode / decode utilities
  exit            Exit the shell application
  help            List out all top level commands
  version         Output the software version
  ble             BLE transport commands
  config          Manage device configuration. Usage to dump value: config [param_name] and to set some values (discriminator): config [param_name] [param_value].
  device          Device management commands
  onboardingcodes Dump device onboarding codes. Usage: onboardingcodes none|softap|ble|onnetwork [qrcode|qrcodeurl|manualpairingcode]
  dns             Dns client commands
  ota             OTA commands
  echo            Echo back provided inputs
  log             Logging utilities
  rand            Random number utilities
  otcli           Dispatch OpenThread CLI command
Done
matterCli > onboardingcodes ble
QRCode:            MT:6FCJ142C00KA0648G00
QRCodeUrl:         https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3A6FCJ142C00KA0648G00
ManualPairingCode: 34970112332
Done
```

Thanks

**Comment by ihidchaos** [comment]
On many other platforms (such as Zephyr-based Nordic and Telink), logging is enabled by default on both UART and RTT, and even if you use RTT to view logs, there is no interruption that can affect your development or debugging experience.

I would like to know why Silabs does not redirect logs to UART as well by default, and why not optimize the default RTT_Conf configuration to make the logging experience better?

I think it can be frustrating when you build your Lighting application with the default configuration and a development board such as BRD4187C, only to find that the logs are truncated and you have to manually configure it yourself to see all the logs, rather than having an out-of-the-box experience.

**Comment by lboue** [comment]
> On many other platforms (such as Zephyr-based Nordic and Telink), logging is enabled by default on both UART and RTT, and even if you use RTT to view logs, there is no interruption that can affect your development or debugging experience.
> 
> I would like to know why Silabs does not redirect logs to UART as well by default, and why not optimize the default RTT_Conf configuration to make the logging experience better?
> 
> I think it can be frustrating when you build your Lighting application with the default configuration and a development board such as BRD4187C, only to find that the logs are truncated and you have to manually configure it yourself to see all the logs, rather than having an out-of-the-box experience.

I agree, it would be easier if it were activated out of the box.

**Comment by jmartinez-silabs** [comment]
@lboue @ihidchaos @silabs-AKates 
I realize this is now an old/stale issue. 

I have however a few updates:
- SetupQRCode and QR code URL at printed at bootup. But Logs can be lost if RTT buffer is full.
- PB0 press now also prints you the SetupQrCode and URL to the QRcode so you can have it on-demand.
```
[74:58:26.113][info  ][SVR] SetupQRCode: [MT:6FCJ142C00KA0648G00]
[74:58:26.114][info  ][SVR] Copy/paste the below URL in a browser to see the QR Code:
[74:58:26.114][info  ][SVR] https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT%3A6FCJ142C00KA0648G00
```
- The RTT still has the same limitation and will drop traces when its buffer is full. 
- We are inquiring our internal apps support teams and customers if they are in favour of defaulting the sample apps to UART logs rather than RTT.

Some customers are used to/prefer RTT nonetheless.

I'll close this ticket as workarounds of the discussed limitations are in place and defaulting to UART will probably occurs in the near future.
