### ISSUE TITLE
[BUG] Read UniqueID failure with 134 error code

### ISSUE THREAD

**Issue by edWin-m** [project-chip/connectedhomeip#26410]
### Reproduction steps

Invoke `BasicInformationCluster(devicePtr, endpointId).readUniqueIDAttribute(callback)`

### Bug prevalence

every function call

### GitHub hash of the SDK that was being used

19909cecb91d2b0f4623c7f9144398eadd638c8c

### Platform

android, esp32

### Anything else?

Here is the CHIPTool app log [UntitledCHIPCluster134Error.txt](https://github.com/project-chip/connectedhomeip/files/11418895/UntitledCHIPCluster134Error.txt).  
@bzbarsky-apple I have already checked the [ERROR_CDDES.md](https://github.com/project-chip/connectedhomeip/blob/6c0c5ea6d2b8f38c6b36b83195b6ee55384bb599/docs/ERROR_CODES.md) and corresponds to  `CHIP_ERROR_INVALID_TIME`.  How is this related to the operation of reading attributes in `BasicInformationCluster`?

**Comment by bzbarsky-apple** [comment]
@edWin-m You're looking at the wrong error list.  This is interaction model status 0x86 (decimal 134), which is defined in the specification (see "8.10.1. Status Code Table").  It's UNSUPPORTED_ATTRIBUTE.

As in, the server application being used here does not support this optional attribute, which is a perfectly reasonable thing for it to do.
