### ISSUE TITLE
[TC-MOD-1.1]ModeSelect cluster -- ClusterRevision value missmatch 

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#26445]
**Problem**
As per Spec and test plan, cluster revision value should be 2 but currently getting cluster revision value as 1 in SDK .

**Expected behavior**: ClusterRevision value as 2

**Actual behavior** : ClusterRevision value as 1

**Steps to reproduce**
./chip-tool modeselect read cluster-revision 1 1

**System configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : Onnetwork
Commit-ID:6c0c5ea6d2b8f38c6b36b83195b6ee55384bb599
Dut application: all-clusters-app

**Test-Plan Reference:-**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/modeselect.adoc

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ModeSelect.adoc

**Log**
[TC-MOD-1.1.txt](https://github.com/project-chip/connectedhomeip/files/11429930/TC-MOD-1.1.txt)

**Comment by bzbarsky-apple** [comment]
The SDK does not yet implement revision 2 of the cluster. This is not just about bumping the revision number; support is also needed for ChangeToModeWithStatus, the EXT feature, etc.

**Comment by rbultman** [comment]
The mode select cluster has almost completely reverted back to its original state prior to the additions being moved into the modebase cluster.  The revision is still 2, however, but the only substantive change made was to remove the nullable quality from MfgCode.  Not sure how that affects your comment @bzbarsky-apple.

**Comment by bzbarsky-apple** [comment]
SDK implements revision 2, since it had MfgCode non-nullable to start with.  We should bump the revision in the SDK...

**Comment by andy31415** [comment]
Need just a version bump, assigning to myself (expecting just a zap file change)

**Comment by bzbarsky-apple** [comment]
> (expecting just a zap file change)

The XML also needs to be changed.
