### ISSUE TITLE
[TC-OO-1.1] ClusterRevision value missmatch in OnOff cluster.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#26469]
**Problem**
As per Spec, ClusterRevision attribute value should be 5 but currently getting ClusterRevision value as 4 in SDK .

**Expected behavior**: ClusterRevision value as 5

**Actual behavior** : ClusterRevision value as 4

**Steps to reproduce**
./chip-tool onoff read cluster-revision 1 1

**System configuration**
Chip-tool - RPI-4, 8GB RAM
DUT - RPI - RPI-4, 8GB RAM
Platform : Onnetwork
Commit-ID:6c0c5ea6d2b8f38c6b36b83195b6ee55384bb599
Dut application: all-clusters-app

**Spec Reference:-**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OnOff.adoc#ref_sec_3_8_1_1

**Log**
[TC-OO-1.1.txt](https://github.com/project-chip/connectedhomeip/files/11438543/TC-OO-1.1.txt)

**Comment by bzbarsky-apple** [comment]
This is presumably for the dead front updates, which have not happened yet.  @marktrayer
