### ISSUE TITLE
[BUG] need to commission matter device through IP

### ISSUE THREAD

**Issue by aravindone** [project-chip/connectedhomeip#26468]
### Reproduction steps

Step 1 : all cluster app is installed in esp32 devkit c and wifi ssid and password hardcoded in esp-Idf framework
Step 2 :  try to connect with python-repl tool using ip address

![image](https://github.com/project-chip/connectedhomeip/assets/96520442/c9291bea-06d2-4a50-af63-b6a8685d2732)

https://raw.githubusercontent.com/aravindone/aravindone/main/log%20for%20python%20repl%20with%20wifi%20credentials

### Bug prevalence

regular

### GitHub hash of the SDK that was being used

 ac810b1

### Platform

esp32

### Platform Version(s)

1.1.0-1.1

**Comment by aravindone** [comment]
@bzbarsky-apple @dhrishi @vivien-apple  Please comment on the error im facing

**Comment by dhrishi** [comment]
@aravindone Please check if your host machine running the python utility is connected to the same network as the ESP32? The logs show that the python-repl could not find the ESP32 device on the operational network and hence the commissioning timed out after a while.

**Comment by aravindone** [comment]
@dhrishi  im currently working in virtual ubuntu and the host was connected to the same network as ESP 32 network  and still the issue comes

**Comment by bzbarsky-apple** [comment]
@aravindone At the point when the esp32 starts operational advertising (the `mDNS service published: _matter._tcp` bits), does doing `avahi-browse _matter._tcp -r` on the machine where you are running the Python repl see the esp32?

> After commissioning with google home sample app and if i want to connect through chip-tool again commission need to be happen ? how it should be done.

You have to get the Google Home sample app to open a commissioning window.

**Comment by aravindone** [comment]
closing the ticket as the commission was successful in Direct ubuntu laptop

**Comment by tunm1228** [comment]
<img width="1493" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/42457760/2f132559-390c-402e-ac51-4d2b3d63118b">
For me, it's giving the same error

**Comment by aravindone** [comment]
@tunm1228  can you share the log and proper screenshot from python-repl.

**Comment by tunm1228** [comment]
I am using the command "./out/python_env/bin/chip-repl" and the error is as below
<img width="1495" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/42457760/1aec0ce0-202a-49ab-8898-1d54bded5efb">

**Comment by aravindone** [comment]
@tunm1228  have you tried with sudo with the command ?  and it says there is no config file in /tmp/repl-storage.json, you have to check that

**Comment by tunm1228** [comment]
I don't know what path this file is in. Do you know how to create it?

**Comment by aravindone** [comment]
@tunm1228 which commit are you using ?
