### ISSUE TITLE
Mode Select - refactored RVC Run status codes

### ISSUE THREAD

**Issue by plauric** [project-chip/connectedhomeip#26552]
[Matter 1.2]

The RVC Run cluster's status codes for the ChangeToModeResponse command have been renamed and renumbered. 

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6969/files

The SDK must be updated.

**Comment by hicklin** [comment]
Update [here](https://github.com/project-chip/connectedhomeip/pull/26508/commits/fb574f4be14b82d904a16ee8f69924e2ad3c22e9).

**Comment by woody-apple** [comment]
Marking as complete
