### ISSUE TITLE
Mode Select - renamed RVC cluster aliases

### ISSUE THREAD

**Issue by plauric** [project-chip/connectedhomeip#26551]
[Matter 1.2]

The RVC Run cluster was renamed RVC Run Mode Select. The RVC Clean cluster was renamed RVC Clean Mode Select. 

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6969/files

The SDK must be updated.

**Comment by hicklin** [comment]
Fixed [here](https://github.com/project-chip/connectedhomeip/pull/26508/commits/155039220a5f44d7701a9a260ff8059148843d59).

**Comment by woody-apple** [comment]
Marking complete
