### ISSUE TITLE
Mode Select - renamed struct field - SemanticTags -> ModeTags

### ISSUE THREAD

**Issue by plauric** [project-chip/connectedhomeip#26550]
The SemanticTags field of the ModeOptionStruct data type has been renamed ModeTags in Mode Select rev 2. The SDK must be updated.

https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6969/files

**Comment by hicklin** [comment]
The XML PR has been updated to this spec change [here](https://github.com/project-chip/connectedhomeip/pull/26508).

**Comment by woody-apple** [comment]
Marking complete
