### ISSUE TITLE
[Feature] Add temperature control cluster implementation

### ISSUE THREAD

**Issue by mideayanghui** [project-chip/connectedhomeip#26605]
### Feature description

 Implement the temperature control clusters, the example cluster server application and add the related SDK tests.

This PR depends on the XML PR for this cluster.  REVIEWERS: Please wait to review this PR until the XML PR is merged in this PR is no longer a draft PR.

XML PR:
https://github.com/project-chip/connectedhomeip/pull/26560

### Platform

all

**Comment by jadhavrohit924** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/commit/701fcb21f9a
