### ISSUE TITLE
[Feature] Android support pass caseAuthTag to matter-sdk from JNI

### ISSUE THREAD

**Issue by luobosu** [project-chip/connectedhomeip#26629]
### Feature description

For the JNI method :  CHIPDeviceController-JNI.cpp # onNOCChainGeneration
`
uint64_t adminSubject = env->CallLongMethod(controllerParams, getAdminSubject);
`

the **getAdminSubject** will return java signed long 64 bit number to JNI , but I need pass a Case-Auth-Tag which needs to be unsigned long 64 bit number .  

How can I pass CAT ?

### Platform

android

**Comment by stefano055415** [comment]
@luobosu 

Hi, how did you solve it?

I would have to set the adminSubject using the setAdminSubject() function, but it only accepts a long and as per the specific matter it would be necessary to pass 8 bytes without sign
