### ISSUE TITLE
ASR platform manager synchronization seems to be completely broken

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#26637]
See https://github.com/project-chip/connectedhomeip/pull/26361#pullrequestreview-1431308530

@tx2rx @andy31415

**Comment by bzbarsky-apple** [comment]
Note that I only reviewed PlatformManager and TimeSupport from https://github.com/project-chip/connectedhomeip/pull/26361 and both were broken.  I have extremely low confidence in any of the rest of it...

**Comment by tx2rx** [comment]
> Also, where is _TryLockChipStack implemented for ASR? I don't see it.

Because in src/ , that is not used before. Just in case ,we will add it soon later

**Comment by tx2rx** [comment]
src/include/platform/internal/GenericPlatformManagerImpl_FreeRTOS.ipp may cause the same problem.

**Comment by tx2rx** [comment]
In addition, src/include/platform/internal/GenericPlatformManagerImpl_FreeRTOS.ipp may cause the same problem:

        BaseType_t eventReceived = pdFALSE;
        {
            // Unlock the CHIP stack, allowing other threads to enter CHIP while
            // the event loop thread is sleeping.
            StackUnlock unlock;
            eventReceived = xQueueReceive(mChipEventQueue, &event, waitTime);
**StackLock lock;** // should it open lock again? @bzbarsky-apple 
        }

**Comment by tx2rx** [comment]
refer https://github.com/project-chip/connectedhomeip/pull/19470

**Comment by bzbarsky-apple** [comment]
> // should it open lock again?

It does, in the destructor of the StackLock.
