### ISSUE TITLE
[chiptool.py] Runner is not logging skipped steps as expected

### ISSUE THREAD

**Issue by ccruzagralopes** [project-chip/connectedhomeip#26638]
### Reproduction steps / Feature

Test Harness relies on log messages to indicate the moving from one step to another in the UI. Currently, when a step is skipped (because of PICS value), the chiptool runner is omitting the start of the skipped step. TH expects a log message like
`***** Test Step (...)`
before the skipping log
`**** Skipping (...)`
Currently, the runner is only logging the skipping message. So TH is skipping the wrong step in the UI.

Here are screenshots of logs produced by the `chiptool.py` runner and the `chip-tool` binary running `TC-G-1.1`, for comparison.
<img width="1943" alt="Screenshot 2023-05-17 at 15 08 12 2" src="https://github.com/project-chip/connectedhomeip/assets/116589288/e693e036-ac94-4f09-8dc8-1b0cea00f9d9">
<img width="1938" alt="Screenshot 2023-05-17 at 15 19 41 2" src="https://github.com/project-chip/connectedhomeip/assets/116589288/ceead193-4764-48bc-92e2-2b0639ca1578">

### Platform

other

### Type

Manually tested with SDK

### Anything else?

- Related issue: https://github.com/CHIP-Specifications/chip-certification-tool/issues/822

**Comment by bzbarsky-apple** [comment]
@vivien-apple
