### ISSUE TITLE
[BUG] Return type on Java chipClient.chipDeviceController.compressedFabricId should be ULong, not Long

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#26640]
### Reproduction steps

Return type on Java chipClient.chipDeviceController.compressedFabricId should be ULong, not Long

This impacts printing these IDs, you don't want them to print as negative numbers.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

7d47ed6

### Platform

android

**Comment by joonhaengHeo** [comment]
Java does not have a definition of type such as ULong in kotlin or uint64_t in c++. 
The implementation of getCompressedFabricId is Java Language and can only be implemented using long type.

**Comment by jonsmirl** [comment]
I am using Kotlin and it is annoying to have all of these IDs as INTs and LONGs.
