### ISSUE TITLE
[BUG] Modifications to temperature control cluster as per the spec changes

### ISSUE THREAD

**Issue by dhrishi** [project-chip/connectedhomeip#26646]
### Reproduction steps

NA

### Bug prevalence

NA

### GitHub hash of the SDK that was being used

master

### Platform

core

### Anything else?

The spec issue https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7040 would require changes in the SDK code. Need to make the modifications as and when the spec changes converge

**Comment by dhrishi** [comment]
@jadhavrohit924 Please track this

**Comment by dhrishi** [comment]
@bzbarsky-apple As discussed, requested this to be a cert blocker. Will you add the `cert blocker` label? Or am I allowed to add?

**Comment by cjandhyala** [comment]
I think its related to  #26601 which is already filed

**Comment by dhrishi** [comment]
@cjandhyala The above seems to be specific to the thermostat cluster. This is about the temperature control cluster

**Comment by jadhavrohit924** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/commit/701fcb21f9a
