### ISSUE TITLE
Android -  how to detect weather product is paired or not , if someone tries to pair same product 2nd time?

### ISSUE THREAD

**Issue by swap9391** [project-chip/connectedhomeip#26654]
### Feature description

...
For Android Example- how to detect weather product is paired or not , if someone tries to pair same product 2nd time

### Platform

android

### Platform Version(s)

sfsddsfdfs

**Comment by yunhanw-google** [comment]
usually once the device is paired, this device stop advertisement so controller cannot discover the device again.
