### ISSUE TITLE
[Feature]  Does the zap file support multiple types of the same endpoint?

### ISSUE THREAD

**Issue by JasonHu1** [project-chip/connectedhomeip#26672]
### Feature description

...
For example, I want to have both devicetype that ota provider and aggregator on endpoint 1

### Platform

other

### Platform Version(s)

1.1.0.1

**Comment by bzbarsky-apple** [comment]
Note that you can do this by manually editing the generated endpoint_config.h to provide the device type lists, but it's a bit of a pain.  :(
