### ISSUE TITLE
Add nanopb as submodule

### ISSUE THREAD

**Issue by szatmz** [project-chip/connectedhomeip#2668]
#### Problem
nanopb is a lightweight protobuf implementation. Protobufs are required e.g. by some modules of Pigweed which already is a submodule.

 #### Proposed Solution
Adding https://github.com/nanopb/nanopb.git as a git submodule.

**Comment by gerickson** [comment]
Since there are current no plans to use protocol buffers in CHIP, can we instead file a bug against Pigweed to short-circuit this dependency if CHIP isn't, in turn, using those facilities in Pigweed that depend on protobuf?
