### ISSUE TITLE
[BUG] CacheAndSync feature is not supported,KeySetWrite Command returns Success when sent with GroupKeySecurityPolicy is 1  

### ISSUE THREAD

**Issue by sumaky** [project-chip/connectedhomeip#26692]
### Reproduction steps

1. read feature map  CacheandSync Feature  value is false
2. Send Ket-Set-Write with security policy as 1  we get Success response 
3. Key-Set-Read Command returns response with Group Key Security Policy :1

When CacheandSync is not supported expected Ket-Set-Write with security policy as 1 to return invalid command

https://github.com/CHIP-Specifications/chip-test-plans/pull/2381/

### Bug prevalence

NA

### GitHub hash of the SDK that was being used

NA

### Platform

other

### Platform Version(s)

NA

**Comment by bzbarsky-apple** [comment]
The relevant spec bits here are:

"7.18.1.5. Enumeration (8-bit, 16-bit)" says:

> If a client indicates an enumeration value to the server, that is not supported by the server, because it is optional, deprecated, or a new value unrecognized by a legacy server, then the server SHALL generate a general constraint error, , unless the cluster defines alternate behavior

and "Invoke Execution" says:

> If a data field violates expected constraints, a CommandStatusIB SHOULD be generated with an error status of CONSTRAINT_ERROR.

and under "11.2.5.4. GroupKeySetStruct Type" we have "GroupKeySecurityPolicy Field" saying:

> When CacheAndSync is not supported in the FeatureMap of this cluster, any action attempting to set CacheAndSync in the GroupKeySecurityPolicy field SHALL fail with an INVALID_COMMAND error.
