### ISSUE TITLE
[1.0] TC-SC-5.1 After successful key set removal the corresponding entries in the GroupKeyMap are not removed.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#26709]
## Reproduction steps

In TC-SC-5.1 verifies whether the GroupKeySets and Groups can be added and removed from DUT. In this test case at STEP 10 GroupKeySets value is removed from DUT using  key-set-remove command. This should remove all the corresponding entries in the GroupKeyMap should be removed. To cross verify it in STEP 11 by providing read group-key-map command should result in 0 entries but while using V1.0.0.2 as server against V1.1 and TOT Master the corresponding entries are not removed even after success respond reflected in STEP 10

### **Expected behavior  in step 10 and 11:**
STEP 10 : `./chip-tool groupkeymanagement key-set-remove "0x01a3" 1 0`

> [1674110684.044438][29696:29698] CHIP:DMG:                                 StatusIB =
> [1674110684.044452][29696:29698] CHIP:DMG:                                 {
> [1674110684.044465][29696:29698] CHIP:DMG:                                         status = 0x00 (SUCCESS),
> [1674110684.044476][29696:29698] CHIP:DMG:                                 },

STEP 11: ` ./chip-tool groupkeymanagement read group-key-map 1 0`

> [1674110744.295368][29707:29709] CHIP:TOO:   GroupKeyMap: 0 entries

### **Actual behavior in step 10 and 11:** 
STEP 10 : `./chip-tool groupkeymanagement key-set-remove "0x01a3" 1 0`

> [1674110684.044438][29696:29698] CHIP:DMG:                                 StatusIB =
> [1674110684.044452][29696:29698] CHIP:DMG:                                 {
> [1674110684.044465][29696:29698] CHIP:DMG:                                         status = 0x00 (SUCCESS),
> [1674110684.044476][29696:29698] CHIP:DMG:                                 },

STEP 11: ` ./chip-tool groupkeymanagement read group-key-map 1 0`

> 
> [1684419631.900036][52167:52169] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_003F Attribute 0x0000_0000 DataVersion: 4264123831
> [1684419631.900494][52167:52169] CHIP:TOO:   GroupKeyMap: 1 entries
> [1684419631.900536][52167:52169] CHIP:TOO:     [1]: {
> [1684419631.900547][52167:52169] CHIP:TOO:       GroupId: 259
> [1684419631.900559][52167:52169] CHIP:TOO:       GroupKeySetID: 419
> [1684419631.900570][52167:52169] CHIP:TOO:       FabricIndex: 1
> [1684419631.900580][52167:52169] CHIP:TOO:      }

### **Logs:**
[TC-SC-5.1(V1.0.0.2_DUT).txt](https://github.com/project-chip/connectedhomeip/files/11527512/TC-SC-5.1.V1.0.0.2_DUT.txt)
[TC-SC-5.1(V1.0.0.2_DUT).txt](https://github.com/project-chip/connectedhomeip/files/11527514/TC-SC-5.1.V1.0.0.2_DUT.txt)

### Bug prevalence

When V1.0.0.2 is used as server against the V1.1 and Master TOT as Client

### GitHub hash of the SDK that was being used

4088a77f557e8571a39338fad51a1d8eb0131d79		

### Platform

raspi

### Platform Version(s)

RPI 4 8GB RAM

### Type

Core SDK Performance Improvement

### Anything else?

Same functionality works as expected when V1.1 and Mater TOT is used as server, The issue is only when V1.0.0.2 is used as server.

**Comment by bzbarsky-apple** [comment]
> but while using V1.0.0.2 as server

Yes, V1.0.0.2 is buggy: see https://github.com/project-chip/connectedhomeip/issues/23862.  That bug was fixed for Matter 1.1 in https://github.com/project-chip/connectedhomeip/pull/23864 but the fix was not backported to the 1.0 branch.
