### ISSUE TITLE
Updates needed to move dishwasher error events from op state to a new alarm cluster

### ISSUE THREAD

**Issue by rbultman** [project-chip/connectedhomeip#26754]
Here is the spec PR that moves the error events to a new alarm cluster:  https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7070

See the referenced PR for details.

**Comment by bzbarsky-apple** [comment]
@rbultman Is there anything left to do here?

**Comment by rbultman** [comment]
This should be finished.

**Comment by rbultman** [comment]
Completed.
