### ISSUE TITLE
[BUG] Identify cluster effect identifier and effect variant are NOT the same thing - used in multiple example apps

### ISSUE THREAD

**Issue by fessehaeve** [project-chip/connectedhomeip#26797]
### Reproduction steps

All the below mentioned example codes do casting from effect variant to effect identifier, which are not the same thing.

`sIdentifyEffect = static_cast<EmberAfIdentifyEffectIdentifier>(identify->mEffectVariant);`

```
examples/chef/efr32/src/AppTask.cpp
examples/light-switch-app/silabs/efr32/src/AppTask.cpp
examples/lighting-app/qpg/src/AppTask.cpp
examples/lighting-app/silabs/efr32/src/AppTask.cpp
examples/lock-app/qpg/src/AppTask.cpp
examples/lock-app/silabs/efr32/src/AppTask.cpp
examples/thermostat/silabs/efr32/src/AppTask.cpp
examples/window-app/common/src/WindowApp.cpp
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

e022057aea58fee7f855d8994c7f971c5ac2c875

### Platform

efr32, other

**Comment by mkardous-silabs** [comment]
It's been a while since i've played with the identify sutff. I would need to look into it.

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs Thank you!
