### ISSUE TITLE
nrfconnect lock example: west flash does not work in docker container

### ISSUE THREAD

**Issue by pierredelisle** [project-chip/connectedhomeip#2679]
As discussed with Damian.Krolik@nordicsemi.no:
"Docker for Mac leverages Hyperkit hypervisor which doesn't support USB passthrough, hence Docker service can't expose USB devices to containers."

So nrfjprog --ids does not work in the docker container for MacOS.

Would be good to update the README and recommend for MacOS to use native shell after the binary has been built in docker (because Docker service does not expose USB devices to container).

**Comment by M055277702** [comment]
https://github.com/fastai/fastmac/issues/14
