### ISSUE TITLE
[Documentation] ColorControl Cluster (Matter Specs 1.1): currentHue not "Scene" saved?

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#26796]
### Documentation issues

currentHue arttribute should also have "S" quality if all other "current*" ones have it, or what is the reason that this should not be stored a scene value? Same for the Text below the table about Scene cluster extension points - also there currentHue is missing.

### Platform

core (please add to version below)

**Comment by bzbarsky-apple** [comment]
`EnhancedCurrentHue` is scenable.  If they were both scenable, you would have to define how to handle scenes that define both and have conflicting values, no?

**Comment by bzbarsky-apple** [comment]
In any case, not an SDK issue...

**Comment by Apollon77** [comment]
> EnhancedCurrentHue is scenable. If they were both scenable, you would have to define how to handle scenes that define both and have conflicting values, no?

I understand that this might produce interesting effects, but that means that in clusters without "EnhancedHue" feature the currentHue is not scenable ... which feels wrong.
The specifications could decribe how it need to behave if both are there.

**Comment by bzbarsky-apple** [comment]
@Apollon77 Yes, but is the complexity worth it?  In any case, this is not really the right place to report specification issues....

**Comment by Apollon77** [comment]
User facing wise it would be an inconsistent behaviour in my eyes if device manufacturers implement according to the specs and do not have enhancedHue feature. Me as a user would expect that also hue will be stored and recalled via scene.

And for the place: yes, but because there is no other place for non members you stated in other issues that I should continue to report such topics here when I stumble over it for core implementations of matter.js

Just tell me if I should stop it

Ingo

**Comment by bzbarsky-apple** [comment]
I think there's a difference between "spec bug" and "spec decision that is suboptimal", fwiw.  But please report both; I'm actually asking around to see whether this was a purposeful decision or oversight.

**Comment by Apollon77** [comment]
Thank you very much. If it was a  purposeful decision then all fine, I just want to clarify it.
