### ISSUE TITLE
 [Feature] IDM cluster device tests YAML support

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#26841]
### Feature description

Summary: 
Need IDM cluster YAML support for the below mentioned steps or sample script if implemented already.
Effected tests:
TC-IDM-1.2
TC-IDM-2.2
TC-IDM-3.2
TC-IDM-4.2
TC-IDM-4.3
TC-IDM-4.4
TC-IDM-5.2
TC-IDM-6.1
TC-IDM-6.2
TC-IDM-7.1
TC-IDM-8.1
Feature required: 
1. Need YAML support to send the [ `Invoke Request Message` , `Read Request Message`, `WriteRequestMessage`, `subscription      request message`, `Timed Request message` ] from `TH `to `DUT` with single or multiple `PATHS` and `CommandDataIB` -->' which has the specific Endpoint, Specific Cluster and Specific Command.'
2. Setup TH2 such that it does `not have access` or `have access` to an attribute on a specific cluster and endpoint.
3. TH sends `Read Request Message` to DUT with `EventRequests` set to a specific `event` from a specific `cluster` on a specific `endpoint` on a specific `node`
4. TH sends the `Invoke Request Message `to the DUT with a valid `CommandDataIB` and `SuppressResponse` set to True
5. Need YAML support for all steps in IDM-7.1 & 8.1 testcases

### Platform

other

### Anything else?

IDM-1.2
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/2ddad395-c2f5-4c3a-a4d9-676331c6f0ba)
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/73c724a1-87fa-4ebc-bd7f-f866e49f7564)
IDM-2.2
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/49b4d4cb-8a1a-4818-bf27-bafdcfdab28f)
IDM-3.2
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/fdf8a965-edc6-4a46-b7ea-4d636a0508d1)
IDM-4.2
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/1f1e68e2-36f2-464c-b3be-7be487032822)
IDM-5.2
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/f434269b-dba2-4862-884c-516aca3add13)
IDM-6.4
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/938f6935-9d60-46f6-b8dc-fb20d2236e16)

**Comment by manjunath-grl** [comment]
Breakdown for issue: https://github.com/project-chip/connectedhomeip/issues/23232

**Comment by bzbarsky-apple** [comment]
>  Need YAML support to send the [ Invoke Request Message , Read Request Message, WriteRequestMessage, subscription      request message, Timed Request message ] from TH to DUT with single or multiple PATHS and CommandDataIB -->' which has the specific Endpoint, Specific Cluster and Specific Command.'

This is duplicating things from https://github.com/project-chip/connectedhomeip/issues/23232, no?

>  Setup TH2 such that it does not have access or have access to an attribute on a specific cluster and endpoint.

OK, so set ACLs.  What's missing in YAML here?

>    TH sends Read Request Message to DUT with EventRequests set to a specific event from a specific cluster on a specific endpoint on a specific node

readEvent exists, no?

> Breakdown for issue: https://github.com/project-chip/connectedhomeip/issues/23232

Honestly, a breakdown by _test_ is not useful @manjunath-grl . What's useful is a breadkdown per-missing-piece-of-functionality, one issue per missing piece of functionality.  And the issues involved should clearly describe exactly what's missing.

**Comment by manjunath-grl** [comment]
@bzbarsky-apple I will close this issue. Let me go through this and open a dedicated issue for the functionality.
