### ISSUE TITLE
[BUG] don't store intermediate value into kvs when transitioning

### ISSUE THREAD

**Issue by step0035** [project-chip/connectedhomeip#26866]
### Reproduction steps

- run some command like `move-to-level` with a non-zero transition time
- the intermediate values will be persisted in the kvs
- this can be undesirable for the following reasons
  - writing to kvs (typically an external flash on many platforms) can be time consuming and will affect the timing accuracy
  - reduce the lifetime of the flash significantly, for eg moving from 1 to 254 will require 253 writes into the flash

### Bug prevalence

always

### GitHub hash of the SDK that was being used

ad5253ace34269d07ca8afbd984aec319903ac56

### Platform

other

**Comment by bzbarsky-apple** [comment]
@step0035 This is why https://github.com/project-chip/connectedhomeip/blob/master/src/app/DeferredAttributePersistenceProvider.h exists, right?  So you can choose how often you write these, etc.
