### ISSUE TITLE
Make android  app act as an OTA provider

### ISSUE THREAD

**Issue by MrLiuYunPing** [project-chip/connectedhomeip#26868]
### Feature description

...
I have done this in iOS, because the Matter.framework has supported to set an OTA delegate, and has some test cases related. But, in android,  I announce the controller nodeId to the device to update, when I set OTA delegate using endpoint 0, it always failed(emberAfFindClusterServerEndpointIndex method returns Invalid). When i look the logs on the device, it shows: Received Command Response Status for Endpoint=0 Cluster=0x0000_0029 Command=0x0000_0000 Status=0x7f . . .Status=0x7f whichs means unsupported endpoint. I don't know why iOS success but android failed?

### Platform

android

**Comment by bzbarsky-apple** [comment]
> I don't know why iOS success but android failed?

iOS implements `emberAfFindClusterServerEndpointIndex` specifically so OTA can work.  See https://github.com/project-chip/connectedhomeip/blob/19ae369ee57b828b3934bea599f1e2d000d32730/src/darwin/Framework/CHIP/MTRIMDispatch.mm#L230-L240

Android might need to do something similar.

**Comment by srdantas** [comment]
how could you set ota provider on android @MrLiuYunPing ? may you share your code here? I never found documentarion for support this feature

**Comment by swap9391** [comment]
Any update what steps need to perform on Android code achieve OTA in android?

**Comment by yusheng-jia** [comment]
@bzbarsky-apple Hi Could you give me a simple example how to make OTA process on iOS side? I didn't find any docs on this, I want to do OTA function on iOS, Thank you .

**Comment by yusheng-jia** [comment]
@MrLiuYunPing Hi could you tell me how you implemented on iOS? Thank you

**Comment by bzbarsky-apple** [comment]
@yusheng-jia On iOS, set `otaProviderDelegate` in the `MTRDeviceControllerFactoryParams` to a non-nil value before starting up the controller factory.  Then you will get calls to your delegate implementation as needed.

**Comment by yusheng-jia** [comment]
> @yusheng-jia On iOS, set `otaProviderDelegate` in the `MTRDeviceControllerFactoryParams` to a non-nil value before starting up the controller factory. Then you will get calls to your delegate implementation as needed.

Thanks, I will do that.

**Comment by yunhanw-google** [comment]
I will take a look today. thanks

**Comment by yunhanw-google** [comment]
@MrLiuYunPing  @swap9391 @yusheng-jia https://github.com/srdantas)may I know your requirement on android for ota-provider? for example, you wanna use android-chip-tool or your android app to announce there is ota software, then send this image to your wifi-device using bdx over wifi? I think currently there is no java/jni api for setDelegate for ota-provider, how do you do that, wanna get more details so that we can plan the feature. thanks

**Comment by yusheng-jia** [comment]
> @MrLiuYunPing @swap9391 @yusheng-jia https://github.com/srdantas)may I know your requirement on android for ota-provider? for example, you wanna use android-chip-tool or your android app to announce there is ota software, then send this image to your wifi-device using bdx over wifi? I think currently there is no java/jni api for setDelegate for ota-provider, how do you do that, wanna get more details so that we can plan the feature. thanks

Thank you for support, you're totally right . I did this on iOS, iOS has MTROTAProviderDelegate protocol, it has very detailed method to implement the whole OTA process on App side.

**Comment by yunhanw-google** [comment]
@yusheng-jia are you in matter slack channel, if yes, what is your slack name?

**Comment by yusheng-jia** [comment]
> 
Sorry for miss this message, I'm not in slack channel.

**Comment by eling22** [comment]
@yunhanw-google Hi, I am also surveying this feature. Is an OTA provider currently being developed?

**Comment by yunhanw-google** [comment]
@eling22 are you in slack, could you find me with yunhanw in slack? Wanna also understand your requirement, thanks

**Comment by yunhanw-google** [comment]
@eling22 and @MrLiuYunPing we are actively supporting this feature, we would create several PR for this work soon.

**Comment by Shahmeera** [comment]
I don't have knowledge of an android app, but I was facing same issue with linux PC. In your android app if you want to be as an OTA provider then OTA provider cluster must be in server mode. I have resolved this error by doing following changes.
(1) updated matter version 1.2 from 1.1 because updated ZAP version can support **OTA Provider cluster as a Server**
(2) Enabled OTA provider cluster as a server.
By doing these, you will be able to resolve this.

**Comment by yunhanw-google** [comment]
@Shahmeera @eling22 @MrLiuYunPing @yusheng-jia @swap9391 @srdantas  we have officially added the OTA support in android side, please check-in, thanks
https://github.com/project-chip/connectedhomeip/pull/30145
