### ISSUE TITLE
[Feature] Dead Front Behaviour Feature of OnOff cluster is not implemented

### ISSUE THREAD

**Issue by PSONALl** [project-chip/connectedhomeip#26874]
### Feature description

Fall Release of connectedhomeip contains Room Air Conditioner Device Type
For this device type dead front behaviour feature of the OnOff cluster is mandatory to implement
But this feature is not present in the upstream which needs to be implemented

### Platform

all

**Comment by bzbarsky-apple** [comment]
@PSONALl Is this a duplicate of https://github.com/project-chip/connectedhomeip/issues/26469?  See also https://github.com/project-chip/connectedhomeip/pull/26524

**Comment by PSONALl** [comment]
Closing this issue as it has been already reported
