### ISSUE TITLE
Customer cluster is createad by zap, but clusters.h attributes.h not include  customer content. but clusters.h （app-common）is generated by zap,how to solve it

### ISSUE THREAD

**Issue by CatFuGui** [project-chip/connectedhomeip#26871]

**Comment by bzbarsky-apple** [comment]
@CatFuGui I assume you added the extra cluster to `src/app/zap-templates/zcl/zcl.json`?  If not, how are you getting its XML to be picked up by ZAP?

If you did add it, then running either `scripts/tools/zap_regen_all.py` or more targeted `scripts/tools/zap/generate.py -t src/app/common/templates/templates.json -o zzz_generated/app-common/app-common/zap-generated src/controller/data_model/controller-clusters.zap` will regenerate app-common.
