### ISSUE TITLE
[Scenes] Add support for enabling and disabling endpoints in SceneTable and Scenes Server

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#26877]
Current implementation doesn't interact with dynamically generated endpoints, needs to properly handle creation and deletion of dynamically created endpoints as well as Enabling/disabling fixed endpoints.

Mentioned in this [PR](https://github.com/project-chip/connectedhomeip/pull/26186) in comments:

- https://github.com/project-chip/connectedhomeip/pull/26186/files#r1206103477
- https://github.com/project-chip/connectedhomeip/pull/26186/files#r1206106970
- https://github.com/project-chip/connectedhomeip/pull/26186/files#r1206113491
- https://github.com/project-chip/connectedhomeip/pull/26186/files#r1206151172

**Comment by bzbarsky-apple** [comment]
This is not just about dynamic endpoints.  Enabling/disabling fixed endpoints is also broken with scenes as currently written.

**Comment by lpbeliveau-silabs** [comment]
Also mentioned here: 
 https://github.com/project-chip/connectedhomeip/pull/29639/files#r1349474273

The feature map logic should be moved from the server init to the per-endpoint init.
