### ISSUE TITLE
[Scenes] Fix CurrentGroup, CurrentScene, SceneValid and LastConfiguredBy attributes to be Endpoint and Fabric Scoped.

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#26900]
Related to https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7098. Need to determine and implement the desired behaviour.

**Comment by bzbarsky-apple** [comment]
@tcarmelveilleux says we need to maintain completely separate values of CurrentGroup/CurrentScene/SceneValid/LastConfiguredBy for each fabric.  So we can't store those things in the attribute store, clearly.

**Comment by lpbeliveau-silabs** [comment]
https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7098#issuecomment-1579755740
