### ISSUE TITLE
Python-repl error

### ISSUE THREAD

**Issue by aravindone** [project-chip/connectedhomeip#26912]
### Reproduction steps

whenever i used to python commands involving cluster keyword it throws up the error

In [39]: matterhelp(Clusters.UnitTesting.Commands.TestAddArguments)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[39], line 1
----> 1 matterhelp(Clusters.UnitTesting.Commands.TestAddArguments)

NameError: name 'Clusters' is not defined

@bzbarsky-apple  please comment

### Bug prevalence

every time calling cluster 

### GitHub hash of the SDK that was being used

bfa05804ac3c224c9e70921a857ffcac32ccc7f4

### Platform

python

**Comment by bzbarsky-apple** [comment]
@aravindone you might want to ask someone who knows something about the Python repl, not me....  That said, I am not sure who, if anyone, is maintaining it now.  Maybe @tehampson ?

**Comment by tehampson** [comment]
@aravindone , What happens if you do `import chip.clusters as Clusters`?

**Comment by aravindone** [comment]
problem resolves @tehampson  thanks for the comment. It works. i will close this ticket
