### ISSUE TITLE
Once CI supports IPV6, TestTCP/UDP should make the 'EADDRNOTAVAIL' fatal

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#2698]
#### Problem
We specifically allow transport tests to pass on IPV6 when we get ADDRNOTAVAIL.

 #### Proposed Solution
IPV6 failures should be fatal as CHIP requires IPV6.

**Comment by kpschoedel** [comment]
Reopening because this still exists (and I'm about to fix it).
