### ISSUE TITLE
Android - OTA update documentation is not mentioned steps to process OTA from Android

### ISSUE THREAD

**Issue by swap9391** [project-chip/connectedhomeip#26995]
### Documentation issues

1.https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/esp32/ota.md 

### Platform

android

**Comment by swap9391** [comment]
Any update on this?

**Comment by yunhanw-google** [comment]
duplicate with https://github.com/project-chip/connectedhomeip/issues/26868
