### ISSUE TITLE
Query in Subscribe and Publish command

### ISSUE THREAD

**Issue by rajeshkrishnan2k** [project-chip/connectedhomeip#26997]
I have some queries in our Matter Setup with Raspberry Pi as Border Router and EFR32 board as RCP and End Device. The End Device is loaded with Light Application.

How to take logs for the border router/RCP. We are able to get the logs only for the mattertool/chiptool when i run some commands.

When i am trying the subscribe and publish command i face some problems. The Report data sent by the end device does not receive status response and timeout occurs. So i want to confirm whether the border router is receiving the data or not. I am attaching the logs for the chip tool and Light application when subscribe command is run.

The following is command that we are running : mattertool onoff subscribe on-time 1 10 2303 1. (where 2303 is the node-id)

[sub_chip.txt](https://github.com/project-chip/connectedhomeip/files/11622037/sub_chip.txt)
[light_app01.log](https://github.com/project-chip/connectedhomeip/files/11622039/light_app01.log)

**Comment by bzbarsky-apple** [comment]
> The Report data sent by the end device does not receive status response and timeout occurs. 

Isn't that because you set up the subscription and then chip-tool (mattertool?) exits, so there is nothing to receive the report?  Presumably you want to be doing this:

```
mattertool interactive start
```

and then at the interactive prompt:
```
onoff subscribe on-time 1 10 2303 1
```

so that the tool keeps running after subscription establishment completes and is able to receive reports.
