### ISSUE TITLE
[New Cluster] Door Lock

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#2702]
Parts of the door lock cluster are unimplemented, please work with @bzbarsky-apple to identify what's needed and implement

**Comment by bzbarsky-apple** [comment]
@franck-apple did https://github.com/project-chip/connectedhomeip/pull/2506 fix this?

**Comment by vivien-apple** [comment]
@franck-apple Can you answer Boris's question ? I believe he is right in saying that #2506 fix it.
