### ISSUE TITLE
Error about Matter Test Harness:TC-DRLK-2.2(Semi-automated)

### ISSUE THREAD

**Issue by wuzeshun997** [project-chip/connectedhomeip#27033]
Hi,all  

  I have some questions to consult about the Matter Test-harness Test platform.  
  First, I used the ```/home/ubuntu/chip-certification-tool/scripts/OTBR/otbr_start.sh``` shell script   

  and then used ```/home/ubuntu/chip-certification-tool/scripts/chip-tool ble-thread 8888 hex:$Dataset 20202021 3840``` to pairing my lock device, and the matter lock/unlock can also work normally.  

  But when I harness the Test case TC-DRLK-2.2(Semi-automated) in the Matter test-harness.The pairing failed and the message timed out, so what do I need to do to successfully match?

  The logs provided below are the operations in the Matter Test-harness
  [DRLK2_2_2023_6_2_17_37_14.log](https://github.com/project-chip/connectedhomeip/files/11634183/DRLK2_2_2023_6_2_17_37_14.log)

  The logs provided below is DUT log
  [dut_logs.log](https://github.com/project-chip/connectedhomeip/files/11634184/dut_logs.log)

  So I have another question, is the container "th-chip-tool" started in the test platform different from the container "otbr-chip" started in scripts/OTBR, Thread network?    
Why use "otbr-chip" can be normal network configuration, but in the test platform "th-chip-tool" will prompt failure

**Comment by bzbarsky-apple** [comment]
> The pairing failed 

Looking at the harness log:

```
CHIPTOOL   | 2023-06-02 09:37:42.955286 | [1685698662.879746][7:13] CHIP:DIS: Resolving CAB3DDB265022586:081B8E4FCCB4C3BB ...
..
CHIPTOOL   | 2023-06-02 09:37:47.885129 | [1685698667.884060][7:13] CHIP:DL: Re-trying resolve
CHIPTOOL   | 2023-06-02 09:37:52.893196 | [1685698672.892142][7:13] CHIP:DL: Re-trying resolve
CHIPTOOL   | 2023-06-02 09:37:57.897655 | [1685698677.897059][7:13] CHIP:DL: Re-trying resolve
CHIPTOOL   | 2023-06-02 09:38:02.904664 | [1685698682.903676][7:13] CHIP:DL: Avahi resolve failed
CHIPTOOL   | 2023-06-02 09:38:03.501328 | [1685698683.500248][7:12] CHIP:DL: Got IP address on interface: wlan0 IP: 192.168.2.145
CHIPTOOL   | 2023-06-02 09:38:03.503354 | [1685698683.500299][7:12] CHIP:DL: Failed to report IP address - ip address parsing failed
```

That last is presumably because the harness is compiled without IPv4 support, because devices are supposed to support IPv6... and in any case, IPv4 can't work for a _thread_ device.

From the device log:

```
I: 86537 [DIS]Advertise operational node CAB3DDB265022586-081B8E4FCCB4C3BB
I: 86544 [SVR]Operational advertising enabled
...
E: 88230 [DL]SRP update error: timed out waiting on server response
E: 91436 [DL]SRP update error: timed out waiting on server response
E: 97192 [DL]SRP update error: timed out waiting on server response
E: 106516 [DL]SRP update error: timed out waiting on server response
E: 122161 [DL]SRP update error: timed out waiting on server response
```

which is presumably why the discovery failed.

So look into why the SRP update failed and hence the device advertising failed?

For the other questions: @cjandhyala can you take a look please?
