### ISSUE TITLE
Review and update CHIP architecture pyramid

### ISSUE THREAD

**Issue by anandkp92** [project-chip/connectedhomeip#2705]
Just have a doubt regarding the [protocol stack](https://github.com/project-chip/connectedhomeip/blob/master/docs/images/CHIP_Arch_Pyramid.png): 
* Why are the bottom two layers (message framing and routing & IP framing and transport management) present in the application layer? 
* What are their functions? The tasks mentioned in the README file seem like these should be executed in the the lower layers of the IP stack.

**Comment by woody-apple** [comment]
SW BRB: @robszewczyk @anush-apple  Care to take a peek?

**Comment by mrjerryjohns** [comment]
Stale.
