### ISSUE TITLE
[Scenes] AttributeID in AttributeValuePair should not be optional

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#27076]
Currently in the data model, attributeID is optional, which doesn't respect the scenes cluster specification. It needs to be refactored to the AttributeId type.

**Comment by bzbarsky-apple** [comment]
It should be of type `attrib_id`, no?  Just not optional.  That's in the XML.  On the C++ side it would be `AttributeId`.

**Comment by lpbeliveau-silabs** [comment]
Fixed in [PR](https://github.com/project-chip/connectedhomeip/pull/27509)
