### ISSUE TITLE
[Scenes]  Cluster-Revision not up to date

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/connectedhomeip#27082]
### Reproduction steps

`./chip-tool scenes read cluster-revision 1 1`
expecting cluster-revision 5.
got:
```
[1685992688592] [16321:137048] [TOO] Endpoint: 1 Cluster: 0x0000_0005 Attribute 0x0000_FFFD DataVersion: 2719936702
[1685992688592] [16321:137048] [TOO]   ClusterRevision: 4
```

### Bug prevalence

always

### GitHub hash of the SDK that was being used

5589086a33

### Platform

efr32, raspi

**Comment by lpbeliveau-silabs** [comment]
PR to update [here](https://github.com/project-chip/connectedhomeip/pull/27104)

**Comment by bzbarsky-apple** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/pull/27104
