### ISSUE TITLE
[BUG] device out of power，application still found the device by mDNS

### ISSUE THREAD

**Issue by gen-zi** [project-chip/connectedhomeip#27091]
### Reproduction steps

I use my own implementation of mDNS discovery which based on Android NsdManager to discovery matter devices, serviceType is _matterc._udp, it actually work, but when i interrupt the power supply of device, it still can discovery the device, is this a problem？

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

NA

### Platform

android

**Comment by bzbarsky-apple** [comment]
DNS-SD records can get cached, like all DNS records.  So if you suddenly cut power to an advertiser without giving it a chance to send goodbye packets and invalidate the caches, queries will find the cached records until the TTL expires.

**Comment by gen-zi** [comment]
> DNS-SD records can get cached, like all DNS records. So if you suddenly cut power to an advertiser without giving it a chance to send goodbye packets and invalidate the caches, queries will find the cached records until the TTL expires.

can i invalidate the caches or disable caches in my app?

**Comment by bzbarsky-apple** [comment]
@gen-zi The cache is on the DNS server.  The only way to invalidate the cache is to send the appropriate DNS advertisement packets to that server.

**Comment by gen-zi** [comment]
ok，thank you for your reply

**Comment by gen-zi** [comment]
i have one more question， i think the cache maybe effected to discover the service，but why i can also resolve the service，is the cache still working？
