### ISSUE TITLE
[XML] Update OnOff Cluster XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#27092]
The data types names has been updated in OnOff Cluster and must be updated in the XML as well.

**Added:**
- OnOffControlBitmap
- EffectIdentifierEnum
- DelayedAllOffEffectVariantEnum
- DyingLightEffectVariantEnum 

**Changed feature names:**
- Level Control for Lighting -> Lighting
- Dead Front Behaviour -> DeadFrontBehaviour

**Adjusted value names in DelayedAllOffEffectVariantEnum and DyingLightEffectVariantEnum:**
- FadeToOffIn_0p8Seconds -> DelayedOffFastFade
- 50PercentDimDownIn_0p8SecondsThenFadeToOffIn_12Seconds -> DelayedOffSlowFade
- 20PercentDimUpIn_0p5SecondsThenFadeToOffIn_1Second -> DyingLightFadeOff

Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/6511 (already merged)

**Comment by bzbarsky-apple** [comment]
I am not sure whether it's worth working on this until whatever changes are needed for https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/6336 happen too....  Right now the XML in the SDK cannot in fact be aligned with the spec.
