### ISSUE TITLE
[Scenes] Cleanup of SceneTableImpl types

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#27111]
As mentioned in https://github.com/project-chip/connectedhomeip/pull/27089/files#r1220198788,

The SceneTableImpl could use some "using" to reduce the size of types such as :
`app::DataModel::List<app::Clusters::Scenes::Structs::AttributeValuePair::Type>`

**Comment by bzbarsky-apple** [comment]
In particular, `using List = app::DataModel::List;` and `using AttributeValuePair = app::Clusters::Scenes::Structs::AttributeValuePair::Type;` might be good.
