### ISSUE TITLE
[BUG] TC-CC-6.5: Getting incorrect value of start-up-color-temperature-mireds attribute of color control cluster

### ISSUE THREAD

**Issue by VaishaliAvhale** [project-chip/connectedhomeip#27119]
### Reproduction steps

1. Commission device using chip-tool
2. Execute the below command 
**./chip-tool colorcontrol write start-up-color-temperature-mireds 32639 1 1**
3. power off DUT
4. Power on DUT
5. Execute the below command
./chip-tool colorcontrol read start-up-color-temperature-mireds 1 1
Expected that the DUT response indicates that the StartUpColorTemperatureMireds and color-temperature-mireds attributes match the StartUpColorTemperatureMireds set in Step 2. but, I'm getting a null value for StartUpColorTemperatureMireds and 250 for color-temperature-mireds which is getting before setting StartUpColorTemperatureMireds attribute. 
[esp32.txt](https://github.com/project-chip/connectedhomeip/files/11672987/esp32.txt)
[chip-tool.txt](https://github.com/project-chip/connectedhomeip/files/11672988/chip-tool.txt)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

1aca004d68640ae7df27adea09315308cf1913cd

### Platform

esp32

### Platform Version(s)

v1.2

**Comment by bzbarsky-apple** [comment]
@VaishaliAvhale In the ZAP config for your device, is the storage for color-temperature-mireds set to RAM or NVM?  It should be set to NVM.
