### ISSUE TITLE
[1.2 TE1][TC-OO-1.1] Test Step 10: Read EventList attribute from the DUT. Failed: TH log has no "CHIP:TOO:   EventList: 0 entries"

### ISSUE THREAD

**Issue by luojr9** [project-chip/connectedhomeip#27158]
### Reproduction steps

1. Pi TH run TC-OO-1.1. DUT is Dishwasher.
2. Test case expects "CHIP:TOO:   EventList: 0 entries", but TH log has no this line.

### Bug prevalence

every time

### GitHub hash of the SDK that was being used

xxx

### Platform

raspi, other

### Anything else?

1. Can I cancel TEST step "Read EventList attribute from the DUT"? 
2. Or I should add eventlist on wifi module?

Log
```
CHIPTOOL   | 2023-06-08 12:28:52.971639 | 		***** Test Step 10 : Read EventList attribute from the DUT.For this cluster the list is usually empty but it can contain manufacturer specific event IDs.
INFO       | 2023-06-08 12:28:52.987738 | Test Step Completed [PASSED]: Read the global attribute: GeneratedCommandList
INFO       | 2023-06-08 12:28:53.006321 | Executing Test Step: Read EventList attribute from the DUT.For this cluster the list is usually empty but it can contain manufacturer specific event IDs.
CHIPTOOL   | 2023-06-08 12:28:53.007475 | [37m		10. Running [0m[1mRead EventList attribute from the DUT.For this cluster the list is usually empty but it can contain manufacturer specific event IDs.[0m
CHIPTOOL   | 2023-06-08 12:28:53.008488 | 		USER_PROMPT: Please enter 'y' for success
INFO       | 2023-06-08 12:28:53.009473 | Found a user prompt, prompting user for USER_PROMPT: Please enter 'y' for success
WARNING    | 2023-06-08 12:31:38.108721 | Test Failure: User stated manual step FAILED.
```
Detail log

[[TC-OO-1.1]_[jLUniBv1]_TH_log.log](https://github.com/project-chip/connectedhomeip/files/11699667/TC-OO-1.1._.jLUniBv1._TH_log.log)
[[TC-OO-1.1]_[jLUniBv1]_DUT_log.log](https://github.com/project-chip/connectedhomeip/files/11699674/TC-OO-1.1._.jLUniBv1._DUT_log.log)

**Comment by luojr9** [comment]
same issue in TC-I-1.1

**Comment by bzbarsky-apple** [comment]
And yes, TC-I-1.1 has the same manual test thing going on.
