### ISSUE TITLE
Rendezvous over BLE in android app not working

### ISSUE THREAD

**Issue by nileshvora-sls** [project-chip/connectedhomeip#2715]
**Problem**
Android App is not doing pairing over BLE for esp32 target.
It is supposed to be working as [this ](https://github.com/project-chip/connectedhomeip/projects/20) project is closed.

@vidhis88 can you give more information on this?

**Proposed Solution**
Add new PR to add this feature in android app.

**Comment by vidhis88** [comment]
Not yet. Only part 1 of that effort has landed. There are more changes required in the BLE layer to make it work. It is currently in progress.
