### ISSUE TITLE
SDK has to be implemented for newly added clusters.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27166]
**SDK has to implemented for below mentioned clusters:**
- [ ] ICD Management Cluster
- [ ] Operational State Cluster
- [ ] Refrigerator Alarm Cluster
- [ ] Smoke and CO Alarm Cluster
- [ ] Temperature Control Cluster
- [ ] Time Synchronization Cluster

**Comment by bzbarsky-apple** [comment]
@Survensa One issue per cluster, please.  Note that some of these are already implemented, so please make sure you test on tip before filing the issues.
