### ISSUE TITLE
[NDOCONC] Attribute has to be implemented for Nitrogen Dioxide Concentration Measurement Cluster.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27169]
**Below mentioned attribute has to be implemented for Nitrogen Dioxide Concentration Measurement Cluster.**
1. PeakMeasuredValue
2. PeakMeasuredValueWindow
3. AverageMeasuredValue
4. AverageMeasuredValueWindow
5. LevelValue

**Spec Reference :** https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ConcentrationMeasurement.adoc#6-attributes

**Comment by bzbarsky-apple** [comment]
@Survensa I assume what you mean is you want these turned on in all-clusters-app?

**Comment by Survensa** [comment]
> @Survensa I assume what you mean is you want these turned on in all-clusters-app?

Yes @bzbarsky-apple need this to be implemented in all-clusters-app

**Comment by Survensa** [comment]
This issue Fixed in - f5c462133547c290f7eb09e5628ede162fb4a218

**Comment by bzbarsky-apple** [comment]
I don't see how https://github.com/project-chip/connectedhomeip/commit/f5c462133547c290f7eb09e5628ede162fb4a218 could possibly have fixed this.

**Comment by Survensa** [comment]
@bzbarsky-apple Could you check this log.
**Execution Log:** [TC-NDOCONC-1.1.txt](https://github.com/project-chip/connectedhomeip/files/11829649/TC-NDOCONC-1.1.txt), [TC-NDOCONC-2.1.txt](https://github.com/project-chip/connectedhomeip/files/11829650/TC-NDOCONC-2.1.txt)

**Comment by Survensa** [comment]
@bzbarsky-apple It should be https://github.com/project-chip/connectedhomeip/commit/9354db4ce61d12c83d8de69529addb439607a86e, Please confirm so that I can close the issue

**Comment by bzbarsky-apple** [comment]
Yep, that looks right, thank you!
