### ISSUE TITLE
[BUG] TE1-V1.2: TC-G-2..2 & 2.3: Getting incorrect value of max-groups-per-fabric attribute of groupkeymanagement cluster

### ISSUE THREAD

**Issue by VaishaliAvhale** [project-chip/connectedhomeip#27172]
### Reproduction steps

1. commission a device
2. followed steps from TC-G-2.2 below the command show incorrect output 
./chip-tool groupkeymanagement read max-groups-per-fabric 1 0

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

1aca004d68640ae7df27adea09315308cf1913cd

### Platform

esp32

### Platform Version(s)

v1.2

**Comment by bzbarsky-apple** [comment]
@VaishaliAvhale What value are you getting?  What value are you expecting?  Why are you expecting the value you are expecting?

**Comment by PSONALl** [comment]
the max-groups-per-fabric value should not be less than the minimum number of fabrics supported (i.e, 5) but we are getting value 4

**Comment by bzbarsky-apple** [comment]
> the max-groups-per-fabric value should not be less than the minimum number of fabrics supported

Why not, @PSONALl ?  The number of groups ***per fabric*** is not related to the number of fabrics in any way.

**Comment by PSONALl** [comment]
> Why not, @PSONALl ? The number of groups _**per fabric**_ is not related to the number of fabrics in any way.

right! My bad ! I misunderstood the test case
