### ISSUE TITLE
[OZCONC] Attribute has to be implemented for Ozone Concentration Measurement Cluster.

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27170]
**Below mentioned attribute has to be implemented for Ozone Concentration Measurement Cluster.**
1. MeasuredValue
2. MinMeasuredValue
3. MaxMeasuredValue
4. PeakMeasuredValue
5. PeakMeasuredValueWindow
6. AverageMeasuredValue
7. AverageMeasuredValueWindow
8. MeasurementUnit

**Spec Reference :** https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ConcentrationMeasurement.adoc#6-attributes

**Comment by bzbarsky-apple** [comment]
@Survensa I assume what you mean is you want these turned on in all-clusters-app?

**Comment by Survensa** [comment]
> @Survensa I assume what you mean is you want these turned on in all-clusters-app?

Yes @bzbarsky-apple need this to be implemented in all-clusters-app

**Comment by Survensa** [comment]
This issue Fixed in - https://github.com/project-chip/connectedhomeip/commit/f5c462133547c290f7eb09e5628ede162fb4a218

**Comment by bzbarsky-apple** [comment]
I don't see how https://github.com/project-chip/connectedhomeip/commit/f5c462133547c290f7eb09e5628ede162fb4a218 could have fixed this @Survensa

**Comment by bzbarsky-apple** [comment]
Yep, that looks right, thank you!
