### ISSUE TITLE
The NSLocalizedString() in MTRError:errorForCHIPErrorCode may crash when Invoke from Matter extension

### ISSUE THREAD

**Issue by huangjinlong92568** [project-chip/connectedhomeip#27210]
When Invoke Matter API from Matter extension, the bundle maybe nil for NSLocalizedString(), in this situation, the errorForCHIPErrorCode API may cause a crash for the `[userInfo addEntriesFromDictionary:@{
            NSLocalizedDescriptionKey : NSLocalizedString(@"The device is already a member of this fabric.", nil)
        }];` (for example)

**Comment by huangjinlong92568** [comment]
the bundle maybe nil  because we swizzed the `localizedStringForKey:value:table:` method for NSBundle

**Comment by ksperling-apple** [comment]
The return value of `[NSBundle localizedStringForKey:value:table:]` is not nullable, you need to ensure you're returning a string if you're swizzling it.
