### ISSUE TITLE
[BUG] TC-IDM-7.1 : Getting PATH_EXHAUSTED status when sending command to send a subscribe requests with 3 different paths in a single command. 

### ISSUE THREAD

**Issue by abdulrehmanee12** [project-chip/connectedhomeip#27223]
### Reproduction steps

1.Commission DUT using multiadmin
2.Follow steps in IDM -7.1
3.Subscribe with 5 TH and change the subscribed attribute.
4.In step 3, Once all 15 subscriptions are active send one more subscriptiop command in RD1 .When sends the command to send a subscribe requests with 3 different paths in a single command using below command 'any subscribe-by-id '0x0028,0x0028,0x0028,0x0028,0x0028,0x0028' '5,6,16,1,2,3' 100 1000 1 '0,0,0,0,0,0' --keepSubscriptions true'  gets PATH_EXHAUSTED status: Status = 0xc8 (PATHS_EXHAUSTED),

Chip-tool logs:
[TC-IDM-7.1.log](https://github.com/project-chip/connectedhomeip/files/11741511/TC-IDM-7.1.log)

DUT logs:
[DUT.txt](https://github.com/project-chip/connectedhomeip/files/11741517/DUT.txt)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/commit/1aca004d68640ae7df27adea09315308cf1913cd

### Platform

core

### Platform Version(s)

v1.2

**Comment by bzbarsky-apple** [comment]
> When sends the command to send a subscribe requests with 3 different paths in a single command using below command 'any subscribe-by-id '0x0028,0x0028,0x0028,0x0028,0x0028,0x0028' '5,6,16,1,2,3' 100 1000 1 '0,0,0,0,0,0' --keepSubscriptions true'

That's 6 paths, not 3 paths.  That's more than the spec guaranteed minimum, the server has no free paths, so the server responds with PATHS_EXHAUSTED.
