### ISSUE TITLE
[OPSTATE] SDK has to be implemented for Operational State Cluster

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27233]
### Summary

**All-clusters-app has to be enabled with below mentioned Attributes :**
- [ ] PhaseList
- [ ] CurrentPhase
- [ ] CountdownTime
- [ ] OperationalStateList
- [ ] OperationalState
- [ ] OperationalError
- [ ] Global Attributes

**All-clusters-app has to be enabled with below mentioned commands :**
- [ ] Pause
- [ ] Stop
- [ ] Start
- [ ] Resume
- [ ] OperationalCommandResponse

### GitHub hash of the SDK that was being used

40fb7c246671e9d37ca8bb2cfbf37f81c1509334

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by mideayanghui** [comment]
Record one unresolved issue :
https://github.com/project-chip/connectedhomeip/pull/26971#discussion_r1258873309

another is to design a api for Event bits ——OperationalError and OperationCompletion.

**Comment by mideayanghui** [comment]
@Survensa Please close this issue.  https://github.com/project-chip/connectedhomeip/pull/26971 has solved this issue.

**Comment by Survensa** [comment]
> @Survensa Please close this issue. #26971 has solved this issue.

Sure will validate and close this issue @mideayanghui, Thanks for letting me know :)

**Comment by Rajashreekalmane** [comment]
Issue resolved in latest master TOT : b6caecf7860072bd4e55be43dc830b5ce990ddef
