### ISSUE TITLE
[TIMESYNC] SDK has to be implemented for Time Synchronization Cluster 

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27241]
### Summary

**All-clusters-app has to be enabled with below mentioned Attributes :**
- [ ] UTCTime
- [ ] Granularity
- [ ] TimeSource
- [ ] TrustedTimeSource
- [ ] DefaultNTP
- [ ] TimeZone
- [ ] DSTOffset
- [ ] LocalTime
- [ ] TimeZoneDatabase
- [ ] NTPServerAvailable
- [ ] TimeZoneListMaxSize
- [ ] DSTOffsetListMaxSize
- [ ] SupportsDNSResolve
- [ ] Global Attributes

All-clusters-app has to be enabled with below mentioned commands :
- [ ] SetUTCTime
- [ ] SetTrustedTimeSource
- [ ] SetTimeZone
- [ ] SetTimeZoneResponse
- [ ] SetDSTOffset
- [ ] SetDefaultNTP

### GitHub hash of the SDK that was being used

40fb7c246671e9d37ca8bb2cfbf37f81c1509334

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by cjandhyala** [comment]
PR  #26082 to address this

**Comment by cecille** [comment]
The linked PR has now been merged - all clusters should have time sync support now.
