### ISSUE TITLE
[BUG] [OTA] event not reported in time

### ISSUE THREAD

**Issue by step0035** [project-chip/connectedhomeip#27379]
### Reproduction steps

In TC-SU-2.7
`otasoftwareupdaterequestor subscribe-event state-transition 5  10 0x1234567890 0`

- This step sets the min reporting interval to 5seconds and max reporting interval to 10seconds.
- Once the event is subscribed, execute OTA.
- For some platforms, to prepare for OTA, it needs to erase the flash, which is a blocking call and might exceed the max reporting interval of 10seconds.
- Once the event is missed, the chiptool will not continue to get events from the DUT, causing the test case to fail.
- May I know if this is an expected behaviour?

### Bug prevalence

always

### GitHub hash of the SDK that was being used

83f7a2fe136e0b746db09f1d19e36c693a634b66

### Platform

ameba

**Comment by bzbarsky-apple** [comment]
@step0035 Which state is being transitioned into here, exactly?  "Applying"?  Something else?

**Comment by step0035** [comment]
@bzbarsky-apple , all of the states are not reporting. Chiptool doesn't even get the periodic subscription report.

**Comment by bzbarsky-apple** [comment]
I understand that.  My question was which state transition event, if any would follow immediately after the flash erasure.

That is, if erasing flash took 0 time, what event would you expect to get?

**Comment by step0035** [comment]
The first event transition should be Idle (0x01) => Querying (0x02).

**Comment by bzbarsky-apple** [comment]
OK.  So how should this work for a real client, not chip-tool, that uses a smallish max-interval?

**Comment by step0035** [comment]
Since the subscription is out of sync, to continue to get the subscription reports from server, the client should initiate a re-subscription request.

In my opinion, this is a correct behavior by client/chip-tool. So for TC-SU-2.7 specifically, do you think it could potentially be a test plan issue? Maybe the max-interval should be longer.

**Comment by bzbarsky-apple** [comment]
Yes, that would make sense for the test plan.  Which means probably an issue is needed for https://github.com/CHIP-Specifications/chip-test-plans/

**Comment by step0035** [comment]
Yes, I think we need to find a way to handle it better rather than changing the test plan. Thanks, I will look into it.

**Comment by bzbarsky-apple** [comment]
Did some looking around, and given XIP flash options here might be pretty limited, and in fact the test plan expectation may not be reasonable.

**Comment by step0035** [comment]
There's a way to bypass this on platform level. Instead of erasing the whole flash at one go, we can erase one sector at a time before writing a sector to flash.
