### ISSUE TITLE
Implement full ZCL stack in a single uber-accessory/client

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#2737]
#### Problem
In order to test all ZCL functionality, and end to end tests for our real end to end real stack - we should import all clusters into a client/accessory server that run CI on all them.

 #### Proposed Solution
• Until we have ZAP complete let's hand roll client/server
• Have this in iOS App, CHIP.framework, lib chip, chip-tool

**Comment by bzbarsky-apple** [comment]
chip-all-clusters-app does this.
