### ISSUE TITLE
lighting-app efr32: NewPairing() expects 2 arguments, 5 provided

### ISSUE THREAD

**Issue by pierredelisle** [project-chip/connectedhomeip#2741]
lighting-app efr32 fails to build:

../../src/Server.cpp: In function 'void StartServer(DemoSessionManager*)':
../../src/Server.cpp:224:100: error: no matching function for call to 'chip::SecureSessionMgr<chip::Transport::UDP>::NewPairing(chip::Optional<long long unsigned int>, chip::Optional<chip::Transport::PeerAddress>&, int, int, chip::SecurePairingUsingTestSecret*)'
  224 |     err = sessions->NewPairing(Optional<NodeId>::Value(kUndefinedNodeId), peer, 0, 0, &gTestPairing);
      |                                                                                                    ^
In file included from ../../src/Server.cpp:37:
../../third_party/connectedhomeip/src/transport/SecureSessionMgr.h:133:16: note: candidate: 'CHIP_ERROR chip::SecureSessionMgrBase::NewPairing(const chip::Optional<chip::Transport::PeerAddress>&, chip::SecurePairingSession*)'
  133 |     CHIP_ERROR NewPairing(const Optional<Transport::PeerAddress> & peerAddr, SecurePairingSession * pairing);
      |                ^~~~~~~~~~
../../third_party/connectedhomeip/src/transport/SecureSessionMgr.h:133:16: note:   candidate expects 2 arguments, 5 provided

This error occurs as of:
46b482a8   Mon Sep 21 14:14:19 2020

**Comment by woody-apple** [comment]
SW BRB: This appears to work.. are you still hitting this issue? If so please re-open!
