### ISSUE TITLE
[1.1] [WNCV-3.4-1b] The switch from closing to starting cannot be completed within 6s

### ISSUE THREAD

**Issue by maenkai** [project-chip/connectedhomeip#27454]
### Reproduction steps

1b case from
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/window_covering.adoc#tc-wncv-3-4-uporopen-command-long-run-verification-dut_server

1. The switch from closing to starting cannot be completed within 6s
2. The actual hardware takes 8s to do this because of the delay in bridging the device response and the time required for the hardware to switch directions

### Bug prevalence

every time

### GitHub hash of the SDK that was being used

82db97695c2c899cc130c2d6a0d72b3c92c144db

### Platform

esp32

### Type

Spec Compliance Issue

### Anything else?

[_2023_6_25_12_12_28.log](https://github.com/project-chip/connectedhomeip/files/11858786/_2023_6_25_12_12_28.log)

**Comment by bzbarsky-apple** [comment]
Test plan says "5-15" seconds, so whatever is requiring "6s" is broken.  Sounds like a bug in the verification steps?  Those should be filed in https://github.com/CHIP-Specifications/chip-certification-tool
