### ISSUE TITLE
[Build] High memory consumption when compiling on WSL2

### ISSUE THREAD

**Issue by ericzijian1994** [project-chip/connectedhomeip#27466]
### Build issue(s)

1. Compiling some routines, such as chip-tool, consumes a lot of memory and can cause WSL2 to die if limits are not added manually.
2. After compiling, it seems that there is still a lot of memory that has not been freed。

**Comment by woody-apple** [comment]
@ericzijian1994 Shouldn't this be filed against WSL2 if the memory isn't being reclaimed?

**Comment by bzbarsky-apple** [comment]
@ericzijian1994 chip-tool has a fairly large binary, so large memory use during link is expected.
