### ISSUE TITLE
CASE: Send Busy response when we are in the middle of handshake and receives sigma1

### ISSUE THREAD

**Issue by shubhamdp** [project-chip/connectedhomeip#27473]
### Type

Other

### Explanation

Once https://github.com/project-chip/connectedhomeip/pull/27226 gets merged, the unsolicited handler for sigma1 will not be unregistered after receiving a sigma1, so we can send the busy response when we receives a sigma1 when we are in the middle of handshake.

### Platform

core (please add to version below)

### Testing

Manually tested with SDK

**Comment by shubhamdp** [comment]
While looking into this I had three options... so though of putting up here.
1. Define a function and do similar stuff what [`SendStatusReport`](https://github.com/project-chip/connectedhomeip/blob/master/src/protocols/secure_channel/PairingSession.h#L135) from PairingSession.h is doing.
2. `SendStatusReport()` is not dependent on anything from PairingSession and it just requires exchange context which it takes as an argument, so can we make it static?
3. Move `SendStatusReport()` to ExchangeContext besides [`SendMessage`](https://github.com/project-chip/connectedhomeip/blob/master/src/messaging/ExchangeContext.cpp#L133) so that we call it using exchange context. And we stop duplicating Sending status response code.

Thoughts/

**Comment by bzbarsky-apple** [comment]
@shubhamdp I really like option 3.  Presumably this will have SendStatusReport taking `const Protocols::SecureChannel::StatusReport &` or so?  Having that be a single utility on exchanges makes a _lot_ of sense.

**Comment by bzbarsky-apple** [comment]
I guess another option would be to have a `SendOnExchange` on `SecureChannel::StatusReport`, but that seems like a bit of a layering issue.....

**Comment by shubhamdp** [comment]
1. Going with this... and implemented in the PR #28153
2. Since SendStatusReport is protected and I did not feel good about making it private, so avoided that path.
3. I see the cyclic dependency issue so, could not get around it

I'll raise an issue to see if I can optimize the SendStatusReport bits to avoid code duplication.

**Comment by bzbarsky-apple** [comment]
> I see the cyclic dependency issue so, could not get around it

@shubhamdp what was the cyclic dependency?

**Comment by shubhamdp** [comment]
After https://github.com/project-chip/connectedhomeip/pull/28219 got merged, going with option 3, where we add `SendStatusReport()` API on `ExchangeContext`.
