### ISSUE TITLE
Align DescriptorCluster and SemanticTagStruct with the spec draft

### ISSUE THREAD

**Issue by robszewczyk** [project-chip/connectedhomeip#27556]
The latest changes move the `Label` field from `TagStruct` to `SemanticLabelStruct`.  As a result:

* `TagList` attribute in the Descriptor  cluster changes types to `list[SemanticLabelStruct]`
* `SemanticLabelStruct` contains the following fields:

| ID | Name      | Type       |
|---|---|---|
| 0  | MfgCode   | vendor-id |
| 1  | Namespace | namespace | 
| 2  | Tag    | tag       |
| 3  | Label     | string    |

**Comment by jadhavrohit924** [comment]
Fixed with #27905 and #28753
