### ISSUE TITLE
Align SDK to change in InvalidInMode/INVALID_IN_MODE for ModeBase

### ISSUE THREAD

**Issue by rbultman** [project-chip/connectedhomeip#27560]
Change SDK as needed due to moving the INVALID_IN_MODE status from the interaction model to ModeBase.

Reference PR https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7273

**Comment by bzbarsky-apple** [comment]
Looks like we do not currently have any useful XML for Mode Base, and the "core" status values for it are not expressed anywhere in XML, just in `src/app/clusters/mode-base-server/mode-base-cluster-objects.h`.

So nothing left to do here.
