### ISSUE TITLE
Add `LastChangedTime` to Resource Monitoring Cluster Definition

### ISSUE THREAD

**Issue by p0fi** [project-chip/connectedhomeip#27570]
# 📖 Description
The discussion around the replacement product list caused spec changes. It added 2 new attributes. This issue should only add the `LastChangedTime` to the cluster definition since its unclear if the second attribute will make it into to spec in time.

**Comment by robszewczyk** [comment]
Possible dup of https://github.com/project-chip/connectedhomeip/issues/27562. If tracking this one for ongoing work / resolution, please note this issue number in the spec PR

**Comment by p0fi** [comment]
This is no straight forward dup. It's by design split up into more than one issue (see #27571) to track the work and help make the PRs the right scope and size. Although I was not aware of https://github.com/project-chip/connectedhomeip/issues/27562 existing :)
