### ISSUE TITLE
[Darwin] Need new API to suspend operations

### ISSUE THREAD

**Issue by jtung-apple** [project-chip/connectedhomeip#27582]
For Darwin framework clients that wishes to go away for any reason (e.g. about to disconnect from network) and that wants devices to stop sending subscription reports, there should be an API.

This API should be on MTRDeviceController and be named something similar to "suspend / resume" but more applicable to the Matter API.

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/29273
