### ISSUE TITLE
[TC-FAN-2.3 & 2.4] RockSupport and WindSupport attribute value doesn't satisfy the spec

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27605]
### Reproduction steps

`./chip-tool fancontrol read rock-support 1 1`

> [1688392778.789627][3332:3334] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0202 Attribute 0x0000_0007 DataVersion: 1138422270
> [1688392778.789796][3332:3334] CHIP:TOO:   RockSupport: 3

`./chip-tool fancontrol read wind-support 1 1`

> [1688392809.598691][3335:3337] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0202 Attribute 0x0000_0009 DataVersion: 1138422270
> [1688392809.598838][3335:3337] CHIP:TOO:   WindSupport: 3

### Bug prevalence

Whenever I do this 

### GitHub hash of the SDK that was being used

7ae5919a046a18c7e60537aff814977ee424b9cf - Master

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

### Anything else?

Spec Reference: https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/FanControl.adoc#5-data-types
![image](https://github.com/project-chip/connectedhomeip/assets/95559513/20e1bec0-dcdf-4dcc-b991-a4a167c7725d)
As per the SPEC the maximum support value for RockSupport can be 2 and WindSupport can be 1 but the value reproduced is 3, This issue is reflected in write function of Rocksetting and Wind setting as we are able to write more than the supported modes.

**Comment by bzbarsky-apple** [comment]
> As per the SPEC the maximum support value for RockSupport can be 2

No, this is a _bitmap_.  The maximum value is 7.  The value 3 means "RockLeftRight and RockUpDown are supported, RockRound is not supported."

>  and WindSupport can be 1

It can be 3, which means "both SleepWind and NaturalWind are supported".
