### ISSUE TITLE
[Events] Need YAML support to trigger events.

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#27602]
### Feature description

Summary:
Need YAML support to `trigger` the events. If support is already there please share us the sample script.
Eg: DRLK-2.10: Step 1:  Trigger the DUT to generate DoorLockAlarm Event (by LockJammed scenario)

Effectced tests:
TC-DGSW-2.2
TC-DRLK-2.10

### Platform

other

### Anything else?

Screenshot:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/2ea14305-434e-4eda-abdd-7da4374a2562)
![Screenshot from 2023-07-03 17-34-39](https://github.com/project-chip/connectedhomeip/assets/102359958/b6fd347b-b7d1-4552-af84-80916e044de3)
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/e5182c9c-a3e6-4459-8768-d7d473d66399)

**Comment by bzbarsky-apple** [comment]
YAML can't trigger an event on an actual DUT.  You need to either physically interact with the DUT or use the TestEventTrigger bits with DUT-specific payloads.
