### ISSUE TITLE
[Scenes] Need to increase SceneTableSize attribute value to validate other functionalities like Add and Remove scene

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#27613]
### Summary:
For the test cases like TC-S-2.2, TC-S-2.3, TC-S-2.4, and TC-S-2.5 we have multiple function like Add scene , Remove Scene, View Scene, Store Scene the Scene Table Size has to be more than zero to validate in cert test.

### Feature description

...
1. Read SceneTableSize : .`/chip-tool scenes read scene-table-size 1 1`

> [1685167609.521892][13200:13202] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0005 Attribute 0x0000_0006 DataVersion: 1420980441
> [1685167609.521932][13200:13202] CHIP:TOO:   SceneTableSize: 0

2. Add scene to the added group : `./chip-tool scenes add-scene 1 1 0 "scene name" '[{"clusterID": "0x0006", "attributeValueList":[{"attributeID": "0x0000", "attributeValue": "0x01"}]},{"clusterID": "0x0008", "attributeValueList":[{"attributeID": "0x0000", "attributeValue": "0x64"},{"attributeID": "0x0001", "attributeValue": "0x00"}]}]' 1 1`

> [1688464612.526900][8648:8651] CHIP:DMG: Received Command Response Data, Endpoint=1 Cluster=0x0000_0005 Command=0x0000_0000
> [1688464612.526959][8648:8651] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0005 Command 0x0000_0000
> [1688464612.527035][8648:8651] CHIP:TOO:   AddSceneResponse: {
> [1688464612.527081][8648:8651] CHIP:TOO:     status: 137
> [1688464612.527110][8648:8651] CHIP:TOO:     groupID: 1
> [1688464612.527138][8648:8651] CHIP:TOO:     sceneID: 1
> [1688464612.527166][8648:8651] CHIP:TOO:    }

### Platform

raspi

### Platform Version(s)

RPI4 8GB RAM

### Anything else?

While trying to remove the scene before it is added DUT responses with status failure but for the same Test plan expects Success response.
In Test case 2.2 step 1b : `./chip-tool scenes remove-all-scenes 0x0001 1 1`
**Actual Outcome:**

> [1686815342.516889][12148:12150] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0005 Command 0x0000_0003
> [1686815342.516902][12148:12150] CHIP:TOO:   RemoveAllScenesResponse: {
> [1686815342.516908][12148:12150] CHIP:TOO:     status: 1
> [1686815342.516911][12148:12150] CHIP:TOO:     groupID: 1
> [1686815342.516914][12148:12150] CHIP:TOO:    }

**Expected Outcome:**

> [1686815342.516889][12148:12150] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0005 Command 0x0000_0003
> [1686815342.516902][12148:12150] CHIP:TOO:   RemoveAllScenesResponse: {
> [1686815342.516908][12148:12150] CHIP:TOO:     status: 0
> [1686815342.516911][12148:12150] CHIP:TOO:     groupID: 1
> [1686815342.516914][12148:12150] CHIP:TOO:    }

**Comment by lpbeliveau-silabs** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/29569/files
