### ISSUE TITLE
[Darwin] Consider MTRDevice API to include mechanism to trigger subscription immediately

### ISSUE THREAD

**Issue by jtung-apple** [project-chip/connectedhomeip#27639]
As a follow up to #27582 which is more a general Matter stack unsubscribe/resubscribe, MTRDevice API should have a mechanism to trigger subscription immediately.

This can be useful for API clients that is changing networks / reconnecting, and knows when specific devices should become available.

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/29272
