### ISSUE TITLE
[Darwin] MTRDevice subscription should take a hint of subscription paths

### ISSUE THREAD

**Issue by jtung-apple** [project-chip/connectedhomeip#27641]
Currently MTRDevice does a wildcard subscription to everything. This issue is to track:
* Allow the API client to specify a limited set of interested attribute paths (including wildcards)
* Coalesce the paths into a reasonable number of paths for subscription
* Manage read-throughs when this mechanism is used

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/29272
