### ISSUE TITLE
Remove Previously Provisionally Aliased Concentration Measurement Clusters From the SDK

### ISSUE THREAD

**Issue by mhazley** [project-chip/connectedhomeip#27662]
### Description 

Following discussion on https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7234, the previously provisional clusters will be removed from the Spec, so this issue is to ensure they are removed from the SDK. 

This amounts to:

* Ethylene,
* Ethylene Oxide,
* Hydrogen,
* Hydrogen Sulfide,
* Nitric Oxide,
* Oxygen,
* Sulfur Dioxide,
* Dissolved Oxygen,
* Bromate,
* Chloramines,
* Chlorine,
* Fecal coliform & E. Coli,
* Fluoride,
* Haloacetic Acids,
* Total Trihalomethanes,
* Total Coliform Bacteria,
* Turbidity,
* Copper,
* Lead,
* Manganese,
* Sulfate,
* Bromodichloromethane,
* Bromoform,
* Chlorodibromomethane,
* Chloroform
* Sodium

**Comment by woody-apple** [comment]
@mhazley Trying to move folks to using issue templates, should we propose a new template so we can auto add labels, and such?
