### ISSUE TITLE
[BUG] darwin-framework-tool test fails in Smoke CO Alarm

### ISSUE THREAD

**Issue by ericzijian1994** [project-chip/connectedhomeip#27907]
### Reproduction steps

Since the Smoke CO Alarm cluster is added to the provisional list in availability.yaml, no relevant code is generated, but test_cluster.zapt still generates code that results in undeclared identifiers.

[logs.txt](https://github.com/project-chip/connectedhomeip/files/12026349/logs.txt)

### Bug prevalence

always

### GitHub hash of the SDK that was being used

7fc3ccba35d4df7d2d3ba8603ff72d218af0b1a7

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
The test should be added to the "disable" section in examples/darwin-framework-tool/templates/tests/ciTests.json with comments similar to the other tests that are disabled there.

**Comment by ericzijian1994** [comment]
> The test should be added to the "disable" section in examples/darwin-framework-tool/templates/tests/ciTests.json with comments similar to the other tests that are disabled there.

I've already disabled them here in #27123, but it doesn't work.

I see `{{#if (isSupported (asUpperCamelCase name preserveAcronyms=true))}}` statements in other zapt files, but the test_cluster.zapt file that is causing the error does not have this code.

**Comment by bzbarsky-apple** [comment]
> I've already disabled them here in https://github.com/project-chip/connectedhomeip/pull/27123, but it doesn't work.

That's because you didn't disable all of them, no?  I only see 2_2 through 2_6 listed under the disabled bit, butwhat about 2_1 and 1_1?

> but the test_cluster.zapt file that is causing the error does not have this code.

That's correct, because it can't tell what would need to be supported for which YAML file.

I am working on having darwin-framework-tool be able to do all the bits, including "provisional" ones, but for now please just add them to that "disabled" list.

**Comment by ericzijian1994** [comment]
I see, thanks.
