### ISSUE TITLE
getBaseDevice deprecated

### ISSUE THREAD

**Issue by LucaFagan** [project-chip/connectedhomeip#27918]
### Feature description

getBaseDevice is deprecated in iOS 16.4

xCode suggests to use [MTRBaseDevice deviceWithNodeID:controller:] 

but this api always succeed, even if there is no the node id on the controller or the device is offline

How can I check if the device is online ?

### Platform

darwin

### Platform Version(s)

1.0

**Comment by bzbarsky-apple** [comment]
> How can I check if the device is online ?

You try to send a command/read/write and see what happens. Or subscribe and get notified if the subscription drops.

In particular, there is absolutely no guarantee that a device is online if `getBaseDevice` succeeds.  The device could go offline right after the end ofthe CASE handshake.
