### ISSUE TITLE
[Feature] Consider adding a way to set a delegate on MTRDevice without starting a subscription

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#27926]
### Feature description

We may have some situations where the client is fundamentally not able to maintain a subscription (e.g. the client is basically an ICD).  In those situations, we may want to set up a delegate on the MTRDevice and then just rely on the read-throughs.

### Platform

darwin

**Comment by woody-apple** [comment]
Closing this, we're taking this approach: https://github.com/project-chip/connectedhomeip/issues/29272
