### ISSUE TITLE
[OPSTATE]SDK need to implement the OperationalError Event and OperationCompletion Event

### ISSUE THREAD

**Issue by mideayanghui** [project-chip/connectedhomeip#27928]
### Reproduction steps

The Operational State SDK need to implement the follow event,

- [ ] OperationalError 
- [ ] OperationCompletion

### Bug prevalence

xxx

### GitHub hash of the SDK that was being used

xxx

### Platform

core

### Type

Common Cluster Logic

**Comment by bzbarsky-apple** [comment]
@mideayanghui Please link to the actual review comments describing what needs to be done here...
