### ISSUE TITLE
[OPSTATE] OperationalState attribute has changed to be an enum, not a struct

### ISSUE THREAD

**Issue by mideayanghui** [project-chip/connectedhomeip#27930]
### Reproduction steps

SDK need to update as describe below.
https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7282

### Bug prevalence

xxx

### GitHub hash of the SDK that was being used

xxx

### Platform

other, core

### Type

Common Cluster Logic

**Comment by bzbarsky-apple** [comment]
Might be a duplicate of https://github.com/project-chip/connectedhomeip/issues/27580 ?

**Comment by mideayanghui** [comment]
Yes, duplicate, closed. keep #27580
