### ISSUE TITLE
[Build] Error when I running source scripts/activate.sh command on ubuntu 20.04

### ISSUE THREAD

**Issue by LongND0105** [project-chip/connectedhomeip#27977]
### Build issue(s)

![image](https://github.com/project-chip/connectedhomeip/assets/133942344/2c3af966-8919-444e-b97d-c705b88e213f)

### Platform

other

**Comment by absoluteabutaj** [comment]
@LongND0105 - How about `. ./scripts/activate.sh`?

**Comment by woody-apple** [comment]
@andy31415 ?

**Comment by andy31415** [comment]
is PW_ENVIRONMENT_ROOT set to `/` by any chance. I see logs saying `permission denied /.environment`.
