### ISSUE TITLE
[Groups] TC-ACE-1.6 - `0x000000AC: Internal error` causes failure in YAML

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#27982]
### Reproduction steps

Summary: According to test-plan test ACE-1.6 step 7: `AddGroup` command with groupID set to 0x0104 expected outcome is `no response` but got `failure: src/transport/SessionManager.cpp:194: CHIP Error 0x000000AC: Internal error` when executed.

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:ACE_Groups_ChipError_Response

Reproduction step:
- Terminal 1:

  1. Build All-cluster-app 
       `scripts/examples/gn_build_example.sh      examples/all-clusters-app/linux/      examples/all-clusters-app/linux/out/all-clusters-app   chip_inet_config_enable_ipv4=false`
  2. Run ./chip-all-clusters-app

- Terminal 2:

  1. Build Chip-tool :
       `gn gen out/debug --args='chip_mdns="platform" chip_inet_config_enable_ipv4=false' 
        ninja -C out/debug`
  2. Commission DUT and TH :
       `./out/debug/chip-tool pairing code 0x12344321 MT:-24J0AFN00KA0648G00`
  3. Run ACE-1.6 test:
       `./scripts/tests/yaml/chiptool.py tests Test_TC_ACE_1_6`

### Bug prevalence

Everytime when executed

### GitHub hash of the SDK that was being used

b6caecf7860072bd4e55be43dc830b5ce990ddef

### Platform

other

### Anything else?

Test-plan:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/cddba764-30bd-486f-8a48-7e75a244b133)
Execution logs:
![Screenshot from 2023-07-13 12-03-57](https://github.com/project-chip/connectedhomeip/assets/102359958/6d2ce856-2323-4944-b16b-d5ae6436f2a6)
[ACE_Fail_logs.zip](https://github.com/project-chip/connectedhomeip/files/12067019/ACE_Fail_logs.zip)

**Comment by manjunath-grl** [comment]
Closing the ticket. Duplicate of https://github.com/project-chip/connectedhomeip/issues/27967

**Comment by manjunath-grl** [comment]
Still facing issue attached logs for reference:
Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:connectedhomeip:ACE_Groups_ChipError_Response

Execution logs:
[ACE_Fail_logs.txt](https://github.com/project-chip/connectedhomeip/files/12273321/ACE_Fail_logs.txt)

Screenshots:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/cbcf0974-3bb7-4ce8-92d4-f7e2ba431e41)
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/c3eb89ab-c66a-4a9d-b39d-c2cdd89efa27)

**Comment by sumaky** [comment]
Step 7 is trying to add new group of ID 261( 0X105) using an existing group ID (0x104) that does not have privilege
Test plan does not check for any outcome and moves on with the next step.
The objective is to check no groupid of 0x105 should be added and this is done via ViewGroup using unicast method at later point of time.
The script needs to ignore as there is no expected outcome and needs to continue with the next steps.

Please let me know if there is any issue in continuing with the next steps?

**Comment by cecille** [comment]
Does this error occur with the current manual steps? Or does this happen when you try to implement the yaml?

**Comment by manjunath-grl** [comment]
From @sumaky comment we can understand the there wouldn't be response for the group command and script needs to ignore and proceed with next steps. But while implementing in YAML, even though we don't mention any expected response by default it expects to be  'SUCCESS' if nothing is specified.

**Comment by cecille** [comment]
Yeah, the problem here is that the group command is failing in the controller because the TH doesn't have an entry for that key. It's a tooling problem. Have a patch out to suma for testing.
