### ISSUE TITLE
[ICD] Implement the Session Active Threshold Discovery Key

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#28025]
This task is in two steps :
1) Implement the SAT Discovery key with default value and update client side to take in the key into consideration in the MRP calculations

```
The optional key SAT indicates the SESSION_ACTIVE_THRESHOLD of the Node. 
This key MAY optionally be provided by a Node to override the default setting.
 If the key is not included or invalid, the Node querying the service record SHALL use the default MRP parameter value. 
The SAT value is an unsigned integer with units of milliseconds and SHALL be encoded as a variable-length decimal number in ASCII encoding, omitting any leading zeros. 
The SAT value SHALL NOT exceed 65535 (65.535 seconds). 
```
Add the Active mode threshold to the session-parameter-struct as define the MRP specification

```
session-parameter-struct => STRUCTURE [ tag-order ]
{
  SESSION_IDLE_INTERVAL     [1, optional] : UNSIGNED INTEGER [ range 32-bits ],
  SESSION_ACTIVE_INTERVAL   [2, optional] : UNSIGNED INTEGER [ range 32-bits ],
  SESSION_ACTIVE_THRESHOLD  [3, optional] : UNSIGNED INTEGER [ range 16-bits ],
} 
```
When the client resolves the SAT key, the value of the key should be used to determine if the peer is active or not instead of using the default 4000s value.

In `Session.h`, 
`constexpr System::Clock::Milliseconds32 kMinActiveTime = System::Clock::Milliseconds32(4000); `
 

2) When the device is an ICD, the device should advertise the attribute value in the discovery key. with the SAI and SII keys.

**Comment by bzbarsky-apple** [comment]
Please watch out for https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7315 when fixing this.
