### ISSUE TITLE
Fail to use zap tool to open the zap file after pull the master branch

### ISSUE THREAD

**Issue by mideayanghui** [project-chip/connectedhomeip#28102]
### Reproduction steps

1. I pull the master branch `commit 0869e98d0`
2. git submodule update --init --recursive
3. while  run the command as below, I face a problem, and tell me need to update the zap.
./scripts/tools/zap/run_zaptool.sh examples/all-clusters-app/all-clusters-common/all-clusters-app.zap
4. I delete `.environment`, and `source script/bootstrap.sh`
5. After finish the bootstrap,  use `./scripts/tools/zap/run_zaptool.sh examples/all-clusters-app/all-clusters-common/all-clusters-app.zap` to open the zap. But got the problem as picture show,
![image](https://github.com/project-chip/connectedhomeip/assets/106149377/1b948efd-dd63-492a-8dbb-e35d3d6cd53e)

I can get to selection of clusters. 
may be same as https://github.com/project-chip/zap/issues/1077

### Bug prevalence

always

### GitHub hash of the SDK that was being used

0869e98d0

### Platform

python, vscode

### Platform Version(s)

xxx

**Comment by bzbarsky-apple** [comment]
This is ZAP breakage, but different from the one linked above.  Filed https://github.com/project-chip/zap/issues/1080
