### ISSUE TITLE
[Feature] replace the use of EMBER_AF_PLUGIN_MODE_BASE with a BUILD.gn variable

### ISSUE THREAD

**Issue by hicklin** [project-chip/connectedhomeip#28155]
### Feature description

Remove `#define EMBER_AF_PLUGIN_MODE_BASE` form the all-clusters-app `CHIPProjectAppConfig.h` and find a solution using the BUILD.gn.

Update the Mode Base readme.

### Platform

all

**Comment by hicklin** [comment]
See the conversation [here](https://github.com/project-chip/connectedhomeip/pull/27504/files/088e22c85a2ec01b9c4bfd7ffea16850748a8c94#r1243731838).

**Comment by bzbarsky-apple** [comment]
Better conversation link that will not break: https://github.com/project-chip/connectedhomeip/pull/27504/#discussion_r1243731838

**Comment by hicklin** [comment]
Should I close this issue given that there are no strong opinions against the current implementation? 

If matter continues to utilise zap and generated code, the best way that I think this can be implemented is to have the code regen script define `EMBER_AF_PLUGIN_MODE_BASE` with all the others in `gen_config.h` once, when at least one ModeBase derived cluster is enabled.
