### ISSUE TITLE
[CI error]Build example - Open IoT SDK / Open IoT SDK examples building error

### ISSUE THREAD

**Issue by mideayanghui** [project-chip/connectedhomeip#28158]
### Reproduction steps

src/test_driver/openiotsdk/integration-tests/tv-app/test_app.py::test_smoke_test 
-------------------------------- live log setup --------------------------------
09:34:19.391   INFO   Starting "FVPdev" runner...
09:34:19.647   INFO   "FVPdev" runner started
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
--------------------------------- JSON report ----------------------------------
report saved to: /__w/connectedhomeip/connectedhomeip/src/test_driver/openiotsdk/integration-tests/tv-app/test_report_tv-app.json
=========================== short test summary info ============================
FAILED src/test_driver/openiotsdk/integration-tests/tv-app/test_app.py::test_command_check - AssertionError: assert 'added pp' == 'added app'
  - added app
  ?       -
  + added pp
============== 1 failed, 3 passed, 3 warnings in 81.75s (0:01:21) ==============

Please see this link in detail.
https://github.com/project-chip/connectedhomeip/actions/runs/5620526957/job/15229640737?pr=27748

### Bug prevalence

always

### GitHub hash of the SDK that was being used

a1c1126e457

### Platform

core

### Platform Version(s)

xxx

### Type

Platform Issue

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures
