### ISSUE TITLE
[ReadHandler] Allow custom ReportScheduler Injection

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#28183]
Currently, we are choosing between unsynchronized and synchronized report scheduler by a define in CHIPConfig.h :
`CHIP_CONFIG_SYNCHRONOUS_REPORTS_ENABLED`

We could allow users to define their own scheduler by allowing injection from the app layer by passing a pointer to a reportscheduler implementaiton in the Server::Init()

**Comment by bzbarsky-apple** [comment]
> We could allow users to define their own scheduler by allowing injection from the app layer

Uh... that is in fact what you have currently implemented, no?  I am very unclear as to what this issue is about @lpbeliveau-silabs .

**Comment by lpbeliveau-silabs** [comment]
While it was the case at some point during the merge of integration, it was removed on a request in the integration PR: https://github.com/project-chip/connectedhomeip/pull/28104#discussion_r1269825651

We currently offer the option between the Synchronized Scheduler and the default one from config, however it is not in _ServerInitParams_ anymore.

A user would need to edit Server.cpp/.h to be able to change the scheduling logic.
