### ISSUE TITLE
[CERT-TEST-FAILURE]- TC-ACFREMON-1.1 - Test failed

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#28197]
### Feature Area

Other

### Test Case

TC-ACFREMON-1.1

### Reproduction steps

1. Bring up the DUT with all-cluster-app.
2. Pair the DUT using chip-tool through "onnetwork" transport.
3. Run the command `./chip-tool activatedcarbonfiltermonitoring read feature-map 1 1`

**Expected Outcome:** 
> [1690181499.378839][8062:8064] CHIP:DMG: }
> [1690181499.379113][8062:8064] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0071 Attribute 0x0000_FFFC DataVersion: 1402797121
> [1690181499.379203][8062:8064] CHIP:TOO:   FeatureMap: 7
> [1690181499.379409][8062:8064] CHIP:EM: <<< [E:11917i S:34360 M:35635505 (Ack:251547236)] (S) Msg TX to 1:0000000000000001 [5C90] --- Type 0000:10 (SecureChannel:StandaloneAck)

**Actual Outcome:**
> [1690181499.378839][8062:8064] CHIP:DMG: }
> [1690181499.379113][8062:8064] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0071 Attribute 0x0000_FFFC DataVersion: 1402797121
> [1690181499.379203][8062:8064] CHIP:TOO:   FeatureMap: 3
> [1690181499.379409][8062:8064] CHIP:EM: <<< [E:11917i S:34360 M:35635505 (Ack:251547236)] (S) Msg TX to 1:0000000000000001 [5C90] --- Type 0000:10 (SecureChannel:StandaloneAck)

### Bug prevalence

Whenever I try to read FeatureMap.

### GitHub hash of the SDK that was being used

c1ec2d777456924dcaa59b53351b00d73caf378f

### Platform

raspi

### Anything else?

As per the Replacement Product List feature implementation, the FeatureMap attribute value should be 7. But currently getting FeatureMap value as 3 in SDK.

**Comment by andy31415** [comment]
@cliffamzn Could you take a look regarding feature map flags here?
