### ISSUE TITLE
Can I bind 2 endpoints on the same aggregator?

### ISSUE THREAD

**Issue by LongND0105** [project-chip/connectedhomeip#28206]
I have a Zigbee to Matter bridge. I create a aggregator device (contains zigbee device). I create 1 on/off light endpoint and 1 light switch endpoint (using macro in order to create dymanic endpoint), now I want to bind the on/off light to the light switch. In theory, can I do that and if so, how do I do it?

**Comment by bzbarsky-apple** [comment]
Duplicate of https://github.com/project-chip/connectedhomeip/issues/21626
