### ISSUE TITLE
[ICD] Implement LIT ICD SII discovery Toggle

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#28231]
#### Description
When a LIT ICD does not have a ICDM cluster registration entry, it needs to behave like a SIT ICD until a controller registers a valid entry. This implies that it shall have a shorter polling interval and it advertise it over SII.

When a controller register an entry, the ICD will remove the SII key and return to LIT operating mode.

**Comment by jmartinez-silabs** [comment]
Addressed by https://github.com/project-chip/connectedhomeip/pull/30422
