### ISSUE TITLE
[ICD] Implement client-side Unsolicited Message handler for check-in messages

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#28232]
#### Description
Controllers need to register an UnsolicitedMessageHandler to be able to receive, process check-in message sent by ICDs, and refresh key as needed.

**Comment by yunhanw-google** [comment]
you can consider to take ICDClientStorage.hwhen you init your checkin handler, then implement CHIP_ERROR DefaultICDClientStorage::ProcessCheckInPayload(const ByteSpan & payload, ICDClientInfo & clientInfo)

in this callback function, it would do nouce validation via CheckinMessage::ParseCheckinMessagePayload, then check against counter, if counter is out of range, just ask service or locally in our case to refresh key, then further notify to restart subscription.
