### ISSUE TITLE
Add SetFlag/ClearFlag methods to Header::Flags

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#2823]
#### Problem
Trying to clear a flag via `flags.value &= ~flag` runs into `-Wconversion` warnings necessitating manual casts, because applying `~` to a `uint16_t` produces an `int`.

 #### Proposed Solution
Add a `ClearFlag` method to clear flags, so we can have the relevant casting in just one spot.  Add `SetFlag` for symmetry.

@andy31415 you asked me to assign this to you, but I can also just pick this up.  Let me know, please!

**Comment by andy31415** [comment]
Feel free to pick it up - I will assign this to myself if I get to it. For now I was planning to try for some reliable messaging which takes a while.

I will unassign and whoever has bandwidth can self-assign.
