### ISSUE TITLE
[ICD] Implement client-side interaction buffering

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#28233]
#### Description
By definition, LIT ICD will not be reachable unless they have notified that they are available for communication. This implies that controllers will need to buffer their interactions until a LIT ICD checks in with a check-in message or subscription report.

Implement a buffering mechanism that stores all pending interactions until an ICD checks in.

**Comment by yunhanw-google** [comment]
https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7622
closed
