### ISSUE TITLE
[BUG] Unable to pair M5 board / nordic using chip tool 

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#28241]
### Reproduction steps

Unable to pair the M5 board / nordic board with chip tool app using SHA d328c30ffb91b1703ddd09e5a060fd3cd2e47b5b

Steps to Reproduce:

On terminal 1:

1. cd ~/connectedhomeip
2. git reset --hard d328c30ffb91b1703ddd09e5a060fd3cd2e47b5b
3. git clean -Xdf
4. git submodule update --init
5. source scripts/bootstrap.sh
6. source scripts/activate.sh
7. export ZAP_INSTALL_PATH=~/Downloads/zap-mac/
8. gn gen out/debug --args='chip_mdns="platform"'
9. ninja -C out/debug

On terminal 2:
Put M5 in pairing mode

1. cd ~/connectedhomeip
2. source scripts/activate.sh
3. export ZAP_INSTALL_PATH=~/Downloads/zap-mac/
4. cd ~/tools/esp-idf
5. ./install.sh
6. . ./export.sh
7. cd ~/connectedhomeip/examples/all-clusters-app/esp32
8. export ZAP_INSTALL_PATH=~/Downloads/zap-mac/
9. idf.py build
10. idf.py menuconfig -> (Select M5 stack)
11. idf.py -D 'SDKCONFIG_DEFAULTS=sdkconfig_m5stack.defaults' erase-flash build flash monitor

From terminal 1 execute the following command:
time sudo ./out/debug/chip-tool pairing ble-wifi 1 "wifi_name" password 20202021 3840 --paa-trust-store-path ./credentials/development/paa-root-certs

On terminal 3:
Put nordic in pairing mode

1. cd ~/connectedhomeip
2. source scripts/activate.sh
3. source /Users/priyankahonnakasturi/Desktop/032321_install_nordic_tools.sh
4. python3 scripts/setup/nrfconnect/update_ncs.py --update
5. cd examples/lighting-app/nrfconnect
6. export ZAP_INSTALL_PATH=~/Downloads/zap-mac/
7. west build -b nrf52840dk_nrf52840 --pristine always
8. west flash --erase

From terminal 1 execute the following command:

./out/debug/chip-tool pairing ble-thread 1 hex:0E08000063D80BB10000000300001935060004001FFFC0020814A93EB3E9AD4C340708FD16B6B48DCB407305101F1F13546EB4E68625B43BCB5C720419030F4D79486F6D653137303932373930380102ACF50410067BCAF2D4450681A7CCC3062855C9530C0402A0F7F8 20202021 3840 --paa-trust-store-path ./credentials/development/paa-root-certs

### Bug prevalence

always

### GitHub hash of the SDK that was being used

d328c30ffb91b1703ddd09e5a060fd3cd2e47b5b

### Platform

darwin

### Anything else?

Attaching the nordic logs + M5 logs + chiptool logs from ble + chiptool logs from thread
[chip_tool_thread_logs.txt](https://github.com/project-chip/connectedhomeip/files/12152883/chip_tool_thread_logs.txt)
[nrfboard_logs.txt](https://github.com/project-chip/connectedhomeip/files/12152884/nrfboard_logs.txt)
[chiptool_ble_logs.txt](https://github.com/project-chip/connectedhomeip/files/12152885/chiptool_ble_logs.txt)
[M5Boardlogs.txt](https://github.com/project-chip/connectedhomeip/files/12152886/M5Boardlogs.txt)

**Comment by woody-apple** [comment]
Sorry for the delay, I'm assuming this is working now? (This is a weekly test) can you try this again and see if this is working for you now?
