### ISSUE TITLE
[Build] minimal-mdns-client failed - no space left on drive

### ISSUE THREAD

**Issue by kliao-csa** [project-chip/connectedhomeip#28242]
### Build issue(s)

Fail in build: FAILED: minimal-mdns-client minimal-mdns-client.map
https://github.com/project-chip/connectedhomeip/actions/runs/5646216293/job/15293620944#step:14:1545

Possible cause: LLVM ERROR: IO failure on output stream: No space left on device
https://github.com/project-chip/connectedhomeip/actions/runs/5646216293/job/15293620944#step:14:1547

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures
