### ISSUE TITLE
[Build] Pigweed failure - no space left on device

### ISSUE THREAD

**Issue by kliao-csa** [project-chip/connectedhomeip#28243]
### Build issue(s)

First fail: FAILED: python/gen/third_party/connectedhomeip/third_party/pigweed/repo/pw_env_setup/pigweed_build_venv._install_3p_deps.pw_pystamp
https://github.com/project-chip/connectedhomeip/actions/runs/5646168381/job/15293483651#step:14:777

Possible cause: OSError: [Errno 28] No space left on device
https://github.com/project-chip/connectedhomeip/actions/runs/5646168381/job/15293483651#step:14:1045

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures
