### ISSUE TITLE
Update Spec with text on CASE session handling over TCP

### ISSUE THREAD

**Issue by pidarped** [project-chip/connectedhomeip#28246]

**Comment by bzbarsky-apple** [comment]
Shouldn't this be in https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/ ?

**Comment by pidarped** [comment]
Yes. Apologies. I was trying to use the newly created Project dashboard to create issues and was not able to find the Spec repo. Will close this and reopen in  https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/

**Comment by pidarped** [comment]
Closing this to re-open in the CHIP-Specifications category.
