### ISSUE TITLE
[Android][CHIPTool][Feature] Request to perform NOC generation in cloud but perform device attestation locally

### ISSUE THREAD

**Issue by tnguyen-alarm** [project-chip/connectedhomeip#28270]
### Feature description

On iOS, there was a [`shouldSkipAttestationCertificateValidation`](https://github.com/project-chip/connectedhomeip/blob/d328c30ffb91b1703ddd09e5a060fd3cd2e47b5b/src/darwin/Framework/CHIP/MTROperationalCertificateIssuer.h#L113) flag added that enabled these processes to be decoupled. Their device controller uses that flag to determine whether it should use the default DAC verifier or the partial DAC verifier [here](https://github.com/project-chip/connectedhomeip/blob/d328c30ffb91b1703ddd09e5a060fd3cd2e47b5b/src/darwin/Framework/CHIP/MTRDeviceController.mm#L702-L706)

It would be nice if Android had the same functionality, so we don't have to build CHIP for our cloud servers or re-implement in another tech stack.

### Platform

android

### Platform Version(s)

1.1.0.1

**Comment by yunhanw-google** [comment]
@yufengwangca can we have this flag? thanks
