### ISSUE TITLE
The test plan has "SHALL NOT: bits that are not reflected in this YAML.  File a followup issue, please, add a comment in the YAML pointing to it.

### ISSUE THREAD

**Issue by abpoth** [project-chip/connectedhomeip#28287]
Many .yaml test cases don't seem to account for the "SHALL NOT" include values when testing AttributeList, EventList, AcceptedCommandList, and GeneratedCommandList.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/28023#discussion_r1274099041_

**Comment by manjunath-grl** [comment]
@abpoth Since we have no support for checking the range of values of lists via yaml, we perform this verification step through a manual prompt step. We have opened a ticket while ago in SDK repo for the same https://github.com/project-chip/connectedhomeip/issues/26570
CC @raju-apple @cjandhyala

**Comment by andy31415** [comment]
Considering this not a cert-blocker for now - we are working on better range verification (I believe we had a "manual step", working on automation). #28902 is the original PR regarding this.
