### ISSUE TITLE
[CERT-TEST-FAILURE] - TC-TCTL- 3.2- test failed

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#28293]
### Feature Area

Area:TemperatureControlledCabinet

### Test Case

TC-TCTL- 3.2

### Reproduction steps

Based on Spec, If TN feature implemented the SetTemperature command  should have the TargetTemperature field in SDK but in current SDK it's not implemented 

Expected : SetTemperature command  with TargetTemperature field 
Actual : TargetTemperature field is missing  

PFA Spec Reference
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/82356ebe-6400-4f74-9ce8-144c77f45af7)

PFA SDK screenshot : 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/7c3b096f-f8ab-4c0d-851c-489e2e96fe12)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

5b4f8004662d00bdb111367fec7d3ea978c23372 

### Platform

raspi

**Comment by rbultman** [comment]
This appears to be implemented.  See this PR:  https://github.com/project-chip/connectedhomeip/pull/27036
