### ISSUE TITLE
[CERT-TEST-FAILURE] - TC-TCTL- 3.3- test failed

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#28294]
### Feature Area

Area:TemperatureControlledCabinet

### Test Case

 TC-TCTL- 3.3

### Reproduction steps

Based on Spec, If TN feature implemented the SetTemperature command should have the TargetTemperatureLevel field in SDK but in current SDK it's not implemented

Expected : SetTemperature command with TargetTemperatureLevel field
Actual : TargetTemperatureLevel field is missing

**PFA Spec Screenshot** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/db77c3ae-1a47-45b8-8b29-b0e3f37fb429)

**PFA execution screenshot** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/6ff2c59f-8b0b-4a29-85b6-ac7cf532c6cf)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

5b4f8004662d00bdb111367fec7d3ea978c23372 

### Platform

raspi

**Comment by rbultman** [comment]
This appears to be implemented. See this PR: https://github.com/project-chip/connectedhomeip/pull/27036
