### ISSUE TITLE
Controller API to manage and trigger ZCL scenes

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#2831]
#### Problem
Need Controller API to

1. Create a scene
2. Delete a scene
3. Enumerate existing scenes
4. Store scenes in persistent storage
5. Trigger a scene, by constructing ZCL command and sending it to the devices 

 #### Proposed Solution
It's possible to do 1, 2, 3, and 4 in the controller application. Need more analysis to determine if there is any benefit in providing this as part of CHIP Controller API.

**Comment by andy31415** [comment]
@woody-apple - implementing scenes seems like significant feature work that is not in the "late" list of acl/ota/im/group. 

This does not look like v1.

**Comment by woody-apple** [comment]
This is mostly complete.
