### ISSUE TITLE
[BUG] LocalizationConfiguration implementation overwrite ActiveLocale value on initialization.

### ISSUE THREAD

**Issue by yonko-gospodinov** [project-chip/connectedhomeip#28357]
### Reproduction steps

I'm developing a Matter bridge and there for the **LocalizationConfiguration::ActiveLocale** attribute is set as external. Current active locale of the system is **en-US** and supported locales are: **it-IT**, **de-DE**, **en-US**, **es-ES**, **fr-FR** and **en-GB**.
1. Start the Matter bridge.
2. Matter stack is always changing system locale to **it-IT**. Expectation is system locale to stay unchanged. 

### Bug prevalence

On every system start.

### GitHub hash of the SDK that was being used

8f66f4215bc0708efc8cc73bda80620e67d8955f (tag: v1.1.0.1)

### Platform

darwin

### Anything else?

During initialization, the **emberAfLocalizationConfigurationClusterServerInitCallback** function in **localization-configuration-server.cpp** is called. This function gets the active locale value and check if it is part of the supported locales. If it is not, set the first supported locale as active locale. This logic is triggered every time, because **ActiveLocale::Get** fail to set the correct size of the locale and **outLocale.data_equal(activeLocale)** always return **false**.

The definition of **ActiveLocale::Get** is:
**EmberAfStatus Get(chip::EndpointId endpoint, chip::MutableCharSpan value); // char_string**
there for calling:
**value.reduce_size(length);**
do not have the expected effect.

Change the definition of **ActiveLocale::Get** to:
**EmberAfStatus Get(chip::EndpointId endpoint, chip::MutableCharSpan & value); // char_string**
is fixing the problem.

**Comment by bzbarsky-apple** [comment]
> The definition of ActiveLocale::Get is:

@yonko-gospodinov thank you for finding that, an I am sorry this took so long to get to: it got the "darwin" label auto-added, and I had not been triaging those issues, so just noticed this...  

This needs to be fixed on the ZAP side.  Created https://github.com/project-chip/zap/pull/1122 to fix that there, then we'll need to update ZAP version.
