### ISSUE TITLE
[Test Failed] PASESession timeout in Linux "Run Tests" job

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#28499]
### Test issue(s)

https://github.com/project-chip/connectedhomeip/actions/runs/5660125929/job/15335171052?pr=27874

This is basically the same as https://github.com/project-chip/connectedhomeip/issues/27476 but in the normal "Run Tests" harness...  

### Platform

other

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures
