### ISSUE TITLE
Update expected DishwasherMode Cluster Attribute List to include FFFA

### ISSUE THREAD

**Issue by abpoth** [project-chip/connectedhomeip#28525]
Your CI is failing here: 

`***** Test Failure: value expect the value 65530 but the list does not contains it.`

I _think_ this is FFFA event list, so either that shouldn't be there or its not switched on for the cluster, its in test plan so maybe the latter!

_Originally posted by @mhazley in https://github.com/project-chip/connectedhomeip/pull/27946#discussion_r1284168660_

**Comment by bzbarsky-apple** [comment]
@abpoth You need separate tests conditioned on  PICS_EVENT_LIST_ENABLED.  It's disabled in the SDK right now.

**Comment by abpoth** [comment]
adjustment made
