### ISSUE TITLE
[Scenes] Fix SceneTableSize

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#28521]
Currently, the attribute SceneTableSize is dictated by `CHIP_CONFIG_MAX_SCENES_PER_ENDPOINT` from CHIPConfig.h and doesn't get modified from the Zap configuration.

We need to allow users to defined the size of the scene table by zap from the scenes-server.cpp

**Comment by bzbarsky-apple** [comment]
If we want this defined via ZAP, why are we doing it via AttributeAccessInterface at all?

**Comment by lpbeliveau-silabs** [comment]
Currently we are only getting the SceneCount and RemainingCapacity through the AttributeAccessInterface, SceneTableSize should not rely on it.

**Comment by bzbarsky-apple** [comment]
Then I am confused.  We're not using CHIP_CONFIG_MAX_SCENES_PER_ENDPOINT for the attribute value... Is this issue then about setting CHIP_CONFIG_MAX_SCENES_PER_ENDPOINT or some equivalent automatically to the largest SceneTableSize set in ZAP across all endpoints?

**Comment by lpbeliveau-silabs** [comment]
Yes, that is the actual problem. CHIP_CONFIG_MAX_SCENES_PER_ENDPOINT should be equivalent to the zap parameter, otherwise someone trying to configure a device with a SceneTableSize > CHIP_CONFIG_MAX_SCENES_PER_ENDPOINT would face unexpected Resource exhausted errors.
