### ISSUE TITLE
Counters on group keys

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#28543]
### Feature description

Currently the counters on group keys are 32 bit. 32 bits is small enough that it is possible for them to rollover and wrap which necessitates a need for a mechanism to generate new keys. That mechanism results in epochKey0, epochKey1, epochKey2 on the key-set. Having epochs means the controllers need to worry about expiring keys and updating them before they wrap around. 

An alternative to consider would be switching to 64b counters instead of 32b ones. Now the keys will take thousands of years to wrap. Changing the counter length effectively removes the need for creating new keys and updating the epochs.

### Platform

all

**Comment by bzbarsky-apple** [comment]
This would be a backwards-incompatible wire format change.

The SDK cannot make that sort of change unilaterally; this needs to be proposed as a spec change, with a revision of the wire format, plan for how migration happens, etc.
