### ISSUE TITLE
Remove Unnecessary PICS Guards

### ISSUE THREAD

**Issue by p0fi** [project-chip/connectedhomeip#28560]
# 📖 Description
The test scripts for CONC Measurement and RVC OP state contain some tests protected by PICS codes for all mandatory attributes. However, those guards are unnecessary and should be removed.

## 🔎 Details
The guards which should be deleted are things like 
- `XXX.S.Afffa`
- `XXX.S.Afffb`
- `XXX.S.Afffc`
- ...

**Comment by mhazley** [comment]
Fixed by #28361
