### ISSUE TITLE
Wrong `FanControl` Cluster Revision

### ISSUE THREAD

**Issue by tobiasgraf** [project-chip/connectedhomeip#28562]
# 📖 Description
The cluster revision attribute is set wrong in the `all-cluster-example-app` and the test script `TC-FAN-1.1`.

## 🔎 Details
The `FanControl` cluster is at rev `4`.

- The `all-cluster-example-app` is wrongly set to clusterRevision `2`. 
- The test script `TC-FAN-1.1` has verification steps which should make sure its value is `3` (and the example output still shows `2`), this should also be updated to `4`.

**Comment by cjandhyala** [comment]
dup to 27320
