### ISSUE TITLE
[CERT-TEST-FAILURE] IsUrgent flag is not getting propagated on TH scripts

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#28567]
### Feature Area

Area:TimeSync

### Test Case

TC-TIMESYNC-2.10, 2.12, 2.13

### Reproduction steps

Python scripts for TC-TIMESYNC 2.10, 2.12, and 2.13 subscribe to events with a path tuple include 'urgent==1'. However, the DUT receives a subscribe request without the urgent flag set.

This causes said tests to fail on DUT's which increase the maxInterval during the subscription negotiation.

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

TH -Fall2023-Beta3

### Platform

python

**Comment by jrhees-cae** [comment]
I suspect this affects other Python TC's as well.

**Comment by raju-apple** [comment]
@cecille can you take a look when you get a chance please
