### ISSUE TITLE
[TE2-v1.2] Scenes Cluster's Explicit, TableSize, FabricScenes features implementation is missing 

### ISSUE THREAD

**Issue by PSONALl** [project-chip/connectedhomeip#28599]
### Reproduction steps / Feature

- Scenes Cluster's Explicit, TableSize, FabricScenes features are mandatory in the specifications
- But it's implementation is missing in the SDK 
 

### Platform

core (please add to version below)

### Platform Version(s)

v1.2

### Type

Manually tested with SDK

**Comment by PSONALl** [comment]
> @PSONALl Is this a duplicate of #28217 ?

Closing this issue as it is a duplicate!!

**Comment by dhrishi** [comment]
@PSONALl Please include the original issue in the results of the test case(s) that failed
