### ISSUE TITLE
Implement OTA Software Update cluster (Server side) 

### ISSUE THREAD

**Issue by BroderickCarlin** [project-chip/connectedhomeip#2862]
#### Problem
The CHIP spec defines an OTA software update cluster but the SDK currently does not implement said cluster's server side logic

 #### Proposed Solution
Implement the CHIP OTA software update cluster's server side logic

**Comment by holbrookt** [comment]
@BroderickCarlin  - what is enough to constitute implementing the server side logic? #6476 implements the generic code for OTA Server logic, is this enough to close this issue?

**Comment by BroderickCarlin** [comment]
@holbrookt - I would believe that #6476 fulfills the original intent of this issue. As pointed out in that PR we must rely on a vendor to implement a majority of their own software update system as it is inherently going to be highly vendor specific. The delegate approach, with some fleshed out boilerplate, should suffice to close this issue once merged.
