### ISSUE TITLE
[BUG] Failure building esp32 all-clusters-app example

### ISSUE THREAD

**Issue by aravindone** [project-chip/connectedhomeip#28635]
### Reproduction steps

im facing error will start the building of the esp32 examples.
steps:
1) activate the esp-idf v5.1 environment.
2) activate the  connectedhomeip environment.
3)move to examples/all-clusters-app/esp32.
4)idfy.py set-target esp32 (problem - stuck ).

[set-target esp32_error.TXT](https://github.com/project-chip/connectedhomeip/files/12314661/set-target.esp32_error.TXT)

does any python dependencies im missing for build ?

please let me know .. 

### Bug prevalence

always

### GitHub hash of the SDK that was being used

7353fd6cab156b2f5cf5ca432f005cf33312a1fe 

### Platform

esp32

### Anything else?

@shubhamdp    please comment.

**Comment by shubhamdp** [comment]
https://github.com/project-chip/connectedhomeip/issues/27653#issuecomment-1635375210

**Comment by bzbarsky-apple** [comment]
@aravindone Please stop pinging me on all esp32 issues.

**Comment by aravindone** [comment]
Ok @bzbarsky-apple

**Comment by aravindone** [comment]
from https://github.com/project-chip/connectedhomeip/issues/27653#issuecomment-1635375210 

is working fine im closing this ticket thanks.

@shubhamdp
