### ISSUE TITLE
Implement BDX synchronous sender role over CRMP

### ISSUE THREAD

**Issue by BroderickCarlin** [project-chip/connectedhomeip#2864]
#### Problem
CHIP defines means for performing a bulk-data transfer (BDX) over the CHIP reliable messaging protocol (CRMP). The BDX synchronous sender role over CRMP logic is not currently implemented. 

 #### Proposed Solution
Implement BDX synchronous sender role over CRMP

**Comment by holbrookt** [comment]
See also changes in https://github.com/project-chip/connectedhomeip/pull/8963
