### ISSUE TITLE
[BUG] CRASH: JNI DETECTED ERROR IN APPLICATION: JNI ERROR - ReleaseStringUTFChars

### ISSUE THREAD

**Issue by mukesh-simform** [project-chip/connectedhomeip#28652]
### Reproduction steps

1. Discover available nodes in the network using `discoverCommissionableNodes`
2. Get Discovered Node using `getDiscoveredDevice`
3. Pair the device with the IP Address using `pairDeviceWithAddress`
4. ESP32 chip will be commissioned and shows proper logs but the application using SDK crashes immediately 

### Bug prevalence

Every time

### GitHub hash of the SDK that was being used

8f66f42

### Platform

android, esp32

### Platform Version(s)

v1.1.0.1

### Anything else?

The app is gettings crashed every time when tries to commission over an IP address using  `pairDeviceWithAddress` method

```
A  java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION: JNI ERROR (app bug): jstring is an invalid global reference: 0x418e (stale reference with serial number 3 v. current 6)

java_vm_ext.cc:594]     in call to ReleaseStringUTFChars
```

**Implementation**

<img width="743" alt="Screenshot 2023-08-11 at 1 52 45 PM" src="https://github.com/project-chip/connectedhomeip/assets/56827526/35ad6958-9c68-4abc-a838-67eedf60bb05">

**ESP32 Logs**

<img width="681" alt="Screenshot 2023-08-11 at 1 54 42 PM" src="https://github.com/project-chip/connectedhomeip/assets/56827526/4a8b6c09-4405-4415-8464-ba32d66dc79b">

**Crash Logs Android**

<img width="1361" alt="Screenshot 2023-08-11 at 1 46 21 PM" src="https://github.com/project-chip/connectedhomeip/assets/56827526/9c0c7ca4-f6e2-493b-add3-e60c893e3c20">

**Comment by yunhanw-google** [comment]
@joonhaengHeo could you help to take a look at this issue? thanks

**Comment by pengxuetian** [comment]
![image](https://github.com/project-chip/connectedhomeip/assets/16287435/7c3eee0b-7a61-425b-b9e9-ef80f2451b7f)
@yunhanw-google Making these changes will fix the bug!

**Comment by joonhaengHeo** [comment]
@pengxuetian 
I understood what the problem was. It would be nice if you could post a fix for this issue.
