### ISSUE TITLE
Implement BDX synchronous receiver role over CRMP

### ISSUE THREAD

**Issue by BroderickCarlin** [project-chip/connectedhomeip#2865]
#### Problem
CHIP defines means for performing a bulk-data transfer (BDX) over the CHIP reliable messaging protocol (CRMP). The BDX synchronous receiver role over CRMP logic is not currently implemented. 

 #### Proposed Solution
Implement BDX synchronous receiver role over CRMP

**Comment by holbrookt** [comment]
#9474 includes BDX receiver code but is not yet functional. So it partially solves this issue.

**Comment by holbrookt** [comment]
This should be considered done as of #9474 and #9740 being merged.

See BDX download code in `examples/ota-requestor-app/ota-requestor-common/BDXDownloader.cpp`
