### ISSUE TITLE
missing and no known rule to make it

### ISSUE THREAD

**Issue by chuckrui** [project-chip/connectedhomeip#28700]
When I build chip-tool according to the website, I found some errors, can you help me solve it?
[https://github.com/nrfconnect/sdk-connectedhomeip/blob/9e6386ca7506b04beccba7ec7054054b48ae4d7e/docs/guides/BUILDING.md#prerequisites](url)

![1692081510031](https://github.com/project-chip/connectedhomeip/assets/76715008/3ddeaa95-7961-4bf5-b4f0-bf31c2dedc6b)
Synchronizing submodules does not have any problems, but why display missing files?
![1692081792431](https://github.com/project-chip/connectedhomeip/assets/76715008/a676f40f-f640-4c43-a806-d51840d93c63)

**Comment by chuckrui** [comment]
run gn_build.sh log
[gn_build.txt](https://github.com/project-chip/connectedhomeip/files/12341938/gn_build.txt)

**Comment by aravindone** [comment]
@chuckrui  use the below command after activateing matter sdk to build chip tool , follow steps from url

`./scripts/examples/gn_build_example.sh examples/chip-tool BUILD_PATH`

[https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/chip_tool_guide.md](url)
