### ISSUE TITLE
chip-tool scan device failed 

### ISSUE THREAD

**Issue by chuckrui** [project-chip/connectedhomeip#28717]
I've been testing chip-tool on a Raspberry PI, and now I've created a new ubuntu20.04 virtual machine on vmware.
Burn coprocesse firmware as RCP and insert it into the USB port of the host.
![image](https://github.com/project-chip/connectedhomeip/assets/76715008/c84a6989-d677-4d08-8ba8-872c0769fdef)

When I tried to debug the device by adding it to the Thread network via chip-tool, the following error was displayed
![1692177872800](https://github.com/project-chip/connectedhomeip/assets/76715008/fe687cf6-930c-444b-9732-89301bbbf5ad)

Attach all my commissioning logs.
[chip-tool.txt](https://github.com/project-chip/connectedhomeip/files/12357824/chip-tool.txt)

**Comment by aravindone** [comment]
@chuckrui the logs you attached tells there is not chip device found while BLE scanning, so the timeout error occurred.

> [1692177136.916013][23701:23703] CHIP:BLE: Scan complete. No matching device found.

**Comment by gokul-bhalodiya-7** [comment]
As per the logs, target CHIP end-device is not scanned by Matter controller while running chip-tool.

$ ./chip-tool pairing ble-thread <node_id> hex:<operational_dataset> <pin_code> <discriminator>

You should try the <discriminator> value 3840 instead of 3841 in above command syntax.

And also you should verify that your matter end-device is advertising on BLE or not.

**Comment by chuckrui** [comment]
@gokul-bhalodiya-7  The initial value of the authentication code is 3840, but I changed this to 3841 in order to distinguish it from the switch example.
![image](https://github.com/project-chip/connectedhomeip/assets/76715008/917b3340-b590-4adf-ae60-c22530d63c3b)

> And also you should verify that your matter end-device is advertising on BLE or not.

I made sure that Advertising was enabled on the device, because after I failed chip-tool commissioning, I scanned the qr code through the apple home app and correctly added it to the home app.

**Comment by chuckrui** [comment]
@aravindone Yeah, you're right. I have been wondering whether there is a problem with the Bluetooth driver in my virtual machine. When I turn on the Bluetooth for scanning, there are only 1 or 2 devices, but many Bluetooth devices will be displayed when I access the network in the Raspberry PI
![1692325275987](https://github.com/project-chip/connectedhomeip/assets/76715008/f9b6374d-ad46-4823-855a-bb7b361c1767)

**Comment by aravindone** [comment]
@chuckrui  are you using virtual Ubuntu? please don't use for commissioning purpose because it will get failed. Direct ubuntu laptop is recommended and good to go.

**Comment by chuckrui** [comment]
@chuckrui yes，I installed Ubuntu through VMware, so I'll try to install a real Ubuntu environment.Thank you~
