### ISSUE TITLE
[BUG] Android Sample app throws UnsatisfiedLinkError on QrCode read

### ISSUE THREAD

**Issue by pgatti86** [project-chip/connectedhomeip#28716]
### Reproduction steps

While reading QrCode for device commissioning method parseQrCode(qrCode: String) of OnboardingPayloadParser throws java.lang.UnsatisfiedLinkError.

Details: 
```
Cannot load library.
java.lang.UnsatisfiedLinkError: dlopen failed: library "libOnboardingPayload.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
at java.lang.Runtime.loadLibrary0(Runtime.java:998)
at java.lang.System.loadLibrary(System.java:1661)
at chip.onboardingpayload.OnboardingPayloadParser.<clinit>(OnboardingPayloadParser.kt:125)
at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.handleScannedQrCode$lambda$9(BarcodeFragment.kt:206)
at com.google.chip.chiptool.setuppayloadscanner.BarcodeFragment.lambda$NRVVa2Glsayk9lgWADmqvsfpNRo(Unknown Source:0)
at com.google.chip.chiptool.setuppayloadscanner.-$$Lambda$BarcodeFragment$NRVVa2Glsayk9lgWADmqvsfpNRo.run(Unknown Source:4)
```

### Bug prevalence

Every time A QrCode is scanned

### GitHub hash of the SDK that was being used

7431a51

### Platform

android

### Platform Version(s)

1.0.0.2

**Comment by yunhanw-google** [comment]
@yufengwangca  please take a look, OnboardingPayload kotlin module is impacting android chip-tool.
@pgatti86 could you described a little bit more details on reproducing step. thanks

**Comment by pgatti86** [comment]
@yunhanw-google once launched the sample app (ChipTool) press "SCAN QR CODE" or "PROVISION CHIP DEVICE WITH DEVICE" button.
MlKit successfully returns a barcode object but any attempt to process the displayValue via OnboardingPayloadParser throws an UnsatisfiedLinkError exception.
To mitigate the problem I'm using the dependency found in the GHSA repository:
https://github.com/google-home/sample-apps-for-matter-android/blob/main/3p-ecosystem/third_party/connectedhomeip/libs/jniLibs/arm64-v8a/libSetupPayloadParser.so

**Comment by yufengwangca** [comment]
it looks libSetupPayloadParser.so was not built and installed together with Android Chiptool

**Comment by yufengwangca** [comment]
OnboardingPayload is completely implemented in kotlin, there is no libOnboardingPayload.so needed.

**Comment by yufengwangca** [comment]
It seems the Android ChipTool is still looking for libSetupPayloadParser.so
