### ISSUE TITLE
otbr docker size is more 1.2gb when created using otbr-posix docker file

### ISSUE THREAD

**Issue by otbr-work** [project-chip/connectedhomeip#28745]
### Build issue(s)

[Build] i am trying to create docker image for otbr using the dockerfile that is provided in otbr-posix repo but when i check the size of docker image after built is successful it is very big ~1.2gb.

Can anyone let me know how connectedhomeip is able to generate a docker image for otbr is of less size, which is available publically in dockerhub

https://hub.docker.com/layers/connectedhomeip/otbr/sve2/images/sha256-15b4105efba0f98134f57662d3d7680ad10380722c60bb6afa636fbb54014916?context=explore

### Platform

raspi

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures
