### ISSUE TITLE
Implement Diagnostic Logging cluster (Server side)

### ISSUE THREAD

**Issue by BroderickCarlin** [project-chip/connectedhomeip#2875]
#### Problem
The CHIP spec defines a Diagnostic Logging cluster for retrieving unstructured diagnostic logs from devices but the SDK currently does not implement said cluster's server side logic

 #### Proposed Solution
Implement Diagnostic Logging cluster (Server side)

**Comment by bzbarsky-apple** [comment]
`src/app/clusters/diagnostic-logs-server/diagnostic-logs-server.cpp` exists.  What remains to be done here, if anything?  @mrjerryjohns @BroderickCarlin @kghost
