### ISSUE TITLE
[Feature] How to get ChipDeviceController node id in Android platform?

### ISSUE THREAD

**Issue by Allen-Guof** [project-chip/connectedhomeip#28768]
### Feature description

We need to get controller node id in Android platform. Please Help.

### Platform

android

**Comment by joonhaengHeo** [comment]
@Allen-Guof 
If you don't set controller NOC, Android controller node ID is `112233`.

https://github.com/project-chip/connectedhomeip/blob/059f67410ad27e3e18820be4f9a2e413b7cfaada/src/controller/java/CHIPDeviceController-JNI.cpp#L106

**Comment by yunhanw-google** [comment]
In case application developer wanna get the nodeId via API call, should we create the API to retrieve it?
