### ISSUE TITLE
Update Basic Cluster to align with CHIP spec

### ISSUE THREAD

**Issue by BroderickCarlin** [project-chip/connectedhomeip#2877]
#### Problem
The currently implemented Basic Cluster is pulled unmodified from the ZCL spec and does not align with the CHIP defined Basic Cluster.

 #### Proposed Solution
Update the Basic Cluster implementation to align with the CHIP Basic Cluster

**Comment by kpschoedel** [comment]
@vivien-apple — I have XML changes for this in #5019

**Comment by bzbarsky-apple** [comment]
Note: #5019 was reverted.

**Comment by kpschoedel** [comment]
I brought this up in #zap earlier — it's associated with two .zap json records that are not significantly different from all the others, and goes away if the `code` is not either 5 or 6. It doesn't appear to affect the generated code (although I may have missed something).

**Comment by franck-apple** [comment]
This is done. Closing.
