### ISSUE TITLE
[BUG] Add "powersource" device type to CHEF smoke co alarm device

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#28782]
### Reproduction steps

https://github.com/project-chip/connectedhomeip/pull/28622 endpoint 1 has a PowerSource cluster but no power source device type.

This should be updated now that zap supports multiple device types per endpoint

### Bug prevalence

always

### GitHub hash of the SDK that was being used

master

### Platform

other

**Comment by ericzijian1994** [comment]
Updated at https://github.com/project-chip/connectedhomeip/pull/28795
