### ISSUE TITLE
`MA-colortemperaturelight` has `requiredCommand`s in xml for Color control cluster that are not required per spec (nor do they make sense)

### ISSUE THREAD

**Issue by reinhrst** [project-chip/connectedhomeip#28799]
The XML makes commands like `MoveToHue` required, even though these are not required per (1.1) spec. Also, the `CurrentHue` field is not required, so it's even unclear what the command is meant to do.

https://github.com/project-chip/connectedhomeip/blob/cbc3865401340d48668c5bd3c61bd5f8b09a41c4/src/app/zap-templates/zcl/data-model/chip/matter-devices.xml#L452

According to spec, only `MoveToColorTempera­ture`, `StopMoveStep`, `MoveColorTempera­ture` and `StepColorTemperature` are required (assuming `CT` feature).

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs could you take a look, please?

**Comment by jmartinez-silabs** [comment]
I'll take a look yes
