### ISSUE TITLE
Add CHIP support for the Power Configuration and Battery cluster to one of the demo projects 

### ISSUE THREAD

**Issue by BroderickCarlin** [project-chip/connectedhomeip#2880]
#### Problem
CHIP defines means for reading information about a device's battery and/or power source but does not currently use this functionality in any of the demo applications.

 #### Proposed Solution
Add CHIP support for the Power Configuration and Battery cluster to one of the demo projects

**Comment by fessehaeve** [comment]
We already have power source cluster. Is anyone working on Power source configuration cluster right now?
Is there something else related to battery?

**Comment by fessehaeve** [comment]
@woody-apple @franck-apple anyone working on this?

**Comment by woody-apple** [comment]
@fessehaeve Nope, unfortunately not! :(

**Comment by fessehaeve** [comment]
@woody-apple apparently I did the power source configuration cluster but forgot about this open issue. There is also a power source cluster in the example apps (all-cluster-apps and lock-app). The only thing missing is hooking up the power source to an actual implementation, eg for battery measurement.

**Comment by yufengwangca** [comment]
It looks we just need to enable those cluster in one of example app zap and implement the relevant callback if needed. Maybe thermostat is a good candidate. 

@fessehaeve  please let me know if you need any help on this.

**Comment by fessehaeve** [comment]
The clusters are enabled in all-clusters-app and lock-app. I was proposing having actual implementation with hardware integration. Not sure if that is really necessary. We could close the issue if everyone is satisfied.

**Comment by woody-apple** [comment]
This looks complete, yes. Thanks!
