### ISSUE TITLE
[1.2] TC-ACE-1.2 Fails if DUT negotiates a higher MaxInterval on subscription

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#28817]
### Reproduction steps

Python test TC-ACE-1.2 will fail on Step 8 if a DUT negotiates a higher MaxInterval  than a few seconds (during subscription).

`***** Test Step 8 : TH2 waits for subscription report for access control entry changed event`

Possible remedies are:
1. Modify the test to extend its wait time in step 8 to match the negotiated MaxInterval value from the subscription
2. Set the `isUrgent` flag in the subscription request such that the AccessControlEntryChanged event arrived based on the minInterval time.

This is related to #28793

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

main

### Platform

python

### Type

Test Improvement

**Comment by cecille** [comment]
For now, I think the solution is to use IsUrgent - we don't have a good way to get back the negotiated time right now. We SHOULD implement that, but the chances of it landing and landing bug-free before friday are low.
