### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-MOD-3.3] - Test Failure 

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#28833]
### Feature Area

Area:ModeSelect

### Test Case

TC-MOD-3.3

### Reproduction steps

**Step1**: Run the docker using `sudo docker run --rm -it -e RUNAS=$(id -u) -v ~/nrfconnect:/var/ncs -v ~/connectedhomeip:/var/chip      -v /dev/bus/usb:/dev/bus/usb --device-cgroup-rule "c 189:* rmw" nordicsemi/nrfconnect-chip`

**Step2**: Build  the all-clusters-app for the OTA transfer using `west build -b nrf52840dk_nrf52840 -- -DCONF_FILE=prj_dfu.conf -DCONFIG_CHIP_LIB_SHELL=y` in `examples/all-cluster-app/nrfconnect` folder

### Bug prevalence

Whenever i do this

### GitHub hash of the SDK that was being used

693b30264d3a91c663218ff04d2a83846ca247c5 

### Platform

nrf, raspi

### Anything else?

All-cluster-app for the nrfconnect is failed in the nrfdocker with 

> [732/827] Building CXX object CMakeFiles/app.dir/var/chip/src/app/clusters/door-lock-server/door-lock-server.cpp.obj
/var/chip/src/app/clusters/door-lock-server/door-lock-server.cpp: In member function 'bool DoorLockServer::HandleRemoteLockOperation(chip::app::CommandHandler*, const chip::app::ConcreteCommandPath&, chip::app::Clusters::DoorLock::LockOperationTypeEnum, RemoteLockOpHandler, const chip::Optional<chip::Span<const unsigned char> >&)':
/var/chip/src/app/clusters/door-lock-server/door-lock-server.cpp:3469:38: warning: 'pinCredIdx.chip::Optional<short unsigned int>::mValue.chip::Optional<short unsigned int>::Value::mData' may be used uninitialized [-Wmaybe-uninitialized]
 3469 |         foundCred[0].credentialIndex = pinCredIdx.Value();
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/var/chip/src/app/clusters/door-lock-server/door-lock-server.cpp:3354:24: note: 'pinCredIdx.chip::Optional<short unsigned int>::mValue.chip::Optional<short unsigned int>::Value::mData' was declared here
 3354 |     Optional<uint16_t> pinCredIdx; // Will get set to a value if the PIN is one we know about.
      |                        ^~~~~~~~~~
[807/827] Linking CXX executable zephyr/zephyr_pre0.elf
FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map /var/chip/examples/all-clusters-app/nrfconnect/build/zephyr/zephyr_pre0.map 
: && /opt/zephyr-sdk-0.15.2/arm-zephyr-eabi/bin/arm-zephyr-eabi-g++  -gdwarf-4 -Wl,--whole-archive /var/chip/examples/all-clusters-app/nrfconnect/build/modules/connectedhomeip/lib/libCHIPShell.a -Wl,--no-whole-archive -Wl,--wrap=malloc -Wl,--wrap=calloc -Wl,--wrap=realloc -Wl,--wrap=free -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r -Wl,--wrap=_free_r zephyr/CMakeFiles/zephyr_pre0.dir/misc/empty_file.c.obj -o zephyr/zephyr_pre0.elf  zephyr/CMakeFiles/offsets.dir/./arch/arm/core/offsets/offsets.c.obj  -fuse-ld=bfd  -Wl,-T  zephyr/linker_zephyr_pre0.cmd  -Wl,-Map=/var/chip/examples/all-clusters-app/nrfconnect/build/zephyr/zephyr_pre0.map  -Wl,--whole-archive  app/libapp.a  zephyr/libzephyr.a  zephyr/arch/common/libarch__common.a  zephyr/arch/arch/arm/core/aarch32/libarch__arm__core__aarch32.a  zephyr/arch/arch/arm/core/aarch32/cortex_m/libarch__arm__core__aarch32__cortex_m.a  zephyr/arch/arch/arm/core/aarch32/mpu/libarch__arm__core__aarch32__mpu.a  zephyr/lib/libc/newlib/liblib__libc__newlib.a  zephyr/lib/posix/liblib__posix.a  zephyr/soc/arm/common/cortex_m/libsoc__arm__common__cortex_m.a  zephyr/soc/arm/nordic_nrf/nrf52/libsoc__arm__nordic_nrf__nrf52.a  zephyr/subsys/random/libsubsys__random.a  zephyr/subsys/bluetooth/common/libsubsys__bluetooth__common.a  zephyr/subsys/bluetooth/host/libsubsys__bluetooth__host.a  zephyr/subsys/dfu/boot/libsubsys__dfu__boot.a  zephyr/subsys/net/libsubsys__net.a  zephyr/subsys/net/l2/openthread/libsubsys__net__ip__l2__openthread.a  zephyr/subsys/net/ip/libsubsys__net__ip.a  zephyr/drivers/clock_control/libdrivers__clock_control.a  zephyr/drivers/console/libdrivers__console.a  zephyr/drivers/entropy/libdrivers__entropy.a  zephyr/drivers/flash/libdrivers__flash.a  zephyr/drivers/gpio/libdrivers__gpio.a  zephyr/drivers/hwinfo/libdrivers__hwinfo.a  zephyr/drivers/ieee802154/libdrivers__ieee802154.a  zephyr/drivers/pinctrl/libdrivers__pinctrl.a  zephyr/drivers/serial/libdrivers__serial.a  zephyr/drivers/timer/libdrivers__timer.a  modules/nrf/lib/dk_buttons_and_leds/lib..__nrf__lib__dk_buttons_and_leds.a  modules/nrf/lib/multithreading_lock/lib..__nrf__lib__multithreading_lock.a  modules/nrf/subsys/bluetooth/controller/lib..__nrf__subsys__bluetooth__controller.a  modules/nrf/subsys/dfu/dfu_multi_image/lib..__nrf__subsys__dfu__dfu_multi_image.a  modules/nrf/subsys/dfu/dfu_target/lib..__nrf__subsys__dfu__dfu_target.a  modules/nrf/subsys/mpsl/init/lib..__nrf__subsys__mpsl__init.a  modules/nrf/subsys/mpsl/fem/lib..__nrf__subsys__mpsl__fem.a  modules/nrf/subsys/nfc/ndef/lib..__nrf__subsys__nfc__ndef.a  modules/nrf/subsys/nfc/lib/lib..__nrf__subsys__nfc__lib.a  modules/nrf/subsys/ieee802154/lib..__nrf__subsys__ieee802154.a  modules/nrf/drivers/mpsl/clock_control/lib..__nrf__drivers__mpsl__clock_control.a  modules/nrf/drivers/mpsl/flash_sync/lib..__nrf__drivers__mpsl__flash_sync.a  modules/nrf/drivers/mpsl/temp_nrf5/lib..__nrf__drivers__mpsl__temp_nrf5.a  modules/nrf/drivers/hw_cc310/lib..__nrf__drivers__hw_cc310.a  modules/mcuboot/boot/bootutil/zephyr/libmcuboot_util.a  modules/openthread/platform/libopenthread_platform.a  modules/hal_nordic/nrf_802154/libnrf-802154-platform.a  modules/nrfxlib/nrf_802154/nrf_802154/driver/libnrf-802154-driver.a  modules/hal_nordic/nrfx/libmodules__hal_nordic__nrfx.a  modules/zcbor/libmodules__zcbor.a  modules/nrfxlib/nrfxlib/nrf_security/src/zephyr/libmbedtls_zephyr.a  -Wl,--no-whole-archive  zephyr/kernel/libkernel.a  -L"/opt/zephyr-sdk-0.15.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/thumb/v7e-m+fp/hard"  -L/var/chip/examples/all-clusters-app/nrfconnect/build/zephyr  -lgcc  -Wl,--start-group  modules/connectedhomeip/lib/libCHIP.a  modules/connectedhomeip/lib/libCHIPShell.a  modules/connectedhomeip/lib/libMatterDeviceInfoProviderExample.a  -Wl,--end-group  zephyr/kernel/libkernel.a  zephyr/arch/common/libisr_tables.a  modules/hal_nordic/nrf_802154/libnrf-802154-platform.a  /var/ncs/nrfxlib/nrf_802154/sl/sl/lib/nRF52840/hard-float/libnrf-802154-sl.a  -Wl,--gc-sections  -Wl,--build-id=none  -Wl,--sort-common=descending  -Wl,--sort-section=alignment  -Wl,-u,_OffsetAbsSyms  -Wl,-u,_ConfigAbsSyms  -nostdlib  -static  -Wl,-X  -Wl,-N  -Wl,--orphan-handling=warn  -lstdc++  -Wl,-no-pie  -lm  -Wl,-lc  -L"/opt/zephyr-sdk-0.15.2/arm-zephyr-eabi/arm-zephyr-eabi"/lib/thumb/v7e-m+fp/hard  -Wl,-lgcc  -lc  -specs=nano.specs  modules/openthread/build/src/cli/libopenthread-cli-mtd.a  modules/openthread/build/src/core/libopenthread-mtd.a  modules/openthread/build/third_party/tcplp/libtcplp-mtd.a  modules/openthread/build/src/core/libopenthread-mtd.a  modules/openthread/build/third_party/tcplp/libtcplp-mtd.a  /var/ncs/nrfxlib/nfc/lib/cortex-m4/hard-float/libnfc_t2t.a  modules/nrfxlib/nrfxlib/nrf_security/src/libmbedtls.a  modules/nrfxlib/nrfxlib/nrf_security/src/libmbedx509.a  modules/nrfxlib/nrfxlib/nrf_security/src/libmbedcrypto.a  /var/ncs/nrfxlib/crypto/nrf_cc310_platform/lib/cortex-m4/hard-float/no-interrupts/libnrf_cc310_platform_0.9.17.a  /var/ncs/nrfxlib/crypto/nrf_oberon/lib/cortex-m4/hard-float/liboberon_mbedtls_3.0.13.a  modules/nrfxlib/nrfxlib/nrf_security/src/libmbedcrypto_base.a  -mcpu=cortex-m4  -mthumb  -mabi=aapcs  -mfpu=fpv4-sp-d16  -mfloat-abi=hard  -lc  /var/ncs/nrfxlib/crypto/nrf_oberon/lib/cortex-m4/hard-float/liboberon_3.0.13.a  /var/ncs/nrfxlib/softdevice_controller/lib/cortex-m4/hard-float/libsoftdevice_controller_peripheral.a  /var/ncs/nrfxlib/mpsl/lib/cortex-m4/hard-float/libmpsl.a && cd /var/chip/examples/all-clusters-app/nrfconnect/build/zephyr && /usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake -E echo
/opt/zephyr-sdk-0.15.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../../../../arm-zephyr-eabi/bin/ld.bfd: zephyr/zephyr_pre0.elf section `rodata' will not fit in region `FLASH'
/opt/zephyr-sdk-0.15.2/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.1.0/../../../../arm-zephyr-eabi/bin/ld.bfd: region `FLASH' overflowed by 35736 bytes
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake --build /var/chip/examples/all-clusters-app/nrfconnect/build

**Reference log:**
[Build_thread.txt](https://github.com/project-chip/connectedhomeip/files/12419037/Build_thread.txt)

**Comment by cjandhyala** [comment]
this seem to be a build issue on the platform. pls follow-up with the platform team and get required help. closing the issue.
