### ISSUE TITLE
[Build] ESP32-C3 build error visual-studio code

### ISSUE THREAD

**Issue by BartJozwicki** [project-chip/connectedhomeip#28839]
### Build issue(s)

I Have followed https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md build guide for macOS. 
1. Checkedout Matter code
2. Synchronised submodules
3.  Installed brew
4.  Installed ZAP
5. Used following commands in terminal with success:
- source scripts/activate.sh
- source scripts/bootstrap.sh
- gn gen out/host
- ninja -C out/host
- ninja -C out/host check
Then I usedVisual Studio Code with pre-installed ESP-IDF and opened folder /conncectedhomeip/examples/lighting-app/esp32
6. I have selected port for my ESP32 and set target to esp32c3 (Board I am using to test the code).
7. I build the code and get the following error:

**CMake Error at third_party/connectedhomeip/config/esp32/components/chip/CMakeLists.txt:308 (message):
  The 'gn' command was not found.  Make sure you have GN installed.Or have
  followed necessary build preparations stated in BUILDING.md.**
 
Can you please advise what to do I am running out of ideas, thanks. 

Picture of the output:
![Screenshot 2023-08-23 at 16 11 03](https://github.com/project-chip/connectedhomeip/assets/108279543/cd9846be-f978-4287-a206-1fd90fcc8591)

### Platform

vscode

### Anything else?

![Screenshot 2023-08-23 at 16 11 03](https://github.com/project-chip/connectedhomeip/assets/108279543/8f27c742-14c5-4b40-a674-c7e836f45ca3)

**Comment by sayondeep** [comment]
@BartJozwicki On the same terminal window..you need to export esp-idf using `source path/to/esp-idf/export.sh` and then you need to activate matter using `source path/to/connectedhomeip/scripts/activate.sh` after that you can run `idf.py build`. Can you please try these steps in the same sequence?

**Comment by sayondeep** [comment]
@BartJozwicki 
Are you referring to esp-idf extension for vscode?
What error do you get on building with vscode? is it same i.e., "The 'gn' command was not found. Make sure you have GN installed."
If Yes, can you please confirm that gn is installed on you system by running `gn --version`.

**Comment by dhrishi** [comment]
@BartJozwicki Can you please provide your inputs. If this seems to solve your issue, please close this.

**Comment by BartJozwicki** [comment]
Issue solved thank for help, I will close it now.
