### ISSUE TITLE
Add CHIP support for the Diagnostic cluster to one of the demo projects

### ISSUE THREAD

**Issue by BroderickCarlin** [project-chip/connectedhomeip#2886]
#### Problem
CHIP defines means for reading diagnostic information from a device but does not currently use this functionality in any of the demo applications.

 #### Proposed Solution
Add CHIP support for the Diagnostic cluster to one of the demo projects

**Comment by yufengwangca** [comment]
This is obsolete, we have enabled general, software, wifi/ethernet/thread diagnostic cluster in all-clusters-app and lighting-app
