### ISSUE TITLE
[Simulated] Is it possible to build and run Simulated device (/placeholder/app1) on Raspberry Pi or any ARM64-based machine?

### ISSUE THREAD

**Issue by taigila** [project-chip/connectedhomeip#28861]
### Build issue(s)

Hi Everyone, i am a newbie to this project, so this might be a newbie question. 

I have been using Ubuntu 22.04 in Virtualbox to learn about Matter. One of the first steps that i did was to run Chip-tool and Chip-app (simulated) and try to connect those on my x86-based Ubuntu.

I wonder if it's possible to build and run simulated device any other devices? Specifically Raspberry Pi 4 or any Linux-based system with ARM64 Processor? Thank you.

### Platform

raspi

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures

**Comment by woody-apple** [comment]
Closing older issues, trying to focus on current build failures
