### ISSUE TITLE
Incorrect handling of operational errors

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#28891]
See https://github.com/project-chip/connectedhomeip/pull/28577#pullrequestreview-1595924642

The immediate issue is the backwards check for "is our error different from the previous one?".  But a bigger problem is a clear lack of tests for the functionality....

**Comment by bzbarsky-apple** [comment]
@cjandhyala

**Comment by hicklin** [comment]
The lack of test is due to the need of an application that can trigger an error state. We are in the process of building such a device application to allow us to test this and other events and states that are not testable at the moment.
