### ISSUE TITLE
Merge ServerCallback used in ESP32 and other example apps

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#2891]
#### Problem
Currently, ESP32 has its own SecureSessionMgrCallback / RendezvousDeviceDelegate implementation, which is a bit different from the one in `example/common/chip-app-server`

#### Proposed Solution
Figure out why the difference exists, and merge the code (after #2889), so ESP32 and other example apps can share the same server implementation.

**Comment by vivien-apple** [comment]
One of the difference that I know of at the moment is the `Echo` feature implemented in the server code of the esp32 demo app. I wish it can be remove by doing something like #3020
