### ISSUE TITLE
[BUG] Problem while updating submodules in connectedhomeip 

### ISSUE THREAD

**Issue by mustafayuce33** [project-chip/connectedhomeip#28916]
### Reproduction steps

I have an existing connectedhomeip project at my laptop. Its version was a bit old so that I wanted to upgrade it. I tried `git submodule update --remote --recursive` command to update its submodule and it gave an error that it says `fatal: Unable to find refs/remotes/origin/V10.3.1-kernel-only revision in submodule path 'third_party/freertos/repo'`

I also tried it with following steps by downloading from scratch but it is still same

1. git clone https://github.com/project-chip/connectedhomeip/
2. git submodule update --init --recursive (this is ok)
3. git submodule update --recursive --remote 

At this step it throws exception as you can see below;

![image](https://github.com/project-chip/connectedhomeip/assets/13608541/3fa29f20-2c63-4f87-888f-40dfc40411bb)

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/commits/master

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
> `git submodule update --remote --recursive`

@mustafayuce33 Drop the `recursive` bit.  That does not do the right thing for some of these submodules.

**Comment by mustafayuce33** [comment]
@bzbarsky-apple  But then it will not update/upgrade the submodules inside of connectedhomeip, I guess

**Comment by bzbarsky-apple** [comment]
It won't update the sub-submodules.  Of which I don't think we have any we actually use.
