### ISSUE TITLE
Is an implementation available for adding and removing dynamic endpoints during runtime?

### ISSUE THREAD

**Issue by MonicaisHer** [project-chip/connectedhomeip#28987]
Hello, 

Within the bridge-app examples, there are [simulations](https://github.com/project-chip/connectedhomeip/blob/v1.1.0.1/examples/bridge-app/linux/main.cpp#L853-L860) for adding and removing dynamic endpoints during runtime. I'm wondering if there is an existing implementation that can handle real dynamic endpoints during runtime, rather than just simulations? 

Thank you!

**Comment by bzbarsky-apple** [comment]
@MonicaisHer The same exact APIs that bridge-app uses can be used for "real" endpoints.
