### ISSUE TITLE
[BUG] Removed YAML files were added back in

### ISSUE THREAD

**Issue by plauric** [project-chip/connectedhomeip#28997]
### Reproduction steps

This PR removed some YAML files that are superseded by Python test scripts:
https://github.com/project-chip/connectedhomeip/pull/28583

This PR added back the deleted files:
https://github.com/project-chip/connectedhomeip/pull/28829

### Bug prevalence

100%

### GitHub hash of the SDK that was being used

b3c0ac1

### Platform

core

**Comment by plauric** [comment]
@manjunath-grl Please help with this.

**Comment by manjunath-grl** [comment]
@plauric Removed those tests in PR [28985](https://github.com/project-chip/connectedhomeip/pull/28985) please verify and close the ticket.

**Comment by plauric** [comment]
@manjunath-grl Please also remove Test_TC_RVCOPSTATE_2_1.yaml
Test_TC_RVCOPSTATE_2_3.yaml

**Comment by manjunath-grl** [comment]
@plauric Above mentioned YAML'S are not there in certification folder. Please verify it once.
https://github.com/manjunath-grl/connectedhomeip/tree/master/src/app/tests/suites/certification
