### ISSUE TITLE
[ALOGIN_12_1] constraint error for SetupPIN field of GetSetupPINResponse command.

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#28992]
### Reproduction steps

Summary: 
According to the specification, the minimum characters of the `SetupPIN` field of the `GetSetupPINResponse` command should be 11, but when executed, the `SetupPIN` value has a length of 10 characters and causing test failure `Test Failure : Constraints check failed`

Reproduction step:
Terminal 1: 
Launch `./chip-tv-app `

Terminal 2:
Step 1: Pair the DUT
Step 2: Run test ALOGIN_12_1 with the minLenght: 11 constraint check for step 2.
`./scripts/tests/yaml/chiptool.py tests Test_TC_ALOGIN_12_1`

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:ALOGIN_12_1_SetupPIN_Failure 

Spec screenshot:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/59be1d97-969a-4516-accf-363333adf4b2)

### Bug prevalence

Everytime when executed

### GitHub hash of the SDK that was being used

3f7d03c9e97f82908c0cc6d6f56877c6b5d07891

### Platform

other

### Anything else?

Screenshot:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/5e22446f-8d51-4db8-9cce-2ab89de79b27)

Execution logs:
[ALOGIN_12_1_Failure.zip](https://github.com/project-chip/connectedhomeip/files/12487409/ALOGIN_12_1_Failure.zip)

**Comment by cjandhyala** [comment]
closing per comments from Rajashree
