### ISSUE TITLE
Generate Unique Commissioning QR Code for Multiple ESP Matter Devic

### ISSUE THREAD

**Issue by anuarrozman** [project-chip/connectedhomeip#29045]
### Reproduction steps

**_Unable to commission using new generated manufacturing binary_**
I currently have multiple ESP32 for testing. I want to have different setup passcode. Im following [Manufacturing Partition Generator Utility](https://github.com/espressif/esp-matter/blob/fd842d0/tools/mfg_tool/README.md#manufacturing-partition-generator-utility). I can't manage to successfully commission the device. How can I change it?

**_Command used:_**
./mfg_tool.py -v 0xFFF1 -p 0x8000 --passcode 20202023 --discriminator 3000
esptool.py -p /dev/tty.usbserial-0001 erase_flash
idf.py -p /dev/tty.usbserial-0001 build erase-flash flash
esptool.py -p /dev/tty.usbserial-0001 write_flash 0x10000 ${HOME}/esp/esp-matter/tools/mfg_tool/out/fff1_8000/44293a61-1948-4a9e-a7ca-d9f3de2e8510/44293a61-1948-4a9e-a7ca-d9f3de2e8510-partition.bin

### Bug prevalence

Whenever I flash new generated partition bin file. 

### Platform

esp32

### Platform Version(s)

ESP32

### Anything else?

In the current setup, we employ identical QR codes for all matters or items under consideration. Is there a way to generate unique QR codes for each individual device or item within our system? Additionally, we are looking for guidance on the process of modifying the product and vendor IDs associated with these devices. Any insights or recommendations to resolve these matters would be greatly appreciated.

**Comment by dhrishi** [comment]
As you are using esp-matter and have already raised an issue there, I will close this one. You can track the issue there

**Comment by anuarrozman** [comment]
Thank you!
