### ISSUE TITLE
[Feature] [DCL REST API] Query the PAA certificate with only subjectKeyId

### ISSUE THREAD

**Issue by wqx6** [project-chip/connectedhomeip#29083]
### Feature description

Now we can query a certain PAA certificate with DCL REST APIs if we have both `subject` and `subjectKeyId` or only `subject` of that PAA certificate.
```
curl -X 'GET' 'https://on.dcl.csa-iot.org/dcl/pki/certificates/{subject}/{subjectKeyId}'

curl -X 'GET' 'https://on.dcl.csa-iot.org/dcl/pki/certificates/{subject}'
```

Could we have a DCL REST API that can be used to query PAA certificate with only `subjectKeyId`? Like this:

```
curl -X 'GET' 'https://on.dcl.csa-iot.org/dcl/pki/certificates?subjectKeyId={subjectKeyId}'
```

### Platform

other

**Comment by bzbarsky-apple** [comment]
This does not seem like an SDK issue...  Please file this at https://github.com/zigbee-alliance/distributed-compliance-ledger/issues
