### ISSUE TITLE
[YAML]  EqualityCommands cluster command UnsignedNumberEquals fails for NULL value comparison.

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#29086]
### Reproduction steps

Summary:
According to the test plan, step 2 of the TCCM 3.2 test checks whether the `StartUpMode` attribute has the value integer or null, and if startup_mode_dut is null, proceeds to step 3. When executed in YAML got the value of StartUpMode as `None` using the EqualityCommands cluster command UnsignedNumberEquals, we tried to compare the value as `null` instead of `true` got `false` as the response.

Reproduction steps:
Terminal 1:
Launch `./chip-all-clusters-app`

Terminal 2:
Step 1: Pair the DUT
`./out/chip-tool/chip-tool pairing code 0x12344321 MT:-24J0AFN00KA0648G00`
Step 2: Run test TCCM_3_2
`./scripts/tests/yaml/chiptool.py tests Test_TC_TCCM_3_2`

Effected tests:
TC-TCCM-3.2
TC-TCCM-3.3
TC-RVCCLEANM-3.3
TC-RVCRUNM-3.3

Diff link: https://github.com/project-chip/connectedhomeip/compare/master...manjunath-grl:UnsignedNumberEquals_Fails_for_NULL_Value_Comparsion

### Bug prevalence

Everytime when executed

### GitHub hash of the SDK that was being used

6b708ab29de982d9fa0363d6ce8a2b9a9840b31a

### Platform

other

### Anything else?

Testplan screenshot:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/d1825084-174c-466e-9f9f-45956a8fadf8)

YAML screenshot:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/cb70856f-c335-4d54-bc65-806915a0f5ed)

Execution logs & screenshot:
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/c655fd11-1a02-49e3-a146-b6cb6e478ded)
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/b568739a-d76c-477a-a7fc-3ad74e90d056)
[TCCM32_Execution_logs.zip](https://github.com/project-chip/connectedhomeip/files/12536421/TCCM32_Execution_logs.zip)

**Comment by bzbarsky-apple** [comment]
The schema for UnsignedNumberEquals is:
```
    <command source="client" code="2" name="UnsignedNumberEquals" response="EqualityResponse">
      <arg name="Value1" type="int64u"/>
      <arg name="Value2" type="int64u"/>
    </command>
```
so `null` would not be a valid value for its arguments.  I am pretty surprised that this did not just throw an error; feels like it should have....

**Comment by manjunath-grl** [comment]
> The schema for UnsignedNumberEquals is:
> 
> ```
>     <command source="client" code="2" name="UnsignedNumberEquals" response="EqualityResponse">
>       <arg name="Value1" type="int64u"/>
>       <arg name="Value2" type="int64u"/>
>     </command>
> ```
> 
> so `null` would not be a valid value for its arguments. I am pretty surprised that this did not just throw an error; feels like it should have....

In YAML I am not expected any response value that's y its not failing. If I expect true it fails.
![image](https://github.com/project-chip/connectedhomeip/assets/102359958/4e6c3c35-faf6-4e5f-b6f9-207870416739)

**Comment by vivien-apple** [comment]
I am not sure of why we do check for `None` here. I can see that this is me that have added the change but I don't remember why on top of my head... I made https://github.com/project-chip/connectedhomeip/pull/29107 to revert this particular change.
