### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-DGETH-2.1] -Test Failed

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#29090]
### Feature Area

Other

### Test Case

TC-DGETH-2.1

### Reproduction steps
**As per Spec and Test-plan Expectation after Reboot the DUT  - value of PacketRxCount is

Expected value : 0
Actual value : 97**

Execute the below mentioned command to put DUT into a commissionable state,
 `./chip-all-clusters-app --KVS ./mytest.txt`
Once DUT reach the commissionable state, sent below mentioned command on TH.
` ./chip-tool pairing onnetwork 1 20202021`
After a successfully paired sent mentioned command from TH

Verifying the Step 4 - TH reads a PacketRxCount attribute value from DUT. 
`./chip-tool ethernetnetworkdiagnostics read packet-rx-count 1 0`
Verify the value of PacketRxCount is in range uint64 on TH(chip-tool) log

> [1694003579.650435][2150:2152] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0037 Attribute 0x0000_0002 DataVersion: 1680662781
> [1694003579.650494][2150:2152] CHIP:TOO:   PacketRxCount: 285
> [1694003579.650641][2150:2152] CHIP:EM: <<< [E:26108i S:34513 M:121743241 (Ack:79363268)] (S) Msg TX to 

After reading PacketRxCount attribute reboot the DUT, without commission follow the next steps

TH reads a PacketRxCount attribute value from DUT. 

`./chip-tool ethernetnetworkdiagnostics read packet-rx-count 1 0`
Verify the value of PacketRxCountthe will be reset to 0 on TH(chip-tool) log.

> [1694003631.068050][2155:2157] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0037 Attribute 0x0000_0002 DataVersion: 755783764
> [1694003631.068117][2155:2157] CHIP:TOO:   PacketRxCount: 97
> [1694003631.068289][2155:2157] CHIP:EM: <<< [E:24732i S:56335 M:145435492 (Ack:53376253)] (S) Msg TX to 

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

5ccb774e7e5fe7ead3ff85bec1cda31a459c9c37

### Platform

raspi

### Anything else?

**As per Spec :**

> PacketRxCount Attribute
> The PacketRxCount attribute SHALL indicate the number of packets that have been received on the ethernet network interface. The PacketRxCount attribute SHALL be reset to 0 upon a reboot of the Node.

**and Test-plan expecting :**

> The data type must match the value listed in the specification(s) and the value indicates the number of packets received on 
> ethernet network interface. Upon a node reboot, the value will be reset to 0. The attribute should not be subscribed.

As per Spec and Test-plan Expectation after Rebooting the DUT, Reboot PacketRxCount Attribute attribute value should be set to 0

**Execution Logs :**
[TC-DGETH-2.1.txt](https://github.com/project-chip/connectedhomeip/files/12537329/TC-DGETH-2.1.txt)
[TC-DGETH-2.1 TH.txt](https://github.com/project-chip/connectedhomeip/files/12537331/TC-DGETH-2.1.TH.txt)

**Spec Reference :** https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/DiagnosticsEthernet.adoc#packetrxcount-attribute

**Test-plan Reference :**  https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/ethernet_diagnostics.adoc#tc-dgeth-2-1-attributes-dut_server

**Comment by bzbarsky-apple** [comment]
> Expected value : 0

That's not what the spec says.  The spec says the reboot should reset the count.  But the count you _read_ after that will never be 0 because:

1. You had to do CASE, which means some packets were received.
2. You had to send the read request, which means some packets were received.
3. There is general traffic on the network, which means some packets might be received.

If the test plan says 0 is expected, the test plan is completely broken and needs to be fixed @cjandhyala @Rajashreekalmane
