### ISSUE TITLE
esp32 platform commissioning failed with Apple Home by using BLE  [Platform] 

### ISSUE THREAD

**Issue by zhangzhiliang1xm** [project-chip/connectedhomeip#29101]
### Reproduction steps

We found some BLE commissioning issue using iOS16.5 or later.

1. We found that when commissioning  device to Apple Home through BLE, the commissioning will failed. The iphone os is iOS16.6. The platform is esp32c3. The error log is Apple_Commissioning_failed.txt.
2. But when we use chip-tool to commissioning, the device can be commission successfully
3. We then tried using IP based commissioning instead of Bluetooth and we found that the device could be successfully added to Apple Home.
4. Then we commissioning the device through iOS CHIPTool, and the same error will occur. The error log is CHIPTOOL_Commission_failed
[Apple_Home_Commissioning_failed.txt](https://github.com/project-chip/connectedhomeip/files/12546170/Apple_Home_Commissioning_failed.txt)
[CHIPTOOL_Commission_failed.txt](https://github.com/project-chip/connectedhomeip/files/12546172/CHIPTOOL_Commission_failed.txt)
.txt.

### Platform

esp32

### Type

Platform validated

**Comment by bzbarsky-apple** [comment]
@zhangzhiliang1xm Is this the same as the issue https://github.com/project-chip/connectedhomeip/pull/28923 is fixing?

**Comment by zhangzhiliang1xm** [comment]
@bzbarsky-apple Yes! When I modified esp_ble_gatts_send_indicate usage in the Bluedroid implementation,it works fine.

**Comment by zhangzhiliang1xm** [comment]
The issue is same as https://github.com/project-chip/connectedhomeip/pull/28923 i
