### ISSUE TITLE
mbedTLS NewCertificateSigningRequest fills wrong CSR length

### ISSUE THREAD

**Issue by nileshvora-sls** [project-chip/connectedhomeip#2910]
**Problem**
I was looking into creating csr for OpCSR for my ESP32 platform. However I was getting CSR length 0 when I call **P256Keypair::NewCertificateSigningRequest**. Then I looked into definition of it, it has written something like below.
```
    result = mbedtls_x509write_csr_pem(&csr, out_csr, length, CryptoRNG, nullptr);
    VerifyOrExit(result >= 0, error = CHIP_ERROR_INTERNAL);
    csr_length = static_cast<unsigned int>(result);
```

**Proposed Solution**
According to mbedtls API description **mbedtls_x509write_csr_pem** API return error code, not length. For length, we need to write something like below.
```
    result = mbedtls_x509write_csr_pem(&csr, out_csr, length, CryptoRNG, nullptr);
    VerifyOrExit(result >= 0, error = CHIP_ERROR_INTERNAL);
    csr_length = strlen((char *)out_csr);
```

**Comment by nileshvora-sls** [comment]
CC @pan-apple @bzbarsky-apple

**Comment by pan-apple** [comment]
Thanks @nileshvora-sls , you are right about the return code. I'll push a fix for it.
The code was originally written to use `mbedtls_x509write_csr()` API, which returns the length. But in some iteration of the PR it got changed to PEM format.
