### ISSUE TITLE
[Test_TC_S_2_4] Scenes handling of level control seems to be broken

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#29117]
### Test issue(s)

Running the Test_TC_S_2_4 cert test fails: it expects CurrentLevel after a scene recall to be 100, but it's 200.

Test is being disabled for now; when this is fixed it should be re-enabled.

### Platform

all

**Comment by lpbeliveau-silabs** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/pull/29598
