### ISSUE TITLE
[1.3] How to pairing device KNX?

### ISSUE THREAD

**Issue by tunm1228** [project-chip/connectedhomeip#29122]
### Reproduction steps

I've been testing chip-tool on a Raspberry PI. The matter environment has been installed but do not know how to pair the device address knx

### Bug prevalence

Pairing device

### GitHub hash of the SDK that was being used

matter

### Platform

raspi

### Type

Test Improvement

**Comment by mcreteau** [comment]
Hi

Matter / connectedhomeip project do not provide any specific implementation for KNX protocol. If you are using a KNX solution with a KNX Gateway that include Matter connectivity, maybe you should ask this question to this particular vendor.
