### ISSUE TITLE
[Feature] Decrease flash requirements for a Matter 1.2 SIT ICD

### ISSUE THREAD

**Issue by doru91** [project-chip/connectedhomeip#29131]
### Feature description

![icd](https://github.com/project-chip/connectedhomeip/assets/9597450/dae5091b-085e-4644-a2d1-d23c942fcb04)

Compilation with chip_enable_icd_server=1 + ICDM Cluster Enabled leads to a flash increase of ~5K on NXP Platforms.

Part of this can be optimized by:

- guarding the code from ICDMonitoringTable against a LIT specific define;

- disabling LIT specific attributes/commands from ICDM Cluster.

### Platform

all

### Platform Version(s)

Matter 1.2

**Comment by bzbarsky-apple** [comment]
For a SIT ICD, why is IcdMonitoringTable involved at all?  That seems broken.  Similar for a bunch of the other things in there...
