### ISSUE TITLE
High CPU usage of bridge app

### ISSUE THREAD

**Issue by mustafayuce33** [project-chip/connectedhomeip#29156]
### Reproduction steps

I use dynamic bridge app as base for my project and it runs on a Raspberry PI. It consumes all CPU resources on the system. Is there anything that we can avoid high CPU usage of dynamic bridge app? 

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/tree/1084dd53d50b54e52cc0d91a0f39f84dc68b7039

### Platform

raspi

**Comment by bzbarsky-apple** [comment]
> Is there anything that we can avoid high CPU usage of dynamic bridge app?

Yes, you can profile it to see what's taking up so much time.  Right now, as filed, this issue is not fixable; for all we know there's a busy-loop somewhere in your application that is causing all the CPU use.

**Comment by RDMChristoph** [comment]
Hello!!

We have the same problem regarding high CPU Usage of Matter Bridge App!! @mustafayuce33 : Do you have any additional Infomation how you solved this problem!?

BR Christoph
