### ISSUE TITLE
Matter client developer profile expired,can't reinstall 

### ISSUE THREAD

**Issue by zzqzhp** [project-chip/connectedhomeip#29178]
### Reproduction steps

Matter client developer profile expired,when i reinstall it to my iphone, it alert install failed

### Bug prevalence

when it expired

### GitHub hash of the SDK that was being used

the latest

### Platform

darwin, other

### Anything else?

https://down.dingtalk.com/ddmedia/iwEcAqNwbmcDAQTRAdEF0QLHBrDvAzcv2ce4YgTzZWPyJV8AB9IA1K7tCAAJomltCgAL0gAByB0.png_720x720q90.jpg?bizType=IM&auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%2213938413%3A778089402%22%2C%22msgId%22%3A%2216848321325755%22%7D&open_id=13938413

**Comment by zzqzhp** [comment]
https://down.dingtalk.com/ddmedia/iwEcAqNwbmcDAQTRAdEF0QLHBrDvAzcv2ce4YgTzZWPyJV8AB9IA1K7tCAAJomltCgAL0gAByB0.png_720x720q90.jpg?bizType=IM&auth_bizType=IM&auth_bizEntity=%7B%22cid%22%3A%2213938413%3A778089402%22%2C%22msgId%22%3A%2216848321325755%22%7D&open_id=13938413

**Comment by zzqzhp** [comment]
Description file installation failed
The profile "Bluetooth Central MatterClient Developer Mode" is no longer valid.

**Comment by bzbarsky-apple** [comment]
@zzqzhp Known issue, being worked on.

**Comment by mukesh-simform** [comment]
Facing the same in MacOS as well, while installing profile. "Bluetooth Central Matter Client Developer Mode"

<img width="258" alt="Screenshot 2023-09-12 at 2 48 52 PM" src="https://github.com/project-chip/connectedhomeip/assets/56827526/3ea1442d-984c-45d7-99dc-11098b1048ec">

**Comment by bzbarsky-apple** [comment]
Please stop adding "me too" comments.  The profile is expired.  A new profile with a new expiration date needs to be created and published.  I will update here once I am told that has happened.

**Comment by bzbarsky-apple** [comment]
Profile at https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig has been updated.

**Comment by bzbarsky-apple** [comment]
@zzqzhp Thank you for noticing this so quickly and reporting!  Hopefully this won't happen again...

**Comment by zzqzhp** [comment]
![IMG_0181](https://github.com/project-chip/connectedhomeip/assets/18587026/7e4ee107-ed28-4352-8aef-0278b379898b)
![IMG_0180](https://github.com/project-chip/connectedhomeip/assets/18587026/06e8b2c2-9637-4d83-a9b1-cf6b52823f65)
![IMG_98F57F4186C6-1](https://github.com/project-chip/connectedhomeip/assets/18587026/2098d104-91d9-414e-8983-9f7ef0a1546e)

The new profile still installation failed

**Comment by zzqzhp** [comment]
![one](https://github.com/project-chip/connectedhomeip/assets/18587026/1101a548-d688-4a7a-8950-dd4f665e1459)
![two](https://github.com/project-chip/connectedhomeip/assets/18587026/6f0999b0-0e36-4298-8710-421961abc8e4)

@bzbarsky-apple  The new profile still installation failed

**Comment by bzbarsky-apple** [comment]
@zzqzhp I just tested again, on both MacOS and iOS, and the new profile file works for both...  Please make sure that you're testing the new profile file, freshly downloaded from the link above....

**Comment by zzqzhp** [comment]
@bzbarsky-apple ,thanks,the new profile file works
