### ISSUE TITLE
[Feature] config-data.yaml uses different formats for cluster names

### ISSUE THREAD

**Issue by rochaferraz** [project-chip/connectedhomeip#29186]
### Feature description

`connectedhome/src/app/common/templates/config-data.yaml `has a few top-level tags.

The format of cluster names used by `CommandHandlerInterfaceOnlyClusters`, `DefineBitmaps`, `WeakEnums` seems to be the cluster name with no spaces, converted to CamelCase.

The format used by `ClustersWithInitFunctions`, `ClustersWithAttributeChangedFunctions`, `ClustersWithShutdownFunctions`, and `ClustersWithPreAttributeChangeFunctions` is the cluster name with spaces and no case conversion: as defined in the cluster XML file.

Current status is quite confusing, and formats should converge

Originally filed as https://github.com/project-chip/zap/issues/1134 @bzbarsky-apple 

### Platform

all

**Comment by bzbarsky-apple** [comment]
DefineBitmaps and WeakEnums are not cluster names.

Looks like I was somewhat wrong in the ZAP issue; ClustersWith*Functions _is_ handled on the ZAP side.  But ClustersWithAttributeChangedFunctions is handled on the Matter side, and we can easily change it to match the others.
