### ISSUE TITLE
[ICD] Implement ICD Counter to be compliant with the Check-In counter requirements

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#29184]
#### Description
ICD Counter is currently juste stored in RAM as part of the ICD Management server implementation. Counter needs to be persisted and follow the requirements of the Check-In Counter.

**Comment by bzbarsky-apple** [comment]
Please note https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7375
