### ISSUE TITLE
[Build] Can not build SDK Source in Android Studio

### ISSUE THREAD

**Issue by vecoder** [project-chip/connectedhomeip#29196]
### Build issue(s)

Hi I'm new to the CHIPTool project and Matter and I'm trying to build it for Android. 

I  followed the build guedes to download (**master**) and managed to build the CHIPTool for Android from the console. I can get the APK and install it. When I copy the generated **jar** files and **so** file to the _app/libs_ folder of the Android project,  the project can be open and built from the Android Studio. 
The problem is when I try to build the sources by setting the **matterSdkSourceBuild=true** in the gradle.properties. 
There are plenty of issues:

-  Using incompatible  androidx.appcompat and androidx.annotation version
- Using _javax.annotation. Nullable_ in the generated source files instead of androidx.annotation
- Paths in the **_chip-library:build.gradle_** are wrong and incomplete
    - SourceSets contains paths ` ../../../controller/java/src`, although it should be:   `../../../../src/controller/java/src`
    - SourcerSets has .`./app/src/main/java/com/google/chip/chiptool`. Why we need to reference app source code in the library?
- Missing setput.py in the pigweed: pw_tokenizer/py, pw_log/py and pw_log_rpc/py
- Missing src/crypto/CryptoBuildConfing.h
- ...

I fixed the first three problems and somehow overcome the fourth one (although not sure if this is the rigth way), but no solution for the fifth issue. 

Has anyone faced these problems and what is the solution?
Is there any other way to avoid these issues when building the SDK ?

### Platform

android

**Comment by pachuho** [comment]
Hello vecoder,
I don't know if it helps but I'm going to share a little bit of my build experience.

In my experience, building with ChipTool Script was easier and easier than building with Android Studio.

Try building it the way I tell you.

1. Please refer to Building Page (https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md) and download the submodule.

2. Build using Building Android Page (https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/android_building.md), but follow the Building Android CHIPTool from scripts method.

Other than that, you can follow the errors you find while building, little by little. In my case, I remember updating some submodules and python etc.

I hope it helped you.

**Comment by pachuho** [comment]
and I built it with mac.

**Comment by tejada** [comment]
@woody-apple why has this ticket been closed without resolution? I've tried to build the Android project too and followed the building page without success.

There are wrong annotations in the code, source paths incorrectly set since it got move from /src/ to /examples/ and missing files. Can this please be re-opened and taken care of? Thanks
