### ISSUE TITLE
[Android]Add support for AnnouceOTAProvider Command via OTARequester cluster

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#29298]
Two options:
1. Manually Implement AnnouceOTAProvider command using Generic IM Command API.
2. Codegen all commands using jinja codegen? Size consideration? Maybe it worths pursuing this way, the benefits lies at the later certification test for android matter controller

**Comment by joonhaengHeo** [comment]
@yunhanw-google 
1. I think this implementation should be in Android ChipTool.
2. Cluster class is already created in ChipClusters.java.
https://github.com/project-chip/connectedhomeip/blob/c1ca759a30ca8de8f1553f060b48fffd268f5c03/src/controller/java/zap-generated/chip/devicecontroller/ChipClusters.java#L4475
https://github.com/project-chip/connectedhomeip/blob/c1ca759a30ca8de8f1553f060b48fffd268f5c03/src/controller/java/zap-generated/chip/devicecontroller/ChipClusters.java#L4675
