### ISSUE TITLE
Not to be advertising for ICD and ICD discovery key over mDNS.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#29353]
Per discussion with @turon @jepenven-silabs @jtung-apple @mkardous-silabs @Thivya Ashok Kumar, we would like to check whether the device support ICD or not via feature map from ICDManagement cluster, we don't need to check ICD from advertisement and discovery key over mDNS

**Comment by yunhanw-google** [comment]
recreated it in spec repo, https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7556

**Comment by mkardous-silabs** [comment]
@yunhanw-google  Since we are not doing the discovery key. We are going to need to add a bit in the feature map to inform controllers when the ICD is a LIT device vs. SIT. otherwise we have no means to actually identify a LIT devices.

**Comment by yunhanw-google** [comment]
@mkardous-silabs please prioritize this in spec side and the correponding server implementation in your team. thanks
