### ISSUE TITLE
[TC-TCTL-3.2] Step 7. SetTemperatureCommand with an invalid value but outcome is unexpected

### ISSUE THREAD

**Issue by mideayanghui** [project-chip/connectedhomeip#29369]
### Feature Area

Area:Refrigerators

### Test Case

TC-TCTL-3.2

### Reproduction steps

Expected: Step 7, TH sends command SetTemperatureCommand with an invalid value.
Verify DUT responds Status CONSTRAINT_ERROR(0x87)

Actually, DUT responds Status 0x00.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

 5ccb774e7e5fe7ead3ff85bec1cda31a459c9c37

### Platform

core

### Anything else?

[[TC-TCTL-3.2]_2CHIPTool_log.log](https://github.com/project-chip/connectedhomeip/files/12683103/TC-TCTL-3.2._2CHIPTool_log.log)

**Comment by jadhavrohit924** [comment]
@mideayanghui Which features did you enabled? Please read feature map attribute of the cluster.

**Comment by mideayanghui** [comment]
The feature map of tempearture control cluster is 5
