### ISSUE TITLE
[Tooling] Python -repl activation failure

### ISSUE THREAD

**Issue by aravindone** [project-chip/connectedhomeip#29374]
### Reproduction steps / Feature

Hi , i have cloned the latest master branch 

1)activated the matter sdk -success
2)created python env -success
3)runned chip-repl -faced error ,

can you give the suggestion to solve it

### Platform

python

### Platform Version(s)

master branch

### Type

Manually tested with SDK

### Anything else?

[python-repl_error.TXT](https://github.com/project-chip/connectedhomeip/files/12684969/python-repl_error.TXT)

**Comment by tehampson** [comment]
I'll take a look next week. I am OOO until then

**Comment by aravindone** [comment]
Hi @tehampson thanks for your reply, in the mean time can I have some backup plan that I can use ?

**Comment by tehampson** [comment]
Today on my linux machine I sync'd to tip of tree and did the following without running into any issue:
* `scripts/bootstrap.sh`
* `scripts/activate.sh`
* `scripts/run_in_build_env.sh './scripts/build_python.sh --install_wheel build-env -d true' && source ./scripts/activate.sh`
* `chip-repl`

I was able to drop into interactive python repl shell without any issues. @aravindone is that what you are doing? If not can you try that out.

**Comment by tehampson** [comment]
Sorry scratch that... I just realized I didn't sync properly and still on an old branch. Give me a few mins to report back after sync it done properly

**Comment by tehampson** [comment]
Alright I am able to reproduce the issue. Looking into it now. I'll report back later today with findings

**Comment by aravindone** [comment]
@tehampson Thank you.
