### ISSUE TITLE
[ICD] Identify ICD Device during auto-commissioning flow

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#29382]
Read Descriptor Cluster and Check if ICDManagementCluster exists and further check if ICD feature is there or not from global feature map.

**Comment by yunhanw-google** [comment]
@erjiaqing We also need to Read attribute  "current active mode" to allow dynamic switching of state based upon 
https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7556#issuecomment-1734048250

**Comment by mkardous-silabs** [comment]
@yunhanw-google @erjiaqing  I do not think the `current active mode` is necessary during the commissioning process. A Controller should register to the ICD no matter.

The `current active mode` once we have decided of its final form will only be used to determine if the controller should or should not buffer commands to the device.
