### ISSUE TITLE
[BUG] [Darwin] Failed to Open Commissioning Window 

### ISSUE THREAD

**Issue by qawitherev** [project-chip/connectedhomeip#29425]
### Reproduction steps

1. 'Device1' is commissioned to 'controller1'.
2. Now I want to 'controller2' to commission 'device1' using open commissioning window command.
3. Invoke open commission window command by the following steps.
4. Get discriminator (0 - 4096) from user (not sure if this from user or is automatically generated).
5. Generate random setup passcode by using `MTRSetupPayload.generateRandomSetupPasscode()`.
6. Use the `MTRBaseDevice.openCommissioningWindow()` passing in the **generated random passcode**, the **discriminator**, **timeout duration**, **callback queue** and **completion handler**. 
7. Inside the completion handler, can access the `MTRSetupPayload`. 
8. However the following error occurred.

[Device log]
![image](https://github.com/project-chip/connectedhomeip/assets/59358911/d0bd36dd-1870-40de-a6bb-c0b734cf35fe)

[App log]
![image](https://github.com/project-chip/connectedhomeip/assets/59358911/178c1ad3-fbac-4b29-84f3-9df4cb9a6158)

### Bug prevalence

Whenever i try to do this. 

### GitHub hash of the SDK that was being used

- 

### Platform

darwin

### Anything else?

The goal is to open commissioning window using ECM. By the end of this process, device will now inside two fabrics and can be controlled by controller of fabric 0x1 and 0x2. 

[ADDITIONAL QUESTIONS FOR CLARIFICATION]
1. Inside the `MTRBaseDevice.openCommissioningWindow()` completion handler, there's MTRSetupPayload that we can use to commission the device. My question is, which one is the new setup passcode that we want show to user. Is it the result from `MTRSetupPayload.generateRandomSetupPasscode()` or any other `MTRSetupPayload` that isn't mentioned here?

PS: the opening window implementation is from the CHIP-Tool implementation. I'm not sure if there's any other way to open a commissioning window.

**Comment by bzbarsky-apple** [comment]
@qawitherev What timeout duration did you use?  Ideally the device would log why it considers the command invalid, but in practice the 
```
Failed to open commissioning window. Global status 0x85
```
log means the provided timeout was outside the spec-required range of 180-900 seconds (3-15 minutes).

> My question is, which one is the new setup passcode that we want show to user. Is it the result from MTRSetupPayload.generateRandomSetupPasscode() or any other MTRSetupPayload that isn't mentioned here?

You want to show the user a serialization of the MTRSetupPayload that's passed to the completion handler, as either a QR code or a numeric code.

**Comment by qawitherev** [comment]
Timeout is 180 second, noted. Controller (app) is not notified when device is commissioned to a new admin is it? Its ok tho. Closing this one. Big thanks my guy!

**Comment by bzbarsky-apple** [comment]
> Controller (app) is not notified when device is commissioned to a new admin is it?

It is if it subscribes to the Fabrics attribute on the device...
