### ISSUE TITLE
Hi, need to know that the Android chip-tool is depreciated as i have asked at DEVzone they replied me that it is depricated and buggy. So avoid it 

### ISSUE THREAD

**Issue by Rajesh0071998** [project-chip/connectedhomeip#29446]
### Reproduction steps

why Android chip-tool behave different in different Android phones? .
I am attaching the Devzone link as well.
[https://devzone.nordicsemi.com/f/nordic-q-a/104120/hi-facing-some-issues-while-commissioning-the-android-chip-tool-with-matter-light-bulb](url)
[https://devzone.nordicsemi.com/f/nordic-q-a/104095/hi-as-i-am-using-the-android-chip-tool-for-commissioning-purpose-but-when-i-scan-the-qr-code-it-went-to-thread-credentials-page-i-don-t-understand-what-is-it](url)

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

bd94d060c3

### Platform

nrf

### Type

Platform Issue

**Comment by yunhanw-google** [comment]
feel free to reopen with new issue, thanks
