### ISSUE TITLE
[CERT-TEST-FAILURE] Test_TC_BINFO_2_2 seems to expects that events are stored across restarts but specs do not require this

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#29451]
### Feature Area

Other

### Test Case

Test_TC_BINFO_2_2

### Reproduction steps

The Test is subscribing to StartUp, Shutdown and Leave events (in this order), but always with "keepSubscriptions !== true", this means that the first two subscriptions are gone and before the Reboot only the "Leave" event is subscribed.

After reboot the test reads the StartUpevent and compares it, all good.

Then it subscribes to "ShutDown" event and requires a manual verification "Verify that ShutDown event has priority set as CRITICAL", but in this case there is no ShutDown event existing.
According to the specs (at least till 1.1) Event should just be "buffered", but nothing requires events needing to be persisted.
@bzbarsky-apple or did I missed that anywhere or does "Buffering" in fact means "persisting"?

I personally assume (!) that events should be persisted to really also be part of an possible device-side audit track for door locks or such, but then the specs shouldstate this very clear as requirement.

Thank you for clarification or adjustment of the test.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

current master

### Platform

core

**Comment by bzbarsky-apple** [comment]
The test plan says to shut down the DUT and _then_ do the verification for the Shutdown event.  The test script needs to reflect this.  Filed https://github.com/CHIP-Specifications/chip-test-scripts/issues/675

That said, the test plan is nonsensical with its subscription preconditions.  Filed https://github.com/CHIP-Specifications/chip-test-plans/issues/3488
