### ISSUE TITLE
[ICD] Test ICD Identification during auto-commissioning via icd example app

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#29475]

**Comment by mkardous-silabs** [comment]
@erjiaqing 
For the `without ICD code`, this will be done with the all-cluster-app as the server
For the `with ICD`, this will be done with the lit-icd-app as the server

See #30291 30291

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/29427/files
