### ISSUE TITLE
[1.1] [BUG] [Thermostat] How do I set initial value?

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#29503]
### Reproduction steps

Hi,

I modified `emberAfThermostatClusterServerInitCallback()` as below.

[https://github.com/project-chip/connectedhomeip/blob/8f66f4215bc0708efc8cc73bda80620e67d8955f/src/app/clusters/thermostat-server/thermostat-server.cpp#L65](https://github.com/project-chip/connectedhomeip/blob/8f66f4215bc0708efc8cc73bda80620e67d8955f/src/app/clusters/thermostat-server/thermostat-server.cpp#L65)

```cpp
using namespace ::chip;                // add
using namespace ::chip::DeviceManager; // add
using namespace ::chip::DeviceLayer;   // add
using namespace ::chip::System;        // add

constexpr EndpointId kThermostatEndpoint = 1;

void emberAfThermostatClusterServerInitCallback(chip::EndpointId endpoint)
{
    ChipLogError(Zcl, "********** Start Thermostat Cluster Server Init Callback ***********");

    PlatformMgr().LockChipStack();
    ChipLogError(Zcl, "********** LockChipStack() ***********");

    chip::app::Clusters::Thermostat::Attributes::LocalTemperature::Set(kThermostatEndpoint, 2345, 0);
    ChipLogError(Zcl, "********** Set Attribute value ***********");

    PlatformMgr().UnlockChipStack();
    ChipLogError(Zcl, "********** Finish Thermostat Cluster Server Init Callback ***********");
}
```

However, `PlatformMgr().LockChipStack()` stacked.
How do I resolve it?

> chip[ZCL] DeviceInfoProvider is not registered
> chip[ZCL] Trying to write invalid Calendar Type
> chip[ZCL] Failed to write calendar type with error: 0x87
> chip[DMG] Endpoint 1, Cluster 0x0000_0003 update version to 870e767d
> chip[DMG] Endpoint 1, Cluster 0x0000_0004 update version to a207bc5e
> chip[DMG] Endpoint 1, Cluster 0x0000_0004 update version to a207bc5f
> chip[DMG] Endpoint 1, Cluster 0x0000_0005 update version to 1b3e33d2
> chip[ZCL] ********** Start Thermostat Cluster Server Init Callback ***********

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 8f66f4215bc0708efc8cc73bda80620e67d8955f (HEAD, tag: v1.1.0.1)

### Platform

core

## Environment

Host OS: ubuntu 22.04

Target : Realtek RTL8722DM

Ameba SDK : [https://github.com/pankore/ambd_sdk_with_chip_non_NDA](https://github.com/pankore/ambd_sdk_with_chip_non_NDA)
commit 992e50929fe1d00ca3828cc338f3b19509aa7113 (HEAD -> v1.1-branch, tag: ameba_update_2023_05_05, origin/v1.1-branch)

**Comment by bzbarsky-apple** [comment]
> However, PlatformMgr().LockChipStack() stacked.

I assume you mean "deadlocked"?

The answer is: `emberAfThermostatClusterServerInitCallback` is supposed to be called called _with the stack locked_.  If you try to lock in there again, you will deadlock.  And since the stack is already locked, you don't need to do anything to lock it.  Just set your attributes.
