### ISSUE TITLE
[Build] Passed all the checks stuck on the "Solving dependencies requirements"

### ISSUE THREAD

**Issue by BartJozwicki** [project-chip/connectedhomeip#29507]
### Build issue(s)
I start by exporting esp-idf
1. source export.sh in (esp-idf 5.1 directory)
Then I activate matter in connectedhomeip 
3. source scripts/activate.sh (connectedhomeip directory)
4. Then I run all the tests with ninja etc. it passes
Then i head to the directory with example project
6. cd examples/lighting-app/esp32
7. idf.py clean
8. idf.py --preview set-target esp32c6
Then my terminal get stucked on "Solving dependencies requirements" picture attached. I have reinstalled the enviroment and esp-idf 3 times I tried to set target to different boards with no avail. Please advise what to do. 
<img width="1634" alt="Screenshot 2023-09-29 at 13 36 03" src="https://github.com/project-chip/connectedhomeip/assets/108279543/5ecd0e76-e778-4553-b9dd-6335e21a39c7">

### Platform

esp32

**Comment by bzbarsky-apple** [comment]
@shubhamdp @dhrishi

**Comment by dhrishi** [comment]
@BartJozwicki In general, at this step, the `managed_components` directory is created by pulling in the required components from the Espressif component manager. Can you please wait for some time and see if it completes? Or it is stuck there for a longer time?

**Comment by shubhamdp** [comment]
@BartJozwicki can you please take a look at https://github.com/project-chip/connectedhomeip/issues/27653#issuecomment-1635375210, looks like similar problem.

**Comment by BartJozwicki** [comment]
> @BartJozwicki can you please take a look at [#27653 (comment)](https://github.com/project-chip/connectedhomeip/issues/27653#issuecomment-1635375210), looks like similar problem.

Removing cache helped, thank you my problem has been resolved.
