### ISSUE TITLE
How to commission a device to our fabric after adding it using Matter.Support

### ISSUE THREAD

**Issue by LucaFagan** [project-chip/connectedhomeip#29537]
### Feature description

We have the following configuration:
- eero border router
- our own thermostat device that we are developing
- no home pod or home TV are used

We was able to commission the device using Matter.Framework but it can no more be used as we get error:

`CHIP: [BLE] BLE:Error writing Characteristics in Chip service on the device: [The specified UUID is not allowed for this operation.]`

So we have followed this guide

https://developer.apple.com/documentation/mattersupport/adding-matter-support-to-your-ecosystem

and implemented Matter Extension.

In Matter Extension the following callbacks are fired:

```
override func selectThreadNetwork(from threadScanResults: [MatterAddDeviceExtensionRequestHandler.ThreadScanResult]) async throws -> MatterAddDeviceExtensionRequestHandler.ThreadNetworkAssociation

override func commissionDevice(in home: MatterAddDeviceRequest.Home?, onboardingPayload: String, commissioningID: UUID) async throws
```

In our iOS demo app the following function completes without errors
```
try await request.perform()
```

The thermostat device seems to be successfully commissioned.

In https://developer.apple.com/documentation/mattersupport/adding-matter-support-to-your-ecosystem there is a comment that says: 

`Use Matter.Framework APIs to pair the accessory to your application with the provided onboardingPayload.`

How should this thing be done ?

We tried to start the matter controller in the old way:

```
    func start() -> Bool
    {
        if (self.matterController == nil)
        {
            let storage = MatterStorage.shared
            let factory = MTRDeviceControllerFactory.sharedInstance()
            let factoryParams = MTRDeviceControllerFactoryParams(storage: storage)
            
            do
            {
                try factory.start(factoryParams)
            }
            catch
            {
                return false
            }
            
            let keys = FabricKeys()
            let params = MTRDeviceControllerStartupParams(signing: keys, fabricId: UInt64(fabricId), ipk: keys.ipk)
            params.vendorID = NSNumber(value: self.vendorId)
            
            self.matterController = try? factory.createController(onExistingFabric: params)
            
            let controllerNid = self.matterController?.controllerNodeID
            
            if (self.matterController == nil)
            {
                self.matterController = try? factory.createController(onNewFabric: params)
            }
        }
        
        return (self.matterController != nil)
    }
```

Certificate are generated locally as in Matter Darwin example.

We tried to call 

let params = MTRCommissioningParameters()
matterController?.commissionNode(withID: NSNumber(value: self.deviceNid), commissioningParams: params)

in commissionDevice of Matter Extension but we get error:

Invalid object state.

  

### Platform

darwin

### Platform Version(s)

1.0

**Comment by bzbarsky-apple** [comment]
@LucaFagan in your `commissionDevice` extension implementation you need to create a commissioning session, then when that succeeds do the `matterController?.commissionNode` bit.  Exactly what you used to do over BLE, but using the payload passed to `commissionDevice`, not the device's factory onboarding payload.

See also https://developer.apple.com/documentation/matter/onboarding_a_matter_device#4292463

**Comment by LucaFagan** [comment]
@bzbarsky-apple I tried to create the commission session using setupCommissioningSession and I get the error:

Error Domain=MTRErrorDomain Code=1 UserInfo={NSLocalizedDescription=<private>, errorCode=172}

commissioningSessionEstablishmentDone is never fired.

This is what I do in Matter Extension:

```
class RequestHandler: MatterAddDeviceExtensionRequestHandler
{
    var deviceNid: UInt64 = 11
    var matterController: MTRDeviceController!

...

    override func commissionDevice(in home: MatterAddDeviceRequest.Home?, onboardingPayload: String, commissioningID: UUID) async throws
    {
        // Use Matter.Framework APIs to pair the accessory to your application with the provided onboardingPayload.
        
        // Use this function to commission the device with your Matter stack.
        
        os_log(.default, "FAGAN: commissionDevice")
        
        _ = MatterService.shared.start()
        
        guard let matterController = MatterService.shared.matterController else
        {
            os_log(.default, "FAGAN: commissionDevice->matterController is null")
            return
        }
        
        self.matterController = matterController
        
        let callbackQueue = DispatchQueue(label: "com.bhtronics.pairing.callback")
        self.matterController.setDeviceControllerDelegate(self, queue: callbackQueue)
        
        if let payload = try? MTRSetupPayload(onboardingPayload: onboardingPayload)
        {
            do
            {
                try self.matterController.setupCommissioningSession(with: payload, newNodeID: NSNumber(value: self.deviceNid))
                os_log(.default, "FAGAN: setupCommissioningSession")
            }
            catch let error
            {
                os_log(.default, "FAGAN: setupCommissioningSession ERROR->\(error)")
            }
        }
    }
```


and this is how I create the controller

```
    func start() -> Bool
    {
        if (self.matterController == nil)
        {
            let storage = MatterStorage.shared
            let factory = MTRDeviceControllerFactory.sharedInstance()
            let factoryParams = MTRDeviceControllerFactoryParams(storage: storage)
            
            do
            {
                try factory.start(factoryParams)
            }
            catch
            {
                return false
            }
            
            let keys = FabricKeys()
            let params = MTRDeviceControllerStartupParams(signing: keys, fabricId: UInt64(fabricId), ipk: keys.ipk)
            params.vendorID = NSNumber(value: self.vendorId)
            
            self.matterController = try? factory.createController(onExistingFabric: params)
            
            // let controllerNid = self.matterController?.controllerNodeID
            
            if (self.matterController == nil)
            {
                self.matterController = try? factory.createController(onNewFabric: params)
            }
        }
        
        return (self.matterController != nil)
    }
```

**Comment by LucaFagan** [comment]
Hi again @bzbarsky-apple,

I further aligned my code with the provided example (see below). However I'm still getting the same error when calling setupCommissioningSession(...):

Error Domain=MTRErrorDomain Code=1 UserInfo={NSLocalizedDescription=<private>, errorCode=172}

What am I missing here ?

Regards
Luca Fagan


```
    override func commissionDevice(in home: MatterAddDeviceRequest.Home?, onboardingPayload: String, commissioningID: UUID) async throws
    {
        // Use Matter.Framework APIs to pair the accessory to your application with the provided onboardingPayload.
        
        // Use this function to commission the device with your Matter stack.
        
        os_log(.default, "FAGAN: commissionDevice")
        
        self.matterController = createMatterController()
        
        guard self.matterController != nil else
        {
            os_log(.default, "FAGAN: commissionDevice->matterController is null")
            return
        }
        
        if let payload = try? MTRSetupPayload(onboardingPayload: onboardingPayload)
        {
            do
            {
                try self.matterController!.setupCommissioningSession(with: payload, newNodeID: NSNumber(value: self.deviceNid))
                os_log(.default, "FAGAN: setupCommissioningSession")
            }
            catch let error
            {
                os_log(.default, "FAGAN: setupCommissioningSession ERROR->\(error)")
            }
        }
    }
```


```
    func createMatterController() -> MTRDeviceController?
    {
        let storage = MatterStorage.shared
        let factory = MTRDeviceControllerFactory.sharedInstance()
        let factoryParams = MTRDeviceControllerFactoryParams(storage: storage)
        
        do
        {
            try factory.start(factoryParams)
        }
        catch
        {
            os_log(.default, "FAGAN: unable to start factory")
            return nil
        }
        
        let keys = FabricKeys()
        
        let params = MTRDeviceControllerStartupParams(ipk: keys.ipk, fabricID: NSNumber(value: fabricId), nocSigner: keys)

        // I've tired even with this function that is the one used the darwin example
        // let params = MTRDeviceControllerStartupParams(signing: keys, fabricId: UInt64(fabricId), ipk: keys.ipk)

        params.vendorID = NSNumber(value: self.vendorId)
        
        os_log(.default, "FAGAN: create controller on Existing Fabric")
        var matterController = try? factory.createController(onExistingFabric: params)
        
        if (matterController == nil)
        {
            os_log(.default, "FAGAN: create controller on New Fabric")
            matterController = try? factory.createController(onNewFabric: params)
        }
        
        let callbackQueue = DispatchQueue(label: "com.bhtronics.pairing.callback")
        matterController?.setDeviceControllerDelegate(self, queue: callbackQueue)
        
        return matterController
    }
```

**Comment by bzbarsky-apple** [comment]
@LucaFagan So it's the call to `matterController!.setupCommissioningSession` that returns the `Error Domain=MTRErrorDomain Code=1 UserInfo={NSLocalizedDescription=, errorCode=172}`?

172 is very likely CHIP_ERROR_INTERNAL, but I don't see anything obvious on the "set up the PASE session" codepath that would lead to that.

What I would suggest is filing a feedback assistant ticket following the instructions below and letting me know the ticket id.  That would ideally include logs that would tell us more about what's going on here.


Feedback assistant ticket:
- File a feedback assistant ticket.
https://developer.apple.com/bug-reporting/#feedback-assistant
- Click on the link below using your account:
https://feedbackassistant.apple.com/new-form-response
- Choose iOS/iPadOS to file an issue
- Choose the area as Home App and fill in the details of the type of issue and the description
* Technical Information
Please provide the following
a) Sysdiagnose logs for iPhone / iPad with the timestamp / timeframe of the issue
b) Sysdiagnose logs for all the Home Hubs (HomePod mini / HomePod / Apple TV) with the timestamp / timeframe of the issue
c) Accessory logs with the timestamp / timeframe of the issue
d) mDNS network logs with timestamp / timeframe of the issue
e) Video or screenshot describing the issue (optional but beneficial)
Please make sure you download and install the profiles for iOS and tvOS as provided here. The instructions are also in these links.
* iOS:
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=homekit
 - https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=network
 - https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=mdns
* tvOS:
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=homekit
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=network
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=mdns
For installation instructions, refer to https://developer.apple.com/bug-reporting/profiles-and-logs.
Note: Once you have the profile on the iPhone, it will ask you if you want to install it on other devices. Follow the prompts to install on the HomePod, Apple TV, etc., where you have the described issue and reproduce it.

**Comment by LucaFagan** [comment]
Hi @bzbarsky-apple,

we have filed the assistant ticket, id = FB13238453

This may seem a stupid question: in our configuration we don't have HomePod or Apple TV, we only want to add the device to eero border router thread netowrk and control it using Matter.Framework.

Is this scenario contemplated ?

Regards
Luca Fagan

**Comment by bzbarsky-apple** [comment]
@LucaFagan Thanks!  Following up on that.  I _think_ what you are doing should work without a HomePod or AppleTV....

**Comment by bzbarsky-apple** [comment]
@LucaFagan Just to check: are the "FAGAN: setupCommissioningSession" logs in the code that was used when generating that ticket?  Did the `setupCommissioningSession()` call get reached in the time period covered by that ticket?

**Comment by LucaFagan** [comment]
yes, they did

**Comment by bzbarsky-apple** [comment]
@LucaFagan Understood.  I am just being confused because I am not seeing those logs from your app in the sysdiagnose, or the logs from the Matter library....  At least not around the time period indicated in the feedback ticket.  So either I am looking for them wrong or something else is going on...

**Comment by LucaFagan** [comment]
Hi @bzbarsky-apple,

I've uploaded the new log in ticket FB13239882.

We start commissioning at 9:47 as you can see in Cosole.png

We have attached a screen shot with intalled profiles in InstalledProfiles.png and the MatterExtension project files.

Hope this time you can see something.

Regards
Luca Fagan

**Comment by bzbarsky-apple** [comment]
@LucaFagan Thank you, those new logs are much better from my point of view.  I see Matter things going on there!

So this log:
```
2023-10-06 09:47:06.991085+0200 0x23D6     Default   0xCFE3               505    0 MatterExtension: (MatterExtension) FAGAN: setupCommissioningSession ERROR->Error Domain=MTRErrorDomain Code=1 UserInfo={NSLocalizedDescription=<private>, errorCode=172}
```

is preceded by:
```
2023-10-06 09:47:06.983655+0200 0x23D6     Default   0xCFE3               505    0 MatterExtension: (Matter) [com.csa.matter:Controller] Starting commissioning discovery over DNS-SD
2023-10-06 09:47:06.983703+0200 0x23D6     Default   0xCFE3               505    0 MatterExtension: (Matter) [com.csa.matter:Discovery] Browsing for: _matterc._udp,_L832
...
2023-10-06 09:47:06.988258+0200 0xCAD      Error     0x0                  170    0 mDNSResponder: (mDNSResponder) [com.apple.mdns:trust] App Info.plist(NSBonjourServices) does not allow '_matterc._udp.' for (MatterExtension)
...
2023-10-06 09:47:06.988505+0200 0x23D6     Error     0xCFE3               505    0 MatterExtension: (Matter) [com.csa.matter:Default] Error(src/platform/Darwin/MdnsError.cpp:108: CHIP Error 0x000000AC: Internal error): Failure while pairing the device
```

I suspect what you want is to add
```
	<key>NSBonjourServices</key>
	<array>
		<string>_matter._tcp</string>
		<string>_matterc._udp</string>
	</array>
```
to the Info.plist for your MatterExtension.

I created https://github.com/project-chip/connectedhomeip/pull/29642 to improve the error reporting here.  With that in place, in this situation you should get an error more like this:
```
Error Domain=MTRErrorDomain Code=15  UserInfo={NSLocalizedDescription=Access denied to perform DNS-SD lookups.  Check that "_matter._tcp" and/or "_matterc._udp" are listed under the NSBonjourServices key in Info.plist}
```
(and even if that description does not appear, at least the Code=15 will let you look up what's going on in MTRError.h...)

**Comment by LucaFagan** [comment]
Hi @bzbarsky-apple,
I added NSBonjourServices to the wrong node (NSExtension), instead it must be added to the root (Information Property List).

Now that i have added NSBonjourServices to the right node, setupCommissionSession success but commissioningSessionEstablishmentDone is never called. Even statusUpdate is never called.

Do you have any idea what the problem could be?

I've uploaded the new log in ticket  FB13272537

Device controller delegate is set in createMatterController

```
let callbackQueue = DispatchQueue(label: "com.bhtronics.pairing.callback")
matterController?.setDeviceControllerDelegate(self, queue: callbackQueue)
```

I've checked console log but can't see errors. 

```
//
//  RequestHandler.swift
//  MatterExt
//

import MatterSupport
import Matter
import OSLog
import ThreadNetwork

// The extension is launched in response to `MatterAddDeviceRequest.perform()` and this class is the entry point
// for the extension operations.

class RequestHandler: MatterAddDeviceExtensionRequestHandler, MTRDeviceControllerDelegate, MTRDeviceAttestationDelegate
{
    let vendorId = 0xFFF1
    let fabricId = 1
    
    var deviceNid: UInt64 = 1
    var matterController: MTRDeviceController?
    
    override init()
    {
        super.init()
        
        // self.logger.info("FAGAN: init")
        
        os_log(.error, "FAGAN: init ")
    }
    
    override func validateDeviceCredential(_ deviceCredential: MatterAddDeviceExtensionRequestHandler.DeviceCredential) async throws
    {
        // Use this function to perform additional attestation checks if that is useful for your ecosystem.
        
        os_log(.default, "FAGAN: validateDeviceCredential")
    }

    override func selectWiFiNetwork(from wifiScanResults: [MatterAddDeviceExtensionRequestHandler.WiFiScanResult]) async throws -> MatterAddDeviceExtensionRequestHandler.WiFiNetworkAssociation
    {
        // Use this function to select a Wi-Fi network for the device if your ecosystem has special requirements.
        // Or, return `.defaultSystemNetwork` to use the iOS device's current network.
        
        os_log(.default, "FAGAN: selectWiFiNetwork")
        
        return WiFiNetworkAssociation.defaultSystemNetwork
    }

    override func selectThreadNetwork(from threadScanResults: [MatterAddDeviceExtensionRequestHandler.ThreadScanResult]) async throws -> MatterAddDeviceExtensionRequestHandler.ThreadNetworkAssociation
    {
        // Use this function to select a Thread network for the device if your ecosystem has special requirements.
        // Or, return `.defaultSystemNetwork` to use the default Thread network.
        
        // BHtronics BORDER ROUTER
        // let extPanIdHex = "aca40208546a203f"
       
        // EERO BORDER ROUTER
        let extPanIdHex = "273eef7f4ed7763d"
        
        if let extPanId = UInt64(extPanIdHex, radix: 16)
        {
            os_log(.error, "FAGAN: selectThreadNetwork with extPanId=\(extPanIdHex)")
            
            // Return `extendedPANID` of the Thread network known to your application.
            return ThreadNetworkAssociation.network(extendedPANID: extPanId)
        }
        else
        {
            os_log(.error, "FAGAN: selectThreadNetwork default")
            return ThreadNetworkAssociation.defaultSystemNetwork
        }
    }

    override func commissionDevice(in home: MatterAddDeviceRequest.Home?, onboardingPayload: String, commissioningID: UUID) async throws
    {
        // Use Matter.Framework APIs to pair the accessory to your application with the provided onboardingPayload.
        
        // Use this function to commission the device with your Matter stack.
        
        os_log(.default, "FAGAN: commissionDevice")
        
        self.matterController = createMatterController()
        
        guard self.matterController != nil else
        {
            os_log(.default, "FAGAN: commissionDevice->matterController is null")
            return
        }
        
        if let payload = try? MTRSetupPayload(onboardingPayload: onboardingPayload)
        {
            do
            {
                try self.matterController!.setupCommissioningSession(with: payload, newNodeID: NSNumber(value: self.deviceNid))
                os_log(.default, "FAGAN: setupCommissioningSession SUCCESS")
            }
            catch let error
            {
                os_log(.default, "FAGAN: setupCommissioningSession ERROR->\(error)")
            }
        }
    }

    override func rooms(in home: MatterAddDeviceRequest.Home?) async -> [MatterAddDeviceRequest.Room]
    {
        // Use this function to return the rooms your ecosystem manages.
        // If your ecosystem manages multiple homes, ensure you are returning rooms that belong to the provided home.
        
        os_log(.default, "FAGAN: rooms")
        let room = MatterAddDeviceRequest.Room(displayName: "Living Room")
        return [room]
    }

    override func configureDevice(named name: String, in room: MatterAddDeviceRequest.Room?) async
    {
        // Use this function to configure the (now) commissioned device with the given name and room.
        
        os_log(.default, "FAGAN: configureDevice")
    }
    
    func controller(_ controller: MTRDeviceController, statusUpdate status: MTRCommissioningStatus)
    {
        os_log(.default, "FAGAN: statusUpdate=\(status.rawValue)")
    }
    
    func controller(_ controller: MTRDeviceController, commissioningSessionEstablishmentDone error: Error?)
    {
        os_log(.default, "FAGAN: commissioningSessionEstablishmentDone")
        
        if (error != nil)
        {
            os_log(.default, "FAGAN: commissioningSessionEstablishmentDone->NO ERROR")
            commission()
        }
        else
        {
            os_log(.default, "FAGAN: commissioningSessionEstablishmentDone->\(error!.localizedDescription)")
        }
    }
    
    func controller(_ controller: MTRDeviceController, commissioningComplete error: Error?)
    {
        os_log(.default, "FAGAN: commissioningComplete")
        
        if (error != nil)
        {
            os_log(.error, "FAGAN: commissioningComplete ERROR->\(error!.localizedDescription)")
        }
    }
    
    func createMatterController() -> MTRDeviceController?
    {
        let storage = MatterStorage.shared
        let factory = MTRDeviceControllerFactory.sharedInstance()
        let factoryParams = MTRDeviceControllerFactoryParams(storage: storage)
        
        do
        {
            try factory.start(factoryParams)
        }
        catch
        {
            os_log(.default, "FAGAN: unable to start factory")
            return nil
        }
        
        let keys = FabricKeys()
        
        // OLD WAY
        os_log(.default, "FAGAN: MTRDeviceControllerStartupParams OLD WAY")
        let params = MTRDeviceControllerStartupParams(signing: keys, fabricId: UInt64(fabricId), ipk: keys.ipk)
        // NEW WAY
        //        os_log(.default, "FAGAN: MTRDeviceControllerStartupParams NEW WAY")
        //        let params = MTRDeviceControllerStartupParams(ipk: keys.ipk, fabricID: NSNumber(value: fabricId), nocSigner: keys)
        
        params.vendorID = NSNumber(value: self.vendorId)
        
        os_log(.default, "FAGAN: create controller on Existing Fabric")
        var matterController = try? factory.createController(onExistingFabric: params)
        
        if (matterController == nil)
        {
            os_log(.default, "FAGAN: create controller on New Fabric")
            matterController = try? factory.createController(onNewFabric: params)
        }
        
        let callbackQueue = DispatchQueue(label: "com.bhtronics.pairing.callback")
        matterController?.setDeviceControllerDelegate(self, queue: callbackQueue)
        
        return matterController
    }
    
    func commission()
    {
        let params = MTRCommissioningParameters()
        
        do
        {
            guard self.matterController != nil else
            {
                os_log(.default, "FAGAN: commission->matterController is null")
                return
            }
            
            os_log(.default, "FAGAN: commissionNode(\(self.deviceNid))")
            
            try self.matterController!.commissionNode(withID: NSNumber(value: self.deviceNid), commissioningParams: params)
        }
        catch let error
        {
            os_log(.error, "FAGAN: commissionNode exception->\(error.localizedDescription)")
        }
    }
}

extension RequestHandler
{

}

```

**Comment by LucaFagan** [comment]
hi @bzbarsky-apple ,
i've noticed that if I debug the matter extension, in console I see

0x00000038: Invalid PASE parameter
Failed during PASE session setup: src/protocols/secure_channel/PASESession.cpp:766: CHIP Error 0x00000038: Invalid PASE parameter
Discovery timed out
Mdns: Browse failure (src/platform/Darwin/DnssdImpl.cpp:412: CHIP Error 0x00000074: The operation has been cancelled)

**Comment by bzbarsky-apple** [comment]
> setupPasscode is different between original payload passed in MatterAddDeviceRequest and onboardingPayload returned in commissionDevice callback

Yes, this is expected: those are different commissioning windows, with different PASE parameters.

Looking into the new logs.  I see a browse for what looks like the right discriminator starting now, but nothing showing it ending (including timeout?) which is a bit odd.

**Comment by LucaFagan** [comment]
Hi @bzbarsky-apple,

is it possible to use the onboardingPayload returned in commissionDevice and try to commission the device from the app in a later time ?
The idea is:
- to use the extension to commission the device and print the onboardingPayload
- to use the app to complete the commission of the device in our Matter stack

In this way it could be easier to see what happens

**Comment by bzbarsky-apple** [comment]
> is it possible to use the onboardingPayload returned in commissionDevice and try to commission the device from the app in a later time

Yes, as long as you do it within the 15-minute window while the device is commissionable...

**Comment by LucaFagan** [comment]
@bzbarsky-apple we managed to commission our thermostat into our fabric using RC and NOC generated on our server.

Everything seems to work. Problems arise when we uninstal and re-install the app, we get error

Received error (protocol code 1) during pairing process: src/protocols/secure_channel/CASESession.cpp:1977: CHIP Error 0x000000C9: No shared trusted root
Creating NSError from src/protocols/secure_channel/CASESession.cpp:1977: CHIP Error 0x000000C9: No shared trusted root

rc and controller noc are the same, as we store them in KeyChain. It seems the app needs something in MatterStorage (.plist file) but I don't know what.

So the question is: how I can restore every thing so the app can work after re-intall it on the same iOS device ?

Regards
Luca Fagan

**Comment by LucaFagan** [comment]
@bzbarsky-apple we managed to commission our thermostat into our fabric, even using RC and NOC generated on our server.

If I have understood correctly, using Matter.Support the device is first commissioned into Apple Fabric and once done, I can commission it in our fabric.

Is the commissioning in Apple fabric mandatory or is there a way to use Matter.Support to just let the device join the thread network (without commissioning in Apple frabric), get the onboardingPayload and continue the commissioning in our fabric like I already do ?

Reagards
Luca Fagan

**Comment by bzbarsky-apple** [comment]
> Is the commissioning in Apple fabric mandatory

The Keychain fabric?  Yes, it is.

**Comment by huchuankan** [comment]
Matter Commission  demo video ： https://www.bilibili.com/video/BV1Nx421y7sa/

**Comment by iVoGia** [comment]
Hi @LucaFagan , 
Did you completed this task ? 
I'm newbie with matter device. 
Following your code, device was added to setting -> matter accessories.
How to I can get the device list ? 
Can you share me ? 
Thanks .

**Comment by iVoGia** [comment]
> Hi @LucaFagan , Did you completed this task ? I'm newbie with matter device. Following your code, device was added to setting -> matter accessories. How to I can get the device list ? Can you share me ? Thanks .

Hi @bzbarsky-apple  ,
Can you help me this question ? 
Thanks .

**Comment by bzbarsky-apple** [comment]
@iVoGia I am not sure what you are asking.

The point of MatterSupport is to:

1. Commission the device into the keychain fabric (the one that shows up under Settings > Matter accessories).
2. Open a new commissioning window so that you can commission the device into your fabric.

**Comment by iVoGia** [comment]
Hi @bzbarsky-apple , 
I'm testing to pairing device. 
And I see the test device in the setting -> matter accessories.
![Image](https://github.com/project-chip/connectedhomeip/assets/39343021/ca8043de-7870-495c-91e0-012218e1d2d6)

But, when I'm using the DeviceSelector. 
I saw _deviceList always empty. I don't know why ? 
Because , I'm thought it can get the device list .
![Screenshot 2024-06-06 at 10 13 21](https://github.com/project-chip/connectedhomeip/assets/39343021/304b79d0-62d3-4fbf-9648-721559cdeb34)

Can you explain for me: How to get list paired device ? 

Thanks and best regards,

**Comment by bzbarsky-apple** [comment]
@iVoGia I have no idea, sorry.  I can only see the same public documentation here that you can.

**Comment by iVoGia** [comment]
The DeviceSelectors is in the DefaultUtils of example application. It’s alway return to empty.

**Comment by dhaval-shah1** [comment]
> Hi @bzbarsky-apple,
> 
> is it possible to use the onboardingPayload returned in commissionDevice and try to commission the device from the app in a later time ? The idea is:
> 
> * to use the extension to commission the device and print the onboardingPayload
> * to use the app to complete the commission of the device in our Matter stack
> 
> In this way it could be easier to see what happens.
> 
> I've tried and in xCode console I see:
> 
> Discovery timed out Mdns: Browse failure (src/platform/Darwin/DnssdImpl.cpp:412: CHIP Error 0x00000074: The operation has been cancelled)

@LucaFagan @bzbarsky-apple did you guys able to find root casue of above mentioned error? When I try to comissionDevice I am also getting same error as below:

Discovery timed out Mdns: Browse failure (src/platform/Darwin/DnssdImpl.cpp:412: CHIP Error 0x00000074: The operation has been cancelled)

**Comment by bzbarsky-apple** [comment]
@dhaval-shah1 there are many possible root causes for that error.  Maybe the device is not advertising.  Maybe there's a broken WiFi AP or thread border router involved.  Maybe the Apple device involved is not behaving right.

It's really hard to say anything useful here without some more information (logs, dns-sd tool output, etc).
