### ISSUE TITLE
[Android]After #29572, we need generate UI for all cluster interactions in android chip-tool that use generated IM cluster APIs.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#29573]
After #29572, we need generate UI for all cluster interactions in android chip-tool that use generated IM cluster APIs.

**Comment by joonhaengHeo** [comment]
@yunhanw-google 
I think this will be confirmed once #29542 is merged. Because Android ChipTool has a "Cluster Interaction Tool" Button, where the App is using the Generated IM Cluster APIs.
