### ISSUE TITLE
[Example Not Working] Light-Switch-App Not Working

### ISSUE THREAD

**Issue by jvmahon** [project-chip/connectedhomeip#29597]
The 'light-switch-app" example appears to not function properly on ESP32 builds (and presumably others).

### What should happen:  
This example app should build a device with two endpoints (1) On/Off Light Switch (0x0103), and (2) a Generic Switch (0x000F).

After pairing to Apple iOS Home, I would expect to see a light switch (for 0x0103) as well as an the iOS control for assigning actions to the buttons (for 0x000F).  This is pretty standard stuff.

### What does happen:
As shown in the image below, after pairing to iOS home, you only see the Generic Switch  (0x000F) endpoint. The endpoint for the on/off switch (0x0103) is missing.  I have also paired to Home Assistant and the behavior is the same.

Generic Switch 0x000F also only allows for a single button press. As explained below, this is pretty limited and it would be desirable if this example more closely matched what competing technologies like z-wave already offer (Matter is certainly capable of that, but the example limited itself).

<img src=https://github.com/project-chip/connectedhomeip/assets/15061942/240d8d47-ff78-484e-ac6a-4a608791dcda width=150 >

### What may be wrong

There are a number of errors in the .zap file. Here are some that may be causing the problem:

#### Endpoint 1
Endpoint 1 is for the light switch, 0x0103

The Groups cluster 0x0004 is enabled as Server.   The matter standard says this should be Client.

The Color Control cluster 0x0300 has been included as a client. This is not a valid cluster for device type 0x103.

#### Endpoint 2
Endpoint 2 is for the generic switch 0x000F

Edited: This looks OK

### As a "nice to have while fixing this"...

I'd also suggest setting the Switch cluster's  "multiPressMax" attribute to 5 and FeatureMap to 30.  This would match the more expansive button pressing and reporting found in competing technologies (i.e., it would match the similar Central Scene Reporting feature that z-wave provides, and it would be nice if the examples helped guide developers to at least match what they are competing against).

#### In the "could you please consider" arena ...
Many "real" devices have a number of options associated with them. For example, switches often have a "smart bulb mode" or a way to disable the button tapping. It would be nice if the example applications included several "Mode Select" endpoints (even if just with various stub labels like "option 1", "option 2" etc., and blank choices "Choice 1.1", "Choice 1.2",  "Choice 2.1", etc.  The mode select" isn't that clear and it would be nice to have an implementation with several mode selects showing also how the FixedLabel and other attributes are used.  I'm trying to work on an implementation of this for Home Assistant but its difficult to do so without a real example (which I was trying to build on the ESP32).

**Comment by jvmahon** [comment]
### What may be wrong

There are a number of errors in the .zap file. Here are some that may be causing the problem:

#### Endpoint 0
Endpoint 0 is for the light switch, 0x0103

The Groups cluster 0x0004 is enabled as Server.   The matter standard says this should be Client.

The Color Control cluster 0x0300 has been included as a client. This is not a valid cluster for device type 0x103.

#### Endpoint 1
Endpoint 1 is for the generic switch 0x000F

The "Binding" cluster is missing. Since 0x000F is a "Simple" device type, this is Mandatory.

For the "Switch" cluster, 0x003B:

### As a "nice to have while fixing this"...

I'd also suggest setting the Switch cluster's  "multiPressMax" attribute to 5 and FeatureMap to 30.  This would match the more expansive button pressing and reporting found in competing technologies (i.e., it would match the similar Central Scene Reporting feature that z-wave provides, and it would be nice if the examples helped guide developers to at least match what they are competing against).


#### In the "could you please consider" arena ...
Many "real" devices have a number of options associated with them. For example, switches often have a "smart bulb mode" or a way to disable the button tapping. It would be nice if the example applications included several "Mode Select" endpoints (even if just with various stub labels like "option 1", "option 2" etc., and blank choices "Choice 1.1", "Choice 1.2",  "Choice 2.1", etc.  The mode select" isn't that clear and it would be nice to have an implementation with several mode selects showing also how the FixedLabel and other attributes are used.

**Comment by bzbarsky-apple** [comment]
Please report Home App issues via feedback assistant, but my understanding is that Home App does not currently support the "On/Off Light Switch" device type.

> The "Binding" cluster is missing. Since 0x000F is a "Simple" device type, this is Mandatory.

It's not a Simple device type that has any client clusters, right?  So why would Binding be mandatory?

**Comment by jvmahon** [comment]
> Please report Home App issues via feedback assistant, but my understanding is that Home App does not currently support the "On/Off Light Switch" device type

iOS Home definitely supports on/off light switch -- its one of the few types that is readily available on the commercial market from vendors like T-Link and Eve Home - and it does support the generic switch type. I can get it to correctly work with a Zap example using Chef.  Home Assistant also supports both types and I can get Home Assistant to correctly work too.  So I believe this is an problem in the example implementation, not iOS Home or Home Assistant.

**Comment by jvmahon** [comment]
> It's not a Simple device type that has any client clusters, right? So why would Binding be mandatory?

So maybe I'm reading the standard wrong.  I was looking at:

**Comment by bzbarsky-apple** [comment]
> From your last comment, it just hit me that I should have read it as "if a device meets both the requirement (a) of being in the Simple class and the requirement (b) that it has Client clusters then Binding is Mandatory.".

Yep, that's a boolean "and" there.

**Comment by jvmahon** [comment]
The odd thing is that I was able to re-build this but as a Chef example by starting with a blank template and then re-creating the same endpoints (Root, On/Off Switch 0x0103, and Generic Switch 0x000F). I don't know why my rebuild works, but it does - see image below from iOS where iOS shows both the switch and generic switch side-by-side.  I'm going to close this comment for now, but something remains odd with the example.

![IMG_2144](https://github.com/project-chip/connectedhomeip/assets/15061942/a5ec9b72-74bc-4237-adad-e59b052eade4)
