### ISSUE TITLE
[XML] Update Alarm Clusters XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#29667]
The data type name is being updated in the Alarm Clusters (AlarmBase, DishwasherAlarm and RefrigeratorAlarm) and must be updated in the XML as well.

Renamed:

- AlarmMap to AlarmBitmap

Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7628

**Comment by robszewczyk** [comment]
I think we are too late in the process to take in the rename change especially since it adds relatively little to the overall consistency.

**Comment by bzbarsky-apple** [comment]
Reopening, since the spec here got changed.
