### ISSUE TITLE
[chip-tool] How to get node id in OnAttributeData?

### ISSUE THREAD

**Issue by jaggerwoo** [project-chip/connectedhomeip#29700]
### Build issue(s)

From ReportCommand.h OnAttributeData function i can get endpoint id , attribute id and cluster id except node id, how to get the node id from in function of current reporting node?

### Platform

raspi

**Comment by bzbarsky-apple** [comment]
The expectation is that you have one Callback per ReadClient (because anything else will be _very_ broken) and then you know what ReadClient is involved and know what node ID you initialized it with.
