### ISSUE TITLE
After implementing multi-admin, how should I use CHIP-TOOL to query all administrators of the matter device?

### ISSUE THREAD

**Issue by whqxbs** [project-chip/connectedhomeip#29713]
### Test issue(s)

After implementing multi-admin, how should I use CHIP-TOOL to query all administrators of the matter device?
I noticed that I can see all the administrators of the device in full in Homekit, but I didn't find a way to implement it in CHIP-TOOL, can you tell me how to go about it?

### Platform

other, all

**Comment by whqxbs** [comment]
![微信图片_20231012032242](https://github.com/project-chip/connectedhomeip/assets/45973939/73433b43-2980-446d-90e3-4807582f72f1)

**Comment by bzbarsky-apple** [comment]
```
chip-tool operationalcredentials read fabrics ${NODE_ID} 0 --fabric-filtered false
```

That is, read the "Fabrics" attribute from the "Operational Credentials" cluster on endpoint 0 of the node, and turn off fabric-filtering, so you get all the entries for all the fabrics.

**Comment by whqxbs** [comment]
I have tried the commond you say, but I can only get the information below. 
I still can't get the admins' name like what Homekit can do in the picture above.
![QQ截图20231012125141](https://github.com/project-chip/connectedhomeip/assets/45973939/8ce0c94e-d47e-4da1-85e6-63b09dd132b3)

**Comment by whqxbs** [comment]
> ```
> chip-tool operationalcredentials read fabrics ${NODE_ID} 0 --fabric-filtered false
> ```
> 
> That is, read the "Fabrics" attribute from the "Operational Credentials" cluster on endpoint 0 of the node, and turn off fabric-filtering, so you get all the entries for all the fabrics.

**Comment by bzbarsky-apple** [comment]
> I have tried the commond you say, but I can only get the information below.

Please attach (as a text attachment, not paste, not an image) the full log from the command involved, including the chip-tool command line.

Because either you left off `--fabric-filtered false` or this is not the same device as the "Connected Services" screen shot above (which seems to show three fabrics, whereas here the new screenshot only shows one).

**Comment by bzbarsky-apple** [comment]
But also: I am pretty sure the strings shown above do not come from the device.  "Matter Test" just means the VendorId was 0xFFF1 == 65521.  "Apple Home" means the vendor ID was 0x1349, etc.

**Comment by whqxbs** [comment]
Thank you for your reply! I corrected the command I entered and can successfully see 3 fabrics with CHIP-TOOL connected to the device at the same time as Homekit (image and text are below).
I would also like to ask why three fabrics and what is this extra VendorID: 4996?
[result.txt](https://github.com/project-chip/connectedhomeip/files/12878629/result.txt)
![QQ截图20231012154916](https://github.com/project-chip/connectedhomeip/assets/45973939/f80835fc-6fb0-4216-a604-2f7f007677df)

**Comment by whqxbs** [comment]
> 4996 == 0x1384 is "Apple Keychain". That's the fabric that lets you have that "Connected Services" UI even if a device is removed from Apple Home, lets you easily commission the device onto other fabrics even if it gets removed from Apple Home, etc.

Could you tell me how to implement what you said about continuing to implement that commission the device onto other fabrics after deleting the device in Homekit's Home? I would like to know the relevant operations and commands, thank you!

**Comment by bzbarsky-apple** [comment]
See https://developer.apple.com/documentation/mattersupport
