### ISSUE TITLE
[Build] error: 'StartAppTask' does not name a type

### ISSUE THREAD

**Issue by BartJozwicki** [project-chip/connectedhomeip#29822]
### Build issue(s)

I have used matter before I managed to activate esp-idf then run matter did all the checks with 

gn gen out/host
ninja -C out/host

No issues there, then I go to the folder with examples -> lighting-app -> esp32

I cleand project, then I changed target to esp32-c3 (Also have tried c6 with the same result), when I use 
idf.py build 
my build process gets stuck on: 
/Users/Bart/connectedhomeip/examples/lighting-app/esp32/main/tempCodeRunnerFile.cpp:1:1: error: 'StartAppTask' does not name a type
    1 | StartAppTask
      | ^~~~~~~~~~~~
[1030/1114] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/__/third_party/connectedhomeip/zzz_generated/app-common/app-common/zap-generated/attributes/Accessors.cpp.objninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /Users/Bart/connectedhomeip/examples/lighting-app/esp32/build/log/idf_py_stderr_output_64564 and /Users/Bart/connectedhomeip/examples/lighting-app/esp32/build/log/idf_py_stdout_output_64564

I have checked if that folder is up to date with git repo, I bootstraped the whole project just to make sure it is fine but with no results. Could you advise please? For clarity I will attach screen from the terminal. 

![Screenshot 2023-10-17 at 16 22 33](https://github.com/project-chip/connectedhomeip/assets/108279543/a65e1250-68fd-4205-b4b7-0e812bfa2b65)

### Platform

esp32

**Comment by bzbarsky-apple** [comment]
@shubhamdp @dhrishi

**Comment by shubhamdp** [comment]
@BartJozwicki please take a look at this guide which documents how to build the esp32 examples. https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/esp32/build_app_and_commission.md#build-flash-and-monitor-an-example
