### ISSUE TITLE
[Build] ERROR at //third_party/connectedhomeip/third_party/jsoncpp/BUILD.gn:26:1: Source file not found.source_set("jsoncpp"){

### ISSUE THREAD

**Issue by tianrongqin** [project-chip/connectedhomeip#29839]
### Build issue(s)

when I build the esp32 which is in connectedhomeip,it can't build successfully and display "ERROR at //third_party/connectedhomeip/third_party/jsoncpp/BUILD.gn:26:1: Source file not found.source_set("jsoncpp"){".How can  I do to slove this problem?

### Platform

esp32

**Comment by bzbarsky-apple** [comment]
@tianrongqin What exact steps are you following to build?  Which SHA are you building?

@dhrishi @shubhamdp

**Comment by bzbarsky-apple** [comment]
Duplicate of https://github.com/project-chip/connectedhomeip/issues/29842
