### ISSUE TITLE
Replace usage of IPv4 address to IPv6

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#2984]
#### Problem
There are parts of CHIP stack that's using IPv4 address. CHIP has mandated use of IPv6 addresses. The code should be updated to use the mandated addressing scheme.

 #### Proposed Solution
Update the code.

**Comment by gerickson** [comment]
Some of these may be work arounds for various Android and iOS issues during Rendezvous. Before expunging these wholesale, we should pause to analyze the uses to make sure we aren't introducing regressions for previously-solved problems.
