### ISSUE TITLE
[Platform] 

### ISSUE THREAD

**Issue by junim4u** [project-chip/connectedhomeip#29991]
### Reproduction steps

How should I modify chip-tool to process zcl commands simultaneously targeting different nodes?

### Platform

raspi

### Platform Version(s)

1.0.1

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
chip-tool does not do ZCL at all, so...

If what you want to do is send multiple Matter commands targeting different nodes "in parallel" (as in, send the next one before the previous one finishes), that would require a good bit of re-architecture in chip-tool; it has a concept of "currently running command" and that's a singleton.  But you can start in `examples/chip-tool/commands/common/Commands.cpp` in the `Commands::RunCommand` and see how the logic flows from there.

If you are asking about something else, please reopen and clearly describe what you are asking.
