### ISSUE TITLE
[Tooling] Tag for the TH SHA

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#30001]
### Reproduction steps / Feature

We need a tag or branch for the TH SHA both so we have an official record of where this was taken and so devs can easily repro.

### Platform

core (please add to version below)

### Type

Manually tested with SDK

**Comment by andy31415** [comment]
what is the SHA we need to tag? 19771ed7 or something else?

**Comment by raju-apple** [comment]
Yeah , [19771ed7101321d68b87d05201d42d00adf5368f] is the SHA we made the final release for TH

**Comment by raju-apple** [comment]
@andy31415 can we tag the above SHA ?

**Comment by andy31415** [comment]
what should be the tag name? what is the description for it?

**Comment by doublemis1** [comment]
I understand that the tag should be created for previous Matter releases Test Harness (Matter 1.0, Matter 1.1),

**Comment by cecille** [comment]
@raju-apple - can you answer above about tag names?

**Comment by raju-apple** [comment]
@andy31415 Lets do TH-Matter-1.2 ? ( Current Matter Test Harness-Fall 2023 version is based of this SDK SHA )

**Comment by andy31415** [comment]
https://github.com/project-chip/connectedhomeip/releases/tag/TH-Matter-1.2 created
