### ISSUE TITLE
AverageWearCount attribute got merged throughout SDK without existing in spec, needs to be removed

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#30002]
### Problem

The `AverageWearCount` attribute of the General Diagnostics cluster got introduced throughout the SDK, (possibly including the test harness), in Matter 1.2. This happened in https://github.com/project-chip/connectedhomeip/pull/29285 that predated the 1.2.0 tag, so it is included in that tag.

The AverageWearCount attribute is not present in spec. It was merged from a work-in-progress PR, in the SDK, before the spec had been updated to include it. The spec PR itself (https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7535) got  closed without merging, because it was a new feature that did not follow the NFR/TCR process. 

It is likely that real products will be certified to 1.2 that will include the AverageWearCount "non standard" attribute that is in standard range, but not tested or certified.

### Proposed solution

- Remove AverageWearCount attribute from General Diagnostics cluster XML
- Reserve attribute ID 9 in General Diagnostics cluster, including in spec (do so in rev 3)
- Remove AverageWearCount from General Diagnostics cluster implementation and associated YAML tests, until it appears in the spec.
- Make an urgent CCB to mention that this attribute ID should not be found.

**Comment by tcarmelveilleux** [comment]
FYI @marius-alex-tache @cecille @bzbarsky-apple @woody-apple @robszewczyk

**Comment by tcarmelveilleux** [comment]
The SHA used by TH (according to Chaitanya) is 19771ed7101321d68b87d05201d42d00adf5368f. This includes the new attribute. This means it will not be detected by TC-IDM-10.1 as a reserved/invalid attribute.

**Comment by cecille** [comment]
Per discussion here, we'd like to propose a one-off errata test that should be back ported to 1.2 testing with a test house notification. @naveenkommareddi FYI.

If we go forward with the proposal to mark the attribute ID as reserved and disallowed in the spec going forward, the conformance tests that are landing for 1.3 should catch it automatically.

**Comment by cecille** [comment]
I've added a proposal for a test for 1.2 - please see linked PRs. Given that the plan is to fix this in the spec for 1.3 by marking this attribute as disallowed, we should be able to remove this test for the next release.
