### ISSUE TITLE
[Question] How to add callbacks to linux thermostat example to increase the temperature?

### ISSUE THREAD

**Issue by BurievSardor** [project-chip/connectedhomeip#30010]
I want to generate events like how air-quality-sensor-app does to increase and decrease the temperature of a thermostat. How it can be done?

**Comment by bzbarsky-apple** [comment]
It sounds like you want a setup like all-clusters-app or lock-app have where they are reading a FIFO from `/tmp` and you can send JSON down the pipe to trigger actions.
