### ISSUE TITLE
ReadClient Callback OnAttribute doesn't give the nodeID

### ISSUE THREAD

**Issue by Suresh91439** [project-chip/connectedhomeip#30048]
https://github.com/project-chip/connectedhomeip/blob/02e7647bc6ae8c87012113fb69fcf18f865d075c/examples/chip-tool/commands/clusters/ReportCommand.h#L34

Hi,

After subscribing to the attribute, when there is a change, we get the OnAttribute call back from ReadClient with Attribute path and the data. How do we know, which node has sent this change?

Regards
Suresh Pabbathi

**Comment by bzbarsky-apple** [comment]
The expectation is that the callback knows which ReadClient it's dealing with and hence which node the read/subscribe was dispatched to.
