### ISSUE TITLE
[Build] Chip-Tool: How to import mqtt library

### ISSUE THREAD

**Issue by jaggerwoo** [project-chip/connectedhomeip#30115]
### Build issue(s)

I am a novice at using c++；I want to use mqtt with https://github.com/eclipse/paho.mqtt.c; I added this lib to `/third_party` as submodules.

when i `#include "MQTTClient.h"` to compile, i get errors:

``` c
+ gn gen --check --fail-on-unused-args --root=examples/chip-tool aaa --args=
Done. Made 258 targets from 216 files in 311ms
+ ninja -C aaa
ninja: Entering directory `aaa'
[3/4] ld ./chip-tool
FAILED: chip-tool chip-tool.map 
g++ -target x86_64-apple-macos11.0 -O0 -fPIC -Werror -fdiagnostics-color -Wl,-dead_strip liblogging-stdio.a -Wl,-map,./chip-tool.map @./chip-tool.rsp -o ./chip-tool
Undefined symbols for architecture x86_64:
  "_MQTTClient_connect", referenced from:
      connectMQTT() in chip-tool-utils.a(chip-tool-utils.InteractiveCommands.cpp.o)
  "_MQTTClient_create", referenced from:
      connectMQTT() in chip-tool-utils.a(chip-tool-utils.InteractiveCommands.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

The reason I found this problem was because this parameter  `-lpaho-mqtt3a` was missing at compile time in `paho.mqtt.c` lib, such as: `gcc test.c -o test -lpaho-mqtt3c`,  this parameter meaning is asynchronous, no encryption.

but in our `connectedhomeip` project, i found the compilation tool is gn, so my question is:
1. how and where can i add the `-lpaho-mqtt3a` with gn?
2. how to add this mqtt lib that i can also use `./scripts/examples/gn_build_example.sh` to compile?

**Comment by woody-apple** [comment]
Just including the header doesn't do it, you'll need to update the build GN config to link your library as well. Please look at the other .gn files as examples for how to include external dependencies.
