### ISSUE TITLE
[BUG] Non-backwards-compatible breaking change in Application Launcher cluster.

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#30164]
### Reproduction steps

https://github.com/project-chip/connectedhomeip/pull/30134 made a breaking change to client APIs by changing a writable attribute to readonly.  

We need to either revert that change or figure out some other way of making the APIs continue to exist.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

6ec33d400734ac55ee4b200fece52896398f7f30

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
@andy31415

**Comment by andy31415** [comment]
What is the breaking change (i.e. what methods are missing as a result)? I had assumed this was not an ABI issue.

If this is just some `write*` method availability, could we on-off them into some h/mm file?

**Comment by andy31415** [comment]
I can see no reasonable way to change the spec to make this attribute writable (what would be the meaning? Syaing `SHALL always return an error` also seems wrong) nor do I think keeping it writable in the sdk not in the spec is that practical.

**Comment by bzbarsky-apple** [comment]
> If this is just some write* method availability, could we on-off them into some h/mm file?

That is what it is, and maybe we can, but this is breaking things in the meantime.  I am happy to look into doing this change in a non-breaking way, but I can't do it this week.
