### ISSUE TITLE
Two questions about limiting fabric permissions.

### ISSUE THREAD

**Issue by whqxbs** [project-chip/connectedhomeip#30200]
### Test issue(s)

I know that it is possible to pair a device via the device pairing window that opens with command `./chip-tool administratorcommissioning open-commissioning-window` and have the device join a new fabric. each fabric joined in this way has the same administrator privileges and can be released from the other fabric's control of the device at any time.

So I have TWO questions:
1. Is there a way to limit the privileges of the administrator (called A) of a new fabric added to the device, such as not letting it remove other fabrics of the device?
2. Is there a way to have a device join a special fabric (called B) while making it impossible for other fabric administrators to see that fabric B exists?(such as using `./chip-tool operationalcredentials read fabrics $nodeid 0 --fabric-filtered false` and then can not see fabric B)

I have read the matter documentation but have not found an idea. Thank you very much!

**Comment by bzbarsky-apple** [comment]
> Is there a way to limit the privileges of the administrator (called A) of a new fabric added to the device

From a different fabric?  No.  The new administrator can limit itself, of course.

> Is there a way to have a device join a special fabric (called B) while making it impossible for other fabric administrators to see that fabric B exists?

No.
