### ISSUE TITLE
[Question] ESP32 device type recognition HomeApp 

### ISSUE THREAD

**Issue by BartJozwicki** [project-chip/connectedhomeip#30237]
### Reproduction steps

I am not sure where to post this questions so sorry if I labelled it incorrectly. 

I am building a smart light using ESP32-H2, I have my code working based on light-app example, I can control brightness of the light using sliders in the HomeAPP (iOS) but I would like to have only one slider present in the HomeApp rather than 6 different colours from the RGBW example. Could you please point me to the parts of code or some documentation where I can solve that? I suppose there is some kind of identifier in the code that sends information to the HomeApp but I have a hard time finding it. Thank you for help. 

### Platform

esp32

### Type

Platform validated

**Comment by dhrishi** [comment]
@BartJozwicki Can you please provide the details about the example you are using, is it the lighting-app? Also, any screenshots from the Home app would help

**Comment by BartJozwicki** [comment]
> @BartJozwicki Can you please provide the details about the example you are using, is it the lighting-app? Also, any screenshots from the Home app would help

I am using Lighting-app as my template yes.

Sure that is the view from my HomeApp:

![MicrosoftTeams-image](https://github.com/project-chip/connectedhomeip/assets/108279543/497f86a1-3cd8-4d29-a90a-deaa7b92b8e8)

My goal is to have only one of the sliders for brightness (at the moment you can see 6 different colours)

**Comment by bzbarsky-apple** [comment]
@BartJozwick Make sure the device type does not say "color light" on the endpoint in ZAP, and disable the color control cluster on that endpoint.

**Comment by BartJozwicki** [comment]
> @BartJozwick Make sure the device type does not say "color light" on the endpoint in ZAP, and disable the color control cluster on that endpoint.

I have changed the lighting-app.zap as suggested:
(enable color control: 0)

![Color controlDisable](https://github.com/project-chip/connectedhomeip/assets/108279543/842ae325-5c78-40b0-8d36-03a009fb9c98)

Device says Dimmible Light:

![name](https://github.com/project-chip/connectedhomeip/assets/108279543/3ee7de34-cb50-4ca8-bff8-48e852772476)

After changes I have deleted build files in the lighting-app and used idf.py build
I get the following errors when building the file:

![Screenshot 2023-11-08 at 11 14 06](https://github.com/project-chip/connectedhomeip/assets/108279543/95a44e1e-9c7b-40a3-b124-c29f9855d531)


Could you please advise what is wrong ?

**Comment by bzbarsky-apple** [comment]
See https://github.com/project-chip/connectedhomeip/issues/30324#issuecomment-1802270280
