### ISSUE TITLE
[QUESTION] How to integrate Matter linux App with another process without named pipes?

### ISSUE THREAD

**Issue by BurievSardor** [project-chip/connectedhomeip#30233]
We have a custom thermostat application based on Qt. We are thinking how to integrate our Qt based application with Matter linux thermostat. Named pipes are not a good option for us. 
Can we run Matter linux application as Http Server? If it is so, then how it is done?

**Comment by bzbarsky-apple** [comment]
> Can we run Matter linux application as Http Server?

Not out of box.  You can, of course, modify it, and even contribute these modifications back....
