### ISSUE TITLE
[Scenes] Apply attributes fix once Zigbee legacy is removed in Spec

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#30256]
Once the fixes from https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7910 are applied, the implementation needs to be modified accordingly.

**Comment by lpbeliveau-silabs** [comment]
Once the fixes from https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/7910 are applied, the implementation needs to be modified accordingly.

**Comment by bzbarsky-apple** [comment]
@lpbeliveau-silabs If we don't, we can't make the change after 1.3.  The issue above is a ballot comment for the spec release corresponding to 1.3....
