### ISSUE TITLE
[CERT-TEST-FAILURE] 

### ISSUE THREAD

**Issue by zacwbond** [project-chip/connectedhomeip#30255]
### Feature Area

Area:Scenes

### Test Case

S.S.C03.Rsp(RemoveAllScenes)

### Reproduction steps

v1.2.0.0 of the spec lists the `LastConfiguredBy` attribute of the `Scenes` cluster as optional, but if the DUT does not support this attribute, S.S.C03.Rsp (RemoveAllScenes) and many other tests will fail because the DUT will respond with `Unsupported Attribute`.   If I add `LastConfiguredBy`, the error goes away.

Should `LastConfiguredBy` be removed from `all-clusters-minimal-app`?

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

v1.2.0.0

### Platform

esp32

**Comment by lpbeliveau-silabs** [comment]
At first glance it looks like the scenes cluster implementation is enforcing this attribute regardless of the DUT configuration.
I'll look into it shortly to address this.
