### ISSUE TITLE
[1.3] The implementation of the Water Heater Management Cluster is missing in chip-tool

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#30268]
### Reproduction steps

1. Executed the below mentioned command to put DUT into a commissionable state
./chip-all-clusters-app
2. Once DUT reach the commissionable state sent below mentioned command on TH.
./chip-tool pairing onnetwork 1 20202021

3. After the successful commissioning, I attempted to validate the Water Heater Management Cluster , but it is not implemented in chip-tool
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/570057f0-257a-4001-a25e-cfa300ed9894)

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

 24d38dac1000c0e57143a2a481268ecbcd398138 

### Platform

raspi

### Type

Test Improvement

### Anything else?

**Spec Reference :**
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/WaterHeaterManagement.adoc

**Comment by ReneJosefsen** [comment]
Water Heater is, despite the similarity in naming, currently not a part of the Water Management effort. Removing it from the project.
