### ISSUE TITLE
[1.3] The implementation of the Demand Response Load Control Cluster is required

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#30273]
### Reproduction steps

1. Executed the below mentioned command to put DUT into a commissionable state
./chip-all-clusters-app

2. Once DUT reach the commissionable state sent below mentioned command on TH.
./chip-tool pairing onnetwork 1 20202021

3. After the successful commissioning, I attempted to validate the Demand Response Load Control Cluster, but it is not implemented in chip-tool
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/0c728148-357f-47cf-a75e-1e4726e1a299)

### Bug prevalence

  Whenever I do

### GitHub hash of the SDK that was being used

24d38dac1000c0e57143a2a481268ecbcd398138

### Platform

raspi

### Type

Test Improvement

### Anything else?

**Spec Reference :** 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/DemandResponseLoadControl.adoc

**Comment by jamesharrow** [comment]
Believe that this is now in the SDK.
@bzbarsky-apple ?

**Comment by bzbarsky-apple** [comment]
Yes, chip-tool has this now.
