### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by BartJozwicki** [project-chip/connectedhomeip#30324]
### Build issue(s)

I have stated my initial question here: https://github.com/project-chip/connectedhomeip/issues/30237 but it was closed before I could test the proposed solution so I opened it as a new issue. 

I have changed the lighting-app.zap as suggested to only have one slider in the HomeApp IOs for dimming rather than 6 for different colors  by default in lighting-app):

(enable color control: 0)

![Color controlDisable](https://github.com/project-chip/connectedhomeip/assets/108279543/5d4a0ac4-913d-4237-8ed1-d40bd9afa99e)

that was my initial change which didn't help I then dowloaded ZAP GUI and opened lighting-app.zap using it and regenerated .zap then I run script to regenerate new .matter file. I put it in connectedhomeip/examples/lighting-app/light-common

Device says Dimmible Light in ZAP file:

![name](https://github.com/project-chip/connectedhomeip/assets/108279543/e239f578-3c41-4b44-9040-9e12b30825f8)

After above changes I have deleted build files in the lighting-app and used idf.py build

I get the following errors when building the file:

![errors](https://github.com/project-chip/connectedhomeip/assets/108279543/cc4fec2c-5fee-413c-9fef-f43b431ca499)

I thought that should not be considered anymore as I disabled colourcontrol? 
Could you please advise what is wrong ?

### Platform

esp32

**Comment by bzbarsky-apple** [comment]
`examples/lighting-app/esp32/main/CMakeLists.txt` has:

```
                     "${CMAKE_SOURCE_DIR}/third_party/connectedhomeip/src/app/clusters/color-control-server"
```

which will unconditionally try to compile the color control server.  This needs to be changed if you change the ZAP config, no?
