### ISSUE TITLE
How do I use CHIP-TOOL to remove a Zigbee (non-matter device) device connected to a matter bridge paired with CHIP-TOOL?

### ISSUE THREAD

**Issue by whqxbs** [project-chip/connectedhomeip#30336]
### Build issue(s)

I paired the matter bridge using an app and later connected a Zigbee thermometer device with the help of the bridge in the app. After that I shared the bridge to CHIP-TOOL via matter using the app and I connected a Zigbee thermometer device with the help of the bridge in CHIP-TOOL using `. /chip-tool descriptor read device-type-list 1020 4` and other commands to successfully see the presence of the Zigbee thermometer.

Now I want to use CHIP-TOOL to unpair the bridge with the Zigbee device, but at the same time I want to keep CHIP-TOOL paired with the bridge. I didn't find the right command, what should I do?

Thank you very much and looking forward to your answer!

**Comment by bzbarsky-apple** [comment]
chip-tool can only do Matter things.  You're asking for a way to affect the Zigbee network, which Matter has no way of doing.
