### ISSUE TITLE
[1.3] ICD Management Cluster XML has to be updated as per spec 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#30357]
**Description**
1. XML should remove the attributes which are not available in spec those are
UserActiveModeTriggerHint
UserActiveModeTriggerInstruction

**PFA XML Screenshot :** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/be99d391-dba7-4280-b612-1d98048305bb)

**PFA Spec Screenshot** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/c1875684-ae53-477b-a7e3-df93a0c9825d)

2. below mentioned command is missed to define in xml
StayActiveResponse

**Spec Reference :** 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/ICDManagement.adoc

**XML Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/icd-management-cluster.xml

**Comment by mkardous-silabs** [comment]
@Rajashreekalmane The attribute are in the spec but they are behind the in-progress field since they are aimed for 1.3.
The github does not show them; Check the code directly.

**Comment by mkardous-silabs** [comment]
Reopened since the StayActiveRespone is missing.
