### ISSUE TITLE
[1.3] Relative Humidity Measurement XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#30366]
### Description:

- [ ] **"MeasuredValue" attribute Min and Max range is not defined in XML.**

**Spec Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/92d30a8c-b9dc-4aae-a32c-bc7f35c93e11)

**XML Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/d683a3a7-1de4-4ec8-8c3e-f35949b87cf3)

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/WaterContentMeasurement.adoc#4-attributes

**XML Reference:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/relative-humidity-measurement-cluster.xml

**Comment by bzbarsky-apple** [comment]
XML has no way to define non-constant min and max, and more importantly there is no reason to list min and max for non-writable attributes in XML: it's not used.
