### ISSUE TITLE
[1.3] Occupancy Sensing Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#30364]
### Description:

- [x]  **"OccupancySensorType" attributes max range has to be updated as per spec in XML.**

**XML Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/77792111-f865-4c5b-b94c-091bc667c377)

**Spec Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/2e0c364a-8cde-4818-91f5-85863dfeb8f3)

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OccupancySensing.adoc#43-occupancysensortypeenum-type

**XML Reference:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/occupancy-sensing-cluster.xml

**Comment by tcarmelveilleux** [comment]
No longer relevant from last cluster revision that has addditional tests to cover this.
