### ISSUE TITLE
[1.3] Descriptor Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#30369]
### Description:

- [ ]  **In  SemanticTagStruct, "NamespaceID" and "Tag"  fields  data type is wrong in XML. It has to be updated as per Spec.**

**Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/41f0b522-571b-4279-8b01-9397b8d517be)

- [ ]  **"DeviceTypeList" attribute Constraint should to be added in XML.**

**Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/0bf6f907-1c30-413f-991f-7f627ac0a8a7)

![image](https://github.com/project-chip/connectedhomeip/assets/98016634/40d5bebc-bf7c-4aeb-ac5d-10fcda4dac7b)

- [ ]  **"TagList" attribute min range is not defined in XML.**

**Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/75e033f6-8083-4468-ae91-14f03617642b)

![image](https://github.com/project-chip/connectedhomeip/assets/98016634/6e3b4cc1-8e52-43b5-86d2-b73977fc43e7)

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/data_model/Descriptor-Cluster.adoc#6-attributes

**XML Reference:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/descriptor-cluster.xml

**Comment by bzbarsky-apple** [comment]
* There are no "namespace" or "tag" types in ZAP XML.
* There are no list length constraints in ZAP XML.
