### ISSUE TITLE
[1.3] Unit Localization Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#30378]
### Description:

- [ ]  **In XML Default value and  Access are not defined for "TemperatureUnit" attribute.**

**Screenshot:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/085f3aee-4da2-46cc-9b32-14ea9579f4a6)

![image](https://github.com/project-chip/connectedhomeip/assets/98016634/00abd911-8038-4a72-bdf2-c149ae02bb0a)

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/LocalizationUnit.adoc#6-attributes

**XML Reference:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/unit-localization-cluster.xml

**Comment by bzbarsky-apple** [comment]
Default in XML is unrelated to default in spec.

The Manage thing is fixed in https://github.com/project-chip/connectedhomeip/pull/29960
