### ISSUE TITLE
[1.3] Temperature Control Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#30375]
### Reproduction steps

1. for Below mentioned attributes, constraints are missed to define in XML file

- TemperatureSetpoint
- MinTemperature
- Step
- SelectedTemperatureLevel
- SupportedTemperatureLevels

**PFA XML Screenshot :** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/6c2a17bf-8d4f-4380-a99a-fcf316dd4f3a)

**PFA spec screenshot** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/3be2a9ce-c641-4f24-ae98-8bb23fd37900)

**XML Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/temperature-control-cluster.xml

**Spec Reference** 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/TemperatureControl.adoc#attributes

**Comment by bzbarsky-apple** [comment]
@Rajashreekalmane Constraints for readonly attributes are ignored in XML, so don't matter.  And the XML has no way to express most of the constraints this cluster defines anyway.
