### ISSUE TITLE
[1.3] Pressure Measurement Cluster  XML has to be updated as per spec

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#30371]
**Description :**
Constraints are not defined for MeasuredValue, MinMeasuredValue, MaxMeasuredValue, Scale, ScaledValue, MinScaledValue and MaxScaledValue in XML.

**PFA XML Screenshot :** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/920ffbf4-f2a2-4aa9-bbbc-5cbb654f5815)

**Spec Screenshot :** 
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/4fea9a08-6981-41e2-9d9f-3d1c99fc5e3b)

**PFA Spec Reference :** 
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/PressureMeasurement.adoc#attributes

**PFA XML Reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/pressure-measurement-cluster.xml

**Comment by bzbarsky-apple** [comment]
Constraints for readonly attributes are ignored in ZAP XML.

**Comment by bzbarsky-apple** [comment]
And non-constant constraints are not expressible anyway.
