### ISSUE TITLE
[1.3] Time Format Localization Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#30380]
### Description:
- [ ] **Default value is not defined in XML for below mentioned attributes.** 
- HourFormat,
- ActiveCalendarType

**Screenshot**:
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/b47f8905-9895-4ec6-a78e-54809f9ffcbf)

![image](https://github.com/project-chip/connectedhomeip/assets/98016634/2c4402cb-0487-4383-b1ae-3546468da413)

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/LocalizationTimeFormat.adoc#6-attributes

**XML Reference:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/time-format-localization-cluster.xml

**Comment by bzbarsky-apple** [comment]
There is no way to indicate a null default in ZAP XML.
