### ISSUE TITLE
[Build] Matter Linux Air Quality Example build issue

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#30394]
## [Build] Matter Linux Air Quality Example build issue

1. FAILED: obj/third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-app.air-quality-sensor-manager.cpp.o

**Steps to reproduce**

1. switch to commit 699ff65e065a28e4b7ee3a2d84110444b1709040
2. cd connectedhomeip
3. cd examples/air-quality-sensor-app/linux
4. gn gen out/debug
5. ninja -C out/debug

### Platform

core (please add to version below)

### Anything else?

    FAILED: obj/third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-app.air-quality-sensor-manager.cpp.o

**More details**

[air-quality-sensor-app.log](https://github.com/project-chip/connectedhomeip/files/13312515/air-quality-sensor-app.log)

    
    user@matter-vm:~/matter-10-2023/esp-matter/connectedhomeip/connectedhomeip/examples/air-quality-sensor-app/linux$ gn gen out/debug
     1891  ninja -C out/debug
    Done. Made 261 targets from 219 files in 485ms
    user@matter-vm:~/matter-10-2023/esp-matter/connectedhomeip/connectedhomeip/examples/air-quality-sensor-app/linux$  ninja -C out/debug
    ninja: Entering directory `out/debug'
    [1/105] c++ obj/third_party/connectedhomeip/examples/air-quality-sen...r-common/src/air-quality-sensor-app.air-quality-sensor-manager.cpp.o
    FAILED: obj/third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-app.air-quality-sensor-manager.cpp.o
    g++ -MMD -MF obj/third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-app.air-quality-sensor-manager.cpp.o.d -Wconversion -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow -Wunreachable-code -Wvla -Wformat -Wformat-nonliteral -Wformat-security -Wno-deprecated-declarations -Wno-missing-field-initializers -Wno-unknown-warning-option -Wno-unused-parameter -Wno-cast-function-type -Wno-psabi -Wno-maybe-uninitialized -fdiagnostics-color -fno-strict-aliasing -fmacro-prefix-map=../../third_party/connectedhomeip/= -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wno-format-nonliteral -Wno-format-nonliteral -std=gnu++17 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -DCHIP_ADDRESS_RESOLVE_IMPL_INCLUDE_HEADER=\<lib/address_resolve/AddressResolve_DefaultImpl.h\> -DCHIP_MINMDNS_USE_EPHEMERAL_UNICAST_PORT=1 -DCHIP_MINMDNS_HIGH_VERBOSITY=0 -DCHIP_MINMDNS_DEFAULT_POLICY=1 -I../../include -I../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/include -I../../third_party/connectedhomeip/zzz_generated/air-quality-sensor-app -Igen/third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common -Igen/third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/zapgen -I../../third_party/connectedhomeip/src/include -I../../third_party/connectedhomeip/src -Igen/include -I../../third_party/connectedhomeip/zzz_generated/app-common -I../../third_party/connectedhomeip/examples/air-quality-sensor-app/linux/include -I../../third_party/connectedhomeip/config/standalone -I../../third_party/connectedhomeip/third_party/nlassert/repo/include -I../../third_party/connectedhomeip/third_party/nlio/repo/include -I../../third_party/connectedhomeip/third_party/inipp/repo/inipp -I../../third_party/connectedhomeip/src/tracing/perfetto/include -I../../third_party/connectedhomeip/third_party/perfetto/repo/sdk -I../../third_party/connectedhomeip/examples/platform/linux -I../../third_party/connectedhomeip/third_party/jsoncpp/repo/include -c ../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-manager.cpp -o obj/third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-app.air-quality-sensor-manager.cpp.o
    In file included from ../../third_party/connectedhomeip/src/lib/support/CodeUtils.h:32,
                     from ../../third_party/connectedhomeip/src/lib/core/CASEAuthTag.h:25,
                     from ../../third_party/connectedhomeip/src/access/SubjectDescriptor.h:23,
                     from ../../third_party/connectedhomeip/src/app/AttributeAccessInterface.h:21,
                     from ../../third_party/connectedhomeip/src/app/clusters/air-quality-server/air-quality-server.h:21,
                     from ../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/include/air-quality-sensor-manager.h:3,
                     from ../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-manager.cpp:1:
    ../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-manager.cpp: In member function ‘void chip::app::Clusters::AirQualitySensorManager::OnAirQualityChangeHandler(chip::app::Clusters::AirQuality::AirQualityEnum)’:
    ../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-manager.cpp:140:33: error: format ‘%hu’ expects argument of type ‘int’, but argument 4 has type ‘chip::app::Clusters::AirQuality::AirQualityEnum’ [-Werror=format=]
      140 |     ChipLogDetail(NotSpecified, "Updated AirQuality value: %huu", newValue);
          |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~
          |                                                                   |
          |                                                                   chip::app::Clusters::AirQuality::AirQualityEnum
    ../../third_party/connectedhomeip/src/lib/support/logging/CHIPLogging.h:448:70: note: in definition of macro ‘ChipInternalLogImpl’
      448 |             chip::Logging::Log(chip::Logging::kLogModule_##MOD, CAT, MSG, ##__VA_ARGS__);                                          \
          |                                                                      ^~~
    ../../third_party/connectedhomeip/src/lib/support/logging/CHIPLogging.h:134:38: note: in expansion of macro ‘ChipInternalLog’
      134 | #define ChipLogDetail(MOD, MSG, ...) ChipInternalLog(MOD, DETAIL, MSG, ##__VA_ARGS__)
          |                                      ^~~~~~~~~~~~~~~
    ../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-manager.cpp:140:5: note: in expansion of macro ‘ChipLogDetail’
      140 |     ChipLogDetail(NotSpecified, "Updated AirQuality value: %huu", newValue);
          |     ^~~~~~~~~~~~~
    ../../third_party/connectedhomeip/examples/air-quality-sensor-app/air-quality-sensor-common/src/air-quality-sensor-manager.cpp:140:62: note: format string is defined here
      140 |     ChipLogDetail(NotSpecified, "Updated AirQuality value: %huu", newValue);
          |                                                            ~~^
          |                                                              |
          |                                                              int
    At global scope:
    cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
    cc1plus: all warnings being treated as errors
    [3/105] c++ obj/air-quality-sensor-app.main.cpp.o
    ninja: build stopped: subcommand failed.
    user@matter-vm:~/matter-10-2023/esp-matter/connectedhomeip/connectedhomeip/examples/air-quality-sensor-app/linux$

**Comment by bzbarsky-apple** [comment]
> switch to commit https://github.com/project-chip/connectedhomeip/commit/699ff65e065a28e4b7ee3a2d84110444b1709040

Yes, that's sort of old.  This was fixed in #30057.
