### ISSUE TITLE
[Scenes] Removing mNameLenght form SceneData in SceneTableImpl

### ISSUE THREAD

**Issue by lpbeliveau-silabs** [project-chip/connectedhomeip#30401]
We need to remove mNameLength and ensure trailing null character removal.

Also, if https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/8022 is accepted, we can move to determine end of string with null terminators.

**Comment by lpbeliveau-silabs** [comment]
See https://github.com/project-chip/connectedhomeip/pull/30393#discussion_r1388596042 (and the remainder of the PR)

**Comment by bzbarsky-apple** [comment]
The issue is not "trailing null character" so much as "you should be returning the strings you actually have, not something that includes extra garbage", no?

And no, you cannot move to determining end of string "with null terminators" for a data model string (i.e. CharSpan) someone hands you.

**Comment by andy31415** [comment]
Technically including a null inside a string is allowed by the spec (you can have inside null, just no null at the end ... fun... I complained in the spec about this).

**Comment by lpbeliveau-silabs** [comment]
Given the comments above, I am closing the issue.
