### ISSUE TITLE
[Build] How to further reduce the size of the output binary?

### ISSUE THREAD

**Issue by AllsVoid** [project-chip/connectedhomeip#30442]
Hi guys~
I use the **lighting-app** demo to compile the app. The output binary size is still a bit large after stripping. 
Is there any way to further reduce the size?

### Environment:
- Ubuntu20.04
- Host: x86_64
- Target: 32bit devices

### Compile steps
- Enter examples/lighting-app/linux
- gn gen out/debug && ninja -C out/debug
- strip output binary
The binary size : 46M -> 2.6M

But i want to run this app on a memory-limited device.

What should I do further to reduce the size of the program? (eg: only keep the protocol processing part of the program?)

**Comment by bzbarsky-apple** [comment]
@AllsVoid Compiling with `-Os` might be a good start.  I doubt that's happening by default on Linux.

**Comment by AllsVoid** [comment]
> @AllsVoid Compiling with `-Os` might be a good start. I doubt that's happening by default on Linux.

It works, thank you~
The final binary size:  1.3M

**Comment by yf-fan-org** [comment]
> > @AllsVoid Compiling with `-Os` might be a good start. I doubt that's happening by default on Linux.
> 
> It works, thank you~ The final binary size: 1.3M

Can you tell me how to set the parameters?

**Comment by AllsVoid** [comment]
> > > @AllsVoid Compiling with `-Os` might be a good start. I doubt that's happening by default on Linux.
> > 
> > 
> > It works, thank you~ The final binary size: 1.3M
> 
> Can you tell me how to set the parameters?

You may find the compile config file to add/modify to  "-Os" parm, however it's been too long that i forgot which file needs to be modified…… sorry

**Comment by yf-fan-org** [comment]
> > > > @AllsVoid Compiling with `-Os` might be a good start. I doubt that's happening by default on Linux.
> > > 
> > > 
> > > It works, thank you~ The final binary size: 1.3M
> > 
> > 
> > Can you tell me how to set the parameters?
> 
> You may find the compile config file to add/modify to "-Os" parm, however it's been too long that i forgot which file needs to be modified…… sorry

thanks very much
