### ISSUE TITLE
In `PairingSession::EncodeSessionParameters` figure out what MRP values we should sent when `providedMrpConfig.HasValue() == false`

### ISSUE THREAD

**Issue by tehampson** [project-chip/connectedhomeip#30456]
Based on the spec `For backwards compatibility, if any tag after tag 2 (SESSION_ACTIVE_INTERVAL) is present, then the SESSION_ACTIVE_INTERVAL SHALL also be present.`

The spec really doesn't define what should happen if we don't have a local config. The other side would assume `GetDefaultMRPConfig()`. But it is not entirely clear if these are the same values on both side

**Comment by bzbarsky-apple** [comment]
The real question is this: under what conditions would we not have a local config?
