### ISSUE TITLE
[BUG] The command handler state tracking does not work properly for the groupcast messages.

### ISSUE THREAD

**Issue by kkasperczyk-no** [project-chip/connectedhomeip#30472]
### Reproduction steps

The `DispatchCommand` is called the same way for both groupcast and unicast scenarios: `mpCallback->DispatchCommand(*this, concretePath, dataReader);` and it doesn't pass the information about the originator of this call. It results in attempts of updating the status (with `AddStatus` method) for the invoking response purposes.

For the groupcast scenario updating status does not make sense, as response will not be sent anyway and additionally it leads to the application being killed if more than one endpoint existing on a single Matter node was added to the same group.
In such case receiving the groupcast command invokes the status update, which works well for the first endpoint from a list, but it fails for the following ones on a following check: `VerifyOrDie(FallibleAddStatus(aCommandPath, aStatus, context) == CHIP_NO_ERROR);`

This issue affects all devices that would like to configure single group on more than one endpoint within the single Matter node and also bridge devices that may represent several different bridged devices belonging to a single group.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

Tested with 181b0cb14ff007ec912f2ba6627e05dfb066c008, but it applies to master as well.

### Platform

core

### Platform Version(s)

All

### Anything else?

The potential solution could be adding `isGroupcastInvoked`-like boolean flag to the `DispatchCommand` method, forward it up to the `AddStatus` call and then conditionally return without updating the status in case of groupcast scenario.

**Comment by tehampson** [comment]
I think [the suggestion that was proposed in slack](https://csamembers.slack.com/archives/G014G30SVV0/p1699976731844579?thread_ts=1699971396.191729&cid=G014G30SVV0) is instead of plumbing a flag through `CommandHandler::DispatchCommand` all the way back to `CommandHandler::AddStatus`. That you just indicate through some state variable in `CommandHandler` that we are handling a group command and that way it gets dropped once `CommandHandler::AddStatus` is called

**Comment by kkasperczyk-no** [comment]
TODO: Add yaml tests covering the scenario of using multiple endpoints belonging to the same group and existing on a single Matter node.
