### ISSUE TITLE
[1.2] Thermostat not working with Apple Home when it's on the same node as a bridge

### ISSUE THREAD

**Issue by WOLEN6914183** [project-chip/connectedhomeip#30481]
### Reproduction steps

"I added a non-bridged thermostat to endpoint 2 in the 'zap' file under 'example/bridge-app'. I can read the content of the thermostat on the Raspberry Pi, and it also appears on Google Home as an accessory. However, when I add it to Apple HomeKit, the thermostat accessory is not discovered. Is this an issue on Apple's side or a matter SDK problem? Please note that the thermostat's properties in the 'zap' file are correct, and the same configuration works fine in another example, 'light-switch-app'."

### Bug prevalence

1-2 times week

### GitHub hash of the SDK that was being used

181b0cb14ff007ec912f2ba6627e05dfb066c008

### Platform

esp32

### Platform Version(s)

Homekit

### Type

Platform Issue

### Anything else?

![Uploading WechatIMG190.jpg…]()

**Comment by bzbarsky-apple** [comment]
@WOLEN6914183 I am happy to try to help, but see above for the information I will need.
