### ISSUE TITLE
[1.3][ICD] Add Helper to find subscription with a CAT tag OR a NodeId

### ISSUE THREAD

**Issue by jepenven-silabs** [project-chip/connectedhomeip#30553]
ICD Check-In Protocol allows Monitored subject to be a CaseAuthenticatedTag in order to retrieve a subscription. However it seems like we do not store any CAT tag within the read handler. Making it impossible to find a subscription from a CAT tag.

**Comment by bzbarsky-apple** [comment]
Doesn't the read handler have a session?  The session knows about the CATs of the other side, no?  @jepenven-silabs

**Comment by bzbarsky-apple** [comment]
In particular, see https://github.com/project-chip/connectedhomeip/blob/dca427168edd52b958c6d21cd1290e516b32a8cf/src/app/ReadHandler.h#L401 and https://github.com/project-chip/connectedhomeip/blob/dca427168edd52b958c6d21cd1290e516b32a8cf/src/access/SubjectDescriptor.h#L43-L44

**Comment by mkardous-silabs** [comment]
This was resolved with #30526
