### ISSUE TITLE
[Build] Is there a javascript/typescript version of the light-switch example program?

### ISSUE THREAD

**Issue by whqxbs** [project-chip/connectedhomeip#30578]
### Build issue(s)

Dear,

I initially used the ESP32 example program in `connectedhomeip/examples/light-switch-app` with acl and binding cluster to implement the ESP32 development board to control the light on/off. But because of some problems ESP32 physical device is not very convenient for my debugging, so I want to use matter.js(javascritp/typescript) project to generate virtual switch and light so that it is more convenient to carry out related tests.

I found `DeviceNode.ts` is the sample program for the light, but I didn't find the sample program for the switch, where can I get it please? Or is there any good brother who has implemented the matter.js code for this switch and could you share it for me? Thanks a lot!

Thanks and looking forward to your replies!

**Comment by bzbarsky-apple** [comment]
There is no such thing that I am aware of... Certainly nothing in the Matter tree.
