### ISSUE TITLE
[NXP] Layering inversion in ConfigurationmanagerImpl.cpp

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#30599]
We have:

```
src/platform/nxp/common/ConfigurationManagerImpl.cpp
30:#include <app/server/Server.h>
```

It is not ok for something inside Platform to depend On app - this inverts layering as platform is supposed to be the lowest level and app is one of the highest levels. Generally GN would prevent this however app is excluded from layering checks because of legacy code. We should fix these layering inversions.

Found while checking #30596

**Comment by andy31415** [comment]
It looks like the reason this is done is for `Server::GetInstance().GetFabricTable().DeleteAllFabrics();`.
We should figure out some eventing system and pass this into app rather than having platform calling directly into server.

**Comment by marius-alex-tache** [comment]
@dinabenamar
