### ISSUE TITLE
[Documentation] Configure key for universal groups missing in Commissioning flow

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#30593]
### Documentation issues

In Matter Specs it says in "2.5.4.1. Universal Group ID":

> The Commissioner SHALL configure one or more shared keys for these groups on all Nodes within the Fabric.

But the commissioning flow sections like 2.8 do not include this at all ... 

### Platform

other

### Anything else?

Additionally: I'm not sure if this is implemented at all, because no controller wad doing this from my observations. Or is any compile flag needed to enable it?

Additionally it would be great to get clarification what that above sentence exactly means? 

My interpretation would be: "generate one key (ok one key-set formally with 1-3 epoch keys) and register this one keySet for the three group ids 0xFFFF, 0xFFFE and 0xFFFD during commissioning... right? I assume this means "shared key"?

**Comment by bzbarsky-apple** [comment]
This is not implemented at all, and actually _can't_ be implemented because a server might only support one group key (for the IPK) per "2.11.1.2. Group Limits".  Filed https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/8647

**Comment by Apollon77** [comment]
Hm ... but I think the basic requirement always having keys available for the Universal group IDs is not wrong ... and if  groups are supported by any endpoint then is maybe still "SHALL" be done by the comissioner ... kind of with the same rules like in general "enabling groups" logic.

But ok for now good to k ow so I will not implement it. Thank you!

**Comment by bzbarsky-apple** [comment]
> but I think the basic requirement always having keys available for the Universal group IDs is not wrong

It's wrong.  If admins want to do group communication via that group, then they can provide a key (assuming devices have the space for it, which they might not).  If not, why should they provide one?

> Additionally can you please also make sure the text is made clear about what should be done

For a commissioner?  Nothing.  You have to send an IPK in AddNOC; any other group key bits are up to you.

**Comment by Apollon77** [comment]
Ok then I get it now ... so the sentence should simply be removed completely then and not only the SHALL should be replaced, because then anything is as "for any other group id" ... if group controller wants to use them it dows the same as for any other own defined group.

**Comment by bzbarsky-apple** [comment]
That is at least my opinion, yes.

**Comment by Apollon77** [comment]
Thank you for your support, so lets see how it gets changed in 1.3 specs then ;-))

**Comment by Apollon77** [comment]
@bzbarsky-apple seems nothing changed regarding this in Matter 1.3 ...

**Comment by Apollon77** [comment]
Thank you for following up. As you know I have no access to these "internals".

**Comment by bzbarsky-apple** [comment]
Yes, I know.  It's no less annoying to me than to you.
