### ISSUE TITLE
[1.3] Microwave Oven Control Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#30818]
### Description
**XML has to be updated as per spec:**

- Min and Max value has to be added for CookTime, MinPower, MaxPower, PowerStep attributes.
- In AddMoreTime command, the Min and Max value has to be added for TimeToAdd field.

**Specification Reference:** https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/MicrowaveOvenControl.adoc

**Comment by liangpy4** [comment]
Adding min/max values for MicrowaveOven attributes don't mean anything in the XML, the min/max attributes value of this cluster are controlled by the SDK now, please consider to close this issue.

**Comment by KishokG** [comment]
As per the above comment. Closing the Issue.
