### ISSUE TITLE
[1.3] Demand Response Load Control Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#30815]
**Description :**

- [ ] While defining the 'LoadControlEventStatusChange' event field, there was a miss in defining the mandatory 'Signature' field.

![image](https://github.com/project-chip/connectedhomeip/assets/95841834/d48f0376-df36-4478-a7b8-a6669cbdbef2)

![image](https://github.com/project-chip/connectedhomeip/assets/95841834/2ce02686-dc12-40cd-b5e6-7c9f236759e2)

**PFA XML Reference** 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/drlc-cluster.xml

**Comment by bzbarsky-apple** [comment]
That field is removed in the outstanding spec PRs that should be landing soon.
