### ISSUE TITLE
[BUG] Storing active mode trigger hint information along with check-in keys does not make sense

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#30842]
### Reproduction steps

https://github.com/project-chip/connectedhomeip/pull/30770 added some code that assumes that the check-in recipient is the entity that will communicate with the user to let them know how to put the ICD into active mode if the user needs it in active mode "now".

This is not a valid assumption; these can generally be different entities.

What probably makes the most sense is making sure that during commissioning the hint information is communicated to the SDK client; they can then decide how and whether to store it and what entities should have it.  But having it stored along with the check-in key on the check-in recipient does not really make sense.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

master

### Platform

core

**Comment by yunhanw-google** [comment]
reverted https://github.com/project-chip/connectedhomeip/pull/30850/files, and would go with callback which can pass hint information is communicated to the SDK client;

**Comment by bzbarsky-apple** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/30850
