### ISSUE TITLE
[BUG] Failed to Commission the TV app with the TV casting app.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#30868]
### Reproduction steps

Follow the instructions [here](https://github.com/project-chip/connectedhomeip/blob/master/examples/tv-casting-app/linux/README.md) to run the tv-casting-app against the tv-app.

> [1701945917.240370][9557:9557] CHIP:EM: >>> [E:52842r S:48920 M:143900880 (Ack:201253874)] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
> [1701945917.240406][9557:9557] CHIP:EM: Found matching exchange: 52842r, Delegate: (nil)
> [1701945917.240436][9557:9557] CHIP:EM: Rxd Ack; Removing MessageCounter:201253874 from Retrans Table on exchange 52842r
> [1701945917.242657][9557:9557] CHIP:EM: >>> [E:52844r S:48920 M:143900881] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
> [1701945917.242746][9557:9557] CHIP:EM: Handling via exchange: 52844r, Delegate: 0xaaaace27c798
> [1701945917.242836][9557:9557] CHIP:DMG: InvokeRequestMessage =
> [1701945917.242873][9557:9557] CHIP:DMG: {
> [1701945917.242920][9557:9557] CHIP:DMG: 	suppressResponse = false, 
> [1701945917.242958][9557:9557] CHIP:DMG: 	timedRequest = false, 
> [1701945917.242992][9557:9557] CHIP:DMG: 	InvokeRequests =
> [1701945917.243049][9557:9557] CHIP:DMG: 	[
> [1701945917.243083][9557:9557] CHIP:DMG: 		CommandDataIB =
> [1701945917.243135][9557:9557] CHIP:DMG: 		{
> [1701945917.243171][9557:9557] CHIP:DMG: 			CommandPathIB =
> [1701945917.243226][9557:9557] CHIP:DMG: 			{
> [1701945917.243271][9557:9557] CHIP:DMG: 				EndpointId = 0x0,
> [1701945917.243368][9557:9557] CHIP:DMG: 				ClusterId = 0x30,
> [1701945917.243428][9557:9557] CHIP:DMG: 				CommandId = 0x0,
> [1701945917.243471][9557:9557] CHIP:DMG: 			},
> [1701945917.243528][9557:9557] CHIP:DMG: 			
> [1701945917.243604][9557:9557] CHIP:DMG: 			CommandFields = 
> [1701945917.243660][9557:9557] CHIP:DMG: 			{
> [1701945917.243718][9557:9557] CHIP:DMG: 				0x0 = 0, 
> [1701945917.243766][9557:9557] CHIP:DMG: 				0x1 = 0, 
> [1701945917.243858][9557:9557] CHIP:DMG: 			},
> [1701945917.243901][9557:9557] CHIP:DMG: 		},
> [1701945917.243958][9557:9557] CHIP:DMG: 		
> [1701945917.243991][9557:9557] CHIP:DMG: 	],
> [1701945917.244047][9557:9557] CHIP:DMG: 	
> [1701945917.244082][9557:9557] CHIP:DMG: 	InteractionModelRevision = 11
> [1701945917.244128][9557:9557] CHIP:DMG: },
> [1701945917.244319][9557:9557] CHIP:DMG: AccessControl: checking f=0 a=p s=0xFFFFFFFB00000000 t= c=0x0000_0030 e=0 p=a
> [1701945917.244358][9557:9557] CHIP:DMG: AccessControl: implicit admin (PASE)
> [1701945917.244395][9557:9557] CHIP:DMG: Received command for Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0000
> [1701945917.244561][9557:9557] CHIP:FS: GeneralCommissioning: Received ArmFailSafe (0s)
> [1701945917.244615][9557:9557] CHIP:FS: Fail-safe timer expired
> [1701945917.244669][9557:9557] CHIP:DMG: Command handler moving to [ Preparing]
> [1701945917.244723][9557:9557] CHIP:DMG: Command handler moving to [AddingComm]
> [1701945917.244766][9557:9557] CHIP:DMG: Command handler moving to [AddedComma]
> [1701945917.244866][9557:9557] CHIP:DMG: Decreasing reference count for CommandHandler, remaining 0
> [1701945917.245156][9557:9557] CHIP:EM: <<< [E:52844r S:48920 M:201253876 (Ack:143900881)] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [UDP:[fe80::e65f:1ff:fe49:ae1a%eth0]:5652] --- Type 0001:09 (IM:InvokeCommandResponse)
> [1701945917.245402][9557:9557] CHIP:DMG: Command handler moving to [CommandSen]
> 
> 

### Bug prevalence

whenever I do

### GitHub hash of the SDK that was being used

db06afc6084b26a62259f8561035ca3df23f4fdf

### Platform

raspi

### Anything else?

**PFA logs below :** 

[tc-casting app.txt](https://github.com/project-chip/connectedhomeip/files/13599126/tc-casting.app.txt)
[tv-app.txt](https://github.com/project-chip/connectedhomeip/files/13599128/tv-app.txt)

**Comment by chrisdecenzo** [comment]
I believe this bug was fixed 2 weeks ago (see https://github.com/project-chip/connectedhomeip/issues/30604). Is it possible you are not using top of tree?
