### ISSUE TITLE
CHIPMem.h called from C

### ISSUE THREAD

**Issue by kpschoedel** [project-chip/connectedhomeip#3092]
#### Problem

Part of #2748 All Embedded Device-side Code Needs to Be Scrubbed of Direct Heap Usage

Some C code currently calls malloc-family functions. Replacing these calls with CHIPMem.h
requires that it have an interface callable from C, ideally without adding overhead.

CHIPMem.h fundamentally provides a C-compatible interface, but wraps it in a namespace. The file also includes CHIPError.h, which is not currently C-compatible (again due to namespace).

 #### Proposed Solution

TBD

**Comment by gerickson** [comment]
CHIP isn't / doesn't purport to be a C-compatible stack. Is there any need to provide C APIs for CHIPMem as a result?

**Comment by kpschoedel** [comment]
If CHIP isn't intended to be C-compatible, then I suppose the burden can be on such platform C code to use a wrapper.

**Comment by gerickson** [comment]
> If CHIP isn't intended to be C-compatible, then I suppose the burden can be on such platform C code to use a wrapper.

+1
