### ISSUE TITLE
Add nrf5 version of temperature sensor demo

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3095]
#### Problem
Codesize measurements are quite platform-dependent, because of system libraries, and the esp32 system libraries are fairly big, because there's a lot of headroom on that hardware.  If we're trying to measure a "minimal" number, we should measure on a different platform.

 #### Proposed Solution
Create an nrfconnect version of the temperature measurement app.

**Comment by kkasperczyk-no** [comment]
Is there a reason for it to be marked as TE2 issue? If not please remove the label to have a clear information what else still left to do for TE2.

**Comment by franck-apple** [comment]
Agree. Moving it to TE3.

**Comment by mrjerryjohns** [comment]
Stale.
