### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-BSENCFG-2.1] - Test failure

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#31010]
### Feature Area

Other

### Test Case

TC-BSENCFG-2.1

### Reproduction steps

Command used to execute the testcase is :`python3 TC_BSENCFG_2_1.py --commissioning-method on-network --discriminator 3840 --passcode 20202021  --paa-trust-store-path /credentials/development/paa-root-certs/ --storage-path admin_storage.json`

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

85a48aabbc4e43c433aa4b2d35b2817d611946de

### Platform

python, raspi

### Anything else?

TC-BSENCFG-2.1 testcase is failed with the error:`Error reading <class 'chip.clusters.Objects.BooleanSensorConfiguration'>:<class 'chip.clusters.Objects.BooleanSensorConfiguration.Attributes.AttributeList'>` because the boolean sensor configuration cluster is not implemented in the Sample app(all-clusters-app).

Log:
[tc-bsencfg-2-1.txt](https://github.com/project-chip/connectedhomeip/files/13675053/tc-bsencfg-2-1.txt)

**Comment by ReneJosefsen** [comment]
Given we now have the implementation merged into the SDK, this issue should be fixed. I will close it for now. Given the test case has been renamed I suggest opening a new issue if this reoccurs.
