### ISSUE TITLE
[1.3] The implementation of the Electrical Power Measurement Cluster is required

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#31095]
### Reproduction steps

Executed the below mentioned command to put DUT into a commissionable state
**./chip-all-clusters-app**

Once DUT reach the commissionable state sent below mentioned command on TH.
**./chip-tool pairing onnetwork 1 20202021**

After the successful commissioning, I attempted to validate the Electrical Power Measurement, but it is not implemented in chip-tool.

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

7cbac9130d2b10d6bfdba873129dfbffa294cf8d

### Platform

raspi

### Platform Version(s)

1.3

### Anything else?

**Chip-tool has to be implement for below mentioned Attribute:**

- [ ] ClusterRevision
- [ ]  FeatureMap
- [ ]  AttributeList
- [ ]  AcceptedCommandList
- [ ]  GeneratedCommandList
- [ ] PowerMode
- [ ] Accuracy
- [ ] Ranges
- [ ] Voltage
- [ ] Current
- [ ] ActivePower
- [ ] RMSCurrent
- [ ] RMSPower
- [ ] ApparentPower
- [ ] ReactivePower
- [ ] Frequency
- [ ] HarmonicCurrents
- [ ] HarmonicPhases
- [ ] PowerFactor
- [ ] LineCurrent
- [ ] NeutralCurrent

**Chip-tool has to be implement for below mentioned Events:**

- [ ] MeasurementPeriodRange Event

**Comment by bzbarsky-apple** [comment]
This needs XML added to the SDK.

**Comment by jamesharrow** [comment]
The XML and Cluster was implemented in PR #30389 and is in all-clusters-app
There is a new PR #31622 which enables it with fake test data in the energy-management-app
