### ISSUE TITLE
[1.3] "MaxCookTime"  Mandatory attribute has to be implemented in Chip-tool

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#31107]
### Reproduction steps

Executed the below mentioned command to put DUT into a commissionable state
**./chip-microwave-oven-app**

Once DUT reach the commissionable state sent below mentioned command on TH.
**./chip-tool pairing onnetwork 1 20202021**

After the successful commissioning Send the below command

`./chip-tool microwaveovencontrol read `

![image](https://github.com/project-chip/connectedhomeip/assets/98016634/8d96ae59-3d2b-430b-b48e-bef743b3059a)

**Below mentioned Mandatory attribute has to be implemented in Chip-tool**
- [ ]  MaxCookTime 

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

7cbac9130d2b10d6bfdba873129dfbffa294cf8d

### Platform

raspi

### Platform Version(s)

1.3

### Type

Test Improvement

### Anything else?

**Spec References:**

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/MicrowaveOvenControl.adoc#5-attributes

**Comment by bzbarsky-apple** [comment]
New spec addition.
