### ISSUE TITLE
[1.1] Chip-tool example cross compiling failure with 'MIPS' architecture 

### ISSUE THREAD

**Issue by Shahmeera** [project-chip/connectedhomeip#31124]
### Reproduction steps

I am doing a cross-compile of the chip-tool example with the toolchain(**mipsel-gcc472-glibc216-mips32**) using this syntax below.
>xyz@67679f2-desktop:~/opt/connectedhomeip/examples/chip-tool$` gn gen out --args='target_os="linux" target_cpu="mipsel" is_clang = false sysroot="/opt/mipsel-gcc472-glibc216-mips32"
> import("//build_overrides/build.gni")
> target_cflags=[ "'-Wno-conversion'", "'-Wno-error'", "-DG_SOURCE_FUNC(f)=((GSourceFunc)(void (*)(void)) (f))", "-fdiagnostics-color" ]
> target_ldflags = ["'-lz'", "'-lffi'", "'-lgmodule-2.0'" ]
> custom_toolchain="/home/meera/connectedhomeip/build/toolchain/custom"
> target_cc="/opt/mipsel-gcc472-glibc216-mips32/bin/mipsel-linux-gcc" 
> target_cxx="/opt/mipsel-gcc472-glibc216-mips32/bin/mipsel-linux-g++" 
> target_ar="/opt/mipsel-gcc472-glibc216-mips32/bin/mipsel-linux-ar"'
`

But I am having an error like this: 
>FAILED: obj/BUILD_DIR/gen/include/platform/Linux/dbus/openthread/openthread.introspect.c.o 
/opt/mipsel-gcc472-glibc216-mips32/bin/mipsel-linux-gcc -MMD -MF obj/BUILD_DIR/gen/include/platform/Linux/dbus/openthread/openthread.introspect.c.o.d -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Werror -Wextra -Wshadow -Wunreachable-code -Wvla -Wformat -Wformat-nonliteral -Wformat-security -Wundef -Wno-deprecated-declarations -Wno-missing-field-initializers -Wno-unknown-warning-option -Wno-unused-parameter -Wno-cast-function-type -Wno-psabi -Wno-maybe-uninitialized -fdiagnostics-color --sysroot=/opt/mipsel-gcc472-glibc216-mips32 -fno-strict-aliasing -Wno-conversion -Wno-error -DG_SOURCE_FUNC\(f\)=\(\(GSourceFunc\)\(void\ \(\*\)\(void\)\)\ \(f\)\) -fdiagnostics-color -Wno-unreachable-code -I/opt/mipsel-gcc472-glibc216-mips32/usr/include/gio-unix-2.0 -I/opt/mipsel-gcc472-glibc216-mips32/usr/include/libmount -I/opt/mipsel-gcc472-glibc216-mips32/usr/include/blkid -I/opt/mipsel-gcc472-glibc216-mips32/usr/include/glib-2.0 -I/opt/mipsel-gcc472-glibc216-mips32/usr/lib/x86_64-linux-gnu/glib-2.0/include -std=gnu11  -Igen/include -c gen/include/platform/Linux/dbus/openthread/introspect.c -o obj/BUILD_DIR/gen/include/platform/Linux/dbus/openthread/openthread.introspect.c.o
**mipsel-linux-gcc: error: unrecognized command line option '-fdiagnostics-color'**
mipsel-linux-gcc: error: unrecognized command line option '-fdiagnostics-color'
[7/599] cc obj/BUILD_DIR/gen/include/platform/Linux/dbus/bluez/bluez.DbusBluez.c.o

### Bug prevalence

None

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/releases/tag/v1.1.0.1

### Platform

other

### Type

Test Improvement

**Comment by andy31415** [comment]
Config seems to come  from third_party/pigweed/repo/pw_build/BUILD.gn where pw_build_COLORIZE_OUTPUT seems to control that flag. You could update your args.gni to have `pw_build_COLORIZE_OUTPUT = false`

This may also be a compiler version issue: we test with gcc and clang, however recent versions only.
