### ISSUE TITLE
nrfconnect lock example: ASSERTION FAIL 

### ISSUE THREAD

**Issue by pierredelisle** [project-chip/connectedhomeip#3114]
#### Problem
Sync'ed to: e5ac330f Wed Oct 7 04:44:57 2020

Click on button 2 to trigger lock/unlock action, app log shows the following:

uart:~$ I: Unlock Action has been initiated
**ASSERTION FAIL [!arch_is_in_isr() || ((timeout).ticks == (((k_timeout_t) {})).ticks)] @ WEST_TOPDIR/zephyr/kernel/msg_q.c:118**

E: r0/a1:  0x00000004  r1/a2:  0x00000076  r2/a3:  0x00000001
E: r3/a4:  0x00000000 r12/ip:  0x00000000 r14/lr:  0x00050ca7
E:  xpsr:  0x61000021
E: Faulting instruction address (r15/pc): 0x00073b96
E: >>> ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0
E: Fault during interrupt handling

E: Current thread: 0x20007218 (idle 00)
E: Resetting system

uart:~$ I: nRF5 802154 radio initialized
I: 8 Sectors of 4096 bytes
I: alloc wra: 0, ff0
I: data wra: 0, 0
*** Booting Zephyr OS build v2.3.0-rc1-ncs1-2408-g332206bcad13  ***
I: Init CHIP stack
I: SoftDevice Controller build revision: 
I: 6c 5a 3f 71 f8 d7 7b 90 |lZ?q..{.
I: 44 46 90 6f 71 32 9d 13 |DF.oq2..
I: f1 c0 ce ce             |....    
I: Starting CHIP task
I: Init Thread stack
I: [DL] OpenThread started: OK
I: [DL] Setup PIN code not found; using default: 012345678
I: [IN] New pairing for key 0!!
I: [SVR] Server Listening...
I: [DL] Setup PIN code not found; using default: 012345678
I: [DL] Setup PIN discriminator not found; using default: f00
I: [SVR] SetupPINCode: [12345678]
I: [SVR] SetupQRCode:  [CH:I34DV*-00 0C9SS0]
D: [DL] CHIP task running
D: [DL] In DriveBLEState
I: [DL] Setup PIN discriminator not found; using default: f00
E: [DL] void chip::DeviceLayer::Internal::GenericThreadStackManagerImpl_Zephyr<ImplClass>::_OnCHIPoBLEAdvertisingStart() [with ImplClass = chip::DeviceLayer::ThreadStackD
I: [DL] CHIPoBLE advertising started

**Comment by Damian-Nordic** [comment]
@pierredelisle Yeah, I noticed that too. I've added a PR that should solve the issue.
