### ISSUE TITLE
[1.3] Scenes Cluster XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#31153]
### Description:

- [ ]  In Scenes cluster XML Access(F) are not defined for "FabricSceneInfo" attribute.
- [ ] In RecallScene Command  “TransitionTime” field is mention as Nullable="true", But Spec is not saying about null value.
- [ ]  “EnhancedAddScene”, “CopyScene”  commands Access is missing in XML.
- [ ]  For below commands mentioned as,  isFabricScoped="true" in XML, But spec is not saying about the FabricScoped in Access.
    • CopyScene
    • EnhancedViewScene
    • EnhancedAddScene
    • GetSceneMembership
    • RecallScene
    • StoreScene
    • RemoveAllScenes
    • RemoveScene
    • ViewScene
    • AddScene

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Scenes.adoc#scenes-cluster

**XML Reference:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/scene.xml

**Comment by bzbarsky-apple** [comment]
>  In Scenes cluster XML Access(F) are not defined for "FabricSceneInfo" attribute.

ZAP XML has no way to express "F".

> In RecallScene Command “TransitionTime” field is mention as Nullable="true", But Spec is not saying about null value.

Spec has the X quality, no?  And "1.4.9.12.4. Effect on Receipt" defines what to do with the null value.

> For below commands mentioned as, isFabricScoped="true" in XML, But spec is not saying about the FabricScoped in Access.

The spec says:

> To retain semantic equivalence to earlier versions of the Scenes cluster which were designed prior to the introduction of multiple fabrics, the behavior of fabric-scoping in this cluster replaces use of explicit fabric-scoped access quality with an implicit method.

but the effect is the same, and the XML needs to have that bit to have the spec-required behavior.
