### ISSUE TITLE
[1.3] Electrical Energy Measurement XML has to be updated as per spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#31150]
### Description:

**1. "EphemeralEnergy" Feature is missing in XML file .**

**2. Below mentioned attributes are missing in XML file.**

- [ ] Measured
- [ ] CumulativeEnergyImportedTime
- [ ] CumulativeEnergyExportedTime
- [ ] PeriodicEnergyImportedStartTime
- [ ] PeriodicEnergyImportedEndTime
- [ ] PeriodicEnergyExportedStartTime
- [ ] PeriodicEnergyExportedEndTime
- [ ] EphemeralEnergyImported
- [ ] EphemeralEnergyExported

**3. Below mentioned attributes Id and Data type is Wrong in XML file.**

- [ ] CumulativeEnergyImported
- [ ] CumulativeEnergyExported
- [ ] PeriodicEnergyImported
- [ ] PeriodicEnergyExported

**4. "Accuracy" attribute is not available in Spec, But it is reflecting in the XML file.**

**5. Below mentioned Events has to be added in XML**

- [ ] CumulativeEnergyImported
- [ ] CumulativeEnergyExported
- [ ] PeriodicEnergyImported
- [ ] PeriodicEnergyExported
- [ ] EphemeralEnergyImported
- [ ] EphemeralEnergyExported

**6. Below mentioned events are not available in Spec, So these should be removed from XML**

- [ ] CumulativeEnergyMeasured
- [ ] PeriodicEnergyMeasured

**7. Below mentioned Enum and Struct values are not available** 

- [ ] MeasurementTypeEnum
- [ ] EnergyMeasurementStruct
- [ ] MeasurementAccuracyRangeStruct
- [ ] MeasurementAccuracyStruct

### Anything else?

**Spec References:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ElectricalEnergyMeasurement.adoc#electrical-energy-measurement

**XML file References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/electrical-energy-measurement-cluster.xml

**Comment by Survensa** [comment]
Spec has been updated. The XML is matching with the latest spec.
