### ISSUE TITLE
[1.3] The implementation of the Energy Preference Cluster is required in sample app

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#31257]
### Feature description

**All-clusters-app has to be enabled with below mentioned attributes :**

- [ ] EnergyBalances
- [ ] CurrentEnergyBalance
- [ ] EnergyPriorities
- [ ] LowPowerModeSensitivities
- [ ] CurrentLowPowerModeSensitivity

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by Rajashreekalmane** [comment]
[https://github.com/project-chip/connectedhomeip/issues/31257](url)

**Comment by KishokG** [comment]
Issue fixed
