### ISSUE TITLE
[1.3] The implementation of the Electrical Energy Measurement Cluster is required in chip-tool and sample app

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#31258]
### Feature description

**Chip-tool and All-clusters-app has to be enabled with below mentioned attributes :**

- [ ] Measured
- [ ] CumulativeEnergyImportedTime
- [ ] CumulativeEnergyExportedTime
- [ ] PeriodicEnergyImportedStartTime
- [ ] PeriodicEnergyImportedEndTime
- [ ] PeriodicEnergyExportedStartTime
- [ ] PeriodicEnergyExportedEndTime
- [ ] EphemeralEnergyImported
- [ ] EphemeralEnergyExported

**Chip-tool and All-clusters-app has to be enabled with below mentioned events :**

- [ ] CumulativeEnergyImported
- [ ] CumulativeEnergyExported
- [ ] PeriodicEnergyImported
- [ ] PeriodicEnergyExported
- [ ] EphemeralEnergyImported
- [ ] EphemeralEnergyExported

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by jamesharrow** [comment]
The XML and Cluster was implemented in PR #30389 and is in all-clusters-app
There is a new PR #31622 which enables it with fake test data in the energy-management-app
