### ISSUE TITLE
[BUG] onError(Int, Long) of UnpairDeviceCallback on Android has never been called with "Failed to access callback 'onError' method" because of JNI bug.  

### ISSUE THREAD

**Issue by Trishia** [project-chip/connectedhomeip#31273]
### Reproduction steps

Whenever I remove device with offline matter device, onError() has never been called.   

According to Java Interface UnpairDeviceCallback API (https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/src/chip/devicecontroller/UnpairDeviceCallback.java), the GetMethodID() in AndroidCurrentFabricRemover() of AndroidCurrentFabricRemover.cpp (https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/AndroidCurrentFabricRemover.cpp#L41) should be like below : 

```env->GetMethodID(callbackClass, "onError", "(IJ)V"); ```

@yunhanw-google Fix please for everyone.

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

4e2d4898735f35555576e0ecccfd3b782c8b320a

### Platform

android

### Platform Version(s)

1.2

**Comment by VinhBH1** [comment]
the sane here , unpairDeviceCallback never callback
