### ISSUE TITLE
[1.3] Gaps in TV clusters - cont

### ISSUE THREAD

**Issue by chrisdecenzo** [project-chip/connectedhomeip#31320]
### Reproduction steps

Here is a list of updates needed for the tv example apps in order to use them for showcasing 1.3 functionality:
1. tv-app: ensure all the new TV 1.3 features are enabled
2. wrap up message cluster PR (see https://github.com/project-chip/connectedhomeip/pull/30254)
3. tv-app: add message as a server cluster on ep2.
4. tv-casting-app: add message as a client cluster on ep2.
5. Bump revision number of updated TV clusters from 1 to 2: AccountLogin, Channel, MediaPlayback, TargetNavigator - see [30261](https://github.com/project-chip/connectedhomeip/issues/30261) , [30410](https://github.com/project-chip/connectedhomeip/issues/30410) and [30411](https://github.com/project-chip/connectedhomeip/issues/30411)
6. Add missing OTT type to ChannelTypeEnum in Channel cluster.
7. Enable 3 new feature flags for ContentControl cluster (bits 5, 6, 7).

NOTE: This commit by @cecille seems to have accidentally removed the Message cluster events:
https://github.com/project-chip/connectedhomeip/commit/9c0cd9eb3656d3c7e40ca811257270db50384d61#diff-cc2349c86fdf91ea42e6eaf7253544065f6adefd863ab6f6a16e0b63f8ca8743

### Bug prevalence

always

### GitHub hash of the SDK that was being used

master

### Platform

core

### Type

Common Cluster Logic

**Comment by lazarkov** [comment]
https://github.com/project-chip/connectedhomeip/pull/30254 under point number 2 continued here: https://github.com/project-chip/connectedhomeip/pull/31656
