### ISSUE TITLE
[BUG][SmartThings Ecosystem] What's the reason why SmartThings ecosystem set the NodeLabel value of the end-device after commission

### ISSUE THREAD

**Issue by jamesluo11** [project-chip/connectedhomeip#31329]
### Reproduction steps

1. Commission the device by chip-tool , then read the NodeLabel in basic cluster, it's empty value
2. Share the device to smartThings ecosystem, then read the NodeLabel, it's "Matter Color Light" or sometings the settting is "Matter Temperature Light" . Analyze the logs, it's true that the smartThings set the value 

### Bug prevalence

Every time

### GitHub hash of the SDK that was being used

Matter tag v1.0.0

### Platform

other

### Platform Version(s)

Matter 1.0

### Anything else?

Just want to know the reason
1. What makes the setting happen
2. Why set the "Matte Color Light"

**Comment by bzbarsky-apple** [comment]
This sounds like a question for Samsung, not a core Matter issue.  Per spec for NodeLabel:

>  This attribute SHALL represent a user defined name for the Node. This attribute SHOULD be set during initial commissioning and MAY be updated by further reconfigurations.

so setting the attribute during commissioning is perfectly reasonable in general.
