### ISSUE TITLE
[1.3] The implementation of the Energy EVSE Cluster is required in sample app

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#31358]
### Feature description

**Below commands has to be added in All-clusters-app:**

- [ ] SetTargets
- [ ] GetTargets
- [ ] ClearTargets

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by Rajashreekalmane** [comment]
[https://github.com/project-chip/connectedhomeip/pull/31407](url)

**Comment by KishokG** [comment]
Issue fixed
