### ISSUE TITLE
File issues against dependencies to enable code scanning

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#3137]
#### Problem
After enabling GitHub Code Scanning on this repo many of our third party dependencies had a bunch (2000+ total) had items that were flagged. These have been tagged "Won't fix", as we can't fix them in here, but we should file issues against the following dependencies to enable Code Scanning, and ideally fix them:

* bluez
* cirque
* happy
* mbledtls
* nrfxlib
* nrfconnect
* openthread

 #### Proposed Solution
File issues with link to how to enable code scanning

**Comment by tcarmelveilleux** [comment]
@woody-apple will this be done, or is this obsolete?
