### ISSUE TITLE
[v1.3]The implementation of the Oven Operational State Cluster is required in Chip-tool and Sample app

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#31384]
### Feature Area

Area:OperationalState

### Reproduction steps
Executed the below mentioned command to put DUT into a commissionable state
./chip-all-clusters-app

Once DUT reach the commissionable state sent below mentioned command on TH.
./chip-tool pairing onnetwork 1 20202021

After the successful commissioning, I attempted to validate the Oven Operational State Cluster, but it is not implemented in chip-tool
![image](https://github.com/project-chip/connectedhomeip/assets/95841834/603428d7-d7d5-4113-966c-c275519675b5)

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

a4300e7f3a8999e5b283aeae20e39d645b296a67

### Platform

raspi

### Anything else?

Spec Reference: https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/OperationalState_Oven.adoc

**Comment by beckerzito** [comment]
Hi @Rajashreekalmane.

According to the spec, the cluster name is "ovencavityoperationalstate". It is listed on your picture: 
<img width="829" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/26304432/a0a0d2f9-8b96-47ff-827d-6e883a2bbb93">

Despite the cluster can be used on the chip tool already, its example implementation on the all-cluster-app is still in progress on the PR:
Example all-cluster-app: https://github.com/project-chip/connectedhomeip/pull/30898
Test Case: https://github.com/project-chip/connectedhomeip/pull/30860
