### ISSUE TITLE
[1.1] what’s the difference  matter sdk  from sdk of google home ？

### ISSUE THREAD

**Issue by netscell** [project-chip/connectedhomeip#31426]
### Reproduction steps

google home log：
01-15 15:36:06.619  3630  3742 I native  : I0000 00:00:1705304166.619559    3742 chip_logging.cc:17] CHIP: DIS: UDP:[fe80::32de:4bff:fedb:8aa7%wlan0]:5540: new best score: 8

in fact,matter sdk has no  best score value 8；
and google home can add LLA interface wlan0.
so matter sdk  google home used has some unkown modify？

### Bug prevalence

NA

### GitHub hash of the SDK that was being used

1.1

### Platform

android

### Platform Version(s)

1.1

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
>  so matter sdk google home used has some unkown modify？

Sounds like it, yes.
