### ISSUE TITLE
[BUG] Example "Contact-Sensor-App" not working to build

### ISSUE THREAD

**Issue by FloBer431** [project-chip/connectedhomeip#31443]
### Reproduction steps

I'm working on a Windows 11 system with an WSL2 subsystem on ubuntu.
I'm starting the system with the available instructions.

I'm starting VSCode with "code .".
The VSCOde extension is working fine.
Connecting the board and trying to build the project with the ESD-IDF command.

An error occures, stating that the cmakelist.txt is missing. Where do I get this from?

Or is there another way of flashing this example on my esp32-s3?

Sorry if I'm missing something, but I'm new to working with this on a linux subsystem.

### Bug prevalence

Whenever I try to do this.

### GitHub hash of the SDK that was being used

dont know

### Platform

esp32, vscode, windows

**Comment by andy31415** [comment]
The builds are not directly controlled by VSCode/CMake.

To build this, you will need to compile from the command line. Please follow https://project-chip.github.io/connectedhomeip-doc/platforms/esp32/setup_idf_chip.html or generally https://project-chip.github.io/connectedhomeip-doc/getting_started/first_example.html

For example I use:

```
source scripts/bootstrap.sh
./scripts/build/build_examples.py --target esp32-m5stack-all-clusters build
```

I would also note that windows has no official maintainer support currently. making compilation work on windows may be painful and I recommend a linux machine/VM instead.
