### ISSUE TITLE
[Feature] locate GSON libraries as a prebuilt JAR in the repo?

### ISSUE THREAD

**Issue by kencottrell** [project-chip/connectedhomeip#31495]
### Feature description

...
Hi, am attempting to manually build Kotlin and Java controllers in Android studio, and am getting these unresolved references in my JsonToTLv.kt file. I assume that I need to add a JAR to my environment and was hoping to not have to pick through the github and do a Maven build since I am using the incorporated Gradle within Android studio.  Is this JAR located somewhere in the repo, or if not can it added as a future feature?

If not in the repo, I've looked around to see if I could download the jar but don't see one. Does anyone have one that they can post to the repo or somewhere else public? 

****import com.google.gson.JsonArray
import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonParser****

### Platform

windows

### Anything else?

e: file:///C:/Users/kjcot/AndroidStudioProjects/KensMatterControllerSample/app/src/main/java/matter/jsontlv/JsonToTlv.kt:21:12 Unresolved reference: google

unresolved refs shown:  
- import com.google.gson.JsonArray
- import com.google.gson.JsonElement
- import com.google.gson.JsonObject
- import com.google.gson.JsonParser

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/third_party/java_deps/set_up_java_deps.sh

**Comment by kencottrell** [comment]
thank you @yunhanw-google

**Comment by kencottrell** [comment]
one more comment, @yunhanw-google  I couldn't get the refs recognized by adding them to the ./libs directory - I also had to setup the project structure |  dependencies path to point to the jars. now they are recognized. I'm not sure why Android didn't look at the libs directory after synching the Gradle build.
