### ISSUE TITLE
Nordic  globalscenecontrol does not change with onoff

### ISSUE THREAD

**Issue by chuckrui** [project-chip/connectedhomeip#31499]
NCS：V2.3.0
Project：light_bulb

Test1：
Step
(1) ./chip-tool onoff on 1 1
(2)./chip-tool onoff read on-off 1 1
(3)./chip-tool onoff read global-scene-control 1 1
(4)./chip-tool onoff **off-with-effect** 0 0 1 1
(5)./chip-tool onoff read on-off 1 
(6)./chip-tool onoff read global-scene-control 1 1
(7)./chip-tool onoff off-with-effect 0 0 1 1
(8)./chip-tool onoff read global-scene-control 1 1

Command Result：
(1)Success
(2)True
(3)True
(4)Success
(5)False
(6)True
(7)Success
(8)False

The Test1 step(6) result should be false as same as on-off state because it changed by “onoff off-with-effect”command.
But got true.If i run the step(7) again,the step(8) will from true change to false.
In other words, the value of "global-scene-control" can remain the same as the on-off state after the "off-with-effect" command is executed **twice**.

Test1 Log:
[step1.txt](https://github.com/project-chip/connectedhomeip/files/13973069/step1.txt)

Test2：
Step
(1)./chip-tool onoff off 1 1
(2)./chip-tool onoff read on-off 1 1
(3)./chip-tool onoff read global-scene-control 1 1
(4)./chip-tool onoff on-with-recall-global-scene 1 1
(5)./chip-tool onoff read on-off 1 1
(6)./chip-tool onoff read global-scene-control 1 1

Command Result：
(1)Success
(2)False
(3)False
(4)Success
(5)True
(6)True

Test2 Log:
[step2.txt](https://github.com/project-chip/connectedhomeip/files/13973082/step2.txt)
All the command run normal.

Refer to the test file **Draft_SVE2_TestPlanVerificationSteps.xlsx**  TC-OO-2.3 3b
[]https://groups.csa-iot.org/wg/members-all/document/31911
![image](https://github.com/project-chip/connectedhomeip/assets/76715008/9242906b-773f-47c8-b58f-71fc1b34c88f)

Add:
I see the code about on-off-server,when run the offWithEffect Command, and globalSceneControl=true,it will set GlobalSceneControl value to false,and i get the return value is 0x00,it mean successed,but in fact，GlobalSceneControl value still true.
And i run the ". /chip-tool onoff off-with-effect 0 0 1 1" command again, the return values are the same as the before.
![image](https://github.com/project-chip/connectedhomeip/assets/76715008/435585a8-83cd-452a-9562-b8c11cbb477a)

**Comment by bzbarsky-apple** [comment]
@chuckrui Is this only an issue with Nordic devices?

@Damian-Nordic @kkasperczyk-no

**Comment by bzbarsky-apple** [comment]
In particular, I cannot reproduce with the "linux" all-clusters-app: I get back "false" at step 6 in the steps above.

**Comment by chuckrui** [comment]
@bzbarsky-apple right，I encountered this problem temporarily on nordic platforms

**Comment by kkasperczyk-no** [comment]
@chuckrui well I couldn't reproduce your problem on the current master branch (c1c9237bccd5ff062049e913df4d6c283788b20e) + NCS 2.5.0, it works for me correctly. You wrote you tested it with NCS 2.3.0 that was released ~10 months ago and included Matter 1.0.0.2, so it's possible that something changed in the meantime. Let me try to go back to the older versions and try to reproduce it again.

**Comment by kkasperczyk-no** [comment]
Ok, indeed I can see this issue on the Matter 1.0.0.2 + NCS 2.3.0 versions.

**Comment by chuckrui** [comment]
@kkasperczyk-no I know that currently ncs has reached v2.5.0, but our certification is still in v2.3.0 Matter1.0, so I want to know how to solve this problem, because we found this problem when we sent the certification. And this is a feature that 0x0101 Matter Dimmable Light device type must support.

**Comment by chuckrui** [comment]
We have been stuck here for a long time and have been unable to solve it. Once this problem is solved, we can pass the certification. We hope to get your reply as soon as possible.Thank you very much~

**Comment by kkasperczyk-no** [comment]
@chuckrui I think I've got a fix. The problem is not with the `on-off` server, but with the `level-control`. The `on-off` server sets `global-scene-control` to false correctly, but then `level-control` puts it back to true, as `off-with-effect` triggers `moveToLevelHandler`: https://github.com/project-chip/connectedhomeip/blob/v1.0.0.2/src/app/clusters/level-control/level-control.cpp#L770 

Please try to apply this commit: https://github.com/project-chip/connectedhomeip/commit/836390ed636ca36126dbcbe763d0f127626cba8d and let me know if everything works as expected.

At least I don't see this issue anymore after I made a cherry-pick.

**Comment by chuckrui** [comment]
Yes, I have verified it.Thank you very much~
