### ISSUE TITLE
[DEM] Sample app and SDK impementation required for Device Energy Management cluster

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#31507]
### Feature description

**Chip-tool and All-clusters-app has to be enabled with below mentioned attribute :**

- [ ] OptOutState

**Chip-tool and All-clusters-app has to be enabled with below mentioned command :**

- [ ] CancelRequest

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by bzbarsky-apple** [comment]
Duplicate of https://github.com/project-chip/connectedhomeip/issues/31479.  Please check for duplicates before filing.
