### ISSUE TITLE
[BUG] Build error for microwave-oven app

### ISSUE THREAD

**Issue by ccruzagralopes** [project-chip/connectedhomeip#31525]
### Reproduction steps

Tried to build the microwave-oven exemple app using the following command:
```
scripts/build/build_examples.py --target linux-x64-microwave-oven-ipv6only build
```

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

a0334268f379bbac96b8bf9161a501f29d0298bb

### Platform

vscode

### Anything else?

Failure logs: [failure.log](https://github.com/project-chip/connectedhomeip/files/13981066/failure.log)

Build was successful when using SHA `9034671cab2891c140fdb32a6863e3429b9fe4d8`.

**Comment by bzbarsky-apple** [comment]
Looks like fallout from #31130.  @liangpy4 please take a look.
