### ISSUE TITLE
[CERT-TEST-FAILURE] - TC-ACE-2.1 & 2.2- Test failed

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#31545]
### Feature Area

Other

### Test Case

TC-ACE-2.1 & 2.2

### Reproduction steps

Read and write privilege enforcement fails in all-clusters-app.

### Bug prevalence

Whenever I do this 

### GitHub hash of the SDK that was being used

0ff709f25f6a7af68314c1b0a147a76c30c234f6

### Platform

raspi
python

### Anything else?

Error Log : [TC-ACE-2.1 & 2.2 Failure responses](https://github.com/project-chip/connectedhomeip/files/14008069/Accecc_checker.txt)

**Comment by KishokG** [comment]
@cecille Write privilege test case is PASSED when I ran the script in this commit 039cbab7aeb6387d56b6196249b45ea71350752a. But I tried with latest commit 0ff709f25f6a7af68314c1b0a147a76c30c234f6 and now both read and write privileges gets fail. So I have added `TC-ACE-2.2` test case in this ticket and updated the log as well.

**Comment by cecille** [comment]
Discussed on slack, but didn't update issue. This appears to be a timeout. https://github.com/project-chip/connectedhomeip/pull/31643

**Comment by Survensa** [comment]
Issue fixed
