### ISSUE TITLE
[Build] Substitute SDK Docker Image

### ISSUE THREAD

**Issue by jscarey1** [project-chip/connectedhomeip#31554]
### Build issue(s)

1. Attempting to build a Docker Image for Test Harness (not on RPI).
2. Using SDK SHA `85a48aabbc4e43c433aa4b2d35b2817d611946de`
3. Fails to Build due to ImportError: cannot import name 'OneStyleAndTextTuple' from 'prompt_toolkit.formatted_text' (/root/connectedhomeip/.environment/pigweed-venv/lib/python3.10/site-packages/prompt_toolkit/formatted_text/__init__.py)
...

### Platform

python

### Anything else?

[docker_fail.txt](https://github.com/project-chip/connectedhomeip/files/13990615/docker_fail.txt)

**Comment by bzbarsky-apple** [comment]
@andy31415

**Comment by andy31415** [comment]
You will need a new SDK SHA to have the fix or cherry-pick the update to prompt-toolkit.
