### ISSUE TITLE
[1.3] Kotlin Matter controller  Main.kt type mismatch between getPairingCommands() and PairOnNetworkLongCommand()

### ISSUE THREAD

**Issue by kencottrell** [project-chip/connectedhomeip#31577]
### Reproduction steps

android build routine that includes these imports and tries to instance the getPairingCommands()function
import com.matter.controller.commands.common.Command
import com.matter.controller.commands.common.CommandManager
import com.matter.controller.commands.common.CredentialsIssuer
import com.matter.controller.commands.pairing.PairOnNetworkLongCommand
import com.matter.controller.commands.pairing.PairOnNetworkLongImInvokeCommand
import com.matter.controller.commands.pairing.PairOnNetworkLongImReadCommand
import com.matter.controller.commands.pairing.PairOnNetworkLongImSubscribeCommand
import com.matter.controller.commands.pairing.PairOnNetworkLongImWriteCommand
import matter.controller.ControllerParams
import matter.controller.MatterController
import matter.controller.MatterControllerImpl
....
// sends Matter Controller, but PairOnNetworkLongCommands is expecting DeviceController
private fun getPairingCommands(
    controller: MatterController,
    credentialsIssuer: CredentialsIssuer
): List<Command> {
    return listOf(
        PairOnNetworkLongCommand(controller, credentialsIssuer),
    )
}

// this function also used MatterController instead of ChipDeviceController
private fun getImCommands(
    controller: MatterController,   // change this

    credentialsIssuer: CredentialsIssuer
): List<Command> {
    return listOf(
        PairOnN....

### Bug prevalence

everytime I run the main file

### GitHub hash of the SDK that was being used

not sure where to find this?

### Platform

windows

### Type

Common Cluster Logic

### Anything else?

: in Main.kt, getPairing Commands() method sends MatterController to PairOnNetworkLongCOmmand()

private fun getPairingCommands(
   // controller: MatterController,   <<< I commented this out and changed to ChipDeviceController and it now builds ok
    controller: ChipDeviceController,   <<< changed to this
    credentialsIssuer: CredentialsIssuer
): List<Command> {
    return listOf(
        PairOnNetworkLongCommand(controller, credentialsIssuer),
    )
}

private fun getImCommands(
    // controller: MatterController,   // change this
    controller: ChipDeviceController,   //  <<< to this
    credentialsIssuer: CredentialsIssuer
): List<Command> {
    return listOf(
        PairOnNetworkLongImReadCommand(controller, credentialsIssuer),
        PairOnNetworkLongImSubscribeCommand(controller, credentialsIssuer),
        PairOnNetworkLongImWriteCommand(controller, credentialsIssuer),
        PairOnNetworkLongImInvokeCommand(controller, credentialsIssuer),
    )
}

**Comment by yunhanw-google** [comment]
@kencottrell Kotlin Matter controller is a little far away from the readiness, which still need some time development on it, please still use java device controller https://github.com/project-chip/connectedhomeip/tree/master/src/controller/java/src/chip/devicecontroller, and refer the android-chip-tool for usage, thanks

**Comment by kencottrell** [comment]
@yunhanw-google  I'll close this if ok with you.
