### ISSUE TITLE
[1.3] DEMM / EVSEM FeatureMap list has to be updated as per Test Plan

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#31599]
### Reproduction steps

1. Executed the below mentioned command to put DUT into a commissionable state
**./chip-all-clusters-app**

2. Once DUT reach the commissionable state sent below mentioned command on TH.
**./chip-tool pairing onnetwork 1 20202021**

3. After the successful commissioning, Read the FeatureMap List from Device Energy Management Mode cluster and Energy EVSE Mode cluster.

**Device Energy Management Mode cluster**
**Actual Outcome:**
` ./chip-tool deviceenergymanagementmode read feature-map 1 1
`
> [1706881081.042184][440495:440497] CHIP:DMG: }
> [1706881081.043033][440495:440497] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_FFFC DataVersion: 1547715270
> [1706881081.043698][440495:440497] CHIP:TOO:   FeatureMap: 1

**Expected Outcome:**
` ./chip-tool deviceenergymanagementmode read feature-map 1 1
`
> [1706881081.042184][440495:440497] CHIP:DMG: }
> [1706881081.043033][440495:440497] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_FFFC DataVersion: 1547715270
> [1706881081.043698][440495:440497] CHIP:TOO:   FeatureMap: 0

**Energy EVSE Mode cluster.**

**Actual Outcome:**

`./chip-tool energyevsemode read feature-map 1 1
`
> [1706881220.115407][440516:440518] CHIP:DMG: }
> [1706881220.115534][440516:440518] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_FFFC DataVersion: 3292688480
> [1706881220.115569][440516:440518] CHIP:TOO:   FeatureMap: 1

**Expected Outcome:**

`./chip-tool energyevsemode read feature-map 1 1
`
> [1706881220.115407][440516:440518] CHIP:DMG: }
> [1706881220.115534][440516:440518] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_FFFC DataVersion: 3292688480
> [1706881220.115569][440516:440518] CHIP:TOO:   FeatureMap: 0

### Summary
In Test Plan FeatureMap list entry is 0, But in SDK  getting value as 1 . So SDK has to be updated as test plan for `Energy EVSE Mode` and `Device Energy Management Mode`. 

Took Example as Device Energy Management Mode

**Test Plan References:**
![image](https://github.com/project-chip/connectedhomeip/assets/98016634/416b215b-001a-4563-ab58-7834b20cd028)
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_device_energy_management.adoc

**Log Reference:**
./chip-tool deviceenergymanagementmode read feature-map 1 1

```
[1705926658.591763][137899:137905] CHIP:DMG: }
[1705926658.591927][137899:137905] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_FFFC DataVersion: 2217281179
[1705926658.591968][137899:137905] CHIP:TOO:   FeatureMap: 1
```

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

0ff709f25f6a7af68314c1b0a147a76c30c234f6

### Platform

raspi

### Platform Version(s)

1.3

**Comment by jamesharrow** [comment]
Needs a small change to ZAP, but will wait until other PRs merge before changing this now.
