### ISSUE TITLE
[Tooling] update pyspelling in SDK to support camel-case

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#31602]
### Reproduction steps / Feature

newer versions fixed the camel-case option to aspell. The spec repo uses this version. We should update the SDK to do the same. Then we can remove some of the excluded files from the spell checker.

### Platform

python

### Type

CI tested

**Comment by cecille** [comment]
After updating, we should also prune the wordlist to exclude the things that were added to work around not having camel case. When we did this in the spec, we found lots of spelling errors.

**Comment by kliao-csa** [comment]
Pyspelling updated, Reviewdog commented out
Slowly removing camelcase entries from the wordlist - regex indicates there are a few hundred
