### ISSUE TITLE
[1.2] cannot decode payload_hex on chip-tool trace_file

### ISSUE THREAD

**Issue by mmt-10** [project-chip/connectedhomeip#31618]
### Reproduction steps

```
$ ./chip-tool doorlock read door-state 1234 1 --trace_log 1 --trace_file ./psoc6-log/doorstate.log
$ ./chip-tool payload parse-setup-payload 15360017240201250301012404031818290324ff0b18
```
then, chip-tool shows error.

> [1705975377.180310][16350:16350] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_tool_kvs
> [1705975377.180353][16350:16350] CHIP:SPL: Parsing decimalRepresentation: 15360017240201250301012404031818290324ff0b18
> [1705975377.180364][16350:16350] CHIP:TOO: Run command failure: src/setup_payload/ManualSetupPayloadParser.cpp:49: Error 0x00000013

```
$ ./chip-tool payload parse-additional-data-payload 15360017240201250301012404031818290324ff0b18
```

> [1705975810.930273][16552:16552] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_tool_kvs
> [1705975810.930320][16552:16552] CHIP:TOO: AdditionalDataParseCommand, RotatingDeviceId=

I would like to decode `payload_hex` on below trace file.
[doorstate.log](https://github.com/project-chip/connectedhomeip/files/14017380/doorstate.log)

### Bug prevalence

always

### GitHub hash of the SDK that was being used

commit 181b0cb14ff007ec912f2ba6627e05dfb066c008 (HEAD, tag: v1.2.0.1)

### Platform

core

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
@mmt-10 I don't understand what you are trying to do.  Message payloads are not the same as either setup payloads or the "additional data" payload in a QR code.  Why do you think "chip-tool payload" (which specifically works with Matter setup payloads) is supposed to be a generic "parse any payload of any packet" thing?

**Comment by mmt-10** [comment]
Thank you for your reply.

I understand that I misunderstood `chip-tool payload` function.
I want to know how to decode `payload_hex` in trace file [doorstate.log](https://github.com/project-chip/connectedhomeip/files/14017380/doorstate.log).

**Comment by bzbarsky-apple** [comment]
It's just a hex dump of the bytes of the payload, no?  Then you have to look at the exact message type to figure out what it might mean.

**Comment by mmt-10** [comment]
@Chapoly1305 
Thank you for your reply.
`--trace_decode 1` could print decoded message.
