### ISSUE TITLE
Investigate removing `template <typename CommandData>` for `TryAddResponseData`

### ISSUE THREAD

**Issue by tehampson** [project-chip/connectedhomeip#31627]
It should be possible to use a base class instead of the template "duck-typing" we are using when calling `DataModel::Encode(*writer, TLV::ContextTag(CommandDataIB::Tag::kFields), aData)`.

This will help reduce code compiled code size as well as make code more readable in `CommandHandler`

#### Alternative Solution to still explore:
* `LambdaBridge` as [mentioned here](https://github.com/project-chip/connectedhomeip/pull/31631#discussion_r1463535688)

**Comment by andy31415** [comment]
#33736 updated TryAddResponseData to not be a template anymore. Assyming this closed.
