### ISSUE TITLE
M5Stack Identify Cluster command never stops

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#3165]
#### Problem
Running the Identify Cluster Command on the M5Stack via the CHIP Tool CLI never seems to stop identifying. 

```
./out/debug/standalone/chip-tool identify 192.168.x.xx 11095 1 5
```

 #### Proposed Solution
Find and fix this regression

**Comment by sagar-apple** [comment]
@vivien-apple is this something you can take a look at?

**Comment by vivien-apple** [comment]
> @vivien-apple is this something you can take a look at?

Adding to my list.
