### ISSUE TITLE
[ICD] If chip-tool sends the register-client command, the information is not stored in the ICD storage

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#31697]
#### Description
If the registration with the ICD is done at commissioning, the ICD information is persisted.
If the registration is done after commissioning, the ICD information is not persisted

**Comment by erjiaqing** [comment]
> If the registration is done after commissioning, the ICD information is not persisted

I guess this is done by sending the command manually?

I would suggest add a "register" command to icd to do register + persist.

**Comment by yunhanw-google** [comment]
@erjiaqing let's go with a new command for registrer-client that can store the icd info to storage.

**Comment by mkardous-silabs** [comment]
@erjiaqing @yunhanw-google We would also need an `unregister` command that can clear the persistant storage information.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/33671
