### ISSUE TITLE
[Feature] How can I detect a Matter Device is using Thread or Wi-Fi

### ISSUE THREAD

**Issue by huynguyen-df** [project-chip/connectedhomeip#31729]
### Feature description

# Problem
I'm using. the lib [Matter](https://developer.apple.com/documentation/matter) of Apple.
I have a problem when I want to detect whether the device is using which network connection Wi-Fi or Thread to provide the correct credentials it needs.
Anyone can help me?

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
@huynguyen-df You should be using https://developer.apple.com/documentation/mattersupport which should handle that for you, no?

**Comment by huynguyen-df** [comment]
Thank you. However, because of some reason, I don't want to apply it to the current project. So I want to find a good other way to detect should use which network connection Wi-Fi or Thread, instead of using MatterSupport to detect that.

**Comment by bzbarsky-apple** [comment]
@huynguyen-df Once you have a PASE session to the device, you should be able to get this information from the Network Commissioning cluster, no?

That said, some devices can do both Wi-Fi and Thread; I have no idea what you want to do there.

**Comment by huynguyen-df** [comment]
Thank you so much. The Network Commissioning cluster worked well. It correct with my requirement
