### ISSUE TITLE
[1.3] The implementation of the Messages Cluster is required in sample app

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#31742]
### Test Case

TC-MESS-1.1 & 2.1

### Description:
**Below Attibutes, Commands and Events has to be added in All-clusters-app:**

**Attributes:**

- [ ] Messages
- [ ] ActiveMessageIDs

**Commands:**

- [ ] PresentMessagesRequest
- [ ] CancelMessagesRequest

**Events:**

- [ ] MessageQueued
- [ ] MessagePresented
- [ ] MessageComplete

### Platform

raspi

**Comment by Survensa** [comment]
Issue fixed
