### ISSUE TITLE
Use mbedtls_platform_set_calloc_free() for non-malloc() configurations

### ISSUE THREAD

**Issue by kpschoedel** [project-chip/connectedhomeip#3178]
#### Problem

Part of #2748 All Embedded Device-side Code Needs to Be Scrubbed of Direct Heap Usage

MbedTLS can be configured at compile-time or run-time to use memory management functions other than the default `calloc()` and `free()`. Doing this at compile-time is [awkward](https://github.com/project-chip/connectedhomeip/pull/3143#discussion_r502510143).

 #### Proposed Solution

Ensure that `mbedtls_platform_set_calloc_free()` is called when `chip_config_memory_management` is not `"malloc"`.

It would be nice to have this happen on `Platform::MemoryInit()`, which implies a split of management×platform there.

**Comment by woody-apple** [comment]
Maybe resolved?
