### ISSUE TITLE
[TC-DA-1.7] Missing validation for exact byte equivalence of issuer to CA's subject

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#31799]
Since https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8749, we need to check at certification that DACs/PAIs have properly matching byte-for-byte issuer field to the CA cert's subject field.

TC-DA-1.7 test script needs to be updated.

**Comment by cecille** [comment]
This issue was addressed in https://github.com/project-chip/connectedhomeip/pull/33117/files.
