### ISSUE TITLE
[1.3] RVC OpState TC 2.4 - update to match test plan

### ISSUE THREAD

**Issue by plauric** [project-chip/connectedhomeip#31829]
### Reproduction steps

Update RVCOPSTATE TC 2.4 due to this test plan change: https://github.com/CHIP-Specifications/chip-test-plans/pull/3915/files

- remove the steps related to the Running, Pause, Stopped states
- add step related to the Seeking Charger state

### Bug prevalence

always

### GitHub hash of the SDK that was being used

e75f229

### Platform

other

### Type

Test Improvement

**Comment by cjandhyala** [comment]
@hicklin @plauric Now the test plan issue is merged for RVCOPSTATE TC 2.4, Do you plan getting a SDK PR to provide automation scripts for the same ?
