### ISSUE TITLE
[1.3] - TC-S-2.3  - Test failed

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#31954]
### Reproduction steps

1. Executed the below mentioned command to put DUT into a commissionable state
`./chip-all-clusters-app`
2. Once DUT reach the commissionable state sent below mentioned command on TH.
`./chip-tool pairing onnetwork 1 20202021
`
3. After the successful commissioning

**Precondition Steps for adding a Group:**

`./chip-tool groupkeymanagement key-set-write '{"groupKeySetID": "0x01a1","groupKeySecurityPolicy": 0, "epochKey0":"d0d1d2d3d4d5d6d7d8d9dadbdcdddedf","epochStartTime0": 2220000,"epochKey1":"d1d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime1": 2220001,"epochKey2":"d2d1d2d3d4d5d6d7d8d9dadbdcdddedf", "epochStartTime2": 2220002 }' 1 0`

```
[1658316948.574526][4039:4044] CHIP:DMG:                                StatusIB =
[1658316948.574561][4039:4044] CHIP:DMG:                                {
[1658316948.574597][4039:4044] CHIP:DMG:                                   status = 0x00 (SUCCESS),
[1658316948.574632][4039:4044] CHIP:DMG:                                },
```
`./chip-tool groupkeymanagement write group-key-map '[{"groupId": "0x0101", "groupKeySetID": "0x01a1", "fabricIndex": 1} ]' 1 0
`

> [1701068700.776737][13805:13807] CHIP:DMG:                         StatusIB =
> [1701068700.776740][13805:13807] CHIP:DMG:                         {
> [1701068700.776744][13805:13807] CHIP:DMG:                                 status = 0x00 (SUCCESS),
> [1701068700.776747][13805:13807] CHIP:DMG:                         },

`./chip-tool groups add-group 0x0101 Gp1 1 1
`
> [1707218444.541162][22520:22522] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0004 Command 0x0000_0000
> [1707218444.541243][22520:22522] CHIP:TOO:   AddGroupResponse: {
> [1707218444.541268][22520:22522] CHIP:TOO:     status: 0
> [1707218444.541279][22520:22522] CHIP:TOO:     groupID: 257
> [1707218444.541290][22520:22522] CHIP:TOO:    }

Send add scene command with groupcast method

`./chip-tool scenesmanagement add-scene 0x0101 0x03 1 "scene name" '[{"clusterID": "0x0300", "attributeValueList":[{"attributeID": "0x4002", "attributeValue": "0x01"}]}]' 0xffffffffffff0101 1
`
There is no Response from Server

**Try to View the 0x03 Scene with below command**
**Actual Outcome:**

`./chip-tool scenesmanagement view-scene 0x0101 0x03 1 1
`
> [1707218475.652642][22529:22531] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0062 Command 0x0000_0001
> [1707218475.652701][22529:22531] CHIP:TOO:   ViewSceneResponse: {
> [1707218475.652725][22529:22531] CHIP:TOO:     status: 139
> [1707218475.652736][22529:22531] CHIP:TOO:     groupID: 257
> [1707218475.652746][22529:22531] CHIP:TOO:     sceneID: 3
> [1707218475.652757][22529:22531] CHIP:TOO:    }

**Expected Outcome:**
`./chip-tool scenesmanagement view-scene 0x0101 0x03 1 1
`
> [1705911468.473125][20816:20818] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_0062 Command 0x0000_0001
> [1705911468.473151][20816:20818] CHIP:TOO:   ViewSceneResponse: {
> [1705911468.473155][20816:20818] CHIP:TOO:     status: 0
> [1705911468.473158][20816:20818] CHIP:TOO:     groupID: 257
> [1705911468.473160][20816:20818] CHIP:TOO:     sceneID: 3
> [1705911468.473162][20816:20818] CHIP:TOO:     transitionTime: 1
> [1705911468.473165][20816:20818] CHIP:TOO:     sceneName: scene name
> [1705911468.473170][20816:20818] CHIP:TOO:     extensionFieldSets: 1 entries
> [1705911468.473180][20816:20818] CHIP:TOO:       [1]: {
> [1705911468.473183][20816:20818] CHIP:TOO:         ClusterID: 768
> [1705911468.473186][20816:20818] CHIP:TOO:         AttributeValueList: 1 entries
> [1705911468.473195][20816:20818] CHIP:TOO:           [1]: {
> [1705911468.473197][20816:20818] CHIP:TOO:             AttributeID: 16386
> [1705911468.473199][20816:20818] CHIP:TOO:             AttributeValue: 1
> [1705911468.473201][20816:20818] CHIP:TOO:            }
> [1705911468.473204][20816:20818] CHIP:TOO:        }
> [1705911468.473207][20816:20818] CHIP:TOO:    }

**This behavior is consistent with the Remove Scenes, CopyScene command, and RemoveAllScenes command as well.**

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

4c4d8bfc90e0c345ad3f0cf61220067ad31b0391

### Platform

raspi

### Platform Version(s)

1.3

### Type

Test Improvement

### Anything else?

As per the specification, if the AddScene command is received as a groupcast, the server SHALL NOT generate an AddSceneResponse command. When attempting to add a scene using the groupcast method, the server does not generate an AddSceneResponse command. However, in the Next step, when attempting to view the scenes, the response status is reported as NOT FOUND instead of SUCCESS.

This behavior is consistent with the Remove Scenes, CopyScene command, and RemoveAllScenes command as well.

**Specification References:**

- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Scenes.adoc#94-viewscene-command

**Test Plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/scenes.adoc

**Reference Log:**
[TC-S-2.3(Chip-tool log).txt](https://github.com/project-chip/connectedhomeip/files/14178900/TC-S-2.3.Chip-tool.log.txt)
[TC-S-2.3(DUT log).txt](https://github.com/project-chip/connectedhomeip/files/14178901/TC-S-2.3.DUT.log.txt)

**Comment by lpbeliveau-silabs** [comment]
@Ashwinigrl Please note that you should run run
`mattertool accesscontrol write acl '[{"privilege": 5, "authMode": 2, "subjects": null, "targets": null}, {"privilege": 4, "authMode": 3, "subjects": null, "targets": null}]' 1 0`
To ensure group commands are allowed by the device.

Furthermore, the problem seems to be that the Script comment and the Test plan should have their keys replaced to have the command like this:
`mattertool groupkeymanagement key-set-write '{"groupKeySetID": "0x01a1", "groupKeySecurityPolicy": 0, "epochKey0": "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf", "epochStartTime0": 1110000,"epochKey1": "b0b1b2b3b4b5b6b7b8b9babbbcbdbebf", "epochStartTime1": 1110001,"epochKey2": "c0c1c2c3c4c5c6c7c8c9cacbcccdcecf", "epochStartTime2": 1110002 }' 1 0`

A PR for this will be opened soon in the Test plan and SDK.
