### ISSUE TITLE
[1.3] Chip stack locking error at 'src/app/util/attribute-storage.cpp:573'. Code is unsafe/racy

### ISSUE THREAD

**Issue by nmtoan91** [project-chip/connectedhomeip#31984]
### Reproduction steps

I just trying to get the on-off value by
`OnOffServer::Instance().getOnOffValue(endpointid, &currentLedState);`
and the error occurs. 
There is no error when I use the chip-tool 

### Bug prevalence

all the time

### GitHub hash of the SDK that was being used

latest

### Platform

darwin

### Platform Version(s)

latest

### Type

Platform Issue

**Comment by xvortep** [comment]
Generally, Matter SDK aborts the program when your code is not thread safe (with assertChipStackLockedByCurrentThread()). Try locking the chip stack before calling that function with chip::DeviceLayer::StackLock or with PlatformMgr().LockChipStack(); PlatformMgr().UnlockChipStack();

**Comment by bzbarsky-apple** [comment]
Or do the read in a task queued to the Matter event queue.  But yes, `OnOffServer::Instance().getOnOffValue` _must_ be called with the Matter lock held in some way, because otherwise you are racing modifications to the attribute and could get garbage data.
