### ISSUE TITLE
[1.3] T key in TXT record set incorrectly

### ISSUE THREAD

**Issue by raul-marquez-csa** [project-chip/connectedhomeip#32008]
### Reproduction steps

The T key is set incorrectly per the new spec
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/secure_channel/Discovery.adoc#4-common-txt-keyvalue-pairs

T key is coming in as '1'.

![image](https://github.com/project-chip/connectedhomeip/assets/130402456/2f76912d-5077-4915-af37-5f681d4ebfe8)

The restriction on bit 0 is present in the recirculation ballot and hence should be landing in 1.3

### Bug prevalence

n/a

### GitHub hash of the SDK that was being used

master

### Platform

python

### Type

Spec Compliance Issue

**Comment by bzbarsky-apple** [comment]
The spec is new and the SDK has not been updated to it yet.  The reason bit 0 (the one that's set here) is reserved in the spec is precisely because the SDK has been setting it and so it means nothing.

@pidarped

**Comment by raul-marquez-csa** [comment]
Addressed in:

https://github.com/project-chip/connectedhomeip/pull/32083
