### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-S-1.1] Test failure in case if optional LastConfiguredBy attribute isn't supported by DUT.

### ISSUE THREAD

**Issue by AntonGrey** [project-chip/connectedhomeip#32040]
### Feature Area

Area:Scenes

### Test Case

TC-S-1.1

### Reproduction steps

Run TC-S-1.1 from TestHarness version 2.10-beta2.2+spring2024 on DUT without support LastConfiguredBy attribute

### Bug prevalence

Whenever I do this.

### GitHub hash of the SDK that was being used

0ff709f25f6a7af68314c1b0a147a76c30c234f6

### Platform

raspi

### Anything else?

Here is TestHarness log. FYI: PICS filled correctly.
[TC-S-1.1_huebridge_TH_log.log](https://github.com/project-chip/connectedhomeip/files/14223304/TC-S-1.1_huebridge_TH_log.log)

**Comment by lpbeliveau-silabs** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/32003
