### ISSUE TITLE
Figure out where to declare UNUSED_VAR and UNUSED_PARAMETER so they can be shared

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#32113]
Same as above, I'm not going to boil this ocean, which is already a pattern elsewhere in the code base, will just put the macro back in.

_Originally posted by @woody-apple in https://github.com/project-chip/connectedhomeip/pull/32053#discussion_r1488618422_

**Comment by bzbarsky-apple** [comment]
I think the right answer is to just use `[[maybe_unused]]` now that we are c++17, instead of making up our own variants.
