### ISSUE TITLE
[BUG] Getting error "chip.devicecontroller.ChipClusterException: CHIP cluster error: 126" and "IM Error 0x00000580: General error: 0x80"

### ISSUE THREAD

**Issue by aroraprateek202112** [project-chip/connectedhomeip#32121]
### Reproduction steps

Facing error to connect to the already matter device.

Reproduction Steps:
1. Create keypair and save the public and private key from keypair and using the keypair to generate CSR.
2. Get RCAC, ICAC
3. NOC is created using the public key used to generate CSR.
4. Get unique IPK value
5. Commission a matter device.
6. Matter Device successfull commissioned.
7. Able to control the device.
8. Uninstall the app and reinstall it.
9. Login to the same account.
10. Create keypair from the saved public and private key and using the saved keys to generate CSR.
11. Generate fresh RCAC, ICAC certificate
12. NOC is created using the saved public key used to generate CSR
13. Use the same IPK value
14. As per logs, Device controller and device pointer is intializing successfully.
15. When we are subscribing to OnOff cluster, getting error **IM Error 0x00000580: General error: 0x80**
16. When we reading onOffAttribute from OnOffCluster, getting **chip.devicecontroller.ChipClusterException: CHIP cluster error: 126** 

Please find the logs below:

> 2024-02-14 14:02:29.106  2542-2974  TOO 		D  KVS: Getting key g/sri
> 2024-02-14 14:02:29.106  2542-2974  TOO 		D  KVS: Setting key f/1/s/000000000000010E
> 2024-02-14 14:02:29.106  2542-2974  TOO 		D  KVS: Setting key g/s/A/GmQCtQpfgQa3Tb/Won4Q==
> 2024-02-14 14:02:29.107  2542-2974  TOO 		D  KVS: Setting key g/sri
> 2024-02-14 14:02:29.107  2542-2974  SC  		D  SecureSession[0xb400007cb11f5700, LSID:47052]: State change 'kEstablishing' --> 'kActive'
> 2024-02-14 14:02:29.107  2542-2974  IN  		D  SecureSession[0xb400007cb11f5700]: Activated - Type:2 LSID:47052
> 2024-02-14 14:02:29.107  2542-2974  IN  		D  New secure session activated for device <000000000000010E, 1>, LSID:47052 PSID:45859!
> 2024-02-14 14:02:29.107  2542-2974  DIS 		D  OperationalSessionSetup[1:000000000000010E]: State change 4 --> 5
> 2024-02-14 14:02:29.108  2542-2974  ChipClient 	D  Got connected device pointer
> 2024-02-14 14:02:29.109  2542-2974  EM          D  <<< [E:38913i S:0 M:45244897 (Ack:258765561)] (U) Msg TX to 0:0000000000000000 [0000] [UDP:192.168.29.35%wlan0:5540] --- Type 0000:10 (SecureChannel:StandaloneAck)
> 2024-02-14 14:02:29.109  2542-2974  EM          D  Flushed pending ack for MessageCounter:258765561 on exchange 38913i
> 2024-02-14 14:02:29.111  2542-2542  Looper      W  PerfMonitor longMsg : seq=593 plan=14:02:26.787 late=234ms wall=2086ms running=0ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver procState=-1
> 2024-02-14 14:02:29.111  2542-2542  Looper      W  PerfMonitor doFrame : time=2086ms vsyncFrame=0 latency=234ms procState=-1 historyMsgCount=1 (msgIndex=1 wall=2086ms seq=593 late=234ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
> 2024-02-14 14:02:29.126  2542-2542  MatterDevi...nViewModel D  **** ViewModel getDevicePtr newly created devicePtr : -5476376612487978736 for deviceId : ffaf6a8ed997
> 2024-02-14 14:02:29.127  2542-2542  MatterDevi...nViewModel D  MATTER: getOnOffClusterForDevice devicePtr : -5476376612487978736 for deviceId : ffaf6a8ed997
> 2024-02-14 14:02:29.129  2542-2542  DMG         D  SendReadRequest ReadClient[0xb400007cba018f00]: Sending Read Request
> 2024-02-14 14:02:29.130  2542-2542  EM          D  <<< [E:38914i S:47052 M:13407320] (S) Msg TX to 1:000000000000010E [F904] [UDP:192.168.29.35%wlan0:5540] --- Type 0001:02 (IM:ReadRequest)
> 2024-02-14 14:02:29.130  2542-2542  DMG         D  MoveToState ReadClient[0xb400007cba018f00]: Moving to [AwaitingIn]
> 2024-02-14 14:02:29.131  2542-2542  MatterDevi...nViewModel D  **** sendSubscribeOnOff fun entered
> 2024-02-14 14:02:29.132  2542-2542  MatterDevi...nViewModel D  **** sendsubscribe method: devpointer size:1 devid:ffaf6a8ed997
> 2024-02-14 14:02:29.133  2542-2542  MatterDevi...nViewModel D  **** getDevicePtr for :ffaf6a8ed997 / -5476376612487978736 size:1
> 2024-02-14 14:02:29.134  2542-2542  EM          D  <<< [E:38915i S:47052 M:13407321] (S) Msg TX to 1:000000000000010E [F904] [UDP:192.168.29.35%wlan0:5540] --- Type 0001:03 (IM:SubscribeRequest)
> 2024-02-14 14:02:29.134  2542-2542  DMG         D  MoveToState ReadClient[0xb400007cba019500]: Moving to [AwaitingIn]
> 2024-02-14 14:02:29.205  2542-2974  EM          D  >>> [E:38915i S:47052 M:256099959 (Ack:13407321)] (S) Msg RX from 1:000000000000010E [F904] --- Type 0001:01 (IM:StatusResponse)
> 2024-02-14 14:02:29.205  2542-2974  EM          D  Found matching exchange: 38915i, Delegate: 0xb400007cba019510
> 2024-02-14 14:02:29.205  2542-2974  EM          D  Rxd Ack; Removing MessageCounter:13407321 from Retrans Table on exchange 38915i
> **2024-02-14 14:02:29.205  2542-2974  DMG         D  StatusResponseMessage =
> 2024-02-14 14:02:29.205  2542-2974  DMG         D  {
> 2024-02-14 14:02:29.205  2542-2974  DMG         D  	Status = 0x80,
> 2024-02-14 14:02:29.205  2542-2974  DMG         D  	InteractionModelRevision = 1
> 2024-02-14 14:02:29.205  2542-2974  DMG         D  }**
> 2024-02-14 14:02:29.205  2542-2974  IM          D  Received status response, status is 0x80
> 2024-02-14 14:02:29.206  2542-2974  EM          D  <<< [E:38915i S:47052 M:13407322 (Ack:256099959)] (S) Msg TX to 1:000000000000010E [F904] [UDP:192.168.29.35%wlan0:5540] --- Type 0001:01 (IM:StatusResponse)
> 2024-02-14 14:02:29.206  2542-2974  DMG         D  MoveToState ReadClient[0xb400007cba019500]: Moving to [      Idle]
> 2024-02-14 14:02:29.206  2542-2974  DMG         D  Will try to resubscribe to 01:000000000000010E at retry index 0 after 0ms due to error **IM Error 0x00000580: General error: 0x80**
> 2024-02-14 14:02:29.207  2542-2974  MatterDevi...nViewModel D  **** sendSubscribeOnOff::ResubscriptionAttemptCallback::onResubscriptionAttempt terminationCause : 1408, nextResubscribeIntervalMsec : 0
> 2024-02-14 14:02:29.207  2542-2974  DMGD  OnResubscribeTimerCallback: ForceCASE = 0
> 
> 2024-02-14 14:02:29.208  2542-2974  EM          D  <<< [E:38916i S:47052 M:13407323] (S) Msg TX to 1:000000000000010E [F904] [UDP:192.168.29.35%wlan0:5540] --- Type 0001:03 (IM:SubscribeRequest)
> 2024-02-14 14:02:29.208  2542-2974  DMG         D  MoveToState ReadClient[0xb400007cba019500]: Moving to [AwaitingIn]
> 2024-02-14 14:02:29.214  2542-2542  MatterDevi...rollerView D  mMatterDeviceObserver::onChanged deviceId : ffaf6a8ed997, isConnected : false
> 2024-02-14 14:02:29.223  2542-2974  EM           D  >>> [E:38914i S:47052 M:256099960 (Ack:13407320)] (S) Msg RX from 1:000000000000010E [F904] --- Type 0001:05 (IM:ReportData)
> 2024-02-14 14:02:29.223  2542-2974  EM           D  Found matching exchange: 38914i, Delegate: 0xb400007cba018f10
> 2024-02-14 14:02:29.223  2542-2974  EM           D  Rxd Ack; Removing MessageCounter:13407320 from Retrans Table on exchange 38914i
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  ReportDataMessage =
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  {
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  	AttributeReportIBs =
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  	[
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  		AttributeReportIB =
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  		{
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  			AttributeStatusIB =
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  			{
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  				AttributePathIB =
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  				{
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  					Endpoint = 0x1,
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  					Cluster = 0x6,
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  					Attribute = 0x0000_0000,
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  				}
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  					
> **2024-02-14 14:02:29.223  2542-2974  DMG          D  				StatusIB =
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  				{
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  					status = 0x7e,
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  				},**
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  				
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  			},
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  			
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  		},
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  		
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  	],
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  	
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  	SuppressResponse = true, 
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  	InteractionModelRevision = 1
> 2024-02-14 14:02:29.223  2542-2974  DMG          D  }
> 2024-02-14 14:02:29.224  2542-2542  MatterDevi...rollerView D  refreshUI for deviceId : ffaf6a8ed997 name : Matter Device
> 2024-02-14 14:02:29.225  2542-2974  MatterDevi...nOffStatus D  *** getOnOffStatus::onError status for ffaf6a8ed997 ex : **chip.devicecontroller.ChipClusterException: CHIP cluster error: 126**

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

a9769a8150d972c7150f857017dc2e0e170643cb

### Platform

android

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/blob/master/src/protocols/interaction_model/StatusCodeList.h#L34C1-L34C76
0x7e means unsupported access....

You need factory reset the DUT, right? if you wanna re-commissioning the same device....
