### ISSUE TITLE
[ICD] Add ActiveModeDuration in ICD Client Storage,

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#32190]
the user case is that when controller, for example, chip-tool/android chip-tool queue IM operations, once check-in message comes,  controller flush IM operations one by one, then stay active based upon ActiveModeDuration, after ActiveModeDuration expires or timeout for subscription happens assume you run subscription with LIT, controller would do automatically queue

**Comment by bzbarsky-apple** [comment]
> then stay active based upon ActiveModeDuration, after ActiveModeDuration expires or timeout for subscription happens assume you run subscription with LIT, controller would do automatically queue

I don't understand what this is trying to say.

**Comment by turon** [comment]
WG: how one client with one ecosystem can send back-to-back to a single ICDs.  Needs to know how long the ICD will stay up, but calculated remaining time requires `ActiveModeThreshold` which is not being stored on client side.

**Comment by yunhanw-google** [comment]
closed it since we don't need this any more
