### ISSUE TITLE
Does chip-tool provide a cluster or method to "getCurrentFabricIndex"?

### ISSUE THREAD

**Issue by whqxbs** [project-chip/connectedhomeip#32218]
### Test issue(s)

In my research on the Matter for Android, I noticed that the fabric index is used to determine if a fabric "**isCurrent**" to the app.

I didn't find a command to query the index of the current fabric(**getCurrentFabricIndex**) when using chip-tool (e.g. command `chip-tool operationalcredentials read fabrics ${NODE_ID} 0 --fabric-filtered false`) the result doesn't mention the current fabric, so I have to make my own judgment.

Does chip-tool provide a cluster or method to "getCurrentFabricIndex"?

Looking forward to your reply! :)

**Comment by bzbarsky-apple** [comment]
@whqxbs Does
```
chip-tool operationalcredentials read current-fabric-index ${NOD_ID} 0
```
not do what you want?

**Comment by bzbarsky-apple** [comment]
And in particular, are you trying to get the fabric index of the fabric on the _server_ or on the _client_?

**Comment by whqxbs** [comment]
> @whqxbs Does
> 
> ```
> chip-tool operationalcredentials read current-fabric-index ${NODE_ID} 0
> ```
> 
> not do what you want?

As shown in the figure I have queried the fabric list of a certain matter device with the chiptool command `chip-tool operationalcredentials read current-fabric-index ${NODE_ID} 0`, but I don't have a way to tell directly which is the fabric of the **chiptool** that is **currently in use**, so the result doesn't say directly what the `FabricIndex` of the **current chiptool** is.
<img width="536" alt="fabric1" src="https://github.com/project-chip/connectedhomeip/assets/45973939/646a2ba3-5899-4102-aca2-3c3cb850e166">

**Comment by whqxbs** [comment]
> And in particular, are you trying to get the fabric index of the fabric on the _server_ or on the _client_?

I'm guessing server? Let me describe a scenario where I've paired a Matter device (called B) with a chiptool (called A) and I'm looking at B's fabric info on A.

**Comment by bzbarsky-apple** [comment]
Then
 ```
chip-tool operationalcredentials read current-fabric-index ${NODE_ID} 0
```
should do what you want.

**Comment by whqxbs** [comment]
It works! Thank you!
