### ISSUE TITLE
[TC-CNET-4.4] Python script is not matching with test plan

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#32219]
### Description

**TC-CNET-4.4 Python test script is not matching with the Test plan:**

- Test step number has to be updated as per test plan.
- In Step 2c, the test plan says `Turn off the Wi-Fi access points, wait 3 seconds. Sending ScanNetworks Command to the DUT with SSID field set to PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID and Breadcrumb field set to 2 from the TH`. 
- But in script, the SSID field is used as `random ssid` instead of `PIXIT.CNET.WIFI_1ST_ACCESSPOINT_SSID` and there is no provision to turning off the wifi access point.

**Python Script Reference:**

![image](https://github.com/project-chip/connectedhomeip/assets/95559513/45377a75-d50a-41c4-991e-6e5753a290cb)

**Test Plan Reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/network_commissioning.adoc#tc-cnet-4-4-wi-fi-verification-for-scannetworks-command-dut-server

### Platform

raspi

**Comment by cecille** [comment]
Please see https://github.com/CHIP-Specifications/chip-test-plans/pull/3991, looks like the test plan PR did not get merged yet. Original test plan was not actually testable at all. If you turn off the access point, you can't send a command so I'm not sure how that was actually being tested.

**Comment by Survensa** [comment]
Test plan fixed and now python script is matching with the test plan.
