### ISSUE TITLE
[Bug] Failed to build SDK docker image

### ISSUE THREAD

**Issue by jscarey1** [project-chip/connectedhomeip#32225]
### Describe the bug

Failed to build SDK DOCKER Image

### Steps to reproduce the behavior

Follow steps to Substitute the SDK’s docker image and update sample apps using SDK_DOCKER_TAG: 0ff709f25f6a7af68314c1b0a147a76c30c234f6

### Expected behavior

Build successfully

### Log files

250.2 /bloaty/tests/bloaty_test.cc: In member function 'virtual void BloatyTest_InputFiles_Test::TestBody()':
250.2 /bloaty/tests/bloaty_test.cc:278:69: warning: 'size2' may be used uninitialized in this function [-Wmaybe-uninitialized]
250.2   278 |                                              static_cast<int>(size1 + size2))});
250.2       |                                                               ~~~~~~^~~~~~~
250.2 /bloaty/tests/bloaty_test.cc:257:52: warning: 'size1' may be used uninitialized in this function [-Wmaybe-uninitialized]
250.2   257 |                  {std::make_tuple(file1, kUnknown, static_cast<int>(size1)),
250.2       |                                                    ^~~~~~~~~~~~~~~~~~~~~~~
250.4 [100%] Linking CXX executable bloaty_test
250.6 [100%] Built target bloaty_misc_test
250.7 [100%] Linking CXX executable bloaty_test_pe
250.9 [100%] Built target range_map_test
251.5 [100%] Built target bloaty_test_pe
251.6 [100%] Built target bloaty_test
251.6 + make install
251.6 [  0%] Built target gtest
251.6 [  1%] Built target gtest_main
251.6 [  8%] Built target re2
251.6 [ 26%] Built target capstone-static
251.6 [ 50%] Built target libprotobuf
251.7 [ 74%] Built target libprotoc
251.7 [ 75%] Built target protoc
251.7 [ 86%] Built target libbloaty
251.7 [ 86%] Built target gmock
251.7 [ 87%] Built target range_map_test
251.7 [ 88%] Built target bloaty_misc_test
251.7 [ 89%] Built target bloaty_test_pe
251.7 [ 89%] Built target bloaty_test
251.8 [ 89%] Built target bloaty
251.8 [ 90%] Built target fuzz_test
251.8 [ 99%] Built target libprotobuf-lite
251.8 [100%] Built target gmock_main
251.8 Install the project...
251.8 -- Install configuration: "RelWithDebInfo"
251.8 -- Installing: /usr/local/bin/bloaty
251.8 -- Installing: /usr/local/lib/Bloaty/BloatyTargets.cmake
251.8 -- Installing: /usr/local/lib/Bloaty/BloatyTargets-relwithdebinfo.cmake
251.8 -- Installing: /usr/local/include/re2/filtered_re2.h
251.8 -- Installing: /usr/local/include/re2/re2.h
251.8 -- Installing: /usr/local/include/re2/set.h
251.8 -- Installing: /usr/local/include/re2/stringpiece.h
251.8 -- Installing: /usr/local/lib/libre2.a
251.8 -- Installing: /usr/local/lib/cmake/re2/re2Config.cmake
251.8 -- Installing: /usr/local/lib/cmake/re2/re2Config-relwithdebinfo.cmake
251.8 -- Installing: /usr/local/include/capstone/arm64.h
251.8 -- Installing: /usr/local/include/capstone/arm.h
251.8 -- Installing: /usr/local/include/capstone/capstone.h
251.8 -- Installing: /usr/local/include/capstone/evm.h
251.8 -- Installing: /usr/local/include/capstone/mips.h
251.8 -- Installing: /usr/local/include/capstone/ppc.h
251.8 -- Installing: /usr/local/include/capstone/x86.h
251.8 -- Installing: /usr/local/include/capstone/sparc.h
251.8 -- Installing: /usr/local/include/capstone/systemz.h
251.8 -- Installing: /usr/local/include/capstone/xcore.h
251.8 -- Installing: /usr/local/include/capstone/m68k.h
251.8 -- Installing: /usr/local/include/capstone/tms320c64x.h
251.8 -- Installing: /usr/local/include/capstone/m680x.h
251.8 -- Installing: /usr/local/include/capstone/mos65xx.h
251.8 -- Installing: /usr/local/include/capstone/platform.h
251.8 -- Installing: /usr/local/lib/libcapstone.a
251.9 -- Installing: /usr/local/lib/libprotobuf-lite.a
251.9 -- Installing: /usr/local/lib/libprotobuf.a
252.3 -- Installing: /usr/local/lib/libprotoc.a
253.1 CMake Error at third_party/protobuf/cmake/cmake_install.cmake:54 (file):
253.1   file INSTALL cannot copy file
253.1   "/bloaty/build/third_party/protobuf/cmake/libprotoc.a" to
253.1   "/usr/local/lib/libprotoc.a": Success.
253.1 Call Stack (most recent call first):
253.1   cmake_install.cmake:84 (include)
253.1 
253.1 
253.1 make: *** [Makefile:93: install] Error 1
------
Dockerfile:144
--------------------
 143 |     # Install bloat comparison tools
 144 | >>> RUN set -x \
 145 | >>>     && git clone https://github.com/google/bloaty.git \
 146 | >>>     && mkdir -p bloaty/build \
 147 | >>>     && cd bloaty/build \
 148 | >>>     && cmake ../ \
 149 | >>>     && make -j8 \
 150 | >>>     && make install \
 151 | >>>     && cd ../.. \
 152 | >>>     && rm -rf bloaty \
 153 | >>>     && : # last line
 154 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c set -x     && git clone https://github.com/google/bloaty.git     && mkdir -p bloaty/build     && cd bloaty/build     && cmake ../     && make -j8     && make install     && cd ../..     && rm -rf bloaty     && : # last line" did not complete successfully: exit code: 2

### Environment

TH = v2.10-beta2.2+spring2024
SDK_DOCKER_TAG = 0ff709f25f6a7af68314c1b0a147a76c30c234f6
Ubuntu 22.04.3 LTS

**Comment by Alami-Amine** [comment]
It seems the information in this Issue is outdated, will close for now
