### ISSUE TITLE
[BUG] [1.2.0.1] chiptool fails to load somes CD certificates

### ISSUE THREAD

**Issue by caipiblack** [project-chip/connectedhomeip#32337]
### Reproduction steps

1. Download the matter-stack (connectedhomeip) using v1.2.0.1 tag
2. Build chiptool

At this point:
1. Do a random command with `--cd-trust-store-path` to check that when you use the path `credentials/development/cd-certs` it's okay:
```
./chip-tool pairing unpair 1 --cd-trust-store-path "/path_to/connectedhomeip-v1.2.0.1/credentials/development/cd-certs"
```
2. Create a temporary directory and copy (only) the `CSA_Matter_CD_Signing_Key_*.cert.der` files to this directory:
```
rm -rf /tmp/tmp-cd && mkdir /tmp/tmp-cd
cp credentials/development/cd-certs/CSA_Matter_CD_Signing_Key_00*.der /tmp/tmp-cd/
```
3. Run chip-tool again using this new directory:
```
./chip-tool pairing unpair 1 --cd-trust-store-path "/tmp/tmp-cd"
```

At this point you will get this message:

```
CHIP:TOO: Warning: no CD signing certs found in path: /tmp/tmp-cd, only defaults will be used
```

The warning appear because only `Chip-Test-CD-Cert.der` and `CSA_Matter_Certificate_and_Testing_Root.cert.der` are successfully parsed using `chip::Credentials::LoadAllX509DerCerts(cdTrustStorePath)`. The certificates `CSA_Matter_CD_Signing_Key_*.cert.der` are not recognised.

The problem is that in `VerifyAttestationCertificateFormat()`, the function `X509_get_pathlen(x509Cert)` returns 0.

I don't know if it's normal or not, it's not really clear to me. 

Attached you will find the CD certificates that we get from DCL that are also not "recognised":

[certs.zip](https://github.com/project-chip/connectedhomeip/files/14418159/certs.zip)

### Bug prevalence

100%

### GitHub hash of the SDK that was being used

181b0cb14ff007ec912f2ba6627e05dfb066c008

### Platform

other

**Comment by bzbarsky-apple** [comment]
Why are we ever running `VerifyAttestationCertificateFormat()` on non-attestation certs?
