### ISSUE TITLE
[Darwin] MTRDevice should detect device configuration change and inform delegate

### ISSUE THREAD

**Issue by jtung-apple** [project-chip/connectedhomeip#32353]
As title says. Part of this is to investigate what are all the necessary / sufficient signals for this, and how it should be conveyed.

**Comment by bzbarsky-apple** [comment]
Some thoughts on what might be relevant here:

1. PartsList changes.
2. AcceptedCommandList changes.
3. AttributeList changes.
4. DeviceTypeList changes.
5. ClusterRevision changes.
6. FeatureMap changes.

**Comment by nivi-apple** [comment]
Following are the changes that were tracked.
PartsList changes.
AcceptedCommandList changes -> Cluster revision should be updated for this.
AttributeList changes  -> Cluster revision should be updated for this.
DeviceTypeList changes.
ClusterRevision changes.
FeatureMap changes.
ServerList is needed for changes in clusters that are supported per endpoint
