### ISSUE TITLE
Message Security

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#3253]
#### Problem
Group security requires low level encryption/decryption pipeline to be implemented.

 #### Proposed Solution
Implement low levels of Message Security as defined in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/241.

**Comment by woody-apple** [comment]
Covered in:
https://github.com/project-chip/connectedhomeip/issues/1818
https://github.com/project-chip/connectedhomeip/issues/1819
https://github.com/project-chip/connectedhomeip/issues/1820
https://github.com/project-chip/connectedhomeip/issues/1821

**Comment by turon** [comment]
Don't agree that implementation of encryption / decryption details is covered in those 4 "key management" issues.

**Comment by woody-apple** [comment]
Can you please elaborate what is needed in addition specifically? We're trying to narrow down issues and clarify what's required.
