### ISSUE TITLE
[Workflow]  the QEMU tests are still failing in CI 

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#32587]
### Workflow issues

1.
2.
3.
...
https://github.com/project-chip/connectedhomeip/actions/workflows/qemu.yaml?query=branch%3Amaster

### Platform

esp32

**Comment by andy31415** [comment]
Do we have the logs of what was happening here? the link seems to show all actions (which now are green) and I cannot find an example failure with logs.

**Comment by andy31415** [comment]
I see some failures with `The hosted runner: GitHub Actions ... lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.`

was this the error? Something else?
