### ISSUE TITLE
[BUG] The XML file of Illuminance Measurement Cluster has errors

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#32599]
### Reproduction steps

check the xml file : https://github.com/project-chip/connectedhomeip/blob/v1.2.0.0/src/app/zap-templates/zcl/data-model/chip/illuminance-measurement-cluster.xml

0x0004 should be null, but default is 0xff
<img width="1508" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/b5f774fb-1808-459b-823b-3eed622fc160">

The specifications (1.0 and 1.2) describe as below
<img width="638" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/c6998687-e07f-4466-85cb-d286af28e702">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

v1.2.0.0 and v1.0.0

**Comment by bzbarsky-apple** [comment]
Ignoring that "default" means different things in the spec and in this XML, 0xff is how the XML represents null for an unsigned 8-bit type.
