### ISSUE TITLE
[BUG] The XML file of Door lock  Cluster has error

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#32594]
### Reproduction steps

check the xml file : https://github.com/project-chip/connectedhomeip/blob/v1.2.0.0/src/app/zap-templates/zcl/data-model/chip/door-lock-cluster.xml
Lack **NumberOfLogRecordsSupported** attribute
The specifications (1.0 and 1.2) describe as below
<img width="660" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/9e8d3350-ef02-4fe3-86a2-ae79acd4b8d4">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

v1.2.0.0 and v1.0.0

**Comment by bzbarsky-apple** [comment]
I filed https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/9055 to get the specification to be a little clearer here.

**Comment by bzbarsky-apple** [comment]
@Agatha2333 You would need access to the spec repository; please contact the CSA about that.

What the issue says is:

> Door lock LOG feature should be removed
>
> It's not allowed to be supported in Matter, since Matter supports events. We should just remove it and all the things
> dependent on it... People keep filing issues about it not being implemented, which wastes everyone's time.
