### ISSUE TITLE
[BUG] The xml file of Binding cluster has a parameter error

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#32592]
### Reproduction steps

The Specification provides detailed descriptions for each field within the TargetStruct, including operational conditions (e.g., Node and Endpoint fields must be present together, Group field should not be present with Endpoint). The XML structure defines these fields and their types but lacks the descriptive context found in the PDF.

https://github.com/project-chip/connectedhomeip/blob/v1.2.0.0/src/app/zap-templates/zcl/data-model/chip/binding-cluster.xml#L34C3-L35C13
<img width="1270" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/937106af-74c3-41a2-afa7-29420407af79">

Specification :

<img width="718" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/a89fa209-9884-431c-915d-fa6852090c9e">

the parameter should be :  List[node-id, endpoint-id, cluster-id] or List[group-id].

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

v1.2.0.0 and v1.0.0

**Comment by bzbarsky-apple** [comment]
This XML format does not have a way to express anything other than "optional" and "required".
