### ISSUE TITLE
[BUG] The XML file of Thermostat User Interface Configuration Cluster has errors

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#32608]
### Reproduction steps

check the xml file : https://github.com/project-chip/connectedhomeip/blob/v1.2.0.0/src/app/zap-templates/zcl/data-model/chip/thermostat-user-interface-configuration-cluster.xml

1. 0x0000 attribute has default error
<img width="1478" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/9b58ce36-1285-49c4-9a40-4615d45797df">
The specifications (1.0 and 1.2) describe as below
<img width="658" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/8ea48f6a-2f76-4b1c-8494-36ab683ac8b4">

2. The data type of the parameter in 0x0002 Attribute is wrong
<img width="1404" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/80809593-27a9-454e-a9c7-af19203626eb">
The specifications (1.0 and 1.2) describe as below
<img width="1091" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/509b178c-24a7-428b-b3b7-753325f0263e">
****

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

v1.2.0.0 and v1.0.0

**Comment by bzbarsky-apple** [comment]
> but the data type of ScheduleProgrammingVisibilityEnum will be ignored ?

@Agatha2333 I'm not sure what you are asking here.  What will be ignored by what entity?
