### ISSUE TITLE
[BUG] The XML file of Proxy Discovery Cluster has an error

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#32606]
### Reproduction steps

check the xml file : https://github.com/project-chip/connectedhomeip/blob/v1.2.0.0/src/app/zap-templates/zcl/data-model/chip/proxy-discovery-cluster.xml 

Lack command 
<img width="638" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/c5be8847-4599-4a7c-a9c8-9cc103f6c7fe">
The specifications (1.0 and 1.2) describe as below
<img width="705" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/2cf5f8af-7844-4247-bf40-c4d038066809">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

v1.2.0.0 and v1.0.0

**Comment by bzbarsky-apple** [comment]
The Proxy bits are provisional and not implemented and about to be removed from the spec.
