### ISSUE TITLE
[BUG] The XML file of OnOff Cluster has errors

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#32603]
### Reproduction steps

check the xml file : https://github.com/project-chip/connectedhomeip/blob/v1.2.0.0/src/app/zap-templates/zcl/data-model/chip/onoff-cluster.xml

1. The EffectVariant parameter of Command 0x40 only accept emun8
<img width="951" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/d1a8f9b6-c210-4c61-b1c1-b64a7ffbc46a">
The specifications (1.0 and 1.2) describe as below
<img width="652" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/5017fdd5-750e-4785-aefd-1bf23efcb260">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

v1.2.0.0 and v1.0.0

**Comment by bzbarsky-apple** [comment]
This is fixed in https://github.com/project-chip/connectedhomeip/blob/d2eab7f07ae9289fe14aa7e13dba7e64904ef80e/src/app/zap-templates/zcl/data-model/chip/onoff-cluster.xml (tip of master from today).
