### ISSUE TITLE
[BUG] The XML file of Proxy Configuration Cluster has an error

### ISSUE THREAD

**Issue by Agatha2333** [project-chip/connectedhomeip#32605]
### Reproduction steps

check the xml file : https://github.com/project-chip/connectedhomeip/blob/v1.2.0.0/src/app/zap-templates/zcl/data-model/chip/proxy-configuration-cluster.xml
lack one attribute 
<img width="694" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/eb00d339-958b-43ea-be0e-7052c24db71c">
The specifications (1.0 and 1.2) describe as below
<img width="662" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/62049491/46bddace-3550-4c96-84c8-8eeab068ce63">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

v1.2.0.0 and v1.0.0

**Comment by bzbarsky-apple** [comment]
The Proxy bits are provisional and not implemented and about to be removed from the spec.
