### ISSUE TITLE
Sort out what to do with HAL tokens in Silicon Labs code

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3275]
#### Problem
"IAS Zone" server cluster uses `halCommonGetToken`/`halCommonSetToken` and we don't have those implemented so far.

 #### Proposed Solution
Figure out whether we actually need those bits and if so how to implement them.

**Comment by jonsmirl** [comment]
Not implementing halCommonGetToken/halCommonSetToken also disables part of the on/off cluster.
OnWithRecallGlobalScene  and OffWithEffect

The existing code appears to be storing these on/off global scenes in RAM. Check cluster/scene/scene.h

**Comment by bzbarsky-apple** [comment]
Yes, scenes are not supported at all in Matter 1.0.

**Comment by bzbarsky-apple** [comment]
Scenes is being switched to Matter storage.
