### ISSUE TITLE
[Feature] Thermostat seems to be missing a lot of essential alarms.

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#32786]
### Feature description

The thermostat cluster is missing many essential alarms. I only see three defined. Are these events indicated some other way?

![image](https://github.com/project-chip/connectedhomeip/assets/14943/0d78b73c-ae25-4fe6-a75b-a7aa2795093b)

Things like
a) call for cool, but not cooling
b) call for heat, but not heating
c) heat exceed limit (heat did not shut off)
d) cool exceed limit (cool did not shut off)
e) run time exceed (heat or cool running for hours with no effect)
f) maximum temp exceed (area got too hot)
g) minimum temp exceed (area got too cold, freeze)
h) filter lifetime exceeded

These alarms should trigger events, and then those events go back to controllers which generate an email or text message via script.

### Platform

all

**Comment by bzbarsky-apple** [comment]
The Alarm stuff is not part of Matter at all.  It's Zigbee-only.
