### ISSUE TITLE
[Test Failed] What method should be used to pair the devices being shared? pairDevice cannot be paired and always fails. Bluetooth is not turned on in the device sharing status.

### ISSUE THREAD

**Issue by JasonClark2** [project-chip/connectedhomeip#32782]
### Test issue(s)

1.When I use the openPairingWindowWithPINCallback method to open device sharing, 

2.public void pairDevice(BluetoothGatt bleServer, int connId, long deviceId, long setupPincode, NetworkCredentials networkCredentials) {
         this.pairDevice(bleServer, connId, deviceId, setupPincode, (byte[])null, networkCredentials);
     }
3.It always fails. This method can only pair the device for initialization. When the device is in the sharing state, it cannot be paired through this method. So what method do I need to use to pair the shared device?
...

### Platform

android

**Comment by joonhaengHeo** [comment]
@JasonClark2 
You can use `pairDeviceWithCode` method or `pairDeviceWithAddress` method after `discoverCommissionableNodes` in ChipDeviceController class.
