### ISSUE TITLE
Error occurs while building CHIP-TOOL and sample apps in new connectedhomeip

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#32795]
### Description

When attempting to build the sample apps and chip-tool on a Raspberry Pi (Linux platform) with the newly built connectedhomeip directory, the build fails, throwing the error mentioned below.

```
The target:
  //third_party/connectedhomeip/third_party/nlunit-test:nlunit-test
has a source file:
  //third_party/connectedhomeip/third_party/nlunit-test/repo/src/nlunit-test.c
which was not found.
___________________
ERROR at //third_party/connectedhomeip/third_party/perfetto/BUILD.gn:36:1: Source file not found.
source_set("sdk") {
^------------------
The target:
  //third_party/connectedhomeip/third_party/perfetto:sdk
has a source file:
  //third_party/connectedhomeip/third_party/perfetto/repo/sdk/perfetto.cc
which was not found.
___________________
ERROR at //third_party/connectedhomeip/third_party/perfetto/BUILD.gn:36:1: Source file not found.
source_set("sdk") {
^------------------
The target:
  //third_party/connectedhomeip/third_party/perfetto:sdk
has a source file:
  //third_party/connectedhomeip/third_party/perfetto/repo/sdk/perfetto.h
which was not found.
```

**Error Logs:** [Build_error.txt](https://github.com/project-chip/connectedhomeip/files/14819890/Build_error.txt)

**Note:**
However, when attempting to build the sample apps and chip-tool on a Raspberry Pi (Linux platform) with a previously built connectedhomeip directory, the build is successfully completed without any issues.

### Reproduction steps

_**Steps used to build new connectedhomeip directory**_ 
1. [git clone ](https://github.com/project-chip/connectedhomeip.git) https://github.com/project-chip/connectedhomeip.git
2. cd connectedhomeip
3. git pull
4. git checkout v1.3-branch
5. source scripts/bootstrap.sh
6. source scripts/activate.sh
7. scripts/examples/gn_build_example.sh      examples/all-clusters-app/linux/      examples/all-clusters-app/linux/out/all-clusters-app   chip_inet_config_enable_ipv4=false 

_**Steps used to update the previously built connectedhomeip directory**_ 

1. cd connectedhomeip
2. rm -rf .environment
3. git pull
4. git checkout v1.3-branch
5. source scripts/bootstrap.sh
6. source scripts/activate.sh
7. scripts/examples/gn_build_example.sh      examples/all-clusters-app/linux/      examples/all-clusters-app/linux/out/all-clusters-app   chip_inet_config_enable_ipv4=false 

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

5bb5c9e23d532cea40476fc0bd1d3008522792ba

### Platform

raspi

**Comment by jinbiaochenstayhungry** [comment]
seems like you clone of perfetto and nlunit-test had not successed .suggest you check it first.

**Comment by Survensa** [comment]
Issue resolved with the `git submodule sync && git submodule update --init` before bootstrap
