### ISSUE TITLE
[Test Failed] After connecting to the device through Android, I need to read the IP of the device, but sometimes what is read is IPv6, I need IPv4

### ISSUE THREAD

**Issue by JasonClark2** [project-chip/connectedhomeip#32804]
### Test issue(s)

1.deviceController.getIpAddress(nodeId)
2.deviceController.getNetworkLocation(nodeId).ipAddress
3.IPs obtained through devicecontrol have a chance of getting ipv6. How can I get ipv4?
...

### Platform

android

**Comment by bzbarsky-apple** [comment]
JasonClark2: Matter generally uses IPv6.  Some Matter devices (e.g. Thread ones) do not have an IPv4 address at all.
