### ISSUE TITLE
Building in XCode 12 for iOS simulator targets fails

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3281]
#### Problem
When I try to compile in XCode 12 for one of the iOS simulator targets (say iPhone 8), I get a link error like so:
```
ld: in /${HOME}/Library/Developer/Xcode/DerivedData/Darwin-gradnxuszkbudvafkyzpssssvewn/Build/Intermediates.noindex/CHIP.build/Debug iOS-iphonesimulator/CHIP.build/out/lib/libCHIP.a(libSetupPayload.SetupPayload.cpp.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
```

I checked older changesets, and before `b14e3e37d6038669cc46f849fc571b2f1e63c986` (switching XCode build to gn) the build would complete, but then XCode would complain that it couldn't run an arm64 binary in the simulator.

So it seems like going from XCode 11 to XCode 12 the simulator switched from running ARM binaries to x86_64 binaries?

 #### Proposed Solution
No idea offhand...

@rwalker-apple @bhaskar-apple @shana-apple @sagar-apple @andy31415

**Comment by bzbarsky-apple** [comment]
> So it seems like going from XCode 11 to XCode 12 the simulator switched from running ARM binaries to x86_64 binaries?

Or perhaps we switched to compiling arm64 because `$ARCHS_STANDARD` changed?

**Comment by andy31415** [comment]
I wressled with it and according to some google searches, it seems that historically simulators were x86_64 but arm macs may be coming so now the simulator seems to somehow crosscompile.

I got it working on my machine, but after a lot of trial and error (and unsure which of the fixes actually makes thins work). generally I tried to make everything just be x86_64 by:
  - updating valida ARCHS to include x86_64
  - add arm64 to excluded archs
  - did some manual add/remove frameworks and manual compiles and eventually it ran. Not convinced I could easily reproduce the success from scratch though

https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios
https://developer.apple.com/forums/thread/656509

**Comment by andy31415** [comment]
> > So it seems like going from XCode 11 to XCode 12 the simulator switched from running ARM binaries to x86_64 binaries?
> 
> Or perhaps we switched to compiling arm64 because `$ARCHS_STANDARD` changed?

This seems to be inline with what I read while trying to debug this issue - it now compiles both x64 and arm64 and our build setup does not like this.

**Comment by bzbarsky-apple** [comment]
So for extra confusion, it seems like `VALID_ARCHS` is only ARM things for some reason?

**Comment by rwalker-apple** [comment]
@andy31415 great work

I can look at this Monday
