### ISSUE TITLE
After Issue #300 Is Addressed, Move TestInetLayerDNS from noinst_PROGRAMS Back to check_PROGRAMS

### ISSUE THREAD

**Issue by gerickson** [project-chip/connectedhomeip#329]
After GitHub issue #300 is addressed, move the Inet layer unit and functional test, *TestInetLayerDNS* from `noinst_PROGRAMS` back to `check_PROGRAMS` in *src/inet/tests/Makefile.am*.

**Comment by gerickson** [comment]
@yunhanw-google, any updates on this?

**Comment by yunhanw-google** [comment]
Hi, Grant

The initial happy PR is in https://github.com/project-chip/connectedhomeip/pull/2319 with test_inet_multicast

**Comment by yunhanw-google** [comment]
It seems we are moving to gn build only for CHIP.

**Comment by gerickson** [comment]
Yes, those are functional tests; however, what about the standalone unit tests that are still broken and have been broken for 5+ months?

**Comment by gerickson** [comment]
Sure, we need to figure out the equivalent action in GN; regardless, the tests need to run.

**Comment by yunhanw-google** [comment]
> Sure, we need to figure out the equivalent action in GN; regardless, the tests need to run.

Thanks for the reply, yep, i have enabled the tests in both automake and build gn successfully.

**Comment by gerickson** [comment]
This has been deprecated through the deprecation of autotools-based builds and has been resolved in the GN-based build.
