### ISSUE TITLE
[Feature] XML Device Types define Endpoint Composition 

### ISSUE THREAD

**Issue by paulr34** [project-chip/connectedhomeip#32941]
### Feature description

ZAP utilizes the data model XML and has recently incorporated support for Parent Endpoints.

For ZAP to store Endpoint Composition into the database, it requires the Endpoint Composition to be specified in the Device Type XML.

For instance, the XML should accurately represent the specifications regarding Endpoint Composition. Notably, the current XML lacks any mention of the Temperature Controlled Cabinet being mandatory for a Refrigerator Device Type.

![Screenshot 2024-03-05 at 11 15 38 AM](https://github.com/project-chip/connectedhomeip/assets/64710345/d1d1f1b2-1a3c-4f89-a7c4-cc7f3c4ec29b)

Referencing the "old XML" [here](https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/matter-devices.xml#L2017-L2031) and the "new XML" [here](https://github.com/project-chip/connectedhomeip/blob/7bf764ab05eb4ef52b007666e822ba963f643922/data_model/device_types/Refrigerator.xml), it's evident that we need the Device Type to be defined as either "Tree" or "FullFamily" if the Device Type includes Endpoint Composition.

### Platform

all

**Comment by paulr34** [comment]
@bzbarsky-apple it makes sense based on previous discussion to do something like following:

Example 1

```
<endpointComposition>
         <type>fullFamily</type>
         <endpoint>
                    <deviceType> name of device type </deviceType>
         </endpoint>
</endpointComposition>
```
OR

Example 2

```
<endpointComposition>
         <endpoint>
                    <deviceType> name of device type </deviceType>
         </endpoint>
         <endpoint>
                    <deviceType> name of device type </deviceType>
         </endpoint>
</endpointComposition>
```


ZAP can parse the XML in this case and know 
1. This Device Type has Endpoint Composition
2. This Device Type is fullFamily or not by the "type"
3. If the "type" is not "fullFamily" then it is "tree" like in Example 2


Alternatively we could put "type" for tree as well like:

Example 3

```
<endpointComposition>
         <type> tree </type>
         <endpoint>
                    <deviceType> name of device type </deviceType>
         </endpoint>
         <endpoint>
                    <deviceType> name of device type </deviceType>
         </endpoint>
</endpointComposition>
```


I might be out of date or missing some context, but If something along these lines is added to the XML, ZAP can parse and add to the database per Device Type

**Comment by paulr34** [comment]
It's logical to assign an attribute to an endpoint XML tag to indicate whether it's optional. In the example below, the first endpoint is marked as mandatory (true), while the second one is not (false), making it optional. Despite not being mandatory, the presence of the second endpoint in the table implies that it's allowed.

Something along these lines makes sense to me:

```
<endpointComposition>
         <endpoint mandatory=true>
                    <deviceType> name of device type </deviceType>
         </endpoint>
         <endpoint mandatory=false>
                    <deviceType> name of device type </deviceType>
         </endpoint>
</endpointComposition>
```

**Comment by paulr34** [comment]
If there are Conformance rules like how there are with "features" we could add something like
`      <optionalConform>
        <notTerm>
          <orTerm>
            <feature name="LT"/>
            <feature name="DF"/>
          </orTerm>
        </notTerm>
      </optionalConform>`

Regarding Device Type or Id, from a ZAP perspective either *could* work but let me double check and get back to you tomorrow.

**Comment by paulr34** [comment]
It makes most sense for ZAP to consume the Device Type ID rather than the name

**Comment by bzbarsky-apple** [comment]
That seems pretty reasonable.
