### ISSUE TITLE
Move kVendorIdPresent flag from message header to exchange header

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#3306]
#### Problem
Currently, kVendorIdPresent is defined as message header flag in code, but it is defined as the exchange header in spec.

 #### Proposed Solution
Align the message header encoding/decoding with the MessageFormat defined in the latest spec:  https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/secure_channel/Message_Format.adoc

**Comment by woody-apple** [comment]
@yufengwangca  Can we break this into actionable updates so we can separate tasks?
eg: " as kVendorIdPresent should be defined in the ExchangeHeader instead of MessageHeader"

**Comment by yufengwangca** [comment]
The current design re-use the flags, it has certain advantages than splitting it clearly out. Keep the current design for now until we see there is really need to refactor it.
