### ISSUE TITLE
[Release] Bluetooth device pairing doesn't work without installing Bluetooth profile

### ISSUE THREAD

**Issue by lvaky** [project-chip/connectedhomeip#33086]
### Build issue(s)

Hi, 
We are finalizing implementation of chiptool SDK  in our iOS application. I have some concern about publishing my app to the App Store,
At https://developer.apple.com/app-store/review/guidelines/ there is refence that say

> Apps that support Matter must use Apple’s support framework for Matter to initiate pairing. In addition, if you choose to use any Matter software component in your app other than the Matter SDK provided by Apple, the software component must be certified by the Connectivity Standards Alliance for the platform it runs on.

We didn't include Apple’s support framework for Matter, rather we are using chiptool approach.
Problem is that Bluetooth device pairing doesn't work without installing Bluetooth profile and enabling developer mode on mobile device.
Is this going to be a problem when we submit application to certification, or is it expected behavior, and it will be overcome when app is certified ?

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
Like the documentation says: you need to be using the MatterSupport framework.  The profile thing is there for testing purposes only.
