### ISSUE TITLE
Multiple mobile phones controlling the same device

### ISSUE THREAD

**Issue by AlbertLarry** [project-chip/connectedhomeip#33188]
I am developing my own Android application. Following the example of chip tool Android, pairing and control have been implemented.
Now I want to save some important configuration information on the server, so that when another phone downloads these configurations, it can directly connect and control the matter device.
Is there anything that can help me?

**Comment by joonhaengHeo** [comment]
@AlbertLarry 
If you issue NOC from outside (i.e., Server) and add ACL during commissioning, I think Device Control will be possible from multiple Controllers at the same time.

Refer,
https://github.com/project-chip/connectedhomeip/blob/c024e4f2770fd02b9877c1da2767f04f0ecd085b/src/controller/java/src/chip/devicecontroller/ControllerParams.java#L21

https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/src/chip/devicecontroller/ChipDeviceController.java#L95
