### ISSUE TITLE
TC-IDM-2.2  Step 34 error

### ISSUE THREAD

**Issue by kagami555** [project-chip/connectedhomeip#33193]
### Feature Area

Other

### Test Case

TC-IDM-2.2

### Reproduction steps

1. Compile and obtain chip-lighting-app through the command ./scripts/examples/gn_build_example.sh examples/lighting-app/linux out/ax 'target_cpu="arm" target_os="linux"',
2. Execute the application through the command ./chip-lighting-app --ble-device 0 --wifi
3. Use the command ./chip-tool pairing ble-wifi 12344321 TP-LINK_7249 20170201 62909270 1030 --paa-trust-store-path /var/paa-root-certs to use Raspberry Pi for matter configuration.
4. Execute the command: ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects":[112233], "targets": [{ "cluster ":31, "endpoint":0, "deviceType":null }]}]' 12344321 0
5. Execute the command: ./chip-tool any read-by-id 0xFFFFFFFF 0xFFFFFFFF 12344321 0 (this step reports an error, timeout)
6. Execute the command: ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects":[112233], "targets":null}]' 12344321 0
7. Execute the command: ./chip-tool any read-by-id 0xFFFFFFFF 0xFFFFFFFF 12344321 0 Normal operation

[device.log](https://github.com/project-chip/connectedhomeip/files/15128632/device.log)
[TC-IDM-2.2_rpi.log](https://github.com/project-chip/connectedhomeip/files/15128633/TC-IDM-2.2_rpi.log)

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

437c5743ef4eac87ec5f80114d295f71e8a4f0e0

### Platform

raspi, other

**Comment by cjandhyala** [comment]
closing the issue as the issue does not have clear details on exactly happening when the test is run. Feel free to re-open the issue, if there is any SDK fix required
