### ISSUE TITLE
[BUG] Node resolution attempt marked complete incorrectly.

### ISSUE THREAD

**Issue by su-shanka** [project-chip/connectedhomeip#33287]
### Reproduction steps

In MinMdns Resolver (Resolver_ImplMinimalMdns.cpp), when `resolver->Take()` fails for `ResolvedNodeData`, the corresponding active resolver is marked complete and `OnOperationalNodeResolved` is called with arbitrary garbage in `ResolvedNodeData`.

### Bug prevalence

NA

### GitHub hash of the SDK that was being used

fcfc9bc

### Platform

core

**Comment by bzbarsky-apple** [comment]
@andy31415

**Comment by andy31415** [comment]
@su-shanka do you have a path that makes Take fail?

The bug seems valid, however I also wonder under what operations we would have that code path taken.

**Comment by andy31415** [comment]
Basically what happens is that `Take` will verify that `IsActiveOperationalParse()` and return an error only in that case. The unchecked Take is on a `if IsActiveOperationalParse` branch, so Take would never fail.

I will fix the code to always look ok, however right now I am not sure there is a path to trigger the bad behavior.
