### ISSUE TITLE
[Test Failed] EFR32 TestExchange.cpp asserts

### ISSUE THREAD

**Issue by jmartinez-silabs** [project-chip/connectedhomeip#33373]
### Test issue(s)

While Running the test driver on efr32 hardware,
the device asserts in the test `TestExchange.cpp ; CheckBasicMessageRounTrip` in the function 

```
CHIP_ERROR ExchangeContext::SendMessage(Protocols::Id protocolId, uint8_t msgType, PacketBufferHandle && msgBuf,
                                        const SendFlags & sendFlags)
```
line 
`VerifyOrReturnError(mExchangeMgr != nullptr, CHIP_ERROR_INTERNAL);`

Before the assert, logs show events failing to get posted to the chip event queue because the queue is full. 
```
00> [00:00:13.921][error ][DL] Failed to post event to CHIP Platform event queue
00> [00:00:13.929][error ][DL] Failed to post event to CHIP Platform event queue
00> [00:00:13.936][info  ][-] src/messaging/tests/TestExchange.cpp:166: assertion failed: "delegate2.mReceivedMessageCount == 1"
```

### Platform

efr32

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs Is something supposed to be pumping that queue?  I would have expected `ctx.DrainAndServiceIO();` to do that sort of thing, but maybe the cut-down event loop it's using is broken on efr32?  If so, I expect lots of other message-send tests are failing there for similar reasons?

**Comment by jmartinez-silabs** [comment]
@bzbarsky-apple Trying to run any test under src/messaging/tests/BUILD.gn ran is the seemingly same issue.

We had a series of tests running fine on our hardware not long ago. 
Currently, there I am looking into  an issue where strangely no tests are run.. They are compiled and part of the binary, But nothing runs. I'm not sure what is occurring yet and therefore can't say if the event loop is generally broken on the ef32 test driver.

The only one running yesterday was actually `TestExchange`

```
python -m nl_test_runner.nl_test_runner -d /dev/cu.usbmodem0004402662211 -o out3.log


All tests completed
Total of all tests failed: 0 of 0
```

I'll try to find and fix it so all built tests are run then investigate the event loop
