### ISSUE TITLE
[Feature] Thermostat cluster is missing a feature for Humidifier support

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#33379]
### Feature description

.The Thermostat cluster needs an optional Feature for Humidifier support. Nothing complex, just ability to bind a Humidity Sensor and then a set point for turning the humidifier on/off. Will need some thought as to how to handle humidifiers vs dehumidifiers depending on climate.

### Platform

core

**Comment by bzbarsky-apple** [comment]
Not an SDK issue.   This would need to happen in the spec.

**Comment by bzbarsky-apple** [comment]
That said, note that the spec is in fact adding humidifiers/dehumidifers: see https://github.com/project-chip/connectedhomeip/issues/33384
