### ISSUE TITLE
[1.2] FabricDescriptorStruct type error in OperationalCredentialsCluster on Android Platform

### ISSUE THREAD

**Issue by elethiame** [project-chip/connectedhomeip#33400]
### Reproduction steps

1. invoke command readFabricsAttribute of OperationalCredentialsCluster
2. get result from android sdk:
`result: Endpoint 0: {
  Cluster 62: {
  Attribute 1: {"1:ARRAY-STRUCT":[{"1:BYTES":"BDx99TpkVj+pForMbMO+Tm1M7MiSiJvXND+rxiJ2cNnkQNYn0VqgLevB7uzyfIPvMS7h9YBfp9CpVDLgh1yLchc=","254:UINT":1,"2:UINT":4882,"3:UINT":1,"4:UINT":"89764395371061248","5:STRING":""}]}
  }`
3."4:UINT":"89764395371061248" : the data type is UINT, but we got a string result

### Bug prevalence

always

### GitHub hash of the SDK that was being used

181b0cb  

### Platform

android

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
> the data type is UINT, but we got a string result

That's because the integer is too big to be represented as a number in JavaScript (which only supports integers up to 2^53).

In theory JSON does not have that restriction, but in practice it does.
