### ISSUE TITLE
[Feature] Be able to update FileAttestationTrustStore during execution 

### ISSUE THREAD

**Issue by caipiblack** [project-chip/connectedhomeip#33417]
### Feature description

Hello,

We are using Matter in a Linux board (as commissioner).

We load the PAA certificates from a directory and we have a script that update this directory based on the DCL when we need (for exemple every 24h).

Currently **it seems** that we can't update the PAA/CD certificates during the "runtime" (after the initialisation of matter stack), so if we update the certificates we need to restart the software that run matter stack.

**It should be good if something is implemented that permits to update the PAA certificates during the matter-stack execution.**

This is the reasons **why we think it's currently not possible**:
1. We instanciate `FileAttestationTrustStore` on startup, so the certificates from the specified folder are loaded at instanciation.
2. We get the DAC verifier like this: `chip::Credentials::GetDefaultDACVerifier(trustStore)`
3. Then we use it.

The function `chip::Credentials::GetDefaultDACVerifier(trustStore)` say's:

```
/**
 * @brief Get a singleton implementation of a sample DAC verifier to validate device
 *        attestation procedure.
 *
 * @param[in] paaRootStore Pointer to the AttestationTrustStore instance to be used by implementation
 *                         of default DeviceAttestationVerifier. Caller must ensure storage is
 *                         always available while the DeviceAttestationVerifier could be used.
 *
 * @returns a singleton DeviceAttestationVerifier that satisfies basic device attestation procedure requirements.
 *          This has process lifetime, so the paaRootStore must also have
 *          process lifetime.  In particular, after the first call it's not
 *          possible to change which AttestationTrustStore is used by this verifier.
 */
```

It say's:

```
This has process lifetime, so the paaRootStore must also have process lifetime.
In particular, after the first call it's not possible to change which AttestationTrustStore is used by this verifier.
```

What is unclear:
- Is it possible to pass a static truststore object **that can be updated after calling this function** ?
- If yes, one possible solution (for us) is to re-implement  `FileAttestationTrustStore` and add a function to update `mPAADerCerts` ? (what do you think?) Did we have to do something else to take effect ?

Also some questions:
- Can you confirm that currently (AS-IS) It's not possible to update the PAA certificates when the matter stack is initialized ?
- If yes, is it wanted ? what is the reason ? Is it going to change ?

### Platform

all

**Comment by bzbarsky-apple** [comment]
The trust store will be asked any time a trust check needs to be made, right?  So if you change its internal state, that affects checks after that point.
