### ISSUE TITLE
examples/wifi-echo (ESP32): Abstract the button/display code

### ISSUE THREAD

**Issue by dhrishi** [project-chip/connectedhomeip#3341]
#### Problem
With addition of new ESP32 based boards, the wifi-echo example has quite some #ifdefs, depending on their hardware design or support.

 #### Proposed Solution
With reference to this comment https://github.com/project-chip/connectedhomeip/pull/3304#pullrequestreview-511751224, need to abstract out the button/display related code.

**Comment by holbrookt** [comment]
This doesn't seem necessary for 1.0. @dhrishi please re-label if I'm wrong

**Comment by dhrishi** [comment]
@holbrookt Yes, you are correct.

**Comment by dhrishi** [comment]
Fixed with https://github.com/project-chip/connectedhomeip/pull/15624
