### ISSUE TITLE
[1.2] TLV structure differences observed in spec and SDK

### ISSUE THREAD

**Issue by rohan-ifx24** [project-chip/connectedhomeip#33439]
### Reproduction steps

1. In Matter TLV structure sent from chiptool, it is expected that the “ExpiryLengthSeconds” is expected to be uint16_t and the value is 60 seconds. But there is a deviation observed like
Expected : 24 01 3C 00
Observed: 24 01 3C
I see the structure is optimized based on the value (since it fits in 1 byte), but this does not align with the spec. I would really appreciate the clarification for this.
![issue_1](https://github.com/project-chip/connectedhomeip/assets/161683535/e62afc3d-6beb-4ee1-83d4-eb872a6b0bb0)

2. On the PBKDF parameter response, the “S” flag is to be set to 0 as per spec. But when this is sent to the chiptool, it throws an error as the source node ID wasn’t included. 
![issue_2](https://github.com/project-chip/connectedhomeip/assets/161683535/77aa5643-a0af-4f5d-b9e4-bd9eafb1b495)

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

f63b505179fd326c2cb5df91eed330ecd71a39b8

### Platform

raspi

### Platform Version(s)

1.2

### Type

Spec Compliance Issue

**Comment by bzbarsky-apple** [comment]
The _interaction model_ type is `uint16`.

TLV encoding is allowed to encode signed/unsigned integers in any number of bytes that fit the value, and the encoding itself tells you how many bytes it is using.  This is explicitly spelled out in the Encoding section of the spec.  Specifically, section "10.3.1. Analog - Integer" says:

> The specific TLV element type (1-byte, 2-byte, 4-byte and 8-byte signed integer types) SHALL be selected automatically at runtime depending on the actual value.

> In this regard, the actual width of the over-the-wire type can be narrower than the width specified in schema.

> E.g. a 32-bit value defined in schema will be encoded to a 1-byte TLV signed integer type if the value doesn’t exceed (-128 to +127).

>Similarly, all unsigned integer schema types SHALL be encoded using the TLV unsigned integer type.
