### ISSUE TITLE
One problem about the definition of Vendor ID in Matter Specification Version 1.3 documentation.

### ISSUE THREAD

**Issue by whqxbs** [project-chip/connectedhomeip#33467]
### Documentation issues

**Page 828 in Matter Specification Version 1.3 documentation has the definition in the figure for `AdminVendorID Field`:**
![image](https://github.com/project-chip/connectedhomeip/assets/45973939/ac481979-2cc6-4550-961f-1239b75c7bad)
**I would like to know what is mentioned here "This value SHALL NOT be one of the reserved Vendor ID values defined in Table 1, 'Vendor ID Allocations '."** 

- **How to understand it?** 
- **And why can't I use the Vendor ID in Table 1?**

**Page 53 in Matter Specification Version 1.3 documentation has the Table 1, and all Vendor IDs in Table 1 are "reserved" as described in the documentation:**
![image](https://github.com/project-chip/connectedhomeip/assets/45973939/50d92f74-e983-4dff-a181-9806a75fef80)

- **I would like to know what happens if the Vendor ID from Table 1 is used in the AdminVendorID Field?**

Thank you very much for your answering!

**Comment by whqxbs** [comment]
I used the CHIP Tool's `--commissioner-vendor-id` parameter for the test of Vendor ID definition and I can specify any value for the Vendor ID. So I don't understand what the documentation means by "SHALL NOT be one of the reserved Vendor ID values defined in Table 1".

**Comment by bzbarsky-apple** [comment]
I think the intent is that it can't be 0 or one of the test values; it has to be an actual vendor id identifying the commissioner....   But either way, spec issues need to go in the spec repository (unfortunately not public).

I filed https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/9212 to track this; thank you for raising it!

**Comment by whqxbs** [comment]
Thank you! If there is any progress, I would appreciate it if you could reply here with an explanation of the documentation because of the not public spec issues. :)

**Comment by bzbarsky-apple** [comment]
I'll try, but I am not following the spec closely...
