### ISSUE TITLE
[Documentation] Source Node Id during comissioning

### ISSUE THREAD

**Issue by lava** [project-chip/connectedhomeip#33518]
### Documentation issues

The Matter specification states in `4.13.1.2. Protocol Details` that for all PASE messages

> The S Flag and DSIZ fields of the Message Flags SHALL be set to 0.

On the other hand, PASE messages are sent unencrypted and thus according to `4.12.1.1. Unsecured Session Context` the initiator should "enclose" (?) an ephemeral node id as the source node id:

> Ephemeral Initiator Node ID: Randomly selected for each session by the initiator from the Oper­ational Node ID range and enclosed by initiator as Source Node ID and responder as Destination Node ID.

This seems to be a contradiction, since a message cannot include a source node id if the S flag is set to 0.

Empirically, `chip-tool` ignores the first requirement and just sets the `S` flag to 1 for the `PBKDFParamRequest` message.

So, two questions:
1. Is this the intended behavior?
2. If yes, is it a bug in the Matter specification or did I miss some other paragraph that reconciles the two?

**Comment by Alami-Amine** [comment]
This was Fixed in the Spec for Matter-1.3 that was released in April 2024
The Text says in `4.13.1.2. Protocol Details`
>• In the PASE messages from the initiator, S Flag SHALL be set to 1 and DSIZ SHALL be set to 0.
>• In the PASE messages from the responder, S Flag SHALL be set to 0 and DSIZ SHALL be set to 1.

This ticket can be closed.
