### ISSUE TITLE
demand for event change state of occupancy cluster

### ISSUE THREAD

**Issue by Leo2442926161** [project-chip/connectedhomeip#33528]
### Documentation issues

Dear all,

I've noticed that the occupancy cluster doesn't has the event for attribute 0x0000, the hub will lost the records during the devices are being offline, I am wondering could you augment event for that cluster?
 
imagine this use-case:
we don't have specific motion sensor device type for security use in the spec so far, so most of device manufactures are using the occupancy cluster as generic motion sensor,  that would make the attribute more important.

Since it used as a security sensor, the users may interest in the records of occupancy  all the time. During our testing, the hub will lost the state of occupancy if  it changes during the occupancy lost its connection with hub due to some reasonable circumstances , or the sensor is doing CASE with hub.

Off the top of my head,  I think of the occupancy change event can solve this problem,  the hub can reads the records from the occupancy devices,  then shows to user or equivalent  way.

### Platform

other

**Comment by leorozendaal** [comment]
this is getting addressed in the 1.4 draft - PR [8981](https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/8981) adds this event
