### ISSUE TITLE
[Darwin] How to initialize MTRDeviceController with MTRKeypair

### ISSUE THREAD

**Issue by law-ko** [project-chip/connectedhomeip#33636]
### Reproduction steps

Hello,

we are trying to create and initialize `MTRDeviceController` by `Matter` Swift SDK but do not know how to create MTRKeypair. Is there any reference that we can follow or is the keypair something that we should request from CSA?

Here is the [link](https://developer.apple.com/documentation/matter/onboarding_a_matter_device) we are following.

Our testing code:
```
// Generate an IPK.
guard let ipk = NSMutableData(length: 16) else {
    return
}
let status = SecRandomCopyBytes(kSecRandomDefault, ipk.count, ipk.mutableBytes)

let param = MTRDeviceControllerStartupParams(ipk: ipk as Data, fabricID: 1, nocSigner: mtrkey) // how to create mtrkey??
self.mtr = MTRDeviceControllerFactory().createController(onNewFabric: param)
```

Thank you.

### Platform

darwin

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
You create the keypair yourself, however you want to.  It's just a public/private keypair to use for the controller's certificate....  Depending on what you are doing you might want it to be stable, in which case you need to save it, of course...

You can use `SecKeyCreateRandomKey` to create the key.  See https://github.com/project-chip/connectedhomeip/blob/533df0c7ab1b9d7b7bb41e4ab119985c0bfe43ca/src/darwin/Framework/CHIPTests/TestHelpers/MTRTestKeys.m#L55-L70 for an Objective-C example, though I would expect the Swift version to be a pretty straightforward translation of that.

**Comment by bzbarsky-apple** [comment]
Or you can use whatever other method you have; creating public/private keypair is not Matter-specific.

**Comment by law-ko** [comment]
@bzbarsky-apple We have managed to create public/private Keypair, but do not know how to pack into the type MTRKeypair.

Here's how we create the public/private keys.
```
var error: Unmanaged<CFError>?
        guard let privateKey =
                SecKeyCreateRandomKey(attributes as CFDictionary, &error) else {
            // throw error
            return
        }
        guard let publicKey =
                SecKeyCopyPublicKey(privateKey) else {
            // throw error
            return
        }
```
