### ISSUE TITLE
[Darwin] Failed in verifying 'Attestation Information' command received from the device: err 101

### ISSUE THREAD

**Issue by law-ko** [project-chip/connectedhomeip#33662]
### Reproduction steps

Hello,

We are trying to pair non-certified Matter devices on iOS but result in the error:
```
Failed in verifying 'Attestation Information' command received from the device: err 101. Look at AttestationVerificationResult enum to understand the errors
Failed to perform commissioning step 13
```

We have passed in
```
if let fileURL = Bundle.main.url(forResource: "dcld_mirror_CN_Espressif_Matter_PAA_O_Espressif_Systems_vid_0x131B", withExtension: "pem") {
                factoryParams.productAttestationAuthorityCertificates = try [Data(contentsOf: fileURL)]
            }
```
to include a PAA but still results the same error. Is there any method to bypass Attestation check?

Thank you.

### Platform

darwin

### Type

Platform validated

**Comment by bzbarsky-apple** [comment]
@law-ko You can absolutely bypass the attestation check if it's happening during your commissioning: Implement `MTRDeviceAttestationDelegate`, pass it in as part of the `MTRCommissioningParameters` when doing the commissioning, and call `continueCommissioningDevice` as desired.

That said, adding the PAA should in fact work if that's the only attestation problem the device says.

And it's really not clear from the above whether what's failing is your commissioning or the keychain commissioning.
