### ISSUE TITLE
Since terminal devices need certificates issued by authoritative organizations because of DAC, do commissioners and controllers also need certificates issued by certain authoritative organizations? [1.3] 

### ISSUE THREAD

**Issue by yf-fan-org** [project-chip/connectedhomeip#33676]
Since terminal devices need certificates issued by authoritative organizations because of DAC, do commissioners and controllers also need certificates issued by certain authoritative organizations? Because the commissioner needs to generate NOC, and NOC depends on RCAC, does this RCAC certificate need to be issued by an authoritative organization, or can it be generated by self-signature?

**Comment by bzbarsky-apple** [comment]
RCAC can be generated by anyone.

**Comment by yf-fan-org** [comment]
> RCAC can be generated by anyone.

So how does this ensure it's authoritative, or is it sufficient here to be able to generate RCACs

**Comment by bzbarsky-apple** [comment]
Anyone can be a commissioner, yes, as long as a user wants them to be.
