### ISSUE TITLE
[BUG] Unpairing function is failed with src/app/ReadClient.cpp:682: CHIP Error 0x00000032: Timeout

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#33755]
### Reproduction steps

I have used python controller to done a stress test on my RPI sample dut (all-clusters-app) on Pair-Unpair operation for 10000 iteration. The iteration 5688 is passed without any error but the 5689 is failed to Unpair the dut during the OnReadAttribute step for the currentFabricIndex attribute with the below traceback error and the next iteration 5690 is also passed without any issues.

> Traceback (most recent call last):
  File "/Users/chaitanyajandhyala/code/python/matter-qa/src/matter_qa/library/helper_libs/matter_testing_support.py", line 1187, in unpair_dut
    controller.UnpairDevice(node_id)
  File "/Users/chaitanyajandhyala/code/python/matter-qa/.venv/lib/python3.9/site-packages/chip/ChipDeviceCtrl.py", line 452, in UnpairDevice
    return self._ChipStack.CallAsync(
  File "/Users/chaitanyajandhyala/code/python/matter-qa/.venv/lib/python3.9/site-packages/chip/native/__init__.py", line 87, in raise_on_error
    raise self.to_exception()
chip.exceptions.ChipStackError: src/app/ReadClient.cpp:682: CHIP Error 0x00000032: Timeout

### Bug prevalence

Whenever i do this  

### GitHub hash of the SDK that was being used

3718e996b56f36a553c1b4571f77728396590776

### Platform

python, raspi

### Platform Version(s)

RPI-4, 8GB RAM

### Anything else?

Example of Failed iteartion details:

The iteartion number 5688 is passed below file for the same
TH log: [log_2024-04-27_04-43-23.log](https://github.com/user-attachments/files/15589034/log_2024-04-27_04-43-23.log)
 
DUT log:  [Dut_log_5688_2024-04-27T04_43_33_846904.log](https://github.com/user-attachments/files/15589021/Dut_log_5688_2024-04-27T04_43_33_846904.log)

The iteration number 5689 is failed with this error below the logfile
TH log : [log_2024-04-27_04-43-44.log](https://github.com/user-attachments/files/15588965/log_2024-04-27_04-43-44.log)
DUT log: [Dut_log_5689_2024-04-27T04_48_18_251279.log](https://github.com/user-attachments/files/15588979/Dut_log_5689_2024-04-27T04_48_18_251279.log)

The iteartion number 5690 is passed below file for the same
TH log: [log_2024-04-27_04-48-28.log](https://github.com/user-attachments/files/15589115/log_2024-04-27_04-48-28.log)
Dut log: [Dut_log_5690_2024-04-27T04_48_38_665934.log](https://github.com/user-attachments/files/15589099/Dut_log_5690_2024-04-27T04_48_38_665934.log)

For the detailed summary please reference this json: [summary.json](https://github.com/user-attachments/files/15588197/summary.json)

Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Pair.py

**Comment by cjandhyala** [comment]
closing the ticket for now, following-up with a new ticket..
