### ISSUE TITLE
[BUG] Commissioning failed with src/controller/python/ChipDeviceController-ScriptDevicePairingDelegate.cpp:89: CHIP Error 0x00000003: Incorrect state

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#33756]
### Reproduction steps

I have used python controller to done a stress test on my RPI sample dut (all-clusters-app) on Pair-Unpair operation for 10000 iteration. The iteration 3732 is passed without any error but the 3733 is Failed to establish secure session to device during commission the dut with the below traceback error and the next iteration 3734 is also passed without any issues.

> Traceback (most recent call last):
  File "/Users/chaitanyajandhyala/code/python/matter-qa/src/matter_qa/library/helper_libs/matter_testing_support.py", line 1177, in pair_dut
    raise CommissionFailure(f"Pairing with DUT failed Reason {commission_device_result.__str__()} ")
chip.commissioning.CommissionFailure: CommissionFailure(Pairing with DUT failed Reason src/controller/python/ChipDeviceController-ScriptDevicePairingDelegate.cpp:89: CHIP Error 0x00000003: Incorrect state )

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

3718e996b56f36a553c1b4571f77728396590776

### Platform

python, raspi

### Platform Version(s)

RPI-4, 8GB RAM

### Anything else?

Example of Failed iteartion details:

The iteartion number 3732 is passed below file for the same
TH log: [log_2024-04-26_12-34-20.log](https://github.com/user-attachments/files/15589758/log_2024-04-26_12-34-20.log)
DUT log: [Dut_log_3732_2024-04-26T12_34_30_676217.log](https://github.com/user-attachments/files/15589751/Dut_log_3732_2024-04-26T12_34_30_676217.log)

The iteration number 3733 is failed with this error below the logfile
TH log : [log_2024-04-26_12-34-44.log](https://github.com/user-attachments/files/15589721/log_2024-04-26_12-34-44.log)
DUT log: [Dut_log_3733_2024-04-26T12_39_18_541072.log](https://github.com/user-attachments/files/15589740/Dut_log_3733_2024-04-26T12_39_18_541072.log)

The iteartion number 3734 is passed below file for the same
TH log: [log_2024-04-26_12-39-27.log](https://github.com/user-attachments/files/15589783/log_2024-04-26_12-39-27.log)
Dut log: [Dut_log_3734_2024-04-26T12_39_37_352524.log](https://github.com/user-attachments/files/15589792/Dut_log_3734_2024-04-26T12_39_37_352524.log)

For the detailed summary please reference this json: [summary.json](https://github.com/user-attachments/files/15588197/summary.json)

Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Pair.py

**Comment by cjandhyala** [comment]
closing the ticket for now, following-up with a new ticket..
