### ISSUE TITLE
Message Synchronization Protocol

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#3376]
#### Problem
Group security requires Message Synchronization Protocol to be implemented.

#### Proposed Solution

Implement low levels of Message Security as defined in:
* CHIP-Specifications/connectedhomeip-spec#230
* CHIP-Specifications/connectedhomeip-spec#256

**Comment by woody-apple** [comment]
@kghost can this task be broken up at this point?

**Comment by yufengwangca** [comment]
It seems #4626 is dup of this ticket, just synced with Mingjie, I will post my PR with this ticket instead

**Comment by yufengwangca** [comment]
Reopen https://github.com/project-chip/connectedhomeip/issues/4626 which handle the protocol implementation, the Initiating Message Counter Synchronization part is left in this ticket after all dependencies are closed
