### ISSUE TITLE
[BUG] commissiong failed with src/controller/python/ChipDeviceController-ScriptPairingDeviceDiscoveryDelegate.h:59: CHIP Error 0x00000032: Timeout

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#33778]
### Reproduction steps

I have used python controller to done a stress test on my RPI sample dut (all-clusters-app) on Pair-Unpair operation for 10000 iteration. The iteration 6126 is passed without any error but the 6127 is Failed to establish secure session to device during commission the dut with the below error and the next iteration 6128 is also passed without any issues.

> 2024-04-27 09:39:17,885 - root - WARNING - ChipDeviceCtrl.py:HandlePASEEstablishmentComplete:307 - Failed to establish secure session to device: src/controller/python/ChipDeviceController-ScriptPairingDeviceDiscoveryDelegate.h:59: CHIP Error 0x00000032: Timeout
2024-04-27 09:39:17,885 - root - WARNING - ChipDeviceCtrl.py:HandleCommissioningComplete:271 - Failed to commission: src/controller/python/ChipDeviceController-ScriptPairingDeviceDiscoveryDelegate.h:59: CHIP Error 0x00000032: Timeout

### Bug prevalence

Whenever i do this

### GitHub hash of the SDK that was being used

3718e996b56f36a553c1b4571f77728396590776

### Platform

python, raspi

### Platform Version(s)

RPI-4, 8GB RAM

### Anything else?

Example of Failed iteartion details:

The iteartion number 6126 is passed below file for the same
TH log: [log_2024-04-27_09-31-00.log](https://github.com/user-attachments/files/15641015/log_2024-04-27_09-31-00.log)
DUT log:[Dut_log_6126_2024-04-27T09_31_10_889913.log](https://github.com/user-attachments/files/15641109/Dut_log_6126_2024-04-27T09_31_10_889913.log)

The iteration number 6127 is failed with this error below the logfile
TH log : [log_2024-04-27_09-31-26.log](https://github.com/user-attachments/files/15640913/log_2024-04-27_09-31-26.log)
DUT log: [Dut_log_6127_2024-04-27T09_39_18_048163.log](https://github.com/user-attachments/files/15640934/Dut_log_6127_2024-04-27T09_39_18_048163.log)

The iteartion number 6128 is passed below file for the same
TH log: [log_2024-04-27_09-39-31.log](https://github.com/user-attachments/files/15641169/log_2024-04-27_09-39-31.log)
Dut log: [Dut_log_6128_2024-04-27T09_39_40_860987.log](https://github.com/user-attachments/files/15641181/Dut_log_6128_2024-04-27T09_39_40_860987.log)

For the detailed summary please reference this json: [summary.json](https://github.com/user-attachments/files/15588197/summary.json)

Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Pair.py

**Comment by cjandhyala** [comment]
closing the ticket for now, following-up with a new ticket..
