### ISSUE TITLE
IPv6 Multicast Addressing

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#3377]
#### Problem
Group messaging requires nodes constructing their IPv6 multicast address for each group, and registering to listen for mutlicast messages to that address.

 #### Proposed Solution
Implement IPv6 Multicast Addressing specification (spec reference TBD)

**Comment by jepenven-silabs** [comment]
Reopening, Since PR #11368 added the functionality to build multicast address but is not in use in the actual stack.

**Comment by cecille** [comment]
Possibly finished? There seems to be a linked PR, but specifically for linux.
