### ISSUE TITLE
[BUG] Commissioning failed with src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#33781]
### Reproduction steps

I have used python controller to done a stress test on my RPI sample dut (all-clusters-app) on Pair-Unpair operation for 10000 iteration. The iteration 8022 is passed without any error but the 8023 is Failed to commission the dut during FindOperational step  with the below traceback error and the next iteration 8024 is also passed without any issues.

> Traceback (most recent call last):
  File "/Users/chaitanyajandhyala/code/python/matter-qa/src/matter_qa/library/helper_libs/matter_testing_support.py", line 1177, in pair_dut
    raise CommissionFailure(f"Pairing with DUT failed Reason {commission_device_result.__str__()} ")
chip.commissioning.CommissionFailure: CommissionFailure(Pairing with DUT failed Reason src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout )

### Bug prevalence

Whenever i do this

### GitHub hash of the SDK that was being used

3718e996b56f36a553c1b4571f77728396590776

### Platform

python, raspi

### Platform Version(s)

RPI-4, 8GB RAM

### Anything else?

Example of Failed iteartion details:

The iteartion number 8022 is passed below file for the same
TH log: [log_2024-04-28_03-31-58.log](https://github.com/user-attachments/files/15646584/log_2024-04-28_03-31-58.log)
DUT log: [Dut_log_8022_2024-04-28T03_32_08_256032.log](https://github.com/user-attachments/files/15646605/Dut_log_8022_2024-04-28T03_32_08_256032.log)

The iteration number 8023 is failed with this error below the logfile
TH log : [log_2024-04-28_03-32-30.log](https://github.com/user-attachments/files/15646419/log_2024-04-28_03-32-30.log)
DUT log: [Dut_log_8023_2024-04-28T03_40_32_688669.log](https://github.com/user-attachments/files/15646448/Dut_log_8023_2024-04-28T03_40_32_688669.log)

The iteartion number 8024 is passed below file for the same
TH log: [log_2024-04-28_03-40-44.log](https://github.com/user-attachments/files/15646538/log_2024-04-28_03-40-44.log)
Dut log: [Dut_log_8024_2024-04-28T03_41_54_148214.log](https://github.com/user-attachments/files/15646528/Dut_log_8024_2024-04-28T03_41_54_148214.log)

For the detailed summary please reference this json: [summary.json](https://github.com/user-attachments/files/15588197/summary.json)

Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Pair.py

**Comment by cjandhyala** [comment]
closing the ticket for now, following-up with a new ticket..
