### ISSUE TITLE
The CHIP_CONFIG_MAX_GROUP_ENDPOINTS_PER_FABRIC macro is inconsistent with the requirements in the specification

### ISSUE THREAD

**Issue by ChengqiangShe** [project-chip/connectedhomeip#33794]
https://github.com/project-chip/connectedhomeip/blob/5bb5c9e23d532cea40476fc0bd1d3008522792ba/src/lib/core/CHIPConfig.h#L1069

Matter Specification Version 0.7-fall2024, 2024-05-31 16:09:52 -0700: Draft：
2.11.1.2 Section Definitions:
The node SHALL support at least four group table entries per fabric per endpoint having a Groups cluster instance.

**Comment by bzbarsky-apple** [comment]
This macro is for the number of _endpoints_ that have the groups cluster on them, not for the number of group table entries. 

The number of group table entries is then computed like so:

```
src/lib/core/CHIPConfig.h:#define CHIP_CONFIG_MAX_GROUPS_PER_FABRIC (4 * CHIP_CONFIG_MAX_GROUP_ENDPOINTS_PER_FABRIC)
```
