### ISSUE TITLE
[Documentation] Flag List Change Actions Replace and Delete as provisional and document write List behavior

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#33807]
### Documentation issues

As follow up to https://github.com/project-chip/connectedhomeip/issues/33487 I would propose to update "8.9.2.6. AttributeDataIB" and also 10.6.4.3.1. Lists
* mark "List change processing actions MODIFY and DELETE" as provisional because they are not implemented by chip
* maybe also add information for  "List change processing action ADD" that this is basically only supported with clearing the list before becaus when I understand code correctly then the list is cleared before the first value of a list is added

Code wise it is commented already in https://github.com/project-chip/connectedhomeip/blob/5db170117d3afd5b4c815c1c181cc8646779cc5a/src/app/MessageDef/AttributePathIB.cpp#L197 (formally also Delete support is missing) and here https://github.com/project-chip/connectedhomeip/blob/5db170117d3afd5b4c815c1c181cc8646779cc5a/src/app/WriteHandler.cpp#L304 (and following lines)

In general these limitations should be clear in the specification and also to make sure that, if it ever gets implemented, it is clear that model revisions needs to be increased because adding these new types is not backward compatible.

The same goes for the requirements on how write interactions should be working withg chunked lists (see linked other issue for examples). Main thing is:
* single entries are processed one by one
* a single write path can fail which just means that this action to process fails but not complete writing
* validation happens per write interaction, the same for "logical processing of the write"
* when all write actions for a particular path are done then the value is updated and becomes effective for potential other parts of the logic (e.g. acl)

This is also not contained in the specification from my knowledge.

Thank you

### Anything else?

Formally also the "field ID" options for a nestedpath in "8.2.1.7. Attribute Path" and other spec places should clearly be marked as provisional or removed because AttributeDataIB Tlv structs do not allow adding a fieldId at all. So all these fieldId optiuons are "specification only" and not implementable at all. An alternative (even taht it would be an interesting idea) could be to simply remove the "fieldId"  cases from the pecs because also this would not be breaking in any wey and much cleaner. It can be re-added if wanted at a later timepoint

**Comment by Apollon77** [comment]
PS: And the comment in https://github.com/project-chip/connectedhomeip/blob/5db170117d3afd5b4c815c1c181cc8646779cc5a/src/app/WriteHandler.cpp#L314-L316 is wrong because the first item is set as mListOp = ReplaceAll some line above that and so the result of isListItemOperation is false and never true

Means that "emptying the list" is not ignored but processed as a "ReplaceAll" operation.

The code login would ignore btw any first "Add/Delete/Modify" action being sent without a "clear" package before that when I understand the implications correctly, so they would be ignored with a Busy response (which is also nowhere documented in the specs)

**Comment by ReneJosefsen** [comment]
Is any of this is covered by https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9118?

**Comment by Apollon77** [comment]
I can not answer this because no access

**Comment by Apollon77** [comment]
@ReneJosefsen I commented on the mentioned PR. Please tell me if you like me to open anew Spec issue internally describing it more complete rather then commenting on the closed PR.

**Comment by Apollon77** [comment]
Ok I close here, lets discuss detsils in spec issue
