### ISSUE TITLE
[ICD] Add ClientType Support in the Android Chip-tool

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#33823]
#### Description
Spec adds the ClientType to register client command - https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9315
Android chip-tool needs to support the argument.

See https://github.com/project-chip/connectedhomeip/pull/33811 for the C++ chip-tool.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/33811
