### ISSUE TITLE
Add implementation for added Q quality in Color Control

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#33863]
https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9064 and https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/9181

Adds the Q quality to RemainingTime, CurrentHue, CurrentSaturation, CurrentX, CurrentY and EnhancedCurrentHue. The SDK needs to be updated to match the rules proposed by the spec on how often these values SHALL be reported.

**Comment by jmartinez-silabs** [comment]
@ReneJosefsen Shouldn't the `ColorTemperatureMireds` also have a Q quality?
