### ISSUE TITLE
[Device Controller] WiFi network provisioning procedure should be a seperate command

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#3387]
#### Problem
Currently, we support network provisioning when connect to device, however, this procedure should be extract from connect.

 #### Proposed Solution
One possible flow of provisioning:
1. `ble-scan-connect`
2. `connect (rendezvous)`
3. *(wait for connect)*
4. `set-wifi-network ssid password`
5. *(connect to thread network, service provisoning, etc.)*

**Comment by woody-apple** [comment]
@erjiaqing Can this task be more specific? Is this still required?

**Comment by erjiaqing** [comment]
This is covered by network provisioning cluster.
