### ISSUE TITLE
Need to add transport layer and on/off cluster integration in Chip Linux BLE peripheral

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#3388]
Current Chip Linux BLE peripheral has not yet integrated transport layer and on/off integration, we need to add them in this ticket.

**Comment by woody-apple** [comment]
@yunhanw-google What is this tracking? I'm not sure On/Off is supported over BLE?

**Comment by erjiaqing** [comment]
> @yunhanw-google What is this tracking? I'm not sure On/Off is supported over BLE?

This PR should be covered by other more generic PRs related to clusters and BLE now. I think it can be closed.
