### ISSUE TITLE
[1.3]Show paired devices node ID  using chip-tool on linux

### ISSUE THREAD

**Issue by gn03261335** [project-chip/connectedhomeip#33917]
### Reproduction steps

I used chip-tool paring to pair three Matter devices, but I don't know how to get the node IDs of all my paired devices.
has any commamd or methond to know it?

### Bug prevalence

etc

### GitHub hash of the SDK that was being used

be60b122b5c39799fd1024aca91a9d430a033e81

### Platform

other

### Platform Version(s)

1.3

### Type

Common Cluster Logic

**Comment by bzbarsky-apple** [comment]
chip-tool does not store this information.   See also discussion in https://github.com/project-chip/connectedhomeip/issues/31308
