### ISSUE TITLE
[1.2] IOS-Google Home Connect failed

### ISSUE THREAD

**Issue by kagami555** [project-chip/connectedhomeip#33923]
### Reproduction steps

1.Built chip-lighting-app in linux  using command : ./scripts/examples/gn_build_example.sh  examples/lighting-app/linux out/ax 'target_cpu="arm" target_os="linux"'
2.Brought up DUT using commnad : ./chip-lighting-app --ble-device 0 --wifi
3.When I use the Google Home software on the iOS platform to add a device, it shows that the device cannot be added.

I checked the device log and saw that it has been successfully connected to the Internet and communicated via UDP. However, after receiving the message ClusterId = 0x3c, CommandId = 0x2, it shows Received command to close commissioning window. What is the problem? This device can be paired normally through other methods, including Android Google Home and iOS HomeKit.

Android_Google.log is the device log of Google Home connected to Android platform
IOS_Google.log is the device log of Google Home connected to IOS platform
IOS_Homekit.log is the device log of HomeKit connected to IOS platform
matter.sh.txt is the startup script of chip-lighting-app
[Android_Google.log](https://github.com/user-attachments/files/15837155/Android_Google.log)
[IOS_Google.log](https://github.com/user-attachments/files/15837158/IOS_Google.log)
[IOS_Homekit.log](https://github.com/user-attachments/files/15837159/IOS_Homekit.log)
[matter.sh.txt](https://github.com/user-attachments/files/15837166/matter.sh.txt)

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

437c5743ef4eac87ec5f80114d295f71e8a4f0e0

### Platform

other

### Platform Version(s)

1.2

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
This sounds like an issue you should report to Google through their bug reporting channels, not a bug in the Matter SDK.
