### ISSUE TITLE
How to generated the "./zzz_generated/chip-tool/zap-generated/Commands.h"

### ISSUE THREAD

**Issue by yangchaoFree** [project-chip/connectedhomeip#33941]
as can be seen, the "zzz_generated/chip-tool/zap-generated/Commands.h" is generated by zap tool. but the document not say how to generate  and the source files to generate it.

**Comment by korbinZhang** [comment]
`scripts/tools/zap_regen_all.py`

**Comment by yangchaoFree** [comment]
thanks
