### ISSUE TITLE
[BUG] Bug found by bugprone-casting-through-void check in .clang-tidy

### ISSUE THREAD

**Issue by jlatusek** [project-chip/connectedhomeip#34008]
### Reproduction steps

1. Add `bugprone-casting-through-void` to `.clang-tidy`
2. Open latest build container based on ubuntu:24.04
3. Run `Clang-tidy validation` and previous step from [build.yaml](https://github.com/project-chip/connectedhomeip/blob/master/.github/workflows/build.yaml)

### Bug prevalence

always

### GitHub hash of the SDK that was being used

4cdce52a5fa25542d4fbeb3cdff6e75b3aa1c379

### Platform

other

### Anything else?

Log file with clang-tidy error:
[1_Build on Linux (fake, gcc_release, clang, simulated).txt](https://github.com/user-attachments/files/15898096/1_Build.on.Linux.fake.gcc_release.clang.simulated.txt)

**Comment by bzbarsky-apple** [comment]
@jlatusek Those are all from using the GLib API macros, right?  Sounds like we need to add suppressions for those cases or something.

**Comment by jlatusek** [comment]
@bzbarsky-apple This error is caused by using glib macros to do the casting. We can try to do the casting another way, but glib macros also check that the object being casted is of the correct type.

**Comment by bzbarsky-apple** [comment]
Right, so it sounds like we need to suppress the clang-tidy check for these known-safe cases....

**Comment by andy31415** [comment]
We should add supression comments or fix the code.
At the same time, I believe we updated to ubuntu 24.04 and evetyhing should be updated now.

Closing as likely stale - we support ubuntu 24.04 today.
