### ISSUE TITLE
[Platform] linux(arm64)

### ISSUE THREAD

**Issue by hassan-xy** [project-chip/connectedhomeip#34030]
### Reproduction steps

I run the command ./gn_build.sh
It builds and takes a space of around 30GB while my linux arm64 dev board has only 8 GB. Any ideas as to how I can cross-compile and resolve the issue.

### Platform

other

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
`./gn_build.sh` builds a whole bunch of different example apps and configurations.  It's supposed to be a "build and test everything" kind of thing, not appropriate for anything like a constrained device.

What are you actually trying to build?

**Comment by hassan-xy** [comment]
I am trying to build chip-tool firstly.
Later I would want to test example codes for Linux arm64 arch.
If there is a way to only build for my arch then that would be great.

**Comment by bzbarsky-apple** [comment]
If you want to just build chip-tool, I would recommend either 

```
scripts/examples/gn_build_example.sh examples/chip-tool place/to/put/binary
```

or 

```
./scripts/run_in_build_env.sh "./scripts/build/build_examples.py --target linux-arm64-chip-tool"
```

All the builds `./gn_build.sh` does are for your arch, but it does them with different compilers/settings...

**Comment by hassan-xy** [comment]
![image](https://github.com/project-chip/connectedhomeip/assets/125990448/466848a7-68b3-4628-a0d3-7290992b4a10)
Well, I am not sure how many more times I see this missing dependencies. Maybe I am missing few commands here.

**Comment by hassan-xy** [comment]
I tried to install but still I dont have enough space, I only have 8GB eMMC.
Is it possible to build the binary on x86 ubuntu 20 desktop and move to my arch64 board(ubuntu 18)?

**Comment by hassan-xy** [comment]
![image](https://github.com/project-chip/connectedhomeip/assets/125990448/b21146fd-4654-4f77-844d-fcfe7b523bb7)
Well I am running on the x86 desktop for my target board.

**Comment by bzbarsky-apple** [comment]
@andy31415 what's the right way to build just chip-tool while cross-compiling?

**Comment by andy31415** [comment]
Only clang can cross-compile, hence the error there saying `due to rule ONLY IF `-(clang|nodeps)`.

The target should be `linux-arm64-chip-tool-clang`

**Comment by hassan-xy** [comment]
Hi @andy31415 
I tried and I got a diffrent error this time.
![image](https://github.com/project-chip/connectedhomeip/assets/125990448/c30e4ddb-d977-425f-bac8-084d94cc9047)
![image](https://github.com/project-chip/connectedhomeip/assets/125990448/1194f2a8-3e95-4859-b126-2888060e7e13)
I have tried different combinations like --out-prefix, --clean but still the same error.

**Comment by bzbarsky-apple** [comment]
@hassan-xy You want
```
./scripts/run_in_build_env.sh "./scripts/build/build_examples.py --target linux-arm64-chip-tool-clang build"
```

**Comment by hassan-xy** [comment]
Well...
![image](https://github.com/project-chip/connectedhomeip/assets/125990448/3ca59595-0536-4883-92f8-60fb8b2499db)
I am cross-compiling for arm64 environment on x86_64 ubuntu 20.04 desktop.

I am also parallely trying to build on the dev board by building inside of a sd card. I am also facing the same python dependencies. Do you guys have a list of all the python packages or versions necessary for build to succeed?

**Comment by bzbarsky-apple** [comment]
The sysroot env var presumably needs to be set to the relevant sysroot for the cross-compile that has the other-arhc compilers, libraries, etc?   That's about as much as I know about the cross-compiling bits, which are badly under-documented....

**Comment by hassan-xy** [comment]
Hi,
Well I tried to move the binary to my device after building on RPI 4 board but faced issues with glibc 2.35 version and openssl 3.
Even after building the source code to update, the current version I am facing the issue.

So, can you share a list of all the dependencies connectedIP and its example binaries like chip-tool has so I can prepare for it.
Also please provide support for the **linux yocto environment**. I very popular among developers and will beneficial for everyone.

I will be waiting for your responses.
THANKS!!!

**Comment by hassan-xy** [comment]
Guys, I am waiting for your comments...

**Comment by bzbarsky-apple** [comment]
I think fundamentally: no one knows the answers to your questions.

**Comment by hassan-xy** [comment]
Well can you at least share the I'd of the person working with platform integration.

https://www.yoctoproject.org/
Link to the yocto project.
It's just another flavour of the Linux distro but quite popular.

Let me know if anything else is needed.

**Comment by hassan-xy** [comment]
Still wait for a comment....

**Comment by hassan-xy** [comment]
No updates here as well.
