### ISSUE TITLE
Create a Second Test Context for TestReadInteraction

### ISSUE THREAD

**Issue by Alami-Amine** [project-chip/connectedhomeip#34041]
https://github.com/project-chip/connectedhomeip/blob/9d56786ed093473fdfb66d770a2e2338ab579d3e/src/app/tests/TestReadInteraction.cpp#L232-L233

- before the migration to pw_unit_tests, `TestReadInteraction` Got executed with two contexts with the second test context having `sSyncScheduler = true`. This was not ported as pw_unit_test doesn't offer a clear way to do that and we had to wait for the migration effort to be finished to do that.

- A workaround to do this was mentioned @arkq 

- This workaround should be done after the changes in #34036 are integrated.

**Comment by Alami-Amine** [comment]
Hello @arkq,
any chance we can get your above-mentioned workaround?

**Comment by arkq** [comment]
Not until pigweed update, which will happen after full migration to ubuntu 24.04.
