### ISSUE TITLE
[SDK Quality Test] : Commission failed with src/transport/raw/BLE.cpp:100: CHIP Error 0x00000003: Incorrect state

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#34058]
**Description:**
I have used python controller to run a stress test on my RPI sample dut (all-clusters-app) on Pair-Unpair test scenario for 10,000 iterations. The test passed in iteration 80 without any error but the iteration 81 is Failed to commission the dut during the ReadCommissioningInfo2 stage with the below error

> 2024-06-22 12:06:59,035 - chip.native.CTL - ERROR - __init__.py:_RedirectToPythonLogging:39 - Error on commissioning step 'ReadCommissioningInfo2': 'src/transport/raw/BLE.cpp:100: CHIP Error 0x00000003: Incorrect state'
2024-06-22 12:06:59,035 - chip.native.CTL - INFO - __init__.py:_RedirectToPythonLogging:41 - Going from commissioning step 'ReadCommissioningInfo2' with lastErr = 'src/transport/raw/BLE.cpp:100: CHIP Error

GitHub hash of the SDK that was being used: https://github.com/project-chip/connectedhomeip/commit/c829a2cb6b3e60f9075146130fcb92d1529b24b3

**Platform**
controller - python controller running on raspi,
DUT - all-cluster-app running on raspi
Provisioned using ble-wifi

**Platform Version(s)**
RPI-4, 8GB RAM

**Test Scenario**

Pair/Provision the DUT (All-cluster-app running on raspi) using on-network
Read device information after the device is provisioned
sleep for 2 secs
Unpair the DUT (i.e. removing the fabric)
factory reset the DUT
repeat step1 - 6 for 10,000 iterations
Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Pair.py

**Reference log:**
Example of Passed iteration details:

The iteration number 80 is passed, below log files for the same
TH log: [log_2024-06-22_12-05-30.log](https://github.com/user-attachments/files/15959677/log_2024-06-22_12-05-30.log)
DUT log: [Dut_log_80_2024-06-22T12_06_05_658979.log](https://github.com/user-attachments/files/15959675/Dut_log_80_2024-06-22T12_06_05_658979.log)
TCP_DUMP: https://drive.google.com/file/d/1E63ZE1TA-L-tZLngiHU7AEHbbMEz6hUW/view?usp=drive_link

Example of Failed iteration details:

The iteration number 81 is failed with this error below the log file
TH log: [log_2024-06-22_12-06-20.log](https://github.com/user-attachments/files/15959604/log_2024-06-22_12-06-20.log)
DUT log: [Dut_log_81_2024-06-22T12_06_59_240146.log](https://github.com/user-attachments/files/15959596/Dut_log_81_2024-06-22T12_06_59_240146.log)
TCP_DUMP:https://drive.google.com/file/d/1RAUaC4jV75uYqhrNytjuD3q43FRY_5yj/view?usp=drive_link

**Comment by woody-apple** [comment]
Closing issues that aren't in top X, or listed as such.
