### ISSUE TITLE
[SDK Quality Test] : Commission is failed with src/platform/Linux/bluez/BluezEndpoint.cpp:624: CHIP Error 0x000000AC: Internal error

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#34057]
**Description:**
I have used python controller to run a stress test on my RPI sample dut (all-clusters-app) on Pair-Unpair test scenario for 10,000 iterations. The test passed in iteration 7 without any error but the iteration 8 is Failed to connect with the dut during the commissioning with the below error

> 2024-06-22 12:12:09,396 - chip.native.DL - ERROR - __init__.py:_RedirectToPythonLogging:39 - FAIL: ConnectDevice: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist
 (41)
2024-06-22 12:12:09,404 - chip.native.DL - DEBUG - __init__.py:_RedirectToPythonLogging:43 - HandlePlatformSpecificBLEEvent 16388
2024-06-22 12:12:09,403 - chip.native.BLE - ERROR - __init__.py:_RedirectToPythonLogging:39 - Device connection failed: src/platform/Linux/bluez/BluezEndpoint.cpp:625: CHIP Error 0x000000AC: Internal error
2024-06-22 12:12:09,404 - chip.native.DIS - INFO - __init__.py:_RedirectToPythonLogging:41 - Closing all BLE connections
2024-06-22 12:12:09,413 - root - WARNING - ChipDeviceCtrl.py:HandlePASEEstablishmentComplete:460 - Failed to establish secure session to device: src/platform/Linux/bluez/BluezEndpoint.cpp:624: CHIP Error 0x000000AC: Internal error
2024-06-22 12:12:09,419 - root - ERROR - matter_testing_support.py:_commission_device:1178 - Commissioning failed: src/platform/Linux/bluez/BluezEndpoint.cpp:624: CHIP Error 0x000000AC: Internal error

GitHub hash of the SDK that was being used: https://github.com/project-chip/connectedhomeip/commit/c829a2cb6b3e60f9075146130fcb92d1529b24b3

**Platform**
controller - python controller running on raspi,
DUT - all-cluster-app running on Nordic-DK
Provisioned using ble-thread

**Platform Version(s)**
RPI-4, 8GB RAM
NRF53840-DK

**Test Scenario**

Pair/Provision the DUT (All-cluster-app running on raspi) using on-network
Read device information after the device is provisioned
sleep for 2 secs
Unpair the DUT (i.e. removing the fabric)
factory reset the DUT
repeat step1 - 6 for 10,000 iterations
Script reference: https://github.com/CHIP-Specifications/matter-qa/blob/main/src/matter_qa/scripts/reliability_scripts/TC_Pair.py

**Reference log:**

Example of Passed iteration details:

The iteration number 7 is passed, below log files for the same
TH log: [log_2024-06-22_12-11-08.log](https://github.com/user-attachments/files/15959401/log_2024-06-22_12-11-08.log)
DUT log: [Dut_log_6_2024-06-22T12_11_08_468462.log](https://github.com/user-attachments/files/15959403/Dut_log_6_2024-06-22T12_11_08_468462.log)
TCP_DUMP: [controller_tcpdump_2024-06-22_12-11-08.zip](https://github.com/user-attachments/files/15959405/controller_tcpdump_2024-06-22_12-11-08.zip)

Example of Failed iteration details:

The iteration number 8 is failed with this error below the log file
TH log: [log_2024-06-22_12-12-09.log](https://github.com/user-attachments/files/15959385/log_2024-06-22_12-12-09.log)
DUT log:[Dut_log_7_2024-06-22T12_12_09_229320.log](https://github.com/user-attachments/files/15959390/Dut_log_7_2024-06-22T12_12_09_229320.log)
TCP_DUMP:[controller_tcpdump_2024-06-22_12-12-09.zip](https://github.com/user-attachments/files/15959393/controller_tcpdump_2024-06-22_12-12-09.zip)

**Comment by woody-apple** [comment]
Closing issues that aren't in top X, or listed as such.
