### ISSUE TITLE
Do we have any example for room air conditioner. If not, then how to create such device

### ISSUE THREAD

**Issue by Aryan-Tamboli** [project-chip/connectedhomeip#34083]
### Reproduction steps / Feature

Any resources on how to build room air conditioner device

### Platform

esp32

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
You use the "Room Air Conditioner" type from the device library, configure that in your ZAP configuration for the device, then enable any optional features you might need.

Past that, you'd need to ask more specific questions, but this does not seem like an issue in the Matter SDK.

**Comment by Aryan-Tamboli** [comment]
Thanks for helping. I have generated the ZAP files, now how to integrate it with example and flash the firmware?

**Comment by bzbarsky-apple** [comment]
It depends on which example you are using, exactly...
