### ISSUE TITLE
[TC-IDM-10.4] Python script has to be updated as per test plan changes

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#34099]
### Test Case

TC-IDM-10.4

**Description :**
In TC-IDM-10.4, step 7 has been added newly in the test plan. So the python script has to be updated by adding step 7 as per the test plan.

### GitHub hash of the SDK that was being used

58536ba64da75f0a63c569baa29966008ffdf306

### Platform

raspi

**Python script reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_pics_checker.py

**Test-Plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/interactiondatamodel.adoc#tc-idm-10-4-cluster-requirements-pics-dut_server 

Test-Plan PR which added step 7 : https://github.com/CHIP-Specifications/chip-test-plans/pull/4201/

**Comment by cjandhyala** [comment]
@Rajashreekalmane is this still an open issue ? or can we close the issue ?

**Comment by Rajashreekalmane** [comment]
Python script has been updated as per the test plan hence closing this issue .
