### ISSUE TITLE
[TC-EEVSE-2.2,2.4 & 2.5] Python script has to be updated as per the test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#34100]
### Test Case

TC-EEVSE-2.2,2.4 & 2.5

### Description

For below mentioned test cases, the test plan has been updated by adding expected outcome for most of the steps and few new checks has been added. So the Python script has to be updated for the same.

**Updated Test Case:**

**- TC-EEVSE-2.2:** Expected outcome has been added for most of the steps.
**- TC-EEVSE-2.4:** Expected outcome has been added for most of the steps.
**- TC-EEVSE-2.5:** Expected outcome has been added for most of the steps and Step 8 and 8a(Enable charging and supply state) has been added newly.

**Here is the test plan PR for reference:** https://github.com/CHIP-Specifications/chip-test-plans/pull/4071/

**Test plan reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/energy_EVSE.adoc

### GitHub hash of the SDK that was being used

07ac2f113c078b2659cf1b2b320776272070f99a

### Platform

raspi

**Comment by cjandhyala** [comment]
@KishokG is this still an open issue or can we close the ticket ?

**Comment by KishokG** [comment]
Yes @cjandhyala It's yet to be fixed

**Comment by jamesharrow** [comment]
I'll check but I think the python code automatically checks commands 'success' so there may be no changes needed in the scripts. The PR on the test plan was to align it to the scripts if I recall.

But I'll double check!
