### ISSUE TITLE
[TC-OPCREDS-3.1] - Python Test case failed  during PASE Reconnection

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#34101]
### Test Case

TC-OPCREDS-3.1

**Description:**

An error occurs during the PASE reconnection step of the test_TC_OPCREDS_3_1 test case. The test fails with a CHIP Error 0x000000C9: No shared trusted root when trying to establish a secure channel.

below mentioned command used to launch the DUT
./chip-all-clusters-app 

Below mentioned command used to validate the Test case : 
python3 TC_OPCREDS_3_1.py --commissioning-method on-network --discriminator 3840 --passcode 20202021  --paa-trust-store-path ../../credentials/development/paa-root-certs/ --storage-path admin_storage.json 

> [MatterTest] 06-27 05:47:03.531 INFO ***** Test Step 33 : TH1 reconnects to the DUT over PASE
> [MatterTest] 06-27 05:47:03.532 INFO Avahi browse: remove
> [MatterTest] 06-27 05:47:03.534 INFO StopPairing called for node ID 0x0000000012344322
> [MatterTest] 06-27 05:47:03.535 INFO SecureSession[0xffff7c027650, LSID:2272]: State change 'kActive' --> 'kPendingEviction'
> /home/ubuntu/Jun24/connectedhomeip/src/python_testing/TC_OPCREDS_3_1.py:345: RuntimeWarning: coroutine 'TC_OPCREDS_3_1.FindAndEstablishPase' was never awaited
>   self.FindAndEstablishPase(dev_ctrl=TH1, longDiscriminator=longDiscriminator,
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> [MatterTest] 06-27 05:47:03.541 INFO ***** Test Step 34 : TH1 reads the TrustedRootCertificates list from DUT and verifies the TH1 root is not present
> [MatterTest] 06-27 05:47:03.543 INFO Resolving AAD32AB44B1DE5DB:0000000012344322 ...
> [MatterTest] 06-27 05:47:03.545 INFO Lookup started for AAD32AB44B1DE5DB-0000000012344322
> [MatterTest] 06-27 05:47:03.546 INFO Avahi resolve found
> [MatterTest] 06-27 05:47:03.547 INFO Node ID resolved for AAD32AB44B1DE5DB-0000000012344322
> [MatterTest] 06-27 05:47:03.549 INFO UDP:[fe80::a0dc:b4ff:fe4f:c3e2%veth2725d66]:5540: new best score: 7
> [MatterTest] 06-27 05:47:03.549 INFO Checking node lookup status for AAD32AB44B1DE5DB-0000000012344322 after 6 ms
> [MatterTest] 06-27 05:47:03.549 INFO Keeping DNSSD lookup active
> [MatterTest] 06-27 05:47:03.715 INFO Avahi group established
> [MatterTest] 06-27 05:47:03.727 INFO Avahi group established
> [MatterTest] 06-27 05:47:03.743 INFO Avahi group established
> [MatterTest] 06-27 05:47:03.744 INFO Checking node lookup status for AAD32AB44B1DE5DB-0000000012344322 after 200 ms
> [MatterTest] 06-27 05:47:03.747 INFO Initiating session on local FabricIndex 2 from 0x000000000001B66A -> 0x0000000012344322
> [MatterTest] 06-27 05:47:03.758 INFO <<< [E:56354i S:0 M:167517234] (U) Msg TX to 0:0000000000000000 [0000] [UDP:[fe80::a0dc:b4ff:fe4f:c3e2%veth2725d66]:5540] --- Type 0000:30 (SecureChannel:CASE_Sigma1)
> [MatterTest] 06-27 05:47:03.758 INFO Sent Sigma1 msg
> [MatterTest] 06-27 05:47:03.760 INFO Avahi group established
> [MatterTest] 06-27 05:47:03.761 INFO >>> [E:56354i S:0 M:75094260 (Ack:167517234)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:40 (SecureChannel:StatusReport)
> [MatterTest] 06-27 05:47:03.762 ERROR Received error (protocol code 1) during pairing process: src/protocols/secure_channel/CASESession.cpp:2140: CHIP Error 0x000000C9: No shared trusted root
> [MatterTest] 06-27 05:47:03.764 INFO <<< [E:56354i S:0 M:167517235 (Ack:75094260)] (U) Msg TX to 0:0000000000000000 [0000] [UDP:[fe80::a0dc:b4ff:fe4f:c3e2%veth2725d66]:5540] --- Type 0000:10 (SecureChannel:StandaloneAck)
> [MatterTest] 06-27 05:47:03.766 ERROR Exception occurred in test_TC_OPCREDS_3_1.
> Traceback (most recent call last):
>   File "/home/ubuntu/Jun24/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 783, in exec_one_test
>     test_method()
>   File "/home/ubuntu/Jun24/connectedhomeip/src/python_testing/matter_testing_support.py", line 1506, in async_runner
>     return asyncio.run(runner_with_timeout)
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
>     return fut.result()
>   File "/home/ubuntu/Jun24/connectedhomeip/src/python_testing/TC_OPCREDS_3_1.py", line 349, in test_TC_OPCREDS_3_1
>     trusted_root_list = await self.read_single_attribute_check_success(dev_ctrl=TH1, node_id=newNodeId, cluster=opcreds, attribute=opcreds.Attributes.TrustedRootCertificates)
>   File "/home/ubuntu/Jun24/connectedhomeip/src/python_testing/matter_testing_support.py", line 796, in read_single_attribute_check_success
>     result = await dev_ctrl.ReadAttribute(node_id, [(endpoint, attribute)], fabricFiltered=fabric_filtered)
>   File "/home/ubuntu/Jun24/connectedhomeip/no/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 1531, in ReadAttribute
>     res = await self.Read(nodeid,
>   File "/home/ubuntu/Jun24/connectedhomeip/no/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 1454, in Read
>     device = await self.GetConnectedDevice(nodeid)
>   File "/home/ubuntu/Jun24/connectedhomeip/no/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 1033, in GetConnectedDevice
>     await future
> chip.exceptions.ChipStackError: src/protocols/secure_channel/CASESession.cpp:2140: CHIP Error 0x000000C9: No shared trusted root
> [MatterTest] 06-27 05:47:03.776 ERROR Exception happened when executing on_fail for test_TC_OPCREDS_3_1.
> Traceback (most recent call last):
>   File "/home/ubuntu/Jun24/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 646, in _exec_procedure_func
>     func(copy.deepcopy(tr_record))
>   File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>   File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
>     y = copier(memo)
>   File "/home/ubuntu/Jun24/connectedhomeip/no/lib/python3.10/site-packages/mobly/records.py", line 280, in __deepcopy__
>     exception = copy.deepcopy(self.exception)
>   File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.10/copy.py", line 265, in _reconstruct
>     y = func(*args)
>   File "/usr/lib/python3.10/copy.py", line 264, in <genexpr>
>     args = (deepcopy(arg, memo) for arg in args)
>   File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
>     rv = reductor(4)
> ValueError: ctypes objects containing pointers cannot be pickled
> [MatterTest] 06-27 05:47:03.780 INFO [Test] test_TC_OPCREDS_3_1 ERROR
> [MatterTest] 06-27 05:47:03.797 INFO Summary for test class TC_OPCREDS_3_1: Error 1, Executed 1, Failed 0, Passed 0, Requested 1, Skipped 0
> [MatterTest] 06-27 05:47:03.799 INFO Summary for test run MatterTest@06-27-2024_05-46-54-684:
> 

### GitHub hash of the SDK that was being used

58536ba64da75f0a63c569baa29966008ffdf306

### Platform

raspi

### Anything else?

**PFA log below** 
[TC-OPCRED-3.1 _CNTR.txt](https://github.com/user-attachments/files/16009139/TC-OPCRED-3.1._CNTR.txt)
[tc-opcred-3.1_DUT.txt](https://github.com/user-attachments/files/16009145/tc-opcred-3.1_DUT.txt)

**Comment by bilalahmaddev** [comment]
I am still getting this issue in Version: 2.10.2+spring2024 Sha: 2a350c8 while testing with matter over Thread device
