### ISSUE TITLE
[1.3] Apk Size of Android app is over 500 Mb

### ISSUE THREAD

**Issue by swap9391** [project-chip/connectedhomeip#34125]
### Reproduction steps

Apk size of app is getting higher with libs folder, any solution to reduce it. 

**If I remove jniLibs folder app runs with smaller apk size but I get issue for parsing QR string to CHIPDeviceInfo model.** 

I have tried enable proguard 

![image](https://github.com/project-chip/connectedhomeip/assets/12757858/aaef6831-e84f-4349-87c4-236adc478227)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

1.3

### Platform

android

### Platform Version(s)

14

### Type

Core SDK Memory Issue

**Comment by andy31415** [comment]
are the .so files stripped in this case? We use templates quite heavily and this could contain a lot of debug information.

Before stripping:
![image](https://github.com/project-chip/connectedhomeip/assets/1832280/0c8e900d-7b61-437a-97d7-3088f113838a)
![image](https://github.com/project-chip/connectedhomeip/assets/1832280/0f6c1cc2-d10f-4eab-8120-d4173bc70473)

After stripping:

![image](https://github.com/project-chip/connectedhomeip/assets/1832280/389f8d3e-2d65-4ac6-808e-50ebb83fe461)
![image](https://github.com/project-chip/connectedhomeip/assets/1832280/f5f6822d-9901-45db-beb0-96296629beb8)


I am however unsure how you got the 385MB so file though ... that one is very large.

**Comment by Trishia** [comment]
@andy31415 
In my case, `./scripts/build/build_examples.py --clean --target android-arm64-chip-tool-no-debug build` does not make any difference on android library size which is still over 80M.  
How to strip android library (so files) ?  
Advise me plz.
