### ISSUE TITLE
How to identify similar endpoints in Apple HomeKit

### ISSUE THREAD

**Issue by supersunil** [project-chip/connectedhomeip#34176]
Hello there,

I've a node with similar endpoints (but with different purpose), when the device is commissioned to Apple HomeKit, the endpoint were showed up randomly. 

I would like to know the endpoints corresponding to the logical device types.

Let's say:
I've a presence sensor mapped with 3 zones : zone 1,2 and 3. The device showing up in Apple HomeKit is random.

How can I map?
Occupancy Sensor = Zone1
Occupancy Sensor 2 = Zone2
Occupancy Sensor 3 = Zone3

![2024-07-03_17-10](https://github.com/project-chip/connectedhomeip/assets/64037214/718be37f-0d14-472a-a08c-2a3f7cc915a1)

**Comment by bzbarsky-apple** [comment]
This does not sound like a core SDK issue.  Please report Apple-specific issues to Apple via Feedback Assistant, following the directions below:

Feedback assistant ticket:
- File a feedback assistant ticket.
https://developer.apple.com/bug-reporting/#feedback-assistant
- Click on the link below using your account:
https://feedbackassistant.apple.com/new-form-response
- Choose iOS/iPadOS to file an issue
- Choose the area as Home App and fill in the details of the type of issue and the description
* Technical Information
Please provide the following
a) Sysdiagnose logs for iPhone / iPad with the timestamp / timeframe of the issue
b) Sysdiagnose logs for all the Home Hubs (HomePod mini / HomePod / Apple TV) with the timestamp / timeframe of the issue
c) Accessory logs with the timestamp / timeframe of the issue
d) mDNS network logs with timestamp / timeframe of the issue
e) Video or screenshot describing the issue (optional but beneficial)
Please make sure you download and install the profiles for iOS and tvOS as provided here. The instructions are also in these links.
* iOS:
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=homekit
 - https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=network
 - https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=ios&name=mdns
* tvOS:
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=homekit
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=network
- https://developer.apple.com/bug-reporting/profiles-and-logs/?platform=tvos&name=mdns
For installation instructions, refer to https://developer.apple.com/bug-reporting/profiles-and-logs.
Note: Once you have the profile on the iPhone, it will ask you if you want to install it on other devices. Follow the prompts to install on the HomePod, Apple TV, etc., where you have the described issue and reproduce it.
