### ISSUE TITLE
CHIP AES CCM Cipher Should Support Zero Length Plaintext

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#342]
#### Problem
In the current implementation zero length plaintext is not supported because of these checks in the Encrypt function:

    VerifyOrExit(plaintext != NULL, error = CHIP_ERROR_INVALID_ARGUMENT);
    VerifyOrExit(plaintext_length > 0, error = CHIP_ERROR_INVALID_ARGUMENT);

#### Proposed Solution

Remove these checks.
Verify that the rest of the code handles zero length plaintext properly.
Add test case.

**Comment by franck-apple** [comment]
Closing this issue per Slack conversion: 

> Boris Zbarsky  10:13 AM
A CRMP Ack message encrypts the counter value being acked in CHIP
So does not have zero length, afaict
Also, all CHIP messages encrypt the protocol id and message type
(protocol opcode, whatever you want to call it)
So in particular, in a CHIP message the following fields are always present and are part of the encrypted payload: Protocol Header, Protocol Opcode, Exchange Id, Message Protocol Id.
(for a message that does encryption at all, of course)

> Evgeni Margolis  11:09 AM
Agree! I opened this ticket before the CHIP message format was finalized. It looks that in CHIP there is always some data to be encrypted so this ticket can be closed as irrelevant.
