### ISSUE TITLE
[1.3] The Groups XML files contain issues regarding group_id

### ISSUE THREAD

**Issue by agatah2333** [project-chip/connectedhomeip#34213]
### Reproduction steps

The Groups XML files contain issues regarding group_id

As shown in the specification, group_id is constrained from 1 to the maximum value, but the XML does not show these constraints.

link: https://github.com/project-chip/connectedhomeip/blob/v1.3.0.0/src/app/zap-templates/zcl/data-model/chip/groups-cluster.xml

<img width="1044" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/ef1ac176-e927-410f-a80a-7e3f242f6cdc">

This results in issues when running related commands, such as
```
./chip-tool groups add-group 0 str  0x654325 1 
```
This command could work incorrectly due to the missing constraints.

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

other

### Platform Version(s)

1.3

### Type

Spec Compliance Issue, Security Issue, Core SDK Performance Improvement, Core SDK Interopability Issue

**Comment by bzbarsky-apple** [comment]
This XML format does not have a way to express constraints in command fields.  Any such constraints have to be implemented in the cluster directly.

**Comment by bzbarsky-apple** [comment]
@agatah2333 That said, if there is an issue where invalid values are being allowed by the cluster, please file an issue about that.  But that has nothing to do with the XML.

**Comment by agatah2333** [comment]
Thanks for your reply! I also reviewed the other XML files, and there are multiple ways to express the minimum value.

 I have a follow-up question: if the code needs to add the limitation, why does the XML provide the detailed limitation? Does it only affect the .matter file when using ZAP.....?

**Comment by bzbarsky-apple** [comment]
> if the code needs to add the limitation, why does the XML provide the detailed limitation? 

It doesn't.  The information in the XML is completely ignored, but there is a lot of cargo-culting going on here.
