### ISSUE TITLE
[1.3] Inconsistent Description for Flow Measurement, Missing Constraint for Max Value of 0x0002 MaxMeasuredValue

### ISSUE THREAD

**Issue by agatah2333** [project-chip/connectedhomeip#34218]
### Reproduction steps

The description for Flow Measurement is inconsistent, and the maximum value for 0x0002 MaxMeasuredValue is missing a constraint.

https://github.com/project-chip/connectedhomeip/blob/v1.3.0.0/src/app/zap-templates/zcl/data-model/chip/flow-measurement-cluster.xml
<img width="980" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/d8d7c6b6-5558-4256-8ddc-992ab928c1cc">

<img width="641" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/0a4a5100-8d74-4230-ba9b-df671954a753">

<img width="602" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/4419f588-0f89-4b21-8513-60a86e0a50e1">

<img width="1131" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/f3459d89-27cb-4a1a-b813-2f21469f44d3">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

5bb5c9e23d532cea40476fc0bd1d3008522792ba

### Platform

other

### Platform Version(s)

1.3

### Type

Spec Compliance Issue, Core SDK Interopability Issue

**Comment by bzbarsky-apple** [comment]
It's a readonly attribute, so the min/max in the XML are not used for anything, even if they were provided.

**Comment by bzbarsky-apple** [comment]
If the ZAP UI uses the value, we could add this, sure.  Does it?
