### ISSUE TITLE
[1.3] Inconsistent Description for Laundry Dryer Controls  

### ISSUE THREAD

**Issue by agatah2333** [project-chip/connectedhomeip#34217]
### Reproduction steps

The description for Laundry Dryer Controls is inconsistent.

https://github.com/project-chip/connectedhomeip/blob/v1.3.0.0/src/app/zap-templates/zcl/data-model/chip/laundry-dryer-controls-cluster.xml

<img width="756" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/53c28e88-f2dd-4744-8d66-5abffd60ace5">

<img width="643" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/0cdaa86b-1511-4fd9-8580-70e4d33f6f6d">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

5bb5c9e23d532cea40476fc0bd1d3008522792ba

### Platform

other, core

### Platform Version(s)

1.3

### Type

Spec Compliance Issue, Core SDK Performance Improvement

**Comment by bzbarsky-apple** [comment]
@rbultman Please take a look.
