### ISSUE TITLE
BDX State Machine and Message Definitions

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#3423]
#### Problem
Need to implement main business logic and state machine for the BDX spec.

 #### Proposed Solution
Implement a state machine for BDX message exchanges according to spec. This includes logic on what messages can be received at a specific point in a transfer, depending on the parameters of the transfer (sender vs. receiver drive, async vs sync, max length, etc). At minimum, this will also require declaring message types in the BDX "profile".

This should include unit tests to ensure the state machine behaves according to spec.

**Comment by holbrookt** [comment]
The merged PR was just for message definitions. PR for state machine logic is coming later

**Comment by BroderickCarlin** [comment]
Looks like we got bit by some automations. Sorry about that!
