### ISSUE TITLE
[1.3] Inconsistent Description for Occupancy Sensing cluster

### ISSUE THREAD

**Issue by agatah2333** [project-chip/connectedhomeip#34278]
### Reproduction steps

The description for Occupancy Sensing cluster is inconsistent with the spec.

<img width="626" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/2d449bed-dc20-43e4-bbab-cec02d22a506">

https://github.com/project-chip/connectedhomeip/blob/v1.3.0.0/src/app/zap-templates/zcl/data-model/chip/occupancy-sensing-cluster.xml#L43
<img width="978" alt="image" src="https://github.com/project-chip/connectedhomeip/assets/90156813/63540523-39ba-43ad-9feb-5527db13de00">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

5bb5c9e23d532cea40476fc0bd1d3008522792ba

### Platform

core

### Platform Version(s)

1.3

### Type

Spec Compliance Issue

**Comment by tcarmelveilleux** [comment]
Fixing in 1.4

**Comment by tcarmelveilleux** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/35220
