### ISSUE TITLE
[TC-DRLK-2.2,2.3 & 2.12] Python script has to be updated as per the test plan changes

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#34344]
### Test Case

TC-DRLK-2.2, 2.3 and 2.12

### Description

For below mentioned test cases, the test plan has been updated by adding few new checks and expected outcome modified. So the Python script has to be updated for the same.

**Updated Test Case:**

- TC-DRLK-2.2
- TC-DRLK-2.3
- TC-DRLK-2.12

**Here is the test plan PR for reference:** https://github.com/CHIP-Specifications/chip-test-plans/pull/4247

**Test plan reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/door_lock_Cluster.adoc

### GitHub hash of the SDK that was being used

05e4c10358a18f9c9295c2dcd7cdd880502d539a

### Platform

raspi

**Comment by cjandhyala** [comment]
closing the ticket since the PR is merged.
