### ISSUE TITLE
[BUG] [Fabric Sync Example App] An error occurred during fabricsynchronization add-bridge command.

### ISSUE THREAD

**Issue by joyoungjun** [project-chip/connectedhomeip#34436]
### Reproduction steps

Reference Guide : https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/fabric_synchronization_guide.md
> **Fabric Sync Setup**
> Enable Fabric Auto Sync:
> 
> In Fabric-Sync console:
> `fabricsync enable-auto-sync 1`
> 
> Pair the Fabric-Source bridge to Fabric-Sync with node ID 1:
> `fabricsync add-bridge 1 <fabric-sink-ip>`

During the fabircsync add-bridge step, an error is occured as below.

```
******* run_fabric_sink_sh console ******* 
...
ERR  Failed to connect to 127.0.0.1:33002: Connection refused
>>> fabricsync enable-auto-sync 1
>>> Auto Fabric Sync is enabled.
ERR  Failed to connect to 127.0.0.1:33002: Connection refused
ERR  Failed to connect to 127.0.0.1:33002: Connection refused
ERR  Failed to connect to 127.0.0.1:33002: Connection refused
fabricsync add-bERR  Failed to connect to 127.0.0.1:33002: Connection refused
ridge 1 192.168ERR  Failed to connect to 127.0.0.1:33002: Connection refused
.1.41
>>> ./run_fabric_sink.sh: line 78: 30156 Aborted                 (core dumped) "$FABRIC_ADMIN_PATH" --log-file-path "$FABRIC_ADMIN_LOG"
```

```
******* /tmp/fabric_admin.log *******
[509967.000494] CHIP:DIS: mDNS service published: _matterd._udp
[509967.000528] CHIP:DL: Long dispatch time: 197 ms, for event type 2
[509967.000529] CHIP:-: Failed to connect to Fabric-Bridge, retry in 5 seconds....
[509972.000534] CHIP:-: Failed to connect to Fabric-Bridge, retry in 5 seconds....
[509977.000541] CHIP:-: Failed to connect to Fabric-Bridge, retry in 5 seconds....
[509982.000546] CHIP:-: Failed to connect to Fabric-Bridge, retry in 5 seconds....
[509987.000552] CHIP:-: Failed to connect to Fabric-Bridge, retry in 5 seconds....
[509989.000367] CHIP:-: Command: fabricsync add-bridge 1 192.168.1.41
[509989.000369] CHIP:-: PushCommand: pairing already-discovered 1 20202021 192.168.1.41 5540
[509990.000368] CHIP:-: Command: pairing already-discovered 1 20202021 192.168.1.41 5540
[509990.000370] CHIP:SPT: VerifyOrDie failure at src/lib/support/SetupDiscriminator.h:52: discriminator == (discriminator & kLongMask)
```

It seems that the error occurred because the "fabircsync add-bridge" command did not pass a "discriminator".

https://github.com/project-chip/connectedhomeip/blob/3bc5667b3a9f2cabcaec1aaf49d8c0aec0583d11/examples/fabric-admin/commands/pairing/PairingCommand.cpp#L224

If I remove ".SetDiscriminator(mDiscriminator)" from the code, the "fabircsync add-bridge" command runs successfully. However, I'm not sure if this fix matches the intent of the code as written.

### Bug prevalence

Every Time

### GitHub hash of the SDK that was being used

3bc5667b3a9f2cabcaec1aaf49d8c0aec0583d11

### Platform

raspi

### Platform Version(s)

ubuntu 22.04

**Comment by yufengwangca** [comment]
Not able to reproduce this issue, https://github.com/project-chip/connectedhomeip/pull/34882 might fix the problem

1. Add bridge from run_fabric_sink.sh (which only build fabri-admin at sink side, so need to disable RPC)
./scripts/examples/gn_build_example.sh examples/fabric-admin out/debug/standalone 
./scripts/examples/gn_build_example.sh examples/fabric-bridge-app/linux out/debug/standalone chip_config_network_layer_ble=false 'import("//with_pw_rpc.gni")'
./examples/fabric-admin/scripts/run_fabric_sink.sh
./examples/fabric-admin/scripts/run_fabric_source.sh

```
>>> fabricsync add-bridge 1 192.168.86.246
New device with Node ID: 0x1 has been successfully added.
```

2. Add bridge from run_fabric_source.sh
./scripts/examples/gn_build_example.sh examples/fabric-admin out/debug/standalone 'import("//with_pw_rpc.gni")'
./scripts/examples/gn_build_example.sh examples/fabric-bridge-app/linux out/debug/standalone chip_config_network_layer_ble=false 'import("//with_pw_rpc.gni")'
./examples/fabric-admin/scripts/run_fabric_source.sh
./examples/fabric-admin/scripts/run_fabric_source.sh

```
>>> fabricsync add-bridge 1 192.168.86.246
New device with Node ID: 0x1 has been successfully added.
```

This setup only support add-bridge, if you try to sync device with this setup, it will cuase cyclical syncing
