### ISSUE TITLE
[BUG] bootstrap.sh no such file or directory error

### ISSUE THREAD

**Issue by 2jungg** [project-chip/connectedhomeip#34441]
### Reproduction steps

Platform
WSL + VS Code

Problems
source scripts/bootstrap.sh and source scripts/activate.sh doesn't work. There are errors like:
[Error Message]
bash: setup/bootstrap.sh: No such file or directory

However, the file exists.
So I try "source scripts/setup/bootstrap.sh" directly. After that, when I try to build sample lighting-app, I can't build because loading gni files fail. But the files also exists....
[Error Message]
2024-07-23 05:36:42 INFO    ERROR at //.gn:15:1: Unable to load "/workspaces/connectedhomeip/examples/lighting-app/linux/build_overrides/build.gni".

I already checked #33484 , but my construction is ok.
Please help me 😢😢

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

master

### Platform

vscode, windows

**Comment by andy31415** [comment]
Windows is not an officially supported platform at this time.
