### ISSUE TITLE
[CERT-TEST-FAILURE] - [TC-DEMM-3.3] Test failing due to CurrentMode value missmatch with OnMode value.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#34479]
### Feature Area

Other

### Test Case

TC-DEMM-3.3

### Reproduction steps

1. Execute the below mentioned command to put DUT into a commissionable state :
` ./chip-all-clusters-app`
2. Once DUT reach the commissionable state sent below mentioned command on TH.
`./chip-tool pairing onnetwork 1 20202021`

**Once after successful pairing provide the below commands:**

1. TH reads from the DUT the StartUpMode attribute.
`./chip-tool deviceenergymanagementmode read start-up-mode   1 1`

> [1721642000.514] [55438:55440] [TOO] Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_0002 DataVersion: 1107902942
> [1721642000.514] [55438:55440] [TOO]   StartUpMode: null

 if startup_mode_dut is null, Set the StartUpMode to any mode value listed in the SupportedModes entries. For getting list of supported mode please read the SupportedModes attribute and select the value.

`./chip-tool deviceenergymanagementmode read supported-modes   1 1`

2. TH writes to the DUT the StartUpMode attribute with the any value listed in the supported modes.
`./chip-tool deviceenergymanagementmode write start-up-mode 1  1 1`

> [1721729733.438] [93998:94000] [DMG]                                 status = 0x00 (SUCCESS),
> [1721729733.438] [93998:94000] [DMG]                         },

3. As default value of OnMode attribute is NULL. Set the OnMode to any mode value listed in the SupportedModes entries.

`./chip-tool deviceenergymanagementmode write  on-mode 2 1 1`
> [1721729733.438] [93998:94000] [DMG]                                 status = 0x00 (SUCCESS),
> [1721729733.438] [93998:94000] [DMG]                         },

4. TH reads from the DUT the OnMode attribute.

`./chip-tool deviceenergymanagementmode read on-mode   1 1`
> [1721642080.817] [55449:55452] [TOO] Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_0003 DataVersion: 1107902943
> [1721642080.817] [55449:55452] [TOO]   OnMode: 2

5. If startup_mode_dut is equal to old_on_mode_dut proceed to next step, Otherwise change the OnMode value to different from StartUpmode value.

In above StartUp Mode and onMode values are different So proceeding with next step

6. TH writes to the DUT the StartUpOnOff attribute with the value 1.

`./chip-tool onoff write start-up-on-off 1 1 1`
> [1651101661960] [90832:7598169] CHIP: [DMG] status = 0x00 (SUCCESS),
> [1651101661960] [90832:7598169] CHIP: [DMG] },

**Physically power cycle the device**

7. TH reads from the DUT the StartUpMode attribute.

`./chip-tool deviceenergymanagementmode read start-up-mode   1 1`
> [1721642215.511] [55471:55473] [TOO] Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_0002 DataVersion: 1107902944
> [1721642215.511] [55471:55473] [TOO]   StartUpMode: 1

8. TH reads from the DUT the CurrentMode attribute.

`./chip-tool deviceenergymanagementmode read current-mode   1 1`

**Actual Outcome:**
> [1721642237.336] [55475:55477] [TOO] Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_0001 DataVersion: 1107902944
> **[1721642237.336] [55475:55477] [TOO]   CurrentMode: 1**(CurrentMode attribute value should be same as Onmode value read in the step 4)
> 

**Expected Outcome:**
> [1721642237.336] [55475:55477] [TOO] Endpoint: 1 Cluster: 0x0000_009F Attribute 0x0000_0001 DataVersion: 1107902944
> **[1721642237.336] [55475:55477] [TOO]   CurrentMode: 2**

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

f6022e4b0ff020835f02b85e13875e51a0de3d19 

### Platform

raspi

### Anything else?

As per the Modebase Spec, If the On/Off feature is supported and the On/Off cluster attribute StartUpOnOff  is present, with a value of On (turn on at power up), then the CurrentMode attribute SHALL be set to the OnMode attribute value when the server is supplied with power, except if the OnMode attribute is null. However, in the **Device Energy Management Mode cluster**, the value of the **`CurrentMode`** is not being set to the **`OnMode`** value after powering up the DUT in the current SDK.

**Spec References:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ModeBase.adoc#651-onmode-with-power-up

![image](https://github.com/user-attachments/assets/ad3c488a-88d5-4bff-8ff5-9d8966e5853d)

**Test plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_device_energy_management.adoc

![image](https://github.com/user-attachments/assets/ffee537e-ebff-496a-913d-43465a74befb)

**Test step that require Review:**
Step 12

**Note:**  This functionality is working fine in other mode-based clusters, such as the Laundry Washer Mode Cluster and the Dishwasher Mode Cluster

**Reference Log:**
[TC-DEMM-3.3.txt](https://github.com/user-attachments/files/16361365/TC-DEMM-3.3.txt)

**Comment by jamesharrow** [comment]
Based on discussion in DM TT and EM TT on 1st Aug - we plan now to disallow the OnMode and StartUpMode attributes in the DEMM, EVSEM and WHMM clusters - I will reference this issue in the PR.

These attributes don't make sense for DEM, EVSE and WHM - like the Microwave Oven etc.
