### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-EEVSEM-3.3] Test failing due to CurrentMode value missmatch with OnMode value

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#34506]
### Feature Area

Other

### Test Case

TC-EEVSEM-3.3

### Reproduction steps

1. Execute the below mentioned command to put DUT into a commissionable state :
` ./chip-all-clusters-app`

2. Once DUT reach the commissionable state sent below mentioned command on TH.
`./chip-tool pairing onnetwork 1 20202021`

**Once after successful pairing provide the below commands:**

1. TH reads from the DUT the StartUpMode attribute.

`./chip-tool energyevsemode read start-up-mode  1 1`

> [1721899437.336] [4207:4210] [TOO] Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0002 DataVersion: 2731402180
> [1721899437.336] [4207:4210] [TOO]   StartUpMode: 1

2. TH reads from the DUT the OnMode attribute.

`./chip-tool energyevsemode read on-mode  1 1`

> [1721900058.715] [4247:4249] [TOO] Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0003 DataVersion: 2731402184
> [1721900058.715] [4247:4249] [TOO]   OnMode: 2

3. TH writes to the DUT the StartUpOnOff attribute with the value 1.

`./chip-tool onoff write start-up-on-off 1 1 1`

> [1651101661960] [90832:7598169] CHIP: [DMG] status = 0x00 (SUCCESS),
> [1651101661960] [90832:7598169] CHIP: [DMG] },

**Physically power cycle the device**

4. TH reads from the DUT the StartUpMode attribute.

`./chip-tool energyevsemode read start-up-mode  1 1`

> [1721900430.356] [4288:4290] [TOO] Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0002 DataVersion: 1273214277
> [1721900430.357] [4288:4290] [TOO]   StartUpMode: 1

5. TH reads from the DUT the CurrentMode attribute.

`./chip-tool energyevsemode read current-mode  1 1`

**Actual Outcome:**

> [1705995474.391347][7551:7553] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0001 DataVersion: 1324786556
> **[1705995474.391367][7551:7553] CHIP:TOO:   CurrentMode: 1**(CurrentMode value SHALL be set to the OnMode value when the server is supplied with power)

**Expected Outcome:**

> [1705995474.391347][7551:7553] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0001 DataVersion: 1324786556
> **[1705995474.391367][7551:7553] CHIP:TOO:   CurrentMode: 2**

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

f6022e4b0ff020835f02b85e13875e51a0de3d19

### Platform

raspi

### Anything else?

As per the Modebase Spec, If the On/Off feature is supported and the On/Off cluster attribute StartUpOnOff is present, with a value of On (turn on at power up), then the CurrentMode attribute SHALL be set to the OnMode attribute value when the server is supplied with power, except if the OnMode attribute is null. However, in the Energy EVSE Mode Cluster, the value of the CurrentMode is not being set to the OnMode value after powering up the DUT in the current SDK.

**Test step that require Review:**
Step 12

**Spec References:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ModeBase.adoc#651-onmode-with-power-up

![image](https://github.com/user-attachments/assets/847d9631-2ff1-4e0f-b9c0-03971d811929)

**Test plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_energy_EVSE.adoc

![image](https://github.com/user-attachments/assets/f6370f5a-8a3a-465b-bdca-e0987ffe4a55)

**Note:** This functionality is working fine in other mode-based clusters, such as the Laundry Washer Mode Cluster and the Dishwasher Mode Cluster

**Reference Log:**
[TC-EEVSEM-3.3.txt](https://github.com/user-attachments/files/16377400/TC-EEVSEM-3.3.txt)

**Comment by jamesharrow** [comment]
Based on discussion in DM TT and EM TT on 1st Aug - we plan now to disallow the OnMode and StartUpMode attributes in the DEMM, EVSEM and WHMM clusters - I will reference this issue in the PR.

These attributes don't make sense for DEM, EVSE and WHM - like the Microwave Oven etc.
