### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-EEVSEM-3.1] Test failing due to CurrentMode value missmatch with OnMode value

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#34505]
### Feature Area

Other

### Test Case

TC-EEVSEM-3.1

### Reproduction steps

1. Execute the below mentioned command to put DUT into a commissionable state :
 `./chip-all-clusters-app`

2. Once DUT reach the commissionable state sent below mentioned command on TH.
`./chip-tool pairing onnetwork 1 20202021`

**Once after successful pairing provide the below commands:**

1.TH reads from the DUT the OnMode attribute.

 `./chip-tool energyevsemode read on-mode  1 1`
> [1721730589.194] [94201:94203] [TOO] Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0003 DataVersion: 1716915931
> [1721730589.194] [94201:94203] [TOO]   OnMode: 2

2. TH reads from the DUT the CurrentMode attribute.

`./chip-tool energyevsemode read current-mode  1 1`
> [1705995474.391347][7551:7553] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0001 DataVersion: 1324786556
> [1705995474.391367][7551:7553] CHIP:TOO:   CurrentMode: 0

4. TH sends a Off command to the DUT

`./chip-tool onoff off 1 1`

> [1684931101.118663][20709:20711] CHIP:DMG:                                         status = 0x00 (SUCCESS),
> [1684931101.118665][20709:20711] CHIP:DMG:                                 },

5. TH sends a On command to the DUT

`./chip-tool onoff on 1 1`

> [1684931217.055520][20729:20731] CHIP:DMG:                                         status = 0x00 (SUCCESS),
> [1684931217.055523][20729:20731] CHIP:DMG:                                 },

6. TH reads from the DUT the CurrentMode attribute.

`./chip-tool energyevsemode read current-mode  1 1`

**Actual Outcome:**

> [1705995474.391347][7551:7553] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0001 DataVersion: 1324786556
> **[1705995474.391367][7551:7553] CHIP:TOO:   CurrentMode: 0** (CurrentMode attribute value should be set to the OnMode attribute value once the OnOff state has changed from OFF to ON)

**Expected Outcome:**

> [1705995474.391347][7551:7553] CHIP:TOO: Endpoint: 1 Cluster: 0x0000_009D Attribute 0x0000_0001 DataVersion: 1324786556
> **[1705995474.391367][7551:7553] CHIP:TOO:   CurrentMode: 2**

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

f6022e4b0ff020835f02b85e13875e51a0de3d19

### Platform

raspi

### Anything else?

As per the Modebase spec, the CurrentMode attribute value should be set to the OnMode attribute value once the OnOff state has changed from OFF to ON. However, in the  Energy EVSE Mode cluster, the CurrentMode value is not being set to the OnMode value when the OnOff value is changed from OFF to ON.

**Test step that require Review:**
Step 8

**Specification Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/ModeBase.adoc#65-onmode-attribute

![image](https://github.com/user-attachments/assets/50062269-f450-436c-91f0-f4734e6c3548)

**Test plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/mode_energy_EVSE.adoc

![image](https://github.com/user-attachments/assets/35018b31-1284-4f33-a452-a8ab77b588a5)

**Note:** This functionality is working fine in other mode-based clusters, such as the Laundry Washer Mode Cluster and the Dishwasher Mode Cluster

**Reference Log:**
[TC-EEVSEM-3.1.txt](https://github.com/user-attachments/files/16377114/TC-EEVSEM-3.1.txt)

**Comment by jamesharrow** [comment]
Based on discussion in DM TT and EM TT on 1st Aug - we plan now to disallow the OnMode and StartUpMode attributes in the DEMM, EVSEM and WHMM clusters - I will reference this issue in the PR.

These attributes don't make sense for DEM, EVSE and WHM - like the Microwave Oven etc.
