### ISSUE TITLE
[1.3] Problem about the Chip-tool Any command

### ISSUE THREAD

**Issue by agatah2333** [project-chip/connectedhomeip#34524]
### Reproduction steps

./chip-tool any write-by-id 0x0030 0x00 "[{"2":1,"4":6}]" 0x654324 0 ---get constraint error

 ./chip-tool binding write binding '[{ "group":1, "cluster":6}]' 0x654324 0 ---could work normal

I wonder why two same commands will get different result

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

core

### Platform Version(s)

1.3

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
> ./chip-tool any write-by-id 0x0030 0x00 "[{"2":1,"4":6}]" 0x654324 0 ---get constraint error

Where is `0x0030` coming from?  Cluster `0x0030` is General Commissioning, so this is trying to write the Breadcrumb attribute to a value not valid for it.

Binding is cluster `0x001E` (_decimal_ 30, not hex).
