### ISSUE TITLE
Restyled fails to create restyled pull request.

### ISSUE THREAD

**Issue by gjc13** [project-chip/connectedhomeip#3453]
#### Problem
https://restyled.io/gh/project-chip/repos/connectedhomeip/jobs/419793

Restyled complains
```
stderrerror: failed to push some refs to 'https://<SCRUBBED>@github.com/project-chip/connectedhomeip.git'
stderrWe had trouble running a system command:
stderr
stderr  callProcess: git "push" "--force-with-lease" "origin" "restyled/pull-3452" (exit
stderr  1): failed
```

We've encountered this issue in multiple PRs.

 #### Proposed Solution
Is it github access token issue?

**Comment by rwalker-apple** [comment]
this is a known issue with  restyled

if a PR needs a restyle and the PR includes a modification to //.github/workflows, the restyle push fails (independent of whether any workflow needs restyling)

a workaround is to run //scripts/helpers/restyle-diff.sh from // before pushing your PR.
