### ISSUE TITLE
ESP32 with Google home mini 

### ISSUE THREAD

**Issue by jarvissd** [project-chip/connectedhomeip#34530]
### Reproduction steps

hi everyone, i have a problem about connecting ESP32 with google home mini.
I used examples all-cluster-app and lighting-app for ESP32 then tried to connect it to google home through google home mini device and it failed. 
I can add ESP32 in many apps like ESP-rainmaker, life-smart, tuya,.. but when i added it into google home, esp just connected to wifi and both the google home mini device and google home app still didn't add it
Is it possible to connect it ? or did i do somethings wrong? 
I use ESP32 Wroom32 C3 
Can somebody give me an advise or idea for this? 
Thank a lot <3

### Bug prevalence

everytime

### GitHub hash of the SDK that was being used

all-cluster-app and lighting-app for esp32

### Platform

esp32

### Platform Version(s)

1.3

### Type

Test Improvement

**Comment by andy31415** [comment]
This seems google-specific rather that matter SDK directly. https://developers.home.google.com/matter has a communities bit that should probably be used instead.
