### ISSUE TITLE
[1.3] BatPercentRemaining Attribute display 'ERROR'in Google Home

### ISSUE THREAD

**Issue by KEEPHEADU** [project-chip/connectedhomeip#34533]
### Reproduction steps

I used silabs EFR32MG24 to develop the matter device. Use the following two SDKS, which support Matter 1.3.

[SiliconLabs/matter_extension at v2.3.0 (github.com)](https://github.com/SiliconLabs/matter_extension/tree/v2.3.0)

[SiliconLabs/simplicity_sdk: The Simplicity Software Development Kit (SDK) is an embedded software de...](https://github.com/SiliconLabs/simplicity_sdk)

In the device, I implemented the BatPercentRemaining Attribute in the Power Source Cluster, which correctly displays the percentage of battery remaining in the device in HomePod, but displays ERROR in Google Home.

### Bug prevalence

any time

### GitHub hash of the SDK that was being used

no

### Platform

efr32

### Platform Version(s)

1.3

### Type

Platform Issue

**Comment by andy31415** [comment]
Please use the communities in https://developers.home.google.com/matter since this seems to be google-home specific rather than generic SDK.
