### ISSUE TITLE
[Feature] Implements the Ecosystem Information Server in Matter SDK

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#34553]
### Feature description

Add Ecosystem Information Cluster Server implementation to src/app/clusters/ for provisional fabric sync

This registers AttributeAccessInterface so that we can override the read attributes. This instance was developed in a way so that ownership of the underlying types are embedded into the Device and Location structs themselves and that we would only create instance of those structs if the data is valid.

To be completed in follow up PRs:
Proper fabric scoping of elements in the device and location lists.
Testing:
With local changes to examples/fabric-bridge-app/ confirmed was able to read attributes from EcosystemInformationCluster

### Platform

other

**Comment by tehampson** [comment]
Issue is still opened as unit test should be added and we still need to address Fabric scoped entries
