### ISSUE TITLE
[1.4][TC-PS-2.3] Python script has to be updated as per the test plan

### ISSUE THREAD

**Issue by KishokG** [project-chip/connectedhomeip#34575]
### Feature Area

Other

### Test Case

TC-PS-2.3

### Description

- For TC-PS-2.3, the Python script has to be updated from Step 2 to 9 as per the test plan.

**Python script reference:** https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_PS_2_3.py

![image](https://github.com/user-attachments/assets/24d8d35b-710c-4c01-aefa-38e93a49eb9a)

**Test plan Reference:** https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/powersource.adoc#tc-ps-2-3-reporting-requirements-with-dut_server

![image](https://github.com/user-attachments/assets/91ce1651-2439-499f-befc-c21b6224f029)

### GitHub hash of the SDK that was being used

13fe13ae3b61a5b9adb3b1ab8248fa3db11dddf2

### Platform

raspi

**Comment by cjandhyala** [comment]
not an issue, as script is doing the essential parts of test plan. closing the issue.
