### ISSUE TITLE
[Feature][Darwin] Question of EventNameForID function plan

### ISSUE THREAD

**Issue by joonhaengHeo** [project-chip/connectedhomeip#34573]
### Feature description

Are there any plans to support a function that can return EventName with Event ID similar to the function below?
https://github.com/project-chip/connectedhomeip/blob/13fe13ae3b61a5b9adb3b1ab8248fa3db11dddf2/src/darwin/Framework/CHIP/MTRClusterNames.h#L43C88-L43C109

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
We could add something like this.  The only reason it's not there so far is that there weren't any known use cases...

**Comment by joonhaengHeo** [comment]
@bzbarsky-apple 
I needed this, so I implemented it separately and used it. Is it okay if I contribute it?

**Comment by bzbarsky-apple** [comment]
@joonhaengHeo Absolutely, yes!

**Comment by joonhaengHeo** [comment]
@bzbarsky-apple 
Thanks. I upload new PR about this.
