### ISSUE TITLE
[BUG] Color control Q - Remaining time appears to only report at 0

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#34643]
### Reproduction steps

See TC_CC_2.2

### Bug prevalence

always

### GitHub hash of the SDK that was being used

3263e403469fd66827d923484a50ddb504544112

### Platform

core

**Comment by bzbarsky-apple** [comment]
This _might_ be related to https://github.com/project-chip/connectedhomeip/issues/34618.  Can't say for sure because I am not clear on the steps to reproduce for this issue.

**Comment by cecille** [comment]
yup - seems related. Test is still up in PR form, but I'm seeing only 1 report come back.
