### ISSUE TITLE
[BUG] Q color control too many reports

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#34646]
### Reproduction steps

Getting more reports than expected on transitions. looks like 1 per second even after transition is complete. Or something.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

3263e403469fd66827d923484a50ddb504544112

### Platform

core

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs

**Comment by jmartinez-silabs** [comment]
@cecille Depending on the transition time, the report interval could be 1s. This should be the smaller interval of report posible. Other than end of transition report. 

Can you clarify/what step we're done to see report after transition? That should not be possible. the new code is only exercise on the calculation of the steps.

I'll have to look at it on Monday, I am still away
