### ISSUE TITLE
Fix remaining issues in TC_SWTCH.py that didn't make TE2 deadline

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#34656]
- [x] TC-SWTCH-2.2 step 7 has to be implemented (> 2 position latching)
- [x] Steps for TC-SWTCH-2.4 have to be reconciled to plan and provided in the steps list
- [x] `_placeholder_for_step` has to be repaced
- [x] Switch pressed position must be configurable by PIXIT/arg
- [x] Test plan has to be triple-checked to script and back-annotated
- [x] Check short-release test (added by Cecille)

**Comment by tcarmelveilleux** [comment]
Test plan was: https://github.com/CHIP-Specifications/chip-test-plans/pull/4241

**Comment by cecille** [comment]
One more - I think the short release test plan might be incorrect and hence the script is also incorrect

**Comment by tcarmelveilleux** [comment]
All fixed.
