### ISSUE TITLE
Add more tests to the Thermostat presets test for testing the presets constraints- TC_TSTAT_4_2

### ISSUE THREAD

**Issue by nivi-apple** [project-chip/connectedhomeip#34695]
# TODO: Add tests for the total number of Presets exceeds the NumberOfPresets supported. Also Add tests for adding presets with preset scenario not present in PresetTypes

**Comment by nivi-apple** [comment]
Follow up - have a test exercising the "empty and null are treated identically" behavior, though. for the preset handles. 

test "negative" at all, like change an expected success assertion  for a different status code and see that the way you catch failures leads to expected logs and failure, rather than a different exception? 
Make sure that a really failing product leads to a clean fail of the test.

**Comment by ReneJosefsen** [comment]
@ReneJosefsen - Open test plan issues for this and use this issue for making sure we align the scripts accordingly
