### ISSUE TITLE
[CERT-TEST-FAILURE] TC-MCORE-FS-1.2 - AttributeError and ValueError in TC-MCORE-FS-1.2 Test Case

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#34706]
### Feature Area

Other

### Test Case

TC-MCORE-FS-1.2

### Reproduction steps

The TC-MCORE-FS-1.2 test case fails due to two distinct errors:

1. An AttributeError occurs during the execution of the test_TC_MCORE_FS_1_2 method.
2. A ValueError occurs during the on_fail method execution, indicating that ctypes objects containing pointers cannot be pickled.

**TH/TH_FSA** - python controller
commands used to build -
- source scripts/activate.sh && scripts/build_python.sh -m platform -d true -i no
- source no/bin/activate

**DUT/DUT_FSA** - fabric-bridge-app
- ./scripts/examples/gn_build_example.sh examples/fabric-bridge-app/linux out/debug/standalone chip_config_network_layer_ble=false 'import("//with_pw_rpc.gni")'

**Command used to launch the DUT :** ` ./fabric-bridge-app`
**Command used to run the python script :**` python3 TC_MCORE_FS_1_2.py  --commissioning-method on-network --discriminator 3840 --passcode 20202021 --paa-trust-store-path ../../credentials/development/paa-root-certs/ --storage-path admin_storage.json`

> [MatterTest] 08-01 11:01:05.847 ERROR Exception occurred in test_TC_MCORE_FS_1_2.
> Traceback (most recent call last):
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 783, in exec_one_test
>     test_method()
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/src/python_testing/matter_testing_support.py", line 1671, in async_runner
>     return _async_runner(body, self, *args, **kwargs)
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/src/python_testing/matter_testing_support.py", line 1659, in _async_runner
>     return asyncio.run(runner_with_timeout)
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
>     return fut.result()
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/src/python_testing/TC_MCORE_FS_1_2.py", line 63, in test_TC_MCORE_FS_1_2
>     sub = await self.default_controller.ReadAttribute(
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/no/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 1606, in ReadAttribute
>     res = await self.Read(nodeid,
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/no/lib/python3.10/site-packages/chip/ChipDeviceCtrl.py", line 1536, in Read
>     return await future
> chip.exceptions.ChipStackError: IM Error 0x00000580: General error: 0x80 (INVALID_ACTION)
> [MatterTest] 08-01 11:01:05.861 ERROR Exception happened when executing on_fail for test_TC_MCORE_FS_1_2.
> Traceback (most recent call last):
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 646, in _exec_procedure_func
>     func(copy.deepcopy(tr_record))
>   File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
>     state = deepcopy(state, memo)
>   File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
>     y = copier(x, memo)
>   File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
>     y[deepcopy(key, memo)] = deepcopy(value, memo)
>   File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
>     y = copier(memo)
>   File "/home/ubuntu/Jul_Dut/connectedhomeip/no/lib/python3.10/site-packages/mobly/records.py", line 280, in __deepcopy__
>     exception = copy.deepcopy(self.exception)
>   File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
>     y = _reconstruct(x, memo, *rv)
>   File "/usr/lib/python3.10/copy.py", line 265, in _reconstruct
>     y = func(*args)
>   File "/usr/lib/python3.10/copy.py", line 264, in <genexpr>
>     args = (deepcopy(arg, memo) for arg in args)
>   File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
>     rv = reductor(4)
> ValueError: ctypes objects containing pointers cannot be pickled
> [MatterTest] 08-01 11:01:05.858 INFO >>> [E:49663i S:47664 M:125989985 (Ack:40073821)] (S) Msg RX from 1:0000000012344321 [603A] --- Type 0000:10 (SecureChannel:StandaloneAck) (B:34)
> [MatterTest] 08-01 11:01:05.899 INFO [Test] test_TC_MCORE_FS_1_2 ERROR
> [MatterTest] 08-01 11:01:05.930 INFO Summary for test class TC_MCORE_FS_1_2: Error 1, Executed 1, Failed 0, Passed 0, Requested 1, Skipped 0
> 

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

5d280dedd0bcea407f575aef11e67c8bb7f0a7a1

### Platform

raspi

### Anything else?

**PFA log below :** 
[TC_MCORE_FS_1_2.txt](https://github.com/user-attachments/files/16456212/TC_MCORE_FS_1_2.txt)
[TC_MCORE_FS_1_2_DUT.txt](https://github.com/user-attachments/files/16456213/TC_MCORE_FS_1_2_DUT.txt)

**Python script for reference :** 
https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_MCORE_FS_1_2.py

**Comment by cecille** [comment]
pickling error was a problem with the base framework, it is a symptom, not a cause and it is fixed by 
https://github.com/project-chip/connectedhomeip/pull/35016
