### ISSUE TITLE
[1.3] Duplicate attributes shows in Fan Control Cluster

### ISSUE THREAD

**Issue by agatah2333** [project-chip/connectedhomeip#34723]
### Reproduction steps

Fan Control Cluster has duplicate attributes when the ID is 0x01 and has conflicting access descriptions.

![image](https://github.com/user-attachments/assets/abe45294-cdc2-4f43-9851-c4ed4fef9489)

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

core

### Platform Version(s)

1.3

### Type

Spec Compliance Issue

**Comment by bzbarsky-apple** [comment]
Not an SDK issue, but note the different Conformance values.  Those two rows are supposed to be mutually exclusive.
