### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-OCC-3.1, 3.2] - Python Script Failure

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#34730]
### Feature Area

Other

### Test Case

TC-OCC-3.1
TC-OCC-3.2

### Reproduction steps

1. Command used to launch the DUT : `./chip-all-clusters-app `
2. Command used to run the python script : `python3 TC_OCC_3_2.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --storage-path admin_storage.json  --paa-trust-store-path ../../credentials/development/paa-root-certs/`

While executing the TC-OCC-3.2 python script, Test case is failing due to the `AttributeError: module 'chip.ChipDeviceCtrl' has no attribute 'ReadAttribute'` error. . 

In Python script line number 142 `ChipDeviceCtrl` has to be updated to Actual controller object.

> [MatterTest] 08-02 08:10:37.058 INFO 		***** Test Step 2 : TH establishes a wildcard subscription to all attributes on Occupancy Sensing Cluster on the endpoint under test. Subscription min interval = 0 and max interval = 30 seconds.
> [MatterTest] 08-02 08:10:37.061 ERROR Exception occurred in test_TC_OCC_3_2.
> Traceback (most recent call last):
>   File "/home/ubuntu/master_CNTRL/connectedhomeip/no/lib/python3.10/site-packages/mobly/base_test.py", line 783, in exec_one_test
>     test_method()
>   File "/home/ubuntu/master_CNTRL/connectedhomeip/src/python_testing/matter_testing_support.py", line 1671, in async_runner
>     return _async_runner(body, self, *args, **kwargs)
>   File "/home/ubuntu/master_CNTRL/connectedhomeip/src/python_testing/matter_testing_support.py", line 1659, in _async_runner
>     return asyncio.run(runner_with_timeout)
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
>     return fut.result()
>   File "/home/ubuntu/master_CNTRL/connectedhomeip/src/python_testing/TC_OCC_3_2.py", line 142, in test_TC_OCC_3_2
>     await attrib_listener.start(ChipDeviceCtrl, node_id, endpoint=endpoint_id)
>   File "/home/ubuntu/master_CNTRL/connectedhomeip/src/python_testing/matter_testing_support.py", line 360, in start
>     self._subscription = await dev_ctrl.ReadAttribute(
> AttributeError: module 'chip.ChipDeviceCtrl' has no attribute 'ReadAttribute'
> [MatterTest] 08-02 08:10:37.068 INFO 		***** Test Failure : 
> 

### Anything else?

**Python Script References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_OCC_3_2.py

![image](https://github.com/user-attachments/assets/64ad996c-cb72-472a-b7d3-60a724cd58f3)

**Reference Log:**
[TC-OCC-3.2.txt](https://github.com/user-attachments/files/16468517/TC-OCC-3.2.txt)
[TC-OCC-3.1.txt](https://github.com/user-attachments/files/16468522/TC-OCC-3.1.txt)

**Comment by jaehs6sam** [comment]
Need to change to self.default_controller instead of ChipDeviceCtrl
