### ISSUE TITLE
[1.3] Issues about Thermostat cluster

### ISSUE THREAD

**Issue by agatah2333** [project-chip/connectedhomeip#34793]
### Reproduction steps

1. <img width="1144" alt="image" src="https://github.com/user-attachments/assets/f9387ae8-16bc-402e-b10d-296f1a958344">
https://github.com/project-chip/connectedhomeip/blob/v1.3.0.0/src/app/zap-templates/zcl/data-model/chip/thermostat-cluster.xml
<img width="605" alt="image" src="https://github.com/user-attachments/assets/cb2e1737-cbae-4ac9-a565-84264adc0e0a">
Attribute Occupancy Should be OccupancyBitmap: The attribute Occupancy should be renamed to OccupancyBitmap, but the definition of this type is missing.

2. HVACSystemTypeBitmap Defined but Unused: The HVACSystemTypeBitmap is defined but never used. It should be associated with constraint 0x0009.

3. Attribute Types for IDs 0x0011-0x0018 Should be Temperature: The types of attributes with IDs from 0x0011 to 0x0018 should be temperature.
<img width="615" alt="image" src="https://github.com/user-attachments/assets/72e113cf-17f7-4ac6-a3e3-7d2e81426b69">

### Bug prevalence

each time

### GitHub hash of the SDK that was being used

561d23d0db215a99705ff0696e73853c8edf11b2 

### Platform

core

### Platform Version(s)

1.3

### Type

Spec Compliance Issue

**Comment by hasty** [comment]
I believe these were all fixed in #34570

**Comment by agatah2333** [comment]
> I believe these were all fixed in #34570

Will the fixed MR be picked up in branch 1.3?

**Comment by bzbarsky-apple** [comment]
No, this sort of work will not get backported to stable branches.
