### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-ICDB-2.4] -At Step 3b, the DUT is expected not to send Check-In Messages to TH1 and TH2 after MaxInterval cycles. Currently, the DUT is sending Check-In Messages to both TH1 and TH2 after these MaxInterval cycles.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#34802]
### Feature Area

Area:ICDPhase2

### Test Case

TC-ICDB-2.4

### Reproduction steps

 **As per test plan test step 3b says after waiting 1 or more max of MaxInterval1 and MaxInterval2. DUT sends subscription reports periodically to TH1 and TH2 within their perspective MaxInterval1 and MaxInterval2 time. **DUT does not send check-in message to client. but currently in SDK ,  TH1 and TH2 is receiving  check-in message**
![image](https://github.com/user-attachments/assets/ea01dd39-6b03-426f-8aee-933de0d3f94c)

**Use  below commands to provision the DUT with 2 TH's in RPI platform**
execute the below mentioned command to put DUT into a commissionable state, Pls use equivalent command on the respective DUT
**./lit-icd-app**

Once DUT reach the commissionable state pls send below mentioned command on TH's respectively. Pls use equivalent command on the respective DUT
Provision the device using chip tool on first controller(TH1)
` ./chip-tool pairing onnetwork 1 20202021
`
./chip-tool pairing open-commissioning-window 1 1 400 2000 3840 
Provision the device using chip tool on 2nd controller(TH2)
 ` ./chip-tool pairing code 2 36453420312(mannualcode) --commissioner-name beta`

at step 3a - for TH1 and TH2 - Activate the subscription to subscribe to all by sending below mentioned command 

From TH1:
 >>> any subscribe-by-id 0xFFFFFFFF 0xFFFFFFFF 10 100 1 0

and From TH2 : 
 >>> any subscribe-by-id 0xFFFFFFFF 0xFFFFFFFF 30 300 2 0 --commissioner-name beta
 
**At step 3b - After waiting for one or more MaxInterval cycles, DUT should not send any check-in messages to either TH1 or TH2 during this period but currently in SDK, TH1 and TH2 is receiving  check-in message.**
On TH1 - 

> [1721996800.985] [41041:41043] [EM] >>> [E:12802r S:29377 M:175964098 (Ack:102078201)] (S) Msg RX from 1:0000000000000001 [3682] --- Type 0000:10 (SecureChannel:StandaloneAck) (B:18)
> [1721996800.985] [41041:41043] [EM] Found matching exchange: 12802r, Delegate: (nil)
> [1721996800.985] [41041:41043] [EM] Rxd Ack; Removing MessageCounter:102078201 from Retrans Table on exchange 12802r
> [1721996801.177] [41041:41043] [EM] >>> [E:12803r S:0 M:208169304] (U) Msg RX from 0:D1A5199F7092F335 [0000] --- Type 0000:50 (SecureChannel:ICD_CheckInMessage) (B:57)
> [1721996801.177] [41041:41043] [EM] Handling via exchange: 12803r, Delegate: 0x55fb47e3aac0
> [1721996801.177] [41041:41043] [ICD] Check In Message processing complete: start_counter=2047272997 offset=3 nodeid=<000000000001B669, 1>
> [1721996801.177] [41041:41043] [TOO] The node <000000000001B669, 1> is not the one we are interested in.
> [1721996810.995] [41041:41043] [EM] >>> [E:12805r S:29377 M:175964099] (S) Msg RX from 1:0000000000000001 [3682] --- Type 0001:05 (IM:ReportData) (B:25)
> [1721996810.995] [41041:41043] [EM] Handling via exchange: 12805r, Delegate: 0x55fb47e3e868
> [1721996810.995] [41041:41043] [DMG] ReportDataMessage =

**On TH2 -** 

> [1721996831.018] [51881:51883] [EM] >>> [E:12812r S:47654 M:210958835 (Ack:75847648)] (S) Msg RX from 1:0000000000000002 [09FE] --- Type 0000:10 (SecureChannel:StandaloneAck) (B:18)
> [1721996831.018] [51881:51883] [EM] Found matching exchange: 12812r, Delegate: (nil)
> [1721996831.018] [51881:51883] [EM] Rxd Ack; Removing MessageCounter:75847648 from Retrans Table on exchange 12812r
> [1721996831.214] [51881:51883] [EM] >>> [E:12814r S:0 M:208169311] (U) Msg RX from 0:CB0FA3DF99C27D95 [0000] --- Type 0000:50 (SecureChannel:ICD_CheckInMessage) (B:57)
> [1721996831.214] [51881:51883] [EM] Handling via exchange: 12814r, Delegate: 0xaaaad62273f8
> [1721996831.215] [51881:51883] [ICD] Check In Message processing complete: start_counter=2047272998 offset=5 nodeid=<000000000001B669, 1>
> [1721996831.215] [51881:51883] [TOO] The node <000000000001B669, 1> is not the one we are interested in.
> [1721996841.224] [51881:51883] [EM] >>> [E:12817r S:0 M:208169313] (U) Msg RX from 0:52A62AA8254EE0BC [0000] --- Type 0000:50 (SecureChannel:ICD_CheckInMessage) (B:57)
> [1721996841.224] [51881:51883] [EM] Handling via exchange: 12817r, Delegate: 0xaaaad62273f8
> 

**PFA Log below** 
[TC-ICDB-2.4 DUT.txt](https://github.com/user-attachments/files/16506836/TC-ICDB-2.4.DUT.txt)
[TC-ICDB-2.4 TH1.txt](https://github.com/user-attachments/files/16506839/TC-ICDB-2.4.TH1.txt)
[TC-ICDB-2.4 TH2.txt](https://github.com/user-attachments/files/16506840/TC-ICDB-2.4.TH2.txt)

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

a5124a9e5b8fdaed6d7304d406c0edb2cf4a49dd (Master)

### Platform

raspi

### Anything else?

**Test Plan Reference**  : 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/icdbehavior.adoc#tc-icdb-2-4-icd-state-machine-multiple-fabrics-dut_server

**Comment by yunhanw-google** [comment]
dup with https://github.com/project-chip/connectedhomeip/issues/34803
