### ISSUE TITLE
[BUG] (Android) Commissioning to a custom fabric, FindOperational fails with CHIP Error 0x00000054: Invalid CASE parameter

### ISSUE THREAD

**Issue by NagendraMudadla** [project-chip/connectedhomeip#34838]
### Reproduction steps

I have added the Wi-Fi socket that I'm attempting to commission to a custom fabric. I've got self-signed RCAC and use it to provide a NOC during commissioning.  The NOC generation is completed.
Attempts to establish CASE
Sent Sigma3 msg. 
Fails with  Error on commissioning step 'FindOperational': 'src/protocols/secure_channel/CASESession.cpp:1918: CHIP Error 0x00000054: Invalid CASE parameter'
Any provide a proper solution how to resolve?.
Attached the both App side and device firmware side logs
[CASE_Session_failure.txt](https://github.com/user-attachments/files/16518302/CASE_Session_failure.txt)
 below for references.
[Matter Device App Side Log.txt](https://github.com/user-attachments/files/16518286/Matter.Device.App.Side.Log.txt)

### Bug prevalence

hour

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/commit/8f66f4215bc0708efc8cc73bda80620e67d8955f

### Platform

android

**Comment by joonhaengHeo** [comment]
It looks like you issued a separate certificate including the NOC. Did you add the rootCA and NOC (Optional ICA) correctly? I think we need to look at the certificate to be able to analyze it.
