### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-OCC-3.1, 3.2] - Python Script Failure

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#34844]
### Feature Area

Other

### Test Case

- [ ] TC-OCC-3.1
- [ ] TC-OCC-3.2

### Reproduction steps

1. Command used to launch the DUT :` ./chip-all-clusters-app `
2. Command used to run the python script : `python3 TC_OCC_3_1.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --endpoint 1 --storage-path admin_storage.json  --paa-trust-store-path /credentials/development/paa-root-certs/`

While executing the **TC-OCC-3.1** Python script, the test is failing at Test Step 4: `Trigger DUT occupancy sensing to change the occupancy state and start a timer`. This test step expects to trigger the DUT to change the occupancy state of occupancy sensing and Then reading the Occupancy state. However, the script does not include any method to trigger the DUT. So it is not changing the Occupancy state and test step is failing.  Therefore, the Python script needs to be updated to include a method for triggering the DUT.

> [MatterTest] 08-07 06:10:07.702 INFO 		***** Test Step 4 : Trigger DUT occupancy sensing to change the occupancy state and start a timer.
> [MatterTest] 08-07 06:10:07.703 INFO <<< [E:48350i S:656 M:139433196 (Ack:256120593)] (S) Msg TX to 1:0000000012344321 [AAF5] [UDP:[fe80::42c:dbff:fe1f:df40%veth59bd233]:5540] --- Type 0000:10 (SecureChannel:StandaloneAck) (B:34)
> [MatterTest] 08-07 06:10:07.703 INFO ========= USER PROMPT =========
> [MatterTest] 08-07 06:10:07.704 INFO >>> Type any letter and press ENTER after a sensor occupancy is triggered. (press enter to confirm)
> [MatterTest] 08-07 06:10:07.816 INFO Avahi browse: remove
> A
> [MatterTest] 08-07 06:11:01.307 INFO Found an existing secure session to [1:0000000012344321]!
> [MatterTest] 08-07 06:11:01.313 INFO 0 data version filters provided, 0 not relevant, 0 encoded, 0 skipped due to lack of space
> [MatterTest] 08-07 06:11:01.315 INFO <<< [E:48351i S:656 M:139433197] (S) Msg TX to 1:0000000012344321 [AAF5] [UDP:[fe80::42c:dbff:fe1f:df40%veth59bd233]:5540] --- Type 0001:02 (IM:ReadRequest) (B:52)
> [MatterTest] 08-07 06:11:01.319 INFO >>> [E:48351i S:656 M:256120594 (Ack:139433197)] (S) Msg RX from 1:0000000012344321 [AAF5] --- Type 0001:05 (IM:ReportData) (B:71)
> [MatterTest] 08-07 06:11:01.331 INFO <<< [E:48351i S:656 M:139433198 (Ack:256120594)] (S) Msg TX to 1:0000000012344321 [AAF5] [UDP:[fe80::42c:dbff:fe1f:df40%veth59bd233]:5540] --- Type 0000:10 (SecureChannel:StandaloneAck) (B:34)
> [MatterTest] 08-07 06:11:01.332 ERROR Exception occurred in test_TC_OCC_3_1.
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/dist-packages/mobly/base_test.py", line 818, in exec_one_test
>     test_method()
>   File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 1743, in async_runner
>     return _async_runner(body, self, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 1731, in _async_runner
>     return asyncio.run(runner_with_timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
>     return await fut
>            ^^^^^^^^^
>   File "/root/python_testing/scripts/sdk/TC_OCC_3_1.PY", line 115, in test_TC_OCC_3_1
>     asserts.assert_equal(occupancy_dut, 1, "Occupancy state is not changed to 1")
>   File "/usr/local/lib/python3.12/dist-packages/mobly/asserts.py", line 66, in assert_equal
>     _call_unittest_assertion(
>   File "/usr/local/lib/python3.12/dist-packages/mobly/asserts.py", line 50, in _call_unittest_assertion
>     raise signals.TestFailure(my_msg, extras=extras)
> mobly.signals.TestFailure: Details=0 != 1 Occupancy state is not changed to 1, Extras=None
> [MatterTest] 08-07 06:11:01.350 INFO 		***** Test Failure : 

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

 d0d91272068f267cf880f9d56787ca28da885673 

### Platform

raspi

### Anything else?

**Facing same Issue with TC-OCC-3.2.**

**Python Script References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_OCC_3_1.py
- https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_OCC_3_2.py

**Reference Log:**
[TC-OCC-3.1.txt](https://github.com/user-attachments/files/16519309/TC-OCC-3.1.txt)
[TC-OCC-3.2.txt](https://github.com/user-attachments/files/16519700/TC-OCC-3.2.txt)

**Comment by jaehs6sam** [comment]
This issue should be addressed by PR #34686 merging.
