### ISSUE TITLE
[CERT-TEST-FAILURE] TC_PWRTL_2_1.py is not matching testplan

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#34847]
### Feature Area

Other

### Test Case

TC_PWRTL_2_1

### Reproduction steps

The test has multiple errors:
*  https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_PWRTL_2_1.py#L64 is  checks for a list length of up to 21 entries, but should be 20
* The test verifies "null" cases and matches, but the tested attributes are both not nullable as by specification. This is also not required by the test plan as all.
*  The script misses the length and “subset” validation requirements from the testplan for the second attribute.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

master

### Platform

other

**Comment by cjandhyala** [comment]
closing the ticket , since PR is merged.
