### ISSUE TITLE
ServiceArea server: compare structs directly

### ISSUE THREAD

**Issue by plauric** [project-chip/connectedhomeip#34859]
This is just comparing two optional structs, right? can you not just use the default comparison operator? 
ex
if (areaDesc.landmarkInfo != aOther.areaDesc.landmarkInfo) {
return false;
}

_Originally posted by @cecille in https://github.com/project-chip/connectedhomeip/pull/34738#discussion_r1707860518_

**Comment by hicklin** [comment]
This is not possible as there auto-generated structures do not implement the `!=` operator.
