### ISSUE TITLE
[CERT-TEST-FAILURE] ICDM-3.4 python script doesn't work in practice

### ISSUE THREAD

**Issue by fessehaeve** [project-chip/connectedhomeip#34985]
### Feature Area

Area:ICDPhase2

### Test Case

TC-ICDM-3.4

### Reproduction steps

Run tests until step 2b and observe that after DUT reboots, previous secure session is not usable anymore. Therefore, test fails.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

350b13f76c0ad630081c4e50d608f6d62477ac1a

### Platform

python

### Anything else?

There needs to be a way for DUTs or controllers to fallback to establishing a new secure session in such scenarios.

**Comment by mkardous-silabs** [comment]
@fessehaeve  how do other reboot test cases succeed if the a new secure session cannot established?

**Comment by fessehaeve** [comment]
> @fessehaeve how do other reboot test cases succeed if the a new secure session cannot established?

@mkardous-silabs this is an issue since chip-tool interactive mode and the python chip reuse the session. I am not sure if there is a python test that involves rebooting the DUT. May be @cecille or @ReneJosefsen could know about such a test?
