### ISSUE TITLE
[TC_BOOLCFG_3_1] Cosmetic update - Modify Feature Name in Python Script from SENS to SENSLVL at Step 2b in python script

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#35033]
**Description** 
In the current Python script, step 2b states: TestStep("2b", "Verify SENS feature is supported"). This feature name should be updated to SENSLVL to align with the test plan and improve clarity.

**Requested Change:**
Modify the feature name in the script from SENS to SENSLVL at step 2b.

**Test Plan Reference** 
![image](https://github.com/user-attachments/assets/adbe1661-062b-474a-8ad3-77e953508812)
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/boolean_state_configuration.adoc#tc-boolcfg-3-1-sensitivitylevel-with-dut_server

**Script reference :** 
![image](https://github.com/user-attachments/assets/604415aa-95ec-437f-afa8-371f7215d386)

https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_BOOLCFG_3_1.py

**Comment by Harshith-GRL** [comment]
@ReneJosefsen I am raising a PR for this issue you can ignore this issue.
