### ISSUE TITLE
[1.3] Google Home Can't connect to your device

### ISSUE THREAD

**Issue by KEEPHEADU** [project-chip/connectedhomeip#35047]
### Reproduction steps

I used silabs EFR32MG24 to develop the matter device. Use the following two SDKS, which support Matter 1.3.

[SiliconLabs/matter_extension at v2.3.0 (github.com)](https://github.com/SiliconLabs/matter_extension/tree/v2.3.0)

[SiliconLabs/simplicity_sdk: The Simplicity Software Development Kit (SDK) is an embedded software de...](https://github.com/SiliconLabs/simplicity_sdk)

Google Home version: 3.21.1.8
Nest Hub 2 software version: 58.102.2.613521407

I use the test certificate for development, in the multiple commissioning rounds of Google Home often appear 'Can't connect to your device', the error log is attached.

It usually appears after this step:
![lQDPJxH0b0J3_5fNCWDNBDiwNcjbLq7z3zAGqW1XneY9AA_1080_2400](https://github.com/user-attachments/assets/527b0bd5-0c0e-4bb3-8053-e994258e8798)

The choice `Set up anyway` will follow. It will come right after that:
![lADPM4c6JKYyrPPNCWDNBDg_1080_2400](https://github.com/user-attachments/assets/8b8a57d9-d072-419f-ac78-180934b62ef8)

[failed-log.txt](https://github.com/user-attachments/files/16643939/failed-log.txt)

### Bug prevalence

1-2 times out of every five

### GitHub hash of the SDK that was being used

matter-extension-2.3.0

### Platform

efr32

### Platform Version(s)

1.3

### Type

Platform Issue

**Comment by bzbarsky-apple** [comment]
Sounds like a Google Home issue, not a core Matter one.  Please report the issue to Google...
