### ISSUE TITLE
[Trivial] Review the nomenclature term used in the fabric sync setup process

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#35042]
### Type

Other

### Explanation

 There are a lot of consufion on the various terms used in CCTRL. Especially the term "Reverse" caused confusion because it has different meanings depending on whether it's from the perspective of the sender or the executor of the CommissionNode command. 

We have temperately agreed to use "SendCommissionNode" on the side sending the CommissionNode command and "CommissionNode" on the side executing the command.
 
But we would like to review these nomenclature term used in the fabric sync setup process to make sure there is no further confusion.

### Platform

other

### Testing

Manually tested with SDK

**Comment by tehampson** [comment]
Confirmed with Chris today that he agrees with the nomenclature terms we ended up using
