### ISSUE TITLE
[Feature] which mechanism can auto fetch & connect with the mobile device wifi in CHIPTool app

### ISSUE THREAD

**Issue by Kartikgupta1502** [project-chip/connectedhomeip#35066]
### Feature description

Which mechanism can automatically fetch and connect to the mobile device's Wi-Fi in the CHIPTool app? I tried the Android CHIPTool but didn't find such an option. Currently, I have to manually provide the Wi-Fi credentials, but I'm looking for a one-touch connection that can fetch the credentials from the mobile device and pass them to the chip.

### Platform

android

**Comment by joonhaengHeo** [comment]
I know this is impossible. I understand that Password is not supported by the Android Framework API.

**Comment by yunhanw-google** [comment]
closed as infeasible, thanks
