### ISSUE TITLE
[CERT-TEST-FAILURE] TC-ICDB-2.2 DUT fails to stop check-in message when there is active subscription to client

### ISSUE THREAD

**Issue by fessehaeve** [project-chip/connectedhomeip#35072]
### Feature Area

Area:ICDPhase2

### Test Case

TC-ICDB-2.2

### Reproduction steps

Follow the steps in the TE-2 verification steps unto 3b. When maxInterval reaches, DUT sends both subscription report and check-in message. It should have only sent subscription report. 

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

ddf44dc121b1e3973e4d7f8d53fd78a3680c0022

### Platform

nrf

### Anything else?

Seems similar issue with #34802 and #34803

**Comment by yunhanw-google** [comment]
dup with https://github.com/project-chip/connectedhomeip/issues/34803
