### ISSUE TITLE
[Build] Can you update the Android SDK, or can I only use Ubuntu?

### ISSUE THREAD

**Issue by JasonClark2** [project-chip/connectedhomeip#35119]
### Build issue(s)

1.matter-android-demo-sdk，This SDK is still version 1.0
Can you update the version of matter?
2.Or can you compile 1.3 code for Ubuntu? I need the latest jar package used by Android.
3.
...

### Platform

android

**Comment by joonhaengHeo** [comment]
In my case, I can compile ubuntu environment.

**Comment by yunhanw-google** [comment]
yes, we can compile on ubuntu environment, feel free to file the new issue if the issue is still outstanding.
