### ISSUE TITLE
[Trivial]  emberAfIsTypeSigned doesn't return true for all signed types

### ISSUE THREAD

**Issue by hasty** [project-chip/connectedhomeip#35147]
### Type

Other

### Explanation

Namely, ZCL_POWER_MW_ATTRIBUTE_TYPE, ZCL_AMPERAGE_MA_ATTRIBUTE_TYPE, ZCL_VOLTAGE_MV_ATTRIBUTE_TYPE, ZCL_ENERGY_MWH_ATTRIBUTE_TYPE

### Platform

all

### Testing

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
Note that this will become IsSignedIntegerAttribute in https://github.com/project-chip/connectedhomeip/pull/32632
