### ISSUE TITLE
[BUG] MatterAddDeviceExtensionRequestHandler is never invoked

### ISSUE THREAD

**Issue by JoeyYang2010** [project-chip/connectedhomeip#35145]
### Reproduction steps

Added Matter Extension and add class RequestHandler: MatterAddDeviceExtensionRequestHandler , but commissionDevice is not invoked, so can not get onboarding payload

### Bug prevalence

Each time

### GitHub hash of the SDK that was being used

2024/4/19 master version

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
This sounds like a MatterSupport.framework issue, yes?

If so, please report it to Apple via Feedback Assistant.  If you drop the id of the resulting ticket here, I can try to get it followed up on.  But you'll probably need to provide some more information, logs, etc, for this to be actionable.

**Comment by JoeyYang2010** [comment]
@bzbarsky-apple  There is a same issue here: https://forums.developer.apple.com/forums/thread/726873. 
Add MatterExtension to receive "MatterAddDeviceExtensionRequestHandler" callback, but no response after scanned QR code.It seems many people have such problem but no clear answer about this issue, it make develop on Matter so hard.

**Comment by JoeyYang2010** [comment]
@bzbarsky-apple  I raise another ticket here: https://forums.developer.apple.com/forums/thread/762695

**Comment by bzbarsky-apple** [comment]
Please file a feedback assistant ticket, not a forum post.  See https://github.com/project-chip/connectedhomeip/issues/23566#issuecomment-1312351343 for instructions.
