### ISSUE TITLE
Investigate .bss usage of memp_memory_PBUF_POOL_base

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#3516]
2.8%  15.2Ki    ../../third_party/connectedhomeip/third_party/lwip/repo/lwip/src/core/memp.c
    96.6%  14.7Ki    .bss
 80.7%  11.8Ki    memp_memory_PBUF_POOL_base

**Comment by kpschoedel** [comment]
lwip has wrappers around memory allocation so it should be possible to have it go through CHIPMem rather than allocating from its own pool. This may or may not actually be a good idea.

See third_party/lwip/repo/lwip/src/include/lwip/mem.h and third_party/lwip/repo/lwip/src/core/mem.c
