### ISSUE TITLE
Investigate .bss usage of gTestPairing

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#3518]
1.1%  5.95Ki    ../../third_party/connectedhomeip/examples/common/chip-app-server/Server.cpp
    79.6%  4.73Ki    .bss
      37.1%  1.76Ki    (anonymous namespace)::gRendezvousServer
      34.5%  1.63Ki    (anonymous namespace)::gTestPairing
      28.4%  1.34Ki    (anonymous namespace)::gSessions

**Comment by pan-apple** [comment]
`gTestPairing` is a stop gap solution for apps and devices that do not support secure pairing. This will not be present in the production devices. Also, once all controller apps and devices migrate to secure pairing flow, we can remove `gTestPairing` from the example devices.

**Comment by bzbarsky-apple** [comment]
gTestPairing is gone.
