### ISSUE TITLE
Investigate .bss usage of _acUpBuffer

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#3520]
0.9%  4.60Ki    ../../third_party/connectedhomeip/third_party/jlink/segger_rtt/RTT/SEGGER_RTT.c
    90.4%  4.16Ki    .bss
      96.2%  4.00Ki    _acUpBuffer

**Comment by andy31415** [comment]
Removing from v1: I would expect RTT to require RAM as it uses ram buffers to transfer RTT data between debugger and program.

Inclusion of RTT is likely only useful for debug builds though. At most for V1 we could check inclusion of RTT, however that seems to be a end device/production readyness checkmark of what libraries are enabled or not.

Currently I only see segger_rtt_root used in third_party in efr32_sdk. Tagging @selissia as FIY that efr32 builds may be larger than expected and we may want RTT only in debug builds.
