### ISSUE TITLE
ZCL Implement emberAfReadAttributesResponseCallback

### ISSUE THREAD

**Issue by jepenven-silabs** [project-chip/connectedhomeip#3522]
#### Problem
ZCL `emberAfReadAttributesResponseCallback` is not implemented 

 #### Proposed Solution
Implement this callback if needed inside /src/app/

**Comment by vivien-apple** [comment]
Same answer than https://github.com/project-chip/connectedhomeip/issues/3523#issuecomment-774159313
Closing.
