### ISSUE TITLE
[Build] CI Job 'Build Docker CHIP Build images - base' is failing

### ISSUE THREAD

**Issue by rquidute** [project-chip/connectedhomeip#35269]
### Build issue(s)

The build process started by CI for this PR (https://github.com/project-chip/connectedhomeip/pull/35207) is failing. 
The failing seems not be related with the code changes in the PR.
Build Logs: https://github.com/project-chip/connectedhomeip/actions/runs/10569074862/job/29281187600?pr=35207#step:4:4810

### Platform

other

**Comment by Alami-Amine** [comment]
Issue should be fixed, please remerge master into your PR and check again
