### ISSUE TITLE
[1.2]  The UI update of the onoff command platform ui platform switch is very slow.

### ISSUE THREAD

**Issue by wolen666** [project-chip/connectedhomeip#35276]
### Reproduction steps

1 Premise:
   1.1 esp-idf 5.1 Matter1-2
2 Step:

   2.1 
      I have a functional requirement that when the web page sends an open command, first upload the open command to Matter and wait for 400ms before sending a close command. The switch UI of AppHome is to open first and then close after 400ms. 

  2.2 
    When I send it through the web page, Homekit turns on for 400ms and then turns off. There is no problem with the function.If I turn on the switch on HomeKit, it should wait for 400ms before turning it off. In fact, when I turn it on, it will wait for about 6 to 8 seconds before turning it off. While 400ms after, I read the current switch status and it changed from 1 to 0.I also found that the code I ran before April this year was the same as now, but there was no problem before April. I tried many platforms and they were the same. Did I violate some of the rules of Matter1-2?

  2.3 Below is the code I used to update data to matter

  void C_set_onoff_to_matter(int channel,int state)
  {
    chip::DeviceLayer::StackLock lock;
    if(state==0) OnOffServer::Instance().setOnOffValue(channel,chip::app::Clusters::OnOff::Commands::Off::Id,false);
    else         OnOffServer::Instance().setOnOffValue(channel,chip::app::Clusters::OnOff::Commands::On::Id,false);
    chip::DeviceLayer::StackUnlock unlock;
  }

2.4 
The first picture below is the Log controlled by the web page. The second picture is the Log controlled by the app
![image](https://github.com/user-attachments/ass

https://github.com/user-attachments/assets/6f66a9f5-2e3b-4941-8668-062e82afe6e5

ets/44fc86fa-4386-467f-b748-315f9bab780e)
![image](https://github.com/user-attachments/assets/1995e758-ea20-4e8c-a428-4defaa5e39b3)

2.5 
Below is a specific demonstration video，The first is web control and the second is App control.

https://github.com/user-attachments/assets/6d93a613-8f88-4424-acc3-4ada844d1685

### Bug prevalence

1-2 times week

### GitHub hash of the SDK that was being used

13028cf6bf21f211215ed513e5e03d78b46418eb

### Platform

esp32

### Platform Version(s)

Homekit

### Type

Spec Compliance Issue

**Comment by bzbarsky-apple** [comment]
@wolen666 Please file a feedback assistant ticket following the directions at https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md#providing-feedback-to-apple 

That will include the logs on the Apple Home side that will help figure out what's going on from Home's point of view.  Please also include the logs from your device.

Once you have filed the ticket, please mention the ticket ID here so I can follow up on it.
