### ISSUE TITLE
[CERT-TEST-FAILURE] TC-MCORE.FS-1.2 - Segmentation Fault After Sending pairing Command in fabric-admin

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#35316]
### Feature Area

Other

### Test Case

TC-MCORE.FS-1.2

### Reproduction steps

Command used to build -
Fabric admin app
./scripts/build/build_examples.py --target linux-arm64-fabric-admin-rpc build
Command used to launch : ./fabric-admin

fabric-bridge-app
./scripts/build/build_examples.py --target linux-arm64-fabric-bridge-rpc build
Command used to launch : ./fabric-bridge-app

TH - python controller
commands used to build -
source scripts/activate.sh && scripts/build_python.sh -m platform -d true -i no
source no/bin/activate

Command used to build all-clusters app
scripts/examples/gn_build_example.sh examples/all-clusters-app/linux/ examples/all-clusters-app/linux/out/all-clusters-app chip_inet_config_enable_ipv4=false

Command used to run the python script : rm -r admin_storage.json && python3  TC_MCORE_FS_1_2.py --commissioning-method on-network --discriminator 3840 --passcode 20202021 --paa-trust-store-path ../../credentials/development/paa-root-certs/ --storage-path admin_storage.json --string-arg th_server_app_path:</home/ubuntu/Aug26_cntr/connectedhomeip/examples/all-clusters-app/linux/out/all-clusters-app/chip-all-clusters-app>

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

125b8e7f64db14f650f8fdea9e8d42fbc7a5b951

### Platform

raspi

### Anything else?

Issue Description:
 A segmentation fault occurs in the commissioning process after executing the pairing command with the parameters onnetwork 111 20202021 in fabric-admin. This issue causes the commissioning process to fail during the AttestationRevocationCheck step.

> [1725011537.751] [4945:4947] [CTL] Commissioning stage next step: 'SendAttestationRequest' -> 'AttestationVerification'
> [1725011537.751] [4945:4947] [CTL] Performing next commissioning step 'AttestationVerification'
> [1725011537.751] [4945:4947] [CTL] Verifying attestation
> [1725011537.772] [4945:4947] [CTL] Successfully finished commissioning step 'AttestationVerification'
> [1725011537.772] [4945:4947] [CTL] Commissioning stage next step: 'AttestationVerification' -> 'AttestationRevocationCheck'
> [1725011537.772] [4945:4947] [CTL] Performing next commissioning step 'AttestationRevocationCheck'
> [1725011537.772] [4945:4947] [CTL] Verifying device's DAC chain revocation status
> Segmentation fault (core dumped)
> ubuntu@raspberrypi:~/Aug7/connectedhomeip/out/linux-arm64-fabric-admin-rpc$ 

PFA log below : 
[TC-MCORE.FS-1.2 - Fabric admin log.txt](https://github.com/user-attachments/files/16815286/TC-MCORE.FS-1.2.-.Fabric.admin.log.txt)
[TC-MCORE.FS-1.2 - Fabric bridge app.txt](https://github.com/user-attachments/files/16815287/TC-MCORE.FS-1.2.-.Fabric.bridge.app.txt)
[TC-MCORE.FS-1.2 - python controller log.txt](https://github.com/user-attachments/files/16815288/TC-MCORE.FS-1.2.-.python.controller.log.txt)

**Comment by Ashwinigrl** [comment]
Encountered the same issue while validating the **TC-ECOINFO-2.1** and **TC-ECOINFO-2.2** Python scripts. 

**Reference Log:**
[TC-ECOINFO-2.1(All-cluster-app).txt](https://github.com/user-attachments/files/16815806/TC-ECOINFO-2.1.All-cluster-app.txt)
[TC-ECOINFO-2.1(CNTRL).txt](https://github.com/user-attachments/files/16815807/TC-ECOINFO-2.1.CNTRL.txt)
[TC-ECOINFO-2.1(Fabric-admin).txt](https://github.com/user-attachments/files/16815809/TC-ECOINFO-2.1.Fabric-admin.txt)
[TC-ECOINFO-2.1(Fabric-bridge).txt](https://github.com/user-attachments/files/16815810/TC-ECOINFO-2.1.Fabric-bridge.txt)
