### ISSUE TITLE
[TC-TBRM-3.1] TBRM cluster needs to be implemented in the Simulated sample app (app1)

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#35330]
### Feature Area

Other

### Test Case

TC-TBRM-3.1

### Reproduction steps

Thread Border Router Mangement cluster (TBRM) is not implemented in the Simulated app (app1). Since the TC-TBRM-3.1 is an Simulated test case TBRM cluster needs to be implemented in the Simulated app (app1).

Steps to run this yaml script:

```
1. ./scripts/tests/chipyaml/runner.py Test_TC_TBRM_3_1 app1
2. commission the dut :   ./out/debug/chip-tool pairing code 0x654321 MT:-24J0AFN00KA0648G00
3. Run the SetActiveDatasetRequest command:  ./out/debug/chip-tool threadborderroutermanagement set-active-dataset-request hex:<active-dataset>1 1
```
While running this command in the chip-tool we got the response as `UNSUPPORTED-CLUSTER(0xC3)` , But the Excepted response is `SUCCESS (0x00)` 

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

0e3434a0665ab908e27bef9a84d4429ab8f9d93a

### Platform

raspi

**Comment by ksperling-apple** [comment]
```
    # Step 1
    - label: "DUT send SetActiveDatasetRequest to TH"
      PICS: TBRM.C.C03.Tx
      wait: "SetActiveDatasetRequest"
```

I'm not sure why you're expecting an outcome of success, isn't the test is just meant to verify that the DUT (client) sent the command?
