### ISSUE TITLE
[Fabric Sync] Follow ups on data-model-no-unique-id example application

### ISSUE THREAD

**Issue by tehampson** [project-chip/connectedhomeip#35334]
After https://github.com/project-chip/connectedhomeip/pull/35195 merged we need to address two issues:

1. ~When zap codegen generates `examples/lighting-app-data-mode-no-unique-id/lighting-common/lighting-app.matter` it adds the mandatory UniqueId even though it is removed from .zap file~
2. Need to fix `scripts/tools/zap/update_cluster_revisions.py` to not update the ZAP file for this app, in a separate PR. [from this comment](https://github.com/project-chip/connectedhomeip/pull/35195#pullrequestreview-2270255028)

Edit: for 1 we later determined there was no issue in the .matter file as the UniqueId was for the client side, not the server side on the endpoint cluster was enumerated on

**Comment by tehampson** [comment]
@jlatusek For some reason I cannot assign the issue to you

**Comment by jlatusek** [comment]
@tehampson 
Unfortunately I will not be able to finish this task. I've changed project that I'm working on.
