### ISSUE TITLE
[TC-SWTCH-##] High level PICS has to be added in the Python script.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#35358]
**Description:**

- [ ] - In the following switch test case, high-level PICS need to be added according to the test plan.

1. TC-SWTCH-2.2
2. TC-SWTCH-2.3
3. TC-SWTCH-2.4
4. TC-SWTCH-2.5
5. TC-SWTCH-2.6

- [x] - TC_SWTCH_2_4 - In Test step 5  ` if MSL or AS feature is supported, TH expect receiving LongPress/LongRelease in that order` has to be updated to ` if MSL feature is supported, TH expect receiving LongPress/LongRelease in that order` as per the Test plan.

- [x] - TC_SWTCH_2_6 - Test step 9b  `TH receives MultiPressComplete event with PreviousPosition set to 1 and TotalNumberOfPressesCounted set to 2 from the DUT"` has to be updated to `TH receives MultiPressComplete event with PreviousPosition set to 1 and TotalNumberOfPressesCounted set to 1 from the DUT` as per the Test plan.

**Test plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/switch.adoc

**Python Script References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_SWTCH.py

### GitHub hash of the SDK that was being used

708558881bf6e5b0dac3c09489124907927b6cd2

**Comment by andy31415** [comment]
These tests seem to have been updated to match on endpoint conditions rather than PICS.
