### ISSUE TITLE
[TC-EWATERHTR-2.1] Python Script has to be aligned with Test plan for Test step 5, 6 and 7

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#35356]
### Description:
**TC-EWATERHTR-2.1**

In `TC-EWATERHTR-2.1`, Test Steps 5, 6, and 7 utilize the `PIXIT.EWATERHTR.TP` and `PIXIT.EWATERHTR.EM` values in the Python script. However, the test plan does not reference these PIXIT values. Therefore, the script should be updated to align with the test plan.

**Test step that Require Review:**
- Test Steps 5, 6, and 7

**Python Script References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_EWATERHTR_2_1.py

![image](https://github.com/user-attachments/assets/3f7864e4-89d0-4e24-a1f9-9ce054b1974c)

**Test plan References:**
- https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/WaterHeaterManagement.adoc

### GitHub hash of the SDK that was being used

708558881bf6e5b0dac3c09489124907927b6cd2

**Comment by jamesharrow** [comment]
I think the debug message should be changed to PICS instead of PIXIT and that should resolve this?
