### ISSUE TITLE
[BUG] ZAP tool --> Primary Device is not correctly saved to zap file

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#35437]
### Reproduction steps

I am facing an issue with ZAP tool. Primary Device is not correctly saved to zap file. For example, with PR #35410.

**Reproduce steps**

- `cd ~/connectedhomeip`
- `./scripts/tools/zap/run_zaptool.sh examples/chef/devices/rootnode_waterleakdetector_0b067acfa3.zap`
- Edit EP1 and add `Matter Power Source` in the device list
- Check that Primary Device is still `Matter Water Leak Detector`
- Save save with CTRL+S
- Close the ZCL windows
- `./scripts/tools/zap/run_zaptool.sh examples/chef/devices/rootnode_waterleakdetector_0b067acfa3.zap`
- Edit EP1 and notice that Primary Device is not `Matter Water Leak Detector` but `Matter Power Source`

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

c6f66811c00f6c13e09938147a7c37310ee7bdc9

### Platform

core

### Platform Version(s)

N/A

**Comment by QuentinCaldeira-eaton** [comment]
I don't know if it's linked, but you need to activate Power Source Configuration in the endpoint 0 in order to use PowerSource Cluster in other endpoints. Tell me if it helps !

**Comment by lboue** [comment]
> I don't know if it's linked, but you need to activate Power Source Configuration in the endpoint 0 in order to use PowerSource Cluster in other endpoints. Tell me if it helps !

@QuentinCaldeira-eaton I used the contact sensor as an example and EP 0 does not contain this cluster. 
This is not related to my issue.

![image](https://github.com/user-attachments/assets/6a093410-fde9-4f33-a828-c9bcd32349bb)

**Comment by bzbarsky-apple** [comment]
@lboue ZAP tool issues go in https://github.com/project-chip/zap/issues

**Comment by lboue** [comment]
> @lboue ZAP tool issues go in https://github.com/project-chip/zap/issues

https://github.com/project-chip/zap/issues/1420
