### ISSUE TITLE
[BUG][Android] Resolve fail issue due to abnormal behavior of some Android devices

### ISSUE THREAD

**Issue by joonhaengHeo** [project-chip/connectedhomeip#35550]
### Reproduction steps

1. Try to call "getConnectedDevicePointer" method for CASE session establishment.
2. Fail connection Failed due to the reason in the log below.

CSM     : FindOrEstablishSession: PeerId = [1:534C0B956F2011EF]
CSM     : FindOrEstablishSession: No existing OperationalSessionSetup instance found
DIS     : OperationalSessionSetup[1:534C0B956F2011EF]: State change 1 --> 2
DIS     : Resolving 6E7CB9C39B4A1524:534C0B956F2011EF ...
NsdManagerServiceResolver: resolve: Starting service resolution for '6E7CB9C39B4A1524-534C0B956F2011EF' type '_matter._tcp'
NsdManagerResolverAvailState: Found NsdManager Resolver free, using it and marking it as busy
DIS     : Checking node lookup status after 201 ms
NsdServiceFinderAndResolver: Service discovery started. regType: _matter._tcp
**NsdServiceFinderAndResolver: onServiceFound: found target service name: 6E7CB9C39B4A1524-534C0B956F2011EF, type: _matter._tcp., host: null, port: 0, txtRecord: 
NsdServiceFinderAndResolver: onServiceFound: found target service name: 6E7CB9C39B4A1524-534C0B956F2011EF, type: _matter._tcp., host: null, port: 0, txtRecord:** 
NsdServiceFinderAndResolver: Discovery stopped: _matter._tcp
NsdServiceFinderAndResolver: Failed to resolve service '6E7CB9C39B4A1524-534C0B956F2011EF': 3
NsdManagerResolverAvailState: Signaling NsdManager Resolver as free
**NsdServiceFinderAndResolver: Failed to resolve service '6E7CB9C39B4A1524-534C0B956F2011EF': 3**
DIS     : Checking node lookup status after 45024 ms
E DIS     : OperationalSessionSetup[1:534C0B956F2011EF]: operational discovery failed: src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:119: CHIP Error 0x00000032: Timeout

### Bug prevalence

1-2 times a week

### GitHub hash of the SDK that was being used

ac289edd6050de2f1646d839f07e055eb2848c8e

### Platform

android

**Comment by MrLiuYunPing** [comment]
Sansung Galaxy Flip4 easily to reproduce this issue.
