### ISSUE TITLE
BLE advertisements are inconsistent between spec, commissioner apps, & examples

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#3556]
BLE advertisements are not consistent between iOS, Android, and example apps.

- iOS & ESP32 are serializing discriminator incorrectly
- iOS requires a short length payload (4 bytes for VID/PID omitted)

As of #2954, Android expects the correct format, but that broke discovery of examples still using the wrong format such as ESP32.

https://github.com/project-chip/connectedhomeip/blob/master/src/platform/Darwin/BleConnectionDelegateImpl.mm#L128-L137

https://github.com/project-chip/connectedhomeip/blob/master/src/android/CHIPTool/app/src/main/java/com/google/chip/chiptool/bluetooth/BluetoothManager.kt#L54-L57

**Comment by smides-nest** [comment]
@mspang - in a sidebar you mentioned that the current BLE Advertisement format is too short for iOS discovery but not for Android. Am I understanding that correctly? The above summary makes it sounds as if both iOS and Android both have issues with discovering the BLE Advertisement as currently specified here (https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/326).

**Comment by mspang** [comment]
> @mspang - in a sidebar you mentioned that the current BLE Advertisement format is too short for iOS discovery but not for Android. Am I understanding that correctly? The above summary makes it sounds as if both iOS and Android both have issues with discovering the BLE Advertisement as currently specified here ([CHIP-Specifications/connectedhomeip-spec#326](https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/326)).

Updated the wording.

I was confused about Android, it's actually correct but there are two separate open PRs to change it back to the wrong format because of the inconsistencies.

**Comment by smides-nest** [comment]
@mspang -- Is "iOS requires a short length payload (4 bytes for VID/PID omitted)" fixed in b255818 #3557? So now iOS always expects the fully-specified Service Data and is able to process it?
