### ISSUE TITLE
[Workflow] REPL Tests - Linux / ModuleNotFoundError: No module named 'pyperclip'

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#35581]
### Workflow issues

REPL Tests - Linux / ModuleNotFoundError: No module named 'pyperclip'

I am facing an issue with `REPL Tests - Linux` CI pipeline:

Exemple: [job 30120518953](https://github.com/project-chip/connectedhomeip/actions/runs/10853057290/job/30120518953?pr=35410#logs)

### Platform

other

**Comment by andy31415** [comment]
Closing as not reproducible: PR got merged and I have not seen this error since then. Should re-open if this happens frequently.
