### ISSUE TITLE
Profile at https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig has been updated.

### ISSUE THREAD

**Issue by mokap13** [project-chip/connectedhomeip#35626]
Profile at https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig has been updated.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/issues/29178#issuecomment-1718389067_
  
I think it happened again, can check it?

<img width="709" alt="Screenshot 2024-09-17 at 18 37 58" src="https://github.com/user-attachments/assets/3bd7a0d2-7e4a-4fdb-a5cb-ba65e7e07b13">

**Comment by ReneJosefsen** [comment]
From what I understand the profile linked in the docs has been updated? I did also get this error yesterday, but I have been able to install it today.

**Comment by ReneJosefsen** [comment]
@bzbarsky-apple I assume this is fixed, so I guess we can close it?

**Comment by mokap13** [comment]
Thanks! Yes, you can close.

**Comment by mantosh83** [comment]
Hi Team,

The profile that was recently updated seems to have expired. Could you please help by updating it with the latest version, or kindly let me know where I can download the most recent one?

Expired:  Profile at https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig

**Comment by bzbarsky-apple** [comment]
@mantosh83 The profile has been updated.  See https://github.com/project-chip/connectedhomeip/issues/40972
