### ISSUE TITLE
[Tooling] Apple Matter Developer Profile is no longer valid

### ISSUE THREAD

**Issue by andrew-elsayeh** [project-chip/connectedhomeip#35620]
### Reproduction steps / Feature

The Matter Developer Profile which is required for developing matter devices using a Mac/iOS/iPadOS device is no longer valid. 

Link to guide for matter development on Apple devices: https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md#profile-installation

 Link to profile: https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig
 
 

### Platform

other

### Type

Manually tested with SDK

**Comment by bzbarsky-apple** [comment]
@andrew-elsayeh Thank you for the report.  This is being worked on.

**Comment by bzbarsky-apple** [comment]
This should be fixed now.

**Comment by selissia** [comment]
As expected, this profile has expired one year later. Please re-enable it.

**Comment by selissia** [comment]
Created a new issue https://github.com/project-chip/connectedhomeip/issues/40972, closing this one.
