### ISSUE TITLE
Examples for nRF52833

### ISSUE THREAD

**Issue by MacWyznawca** [project-chip/connectedhomeip#3568]
#### Functionality request.
Can you expect support and examples on nRF52833?

**Comment by LuDuda** [comment]
Hello @MacWyznawca,

Right now we focus on nRF52840 only. Fitting Thread, BLE and CHIP stacks together with Secure Bootloader and other application components might be challenging on nRF52833, though we haven't done major optimization work yet. The reason behind it is that CHIP SDK is still incomplete and changes very often, but we will look at it soon.

**Comment by MacWyznawca** [comment]
Dziękuję! @LuDuda Thanks 😉
