### ISSUE TITLE
[TC-TBRM-2.4]: YAML script requires configuration update and endpoint flexibility

### ISSUE THREAD

**Issue by ZainZhongUL** [project-chip/connectedhomeip#35726]
Please follow the below template to file issues/concerns/feature enhancement against Test Scripts:

## Summary Title: 
TC-TBRM-2.4: After side-loading the new [YAML script,](https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_TBRM_2_4.yaml) the parameter "payload: "MT:8IZJ1RXS02TATG30000" must be added to the TH project configuration. Additionally, the YAML script currently hardcodes GetActiveDatasetRequest and GetPendingDatasetRequest to endpoint 1. This can cause test failures for DUT that TBRM clusters do not implement on endpoint 1.

**Comment by ksperling-apple** [comment]
#35784 fixes the hard-coding of the endpoint number.

> the parameter "payload: "MT:8IZJ1RXS02TATG30000" must be added to the TH project configuration.

I don't understand why this would be necessary? The script assumes the DUT is already paired, and uses this existing pairing to open a commissioning window to be able to test the PASE handling.
