### ISSUE TITLE
[SVE] TC-MCORE-FS-1.3: Timeout too low for device discovery & commissioning from DUT

### ISSUE THREAD

**Issue by samadDotDev** [project-chip/connectedhomeip#35739]
### Reproduction steps

In `TC-MCORE-FS-1.3`, a `TH_SERVER_NO_UID` (an example app with no unique ID) is [commissioned onto TH's fabric](https://github.com/project-chip/connectedhomeip/blob/6b99a99a762e58f0b07b6b3e4d0d4f1fbad39c22/src/python_testing/TC_MCORE_FS_1_3.py#L163), and `DUT_FSA`'s aggregator parts list is checked before the [commissioning window on TH_SERVER_NO_UID is opened using TH's fabric](https://github.com/project-chip/connectedhomeip/blob/6b99a99a762e58f0b07b6b3e4d0d4f1fbad39c22/src/python_testing/TC_MCORE_FS_1_3.py#L143) (this is in response to `CommissionerControlCluster::CommissionNode` command as part of reverse commissioning between TH and DUT). Right after that, the DUT is expected to discover and commission `TH_SERVER_NO_UID` and [just 2s after that](https://github.com/project-chip/connectedhomeip/blob/6b99a99a762e58f0b07b6b3e4d0d4f1fbad39c22/src/python_testing/TC_MCORE_FS_1_3.py#L192), the DUT's parts list is reread to determine whether the new device has been made available as a bridged node.

This timeout is pretty short because right after issuing the `CommissionerControlCluster::ReverseOpenCommissioningWindow` command, the DUT is expected to discover the newly advertised `_matterc._udp` service, resolve its address, establish PASE, install the `DUT_FSA`'s fabric, subscribe (& perform other necessary interactions during onboarding) before making it available as a newly accessible bridged node on the `DUT_FSA`'s aggregator parts list, and some of these operations can take a bit of time.

### Bug prevalence

Almost always on our DUT

### GitHub hash of the SDK that was being used

56c0bd8

### Platform

other

### Type

Test Improvement

### Testing

Hardware validated, Platform validated

**Comment by cjandhyala** [comment]
@samadDotDev can you update the PR with the comments ?
