### ISSUE TITLE
[Workflow] `Run framework tests (leaks, ENABLE_LEAK_DETECTION=1)` failure

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#35766]
### Workflow issues

Hello,

Job [30627148241](https://github.com/project-chip/connectedhomeip/actions/runs/11027733002/job/30627148241?pr=35392) for my PR [[Linux] Matter Linux Water Leak Detector Example #35392](https://github.com/project-chip/connectedhomeip/pull/35392) is failing after 24m.

Could you fix this CI pipeline?

Regards

### Platform

all

### Anything else?

[log file](https://productionresultssa8.blob.core.windows.net/actions-results/2d951f82-04ef-4583-94fd-c308cb71d9a5/workflow-job-run-a884aa2a-d904-5976-613a-23bfd1baa804/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-09-25T09%3A43%3A04Z&sig=Hv%2BRLLvjehDkfm%2BmX1OLeXKZE%2FGnv%2Fz3OJsgixDbkmQ%3D&ske=2024-09-25T18%3A48%3A37Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-09-25T06%3A48%3A37Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-09-25T09%3A32%3A59Z&sv=2024-05-04)

**Comment by bzbarsky-apple** [comment]
@lboue I'm looking into that, but the job there is picking up a real (albeit intermittent?) leak....

**Comment by lboue** [comment]
> @lboue I'm looking into that, but the job there is picking up a real (albeit intermittent?) leak....

Why does it work for all the other pipelines and not this one?

**Comment by bzbarsky-apple** [comment]
This is the one pipeline that does a leak check.

**Comment by bzbarsky-apple** [comment]
For now, fixed by https://github.com/project-chip/connectedhomeip/pull/35782
