### ISSUE TITLE
emberAfDoorLockClusterSetHolidayScheduleCallback needs to validate operatingModeDuringHoliday value

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3578]
#### Problem
Right now an invalid value of `operatingModeDuringHoliday` (out of range) will just get stored in the schedule table.  I would have expected a check here and an error return if it's out of range....

 #### Proposed Solution
Add a check.  I'm not sure how best to do that, given the enum is generated.  Maybe we could 
add something in the generated code that lets us check whether the value is valid for a given enum?

@vivien-apple

**Comment by mrjerryjohns** [comment]
`emberAfDoorLockClusterSetHolidayScheduleCallback` is not implemented (still) in the SDK. Closing this as a stale issue for now since there isn't actually an illegal implementation yet.

**Comment by bzbarsky-apple** [comment]
> emberAfDoorLockClusterSetHolidayScheduleCallback is not implemented (still)

More precisely, the implementation that was there (and buggy as described above) was removed, and a new one was not added.
