### ISSUE TITLE
`MeasurementUnitEnum` issue for `NitrogenDioxideConcentrationMeasurement`

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#35794]
Hello,

I notice that there are 2 different units of measurement in 2 different classes for `NitrogenDioxideConcentrationMeasurement`.

https://github.com/project-chip/connectedhomeip/blob/c0500f7360765b5d1c2f7c979ce6daac488e16e5/examples/all-clusters-app/all-clusters-common/src/concentration-measurement-instances.cpp#L36-L38

`MeasurementUnitEnum::kPpb
`
https://github.com/project-chip/connectedhomeip/blob/c0500f7360765b5d1c2f7c979ce6daac488e16e5/examples/chef/common/chef-concentration-measurement.cpp#L227-L228

Which one is correct?

**Comment by bzbarsky-apple** [comment]
Both are correct.  The concentration measurement cluster provides a measurement (via MeasuredValue and the like) and a MeasurementUnit attribute that says what units that measurement is in.

So an application that provides measurements in ppm should use kPpm, while one that provides measurements in pbb (so 1000 times larger numbers than the ppm case) should use  kPpb.
