### ISSUE TITLE
setUser or its callers needs to validate userStatus

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3579]
#### Problem
In the door lock cluster server's setUser function, nothing ensures that `userStatus` is a valid value.

 #### Proposed Solution
Add a check. I'm not sure how best to do that, given the enum is generated. Maybe we could
add something in the generated code that lets us check whether the value is valid for a given enum?

@vivien-apple

**Comment by turon** [comment]
Validation of cluster field ranges is required for v1.
Removing `v1_triage_split_4`.

**Comment by bzbarsky-apple** [comment]
This might not be relevant anymore, because the old door lock implementation was removed wholesale and a new one written.
