### ISSUE TITLE
[Build] [ICD] `ICDServerBuildConfig.h` missing in `app/icd/server/` directory

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#35803]
### Build issue(s)

Hi,

Were can we found this ICDServerBuildConfig.h file referenced here?

https://github.com/project-chip/connectedhomeip/blob/9a96e6d5eed481eee13e489759c0f141b0ed7b01/src/app/icd/server/ICDServerConfig.h#L21

It should be here:
https://github.com/project-chip/connectedhomeip/tree/master/src/app/icd/server

Regards

### Platform

all

**Comment by bzbarsky-apple** [comment]
ICDServerBuildConfig is generated at build-time, no?  

```
src/app/icd/server/BUILD.gn:  header = "ICDServerBuildConfig.h"
```

If you're not building this via gn, you will need to figure out some other mechanism of providing it.
