### ISSUE TITLE
Need to validate userType values in door lock server

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3580]
#### Problem
In `emberAfDoorLockClusterSetUserTypeCallback` and in `setUser` we have a `uint8_t userType` that we are casting to `EmberAfDoorLockUserType`, but nothing makes sure that it's a valid value.

 #### Proposed Solution
Add a check. I'm not sure how best to do that, given the enum is generated. Maybe we could
add something in the generated code that lets us check whether the value is valid for a given enum?

@vivien-apple

**Comment by bzbarsky-apple** [comment]
This might not be relevant with the door lock cluster rewrites (and the fact that the "Set User Type" command is gone to start with in Matter)....

@mykrupp can you confirm that this is not an issue anymore, please?

**Comment by mykrupp** [comment]
I don't see emberAfDoorLockClusterSetUserTypeCallback in the connectedhomeip repo anywhere. 

Although 4.26 in the doorlock spec indicates that Set User Type should be there. Was it decided at some point to remove the Set User Type command from matter?
<img width="658" alt="Screen Shot 2022-08-26 at 7 58 29 AM" src="https://user-images.githubusercontent.com/95718139/186898604-f5761643-0eff-4015-b5b0-5c0d25e97f8a.png">

**Comment by bzbarsky-apple** [comment]
Set User Type is Zigbe-only.  The Matter equivalent is SetUser.  The question is whether SetUser validates the user type it's passed @mykrupp

**Comment by mykrupp** [comment]
https://github.com/project-chip/connectedhomeip/pull/19813 This PR took care of it for SetUser

**Comment by bzbarsky-apple** [comment]
Perfect!
