### ISSUE TITLE
Consider switching various indexOrDestination bits to some sort of struct/union type

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3584]
#### Problem
There are a bunch of functions that take an `EmberOutgoingMessageType` and a numeric `indexOrDestination`.  The meaning of the indexOrDestination is then determined by the value of the `EmberOutgoingMessageType`.

 #### Proposed Solution
It might be better to have a struct that has an EmberOutgoingMessageType member and then a union of whatever things `indexOrDestination` is supposed to be able to represent, with accessors to get at various information.

I _think_ `indexOrDestination` can be a `NodeId` or a `GroupId` or an index into the binding table.  @selissia does that sound about right?

**Comment by selissia** [comment]
> I _think_ `indexOrDestination` can be a `NodeId` or a `GroupId` or an index into the binding table. @selissia does that sound about right?

Yes, that's right. We discussed this on the #chipsilabsintegration a while ago (for some reason I can no longer see the old messages). 

￼

**Comment by bzbarsky-apple** [comment]
> for some reason I can no longer see the old messages

Because we're not paying Slack (enough?) so they only keep a certain number of messages.

**Comment by kghost** [comment]
I'm working on this, this will be a subtask of integrate ember with exchange layer.

I'll add a `EmberContext` to capture all short live variables, and it will replace `indexOrDestination`. The binding and the destination node id will be the member of `EmberContext`

**Comment by bzbarsky-apple** [comment]
Please don't use "Ember" in new names; we are generally aiming to eliminate that naming convention from the code, but it's waiting on us having control of the generator for the generated files so we can change those in sync with the non-generated ones.

Also, "Context" is kind of generic.... the right thing here is "MessageDestination" or the like, right?

**Comment by kghost** [comment]
Let's continue the discussion in the linked PR.

**Comment by woody-apple** [comment]
@kghost is this still required? Please re-open if needed! (Linked PR is closed)

**Comment by bzbarsky-apple** [comment]
Yes, this is still needed.

**Comment by kghost** [comment]
This is block by #4019, see https://github.com/project-chip/connectedhomeip/issues/4170#issuecomment-771352570
