### ISSUE TITLE
BLE auth fails when connecting through python chip-device-ctrl 

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#3585]
Expecting  "Remote device completed SPAKE2+ handshake"

chip-device-ctrl > set-pairing-wifi-credential testap testtest
WiFi credential set
chip-device-ctrl > connect 12345678
CHIP: [BLE] subscribe complete, ep = 0x10f570c88
CHIP: [BLE] peripheral chose BTP version 3; central expected between 2 and 3
CHIP: [BLE] using BTP fragment sizes rx 20 / tx 128.
CHIP: [BLE] local and remote recv window size = 3

**Comment by erjiaqing** [comment]
#3541 have updated the ptotocol ID, please rebuild chip-device-ctrl with latest code.
