### ISSUE TITLE
CHIP ignore esp-idf log level and print "empty" messages

### ISSUE THREAD

**Issue by mokap13** [project-chip/connectedhomeip#35939]
https://github.com/project-chip/connectedhomeip/blob/bcc1f1b3b8243326ec1818b0d1b84c37464bd0f6/src/platform/ESP32/Logging.cpp#L51

When the chip calls the esp logs, the lines with "printf" ignores the log level, I think this can be fixed as follows:
`esp_log_write(ESP_LOG_DEBUG, tag, LOG_COLOR_D "D (%" PRIu32 ") %s: ", esp_log_timestamp(), tag);`
`esp_log_writev(ESP_LOG_DEBUG, tag, msg, v);`
`esp_log_write(ESP_LOG_DEBUG, tag, LOG_RESET_COLOR "\n");`

**Comment by bzbarsky-apple** [comment]
@shubhamdp @dhrishi
