### ISSUE TITLE
[BUG] Unable to get correct MaxIntervalCeiling in OnSubscriptionRequested for ICD

### ISSUE THREAD

**Issue by fuxiaoming-lumi** [project-chip/connectedhomeip#35991]
### Reproduction steps

When using ReadHandler::ApplicationCallback to implement a custom strategy, you will not be able to get the MaxIntervalCeiling in OnSubscriptionRequested for ICD devices. 

We only have GetReportingIntervals API and it get mMaxInterval but is overridden.

https://github.com/project-chip/connectedhomeip/blob/5224cec13d97a8746a8d1a9da70bc16a859d8ee7/src/app/ReadHandler.cpp#L744 https://github.com/project-chip/connectedhomeip/blob/5224cec13d97a8746a8d1a9da70bc16a859d8ee7/src/app/ReadHandler.cpp#L794

### Bug prevalence

100%

### GitHub hash of the SDK that was being used

5224cec13d97a8746a8d1a9da70bc16a859d8ee7

### Platform

core

**Comment by bzbarsky-apple** [comment]
@lpbeliveau-silabs

**Comment by fuxiaoming-lumi** [comment]
More details https://csamembers.slack.com/archives/C036A932BQ8/p1728399013259439

**Comment by fuxiaoming-lumi** [comment]
@yunhanw-google @mkardous-silabs @andy31415 I think we also need cherry-pick this commit to v1.4-branch.
