### ISSUE TITLE
[BUG] emberAfClearDynamicEndpoint() invalid real index cast (uint8_t instead of uint16_t)

### ISSUE THREAD

**Issue by hacker-cb** [project-chip/connectedhomeip#36007]
### Reproduction steps

Current `emberAfClearDynamicEndpoint()` has error during calculation real index of dynamic endpoint. As a result, total endpoints index is limited to 255.

`emberAfSetDynamicEndpoint()` - ok, `uint16_t`.

https://github.com/project-chip/connectedhomeip/blob/8a01f93835700bf96acd47d246024bbfd4370602/src/app/util/attribute-storage.cpp#L285

`emberAfClearDynamicEndpoint()` - wrong, `uint8_t`.

https://github.com/project-chip/connectedhomeip/blob/8a01f93835700bf96acd47d246024bbfd4370602/src/app/util/attribute-storage.cpp#L325

So, in  `emberAfClearDynamicEndpoint()` should be cast to `uint16_t`

Updates:

`emberAfGetDynamicIndexFromEndpoint` - wrong, `uint8_t`.
https://github.com/project-chip/connectedhomeip/blob/8a01f93835700bf96acd47d246024bbfd4370602/src/app/util/attribute-storage.cpp#L258

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

8a01f93835700bf96acd47d246024bbfd4370602

### Platform

core

**Comment by bzbarsky-apple** [comment]
`emberAfGetDynamicIndexFromEndpoint` has a similar problem.

**Comment by hacker-cb** [comment]
Also emberAfClearDynamicEndpoint.

I updated issue first message.
