### ISSUE TITLE
[Device Energy Management Mode Cluster] Device Energy Management Mode Cluster XML has to be updated as per Spec

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#36059]
### Description:

- [ ] 1. Below following `Feature` and `Attributes` are Disallowed for the Device Energy Management Mode Cluster. So these should be removed from the Device Energy Management Mode Cluster device XML.

**Feature:**

1. OnOff  

**Attributes:**

1. StartUpMode
2. OnMode 

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Mode_DeviceEnergyManagement.adoc#4-features

![image](https://github.com/user-attachments/assets/40d81580-9797-4593-a113-5bc5fb0b55bf)

![image](https://github.com/user-attachments/assets/482d8ebe-928c-45af-bc81-bbbe2260ca52)

**XML References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/device-energy-management-mode-cluster.xml

![image](https://github.com/user-attachments/assets/9d67cb77-4724-4114-b96a-f86d5be6ece2)

![image](https://github.com/user-attachments/assets/ad7e1b3d-3a28-4d91-bff8-1239ec865b51)

- [ ] 2. In Spec,  Device Energy Management Mode Cluster Revision value has been updated from 1 to 2. So XML has to be updated as per the spec.

**Spec Reference:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Mode_DeviceEnergyManagement.adoc#1-revision-history

![image](https://github.com/user-attachments/assets/521d438f-f1f1-4c6a-b965-9f9e0bd899a7)

**XML References:**
- https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/zcl/data-model/chip/device-energy-management-mode-cluster.xml#L51

![image](https://github.com/user-attachments/assets/f1a1d561-2775-4eaf-a9b5-f31388ac76fb)

**Comment by cecille** [comment]
Data model XMLs are updated automatically and aligned to spec tags. These data model XMLs will be updated when the spec tag for the board release is tagged.
These data model files are automatically generated and should not be updated by hand. 

They don't need individual issues opened.

Closing this as it will be fixed once the spec is properly tagged and I don't want anyone thinking they need to make hand edits.

**Comment by bzbarsky-apple** [comment]
> Data model XMLs are updated automatically and aligned to spec tags

This is not about data model XMLs, which are under `/data_model`.  This is about a file under `/src/app/zap-templates/zcl/data-model/chip`.

**Comment by jamesharrow** [comment]
PR here to fix: #36155
