### ISSUE TITLE
[Device Energy Management Mode Cluster] Sample app(All-cluster-app) has to be updated by removing the disallowed Attributes.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#36072]
### Description:

 **StartUpMode** and **OnMode** attributes are disallowed for **`Device Energy Management Mode Cluster`**. So these should be removed from the Sample app(All-cluster-app).

**Specification References:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Mode_DeviceEnergyManagement.adoc#6-attributes

![image](https://github.com/user-attachments/assets/d6a355f6-97be-4e1c-8e7a-87a21b0f6b93)

**Sample app used to run this cluster:**
All-cluster-app

**Log References:**
[DEMM.txt](https://github.com/user-attachments/files/17373368/DEMM.txt)
![image](https://github.com/user-attachments/assets/2714d101-8cc8-4aef-93e6-774a2dc70d9e)

### Bug prevalence

Whenever we do

### GitHub hash of the SDK that was being used

78f489d7d5cb5f8c48120d8a18e14efb8fe01d11

### Platform

raspi

**Comment by jamesharrow** [comment]
This was corrected in Energy management app (which was typically used for SVE). Will also fix in all-clusters-app
