### ISSUE TITLE
[Water Heater Mode Cluster] Sample app(All-cluster-app) has to be updated by removing the disallowed Attributes.

### ISSUE THREAD

**Issue by Ashwinigrl** [project-chip/connectedhomeip#36074]
### Description:

 **StartUpMode** and **OnMode** attributes are disallowed for **`Water Heater Mode Cluster`**. So these should be removed from the Sample app(All-cluster-app).

**Specification References:**
- https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Mode_WaterHeater.adoc#6-attributes

![image](https://github.com/user-attachments/assets/654614d5-c964-45b7-a3dc-d65eaca2570c)

**Sample app used to run this cluster:**
All-cluster-app

**Log References:**
[WHM.txt](https://github.com/user-attachments/files/17373682/WHM.txt)

![image](https://github.com/user-attachments/assets/a44ea64a-4b2f-4d50-8bbc-687d5f3db95e)

### Bug prevalence

Whenever we do

### GitHub hash of the SDK that was being used

78f489d7d5cb5f8c48120d8a18e14efb8fe01d11

### Platform

raspi

**Comment by jamesharrow** [comment]
This was corrected in Energy management app (which was typically used for SVE) - will also fix in all-clusters-app.
