### ISSUE TITLE
[Feature] When the thermostat supports automatic mode and is in heating or cooling mode, why does it need to meet the requirement that the heating temperature is less than the cooling temperature minus the dead zone?

### ISSUE THREAD

**Issue by RtuQ** [project-chip/connectedhomeip#36191]
### Feature description

in thermostat-server.cpp
MatterThermostatClusterServerPreAttributeChangedCallback
`
if (AutoSupported)
{
  if (requested > OccupiedCoolingSetpoint - DeadBandTemp)
      return imcode::InvalidValue;
}
`
The current mode should be determined here, otherwise when the user is in heating or cooling mode, the temperature cannot be adjusted at one time; for example, the heating temperature is set to 26 degrees, and if you want to set the cooling mode, and the temperature is 22 degrees, the user must switch to heating mode, and Lower the temperature, otherwise the cooling temperature will be judged as illegal。
I want to know why Matter designed like this?

Thanks.

### Platform

all

**Comment by hasty** [comment]
1. You do not need to switch to heating or cooling mode to change the associated setpoint via writing directly to the attributes.
2. You _do_ need to have the mode set when using SetpointRaiseLower, but that path will auto-adjust the other setpoint (unless doing so would violate the setpoint limits)
3. There's a PR in progress that brings that auto-adjust logic to the setpoint attributes here: #35673

**Comment by hasty** [comment]
To answer the broader question: if a thermostat in auto mode did not have a deadband, then it would be valid to set the heating and cooling setpoints to the same value.

For example, if both were set to 22°, and the indoor temperature were 19°, then the thermostat would heat until the indoor temperature went above 22°. Of course, it would now be over the cooling setpoint, so the thermostat would immediately begin cooling to bring it below 22°, which would put it below the heating setpoint, so it would begin heating, etc. The thermostat would be fighting with itself.

**Comment by bzbarsky-apple** [comment]
>  if a thermostat in auto mode did not have a deadband,

But the check is not "are we in auto mode?"  It's "Is auto mode supported at all?"

That said, switching between auto and non-auto mode should perhaps not affect setpoints...

**Comment by RtuQ** [comment]
@hasty Thank you for your response to my question; it was very helpful to me.

I tested https://github.com/project-chip/connectedhomeip/pull/35673,and this feature is exactly what I need.
