### ISSUE TITLE
chip-tool write-by-id returns constraint-error while write works

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/connectedhomeip#36218]
### Reproduction steps

./chip-tool thermostat write-by-id 25 10 1 1 -> CONSTRAINT_ERROR, 
./chip-tool thermostat write min-setpoint-dead-band 10 1 1 -> success.

log from thermostat linux app:
[thermostat-write-by-id.log](https://github.com/user-attachments/files/17495881/thermostat-write-by-id.log)

### Bug prevalence

always

### GitHub hash of the SDK that was being used

7026061c16

### Platform

other

**Comment by bzbarsky-apple** [comment]
write-by-id clearly documents how its arguments work:
```
attribute-values:
...
  * unsigned integer: One of:
      a) The number directly, as decimal.
      b) The number directly, as 0x followed by hex digits. (Only for the toplevel value, not inside structs or lists.)
      c) A string starting with "u:" followed by decimal digits
  * signed integer: One of:
      a) The number directly, if it's negative.
      c) A string starting with "s:" followed by decimal digits
```

`10` is not negative, so it gets treated as "unsigned integer".  But you're trying to write a signed value, so that fails.

You want `"s:10"` for the value.
