### ISSUE TITLE
Issue with certified shipping product: Zemismart Wifi Light Switch

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#36301]
### Reproduction steps

I just bought one of these: Zemismart Wifi Light Switches.
This is a certified, shipping Matter product.
https://csa-iot.org/csa_product/zemismart-wifi-smart-switch-31/

It didn't work in my app when I commissioned it. So I looked at the descriptors. This device has a device type 0x103 light switch. So of course it didn't appear in my app UI since it is a transmit only switch. ​Note that there is no mention of server clusters in device type Light Switch for anything other than identify.​The problem here is that this device should be listing both device type 0x100 (onOff light) and 0x103 (onOff switch) on that endpoint.

So how is my app supposed to deal with this? 
And how did it get certified like this?

I really, really don't want to add code to my app which attempts to guess the correct device type. That is a slippery slope which ends in disaster. For a workaround I can add the vendor/product ID for Zemismart to my app and fix the device type.

![image](https://github.com/user-attachments/assets/085f7800-55a3-40b7-9bd2-a92df7b54992)

### Bug prevalence

always

### GitHub hash of the SDK that was being used

17b1a38e909e7874593bcb87c31be03a5866f1d4

### Platform

other

**Comment by bzbarsky-apple** [comment]
> The problem here is that this device should be listing both device type 0x100 (onOff light) and 0x103 (onOff switch) on that endpoint.

Why do you think it should be doing that?

> So how is my app supposed to deal with this?

What is your app trying to do with this switch?  This sounds like a product that does not allow its state to be remotely controlled, but lets physical interaction with it control an On/Off server.  If your app is trying to remotely control a product that doesn't allow remote control, then obviously it will not work.

>  And how did it get certified like this?
