### ISSUE TITLE
Rendezvous Parameters should not know about Setup Payload requirements

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#3631]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/3550 introduces a constant in the Rendezvous Parameters that limtis the maximum value of the discriminator. This class shouldn't know about this spec implementation detail. 

 #### Proposed Solution
Consider refactoring such that the owner of a Rendezvous Parameter object can define it's "limits".

**Comment by andy31415** [comment]
As this is a refactor, removing this from 'blocking v1'. Helps maintainability of code, can be done later.
