### ISSUE TITLE
segmentation fault  when chip-tool (Mac) connects to BT advertisements on raspi running on ubuntu desktop

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#3635]
segmentation fault  when chip-tool (Mac) connects to BT advertisements on raspi running on ubuntu desktop

 ./out/host/chip-tool echo ble 12345678 1383
CHIP: [DL] _Init
CHIP: [DL] CHIP task running
CHIP: [BLE] NewConnection
CHIP: [BLE] CBManagerState: ON
CHIP: [BLE] Connecting to device: @
zsh: segmentation fault  ./out/host/chip-tool echo ble 12345678 1383

**Comment by woody-apple** [comment]
Can this be retested post this? https://github.com/project-chip/connectedhomeip/pull/4542
