### ISSUE TITLE
Where to find stable SDK for Matter 1.3.0?

### ISSUE THREAD

**Issue by lpetrov** [project-chip/connectedhomeip#36385]
There is no such official/stable release in the releases tab.

However, there is a 1.3.0 tag, but I'm not sure if thats stable/to be used by developers.

**Comment by andy31415** [comment]
https://github.com/project-chip/connectedhomeip/tree/v1.3-branch was created for the 1.3 branch that is reasonably stable (only bugfixes and compile fixes are generally back ported, usually by platform maintainers). We opted to not create "releases" at this time as we had no direct trigger point as to why a specific SHA would be more stable than another (we do not run additional validation/conformance tests)
