### ISSUE TITLE
Refactor Chip Message Def in message def folder for interaction model to different files with each class

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#3644]
In this https://github.com/project-chip/connectedhomeip/pull/3491, we need to follow-up PR to refactor Chip Message Def for interaction model to different files with each class

**Comment by woody-apple** [comment]
@yunhanw-google Can you please elaborate what this is? "Refactor" isn't super clear what this is tracking

**Comment by yunhanw-google** [comment]
This has been done, close it.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/4431/commits/17e0b8f8bbdb58eb0dd1328eca7ea200c3964118
