### ISSUE TITLE
[Workflow] Release a new version for chip-build container

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#36468]
### Workflow issues

Hello,

Could you release a new version for [chip-build](https://github.com/project-chip/connectedhomeip/pkgs/container/chip-build) `container` ? The last one was published 5 months ago 
https://github.com/project-chip/connectedhomeip/pkgs/container/chip-build/232396506?tag=91

### Platform

core (please add to version below)

**Comment by bzbarsky-apple** [comment]
@andy31415

**Comment by andy31415** [comment]
https://github.com/project-chip/connectedhomeip/pkgs/container/chip-build contains 92 and 93
