### ISSUE TITLE
Rename kTLVType_Path to kTLVType_List

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#3648]
#### Problem
In latest chip tlv spec, tlv path has beeen renamed to list
https://github.com/project-chip/connectedhomeip/blob/master/docs/specs/chip-tlv-format.adoc#lists

 #### Proposed Solution
Update code from kTLVType_Path to  kTLVType_List

**Comment by woody-apple** [comment]
Done
