### ISSUE TITLE
[BUG] chip-tool subscriptions break when more than one is created, but read clients stay active

### ISSUE THREAD

**Issue by w8floosh** [project-chip/connectedhomeip#36524]
### Reproduction steps

1. Start chip-tool in interactive mode and pair it with the all-clusters-app.
2. Subscribe to all attributes of cluster OnOff with ```any subscribe-by-id 6 0xFFFFFFFF 0 65535 <node> 1```
3. Subscribe to all attributes of cluster Identify with ```any subscribe-by-id 3 0xFFFFFFFF 0 65535 <node> 1```
4. In ```InteractiveStartCommand::RunCommand()```, write some code in the ```while(true)``` loop to alternate the execution of the following commands repeatedly:
- ```any command-by-id 6 0 {} <node> 1```
- ```any command-by-id 6 1 {} <node> 1```
- ```any command-by-id 3 0 {"0":"1"} <node> 1```
- ```any command-by-id 3 0 {"0":"0"} <node> 1```

The **OnOff** and **IdentifyTime** attributes should change their value and the all-clusters-app return a subscription report, but no report is being received. I also tried avoiding the wildcard by manually typing all the attributes ID but didn't work either. The problem was detected also when testing actual Matter devices.
If I subscribe only to the OnOff cluster attributes, the OnOff attribute is correctly reported, while if I create two or more subscriptions none of them work as intended

While debugging, I noticed two things: 
1. the ```ReadClient``` of each subscription still stays active, but they do not call any report processing callback, like they didn't receive anything at all;
2. During the period the subscription report should be received within, the event receiver loop blocks at the ```select()``` call in ```LayerImplSelect::WaitForEvents()```. This call should be successful when some data is available to read from the read file descriptor set (e.g. report data), but it keeps blocking the thread for some reason.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

73ff58ff

### Platform

core

**Comment by bzbarsky-apple** [comment]
The second subscription cancels the first one on the server, since it's not using `--keepSubscriptions true`.
