### ISSUE TITLE
[1.3] IIC protocol communication

### ISSUE THREAD

**Issue by swang4415** [project-chip/connectedhomeip#36605]
### Reproduction steps

When I use the iic protocol to communicate, I want to display different contents by rotating the encoder, but the contents of the screen do not change when I rotate the encoder, and it remains as initialized. However, the log shows that the screen has been cleared and displayed, and I don't know why. Here is my code:
static void ENCA_timer_callback(void *arg)
{
    uint8_t ENC_A = gpio_get_level(GPIO_A);
    uint8_t ENC_B = gpio_get_level(GPIO_B);

    if (ENC_A == 0)
    {
        if (ENC_A != ENC_B)  // 顺时针旋转
        {
            current_node_index++;
            if (current_node_index > max_node_index)
            {
                current_node_index = 0;  // 回到第一个灯具
            }
            ESP_LOGI(TAG, "旋钮 A 顺时针旋转，选择的灯具 NodeID: 0x%llX", node_ids[current_node_index]); 
            ESP_LOGI(TAG, "current_node_index: %d", current_node_index);
            OLED_CMD_PRINT();
        }
        else
        {
             ESP_LOGI(TAG, "旋钮 A 未检测到旋转!!");
        }
    }   
        
}
void OLED_CMD_PRINT(void) {
    // 获取当前节点 ID
    chip::NodeId currentNodeId = node_ids[current_node_index];

    // 更新地址信息
    static char addrBuffer[20];
    snprintf(addrBuffer, sizeof(addrBuffer), "Addr: 0x%llX", currentNodeId);
    oledaddr = addrBuffer;

    // 从 `lightStateTable` 获取当前节点状态和亮度
    auto it = lightStateTable.find(currentNodeId);
    if (it != lightStateTable.end()) {
        LightState &light = it->second;

        // 设置开关状态
        if (light.lightA.isOn || light.lightB.isOn) {
            oledstate = "State:Open";
        } else {
            oledstate = "State:Close";
        }

        // 分别显示两盏灯的亮度
        snprintf(oledvalue, sizeof(oledvalue), "Yellow:%d Blue:%d",
                 light.lightA.brightness, light.lightB.brightness);
    } else {
        // 当前节点不在状态表中，设置为未知
        oledstate = "State:Unknown";
        snprintf(oledvalue, sizeof(oledvalue), "Yellow:N/A Blue:N/A");
    }

    // 日志调试信息
    ESP_LOGI("OLED_DEBUG", "刷新数据: Addr=%s, State=%s, Mode=%s, Value=%s", oledaddr, oledstate, oledmode, oledvalue);

    // 刷新显示
    oled_refresh(oledaddr, oledstate, oledmode, oledvalue);
}
void oled_refresh(char* addr, char* state, char* mode, char* value) {
    ESP_LOGI("OLED_REFRESH", "刷新参数: Addr=%s, State=%s, Mode=%s, Value=%s", addr, state, mode, value);

    ESP_LOGI("OLED_REFRESH", "清屏操作开始");
    OLEDDisplay_clear(oled);

    ESP_LOGI("OLED_REFRESH", "设置文本对齐和字体");
    OLEDDisplay_setTextAlignment(oled, TEXT_ALIGN_CENTER);
    OLEDDisplay_setFont(oled, ArialMT_Plain_16);

    ESP_LOGI("OLED_REFRESH", "绘制地址: %s", addr);
    OLEDDisplay_drawString(oled, 64, 0, addr);

    ESP_LOGI("OLED_REFRESH", "绘制状态: %s", state);
    OLEDDisplay_drawString(oled, 64, 15, state);

    ESP_LOGI("OLED_REFRESH", "绘制模式: %s", mode);
    OLEDDisplay_drawString(oled, 64, 30, mode);

    ESP_LOGI("OLED_REFRESH", "绘制值: %s", value);
    OLEDDisplay_drawString(oled, 64, 45, value);

    ESP_LOGI("OLED_REFRESH", "调用 OLEDDisplay_display 刷新屏幕");
    OLEDDisplay_display(oled);  // 刷新屏幕
    vTaskDelay(pdMS_TO_TICKS(10));  // 确保显示稳定
    ESP_LOGI("OLED_REFRESH", "屏幕刷新完成");
}

### Bug prevalence

Once or twice a week

### GitHub hash of the SDK that was being used

5.0.2

### Platform

esp32

### Type

Security Issue

**Comment by bzbarsky-apple** [comment]
This does not look like a core Matter SDK issue.  Please report this issue in the appropriate place for your platform.
