### ISSUE TITLE
Unbounded stack in src/setup_payload

### ISSUE THREAD

**Issue by kpschoedel** [project-chip/connectedhomeip#3663]
#### Problem

payloadBase41RepresentationWithTLV() allocates stack space based on an argument, with no upper bound. This could lead to stack exhaustion on small devices.

 #### Proposed Solution

TBD. The caller's callers pass in a destination buffer, which might be usable as temporary space.

Code in this path also uses heap-allocated std::strings, which should ultimately be removed for issue #2748 (All Embedded Device-side Code Needs to Be Scrubbed of Direct Heap Usage).

**Comment by kpschoedel** [comment]
decimalStringWithPadding() in src/setup_payload/ManualSetupPayloadGenerator.cpp added to this issue.

Per https://github.com/project-chip/connectedhomeip/pull/3683/files#r518644463 these uses are probably OK, and just need to be recorded as such.

**Comment by alexhqwang** [comment]
Not sure how to change assignee, but I am looking into this since the Nest RTOS thermostat does not support std::string.

**Comment by alexhqwang** [comment]
PR has merged, this can be closed. thanks!
