### ISSUE TITLE
[BUG] Matter Device pairing without Matter client developer profile 

### ISSUE THREAD

**Issue by sudhanshgupta** [project-chip/connectedhomeip#36700]
### Reproduction steps

We need support regarding an issue encountered with Matter devices.

We have integrated custom Fabric commissioning in App and implemented the commissioning and control functionality.

In development, I can commission and control Matter devices successfully. However, in the production (App Store build) version, if I delete the [Bluetooth Central developer (EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig)](https://developer.apple.com/services-account/download?path=/iOS/iOS_Logs/EnableBluetoothCentralMatterClientDeveloperMode.mobileconfig) profile from the device and attempt to commission it, I encounter the following error:
 
```
BLE:Error writing Characteristics in Chip service on the device: [The specified UUID is not allowed for this operation.]
Failed to establish BLE connection: src/platform/Darwin/BleConnectionDelegateImpl.mm:509: Ble Error 0x00000407: GATT write characteristic operation failed
Discovery timed out
Mdns: Browse failure (src/platform/Darwin/DnssdImpl.cpp:554: CHIP Error 0x00000074: The operation has been cancelled)
PASESession timed out while waiting for a response from the peer. Expected message type was 33
MTRDeviceControllerDelegate PASE session establishment failed: src/protocols/secure_channel/PASESession.cpp:258: CHIP Error 0x00000032: Timeout
Creating NSError from src/protocols/secure_channel/PASESession.cpp:258: CHIP Error 0x00000032: Timeout (context: (null))
```
**Device:** Matter Device 
**Platform:** iOS
**Library:** Apple 
1. Matter.xcframework 
2. MatterSupport.xcframework 

Could you please advise on resolving this? 

Users cannot install the Bluetooth profile intended for "Development Only."
 
Looking forward to your guidance.

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

NA

### Platform

darwin

**Comment by bzbarsky-apple** [comment]
You should be using MatterSupport to handle bringing the device onto the network (needs Bluetooth communication, but MatterSupport handles that without the profile) and open an on-network commissioning window for you.  At that point you can commission without Bluetooth being involved, which does not need the profile bits either.
