### ISSUE TITLE
CHIP Device Controller Python Script Binding will crash on error

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#3672]
#### Problem
```
ble-scan-connect xxxxx
connect xxxx
ble-disconnect
(crash)
```

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Is this still happening @erjiaqing post https://github.com/project-chip/connectedhomeip/pull/4542 ?

**Comment by erjiaqing** [comment]
After 4542 is merged, we no longer use this API, so we close it now.
