### ISSUE TITLE
What happens if we don't do that?  Won't the writes happen anyway?  Or are we worried about our caller tearing down the storage backend if we return from here, before the writes have a chance to happen?  Would be good to document why this needs to be a sync point.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#36814]
What happens if we don't do that?  Won't the writes happen anyway?  Or are we worried about our caller tearing down the storage backend if we return from here, before the writes have a chance to happen?  Would be good to document why this needs to be a sync point.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/36791#discussion_r1881255908_

**Comment by bzbarsky-apple** [comment]
This got addressed in #36791.
