### ISSUE TITLE
Consider eliminating strncpy from our code

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3736]
#### Problem
`strncpy` will sometimes null-terminate and sometimes not.

 #### Proposed Solution
Use `strlcpy` instead.

@rwalker-apple @pan-apple @mspang

**Comment by mspang** [comment]
Linux's libc doesn't have `strlcpy`.

**Comment by bzbarsky-apple** [comment]
Ah, that's unfortunate.  I guess not much we can do here, then, apart from making sure all `strncpy` callers properly check return values...

**Comment by rwalker-apple** [comment]
strlcpy() isn't terribly hard to implement

**Comment by gerickson** [comment]
Agreed. I know we've moved well-past autotools; however, in typical autotools projects, you have a compat directory and where implementations of things like strlcpy aren't natively available, something from compat is used. In fact, I suspect we could "third_party" an existing `compat` implementation from another project with a suitable license and call it done.

**Comment by rwalker-apple** [comment]
> Linux's libc doesn't have `strlcpy`.

libbsd-dev has strlcpy()...
