### ISSUE TITLE
Change DeviceController to use async persistent storage API

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#3738]
#### Problem
https://github.com/project-chip/connectedhomeip/pull/3630 adds a dependency on a sync interface in persistent storage API. This should be changed to using the async interface, as the sync call could block and take longer.

Reference: https://github.com/project-chip/connectedhomeip/pull/3630#discussion_r520211243

 #### Proposed Solution
Change to using the async API.

**Comment by woody-apple** [comment]
Moving to post V1.0, not clearly required for V1.0
