### ISSUE TITLE
Need better byte ordering function in CHIPEncoding

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#3762]
#### Problem
Code is currently using HostSwap* functions to convert from network to host and the opposite. While it works, we need better function names to improve code readability.

Reference: https://github.com/project-chip/connectedhomeip/pull/3630/files#r520135742

 #### Proposed Solution
Add new functions and use them at the relevant points in the code.

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/952
