### ISSUE TITLE
ESP32: Not able to complete Rendezvous session using chip-tool with static sdkconfig

### ISSUE THREAD

**Issue by prasad-alatkar** [project-chip/connectedhomeip#3785]
#### Problem

CHIP-TOOL is not able to connect to ESP32 (BLE mode) after commit: b255818f. This failure is applicable for both NimBLE and Bluedroid BLE stacks of ESP32.  

 * expected behavior:
   - Should be able to connect to ESP32 using chip-tool and complete Rendezvous session.
 * actual behavior
   - Even after running `./out/debug/chip-tool echo ble 12345678 3840` on mac not able to connect to ESP32(NimBLE). This behavior has been seen after `Fix BLE advertisement service data format (#3557)` commit. 
 * steps to reproduce
   - Run `all-clusters-app` app on ESP32 with NimBLE BLE stack.
   - On mac, run `./out/debug/chip-tool echo ble 12345678 3840` , it won't connect to ESP32
 * system configuration
  * NimBLE:
  -- Enable NimBLE stack (enabled by default)
  -- Choose Rendezvous Mode as BLE.
  * Bluedroid:
  -- Enable Bluedroid stack from menuconfig options
  -- Choose Rendezvous mode as BLE

 #### Proposed Solution

If we comment out [kFlag_AdvertisingRefreshNeeded](https://github.com/project-chip/connectedhomeip/blob/master/src/platform/ESP32/nimble/BLEManagerImpl.cpp#L276) the chip-tool can connect to ESP32, but I am currently not sure of other implications of this.

**Comment by prasad-alatkar** [comment]
Update: This issue occurs when I provide SSID + password through static configuration(`sdkconfig`) . Since the SSID and credentials are provided to device, I get `kWiFiConnectivityChange` platform event which retriggers the device advertisement and then chip-tool is unable to connect to ESP32. Is this expected behavior ? CC: @mspang @dhrishi

**Comment by dhrishi** [comment]
Hey @woody-apple I think this isn't relevant now. Should we close this?

**Comment by dhrishi** [comment]
Closing as this is not relevant now.
