### ISSUE TITLE
Incorporate Buffer Reference Counting (#2707) into BDX message structs

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#3837]
#### Problem
In PR #3731, the message structs for BDX messages store a pointer into a PacketBuffer to represent the File Designator and Metadata fields. This is dangerous, because if the struct outlives the PacketBuffer, there is a risk of unsafe memory access.

 #### Proposed Solution
We should incorporate #2707, which addresses this problem.

**Comment by holbrookt** [comment]
#3731 was merged but still uses raw pointers to represent variable-length data in the message structs. This issue still needs to be fixed

**Comment by woody-apple** [comment]
Moving this into v0.7, looks like BDX will be ready enough for this by then.
