### ISSUE TITLE
update MACOSX_DEPLOYMENT_TARGET to 10.16 to support building Python chip-device-ctrl on Bigsur 

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#3853]
Building Python chip-device-ctrl on Bigsur generates whl file with old OS version and might throw error ERROR: chip-0.0-cp38-cp38-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

 #### Proposed Solution
update MACOSX_DEPLOYMENT_TARGET to 10.16 to support building Python chip-device-ctrl on Bigsur until the https://github.com/pypa/packaging/pull/319 resolved

**Comment by woody-apple** [comment]
Looks like the referenced PR is already in. Closing.
