### ISSUE TITLE
Buffer length message in CHIPDevice.mm sendMessage might not be safe

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3856]
#### Problem
The code looks like this:
```
        buffer->SetDataLength(messageLen);

        memcpy(buffer->Start(), messageChars, messageLen);
```

but `SetDataLength` does not guarantee that it will set the length to its argument.  It might clamp it to a smaller length, if the argument is larger than what `PacketBuffer` can support.

 #### Proposed Solution
Check the data length after the `SetDataLength` call and either error out if it's smaller than `messageLen` or only copy enough bytes that will actually fit, whichever makes more sense here.

@pan-apple

**Comment by pan-apple** [comment]
Fixed in #3879
