### ISSUE TITLE
EFR32 includes aren't working

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#386]
#### Problem
These headers aren't seen by VS Code:
```
#include "display.h"
#include "dmd.h"
#include "glib.h"
```

 #### Proposed Solution
Update settings.json to include them

**Comment by andy31415** [comment]
I believe gn can generate a compile_commands.json file to find headers.

The tricky bit is to be able to choose which build we reference - I believe we currently may default to linux rather than efr32 and such.

**Comment by woody-apple** [comment]
SW BRB: This is a great enhancement for the future.
