### ISSUE TITLE
Add adversarial tests or verification that error cases return reasonable errors for IM message df

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#3886]
I don't see any adversarial tests or verification that error cases return reasonable errors.  Are more than functional tests coming at some point?

_Originally posted by @rwalker-apple in https://github.com/project-chip/connectedhomeip/pull/3491#discussion_r524804428_

**Comment by woody-apple** [comment]
Moving to post V1.0, not clearly required for V1.0
