### ISSUE TITLE
BLEEndPoint::Receive should probably check that it has data

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#3922]
#### Problem
`BLEEndPoint::Receive` does:
```
    if (mBtpEngine.IsCommandPacket(data))
```
which will examine the first byte of `data`.  But what if `data` has no payload bytes at all?  Seems like we'd be reading random memory.

 #### Proposed Solution
Check that we have a byte to read before reading it.

It looks like this code came in like this from Weave....  @pan-apple @turon

**Comment by andy31415** [comment]
Marking looks critical: memory safety and by the description sounds quite a small change.
