### ISSUE TITLE
Add network provisioning cluster to CHIP

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#3945]
#### Problem
per spec https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/309, we need initial network provisioning cluster xml

**Comment by erjiaqing** [comment]
The code for this issue should be submitted to zap repo. Will work on this since related spec is ready.

**Comment by franck-apple** [comment]
Re-opening. The issue should be closed once it’s working end to end.

**Comment by erjiaqing** [comment]
> Re-opening. The issue should be closed once it’s working end to end.

Just submitted a PR for basic support (only supports WiFi, and only on lighting app)

Will create seperate PR for scale the network commissioning to all example apps and for details functions. (Or maybe add a list to this PR? However, I'd like to create a project for all commissioning works.)

Note: Some features depends on other features in CHIP(like fabric commissioning) to be finished first.
