### ISSUE TITLE
ESP32: Optimize the temperature-measurement-app to use less RAM and Flash

### ISSUE THREAD

**Issue by dhrishi** [project-chip/connectedhomeip#3977]
#### Problem
Need to optimize the temperature-measurement-app to use less RAM and Flash

 #### Proposed Solution
Add optimization in the sdkconfig related to: code size, Wi-Fi and lwIP configuration options, minimal logging, BLE maximum connections  etc.

**Comment by woody-apple** [comment]
@dhrishi What are next steps here?

**Comment by dhrishi** [comment]
@woody-apple  Updated [here](https://github.com/project-chip/connectedhomeip/issues/3793#issuecomment-773061683)

**Comment by sweetymhaiske** [comment]
Optimizations are done #4756
