### ISSUE TITLE
BufBound redundant, remove it

### ISSUE THREAD

**Issue by rwalker-apple** [project-chip/connectedhomeip#4029]
#### Problem
> * BufferWriter is basically BufBound, except it is either LittleEndian or BigEndian (just Put, never PutLE or PutBE)

BufBound can be deleted

_Originally posted by @rwalker-apple in https://github.com/project-chip/connectedhomeip/issues/4014#issuecomment-736034179_

#### Proposed solution
delete BufBound, move consumers to BufferWriter

**Comment by kpschoedel** [comment]
There's also `core/CHIPEncoding.h`.

*Dear Mr. President: There are too many buffer APIs nowadays. Please eliminate three. I am not a crackpot.*

**Comment by kpschoedel** [comment]
I'll do this, since I just touched BufBound.
