### ISSUE TITLE
python not checked by restyled.io

### ISSUE THREAD

**Issue by rwalker-apple** [project-chip/connectedhomeip#4051]
####Problem

this reformatting looks extraneous, can you revert these until we have python in restyled?

_Originally posted by @rwalker-apple in https://github.com/project-chip/connectedhomeip/pull/4050#r533904312_

#### Proposed Solution
enable autopep8 and/or black and/or ?? for python in CHIP

https://docs.restyled.io/available-restylers/

**Comment by woody-apple** [comment]
@andy31415 Anyone care to take a peek at this?
