### ISSUE TITLE
Missing requirements for chip-device-ctrl.py: dbus-python PyGObject

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [project-chip/connectedhomeip#4087]
#### Problem

It seems that at least the following python packages are missing in requirements.txt:

dbus-python
PyGObject

 #### Proposed Solution

Add the two packages to `./scripts/requirements.in` and/or `./scripts/requirements.txt`.

**Comment by markus-becker-tridonic-com** [comment]
FYI: @mspang

**Comment by woody-apple** [comment]
Is this still needed @mspang ?

**Comment by mspang** [comment]
It installs automatically with the chip wheel, but I think it's right that we should add it since that will lock down the version and allow us to manage breaks, if any.
