### ISSUE TITLE
Sniffer Support for CHIP

### ISSUE THREAD

**Issue by kidip** [project-chip/connectedhomeip#4145]
#### Needs

WireShark plugin or other type of sniffing capability for the Certification Tool.

#### Reason

The CHIP Certification Tool requires sniffing capability to verify protocol information being sent from devices.  We will need a WireShark or some other solution to be able to analyze these packets.

**Comment by markus-becker-tridonic-com** [comment]
Similar to https://github.com/project-chip/connectedhomeip/issues/1908?

**Comment by woody-apple** [comment]
SW BRB: Yup, duplicate.
