### ISSUE TITLE
Linux ConnectivityManager tries to use  wpa_supplicant

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#4146]
#### Problem
For rasberry pi integration, Connectivity manager tries to fully control the O/S wifi stack.

This does not work well for general desktop linux examples.

 #### Proposed Solution
Should be able to enable/disable this functionality at build time. Likely should be disabled by default and only enabled for rasberry pi builds.

**Comment by yufengwangca** [comment]
Yes, on Desktop Linux, we need to disable the network manager, otherwise there will be conflict between CHIP daemon and native network manager since both of them try to control the WiFi via wpa_supplicant
