### ISSUE TITLE
Received packet buffer is not getting freed after processing incoming message in IOS app

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#4150]
https://github.com/project-chip/connectedhomeip/blob/222a5754ee7e0e18267ea8bffe8cf1d3c8d162a1/src/darwin/Framework/CHIP/CHIPDeviceStatusDelegateBridge.mm#L54

The call to `chip::System::PacketBuffer::Free(message);` is being made after the PacketBuffer * `message` has already traversed the buffer list, and therefore `message` is already set to NULL when calling Free().

**Comment by kpschoedel** [comment]
I believe this was fixed by #4011

https://github.com/project-chip/connectedhomeip/blob/316a6f5677c6d53ba91c962b308e0c3886e74dad/src/darwin/Framework/CHIP/CHIPDeviceStatusDelegateBridge.mm#L39
