### ISSUE TITLE
Migrate to messaging layer

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#4170]
Create an issue to track the progress of migrating to messaging layer.

This contains 2 major parts:
* Migrate device controller #4171
* Migrate app-server & interactive data model #3602 
  * [ExchangeManager] Pass SecureSession messages and events to old SecureSession delegates #4516 (temporary solution to maintain backward compatibility)
  * Enable ExchangeManager #5095 (Draft, blocked by #4516) 

~~Both of them depends on the Channel API #4019. (Done)~~ 

~~The Channel implementation depends on #3728. (Done)~~

**Comment by kghost** [comment]
@woody-apple this is blocked on PR #4019. This PR is essential to solved the issue #3584, which is the major problem blocking message layer.

**Comment by woody-apple** [comment]
Closing this
