### ISSUE TITLE
Consider a bit more safety for HashFinalize and its callers

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#4189]
#### Problem
Right now `Spake2p_P256_SHA256_HKDF_HMAC::HashFinalize` and `Hash_SHA256_stream::Finish` both take a raw `uint8_t *` for their outparam and assume the caller will pass in a big enough thing.

 #### Proposed Solution
Use `std::array<uint8_t, kSHA256_Hash_Length>` to enforce the right length. Would be nice if we had writable slices in C++, but we don't...

@pan-apple

**Comment by tcarmelveilleux** [comment]
Will take this on
