### ISSUE TITLE
Various opaque contexts in CryptoPAL should ensure they have sufficient alignment

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#4190]
#### Problem
We should ensure that the alignment requirements of `HashSHA256OpaqueContext` are no lower than the various concrete contexts it represents.  Similar for other opaque contexts in CryptoPAL.

 #### Proposed Solution
Add relevant static asserts if we can.

@pan-apple

**Comment by andy31415** [comment]
v1 review: @bzbarsky-apple could you provide an opinion/statement if this should block v1 or not?

**Comment by andy31415** [comment]
I believe that `add static asserts` should not be v1blocking. Please adjust @bzbarsky-apple if you disagree.

**Comment by bzbarsky-apple** [comment]
It's not v1 blocking if the asserts would pass @andy31415 

If they fail, we are going to have issues with our crypto operations....

**Comment by bzbarsky-apple** [comment]
Looks like we started using `SafePointerCast` to cast from the opaque contexts, which enforces the necessary alignment bits via static assert.
