### ISSUE TITLE
Move all API documentation to header for ReliableMessageContext/ReliableMessageMgr

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#4214]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
@yufengwangca can you please clarify what this is needed?
