### ISSUE TITLE
Check if we still need to evaluate non-critical error for the first CRMP

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#4217]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
@yufengwangca What is this covering?

**Comment by yufengwangca** [comment]
Weave is evaluating the non-critical errors for WRMP, this is one of the review comment to check if we need the same behavior in CHIP.

CRMP  is an new implementation on CHIP, a lot of concepts are changed, we don't have this behavior specified in Spec, so I will close this ticket for now.
