### ISSUE TITLE
Check if we still need to evaluate non-critical error for the initial CRMP sending 

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#4218]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
@yufengwangca what is this covering?

**Comment by yufengwangca** [comment]
There is non-critical error defined for CRMP in CHIP.
