### ISSUE TITLE
python dev ctrl to support Run-time dynamic discovery of operational CHIP Nodes 

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4236]
python dev ctrl controller should discover the current IPv6 address and port for a known commissioned CHIP Node.

**Comment by Damian-Nordic** [comment]
@cjandhyala Note that Python CHIP controller built with `--args='chip_mdns="platform"'` supports "resolve" command which does more less what the description contains. Is there anything more needed for this task?

**Comment by cjandhyala** [comment]
@Damian-Nordic , building with the above args ,crashes the python controller

$ chip-device-ctrl 
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:DL: CHIP task running
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/chip-device-ctrl", line 642, in <module>
    main()
  File "/home/ubuntu/.local/bin/chip-device-ctrl", line 623, in main
    devMgrCmd = DeviceMgrCmd(rendezvousAddr=options.rendezvousAddr, controllerNodeId=options.controllerNodeId, bluetoothAdapter=adapterId)
  File "/home/ubuntu/.local/bin/chip-device-ctrl", line 146, in __init__
    self.devCtrl = ChipDeviceCtrl.ChipDeviceController(controllerNodeId=controllerNodeId, bluetoothAdapter=bluetoothAdapter)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chip/ChipDeviceCtrl.py", line 51, in wrapper
    instance[0] = cls(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/chip/ChipDeviceCtrl.py", line 84, in __init__
    raise self._ChipStack.ErrorToException(res)
chip.exceptions.ChipStackError: CHIP Error 4003 (0x00000FA3): Incorrect state

**Comment by Damian-Nordic** [comment]
@cjandhyala It should be fixed by https://github.com/project-chip/connectedhomeip/pull/6041.

**Comment by cjandhyala** [comment]
@Damian-Nordic , looks like the resolve command is looking for mdns _chip_tcp only. Could we expand this to cover _chipd._udp. so that we can verify '4.2.3. Commissionable Discovery' as well

**Comment by Damian-Nordic** [comment]
@cjandhyala That is a separate functionality and I believe @cecille is working on adding another command for that purpose: #5716. This task is only about operational discovery which uses `_chip._tcp` service type.

**Comment by franck-apple** [comment]
@Damian-Nordic, was this solved with #6459 (that replaced #5716)?
