### ISSUE TITLE
Map ESP32 error codes with CHIP error codes

### ISSUE THREAD

**Issue by dhrishi** [project-chip/connectedhomeip#4256]
#### Problem
ESP32 APIs return the error codes specific to ESP32. When these are called in the CHIP code, they should be mapped to corresponding CHIP error codes to be propagated forward so that the behavior is correct

 #### Proposed Solution
Add a function that converts ESP32 error codes to CHIP error codes and vice versa (if required)

**Comment by woody-apple** [comment]
@dhrishi Would you be able to take a stab at this for test event 2?

**Comment by dhrishi** [comment]
Hey @woody-apple Yes, I have already assigned this. @sweetymhaiske will be working on this. Thanks!
