### ISSUE TITLE
The linux device crashed if we do network provisioning twice

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#4269]
#### Problem
The linux device crashed if we do network provisioning twice:
chip::DeviceLayer::ConnectivityMgrImpl().StartWiFiManagement();
(wait)
chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(ssid, passwd);
(wait)
chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(ssid, passwd);

According to the backtrace, seems we have some kind of double free issue:
```
#0 0x0000fffff7a3000c in g_type_check_instance_is_fundamentally_a () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#1 0x0000fffff7a139b8 in g_object_unref () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#2 0x0000aaaaaaae46a4 in chip::DeviceLayer::ConnectivityManagerImpl::ProvisionWiFiNetwork(char const*, char const*)
(this=0xaaaaaab919b8 <chip::DeviceLayer::ConnectivityManagerImpl::sInstance>, ssid=0xffffffffe7d0 "Nest-T", key=0xffffffffe7f8 "Nesttesting")
at ../third_party/connectedhomeip/src/platform/Linux/ConnectivityManagerImpl.cpp:849

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
@yufengwangca What are the next steps here? Looks like you have reliable repo-steps, and a stack trace?
