### ISSUE TITLE
Remove map from IM invoke command

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#4275]
Are we really OK to use std::map here? It's big and directly uses the heap, right? Believe we're planning to avoid the STL altogether.

_Originally posted by @mspang in https://github.com/project-chip/connectedhomeip/pull/4241#discussion_r552359944_

**Comment by erjiaqing** [comment]
According to conversations with @vivien-apple , I will submit another PR as a follow up, in that PR, I will add DispatchSingleCommand(clusterid, commandId, role, tlvReader, commandObj) to replace InteractionModelEngine::ProcessCommand (and this will remove the std::map in InteractionModelEngine, and modify related tests.

In #4298

**Comment by woody-apple** [comment]
@yunhanw-google is this now complete with https://github.com/project-chip/connectedhomeip/pull/4298 ?

**Comment by yunhanw-google** [comment]
yes, it is completed with #4585
