### ISSUE TITLE
Nordic board thread Network Provisioning fails

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4308]
Following Lock app instructions, Provisioning OTBR credentials into the device, chip stack fails at "Failed in sending IP address. error Error 4059 (0x00000FDB)"

uart:~$ ot thread start
: 166737[DL] OpenThread State Changed (Flags: 0x00001015)
D: 166742[DL]    Device Role: DETACHED
D: 166746[DL]    Thread Unicast Addresses:
D: 166750[DL]         fdde:ad00:beef:0:7062:819f:ab1:4081/64 valid preferred
D: 166757[DL]         fe80::2462:761e:71ea:44a3/64 valid preferred
uart:~$ D: 167163[DL] OpenThread State Changed (Flags: 0x00000100)
D: 169423[DL] OpenThread State Changed (Flags: 0x001332b7)
D: 169428[DL]    Device Role: CHILD
D: 169432[DL]    Network Name: OpenThread-90d8
D: 169436[DL]    PAN Id: 0xABCD
D: 169439[DL]    Extended PAN Id: 0x961DE49BA2E97B78
D: 169444[DL]    Channel: 11
D: 169446[DL]    Mesh Prefix: fddd:30f:2baf:e4f7::/64
D: 169451[DL]    Partition Id: 0x59DA4718
D: 169455[DL]    Thread Unicast Addresses:
D: 169459[DL]         fd31:296e:280b:0:32da:e20a:4a1b:9d76/64 valid preferred
D: 169466[DL]         fddd:30f:2baf:e4f7:0:ff:fe00:3804/64 valid preferred rloc
D: 169473[DL]         fddd:30f:2baf:e4f7:7062:819f:ab1:4081/64 valid preferred
D: 169480[DL]         fe80::2462:761e:71ea:44a3/64 valid preferred
I: 169486[NP] Sending IP Address. Delegate 0x20005d74

E: 169491[NP] Failed in sending IP address. error Error 4059 (0x00000FDB)

D: 169498[DL] OpenThread State Changed (Flags: 0x00000001)
D: 169503[DL]    Thread Unicast Addresses:
D: 169507[DL]         fd31:296e:280b:0:32da:e20a:4a1b:9d76/64 valid preferred
D: 169514[DL]         fddd:30f:2baf:e4f7:0:ff:fe00:3804/64 valid preferred rloc
D: 169521[DL]         fddd:30f:2baf:e4f7:7062:819f:ab1:4081/64 valid preferred
D: 169528[DL]         fe80::2462:761e:71ea:44a3/64 valid preferred
I: 169534[NP] Sending IP Address. Delegate 0x20005d74

E: 169539[NP] Failed in sending IP address. error Error 4059 (0x00000FDB)

**Comment by woody-apple** [comment]
Dup of: #4225
