### ISSUE TITLE
Add More Test Cases for Invalid CHIP Certificates

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#4324]
#4060 Implements CHIP Certificate Code.

This is a follow up ticket to add more test cases for this code. Specially around invalid certificates (either invalid TLV or invalid ASN1):
- Invalid certificate field order
- unexpected fields
- missing fields
- incorrect fields (DN, key identifiers, etc...)

**Comment by woody-apple** [comment]
Moving to post V1.0, not clearly required for V1.0
