### ISSUE TITLE
Python dev ctrl to support thread provisioning on nordic boards

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4373]
Python dev ctrl tool to support thread provisioning on nordic boards

**Comment by erjiaqing** [comment]
This PR should be blocked by https://github.com/project-chip/connectedhomeip/issues/3945 and https://github.com/project-chip/connectedhomeip/issues/4421.

**Comment by woody-apple** [comment]
This is a dup of: #4225
