### ISSUE TITLE
CHIP Framework returns an NSError, even when succeeding

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#4393]
#### Problem
It appears that we are not handing back nil when commands/requests succeed, but instead an NSError with success in it. We should return nil 👍 

CHIP Accessory command sent. Error: Error Domain=CHIPErrorDomain Code=8 "Success." UserInfo={NSLocalizedDescription=Success.}

**Comment by holbrookt** [comment]
@woody-apple any idea if this is still an issue or who would know?

**Comment by woody-apple** [comment]
Still an issue, but Darwin

**Comment by bzbarsky-apple** [comment]
@woody-apple I believe this was fixed in #13072.  There is no more "CHIPSuccess" value in CHIPErrorDomain, and we convert CHIP_NO_ERROR to `nil` when converting it to NSError.
