### ISSUE TITLE
Decouple static allocation for the binding table (and static allocation in general)

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#4407]
#### Problem
Part of #4397: `binding-table.cpp` currently allocates the binding data statically and has runtime checks agains `gen/` constants. This strongly couples non-generated code with generated code.

 #### Proposed Solution
 
Remove the static allocation and allow the generated code to pass in the allocated storage + size. This would allow decoupling generated code from `src/app` code.

**Comment by woody-apple** [comment]
Issue Review: Out of time and not critical, moving this out of v1.0.
