### ISSUE TITLE
Rename SecurePairingSession class and associated delegates

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#4468]
#### Problem
SecurePairingSession is implements PASE protocol, as defined in CHIP specifications. The class name is not conveying the purpose of code.

 #### Proposed Solution
Rename SecurePairingSession class, and files to PasswordAuthenticatedSessionEstablishment
Reword pairing related functions in class and delegate (AuthenticatedSessionEstablishmentDelegate) to convey SessionEstablishment functionality.

**Comment by turon** [comment]
Could we call them `PASESession` and `CASESession` for brevity?
Does the class just establish the session or does it manage the full lifecycle?

**Comment by pan-apple** [comment]
Yes, sounds good to me. These classes are just establishing the session. The session is handed over to SecureSessionMgr.
