### ISSUE TITLE
Remove temporary replacements for NFC payload URI compatibility

### ISSUE THREAD

**Issue by kkasperczyk-no** [project-chip/connectedhomeip#4504]
#### Problem
In the #4498 there were introduced some temporary replacements in NFC payload of spaces with _ for nrfconnect platform and _ with spaces for Android platform. It was done to not wait on fixing problems discussed in the CHIP-Specifications/connectedhomeip-spec#415

 #### Proposed Solution
Remove replacements after fixing problems discussed in the CHIP spec issue #415.

**Comment by turon** [comment]
Relevant portions of code related to this issue were tagged with TODO(#4504), but no reference to #4504 exists in current codebase.  This may mean this has been fixed, but we need to verify for v1 -- QR format must make consistent use of `_` or ` ` that matches spec.
Removing `v1_triage_split_4 `.

**Comment by woody-apple** [comment]
Closing, given this will be verified by the CSG, we can re-open if this fails.
