### ISSUE TITLE
EFR32 Build is blocking Openthread Update

### ISSUE THREAD

**Issue by jepenven-silabs** [project-chip/connectedhomeip#4527]
#### Problem
When trying to update the OpenThread submodule, the EFR32 CI job fails, since the newest version of OpenThread use the new GSDK of silabs with new API.

 #### Proposed Solution
Update the GSDK that the EFR32 platform use for a newer version so we can update the OpenThread submodule.

**Comment by tima-q** [comment]
@jepenven-silabs Any update on this update work ? #4561 can only progress by your update here.

**Comment by jepenven-silabs** [comment]
> @jepenven-silabs Any update on this update work ? #4561 can only progress by your update here.

Yes, Should have two PR open this week to fix this. First one is to ensure the backward compatibility and second one is with the GSDK update.

**Comment by jepenven-silabs** [comment]
@tima-q Quick update, need to fix a bug with BLE before I can open a PR.
