### ISSUE TITLE
Implement General commissioning in CHIP

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#4540]
Problem:
Per chip spec, we need fabric provisioning functionality, https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/GeneralProvisioningCluster.adoc#setfabric-command

Solution:
Implement and have unit and integration test on it.

**Comment by yufengwangca** [comment]
@franck-apple , Multiple Fabric  is just finalized in spec, I don't think this should be done in TE2
