### ISSUE TITLE
Ble connection success callback multiple times on darwin platform

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#4547]
#### Problem

It is called every time it discovers a service on a peripheral. Which should be called once only when it connected.

https://github.com/project-chip/connectedhomeip/blob/b0fcbd2944c838245356ae2720a9463555959d57/src/platform/Darwin/BleConnectionDelegateImpl.mm#L192-L200

In https://github.com/project-chip/connectedhomeip/blob/b0fcbd2944c838245356ae2720a9463555959d57/src/transport/BLE.cpp#L162-L175, this will break BLE transport state.

This should be related to and #4339 #4356 

 #### Proposed Solution

Fix it.

**Comment by erjiaqing** [comment]
Assigned to @vivien-apple from code history, please help redirect this to correct person if needed.

**Comment by vivien-apple** [comment]
@erjiaqing Do you have more details ? For example I can't reproduce with the tuple `chip-tool/M5Stack`.

Looking at the code, the only obvious way it can happens is if the device advertise twice with the same short service `UUID` or if `PairDevice` is called twice.

**Comment by tcarmelveilleux** [comment]
This is obsolete.
