### ISSUE TITLE
Fix build break with: https://github.com/project-chip/connectedhomeip/pull/4578

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#4580]
Somehow this PR broke the build.

**Comment by woody-apple** [comment]
@pan-apple can you take a peek?

**Comment by pan-apple** [comment]
#4582 should have fixed it. Sorry for causing the CI breakage.

**Comment by pan-apple** [comment]
Closing this issue, since CI has been stable since #4582 was merged.
