### ISSUE TITLE
Remove NetworkProvisioning.cpp/.h code once ZCL cluster is used for provisioning

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#4606]
#### Problem
The `NetworkProvisioning.cpp/.h` code was implemented as a stop gap solution to configure device for network connectivity. The specifications ask to use ZCL cluster for provisioning, and DNS-SD for device operational discovery. Once the cluster and operational discovery is integrated, `NetworkProvisioning.cpp/.h` and related code should be deleted.

**Comment by yufengwangca** [comment]
NetworkProvisioning.cpp/.h have been cleaned up
