### ISSUE TITLE
Need Example in CI for k32w platform

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#4625]
#### Problem
Our build examples in GitHub don't include the k32w. We should have one of these for all platforms to make sure we build.

 #### Proposed Solution
Make one!

**Comment by woody-apple** [comment]
@doru91 Could you take a peek at this please?

**Comment by doru91** [comment]
@woody-apple, agree, there is a big need for having the K32W in the CI Tool. We are currently investigating the options for making this possible.

**Comment by doru91** [comment]
Ci support added. It can be closed.
