### ISSUE TITLE
Implement Message Counter Synchronization Protocol (MCSP).

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#4626]
Problem
Peer message counter synchronization is an essential part of enabling secure CHIP messaging between members of an application group.

Proposed Solution
Implement  the protocol used to synchronize message counters between peers when using the same symmetric group key. This protocol is focused on encrypted messages sent over UDP with or without use of CHIP Reliable Messaging Protocol (CRMP).

This ticket does not handle the Initiating Message Counter Synchronization part which is depending on the following issues:
1. https://github.com/project-chip/connectedhomeip/issues/4628
2. https://github.com/project-chip/connectedhomeip/pull/4571

**Comment by woody-apple** [comment]
Is this different than? https://github.com/project-chip/connectedhomeip/issues/3376

**Comment by yufengwangca** [comment]
Dup of #3376
