### ISSUE TITLE
Need to split "Make Unit & Functional Tests" into individual tests, and then aggregate at the end

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#464]
#### Problem
We could highly parallelize builds if we didn't have a single monolithic "test" phase. Can we split all the `make check` stuff into separate tests like the crypto and and setup payload ones? This will enable me to build this simultaneously in CI. Also note: I'm sharing built products from the main build, so the tests should be very minimal builds. 

Can we have 'make check' just be a compound make command, and break it into a bunch of subcommands?

 #### Proposed Solution
Split please

**Comment by andy31415** [comment]
@rwalker-apple can we close this now that we moved to gn? I think gn should parallelize as much as possible for test execution.
