### ISSUE TITLE
Add interface in Transport Layer to allows the messaging layer configure packet header

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#4641]
#### Problem
Currently, we only can configure payload header before sending message to transport layer. Packetheader are auto-configured in Transport layer 

 #### Proposed Solution
Add interface in Transport Layer to allows the messaging layer configure packet header

**Comment by woody-apple** [comment]
What feature is this for?

**Comment by yufengwangca** [comment]
To allow the upper layer configure the message. Such as we shall set the C flag in the packet header for certain type of control message.

**Comment by yufengwangca** [comment]
Per Boris, we temperately use hard-code method to configure C-flag since only two messages use this flag in spec now. Close it for now,
