### ISSUE TITLE
Mbed OS Docker image verification

### ISSUE THREAD

**Issue by lukgni** [project-chip/connectedhomeip#4653]
#### Problem
Our team work on adding Mbed OS support into the CHIP project. Having Mbed OS docker image from this repository usable in our fork would help us with development where we have to sync often and work using the both the fork and the upstream repo.

 #### Proposed Solution
Add GitHub workflow to verify Mbed OS image build process.

**Comment by woody-apple** [comment]
Please note: https://github.com/project-chip/connectedhomeip/issues/4654

**Comment by lukgni** [comment]
@woody-apple Thanks, I will take a look.
