### ISSUE TITLE
Build vs Unit test seem to do the same thing in workflows?

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#4659]
#### Problem
I'm not sure the difference between build, and test in the workflows. The output looks identical.

 #### Proposed Solution
Investigate

**Comment by kpschoedel** [comment]
Also, ‘Integration’ is misspelled in the workflow name.

**Comment by erjiaqing** [comment]
This is discussed in https://github.com/project-chip/connectedhomeip/pull/2713, and https://github.com/project-chip/connectedhomeip/pull/2688

The main different is the action for running unit tests are started using "--privileged" for happy tests.
