### ISSUE TITLE
Some DNS tests seem broken in GitHub CI & docker

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#4670]
#### Problem
Some IPv4 DNS tests are failing and breaking CI:
https://github.com/project-chip/connectedhomeip/runs/1832772196

 #### Proposed Solution
Disabled for now, fix.

**Comment by kpschoedel** [comment]
I see this locally when running inside a container (chip-build-cirque in my case) but not natively.

**Comment by woody-apple** [comment]
Thanks, that's helpful to nail this down!
