### ISSUE TITLE
Get rid of packed certificate time in the code

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#4692]
#### Problem
Packed certificate time has been removed from the spec, replaced by CHIP epoch time.  We should update the code accordingly.

 #### Proposed Solution
Remove `PackCertTime`, `UnpackCertTime`.  Figure out what to do with `PackedCertTimeToDate` and `PackedCertDateToTime`.  Replace `SecondsSinceEpochToPackedCertTime` with something that produces CHIP epoch times.  Update comments on `mEffectiveTime`.  Figure out what happens with `mNotBeforeDate` and `mNotAfterDate`.  

@emargolis do you have bandwidth for this?

**Comment by emargolis** [comment]
Yes, will work on that this week.

**Comment by andy31415** [comment]
Fixed by #4888
