### ISSUE TITLE
Unaddressed review comments from Operational Certificate landing

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#4695]
#### Problem
I finally had a chance to go through my review comments from https://github.com/project-chip/connectedhomeip/pull/4060 and see whether they were addressed in the PR as landed.  Not all of them were, or some may have been addressed incorrectly.  Specifically:

* [ ] In `DecodeECDSASignature`, why is there an unchecked `Next` call before `reader.VerifyEndOfContainer()`?
* [ ] https://github.com/project-chip/connectedhomeip/pull/4060#discussion_r571108096 -- reference-to-pointer is not clear at the _callsite_ in terms of whether the callee will write to the pointer.
* [ ] https://github.com/project-chip/connectedhomeip/pull/4060#discussion_r545573274 didn't really get addressed.  What is the "deferred list" and how do we know its structure here?  The ASN1Writer API doesn't say anything about it.  Should it?  Ideally, that API would document something about its buffer sizes and define this extra space constant it clearly depends on.  Then we could reference that stuff here.
* [ ] The comments on the `mTrustAnchor`/`mSigningCert` members of `ValidationContext` don't really address my request for documentation for those members.   The documentation I was hoping for would describe what the difference between the two thing is, not just restate what the name already says.
* [ ] A bunch of the comments added in #4060 say "certificiate" when they mean "certificate".
* [ ] The documentation for `mDecodeBuf` and `mDecodeBufSize` doesn't really say why those things are members and how they would be used.  It should.
* [ ] The documentation for `mMemoryAllocInternal` should probably say something about the semantics of it being true/false.  What does it actually affect?  Who is responsible for freeing the buffers?  Something else?

 #### Proposed Solution
Address the above.

@emargolis do you have bandwidth for these?

**Comment by emargolis** [comment]
> #### Problem
> I finally had a chance to go through my review comments from #4060 and see whether they were addressed in the PR as landed. Not all of them were, or some may have been addressed incorrectly. Specifically:
> 
> * [ ]  In `DecodeECDSASignature`, why is there an unchecked `Next` call before `reader.VerifyEndOfContainer()`?
Addressed in #8537
> * [ ]  [CHIP Operational Certificate Implementation #4060 (comment)](https://github.com/project-chip/connectedhomeip/pull/4060#discussion_r571108096) -- reference-to-pointer is not clear at the _callsite_ in terms of whether the callee will write to the pointer.
Addressed in #8537
> * [ ]  [CHIP Operational Certificate Implementation #4060 (comment)](https://github.com/project-chip/connectedhomeip/pull/4060#discussion_r545573274) didn't really get addressed.  What is the "deferred list" and how do we know its structure here?  The ASN1Writer API doesn't say anything about it.  Should it?  Ideally, that API would document something about its buffer sizes and define this extra space constant it clearly depends on.  Then we could reference that stuff here.
Not relevant as ASN1Writer implementation was changed
> * [ ]  The comments on the `mTrustAnchor`/`mSigningCert` members of `ValidationContext` don't really address my request for documentation for those members.   The documentation I was hoping for would describe what the difference between the two thing is, not just restate what the name already says.
Addressed in #8537; Added detail description for `mTrustAnchor` and removed `mSigningCert`, which is legacy artifact
> * [ ]  A bunch of the comments added in [CHIP Operational Certificate Implementation #4060](https://github.com/project-chip/connectedhomeip/pull/4060) say "certificiate" when they mean "certificate".
Addressed in #8537
> * [ ]  The documentation for `mDecodeBuf` and `mDecodeBufSize` doesn't really say why those things are members and how they would be used.  It should.
Not relevant and implementation has been updated.
> * [ ]  The documentation for `mMemoryAllocInternal` should probably say something about the semantics of it being true/false.  What does it actually affect?  Who is responsible for freeing the buffers?  Something else?
The documentation for this was already updated. 
> 
> #### Proposed Solution
> Address the above.
> 
> @emargolis do you have bandwidth for these?
