### ISSUE TITLE
Update Implementation to Use Default Critical (Non-Critical) Marks for CHIP Cert Extensions

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#4708]
CHIP spec was updated to request default mark for Certificate extensions.

The following certificate extensions, when present, MUST be marked as critical:
  basic constraints extension
  key usage extension
  extended key usage extension

The following certificate extensions, when present, MUST be marked as non-critical:
  subject key identifier extension
  authority key identifier extension

These rules should always be enforced when processing X.509 representation of the certificate.
In the CHIP certificate representation the "critical" field is omitted.

**Comment by andy31415** [comment]
Fixed in #4710
