### ISSUE TITLE
PASE session failed when processing the last key exchange message on Linux platform

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4736]
Linux app (Lighting)  fails to pair with python controller, fails at PASE SPAKE2 handshake . Python ctrl pairs with M5 fine. So the issue seem to be on linux app side.  Whereas M5 seem to work fine with the same code base. 

========== Controller side Log ============
chip-device-ctrl > connect -ble 3840 12345678
CHIP: [BLE] NewConnection
Rendezvous Initialized
Connected
chip-device-ctrl > CHIP: [BLE] CBManagerState: ON
CHIP: [BLE] Connecting to device with discriminator: 3840
CHIP: [BLE] Warning: OnBleConnectionComplete is called multiple times for the same peripheral.
CHIP: [BLE] subscribe complete, ep = 0x103c2c7c8
CHIP: [BLE] peripheral chose BTP version 3; central expected between 2 and 3
CHIP: [BLE] using BTP fragment sizes rx 20 / tx 128.
CHIP: [BLE] local and remote recv window size = 3
CHIP: [BLE] Sent PBKDF param request
CHIP: [BLE] Received pairing message from 12344321
CHIP: [BLE] Received pairing message for 112233
CHIP: [BLE] Received PBKDF param response
CHIP: [BLE] Sent spake2p msg1
CHIP: [BLE] Received pairing message from 12344321
CHIP: [BLE] Received pairing message for 112233
CHIP: [BLE] Received spake2p msg2
CHIP: [BLE] Sent spake2p msg3
CHIP: [CTL] Remote device failed in SPAKE2+ handshake

CHIP: [BLE] Auto-closing end point's BLE connection.

========== Device side log ============
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffb0024920
CHIP:BLE: Indication confirmation, 0xffffb0024920
CHIP:BLE: Indication confirmation, 0xffffb0024920
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffb0024920
CHIP:BLE: Indication confirmation, 0xffffb0024920
CHIP:BLE: Indication confirmation, 0xffffb0024920
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffb0024920
CHIP:BLE: Received rendezvous message from 112233
CHIP:BLE: Received spake2p msg3
CHIP:SVR: OnRendezvousStatusUpdate: Error 4172 (0x0000104C)
CHIP:SVR: OnRendezvousError: Error 4172 (0x0000104C)
CHIP:SVR: OnRendezvousStatusUpdate: Error 4172 (0x0000104C)
CHIP:SVR: OnRendezvousError: Error 4172 (0x0000104C)
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 515
CHIP:BLE: Write request received debug 0xffffb0024920
CHIP:SVR: OnRendezvousError: Error 4003 (0x00000FA3)
CHIP:BLE: Indication confirmation, 0xffffb0024920
CHIP:BLE: Indication confirmation, 0xffffb0024920
CHIP:BLE: ack recv timeout, closing ep 0xaaaad2579d78
CHIP:SVR: OnRendezvousError: Ble Error 6024 (0x00001788): Message fragment acknowledgement timed out
CHIP:BLE: Releasing end point's BLE connection back to application.
CHIP:BLE: Got notification regarding chip connection closure

M5 Logs
---------

> connect -ble 4000 12345678
CHIP: [BLE] NewConnection
Rendezvous Initialized
Connected
chip-device-ctrl > CHIP: [BLE] CBManagerState: ON
CHIP: [BLE] Connecting to device with discriminator: 4000
CHIP: [BLE] subscribe complete, ep = 0x1139827c8
CHIP: [BLE] peripheral chose BTP version 3; central expected between 2 and 3
CHIP: [BLE] using BTP fragment sizes rx 20 / tx 128.
CHIP: [BLE] local and remote recv window size = 3
CHIP: [BLE] Sent PBKDF param request
CHIP: [BLE] Received pairing message from 12344321
CHIP: [BLE] Received pairing message for 112233
CHIP: [BLE] Received PBKDF param response
CHIP: [BLE] Sent spake2p msg1
CHIP: [BLE] Received pairing message from 12344321
CHIP: [BLE] Received pairing message for 112233
CHIP: [BLE] Received spake2p msg2
CHIP: [BLE] Sent spake2p msg3
CHIP: [IN] New pairing for device 12344321, key 0!!
CHIP: [CTL] Remote device completed SPAKE2+ handshake

CHIP: [NP] Sending Network Creds. Delegate 0x7ff88706f018

CHIP: [IN] Secure message was encrypted: Msg ID 0
CHIP: [IN] Sending msg from 112233 to 12344321
CHIP: [IN] Sending secure msg on connection specific transport
CHIP: [IN] Secure msg send status 0
CHIP: [NP] Received kIPAddressAssigned
CHIP: [CTL] Remote device was assigned an ip address

CHIP: [CTL] SetKeyValue: PairedDevicebc5c01=EADaL6iAXCRRxRZxAF754NS/AAAAAAAAAAAAAAAAAAAAAAEAAAAAAGm2AQAAAAAAAVy8AAAAAAAAAAAAAAAAAAFcvAAAAAAAMTkyLjE2OC40LjEzNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFkrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CHIP: [CTL] SetKeyValue: ListPairedDevices0=AVy8AAAAAAA=
CHIP: [BLE] Auto-closing end point's BLE connection.

chip-device-ctrl > zcl OnOff Toggle 12344321 1 0
CHIP: [ZCL] Successfully encoded 11 bytes
CHIP: [IN] Connection from 'UNDEFINED' expired
CHIP: [CTL] OnConnectionExpired: Failed to process received message: err 4051
CHIP: [IN] New pairing for device 12344321, key 0!!
CHIP: [IN] Secure message was encrypted: Msg ID 0
CHIP: [IN] Sending msg from 112233 to 12344321
CHIP: [IN] Sending secure msg on generic transport
CHIP: [IN] Secure msg send status 0
CHIP: [CTL] SendMessage returned 0
chip-device-ctrl > help

Available commands (type help <name> for more information):
============================================================
ble-adapter-print   ble-debug-log  close    set-pairing-wifi-credential
ble-adapter-select  ble-scan       connect  zcl                        

chip-device-ctrl > zcl OnOff Toggle 12344321 1 0
CHIP: [ZCL] Successfully encoded 11 bytes
CHIP: [IN] Secure message was encrypted: Msg ID 1
CHIP: [IN] Sending msg from 112233 to 12344321
CHIP: [IN] Sending secure msg on generic transport
CHIP: [IN] Secure msg send status 0
CHIP: [CTL] SendMessage returned 0
chip-device-ctrl > 

---------- Device Logs ---------------

V (97716) chip[IN]: Secure message was encrypted: Msg ID 0
I (97716) chip[IN]: Sending msg from 12344321 to 112233
I (97726) chip[IN]: Sending secure msg on connection specific transport
GATT procedure initiated: notify; att_handle=14
I (97736) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 0) status= 0 
I (97746) chip[IN]: Secure msg send status 0
I (97746) app-devicecallbacks: Server ready at: 192.168.4.134:11097
I (97756) chip[DIS]: CHIP minimal mDNS started advertising.
I (97756) app-devicecallbacks: Current free heap: 128236

I (97766) chip[DL]: IP_EVENT_STA_GOT_IP
I (97776) chip[DL]: IPv4 address changed on WiFi station interface: 192.168.4.134/255.255.252.0 gateway 192.168.4.1
I (97786) app-devicecallbacks: Current free heap: 128252

GATT procedure initiated: notify; att_handle=14
I (97796) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 0) status= 0 
I (97846) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
GATT procedure initiated: notify; att_handle=14
I (97856) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 0) status= 0 
GATT procedure initiated: notify; att_handle=14
I (97866) chip[DL]: Confirm received for CHIPoBLE TX characteristic indication (con 0) status= 0 
I (97956) CHIP[DL]: Write request received for CHIPoBLE RX characteristic con 0 12
I (98046) chip[DL]: Write request/command received for CHIPoBLE TX CCCD characteristic (con 0 ) indicate = 0 notify = 0
I (98046) chip[DL]: CHIPoBLE unsubscribe received
I (98046) chip[SVR]: OnRendezvousError: Ble Error 6000004 (0x005B8D84): BLE central unsubscribed
I (98056) chip[BLE]: Releasing end point's BLE connection back to application.
GAP procedure initiated: stop advertising.
I (98076) chip[DL]: CHIPoBLE advertising stopped
I (98076) app-devicecallbacks: Current free heap: 129828

I (99676) chip[DL]: IP_EVENT_GOT_IP6
I (99676) chip[DL]: IPv6 addr available. Ready on WIFI_STA_DEF interface: fd13:09c4:60e4:0002:266f:28ff:fe8f:d758
I (99676) app-devicecallbacks: Current free heap: 129632

I (136186) chip[SVR]: Packet received from UDP:192.168.4.228:11097: 14 bytes
V (136186) chip[ZCL]: APS frame processing success!
I (136186) chip[ZCL]: RX len 3, ep 1, clus 0x 6 
I (136186) chip[ZCL]:  FC 1 seq 0 cmd 2 payload[
I (136196) chip[ZCL]: NULL
I (136196) chip[ZCL]: ]
I (136206) chip[ZCL]: On/Off set value: 1 2
I (136206) chip[ZCL]: Toggle on/off from 0 to 1
I (136216) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0006', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (136226) app-devicecallbacks: Current free heap: 128428

I (136226) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0008', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (136246) app-devicecallbacks: Unhandled cluster ID: 8
I (136246) app-devicecallbacks: Current free heap: 128428

I (136256) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0005', EndPoint ID: '0x01', Attribute ID: '0x0003'
I (136266) app-devicecallbacks: Unhandled cluster ID: 5
I (136276) app-devicecallbacks: Current free heap: 128428

V (136276) chip[ZCL]: Measured APS frame size 11
V (136286) chip[ZCL]: Successfully encoded 11 bytes
V (136286) chip[IN]: Secure message was encrypted: Msg ID 1
I (136296) chip[IN]: Sending msg from 12344321 to 112233
I (136296) chip[IN]: Sending secure msg on generic transport
I (136306) chip[IN]: Secure msg send status 0
I (136316) chip[ZCL]: T   0:TX (0x3f40bd96) Ucast 0x00x3f400d6f
I (136316) chip[ZCL]: TX buffer: [
I (136326) chip[ZCL]: 08 00 0B 02 00 
I (136326) chip[ZCL]: ]
V (136326) chip[ZCL]: Data model processing success!
E (136336) chip[DL]: Long dispatch time: 154 ms
I (1596406) chip[SVR]: Packet received from UDP:192.168.4.228:11097: 14 bytes
V (1596406) chip[ZCL]: APS frame processing success!
I (1596406) chip[ZCL]: RX len 3, ep 1, clus 0x 6 
I (1596416) chip[ZCL]:  FC 1 seq 1 cmd 2 payload[
I (1596416) chip[ZCL]: NULL
I (1596426) chip[ZCL]: ]
I (1596426) chip[ZCL]: On/Off set value: 1 2
I (1596436) chip[ZCL]: Toggle on/off from 1 to 0
I (1596436) app-devicecallbacks: PostAttributeChangeCallback - Cluster ID: '0x0006', EndPoint ID: '0x01', Attribute ID: '0x0000'
I (1596446) app-devicecallbacks: Current free heap: 128400

**Comment by erjiaqing** [comment]
```
CHIP:BLE: Received spake2p msg3
CHIP:SVR: OnRendezvousStatusUpdate: Error 4172 (0x0000104C)
```

@pan-apple , Hi Pankaj, seems the Linux app failed to finish key exchange, do you have any ideas about how to debug this? Previously, I met this error and it is resolved by removing `/tmp/chip*`, and I believe that is caused by `https://github.com/project-chip/connectedhomeip/issues/4713`.

However, as for this issue, @cjandhyala told me that the /tmp/chip* files are empty, , can you reproduce this error on your side?

**Comment by pan-apple** [comment]
Hi Song, I don't have a Linux setup to reproduce it on my end. Let me check with @cjandhyala and see if we can get more debug information to narrow down the issue.

**Comment by cjandhyala** [comment]
Issue is not reproduced after updating the code to the latest.
