### ISSUE TITLE
BLE rendezvous advertisement cannot be configured with a temporary discriminator 

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#4767]
#### Problem
BLE reads the discriminator from the ConfigurationMgr(), which is backed by persistent storage. For multi-admin use cases, the pairing window could use a temporary discriminator. But the current implementation requires the discriminator to be updated in the persistent storage. If the device crashes/reboots in the middle of pairing process, the original discriminator (set up the manufacturer) may be lost forever.
 
 #### Proposed Solution
Add a mechanism to pass discriminator the BLE without persisting it in storage.

**Comment by andy31415** [comment]
looks critical - this is an API design issue: we should not attempt to try to overwrite any written discriminators. Factory data is actually expected to be read-only: I should not be able to overwrite serial, PKBDF data, discriminators etc.
