### ISSUE TITLE
EFR32: Update OpenThread stack

### ISSUE THREAD

**Issue by doru91** [project-chip/connectedhomeip#4818]
#### Problem
If OpenThread stack is updated to the latest master then EFR32 Demo App stops compiling.

NXP needs a more recent OpenThread stack where some vendor specific fixes were added.

 #### Proposed Solution
Please update EFR32 implementation to the latest OT master. @jepenven-silabs

**Comment by jepenven-silabs** [comment]
Duplicate of #4527
