### ISSUE TITLE
raspi: Network Provisioning step Failed in sending Network Creds

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#4823]
Python Controller side logs
========================
CHIP:IN: New pairing for device 12344321, key 0!!
CHIP:CTL: Remote device completed SPAKE2+ handshake

CHIP:NP: Sending Network Creds. Delegate 0x19cf7c8

CHIP:NP: Failed in sending Network Creds. error Error 4047 (0x00000FCF)

Device side (Lightining App) logs
==========================

CHIP:BLE: Received spake2p msg3
CHIP:IN: New pairing for device 112233, key 0!!
CHIP:SVR: Received a new connection.
CHIP:SVR: Device completed SPAKE2+ handshake
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffa80257c0
CHIP:BLE: Indication confirmation, 0xffffa80257c0

**Comment by austinh0** [comment]
I ran into this error as well - from RendezvousSession.SendSecureMessage() -> SecureSessionMgr.SendMessage() -> SecureMessageCodec.Encode() -> MessageAuthenticationCode.Encode()

In MessageHeader.cpp line 371: 
`VerifyOrExit(size >= taglen, err = CHIP_ERROR_INVALID_ARGUMENT);`
size is 0.
