### ISSUE TITLE
mDNS appears broken on ESP32 after #4132

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#4853]
#### Problem

I'm not seeing any mDNS advertisements after #4132

Repro:

Run `dns-sd -B _chip._tcp`
Provision ESP32

Expected output:

mDNS "Add" reported once ESP32 joins network

Actual output:

Nothing

**Comment by andy31415** [comment]
minmdns implementation does not yet implement advertisements at startup (does not auto-broadcast its services). I assume the esp32-native library was doing it.

**Comment by mspang** [comment]
Linux version doesn't seem to work either:
avahi-browse -r _chip._tcp
