### ISSUE TITLE
Can the specifications be added to the docs/ area?

### ISSUE THREAD

**Issue by Ml0** [project-chip/connectedhomeip#4855]
In order to work with this code, knowledge of the specifications is critical in my opinion.
Looking in the repository and searching for issues with the word `specification` in it, I found nothing.

Can it be explained how to be effective within this initiative and how to obtain the specifications?

Thanks in Advance!

**Comment by HomeACcessoryKid** [comment]
I found that the specifications are on a CLOSED GitHub account called https://github.com/CHIP-Specifications
Why does 'Matter'='CHIP' claim to be open-source if the specs are not public?
Can this account or at least the specifications part be opened up to everyone?

TIA
