### ISSUE TITLE
Need to sort out what happens with TCP if the upper layers decide to reuse the buffer they receive to do a send

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#4869]
#### Problem
The way our TCP implementation works is that it has a packet buffer chain, compacts things into the first buffer in the chain (sometimes), and then passes that first buffer in the chain to upper layers, after retaining it.

When upper layers return, it then updates the state of that buffer to indicate that some data got read from it.

This can fail if upper layers decide to reuse the packet buffer they received to send something.  If they do that, they might stomp on state that is not theirs (the bytes in the buffer which are part of the next message) and then TCP will also stomp on state that is not its (the `DataLength()` of the buffer after unwinding). 

 #### Proposed Solution
It seems like we have a few options:

1. Forbid upper layers from modifying the bytes of the packetbuffer.  This prevents in-place decryption and such.  Note that if there are other things upper layers want to do that are not same-size (like in-place decryption is), that could be a problem even if they are not reusing the buffer for sending.
2. Change TCP to ensure that it never has bytes from more than one message in a given packetbuffer in its queue.  That means not using `CompactHead`, but that might not be enough if a packet can come off the wire with pieces of multiple messages in it...
3. Check whether there is anything else in our buffer when pulling things out of the TCP queue, and actually copy, not just retain, as needed.  This might be done in tandem with some attempt to do item 2, so we'll mostly avoid having multiple messages in a buffer and copy when we can't avoid it.
4. Do nothing, document the heck out of what consumers are allowed to do with the incoming message buffer.  This is my least-favorite option, because it's too easy to screw this up as a consumer.

Other ideas?  

@andy31415 @pan-apple @kpschoedel

**Comment by kpschoedel** [comment]
Fixed by #5265 (commit 4eb50c2b) — upper layers get sole ownership.
