### ISSUE TITLE
CHIP Framework: Add FeatureMap property to the clusters

### ISSUE THREAD

**Issue by lazarkov** [project-chip/connectedhomeip#4876]
#### Problem
We need feature map as part of cluster code. It's defined in almost all of the clusters that will be implemented.

 #### Proposed Solution
FeatureMap Attribute is defined in the [spec](https://github.com/project-chip/connectedhomeip-spec/blob/master/src/data_model/Data-Model.adoc#featuremap-attribute).

**Comment by tcarmelveilleux** [comment]
AFAIK this is done. @mrjerryjohns to confirm/close

**Comment by mrjerryjohns** [comment]
Yes, done.
