### ISSUE TITLE
Pass in only PeerAddress for pairing (not remote port and interface id)

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#4926]
#### Problem
PeerAddress contains remote port and interface if the transport is TCP or UDP.
If PeerAddress is BLE, remote port and interfaces ahave no meaning.

`chip::Device::Init` that is used for pairing (or alternatively  `DeviceCommissioner::PairDevice`) should use the PeerAddress settings to setup configuration of port/interface (if available). It should also accept that remote node ports may not be available if BLE is used (since device is not on the network yet).

 #### Proposed Solution
Remove remotePort and remoteInterfaceId parameters.

**Comment by woody-apple** [comment]
This appears resolved
