### ISSUE TITLE
crash in GetBluezConnectionViaDevice

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#4962]
Was trying to provision examples/lighting-app/linux via chip-tool over BLE and saw a crash:

Thread 4 "chip-tool-serve" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xfffff5ed7fc0 (LWP 4064)]
0x0000fffff78f32b0 in g_str_hash () from /lib/aarch64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x0000fffff78f32b0 in g_str_hash () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#1  0x0000fffff78f1a4c in g_hash_table_lookup () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#2  0x0000aaaaaaadc928 in chip::DeviceLayer::Internal::GetBluezConnectionViaDevice(chip::DeviceLayer::Internal::BluezEndpoint*) (apEndpoint=0xaaaaaabae320) at ../../third_party/connectedhomeip/src/platform/Linux/bluez/Helper.cpp:1131
#3  0x0000aaaaaaadaad4 in chip::DeviceLayer::Internal::BluezCharacteristicAcquireWrite(BluezGattCharacteristic1*, GDBusMethodInvocation*, GVariant*, gpointer)
    (aChar=0xffffe0004370, aInvocation=0xffffe002ab10, aOptions=0xffffe801c470, apEndpoint=0xaaaaaabae320) at ../../third_party/connectedhomeip/src/platform/Linux/bluez/Helper.cpp:482
#4  0x0000fffff7359148 in  () at /lib/aarch64-linux-gnu/libffi.so.8
#5  0x0000fffff7358748 in  () at /lib/aarch64-linux-gnu/libffi.so.8
#6  0x0000fffff7a0ba50 in g_cclosure_marshal_generic () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#7  0x0000fffff7a0b058 in g_closure_invoke () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#8  0x0000fffff7a1fc74 in  () at /lib/aarch64-linux-gnu/libgobject-2.0.so.0
#9  0x0000aaaaaab10db0 in _bluez_gatt_characteristic1_skeleton_handle_method_call
    (connection=0xaaaaaaba0040, sender=0xffffe8006dc0 ":1.11", object_path=0xffffe8010130 "/chipoble/0fdb/service/c1", interface_name=0xffffec009a50 "org.bluez.GattCharacteristic1", method_name=0xffffe8010030 "AcquireWrite", parameters=0xffffe801c440, invocation=0xffffe002ab10, user_data=0xffffe0004370) at gen/platform/Linux/dbus/bluez/DbusBluez.c:12258
#10 0x0000fffff7b9f0e8 in  () at /lib/aarch64-linux-gnu/libgio-2.0.so.0
#11 0x0000fffff7b83704 in  () at /lib/aarch64-linux-gnu/libgio-2.0.so.0
#12 0x0000fffff79059f0 in g_main_context_dispatch () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#13 0x0000fffff7905d98 in  () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#14 0x0000fffff79060f0 in g_main_loop_run () at /lib/aarch64-linux-gnu/libglib-2.0.so.0
#15 0x0000aaaaaaad6ae4 in chip::DeviceLayer::GDBus_Thread() () at ../../third_party/connectedhomeip/src/platform/Linux/PlatformManagerImpl.cpp:45
#16 0x0000aaaaaaad8eb8 in std::__invoke_impl<void, void (*)()>(std::__invoke_other, void (*&&)()) (__f=@0xffffe8006cd8: 0xaaaaaaad6ac4 <chip::DeviceLayer::GDBus_Thread()>) at /usr/include/c++/10/bits/invoke.h:60
#17 0x0000aaaaaaad8e44 in std::__invoke<void (*)()>(void (*&&)()) (__fn=@0xffffe8006cd8: 0xaaaaaaad6ac4 <chip::DeviceLayer::GDBus_Thread()>) at /usr/include/c++/10/bits/invoke.h:95
#18 0x0000aaaaaaad8de0 in std::thread::_Invoker<std::tuple<void (*)()> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xffffe8006cd8) at /usr/include/c++/10/thread:264
#19 0x0000aaaaaaad8db4 in std::thread::_Invoker<std::tuple<void (*)()> >::operator()() (this=0xffffe8006cd8) at /usr/include/c++/10/thread:271
#20 0x0000aaaaaaad8d94 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)()> > >::_M_run() (this=0xffffe8006cd0) at /usr/include/c++/10/thread:215
#21 0x0000fffff7797e1c in  () at /lib/aarch64-linux-gnu/libstdc++.so.6
#22 0x0000fffff7fa1f74 in start_thread (arg=0x0) at pthread_create.c:463
#23 0x0000fffff76283dc in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
