### ISSUE TITLE
Chip fail to compile in macbook

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#4986]
#### Problem
./gn_build.sh

it generate the error introduced from https://github.com/project-chip/connectedhomeip/commit/1a78a5f67de897673058b70604e69598dd9e58e2

Undefined symbols for architecture x86_64:
  "emberAfOnOffClusterOffWithEffectCallback(unsigned char, unsigned char)", referenced from:
      emberAfOnOffClusterServerCommandParse(EmberAfClusterCommand*) in bridge-common.call-command-handler.cpp.o
  "emberAfOnOffClusterOnWithRecallGlobalSceneCallback()", referenced from:
      emberAfOnOffClusterServerCommandParse(EmberAfClusterCommand*) in bridge-common.call-command-handler.cpp.o
  "emberAfOnOffClusterOnWithTimedOffCallback(unsigned char, unsigned short, unsigned short)", referenced from:
      emberAfOnOffClusterServerCommandParse(EmberAfClusterCommand*) in bridge-common.call-command-handler.cpp.o

**Comment by erjiaqing** [comment]
Seems it can build after c486c91b98b16d5c990b4c0a7ee0a648c0151999
