### ISSUE TITLE
Investigate how to make chip over bluez connection without disabling bredr or with LE only mode from code

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#5010]
#### Problem
Currently for raspberry pi4, when we do chip over ble connection between raspis, we need to disable bredr.

As described https://github.com/nexussays/ble.net/issues/4 
: raspberry pi has a dual mode bluetooth chip. Glinux or android phone by default tries to connect using a classic mode(BREDR). 

Therefore we must disable bredr in /etc/bluetooth/main.conf or use btmgmt to disable bredr. 

We will need to figure out the better way to fix this issue.

**Comment by mspang** [comment]
This also happens for linux -> linux, not just Android.
