### ISSUE TITLE
The "BLE recv ack timeout" error will be occured on M5Stack device after sending ip address to Android chip-tool

### ISSUE THREAD

**Issue by Hugh-Bao** [project-chip/connectedhomeip#5036]
#### Problem
expected behavior : 
Clicked the save button for sending "ssid" & "password" on Anrdoid chip-tool, the M5Stack device received that two parameters and entered into the process of network provisioing, if the process was executed successfully, then sending ip address to Anroid chip-tool, the BTP transaction should be OK.

actual behavior:
The "BLE recv ack time" error was occured on M5Stack device after sending ip address to Android chip-tool

analysis:
If send "ssid" & "pwd" directly after PASE established without sendig them via "SAVE" button on the network credential dialog on Android chip-tool, the error that mentioned will not be occured.

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
