### ISSUE TITLE
esp-idf platform mDNS implementation fails at initialization

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#5076]
As of 27d3ea89f ("Make CHIP devices advertise as operational devices via mDNS (#4132)") we cannot use the esp-idf mDNS implementation.

This should be possible after 2c820d0f6 ("Add platform implementation for Advertiser (#4345)") but this is not working as there is an error at initialization:

```
E (677) chip[DL]: esp mdns internal error: ESP_ERR_INVALID_STATE
E (678) chip[DIS]: mDNS initialization failed with Error 4000172 (0x003D09AC)
E (681) chip[DIS]: Failed to initialize platform mdns: Error 4000172 (0x003D09AC)
I (690) spi_flash: detected chip: gd
```

Repro: Set chip_mdns_advertiser = "platform" and chip_enable_rotating_device_id = false for ESP32 build. Error shows at boot and the device cannot be discovered.

**Comment by gjc13** [comment]
Ack, will investigate.
