### ISSUE TITLE
[efr32] Typo in file name in BUILD.gn

### ISSUE THREAD

**Issue by thcu-gp** [project-chip/connectedhomeip#5107]
Typo in filename, 
`PigWeedLoggerMutex.cpp -> PigweedLoggerMutex.cpp`
no capital `w`
 
https://github.com/project-chip/connectedhomeip/blob/070a49ae2fa1b9f4b4a3448178bfba047b6035d6/examples/pigweed-app/efr32/BUILD.gn#L102

**Comment by jmartinez-silabs** [comment]
This issue can be close. the Typo go fix in the mentioned PR above (#5115)
