### ISSUE TITLE
Adding Discovery capability to the platform abstraction layer

### ISSUE THREAD

**Issue by hnnajh** [project-chip/connectedhomeip#5110]
#### Problem
Currently it's the responsibility of the commissioner to implement the discovery logic outside the SDK, and then integrate the data returned to feed the SDK to complete the provisioning flow.

 #### Proposed Solution
It would be better to have the discovery as part of the provisioning flow for all platforms and expose a hardware abstraction layer to implement the discovery APIs. this will enable the commissioner to use the CHIP SDK for all the provisioning steps.

```
adapter = chip.GetBleAdapters()[0]                                # I am feeling lucky
device = adapter.Discover(timeout_sec = 10, vendor_id = 123)[0]   # still assume lucky
connection = device.Connect()
connection.Pair(bytearray([1,2,3,4]), num_bits=27)
network = connection.FindClusters(chip.clusters.NETWORK_PROVISIONING)[0]
network.ConnectToWifi('ssid', 'password')
```

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
