### ISSUE TITLE
mbedTLS error

### ISSUE THREAD

**Issue by silabs-NikhilS** [project-chip/connectedhomeip#5226]
#### Problem
Hello,

I am using EFR32 on BRD4170A dev board to create a CHIP demo. I am running the CHIP lighting app on two BRD4170As. I can provision the devices on the therad network over BLE using the CHIPtool android app. This process goes through successfully for both the devices. And I can send on/off commands from the android app to toggle the LED on the WSTK as expected.

I have two issues after that -
1. After provisioning the device2, I can no longer communicate with the device1 from the app. When I enter the IP address of device1, the command is executed on device2. Infact it doesn't matter what I put as the ip address textbox, the on-off command only goes device2. 
2. When I close the android app and reopen it again, I cannot send the command to either of the devices. I can see "mbedTLS error:" in the RTT log.

00> [DL] Thread packet RCVD: UDP, len 108
00> [DL]     src  FD11:33::F19B:BD6E:3520:B2BF, port 11097
00> [DL]     dest FD11:22::A001:BC9E:76D5:EEE7, port 11097
00> [CR] mbedTLS error: 
00> 

To be able to communicate with the nodes again, I have to factory reset the nodes and re-provisioning them via the app.

Is this a expected behavior? Is there a way I can communicate with multiple nodes without having to re-provisioning them?

Thanks
Nik

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
