### ISSUE TITLE
DeviceCommissioner pairs one device at a time

### ISSUE THREAD

**Issue by hnnajh** [project-chip/connectedhomeip#5252]
#### Problem
The current structure and callbacks supported in DeviceCommissioner, does not specify which device had errors or got paired? and it does not enable the caller/consumer to specify a context object to differentiate/group callbacks per device

Example:
```
class DLL_EXPORT DevicePairingDelegate
{
public:
    virtual ~DevicePairingDelegate() {}
    virtual void OnStatusUpdate(RendezvousSessionDelegate::Status status) {}
    virtual void OnNetworkCredentialsRequested(RendezvousDeviceCredentialsDelegate * callback) = 0;
    virtual void OnOperationalCredentialsRequested(const char * csr, size_t csr_length,
                                                   RendezvousDeviceCredentialsDelegate * callback) = 0;
    virtual void OnPairingComplete(CHIP_ERROR error) {}
    virtual void OnPairingDeleted(CHIP_ERROR error) {}
};
```

 #### Proposed Solution
Callbacks should contain either remote node id or context object to differentiate between callbacks for each CHIP node (being paired).

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
