### ISSUE TITLE
[Darwin] CHIPFramework's stopDevicePairing and unpairDevice APIs don't work as expected

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#5272]
#### Problem
CHIPFramework's `stopDevicePairing` and `unpairDevice` APIs don't trigger the pairingComplete callback if pairing is in progress. 

 #### Proposed Solution
Fix behavior to match documentation or change documentation.

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
