### ISSUE TITLE
Nordic thread accessory can't decrypt CHIP messages sent over UDP

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#5273]
Nordic thread accessory can't decrypt CHIP messages sent over UDP. This issue was fixed in master https://github.com/project-chip/connectedhomeip/issues/5016 branch before, it seems regression again. 

Accessory log
-------------

D: 29307 [DL]Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 29315 [DL]Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 29322 [DL]Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 29403 [DL]Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 29410 [DL]Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 29505 [DL]Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 29512 [DL]Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 29520 [DL]Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 29600 [DL]Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 29608 [DL]Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 8)
D: 29696 [DL]Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 29704 [DL]Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 29711 [DL]Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 29792 [DL]Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 29800 [DL]Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 29894 [DL]Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
I: 31548 [DL]BLE GAP connection terminated (reason 0x13)
I: 31557 [DL]Current number of connections: 0/1
D: 31561 [DL]In DriveBLEState
I: 31572 [DL]CHIPoBLE advertising started
E: 41773 [CR]mbedTLS error: 

E: 44718 [BLE]ack recv timeout, closing ep 0x20006378
D: 44723 [DL]SetAdvertisingEnabled(false)
I: 44727 [SVR]Persisting admin ID 0, next available 1
I: 44964 [SVR]Persisting admin ID successfully
I: 44968 [SVR]OnRendezvousError: Ble Error 6024 (0x00001788): Message fragment acknowlt
I: 44977 [BLE]Releasing end point's BLE connection back to application.
D: 44984 [DL]In DriveBLEState
I: 44987 [DL]CHIPoBLE advertising stopped
E: 49648 [CR]mbedTLS error: 

E: 63034 [CR]mbedTLS error: 

CTRL-A Z for help | 115200 8N1 | NOR | Minicom 2.8 | VT102 | Offline | em0006830147531

Controller side log
------------------
$ chip-device-ctrl 
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 18446743528248704968

CHIP:DL: CHIP task running
Chip Device Controller Shell

chip-device-ctrl > set-pairing-thread-credential 11 abcd 00112233445566778899aabbccddeeff
Thread credential set
chip-device-ctrl > connect -ble 3000 12345678 12344321
Device is assigned with nodeid = 12344321
CHIP:DL: TRACE: Bluez mainloop starting Thread
CHIP:DL: TRACE: Bus acquired for name C-9b95
CHIP:DL: PlatformBlueZInit init success
CHIP:BLE: BLE scanning through known devices.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: Device FB:67:AC:AE:05:8A does not look like a CHIP device.
CHIP:BLE: Device 5C:BC:48:E6:B1:48 does not look like a CHIP device.
CHIP:BLE: Device 62:D7:84:68:52:36 does not look like a CHIP device.
CHIP:BLE: Device F3:33:19:1E:96:07 does not look like a CHIP device.
CHIP:BLE: Device 7B:B8:07:F9:B2:DE does not look like a CHIP device.
CHIP:BLE: Device 08:66:98:91:66:E3 does not look like a CHIP device.
CHIP:BLE: Device 1A:F9:BD:D6:E1:4D does not look like a CHIP device.
CHIP:BLE: Device 23:28:86:6C:FF:CD does not look like a CHIP device.
CHIP:BLE: Device 5B:AB:AA:17:D1:6D does not look like a CHIP device.
CHIP:BLE: Device 4F:DA:BD:10:3A:10 does not look like a CHIP device.
CHIP:BLE: Device 26:60:01:44:98:5F does not look like a CHIP device.
CHIP:BLE: Device 48:40:A4:D7:00:33 does not look like a CHIP device.
CHIP:BLE: Device 7E:9D:1C:96:53:FE does not look like a CHIP device.
CHIP:BLE: New device scanned: C2:02:86:8F:C5:29
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Scan complete notification without an active scan.
CHIP:DL: ConnectDevice complete
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0007
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: Char1 /org/bluez/hci0/dev_C2_02_86_8F_C5_29/service0001
CHIP:DL: New BLE connection 0xffff7404e040, device C2:02:86:8F:C5:29, path /org/bluez/hci0/dev_C2_02_86_8F_C5_29
CHIP:DL: HandlePlatformSpecificBLEEvent 16385
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:BLE: subscribe complete, ep = 0xffff7e7e2b40
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:BLE: peripheral chose BTP version 3; central expected between 2 and 3
CHIP:BLE: using BTP fragment sizes rx 20 / tx 20.
CHIP:BLE: local and remote recv window size = 3
CHIP:BLE: Sent PBKDF param request
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:BLE: Received PBKDF param response
CHIP:BLE: Sent spake2p msg1
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:BLE: Received spake2p msg2
CHIP:BLE: Sent spake2p msg3
CHIP:IN: New pairing for device 12344321, key 0!!
CHIP:CTL: Remote device completed SPAKE2+ handshake

CHIP:NP: Sending Thread Credentials
CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 18446743528248704968 to 12344321
CHIP:IN: Sending secure msg on connection specific transport
CHIP:IN: Secure msg send status 0
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:DL: Indication received, conn = 0xffff7404e040
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:NP: Received kIPAddressAssigned
CHIP:CTL: Remote device was assigned an ip address

CHIP:CTL: SetKeyValue: PairedDevicebc5c01=EAB6ZTNdJbgZ+MIDpngQVPmTAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAFcvAAAAAAAZmQzMToyOTZlOjI4MGI6MDo0YjQwOjI1ZDpiZjI4OjZkM2MAAAAAAAAAAAAAAFkrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Secure Session to Device Established
CHIP:CTL: SetKeyValue: ListPairedDevices0=AVy8AAAAAAA=
Device temporary node id (**this does not match spec**): 12344321
chip-device-ctrl > CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:BLE: Auto-closing end point's BLE connection.
CHIP:DL: Closing BLE GATT connection (con 0xffff7404e040)
CHIP:DL: BluezDisconnect peer=C2:02:86:8F:C5:29
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:BLE: no endpoint for BLE sent data ack
CHIP:DL: Bluez disconnected
CHIP:DL: Bluez notify CHIPoBluez connection disconnected

chip-device-ctrl > zcl OnOff Toggle 12344321 1 0
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Connection from 'UNDEFINED' expired
CHIP:CTL: OnConnectionExpired: Failed to process received message: err 4051
CHIP:IN: New pairing for device 12344321, key 0!!
CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 18446743528248704968 to 12344321
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:CTL: SendMessage returned 0
chip-device-ctrl > zcl OnOff Toggle 12344321 1 0
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 1
CHIP:IN: Sending msg from 18446743528248704968 to 12344321
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:CTL: SendMessage returned 0
chip-device-ctrl > zcl OnOff Toggle 12344321 1 0
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 2
CHIP:IN: Sending msg from 18446743528248704968 to 12344321
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:CTL: SendMessage returned 0
chip-device-ctrl >

**Comment by franck-apple** [comment]
CSG validated that this is needed in the TE1 branch

**Comment by andy31415** [comment]
I replaced the label  of cherrypick to just TE1 - I need cherrypick to only apply to PRs (so that I have a commit to cherrypick)

**Comment by Damian-Nordic** [comment]
This has been fixed, but the issue hasn't been closed. Closing it now.
