### ISSUE TITLE
Add Color control to Light application

### ISSUE THREAD

**Issue by tima-q** [project-chip/connectedhomeip#5313]
Problem:
Current light example only shows a dimmable light.
QPG6100 DK board also has a RGB Led for demonstration of a color light

Solution
- add Color control cluster
-- would require zap regeneration of the app's clusters ?
- enable control to QPG6100 DK HW

**Comment by mspang** [comment]
@tima-q Are you taking this on?

@kpschoedel

**Comment by tima-q** [comment]
> @tima-q Are you taking this on?
> 
> @kpschoedel

@mspang This is in our planning yes - some alignment might be required between the other lighting-app implementers as I assume this will affect them as well
