### ISSUE TITLE
Create a stable (synchronous only) persistent storage interface.

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#5349]
#### Problem
Existing persistent storage implementation provides both synchronous and asynchronous APIs.

However actual implementations either implement one side or the other (either sync or async) and usage is not as clear.

 #### Proposed Solution
 
Standardize on a single persistent storage implementation. Synchronous operation seems the easiest to reason about and directly maps to KVS, so that approach can be used.

**Comment by andy31415** [comment]
Generally KeyValueStoreManager should be usable across the board EXCEPT likely Android and iOS do not provide KVS.

@rgoliver - is this accurate? Could we have android/iOS/other implementations? Trying to figure out how sane the idea of 'use KVS everywhere' is vs needing one level of indirection to switch between kvs and non-kvs platforms.

**Comment by rgoliver** [comment]
I don't know of any technical limitation which would stop KVS being implemented on Android or iOS.
