### ISSUE TITLE
Document CommandHandler API and fix leaks.

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5352]
#### Problem
`app::CommandHandler::OnMessageReceived` sometimes calls `Shutdown()` and sometimes not.  The behavior is not documented, so consumers have no way to tell whether it did or not, based on the API.  Not calling `Shutdown()` results in a leak.

 #### Proposed Solution
Document the API semantics clearly, then ensure that consumers use it properly, so we don't end up leaking.

**Comment by bzbarsky-apple** [comment]
@yunhanw-google

**Comment by yunhanw-google** [comment]
obsolote
