### ISSUE TITLE
Cleanup OnMessageReceived in im Command handler

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#5374]
Why are we ignoring the return value from OnMessageReceived?

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/5198#discussion_r593463468_

**Comment by bzbarsky-apple** [comment]
This is fixed now: CommandHandler::OnInvokeCommandRequest is called for an initial invoke, and handles its own failures, and CommandHandler::OnMessageReceived sends a status response.
