### ISSUE TITLE
evaluate if use the existing reader to save stack depth.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#5377]
So this assumes nothing will need to use the reader after this point, right?

This seems really fragile.  I'd prefer we use a new reader and file a followup issue to re-evaluate once this code is more fleshed-out and stable whether reuse makes sense then.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/5198#discussion_r593485988_

**Comment by bzbarsky-apple** [comment]
This is probably fine now: the two readers are never on-stack at the same time, so the compiler can reuse the stack itself.
