### ISSUE TITLE
Docker builds are slow

### ISSUE THREAD

**Issue by bhaskar-apple** [project-chip/connectedhomeip#540]
#### Problem
Docker builds are slow. Takes upwards of 10 or more mins. This is about 5x less if built directly on the same Mac. 
Need to investigate what’s different. Seems like a recent regression.

**Comment by bhaskar-apple** [comment]
I do not think this is an issue anymore.

**Comment by bzbarsky-apple** [comment]
It's still an issue; it's just that builds are so much faster in general that the docker slowdown is not as painful....
