### ISSUE TITLE
Unencypted message  is dropped since no corresponding handler is set in TransportMgr

### ISSUE THREAD

**Issue by 362dyx** [project-chip/connectedhomeip#5409]
hi
I use the two following command on chip-device-ctrl :
chip-device-ctrl > connect -ip  FDB4:EE6:53CC:39C0:5CDF:AD7b:9F6d:DF73 11097
When using Python conntroller to drive lighting-app i have the following log on RTT viewer:

<efr32 > Current Firmware Version: 0.1ALPHA
00> <inf<detail> [DL] Thread packet RCVD: UDP, len 110
00> <detail> [DL]     src  FDB4:EE6:53CC:39C0:0:FF:FE00:4C00, port 11097
00> <detail> [DL]     dest FDB4:EE6:53CC:39C0:3D86:7A5E:543F:F495, port 11097
00> <error > [IN] Unencrypted message from UDP:FDB4:EE6:53CC:39C0:0:FF:FE00:4C00:11097 is dropped since no corresponding handler is set in TransportMgr.

Why does such an error occur？how to solve this problem！

**Comment by woody-apple** [comment]
Is this resolved? Please reopen if not.
