### ISSUE TITLE
Support for acceptance of device's leaf certificate with multiple OID items in the Subject field

### ISSUE THREAD

**Issue by bitkis** [project-chip/connectedhomeip#5410]
#### Problem
Currently CHIP code does not accept device's leaf certificate with multiple OID items in the Subject field.

 #### Proposed Solution
Add support for DNs containing multiple RDNs, and multiple attributes per RDN (touches to both `ChipND` class and `DecodeConvertDN()` function.)

**Comment by bzbarsky-apple** [comment]
@bitkis @emargolis Is this still an issue?

**Comment by emargolis** [comment]
I believe this shouldn't be an issue. CHIP Certificate code supports up to 5 RNDs in the subject/issuer DN and about 20 different attribute types.

**Comment by woody-apple** [comment]
Issue Review: Closing based on @emargolis's feedback.
