### ISSUE TITLE
TLV-based command decoders do terrible things on decoding errors

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5432]
#### Problem
The typical logic for IMClusterCommandHandler.cpp handling of a command looks like this (using a command with one argument to make it clear, but this happens with multiple args too):

```
            CHIP_ERROR TLVError = CHIP_NO_ERROR;
            const uint8_t * PIN;

            while ((TLVError = dataTlv.Next()) == CHIP_NO_ERROR)
            {
                switch (TLV::TagNumFromTag(dataTlv.GetTag()))
                {
                case 0:
                    TLVError = dataTlv.GetDataPtr(PIN);
                    break;
                default:
                    // Unsupported tag, ignore it.
                    ChipLogProgress(Zcl, "Unknown TLV tag during processing.");
                    break;
                }
                if (TLVError != CHIP_NO_ERROR)
                {
                    ChipLogProgress(Zcl, "Failed to decode TLV data with tag %" PRIx32 ": %" PRId32,
                                    TLV::TagNumFromTag(dataTlv.GetTag()), TLVError);
                }
            }
            // TODO(#5098) We should pass the Command Object and EndpointId to the cluster callbacks.
            emberAfDoorLockClusterLockDoorCallback(const_cast<uint8_t *>(PIN));
```

What happens if there is an error in any of the TLV stuff?  We will happily call `emberAfDoorLockClusterLockDoorCallback` with an uninitialized pointer. 

 #### Proposed Solution
Actually do something useful if the TLV calls fail that does NOT involve calling the callback.

@erjiaqing @vivien-apple

**Comment by erjiaqing** [comment]
Thanks for catching this miss, PR for fixing this submitted.

BTW, another issue is we did not check if all argument are present in the TLV, this is also fixed in the PR.
