### ISSUE TITLE
Evaluate if memory pool is suitable fo IM's client and handler

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#5440]
It appears this caps the number of concurrent reads to 1.  Setting to something like #CHIP_CONFIG_MAX_DEVICE_ADMINS would seem a lot safer.

I suppose this can work if all reads are completely synchronous.  But I'm concerned that this will show an artificially small memory footprint for this feature, when in production we may need much more.

If we are finding that we need a lot of some class of object, have we considered a memory pool as we have for pbufs?  Obviously this is more complex to implement for objects, but it's still possible.  It seems like the interaction model may create a need for many concurrent interactions, but yet it may be difficult to predict how many of each type would be needed.

_Originally posted by @msandstedt in https://github.com/project-chip/connectedhomeip/pull/5198#discussion_r596098071_

**Comment by bzbarsky-apple** [comment]
@yunhanw-google Is there anything to be done here now?  Clients are no longer pool-allocated, and handlers use the minima defined in the spec.
