### ISSUE TITLE
Logic error for the calling of  "N2J_ByteArray" in "OnOperationalCredentialsRequested" and "OnOperationalCredentialsResponsed"

### ISSUE THREAD

**Issue by Hugh-Bao** [project-chip/connectedhomeip#5449]
#### Problem
`
{
    ... ...
    if (_!N2J_ByteArray_(env, reinterpret_cast<const uint8_t *>(csr), csr_length, jCsr))
    {
        ChipLogError(Controller, "Failed to build byte array for operational credential request");
        return;
    }
   ... ...
  }`

 #### Proposed Solution
`
{
    ... ...
    if (_N2J_ByteArray_(env, reinterpret_cast<const uint8_t *>(csr), csr_length, jCsr))
    {
        ChipLogError(Controller, "Failed to build byte array for operational credential request");
        return;
    }
   ... ...
}`

The return value of N2J_ByteArray is 0 represents no error return, otherwise represents error return.

**Comment by woody-apple** [comment]
Given this is an old issue, is this still present? If so, please re-open, thanks!
