### ISSUE TITLE
Helper /Utility Library for self Signed Certificate generation

### ISSUE THREAD

**Issue by saurabhst** [project-chip/connectedhomeip#5466]
#### Problem
Currently the CHIP-SDK does not have any helper /utility library for self signed certificate generation by the commissioner for the devices.

 #### Proposed Solution
Add helper/utility library for self signed certificate generation

**Comment by emargolis** [comment]
This has been addressed in the SDK.

The `NewRootX509Cert()`, `NewICAX509Cert()`, and `NewNodeOperationalX509Cert()` methods can be used to generate Operational Root, ICA, and Node certificates.

This can be closed.
