### ISSUE TITLE
TestExchangeMgr.cpp: use enums for ProtocolID and MessageType test values

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#5467]
#### Problem
[TestExchangeMgr.cpp](https://github.com/project-chip/connectedhomeip/blob/master/src/messaging/tests/TestExchangeMgr.cpp) is using hard-coded values for protocol ID and MessageType values. Example:
```
    err = ctx.GetExchangeManager().RegisterUnsolicitedMessageHandlerForType(0x0002, 0x0001, &mockAppDelegate);
    NL_TEST_ASSERT(inSuite, err == CHIP_NO_ERROR);
```

 #### Proposed Solution
Use the enum values provided by `src/protocols/Protocols.h` and `src/protocols/secure_channel/Constants.h`

**Comment by yufengwangca** [comment]
This issue is obsolete, all hard coded protocol ID or MessageType have been already replaced.
