### ISSUE TITLE
Sort out handling of protocol id

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5468]
#### Problem
We currently have multiple representations of a protocol id in our code:

1. PayloadHeader represents it as a pair: `(Optional<uint16_t>, uint16_t)` (vendor id and protocol id).
2. Various code represents it as `uint32_t`
3. Protocols.h represents it as an untyped enum which contains both `0` and ... whatever `kProtocol_NotSpecified` ends up being.  Over here it ends up being an `int32_t` with the value -1.
4. Some code just has a single `uint16_t` for the protocol id.

 #### Proposed Solution
Introduce a `chip::Protocols::Id` type: a struct containing a `uint32_t`.   Have some constexpr values of this type representing built-in protocols (including `kProtocol_NotSpecified`).  Have a constructor that takes 16-bit vendor id and 16-bit protocol id.  Change the API of PayloadHeader to accept this type and convert it into its internal representation under the hood; same for returning the protocol id from `PayloadHeader`.

See what, if anything, is still broken at that point.

**Comment by holbrookt** [comment]
Noting here that the incoming StatusReport class should also incorporate the proposed solution.
