### ISSUE TITLE
C++11 concurrency constructs are not supported on Nordic platform

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#5496]
#### Problem

C++14 is enabled for Nordic board, CONFIG_STD_CPP14=y, but compiler are complaining some basic concurrency constructs are not available as I try to build nrfconnect. 

/var/chip/examples/shell/shell_common/cmd_ping.cpp:143:6: error: 'condition_variable' in namespace 'std' does not name a type
143 | std::condition_variable gCond;
| ^~~~~~~~~~~~~~~~~~
/var/chip/examples/shell/shell_common/cmd_ping.cpp:248:10: error: 'mutex' is not a member of 'std'
248 | std::mutex mtx;
| ^~

 #### Proposed Solution
Enable C++11 basic concurrency constructs such as mutex, condition_variable on Nordic platform.

**Comment by woody-apple** [comment]
Given this is an old issue, is this still present? If so, please re-open, thanks!
