### ISSUE TITLE
[Linux] The server is dropping the request pinged by the client. Error: Data received on an unknown connection (0). Dropping it!!

### ISSUE THREAD

**Issue by rohit10000** [project-chip/connectedhomeip#5519]
#### Problem
  The server(chip-all-cluster-app) is dropping the request pinged by the client.

 * **expected behaviour**: Server must acknowledge the ping request.

 * screenshots, images, logs, etc.
 >
**Logs at Server:**

_$ ~/connectedhomeip/examples/all-clusters-app/linux/out/debug/chip-all-clusters-app_
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:ZCL: 0x55ef7669e39dep 1 clus 101 attr  3 not supported
CHIP:ZCL: Failed to write DoorState attribute: 0x86
CHIP:ZCL: 0x55ef7669e39dep 1 clus 101 attr 21 not supported
CHIP:ZCL: Failed to write Language attribute: 0x86
CHIP:ZCL: Start identify callback on endpoint 1 time 0
CHIP:ZCL: Stop identify callback on endpoint 1
CHIP:ZCL: WARNING: ATTRIBUTES ARE NOT BEING STORED IN FLASH! 
CHIP:ZCL: DEVICE WILL NOT FUNCTION PROPERLY AFTER REBOOTING!!
CHIP:ZCL: Failed to send IAS Zone update. Err 0x70
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 12344321

CHIP:DL: wpa_supplicant: _IsWiFiStationProvisioned: interface not connected
CHIP:BLE: Waiting for PBKDF param request
CHIP:DL: MDNS failed to join multicast group on enp1s0 for address type IPv4: Inet Error 1016 (0x000003F8): Address not found
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:SVR: Server Listening...
CHIP:DL: FAIL: BLE name is NULL in ConfigureBluezAdv
CHIP:DL: Disabling CHIPoBLE service due to error: CHIP Error 4003 (0x00000FA3): Incorrect state
**CHIP:IN: Data received on an unknown connection (0). Dropping it!!
CHIP:SVR: Packet received error: CHIP Error 4127 (0x0000101F): Key not found error code received from peer**

**Logs at Client:**

_~/connectedhomeip/examples/shell/shell_common/out/foo$ ./chip-shell
\> ping 127.0.0.1_

IP address: 127.0.0.1
CHIP:IN: TransportMgr initialized
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 112233

CHIP:IN: New pairing for device 12344321, key 0!!
Establish secure session succeeded

Send echo request message to Node: 12344321
CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 112233 to 12344321
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:IN: Sending msg from 112233 to 12344321
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:EM: Retransmit MsgId:00000000 Send Cnt 1
No response received

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Given this is an old issue, is this still present? If so, please re-open, thanks!
