### ISSUE TITLE
None-CHIP certificates validation

### ISSUE THREAD

**Issue by bitkis** [project-chip/connectedhomeip#5527]
#### Problem
We need is to verify a certificate stored in a DER format. Now in the CHIP code base the only way to verify a certificate is to convert it to the CHIP format using the `ConvertX509CertToChipCert` function because all routines for dealing with certificates expect certificates in the internal format. However, `ConvertX509CertToChipCert` works with CHIP compliant certificates only. Device manufacturer certificate used during CASE session establishment might not be CHIP compatible in general. So we need a way to verify none-CHIP certificates.

 #### Proposed Solution
It seems, the easiest way is to extend a CHIPCryptoPAL library with a method for DER certificate verification.

**Comment by woody-apple** [comment]
Given this is an old issue, is this still present? If so, please re-open, thanks!
