### ISSUE TITLE
Re-enable CodeQL

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#5541]
#### Problem
CodeQL has been failing almost every build due to "out of space".

#### Proposed Solution
Fix and re-enable

**Comment by woody-apple** [comment]
Looks like:
```
              with:
                  fetch-depth: 0
```
Is checking out all branches, which... is huge.

**Comment by woody-apple** [comment]
Looks like this is needed for bloat check, is there a way to just pull master (needed branches?) instead of all the branches?

**Comment by Damian-Nordic** [comment]
I wonder if `fetch-depth: 0` is still needed. It was added in https://github.com/project-chip/connectedhomeip/commit/67a1b5919, but at that time the bloat check was executed in the examples' workflows and now it's performed in a separate job.

**Comment by cecille** [comment]
@kpschoedel (I think you worked on bloat check) - any idea about this one?

**Comment by kpschoedel** [comment]
Bloat check no longer needs it. (It now records sizes of individual builds from CI and matches them up with parent builds later.)
