### ISSUE TITLE
Encode status code for cluster commands

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#5590]
#### Problem
Currently, the response of IM command handler is an empty command, this is a placeholder solution before the spec about this is clear.

We can now determine which value should be returned, and update related code.

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
In particular, decoding errors need to use this functionality.

**Comment by erjiaqing** [comment]
Seems this is already fixed.
