### ISSUE TITLE
ZAP: Remove profile id from endpoint configuration

### ISSUE THREAD

**Issue by lazarkov** [project-chip/connectedhomeip#5637]
#### Problem
Currently you can add/edit a Profile ID on a endpoint through zap tool. 
Profile ID is not supported on CHIP. It creates only confusion. 

 #### Proposed Solution
Remove the profile id reference from the ZAP tool.
Remove the profile id reference from the generated code.

**Comment by lazarkov** [comment]
[
<img width="401" alt="Screenshot 2021-03-22 at 15 42 43" src="https://user-images.githubusercontent.com/4352569/112600925-13f04100-8e12-11eb-8e76-5a4a5d5e1da2.png">
](url)

**Comment by bzbarsky-apple** [comment]
This will need some changes to non-generated code too, because some of that examines the profile id.

**Comment by bzbarsky-apple** [comment]
> Is profileID meaningless for CHIP, or does it simply get set to a specific value and nobody should touch it?

Meaningless; CHIP has different extension mechanisms.

**Comment by woody-apple** [comment]
Given this is an old issue, is this still present? If so, please re-open, thanks!

**Comment by bzbarsky-apple** [comment]
Moved to https://github.com/project-chip/zap/issues/394
