### ISSUE TITLE
Remove kFromInitiator flags

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5651]
#### Problem
They don't make sense as API (esp. in SendFlags), because the exchange context already knows that information.  Which is why they are unused.

 #### Proposed Solution
Remove the flags.

**Comment by woody-apple** [comment]
Given this is an old issue, is this still present? If so, please re-open, thanks!

**Comment by bzbarsky-apple** [comment]
Still an issue.  Will just fix.
