### ISSUE TITLE
Basic types are not aligned with the spec

### ISSUE THREAD

**Issue by kkasperczyk-no** [project-chip/connectedhomeip#5691]
#### Problem
The sizes of types defined in the basic-types.h https://github.com/project-chip/connectedhomeip/blob/master/src/app/util/basic-types.h seems to be not aligned with the spec 7.1.13.2. For example:
                        

|  | Spec  | Code |
|--- | ------------- | ------------- |
| Group Id | uint32_t  | uint16_t  |
| Command Id | uint32_t  | uint8_t  |
| Event Id | uint32_t  | uint16_t |
| Data Version | uint32_t  | uint64_t |

 #### Proposed Solution
Investigate the reason of inconsistencies and impact of aligning sizes to the spec on the code. Eventually raise the spec issue or fix the problem in code.

**Comment by andy31415** [comment]
Data model types defined in https://github.com/project-chip/connectedhomeip/blob/master/src/lib/core/DataModelTypes.h:

OK:
  - CommandID is uint32_t - spec 7.18.2 agrees
  - EventId is uint32_t - spec 7.18.2 agrees
  
  - DataVersion is uint32_t: 7.18.2. Derived Data Types in spec says derived data type `Data Version` is uint32.

src/lib/core/GroupId.h says GroupID is uint16_t, however 2.5.4. Group Identifier (GID) says GID is a 16-bit number, so this seems correct.

Based on the above, I believe existing code matches spec. Closing.
