### ISSUE TITLE
Enabling interaction model causes crash with null pointer

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#5788]
#### Problem
STR:
1 - set chip_enable_interaction_model = true in src/lib/core/core.gni

2 - build examples/chip-tool

3 - ensure you have a paired device

4 - run with arguments onoff on 1

Result: crash with null pointer. The line in OnOffCluster::On in CHIPClusters.cpp:

app::Command * ZCLcommand             = mDevice->GetCommandSender();

returns null then the null pointer gets used.

 #### Proposed Solution
call mDevice->InitCommandSender() at the appropriate place to ensure the sender is not null.

**Comment by yunhanw-google** [comment]
@erjiaqing please kindly fix this issue, thanks
