### ISSUE TITLE
Interactive model commands generate invalid/incomplete tlv data

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#5789]
#### Problem
src/app/Command.h and .cpp create incomplete tlv data, the commandList array is missing the end of container byte

Calling Command::Init() followed by Command::FinalizeCommandsMessage() results in following invalid tlv data:

15 36 00 18

It should be: 15 36 00 18 18

This affects every interactive model command, they are all incomplete/invalid.

 #### Proposed Solution
add this to beginning of Command::FinalizeCommandsMessage():

mInvokeCommandBuilder.GetCommandListBuilder().EndOfCommandList()

**Comment by yunhanw-google** [comment]
thanks for reporting this issue, just create the PR for issue fix, https://github.com/project-chip/connectedhomeip/pull/5799
