### ISSUE TITLE
ESP32 idf.py build broken for all-clusters app

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5818]
#### Problem
If I follow the steps in examples/all-clusters-app/esp32/README.md to try to build the all-clusters-app on ESP32, I get:
```
In file included from examples/common/screen-framework/include/Screen.h:28,
                 from examples/common/screen-framework/include/ListScreen.h:28,
                 from examples/common/screen-framework/ListScreen.cpp:26:
examples/common/screen-framework/include/Display.h:51:10: fatal error: tft.h: No such file or directory
 #include "tft.h"
          ^~~~~~~
compilation terminated.
```

 #### Proposed Solution
Following the directions should work.

For comparison, using the "old" way to build (via `source idf.sh` and then `idf make` works just fine.  The officially documented way should also work.

@dhrishi @sweetymhaiske

**Comment by sweetymhaiske** [comment]
@bzbarsky-apple I rechecked it. It worked fine on my side. Can you please clean and rebuild via CMake?

**Comment by dhrishi** [comment]
@sweetymhaiske The above compilation seems to be for M5Stack and yes, it is failing. Can you please check?

**Comment by sweetymhaiske** [comment]
@dhrishi @bzbarsky-apple  I compiled for ESP32, for which it worked fine. Yes for M5Stack it was failing. I have added the fixes for the same.

**Comment by bzbarsky-apple** [comment]
Thank you for the quick fix!  Sorry, I should have specified I was compiling for m5stack...  I did try cleaning to make sure that was not the problem, of course.  :)
