### ISSUE TITLE
nrfconnect: FDR doesn't reset KVS

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#5822]
#### Problem

Long-press on button 1 should reset the device to a factory default state.

Currently, KVS contents survive FDR which exacerbates problems such as as #5782 and isn't recoverable without using nrfjprog.

 #### Proposed Solution

FDR operation should clear KVS contents.

**Comment by mrjerryjohns** [comment]
NRF does have a matter specific factory reset implementation that does seem to work fine (when I last tested it last week). Marking this as stale.
