### ISSUE TITLE
Android 32bit don't include OpenThread library(libcommissioner-java.so)

### ISSUE THREAD

**Issue by wissn84** [project-chip/connectedhomeip#5845]
#### Problem
Android 32bit don't include OpenThread  library(libcommissioner-java.so).
Here is Build result when 32bit build using below command
`TARGET_CPU=arm ./scripts/examples/android_app.sh`

**Comment by woody-apple** [comment]
Given this is an older issue, does this till reproduce on current builds? Please re-open if so!
