### ISSUE TITLE
Provide an echo client on macOS 

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#585]
This issue has a few different stages of completion
1. Enable an echo client that runs on macOS and can ping an ESP32 running CHIP
2. Implement the echo client as a native macOS application that links with CHIP.Framework
3. After CHIP.Framework is updated to support NW.Framework APIs for InetLayer, ensure this application uses the NW apis.

The echo client should periodically send messages to the EPS32's echo server and verify that the messages received are as expected.

**Comment by woody-apple** [comment]
SW BRB: Closing this, as CHIP-tool does what we need here.
