### ISSUE TITLE
bridge app show "OnRendezvousError: Error 4042 (0x00000FCA)" when try pairing bridge app to chip-device-ctrl via wifi

### ISSUE THREAD

**Issue by ElthamLiu** [project-chip/connectedhomeip#5853]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 bridge app can be paired to chip too by command "chip-device-ctrl connect -ip 127.0.0.1 12345678 1234"
 * actual behavior
 bridge app show "OnRendezvousError: Error 4042 (0x00000FCA)" 
 * steps to reproduce
 1. build chip-device-ctrl
 2. build bridge-app
 3. use command "chip-device-ctrl connect -ip 127.0.0.1 12345678 1234" trying to pair bridge app
 
 * system configuration
 hardware: raspberry pi 4b
 os: ubuntu
 * screenshots, images, logs, etc.
 >
* bridge-app log:
(python_env) ubuntu@ubuntu:~/connectedhomeip/examples/bridge-app/linux$ ./out/debug/chip-bridge-app --ble-device 0
SetupPINCode: [12345678]
SetupQRCode:  [CH:I34DV*700 0C9SS0]
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 12344321

CHIP:DL: wpa_supplicant: _IsWiFiStationProvisioned: interface not connected
CHIP:BLE: Waiting for PBKDF param request
CHIP:DIS: CHIP minimal mDNS configured as 'Commisioning device'.
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:SVR: Server Listening...
CHIP:DL: TRACE: Bluez mainloop starting Thread
CHIP:DL: TRACE: Bus acquired for name CHIP-3840
CHIP:DL: CREATE service object at /chipoble/208e/service
CHIP:DL: Create characteristic object at /chipoble/208e/service/c1
CHIP:DL: Create characteristic object at /chipoble/208e/service/c2
CHIP:DL: CHIP BTP C1 /chipoble/208e/service
CHIP:DL: CHIP BTP C2 /chipoble/208e/service
CHIP:DL: CHIP_ENABLE_ADDITIONAL_DATA_ADVERTISING is TRUE
CHIP:DL: Create characteristic object at /chipoble/208e/service/c3
CHIP:DL: rotatingDeviceId: 00007C5F6E176CD40F68685D100A1CF8A98B
CHIP:DL: CHIP BTP C3 /chipoble/208e/service
CHIP:DL: PlatformBlueZInit init success
CHIP:DL: BluezPeripheralRegisterAppDone done
CHIP:DL: HandlePlatformSpecificBLEEvent 16391
CHIP:DL: Create adv object at /chipoble/208e/advertising
CHIP:DL: SET service data to {'0xFEAF': <[byte 0x00, 0x00, 0x0f, 0x5a, 0x23, 0xff, 0xfe]>}
CHIP:DL: HandlePlatformSpecificBLEEvent 16392
CHIP:DL: CHIPoBLE advertising config complete
CHIP:DL: RegisterAdvertisement complete
CHIP:DL: HandlePlatformSpecificBLEEvent 16393
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply
CHIP:DIS: Broadcasting mDns reply

CHIP:BLE: Received pairing message for 1
CHIP:BLE: Received PBKDF param request
CHIP:BLE: Sent PBKDF param response
**CHIP:SVR: OnRendezvousStatusUpdate: Error 4042 (0x00000FCA)**
CHIP:SVR: Persisting admin ID 0, next available 1
**CHIP:SVR: OnRendezvousError: Error 4042 (0x00000FCA)**
CHIP:DL: UnregisterAdvertisement complete
CHIP:DL: HandlePlatformSpecificBLEEvent 16394
CHIP:DL: CHIPoBLE advertising stopped

* chip-device-ctrl log:
ubuntu@ubuntu:~/connectedhomeip$ chip-device-ctrl 
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 18446743528248704968

CHIP:DL: CHIP task running
Chip Device Controller Shell

chip-device-ctrl > connect -ip 10.0.0.17 12345678 1
Device is assigned with nodeid = 1
CHIP:BLE: Sent PBKDF param request

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Given this is an older issue, does this till reproduce on current builds? Please re-open if so!
