### ISSUE TITLE
ExchangeContext is really big

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5876]
ExchangeContext is 120 bytes on 64-bit, 88 bytes on 32-bit.  We have 8 of them in a pool, so this is ~1KB of RAM.

@andy31415 did a a clang AST dump for this class on 64-bit, which looks like this:
<details>
<summary>Click to expand dump</summary>

```
         0 | class chip::Messaging::ExchangeContext
         0 |   class chip::ReferenceCounted<class chip::Messaging::ExchangeContext, class chip::Messaging::ExchangeContextDeletor, 0> (base)
         0 |     chip::ReferenceCounted::count_type mRefCount
         4 |   chip::Messaging::ExchangeContext::Timeout mResponseTimeout
         8 |   class chip::Messaging::ReliableMessageContext mReliableMessageContext
         8 |     class chip::BitFlags<enum chip::Messaging::ReliableMessageContext::Flags, unsigned short> mFlags
         8 |       unsigned short mValue
        16 |     class chip::Messaging::ReliableMessageMgr * mManager
        24 |     class chip::Messaging::ExchangeContext * mExchange
        32 |     class chip::Messaging::ReliableMessageDelegate * mDelegate
        40 |     struct chip::Messaging::ReliableMessageProtocolConfig mConfig
        40 |       uint32_t mInitialRetransTimeoutTick
        44 |       uint32_t mActiveRetransTimeoutTick
        48 |       uint16_t mAckPiggybackTimeoutTick
        50 |       uint8_t mMaxRetrans
        52 |     uint16_t mNextAckTimeTick
        56 |     uint32_t mPendingPeerAckId
        64 |   class chip::Messaging::ExchangeDelegate * mDelegate
        72 |   class chip::Messaging::ExchangeManager * mExchangeMgr
        80 |   class chip::Messaging::ExchangeACL * mExchangeACL
        88 |   class chip::SecureSessionHandle mSecureSession
        88 |     chip::NodeId mPeerNodeId
        96 |     uint16_t mPeerKeyId
        98 |     Transport::AdminId mAdmin
       100 |     _Bool mPeerGroupMsgIdNotSynchronized
       104 |   uint16_t mExchangeId
       106 |   uint8_t [8] mChallenge
       114 |   class chip::BitFlags<enum chip::Messaging::ExchangeContext::ExFlagValues, unsigned short> mFlags
       114 |     unsigned short mValue
           | [sizeof=120, dsize=116, align=8,
           |  nvsize=116, nvalign=8]
```

</details>

Looks like:
* 4 bytes refcount
* 4 bytes mResponseTimeout
* 52 bytes ReliableMessageContext (36 bytes on 32-bit)
* 4 bytes padding (64-bit only)
* 24 bytes pointers to delegate, exchange mgr, exchange acl (12 bytes on 32-bit)
* 16 bytes SecureSessionHandle
* 2 bytes exchange id
* 8 bytes challenge
* 2 bytes mFlags
* 4 bytes padding to get to 8-byte alignment (even on 32-bit!)

Things to look into:
* [ ] Why the 8-byte alignment requirement on 32-bit?
* [ ] Can we come up with a more compact representation for SecureSessionHandle?  Is the handle we have here one of the ones from the pool?  If so, could we store an index, not the whole handle?
* [ ] Is this really the right place to store mExchangeACL?  We don't have one of those per-exchange; we have a per-node singleton, really.
* [ ] Do we need to store the challenge in here?  Looks like #4711 is already tracking this?
* [ ] We could probably reduce the ExchangeManager pointer to a single-byte offset into the exchange context pool.  That could then pack with mFlags (which we can make 1-byte; we only have two flags) to save 4-8 bytes of memory, depending on where we get with the alignment thing.  It would be a little ugly, but doable.
* [ ] ReliableMessageContext can be much smaller.  Filed https://github.com/project-chip/connectedhomeip/issues/5875

@yufengwangca

**Comment by yufengwangca** [comment]
Closed with #5942
