### ISSUE TITLE
Support pairing timeouts in the Darwin framework

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#5880]
We should support timeouts in the Darwin framework too

_Originally posted by @woody-apple in https://github.com/project-chip/connectedhomeip/pull/5849#discussion_r610042605_

**Comment by sagar-apple** [comment]
@woody-apple I took a look at #5849 and those timeout errors will be bubbled up to the Darwin Framework correctly. Is there any more work needed here?
