### ISSUE TITLE
Demo Echo Server<->Client examples to Software Development Team

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#589]
- Demo the existing Echo Server and Client(posix) examples
- Demo the native, CHIP.Framework based, macOS Echo Client interacting with the existing Echo Server on the esp32

**Comment by andy31415** [comment]
@sagar-apple could we close this? I assume the demo is done since the issue was opened quite a while ago.

**Comment by sagar-apple** [comment]
Already done!
