### ISSUE TITLE
Passing write or readLength = 0 as an argument to emAfReadOrWriteAttribute is unsafe

### ISSUE THREAD

**Issue by vivien-apple** [project-chip/connectedhomeip#5897]
Passing a 0 `readLength` here is just asking for trouble in memory safety terms for both reads and writes.  Please make sure a followup is filed to stop doing that, marked as a critical security problem.  Or fix it before landing, I guess....

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/5020#discussion_r610126472_

**Comment by tcarmelveilleux** [comment]
A bit more context since the original PR conversation link does not expand:

![image](https://user-images.githubusercontent.com/1313847/151980018-ad2d0139-d6a3-477f-b0df-7687216f37b8.png)

**Comment by bzbarsky-apple** [comment]
Note that the code in question (the caller of emAfReadOrWriteAttribute) is gone now.  The API itself still has issues, but this callsite is not one of them.
