### ISSUE TITLE
Consider setting CHIP_CONFIG_RMP_RETRANS_TABLE_SIZE to the min of pool size and exchange context count

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5924]
#### Problem
Right now if we have a limited number or possible exchange contexts but a large packetbuffer pool, we can end up with a large CRMP retransmit table.

 #### Proposed Solution
Take both values into account when defining the retransmit table size.

@yufengwangca Do you have time for this?

**Comment by yufengwangca** [comment]
Yes, as I said in the email, current setting is based on the assumption exchange size is no less than buffer pool size.  In Weave, we set the maximum exchange pool size based on the available buffer pool size, so we can guarantee  that. 

But take the min of two is better.
