### ISSUE TITLE
CASE handshake implementation looks nothing like the spec

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#5934]
#### Problem
#5442 implemented CASE, but it looks very little like the CASE in the spec in terms of what's going in to the messages and how.

 #### Proposed Solution
Implement what the spec says.

**Comment by bzbarsky-apple** [comment]
Specifically, we want TLV encoding here, etc.

**Comment by tcarmelveilleux** [comment]
CASE is still not up to spec. See #8137 for ongoing spec compliance work.
