### ISSUE TITLE
make CHIP_DEVICE_CONFIG_BLE_ADVERTISING_TIMEOUT configurable via menuconfig

### ISSUE THREAD

**Issue by shah-kartik** [project-chip/connectedhomeip#5996]
make CHIP_DEVICE_CONFIG_BLE_ADVERTISING_TIMEOUT configurable via menuconfig

Currently it is defined as 
CHIP_DEVICE_CONFIG_BLE_ADVERTISING_TIMEOUT (15 * 60 * 1000)

can we make it configurable.
either via menuconfig or any other way ?

**Comment by Damian-Nordic** [comment]
@shah-kartik You can use `chip_ble_project_config_include` GN arguments to provide a project-specific BLE configuration file where you can override the constants. Which platform do you use by the way?

**Comment by shah-kartik** [comment]
@Damian-Nordic, Thanks for the comment. I am using M5Stack kits right now.
