### ISSUE TITLE
mDNS reply is unreachable

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6024]
mDNS reply to the peer seem to be advertised on all interfaces (including local host) and peer unreachable on some interfaces.

CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable
CHIP:DIS: Directly sending mDns reply to peer on port 5353
CHIP:DIS: Failed to reply to query: OS Error 2101 (0x00000835): Network is unreachable

**Comment by turon** [comment]
I'm seeing something similar with the python controller on Linux as well:

```
chip-device-ctrl > discover -all
[1624055419.310826][122497] CHIP:DIS: mDNS broadcast success
[1624055419.310918][122497] CHIP:DIS: Attempt to mDNS broadcast failed:  OS Error 2101 (0x00000835): Network is unreachable
[1624055419.311116][122497] CHIP:DIS: mDNS broadcast success
[1624055419.311298][122497] CHIP:DIS: mDNS broadcast success
[1624055419.311414][122497] CHIP:DIS: mDNS broadcast success
[1624055419.311465][122497] CHIP:DIS: Attempt to mDNS broadcast failed:  OS Error 2099 (0x00000833): Cannot assign requested address
Waiting for device responses...
```

**Comment by woody-apple** [comment]
Given this is an older issue, does this till reproduce on current builds? Please re-open if so!
