### ISSUE TITLE
invalid passcode in source file(s)

### ISSUE THREAD

**Issue by leorozendaal** [project-chip/connectedhomeip#6058]
#### Problem
File examples/lock-app/nrfconnect/main/include/CHIPProjectConfig.h:38 contains
`#define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 12345678`
Looking at spec section 5.1.6.1, this is one of the **invalid** passcodes.

#### Proposed Solution
Suggest to change it to another value (e.g. `20202021`).
Note - I expect there are other source files (e.g. the other example files) with the same invalid value. Please check and fix.

 
Triggered from slack discussion ([link](https://zigbeeiot.slack.com/archives/C01RATGFSJD/p1617953391126700))

**Comment by lucicop** [comment]
See PR #6133.
