### ISSUE TITLE
Add random number to echo example using DRBG

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#608]
Add a random number to echo requests and responses using CHIP's `DRBG_get_bytes()` API. The request will contain the random number generated by client. The response message will contain client's original random number, and also include a new random number generated by the server. The intent is to test `DRBG_get_bytes()` API, ensuring each request/response contains a unique identifier.

**Comment by vivien-apple** [comment]
`echo` does not exists anymore. Should we close this ? @pan-apple

**Comment by pan-apple** [comment]
Yes, I think we should close it

**Comment by vivien-apple** [comment]
Closing. Feel free to reopen if needed.
