### ISSUE TITLE
Sign and verify echo request and response in Echo example app

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#609]
Sign the echo request using client's private key. The signature will be carried in the echo request as additional payload. Verify the signature on server using peer (client's) public key. Once verified, sign the echo response using server's private key. The client will verify the signature of response using peer (server's) public key.

**Comment by woody-apple** [comment]
SW BRB: We don't believe this is required at this point, given we're moving to a secure channel that does this.
