### ISSUE TITLE
python controller zclread command to have a timeout

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6117]
python controller zclread command to have a timeout, right now if the accessory could not respond for some reason, zclread command waits indefinitely until is is killed 

chip-device-ctrl > zclread Basic VendorID 12344321 1 0
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 2
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 442122799 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: SendMessage returned No Error
CHIP:EM: ec pos: 0, id: 17770, Delegate: 0x2926fba0
CHIP:ZCL: APS frame processing success!
CHIP:ZCL: RX len 9, ep 1, clus 0x28 
CHIP:ZCL:  FC 8 seq 2 cmd 1 payload[
CHIP:ZCL: 02 00 00 21 5A 23 
CHIP:ZCL: ]
CHIP:ZCL: ReadAttributesResponse:
CHIP:ZCL:   ClusterId: 0x0028
CHIP:ZCL:   attributeId: 0x0002
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:ZCL:   attributeType: 0x21
CHIP:ZCL:   value: 0x235a
Failed to establish secure session to device: 2585764192
CHIP:ZCL: Data model processing success!
An exception occurred during reading ZCL attribute:
Error -1709203104 (0x9A1FA160)
chip-device-ctrl > **zclread Basic VendorID 12344321 1 0**
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 3
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 443884592 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: SendMessage returned No Error

^C

**Comment by woody-apple** [comment]
Given this is an older issue, does this till reproduce on current builds? Please re-open if so!
