### ISSUE TITLE
Python controller to support Network Commissioning Cluster Commands

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6121]
Python controller to support Network Commissioning Cluster Commands , Required for cert test case 
https://github.com/project-chip/chip-test-plans/blob/master/src/devicemanagement.adoc#6327-test-procedure 

![Screen Shot 2021-04-18 at 10 45 18 PM](https://user-images.githubusercontent.com/68604034/115187242-d640aa00-a097-11eb-87db-652a959a77dc.png)
![Screen Shot 2021-04-18 at 10 45 25 PM](https://user-images.githubusercontent.com/68604034/115187251-d80a6d80-a097-11eb-8dac-5359fb1cf6e9.png)

**Comment by Damian-Nordic** [comment]
@erjiaqing I can add support for the Network Commissioning Cluster commands to Python CHIP controller if you haven't started looking into that.

**Comment by erjiaqing** [comment]
> @erjiaqing I can add support for the Network Commissioning Cluster commands to Python CHIP controller if you haven't started looking into that.

Seems no special support is required?
The network commissioning cluster is already in the zap file for controller.

**Comment by Damian-Nordic** [comment]
I think we need to add Network Commissioning Cluster to the Python app's ZAP configuration and re-gen files in `python/gen` to support parsing responses to some of the commands.
