### ISSUE TITLE
Segmentation fault with sending commands using python controller

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6123]
Seg fault with EnableNetwork command in NetworkCommissioning using python controller
 $ chip-device-ctrl 
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:DL: CHIP task running
CHIP:DL: Platform main loop started.
Chip Device Controller Shell

chip-device-ctrl > help

Available commands (type help <name> for more information):
============================================================
ble-adapter-print   ble-scan  set-pairing-thread-credential  zcl    
ble-adapter-select  connect   set-pairing-wifi-credential    zclread
ble-debug-log       resolve   setup-payload                

chip-device-ctrl > set-pairing-wifi-credential TESTSSID PASSWD
WiFi credential set
chip-device-ctrl > connect -ble 3840 12345678 12344321
Device is assigned with nodeid = 12344321
CHIP:DL: TRACE: Bluez mainloop starting Thread
CHIP:DL: TRACE: Bus acquired for name C-a7d3
CHIP:DL: PlatformBlueZInit init success
CHIP:BLE: BLE removing known devices.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: Device 7B:2D:75:85:0F:73 does not look like a CHIP device.
CHIP:BLE: Device 08:66:98:91:F5:27 does not look like a CHIP device.
CHIP:BLE: Device 0E:BC:A0:27:F8:88 does not look like a CHIP device.
CHIP:BLE: Device 4C:B3:EF:82:82:4E does not look like a CHIP device.
CHIP:BLE: Device 79:DD:1C:CB:C8:88 does not look like a CHIP device.
CHIP:BLE: Device 32:1F:F5:0D:A4:E9 does not look like a CHIP device.
CHIP:BLE: Device 23:D4:77:99:9F:E4 does not look like a CHIP device.
CHIP:BLE: Device 77:36:05:2C:C0:48 does not look like a CHIP device.
CHIP:BLE: Device 1E:A2:77:BA:3B:F4 does not look like a CHIP device.
CHIP:BLE: Device FB:67:AC:AE:05:8A does not look like a CHIP device.
CHIP:BLE: Device 6A:55:F0:28:2C:BC does not look like a CHIP device.
CHIP:BLE: Device 6A:96:27:E2:D2:DC does not look like a CHIP device.
CHIP:BLE: Device 71:82:E7:CE:74:BB does not look like a CHIP device.
CHIP:BLE: Device 68:C7:C2:BD:71:DB does not look like a CHIP device.
CHIP:BLE: Device 5D:F5:12:02:E1:87 does not look like a CHIP device.
CHIP:BLE: Device 76:EC:48:07:B1:6C does not look like a CHIP device.
CHIP:BLE: Device 5C:B0:77:1B:02:CD does not look like a CHIP device.
CHIP:BLE: New device scanned: DC:A6:32:8D:70:74
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Scan complete notification without an active scan.
CHIP:DL: ConnectDevice complete
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0010
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0010
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0010
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service0006
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_8D_70_74/service011b
CHIP:DL: New BLE connection 0xffff8005dfd0, device DC:A6:32:8D:70:74, path /org/bluez/hci0/dev_DC_A6_32_8D_70_74
CHIP:DL: HandlePlatformSpecificBLEEvent 16385
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:BLE: subscribe complete, ep = 0xffff952ae970
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:BLE: peripheral chose BTP version 3; central expected between 2 and 3
CHIP:BLE: using BTP fragment sizes rx 20 / tx 128.
CHIP:BLE: local and remote recv window size = 3
CHIP:BLE: Assigned local session key ID 0
CHIP:BLE: SessionEstablishmentExchangeDispatch::SendMessageImpl mBLETransport 0x24bf3230, mTransportMgr 0xffff88007930
CHIP:BLE: Sending message using BLE transport
CHIP:BLE: Sent PBKDF param request
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:BLE: Received PBKDF param response
CHIP:BLE: SessionEstablishmentExchangeDispatch::SendMessageImpl mBLETransport 0x24bf3230, mTransportMgr 0xffff88007930
CHIP:BLE: Sending message using BLE transport
CHIP:BLE: Sent spake2p msg1
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:BLE: Received spake2p msg2
CHIP:BLE: Peer assigned session key ID 0
CHIP:BLE: SessionEstablishmentExchangeDispatch::SendMessageImpl mBLETransport 0x24bf3230, mTransportMgr 0xffff88007930
CHIP:BLE: Sending message using BLE transport
CHIP:BLE: Sent spake2p msg3
CHIP:IN: New pairing for device 0x0000000000bc5c01, key 0!!
CHIP:CTL: Remote device completed SPAKE2+ handshake

CHIP:NP: Sending Network Creds

CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 23582268 msec
CHIP:IN: Sending secure msg on connection specific transport
CHIP:IN: Secure msg send status No Error
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: Indication received, conn = 0xffff8005dfd0
CHIP:DL: HandlePlatformSpecificBLEEvent 16389
CHIP:EM: ec pos: 1, id: 17767, Delegate: 0x24d561f0
CHIP:NP: Received kIPAddressAssigned
CHIP:CTL: Remote device was assigned an ip address

CHIP:CTL: AsyncSetKeyValue: PairedDevicebc5c01=EADX2NmTjR65+AeWNIXhm9pdAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAFcvAAAAAAAMTkyLjE2OC42Ljk0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFkrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CHIP:BLE: BleConnectionDelegate::CancelConnection is not implemented.
CHIP:CTL: AsyncSetKeyValue: ListPairedDevices0=AVy8AAAAAAA=
CHIP:CTL: AsyncSetKeyValue: StartKeyID=1
Secure Session to Device Established
Device temporary node id (**this does not match spec**): 12344321
chip-device-ctrl > CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:BLE: Auto-closing end point's BLE connection.
CHIP:DL: Closing BLE GATT connection (con 0xffff8005dfd0)
CHIP:DL: BluezDisconnect peer=DC:A6:32:8D:70:74
CHIP:DL: Bluez disconnected
CHIP:DL: Bluez notify CHIPoBluez connection disconnected

chip-device-ctrl > zcl NetworkCommissioning AddWiFiNetwork 12344321 1 0 ssid=str: TESTSSID credentials=str: PASSWD breadcrumb=0 timeoutMs=1000
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Connection from 'UNDEFINED' expired
CHIP:CTL: OnConnectionExpired was called for unknown device, ignoring it.
CHIP:IN: New pairing for device 0x0000000000bc5c01, key 0!!
CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 23594070 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: SendMessage returned No Error
CHIP:EM: ec pos: 0, id: 17768, Delegate: 0x24cd4ba0
CHIP:ZCL: APS frame processing success!
CHIP:ZCL: RX len 5, ep 1, clus 0x31 
CHIP:ZCL:  FC 8 seq 0 cmd b payload[
CHIP:ZCL: 02 00 
CHIP:ZCL: ]
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   ClusterId: 0x0031
CHIP:ZCL:   CommandId: 0x02
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
Failed to establish secure session to device: 2537636192
CHIP:ZCL: Data model processing success!
An exception occurred during process ZCL command:
Error -1757331104 (0x97414160)
chip-device-ctrl > zcl NetworkCommissioning EnableNetwork 12344321 1 0 networkID=str:Partyguys breadcrumb=0 timeoutMs=1000
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 1
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 23609060 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: SendMessage returned No Error
CHIP:EM: ec pos: 0, id: 17769, Delegate: 0x24cd4ba0
CHIP:ZCL: APS frame processing success!
CHIP:ZCL: RX len 5, ep 1, clus 0x31 
CHIP:ZCL:  FC 8 seq 1 cmd b payload[
CHIP:ZCL: 0C 00 
CHIP:ZCL: ]
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   ClusterId: 0x0031
CHIP:ZCL:   CommandId: 0x0c
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
Failed to establish secure session to device: 2537636192
CHIP:ZCL: Data model processing success!
CHIP:EM: ec pos: 0, id: 17770, Delegate: 0x24d561f0
[1]+  Killed                  chip-device-ctrl
Segmentation fault (core dumped)
------------------------
Accessory log

$ sudo ./out/host/chip-lighting-app --wifi
SetupPINCode: [12345678]
SetupQRCode:  [CH:H34DV+700 0C9SS0]
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x0000000000bc5c01
CHIP:DL: wpa_supplicant: _IsWiFiStationProvisioned: interface not connected
CHIP:BLE: Assigned local session key ID 0
CHIP:BLE: Waiting for PBKDF param request
CHIP:DIS: Start dns-sd server
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:SVR: Server Listening...
CHIP:DL: TRACE: Bluez mainloop starting Thread
CHIP:DL: TRACE: Bus acquired for name CHIP-3840
CHIP:DL: CREATE service object at /chipoble/4bc6/service
CHIP:DL: Create characteristic object at /chipoble/4bc6/service/c1
CHIP:DL: Create characteristic object at /chipoble/4bc6/service/c2
CHIP:DL: CHIP BTP C1 /chipoble/4bc6/service
CHIP:DL: CHIP BTP C2 /chipoble/4bc6/service
CHIP:DL: CHIP_ENABLE_ADDITIONAL_DATA_ADVERTISING is TRUE
CHIP:DL: Create characteristic object at /chipoble/4bc6/service/c3
CHIP:DL: rotatingDeviceId: 00007C5F6E176CD40F68685D100A1CF8A98B
CHIP:DL: CHIP BTP C3 /chipoble/4bc6/service
CHIP:DL: PlatformBlueZInit init success
CHIP:DL: wpa_supplicant: connected to wpa_supplicant proxy
CHIP:DL: wpa_supplicant: WiFi interface: /fi/w1/wpa_supplicant1/Interfaces/0
CHIP:DL: HandlePlatformSpecificBLEEvent 16392
CHIP:DL: BluezPeripheralRegisterAppDone done
CHIP:DL: Create adv object at /chipoble/4bc6/advertising
CHIP:DL: SET service data to {'0xFEAF': <[byte 0x00, 0x00, 0x0f, 0x5a, 0x23, 0xff, 0xfe]>}
CHIP:DL: HandlePlatformSpecificBLEEvent 16393
CHIP:DL: CHIPoBLE advertising config complete
CHIP:DL: wpa_supplicant: connected to wpa_supplicant interface proxy
CHIP:DL: RegisterAdvertisement complete
CHIP:DL: HandlePlatformSpecificBLEEvent 16394
CHIP:DL: Got IP address on interface: wlan0 IP: 192.168.6.94
CHIP:DL: HandlePlatformSpecificBLEEvent 32770
CHIP:DL: Device DC:A6:32:7E:5C:77 (Path: /org/bluez/hci0/dev_DC_A6_32_7E_5C_77) Connected
CHIP:DL: BluezCharacteristicAcquireWrite is called, conn: 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: local and remote recv window sizes = 3
CHIP:BLE: selected BTP version 3
CHIP:BLE: using BTP fragment sizes rx 128 / tx 20.
CHIP:DL: CHIPoBLE subscribe received
CHIP:DL: HandlePlatformSpecificBLEEvent 32777
CHIP:DL: Receive kCHIPoBLEConnectionEstablished
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:EM: ec pos: 0, id: 17767, Delegate: 0xc64ae2b8
CHIP:BLE: Received PBKDF param request
CHIP:BLE: SessionEstablishmentExchangeDispatch::SendMessageImpl mBLETransport 0xaaaad5475f10, mTransportMgr 0xaaaac64ada20
CHIP:BLE: Sending message using BLE transport
CHIP:BLE: Sent PBKDF param response
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Received spake2p msg1
CHIP:BLE: Peer assigned session key ID 0
CHIP:BLE: SessionEstablishmentExchangeDispatch::SendMessageImpl mBLETransport 0xaaaad5475f10, mTransportMgr 0xaaaac64ada20
CHIP:BLE: Sending message using BLE transport
CHIP:BLE: Sent spake2p msg2
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Received spake2p msg3
CHIP:BLE: Missing node id in rendezvous parameters. Node ID is required until opcerts are implemented
CHIP:IN: New pairing for device 0x0000000000000000, key 0!!
CHIP:SVR: Device completed SPAKE2+ handshake
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:EM: ec pos: 1, id: 17768, Delegate: 0xc64aebb0
CHIP:NP: Received kWiFiAssociationRequest.

CHIP:NP: LinuxNetworkProvisioningDelegate: SSID: Partyguys
CHIP:DL: wpa_supplicant: added network: SSID: Partyguys: /fi/w1/wpa_supplicant1/Interfaces/0/Networks/16
CHIP:DL: wpa_supplicant: connected to network: SSID: Partyguys
CHIP:DL: wpa_supplicant: save config succeeded!
CHIP:DL: Got IP address on interface: wlan0 IP: 192.168.6.94
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: dhclient is running on the wlan0 interface.
CHIP:SVR: Device was assigned network credentials
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Found admin paring for admin 0, node BC5C01
CHIP:DIS: Using wifi MAC for hostname
CHIP:DIS: Advertise operational node 0-BC5C01
CHIP:DIS: CHIP minimal mDNS configured as 'Operational device'.
CHIP:SVR: Device completed Rendezvous process
CHIP:SVR: Failed to store the connection state
CHIP:DL: Long dispatch time: 172 ms
CHIP:DL: HandlePlatformSpecificBLEEvent 32770
CHIP:NP: Sending IP Address

CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 0x0000000000bc5c01 to 0x000000000001b669 at utc time: 269773410 msec
CHIP:IN: Sending secure msg on connection specific transport
CHIP:IN: Secure msg send status No Error
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:BLE: Write request received debug 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:BLE: Indication confirmation, 0xffffb00468b0
CHIP:DL: Bluez disconnected
CHIP:DL: Bluez notify CHIPoBluez connection disconnected
CHIP:SVR: Persisting admin ID 0, next available 1
CHIP:BLE: BleConnectionDelegate::CancelConnection is not implemented.
CHIP:SVR: OnRendezvousError: Ble Error 6012 (0x0000177C): Remote device closed BLE connection
CHIP:DL: UnregisterAdvertisement complete
CHIP:DL: HandlePlatformSpecificBLEEvent 16395
CHIP:DL: CHIPoBLE advertising stopped
CHIP:EM: ec pos: 1, id: 17769, Delegate: 0xc64afc10
CHIP:SVR: Packet received from Node:1b669: 50 bytes
CHIP:ZCL: APS frame processing success!
CHIP:ZCL: RX len 39, ep 1, clus 0x31 
CHIP:ZCL:  FC 1 seq 0 cmd 2 payload[
CHIP:ZCL: 0A 50 61 72 74 79 67 75 79 73 00 0C 49 6E 76 61 6C 69 64 24 31 32 33 00 00 00 00 00 00 00 00 00 E8 03 00 00 
CHIP:ZCL: ]
CHIP:ZCL: WiFi provisioning data: SSID: Partyguys
CHIP:ZCL: AddWiFiNetwork: 0
CHIP:ZCL: Measured APS frame size 11
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 1
CHIP:IN: Sending msg from 0x0000000000bc5c01 to 0x000000000001b669 at utc time: 269784904 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:ZCL: T   0:TX (0xaaaac6480eb8) Ucast 0x00xaaaac6480eb0
CHIP:ZCL: TX buffer: [
CHIP:ZCL: 08 00 0B 02 00 
CHIP:ZCL: ]
CHIP:ZCL: Data model processing success!
CHIP:EM: ec pos: 1, id: 17770, Delegate: 0xc64afc10
CHIP:SVR: Packet received from Node:1b669: 37 bytes
CHIP:ZCL: APS frame processing success!
CHIP:ZCL: RX len 26, ep 1, clus 0x31 
CHIP:ZCL:  FC 1 seq 1 cmd c payload[
CHIP:ZCL: 0A 50 61 72 74 79 67 75 79 73 00 00 00 00 00 00 00 00 00 E8 03 00 00 
CHIP:ZCL: ]
CHIP:NP: LinuxNetworkProvisioningDelegate: SSID: Partyguys
CHIP:DL: wpa_supplicant: removed network: /fi/w1/wpa_supplicant1/Interfaces/0/Networks/16
CHIP:DL: wpa_supplicant: added network: SSID: Partyguys: /fi/w1/wpa_supplicant1/Interfaces/0/Networks/16
CHIP:DL: wpa_supplicant: connected to network: SSID: Partyguys
CHIP:DL: wpa_supplicant: save config succeeded!
CHIP:DL: Got IP address on interface: wlan0 IP: 192.168.6.94
CHIP:DL: dhclient is running on the wlan0 interface.
CHIP:ZCL: Measured APS frame size 11
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 2
CHIP:IN: Sending msg from 0x0000000000bc5c01 to 0x000000000001b669 at utc time: 269800047 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:ZCL: T   0:TX (0xaaaac6480eb8) Ucast 0x00xaaaac6480eb0
CHIP:ZCL: TX buffer: [
CHIP:ZCL: 08 01 0B 0C 00 
CHIP:ZCL: ]
CHIP:ZCL: Data model processing success!
CHIP:DL: HandlePlatformSpecificBLEEvent 32770
CHIP:NP: Sending IP Address

CHIP:IN: Secure message was encrypted: Msg ID 3
CHIP:IN: Sending msg from 0x0000000000bc5c01 to 0x000000000001b669 at utc time: 269800048 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:DIS: Broadcasting mDns reply

**Comment by erjiaqing** [comment]
Now, we are using IM for sending messages, does this issue occurs on IM also?

**Comment by cjandhyala** [comment]
@erjiaqing we don't see this issue anymore. we can close the issue and open a new issue when we see it again
