### ISSUE TITLE
CHIP_DEVICE_CONFIG_DEVICE_FIRMWARE_REVISION type changed

### ISSUE THREAD

**Issue by eve-cxrp** [project-chip/connectedhomeip#6124]
The define CHIP_DEVICE_CONFIG_DEVICE_FIRMWARE_REVISION changed from char* to uint32_t.

Is uint32_t the correct approach? Shouldn't it not stay char* to have better semantic versioning?

**Comment by Damian-Nordic** [comment]
Hi,
Apart from changing `CHIP_DEVICE_CONFIG_DEVICE_FIRMWARE_REVISION` to a number `CHIP_DEVICE_CONFIG_DEVICE_FIRMWARE_REVISION_STRING` was introduced for the string version. It was done to be able to initialize the Basic cluster which requires the software/firmware version both as a number and a string.

**Comment by eve-cxrp** [comment]
I see, thank you @Damian-Nordic for sharing this information.
