### ISSUE TITLE
all-clusters-app and tv-app on linux fail to advertise over BLE

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6139]
Both All cluster app and tv-app fail to advertise over BLE on Raspi running Ubuntu OS with CHIP:DL: FAIL: BLE name is NULL in ConfigureBluezAdv

$ sudo ./out/host/chip-all-clusters-app --wifi
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:ZCL: 0xaaaab6fb8f10ep 1 clus 101 attr  3 not supported
CHIP:ZCL: Failed to write DoorState attribute: 0x86
CHIP:ZCL: 0xaaaab6fb8f10ep 1 clus 101 attr 21 not supported
CHIP:ZCL: Failed to write Language attribute: 0x86
CHIP:ZCL: Start identify callback on endpoint 1 time 0
CHIP:ZCL: Stop identify callback on endpoint 1
CHIP:ZCL: WARNING: ATTRIBUTES ARE NOT BEING STORED IN FLASH!
CHIP:ZCL: DEVICE WILL NOT FUNCTION PROPERLY AFTER REBOOTING!!
CHIP:ZCL: Failed to send IAS Zone update. Err 0x70
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x0000000000bc5c01
CHIP:DL: wpa_supplicant: _IsWiFiStationProvisioned: interface not connected
CHIP:BLE: Assigned local session key ID 0
CHIP:BLE: Waiting for PBKDF param request
CHIP:DIS: Start dns-sd server
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:SVR: Server Listening...
CHIP:DIS: Start dns-sd server
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DL: FAIL: BLE name is NULL in ConfigureBluezAdv
CHIP:DL: Disabling CHIPoBLE service due to error: CHIP Error 4003 (0x00000FA3): Incorrect state

**Comment by chuck-thomas** [comment]
Needed For TE2.
