### ISSUE TITLE
Implement CRMP to throw error  CHIP_ERROR_MESSAGE_TOO_LONG 

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6147]
Per spec section 4.14.4.2. 

4.14.4.2. Data Communication
Any attempt by a sender to send a message larger than the agreed upon maximum message size (CRMP_MAX_MESSAGE_SIZE) results in a CHIP_ERROR_MESSAGE_TOO_LONG error. Moreover, CRMP aborts the connection if an incoming message is larger than the acceptable message size negotiated during connection setup.

**Comment by pan-apple** [comment]
Fixed by #6174
