### ISSUE TITLE
Log messages for CASE and OpCreds

### ISSUE THREAD

**Issue by franck-apple** [project-chip/connectedhomeip#6148]
Need to log all the phases of the provisioning flow as shown in Fig 26 of section 5.3 (see images below). Since most of the messages exchanged during these phases are encrypted messages, we need to have verbose logs to make sure device completed all the phases mentioned in the provisioning flow

We need log messages that each of the phases in the commissioning flow is entered/completed.
![](https://user-images.githubusercontent.com/68604034/110896355-434e6c00-82b0-11eb-839c-c41b99e3aaca.png)

Concurrent connection commissioning flow
![](https://user-images.githubusercontent.com/68604034/110896026-970c8580-82af-11eb-9203-317e37ec4f40.png)

Non-concurrent commissioning flow
![](https://user-images.githubusercontent.com/68604034/110896078-b5728100-82af-11eb-800a-8daa50bdda78.png)

**Comment by pan-apple** [comment]
Added logs for Operational Credentials provisioning flow, and CASE Session setup state machine.
