### ISSUE TITLE
Add support for NetworkCommissioning cluster ScanNetworks command.

### ISSUE THREAD

**Issue by kkasperczyk-no** [project-chip/connectedhomeip#6201]
#### Problem
Currently not all NetworkCommissioning cluster commands are supported on the accessory side (device responds with default not supported messages), including ScanNetworks command. This issue is also tracked in the more general issue considering full NetworkCommissioning cluster support https://github.com/project-chip/connectedhomeip/issues/5619.

 #### Proposed Solution
Add implementation for emberAfNetworkCommissioningClusterScanNetworksCallback() method.

**Comment by arunbharadwaj** [comment]
Is ScanNetworks command now fully supported, or is this item still open?

**Comment by kkasperczyk-no** [comment]
@arunbharadwaj I don't know, as I stopped working on that item long time ago, so I'm not aware of the current state. I believe that maybe @erjiaqing could be able to answer that.
