### ISSUE TITLE
when CHIPTool scanning the QR code, nothing happened.

### ISSUE THREAD

**Issue by lylezhu2014** [project-chip/connectedhomeip#6219]
#### Problem
when CHIPTool scanning the QR code, nothing happened. 

 #### Proposed Solution
After open the URL of the QR code, I opened the CHIPTool APK of ceelphone  and selected the menu "SCAN QR CODE". Nothing happended when the CHIPTOOL scanning the QR code.

OS version, Andriod 9.

**Comment by lijinlei2011** [comment]
Hello ！ Could you share which phone model and Android version you use? Must i connect to the hotspot first, before use CHIPTool to scan the QR image?

 I use CHIPTool to scan the QR image but CHIPTool always displays "Scanning for BLE device 3840" and then "Device not found". Android Phone I am using is honor 10. Android version is 9.

Thanks,

Ray.

**Comment by woody-apple** [comment]
Given this is an older issue, does this till reproduce on current builds? Please re-open if so!
