### ISSUE TITLE
return spec defined CRMP error codes

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6243]
1. Per cert TC 6.1.2. https://github.com/project-chip/chip-test-plans/blob/master/src/securechannel.adoc#6127-test-procedure , if the TH sends a single message to DUT with a message size larger then CRMP_MAX_MESSAGE_SIZE and reliability bit set to 1 ,  DUT responds with an error message CHIP_ERROR_MESSAGE_TOO_LONG
2. per cert TC 6.1.4. https://github.com/project-chip/chip-test-plans/blob/master/src/securechannel.adoc#6147-test-procedure after the maximum number X of failed attempts has reached, DUT sends a message CHIP_ERROR_MESSAGE_NOT_ACKNOWLEDGED to the application layers

**Comment by turon** [comment]
Spec no longer mandates implementations use any particular error code.
All references to `CRMP_MAX_MESSAGE_SIZE`, `CHIP_ERROR_MESSAGE_TOO_LONG`, or `CHIP_ERROR_MESSAGE_NOT_ACKNOWLEDGED` (or `MRP_` variations) have been removed from spec.

Closing.
Removing tag `v1_triage_split_4`.
