### ISSUE TITLE
Generated ThreadInterfaceScanResult content doesn't meet with the spec.

### ISSUE THREAD

**Issue by kkasperczyk-no** [project-chip/connectedhomeip#6254]
#### Problem
Generated in ZAP tool ThreadInterfaceScanResult contains only `uint8_t * DiscoveryResponse`, while according to spec (11.9.6.1) it should have also `int8_t RSSI` and `uint8_t LQI` fields.

 #### Proposed Solution
Fix ThreadInterfaceScanResult structure and regenerate header files using ZAP tool.

**Comment by tcarmelveilleux** [comment]
Fixed at least since PR #12931
