### ISSUE TITLE
Echo Sever does't work on the applications with chip-shell

### ISSUE THREAD

**Issue by wqx6** [project-chip/connectedhomeip#6257]
### Problem
The application can't correctly respond to the ping command form chip-shell. 
### Description
1.Build the Linux examples in all-clusters-app and lighting-app using
```
gn gen out/debug --args='chip_bypass_rendezvous=true chip_app_use_echo=true'
ninja -C out/debug
```
2.Start the Linux application and send the ping command with chip-shell, the chip-shell receives no response, and the application log is 
```
CHIP:IN: Secure transport received message, but failed to decode it, discarding
```

**Comment by yufengwangca** [comment]
@gjc13 the real example app does not use TestSecret, you can not ping them directly from chip-shell without pairing first.

I tried pairing from chip-tool, ./chip-tool pairing bypass 192.168.86.171 11097. but it seems not working. We can either to add the ping command to chip-tool or pairing command to chip-shell
