### ISSUE TITLE
mDNS queries show dual IP address records on minimal mDNS when IP address changes

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#6263]
When using minimal mDNS, if IP address of network is changed, both the old and new IP address records will be returned in a query.

Eventually the 'old' IP address will be eliminated from the cache.

It appears that the old IP address is not being Removed.

**Comment by andy31415** [comment]
This is likely minMdns implementation not sending a 'clear cache' or 'leave' messages. We likely need to implement more of the mdns spec in minmdns.

**Comment by andy31415** [comment]
We are sending TTL=0 to clear cache since #19692. Assuming this one is fixed.
