### ISSUE TITLE
Building on Linux with chip_mdns="minimal" links in and calls UpdateMdnsDataset() and ProcessMdns() from the Avahi implementation

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#6265]
When building for a Linux platform, if the "minimal" mDNS configuration is used, the file src/platform/Linux/MdnsImpl.cpp is built and linked in (which is the Avahi implementation) and the entry points UpdateMdnsDataset() and ProcessMdns() from that file are called from src/include/platform/internal/GenericPlatformManagerImpl_POSIX.cpp

**Comment by woody-apple** [comment]
Given this is an older issue, is this complete at this point? If not, please re-open.
