### ISSUE TITLE
[TE2] chip-device-ctrl can't do NetworkCommissioning

### ISSUE THREAD

**Issue by wissn84** [project-chip/connectedhomeip#6306]
#### Problem
- controller (chip-device-ctrl) in Ubuntu 20.xx
- controllee (chip-lighting-app) in Ubuntu 20.xx 
- branch : test_event_2.2

I have tried to Commissioning between chip-device-ctrl and chip-lighting-app 

1. chip-device-ctrl > connect -ble 3840 20202021

`Secure Session to Device Established
Device temporary node id (**this does not match spec**): 860392
chip-device-ctrl > CHIP:DL: HandlePlatformSpecificBLEEvent 16387`

2. zcl NetworkCommissioning AddWiFiNetwork 12344321 1 0 ssid=str:chip credentials=str:qwerasdf breadcrumb=0 timeoutMs=1000

then I got error message like below
`An exception occurred during process ZCL command:
CHIP Error 4072 (0x00000FE8): Not connected`

So I check log of chip-lighting-app and got error called "Failed to store ~~"

`CHIP:SVR: Device completed SPAKE2+ handshake
CHIP:SVR: Device completed Rendezvous process
CHIP:SVR: Failed to store the connection state
CHIP:DL: UnregisterAdvertisement complete`

There exist Persistent Storage in in tmp folder but  There is empty file

Logs are attached
[chip-python-ctrl-20210426.txt](https://github.com/project-chip/connectedhomeip/files/6382102/chip-python-ctrl-20210426.txt)
[chip-lighting-server-20210426-error.txt](https://github.com/project-chip/connectedhomeip/files/6382103/chip-lighting-server-20210426-error.txt)

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by erjiaqing** [comment]
The nodeid is `860392` not `12344321`

**Comment by woody-apple** [comment]
Given this is an older issue, is this complete at this point? If not, please re-open.
