### ISSUE TITLE
Android CHIPTool will crash when using it to scan the QRCode on M5Stack 

### ISSUE THREAD

**Issue by Hugh-Bao** [project-chip/connectedhomeip#6310]
#### Problem
Using latest Android CHIPTool from master branch to scan the QRCode on M5Stack, CHIPTool APP will crash and exit.

The 'mBleLayer' in DeviceController is not initialized. 

In DeviceController::Init function,

#if CONFIG_NETWORK_LAYER_BLE
#if CONFIG_DEVICE_LAYER                         ------ it is defined to 0, the code do not enter this process
    if (params.bleLayer == nullptr)
    {
        params.bleLayer = DeviceLayer::ConnectivityMgr().GetBleLayer();
    }
#endif // CONFIG_DEVICE_LAYER
    mBleLayer = params.bleLayer;               ------- params.bleLayer is nullptr makes the mBleLayer be nullptr
    VerifyOrExit(mBleLayer != nullptr, err = CHIP_ERROR_INVALID_ARGUMENT);
#endif

**Comment by austinh0** [comment]
Fixed in #6315
