### ISSUE TITLE
Add configuration flags to SRP settings

### ISSUE THREAD

**Issue by tima-q** [project-chip/connectedhomeip#6320]
#### Problem
The SRP feature currently adds 3kB in ThreadStackManager alone when added due to the current default set.

The defined struct for the SRP settings are listed here:
https://github.com/project-chip/connectedhomeip/blob/85f0bc2667f1c23f311eaed8e54744d33d753d84/src/platform/OpenThread/GenericThreadStackManagerImpl_OpenThread.h#L120

 #### Proposed Solution
Create CHIP_DEVICE_CONFIG_THREAD_SRP_* flags to allow adjustment of:
* kMaxServicesNumber
* kMaxTxtEntriesNumber
* ... ?

**Comment by kkasperczyk-no** [comment]
I think that you could try reduce `kMaxTxtValueSize`, as it seems to be far bigger than it is necessary and maybe `kMaxTxtKeySize` too. You can take a look on this method to see what sizes are currently used when advertising: https://github.com/project-chip/connectedhomeip/blob/85f0bc2667f1c23f311eaed8e54744d33d753d84/src/lib/mdns/Discovery_ImplPlatform.cpp#L234 Be careful when reducing `kMaxTxtEntriesNumber`, as currently in Operational Advertising we use 2 entries, but e.g in Commissionable Advertising there are already 4 entries. Thread devices are not using it for now, but someday it will change.
