### ISSUE TITLE
Build system not very friendly for platformio.org

### ISSUE THREAD

**Issue by CodeChronos928** [project-chip/connectedhomeip#6322]
Hello folks,

I've been using https://platformio.org/ recently, which is great at bringing development flows for different boards into one place (toolchains, flashing, debugging, etc.).

Unfortunately, the CHIP repository's build system isn't very accommodating to it.

I might be able to get something like the ESP32 "all-clusters-example" built and flashed without modifying the CHIP repository if I can find the right CMake logic, however, I'd appreciate your thoughts on playing nicely (or less painfully) with PlatformIO's project management system.  I doubt I'm the only one trying to use it with CHIP -- it seems to have a significant user base.

Thanks!

**Comment by woody-apple** [comment]
Hi @CodeChronos928 Thanks for reaching out. I haven't used this personally, but it does look quite interesting. Would love some help from any interested contributor to have the repo play nicely with if it possible.
