### ISSUE TITLE
Add another entry point for MSCP received message re-entrance.

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#6340]
#### Problem
 Currently `peerNodeId`, `packetHeader`, `peerAddress`, `msgBuf` is stored for MSCP received message, which is delivered once MCSP is complemented. We may omit `packetHeader`, `peerAddress` fields by refactoring secure session manager, and add another entry point of `OnMessageReceived` which it only take `msgBuf` as argument.

**Comment by bzbarsky-apple** [comment]
Note that we don't even need to do any refactoring.  The current code that does message counter bits stores the header in the buffer and parses it out.  We just need to put that code back...
