### ISSUE TITLE
[TE2]  [ICMPv6]Destination Unreachable    when joined CHIP/thread network 

### ISSUE THREAD

**Issue by 568760310** [project-chip/connectedhomeip#6364]
[ICMP-Destination-Unreachable.zip](https://github.com/project-chip/connectedhomeip/files/6396327/ICMP-Destination-Unreachable.zip)

 #### question
When pairing Lock device of  nordic into a thread network according to TE2  Instructions .
After deice atteched to BR, there is an " ICMPv6  package " , I just wonder  why .
![image](https://user-images.githubusercontent.com/73684884/116502754-fd447a80-a8e6-11eb-87e3-967e0bdd5301.png)

Here is my LOCK  and BR addrs:
```
fda9:e910:c470:fd94:8d4:458c:c9bf:a6f4
fdea:de07:60c6:2120:0:ff:fe00:3401
fdea:de07:60c6:2120:f637:4165:73d5:dac0
fe80:0:0:0:c85e:67c6:2012:71f0

wpan0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet6 fdea:de07:60c6:2120:0:ff:fe00:3400  prefixlen 64  scopeid 0x0<global>
        inet6 fdea:de07:60c6:2120:0:ff:fe00:fc10  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::3c32:e907:44e8:7ce0  prefixlen 64  scopeid 0x20<link>
        inet6 fdea:de07:60c6:2120::fc38  prefixlen 64  scopeid 0x0<global>
        inet6 fda9:e910:c470:fd94:afd6:fa69:9799:1335  prefixlen 64  scopeid 0x0<global>
        inet6 fdea:de07:60c6:2120:0:ff:fe00:fc11  prefixlen 64  scopeid 0x0<global>
        inet6 fdea:de07:60c6:2120:0:ff:fe00:fc00  prefixlen 64  scopeid 0x0<global>
        inet6 fdea:de07:60c6:2120:2ed1:5544:974:6734  prefixlen 64  scopeid 0x0<global>
```

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
