### ISSUE TITLE
chip-tool can't pairing to chip-lighting-app

### ISSUE THREAD

**Issue by wissn84** [project-chip/connectedhomeip#6391]
#### Problem
chip-tool can't not pairing to chip-lighting-app.
log is below because of invalid endpoint during networking commissioning.

`CHIP:EM: ec pos: 1, id: 17768, Delegate: 0xdd6e1b70
CHIP:SVR: Packet received from Node:1b669: 40 bytes
CHIP:ZCL: APS frame processing success!
CHIP:ZCL: RX len 29, ep 0, clus 0x31
CHIP:ZCL:  FC 1 seq 0 cmd 2 payload[
CHIP:ZCL: 04 63 68 69 70 08 71 77 65 72 61 73 64 66 00 00 00 00 00 00 00 00 70 17 00 00
CHIP:ZCL: ]
CHIP:ZCL: Drop cluster 0x31 command 0x2
CHIP:ZCL:  due to invalid endpoint:
CHIP:ZCL: 0x0
CHIP:ZCL: Data model processing failure!`

 #### Proposed Solution
chip-tool use endpoint 0 for networking commissions .
but example endpoint is 1.
We need to modify to change endpoint 0 to 1.

**Comment by lazarkov** [comment]
Can you leave steps to reproduce this issue?

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
