### ISSUE TITLE
Add delegate support for CHIPCircularTLVBuffer, and update ReclaimEventCtx

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#6429]
mAppData is used for ReclaimEventCtx, which has 
struct ReclaimEventCtx
{
    CircularEventBuffer * mpEventBuffer = nullptr;
    size_t mSpaceNeededForMovedEvent    = 0;
};

when debug buffer is full, we try to evict event to next buffer, we need to get to know how much space for evicted event in debug buffer 

EvictHead function(https://github.com/project-chip/connectedhomeip/blob/master/src/lib/core/CHIPCircularTLVBuffer.cpp#L117) would check and call this mProcessEvictedElement function, this function could be AlwaysFail or EvictEvent, if that is EvictEvent, it will check if the tail's event can be moved to higher priority, if not, dropped, if yes, note how much space it needs.

I would use delegate to get rid void pattern in follow-up PR, thanks

_Originally posted by @yunhanw-google in https://github.com/project-chip/connectedhomeip/pull/6366#discussion_r624942829_

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
