### ISSUE TITLE
Add delegate support for CHIPTLVUtilities.cpp, and update CopyEventSince callback

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#6430]
CHIP_ERROR EventManagement::CopyEventsSince(const TLVReader & aReader, size_t aDepth, void * apContext) is used by  err = TLV::Utilities::Iterate(reader, CopyEventsSince, &context, recurse) in FetchEventSince function, Iterate function is https://github.com/project-chip/connectedhomeip/blob/master/src/lib/core/CHIPTLVUtilities.cpp#L62
I would create the follow-up PR to have the delegate pass to achieve typesafe, thanks

_Originally posted by @yunhanw-google in https://github.com/project-chip/connectedhomeip/pull/6366#discussion_r624912561_

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
