### ISSUE TITLE
Investigate the option to 'computer size' without an underlying buffer in TLV

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#6433]
nit/followup: most other systems (e.g. protobufs or even our CHIP endian writers) have an option to have a 'null output' that does not write anything and are just used to compute sizes.

Requiring an allocation of  a packet buffer handle just to do a size computation seems wasteful. TLV should have the option to 'compute size' without an underlying buffer.

_Originally posted by @andy31415 in https://github.com/project-chip/connectedhomeip/pull/6366#r625226467_

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
