### ISSUE TITLE
chip tool to fix resolve cmd on raspi

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6457]
chip tool to fix resolve cmd on raspi

/examples/chip-tool$ ./out/debug/chip-tool discover resolve 12344321 0
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:TOO: Mdns: Searching for NodeId: bc5c01 FabricId: 0 ...
CHIP:DL: CHIP task running
CHIP:TOO: No response from device
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller
CHIP:DL: System Layer shutdown
CHIP:DL: Inet Layer shutdown
CHIP:DL: BLE layer shutdown
CHIP:TOO: Run command failure: CHIP Error 4172 (0x0000104C): Internal error

**Comment by cjandhyala** [comment]
Resolve command fails after the pairing, on ToT today, below commit ID

commit dab17fb378ffc342d94b754a8f03f8d034b9addf (HEAD -> master)
Author: Vivien Nicolas <vnicolas@apple.com>
Date:   Tue May 4 19:18:41 2021 +0200

    Add a Test Cluster in order to validate the generation/implementation of the Data Model (#6445)
    
    * Add a Test Cluster
    
    * Activate the Test Cluster server into multiples ZAP configuration
    
    * Update Darwin tests to use the Test Cluster
    
    * Update gen/ folders



$ ./out/debug/chip-tool discover resolve 12344321 0
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:TOO: Mdns: Searching for NodeId: bc5c01 FabricId: 0 ...
CHIP:DL: CHIP task running
CHIP:TOO: No response from device
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller
CHIP:DL: System Layer shutdown
CHIP:DL: Inet Layer shutdown
CHIP:DL: BLE layer shutdown
CHIP:TOO: Run command failure: CHIP Error 4172 (0x0000104C): Internal error
ubuntu@ubuntuservercontroller:~/chipCode/chip_0422/connectedhomeip/examples/chip-tool$ ./out/debug/chip-tool discover resolve 12344321 1
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:TOO: Mdns: Searching for NodeId: bc5c01 FabricId: 1 ...
CHIP:DL: CHIP task running
CHIP:TOO: No response from device
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller
CHIP:DL: System Layer shutdown
CHIP:DL: Inet Layer shutdown
CHIP:DL: BLE layer shutdown
CHIP:TOO: Run command failure: CHIP Error 4172 (0x0000104C): Internal error

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
