### ISSUE TITLE
SessionEstablishmentExchangeDispatch.cpp encodes a default-initialized packer header

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#6464]
#### Problem
`SessionEstablishmentExchangeDispatch::SendMessageImpl` encodes a default-initialized packer header into the message.  That doesn't make much sense to me, especially given that we don't actually have a clear definition of what default-initializing a packet header initializes it to.

 #### Proposed Solution
Initialize the header to the values we want here.

@pan-apple

**Comment by yufengwangca** [comment]
not valid
