### ISSUE TITLE
Factory reset doesn't clear KVS admin pairings

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#6475]
#### Problem
Factory reset doesn't reset admin pairings. This definitely happens on M5, unsure about others

 #### Proposed Solution
Reset admins on Factory reset - should be done in a way that this works for all platforms.

**Comment by holbrookt** [comment]
@cecille any idea if this is still an issue?

**Comment by cecille** [comment]
I'm not sure - sorry. I do think we need factory resets to be working properly for v1.0, but I'm not sure if it's something that's explicitly covered by the SDK vs. something that's covered by platform. @harimau-qirex may have a better idea as it touches on storage.

**Comment by woody-apple** [comment]
Factory reset is handled per platform, as the matter doesn't really support Factory reset at this point.
