### ISSUE TITLE
Generated request/response struct specs for General Commands

### ISSUE THREAD

**Issue by wehale** [project-chip/connectedhomeip#655]
#### Problem
We'll need generated request/response struct specs for General Commands. We never created these for Dotdot ZCL implementation due to the use of CoAP, we'll need these for general ZCL General message handling.

 #### Proposed Solution
Create generated request/response struct specs for General Commands

**Comment by woody-apple** [comment]
SW BRB: Closing this as we're covering this in @vivien-apple 's work
