### ISSUE TITLE
Add codec api to core-data-model (formerly attribute-db)

### ISSUE THREAD

**Issue by wehale** [project-chip/connectedhomeip#656]
#### Problem
We'll need a way to interact with the core-data-model so that the proper struct specs can be retrieved based on given Endpoint, cluster, etc... These can then be sent off to the codec for message parsing.

 #### Proposed Solution
Create API in core-data-model for interaction with the codec

**Comment by woody-apple** [comment]
SW BRB: @vivien-apple @rwalker-apple is this needed still?

**Comment by rwalker-apple** [comment]
no longer relevant
