### ISSUE TITLE
(chip-device-ctrl) calling resolve does not send out mdns query

### ISSUE THREAD

**Issue by SurekhaMuralidharan777** [project-chip/connectedhomeip#6607]
#### Problem

Steps:
1. sync the latest master for connectedhomeip
2. build and run chip-device-ctrl
3. run the command "resolve <device ip> <node id>"

Expected Result:

resolve sends out an mdns query which the chip device can respond to

Actual Result:

resolve does not send out any mdns query

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
