### ISSUE TITLE
Lighting-app-example crashes

### ISSUE THREAD

**Issue by kai0989** [project-chip/connectedhomeip#6617]
#### Problem
I tried to run chip-lighting-app on raspberry pi4 but the application crashes:

$ ./chip-lighting-app --wifi

CHIP:DL: Device Configuration:
CHIP:DL:   Serial Number: TEST_SN
CHIP:DL:   Vendor Id: 9050 (0x235A)
CHIP:DL:   Product Id: 65279 (0xFEFF)
CHIP:DL:   Product Revision: 1
CHIP:DL:   Setup Pin Code: 20202021
CHIP:DL:   Setup Discriminator: 3840 (0xF00)
CHIP:DL:   Manufacturing Date: (not set)
CHIP:DL:   Device Type: 257 (0x101)
CHIP:SVR: SetupQRCode: [CH:YNJV793700A50324800]
CHIP:SVR: Copy/paste the below URL in a browser to see the QR Code:
CHIP:SVR: https://dhrishi.github.io/connectedhomeip/qrcode.html?data=CH%3AYNJV793700A50324800
CHIP:SVR: Manual pairing code: [34970112332]
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:DIS: Init admin pairing table with server storage.
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x0000000000bc5c01
CHIP:DL: wpa_supplicant: _IsWiFiStationProvisioned: interface not connected
CHIP:BLE: Assigned local session key ID 0
CHIP:BLE: Waiting for PBKDF param request
CHIP:DIS: Start dns-sd server
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
Segmentation fault (core dumped)

Looks like wpa_supplicant reports wpa_supplicant: _IsWiFiStationProvisioned: interface not connected.
wlan0 is connected to wifi and got an IPv4

**Comment by erjiaqing** [comment]
Dup #6643
