### ISSUE TITLE
How do i use zap files

### ISSUE THREAD

**Issue by ChengqiangShe** [project-chip/connectedhomeip#6653]
#### How do i use zap files
In the connectedhomeip/examples/lighting-app/lighting-common directory, you can see lighting-app.zap, but how should I use or modify this file.

**Comment by markus-becker-tridonic-com** [comment]
You can use the script https://github.com/project-chip/connectedhomeip/blob/master/scripts/tools/zap/configure.sh to start the zap tool. You need to install a few dependencies beforehand: https://github.com/project-chip/zap/tree/f2ef0141a099cfb6226f88edb9d341fe594884ee#quick-instructions.

Once you opened the zap file, you can modify it to meet your cluster needs. Save it and run 
https://github.com/project-chip/connectedhomeip/blob/master/scripts/tools/zap_regen_all.py
which will re-generate the files in the gen/ folder.

**Comment by ChengqiangShe** [comment]
Thanks

**Comment by markus-becker-tridonic-com** [comment]
@ChengqiangShe any other questions or would you close the issue?
