### ISSUE TITLE
Update CHIP Op Certificate Tool with Local APIs 

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#6657]
chip-cert tool (#6403) mostly uses OpenSSL functions to operate with certificates and private keys. Some of these functions can be replaced with local APIs implemented in `src/credentials/GenerateChipX509Cert.cpp`. Once these local APIs are enhanced as part of #6656 work - this tool can be updated to use them.

@pan-apple

**Comment by woody-apple** [comment]
Does appear required for v1.0 tooling
