### ISSUE TITLE
Python Chip Controller waits for response indefinitely period of time

### ISSUE THREAD

**Issue by doublemis1** [project-chip/connectedhomeip#6669]
#### Problem
The Python Chip Controller after sending zcl command wait an indefinitely period of time for a response from the chip accessory.
If there is no response the Controller gets stuck and a restart is needed.

 #### Proposed Solution
The Python Chip Controller should have implemented a timeout for zcl command response. The Python Chip Controller should raise error or proper log should be visible on terminal

**Comment by kkasperczyk-no** [comment]
I verified that timeout seems to work properly on the current master branch commit https://github.com/project-chip/connectedhomeip/commit/1c2bca58e1fa307ebe7597634afe168d44738bdd. After sending zcl command to unreachable device I got following message:
`CHIP:DMG: Time out! failed to receive invoke command response from Exchange: 39026`.

**Comment by kkasperczyk-no** [comment]
Closing as issue seems to be resolved, by one of the IM PRs.
