### ISSUE TITLE
FIXED_DEVICE_IDS and FIXED_DEVICE_VERSIONS in generated endpoint_config.h files do not reflect .zap files

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#6757]
The arrays FIXED_DEVICE_IDS and FIXED_DEVICE_VERSIONS in generated endpoint_config.h always contain the static values 0 for DEVICE_ID and 1 for DEVICE_VERSION

For example, the lighting example app uses a Device Type of 0x0101 (LO Dimmable Bulb), yet the FIXED_DEVICE_ID array has 0 for DEVICE_ID.

in third_party/zap/repo/src-electron/generator/helper-endpointconfig.js we see:
```
  endpointTypes.forEach((ept) => {
    ...
    let device = {
      deviceId: 0,
      deviceVersion: 1,
    }
   ...
}
```
and these values never appear to get overridden.

**Comment by woody-apple** [comment]
Looks resolved?
