### ISSUE TITLE
zclread hung-up when reading basic information cluster 

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#6759]
After IM code integrated (commit d65d411cf58490b11174d7b9870046d52b951cd8 ), zclread hung-up when reading basic information cluster attributes

chip-device-ctrl > zcl OnOff Toggle 12344321 1 0
CHIP:DMG: ICR moving to [AddCommand]
CHIP:DL: Chip stack locking error at '../../../../../src/system/SystemLayer.cpp:204'. Code is unsafe/racy
CHIP:IN: Secure message was encrypted: Msg ID 3
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 150175575 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:DMG: ICR moving to [   Sending]
CHIP:IN: Secure transport received message destined to node ID (112233)
CHIP:EM: Received message of type 9 and protocolId 327680
CHIP:DMG: InvokeCommand =
CHIP:DMG: {
CHIP:DMG: 	CommandList =
CHIP:DMG: 	[
CHIP:DMG: 		CommandDataElement =
CHIP:DMG: 		{
CHIP:DMG: 			CommandPath =
CHIP:DMG: 			{
CHIP:DMG: 				EndpointId = 0x1,
CHIP:DMG: 				ClusterId = 0x6,
CHIP:DMG: 				CommandId = 0x2,
CHIP:DMG: 			},
CHIP:DMG: 			
CHIP:DMG: 			StatusElement =
CHIP:DMG: 			{
CHIP:DMG: 				GeneralCode = 0x0,
CHIP:DMG: 				ProtocolId = 0x5,
CHIP:DMG: 				protocolCode = 0x86,
CHIP:DMG: 			},
CHIP:DMG: 			
CHIP:DMG: 		},
CHIP:DMG: 		
CHIP:DMG: 	],
CHIP:DMG: 	
CHIP:DMG: }
SetCommandIndexStatus commandHandle=281472872257760 commandIndex=1
CHIP:DMG: ICR moving to [Initialize]
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 134
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
chip-device-ctrl > 
chip-device-ctrl > zclread Basic VendorName 12344321 1 0
CHIP:ZCL: Successfully encoded 11 bytes
CHIP:IN: Secure message was encrypted: Msg ID 4
CHIP:IN: Sending msg from 0x000000000001b669 to 0x0000000000bc5c01 at utc time: 150218030 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: SendMessage returned No Error

**Comment by franck-apple** [comment]
#6802 has merged and #6761 has closed. Can we now close this one?
