### ISSUE TITLE
build  failed  in docker with  Debian GNU/Linux 9 (stretch)

### ISSUE THREAD

**Issue by Shanlovana** [project-chip/connectedhomeip#6778]
#### Problem
root@eb88c55f77ba:/connectedhomeip# source scripts/activate.sh

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  ACTIVATOR! This sets your shell environment variables.

Activating environment (setting environment variables):

  Setting environment variables for CIPD package manager...done
  Setting environment variables for Python environment.....done
  Setting environment variables for Host tools.............done

Checking the environment:

20210513 13:46:11 INF Environment passes all checks!

Environment looks good, you are ready to go!

root@eb88c55f77ba:/connectedhomeip# gn gen out/host
Done. Made 1724 targets from 184 files in 247ms
root@eb88c55f77ba:/connectedhomeip# gn gen out/host
Done. Made 1724 targets from 184 files in 243ms
root@eb88c55f77ba:/connectedhomeip# ninja -C out/host
ninja: Entering directory `out/host'
[17/700] ACTION //src/platform/Linux/...//build/toolchain/host:linux_x64_gcc)
FAILED: gen/include/platform/Linux/dbus/wpa/DBusWpa.c gen/include/platform/Linux/dbus/wpa/DBusWpa.h
python3 ../../build/chip/linux/gen_gdbus_wrapper.py --input ../../src/platform/Linux/dbus/wpa/DBusWpa.xml --output_c gen/include/platform/Linux/dbus/wpa/DBusWpa.c --output_h gen/include/platform/Linux/dbus/wpa/DBusWpa.h --c-namespace Wpa
Usage: gdbus-codegen [options]

gdbus-codegen: error: no such option: --body
Traceback (most recent call last):
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 81, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 67, in main
    subprocess.check_call(gdbus_args)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gdbus-codegen', '--body', '--output', 'gen/include/platform/Linux/dbus/wpa/DBusWpa.c', '--c-namespace', 'Wpa', '../../src/platform/Linux/dbus/wpa/DBusWpa.xml']' returned non-zero exit status 2.
[18/700] ACTION //src/platform/Linux/...//build/toolchain/host:linux_x64_gcc)
FAILED: gen/include/platform/Linux/dbus/wpa/DBusWpaNetwork.c gen/include/platform/Linux/dbus/wpa/DBusWpaNetwork.h
python3 ../../build/chip/linux/gen_gdbus_wrapper.py --input ../../src/platform/Linux/dbus/wpa/DBusWpaNetwork.xml --output_c gen/include/platform/Linux/dbus/wpa/DBusWpaNetwork.c --output_h gen/include/platform/Linux/dbus/wpa/DBusWpaNetwork.h --c-namespace Wpa
Usage: gdbus-codegen [options]

gdbus-codegen: error: no such option: --body
Traceback (most recent call last):
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 81, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 67, in main
    subprocess.check_call(gdbus_args)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gdbus-codegen', '--body', '--output', 'gen/include/platform/Linux/dbus/wpa/DBusWpaNetwork.c', '--c-namespace', 'Wpa', '../../src/platform/Linux/dbus/wpa/DBusWpaNetwork.xml']' returned non-zero exit status 2.
[19/700] ACTION //src/platform/Linux/...//build/toolchain/host:linux_x64_gcc)
FAILED: gen/include/platform/Linux/dbus/bluez/DbusBluez.c gen/include/platform/Linux/dbus/bluez/DbusBluez.h
python3 ../../build/chip/linux/gen_gdbus_wrapper.py --input ../../src/platform/Linux/dbus/bluez/DbusBluez.xml --output_c gen/include/platform/Linux/dbus/bluez/DbusBluez.c --output_h gen/include/platform/Linux/dbus/bluez/DbusBluez.h --c-namespace Bluez --interface-prefix org.bluez --c-generate-object-manager
Usage: gdbus-codegen [options]

gdbus-codegen: error: no such option: --body
Traceback (most recent call last):
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 81, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 67, in main
    subprocess.check_call(gdbus_args)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gdbus-codegen', '--body', '--output', 'gen/include/platform/Linux/dbus/bluez/DbusBluez.c', '--c-namespace', 'Bluez', '--interface-prefix', 'org.bluez', '--c-generate-object-manager', '../../src/platform/Linux/dbus/bluez/DbusBluez.xml']' returned non-zero exit status 2.
[20/700] ACTION //src/platform/Linux/...//build/toolchain/host:linux_x64_gcc)
FAILED: gen/include/platform/Linux/dbus/wpa/DBusWpaInterface.c gen/include/platform/Linux/dbus/wpa/DBusWpaInterface.h
python3 ../../build/chip/linux/gen_gdbus_wrapper.py --input ../../src/platform/Linux/dbus/wpa/DBusWpaInterface.xml --output_c gen/include/platform/Linux/dbus/wpa/DBusWpaInterface.c --output_h gen/include/platform/Linux/dbus/wpa/DBusWpaInterface.h --c-namespace Wpa
Usage: gdbus-codegen [options]

gdbus-codegen: error: no such option: --body
Traceback (most recent call last):
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 81, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/connectedhomeip/out/host/../../build/chip/linux/gen_gdbus_wrapper.py", line 67, in main
    subprocess.check_call(gdbus_args)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gdbus-codegen', '--body', '--output', 'gen/include/platform/Linux/dbus/wpa/DBusWpaInterface.c', '--c-namespace', 'Wpa', '../../src/platform/Linux/dbus/wpa/DBusWpaInterface.xml']' returned non-zero exit status 2.
[23/700] c++ obj/src/inet/libInetLayer.IPPrefix.cpp.o
FAILED: obj/src/inet/libInetLayer.IPPrefix.cpp.o
g++ -MMD -MF obj/src/inet/libInetLayer.IPPrefix.cpp.o.d -Wconversion -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Wextra -Wshadow -Wunreachable-code -Werror -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wno-cast-function-type -fdiagnostics-color -fno-strict-aliasing -std=gnu++14 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -DLWIP_IPV4=1 -DLWIP_IPV6=1 -DLWIP_API=1 -DLWIP_ETHERNET=1 -DLWIP_SLIP=0 -DLWIP_6LOWPAN=1 -DLWIP_PPP=1 -I../../src/include -I../../src -Igen/include -I../../config/standalone -I../../src/lib -I../../third_party/nlassert/repo/include -I../../third_party/nlio/repo/include -I../../third_party/nlfaultinjection/repo/include -I../../src/lwip/standalone -I../../third_party/lwip/repo/lwip/src/include -c ../../src/inet/IPPrefix.cpp -o obj/src/inet/libInetLayer.IPPrefix.cpp.o
../../src/inet/IPPrefix.cpp: In member function ‘bool chip::Inet::IPPrefix::MatchAddress(const chip::Inet::IPAddress&) const’:
../../src/inet/IPPrefix.cpp:65:33: error: conversion to ‘uint8_t {aka unsigned char}’ from ‘int’ may alter its value [-Werror=conversion]
     uint8_t l = (Length <= 128) ? Length : 128;
                 ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-cast-function-type’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
[38/700] c++ obj/src/crypto/libChipCrypto.CHIPCryptoPALOpenSSL.cpp.o
FAILED: obj/src/crypto/libChipCrypto.CHIPCryptoPALOpenSSL.cpp.o
g++ -MMD -MF obj/src/crypto/libChipCrypto.CHIPCryptoPALOpenSSL.cpp.o.d -Wconversion -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Wextra -Wshadow -Wunreachable-code -Werror -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wno-cast-function-type -fdiagnostics-color -fno-strict-aliasing -std=gnu++14 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -DLWIP_IPV4=1 -DLWIP_IPV6=1 -DLWIP_API=1 -DLWIP_ETHERNET=1 -DLWIP_SLIP=0 -DLWIP_6LOWPAN=1 -DLWIP_PPP=1 -I../../src/include -I../../src -Igen/include -I../../src/lib -I../../config/standalone -I../../third_party/nlassert/repo/include -I../../third_party/nlio/repo/include -I../../third_party/nlfaultinjection/repo/include -I../../src/lwip/standalone -I../../third_party/lwip/repo/lwip/src/include -c ../../src/crypto/CHIPCryptoPALOpenSSL.cpp -o obj/src/crypto/libChipCrypto.CHIPCryptoPALOpenSSL.cpp.o
../../src/crypto/CHIPCryptoPALOpenSSL.cpp: In member function ‘virtual CHIP_ERROR chip::Crypto::HKDF_sha::HKDF_SHA256(const uint8_t*, size_t, const uint8_t*, size_t, const uint8_t*, size_t, uint8_t*, size_t)’:
../../src/crypto/CHIPCryptoPALOpenSSL.cpp:409:46: error: ‘EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND’ was not declared in this scope
     result = EVP_PKEY_CTX_hkdf_mode(context, EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND);
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/crypto/CHIPCryptoPALOpenSSL.cpp:409:84: error: ‘EVP_PKEY_CTX_hkdf_mode’ was not declared in this scope
     result = EVP_PKEY_CTX_hkdf_mode(context, EVP_PKEY_HKDEF_MODE_EXTRACT_AND_EXPAND);
                                                                                    ^
../../src/crypto/CHIPCryptoPALOpenSSL.cpp: In function ‘CHIP_ERROR chip::Crypto::DRBG_get_bytes(uint8_t*, size_t)’:
../../src/crypto/CHIPCryptoPALOpenSSL.cpp:475:87: error: ‘RAND_priv_bytes’ was not declared in this scope
     result = RAND_priv_bytes(Uint8::to_uchar(out_buffer), static_cast<int>(out_length));
                                                                                       ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-cast-function-type’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
[39/700] c++ obj/src/transport/retran...ts/libRetransmitTests.TestCache.cpp.o
FAILED: obj/src/transport/retransmit/tests/libRetransmitTests.TestCache.cpp.o
g++ -MMD -MF obj/src/transport/retransmit/tests/libRetransmitTests.TestCache.cpp.o.d -Wconversion -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -Wall -Wextra -Wshadow -Wunreachable-code -Werror -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wno-cast-function-type -fdiagnostics-color -fno-strict-aliasing -std=gnu++14 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -DLWIP_IPV4=1 -DLWIP_IPV6=1 -DLWIP_API=1 -DLWIP_ETHERNET=1 -DLWIP_SLIP=0 -DLWIP_6LOWPAN=1 -DLWIP_PPP=1 -I../../src/include -I../../src -Igen/include -I../../src/lib -I../../config/standalone -I../../third_party/nlassert/repo/include -I../../third_party/nlio/repo/include -I../../third_party/nlfaultinjection/repo/include -I../../src/lwip/standalone -I../../third_party/lwip/repo/lwip/src/include -I../../third_party/nlunit-test/repo/src -c ../../src/transport/retransmit/tests/TestCache.cpp -o obj/src/transport/retransmit/tests/libRetransmitTests.TestCache.cpp.o
../../src/transport/retransmit/tests/TestCache.cpp:95:57: error: specialization of ‘template<class PayloadType> static PayloadType chip::Retransmit::Lifetime<PayloadType>::Acquire(PayloadType&)’ in different namespace [-fpermissive]
 int chip::Retransmit::Lifetime<int>::Acquire(int & value)
                                                         ^
In file included from ../../src/transport/retransmit/tests/TestCache.cpp:21:0:
../../src/transport/retransmit/Cache.h:36:24: error:   from definition of ‘template<class PayloadType> static PayloadType chip::Retransmit::Lifetime<PayloadType>::Acquire(PayloadType&)’ [-fpermissive]
     static PayloadType Acquire(PayloadType & payload);
                        ^~~~~~~
../../src/transport/retransmit/tests/TestCache.cpp:102:58: error: specialization of ‘template<class PayloadType> static void chip::Retransmit::Lifetime<PayloadType>::Release(PayloadType&)’ in different namespace [-fpermissive]
 void chip::Retransmit::Lifetime<int>::Release(int & value)
                                                          ^
In file included from ../../src/transport/retransmit/tests/TestCache.cpp:21:0:
../../src/transport/retransmit/Cache.h:37:17: error:   from definition of ‘template<class PayloadType> static void chip::Retransmit::Lifetime<PayloadType>::Release(PayloadType&)’ [-fpermissive]
     static void Release(PayloadType & payload);
                 ^~~~~~~
cc1plus: error: unrecognized command line option ‘-Wno-cast-function-type’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1plus: all warnings being treated as errors
[42/700] c++ obj/src/setup_payload/te...libSetupPayloadTests.TestQRCode.cpp.o
ninja: build stopped: subcommand failed.

 #### Proposed Solution

     git gcc g++ python pkg-config libssl-dev libdbus-1-dev \
     libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev \
     python3-pip unzip libgirepository1.0-dev libcairo2-dev

all installed 
but still error
thanks for help

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
