### ISSUE TITLE
CommandSender->SendCommandRequest - always pass secureSession

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#6792]
#### Problem
Right now, the secureSession is a nullable pointer by default - sending nullptr causes the command sender to create a new exchange context with a key id of 0. Right now, this is needed to preserve some of the test functionality. If possible, this should be changed to a non-optional value and always passed (SecureSessionHandle &).

 #### Proposed Solution
Investigate if tests can be updated to pass the secure session to the SendCommandRequest.

**Comment by kghost** [comment]
I think this is resolved by #10916
