### ISSUE TITLE
NodeId should be optional in AttributePathParams

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#6793]
I know why it's in there, sure.  I'm just saying most devices (esp. constrained ones) will not actually need it.  Followup tracking that is fine.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/6356#r622415454_

**Comment by bzbarsky-apple** [comment]
AttributePathParams no longer has NodeId at all.
