### ISSUE TITLE
Switch NetworkInterfaceType Name member to CHAR_STRING

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#6805]
#### Problem
We don't support CHAR_STRING in structs yet.  So for now the Name of NetworkInterfaceType in `src/app/zap-templates/zcl/custom-types.xml` is OCTET_STRING.

 #### Proposed Solution
Once CHAR_STRING is supported in structs, use it here.

@vivien-apple

**Comment by bzbarsky-apple** [comment]
Might be a dup of https://github.com/project-chip/connectedhomeip/issues/6112

**Comment by mrjerryjohns** [comment]
I can't seem to find `NetworkInterfaceType` in the cluster specs anymore. More-over, char string is now supported. Marking as stale.

**Comment by bzbarsky-apple** [comment]
> I can't seem to find NetworkInterfaceType in the cluster specs anymore

In the spec it's called "NetworkInterface struct".  In our XML it's NetworkInterfaceType.

That said, its Name is CHAR_STRING in the XML, so we're good.
