### ISSUE TITLE
Do not use /tmp directory for persistent storage

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#6811]
#### Problem
chip-tool uses /tmp as a directory for persistent storage, see examples/chip-tool/config/PersistentStorage.cpp.

This is not good since by definition the contents of /tmp are not persistent.

 #### Proposed Solution
Use anything else but not /tmp.

**Comment by yunhanw-google** [comment]
@bzbarsky-apple @yufengwangca any reasoning for us to use tmp?

**Comment by bzbarsky-apple** [comment]
@vivien-apple might know, though he might also be off for the rest of the week....

In any case, we could try putting this somewhere else; the question is where.  `${HOME}/.matter` or something?

**Comment by tcarmelveilleux** [comment]
I would argue that the location of the settings should never be assumed to have a default, and a command-line argument should have the path for the storage root, on hosts. The test scripts that run the different tools should pass-in appropriate values. The reason to avoid a default is that defaults just work if a single "thing" is used, or if we make strong assumption about how the storage is done, such that collisions of stored state is not possible.

**Comment by mspang** [comment]
/tmp honestly sounds right to me since we just base64 encoding C structs...

Without adopting a backwards compatible storage format, long term persistence is impossible anyway.

**Comment by mspang** [comment]
(the current format is not even ABI stable so it's really quite problematic)

**Comment by kpschoedel** [comment]
Any hard-coded location is painful when using multiple devices.

**Comment by bluebin14** [comment]
Based on input a more flexible solution is needed that also allows multi controller and multi device support. Basically adding some command line options. Closing this and opening https://github.com/project-chip/connectedhomeip/issues/9818
