### ISSUE TITLE
Update AdminPairingTable (and other uses of Admin) to Fabric Context

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#6826]
#### Problem
The code is currently using `Admin` to reflect different `Fabric`. The spec has evolved since the code was initially written. The code should be updated to match the spec.

 #### Proposed Solution
Update the code.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
