### ISSUE TITLE
Compilation fail for all-clusters-app on ESP32

### ISSUE THREAD

**Issue by fengbowe** [project-chip/connectedhomeip#6845]
#### Problem
compilation fail during linking:

/Users/fengbowe/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/chip/lib/libCHIP.a(libCHIPDataModel.CommandHandler.cpp.o):(.literal._ZN4chip3app14CommandHandler25ProcessCommandDataElementERNS0_18CommandDataElement6ParserE+0x8): undefined reference to `chip::app::DispatchSingleClusterCommand(unsigned short, unsigned char, unsigned char, chip::TLV::TLVReader&, chip::app::Command*)'
/Users/fengbowe/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/chip/lib/libCHIP.a(libCHIPDataModel.CommandHandler.cpp.o): in function `chip::app::CommandHandler::ProcessCommandDataElement(chip::app::CommandDataElement::Parser&)':
/Users/fengbowe/Documents/CHIP/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/app/CommandHandler.cpp:101: undefined reference to `chip::app::DispatchSingleClusterCommand(unsigned short, unsigned char, unsigned char, chip::TLV::TLVReader&, chip::app::Command*)'
/Users/fengbowe/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/chip/lib/libCHIP.a(libCHIPDataModel.CommandSender.cpp.o): in function `chip::app::CommandSender::ProcessCommandDataElement(chip::app::CommandDataElement::Parser&)':
/Users/fengbowe/Documents/CHIP/connectedhomeip/examples/all-clusters-app/esp32/build/esp-idf/chip/../../../../../../config/esp32/third_party/connectedhomeip/src/app/CommandSender.cpp:162: undefined reference to `chip::app::DispatchSingleClusterCommand(unsigned short, unsigned char, unsigned char, chip::TLV::TLVReader&, chip::app::Command*)'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

 #### Details

OS: Mac 10.15.7 

commit:
commit d7c56ff93aa1e87199a3cd097d217c905138843d (HEAD -> master, origin/master, origin/HEAD)
Author: Pankaj Garg <pgarg2@apple.com>
Date:   Fri May 14 16:56:54 2021 -0700

    Persist keypair used by example opcert signer (#6821)
    
    * Persist keypair used by example opcert signer
    
    * Fix Android build

Repro steps:
(1) mkdir ${HOME}/tools
(2) cd ${HOME}/tools
(3) git clone https://github.com/espressif/esp-idf.git
(4) cd esp-idf
(5) git checkout release/v4.2
(6) git submodule update --init
(7) export IDF_PATH=${HOME}/tools/esp-idf
(8) ./install.sh
(9) . ./export.sh
(10) cd ${HOME}
(11) git clone https://github.com/project-chip/connectedhomeip.git
(12) cd connectedhomeip
(13) source ./scripts/bootstrap.sh
(14) source ./scripts/activate.sh
(15) cd examples/all-clusters-app/esp32
(16) idf.py menuconfig 
`Demo`->`Device Type` -> `ESP32-WROVER-KIT_V4.1`
`Demo`->`Rendezvous Mode`->`BLE`
(17) idf.py build

Full build log:
[build_log.txt](https://github.com/project-chip/connectedhomeip/files/6481612/build_log.txt)

**Comment by dhrishi** [comment]
#6774

**Comment by dhrishi** [comment]
@yunhanw-google Raised a PR here with @erjiaqing 's suggestions: https://github.com/project-chip/connectedhomeip/pull/6849

**Comment by pan-apple** [comment]
I think @fengbowe was able to build this with the following steps (replacing step 16 onwards in the issue description)

```
1. source idf.sh
2. idf make menuconfig
Demo->Device Type -> ESP32-WROVER-KIT_V4.1
Demo->Rendezvous Mode->BLE
3. idf make flash monitor ESPPORT=/dev/tty.SLAB_USBtoUART -j 16
```

**Comment by dhrishi** [comment]
@pan-apple Yes, the compilation works fine with automake (make command) but fails with CMake (idf.py). CMake would be the default one going forward and hence is recommended.

**Comment by bzbarsky-apple** [comment]
@fengbowe @dhrishi Did #6849 fix this?

**Comment by fengbowe** [comment]
@bzbarsky-apple Yes it's fixed now
