### ISSUE TITLE
[chip-tool] the CHIP tool is parsing Thread operational dataset as string but not HEX string.

### ISSUE THREAD

**Issue by wgtdkp** [project-chip/connectedhomeip#6857]
#### Problem
The CHIP tool is parsing Thread operational dataset as string but not HEX string. This result in Thread device provisioning failures with the command `pairing ble-thread ...`

 #### Proposed Solution
parse Thread Operational dataset as HEX string.

It was fixed by #6627 but reverted by #6689

**Comment by woody-apple** [comment]
I think this is now resolved?
