### ISSUE TITLE
Fix data corruption/mangling in DeviceCommissioner::SendOperationalCertificate

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#6877]
#### Problem
DeviceCommissioner::SendOperationalCertificate has the task of sending 2 certificates to the device. Instead, it only sends the first one and splits it into 2 portions as a "hack" for ZAP compatibility. This is bad and absolutely not needed since the code is only used with Interaction Model which is not limited to 255 bytes. See OperationalCredentialsCluster::AddOpCert for proof, it calls writer->Put(TLV::ContextTag(argSeqNumber++), noc) which does the right thing regardless of length

 #### Proposed Solution
The following one liner is all you need to do it right:
ReturnErrorOnFailure(cluster.AddOpCert(successCallback, failureCallback, opCertBuf, icaCertBuf, ByteSpan(nullptr, 0), mLocalDeviceId, 0));

**Comment by yunhanw-google** [comment]
@bluebin14  post a pr?

**Comment by bluebin14** [comment]
https://github.com/project-chip/connectedhomeip/pull/7309
