### ISSUE TITLE
Remove the outdate zcl command error message during IM command

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#6886]
#### Problem
Please Remove the outdate zcl command error message during IM command
SetCommandIndexStatus commandHandle=281473512828632 commandIndex=1
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0xffffa8beeed8
CHIP:ZCL:   status: EMBER_ZCL_STATUS_FAILURE (0x01)
CHIP:ZCL: emberAfDefaultResponseCallback: Missing success callback
CHIP:ZCL: emberAfDefaultResponseCallback: Missing failure callback
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0xffffa8beeed8
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:ZCL: emberAfDefaultResponseCallback: Missing success callback
CHIP:ZCL: emberAfDefaultResponseCallback: Missing failure callback

**Comment by erjiaqing** [comment]
Should be resolved by follow ups in im.
