### ISSUE TITLE
resolve command is failing, may be related to PR6705

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#6901]
#### Problem
resolve command is failing, may be related to PR6705
chip-device-ctrl > resolve 0 12344321
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:CTL: SyncSetKeyValue on PairedDevicebc5c01
Node address has been updated
CHIP:CTL: SyncSetKeyValue on PairedDevicebc5c01
Node address has been updated
Current address: fe80::dea6:32ff:fe8d:7072:11097
CHIP:CTL: SyncSetKeyValue on PairedDevicebc5c01
Node address has been updated
chip-device-ctrl > CHIP:CTL: SyncSetKeyValue on PairedDevicebc5c01
Node address has been updated
CHIP:CTL: SyncSetKeyValue on PairedDevicebc5c01
Node address has been updated

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
