### ISSUE TITLE
racing in chip_im_initiator, exchange context leak

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#6915]
#### Problem
Cirque fail: https://github.com/project-chip/connectedhomeip/actions/runs/844261919

There is a racing in chip_im_initiator tests. sometime `ExchangeContext` is leaked

> chip-im-initiator: ../../../../../src/messaging/ExchangeMgr.cpp:101: chip::Messaging::ExchangeManager::Shutdown()::<lambda(auto:2*)> [with auto:2 = chip::Messaging::ExchangeContext]: Assertion `false' failed.

Apply following patch will make it fail everytime.

```
diff --git a/src/app/tests/integration/chip_im_initiator.cpp b/src/app/tests/integration/chip_im_initiator.cpp
index 09bceacc..9e971132 100644
--- a/src/app/tests/integration/chip_im_initiator.cpp
+++ b/src/app/tests/integration/chip_im_initiator.cpp
@@ -191,6 +191,7 @@ void HandleReadComplete()
            static_cast<double>(gReadRespCount) * 100 / gReadCount, static_cast<double>(transitTime) / 1000);
 
     gCond.notify_one();
+    usleep(20);
 }
 
 class MockInteractionModelApp : public chip::app::InteractionModelDelegate
```

There are 2 threads:

Event thread (Thread E):
 1. send read request
 2. receive read response
 3. notify main thread read successful
 4. delete `ExchangeContext`

Main thread (Thread M):
 1. Wait for read successful
 2. Shutdown `ExchangeManager`

if Shutting down the `ExchangeManager` happens before deleting the `ExchangeContext`, there will be an assert fail

 #### Proposed Solution
Lock guard `ExchangeManager::Shutdown`

**Comment by woody-apple** [comment]
Is this still an issue?
