### ISSUE TITLE
Implement CHIP platform lock for Android.

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#6919]
#### Problem
CHIP platform lock is needed to guard chip stack against racing. But device layer is not implemented for Android.

#### Possible Solution
Implement device layer for android.

**Comment by austinh0** [comment]
We have a lock: https://github.com/project-chip/connectedhomeip/blob/15669b66d32369462d0079649b8edc698e327941/src/controller/java/JniReferences.h#L81
