### ISSUE TITLE
TestUDP is failing for some developers

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#6947]
We've had multiple reports of TestUDP failing for some developers (on Linux).

Also, one of the reports went away after rebooting.

**Comment by kghost** [comment]
I'm having the same problem when in the office, but can't reproduce when at home. I guess it is related to the network environment, Maybe decided by whether ipv6 is assigned by AP.

**Comment by mlepage-google** [comment]
Happening for me too, at home, on Linux.

**Comment by mspang** [comment]
Is it a deterministic fail in these cases or does it pass when you retry?

**Comment by mlepage-google** [comment]
It seems to always fail when I run from scratch, but yes it passed on subsequent runs. (Probably because of less contention for the port.)

@kghost made a PR which seems to fix it (not sure it was linked to this issue)
https://github.com/project-chip/connectedhomeip/pull/9692

**Comment by mspang** [comment]
Ok, just a port reuse issue - that's what I thought.
