### ISSUE TITLE
Update MessageHeader to align with latest specifications

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#6983]
#### Problem
The message header structure needs update to follow the latest specifications.
To list some of the issues
1. Message Flags, and Security Flags are different
2. The order of Optional Vendor ID  and Protocol ID seems reversed
3. The comment in `MessageHeader.cpp` has `Payload Length`, but it's not needed (as per spec), and is not actually encoded in the header.

 #### Proposed Solution
1. Update the code to match the spec.
2. Add unit tests with a set of golden pre-constructed message headers (which are as per spec), and ensure that encoder constructs the same header with the given input values, and decoder can parse the pre-constructed headers to get specific outputs. The current tests are using encoder and decoder from the same code base, and can potentially hide encoding problems.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
