### ISSUE TITLE
chip-tool on Linux does not have a nodeID argument

### ISSUE THREAD

**Issue by arunbharadwaj** [project-chip/connectedhomeip#7003]
#### Problem
Currently, the Linux version of chip-tool supports sending cluster commands in the following way:
`chip-tool <Cluster> <Command> <EndpointId>`

There is no way to tell which nodeID to send this command to if multiple devices are paired. We need to add an option to chip-tool to specify this.

 #### Proposed Solution
The python controller does have this option:
`zcl <Cluster> <Command> <NodeId> <EndpointId> <GroupId> [arguments]`

So, my guess is that the logic exists underneath to send a command to a specific nodeID. We just need to hook it up with the Linux chip-tool
@vivien-apple @bzbarsky-apple @pan-apple @andy31415 @sagar-apple

**Comment by woody-apple** [comment]
Appears resolved
