### ISSUE TITLE
Enable clang-tidy misc-use-after-move

### ISSUE THREAD

**Issue by kghost** [project-chip/connectedhomeip#7044]
#### Problem
#6874 is using rvalue ref to pass packet handles, but we should verify that the handle is not used after moved.

 #### Proposed Solution
Update gn to enable clang-tidy misc-use-after-move check.

https://releases.llvm.org/5.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/misc-use-after-move.html

**Comment by bzbarsky-apple** [comment]
See also #2814

**Comment by turon** [comment]
The reference code has since been significantly refactored, but certainly adding such general lint checks would be great, time permitting, to add in v1.
Removing tag `v1_triage_split_4 `

**Comment by bzbarsky-apple** [comment]
Looks like bugprone-use-after-move is already enabled in CI.
