### ISSUE TITLE
Posix critical section implementation happily ignores lock/unlock failures in non-debug builds

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#7052]
#### Problem
```
void CriticalSectionEnter()
{
    int err = pthread_mutex_lock(&eventLocker);
    assert(err == 0);
}
```
and similar for CriticalSectionExit.  On error, it silently presses on in non-debug builds.

 #### Proposed Solution
Make these functions fallible and check for failure appropriately.

**Comment by woody-apple** [comment]
Issue Scrub: We don't believe this is an issue anymore
