### ISSUE TITLE
FieldId and Listindex should not be exclusive in attribute path

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7055]
#### Problem
FieldId and ListIndex should not be exclusive in attribute Path.
If targeting an item in a list-typed attribute we would do node id, endpoint id, cluster id, attribute (field) id, list index

if (apAttributePathParamsList[index].mFlags == AttributePathFlags::kFieldIdValid)
                {
                    attributePathBuilder.FieldId(apAttributePathParamsList[index].mFieldId);
                }
                else if (apAttributePathParamsList[index].mFlags == AttributePathFlags::kListIndexValid)
                {
                    attributePathBuilder.ListIndex(apAttributePathParamsList[index].mListIndex);
                }
                else
                {
                    err = CHIP_ERROR_INVALID_ARGUMENT;
                    ExitNow();
                }
 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
To be clear, `ReadClient::SendReadRequest` is where the buggy code quoted above lives.
