### ISSUE TITLE
Update PASE Session code to match specifications changes

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#7071]
#### Problem
Specifications were updated in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/2894/files. The PASE Session code needs corresponding changes.

 #### Proposed Solution
Update the code to align with the latest specifications.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
