### ISSUE TITLE
[IM] Adding tests for catching objects leaks in IM.

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#7074]
#### Problem

We may leak exchange contexts, CommandSender, CommandHandler or other objects from IM, we should add tests to cover this.

 #### Proposed Solution

See above.

**Comment by bzbarsky-apple** [comment]
The specific suggestion in #7041 was that the test being added there be changed to send commands a larger number of times than 2 (e.g. 100), so it would be more likely to catch leaks due to hitting pool limits.
