### ISSUE TITLE
How to ctrl more than one EFR32-lighting ?

### ISSUE THREAD

**Issue by hainahouwei** [project-chip/connectedhomeip#7075]
#### How to ctrl more than one EFR32-lighting ?
 * expected behavior :
     1.More than one devices should be connected with command "connect -ble 3840 73141520" in chip-device-ctrl .
     2.Devices should be ctrl in a group .
 * actual behavior  :
     1. There are 3 light devices in the Thread Network 。And all of then can be find with command "ble-scan"
     
     2.Only one device can be connected with command "connect -ble 3840 73141520"  .
        When try the command again, the device connected in the first time will be remove and connect the new one .
        So , no matter how many times be tried , just one device can be connect.

 * system configuration
    ubuntu 20.04
    commit 2fb8fc1adb416c3bb7c24f617f75d34f86f413e2
    EFR32 BOARD : BRD4161A and BRD4180A

 * screenshots, images, logs, etc.

chip-device-ctrl > ble-scan
2021-05-25 09:39:37,765 ChipBLEMgr   INFO     scanning started
2021-05-25 09:39:38,023 ChipBLEMgr   INFO     Name            = EFR32_LIGHT
2021-05-25 09:39:38,024 ChipBLEMgr   INFO     ID              = d558231f-fb05-389c-bae2-6b797b364d28
2021-05-25 09:39:38,025 ChipBLEMgr   INFO     RSSI            = -43
2021-05-25 09:39:38,027 ChipBLEMgr   INFO     Address         = 69:65:58:D6:5C:4B
2021-05-25 09:39:38,028 ChipBLEMgr   INFO     Pairing State   = 0
2021-05-25 09:39:38,029 ChipBLEMgr   INFO     Discriminator   = 3840
2021-05-25 09:39:38,029 ChipBLEMgr   INFO     Vendor Id       = 9050
2021-05-25 09:39:38,030 ChipBLEMgr   INFO     Product Id      = 21324
2021-05-25 09:39:38,030 ChipBLEMgr   INFO     Adv UUID        = 0000fff6-0000-1000-8000-00805f9b34fb
2021-05-25 09:39:38,031 ChipBLEMgr   INFO     Adv Data        = 00000f5a234c53
2021-05-25 09:39:38,031 ChipBLEMgr   INFO     
2021-05-25 09:39:38,139 ChipBLEMgr   INFO     Name            = EFR32_LIGHT
2021-05-25 09:39:38,140 ChipBLEMgr   INFO     ID              = d558231f-fb05-389c-bae2-6b797b364d28
2021-05-25 09:39:38,140 ChipBLEMgr   INFO     RSSI            = -42
2021-05-25 09:39:38,141 ChipBLEMgr   INFO     Address         = 6F:A7:45:44:6A:3D
2021-05-25 09:39:38,142 ChipBLEMgr   INFO     Pairing State   = 0
2021-05-25 09:39:38,142 ChipBLEMgr   INFO     Discriminator   = 3840
2021-05-25 09:39:38,143 ChipBLEMgr   INFO     Vendor Id       = 9050
2021-05-25 09:39:38,143 ChipBLEMgr   INFO     Product Id      = 21324
2021-05-25 09:39:38,144 ChipBLEMgr   INFO     Adv UUID        = 0000fff6-0000-1000-8000-00805f9b34fb
2021-05-25 09:39:38,145 ChipBLEMgr   INFO     Adv Data        = 00000f5a234c53
2021-05-25 09:39:38,145 ChipBLEMgr   INFO     
2021-05-25 09:39:39,368 ChipBLEMgr   INFO     Name            = EFR32_LIGHT
2021-05-25 09:39:39,368 ChipBLEMgr   INFO     ID              = d558231f-fb05-389c-bae2-6b797b364d28
2021-05-25 09:39:39,376 ChipBLEMgr   INFO     RSSI            = -37
2021-05-25 09:39:39,377 ChipBLEMgr   INFO     Address         = 5F:F0:5A:5F:82:D6
2021-05-25 09:39:39,378 ChipBLEMgr   INFO     Pairing State   = 0
2021-05-25 09:39:39,380 ChipBLEMgr   INFO     Discriminator   = 3840
2021-05-25 09:39:39,381 ChipBLEMgr   INFO     Vendor Id       = 9050
2021-05-25 09:39:39,382 ChipBLEMgr   INFO     Product Id      = 21324
2021-05-25 09:39:39,383 ChipBLEMgr   INFO     Adv UUID        = 0000fff6-0000-1000-8000-00805f9b34fb
2021-05-25 09:39:39,384 ChipBLEMgr   INFO     Adv Data        = 00000f5a234c53
2021-05-25 09:39:39,384 ChipBLEMgr   INFO     
2021-05-25 09:39:47,891 ChipBLEMgr   INFO     scanning stopped
chip-device-ctrl > connect -ble 3840 73141520 
Device is assigned with nodeid = 72416
CHIP:BLE: BLE removing known devices.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: New device scanned: 5F:F0:5A:5F:82:D6
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Scan complete notification without an active scan.
CHIP:BLE: subscribe complete, ep = 0x7f7923d2ae60
CHIP:BLE: peripheral chose BTP version 3; central expected between 2 and 3
CHIP:BLE: using BTP fragment sizes rx 20 / tx 128.
CHIP:BLE: local and remote recv window size = 3
CHIP:EM: Received message of type 33 and protocolId 0
CHIP:EM: Received message of type 35 and protocolId 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000011AE0 at utc time: 325670416 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:IN: Setting fabricID 11AE0 on admin.
CHIP:IN: Since admin was modified, persisting changes to KVS
CHIP:EM: Received message of type 9 and protocolId 327680
CHIP:ZCL: OpCSRResponse:
CHIP:ZCL:   CSR: 205
CHIP:ZCL:   CSRNonce: 32
CHIP:ZCL:   VendorReserved1: 0
CHIP:ZCL:   VendorReserved2: 0
CHIP:ZCL:   VendorReserved3: 0
CHIP:ZCL:   Signature: 0
CHIP:CTL: Received certificate signing request from the device
CHIP:CTL: Generating operational certificate for device 11ae0
CHIP:CTL: Getting intermediate CA certificate from the issuer
CHIP:CTL: GetIntermediateCACertificate returned 4190
CHIP:CTL: Intermediate CA is not needed
CHIP:CTL: Sending operational certificate to the device. Op Cert Len 258, ICA Cert Len 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000011AE0 at utc time: 325672819 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: Sent operational certificate to the device
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773824 commandIndex=1
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0x7f7923d295c0
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:CTL: Device confirmed that it has received the operational certificate
CHIP:CTL: Sending root certificate to the device
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000011AE0 at utc time: 325673868 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: Sent root certificate to the device
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:CTL: Device confirmed that it has received the root certificate
CHIP:CTL: Operational credentials provisioned on device 0x27fcdb0
Secure Session to Device Established
Device temporary node id (**this does not match spec**): 72416
chip-device-ctrl > connect -ble 3840 73141520 
Device is assigned with nodeid = 724454
CHIP:BLE: BLE removing known devices.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: New device scanned: 5F:F0:5A:5F:82:D6
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Scan complete notification without an active scan.
CHIP:DL: Bluez notify CHIPoBluez connection disconnected
CHIP:DL: FAIL: ConnectDevice : GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist

Failed to establish secure session to device: 4050
CHIP:BLE: PASESession timed out while waiting for a response from the peer. Expected message type was 33
CHIP Error 4050 (0x00000FD2): Timeout
Failed to establish secure session to device: 4050
chip-device-ctrl > connect -ble 3840 73141520 
Device is assigned with nodeid = 608966
CHIP:BLE: BLE removing known devices.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: New device scanned: 69:65:58:D6:5C:4B
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Scan complete notification without an active scan.
CHIP:BLE: subscribe complete, ep = 0x7f7923d2ae60
CHIP:BLE: peripheral chose BTP version 3; central expected between 2 and 3
CHIP:BLE: using BTP fragment sizes rx 20 / tx 128.
CHIP:BLE: local and remote recv window size = 3
CHIP:EM: Received message of type 33 and protocolId 0
CHIP:EM: Received message of type 35 and protocolId 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325882622 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:IN: Setting fabricID 94AC6 on admin.
CHIP:IN: Since admin was modified, persisting changes to KVS
CHIP:EM: Received message of type 9 and protocolId 327680
CHIP:ZCL: OpCSRResponse:
CHIP:ZCL:   CSR: 204
CHIP:ZCL:   CSRNonce: 32
CHIP:ZCL:   VendorReserved1: 0
CHIP:ZCL:   VendorReserved2: 0
CHIP:ZCL:   VendorReserved3: 0
CHIP:ZCL:   Signature: 0
CHIP:CTL: Received certificate signing request from the device
CHIP:CTL: Generating operational certificate for device 94ac6
CHIP:CTL: Getting intermediate CA certificate from the issuer
CHIP:CTL: GetIntermediateCACertificate returned 4190
CHIP:CTL: Intermediate CA is not needed
CHIP:CTL: Sending operational certificate to the device. Op Cert Len 258, ICA Cert Len 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325887921 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: Sent operational certificate to the device
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773824 commandIndex=1
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0x7f7923d295c0
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:CTL: Device confirmed that it has received the operational certificate
CHIP:CTL: Sending root certificate to the device
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325888720 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:CTL: Sent root certificate to the device
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
CHIP:CTL: Device confirmed that it has received the root certificate
CHIP:CTL: Operational credentials provisioned on device 0x27fcdb0
Secure Session to Device Established
Device temporary node id (**this does not match spec**): 608966
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325952057 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325959845 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325962289 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325965053 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325967101 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325974213 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325983465 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > zcl OnOff Toggle 608966 0 0
CHIP:IN: Sending msg from 0x000000000001B669 to 0x0000000000094AC6 at utc time: 325985721 msec
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status No Error
CHIP:IN: Secure transport received message destined to node ID (0x000000000001B669)
CHIP:EM: Received message of type 9 and protocolId 327680
SetCommandIndexStatus commandHandle=140158268773520 commandIndex=1
CHIP:ZCL: DefaultResponse:
Received command status response:
Container: 
    ProtocolId = 5
    ProtocolCode = 0
    EndpointId = 1
    ClusterId = 6
    CommandId = 2
    CommandIndex = 1
CHIP:ZCL:   Transaction: 0x7f7923d29490
CHIP:ZCL:   status: EMBER_ZCL_STATUS_SUCCESS (0x00)
chip-device-ctrl > connect -ble 3840 73141520 
Device is assigned with nodeid = 365922
CHIP:BLE: BLE removing known devices.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: New device scanned: 69:65:58:D6:5C:4B
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Scan complete notification without an active scan.
CHIP:DL: Bluez notify CHIPoBluez connection disconnected
CHIP:DL: FAIL: ConnectDevice : GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist

Failed to establish secure session to device: 4050
CHIP:BLE: PASESession timed out while waiting for a response from the peer. Expected message type was 33
CHIP Error 4050 (0x00000FD2): Timeout
chip-device-ctrl > Failed to establish secure session to device: 4050

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
