### ISSUE TITLE
[How] How to understand and learn Matter?

### ISSUE THREAD

**Issue by InfiniteYuan** [project-chip/connectedhomeip#7127]
As we all know, Matter is one of the most promising protocols in the IOT field in the future. So how should developers understand and learn Matter? And how to use it?

Will Matter officially have relevant tutorials and instructional videos? This should be very necessary information for developers. When does Matter officially plan to release related tutorials and videos?

Thank you and look forward to your reply.

**Comment by doru91** [comment]
A good place to start would be reproducing some of the demos available from the vendors: https://github.com/project-chip/connectedhomeip/tree/master/docs/guides

Also, the specification would be a very good starting point once it's open-source.

**Comment by ShadowJonathan** [comment]
@stale no.

Also for anyone wishing to get some more info on Matter, i recommend [this site](https://matter-smarthome.de/en/), which tries to independently follow Matter and its developments.

**Comment by ShadowJonathan** [comment]
@stale still no

**Comment by ShadowJonathan** [comment]
This is NOT a stale issue
