### ISSUE TITLE
Build Android CHIP Tool App Failed

### ISSUE THREAD

**Issue by Lemon-7** [project-chip/connectedhomeip#7129]
Facing error when I'm trying to build android CHIP tool app by running task "Build Android App" in vscode

Below are the logs which I see at the end. Can someone help me to solve this issue?

//*********** Logs **************//
+ ninja -C out/android_arm64 src/setup_payload/java src/controller/java default
ninja: Entering directory `out/android_arm64'
ninja: no work to do.
+ rsync -a out/android_arm64/lib/CHIPController.jar out/android_arm64/lib/SetupPayloadParser.jar src/android/CHIPTool/app/libs
scripts/examples/android_app.sh: line 43: rsync: command not found
The terminal process "/bin/bash '-c', 'TARGET_CPU=arm64 scripts/examples/android_app.sh'" terminated with exit code: 127.
//***********************//

**Comment by austinh0** [comment]
`android_app.sh` works for me close to HEAD. Can you install `rsync`?

**Comment by Lemon-7** [comment]
> `android_app.sh` works for me close to HEAD. Can you install `rsync`?

I have installed rsync, but it isn't work

**Comment by austinh0** [comment]
Is rsync on your PATH? Does it make a difference if you run `TARGET_CPU=arm64 ./scripts/examples/android_app.sh` from terminal instead of using the VSCode task?

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
