### ISSUE TITLE
Fix multiple A/AAAA records with same address on minimal mdns

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#7175]
#### Problem
Minimal mdns sending many redundant A / AAAA records

 #### Proposed Solution
Let's just send one.

**Comment by tcarmelveilleux** [comment]
According to spec:
```
Nodes SHALL publish AAAA records for all available IPv6 addresses
upon which they are willing to accept CHIP commissioning messages.
```

**Comment by cecille** [comment]
To clarify - this is multiple records with the same address. ie, mulitple copies of an identical A record.
