### ISSUE TITLE
ESP32: Update qemu CI to CMake build system.

### ISSUE THREAD

**Issue by sweetymhaiske** [project-chip/connectedhomeip#7186]
#### Problem
ESP32 uses CMake build system in CHIP. However, esp32 qemu GitHub CI uses Make build system.

 #### Proposed Solution
Use CMake build system for qemu GitHub CI.

**Comment by dhrishi** [comment]
@sweetymhaiske  Please address this https://github.com/project-chip/connectedhomeip/pull/7034#discussion_r640624363 here if it is not done in #7034

**Comment by sweetymhaiske** [comment]
> @sweetymhaiske Please address this [#7034 (comment)](https://github.com/project-chip/connectedhomeip/pull/7034#discussion_r640624363) here if it is not done in #7034

@dhrishi  added the changes in same PR #7034.

**Comment by woody-apple** [comment]
This looks complete.
