### ISSUE TITLE
python controller resolve command needs timesout of it can not resolve node IP address

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#7238]
python controller resolve command needs timesout of it can not resolve node IP address, right now (per current ToT fd547be39cc61bd542d84f7c027d6f41a7a39f8f) it hangs up if it doesn't get the IP address of the node for some reason

chip-device-ctrl > resolve 5544332211 12344321
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.

**Comment by bluebin14** [comment]
Is there a consensus on how long the timeout should be?

**Comment by cjandhyala** [comment]
@bluebin14 may be we can have it as an argument for the resolve command. resolve -t <TIMEOUT>
