### ISSUE TITLE
Lighting-app example flashing fails following instructions

### ISSUE THREAD

**Issue by gunarkroeger** [project-chip/connectedhomeip#7264]
#### Problem
I'm trying to run the Lighting-app example for the nRF52840 DK. I'm following the instructions in the README.md, which although not at all simple to follow, got me up to the point of building the example and generating the zephyr.hex file.

Now, running the command "west flash --erase" fails:

<pre><font color="#8AE234">-- west flash: using runner nrfjprog</font>
<font color="#8AE234">-- runners.nrfjprog: mass erase requested</font>
Using board 683433932
<font color="#8AE234">-- runners.nrfjprog: Flashing file: /var/chip/examples/lighting-app/nrfconnect/build/zephyr/zephyr.hex</font>
ERROR: JLinkARM DLL reported an error. Try again. If error condition
ERROR: persists, run the same command again with argument --log, contact Nordic
ERROR: Semiconductor and provide the generated log.log file to them.
<font color="#EF2929">FATAL ERROR: command exited with status 33: nrfjprog --program /var/chip/examples/lighting-app/nrfconnect/build/zephyr/zephyr.hex --chiperase -f NRF52 --snr 683433932</font>
</pre>

Interestingly, I am able to flash the device by drawing the zephyr.bin file into the JLINK removable device, but the west debug command does not work afterwards either.
I am using Ubuntu on a VMware virtual machine. Any suggestion would be welcome, and if a video guide for the whole setup would be extremely helpful if it exists already!

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
