### ISSUE TITLE
Darwin tests fail: -[CHIPClustersTests testSendClusterBridgedDeviceBasicReadAttributeUserLabelWithResponseHandler] 

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#7270]
#### Problem
Looks like the Darwin build has been broken, appears to be regressed from this PR: 
https://github.com/project-chip/connectedhomeip/pull/7060

 #### Proposed Solution
Fix please :)

**Comment by woody-apple** [comment]
Revert here: https://github.com/project-chip/connectedhomeip/pull/7276

**Comment by andy31415** [comment]
Closing - revert completed and looks green in the commits view.
