### ISSUE TITLE
Darwin tests timeout while shutting down CHIP stack

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#7271]
#### Problem
When shutting down the CHIP stack, the Darwin tests often timeout:
https://github.com/project-chip/connectedhomeip/runs/2712047404?check_suite_focus=true

 #### Proposed Solution
Fix

**Comment by woody-apple** [comment]
First instance of this in history was here:
https://github.com/project-chip/connectedhomeip/runs/2641216058?check_suite_focus=true

**Comment by woody-apple** [comment]
The first time it failed in master was here (which doesn't seem related):
https://github.com/project-chip/connectedhomeip/commit/1bc8680c4a88c6e11ca23c7a8cfe3d7fa68eb043

**Comment by cecille** [comment]
Is this still happening?
