### ISSUE TITLE
[Android] Set up tests for Android CHIPTool

### ISSUE THREAD

**Issue by austinh0** [project-chip/connectedhomeip#7287]
#### Problem
Android CHIPTool has no testing infrastructure.

 #### Proposed Solution
Set up emulator or Robolectric tests.

**Comment by turon** [comment]
This is an older issue.  
Android tests are required for v1.
They likely exist now in a form sufficient to close this, but I haven't validated.
Removing tag `v1_triage_split_4`

**Comment by austinh0** [comment]
I still need to work on this. Closing #7286 as duplicate.

**Comment by utzcoz** [comment]
For Android tests, we can use [Robolectric](https://github.com/robolectric/robolectric) as local test infra to run many Android related tests on JVM without Emulator and real devices, and we can use [android-test](https://github.com/android/android-test) with Espresso API to test behaviors on Emulator. All of them can be run GitHub Actions for CI purpose. We can run Robolectric on JVM with a normal JVM and Android building environment, and run Emulator tests with [android-emulator-runner](https://github.com/ReactiveCircus/android-emulator-runner). Hi @austinh0 , what is the current progress of this feature?

**Comment by yufengwangca** [comment]
Currently, Matter Java APIs is tested with java-matter-controller in GitHub CI, I think we are talking about testing Matter Java API, not Android ChipTool example app, right?

**Comment by yufengwangca** [comment]
We have Matter Java APIs tested with java-matter-controller in GitHub CI. Android CHIPTool need to run either in emulator or real device, so it is not good candidate to test Java API in GitHub CI.
