### ISSUE TITLE
CRMP/MRP is unable to recover if ack is lost

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#7292]
#### Problem
The use case is
1. The node1 sends a message to node2 requesting ack (reliable transmission)
2. The node 2 sends the standalone ack, but the ack message gets dropped.
3. The node1 resends the message after timeout
4. The node 2 is supposed to resend the ack back to node 1, even though the message is duplicate.

Currently, the message counter check fails for the message sent in step 3 above. This is because the counter check consider the message as duplicate. The counter check happens in a lower layer than CRMP, so the CRMP code never gets the message. Due to this the ack is never resent (as was expected in step 4 above).

The following PR has a unit test that tests this behavior. It's currently failing. Once this problem is fixed, the test can be enabled.
https://github.com/project-chip/connectedhomeip/pull/7291

 #### Proposed Solution
Analyze and fix the issue.

**Comment by bzbarsky-apple** [comment]
Per spec, there's supposed to be an ack even if the message counter is a dup, precisely because of this.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
