### ISSUE TITLE
Add TestCluster test support in python mobile-device-test script

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7293]

**Comment by bzbarsky-apple** [comment]
The actual desire here is to have CI exercising this.

**Comment by yunhanw-google** [comment]
There is existing test script in Cirque mobile device test,
https://github.com/project-chip/connectedhomeip/blob/master/src/controller/python/test/test_scripts/mobile-device-test.py, we would exercise it after re-enable cirque mobile-device-test.
