### ISSUE TITLE
SDK does not allow app to bypass builtin cluster servers (e.g. does not honor EMBER_AF_PLUGIN_XXX macros)

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#7294]
#### Problem
By default, ZAP assumes that zcl plugin implementations will be used. This includes level-control.cpp, color-control-server.cpp, etc.
While these built-in implementations may work for most use cases, for some use cases the app needs to implement these commands directly. Typically, this is done by not defining EMBER_AF_PLUGIN_LEVEL_CONTROL, EMBER_AF_PLUGIN_LEVEL_CONTROL_SERVER, EMBER_AF_PLUGIN_COLOR_CONTROL, etc., etc. Since ZAP currently defines these automatically in gen_config.h, a workaround existed where these could be commented out or removed after zap generation. However, the current build system always includes level-control.cpp, color-control-server.cpp, etc into the build, causing duplicate definitions of callback functions.
Normally, the inclusion of the server/plugin code would be conditional based on the macros, but they are currently unused in the SDK.

 #### Proposed Solution
Possible fixes:
1. Encase code implementations of plugin code within an #ifdef macro -- e.g. #ifdef EMBER_AF_PLUGIN_LEVEL_CONTROL
2. Change build system to only include source files in build if the corresponding macro is defined.

**Comment by woody-apple** [comment]
Is this still the case? If so, please re-open! (I tagged as v1 required)
