### ISSUE TITLE
The Project CHIP Distribution Contains Undesirable '.Po' Files

### ISSUE THREAD

**Issue by gerickson** [project-chip/connectedhomeip#732]
#### Problem
When running `make dist`, the resulting distribution contains undesirable '.Po' files under `third_party/lwip/repo/lwip/src/`.

#### Proposed Solution
Ensure that this does not happen.

**Comment by andy31415** [comment]
we moved to GN and there is no 'make dist' anymore. 
Removing and if we add a distribution build we can ensure it only generates desirable output.
