### ISSUE TITLE
python discover command returns Insufficient space

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#7327]
TE3 branch 
chip-device-ctrl > discover -all
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
Waiting for device responses...
CHIP:DIS: Device 0
CHIP:DIS: 	Host name:		DCA6328D7072
CHIP:DIS: 	Long discriminator:	3840
CHIP:DIS: 	Vendor ID:		9050
CHIP:DIS: 	Product ID:		65279
CHIP:DIS: 	Address 0:		fd97:9b58:11d2:0:dea6:32ff:fe8d:7072
CHIP:DIS: 	Address 1:		fe80::dea6:32ff:fe8d:7072
CHIP:DIS: 	Address 2:		192.168.4.223
chip-device-ctrl > CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space

====================
chip-device-ctrl > discover -qr CH:YNJV793700A50324800
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
CHIP:DIS: Attempt to mDNS broadcast to an unreachable destination.
Waiting for device responses...
CHIP:DIS: Device 0
CHIP:DIS: 	Host name:		DCA6328D7072
CHIP:DIS: 	Long discriminator:	3840
CHIP:DIS: 	Vendor ID:		9050
CHIP:DIS: 	Product ID:		65279
CHIP:DIS: 	Address 0:		fd97:9b58:11d2:0:dea6:32ff:fe8d:7072
CHIP:DIS: 	Address 1:		fe80::dea6:32ff:fe8d:7072
CHIP:DIS: 	Address 2:		192.168.4.223
chip-device-ctrl > CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space
CHIP:DIS: Failed to add discovered commisisonable node - Insufficient space

**Comment by cecille** [comment]
The errors themselves are fairly benign as long as the details for the device are returned. I'm not currently able to repro, but put in a PR to make the error more verbose (https://github.com/project-chip/connectedhomeip/pull/7337). Will find someone on Monday with repo capability to dig further.
