### ISSUE TITLE
BLE connection gets timed-out while running "connect -ble 3840 20202021 12344321" command on controller Raspi with Accessory Raspi. 

### ISSUE THREAD

**Issue by ramakrishnanandyala** [project-chip/connectedhomeip#7340]
Hi

I'm new to this connected home Ip Project and I'm starting with testing TE2. While running Ble connect command on controller raspi ble connection gets timed out. 

My ubuntu version is 20.04

Please find the logs below.

========== CONTROLLER LOGS ========
ubuntu@ubuntu:~/connectedhomeip/src/controller/python$ chip-device-ctrl 
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:DL: CHIP task running
CHIP:DL: Platform main loop started.
Chip Device Controller Shell
 
chip-device-ctrl > connect -ble 3840 20202021 12344321
Device is assigned with nodeid = 12344321
CHIP:BLE: Assigned local session key ID 0
CHIP:DL: TRACE: Bluez mainloop starting Thread
CHIP:EM: SessionEstablishmentExchangeDispatch::SendMessageImpl  mTransportMgr 0x16a2c870
CHIP:IN: Message appended to BLE send queue
CHIP:BLE: Sent PBKDF param request
CHIP:DL: TRACE: Bus acquired for name C-2aef
CHIP:DL: PlatformBlueZInit init success
CHIP:BLE: BLE removing known devices.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: Device 6E:1E:52:15:9E:96 does not look like a CHIP device.
CHIP:BLE: Device D0:B5:5C:9A:11:8A does not look like a CHIP device.
CHIP:BLE: Device D8:F8:83:7A:87:B6 does not look like a CHIP device.
CHIP:BLE: Device 41:BF:75:F9:2C:BC does not look like a CHIP device.
CHIP:BLE: Device F0:EF:86:D4:01:12 does not look like a CHIP device.
CHIP:BLE: Device 65:D9:E7:B4:6A:24 does not look like a CHIP device.
CHIP:BLE: Device F9:26:E7:8D:68:8E does not look like a CHIP device.
CHIP:BLE: Device 43:E0:D4:C3:F1:4E does not look like a CHIP device.
CHIP:BLE: Device F4:BC:DA:3A:5D:F7 does not look like a CHIP device.
CHIP:BLE: Device 34:F6:4B:73:04:7D does not look like a CHIP device.
CHIP:BLE: Device 90:CC:DF:AC:D9:B9 does not look like a CHIP device.
CHIP:BLE: Device F6:63:15:F5:BF:A1 does not look like a CHIP device.
CHIP:BLE: Device 79:13:26:2D:2C:81 does not look like a CHIP device.
CHIP:BLE: Device F0:EF:86:EA:D4:BC does not look like a CHIP device.
CHIP:BLE: Device 5A:D4:C7:17:45:CF does not look like a CHIP device.
CHIP:BLE: Device 24:0A:C4:EA:51:26 does not look like a CHIP device.
CHIP:BLE: Device 79:EE:D1:FF:A6:77 does not look like a CHIP device.
CHIP:BLE: Device C3:E6:38:14:96:B4 does not look like a CHIP device.
CHIP:BLE: Device D3:A8:C0:61:3B:0E does not look like a CHIP device.
CHIP:BLE: Device C1:28:B2:81:B9:67 does not look like a CHIP device.
CHIP:BLE: Device CD:9A:4F:9C:11:B2 does not look like a CHIP device.
CHIP:BLE: Device 5E:E0:5D:A5:9C:D9 does not look like a CHIP device.
CHIP:BLE: Device 64:DC:F9:EC:AF:FD does not look like a CHIP device.
CHIP:BLE: Device F3:0F:9B:92:43:30 does not look like a CHIP device.
CHIP:BLE: Device FE:41:0D:BB:04:B7 does not look like a CHIP device.
CHIP:BLE: Device 6C:AE:01:CF:4B:08 does not look like a CHIP device.
CHIP:BLE: Device F8:64:09:DE:3A:A6 does not look like a CHIP device.
CHIP:BLE: Device C8:B2:9B:95:E0:E2 does not look like a CHIP device.
CHIP:BLE: Device 43:A8:52:42:A3:B2 does not look like a CHIP device.
CHIP:BLE: Device 4E:A0:13:99:13:C0 does not look like a CHIP device.
CHIP:BLE: Device FF:88:20:D2:C8:DB does not look like a CHIP device.
CHIP:BLE: Device B0:E4:D5:DF:11:DA does not look like a CHIP device.
CHIP:BLE: Device 76:B4:15:2F:8B:B4 does not look like a CHIP device.
CHIP:BLE: Device E5:BD:1B:A7:72:6C does not look like a CHIP device.
CHIP:BLE: Device B0:E4:D5:DC:41:6E does not look like a CHIP device.
CHIP:BLE: Device F7:77:E8:73:78:F1 does not look like a CHIP device.
CHIP:BLE: Device 42:F9:1B:44:3B:67 does not look like a CHIP device.
CHIP:BLE: Device 1C:F2:9A:E4:F5:C1 does not look like a CHIP device.
CHIP:BLE: Device A4:C1:38:3B:D0:81 does not look like a CHIP device.
CHIP:BLE: Device D4:7F:CA:43:DA:1A does not look like a CHIP device.
CHIP:BLE: Device EB:90:73:FE:2F:B8 does not look like a CHIP device.
CHIP:BLE: Device ED:50:D2:2B:BA:DE does not look like a CHIP device.
CHIP:BLE: Device 4C:43:64:39:47:53 does not look like a CHIP device.
CHIP:BLE: Device 6D:7C:81:F4:82:AD does not look like a CHIP device.
CHIP:BLE: Device 7C:D9:5C:9D:3A:3C does not look like a CHIP device.
CHIP:BLE: Device 6E:1E:52:15:9E:96 does not look like a CHIP device.
CHIP:BLE: Device ED:54:D4:1F:9C:85 does not look like a CHIP device.
CHIP:BLE: Device F8:0F:F9:4E:B7:58 does not look like a CHIP device.
CHIP:BLE: Device D6:DB:F3:F9:CD:35 does not look like a CHIP device.
CHIP:BLE: Device 66:23:30:58:D1:CA does not look like a CHIP device.
CHIP:BLE: Device 5A:70:A5:03:82:93 does not look like a CHIP device.
CHIP:BLE: Device E2:A0:61:B5:5F:9B does not look like a CHIP device.
CHIP:BLE: Device 67:DC:5F:5F:7F:C5 does not look like a CHIP device.
CHIP:BLE: Device 8C:C6:81:0D:63:F2 does not look like a CHIP device.
CHIP:BLE: Device 64:16:66:26:6C:69 does not look like a CHIP device.
CHIP:BLE: Device F5:D7:C9:3B:97:AC does not look like a CHIP device.
CHIP:BLE: Device CF:D1:A9:DB:F9:B6 does not look like a CHIP device.
CHIP:BLE: Device F0:EF:86:EA:BB:37 does not look like a CHIP device.
CHIP:BLE: Device 7C:B4:44:60:DE:AA does not look like a CHIP device.
CHIP:BLE: Device 08:9E:08:F9:C0:6B does not look like a CHIP device.
CHIP:BLE: Device 5B:76:C3:18:12:60 does not look like a CHIP device.
CHIP:BLE: Device 44:1D:E2:8B:84:63 does not look like a CHIP device.
CHIP:BLE: Device A4:C1:38:3B:D0:81 does not look like a CHIP device.
CHIP:BLE: Device D6:92:79:0D:7B:B6 does not look like a CHIP device.
CHIP:BLE: Device 52:11:3D:78:AE:1A does not look like a CHIP device.
CHIP:BLE: Device EA:44:60:46:E7:86 does not look like a CHIP device.
CHIP:BLE: Device 6C:AE:01:CF:4B:08 does not look like a CHIP device.
CHIP:BLE: Device 5A:70:A5:03:82:93 does not look like a CHIP device.
CHIP:BLE: Device CE:1B:E5:26:FA:65 does not look like a CHIP device.
CHIP:BLE: Device EE:92:B8:48:90:FC does not look like a CHIP device.
CHIP:BLE: Device 5D:36:4B:4A:0C:8F does not look like a CHIP device.
CHIP:BLE: Device D9:6E:0B:A8:5B:59 does not look like a CHIP device.
CHIP:BLE: Device 20:16:B9:09:F4:A1 does not look like a CHIP device.
CHIP:BLE: Device 64:16:66:26:60:99 does not look like a CHIP device.
CHIP:BLE: Device 63:15:D5:B0:11:65 does not look like a CHIP device.
CHIP:BLE: Device F2:36:B1:50:BB:0C does not look like a CHIP device.
CHIP:BLE: Device F4:BC:DA:3D:90:95 does not look like a CHIP device.
CHIP:BLE: Device 71:07:5F:72:04:00 does not look like a CHIP device.
CHIP:BLE: Device 6E:1E:52:15:9E:96 does not look like a CHIP device.
CHIP:BLE: Device 38:8B:59:AD:4B:5A does not look like a CHIP device.
CHIP:BLE: Device 78:5F:1C:52:3E:0C does not look like a CHIP device.
CHIP:BLE: Device D8:D3:D6:FE:4A:69 does not look like a CHIP device.
CHIP:BLE: Device 20:16:B9:D0:0D:67 does not look like a CHIP device.
CHIP:BLE: Device C2:C3:49:4F:A7:E6 does not look like a CHIP device.
CHIP:BLE: Device 5E:E0:5D:A5:9C:D9 does not look like a CHIP device.
CHIP:BLE: Device E2:EE:57:9F:F5:63 does not look like a CHIP device.
CHIP:BLE: Device D9:3C:8C:23:3E:FF does not look like a CHIP device.
CHIP:BLE: Device 4C:AF:40:13:CE:C0 does not look like a CHIP device.
CHIP:BLE: Device E1:52:8D:BA:15:ED does not look like a CHIP device.
CHIP:BLE: Device F8:0F:F9:6C:DA:60 does not look like a CHIP device.
CHIP:BLE: Device E3:5C:A4:5E:18:6A does not look like a CHIP device.
CHIP:BLE: Device 78:16:CB:36:D6:11 does not look like a CHIP device.
CHIP:BLE: Device D4:1B:A1:C7:0F:27 does not look like a CHIP device.
CHIP:BLE: Device D5:28:98:0B:B5:15 does not look like a CHIP device.
CHIP:BLE: Device DE:78:E7:72:37:19 does not look like a CHIP device.
CHIP:BLE: Device 79:EE:D1:FF:A6:77 does not look like a CHIP device.
CHIP:BLE: Device F0:8B:EE:EF:8F:7F does not look like a CHIP device.
CHIP:BLE: Device 66:FC:CF:D7:72:A2 does not look like a CHIP device.
CHIP:BLE: Device 5B:76:C3:18:12:60 does not look like a CHIP device.
CHIP:BLE: Device 79:39:BB:2E:5C:21 does not look like a CHIP device.
CHIP:BLE: Device 04:D3:B0:49:A9:3E does not look like a CHIP device.
CHIP:BLE: Device A4:C1:38:3B:D0:81 does not look like a CHIP device.
CHIP:BLE: Device 4A:0E:B4:75:D6:79 does not look like a CHIP device.
CHIP:BLE: Device 77:BB:CC:6A:58:08 does not look like a CHIP device.
CHIP:BLE: Device 43:E0:D4:C3:F1:4E does not look like a CHIP device.
CHIP:BLE: Device 78:43:A5:B3:DE:BA does not look like a CHIP device.
CHIP:BLE: Device 04:D3:B0:48:C2:17 does not look like a CHIP device.
CHIP:BLE: Device CB:BF:B2:45:C9:08 does not look like a CHIP device.
CHIP:BLE: Device EB:A4:A3:1E:C4:F7 does not look like a CHIP device.
CHIP:BLE: Device C3:E6:38:14:96:B4 does not look like a CHIP device.
CHIP:BLE: Device D9:2F:99:6D:97:5F does not look like a CHIP device.
CHIP:BLE: Device F3:0F:9B:92:43:30 does not look like a CHIP device.
CHIP:BLE: Device D7:C3:F7:4E:1C:52 does not look like a CHIP device.
CHIP:BLE: Device 65:D9:E7:B4:6A:24 does not look like a CHIP device.
CHIP:BLE: Device 41:F4:E7:19:C7:90 does not look like a CHIP device.
CHIP:BLE: Device E4:DC:8E:50:96:A1 does not look like a CHIP device.
CHIP:BLE: Device C0:61:1B:DB:77:72 does not look like a CHIP device.
CHIP:BLE: Device F7:4A:11:04:ED:CD does not look like a CHIP device.
CHIP:BLE: Device C7:E7:7F:D7:B7:90 does not look like a CHIP device.
CHIP:BLE: Device 75:F5:E2:E9:8D:9C does not look like a CHIP device.
CHIP:BLE: Device F8:0F:F9:7C:25:EC does not look like a CHIP device.
CHIP:BLE: Device 50:AE:B0:79:97:BB does not look like a CHIP device.
CHIP:BLE: Device F8:0F:F9:5E:61:F8 does not look like a CHIP device.
CHIP:BLE: Device A4:C1:38:3B:D0:81 does not look like a CHIP device.
CHIP:BLE: Device D6:48:46:7E:26:C4 does not look like a CHIP device.
CHIP:BLE: Device 42:60:91:4E:B1:96 does not look like a CHIP device.
CHIP:BLE: Device 7A:48:B5:78:44:27 does not look like a CHIP device.
CHIP:BLE: Device E7:EF:85:1C:ED:68 does not look like a CHIP device.
CHIP:BLE: Device 6E:1E:52:15:9E:96 does not look like a CHIP device.
CHIP:BLE: Device 08:9E:08:F9:C0:6B does not look like a CHIP device.
CHIP:BLE: Device C1:02:FF:D8:D0:31 does not look like a CHIP device.
CHIP:BLE: Device EA:32:A7:18:C8:BF does not look like a CHIP device.
CHIP:BLE: Device 90:CC:DF:AC:D9:B9 does not look like a CHIP device.
CHIP:BLE: Device 4A:93:DF:9A:FB:2D does not look like a CHIP device.
CHIP:BLE: Device FE:F7:9B:8C:54:11 does not look like a CHIP device.
CHIP:BLE: Device 3C:8D:20:13:BC:F7 does not look like a CHIP device.
CHIP:BLE: Device C3:07:BC:F1:3D:BD does not look like a CHIP device.
CHIP:BLE: Device C0:9C:BF:27:41:B6 does not look like a CHIP device.
CHIP:BLE: Device 64:16:66:26:4F:8D does not look like a CHIP device.
CHIP:BLE: Device E2:A0:61:B5:5F:9B does not look like a CHIP device.
CHIP:BLE: Device EC:A2:D9:89:AB:D9 does not look like a CHIP device.
CHIP:BLE: Device CA:BE:6C:B9:94:75 does not look like a CHIP device.
CHIP:BLE: Device C5:85:26:A1:75:93 does not look like a CHIP device.
CHIP:BLE: Device 79:39:BB:2E:5C:21 does not look like a CHIP device.
CHIP:BLE: Device 64:16:66:E3:AE:DF does not look like a CHIP device.
CHIP:BLE: Device 4D:EE:F5:CA:6B:A9 does not look like a CHIP device.
CHIP:BLE: Device D4:CC:62:44:63:4C does not look like a CHIP device.
CHIP:BLE: Device 7C:D9:5C:9F:42:1D does not look like a CHIP device.
CHIP:BLE: Device 6C:AE:01:CF:4B:08 does not look like a CHIP device.
CHIP:BLE: Device EE:93:1C:12:3D:0A does not look like a CHIP device.
CHIP:BLE: Device 7C:D9:5C:94:DB:83 does not look like a CHIP device.
CHIP:BLE: Device C4:08:EA:05:F7:F8 does not look like a CHIP device.
CHIP:BLE: Device 1C:F2:9A:D8:AF:9F does not look like a CHIP device.
CHIP:BLE: Device 65:D9:E7:B4:6A:24 does not look like a CHIP device.
CHIP:BLE: Device EF:98:AD:CA:CC:1F does not look like a CHIP device.
CHIP:BLE: Device 78:43:A5:B3:DE:BA does not look like a CHIP device.
CHIP:BLE: Device 76:37:05:FD:66:A6 does not look like a CHIP device.
CHIP:BLE: Device ED:8D:BA:87:F6:41 does not look like a CHIP device.
CHIP:BLE: Device 6D:7C:81:F4:82:AD does not look like a CHIP device.
CHIP:BLE: Device 53:B6:B4:27:C1:86 does not look like a CHIP device.
CHIP:BLE: Device 6E:1E:52:15:9E:96 does not look like a CHIP device.
CHIP:BLE: Device C3:17:09:92:9C:28 does not look like a CHIP device.
CHIP:BLE: Device 90:CC:DF:AC:D9:B9 does not look like a CHIP device.
CHIP:BLE: Device 47:B8:56:17:80:99 does not look like a CHIP device.
CHIP:BLE: Device 41:F4:E7:19:C7:90 does not look like a CHIP device.
CHIP:BLE: Device 90:CC:DF:AC:D9:B9 does not look like a CHIP device.
CHIP:BLE: Device 64:16:66:03:60:A0 does not look like a CHIP device.
CHIP:BLE: Device 64:16:66:E3:AE:DF does not look like a CHIP device.
CHIP:BLE: Device 61:57:9B:3F:51:A8 does not look like a CHIP device.
CHIP:BLE: Device 42:EA:92:8F:B5:52 does not look like a CHIP device.
CHIP:BLE: Device 04:D3:B0:48:C2:17 does not look like a CHIP device.
CHIP:BLE: Device D8:F8:83:86:DF:D4 does not look like a CHIP device.
CHIP:BLE: Device 90:CC:DF:AC:D9:B9 does not look like a CHIP device.
CHIP:BLE: Device F0:17:E6:59:7F:E5 does not look like a CHIP device.
CHIP:BLE: Device F8:0F:F9:3D:09:6A does not look like a CHIP device.
CHIP:BLE: Device F8:0F:F9:55:68:28 does not look like a CHIP device.
CHIP:BLE: Device F8:C0:E6:F6:4A:94 does not look like a CHIP device.
CHIP:BLE: Device D3:92:04:A5:72:6A does not look like a CHIP device.
CHIP:BLE: Device EC:F9:91:F2:D6:34 does not look like a CHIP device.
CHIP:BLE: Device 5B:6B:90:FE:57:3C does not look like a CHIP device.
CHIP:BLE: Device 28:BD:89:6C:AA:81 does not look like a CHIP device.
CHIP:BLE: Device CC:93:2A:92:22:EE does not look like a CHIP device.
CHIP:BLE: Device F4:5C:0D:E6:29:11 does not look like a CHIP device.
CHIP:BLE: Device F5:2D:43:1C:50:CB does not look like a CHIP device.
CHIP:BLE: Device F0:EF:86:EA:BB:37 does not look like a CHIP device.
CHIP:BLE: Device C1:02:FF:D8:D0:31 does not look like a CHIP device.
CHIP:BLE: Device DD:0D:6A:21:D6:E9 does not look like a CHIP device.
CHIP:BLE: Device 5B:76:C3:18:12:60 does not look like a CHIP device.
CHIP:BLE: Device 6B:BA:BE:F1:46:C8 does not look like a CHIP device.
CHIP:BLE: Device 4E:CE:19:72:5B:6D does not look like a CHIP device.
CHIP:BLE: Device FB:BD:C1:56:6C:C1 does not look like a CHIP device.
CHIP:BLE: Device CE:1B:E5:26:FA:65 does not look like a CHIP device.
CHIP:BLE: Device D8:84:45:C4:48:B6 does not look like a CHIP device.
CHIP:BLE: Device 6D:7C:81:F4:82:AD does not look like a CHIP device.
CHIP:BLE: Device D6:56:0D:EA:21:DE does not look like a CHIP device.
CHIP:BLE: Device D5:21:A1:8E:E5:27 does not look like a CHIP device.
CHIP:BLE: Device C8:BF:40:93:8D:13 does not look like a CHIP device.
CHIP:BLE: Device D6:74:5D:03:6D:99 does not look like a CHIP device.
CHIP:BLE: Device 50:A7:FA:BC:85:9C does not look like a CHIP device.
CHIP:BLE: Device CA:69:6B:C4:1B:A9 does not look like a CHIP device.
CHIP:BLE: Device DA:0B:C5:32:C1:B5 does not look like a CHIP device.
CHIP:BLE: Device EE:90:61:88:D8:04 does not look like a CHIP device.
CHIP:BLE: Device 6B:79:9C:41:00:CF does not look like a CHIP device.
CHIP:BLE: Device 52:11:3D:78:AE:1A does not look like a CHIP device.
CHIP:BLE: Device 04:D3:B0:48:C2:17 does not look like a CHIP device.
CHIP:BLE: Device D5:D6:E4:96:6C:93 does not look like a CHIP device.
CHIP:BLE: Device D2:B9:54:F0:D8:BA does not look like a CHIP device.
CHIP:BLE: Device 6E:1E:52:15:9E:96 does not look like a CHIP device.
CHIP:BLE: Device 6B:FE:82:92:74:36 does not look like a CHIP device.
CHIP:BLE: Device 64:16:66:0D:BE:56 does not look like a CHIP device.
CHIP:BLE: Device 39:98:00:00:5A:AD does not look like a CHIP device.
CHIP:BLE: Device 75:09:0F:AC:89:91 does not look like a CHIP device.
CHIP:BLE: Device 5F:FA:5A:78:BD:36 does not look like a CHIP device.
CHIP:BLE: Device 76:B4:15:2F:8B:B4 does not look like a CHIP device.
CHIP:BLE: Device 79:EE:D1:FF:A6:77 does not look like a CHIP device.
CHIP:BLE: Device F7:77:E8:73:78:F1 does not look like a CHIP device.
CHIP:BLE: Device 6B:BA:BE:F1:46:C8 does not look like a CHIP device.
CHIP:BLE: Device F4:BF:63:25:21:11 does not look like a CHIP device.
CHIP:BLE: Device 57:85:2E:DB:9B:25 does not look like a CHIP device.
CHIP:BLE: Device F5:D7:C9:3B:97:AC does not look like a CHIP device.
CHIP:BLE: Device C9:C9:40:ED:E8:E9 does not look like a CHIP device.
CHIP:BLE: Device 66:23:30:58:D1:CA does not look like a CHIP device.
CHIP:BLE: Device 4C:43:64:39:47:53 does not look like a CHIP device.
CHIP:BLE: New device scanned: DC:A6:32:BC:1A:B2
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Scan complete notification without an active scan.
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_BC_1A_B2/service000e
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_BC_1A_B2/service000e
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_BC_1A_B2/service000e
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_BC_1A_B2/service000e
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_BC_1A_B2/service000e
CHIP:DL: Char1 /org/bluez/hci0/dev_DC_A6_32_BC_1A_B2/service000e
CHIP:DL: New BLE connection 0xffff7c194800, device DC:A6:32:BC:1A:B2, path /org/bluez/hci0/dev_DC_A6_32_BC_1A_B2
CHIP:DL: HandlePlatformSpecificBLEEvent 16385
CHIP:IN: BleConnectionComplete: endPoint 0xffff86a00858
CHIP:DL: HandlePlatformSpecificBLEEvent 16387
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:BLE: subscribe complete, ep = 0xffff86a00858
 
CHIP:BLE: connect handshake timed out, closing ep 0xffff86a00858
CHIP:IN: Failed to establish BLE connection: Ble Error 6021 (0x00001785): Connect handshake timed out
CHIP:IN: Clearing BLE pending packets.
CHIP:DL: HandlePlatformSpecificBLEEvent 16388
CHIP:BLE: Auto-closing end point's BLE connection.
CHIP:DL: Closing BLE GATT connection (con 0xffff7c194800)
CHIP:DL: BluezDisconnect peer=DC:A6:32:BC:1A:B2
Failed to establish secure session to device: 4050
CHIP Error 4050 (0x00000FD2): Timeout
chip-device-ctrl > 
chip-device-ctrl > CHIP:DL: FAIL: ConnectDevice : Timeout was reached
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:DL: Bluez disconnected
CHIP:DL: Bluez notify CHIPoBluez connection disconnectep]

====================End of Controller Logs=============================

====================Accessory Logs =================================

ubuntu@ubuntu:~/connectedhomeip/examples/lighting-app/linux$ sudo ./out/host/chip-lighting-app --wifi
CHIP:DL: writing settings to file (/tmp/chip_factory.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_factory.ini)
CHIP:DL: writing settings to file (/tmp/chip_config.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_config.ini)
CHIP:DL: writing settings to file (/tmp/chip_counters.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
CHIP:DL: Device Configuration:
CHIP:DL:   Serial Number: TEST_SN
CHIP:DL:   Vendor Id: 9050 (0x235A)
CHIP:DL:   Product Id: 65279 (0xFEFF)
CHIP:DL:   Product Revision: 1
CHIP:DL:   Setup Pin Code: 20202021
CHIP:DL:   Setup Discriminator: 3840 (0xF00)
CHIP:DL:   Manufacturing Date: (not set)
CHIP:SVR: SetupQRCode: [CH:H34DV+.00 V5C.71]
CHIP:SVR: Copy/paste the below URL in a browser to see the QR Code:
CHIP:SVR: https://dhrishi.github.io/connectedhomeip/qrcode.html?data=CH%3AH34DV%2B.00%20V5C.71
CHIP:SVR: Manual pairing code: [34970112332]
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:ZCL: Unknown cluster ID: 40
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x0000000000bc5c01
CHIP:DL: wpa_supplicant: _IsWiFiStationProvisioned: interface not connected
CHIP:BLE: Assigned local session key ID 0
CHIP:BLE: Waiting for PBKDF param request
CHIP:DIS: Start dns-sd server
CHIP:DIS: CHIP minimal mDNS started advertising.
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:DIS: Replying to DNS-SD service listing request
CHIP:SVR: Server Listening...
CHIP:DL: CHIP:DL: TRACE: Bus acquired for name CHIP-3840
TRACE: Bluez mainloop starting Thread
CHIP:DL: CREATE service object at /chipoble/07f4/service
CHIP:DL: Create characteristic object at /chipoble/07f4/service/c1
CHIP:DL: Create characteristic object at /chipoble/07f4/service/c2
CHIP:DL: CHIP BTP C1 /chipoble/07f4/service
CHIP:DL: CHIP BTP C2 /chipoble/07f4/service
CHIP:DL: CHIP_ENABLE_ADDITIONAL_DATA_ADVERTISING is TRUE
CHIP:DL: Create characteristic object at /chipoble/07f4/service/c3
CHIP:DL: rotatingDeviceId: 00007C5F6E176CD40F68685D100A1CF8A98B
CHIP:DL: CHIP BTP C3 /chipoble/07f4/service
CHIP:DL: PlatformBlueZInit init success
CHIP:DL: wpa_supplicant: connected to wpa_supplicant proxy
CHIP:DL: wpa_supplicant: can't find interface wlan0: GDBus.Error:fi.w1.wpa_supplicant1.InterfaceUnknown: wpa_supplicant knows nothing about this interface.
CHIP:DL: wpa_supplicant: try to create interface wlan0
CHIP:DL: wpa_supplicant: WiFi interface: /fi/w1/wpa_supplicant1/Interfaces/0
CHIP:DL: BluezPeripheralRegisterAppDone done
CHIP:DL: HandlePlatformSpecificBLEEvent 16392
CHIP:DL: Create adv object at /chipoble/07f4/advertising
CHIP:DL: SET service data to {'0xFFF6': <[byte 0x00, 0x00, 0x0f, 0x5a, 0x23, 0xff, 0xfe]>}
CHIP:DL: HandlePlatformSpecificBLEEvent 16393
CHIP:DL: CHIPoBLE advertising config complete
CHIP:DL: wpa_supplicant: connected to wpa_supplicant interface proxy
CHIP:DL: RegisterAdvertisement complete
CHIP:DL: HandlePlatformSpecificBLEEvent 16394
CHIP:DL: New BLE connection 0xffff780476c0, device DC:A6:32:BC:1B:05, path /org/bluez/hci0/dev_DC_A6_32_BC_1B_05
CHIP:DL: BluezCharacteristicAcquireWrite is called, conn: 0xffff780476c0
CHIP:DL: c1 BluezCharacteristicWriteFD mtu, 517
CHIP:DL: FAIL: short read in BluezCharacteristicWriteFD (0)
CHIP:DL: CHIPoBLE subscribe received
CHIP:BLE: no endpoint for sub recvd
CHIP:DL: HandlePlatformSpecificBLEEvent 32777
CHIP:DL: Receive kCHIPoBLEConnectionEstablished
CHIP:DL: Bluez disconnected
CHIP:DL: Bluez notify CHIPoBluez connection disconnected
 
(process:2036): GLib-CRITICAL **: 18:41:04.594: Source ID 52 was not found when attempting to remove it

**Comment by ramakrishnanandyala** [comment]
@erjiaqing, @Damian-Nordic 

Can any of you help me with this

**Comment by yunhanw-google** [comment]
Please use Ubuntu 20.10 (Raspberry Pi 3/4) 64-bit for tesing, in 20.04, the bluez is too old

**Comment by ramakrishnanandyala** [comment]
I don't see ubuntu 20.10 to install, I see only 20.04 works for Raspi-4
https://ubuntu.com/download/raspberry-pi

**Comment by erjiaqing** [comment]
20.10 is reaching EOL, however, you can still find it on http://cdimage.ubuntu.com/releases/20.10/release/

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
