### ISSUE TITLE
How to start on a new hardware platform to support  connectedhomeip?

### ISSUE THREAD

**Issue by wxiangcheng** [project-chip/connectedhomeip#7355]
#### Problem
As topic said, I want to run connectedhomeip on a new WIFI/BLE based platform which has its own WiFi/BLE API lib. I know matter is still at discussion stage and some commercial product will be coming end of 2021. Our product is not in the hardware certification list but we plan to join in near future.

What I want to investigate is software support/effort to run it with our SDK/platform. Is there any group or start-guide to refer? Besides, I don't find how to certificate new hardware platform for matter -- only find some steps for zigbee on your website.
Any comments are welcome. Thanks.

 #### Proposed Solution

**Comment by woody-apple** [comment]
Please reach out to myself or @andy31415 and we can get you started. There is no guide sadly, but you can use an example platform in ~/.github/workflows for the workflows to build, and how they work. Thanks!
