### ISSUE TITLE
resolve command using IPV4 while spec is recommends to use IPV6

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#7374]
resolve command using IPV4 while spec is recommends to use IPV6 address
excerpt Frm the spec

![Screen Shot 2021-06-03 at 5 09 55 PM](https://user-images.githubusercontent.com/68604034/120728378-9f7cf280-c491-11eb-85c1-86db6bc2087b.png)

![Screen Shot 2021-06-03 at 5 33 27 PM](https://user-images.githubusercontent.com/68604034/120728465-d6530880-c491-11eb-9332-5bc8a8fd5521.png)

chip-device-ctrl > resolve 0 12344321
[1622756648.139890][600221] CHIP:DL: Avahi resolve found
[1622756648.140012][600221] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1622756648.140146][600221] CHIP:CTL: SyncSetKeyValue on PairedDevicebc5c01
Node address has been updated
Current address: 192.168.4.223:11097
chip-device-ctrl > 
chip-device-ctrl >

**Comment by woody-apple** [comment]
Resolved
