### ISSUE TITLE
[linux] Linux Device Layer needs ConfigurationMgr.

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#738]
#### Problem
The Linux DeviceLayer needs a ConfigurationMgr module.

 #### Proposed Solution
Implement a FileStore.  Allow partitioning data into two distinct areas:
- immutable / durable: factory parameters (FACTORY_CONFIG_PATH)
- mutable / ephemeral: user parameters (DEVICE_CONFIG_PATH) (factory reset == erasing this "partition") 

Make configuration update transaction based to handle cases of reboot occurring during config update.
- write updates to a temporary file
- perform atomic move and replace when config is complete
- on boot, always throw away temp file

The method could be extended to use hash check.

Reviewer Requirements:
- Use XML format for immutable factory settings.
  This allows simple factory provisioning of fixed settings.

- Use single library / format for both immutable and mutable format.
  This allows Linux to mirror embedded implementations where we have singular functional implementations for both the read-only and read-write use cases.

- Keep API simple.  No virtual.  No CRTP.

- Consider generalizing GroupKeyStore interface to apply to all platforms.

- Integrate [unit test template](https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/internal/testing/ConfigUnitTest.h) implementations for both the read-only and read-write use cases.
   - [Sample usage in nRF here](https://github.com/project-chip/connectedhomeip/blob/master/src/platform/nRF5/nRF5Config.cpp#L744).

- [Update 2020-06-10]
   - Reviewer feedback to evaluate recasting to use inipp.

**Comment by yufengwangca** [comment]
This ticket can be closed
