### ISSUE TITLE
CHIP Certificate: Update ECDSA Signature Representation

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#7382]
#### Problem
Currently SDK implements ECDSA signature in the CHIP Certificate as a TLV structure of R and S parameters:

```
ecdsa-signature => STRUCTURE [tag-order]
{
    r [1]   : OCTET STRING,
    s [2]   : OCTET STRING,
}
```

Recently, the spec was updated to represent ECDSA signature as Octet String:

ec-signature => OCTET STRING [ length (CHIP_CRYPTO_GROUP_SIZE_BYTES * 2) ]

 #### Proposed Solution

Update implementation to match the spec.

**Comment by woody-apple** [comment]
Looks resolved?
