### ISSUE TITLE
Add IM protocol code

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7385]
#### Problem
Need to add IM protocol code table
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/a9781609d101256455fd7ce52ec2b28e5853a012/src/data_model/Interaction-Model.adoc#status-code-table

**Comment by erjiaqing** [comment]
Dup https://github.com/project-chip/connectedhomeip/issues/7072
