### ISSUE TITLE
Adaptive generated enumeration storage width

### ISSUE THREAD

**Issue by gjc13** [project-chip/connectedhomeip#7394]
#### Problem

Currently the zap generated enumerations doesn't specify the storage width or must have unified storage width.

 #### Proposed Solution

Modify the ZAP generation engine to generate the storage width based on the enumeration values.

**Comment by wqx6** [comment]
Maybe we can use `enum class ENUM_TYPE :uintx_t` when defining the enumeration and use `Put(...,static_cast<std::underlying_type_t<ENUM_TYPE>>)` when calling the enumeration. like https://en.cppreference.com/w/cpp/types/underlying_type. It seems a safe solution, but  it needs a lot of changes at where using the enumeration.

**Comment by bzbarsky-apple** [comment]
Using `enum class` is orthogonal to the problem of figuring out what the right underlying type is for an enum....

Ideally that would just come from the spec or some other data source and feed into ZAP.

@tecimovic @vivien-apple

**Comment by jmeg-sfy** [comment]
@bzbarsky-apple this is something i would like to explicity use and define in my xml file. casting is not a solution and is prone to runtime problem . what is the policy regarding enum and packed structure 
Also can we enforce preprocessing compiler checks on ZAP

**Comment by bzbarsky-apple** [comment]
@jmeg-sfy Sorry for the lag; I hope https://github.com/project-chip/connectedhomeip/pull/7746 does what you wanted...

**Comment by jmeg-sfy** [comment]
> @jmeg-sfy Sorry for the lag; I hope #7746 does what you wanted...

yes all is solved now thanks !
