### ISSUE TITLE
Add Compare Operators and Equal

### ISSUE THREAD

**Issue by emargolis** [project-chip/connectedhomeip#7441]
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by woody-apple** [comment]
Can you please clarify what's needed here? (If anything now).
