### ISSUE TITLE
[chip-tool] The ble-thread pairing is using a hardcoded NetworkID when commissioning

### ISSUE THREAD

**Issue by tlykkeberg-grundfos** [project-chip/connectedhomeip#7446]
#### Problem
When doing ble-thread commissioning using the `chip-tool` the tool uses a default (hardcoded) NetworkID. This causes problems when trying to associate with a Thread network which does not have the Network Extended PAN-ID set to this default value.

This is hardcoded in `examples/chip-tool/commands/pairing/PairingCommand.cpp` as `kTemporaryThreadNetworkId` which is set to `0x0123456789ABCDEF`. When commissioning a device onto Thread, the operationalDataset contains a TLV for the Network Extended PAN-ID which should be used.

 #### Proposed Solution
In the `EnableNetwork()` method, one should make use of the operationalDataset and the TLV set during the addition of the actual network.

**Comment by woody-apple** [comment]
Doesn't appear to be the case anymore?
