### ISSUE TITLE
Enable application/protocol to set response timeout in CommandSender

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#7489]
#### Problem
The current `CommandSender` code uses a fixed timeout value for all commands.

In
```
CHIP_ERROR CommandSender::SendCommandRequest(NodeId aNodeId, Transport::AdminId aAdminId, SecureSessionHandle * secureSession)
```

```
    mpExchangeCtx->SetResponseTimeout(kImMessageTimeoutMsec);
```

`kImMessageTimeoutMsec` is currently 6 seconds.

Individual protocols could have different timeout requirements based on how long the peer takes to process the command, and what transport is being used for the message transmission.

For example, commands that require peer to use crypto operations (such as generate CSR) might take longer than command to toggle a light bulb.

And, commands going over CRMP vs BLE may have different timeout requirements to account for the message retries and retry timeouts.

Instead of having a fixed timeout for all applications/protocols, we should provide an API to the application/protocol to set the timeout value.

 #### Proposed Solution
Add an API to `CommandSender` to set the command timeout value. The `CommandSender` can use the current value (`kImMessageTimeoutMsec`) as the default timeout, in case the application doesn't override it.

Add unit tests.

Integrate the API to individual protocols that have non-default timeout requirements.

**Comment by woody-apple** [comment]
What is required here @pan-apple ?
