### ISSUE TITLE
Crash due to exchange timing out a packet before it ever gets a chance to be sent

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#7498]
#### Problem
I just got a crash with the following stack:
```
    frame #0: 0x00000001045cd05e chip-tool`chip::System::PacketBuffer::MaxDataLength(this=0x0000000000000000) const at SystemPacketBuffer.cpp:240:65
    frame #1: 0x00000001045cd0dc chip-tool`chip::System::PacketBuffer::AvailableDataLength(this=0x0000000000000000) const at SystemPacketBuffer.cpp:246:40
  * frame #2: 0x00000001045d0232 chip-tool`chip::SecureMessageCodec::Encode(localNodeId=112233, state=0x00007faf0b00c620, payloadHeader=0x00007ffeeb78e190, packetHeader=0x00007ffeeb78e040, msgBuf=0x0000000104617700, counter=0x00007faf0b00c690) at SecureMessageCodec.cpp:72:5
    frame #3: 0x00000001045d1a80 chip-tool`chip::SecureSessionMgr::SendMessage(this=0x00007faf0b00c600, session=(mPeerNodeId = 12344321, mPeerKeyId = 0, mAdmin = 0), payloadHeader=0x00007ffeeb78e190, packetHeader=0x00007ffeeb78e040, msgBuf=0x0000000104617700, bufferRetainSlot=0x0000000000000000, encryptionState=kPayloadIsUnencrypted) at SecureSessionMgr.cpp:184:36
    frame #4: 0x00000001045d1825 chip-tool`chip::SecureSessionMgr::SendMessage(this=0x00007faf0b00c600, session=(mPeerNodeId = 12344321, mPeerKeyId = 0, mAdmin = 0), payloadHeader=0x00007ffeeb78e190, msgBuf=0x0000000104617700, bufferRetainSlot=0x0000000000000000) at SecureSessionMgr.cpp:129:12
    frame #5: 0x00000001045a992c chip-tool`chip::Messaging::ApplicationExchangeDispatch::SendMessageImpl(this=0x00007faf0b00d318, session=(mPeerNodeId = 12344321, mPeerKeyId = 0, mAdmin = 0), payloadHeader=0x00007ffeeb78e190, message=0x0000000104617700, retainedMessage=0x0000000000000000) at ApplicationExchangeDispatch.cpp:33:25
    frame #6: 0x00000001045ab258 chip-tool`chip::Messaging::ExchangeMessageDispatch::SendMessage(this=0x00007faf0b00d318, session=(mPeerNodeId = 12344321, mPeerKeyId = 0, mAdmin = 0), exchangeId=44249, isInitiator=true, reliableMessageContext=0x00007faf0b00d368, isReliableTransmission=false, protocol=(mVendorId = Common, mProtocolId = 5), type='\b', message=0x0000000104617700) at ExchangeMessageDispatch.cpp:97:9
    frame #7: 0x00000001045a9f87 chip-tool`chip::Messaging::ExchangeContext::SendMessage(this=0x00007faf0b00d368, protocolId=(mVendorId = Common, mProtocolId = 5), msgType='\b', msgBuf=0x0000000104617700, sendFlags=0x00007ffeeb78e340) at ExchangeContext.cpp:124:22
    frame #8: 0x00000001045780f8 chip-tool`int chip::Messaging::ExchangeContext::SendMessage<chip::Protocols::InteractionModel::MsgType, void>(this=0x00007faf0b00d368, msgType=InvokeCommandRequest, msgPayload=0x0000000104617700, sendFlags=0x00007ffeeb78e340) at ExchangeContext.h:108:16
    frame #9: 0x000000010456b53b chip-tool`chip::app::CommandSender::SendCommandRequest(this=0x0000000104617668, aNodeId=12344321, aAdminId=0, secureSession=0x00007faf10148160) at CommandSender.cpp:64:26
    frame #10: 0x0000000104582eeb chip-tool`chip::Controller::Device::SendCommands(this=0x00007faf101480d0, commandObj=0x0000000104617668) at CHIPDevice.cpp:151:24
    frame #11: 0x000000010452c0b5 chip-tool`chip::Controller::TestClusterCluster::Test(this=0x00007ffeeb78e4a8, onSuccessCallback=0x00007faf0ac13e70, onFailureCallback=0x00007faf0ac13ba0) at CHIPClusters.cpp:7274:20
    frame #12: 0x0000000104502f75 chip-tool`TestCluster::TestSendClusterTestClusterCommandTest_0(this=0x00007faf10148000) at Commands.h:97:23
    frame #13: 0x0000000104502d45 chip-tool`TestCluster::NextTest(this=0x00007faf10148000) at Commands.h:43:19
```
and the following corresponding logs:
```
[1623259690183] [0x2d91abf] CHIP: [TOO] Test Cluster - Send Test Command: Sending command...
[1623259690183] [0x2d91abf] CHIP: [DMG] ICR moving to [Initialize]
[1623259690183] [0x2d91abf] CHIP: [DMG] ICR moving to [AddCommand]
[1623259690183] [0x2d91ac2] CHIP: [DL] CHIP task running
[1623259690183] [0x2d91abf] CHIP: [IN] New pairing for device 0x0000000000bc5c01, key 0!!
[1623259690183] [0x2d91ac2] CHIP: [DMG] Time out! failed to receive invoke command response from Exchange: 44249
[1623259690183] [0x2d91ac2] CHIP: [ZCL] DefaultResponse:
[1623259690183] [0x2d91ac2] CHIP: [ZCL]   Transaction: 0x104617668
[1623259690183] [0x2d91ac2] CHIP: [ZCL]   status: EMBER_ZCL_STATUS_FAILURE (0x01)
[1623259690183] [0x2d91ac2] CHIP: [TOO] Test Cluster - Send Test Command: Failure Response
[1623259690183] [0x2d91ac2] CHIP: [TOO] Error: The test was expecting a success callback. Got failure callback
```

What is going on here is that we call into `TestSendClusterTestClusterCommandTest_0` on the chip-tool main thread.  This goes to send a comamnd, lands in `ExchangeContext::SendMessage`, arms the response timeout timer, and calls into the `SecureSessionMgr` to encrypt and send.  While doing that we lose the timeslice for a bit while in the middle of this code:
```
    uint8_t * data    = msgBuf->Start();
    uint16_t totalLen = msgBuf->TotalLength();

    MessageAuthenticationCode mac;
    ReturnErrorOnFailure(state->EncryptBeforeSend(data, totalLen, data, packetHeader, mac));

    uint16_t taglen = 0;
    ReturnErrorOnFailure(mac.Encode(packetHeader, &data[totalLen], msgBuf->AvailableDataLength(), &taglen));
```
Here `msgBuf` is a _reference_ (because we started passing handles by reference, not by value), to the command sender's `mCommandMessageBuf`.

While we don't have the timeslice the timer fires, which I think runs the timer callback on the CHIP message thread (see #7497).  This triggers `CommandSender::OnResponseTimeout` which logs that "Time out! ..." message and then calls `Shutdown` on itself.  That nulls out `mCommandMessageBuf`, which if you will recall is what `msgBuf` is a reference to.

Now at some point the main thread wakes up, does `msgBuf->AvailableDataLength()` and dies with a null-deref.

 #### Proposed Solution
https://github.com/project-chip/connectedhomeip/pull/7478 may address this.  But in general, we need to figure out what the API contract is for CommandSender.  Having it call back with a timeout before the `SendCommandRequest` call even returns does not seem like a thing that should be happening and we should fix either `CommandSender` or something up the chain to prevent that.

@yunhanw-google @kghost @pan-apple

**Comment by bzbarsky-apple** [comment]
In particular, maybe the expedient thing here is to make sure that RunTextTest always runs on the message thread...

**Comment by mrjerryjohns** [comment]
> Having it call back with a timeout before the SendCommandRequest call even returns does not seem like a thing that should be happening 

This isn't the fault of CommandSender. The expectation in any given 'down' call into the stack is that the call is able to complete without it being pre-empted by any other stack call on the receive path.

The onus is the on the application to ensure this, and certainly, #7478 takes one particular stance on how the application can solve it.

**Comment by bzbarsky-apple** [comment]
Yes, that would be fixing "something up the chain to prevent that".

Note that there's also the question of whether ExchangeContext should start the timeout timer before it does the send or after.  It's not really documented what the semantics of that timeout bit are, so it's hard to tell what to expect as a consumer...

**Comment by mrjerryjohns** [comment]
Sorry, didn't see that snippet in the original issue earlier!

> question of whether ExchangeContext should start the timeout timer before it does the send or after

Why would it matter? Given that the call flow will not be preempted between the call to send and the call to start the timer, the sequencing of them is immaterial right?

**Comment by bzbarsky-apple** [comment]
> Why would it matter? 

It depends on whether the semantics of that timer are "starting when I call send" or "starting when I can reasonably maybe expect the other side to reply".  That is, if you spend longer than the timeout getting your own packet on the network, should that be treated as a timeout?  This has nothing to do with threading.

**Comment by mrjerryjohns** [comment]
Is the delay to get it on the network that large in relation to typical exchange timeouts? In my experience in Weave, that typically hasn't been a problem.

What is however an issue, is sleepy devices. The time scales at which they take to even pull that packet from the parent can be in the order of large seconds, minutes. So this clearly influences the timeout you set for your exchange.

Nonetheless, I'd think to keep this properly 'layered', that the meaning of the timeout at the Exchange layer would be to start it when you call send. I don't think the exchange layer _by itself_ should not have any knowledge, or factor in any characteristics of the underlying network medium.

The actual entity using the Exchange however, would have to set that timeout appropriately. If left 'unset', or left in 'auto', perhaps some entity could pull together information about the target's sleepiness to appropriately set the EC timeout to a sensible value, just for sleepy devices.

This latter point is somewhat tangential to the core concerns in this issue, but still worthwhile noting.

**Comment by bzbarsky-apple** [comment]
> Is the delay to get it on the network that large in relation to typical exchange timeouts?

It clearly is sometimes in our CI, and for me locally....  Maybe in a setup with no swap and no real contention from other processes for the CPU (i.e. real device) it won't be.  Not sure about phones.
