### ISSUE TITLE
BLE connection gets Pairing Failure: CHIP Error 4172 (0x0000104C): Internal error while running "./chip-tool pairing ble myssid mypassword 12345678 3840" command

### ISSUE THREAD

**Issue by SeanLinQiang** [project-chip/connectedhomeip#7547]
Hi

While running Ble connect command    Pairing Failure: CHIP Error 4172 (0x0000104C): Internal error.

My ubuntu version is 20.04
              bluetoothctl: 5.53
              firmware :chip-all-clusters-app.bin
              Device board: ESP-WROVER-KIT

Please find the logs below.
dean@dean-XPS-15-9550:~/chip/INNOTECH$ ./chip-tool pairing ble NETGEAR jia123456789 12345678 3840
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:DL: CHIP task running
CHIP:DL: TRACE: Bluez mainloop starting Thread
CHIP:DL: TRACE: Bus acquired for name C-32d0
CHIP:DL: PlatformBlueZInit init success
CHIP:BLE: BLE scanning through known devices.
CHIP:BLE: Device 18:D9:8F:D8:07:51 does not look like a CHIP device.
CHIP:BLE: Device 6D:8C:B9:B8:58:D3 does not look like a CHIP device.
CHIP:BLE: Device 37:99:CF:0F:B7:36 does not look like a CHIP device.
CHIP:BLE: New device scanned: 73:71:6C:1F:A4:1E
CHIP:BLE: Device discriminator match. Attempting to connect.
CHIP:BLE: Failed to stop discovery GDBus.Error:org.bluez.Error.Failed: No discovery started
CHIP:BLE: Scan complete notification without an active scan.
CHIP:BLE: Device 56:82:92:88:55:3D does not look like a CHIP device.
CHIP:BLE: Device 40:03:0E:C9:02:ED does not look like a CHIP device.
CHIP:BLE: Device 6A:05:82:3A:A2:9A does not look like a CHIP device.
CHIP:BLE: Device 60:5F:90:68:A9:A6 does not look like a CHIP device.
CHIP:BLE: New device scanned: 68:98:7D:AC:D7:A5
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 6C:8C:4A:E9:22:B9 does not look like a CHIP device.
CHIP:BLE: Device 50:3D:63:5F:F1:23 does not look like a CHIP device.
CHIP:BLE: New device scanned: 62:CA:E9:0F:82:21
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 67:22:8A:01:42:0F does not look like a CHIP device.
CHIP:BLE: Device FF:8F:C9:27:4B:50 does not look like a CHIP device.
CHIP:BLE: Device 4D:55:21:8A:99:D1 does not look like a CHIP device.
CHIP:BLE: Device 3A:11:A8:78:20:99 does not look like a CHIP device.
CHIP:BLE: Device 34:CD:5A:2A:00:E9 does not look like a CHIP device.
CHIP:BLE: New device scanned: 6A:FE:65:49:A2:4F
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 4D:1D:68:7B:AB:3D does not look like a CHIP device.
CHIP:BLE: New device scanned: 64:37:5F:4E:D3:69
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 72:A7:72:10:BD:81 does not look like a CHIP device.
CHIP:BLE: Device D4:4B:B6:0D:F6:B1 does not look like a CHIP device.
CHIP:BLE: Device 67:02:75:E7:03:32 does not look like a CHIP device.
CHIP:BLE: New device scanned: 5F:95:47:E3:EA:BE
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 6C:3B:B2:B8:1F:CB does not look like a CHIP device.
CHIP:BLE: New device scanned: 42:46:EB:98:A7:D6
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 56:D2:34:B4:3A:AC does not look like a CHIP device.
CHIP:BLE: Device 2C:F6:6E:2C:3A:C9 does not look like a CHIP device.
CHIP:BLE: New device scanned: 68:BD:5D:81:16:D7
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 6A:B8:71:2C:74:F1 does not look like a CHIP device.
CHIP:BLE: Device 6B:34:97:7A:DB:75 does not look like a CHIP device.
CHIP:BLE: Device 52:92:E7:60:D7:6F does not look like a CHIP device.
CHIP:BLE: Device 78:69:A8:92:7C:91 does not look like a CHIP device.
CHIP:BLE: New device scanned: 74:70:3C:02:2B:51
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 66:A7:30:AE:48:C6 does not look like a CHIP device.
CHIP:BLE: Device A0:68:1C:96:58:CD does not look like a CHIP device.
CHIP:BLE: Device 22:60:8C:1C:83:2B does not look like a CHIP device.
CHIP:BLE: Device 6D:EF:AE:18:4A:3E does not look like a CHIP device.
CHIP:BLE: New device scanned: 64:89:9B:35:5F:35
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 45:26:3E:5A:11:D9 does not look like a CHIP device.
CHIP:BLE: Device 60:6E:81:0C:74:EA does not look like a CHIP device.
CHIP:BLE: Device 60:78:5B:9A:35:FD does not look like a CHIP device.
CHIP:BLE: Device 5D:99:39:24:B5:7A does not look like a CHIP device.
CHIP:BLE: Device 2B:5F:F7:06:9C:1B does not look like a CHIP device.
CHIP:BLE: Device 55:56:DB:AE:0D:31 does not look like a CHIP device.
CHIP:BLE: Device 2B:F7:20:D8:02:CF does not look like a CHIP device.
CHIP:BLE: Device 94:B9:7E:A3:C7:3E does not look like a CHIP device.
CHIP:BLE: Device 04:7A:0B:1A:3D:BC does not look like a CHIP device.
CHIP:BLE: Device 5B:5D:4D:8F:0D:FF does not look like a CHIP device.
CHIP:BLE: Device 7B:C0:9E:4B:BD:17 does not look like a CHIP device.
CHIP:BLE: Device 32:59:40:4B:C9:4B does not look like a CHIP device.
CHIP:BLE: Device 69:E0:77:13:B8:85 does not look like a CHIP device.
CHIP:BLE: Device 66:66:FC:3D:E0:45 does not look like a CHIP device.
CHIP:BLE: Device 3A:EC:FF:80:93:8D does not look like a CHIP device.
CHIP:BLE: Device 94:B9:7E:A4:32:8E does not look like a CHIP device.
CHIP:BLE: Device 0F:A8:4A:38:DC:6D does not look like a CHIP device.
CHIP:BLE: Device 74:CE:B0:CF:FE:86 does not look like a CHIP device.
CHIP:BLE: Device E0:CC:F8:63:BE:47 does not look like a CHIP device.
CHIP:BLE: Device 6E:5B:BE:A4:FB:2E does not look like a CHIP device.
CHIP:BLE: Device 40:55:F1:53:D6:B1 does not look like a CHIP device.
CHIP:BLE: Device 5E:E2:8D:8B:44:9D does not look like a CHIP device.
CHIP:BLE: Device 15:C4:73:38:5E:62 does not look like a CHIP device.
CHIP:BLE: Device C8:28:32:47:5D:65 does not look like a CHIP device.
CHIP:BLE: New device scanned: 7A:22:98:45:96:7D
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 3F:C8:A4:97:F8:95 does not look like a CHIP device.
CHIP:BLE: Device 0C:E1:44:EC:18:5B does not look like a CHIP device.
CHIP:BLE: Device 7D:63:1F:36:4D:97 does not look like a CHIP device.
CHIP:BLE: Device E4:DB:6D:E5:49:09 does not look like a CHIP device.
CHIP:BLE: Device 42:9B:D2:70:D5:56 does not look like a CHIP device.
CHIP:BLE: Device 6B:75:6A:A9:D0:88 does not look like a CHIP device.
CHIP:BLE: New device scanned: 45:15:FE:D5:C5:D8
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: New device scanned: 70:E0:20:A9:A0:BB
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 6C:E8:50:23:4F:E1 does not look like a CHIP device.
CHIP:BLE: Device 31:40:A7:C6:F1:21 does not look like a CHIP device.
CHIP:BLE: Device 5C:A8:CA:2A:30:13 does not look like a CHIP device.
CHIP:BLE: Device 67:4F:F3:C5:73:33 does not look like a CHIP device.
CHIP:BLE: Device 7C:D6:D2:E1:67:4B does not look like a CHIP device.
CHIP:BLE: Device 4B:1F:DF:A4:E0:F6 does not look like a CHIP device.
CHIP:BLE: New device scanned: 63:FE:7D:7D:CA:03
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 78:6D:EB:03:05:C7 does not look like a CHIP device.
CHIP:BLE: Device 73:CC:4A:FE:66:3E does not look like a CHIP device.
CHIP:BLE: Device 31:FF:F9:CE:FC:2E does not look like a CHIP device.
CHIP:BLE: Device 7C:F6:66:06:87:90 does not look like a CHIP device.
CHIP:BLE: Device 68:7B:39:A4:16:5F does not look like a CHIP device.
CHIP:BLE: Device 64:30:6C:42:EE:E4 does not look like a CHIP device.
CHIP:BLE: New device scanned: 55:61:33:39:E4:03
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 77:4F:C3:1F:9E:99 does not look like a CHIP device.
CHIP:BLE: Device E4:05:F8:0E:71:C1 does not look like a CHIP device.
CHIP:BLE: Device 77:BE:39:89:4F:A1 does not look like a CHIP device.
CHIP:BLE: Device 13:8A:8F:0D:4A:F5 does not look like a CHIP device.
CHIP:BLE: New device scanned: 78:82:93:40:64:FC
CHIP:BLE: Unknown discovery type. Ignoring scanned device.
CHIP:BLE: Device 1D:00:A4:35:18:4F does not look like a CHIP device.
CHIP:BLE: Device 69:0F:75:B0:FB:8A does not look like a CHIP device.
CHIP:BLE: Device 12:F4:D3:25:94:EE does not look like a CHIP device.
CHIP:BLE: Device 64:6D:9E:EF:66:0B does not look like a CHIP device.
CHIP:BLE: Device 94:B9:7E:A6:6B:4A does not look like a CHIP device.
CHIP:BLE: Device 5A:D1:9A:3B:A5:67 does not look like a CHIP device.
CHIP:BLE: Device 6D:ED:FF:87:3C:63 does not look like a CHIP device.
CHIP:BLE: Device 66:4D:40:E9:1E:74 does not look like a CHIP device.
CHIP:BLE: Device 37:F4:2F:DF:05:76 does not look like a CHIP device.
CHIP:BLE: Device 30:48:1C:49:6E:89 does not look like a CHIP device.
CHIP:BLE: Device 49:58:CF:CD:FB:3E does not look like a CHIP device.
CHIP:BLE: Device 70:85:7F:4B:20:BC does not look like a CHIP device.
CHIP:BLE: Device 79:9F:23:C0:BA:B9 does not look like a CHIP device.
CHIP:BLE: Device 77:06:3A:CE:E6:CA does not look like a CHIP device.
CHIP:BLE: Device 47:6A:53:B2:EB:42 does not look like a CHIP device.
CHIP:BLE: Device 7D:E5:B3:00:52:8B does not look like a CHIP device.
CHIP:BLE: Device 42:14:FF:0A:E4:F5 does not look like a CHIP device.
CHIP:BLE: Device 68:27:12:A6:12:09 does not look like a CHIP device.
CHIP:BLE: Device 0A:A8:6C:47:EE:F2 does not look like a CHIP device.
CHIP:BLE: Device 66:6B:42:56:E8:1F does not look like a CHIP device.
CHIP:BLE: BLE initiating scan.
CHIP:BLE: Failed to start discovery: Operation was cancelled
CHIP:BLE: Scan complete notification without an active scan.
CHIP:DL: FAIL: ConnectDevice : GDBus.Error:org.bluez.Error.Failed: Operation already in progress
CHIP:DL: HandlePlatformSpecificBLEEvent 16386
CHIP:BLE: BleConnectionDelegate::CancelConnection is not implemented.
CHIP:TOO: Pairing Failure: CHIP Error 4172 (0x0000104C): Internal error
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller
CHIP:DL: System Layer shutdown
CHIP:DL: Inet Layer shutdown
CHIP:DL: BLE layer shutdown

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
