### ISSUE TITLE
Compilation error with CONFIG_CHIP_ZEPHYR_SHELL=y [macOS, shell]

### ISSUE THREAD

**Issue by MacWyznawca** [project-chip/connectedhomeip#7568]
Linking errors occur when compiling sample projects for nRF Connect with CONFIG_CHIP_ZEPHYR_SHELL=y enabled. 

Without CONFIG_CHIP_ZEPHYR_SHELL or with CONFIG_CHIP_ZEPHYR_SHELL=n the examples work correctly, but there are no commands for the chip in the UART CLI.

Compilation in the standard nRF Connect environment on macOS in Terminal (Shell)

[Compilation error with CONFIG_CHIP_ZEPHYR_SHELL=y [macOS, shell].txt](https://github.com/project-chip/connectedhomeip/files/6642352/Compilation.error.with.CONFIG_CHIP_ZEPHYR_SHELL.y.macOS.shell.txt)

**Comment by Damian-Nordic** [comment]
Thanks for letting us know! Provided the patch already.
