### ISSUE TITLE
persisted structures should not directly use C/C++ object representation

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#7579]
#### Problem

We're currently using bare C structures as the storage format for data such as `::chip::Controller::SerializableDevice`.

This is problematic:
- it is not extensible
- it couples the stored data to the C ABI

 #### Proposed Solution

Define and use TLV formats for persisted data types.

**Comment by mspang** [comment]
@pan-apple @bzbarsky-apple @andreilitvin @mrjerryjohns

**Comment by bzbarsky-apple** [comment]
`SerializableDevice` is gone.  I don't think we're doing any more direct dumping of C++ structures to storage anywhere, but if I missed something, please reopen @mspang.
