### ISSUE TITLE
require conversations be resolved before merging

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#7581]
I would like to be able to approve PRs with some last comments ("lgtm with nits") without these comments getting unintentionally dropped on the floor.

To that end, can we please enable this feature:
https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-conversation-resolution-before-merging

@woody-apple @andreilitvin

**Comment by woody-apple** [comment]
This is complete.
