### ISSUE TITLE
Ability to add invalid parameters to the device controller for testing negative test cases

### ISSUE THREAD

**Issue by akrithika27** [project-chip/connectedhomeip#7604]
Ability to add invalid parameters to the device controller for testing negative test cases.
Example - we want to test sending a wrong commandId to a device and the device should return a specific error code when that commandId is not implemented. Currently the device controller does some validation and doesnt send the commandId to the DUT if its not implemented and we are not able to test that error response.

This feature will be very useful in testing a lot of negative test cases and testing if the DUT is sending the right error codes.

**Comment by woody-apple** [comment]
Can you please clarify what is required here? Not sure what's necessary.
