### ISSUE TITLE
Premature rand access in GlobalUnencryptedMessageCounter

### ISSUE THREAD

**Issue by SurekhaMuralidharan777** [project-chip/connectedhomeip#7610]
#### Problem
A global constructor uses rand when it is possible that srand has not been called by this time.

Code snippet:
GlobalUnencryptedMessageCounter::GlobalUnencryptedMessageCounter() : value(GetRandU32())

 #### Proposed Solution
A possible solution would be to avoid the global state.

**Comment by kghost** [comment]
The order of constructor calls are fully controllable, the constructor is called when the object is created.

To control the order of the singleton object creation, we should avoid using global variables, whose construction is not controllable. C++11 can guarantee that the static variable in a function (singleton pattern) is created when first calling the function.

So we should not use global variables, and use singleton pattern instead.
