### ISSUE TITLE
Shutdown probably needs to shut down InteractionModelEngine

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#7624]
#### Problem
Nothing calls `InteractionModelEngine::Shutdown`.

 #### Proposed Solution
Do that.  Probably in all the places where we `PlatformMgr::Shutdown()`?

**Comment by woody-apple** [comment]
Is this still required @bzbarsky-apple ?

**Comment by bzbarsky-apple** [comment]
We fixed this: it's called in Server shutdown and DeviceControllerFactory shutdown now.
