### ISSUE TITLE
lwIP is not necessary for Thread devices

### ISSUE THREAD

**Issue by dougleaf** [project-chip/connectedhomeip#7646]
OpenThread has both IP and UDP functionality, thus lwIP is not necessary on Thread-based builds. lwIP has considerable RAM usage, over 16Kb (see #2762). 

Substitution of PacketBuffers is not trivial as the class it dependant on pBuf, but this is an important milestone for reducing RAM usage for small devices

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/13085
