### ISSUE TITLE
Use TCPlp as default Thread TCP stack instead of lwIP

### ISSUE THREAD

**Issue by dougleaf** [project-chip/connectedhomeip#7647]
This issue is a follow-up to #7646. TCPlp is going to be merged into OpenThread (Openthread issue [6650](see https://github.com/openthread/openthread/pull/6650)). Thus, TCP endpoints for Thread builds should be tied to TCPlp instead of lwIP.

**Comment by woody-apple** [comment]
https://github.com/project-chip/connectedhomeip/issues/13085
