### ISSUE TITLE
qrcodetool is not using existing argument parsing library

### ISSUE THREAD

**Issue by bhaskar-apple** [project-chip/connectedhomeip#771]
#### Problem
qrcodetool is not using existing argument parsing library that exists in CHIP repository today.

 #### Proposed Solution
Adopt it.

**Comment by sagar-apple** [comment]
Is this still valid @bhaskar-apple? Could you maybe elaborate a little more?

**Comment by bhaskar-apple** [comment]
Not valid anymore. This was previously using some hand rolled CL parsing vs using existing util functions.
