### ISSUE TITLE
`goto exit` pattern should be replaced with RAII in C++

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#7721]
#### Problem
there is no functional difference between `ExitNow()` and `return` or between `ExitNow(err = FOO)` and `return foo` except that the goto allows a 'separately defined' code to be run under the `exit:` label.

Using goto has several drawbacks in code organization and readability:
  - requires variable declaration at the top of the function (goto cannot bypass initialization), increasing variable scope. Declaring a variable far away from its use is hard on readability
  - cleanup code has to be reviewed and is often far away from code usage. Reviewer has to read code in 3 separate places: function top, code usage, cleanup
  - it does not enforce correctness, only makes it easier to implement especially for C code

C++ has the ability to do RAII which results in easier 'provable correct' code for things like memory allocation or cleanup.

 #### Proposed Solution
Anything with empty cleanup like `exit: return err` has no benefit from the goto pattern at all. These methods should switch to just 'return' or equivalent macros.

Methods that do cleanup should be reviewed for ability to convert to RAII (resource cleanup generally can be RAII, the pattern of 'log if error' is not as clear).

This is not a general ban on `goto exit`, however a strong preference on RAII. Goto exit is a 'I gave up, this cannot be done in C++', which is acceptable but only after RAII was tried.

**Comment by kpschoedel** [comment]
I'm gradually doing a mostly-mechanical removal of simple `exit: return` cases (search git commit titles for that string for examples). I have no plans to work on cases with actual cleanup.
