### ISSUE TITLE
Add ESP32C3 support for the other apps

### ISSUE THREAD

**Issue by wqx6** [project-chip/connectedhomeip#7745]
#### Problem
#6345 add ESP32C3 support for all-clusters app, the other apps' support need to be added.

 #### Proposed Solution
A PR will be raised soon to support ESP32C3 for the other apps.

**Comment by klem-everywhere** [comment]
@wqx6 have you tested the regular ESP32 with your new version?
Can you test if https://github.com/project-chip/connectedhomeip/pull/7749 fixed the other issues for you?

**Comment by 568760310** [comment]
@wqx6 
Hi,Qixiang
Does ESP have a plan to support the bridge-app demo?

**Comment by limic-amazon** [comment]
Hello, is there any plan to pick up this work soon? My team is interested in experimenting with the temperature-measurement-app as well based on the ESP blog post: https://blog.espressif.com/announcing-matter-previously-chip-on-esp32-84164316c0e3#6184

**Comment by chshu** [comment]
We will prioritize this task, will add other apps support for ESP32C3 in following 2 weeks.

**Comment by wqx6** [comment]
@limic-amazon The ESP32C3 support has already added to other examples now, you can try the temperature-measurement-app on C3 now.
Close the issue.
