### ISSUE TITLE
Add app configuration to enable/disable IM write

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#7791]
#### Problem
After #7730 the code for WriteClient is included in all apps, including those that never issue any writes.  This seems to be because a lot of that code is driven from `WriteClient::OnMessageReceived`, which is a virtual function (from ExchangeContext), hence always included by the linker and then it pulls in all the rest.

 #### Proposed Solution
Since we can't rely on the linker to strip this out, we may want to decide whether to include WriteClient based on the app configuration.  If the app does not include the client sides of any clusters that have writable attributes, it should not be including anything related to WriteClient.  Other ideas welcome!

@yunhanw-google @andy31415

**Comment by bzbarsky-apple** [comment]
To be clear, this is ~1KB of codesize, if I am measuring it right, that we don't need to be paying for a lot of constrained apps.

**Comment by yunhanw-google** [comment]
maybe we can introduce the feature flag so that we don't include it in constrained apps?

**Comment by bzbarsky-apple** [comment]
Right, that is my proposal: a feature flag, and then separately work on auto-deducing it at codegen time.

**Comment by tcarmelveilleux** [comment]
@bzbarsky-apple Is this done?

**Comment by bzbarsky-apple** [comment]
Looks fixed to me, by getting rid of the WriteClient pool.  Now only apps that actually create a WriteClient pay the cost.

In particular, the `.map` for the esp32 version of `chip-all-clusters-app` does not mention `WriteClient`.
