### ISSUE TITLE
implement optional attributes in Basic Information Cluster in lighting and all-cluster-apps

### ISSUE THREAD

**Issue by cjandhyala** [project-chip/connectedhomeip#7826]
implement optional attributes in Basic Information Cluster in lighting and all-cluster-apps. below spec ref. 

![Screen Shot 2021-06-22 at 11 08 37 AM](https://user-images.githubusercontent.com/68604034/122977411-3a0e7a00-d34a-11eb-81d3-d715f116f776.png)

**Comment by franck-apple** [comment]
relates to #5604
