### ISSUE TITLE
Allow Operational delegate apis to allow for writing  op certs onto the device.

### ISSUE THREAD

**Issue by ritikananda27** [project-chip/connectedhomeip#7859]
#### Problem
Currently the PairDeviceMethod in the controller automatically adds an  Example Opcert to the device as part of the commissioning process. There is no way to add ecosystem specific OpCert to the device which might be generated asynchronously by an ecosystem during the commissioning process.  

 #### Proposed Solution
Allow Operational delegate apis to allow for writing  op certs onto the device. 
cc  @pan-apple

**Comment by woody-apple** [comment]
@pan-apple ?
