### ISSUE TITLE
[SystemLayer] Make event API general across all builds of SystemLayer

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#788]
#### Problem
The system layer [event API](https://github.com/project-chip/connectedhomeip/blob/master/src/system/SystemLayer.h#L162) is exposed only on LWIP builds.  This forces users of SystemLayer to #ifdef all calls to PostEvent, DispatchEvent, etc.

The [DeviceLayer APIs](https://github.com/project-chip/connectedhomeip/blob/master/src/include/platform/PlatformManager.h#L34) assume system layer provides these event APIs.

 #### Proposed Solution
Make the event APIs a part of the generic system layer interface.
Stub out event handling in the SOCKETS implementation if it is not used.

**Comment by woody-apple** [comment]
SW BRB: @turon can you please clarify what's needed here for v1? Can this be broken down into more specific tasks?

**Comment by turon** [comment]
Sorry I missed the SW BRB -- I updated my calendar invites to add it.
I'm not sure this is essential for v1.  Posix platforms seem to be working fine with a bifurcated model.
This is mainly a call to simplify applications and ports by having a consolidated model at the platform layer.
