### ISSUE TITLE
Resolve the unclear null apWriter in ReadSingleClusterData

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7965]
This is still not making sense to me.  If the caller does not care about the value, what do they care about?  Just whether it exists?

But looking at the `ReadSingleClusterData` implemetations:

* The one in `TestCommandInteraction.cpp` leaves `apDataExists` unset if `apWriter` is null.
* The one in `TestReportingEngine.cpp`, same thing.
* The one in `chip_im_initiator.cpp`, same thing.
* The one in `chip_im_responder.cpp`, same thing.
* The one in `ember-compatibility-functions.cpp` seems to implement the "just set apDataExists" semantics, ok.

And more to the point: is there ever a caller that actually passes null for apWriter?  I don't obviously see one.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/7634#r659998747_

**Comment by bzbarsky-apple** [comment]
This is fixed now, since `ReadSingleClusterData` gets a `AttributeReportIBs::Builder` and hence always has a TLVWriter.
