### ISSUE TITLE
Fix potential invalid memory access  in IMReadReportAttributesResponseCallback

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7966]
Just to reiterate: if `err` is not `CHIP_NO_ERROR` at this point then the value of `onSuccessCallback` is generally speaking garbage we should not be examining it at all.  Same for `onFailureCallback`.  Nothing in the callbacks API definition guarantees that it will leave the values untouched on error, or set to anything in particular on error.

So if we got an error here, we are in fact "missing" both callbacks and the filter, as far as we're concerned.  Or in other words, we should just log that the `GetResponseCallback` call failed and not try to log any details about the state of the callback manager, because we don't know those details here.

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/pull/7634#discussion_r660002826_

**Comment by erjiaqing** [comment]
`IMReadReportAttributesResponseCallback` and similar callbacks are removed after landing cluster object, this should be closed.
