### ISSUE TITLE
`InteractionModelEngine::OnWriteRequest` aborts exchange contexts if a handler cannot be found.  An abort will fail to send an MRP ack; this does not seem like the right behavior.

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7968]
When there is no available write handler, should we send the status report to client, should we abort or close exchange context? @yufengwangca @bzbarsky-apple if we call  apExchangeContext->Close() , can an MRP ack be sent? Is that MRP ack necessary? 

Do we also need to send status report to client?

CHIP_ERROR InteractionModelEngine::OnWriteRequest(Messaging::ExchangeContext * apExchangeContext,
                                                  const PacketHeader & aPacketHeader, const PayloadHeader & aPayloadHeader,
                                                  System::PacketBufferHandle && aPayload)
{
    CHIP_ERROR err = CHIP_NO_ERROR;

    ChipLogDetail(DataManagement, "Receive Write request");

    for (auto & writeHandler : mWriteHandlers)
    {
        if (writeHandler.IsFree())
        {
            err = writeHandler.Init(mpDelegate);
            SuccessOrExit(err);
            err               = writeHandler.OnWriteRequest(apExchangeContext, std::move(aPayload));
            apExchangeContext = nullptr;
            break;
        }
    }

exit:
    ChipLogFunctError(err);

    if (nullptr != apExchangeContext)
    {
        apExchangeContext->Abort();
    }
    return err;
}

**Comment by bzbarsky-apple** [comment]
> if we call apExchangeContext->Close() , can an MRP ack be sent?

Yes.

> Is that MRP ack necessary?

Yes, unless you want the client to just resend the write request packet...

> Do we also need to send status report to client?

I think that's the right action: respond with the "busy" general status code or something and let the client decide how they want to handle it.

**Comment by bzbarsky-apple** [comment]
This has been fixed: we now respond with a BUSY status,
