### ISSUE TITLE
controller: APIs for CASE with previously unknown device on same fabric

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#7976]
#### Problem

Currently to connect to via a device you must
- use PairDevice() to run the commissioning procedure, or
- Have persisted local state from a previous successful commissioning session via PairDevice

With CASE it should be possible to instead establish a session with a previously unknown device on the same fabric (e.g., a device commissioned by a 3rd device on the same fabric). Currently, there is no API that would allow this.

 #### Proposed Solution

Enhance CHIPDeviceController to support establishing CASE session with a previously unknown device on the same fabric.

**Comment by mspang** [comment]
@pan-apple FYI

**Comment by tcarmelveilleux** [comment]
This is the fundamental assumption of CASE: that's what CASE is for. The nodes that will need to communicate over CASE to other nodes will, in large proportion of cases, not be the commissioners, but rather nodes that were told by other administrator nodes that they have a relations with device X (e.g. data model bindings, OTA request to OTA provider, time sync, etc)

**Comment by mspang** [comment]
I made this hack for this,
https://github.com/mspang/connectedhomeip/commit/7d6534f0622f8c687e2e1d94a4758ec50d045610

Haven't opened a PR, it's very low road and unless other folks need this it isn't the solution we want to pursue.

**Comment by holbrookt** [comment]
> I made this hack for this,
> [mspang@7d6534f](https://github.com/mspang/connectedhomeip/commit/7d6534f0622f8c687e2e1d94a4758ec50d045610)
> 
> Haven't opened a PR, it's very low road and unless other folks need this it isn't the solution we want to pursue.

Just want to say that I imagined the actual solution to this issue would not require use of `DeviceCommissioner`.

I would have considered using this to unblock OTA if not for that facet.
