### ISSUE TITLE
CommandHandler does not send required status responses in many cases

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#8030]
#### Problem
`CommandHandler::ProcessCommandDataElement` will send a status response in failure cases.

But if we don't reach that function, we will fail to send spec-required status responses.  Specifically, if `Command::ProcessCommandMessage` errors out before calling `ProcessCommandDataElement` (which it can do if the command list is missing in the TLV or has the wrong tag), we will never reach `ProcessCommandDataElement`.

 #### Proposed Solution
Add tests and fix.  Perhaps hoist the status-response-sending to `Command::ProcessCommandMessage`?

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/21557
