### ISSUE TITLE
ESP32: Compilation of ipv6only-app and lock-app esp32 fails when pigweed is enabled.

### ISSUE THREAD

**Issue by sweetymhaiske** [project-chip/connectedhomeip#8076]
#### Problem
* I am using esp-idf tag v4.3
* Compilation of ipv6only-app and lock-app fails when pigweed is enabled.
* For ipv6only-app changing this https://github.com/project-chip/connectedhomeip/blob/master/examples/ipv6only-app/esp32/CMakeLists.txt#L27 to `std=gnu++17` solved the issue on CHIP layer, however pigweed still uses `std=c++17` here https://github.com/google/pigweed/blob/626a9b8e988ef9f1bb1c5bc809a3490f96caf86c/pw_build/CMakeLists.txt#L80 for compilation hence it fails
* Both apps compile fine using esp-idf release/v4.2
* Logs:

-std=gnu++17 -Os -DLWIP_IPV6_SCOPES=0 -DCHIP_HAVE_CONFIG_H -D_GNU_SOURCE -DESP_PLATFORM -I/home/sweety/Espressif/connectedhomeip/examples/ipv6only-app/esp32/build/config -g -fdiagnostics-color=always -fno-common **-std=c++17** -Wno-register -include /home/sweety/Espressif/connectedhomeip/examples/ipv6only-app/esp32/third_party/connectedhomeip/third_party/pigweed/repo/pw_polyfill/language_features.h -DNDEBUG -DCHIP_HAVE_CONFIG_H=1 -I../../../../../../config/esp32/third_party/connectedhomeip/src/include -I../../../../../../config/esp32/third_party/connectedhomeip/src -Igen/include -I../../../../../../config/esp32/third_party/connectedhomeip/src/lib -I../../../../../../config/esp32/third_party/connectedhomeip/third_party/nlassert/repo/include -I../../../../../../config/esp32/third_party/connectedhomeip/third_party/nlio/repo/include -I../../../../../../config/esp32/third_party/connectedhomeip/third_party/nlfaultinjection/repo/include -c ../../../../../../config/esp32/third_party/connectedhomeip/src/app/CommandHandler.cpp -o obj/third_party/connectedhomeip/src/app/libCHIPDataModel.CommandHandler.cpp.o
In file included from /home/sweety/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/string.h:12,
                 from ../../../../../../config/esp32/third_party/connectedhomeip/src/transport/raw/MessageHeader.h:27,
                 from ../../../../../../config/esp32/third_party/connectedhomeip/src/app/util/basic-types.h:29,
                 from ../../../../../../config/esp32/third_party/connectedhomeip/src/app/CommandPathParams.h:21,
                 from ../../../../../../config/esp32/third_party/connectedhomeip/src/app/Command.h:27,
                 from ../../../../../../config/esp32/third_party/connectedhomeip/src/app/CommandHandler.h:27,
                 from ../../../../../../config/esp32/third_party/connectedhomeip/src/app/CommandHandler.cpp:25:
`/home/sweety/Espressif/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:318:1: error: static assertion failed: portGET_ARGUMENT_COUNT() result does not match for 0 arguments
 _Static_assert(portGET_ARGUMENT_COUNT() == 0, "portGET_ARGUMENT_COUNT() result does not match for 0 arguments");`
 ^

**Comment by sweetymhaiske** [comment]
@rgoliver

**Comment by juejuegongsui** [comment]
很简单，去你的错误的文件下，修改该行代码，修改##__VA__ARGS__为0 __VA_OPT__(,) __VA_ARGS__，啥，你不认识中文吗？那就翻译吧，全是英文烦死了 @sweetymhaiske

**Comment by wqx6** [comment]
I have added
 `chip_gn_arg_append("remove_default_configs"  "[\"//third_party/connectedhomeip/third_party/pigweed/repo/pw_build:cpp17\"]")` in `config/esp32/components/chip/CMakeLists.txt`, it solved the compilation failure in pigweed-app. I will figure out why it does not work in lock-app and ipv6only-app.

**Comment by sweetymhaiske** [comment]
The respective PR for fixing this is merged. #8129
