### ISSUE TITLE
TV Example App: Remove potential memory leaks

### ISSUE THREAD

**Issue by lazarkov** [project-chip/connectedhomeip#8087]
#### Problem
During implementation of [PR](https://github.com/project-chip/connectedhomeip/pull/7906) potential memory leaks were discovered.
[Issue 1](https://github.com/project-chip/connectedhomeip/pull/7906#discussion_r662759053)

 #### Proposed Solution
Find a way to allocate memory for attributes and responses of TV example app

**Comment by bzbarsky-apple** [comment]
To be clear this is a "leak random stack memory on the wire" leak, not a "leak memory by forgetting to deallocate" leak.

**Comment by bzbarsky-apple** [comment]
@lazarkov Were these fixed?  Which PR fixed them?
