### ISSUE TITLE
Remove nested dispatch to drive IO in darwin CHIPDeviceController

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#809]
#### Problem
https://github.com/project-chip/connectedhomeip/blob/57b104cd73cb9301517e49f2236408f44128c989/src/darwin/Framework/CHIP/CHIPDeviceController.mm#L235

The darwin framework for CHIP has to manually drive IO events in CHIP with a nested dispatch loop. This is unnecessarily complicated and mostly an artifact of non-native apis and direct socket usage

 #### Proposed Solution
The IO loop does 2 things: 
1. Collects FDs from all the InetEndPoints and calls select on them
2. Listens to the SystemLayer pipe for interruptions and primarily services timers (I'm not completely sure about this) 

Bringing in the NW framework should solve 1., for 2., we need to see if we can replace or supplement SystemLayer's handling of timer events. Overall this might end up being a 2 stage process. 

We have to be careful with some existing flags like `CHIP_SYSTEM_CONFIG_POSIX_LOCKING` and `CHIP_SYSTEM_CONFIG_USE_SOCKETS`. As some of these might have to be `||` with the NW configuration and posix locking support should not be removed.

**Comment by holbrookt** [comment]
@sagar-apple is this something that needs to be addressed for 1.0?

**Comment by sagar-apple** [comment]
I think this has already been revamped since this issue was filed.
