### ISSUE TITLE
sourcing script activate.sh fails with error indicating an unexpected python version

### ISSUE THREAD

**Issue by AymenLA** [project-chip/connectedhomeip#8104]
#### Problem
when trying to setup build environment, sourcing script "scripts/activate.sh" fails with error indicating that the Python version in unexpected : 

![Screenshot from 2021-07-04 15-41-26](https://user-images.githubusercontent.com/9513216/124387383-b3a94f00-dcde-11eb-8059-9ac1db17b667.png)

 #### Proposed Solution
at least, the error message should suggest to install another version of Python.

**Comment by pin2-sakariya** [comment]
Agree with the proposed solution, I also got this error and no clue.

Below steps solved my issue, 

1. sudo apt install python3.8-dev
2. sudo apt install python3.8-venv
3. sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 <priority>

The print statement need to update in the below file,
Location: third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py, Line:128

**Comment by AymenLA** [comment]
it's been 5 months and no answer for this issue
I'm closing it

although, I still have it :

![Screenshot from 2021-12-05 18-40-43](https://user-images.githubusercontent.com/9513216/144757269-43056854-9c0a-4a8e-92fa-2b4aa745f870.png)

**Comment by AymenLA** [comment]
issue is not solved and no follow-up was made
