### ISSUE TITLE
[darwin] Add a Protocol for Device Controller 

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#811]
#### Problem
Need an easy way to mock Device Controller.
The current implementation is rigid (tightly coupled with the c++ impl). 
 #### Proposed Solution
We can make the current Device Controller implement a new Controller Protocol such that it would be easy to create Mock Device Controllers for testing.

**Comment by woody-apple** [comment]
SW BRB: @sagar-apple what are next steps here?

**Comment by sagar-apple** [comment]
I think this is done. Closing. The "Controller" side has evolved quite a bit since this Issue was first filed.
