### ISSUE TITLE
ci : [TC-OO-1_1] Global attributes with server as DUT - write the default values to ClusterRevision is disabled

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#8150]
SDK needs to add support for writing the default values to ClusterRevision

    - label:
          "write the default values to mandatory global attribute:
          ClusterRevision"
      disabled: true
      command: "writeAttribute"
      attribute: "Cluster Revision"
      arguments:
          value: 2
      response:
          error: 1

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/Test_TC_OO_1_1.yaml

**Comment by vivien-apple** [comment]
Closing it has been enabled a while ago.
