### ISSUE TITLE
ci : [TC-OO-1_1] Global attributes with server as DUT - write the default values to FeatureMap is disabled

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#8151]
SDK needs to add support for writing default values to FeatureMap

    - label: "write the default values to optional global attribute: FeatureMap"
      disabled: true
      command: "writeAttribute"
      attribute: "Feature Map"
      arguments:
          value: 0
      response:
          error: 1

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/Test_TC_OO_1_1.yaml

**Comment by vivien-apple** [comment]
Closing it has been enabled a while ago.
