### ISSUE TITLE
ci : [TC-OO-2.1] Attributes with server as DUT - writing default values to OnOff is disabled

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#8152]
SDK needs to add support for writing default values to OnOff

    - label: "write the default value of mandatory attribute: OnOff"
      disabled: true
      command: "writeAttribute"
      attribute: "On/Off"
      arguments:
          value: 0
      response:
          error: 1

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/Test_TC_OO_2_1.yaml

**Comment by vivien-apple** [comment]
Closing as it has been enabled a while ago.
