### ISSUE TITLE
ci : [TC-OO-2.1] Attributes with server as DUT - writing default values to GlobalSceneControl is disabled

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#8153]
SDK needs to add support to write default values to GlobalSceneControl

    - label: "write the default value to LT attribute: GlobalSceneControl"
      disabled: true
      command: "writeAttribute"
      attribute: "Global Scene Control"
      arguments:
          value: 0
      response:
          error: 1

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/Test_TC_OO_2_1.yaml

**Comment by vivien-apple** [comment]
Closing as it has been enabled a while ago.
