### ISSUE TITLE
ci : [TC-OO-2.1] Attributes with server as DUT - reading back the default values written to GlobalSceneControl is disabled

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#8154]
SDK needs to add support to read back the default values written to GlobalSceneControl

    - label: "reads back LT attribute: GlobalSceneControl"
      disabled: true
      command: "readAttribute"
      attribute: "Global Scene Control"
      response:
          value: 1

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/Test_TC_OO_2_1.yaml

**Comment by vivien-apple** [comment]
Closing as it has been enabled a while ago.
