### ISSUE TITLE
Better handle/structure memory management

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#829]
`chipZclRawAlloc()` has the ability to return `NULL` in the case where the allocation fails, yet that case is not checked here. 

EDIT: Looking through this PR more it does appear there is a general lack of handling error conditions around the dynamic memory management. If this is code that is intended more to get demos put together this is probably fine, but if we plan to use this code more long-term we should consider at least creating an issue to track this (if one doesn't already exist)

_Originally posted by @BroderickCarlin in https://github.com/project-chip/connectedhomeip/pull/804_

**Comment by cecille** [comment]
Closing this issue - chipZclRawAlloc is no longer used, general memory management is handled in other issues.
