### ISSUE TITLE
Copy/pasted non-spec-compliant code in subscribe message definitions

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#8308]
#### Problem
See https://github.com/project-chip/connectedhomeip/pull/8285#issuecomment-878633570 -- ` SubscribeRequest::Parser::GetMinIntervalMs` is not getting the interval (!) and should be treating the value it gets as _seconds_ per spec.

 #### Proposed Solution
Probably revert #8285 and also fix the code to get the right value.  And fix the tests to actually test the code.

**Comment by bzbarsky-apple** [comment]
Also, I have no idea what `FinalSyncInterval` is.  It's not in the actual message definitions in the IM spec; "8.5.3. Subscribe Response Action" has "MinInterval" and "MaxInterval".  It's in the encoding spec, of course, but all that means is that the encoding spec can't encode what the actual messages are supposed to be in its current state...

@mrjerryjohns @CamWms

**Comment by yunhanw-google** [comment]
fixed in latest code
