### ISSUE TITLE
Clarify and fix`FinalSyncInterval` for subscribe in IM spec and code

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#8312]
Also, I have no idea what `FinalSyncInterval` is.  It's not in the actual message definitions in the IM spec; "8.5.3. Subscribe Response Action" has "MinInterval" and "MaxInterval".  It's in the encoding spec, of course, but all that means is that the encoding spec can't encode what the actual messages are supposed to be in its current state...

@mrjerryjohns @CamWms

_Originally posted by @bzbarsky-apple in https://github.com/project-chip/connectedhomeip/issues/8308#issuecomment-878637392_

**Comment by bzbarsky-apple** [comment]
We don't have a FinalSyncInterval in our tree anymore.
