### ISSUE TITLE
Support concurrent CASE handshake sessions

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#8342]
#### Problem
Currently, a device/controller can only have an ongoing CASE handshake. The following use case is not achievable.
1. Node A starts a CASE handshake with Node B
2. Node C starts another CASE handshake with Node A, while handshake with Node B is in progress

 #### Proposed Solution

There are multiple changes needed to support this.

- [ ] Update CASEServer to be able to track multiple ongoing CASE handshakes
- [ ] Don't mutate local credential/certificate set to validate peer's credentials

Add other changes to the issue as detected while enabling this functionality.

**Comment by pan-apple** [comment]
Referring the comment from @tcarmelveilleux, so not to lose track of it.
https://github.com/project-chip/connectedhomeip/issues/8207#issuecomment-887547995

**Comment by msandstedt** [comment]
When we implement this, we will also likely want to move to a dynamically-sized unauthenticated session pool. In such case, we will also need to add a garbage collection mechanism for stale sessions (ref count 0), as eviction no longer works in such an approach.

CC @kghost , @samadDotDev , @kianooshkarami

**Comment by woody-apple** [comment]
Keeping in v1 for now.

**Comment by Alami-Amine** [comment]
It seems that we still do not support concurrent CASE handshake sessions
