### ISSUE TITLE
Refactor OperationalCredentialsDelegate.h so that GetIntermediateCACertificate and GetRootCACertificate are asynchronous

### ISSUE THREAD

**Issue by fengli** [project-chip/connectedhomeip#8353]
#### Problem

Currently, in [OperationalCredentialsDelegate.h](https://github.com/project-chip/connectedhomeip/blob/ba7774d6e98f8bd05707c5f88a05707ffc1bcdc5/src/darwin/Framework/CHIP/CHIPOperationalCredentialsDelegate.h), GetIntermediateCACertificate and GetRootCACertificate are blocking call. It'll be beneficial if both call can be made asynchronous with callbacks. Some use cases, obtaining root certificate and intermediate certificate requires a network call.

 #### Proposed Solution

Refactor GetIntermediateCACertificate and GetRootCACertificate in OperationalCredentialsDelegate.h so that it's asynchronous.

**Comment by pan-apple** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/8550
