### ISSUE TITLE
Cleanup special numbering in ZCL/ZAP

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#836]
Heh. This is an honest comment basically exposing a problem of this body of code not supporting negative integers with length greater than 4 bytes. We should create a github issue to figure out what to do with this. It's been a long-standing fact, known with this implementation and since longer-than-4-bytes negative numbers in ZCL are purely theoretic at this point, it has never been a problem.
But you are correct: this is a scary thing, and it will one day byte someone badly, so we should find a better way to deal with it than play dumb and say:
  "Waaa? You did not read that obscure comment in the doxygen?"

So point taken, we should add an issue.

_Originally posted by @tecimovic in https://github.com/project-chip/connectedhomeip/pull/804_

**Comment by woody-apple** [comment]
SW BRB: @bzbarsky-apple @vivien-apple  is anything needed here?

**Comment by bzbarsky-apple** [comment]
I think this is about the initial "dotdot"-like Silicon Labs code we had, which has since been removed in favor of the "zigbeepro" code.  So nothing to do here, afaict.
