### ISSUE TITLE
[pase] PBKDFParamRequest payload is incomplete

### ISSUE THREAD

**Issue by turon** [project-chip/connectedhomeip#8360]
#### Problem

The spec defines PBKDFParamRequest message as:
```
struct {
  byte randomFromInitiator[32];
  byte initiatorSessionId[2];
  byte passcodeID[2];
  boolean hasPBKDFParameters;
} PBKDFParamRequest
```

Yet the implementation in `PASESession::SendPBKDFParamRequest` only constructs the first field.
 
 #### Proposed Solution
Fix implementation to match spec.

**Comment by yufengwangca** [comment]
@emargolis  this seems related to the work you recently did, could you help to take a look?

**Comment by emargolis** [comment]
From my inspection of the latest SDK code this issue was already addressed.

@pan-apple @bzbarsky-apple  please confirm

**Comment by bzbarsky-apple** [comment]
Yes, this looks good now.
