### ISSUE TITLE
Ubuntu 20.04.1 TLS source ./scripts/bootstrap.sh ERROR subprocess.CalledProcessError:Command [...]returned non-zero exit status 1.

### ISSUE THREAD

**Issue by 736676938** [project-chip/connectedhomeip#8406]
zhaoxu@ubuntu:/mnt/hgfs/shear/ceshi/connectedhomeip$ source ./scripts/bootstrap.sh 

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...[\]^[|]
b'[P19632 01:12:12.939 client.go:306 W] RPC failed transiently. Will retry in 1s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 203.111.254.117:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"1s"}\n[P19632 01:12:36.963 client.go:306 W] RPC failed transiently. Will retry in 2s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 203.111.254.117:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"2s"}\n[P19632 01:13:00.011 client.go:306 W] RPC failed transiently. Will retry in 4s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 203.111.254.117:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"4s"}\n[P19632 01:13:25.083 client.go:306 W] RPC failed transiently. Will retry in 8s    {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 203.111.254.117:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"8s"}\n[P19632 01:13:56.107 client.go:306 W] RPC failed transiently. Will retry in 16s   {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 104.244.46.85:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"16s"}\n[P19632 01:14:33.158 client.go:306 W] RPC failed transiently. Will retry in 32s   {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 104.244.46.85:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"32s"}\n[P19632 01:15:28.210 client.go:306 W] RPC failed transiently. Will retry in 1m4s  {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 104.244.46.85:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"1m4s"}\n[P19632 01:16:53.312 client.go:306 W] RPC failed transiently. Will retry in 2m8s  {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 104.244.46.85:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"2m8s"}\n[P19632 01:19:22.397 client.go:306 W] RPC failed transiently. Will retry in 4m16s {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 75.126.115.192:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"4m16s"}\n[P19632 01:23:59.546 client.go:306 W] RPC failed transiently. Will retry in 8m32s {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 162.125.2.5:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository", "sleepTime":"8m32s"}\n[P19632 01:32:52.692 client.go:350 W] RPC failed permanently: rpc error: code = Internal desc = prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix": dial tcp 108.160.167.174:443: connect: connection refused {"error":"rpc error: code = Internal desc = prpc: when sending request: Post \\"https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix\\": dial tcp 108.160.167.174:443: connect: connection refused", "host":"chrome-infra-packages.appspot.com", "method":"ListPrefix", "service":"cipd.Repository"}\nError: prpc: when sending request: Post "https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ListPrefix": dial tcp 108.160.167.174:443: connect: connection refused.\n'
Traceback (most recent call last):
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 647, in <module>
    sys.exit(main())
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 639, in main
    return EnvSetup(**vars(parse())).setup()
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 345, in setup
    result = step(spin)
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 432, in cipd
    spin=spin):
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/update.py", line 199, in update
    if not check_auth(cipd, package_files, spin):
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/update.py", line 116, in check_auth
    inaccessible_paths = _check_all_paths()
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/update.py", line 100, in _check_all_paths
    [cipd, 'ls', path], stderr=subprocess.STDOUT).decode()
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/cipd', 'ls', 'gn/gn']' returned non-zero exit status 1
zhaoxu@ubuntu:/mnt/hgfs/shear/ceshi/connectedhomeip$ source ./scripts/bootstrap.sh 

  WELCOME TO...

  ▄███▒  ░▓█  ░▓█ ░▓█▓ ▒█████▄
 ██▒ ▀█▒  ▒█   ▒█  ░█▒  ▒█░  █░
 █▓░      ▒██████  ░█▒  ▒█▄▄▄█░
 ▓█   █▒  ▒█   ▒█  ░█░  ▒█▀
 ░▓███▀  ░▓███░▓█▒ ░█░  ▒█

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...[/][P20414 01:54:44.885 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/0/TEQA2BwAc08bDs0UtkrDd43ZOdKdgH8TvQijwfjdxIsC
[P20414 01:54:44.898 client.go:1718 E] Failed to install gn/gn/linux-amd64:TEQA2BwAc08bDs0UtkrDd43ZOdKdgH8TvQijwfjdxIsC - symlink TEQA2BwAc08bDs0UtkrDd43ZOdKdgH8TvQijwfjdxIsC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/0/0dvpUxZPJggP: operation not supported
[P20414 01:54:45.021 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/1/wq2hFn8Q-1WOBOuxw2U33IWshwcfJgH-a7Zt2Bq-viYC
[P20414 01:54:45.032 client.go:1718 E] Failed to install infra/ninja/linux-amd64:wq2hFn8Q-1WOBOuxw2U33IWshwcfJgH-a7Zt2Bq-viYC - symlink wq2hFn8Q-1WOBOuxw2U33IWshwcfJgH-a7Zt2Bq-viYC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/1/qVxeNfuBAtvJ: operation not supported
[P20414 01:55:13.718 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/2/tyRDKSNgQJXdOvCiYBea_xUu4wKTvkFiOdrJjfMEZrgC
[P20414 01:55:13.895 client.go:1718 E] Failed to install infra/cmake/linux-amd64:tyRDKSNgQJXdOvCiYBea_xUu4wKTvkFiOdrJjfMEZrgC - symlink tyRDKSNgQJXdOvCiYBea_xUu4wKTvkFiOdrJjfMEZrgC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/2/PJs5enW6bOVT: operation not supported
[P20414 01:55:14.167 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/3/LPWyPw6ocZpqNafCV-Jw3kCCd1RNypIXo0uM0vr73isC
[P20414 01:55:14.184 client.go:1718 E] Failed to install pigweed/third_party/bloaty-embedded/linux-amd64:LPWyPw6ocZpqNafCV-Jw3kCCd1RNypIXo0uM0vr73isC - symlink LPWyPw6ocZpqNafCV-Jw3kCCd1RNypIXo0uM0vr73isC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/3/9Kp5RUY75iCo: operation not supported
[P20414 01:56:14.651 client.go:1718 E] Failed to install pigweed/third_party/gcc-arm-none-eabi/linux-amd64:wiJ_wmy34ASBeOyRsfNuZf4nMIRpqoUH7vVW7uHqfEoC - symlink libcc1.so.0.0.0 /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/4/6J02vPJIZcEi/lib/uLtkIPzmId78: operation not supported (and 7 other errors)
[P20414 01:56:15.598 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/5/73R9rFfrEWo02NTcJBmtddxWJzZso5ItF_PF1sNWkRoC
[P20414 01:56:15.662 client.go:1718 E] Failed to install infra/3pp/tools/protoc/linux-amd64:73R9rFfrEWo02NTcJBmtddxWJzZso5ItF_PF1sNWkRoC - symlink 73R9rFfrEWo02NTcJBmtddxWJzZso5ItF_PF1sNWkRoC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/5/ZzQxkzrhOmcf: operation not supported
[P20414 01:57:47.153 client.go:1718 E] Failed to install fuchsia/third_party/clang/linux-amd64:zRvL_ACCGLlvQyyLi6bT_5kSLvVhxlGr3sepp98wsqAC - symlink libunwind.so.1.0 /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/6/vQXsqEKCoQE3/lib/x86_64-unknown-fuchsia/c++/asan+noexcept/3_53I32PX8pb: operation not supported (and 95 other errors)
[P20414 02:01:27.952 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/7/6g8E7OutE0d2JQbhcRzB57usngfYF1oLCsx3wXgHH6MC
[P20414 02:01:38.988 client.go:1718 E] Failed to install infra/3pp/tools/go/linux-amd64:6g8E7OutE0d2JQbhcRzB57usngfYF1oLCsx3wXgHH6MC - symlink 6g8E7OutE0d2JQbhcRzB57usngfYF1oLCsx3wXgHH6MC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/7/fZfmrCno4PPi: operation not supported
[P20414 02:01:40.370 deployer.go:1207 W] Failed to create symlink for protoc-gen-go
[P20414 02:01:40.370 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/8/N9ymWVqOj2X-5eYnpss8SZCOO7-zFzTnYcsiJHutWPIC
[P20414 02:01:40.445 client.go:1718 E] Failed to install pigweed/third_party/protoc-gen-go/linux-amd64:N9ymWVqOj2X-5eYnpss8SZCOO7-zFzTnYcsiJHutWPIC - symlink .cipd/pkgs/8/_current/protoc-gen-go /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/PpPTRUZqPeTH: operation not supported
[P20414 02:02:08.161 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/9/ymFsDHsap9IxrVBrtqNOPNlMKGOXCFfHpmfdYWFGnXsC
[P20414 02:02:08.419 client.go:1718 E] Failed to install pigweed/third_party/openocd/linux-amd64:ymFsDHsap9IxrVBrtqNOPNlMKGOXCFfHpmfdYWFGnXsC - symlink ymFsDHsap9IxrVBrtqNOPNlMKGOXCFfHpmfdYWFGnXsC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/9/D5vPdWr9zb7l: operation not supported
[P20414 02:02:09.450 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/10/aQVFyOYwGuka-VdJKAAoiZmz9-Xgz7HskyH4sifyHvEC
[P20414 02:02:09.469 client.go:1718 E] Failed to install pigweed/host_tools/linux-amd64:aQVFyOYwGuka-VdJKAAoiZmz9-Xgz7HskyH4sifyHvEC - symlink aQVFyOYwGuka-VdJKAAoiZmz9-Xgz7HskyH4sifyHvEC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/10/fecTb0cNMlog: operation not supported
[P20414 02:02:17.587 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/11/uy7U74UwmOYq2cKhQ9D4H0M_AX6BXxPAzdMIzRwrlR4C
[P20414 02:02:17.610 client.go:1718 E] Failed to install infra/rbe/client/linux-amd64:uy7U74UwmOYq2cKhQ9D4H0M_AX6BXxPAzdMIzRwrlR4C - symlink uy7U74UwmOYq2cKhQ9D4H0M_AX6BXxPAzdMIzRwrlR4C /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/11/6t48NzQyw8B4: operation not supported
[P20414 02:02:31.910 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/12/FFZaD9tecL-z0lq2XP_7UqiAaMgRGwXTyvcmkv7XCQcC
[P20414 02:02:32.107 client.go:1718 E] Failed to install fuchsia/third_party/qemu/linux-amd64:FFZaD9tecL-z0lq2XP_7UqiAaMgRGwXTyvcmkv7XCQcC - symlink FFZaD9tecL-z0lq2XP_7UqiAaMgRGwXTyvcmkv7XCQcC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/12/9LrMJA6BbyU4: operation not supported
[P20414 02:02:38.339 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/13/qONcLgh-pzcRx8Dk6sTCZBVj0WTCoZvctvZ5dZPsL7wC
[P20414 02:02:38.533 client.go:1718 E] Failed to install infra/3pp/tools/renode/linux-amd64:qONcLgh-pzcRx8Dk6sTCZBVj0WTCoZvctvZ5dZPsL7wC - symlink qONcLgh-pzcRx8Dk6sTCZBVj0WTCoZvctvZ5dZPsL7wC /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/13/7K5W7qAc6aRl: operation not supported
[P20414 02:03:03.751 deployer.go:1207 W] Failed to create symlink for BUILD
[P20414 02:03:03.752 deployer.go:353 W] Deploy aborted, cleaning up /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/14/I8CfASmm-ID03f6uI_K9yahxiGgYBTSmf3ytajQ0L7kC
[P20414 02:03:04.514 client.go:1718 E] Failed to install fuchsia/third_party/kythe:I8CfASmm-ID03f6uI_K9yahxiGgYBTSmf3ytajQ0L7kC - symlink ../.cipd/pkgs/14/_current/BUILD /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/kythe/X-_UaRmxge7c: operation not supported
[P20414 02:03:04.683 client.go:1718 E] Failed to install fuchsia/third_party/kythe-libs/linux-amd64:HpLfjbCYG5c44sh5UBs2q0-AotPeUJ4E6MsrWTe-4SwC - symlink libm-2.30.so /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/15/5k_1U09mjdtC/tT3K7NwbB1xD: operation not supported (and 1 other error)
Error: failed to update packages, see the log.
/mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/cipd ensure -ensure-file /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed.ensure -root /mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed -log-level warning -cache-dir /home/zhaoxu/.cipd-cache-dir -max-threads 0

None
Traceback (most recent call last):
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 647, in <module>
    sys.exit(main())
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 639, in main
    return EnvSetup(**vars(parse())).setup()
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 345, in setup
    result = step(spin)
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 432, in cipd
    spin=spin):
  File "/mnt/hgfs/shear/ceshi/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/update.py", line 248, in update
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/cipd', 'ensure', '-ensure-file', '/mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed.ensure', '-root', '/mnt/hgfs/shear/ceshi/connectedhomeip/.environment/cipd/pigweed', '-log-level', 'warning', '-cache-dir', '/home/zhaoxu/.cipd-cache-dir', '-max-threads', '0']' returned non-zero exit status 1
zhaoxu@ubuntu:/mnt/hgfs/shear/ceshi/connectedhomeip$ 

HELP

**Comment by iot-lorawan** [comment]
Hi,
    我这边souce的时候也出现了一样的client.go:1666 E] [unzip  8/17] Failed to install infra/3pp/tools/go/linux-amd64: symlink 类似问题，后面你这边有解决吗

**Comment by iot-lorawan** [comment]
log:
[P6696 16:46:48.909 deployer.go:346 W] [unzip  8/17] Deploy aborted, cleaning up /mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/16/-xKRu10txxPJsPJD1jyJi-kISvT6ZvAnXLKqmKPt-ZsC
[P6696 16:46:51.260 client.go:1666 E] [unzip  8/17] Failed to install infra/3pp/tools/go/linux-amd64: symlink -xKRu10txxPJsPJD1jyJi-kISvT6ZvAnXLKqmKPt-ZsC /mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed/.cipd/pkgs/16/dLy3K94wsj7C: operation not supported
Error: failed to update the deployment.
/mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/cipd ensure -ensure-file /mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed.ensure -root /mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed -log-level debug -json-output /mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed-output.json -cache-dir /root/.cipd-cache-dir -max-threads 0
None
Traceback (most recent call last):
  File "/mnt/hgfs/matter/chip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 679, in <module>
    sys.exit(main())
  File "/mnt/hgfs/matter/chip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 671, in main
    return EnvSetup(**vars(parse())).setup()
  File "/mnt/hgfs/matter/chip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 414, in setup
    result = step(spin)
  File "/mnt/hgfs/matter/chip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 497, in cipd
    if not cipd_update.update(cipd=cipd_client,
  File "/mnt/hgfs/matter/chip/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/cipd_setup/update.py", line 250, in update
    subprocess.check_call(cmd,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/cipd', 'ensure', '-ensure-file', '/mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed.ensure', '-root', '/mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed', '-log-level', 'debug', '-json-output', '/mnt/hgfs/matter/chip/connectedhomeip/.environment/cipd/pigweed-output.json', '-cache-dir', '/root/.cipd-cache-dir', '-max-threads', '0']' returned non-zero exit status 1.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
