### ISSUE TITLE
We should not require commissioners to add a root cert before calling AddNOC if the root is already known

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#8434]
#### Problem
Right now our commissioning flow assumes the commissioner will call AddTrustedRootCertificate, and in particular we store the root cert in our "fabric" representation.  Per spec, it's not clear that a commissioner is required to do this (see https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/3579 ), and in any case trusted roots are not stored per-fabric in the spec.

 #### Proposed Solution
Make AddNOC look for existing root certs with the right public key and use them if found.

@tcarmelveilleux

**Comment by bzbarsky-apple** [comment]
@msandstedt Do your recent changes resolve this?

**Comment by bzbarsky-apple** [comment]
This is not resolved, and this is in fact a spec-compliance issue...

**Comment by andy31415** [comment]
Review: spec is unclear if keystore is to be shared or not. A spec issue exists:

https://github.com/CHIP-Specifications/connectedhomeip-spec/issues/5420

**Comment by woody-apple** [comment]
Cert Blocker Review: Closing this as we believe the other issue will go into 1.0 spec.
