### ISSUE TITLE
We don't support advertising multiple operational identities

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#8438]
#### Problem
Both `DiscoveryImplPlatform::Advertise(const OperationalAdvertisingParameters & params)` and `AdvertiserMinMdns::Advertise(const OperationalAdvertisingParameters & params)` override an existing advertisement if there is one.  This makes it impossible to advertise multiple operational identities.

 #### Proposed Solution
Fix both codepaths to support multiple operational ids.

See also https://github.com/project-chip/connectedhomeip/issues/8037 and https://github.com/project-chip/connectedhomeip/issues/6141

@andy31415 @cecille @pan-apple

**Comment by andy31415** [comment]
As far as I am aware, we are able to advertise multiple operational networks and we are able to do operational discovery for specific identities. Multi-admin tests  validate that.
