### ISSUE TITLE
Add IM/Ember ACL support

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#8442]
There is a declarative thing where for every attribute or command the relevant access is encoded in the XML and then we generate whatever from it. And we match ACLs against that whatever.

**Comment by tcarmelveilleux** [comment]
@tecimovic is working on XML encoding

**Comment by mlepage-google** [comment]
Dupe of:
- #10246 for the zap parts
- #10247 for the ember parts

Mitigated in the interim by #14283

Closing.
