### ISSUE TITLE
reverts are too slow

### ISSUE THREAD

**Issue by mspang** [project-chip/connectedhomeip#8493]
On multiple occasions I have realized that a change I have merged (not necessarily my changes) has broken the build.

There is no expedient way for me to revert such changes - the revert has to go through CI again, even if it's undoing the last change submitted, and this currently take hours.

It would help minimize disruption have a faster path for (clean) reverts so we can fix breakage as soon as it is discovered.

**Comment by andy31415** [comment]
I am not sure we have a good path. Admin-push of revert works, however that is obviously not ideal.
