### ISSUE TITLE
Hash_SHA256_Stream is missing intermediate digest computation

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#8495]
#### Problem
CASE spec calls for partial transcript in S2K/S3K computation, but full transcript for final keys. However `Hash_SHA256_Stream` can only give final digest and cannot give an intermediate result, which is required.

 #### Proposed Solution
Augment public API to have `GetDigest()` for current digest state in addition to `Finish()`.

**Comment by emargolis** [comment]
Normally, there is no such thing in crypto as "intermediate digest" and introduction of new method to calculate that will be very confusing. I would like to avoid that if possible.

To ease on CASE processing, can we update CASE spec to calculate:
`TranscriptHash1 = CHIP_Crypto_Hash(message = Msg1)`
`TranscriptHash2 = CHIP_Crypto_Hash(message = TranscriptHashMsg1 || Msg2)`
`TranscriptHash3 = CHIP_Crypto_Hash(message = TranscriptHashMsg2 || Msg3)`

@balducci-apple @bzbarsky-apple @tcarmelveilleux  your opinion?

**Comment by tcarmelveilleux** [comment]
"intermediate digest" is a misnomer.

I have seen many instances in crypto protocols in the past of obtaining transcripts at multiple points. The hard way is to keep all the data. The method I add here is not wrong and does not do anything unexpected. It is well documented, and it allows computing the digest to-spec without changing the spec or keeping copies of messages long-lost (which are problematic from a memory perspective).

**Comment by emargolis** [comment]
After chatting with @tcarmelveilleux I agree that introduction of `GetDigest()` might be preferred option at the moment, without a need to change the spec.
