### ISSUE TITLE
Need to clearly document the threading invariants around PlatformManager ScheduleWork and PostEvent

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#8587]
#### Problem
There seems to be a significant lack of clarity around whether `ScheduleWork` and `PostEvent` on the platform manager are "threadsafe" in the sense that they can be called from any thread without taking locks or whether some sort of lock needs to be held.  Some callers clearly assume it's OK to `ScheduleWork` from outside the CHIP thread, but the code being added in https://github.com/project-chip/connectedhomeip/pull/8472/files#diff-3a4487737723239802e02e5a05c96ceac7e9c9a418ce6f421758b1beb7c2e379 very much assumes it's not ok.

 #### Proposed Solution

1. Decide what the right behavior is.  I would argue it should be "you don't have to hold a lock to call these functions", because that would be the normal mode of interacting with the Matter thread in the "spin up a separate Matter thread" setup.
2. Ensure all platform manager implementations have this behavior.
3. Document the behavior.

@kpschoedel @msandstedt @erjiaqing @tcarmelveilleux

**Comment by erjiaqing** [comment]
Just did some code reading, after #7195, calling PostEvent is thread safe on every platform. I think I should change those lines and remove redundant locks.
