### ISSUE TITLE
OTA Cluster: change supportedProtocols back to list argument

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#8605]
#### Problem
Lists are not yet supported in ember/IM code, and commands with list arguments are unable to be parsed without error currently. `QueryImage` is one such command that uses a list argument for `supportedProtocols`.

In the meantime, we will make this argument a single value instead of a list of values. After #8313 is merged, we should change `supportedProtocols` back to a list argument.

 #### Proposed Solution
After #8313 is merged, we should change `supportedProtocols` back to a list argument.

**Comment by carol-apple** [comment]
Fixed by #11336
