### ISSUE TITLE
Need streaming style API for AES CCM encrypt/decrypt

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#862]
#### Problem
The current API only supports one-shot encryption and decryption. For example, the user must provide a contiguous block of plaintext data for encryption. The authentication tag gets generated corresponding to the data block. Another data block cannot be appended (post encryption) to the encrypted data block.

This is causing issues, because CHIP application data could potentially be split into multiple `PacketBuffer` (one data Packet = a linked list of `PacketBuffer`). We want to encrypt the data packet as a single encrypted entity, i.e. all `PacketBuffer` in the list must be encrypted using same key, initialization vector (nonce), and it must generate one final authentication tag.

The above could be achieved by combining all `PacketBuffer` in the list into one contiguous block of data, encrypting the data block, and splitting the encrypted data back into `PacketBuffer` list. But, this is not optimal due to data copy, and memory overheads. 

 #### Proposed Solution
Ideally, we should be able to setup an encryption/decryption session, and stream each `PacketBuffer` into the session. The session will encrypt/decrypt data in place (using `PacketBuffer` memory). At the end of encryption session, it'll generate the authentication tag.

The problem is more complicated, because `mbedTLS` does not support such an API for AES CCM (it only supports one-shot APIs). We may have to hand roll such functionality by using `mbedTLS` CMAC, and AES_CTR APIs.

**Comment by woody-apple** [comment]
SW BRB: @pan-apple what are next steps, is this still needed?

**Comment by pan-apple** [comment]
This change is not needed for CHIP v1.0. CHIP message framing can work with the current encryption/decryption APIs. We can probably close this issue for now. If a future CHIP spec requires this, we can reopen the issue at that time.
