### ISSUE TITLE
CASE Session prematurely considers Session Establish before receiving an ACK for Sigma R3

### ISSUE THREAD

**Issue by kianooshkarami** [project-chip/connectedhomeip#8631]
#### Problem
As of (SHA: [b0c96ee](https://github.com/project-chip/connectedhomeip/blob/b0c96ee73af4ce1dc6894763f6a78855f8be6e79/src/protocols/secure_channel/CASESession.cpp)),

In the following code snippet, CASESession prematurely considers Pairing complete and Session establish upon successful transmission of SigmaR3 message.

```
CHIP_ERROR CASESession::SendSigmaR3()
{
    ...
    // Call delegate to send the Msg3 to peer

    err = mExchangeCtxt->SendMessage(Protocols::SecureChannel::MsgType::CASE_SigmaR3, std::move(msg_R3));
    SuccessOrExit(err);

    ChipLogDetail(SecureChannel, "Sent SigmaR3 msg");

    err = mCommissioningHash.Finish(messageDigestSpan);
    SuccessOrExit(err);

    mPairingComplete = true;

    // Forget our exchange, as no additional messages are expected from the peer
    mExchangeCtxt = nullptr;

    // Call delegate to indicate pairing completion
    mDelegate->OnSessionEstablished();
   ...
}
```

I believe that CASESession.cpp should wait until it has received the Ack from the other node before considering Pairing complete or that Session is established. While there is a high likelihood that the SigmaR3 message will succeed, but the proper approach here would be to assume that SigmaR3 can potentially fail to be sent successfully in a production environment. 

 #### Proposed Solution
Wait until we have received the ACK for SigmaR3 message before considering session establish or CASE Sussuccesful and handle errors in acknowledge as CASE/Session not established.

**Comment by kianooshkarami** [comment]
This is very similar to https://github.com/project-chip/connectedhomeip/issues/5783.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
