### ISSUE TITLE
Telink build docker image does not seem stable

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#8640]
#### Problem
Docker build of 0.4.31 for telink fails builds, however 0.4.30 succeeds.

This means that either the image build failed somehow (unlikely since image build fails when commands fail during the build) or the build itself is not stable (e.g. some URLs are not versioned)

We need repeatable docker builds: as new images are compiled, we need to keep the vscode image stable and working.

 #### Proposed Solution

Investigate the cause of the failure and address. Fix the download images and make the image not change in time.

**Comment by Damian-Nordic** [comment]
@rikorsev FYI
