### ISSUE TITLE
Move to using constructor/destructor for ReadHandler

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#8650]
#### Problem
We have public APIs on `ReadHandler` (like `Init`, and parts of `OnReadRequest`) that are expected to only be called when the handler tests true for `IsFree`.   This is pretty fragile.

 #### Proposed Solution
Switch to having an actual constructor and destructor for `ReadHandler`.  The constructor would take a delegate and exchange context as arguments.  `Shutdown` would call the destructor.  We'd then need some out-of-band tracking of whether things are free or not, but we have helper classes for object pools that work that way.

That would also lay the groundwork for doing heap-allocation of `ReadHandler`s as needed, instead of pool-allocation.

**Comment by mrjerryjohns** [comment]
Working on this already.

**Comment by holbrookt** [comment]
@mrjerryjohns any update for this? Does this need to be in for 1.0?

**Comment by bzbarsky-apple** [comment]
This was fixed in #13066.
