### ISSUE TITLE
Cleanup prefix chip:: from all cluster implementations in which has 'using namespace chip'

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#8658]
#### Problem
The chip:: prefix is not needed most of the places it's being used here, since those files are doing using namespace chip. 

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by bzbarsky-apple** [comment]
The comment above was about the code that is NOT generated; all the cluster impls have extraneous `chip::` all over the place when they should not, and it hurts readability.
