### ISSUE TITLE
[PythonCtrl] Provide human readable responses when user reads server list attributes

### ISSUE THREAD

**Issue by lazarkov** [project-chip/connectedhomeip#8665]
#### Problem
When you use python-ctrl to read server attributes that are storing list values you get binary responses:
`AttributeReadResult(path=AttributePath(nodeId=853471, endpointId=1, clusterId=1292, attributeId=0), status=0, value=[b'\x02\x00{\x00\xc8\x01'])`

#### Steps to reproduce
1. Start the tv-server app: `./out/debug/chip-tv-app`
2. Pair with the server app: `connect -ip 192.168.0.1 20202021 853471`
3. Run read command for input list: `zclread MediaInput MediaInputList 853471 1 0`
4. Run read command for tv channel list: `zclread TvChannel TvChannelList 853471 1 0`
5. Run read command for application list: `zclread ApplicationLauncher ApplicationLauncherList 853471 1 0`

**Comment by yunhanw-google** [comment]
could be fixed by https://github.com/project-chip/connectedhomeip/pull/8411
