### ISSUE TITLE
EFR32 lighting-app build fails for 4180A 

### ISSUE THREAD

**Issue by kai0989** [project-chip/connectedhomeip#8744]
#### Problem

On current master the lighting-app build for BRD4180A fails with error message:

```
_=/usr/bin/env
+ '[' -z BRD4180A ']'
+ '[' -z '' ']'
+ gn gen --check --fail-on-unused-args --root=./examples/lighting-app/efr32/ '--args=efr32_board="BRD4180A"' ./out/lighting-app/BRD4180A
ERROR at //third_party/connectedhomeip/third_party/efr32_sdk/efr32_sdk.gni:217:3: Source file not found.
  source_set(sdk_target_name) {
  ^----------------------------
The target:
  //:sdk
has a source file:
//third_party/connectedhomeip/third_party/efr32_sdk/repo/util/third_party/crypto/sl_component/sl_mbedtls_support/src/se_ccm.c
which was not found.
```

Building the example for 4161A works

**Comment by hainahouwei** [comment]
@jmartinez-silabs

**Comment by jmartinez-silabs** [comment]
Noted, but BRD4180A cannot currently run matter examples as the RAM usage exceed the available 96kB of ram of the EFR32MG21

**Comment by kai0989** [comment]
I tested the BRD4180B with the exampel from last test event, is this also broken due RAM-issue?

**Comment by jmartinez-silabs** [comment]
Yes both of those boards use MG21 which only has 96kB of RAM. Can I ask you for what company you work for? Do you have an applications engineer assigned at silabs?

**Comment by kai0989** [comment]
I'm working for trilux,  i'm also signed in silabs.

**Comment by jmartinez-silabs** [comment]
We stopped supporting BRD4180B (*EFR32MG21 families*) in Matter due to their RAM limitations. Unclear if/when those parts will be supported again in the near future as matter ram usage is way past 96kb currently
