### ISSUE TITLE
ZEPHYR_TOOLCHAIN_VARIANT not specified

### ISSUE THREAD

**Issue by karthikvenkateshp** [project-chip/connectedhomeip#8746]
#### Problem
Facing build error while trying to build connectedhomeip/examples/lock-app/nrfconnect

<what's wrong or missing, please include any applicable:
 * expected behavior: Should build successfully
  
 * actual behavior
 CMake Error at C:/nrfrepo/ncs/zephyr/cmake/verify-toolchain.cmake:116 (message):
  ZEPHYR_TOOLCHAIN_VARIANT not specified and no Zephyr SDK is installed.

  Please set ZEPHYR_TOOLCHAIN_VARIANT to the toolchain to use or install the
  Zephyr SDK.
  
 * steps to reproduce
 \nrfconnect>west build -b nrf52840dk_nrf52840
 
 * system configuration
 OS: Windows 10 Enterprise
 Version 10.0.18363 Build 18363 
 
 * screenshots, images, logs, etc.
 
![image](https://user-images.githubusercontent.com/88246819/127746792-4d61ba53-a1ef-44d0-94ae-c4eac2fd7b24.png)

*Additional Information:
Tried the below already:
1. C:\Users\karpan\pkvenv\Scripts\activate C:\nrfrepo\ncs\zephyr\zephyr-env.sh
2. set ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
3. set GNUARMEMB_TOOLCHAIN_PATH=C:\gnuarmemb\9 2019-q4-major\bin

SDK installation directory: C:\nrfrepo\ncs
GNU Arm Toolchain Directory: C:\gnuarmemb\9 2019-q4-major\bin

Kindly help in resolving the build issue.

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by Damian-Nordic** [comment]
Have you walked through this instruciton: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/gs_assistant.html#toolchain-manager?

Note that on Windows you can use the Toolchain Manager to automatically install all the necessary dependencies. Then you can use the "Open bash" menu item to open a pre-configured command-line environment for building the examples.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
