### ISSUE TITLE
[Android] Fix memory leaks in cluster code

### ISSUE THREAD

**Issue by austinh0** [project-chip/connectedhomeip#8773]
* Need to call BaseChipCluster.deleteCluster when Java object is garbage collected (related: #8578)
* Need to `delete` both onSuccess and onFailure callbacks when either is invoked

**Comment by yunhanw-google** [comment]
protected void finalize() throws Throwable {
      super.finalize();

      if (chipClusterPtr != 0) {
        deleteCluster(chipClusterPtr);
        chipClusterPtr = 0;
      }
    }
we have deleted cluster when finalize is called,  finalize is triggered when garbage collector is happening
