### ISSUE TITLE
the iOS demo in Chiptool can not be builded, why create a so complex project for iOS! not a good way to spread CHIP

### ISSUE THREAD

**Issue by tigline** [project-chip/connectedhomeip#8808]
#### Problem
<what's wrong or missing, please include any applicable:
 1. can not build the iOS project
 
![image](https://user-images.githubusercontent.com/8511718/128282782-83ea6c87-16b0-4137-bd7d-0bb3c98bc6ae.png)
2. even remove git submodule update --init
 it will need the ninja and gn tools. that really hard to install. I have tried many times.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>
I hope the iOS project should be recreated by the default way. all need files should be in the project. not need run shell scripts when build. that real stops many people to use it.

**Comment by tigline** [comment]
So anyone who can run the iOS demo? how to fix

**Comment by tewarid** [comment]
I am able to build and use ChipTool for iOS without resorting to gn/ninja command line. Open src/darwin/Darwin.xcworkspace in Xcode (from command line `open src/darwin/Darwin.xcworkspace`) and build CHIP Framework first (selected by default) then build or run CHIP Tool App.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!

**Comment by phil-margetson** [comment]
make sure that you've cloned the repo rather than just downloading the zip
