### ISSUE TITLE
Min/Max color temperature has no effect

### ISSUE THREAD

**Issue by helaywang-wiz** [project-chip/connectedhomeip#8809]
`ColorTempPhysicalMaxMireds` and `ColorTempPhysicalMinMireds` attributes are not affecting color temperature calculating, and also, parameters `colorTemperatureMaximum` and `colorTemperatureMinimum` of command `StepColorTemperature` and `MoveColorTemperature` are not affecting, too.

I found `lowLimit` and `highLimit` of struct type `Color16uTransitionState` are set but never used in `color-control-server.cpp`, SDK commit is: `903e149bd636a5cd1a8821864cb073b4f7a9d3d8` of TE4.

How to reproduce:
```
chip-device-ctrl > zclread ColorControl ColorTemperature 12344321 1 0 
attributeValue: 250

chip-device-ctrl > zcl ColorControl StepColorTemperature 12344321 1 0 stepMode=1 stepSize=10 transitionTime=300 colorTemperatureMinimum=5 colorTemperatureMaximum=250 optionsMask=0 optionsOverride=0

chip-device-ctrl > zclread ColorControl ColorTemperature 12344321 1 0 
attributeValue: 260
```

**Comment by bzbarsky-apple** [comment]
@jmartinez-silabs

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
