### ISSUE TITLE
China network issue: Run 'source scripts/activate.sh' failed, failed to access 'chrome-infra-packages.appspot.com'

### ISSUE THREAD

**Issue by KenneyQu** [project-chip/connectedhomeip#8810]
#### Problem
I cloned the matter repo, ready the submodules, then run 'source scripts/activate.sh', but always got error:
**OSError: [Errno 101] Network is unreachable**, After analyisis, I found that I can nor access 'chrome-infra-packages.appspot.com', anyone can reproduce this or meet this issue before.

Env:
    Commit:
    commit 203b25d94211952e52b2bcd991218151dd0c9777 (HEAD -> master, origin/master, origin/HEAD)
    Author: Song GUO <songguo@google.com>
    Date:   Thu Aug 5 15:11:33 2021 +0800

    [cloudbuild] Add compress flag to compress built artifacts (#8781)

![image](https://user-images.githubusercontent.com/46238080/128346659-5e79702c-ae79-41dc-b363-76ef37db244f.png)

**Comment by KenneyQu** [comment]
I checked that it seems the address 'chrome-infra-packages.appspot.com' can not work for China network. Anyone can help?

**Comment by KenneyQu** [comment]
I double checked this again, finally get a proxy from NXP IT to fix this.
This may bring a trouble for Chinese customer, if we can have a default proxy in the code for China network, it will be great.
Comments?

**Comment by hainahouwei** [comment]
FQ吧，老兄

**Comment by woody-apple** [comment]
@andy31415 ?

**Comment by niulei0514** [comment]
# Put CIPD client in tools so that users can easily get it in their PATH.
CIPD_HOST = 'chrome-infra-packages.appspot.com'
源码中的 这个地址确实对中国用户很不友好........  要么找代理  要么翻墙...  否则没办法构建.......
