### ISSUE TITLE
Hue value is calculated incorrectly when exceeds Max/Min value

### ISSUE THREAD

**Issue by helaywang-wiz** [project-chip/connectedhomeip#8828]
When Device executing ColorControl Cluster commends `StepHue` and `MoveHue`, if the hue value reaches `(MAX_HUE_VALUE(0xFE) + 1)`, the result will be `0xFE + 1 - 0xFE = 1` (following current implementation of SDK).
But according to the Matter's Specification: `Increase the device’s hue by one step, in a continuous fashion. If the hue value reaches the maximum value then proceed to the minimum allowed value.`, that may mean `MAX_HUE_VALUE + 1 = MIN_HUE_VALUE`, so if the hue value reaches `(MAX_HUE_VALUE(0xFE) + 1)`, the result would be `0`.

There is also the same problem when subtracting hue value and exceeds MIN_HUE_VALUE .

How to reproduce:
```
chip-device-ctrl > zclread ColorControl CurrentHue 12344321 1 0
attributeValue: 249

chip-device-ctrl > zcl ColorControl StepHue 12344321 1 0 stepMode=1 stepSize=10 transitionTime=300 optionsMask=0 optionsOverride=0

zclread ColorControl CurrentHue 12344321 1 0
attributeValue: 5
```

**Comment by jmartinez-silabs** [comment]
On it
