### ISSUE TITLE
Building this example over ARM 32-bit architecture not working?

### ISSUE THREAD

**Issue by saumildmehta** [project-chip/connectedhomeip#8831]
I have Raspberry pi 4B+ with ubuntu 21.04 32-bit server image running.
But chip compilation gives error and it looks like it supports arm64 architecture only.

Setting up CIPD package manager...skipped (0.1s)
    UnsupportedPlatform('linux-armv7l')
    abandoning CIPD setup

I don't have option to switch my OS to 64-bit. Any guide to build for 32-bit?

**Comment by bzbarsky-apple** [comment]
We absolutely compile for all sorts of 32-bit ARM architectures.

@mspang do you know offhand what that ` UnsupportedPlatform('linux-armv7l')` bit from CIPD means and what needs to be done there?

**Comment by turon** [comment]
We should support 32-bit raspi for v1, though not blocking.
Removed tag `v1_triage_split_4`.

**Comment by woody-apple** [comment]
The base case works on pi, moving post v1.

**Comment by woody-apple** [comment]
Is this still happening for you? Please re-open if so.
