### ISSUE TITLE
Allow vscode image to compile telink binaries

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#8843]
#### Problem
Developers cannot validate  telink compilation from vscode (not easily at least), cloudbuild cannot  validate telink compilation (it uses a single image for all compilations,  which is the vscode image)

 #### Proposed Solution
- Fix the `git clone` revision in the chip-build-telink/Dockerfile image
- ensure that zephyr_base environment variables can be set and used correctly so that one can compile both nrf and telink images

**Comment by rikorsev** [comment]
Hi @andy31415 ,
Can you close the issue?
