### ISSUE TITLE
CASE identity checks are not done

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#8859]
#### Problem
Validation in Sigma2 and Sigma3 processing that the nodes participating in the CASE protocol are the expected participants was implied by the spec, but not made explicit enough.

The necessary checks updates were landed in https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/3682.

 #### Proposed Solution
The validations provided in the diffs of https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/3682 must be implemented.

**Comment by tcarmelveilleux** [comment]
Please double-check which ones are missing

**Comment by emargolis** [comment]
This was addressed with #15829 and updated with #15920
