### ISSUE TITLE
CI did not catch an incorrect file being listed in Makefile.am

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#886]
#### Problem
See https://github.com/project-chip/connectedhomeip/issues/882

We had an incorrect filename listed in a `Makefile.am`, and `make distcheck` failed if you just ran it immediately after bootstrapping, but CI somehow did not catch that.

 #### Proposed Solution
Figure out why CI is not catching that and fix it.

@woody-apple @gerickson @rwalker-apple

**Comment by andy31415** [comment]
Move to GN changed any automake-specific issues and they probably do not apply anymore. Closing on the assumption that this is not a thing anymore.
