### ISSUE TITLE
Improve how the build system handles files under src/app

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#887]
#### Problem
We need to figure out how to only list files under src/app in a single .am each instead of the current setup where we list them in all sorts of .am files (`DataModel.am`, `src/app/plugin/test-unit/Makefile.am`, various `extra_dist.am` files).

 #### Proposed Solution
Have a known-name .am file in each leaf dir (e.g. `src/app/plugin/core-data-model/something.am`) that does the following:

1. Lists, in some variable, the source files that should be compiled in if using that plugin, using `@top_builddir@` anchoring.  My gut feeling is that it should add to the value of said variable, and the variable name should be shared across the leaf dirs.
2. Conditionally include the relevant `domething.am` files based on the selected set of plugins.  For the moment, `DataModel.am` would just include all of them, but we can move to using compile-time defines to decide on the set we want to include, right?  `src/app/plugin/test-unit/Makefile.am` would include the ones it cares about.  Then the includers can add the value of whatever our "some variable" to the variable they really care about.

We would continue to have the existing `extra_dist.am` files that just throw everything into `EXTRA_DIST` and keep unconditionally including these for all subdirs as we do now.  These can be rewritten to include the `something.am` file, so we only list files in one place: `.c` files that might be compiled in go into `something.am`, while other files just go directly into `extra_dist.am`.

Thoughts?  @rwalker-apple @tecimovic

**Comment by andy31415** [comment]
@bzbarsky-apple - do we still need this now that we moved to GN?

I believe the chip-library itself should be clean enough now, however we still use make (and cmake?) for example app builds, so I am unsure what to do with this bug.

**Comment by bzbarsky-apple** [comment]
I think this bug as filed is obsoleted by the GN switch.  The general problem of "example apps have to manually list all sorts of files from `src/app`" is still there, but arguably https://github.com/project-chip/connectedhomeip/issues/1630 tracks that better.  And if not, we should file an issue on that explicitly.
