### ISSUE TITLE
CG1: Update ZAP codegen to generate cluster object definitions

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#8895]
#### Problem
Once #8891 is completed and an example template has been provided for how code-generation for cluster objects should look like, ZAP code-gen should be updated to generate these definitions for all clusters.

**Comment by mrjerryjohns** [comment]
@yunhanw-google, assigning this to you since you've already started taking a crack at this.

**Comment by yunhanw-google** [comment]
Tentative branch is in https://github.com/yunhanw-google/connectedhomeip/tree/feature/update_codegen2
