### ISSUE TITLE
Update OpCreds cluster to not use global fabric table

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#8905]
#### Problem
The current implementation of operational credentials cluster uses a global variable to access fabric table. This makes it impossible to write tests where a same cluster server could be used to commission multiple nodes. Other similar use cases are also impacted by this design.

 #### Proposed Solution
Find a way to pass the fabric table as a context to the cluster server.
Reference: https://github.com/project-chip/connectedhomeip/pull/8826#discussion_r686916835

**Comment by woody-apple** [comment]
@tcarmelveilleux Is this still relevant?
