### ISSUE TITLE
Consolidate code that loops over FabricTable

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#8920]
#### Problem
Current `FabricTable` code has multiple of such loops in different functions.
```
    for (FabricIndex i = kMinValidFabricIndex; i <= kMaxValidFabricIndex; i++)
    {
```

This is error prone as change in logic has to be propagated to all the loop conditions.

 #### Proposed Solution
Find a way to consolidate all the loop in a common place and update the current code to use this common functionality.

**Comment by woody-apple** [comment]
We're in progress of reviewing older issues. Is this still an issue given how old the SDK this was tested against? Please re-open if so. Thanks!
