### ISSUE TITLE
CASE allocates memory based on wire-provided sizes without sound bounds

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#8924]
#### Problem
In CASESession.cpp, there exists several usage of the following pattern:

`VerifyOrExit(msg_R2_Encrypted.Alloc(tlvReader.GetLength()), err = CHIP_ERROR_NO_MEMORY);`

This assumes in many places that `tlvReader.GetLength()` is not a huge value (or contextually large value), even though only certain values are permissible.

 #### Proposed Solution

All usage of `tlvReader.GetLength()` for allocations should be audited and each one should be validated against a valid upper bound for the size of the value being read, within practical limits.

**Comment by holbrookt** [comment]
@tcarmelveilleux I see that a few PRs were merged referencing this. Is the issue fixed?

**Comment by woody-apple** [comment]
Marking as closed, please re-open if still an issue.

**Comment by bzbarsky-apple** [comment]
This is still an issue, as far as I can see.  For example, CASESession::HandleSigma2 still does this:
```
    SuccessOrExit(err = tlvReader.Next());
    VerifyOrExit(TLV::TagNumFromTag(tlvReader.GetTag()) == ++decodeTagIdSeq, err = CHIP_ERROR_INVALID_TLV_TAG);
    VerifyOrExit(msg_R2_Encrypted.Alloc(tlvReader.GetLength()), err = CHIP_ERROR_NO_MEMORY);
```
