### ISSUE TITLE
C2: Delete `gCallbackMgr`, `CHIPClientCallbacks.cpp` and `CommandSender` logic.

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#8960]
#### Problem

Once #8958  is complete, we should then delete the `gCallbackMgr`, `CHIPClientCallbacks.cpp` and `CommandSender` logic since they would have been replaced by `SingleInvokeInitiator`.

**Comment by yunhanw-google** [comment]
fixed by  #9877
