### ISSUE TITLE
Need callback for test harness to get received command requests on simulated nodes

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#8986]
#### Problem

Currently, we have `emberAfPostAttributeChangeCallback` to get notified everyting an attribute is changed, we also need similar calback for commands when a command request is received.

 #### Proposed Solution

Add a callback to interaction model for get notified when a command is received.

**Comment by erjiaqing** [comment]
@wahajsyed @SaileeG @trombadore

**Comment by erjiaqing** [comment]
Since this function is unlikely to be inclused in production builds, can we add flags like `CHIP_TEST_HARNESS` to enable it only on test harness builds?

**Comment by mrjerryjohns** [comment]
Stale.
