### ISSUE TITLE
Accessor functions do not set default values for attributes 

### ISSUE THREAD

**Issue by mkardous-silabs** [project-chip/connectedhomeip#8994]
#### Problem
* Accessor functions do not set default values for attributes in case the ember read function fails.
> EmberAfStatus GetColorLoopTime(chip::EndpointId endpoint, uint16_t * colorLoopTime)
{
    return emberAfReadServerAttribute(endpoint, ColorControl::Id, Ids::ColorLoopTime, (uint8_t *) colorLoopTime,
                                      sizeof(*colorLoopTime));
}

 #### Proposed Solution
* Set attributes in accessor function to default value in case ember read fails

**Comment by bzbarsky-apple** [comment]
@vivien-apple

**Comment by turon** [comment]
Zap support for spec defined default values required for v1.
Removing tag `v1_triage_split_4`

**Comment by bzbarsky-apple** [comment]
`GetColorLoopTime` no longer exists.

It's not clear to me what this issue is about, at this point....

**Comment by woody-apple** [comment]
Closing.
