### ISSUE TITLE
UDP endpoint pool FULL

### ISSUE THREAD

**Issue by samgwd** [project-chip/connectedhomeip#9138]
When running All clusters example on an m5 stack I get this error:

E (7930) chip[IN]: UDP endpoint pool FULL
E (7930) chip[DIS]: Failed to start mDNS server: Inet Error 1000020 (0x000F4254): No more TCP endpoints

**Comment by samadDotDev** [comment]
Try increasing default UDP endpoints to a higher value such as 16, via menuconfig 
`Component Config -> CHIP Core -> Networking Options`
https://github.com/project-chip/connectedhomeip/issues/8071

**Comment by msandstedt** [comment]
Closing as dup of #8071.
