### ISSUE TITLE
Can't install the CHIPTool iOS application on our iPhones

### ISSUE THREAD

**Issue by sagar-apple** [project-chip/connectedhomeip#914]
#### Problem
The CHIPTool iOS app cannot be installed on our phones out of the box.

By default xcode gives you an error.
![image](https://user-images.githubusercontent.com/61470494/83290266-3c2ff480-a19b-11ea-923a-5034b52121cb.png)

Currently to use a real iPhone we need to make modifications to the CHIPTool xcode project.
Specifically the Bundle-ID needs to be set to something not already claimed by another user and the Development Team needs to be set. 

![image](https://user-images.githubusercontent.com/61470494/83290321-55d13c00-a19b-11ea-8ae5-8107e7a159c4.png)

 #### Proposed Solution
There might be a better way to do this?

**Comment by jahess** [comment]
@woody-apple , I just googled CHIPTool for iOS and found this.  Find a work around?

**Comment by adminy** [comment]
This video https://www.youtube.com/watch?v=eW1sPzDY3S0 seems to have an IOS app. Is that in this repository somewhere and are there build instructions?

Thanks
