### ISSUE TITLE
Ranges do not appear on generated .zap file for Thermostat Cluster

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/connectedhomeip#9159]
#### Problem
Thermostat.xml file contains the min and max values for 
Temperature setpoints and limits but they do not appear in the generated .zap file
These were identified in https://github.com/project-chip/connectedhomeip/pull/8878

Also the zap tool displays warnings about signed ints but does generate the correct code. 

Matter spec seems to have removed the ranges

 #### Proposed Solution
Follow up on these

**Comment by eve-cxrp** [comment]
@chrisbeach59 I think this issue should be filed in https://github.com/project-chip/zap ?

**Comment by chrisbeach59** [comment]
https://github.com/project-chip/zap/issues/209

**Comment by woody-apple** [comment]
Looks resolved?
