### ISSUE TITLE
SDK forces user code to use certain folder structrues.

### ISSUE THREAD

**Issue by eve-cxrp** [project-chip/connectedhomeip#9185]
#### Problem
PR #9124 moved the gen folder into zap-generated folder. Now e.g. `src/app/util/config.h` uses `#include <zap-generated/gen_config.h>` as an include. So the sdk user would also need to change their folder structure (rename). Is this really necessary to force that on the sdk user?

**Comment by andy31415** [comment]
I expect that any generated files should eventually be fully separated out from 'regular' source files. I expect build rules to set required include paths for accessing files.

**Comment by eve-cxrp** [comment]
> I expect that any generated files should eventually be fully separated out from 'regular' source files. I expect build rules to set required include paths for accessing files.

But is it the case for now?
