### ISSUE TITLE
Fix "unused variable kReportingDirectionReported" error

### ISSUE THREAD

**Issue by selissia** [project-chip/connectedhomeip#9189]
####  Problem

Removing the `maybe_unused` qualifier from 
https://github.com/project-chip/connectedhomeip/blob/master/src/app/zap-templates/templates/app/CHIPClusters-src.zapt#L58
results in the following compile error in CI (does not happen in local builds):
```generated/lighting-common.CHIPClusters.cpp.o
../../zzz_generated/lighting-app/zap-generated/CHIPClusters.cpp:74:19: error: unused variable 'kReportingDirectionReported' [-Werror,-Wunused-const-variable]
constexpr uint8_t kReportingDirectionReported = 0x00;
```
The `maybe_unused` qualifier was added in an unrelated PR but was highlighted as suspicious in the PR review: [https://github.com/project-chip/connectedhomeip/pull/9115#discussion_r693245797](url) . Changing the qualifier to `constexpr` does not fix the error. 

Need to find a way to address the "unused variable kReportingDirectionReported" error.

 #### Proposed Solution
See https://github.com/project-chip/connectedhomeip/pull/9115#discussion_r693245797 for other suggestions.

**Comment by andy31415** [comment]
I think this is a failure of codegen: if creating a constant in CPP, we should only create it if needed.

My suggested approach in the mean time is to place the constant in a header and that will not trigger the 'unused' warning. Also that constant is not actually dependent on input data, so technically it should not be 'generated code' anyway.
