### ISSUE TITLE
Resource leak in Linux/BlueZ

### ISSUE THREAD

**Issue by samadDotDev** [project-chip/connectedhomeip#9214]
#### Problem

In `src/platform/Linux/bluez/MainLoop.cpp`,
`chip::Device::Internal::MainLoop::EnsureStarted()` spawns a thread which is never joined or cleaned up after.
```
int pthreadErr = pthread_create(&mThread, nullptr, &MainLoop::Thread, reinterpret_cast<void *>(this));
```

 #### Proposed Solution

`pthread_join()` for `mThread` needs to be called at an appropriate place to wait for the thread to terminate. Since `pthread_create` is called with null `attr`, the thread is in joinable state.

**Comment by samadDotDev** [comment]
@msandstedt @z-michel

**Comment by holbrookt** [comment]
@samadDotDev it looks like this is still an issue - can you confirm? Do you know who to assign it to?

**Comment by samadDotDev** [comment]
@holbrookt Yes, the latest master still has `mThread` in joinable state but is never joined.

**Comment by woody-apple** [comment]
Given this is a linux platform example issue, can be resolved post v1.0

**Comment by msandstedt** [comment]
Still an issue.  But as @woody-apple, can be post-1.0.

**Comment by msandstedt** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/23320.
