### ISSUE TITLE
Android support for DNS-SD commissioning

### ISSUE THREAD

**Issue by fengli** [project-chip/connectedhomeip#9220]
#### Problem
The android support for DNS-SD commissioning is missing.

e.g. there's a todo for browse here:
https://github.com/project-chip/connectedhomeip/blob/master/src/controller/java/MdnsImpl.cpp#L71

 #### Proposed Solution
- Full support for dns-sd commissioning MATTER device on Android.

**Comment by woody-apple** [comment]
Given this is an older issue, is this complete at this point? If not, please re-open.
