### ISSUE TITLE
MBedOs does not build: updates in python dependences cause pdoc3 conflict

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#9272]
#### Problem
Bootstrap started failing today apparently due to pip package updates.

A refetch of dependencies seems to have worked, expect mbedos  builds fail  due to some pdoc dependencies.

 #### Proposed Solution
 
 Figure out the cause of the error and fix (actual cause unclear).

**Comment by woody-apple** [comment]
Given this is an older issue, is this complete at this point? If not, please re-open.
