### ISSUE TITLE
Need muti-attribute reads in controller

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9275]

**Comment by mrjerryjohns** [comment]
`ReadClient` is already suited to the needs of multi-attribute reads. Beyond that, it's not clear what other changes to the controller side are necessary to achieve this.

@bzbarsky-apple, any thoughts?

**Comment by bzbarsky-apple** [comment]
The higher level APIs don't support this, but that seems ok for now...
