### ISSUE TITLE
AES-256 support in CHIPCryptoPAL backend even if not in spec

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#9277]
#### Problem

In `AES_CCM_encrypt` in `src/crypto/CHIPCryptoPALOpenSSL.cpp`:

```
    // 16 bytes key for AES-CCM-128
    type = (key_length == 16) ? EVP_aes_128_ccm() : EVP_aes_256_ccm();
```

and in `_isValidKeyLength` in `src/crypto/CHIPCryptoPALmbedTLS.cpp`:

```
static bool _isValidKeyLength(size_t length)
{
    // 16 bytes key for AES-CCM-128, 32 for AES-CCM-256
    if (length == 16 || length == 32)
    {
        return true;
    }
    return false;
}
```

AES-CCM-256 is not in the spec for V1, and it is quite a lot of flash to support. 

 #### Proposed Solution

The support of AES-256 should be removed or made compile-time-optional for V1.0 since it's not part of the spec.

**Comment by woody-apple** [comment]
Issue Scrub: @tcarmelveilleux says this isn't an issue anymore, closing.
