### ISSUE TITLE
Is there a guide document how to test report functionality?

### ISSUE THREAD

**Issue by cabin15** [project-chip/connectedhomeip#9417]
Hello all,

This is not a bug report, but rather a question.
I wish if there is a guide to test report functionality.
My understanding is that,
1) cluster (i.e lighting-app) is launched.
2) controller (i.e chip-tool or python controller) provisions the controllee.
3) controller triggers report to cluster.
4) Any attribute change on the cluster is sent to controller.

Question is, how to test this?
It would be so kind someone show me where the guide document is.
If there is not document, it would be kind to let me know the test command on cluster and controller side.

Thank you in advance.
 >

**Comment by learnSu** [comment]
Do you know how to test? Actually, the report function has been added in the project, but I did not see the report from the wireless message

**Comment by woody-apple** [comment]
Please follow up with @kidip
