### ISSUE TITLE
`InteractionModelDelegate` should be split into narrower scoped callbacks

### ISSUE THREAD

**Issue by mrjerryjohns** [project-chip/connectedhomeip#9460]
#### Problem

`InteractionModelDelegate` is too broad a delegate, making it unwieldy for different client-side applications to do different interactions since all callbacks fan-back to a single delegate point.

Instead, the callback should be split into smaller, interaction-scoped callbacks (1 for read, 1 for subscription, 1 for write, 1 for invoke).

Would recommend adopting the model taken in the #8313 for `InvokeInitiator` is in this vein.

**Comment by yunhanw-google** [comment]
This has been removed now.

**Comment by yunhanw-google** [comment]
https://github.com/project-chip/connectedhomeip/pull/14594
