### ISSUE TITLE
Chip-tool example with lightning app over ble-thread is failing

### ISSUE THREAD

**Issue by saumildmehta** [project-chip/connectedhomeip#9461]
- I am trying to use chip-tool example as gateway and lightning app example as end device over ble-thread.
- I can see pairing is done over BLE successfully and in end device it has enabled its thread role as CHILD.
But in chip-tool logs it prints "pairing successfully" but it waits for any message over BLE and at last it prints log "**No response from device**" and it shuts down.
- I have attached both logs. Is there anything missing to be provided to chip-tool?
- I tried to extend timeout of pairing command but no luck!
- It has not created thread network as well. I have otbr-agent running in backgorund. **Do I need to setup thread network manually or chip-tool will do that job?**
[chip_tool_controller.log](https://github.com/project-chip/connectedhomeip/files/7106849/chip_tool_controller.log)
[lightning_app_device.log](https://github.com/project-chip/connectedhomeip/files/7106850/lightning_app_device.log)

**Comment by woody-apple** [comment]
Given this is an older issue, is this complete at this point? If not, please re-open.
