### ISSUE TITLE
[ota-provider-app] Add configuration for sending "Busy" status and DelayedActionTime

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#9478]
#### Problem
The `status` field of the `QueryImageResponse` command can be
* UpdateAvailable
* Busy
* NotAvailable

Currently the `ota-provider-app` can only send `UpdateAvailable` or `NotAvailable`. The user should be able to configure the app to return a `Busy` status as well.

Similarly, the `ota-provider-app` always sends a `DelayedActionTime` of value 0. It should be configured to send a non-zero value if desired.

 #### Proposed Solution
* add a configuration to send `Busy` status
* add a configuration to set a non-zero `DelayedActionTime` for `QueryImageResponse` and `ApplyUpdateRequestResponse`

**Comment by selissia** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/10037
