### ISSUE TITLE
IM encoding spec rename/update several IB, needs to update the corresponding code in app/MessageDef

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9520]
#### Problem
IM encoding spec rename/update several IB, needs to update the corresponding code in app/MessageDef

**Comment by msandstedt** [comment]
Mentioned here: https://github.com/project-chip/connectedhomeip/pull/9510#discussion_r706314636

Among other things, SubscriptionID needs to be changed from 64bit to 32bit.  Likewise, the special 'invalid' subscription ID used in the PR, UINT64_MAX, needs handling and a #define or constexpr.

**Comment by yunhanw-google** [comment]
yep, agree. thanks

**Comment by mrjerryjohns** [comment]
All have been completed.
