### ISSUE TITLE
[ota-requestor-app] Verify QueryImageResponse command

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#9524]
#### Problem
`ota-requestor-app` does not verify the contents of the `QueryImageResponse` command.

 #### Proposed Solution
At the very least, it should:
- react to different values of `Status` (UpdateAvailable, Busy, NotAvailable) - reference 11.20.3.2 Querying the OTA Provider
- if UpdateAvailable:
  - use the ImageURI to download the image
  - verify that SoftwareVersion is greater than the current version - this is being tracked by https://github.com/project-chip/connectedhomeip/issues/13604
  - print the SoftwareVersionString
- If Busy
  - Emit next query - longest of either 2 minutes from the last QueryImage command or delay specified in `DelayedActionTime` field
- If NotAvailable
  -  Emit next query - longest of either 2 minutes from the last QueryImage command or delay specified in `DelayedActionTime` field

Verification of other fields can be added later.

**Comment by dhrishi** [comment]
@shubhamdp PTAL
