### ISSUE TITLE
[ota-provider-app] Start BDX server after QueryImage

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#9528]
#### Problem
Currently, `ota-provider-app` always initializes a BDX server on startup.

 #### Proposed Solution
Dynamically start the BDX server, and only after receiving a `QueryImage` command and determining that an image is available to transfer over BDX.

**Comment by carol-apple** [comment]
Fixed by https://github.com/project-chip/connectedhomeip/pull/13329
