### ISSUE TITLE
Update ClusterInfo with better naming

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9552]
`ClusterInfo` unfortunately is not a very good name for this type. It really should be an `AttributePath` (to match the terminology in the spec).

_Originally posted by @mrjerryjohns in https://github.com/project-chip/connectedhomeip/pull/9510#discussion_r704793885_

**Comment by woody-apple** [comment]
Naming can wait until post v1.

**Comment by yunhanw-google** [comment]
ClusterInfo has been refactored out, close this one, thanks
