### ISSUE TITLE
Size for Location Attribute in Zap Template is incorrect

### ISSUE THREAD

**Issue by andrew-lifx** [project-chip/connectedhomeip#9558]
#### Problem
In the basic imformation cluster zap template (src/app/zap-templates/zcl/data-model/chip/basic-information-cluster.xml), the Location Attribute has been given a size of 2. This should be 16 according to the Specification

```xml
    <attribute side="server" code="6"  define="LOCATION"                  type="char_string"               length="2"   default=""  writable="true"                >Location</attribute>
```

 #### Proposed Solution
change the length value to 16.

**Comment by tcarmelveilleux** [comment]
The spec currently/correctly says 2.
