### ISSUE TITLE
Verhoeff code is not using tables as const causing unnecessary RAM use

### ISSUE THREAD

**Issue by tima-q** [project-chip/connectedhomeip#9564]
#### Problem
The Verhoeff calculations use fixed tables `sMultiplyTable` and `sPermTable` which are currently not defined as const tables.
This adds 110 bytes RAM for example in the Verhoeff10 case.

The function using the permutation table in the Verfhoeff part also doesn't specify 'const' for the table pointer.
Verhoeff::Permute(int val, **uint8_t * permTable**, int permTableLen, uint64_t iterCount)

https://github.com/project-chip/connectedhomeip/tree/master/src/lib/support/verhoeff
https://github.com/project-chip/connectedhomeip/blob/741ab0a032c290f4653593ceac06048c357ebae5/src/lib/support/verhoeff/Verhoeff10.cpp#L33

 #### Proposed Solution
* Declare tables as const to remove the RAM use
* Add const where applicable to API's

**Comment by bzbarsky-apple** [comment]
Fixed in #11726
