### ISSUE TITLE
ClusterInfo member ordering is probably wrong

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#9620]
#### Problem
ClusterInfo has members ordered based on size, but has incorrect sizes for various members due to the definitions of those members changing.

 #### Proposed Solution
Fix the comments and reorder members as needed.

**Comment by holbrookt** [comment]
@bzbarsky-apple is this needed for 1.0?

**Comment by bzbarsky-apple** [comment]
I suspect we'll need this (and so many other things) to hit memory targets.... But it's not a ship blocker otherwise.

**Comment by woody-apple** [comment]
Moving to post V1, until obviously necessary.

**Comment by yunhanw-google** [comment]
ClusterInfo has been refactored out. close this one. thanks
