### ISSUE TITLE
TE5: [TC-DIAGSW-1.1] cannot be execute because the cluster is unknown in chip-device-ctrl

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [project-chip/connectedhomeip#9637]
#### Problem

TE5: [TC-DIAGSW-1.1] cannot be execute because the cluster is unknown in chip-device-ctrl

chip-device-ctrl > zclread ? DiagnosticsSoftware 
An exception occurred during reading ZCL attribute:
UnknownCluster: DiagnosticsSoftware

 #### Proposed Solution

Include the cluster.

**Comment by jaehs6sam** [comment]
If you type, zclread ?, you will see the cluster name "SoftwareDiagnostic" instead of "DiagnosticsSoftware" by the latest spec. This change will be reflected in TE6.  Refer issue at #9600.
