### ISSUE TITLE
Figure out whether we can determine the sizes of buffers for encoding data model commands better

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#965]
#### Problem
Right now we have to guess at a buffer that will be big enough to hold the results of `chipZclEncodeZclHeader` or equivalent.  It would be ideal if callers did not have to guess at that.

 #### Proposed Solution
I don't have a proposed solution yet.  It depends on the range of different sizes the encoded data might have.

@tecimovic @bhaskar-apple

**Comment by vivien-apple** [comment]
@bzbarsky-apple Would if be OK if the caller just pass a `PacketBuffer *` to the underlying command in `src/app` and the code encoder code has the responsibility to allocate the `PacketBuffer` itself ? The necessary size can be directly generated from for the commands.

**Comment by rwalker-apple** [comment]
or a packetbuffer allocator, yeah.

**Comment by bzbarsky-apple** [comment]
Yeah, that would be fine.  The long-term app API  presumably does not involve `PacketBuffer` if we can avoid it, so starting to hide it now makes sense.
