### ISSUE TITLE
Bootstrapping should perhaps bootstrap various dependent repos

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#967]
#### Problem
Running our "bootstrap" step does not do the equivalent of `make -f Makefile-bootstrap repos`.  This means that people have to run it manually if they need one of those repos.

 #### Proposed Solution
Have `bootstrap` run that step.

**Comment by sagar-apple** [comment]
@bzbarsky-apple sounds like this is not really a thing anymore with submodules?

**Comment by bzbarsky-apple** [comment]
Yep.
