### ISSUE TITLE
CASE messages are out of date compared to specifications

### ISSUE THREAD

**Issue by pan-apple** [project-chip/connectedhomeip#9710]
#### Problem
Specifications were recently updated with respect to CASE Sigma messages. The Sigma1 message can optionally include session resumption related information. The response to Sigma1 can be Sigma2 or Sigma2Resume.

 #### Proposed Solution
- [x] Update CASE messages and the state machine
- [ ] Add method to CASE to trigger session resumption
- [ ] Persist necessary values needed for session resumption
- [ ] Use the new method in the correct use-cases to trigger the resumption

**Comment by woody-apple** [comment]
Appears complete
