### ISSUE TITLE
Need  CHIPRNG  to call GetSecureRandomData for subscription id generation

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9716]
#### Problem
Need GetSecureRandomData to generate subscription id,
it needs #include <support/crypto/CHIPRNG.h>, but somehow CHIPRNG.h is missing
https://github.com/project-chip/connectedhomeip/blob/master/src/app/ReadHandler.cpp#L541

**Comment by emargolis** [comment]
Addressed with #9995
