### ISSUE TITLE
Cleanup IM status code

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9726]
--Typedefes and constexprs for all of the places we currently have uint32_t and PRIx32 would be nice, but don't need to block this PR.

Yes, would follow-up it in next PR for status code, thanks

**Comment by bzbarsky-apple** [comment]
@yunhanw-google What is this issue actually about?

**Comment by woody-apple** [comment]
Issue Review: @mrjerryjohns to follow up.

**Comment by yunhanw-google** [comment]
not be the issue now.
