### ISSUE TITLE
Followup to make sure this works with the python controller

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#9743]
Because we have these flags in the codebase anyway, we're already de-facto compiling with different flags. They're plumbed through gn normally, but we can compile with ex. different mdns impls etc. But I don't actually think this needs to be Ifdef'd - it seems like you can call StartServer and it will start advertising as a commissioner if that flag is on.

However, I agree with Andrei - it's unclear how you would compile the python controller to enable or disable this functionality.

_Originally posted by @cecille in https://github.com/project-chip/connectedhomeip/pull/9603#discussion_r709551773_

**Comment by sharadb-amazon** [comment]
PR posted: https://github.com/project-chip/connectedhomeip/pull/9757
