### ISSUE TITLE
Global Attribute Cluster Revision needs to be fixed for  Pump Configuration and Control Cluster

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9769]
Spec Snippet : 

<img width="1618" alt="Screen Shot 2021-09-16 at 4 10 45 PM" src="https://user-images.githubusercontent.com/84206864/133696994-b7f6b6fc-7e7e-4357-b6b1-b1aff79d44fd.png">

Value needs to be 3

**Comment by tlykkeberg-grundfos** [comment]
Fixed in #17181
