### ISSUE TITLE
Global Attribute Cluster Revision needs to be fixed for Thermostat Cluster

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9770]
Spec Snippet  : 

<img width="1379" alt="Screen Shot 2021-09-16 at 4 12 41 PM" src="https://user-images.githubusercontent.com/84206864/133697105-4c960c64-27f1-4586-b819-0df1094f1ac6.png">

Value needs to be 5

**Comment by woody-apple** [comment]
SDK Spec Review: This version needs to be updated.

**Comment by woody-apple** [comment]
SDK Spec Review: Given no cert tests are failing here (cert blocker), we believe this is likely resolved.
