### ISSUE TITLE
Global Attribute Cluster Revision needs to be fixed for Media Input Cluster

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9771]
Spec Snippet : 

<img width="1587" alt="Screen Shot 2021-09-16 at 4 14 09 PM" src="https://user-images.githubusercontent.com/84206864/133697204-ad2a54ce-3874-45ab-9a6f-461dbcdcceb9.png">

Value should be 1

**Comment by mrjerryjohns** [comment]
Just did a read in the REPL, and it comes back as 1.
