### ISSUE TITLE
Global Attribute Cluster Revision needs to be fixed for Color Control Cluster

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9772]
Spec snippet : 

<img width="1639" alt="Screen Shot 2021-09-16 at 4 17 28 PM" src="https://user-images.githubusercontent.com/84206864/133697429-09667830-5f3b-427c-9a42-6c5b7ce77aae.png">

Value should be 5

**Comment by turon** [comment]
Color Control cluster must be spec compliant for v1.
Removing tag `v1_triage_split_4`

**Comment by woody-apple** [comment]
SDK Spec Review: Given no cert tests are failing here (cert blocker), we believe this is likely resolved.
