### ISSUE TITLE
Global Attribute Cluster Revision needs to be fixed for Level Control Cluster

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9773]
Spec Snippet : 

<img width="1692" alt="Screen Shot 2021-09-16 at 4 18 32 PM" src="https://user-images.githubusercontent.com/84206864/133697522-3c9cca04-212b-4c6f-8db5-c35dce5e0ad6.png">

Value needs to be 5

**Comment by tcarmelveilleux** [comment]
Trivial fix, will change
