### ISSUE TITLE
Global Attribute Cluster Revision needs to be fixed for Flow Measurement Cluster

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9774]
Spec Snippet : 

<img width="1626" alt="Screen Shot 2021-09-16 at 4 21 14 PM" src="https://user-images.githubusercontent.com/84206864/133697840-071abf6e-2f63-4c1e-a079-5ae8604ee0ce.png">

Value needs to be 3

**Comment by franck-apple** [comment]
Can be closed. Issue is resolved
