### ISSUE TITLE
Need to audit all GetPeerConnectionState consumers

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#9795]
#### Problem
#9269 changed the semantics of `GetPeerConnectionState` so that it always returns null for an insecure session now.  We need to audit all consumers to make sure they are guarded by an `IsSecure()` check or otherwise know the session is a secure one.  And we may need branches added for the `!IsSecure()` case, similar to #9792.

 #### Proposed Solution
Do the audit, list results here and create any fixes that are needed.

@kghost do you have time to do this?

**Comment by kghost** [comment]
I have audit every usage of `GetPeerConnectionState`, all are safe now.

* In ChipDevice, mSecureSession can be guaranteed to be CASE session
* In SecureSessionMgr, most of them are guarded by `IsSecure`. A few are used callbacks only triggered by secure session, I'll refactor this part later
* In MessageCounterManager, all are called on a CASE session.

**Comment by bzbarsky-apple** [comment]
Thank you!
