### ISSUE TITLE
Few attributes were missing in Pump Configuration and Control Cluster in Mac Chip Tool

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#9809]
The below mentioned attributes were present in ZCL but for MAC Chip Tool they are not available to read.

zclread PumpConfigurationAndControl MinConstPressure 12344321 1 0
zclread PumpConfigurationAndControl MaxConstPressure 12344321 1 0
zclread PumpConfigurationAndControl MinCompPressure 12344321 1 0
zclread PumpConfigurationAndControl MaxCompPressure 12344321 1 0
zclread PumpConfigurationAndControl MinConstSpeed 12344321 1 0
zclread PumpConfigurationAndControl MaxConstSpeed 12344321 1 0
zclread PumpConfigurationAndControl MinConstFlow 12344321 1 0
zclread PumpConfigurationAndControl MaxConstFlow 12344321 1 0
zclread PumpConfigurationAndControl MinConstTemp 12344321 1 0
zclread PumpConfigurationAndControl MaxConstTemp 12344321 1 0
zclread PumpConfigurationAndControl PumpStatus 12344321 1 0
zclread PumpConfigurationAndControl Speed 12344321 1 0
zclread PumpConfigurationAndControl LifetimeRunningHours 12344321 1 0
zclread PumpConfigurationAndControl Power 12344321 1 0
zclread PumpConfigurationAndControl LifetimeEnergyConsumed 12344321 1 0
zclread PumpConfigurationAndControl ControlMode 12344321 1 0

Attaching a screenshot of what attributes were currently available for the Mac Chip Tool to read. Other than these attributes others were not present to read. 
<img width="1026" alt="Pumpconfigurationclusterissue" src="https://user-images.githubusercontent.com/34750871/133848314-814716a6-51f7-4d34-833d-d2829d7f5d0b.png">

**Comment by andersbangGF** [comment]
Since this PR [#10551](https://github.com/project-chip/connectedhomeip/pull/10551) we have support for the following PPC attributes in chip-tool:

```
zclread PumpConfigurationAndControl MinConstPressure 12344321 1 0
zclread PumpConfigurationAndControl MaxConstPressure 12344321 1 0
zclread PumpConfigurationAndControl MinCompPressure 12344321 1 0
zclread PumpConfigurationAndControl MaxCompPressure 12344321 1 0
zclread PumpConfigurationAndControl MinConstSpeed 12344321 1 0
zclread PumpConfigurationAndControl MaxConstSpeed 12344321 1 0
zclread PumpConfigurationAndControl MinConstFlow 12344321 1 0
zclread PumpConfigurationAndControl MaxConstFlow 12344321 1 0
zclread PumpConfigurationAndControl MinConstTemp 12344321 1 0
zclread PumpConfigurationAndControl MaxConstTemp 12344321 1 0
zclread PumpConfigurationAndControl PumpStatus 12344321 1 0
zclread PumpConfigurationAndControl Speed 12344321 1 0
zclread PumpConfigurationAndControl LifetimeEnergyConsumed 12344321 1 0
zclread PumpConfigurationAndControl ControlMode 12344321 1 0
```
This is included in the TE7 branch. There is still two attributes missing as those require issue [#8202](https://github.com/project-chip/connectedhomeip/issues/8202) to be solved first:

```
zclread PumpConfigurationAndControl LifetimeRunningHours 12344321 1 0
zclread PumpConfigurationAndControl Power 12344321 1 0
```
We are working on an implementation but it was not ready for the TE7 branch cut. If we succeed with the implementation we might be able to get it cherrypicked for TE7.
