### ISSUE TITLE
Getting Internal Error response on On-Off Cluster with Mac Chip Tool

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#9810]
While testing the On-Off Cluster Testcase - 3.2.3. [TC-OO-2.3] Secondary functionality with server as DUT,  observing that the Mac Chip Tool is giving internal error. Attaching the logs for the test steps which shows internal error. 

Tried with different endpoint-id values just to see if it works with any of them. But all of them threw internal error. 
[consolidated_mac_accessory_TC-OO-2-3.txt](https://github.com/project-chip/connectedhomeip/files/7188297/consolidated_mac_accessory_TC-OO-2-3.txt)

**Comment by jmartinez-silabs** [comment]
Fixed in referenced pr above
