### ISSUE TITLE
TE5 Mac Chip Tool Testing: Playbackstate, Position attributes are not present for testing

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#9817]
While testing the Media Cluster test cases, 

3.8.1. [TC-MC-6.1] Mandatory Media Playback Verification
3.8.2. [TC-MC-6.2] Optional Media Playback Verification
3.8.3. [TC-MC-6.3] Advanced Seek Media Playback Verification
3.8.4. [TC-MC-6.4] Variable Speed Media Playback Verification

Playbackstate and Position attributes are not present to perform few steps
<img width="1031" alt="MediaCluster-1" src="https://user-images.githubusercontent.com/34750871/133905409-ff5e5512-366b-4266-b92d-30a8af136b74.png">
<img width="1054" alt="MediaCluster-2" src="https://user-images.githubusercontent.com/34750871/133905410-0aea4189-d1a1-4e90-9dc8-720da6e7adaa.png">
.

**Comment by lazarkov** [comment]
They are present now.
