### ISSUE TITLE
TE5 Mac Chip Tool Testing: No Write option to MediaInput, AudioOutput, TVChannelList  - When reading it gives 0 entries hence can't complete test case testing

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#9820]
Test Cluster: Media Cluster
TestCases: 3.9.2. [TC-MC-7.2] Rename Output Verification, 3.5.4. [TC-MC-3.11] Rename Input Verification, 3.7.2. [TC-MC-5.2] Change Channel by Number Verification, 3.7.3. [TC-MC-5.3] Skip Channel Verification

The read response for the above two test cases is 0 entries and the change Name/TVChannel or reading Current TV Channel is not going through as there are no entries. I tried to create entries by writing so that I can read and change the name. But there are no write attributes present for these ones. 

So failing these test cases as the steps can't be checked. 

<img width="1046" alt="MediaCluster-namechange" src="https://user-images.githubusercontent.com/34750871/133912944-3e650aff-d504-4c49-a61d-8875cba67070.png">

**Comment by lazarkov** [comment]
@woody-apple all mentioned cluster attributes have only read enabled per spec.

https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/MediaInput.adoc
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/Channel.adoc
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/media/AudioOutput.adoc
