### ISSUE TITLE
Temperature Measurement Cluster - mandatory attribute: MinMeasuredValue is out of range

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9862]
Spec Snapshot : 

<img width="1538" alt="Screen Shot 2021-09-21 at 10 30 36 AM" src="https://user-images.githubusercontent.com/84206864/134219208-d3ecb3fb-5551-4652-b020-d016ad034dc8.png">

The  minMeasuredValue needs to be within the range -27315 to 32766 , but looks like SDK is reporting -32768

Error message : 
[1632245257480] [83521:7173413] CHIP: [TOO] Error: minMeasuredValue is lower than expected. Min value is -27315 but got '-32768'

**Comment by bzbarsky-apple** [comment]
Fixed in https://github.com/project-chip/connectedhomeip/pull/15821
