### ISSUE TITLE
Change DefaultOTAProvider attribute to DefaultOTAProviders (list)

### ISSUE THREAD

**Issue by holbrookt** [project-chip/connectedhomeip#9894]
#### Problem
The `DefaultOTAProvider` attribute is still implemented as a single value, but the spec was changed to make it `DefaultOTAProviders` - a list.

This is dependent on #8895 (I believe this is the last issue left for supporting list attributes)

 #### Proposed Solution
* Change the XML definition to a list
* Confirm that administrators can write and read multiple values

**Comment by carol-apple** [comment]
Fixed by #11336
