### ISSUE TITLE
Pump Configuration and Control Cluster - optional attributes in Pump Dynamic Information Attributes not implemented

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9903]
Spec Snapshot : 
<img width="1307" alt="Screen Shot 2021-09-22 at 4 09 16 PM" src="https://user-images.githubusercontent.com/84206864/134433978-6829cf37-9f12-4d5d-803b-3dc4a82f750d.png">

In the above Pump Dynamic Information Attributes table , only the mandatory attributes seem to be implemented by the SDK , all the optional attributes need to be implemented as well

**Comment by tlykkeberg-grundfos** [comment]
I'm not quite sure here, what is meant by "implemented by the SDK"? Is it because the attributes are available in the all-clusters-app .zap file or some other .zap file?

**Comment by naveenkommareddi** [comment]
We should move this to 1.x since optional attributes are out of scope for 1.0
