### ISSUE TITLE
Need to implement spec message counter semantics

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#9969]
#### Problem
If a message counter is at 0xFFFFFFFF per spec an incoming value of 0 should be allowed, but our implementation does not do that.  This matters for the global encrypted group counters, which are long-lived and could roll over.

 #### Proposed Solution
Implement the spec semantics.

**Comment by turon** [comment]
Agree spec semantics for message counters need to be implemented.
NOTE: The exact semantics referenced in this issue may be out-of-date or significant revisions has since been posted.
Removing tag `v1_triage_split_4`.

**Comment by jepenven-silabs** [comment]
Implemented with #14996 Need to update Unicast part with Issue #15455
